Add hunting API.
microsoftgraph/microsoft-graph-docs pull request #18272
Opened 2022-09-01 13:10 UTC by BenAlfasi

2022-09-01 13:12 UTC, opbld33 commented
Docs Build status updates of commit _[1c01969](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c01969c8cea3fce229df92f5b84395d0765aaf1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-2b72a542)
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-dac3ac1bee7bca67182c91f7e86632a5-2b72a542)
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6aba4e943962a719c4cb8c5902c04bc8-2b72a542)
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-bec908e47b5c3f046296ff4f4481059a-2b72a542)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2b72a542)
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-2b72a542"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 56, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/huntingqueryresults.md'.`````

<a id="dac3ac1bee7bca67182c91f7e86632a5-2b72a542"></a>
### [api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md)
 - **Line 21, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/singlepropertyschema.md'.`````
 - **Line 22, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/huntingrowresult.md'.`````

<a id="6aba4e943962a719c4cb8c5902c04bc8-2b72a542"></a>
### [api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md)
 - **Line 16, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/huntingqueryresults.md'.`````

<a id="bec908e47b5c3f046296ff4f4481059a-2b72a542"></a>
### [api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md)
 - **Line 16, Column 48**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/security-runhuntingquery.md'.`````

<a id="0817dce4456c16725d5333633847d38f-2b72a542"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209011310092928-18272/BuildReport?accessString=ccbabe1659cf21698edc07c225d95798ce5bac668d7eef09cfffedd69000ca6e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 13:30 UTC, opbld31 commented
Docs Build status updates of commit _[fe64d0f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe64d0ffe910b52a9e4d7310455d686d65981258)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4fb5a221)
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="0817dce4456c16725d5333633847d38f-4fb5a221"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209011327118502-18272/BuildReport?accessString=f58ae9b7444e8687e57b04cbf50987c9cc6d91536ad79dd997c4083426b0a873).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-29 08:28 UTC, angelgolfer-ms commented on api-reference/beta/api/security-runhuntingquery.md
> +|query|String|The hunting query in KQL language.|
Line 50:
@BenAlfasi , is this topic the appropriate reference for the KQL syntax that your API uses: https://learn.microsoft.com/en-us/azure/data-explorer/kql-quick-reference
Or this topic in the M365 Defender hunting API conceptual docs:
https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-query-language?view=o365-worldwide
If not, please find the docs for the appropriate syntax. Then please add a second sentence to the description in line 50, with a link to the appropriate KQL docs. A description like:
```
"The hunting query in Kusto Query Language (KQL). For more information on KQL syntax, see [KQL quick reference](/azure/data-explorer/kql-quick-reference).
```

2022-10-08 05:22 UTC, angelgolfer-ms commented on api-reference/beta/api/security-runhuntingquery.md
> +Microsoft 365 Hunting feature is a query-based threat-hunting tool that lets you explore up to 30 days of raw data. You can proactively inspect events in your network to locate threat indicators and
Line 15 and GLOBAL:
@BenAlfasi , this API is advanced hunting which specifies a query in KQL, right? If that's the case, I'd suggest we refer to it as "advanced hunting" to let customers better correlate with how the admin docs describe it.

Can we start line 15 by saying:
"The Microsoft 365 Defender advanced hunting feature is a query-based..."

2022-10-08 05:53 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-huntingrowresult.md
> +  "@odata.type": "microsoft.graph.huntingRowResult"
FYI I added  "openType": true to this JSON definition.
You can find more info here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211782/Set-up-for-API-Doctor-validation?anchor=json-element-descriptions

2022-10-08 05:55 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-huntingrowresult.md
> +    "Timestamp": "2020-08-30T06:38:35.7664356Z",
Lines 29-31:
The JSON representation section is supposed to show the syntax of the type.
Because this is an open type without any properties, we shouldn't include these lines here. For a while, I was under the impression that this type always has these 3 properties (even though they are not defined in the "Properties" section).

FYI I'm going to remove these lines.

2022-10-08 06:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-huntingrowresult.md
> +This class is a Dictionary of string, object.
FYI I added a paragraph to point out this is an open type, and the actual columns of a row result is specified in the project function that's part of the KQL query...

I don't know how I can clarify line 17 - Dan Kershaw lectured us before not to use the terms "class", "object" in REST API docs. Also, "Dictionary" and the comma after "string" are throwing me off. Can you rephrase what you intend this sentence to say please?

2022-10-08 06:22 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-huntingqueryresults.md
> +``` json
Lines 32-59:
The JSON representation section should define the type of the resource.
Instead these lines are giving an example of what a resource of this type can be like.
FYI I updated this section. Hopefully this would get your PR out of API Doctor error jail.

2022-10-08 07:14 UTC, angelgolfer-ms commented on api-reference/beta/api/security-runhuntingquery.md
> +Microsoft 365 Hunting feature is a query-based threat-hunting tool that lets you explore up to 30 days of raw data. You can proactively inspect events in your network to locate threat indicators and
Even though the implicit expectation is customers go verify how KQL works, desirably we can provide a link. 
Is this appropriate (looks easy to understand): https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/

If it's too partial, can you substitute with a more appropriate source of info for KQL?

2022-10-08 07:29 UTC, angelgolfer-ms commented on api-reference/beta/api/security-runhuntingquery.md
> +<!-- {
I added a description for the example request, to make it easier for those unfamiliar with KQL to catch on. Can you take a look please, and make edits where necessary?

2022-10-08 07:37 UTC, opbld31 commented
Learn Build status updates of commit _[958c5c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/958c5c7f699c7810819ee9fb7e036eb4224843a5)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-8e5016e6)
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-8e5016e6"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 19, Column 95**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 69, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080735016106-18272/BuildReport?accessString=78c9a74bed065cbd03c86f9c9a971ae502f13959fc403439c31b61eab5074012).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 07:39 UTC, opbld31 commented
Learn Build status updates of commit _[0209acc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0209accf38a2610e0b977c435a830115df60d509)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-3b982f93)
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-3b982f93"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 19, Column 95**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 69, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080736034717-18272/BuildReport?accessString=9f323c40a2a302f4a134bc0be85a1c3642f3b72b897e15246c70a8b4816e0693).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 07:43 UTC, opbld31 commented
Learn Build status updates of commit _[0209acc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0209accf38a2610e0b977c435a830115df60d509)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-c4a6b1ef)
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-c4a6b1ef"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 19, Column 95**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 69, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080739233487-18272/BuildReport?accessString=2b94b839e15bdb9e004035229a359b05c01aa4f991375576c558effb9e1587ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 09:39 UTC, opbld31 commented
Learn Build status updates of commit _[3ffcb05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ffcb05010a39074dd399de8ba6325a4e2d1b7bf)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-148f4717)
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-148f4717"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 19, Column 95**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 69, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080935549914-18272/BuildReport?accessString=0b2f4f1356f9d5322f530fc24862534a82e8e8c68f0287c1855b7d480cf56b79).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 09:53 UTC, opbld33 commented
Learn Build status updates of commit _[c243559](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c243559b052cd84226e8284af6d8cd1d4554fd60)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-b5106b89)
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-b5106b89"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 19, Column 95**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 69, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080951169059-18272/BuildReport?accessString=89408ca38e638d83d3c2b48a3818197e6822aa0803e9408e03ba5f6b4da33577).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 06:31 UTC, angelgolfer-ms commented on changelog/Microsoft.M365.Defender.json
> +				},
Lines 349-380,
@BenAlfasi , you should create a new changelog record  for these 4 changelist records, even if the API has gone live some time ago. We consider that customers generally don't know about the API unless the docs  are published (because that's the expectation we build for customers, and most other API producer teams try to sync their docs with the API release).
Just in case the terms "changelog records" and "changelist records" are unclear, you can please take a look at the example under #2, in this section of the CDK topic here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelog-generation-process-summary
In that example, there are 2 changelog records. The first changelog record has 2 changelist records. The second changelog record also has 2 changelist records as well. Each changelog record has its own CreateDateTime value. In the case of the changelog record for this PR, the CreateDateTime value will be set to the date that the PR will be published.

2022-10-10 08:12 UTC, angelgolfer-ms commented on api-reference/beta/api/security-runhuntingquery.md
> +Namespace: microsoft.graph
@BenAlfasi , I just realized all these  4 new files are in the security subnamespace.
Can you please update the following:
- The "Namespace:" line at the beginning of each of these 4 topics to specify microsoft.graph.security as the namespace value.
-  Rename the file for this runHuntingQuery as security-security-runhuntinquery.md, and fix links to this topic. the filename pattern for an action or function defined in a subnamespace is like this: {subnamespace name}-{binding_parameter_type}-{function_or_action_name}.md

2022-10-10 08:16 UTC, angelgolfer-ms commented on api-reference/beta/api/security-runhuntingquery.md
> +
Before and after line 21:
FYI I added a couple of links to the admin docs to give more context:
https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide
https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide

2022-10-10 08:21 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Hunting
Line 14921:
@BenAlfasi , can we call this "Advanced hunting" instead of "Hunting"? 
After reading through the admin topics for this feature, I think it would be better to refer to it as such, mapping more closely to the "advanced hunting" as opposed to "guided hunting" in the admin query builder.

2022-10-10 08:48 UTC, angelgolfer-ms commented on api-reference/beta/api/security-runhuntingquery.md
> +
Because this method has a bindingParameter of security.md, you should include  this method in the Methods table of security.
In the interest of time, FYI I just added a row for this method in security.md.
However, after you rename this file to security-security-runhuntingquery.md, please fix the filename in all the links to this file, including in security.md.

2022-10-10 08:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-huntingqueryresults.md
> +
Lines 21-22 and GLOBAL:
Under the "Type" column, can you provide a fully qualified type value?
In general, for any table (like  Properties, Methods, Relationships tables in a resource topic, under the "type" or "return type" column, if the type is defined in a subnamespace, then please provide the fully qualified resource type. 

For example, if the return type of a method is huntingQueryResults, then under the Type column, please specify the value microsoft.graph.security.huntingQueryResults instead of huntingQueryResults.

2022-10-10 09:20 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Run hunting query
@BenAlfasi , I have another question about the location of this set of API being under "Alerts and incidents" and the need to describe how customers can use these APIs together. Please see my question on Teams.

2022-10-10 09:21 UTC, angelgolfer-ms requested changes
HI @BenAlfasi , I made some direct updates to your PR, and added a few comments to the PR for your action as well. I posed a question in Teams for you too.
Can you please take a look?

2022-10-10 21:29 UTC, opbld30 commented
Learn Build status updates of commit _[bcb2a8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bcb2a8f5c4e73b4ea5be3fa102ea2161ea128914)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-d63c8b59)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-d63c8b59"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 19, Column 96**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 21, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 23, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 23, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide`````
 - **Line 71, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210102126515191-18272/BuildReport?accessString=b0944bee61423d8b0062f8dc1007e01eee072e4d750e0b8dd3e996cfc415114c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 21:42 UTC, opbld33 commented
Learn Build status updates of commit _[eb10b5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb10b5c95f7e7f147d67d12b796fe49d46f72e24)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-6a192a428cb54febe828ea29c15c0639-b55ff7fb)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="6a192a428cb54febe828ea29c15c0639-b55ff7fb"></a>
### [api-reference/beta/api/security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-runhuntingquery.md)
 - **Line 19, Column 94**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 21, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 23, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 23, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide`````
 - **Line 71, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210102140074994-18272/BuildReport?accessString=d1586b20a0e08868f8fc79ec8e2bd2c8978b29eb67b80240ead00f5b0c76fb0b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 06:06 UTC, BenAlfasi commented on api-reference/beta/api/security-runhuntingquery.md
> +Namespace: microsoft.graph
done

2022-10-13 06:07 UTC, BenAlfasi commented on api-reference/beta/api/security-runhuntingquery.md
> +
done

2022-10-13 06:08 UTC, BenAlfasi commented on api-reference/beta/api/security-runhuntingquery.md
> +
Ty!

2022-10-13 06:13 UTC, BenAlfasi commented on api-reference/beta/api/security-runhuntingquery.md
> +|query|String|The hunting query in KQL language.|
done

2022-10-13 06:14 UTC, BenAlfasi commented on api-reference/beta/api/security-runhuntingquery.md
> +<!-- {
looks great, thanks!

2022-10-13 06:16 UTC, BenAlfasi commented on api-reference/beta/resources/security-huntingqueryresults.md
> +
done

2022-10-13 06:19 UTC, BenAlfasi commented on api-reference/beta/resources/security-huntingqueryresults.md
> +``` json
ty!

2022-10-13 06:24 UTC, BenAlfasi commented on api-reference/beta/resources/security-huntingrowresult.md
> +This class is a Dictionary of string, object.
rephrased, please let me know if ok :)

2022-10-13 06:25 UTC, BenAlfasi commented on api-reference/beta/toc.yml
> +        - name: Hunting
done

2022-10-13 06:25 UTC, BenAlfasi commented on api-reference/beta/toc.yml
> +          - name: Run hunting query
done

2022-10-13 06:55 UTC, BenAlfasi commented on changelog/Microsoft.M365.Defender.json
> +				},
done

2022-10-13 06:57 UTC, opbld34 commented
Learn Build status updates of commit _[513b740](https://github.com/microsoftgraph/microsoft-graph-docs/commits/513b7404143b5f5dc342758d5912ca5bf8bc5e2c)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-4192e585465b4ed9bea9b3aa88f7ec52-72bbb984)
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="4192e585465b4ed9bea9b3aa88f7ec52-72bbb984"></a>
### [api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md)
 - **Line 19, Column 94**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 21, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 23, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 23, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide`````
 - **Line 63, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210130654366100-18272/BuildReport?accessString=5e6da716905bfe18a0f461ea64ec1e00ff75a928afb587d944936c7a032cb128).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch [...]

2022-10-13 07:34 UTC, opbld31 commented
Learn Build status updates of commit _[a877b31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a877b3164f45d816e58a30e4a1e8fe2d96f4d792)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e28715dd)

<a id="e28715dd"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a877b3164f45d816e58a30e4a1e8fe2d96f4d792 in branch BenAlfasi-HuntingApi of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 812dc336670b6d2084bebe9ccab8104355898034). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210130734137479-18272/BuildReport?accessString=b952f16093f26dcd516f1bd7156891ddf9394d3e69cdcc5c3e3e4d3d2b4c4687).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 07:36 UTC, opbld32 commented
Learn Build status updates of commit _[e25e1d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e25e1d6160e80a9d9d1382395a0554ac0211781a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b7d66820)

<a id="b7d66820"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit e25e1d6160e80a9d9d1382395a0554ac0211781a in branch BenAlfasi-HuntingApi of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 812dc336670b6d2084bebe9ccab8104355898034). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210130736032046-18272/BuildReport?accessString=e6870f8e2701db4098262a2b09c572d2b95923ecc6095367c668c839555578d6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 01:14 UTC, opbld33 commented
Learn Build status updates of commit _[f9ded94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9ded94778cb6113287d6f40ec78f6e04c2301cc)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-4192e585465b4ed9bea9b3aa88f7ec52-fd5d9616)
[api-reference/beta/api/security-alert-addcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-alert-addcomment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-addcomment?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/api/security-incident-addcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-incident-addcomment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-addcomment?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-addcomment?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="4192e585465b4ed9bea9b3aa88f7ec52-fd5d9616"></a>
### [api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md)
 - **Line 19, Column 94**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 21, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 23, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 23, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide`````
 - **Line 63, Column 18**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-deviceprocessevents-table?view=o365-worldwide`````

For more deta [...]

2022-10-14 02:28 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-addcomment.md
> +title: "Add comment to alert"
FYI I'm changing the filename to security-alert-post-comments.md. 
There's an existing filenaming pattern {subnamespace name}-{parententityname}-post-{navigationpropertyname}.md. I suppose we can repurpose that pattern even though comments is a property and not a nav property.

For more info:
filenaming without subnamespace: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming
filenaming taking subnamespace into account: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace?anchor=filenames

2022-10-14 02:30 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-addcomment.md
> +---
FYI I'm changing the filename to security-incident-post-comments.md.
There's an existing filenaming pattern {subnamespace name}-{parententityname}-post-{navigationpropertyname}.md. I suppose we can repurpose that pattern even though comments is a property and not a nav property.

For more info:
filenaming without subnamespace: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming
filenaming taking subnamespace into account: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace?anchor=filenames

2022-10-14 02:31 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-addcomment.md
> +---
You also need to add this operation to the Methods table for the parent entity, incident.
In the interest of time so that we can wrap up this PR in a day, I'll add the method.

2022-10-14 02:40 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-addcomment.md
> +# Add comment to incident
For the TOC title, we should use "Create comment", and for the topic title, "Create comment for incident".

There's this convention over the nuance of using "create" vs "add". Please see this CDK section: [When to use "Create" vs "Add" and "Delete" vs "Remove"](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22)

Again, part of this having some consistent topic title naming is so to let Graph Studio generate topic titles.

In the interest of time again, I'll make these changes. In case I misunderstood, please let me know.

2022-10-14 02:41 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-addcomment.md
> +title: "Add comment to alert"
For the TOC title, we should use "Create comment", and for the topic title, "Create comment for alert".

There's this convention over the nuance of using "create" vs "add". Please see this CDK section: [When to use "Create" vs "Add" and "Delete" vs "Remove"](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22)

Again, part of this having some consistent topic title naming is so to let Graph Studio generate topic titles.

In the interest of time again, I'll make these changes. In case I misunderstood, please let me know.

2022-10-14 03:15 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-addcomment.md
> +Adds a comment to an existing [incident](../resources/security-incident.md) based on the specified alert **id** property.
Line 16:
I think you mean incident id property, not alert id property, is that right?
I am going ahead to make that update. If I got it wrong, please correct it here and in the Methods table of security-incident.md.

2022-10-14 03:28 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-addcomment.md
> +description: "Adds a comment to the end of the alert comments list"
You also need to add this operation to the Methods table for the parent entity in security-alert.md.
In the interest of time so that we can wrap up this PR in a day, I'll add the method.

2022-10-14 03:35 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-addcomment.md
> +|Property|Type|Description|
Is "comment" technically a parameter in the request body?

FYI in the interest of time, I'm going to apply the structure for the "Request body" section and call it a parameter. If you have any input for me, let me know and update the topic accordingly please.

2022-10-14 03:35 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-addcomment.md
> +
Is "comment" technically a parameter in the request body?

FYI in the interest of time, I'm going to apply the structure for the "Request body" section and call it a parameter. If you have any input for me, let me know and update the topic accordingly please.

2022-10-14 03:48 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-addcomment.md
> +
Line 61 and 78-98:
For any new example like this one, you don't need to be concerned about these lines initially. After the topic gets published, there's a tool that runs weekly and that will insert the language-dependent snippets and UI. You should actually not copy any over from other topics or else customers will see incorrect examples snippets for your new operation.
In the interest of time, I'm deleting these lines for you.

2022-10-14 03:48 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-addcomment.md
> +
Line 61 and 78-98:
For any new example like this one, you don't need to be concerned about these lines initially. After the topic gets published, there's a tool that runs weekly and that will insert the language-dependent snippets and UI. You should actually not copy any over from other topics or else customers will see incorrect examples snippets for your new operation.
In the interest of time, I'm deleting these lines for you.

2022-10-14 07:23 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-api-overview.md
> +Advanced hunting is a query-based threat hunting tool that lets you explore up to 30 days of raw data. You can proactively inspect events in your network to locate threat indicators and entities. The
Lines 32-50:
@BenAlfasi , I made some slight edits to this section. After I check in my commit, can you please take a look to make sure this section is still correct?

2022-10-14 07:28 UTC, angelgolfer-ms commented on api-reference/beta/api/security-security-runhuntingquery.md
> +The hunting query in Kusto Query Language (KQL). For more information on KQL syntax, see [KQL quick reference](/azure/data-explorer/kql-quick-reference).
Line 52:
Hm, actually we need to specify the parameter named "query". 
Do you see a problem with that?
In the interest of time, I'll make the update, but if you see a problem, please let me know.

2022-10-14 07:44 UTC, BenAlfasi commented on api-reference/beta/api/security-incident-addcomment.md
> +Adds a comment to an existing [incident](../resources/security-incident.md) based on the specified alert **id** property.
correct

2022-10-14 07:47 UTC, BenAlfasi commented on api-reference/beta/api/security-alert-addcomment.md
> +|Property|Type|Description|
yes, please see the request example

2022-10-14 08:05 UTC, opbld30 commented
Learn Build status updates of commit _[d6b71f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6b71f5585e4be895c01adde8ffd2fc0f51793b3)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-4192e585465b4ed9bea9b3aa88f7ec52-5ee33339)
[api-reference/beta/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="4192e585465b4ed9bea9b3aa88f7ec52-5ee33339"></a>
### [api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md)
 - **Line 17, Column 161**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 19, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 21, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 21, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view param [...]

2022-10-14 08:30 UTC, opbld31 commented
Learn Build status updates of commit _[48ba534](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48ba5348736f82261ba39489f5a66dd1c9508d1e)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-4192e585465b4ed9bea9b3aa88f7ec52-0ac0a230)
[api-reference/beta/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="4192e585465b4ed9bea9b3aa88f7ec52-0ac0a230"></a>
### [api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md)
 - **Line 17, Column 161**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 19, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 21, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 21, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view param [...]

2022-10-14 08:33 UTC, opbld33 commented
Learn Build status updates of commit _[f7f1e88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7f1e88e1c7df858f1db310c961341e299dc8991)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-4192e585465b4ed9bea9b3aa88f7ec52-52cc4938)
[api-reference/beta/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="4192e585465b4ed9bea9b3aa88f7ec52-52cc4938"></a>
### [api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md)
 - **Line 17, Column 161**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 19, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 21, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 21, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view param [...]

2022-10-14 08:44 UTC, opbld32 commented
Learn Build status updates of commit _[f55e1bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f55e1bdeb65bcc520294feaa5eadfd7990b296d5)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) | [Details](#user-content-4192e585465b4ed9bea9b3aa88f7ec52-5dabecfd)
[api-reference/beta/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingqueryresults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingqueryresults.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingqueryresults?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-huntingrowresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-huntingrowresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-huntingrowresult?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/resources/security-singlepropertyschema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/resources/security-singlepropertyschema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-singlepropertyschema?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-beta&branch=pr-en-us-18272) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18272) |

<a id="4192e585465b4ed9bea9b3aa88f7ec52-5dabecfd"></a>
### [api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-HuntingApi/api-reference/beta/api/security-security-runhuntingquery.md)
 - **Line 17, Column 161**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide`````
 - **Line 19, Column 21**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide`````
 - **Line 21, Column 50**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide`````
 - **Line 21, Column 171**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view param [...]

2022-10-14 09:02 UTC, angelgolfer-ms commented
Per chat with @BenAlfasi , he reviewed my comments and requested me to go ahead and publish the PR.

2022-10-14 09:02 UTC, merged