add documentation for new resources/apis for pages API
microsoftgraph/microsoft-graph-docs pull request #18297
Opened 2022-09-06 05:33 UTC by sangle7

2022-09-06 05:36 UTC, opbld31 commented
Docs Build status updates of commit _[b9dd91e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9dd91e0c5e22652acdcfbb98d8ae14c1f45e260)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-getwebpartbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartbyposition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-f91bcd09864f6ea7ec0cccb93557aa96-7b5cb330)
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-bfb30bce12f295b7d1fbbc7848b2edc6-7b5cb330)
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-cddfd4f58de2670efa8d2d8b298858aa-7b5cb330)
[api-reference/beta/api/webparts-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webparts-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/webparts-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-5c27b9907520f6dc9377c9f91523ca8d-7b5cb330)
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-bcf0bfa370c4b47441f9c3d218474de7-7b5cb330)
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-ac8ddb14e302918d4952cdb4e278350a-7b5cb330)
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-82e7bed146a38b6181d2dde10cf1f11c-7b5cb330)
[api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/sitepage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sitepage?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-7d6ee7cf38ef03cc6ba08bd6a6396695-7b5cb330)
[api-reference/beta/resources/webpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/webpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webpart?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-1997378fed7c7332fdea28996f1532d6-7b5cb330)
[api-reference/beta/resources/webpartdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/webpartdata.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webpartdata?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-cc44ddf57684ec52d393971233a6a3da-7b5cb330)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resou [...]

2022-09-06 05:53 UTC, opbld32 commented
Docs Build status updates of commit _[24ce024](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24ce0244d41a987fde4943a856ca71f5c295d085)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/sitepage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sitepage?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-7d6ee7cf38ef03cc6ba08bd6a6396695-b05edb8f)
[api-reference/beta/resources/webpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/webpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webpart?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-1997378fed7c7332fdea28996f1532d6-b05edb8f)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webparts-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webparts-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webparts-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_chec [...]

2022-09-06 06:11 UTC, opbld32 commented
Docs Build status updates of commit _[27958f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27958f9d23eea1b1cc42909144a2875a9f738020)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serverprocessedcontent?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/sitepage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sit [...]

2022-09-06 06:35 UTC, opbld34 commented
Docs Build status updates of commit _[ddbbeb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ddbbeb8312a747a5ea4de1e8975b69fd5a71d331)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serverprocessedcontent?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/sitepage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sit [...]

2022-09-06 06:53 UTC, opbld32 commented
Docs Build status updates of commit _[b89daae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b89daaecc80a1712871a87607b62638a9186b3eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serverprocessedcontent?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/sitepage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sit [...]

2022-09-06 07:10 UTC, opbld30 commented
Docs Build status updates of commit _[4e9c021](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e9c02101a4022bc0eca7a132123bc3ca122809c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serverprocessedcontent?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/sitepage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sit [...]

2022-09-06 07:54 UTC, opbld32 commented
Docs Build status updates of commit _[bc92329](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc923295babaddde5538042a89012e26ac6c8dc3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a0e1c882)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/a [...]

2022-09-06 08:02 UTC, opbld33 commented
Docs Build status updates of commit _[ffa28a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffa28a2b9af7b8a75a503d6be33c2c679c57cab7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-12e85eed)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/a [...]

2022-09-13 08:19 UTC, opbld31 commented
Docs Build status updates of commit _[78015df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78015df3e9f736049366012e2923f7699a167567)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2bb7de37db6a7f2410442770b1b53b1f-e9c1246e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e9c1246e)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded  [...]

2022-09-13 08:25 UTC, opbld31 commented
Docs Build status updates of commit _[ee1ef7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee1ef7b10a6342188e9652d40a13e824a456093c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e7bbdc6f)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/a [...]

2022-09-13 08:49 UTC, opbld33 commented
Docs Build status updates of commit _[72c77ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72c77eee0fe5e8e0d7ce501e07770f35b047e12f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-414dc4ff)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/a [...]

2022-09-13 08:58 UTC, opbld32 commented
Docs Build status updates of commit _[a83dedf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a83dedf1d58fe1967bdbdebfeb88230ea7eb4822)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8daefc3e)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view [...]

2022-09-13 09:15 UTC, opbld34 commented
Docs Build status updates of commit _[82f578c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82f578c51c7097de1261e5182c8f64dadfac2e16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-036e9a95)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view [...]

2022-09-13 09:55 UTC, Yixian15 approved these changes

2022-09-13 10:01 UTC, opbld31 commented
Docs Build status updates of commit _[956426a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/956426a74a1d5fa428923727c70e1219dfb472f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ca962822)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view [...]

2022-09-14 15:19 UTC, opbld31 commented
Docs Build status updates of commit _[eb3aab7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb3aab7ba893437e6d2d73aedfc6a3a731dc5f2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ffa6c9bc)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view [...]

2022-09-15 04:41 UTC, opbld30 commented
Docs Build status updates of commit _[63fec79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63fec799097f88fe66b9d2daa4558f47a042617f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-795e19ff)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view [...]

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/standardwebpart.md
> +## Properties
Do you want to add an extra line before `## Properties`

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/standardwebpart.md
> +|id|String|Instance identifier of the webPart.Inherited from [entity](../resources/entity.md).|
`webPart.Inherited`: add a space

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/textwebpart.md
> +
remove extra line?

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/titlearea.md
> +| layout                  | [titleAreaLayoutType](../resources/titlearea.md#titlearealayouttype-values)        | Enumeration value that indicates the layout of the title area.The possible values are:
`area.The`: add space

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/webpart.md
> +|id|String| Unique instance identifier of the webPart. nherited from [entity](../resources/entity.md).|
`nherited `: typo

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/webpartdata.md
> +|dataVersion|String|Data version of the WebPart. The value is defined by the webPart's developer. Different dataVersion usually refers to different property structure.
Not a valid Markdown table. missing tailing `|`

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/webpartdata.md
> +|properties|[Json](../resources/json.md)|Properties bag of the WebPart.
Not a valid Markdown table. missing tailing `|`

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/webpartposition.md
> +| columnId            | Double  | Indicate the identifier of the column where the WebPart located in.                             |
too may white space at end

2022-09-15 10:13 UTC, liun27 commented on api-reference/beta/resources/webpartposition.md
> +| webPartIndex         | Double  | Index of the current WebPart.Represents the order of webPart in this column or section |
`WebPart.Represents`: add space

2022-09-17 06:40 UTC, opbld30 commented
Docs Build status updates of commit _[03a4943](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03a4943b930ee55dc6891bfac3bff51acf9e7951)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-dc368f44)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reactionsfacet?view [...]

2022-09-21 05:12 UTC, opbld30 commented
Docs Build status updates of commit _[8432d72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8432d72388962ea8184d3f7263104c114ac406f8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 07:44 UTC, opbld33 commented
Docs Build status updates of commit _[f8798aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8798aadd64e42c241aaf356178f5d1c76b69fe5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c3a1b57e)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resource [...]

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/resources/canvaslayout.md
> +Represent the layout of the content in a given SharePoint page
Add ending dot.

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/resources/canvaslayout.md
> +|horizontalSections|[horizontalSection](../resources/horizontalsection.md) collection|Collection of horizontal sections on the SharePoint page |
Tiny: add tailing dot & re-format mark-down table.

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/api/verticalsection-get.md
> +|Permission type      | Permissions (from least to most privileged)              |
Tiny: format this mark down table

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/api/horizontalsectioncolumn-list.md
> +Get a list of the [horizontalSectionColumn](../resources/horizontalsectioncolumn.md) objects and their properties. Sort by 'id' in ascending order.
'id' still not updated?

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/api/horizontalsectioncolumn-list.md
> +|Permission type      | Permissions (from least to most privileged)              |
Tiny: format mark down table

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/api/horizontalsectioncolumn-get.md
> +|Permission type      | Permissions (from least to most privileged)              |
Tiny: format mark down table

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/api/horizontalsection-list.md
> +Get a list of the [horizontalSection](../resources/horizontalsection.md) objects and their properties. Sort by `id` in ascending order.
update 'id'?

2022-09-21 09:14 UTC, liun27 commented on api-reference/beta/api/horizontalsection-get.md
> +|Permission type      | Permissions (from least to most privileged)              |
tiny: format mark down table

2022-09-21 15:04 UTC, opbld32 commented
Docs Build status updates of commit _[88d0e2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88d0e2eb9b41cfd5dcae785732f55822c32ec49f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-217e0128)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resource [...]

2022-09-21 15:34 UTC, liun27 approved these changes

2022-09-26 04:59 UTC, opbld32 commented
Docs Build status updates of commit _[08d6b90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08d6b9009191d7f427806d03227b677b1b68f110)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/reso [...]

2022-09-27 03:20 UTC, opbld32 commented
Docs Build status updates of commit _[0807d1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0807d1cbf1d2ae11b0c9b4281fdda75f008e3861)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/reso [...]

2022-09-28 05:51 UTC, opbld30 commented
Docs Build status updates of commit _[77ee0b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77ee0b7a41557ec8c169cb8cfb1b335f36890467)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/reso [...]

2022-09-29 03:46 UTC, opbld32 commented
Learn Build status updates of commit _[8184cd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8184cd5868c8d355368332bf6e541d1c7aae62dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-09-29 03:58 UTC, opbld31 commented
Learn Build status updates of commit _[4f446d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f446d6fe036e2e661713e4d5644295cef0bdc58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-03 17:27 UTC, isvargasmsft commented on api-reference/beta/resources/horizontalsectioncolumn.md
> +description: Represent a vertical column in a given horizontal section
@sangle7 @liun27 our guidelines indicate to use imperative (represent) for method topics and present tense (represents) for resources. I am making the updates myself in this case for efficiency, but please keep this in mind for future reference.

2022-10-03 17:33 UTC, isvargasmsft commented on api-reference/beta/resources/horizontalsectioncolumn.md
> +
Isn't there a method to list the collection of webparts associated with a horizontalSectionColumn?

2022-10-03 17:41 UTC, isvargasmsft commented on api-reference/beta/resources/titlearea.md
> +| imageAndTitle      | The title area has an image and title layout. |
This member has a different name according to the CSDL:
```suggestion
| cutInShape   | The title area has an image and title layout. |
```

2022-10-03 19:43 UTC, opbld34 commented
Learn Build status updates of commit _[6c60f14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c60f149f110dd0abc95a619d9bc3b05867d15fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-03 19:43 UTC, isvargasmsft commented on api-reference/beta/api/horizontalsection-get.md
> +## Examples
GLOBAL: To all methods where it applies, please add an extra example using the $select query parameter.

2022-10-03 21:01 UTC, opbld32 commented
Learn Build status updates of commit _[db76842](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db7684201d2923a1d4d4342f0fe8707c8bc4b8ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-03 21:01 UTC, isvargasmsft commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
According to the CSDL and this PR, the changes are being introduced to the beta endpoint. 
```suggestion
      "Id": "986cb8be-7e9b-49ad-b541-ad5285531a08",
      "Cloud": "Prod",
      "Version": "beta",
      "CreatedDateTime": "2022-10-02T07:47:36.3210338Z",
      "WorkloadArea": "Teamwork",
      "SubArea": "Microsoft.Teams.Shifts"
```

2022-10-03 21:03 UTC, isvargasmsft commented on changelog/Microsoft.Teams.GraphSvc.json
> +        }
Are these items related to this PR? I am not seeing information about these elements in the CSDL PR nor in this docs PR. Please clarify or remove these changelog entries from this PR to keep the scope clear.

2022-10-03 21:05 UTC, isvargasmsft requested changes
Hello @sangle7, 

Thank you very much for your work in this pull request. 

Please take a look at some comments and suggestions I left. And please clarify if the extra changelog items are related to another PR. 

Feel free to ping me if you have any questions. 

Kind regards, 

Isaac Vargas

2022-10-04 12:05 UTC, sangle7 commented on api-reference/beta/resources/titlearea.md
> +| imageAndTitle      | The title area has an image and title layout. |
Sorry the name has been changed from 'cutInShape' to 'imageAndTitle'. I should update the CSDL file

2022-10-04 12:06 UTC, opbld30 commented
Learn Build status updates of commit _[95d3585](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95d35853c0711aa18c90cd67eaa64b79abd08150)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-04 12:06 UTC, sangle7 commented on changelog/Microsoft.Teams.GraphSvc.json
> +        }
Action taken :) Thanks

2022-10-04 12:10 UTC, opbld33 commented
Learn Build status updates of commit _[3f3a506](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f3a506d6d8562aa094d37e8b910b5ee1aa3dabe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-04 12:11 UTC, sangle7 commented on api-reference/beta/resources/horizontalsectioncolumn.md
> +
Action taken. I also added this action in 'verticalSection.md'

2022-10-04 13:43 UTC, opbld34 commented
Learn Build status updates of commit _[f48f4bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f48f4bc6b0f799cf3021c5215da23e519a597be7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-04 13:43 UTC, isvargasmsft commented on api-reference/beta/resources/titlearea.md
> +| imageAndTitle      | The title area has an image and title layout. |
@sangle7 please update de CSDL PR and let me know once you have done it.

2022-10-04 13:46 UTC, sangle7 commented on api-reference/beta/api/horizontalsection-get.md
> +## Examples
Thanks! I added a few examples with $select and $expand

2022-10-04 13:52 UTC, sangle7 commented on api-reference/beta/resources/titlearea.md
> +| imageAndTitle      | The title area has an image and title layout. |
@isvargasmsft updated, csdl PR: 6707088

2022-10-07 16:20 UTC, opbld31 commented
Learn Build status updates of commit _[1af03a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1af03a7a4e74b72bca45312de762e0043a6bd991)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-07 16:31 UTC, isvargasmsft commented on api-reference/beta/resources/titlearea.md
> +| layout                  | [titleAreaLayoutType](../resources/titlearea.md#titlearealayouttype-values)               | Enumeration value that indicates the layout of the title area. The possible val
```suggestion
| layout                  | [titleAreaLayoutType](../resources/titlearea.md#titlearealayouttype-values)               | Enumeration value that indicates the layout of the title area. The possible values are: `imageAndTitle`, `plain`, `colorBlock`, `overlap`, `unknownFutureValue`. |
```

2022-10-07 16:33 UTC, isvargasmsft approved these changes

2022-10-07 16:34 UTC, opbld30 commented
Learn Build status updates of commit _[8876ced](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8876cedfed62c9215b2a0e5b11833146fe114ece)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-14 15:14 UTC, isvargasmsft commented
Hello @sangle7, 

Please remember to add the label "ready to merge" when the schema changes in this PR are ready for external customers to use.

2022-10-25 03:41 UTC, opbld31 commented
Learn Build status updates of commit _[c18d3fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c18d3fb7d534494547bfe0745b7ccfeffd6333b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-10-28 05:40 UTC, opbld34 commented
Learn Build status updates of commit _[55d24e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55d24e56a9daa74c3dddbcfc8ece217dab436026)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-11-01 08:54 UTC, opbld33 commented
Learn Build status updates of commit _[b3662ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3662cae43ec737279b0a54acf4bc1973e32b470)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-11-21 03:34 UTC, opbld30 commented
Learn Build status updates of commit _[0ab3825](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ab3825b9d39dfc315ba5424226df3514723bc03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-12-02 02:48 UTC, opbld33 commented
Learn Build status updates of commit _[31423fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31423fd3bf6bbc93bca3106cdaeb1e7f0dd23b90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-12-03 03:27 UTC, Lauragra commented on api-reference/beta/api/sitepage-getwebpartsbyposition.md
> +title: 'Get webparts by position'
The title and H1 here should be "sitepage: getWebPartsByPosition".

2022-12-03 03:29 UTC, Lauragra commented on api-reference/beta/api/webpart-getposition.md
> +# Get webpart position
The title and H1 should be "webPart: getPosition".

2022-12-03 03:30 UTC, Lauragra commented on api-reference/beta/api/webpart-list.md
> +Get the webPart resources from a sitePage. Sort by the order in which they appear on the page.
Please add links to the webPart and sitePage resources here.

2022-12-03 03:30 UTC, opbld30 commented
Learn Build status updates of commit _[f306454](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f30645408ceab9896ba1eb81191967b893819b09)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-5a20b314)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:33 UTC, Lauragra commented on api-reference/beta/resources/metadatakeystringpair.md
> +| value    | String | Value of the metadata. Should be a string. |
Minor point but, do we have to say here that it should be a string, when we provide string as the type in the type column?

2022-12-03 03:33 UTC, opbld33 commented
Learn Build status updates of commit _[34b9f6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34b9f6ac66a5906a3cce5155158882553217ef16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-632ee3f8)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:35 UTC, opbld30 commented
Learn Build status updates of commit _[cbcbc8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbcbc8b2b45873e415b0153c2e026ab6a72c8ec5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-5580cf05)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:38 UTC, opbld32 commented
Learn Build status updates of commit _[b51c865](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b51c86585829c250593194e69e6e94ae79f2a3c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-6094bfca)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:41 UTC, opbld34 commented
Learn Build status updates of commit _[7fb0322](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fb032292f424bf1e9ec57ead9d73b6dbdba18f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-5edfbf0a)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:44 UTC, opbld31 commented
Learn Build status updates of commit _[f160abf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f160abf171421ecf25a730cf71915bfbaaaf8b3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-2ab5e90a)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:47 UTC, opbld34 commented
Learn Build status updates of commit _[961d6cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/961d6cd7340157dc50ec6a11287c26073f67744a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-43a52bf9)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:49 UTC, opbld34 commented
Learn Build status updates of commit _[a1465c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1465c5f9648f322250c33282dcbc5edc6df8d5e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-7dbd7954)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:52 UTC, opbld30 commented
Learn Build status updates of commit _[d3dbcc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3dbcc86555418e03a2321ee6e161cebdf52bc9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-ceda58b2)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:54 UTC, opbld34 commented
Learn Build status updates of commit _[8375f92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8375f92166587bfdbdf60cc1760a4f5b2007c418)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-887e0fbb)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:57 UTC, opbld32 commented
Learn Build status updates of commit _[473855e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/473855e2e217831bc03a5726a9120c8080c92678)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-90aa31e5)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 03:57 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [json](https://learn.microsoft.com/en-us/graph/api/resources/json?view=graph-rest-beta) resource type.",
This resource topic already exists in the repo; I think it's misleading to include it in the changelog. We should remove this entry.

2022-12-03 03:58 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Removed the **webPart** resource type.",
The webPart resource type was updated, but not removed. What is the intent for this entry?

2022-12-03 03:59 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [canvasLayout](https://learn.microsoft.com/en-us/graph/api/resources/canvasLayout?view=graph-rest-beta) resource",
Global: Please make sure that all descriptions end with periods.

2022-12-03 03:59 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Removed the `contentType` property from the [sitePage](https://learn.microsoft.com/en-us/graph/api/resources/sitePage?view=graph-rest-beta) resource.",
Global: Please use bold formatting instead of inline code for property names.

2022-12-03 03:59 UTC, opbld32 commented
Learn Build status updates of commit _[28c8141](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28c81410dadc170fecdf45f81b1c60b0170040df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-d5e3e4bf)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-03 04:01 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [webPart](https://learn.microsoft.com/en-us/graph/api/resources/webPart?view=graph-rest-beta) resource",
Here we say we added webPart again? I think that both of these need to be removed.

2022-12-03 04:02 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +      "WorkloadArea": "Files",
The correct WorkloadArea value for this entry would be "Sites and lists".

2022-12-03 04:02 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +      "ChangeList": [
Please make sure that your ChangeList record includes entries for the new methods that were added as well.

2022-12-05 03:19 UTC, sangle7 commented on api-reference/beta/api/webpart-list.md
> +Get the webPart resources from a sitePage. Sort by the order in which they appear on the page.
action taken

2022-12-05 03:49 UTC, opbld31 commented
Learn Build status updates of commit _[f8f2242](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8f2242072a7fa9d3d57daa5c50d30917fd23641)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) | [Details](#user-content-2b19e54677ba3e73fa43813aa80a4405-96b5b3f4)
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https [...]

2022-12-05 03:55 UTC, opbld33 commented
Learn Build status updates of commit _[ae2047e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae2047e6051f259113bfbba06555b098b2b8b2dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-12-06 00:21 UTC, opbld32 commented
Learn Build status updates of commit _[bb05175](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb0517529f8af1347a5cf24c7e552efb5037d0b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-12-06 00:24 UTC, opbld34 commented
Learn Build status updates of commit _[49a981a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49a981aa57e23a5020a2a00d62baa69009d7a4ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/horizontalsectioncolumn-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsectioncolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsectioncolumn-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsectioncolumn-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/horizontalsection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/horizontalsection-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/horizontalsection-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-getwebpartsbyposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-getwebpartsbyposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-getwebpartsbyposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/sitepage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/sitepage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/sitepage-update?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/verticalsection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/verticalsection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-get?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-getposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-getposition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-getposition?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/api/webpart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/api/webpart-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/canvaslayout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/canvaslayout.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/canvaslayout?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsection?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/horizontalsectioncolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/horizontalsectioncolumn.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/horizontalsectioncolumn?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeystringpair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeystringpair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeystringpair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/metadatakeyvaluepair.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/metadatakeyvaluepair.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/metadatakeyvaluepair?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/reactionsfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/reactionsfacet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/reactionsfacet?view=graph-rest-beta&branch=pr-en-us-18297) (graph-rest-beta) |
[api-reference/beta/resources/serverprocessedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/hanbingwang/introduce-pages-API/api-reference/beta/resources/serverprocessedcontent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/res [...]

2022-12-06 00:48 UTC, merged