Spadimis/permissions reference
microsoftgraph/microsoft-graph-docs pull request #18311
Opened 2022-09-06 16:22 UTC by Sureshpadimi88

2022-09-06 16:27 UTC, opbld34 commented
Docs Build status updates of commit _[a46b15b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a46b15be5a0bb80567880831fcff550941d438eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-b148a653)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-18311) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimis/permissions-reference/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [ [...]

2022-09-07 14:52 UTC, cristobal-buenrostro requested changes
@Sureshpadimi88 , please remove all the files from **api-reference** folder.
the only file needed in this PR is **concepts/permissions-reference.**

2022-09-07 14:52 UTC, cristobal-buenrostro commented on concepts/permissions-reference.md
> +| _EduRoster.ReadBasic.All_            | Read a limited subset of the organization's roster. | Allows the app to read a limited subset of both the structure of schools and classes in an organization'
something is wrong, it seems like you reverted the changes. 
Please check and update accordingly.

2022-09-07 18:10 UTC, Sureshpadimi88 commented on concepts/permissions-reference.md
> +| _EduRoster.ReadBasic.All_            | Read a limited subset of the organization's roster. | Allows the app to read a limited subset of both the structure of schools and classes in an organization'
151465 
update with these new descriptions

Image

2022-09-08 15:33 UTC, opbld31 commented
Docs Build status updates of commit _[5b7dd81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b7dd811c74c6eaa771789201955079bed9e8c68)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7a64ad06)

<a id="7a64ad06"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 5b7dd811c74c6eaa771789201955079bed9e8c68 in branch spadimis/permissions-reference of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 8d8b862c00b04c218107dde07ec1cf2640ff9e29). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081533163583-18311/BuildReport?accessString=4ebf5c9d7a47714c7a9ee0647ae3978a3ff4a3a4f8777d167657cd38afe12261).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 15:34 UTC, Sureshpadimi88 commented on concepts/permissions-reference.md
> +| _EduRoster.ReadBasic.All_            | Read a limited subset of the organization's roster. | Allows the app to read a limited subset of both the structure of schools and classes in an organization'
it's done.

2022-09-09 15:58 UTC, closed without merging