CA templates beta public preview
microsoftgraph/microsoft-graph-docs pull request #18315
Opened 2022-09-06 21:27 UTC by xuchen1122

Public preview for CA templates beta API.

2022-09-06 21:30 UTC, opbld31 commented
Docs Build status updates of commit _[7610431](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7610431b2af25db0b147d931f9619d8a283d3c63)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-e09688ac97029f669846eb612b28fc2f-78610493)
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-cc6f9e7338a7dca1377123d3e477e6f5-78610493)
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-742f9eceea9f8ad531d0abe5c5140a3e-78610493)
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="e09688ac97029f669846eb612b28fc2f-78610493"></a>
### [api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'conditionalAccess'.`````

<a id="cc6f9e7338a7dca1377123d3e477e6f5-78610493"></a>
### [api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'conditionalAccess'.`````

<a id="742f9eceea9f8ad531d0abe5c5140a3e-78610493"></a>
### [api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-post-templates.md'.`````
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccesstemplate-update.md'.`````
 - **Line 28, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-delete-templates.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209062127484914-18315/BuildReport?accessString=56da3093e24e124acd897fbff6b8e66ce1815bcff90b1bff0cfd475767f96ee8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 22:38 UTC, opbld33 commented
Docs Build status updates of commit _[e16b20c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e16b20c2d2a0fd0fc9f09bdc2a583912242946fa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-e09688ac97029f669846eb612b28fc2f-1b7f52d7)
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-cc6f9e7338a7dca1377123d3e477e6f5-1b7f52d7)
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-742f9eceea9f8ad531d0abe5c5140a3e-1b7f52d7)
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="e09688ac97029f669846eb612b28fc2f-1b7f52d7"></a>
### [api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'conditionalAccess'.`````

<a id="cc6f9e7338a7dca1377123d3e477e6f5-1b7f52d7"></a>
### [api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'conditionalAccess'.`````

<a id="742f9eceea9f8ad531d0abe5c5140a3e-1b7f52d7"></a>
### [api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209062236309686-18315/BuildReport?accessString=2951c1d0fa4370c0bbe531a6de727bc02cea1aa9d25be9a7719755d72b0bddfd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 01:10 UTC, opbld31 commented
Docs Build status updates of commit _[39c7fa6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39c7fa64e28788655dcd965d20f27a4d7bd44d01)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-718d0ff1)

<a id="718d0ff1"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209070107532363-18315/BuildReport?accessString=0ba182a45afcdd920c2b037faa0095437c2f9199a55c99e49a02504c70c4dfbf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 01:13 UTC, opbld30 commented
Docs Build status updates of commit _[b86d2e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b86d2e695881f1bd119a52b12c96408265f307cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-e09688ac97029f669846eb612b28fc2f-3943f369)
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-cc6f9e7338a7dca1377123d3e477e6f5-3943f369)
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="e09688ac97029f669846eb612b28fc2f-3943f369"></a>
### [api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'conditionalAccess'.`````

<a id="cc6f9e7338a7dca1377123d3e477e6f5-3943f369"></a>
### [api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'conditionalAccess'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209070109413108-18315/BuildReport?accessString=466463568a312ee80b2b7885a216d97e5acfa94d26608ea7ee8331de07615359).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 02:03 UTC, opbld30 commented
Docs Build status updates of commit _[522f0c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/522f0c692879005c4a3f01398b5764d0fdbff6f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209070201494997-18315/BuildReport?accessString=1d63b76fc55db9c6c911360d8263eee7a8913c1cd8eea36acf5f8d07accb394d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 10:41 UTC, opbld31 commented
Docs Build status updates of commit _[4bd6fd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4bd6fd267aced5e7fffe7c5af70a32fd1fc0137b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209071037464290-18315/BuildReport?accessString=98cd9b3dfb85047ec8238b237d4f9d0a377437ceb55a78555a34ee3e3c792a68).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 10:43 UTC, opbld34 commented
Docs Build status updates of commit _[3bd7011](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bd7011372daf0d219ce96ec370eb756044b567c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209071038252691-18315/BuildReport?accessString=c736b481dcf9c039e60ca81fecb903bde167799e4c6e62748f799e7616a51416).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-05 16:52 UTC, FaithOmbongi requested changes
Thank you, @xuchen1122 for your excellent work on this PR. I've left suggestions for fixes inline plus these:
- Add the new relationship to conditionalaccessroot.md
- Surface this new set of APIs in the TOC at api-reference/beta/toc.yml
- GLOBAL: To help us maintain a single point of contact for all customer issue, please put the PM's GitHub alias as "author".
- For the LIST and GET operations, I'd like to propose enhancing the examples. This is an encounraged practice going forward.
    - For List - Add an Example 2 that uses both $select and $filter to match a template type. $select will allow you to only show specific properties of the payload.
    - For Get - Add an Example 2 for using $select

When you add an example 2, the levels of the titles changes to this flow

```md
## Examples
### Example 1: {Add title e.g. "List all conditional access policy templates"}
#### Request
#### Response
### Example 2: {Title}
#### Request
#### Response
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +description: "Represents a Microsoft recommended template for Azure Active Directory conditional access policy."
Suggestion
```suggestion
description: "Represents a Microsoft recommended template of best practice configurations for Azure Active Directory conditional access policies."
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +Represents a Microsoft recommended template for Azure Active Directory conditional access policies.
```suggestion
Represents a Microsoft recommended template of best practice configurations for Azure Active Directory [conditional access policies](../resources/conditionalaccesspolicy.md).
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|description|String| The human-readable name of the template. |
Did you mean user-friendly instead?
```suggestion
|description|String| The user-friendly name of the template. |
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|id|String| Immutable id of a template, this value will be represented as GUID. Inherited from [entity](../resources/entity.md). |
Looks like a GUID, but not a GUID
```suggestion
|id|String| Immutable ID of a template. Inherited from [entity](../resources/entity.md). |
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|scenarios|templateScenarios| List of scenarios a template is recommended for. The following are valid scenarios `new`, `secureFoundation`, `zeroTrust`, `remoteWork`, `protectAdmins`, `emergingThreat
Add the sentinel enum member as well so customer know it's evolvable enum
Indicate it's a multi-valued enum
Indicate supported query parameters
```suggestion
|name|String| The user-friendly name of the template. |
|scenarios|templateScenarios| List of conditional access scenarios that the template is recommended for. The possible values are: `new`, `secureFoundation`, `zeroTrust`, `remoteWork`, `protectAdmins`, `emergingThreats`, `unknownFutureValue`. This is a multi-valued enum. Supports `$filter` (`eq`).|
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesspolicydetail.md
> +description: "Represents details of a Microsoft recommended template for Azure Active Directory conditional access policy."
```suggestion
description: "Represents the configuration of a Microsoft recommended best-practice template for an Azure Active Directory conditional access policy."
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesspolicydetail.md
> +Represents details of Conditional Access policy templates.
```suggestion
Represents the configuration of the **details** property of a Microsoft recommended best-practice [template](../resources/conditionalaccesspolicytemplate.md) for an Azure Active Directory [conditional access policy](../resources/conditionalaccesspolicy.md).
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesspolicydetail.md
> +|grantControls|[conditionalAccessGrantControls](../resources/conditionalaccessgrantcontrols.md)| Represents grant controls that must be fulfilled to pass the policy. |
```suggestion
|grantControls|[conditionalAccessGrantControls](../resources/conditionalaccessgrantcontrols.md)| Represents grant controls that must be fulfilled for the policy. |
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/conditionalaccessroot-list-templates.md
> +title: "List templates"
OK to tweak this to closely match the functionality.
```suggestion
title: "List conditionalAccessTemplates"
```

2022-10-05 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/conditionalaccesstemplate-get.md
> +GET https://graph.microsoft.com/beta/identity/conditionalAccess/templates/{conditionalAccessTemplateId}
Replace placeholder {id} with real ID
```suggestion
GET https://graph.microsoft.com/beta/identity/conditionalAccess/templates/c7503427-338e-4c5e-902d-abe252abfb43
```

2022-10-05 16:52 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +				},
Not part of your PR

2022-10-05 16:52 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"Description": "Added the [templateScenarios](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource",
tooling bug
```suggestion
					"Description": "Added the **templateScenarios** enumeration.",
```

2022-10-05 16:52 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"Description": "Added the [conditionalAccessPolicyDetail](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessPolicyDetail?view=graph-rest-beta) resource",
```suggestion
					"Description": "Added the [conditionalAccessPolicyDetail](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessPolicyDetail?view=graph-rest-beta) resource.",
```

2022-10-05 16:52 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"Description": "Added the [templates](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessRoot?view=graph-rest-beta) resource",
tooling bug
```suggestion
					"ApiChange": "Relationship",
					"ChangedApiName": "templates",
					"ChangeType": "Addition",
					"Description": "Added the **templates** relationship to the [conditionalAccessRoot](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessRoot?view=graph-rest-beta) resource.",
```

2022-10-05 18:21 UTC, xuchen1122 commented on api-reference/beta/resources/enums.md
> +|Member             |Value|
the second line has been removed

2022-10-05 18:22 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +description: "Represents a Microsoft recommended template for Azure Active Directory conditional access policy."
updated the description as suggested

2022-10-05 18:23 UTC, opbld33 commented
Learn Build status updates of commit _[e2db698](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2db698bcde91ed6c3620352e561fc0173cac53f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-b69ff58c635e6e7aeb8c762e10ecd181-276374a6)
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="b69ff58c635e6e7aeb8c762e10ecd181-276374a6"></a>
### [api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md)
 - **Line 16, Column 99**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/conditionalaccesspolicytemplate.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051820227582-18315/BuildReport?accessString=2bd09e642aef95d342a8aa0295e2109d123660da10d823f8e16b927dec3b7e32).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 18:24 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +Represents a Microsoft recommended template for Azure Active Directory conditional access policies.
updated

2022-10-05 18:24 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|description|String| The human-readable name of the template. |
updated

2022-10-05 18:25 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|id|String| Immutable id of a template, this value will be represented as GUID. Inherited from [entity](../resources/entity.md). |
updated

2022-10-05 18:36 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|scenarios|templateScenarios| List of scenarios a template is recommended for. The following are valid scenarios `new`, `secureFoundation`, `zeroTrust`, `remoteWork`, `protectAdmins`, `emergingThreat
updated the description as suggested.

One question here, in additional to `eq`, it should support all other filter type as well, such as `has`. Do I need to include others? If so can you share with me example?

2022-10-05 18:36 UTC, opbld33 commented
Learn Build status updates of commit _[64a09a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64a09a67c81345b22c5736d6245a6eff00817bab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051833353359-18315/BuildReport?accessString=e7d518ca6bb1331d96c4ecefafd1cffefbb50337e59df720b333a7cd3a938449).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 18:36 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesspolicydetail.md
> +description: "Represents details of a Microsoft recommended template for Azure Active Directory conditional access policy."
fixed

2022-10-05 18:37 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesspolicydetail.md
> +|grantControls|[conditionalAccessGrantControls](../resources/conditionalaccessgrantcontrols.md)| Represents grant controls that must be fulfilled to pass the policy. |
fixed

2022-10-05 18:37 UTC, xuchen1122 commented on api-reference/beta/api/conditionalaccessroot-list-templates.md
> +title: "List templates"
fixed

2022-10-05 18:37 UTC, xuchen1122 commented on api-reference/beta/api/conditionalaccesstemplate-get.md
> +GET https://graph.microsoft.com/beta/identity/conditionalAccess/templates/{conditionalAccessTemplateId}
fixed

2022-10-05 18:38 UTC, xuchen1122 commented on changelog/Microsoft.IdentityProtectionServices.json
> +				},
this was auto-generated by the tool. Yes it is not a part of PR and I removed it.

2022-10-05 18:39 UTC, xuchen1122 commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"Description": "Added the [templateScenarios](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource",
fixed

2022-10-05 18:39 UTC, xuchen1122 commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"Description": "Added the [conditionalAccessPolicyDetail](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessPolicyDetail?view=graph-rest-beta) resource",
fixed

2022-10-05 18:40 UTC, xuchen1122 commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"Description": "Added the [templates](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessRoot?view=graph-rest-beta) resource",
fixed

2022-10-05 18:43 UTC, opbld30 commented
Learn Build status updates of commit _[f04ef90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f04ef900d83ef281c5dce144b4e576c7fd3762a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051841118110-18315/BuildReport?accessString=b4932e5409ad125bf118da67928934097623a65f4a9eae3ad1cec9f91b616e25).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 19:14 UTC, FaithOmbongi commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|scenarios|templateScenarios| List of scenarios a template is recommended for. The following are valid scenarios `new`, `secureFoundation`, `zeroTrust`, `remoteWork`, `protectAdmins`, `emergingThreat
Yeah, please do; (`eq`, `has`) will do.

I suggest that you include that as part of your Example 2 in the LIST doc. This is the first set of APIs in Azure AD that uses the "has" operator and it will be great to show that in an example. Something like `...?$select=id,scenarios,details&$filter=scenarios has 'remoteWork'`

I'll also raise a separate PR to update the [$filter guidance](https://learn.microsoft.com/en-us/graph/filter-query-parameter#operators-and-functions-supported-in-filter-expressions) guidance this operator.

2022-10-05 19:26 UTC, opbld31 commented
Learn Build status updates of commit _[b0e212a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0e212ae11e4966a5f153cdf4a18ca447c2b6470)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051924070741-18315/BuildReport?accessString=886d67fbb4970d7292743cee31d72415824a8dc3483e2d336614eaeb41fc8cd3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 20:12 UTC, opbld30 commented
Learn Build status updates of commit _[6e27461](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e274617c5fbc0d99bcacab6cec957ec842f1260)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-e09688ac97029f669846eb612b28fc2f-f3428f78)
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-cc6f9e7338a7dca1377123d3e477e6f5-f3428f78)
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-742f9eceea9f8ad531d0abe5c5140a3e-f3428f78)
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="e09688ac97029f669846eb612b28fc2f-f3428f78"></a>
### [api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'lhuangnorth' is not a valid GitHub ID.`````

<a id="cc6f9e7338a7dca1377123d3e477e6f5-f3428f78"></a>
### [api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'lhuangnorth' is not a valid GitHub ID.`````

<a id="742f9eceea9f8ad531d0abe5c5140a3e-f3428f78"></a>
### [api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'lhuangnorth' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052010081501-18315/BuildReport?accessString=f78b45d8d26f02bdac7bb915c017241e49b6d17baef6caa90d1aa5f8b19503d8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 20:16 UTC, opbld33 commented
Learn Build status updates of commit _[d05eeaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d05eeaa5e53e8608d87b05e39a128b9e21779a08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-e09688ac97029f669846eb612b28fc2f-410d7d5a)
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-cc6f9e7338a7dca1377123d3e477e6f5-410d7d5a)
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) | [Details](#user-content-742f9eceea9f8ad531d0abe5c5140a3e-410d7d5a)
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="e09688ac97029f669846eb612b28fc2f-410d7d5a"></a>
### [api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'lhuangnorth' is not a valid GitHub ID.`````

<a id="cc6f9e7338a7dca1377123d3e477e6f5-410d7d5a"></a>
### [api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'lhuangnorth' is not a valid GitHub ID.`````

<a id="742f9eceea9f8ad531d0abe5c5140a3e-410d7d5a"></a>
### [api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'lhuangnorth' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052013335320-18315/BuildReport?accessString=87da3c902d3fd8b395dc7222d4a9a72afe5b4266a02bb89f44b1e116b32a3476).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 20:27 UTC, opbld32 commented
Learn Build status updates of commit _[b7ad0bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7ad0bc070cfa7fa81cc7f54f70dceba41e36abb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052025307960-18315/BuildReport?accessString=6a33991e671c8a0a31d33c5a23a04290e71e083db4b75e93c9bee43b31b8ed72).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 20:30 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesstemplate.md
> +|scenarios|templateScenarios| List of scenarios a template is recommended for. The following are valid scenarios `new`, `secureFoundation`, `zeroTrust`, `remoteWork`, `protectAdmins`, `emergingThreat
added!

2022-10-05 20:31 UTC, xuchen1122 commented on api-reference/beta/resources/conditionalaccesspolicydetail.md
> +Represents details of Conditional Access policy templates.
fixed!

2022-10-05 20:32 UTC, xuchen1122 commented
> Thank you, @xuchen1122 for your excellent work on this PR. I've left suggestions for fixes inline plus these:
> 
> * Add the new relationship to conditionalaccessroot.md
> * Surface this new set of APIs in the TOC at api-reference/beta/toc.yml
> * GLOBAL: To help us maintain a single point of contact for all customer issue, please put the PM's GitHub alias as "author".
> * For the LIST and GET operations, I'd like to propose enhancing the examples. This is an encounraged practice going forward.
>   
>   * For List - Add an Example 2 that uses both $select and $filter to match a template type. $select will allow you to only show specific properties of the payload.
>   * For Get - Add an Example 2 for using $select
> 
> When you add an example 2, the levels of the titles changes to this flow
> 
> ```lisp
> ## Examples
> ### Example 1: {Add title e.g. "List all conditional access policy templates"}
> #### Request
> #### Response
> ### Example 2: {Title}
> #### Request
> #### Response
> ```

All of these are now included in this PR.

2022-10-05 20:47 UTC, opbld31 commented
Learn Build status updates of commit _[aab5645](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aab5645a440e657ee16f12eadc60f910e98a4a80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052045057190-18315/BuildReport?accessString=cc578bbd97982f7cf1ff593669f1c309f144012a3f23253386f4b2e38ce76599).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 21:29 UTC, opbld33 commented
Learn Build status updates of commit _[3a57a60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a57a6042c6d1dd58ef43cfdd938c7a8e1adfb61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052127165782-18315/BuildReport?accessString=fd500090968af0edda49b3b44d7b219e0c743c9a8e944ceb043932244e740541).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 21:34 UTC, opbld30 commented
Learn Build status updates of commit _[e4937a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4937a9989145381a21a578c4134e4455bca962f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052131553033-18315/BuildReport?accessString=489681871ce05cdeca299a6889a30cbb63d9cbc4e05e485fc07ad860678a814b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 08:31 UTC, opbld31 commented
Learn Build status updates of commit _[31a1dab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31a1daba36e001d17b31e70f1b8f58b96a536505)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210060829238798-18315/BuildReport?accessString=e056746f47993dfef43b785e04f8fc0a78ca143b3e3b1c2efdc97b4cbdceed4d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 08:33 UTC, FaithOmbongi approved these changes
Thank you, @xuchen1122 for your work in this PR. Approved.

One note: _lisaychuang_ has not completed the process to set up as an internal contributor (I actually thought the PM was David Spooner). Please ask _lisaychuang_ to complete that process (same process you followed of joining orgs and linking accounts) otherwise your PR may not get merged because the feature owner is unknown. Please reach out internally for any questions.

2022-10-06 08:55 UTC, opbld31 commented
Learn Build status updates of commit _[b0528ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0528aeff21c7b66283e8a7b12568a8cd687cd4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210060844143443-18315/BuildReport?accessString=2218c7c46e2239b3b91eee703aefcb7cfc3115c55d9bd5943737145e7c5d6b7b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 03:35 UTC, opbld34 commented
Learn Build status updates of commit _[5bcc11f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bcc11f77f79d5ba5d51852e260992433f43e012)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210070332457510-18315/BuildReport?accessString=c5fd5a413e03dd84f60b0c799b743908615d521c26881b4654e13fd041e0ae76).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 03:42 UTC, opbld33 commented
Learn Build status updates of commit _[f7830d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7830d63997b820e91eda329ba8fb8d627527180)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccessroot-list-templates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccessroot-list-templates.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesstemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/api/conditionalaccesstemplate-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesstemplate-get?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesspolicydetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesspolicydetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicydetail?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccesstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/conditionalaccesstemplate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccesstemplate?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-templates?view=graph-rest-beta&branch=pr-en-us-18315) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ca-templates-api-beta-public-preview/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210070340200200-18315/BuildReport?accessString=c3dde123311be0fa3be83651fcd048b2a3cb00649744e88834e209e01e210a03).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 03:56 UTC, merged