[Cloud PC] Ass Supported Region region group parameter
microsoftgraph/microsoft-graph-docs pull request #18359
Opened 2022-09-08 05:08 UTC by Meadow201317

2022-09-08 05:10 UTC, opbld30 commented
Docs Build status updates of commit _[85bfc0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85bfc0ecb5d2094622c9b9e80b9f06def475b4fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) | [Details](#user-content-374ec5137a77d8312f16138d57ff780b-63c7010f)
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |

<a id="374ec5137a77d8312f16138d57ff780b-63c7010f"></a>
### [api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md)
 - **Line 26, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 32, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '.'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080508238816-18359/BuildReport?accessString=cd73e070c7a79a782533b88c6df96306ac2a65df5115fd497e355661f3122591).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 05:19 UTC, opbld34 commented
Docs Build status updates of commit _[850429b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/850429b18f715472435217c8fe19e066dad1688f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) | [Details](#user-content-374ec5137a77d8312f16138d57ff780b-9c005ccc)
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |

<a id="374ec5137a77d8312f16138d57ff780b-9c005ccc"></a>
### [api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md)
 - **Line 26, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 32, Column 14**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcRegionGroup-values' in 'beta/resources/cloudpcsupportedregion.md', did you mean '#cloudpcregiongroup-values'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080517304571-18359/BuildReport?accessString=eb72cbc436f1a846be280ee67a3d13fa72b9e968473900407f7264da04c034e5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 01:58 UTC, opbld32 commented
Docs Build status updates of commit _[806d66c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/806d66c9392d64ea060098ea717ff5f8ed9568a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150153565193-18359/BuildReport?accessString=20c556ebb618aa4ec8d9cb59de8d25766400b712a75ee20a5d755aa96f39e33b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 02:03 UTC, opbld34 commented
Docs Build status updates of commit _[e91a3b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e91a3b120984c73c395765a6740dc2a66bf1bd81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150159433538-18359/BuildReport?accessString=1c80c03a5e269bb109419e24558c6d8a3a24f35326de5e3457ff3fc0bd5cf15a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 03:23 UTC, AshleyYangSZ commented
@Meadow201317 Could you please help add the change log?
And update the PR title, since it contains two graph changes, 1 is regionGroup, 2 is adding rpaBox enum member to supportedSolution.

2022-09-15 04:12 UTC, Meadow201317 commented
> @Meadow201317 Could you please help add the change log? And update the PR title, since it contains two graph changes, 1 is regionGroup, 2 is adding rpaBox enum member to supportedSolution.

Updated, thx!

2022-09-15 04:15 UTC, opbld34 commented
Docs Build status updates of commit _[44891f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44891f62f77a1dad212464bc386fdae79193bac7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150412027739-18359/BuildReport?accessString=0db770035fccb089363fa57b15dad19ede3a4df953f040d4123455083409b8c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 03:53 UTC, opbld33 commented
Docs Build status updates of commit _[1bbc3b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bbc3b0e2b33e18094a062c7bac8fd60def2bd77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209260351026486-18359/BuildReport?accessString=cac0e049c1890eb0829fb5d8f2b3581b20fee7c4d3a2c212620714b43def58e3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 03:36 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionGroup|[cloudpcRegionGroup](#cloudpcregiongroup-values)|The logic geographic group this region belongs to. Multiple regions could belong to one region group. Customer could select a regionGroup
Please update:
[cloudpcRegionGroup] => [cloudPcRegionGroup]
a CloudPC => a Cloud PC
the CloudPC => the Cloud PC

2022-09-27 03:38 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +        {
As for the changelog, please also add this one: 

{
          "Id": "dd8cc504-3861-450c-add5-763a11dd0266",
          "ApiChange": "Property",
          "ChangedApiName": "regionGroup",
          "ChangeType": "Addition",
          "Description": "Added the `regionGroup` property to the [cloudPcDomainJoinConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcDomainJoinConfiguration?view=graph-rest-beta) resource.",
          "Target": "cloudPcDomainJoinConfiguration"
        },

2022-09-27 03:40 UTC, RuiHou105 requested changes
@Meadow201317 
1.Please resolve comments in this PR.
2.Please create a roadmap workitem and attach the workitem number in comment. This is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/).

2022-10-08 08:37 UTC, Meadow201317 commented
Here is the workitem: [Feature 15373](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15373): [DEVICES AND APPS][CLOUD PC] Add regionGroup to cloudPcSupportedRegion

2022-10-08 08:42 UTC, opbld32 commented
Learn Build status updates of commit _[640ed67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/640ed67bc98c4af0f554bfe2e99122f5202f3131)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080838234117-18359/BuildReport?accessString=7b6ac15d25063005683cfaea52ca9004765ba398bbe35136a2dcad2e9db2f853).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-09 00:28 UTC, opbld31 commented
Learn Build status updates of commit _[9ab8354](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ab8354fd3d2a656da9eecdeea894e8b4506347b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210090026418399-18359/BuildReport?accessString=94d486e2cc7d73032f1ddaac761ba8c384e9885479fa5dcff26223397caeda58).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 00:51 UTC, AshleyYangSZ approved these changes

2022-10-20 08:25 UTC, opbld33 commented
Learn Build status updates of commit _[25e241c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25e241cd652f3e5a53c43495ff6d6fcb2f531a08)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d7b25476)

<a id="d7b25476"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 25e241cd652f3e5a53c43495ff6d6fcb2f531a08 in branch bizhao/supportedRegion_group of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit bd57a4d1a48499dbb8ebdf98fa401d6c595354d3). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210200824454743-18359/BuildReport?accessString=de2bf67786f97abd197b0595c1e172cdf26246a3dd69f70a4d2321beeeeaee8f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 08:45 UTC, opbld31 commented
Learn Build status updates of commit _[34a95bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34a95bb07d156619ae32415a8a77cef9919f42f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210200842435913-18359/BuildReport?accessString=61fa4bf47ad79390536e1c9627bca86d38f086a86e3b371a7d08fe922460adcd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 08:54 UTC, Meadow201317 commented
> @Meadow201317 1.Please resolve comments in this PR. 2.Please create a roadmap workitem and attach the workitem number in comment. This is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/).

Have resolved comments and the workitem has been attached

2022-11-01 07:40 UTC, AshleyYangSZ requested changes

2022-11-01 07:40 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionGroup|[cloudPcRegionGroup](#cloudpcregiongroup-values)|The logic geographic group this region belongs to. Multiple regions could belong to one region group. Customer could select a regionGroup
![image](https://user-images.githubusercontent.com/72924235/199183135-446134f1-443a-4cf2-aed6-fff293ac76db.png)
There're some format issue caused this grid shows incorrectly. Please help update.

2022-12-08 07:31 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionGroup|[cloudPcRegionGroup](#cloudpcregiongroup-values)|The logic geographic group this region belongs to. Multiple regions could belong to one region group. Customer could select a regionGroup
Fixed the format, thx!

2022-12-08 07:32 UTC, opbld34 commented
Learn Build status updates of commit _[7400889](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74008894f660a112a8f99691f2309d50bec56ff3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212080729370727-18359/BuildReport?accessString=3a46c5a8d34912f06b4a3cb9c83e30561c3c3f32a4c101fa4a68472c1b076371).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 02:34 UTC, opbld34 commented
Learn Build status updates of commit _[c71063f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c71063f6afb5969cf23e7c106f5baf15956a11f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-18359) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_group/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212090232019041-18359/BuildReport?accessString=6dc179717caf9386509942bb0f2c013acf566b5f9cd7e0e0f5a402a3dd173212).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-14 07:08 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the regionGroup property to the cloudPcDomainJoinConfiguration resource.",
1. Add to `cloudPcSupportedRegion`, not `cloudPcDomainJoinConfiguration `. 
2. Add please add the link of `cloudPcSupportedRegion `here. You can refer to other examples.

2022-12-14 07:41 UTC, Meadow201317 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the regionGroup property to the cloudPcDomainJoinConfiguration resource.",
Updated, thx!

2022-12-15 02:41 UTC, RuiHou105 approved these changes

2022-12-19 21:04 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| europeUnion        | The region belongs to the region group: European Union.                            |
According to the api.md file, the correct member name for europeUnion is europe. On the other hand, the live schema contains europeUnion. Is the CSDL/api.md file outdated? Please, verify the name of this member and update the value if needed.

2022-12-19 21:04 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| uae                | The region belongs to the region group: UAE.                                       |
According to the CSDL file, uae is a hidden value. Hidden values shouldn't be documented. Please, remove this enum member (uae) from this table.

2022-12-19 21:04 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| southAmerica       | The region belongs to the region group: South America.                             |
According to the CSDL file, the value "euap" should come after "southAmerica". Please, document the missing enum member.

2022-12-19 21:04 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| norway             | The region belongs to the region group: Norway.                                    |
The CSDL file doesn't contain any entry for the enum members "norway", "switzerland", and "southKorea". However, I see that they are already part of the live schema. Is the CSDL outdated?

2022-12-19 21:04 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionGroup|[cloudPcRegionGroup](#cloudpcregiongroup-values)|The geographic group this region belongs to. Multiple regions can belong to one region group. For example, the Europe region group contai
"The Cloud PC will be put under one of the regions under the group based on resource status." Unfortunately, I don't understand this sentence. It this sentence connected to the previous sentence "A customer can select..." What do you mean by resource status - the status of the resource group in Azure? Please, rephrase this sentence to provide more clarity.

2023-01-03 04:43 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| europeUnion        | The region belongs to the region group: European Union.                            |
We have update the CSDL file to EuropeUnion.

2023-01-03 04:59 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| uae                | The region belongs to the region group: UAE.                                       |
Got it, thx!

2023-01-03 05:02 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| southAmerica       | The region belongs to the region group: South America.                             |
Sorry for missing it.

2023-01-03 05:03 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +| norway             | The region belongs to the region group: Norway.                                    |
Here is the latest CSDL file ref: [Pull Request 11933](https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11933): [Cloud PC] Add Norway, Switzerland, SouthKorea and Qatar in CloudPcRegionGroup

2023-01-03 05:09 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionGroup|[cloudPcRegionGroup](#cloudpcregiongroup-values)|The geographic group this region belongs to. Multiple regions can belong to one region group. For example, the Europe region group contai
Thanks for your comment. The sentence "The Cloud PC will be put under one of the regions under the group based on resource status." is connected to the "A customer can select..." which means a customer need to choose a region group but finally where the cloudPC is placed is determined by the region's resource capacity. If customer choose region group X, region A and region B belong to region group X and region A has more quota than region B, we will put the cloud PC in region A.

2023-01-03 23:53 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionGroup|[cloudPcRegionGroup](#cloudpcregiongroup-values)|The geographic group this region belongs to. Multiple regions can belong to one region group. For example, the Europe region group contai
Thanks for the clarification :)

2023-01-04 00:15 UTC, JarbasHorst commented
@Lauragra this PR is ready for a final review.

2023-01-05 03:15 UTC, Lauragra approved these changes

2023-01-05 03:37 UTC, merged