Adding documentation for ELM questions v1
microsoftgraph/microsoft-graph-docs pull request #18356
Opened 2022-09-08 02:15 UTC by saylee-dharne-msft

2022-09-08 02:18 UTC, opbld32 commented
Docs Build status updates of commit _[555065d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/555065d81243b8780e8da63cc7a36ff3eb6ddba6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-bdc3ba90456917902cd62dca535fdd57-9268f0f9)
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-726efc7dd69e80c70a1d5b50acbd89a3-9268f0f9)
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-0658c02ebfa9af2b5cd6ac8596116ea6-9268f0f9)
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |

<a id="bdc3ba90456917902cd62dca535fdd57-9268f0f9"></a>
### [api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md)
 - **Line 14, Column 258**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageresourceattribute.md'.`````

<a id="726efc7dd69e80c70a1d5b50acbd89a3-9268f0f9"></a>
### [api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md)
 - **Line 14, Column 194**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageresourceattribute.md'.`````

<a id="0658c02ebfa9af2b5cd6ac8596116ea6-9268f0f9"></a>
### [api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md)
 - **Line 14, Column 215**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageresourceattribute.md'.`````
 - **Line 22, Column 38**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 38**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080215497454-18356/BuildReport?accessString=0d87d1017d1b7d67baa974ec5a0fc71fc0c037124b70ef8336e6550b0542f3ef).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not [...]

2022-09-08 16:29 UTC, opbld31 commented
Docs Build status updates of commit _[cfed1ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfed1abc4cd2e53fc5f4c6ce68889b1a86e5bfd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-0658c02ebfa9af2b5cd6ac8596116ea6-c63dc71b)
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |

<a id="0658c02ebfa9af2b5cd6ac8596116ea6-c63dc71b"></a>
### [api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md)
 - **Line 22, Column 38**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 38**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081625592932-18356/BuildReport?accessString=00cdc0f27661a526e7bc95e363670571f846da89cd8708b8b1270def395084e5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 16:38 UTC, opbld31 commented
Docs Build status updates of commit _[20c999f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20c999f04a1524a05f5333fb06c177132d6389f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-0658c02ebfa9af2b5cd6ac8596116ea6-ba940f12)
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |

<a id="0658c02ebfa9af2b5cd6ac8596116ea6-ba940f12"></a>
### [api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md)
 - **Line 22, Column 38**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 38**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081627118354-18356/BuildReport?accessString=b101ab9c955af5066b0939207e61e027b0d612a919d7dad0f45bf519d11d804e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 16:40 UTC, opbld31 commented
Docs Build status updates of commit _[4bd7e87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4bd7e8758dc3ccedcd1185b5263b217d1c190b8e)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-0658c02ebfa9af2b5cd6ac8596116ea6-47c5fe1e)
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |

<a id="0658c02ebfa9af2b5cd6ac8596116ea6-47c5fe1e"></a>
### [api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md)
 - **Line 22, Column 38**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/dotnet/standard/base-types/regular-expression-language-quick-reference' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081638087115-18356/BuildReport?accessString=c2e08281a286d6abde6866a1969fe367aa33ed47195ab59ecea3a0220ec845ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 16:44 UTC, opbld31 commented
Docs Build status updates of commit _[b7dd900](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7dd900e43fd5cec0e84f079368c3e8d2ce6c95e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081642161380-18356/BuildReport?accessString=b3f7403211fac6386007ce07701d7e5efd70f8e5a1a75682d20964fd6cd43cf3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 16:57 UTC, opbld31 commented
Docs Build status updates of commit _[a2ebb4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2ebb4b568f57c1c6ff54240973203e9c1a1dcbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081654246856-18356/BuildReport?accessString=09d683ba3a0504cbba72d9ae8d32539e73873608c43851707246a89ec9663370).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 17:03 UTC, opbld31 commented
Docs Build status updates of commit _[da587b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da587b619dfd3a38ffddf84823e4889e84a9d378)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081701258869-18356/BuildReport?accessString=d17bf2a6acceefb414d7e9dd55a2791e119dc41a6712916df225af149ed664ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 18:46 UTC, markwahl-msft approved these changes
Thanks, added some suggestions for text formatting.

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageanswer.md
> +|answeredQuestion|[accessPackageQuestion](../resources/accesspackagequestion.md)|The question the answer is for. Required and Read-only.|
Not critical, but for a data type within the assignmentRequest, the reader might not know what 'required and read-only' means.  E.g., it's the customer's app that creates a assignmentrequest and so they supply the answeredRequest in their POST payload.

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageanswer.md
> +|displayValue|String|The localized display values shown to the requestor and approvers. |
The description has values (plural) but the property name is value (singular).

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageanswerchoice.md
> +|actualValue|String|	The value stored on the requestor's user profile, if this answer is configured to be stored as a specific attribute. |
is storing on an attribute part of this PR or a later PR?

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageanswerchoice.md
> +|localizations|Collection([accessPackageLocalizedText](../resources/accesspackagelocalizedtext.md))|The text of the answer choice represented in a format for a specific locale.|
should this be Collection(X) or X collection ? Normally I see the latter style.

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageanswerstring.md
> +|displayValue|String|The localized display values shown to the requestor and approvers. Inherited from [accessPackageAnswer](../resources/accesspackageanswer.md).|
(see comments on these properties on other resources above in the PR.)

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageassignmentrequest.md
> +  "answers": [
I noticed this PR doesn't have an update to the API for creating a request that illustrates supplying an answer. Do you want to include that example in this PR or in a subsequent PR?

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md
> +|localizations|Collection([accessPackageLocalizedText](../resources/accesspackagelocalizedtext.md))|The text of the question represented in a format for a specific locale. Inherited from [accessPacka
See earlier comment in this PR on Collection(X)

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackagequestion.md
> +|sequence|Int32| Relative position of this question when displaying a list of questions to the requestor.|
What is the smallest possible value? 0? can you have -1 as a sequence?

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackagequestion.md
> +|isAnswerEditable|Boolean| Specifies whether the requestor is allowed to edit answers to questions.|
could you mention which API call the requestor would use to edit answers to questions?

2022-09-14 18:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackagequestion.md
> +|localizations|Collection([accessPackageLocalizedText](../resources/accesspackagelocalizedtext.md))|The text of the question represented in a format for a specific locale.|
see earlier comment on collection syntax.

2022-09-16 22:11 UTC, opbld32 commented
Docs Build status updates of commit _[174a76b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/174a76bbc05f9eff32e8f8eb5dfdada8a27f1d6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209162208391462-18356/BuildReport?accessString=19734b12fac68317b7d5a1285f7faf232dbb36a7e3886f26392e647edae589c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 22:13 UTC, opbld31 commented
Docs Build status updates of commit _[9a3f95f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a3f95f483ea45695cc6dd157de5885494208075)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209162209268589-18356/BuildReport?accessString=a58f4f18233c9d9b3fcb6d025fd70343ea2d9856d99c2ffae91d6c90c3594190).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 22:48 UTC, saylee-dharne-msft commented on api-reference/v1.0/resources/accesspackageanswerchoice.md
> +|actualValue|String|	The value stored on the requestor's user profile, if this answer is configured to be stored as a specific attribute. |
Resource attributes is a separate PR. Here, I mean to say that this value is the machine-readable value that is stored in the directory. If there's a better way to phrase this, please let me know!

2022-09-23 00:08 UTC, saylee-dharne-msft commented on api-reference/v1.0/resources/accesspackageassignmentrequest.md
> +  "answers": [
I will add it in a subsequent PR

2022-09-23 00:09 UTC, saylee-dharne-msft commented on api-reference/v1.0/resources/accesspackagequestion.md
> +|sequence|Int32| Relative position of this question when displaying a list of questions to the requestor.|
Looking at the functionality, technically you could without getting any errors since we use this for a relative order.

2022-09-23 00:10 UTC, opbld34 commented
Docs Build status updates of commit _[114cf8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/114cf8a3908907f0a9cadddd44662ce862eebb2a)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-726efc7dd69e80c70a1d5b50acbd89a3-3db2dd08)
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

<a id="726efc7dd69e80c70a1d5b50acbd89a3-3db2dd08"></a>
### [api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md)
 - **Line 19, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209230007441986-18356/BuildReport?accessString=00167d520ef2ef751f537a3952b6cfe4ba1910e5083756e1f46a163c59589400).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 20:04 UTC, opbld33 commented
Docs Build status updates of commit _[573d70d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/573d70d0052ab9685c8abc042053a0c0b9d127aa)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-726efc7dd69e80c70a1d5b50acbd89a3-289034e3)
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

<a id="726efc7dd69e80c70a1d5b50acbd89a3-289034e3"></a>
### [api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md)
 - **Line 19, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209232001137616-18356/BuildReport?accessString=22f1a0b6b9415298939439f517fa4fb810e4aef767a51067ca2a8ac4b303ef6f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-29 11:57 UTC, FaithOmbongi requested changes
Thank you for your work on this PR. I've left comments for a few minor fixes inline plus:

- GLOBAL: All properties in the resource docs should be ordered alphabetically for easier scanning
- I second Mark's comment: please add an example indicating the request and response. It would be good to have it in this PR for side-by-side reference.
- For the sake of directing all customer issues to a single POC, please put down Mark's GitHub alias in the owner metadata.

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageassignmentpolicy.md
> +      "@odata.type": "microsoft.graph.accessPackageMultipleChoiceQuestion"
It's technically accessPackageQuestion, even though it's an abstract type; then there are two downstream types: textInput and multipleChoice
```suggestion
      "@odata.type": "microsoft.graph.accessPackageQuestion"
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageassignmentrequest.md
> +  "answers": [
I recommend adding the example in this PR to get it done.

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md
> +      "@odata.type": "microsoft.graph.accessPackageMultipleChoiceQuestion"
Same as in the policy
```suggestion
      "@odata.type": "microsoft.graph.accessPackageQuestion"
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagequestion.md
> +description: "The complex type for questions configured on an access package assignment policy."
```suggestion
description: "Represents the questions configured on an access package assignment policy."
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagequestion.md
> +author: "saylee-dharne-msft"
I recommend you maintain Mark's GitHub alias - to direct all customer issues to one POC.

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagequestion.md
> +|isAnswerEditable|Boolean| Specifies whether the requestor is allowed to edit answers to questions [by posting an update to accessPackageAssignmentRequest](../api/entitlementmanagement-post-assignmen
```suggestion
|isAnswerEditable|Boolean| Specifies whether the requestor is allowed to edit answers to questions [by posting an update to accessPackageAssignmentRequest](../api/entitlementmanagement-post-assignmentrequests.md). |
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagelocalizedtext.md
> +description: "A complex type used to represent a string in a specific language."
```suggestion
description: "Represents a question in a specific language."
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagelocalizedtext.md
> +|languageCode|String|The language code that `text` is in. For example, "en-us". The language component follows 2-letter codes as defined in [ISO 639-1](https://www.iso.org/iso-639-language-codes.html
```suggestion
|languageCode|String|The language code that **text** is in. For example, "en-us". The language component follows 2-letter codes as defined in [ISO 639-1](https://www.iso.org/iso-639-language-codes.html), and the country component follows 2-letter codes as defined in [ISO 3166-1 alpha-2](https://www.iso.org/iso-3166-country-codes.html). Required. |
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagelocalizedtext.md
> +|text|String|The text in the specific language. Required. |
```suggestion
|text|String|The question in the specific language. Required. |
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagelocalizedtext.md
> +A complex type used to represent a string in a specific language.
```suggestion
Represents a question in a specific language.
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md
> +description: "Subclass of accessPackageQuestion that has multiple choice as the question's answer format"
```suggestion
description: "Subclass of accessPackageQuestion that has multiple choices as the question's answer format."
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageanswerchoice.md
> +|actualValue|String|	The value stored on the requestor's user profile, if this answer is configured to be stored as a specific attribute. |
Hmm, Is this capability shown anywhere? I haven't seen this relationship with the /users indicated in the docs. Maybe I missed it.

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackagetextinputquestion.md
> +|localizations|Collection([accessPackageLocalizedText](../resources/accesspackagelocalizedtext.md))|The text of the question represented in a format for a specific locale. Inherited from [accessPacka
```suggestion
|localizations|[accessPackageLocalizedText](../resources/accesspackagelocalizedtext.md) collection|The text of the question represented in a format for a specific locale. Inherited from [accessPackageQuestion](../resources/accesspackagequestion.md).|
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageanswer.md
> +description:  "The complex type for answers to an accessPackageQuestion that are stored on an accessPackageAssignmentRequest."
```suggestion
description:  "Represents answers to an accessPackageQuestion that are stored on an accessPackageAssignmentRequest."
```

2022-09-29 11:57 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageanswer.md
> +The complex type of a requestor's provided answer to an [accessPackageQuestion](../resources/accesspackagequestion.md). The actual answer will be a subtype of this complex type, either [accessPackage
```suggestion
Represents the answer a requestor provides to an [accessPackageQuestion](../resources/accesspackagequestion.md). The actual answer will be a subtype of this complex type, either [accessPackageAnswerString](../resources/accesspackageanswerstring.md) or [accessPackageAnswerChoice](../resources/accesspackageanswerchoice.md). These answers will be stored on an [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) object.
```

2022-09-29 20:08 UTC, opbld33 commented
Learn Build status updates of commit _[c23ab4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c23ab4e9cb9b295a11be21a02bc62a8f4c70eaee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209292005363626-18356/BuildReport?accessString=517edad6f2de7f62454f5235185a4f03a5ad5f797bec1ea7b969ec870a932833).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 20:10 UTC, opbld34 commented
Learn Build status updates of commit _[af6e107](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af6e107990e143e5f33a638f3a82ed96b8962d75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209292006328422-18356/BuildReport?accessString=4ee7d186a62b9443627ecdcddf23f400c17792d40873013316d02b8dd261d062).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 20:12 UTC, opbld30 commented
Learn Build status updates of commit _[236f83a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/236f83ae1cd29014390ac3a9331dc1eefc379d4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209292008516791-18356/BuildReport?accessString=b840bd8c445e312339cf41d61b40952962bdddb035821d0515a261e988e922d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 20:44 UTC, saylee-dharne-msft commented on api-reference/v1.0/resources/accesspackageanswerchoice.md
> +|actualValue|String|	The value stored on the requestor's user profile, if this answer is configured to be stored as a specific attribute. |
Hi Faith, good question. I mean to say that it's the value stored in the directory for that user when they answer the question. It allows the answer to the question provided to Entitlement Management to be stored on the user profile (attributes like their country or city or employee id). This value is the application friendly answer value for the question. This is a particularly important for feature called [accessPackageResourceAttribute](https://learn.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta)  which is still preparing to be introduced in v1, but is in beta and our UI.

Since this value does not necessarily have to be connected to user attributes I can reword accordingly to the following description from the beta documentation.

"The actual value of the selected choice. This is typically a string value which is understandable by applications. Required."

2022-09-30 16:43 UTC, opbld30 commented
Learn Build status updates of commit _[64700de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64700deecbc89de92bf4f55eb24b5b8a3c5466f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209301640574984-18356/BuildReport?accessString=2d7876b2fb0db2cf318f9b08bce388799833d3d24dc492d0c13ebdc42a68b454).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 16:45 UTC, opbld34 commented
Learn Build status updates of commit _[ad70462](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad70462834b741e245ec5f37ad2c28f9ed1d0414)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209301642287882-18356/BuildReport?accessString=f347adb4399cd5566819877a22edf6cec72e0be15f5b5b8a2f6eafc299d5e402).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 16:48 UTC, opbld33 commented
Learn Build status updates of commit _[2200849](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2200849f802bdadfed42e9090af247d46703594a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209301643591856-18356/BuildReport?accessString=7ec08dfcf4aaf6201cb93b300cff2e5b2eec8af850f6969db4fd08e53e6e1781).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 17:04 UTC, opbld33 commented
Learn Build status updates of commit _[b8d4e69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8d4e6942c15989eae71e47481c9fe7a5083dad3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209301701504994-18356/BuildReport?accessString=4561b94af976d0ff647ddc715cf6e3fdd02a6d23fc8e76baf9ac71bf47fac4d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 20:39 UTC, opbld32 commented
Learn Build status updates of commit _[5711a82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5711a82406806adca3ab92a619d4e4c9c229ab88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209302037444859-18356/BuildReport?accessString=244072b1e69e24b231e6edaa9a12186ed7984064d489d8f5811109a87bd7af3d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 20:43 UTC, saylee-dharne-msft commented on api-reference/v1.0/resources/accesspackageassignmentrequest.md
> +  "answers": [
Added some example API requests.

2022-09-30 20:43 UTC, opbld33 commented
Learn Build status updates of commit _[3acd8d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3acd8d5b5de557682f8a849a5c523f16c9270f22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209302041156701-18356/BuildReport?accessString=4702cd8ff3fc631cf83a7b20d84c73a29ce8fdd20c705a410b27e1157f861195).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 21:14 UTC, opbld30 commented
Learn Build status updates of commit _[6a4f010](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a4f01029ebfd7d3f5776a4d492750b2a2900bca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) | [Details](#user-content-77ab45f4523d660aee5c12cfb1e93ae3-fb8d7b1a)
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

<a id="77ab45f4523d660aee5c12cfb1e93ae3-fb8d7b1a"></a>
### [api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md)
 - **Line 311, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````
 - **Line 311, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209302112246354-18356/BuildReport?accessString=c877ec78c0fc51dd0015ec076416b94c75abb1a2129829e9af97481b97eb04ac).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a hr [...]

2022-10-03 22:56 UTC, opbld32 commented
Learn Build status updates of commit _[72c75b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72c75b51ca5c2f51cd612661f321e2676481fff8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210032253468672-18356/BuildReport?accessString=8581f2c5b1802b573523e906a425ec6a82f67ba7a76cd743f7eee7c13a4fbcf3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 22:58 UTC, opbld32 commented
Learn Build status updates of commit _[5a6c891](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a6c8910573f63e9ed3e8fc84f40fb876e1e93dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210032254094398-18356/BuildReport?accessString=60ed404d0687dcbb915b9a30d5d7e3936a1da4e1434e4eaa6cb3c268c6993d28).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 23:36 UTC, opbld30 commented
Learn Build status updates of commit _[e8aecfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8aecfa7c3c90ab443a03a83079b60e978751d0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210032334241538-18356/BuildReport?accessString=9e24ba172d98354d73ac57eb0f71c92cda64840a64ffa4ce7e722838c70fad55).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 23:49 UTC, opbld33 commented
Learn Build status updates of commit _[42c51a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42c51a8e88b35a54ceb1bf2b35cd7f6db035b636)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210032347256094-18356/BuildReport?accessString=c3b647e526e2b538b82a65afd05a3cedab445741586ac4428fdcc65dbed34c2a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 01:04 UTC, opbld33 commented
Learn Build status updates of commit _[a0bf872](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0bf872b0584a2b333fac61bd095f9814369a251)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040101436725-18356/BuildReport?accessString=d610edf9994eefb6c0130b7049958499c1390492fbc2d95bfa53f4714816c780).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 01:13 UTC, opbld32 commented
Learn Build status updates of commit _[cd93dfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd93dfe10e01daf606851afe97a1cba43dc09dd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040110552634-18356/BuildReport?accessString=63e032f95a47b21b50195e495006a094ee26f7ceb496c657aa8c1ed6abf97fb2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 01:21 UTC, opbld31 commented
Learn Build status updates of commit _[7c9031e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c9031e9f54c99c4af35643853f706b73b16d8fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040118221234-18356/BuildReport?accessString=1c355f2a5b2fa0d4a7b99f4515625e48e853ef712db9a9d7ade097465dd6e6a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 01:28 UTC, opbld33 commented
Learn Build status updates of commit _[a8dd7a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8dd7a0eef5a279b588ffa9a234d528b645beea6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040126299171-18356/BuildReport?accessString=7479743538323d80cd5ca88dd12a223e0dafa69909ee7649c915faf411df4498).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 01:36 UTC, opbld31 commented
Learn Build status updates of commit _[b3ba324](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3ba324ff3307a9fb9b12510b2aeb97ef347e679)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040134083766-18356/BuildReport?accessString=4ad78a6ffad5d273dc39d4ab706d5a63f7a8926d27911fb7c78c02118586493a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 01:56 UTC, opbld33 commented
Learn Build status updates of commit _[91ce7ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91ce7ca7c22254a4871277857637aa3b2764dfa2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040154294531-18356/BuildReport?accessString=fa07f843a995fe7bc8f1efa1041b4e1506acb16f33d2b2a984cc7a9f01d81348).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 02:46 UTC, opbld34 commented
Learn Build status updates of commit _[c015b36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c015b365a567d530afb21533337e2762a3be9b91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040244250205-18356/BuildReport?accessString=d033e6cfc55dd2830a534ab9585eee59d61907885ebcc9c1df64a81d77234a6e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 18:15 UTC, FaithOmbongi approved these changes
Hi @saylee-dharne-msft - Approved.

I'm unable to pinpoint why your examples are triggering the [API doctor error](https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=97432&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=25484). LMK reach out to the API Doctor team internally to see if they can help. Once that issue is resolved, replace the **do not merge** label with the **ready to merge**.

2022-10-05 20:44 UTC, opbld32 commented
Learn Build status updates of commit _[d098265](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d09826562c2450f391e4362a84f3738cbf2e6909)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/api-reference/v1.0/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-1.0&branch=pr-en-us-18356) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sadharne-elmqav1/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052041362126-18356/BuildReport?accessString=adb5c5e1bb30ff6ac2027ce15f70bbeca031d4373c429ded9539b1b34f530ddb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-02-04 02:50 UTC, merged