Move isEnabled and isSchedulingEnabled  proeprties from Workflow to WorkflowBase
microsoftgraph/microsoft-graph-docs pull request #18388
Opened 2022-09-09 15:17 UTC by vibatra

Move isEnabled and isSchedulingEnabled  proeprties from Workflow to WorkflowBase. This will make these properties available with WorkflowVersions as well

2022-09-09 15:50 UTC, opbld31 commented
Docs Build status updates of commit _[6a2aa19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a2aa19b8d66ea26666d45d321b22ca99d24fc39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091548274565-18388/BuildReport?accessString=eec6fc937fc7e06bc885901aa7a41ba36528cc09da1b0b287050c0a3a87f7fbf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[e75fe2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e75fe2a42cf59a0ca69640a91eaa321fb0d17755)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209141821135033-18388/BuildReport?accessString=af3fd4646a8dd7983de72186428b70f67d4e0cea9150dcd7b54837a4f4ada42c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 18:27 UTC, opbld30 commented
Docs Build status updates of commit _[21562c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21562c2e495ce8fc9d7e4df076c1d2aac11b7192)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209141824364270-18388/BuildReport?accessString=29d3dd432104ae2a3768ba7a0b17edd8d37d8ecc4890b5d8ac90ca28173534df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 19:44 UTC, FaithOmbongi requested changes
Hi @vibatra - Left suggestions for minor changes + the following additions:
+ Update identitygovernance-workflowversion.md as well and add the two new properties. Indicate inheritance just like you'll do for the two properties in identitygovernance-workflow.md. Add the two properties to the JSON representation as well.

2022-09-14 19:44 UTC, FaithOmbongi commented on api-reference/beta/resources/identitygovernance-workflowbase.md
> +|isSchedulingEnabled|Boolean|If true, the `workflow` engine executes the workflow on the schedule defined by tenant settings. |
Clarity on descriptions. Are these technically accurate?
```suggestion
|isEnabled|Boolean| Whether the workflow is enabled or disabled. If this setting is `true`, the workflow can be run on demand or on schedule when **isSchedulingEnabled** is `true`. <br><br>Supports `$filter`(`eq`, `ne`) and `orderBy`.|
|isSchedulingEnabled|Boolean|If `true`, the Lifecycle Workflow engine executes the workflow based on the schedule defined by tenant settings. Cannot be `true` for a disabled workflow (where **isEnabled** is `false`). |
```

2022-09-14 19:44 UTC, FaithOmbongi commented on api-reference/beta/resources/identitygovernance-workflow.md
> -|isSchedulingEnabled|Boolean|If true, the `workflow` engine executes the workflow on the schedule defined by tenant settings. |
Add back the properties with the latest descriptions. Plus append the statements "Inherited from [workflowBase](../resources/identitygovernance-workflowbase.md)."

2022-09-14 19:44 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.LCM.json
> +        },
Proposing that you delete these here and make the most of the next two objects to explain this reorg.

2022-09-14 19:44 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.LCM.json
> +          "Description": "Added the `isEnabled` property to the [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/workflowBase?view=graph-rest-beta) resource.",
```suggestion
          "Description": "Added the **isEnabled** property to the [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowBase?view=graph-rest-beta) resource. [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowBase?view=graph-rest-beta) is an entity type that's inherited by the following derived types in Lifecycle Workflows: [workflow](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta) and [workflowVersion](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowVersion?view=graph-rest-beta).",
```

2022-09-14 19:44 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.LCM.json
> +          "Description": "Added the `isSchedulingEnabled` property to the [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/workflowBase?view=graph-rest-beta) resource.",
```suggestion
          "Description": "Added the **isSchedulingEnabled** property to the [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowBase?view=graph-rest-beta) resource. [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowBase?view=graph-rest-beta) is an entity type that's inherited by the following derived types in Lifecycle Workflows: [workflow](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta) and [workflowVersion](https://docs.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowVersion?view=graph-rest-beta).",
```

2022-09-20 13:38 UTC, opbld30 commented
Docs Build status updates of commit _[4f3178a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f3178a463d2c7a1731960267639f07c4105d2d9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-29 20:38 UTC, vibatra commented on api-reference/beta/resources/identitygovernance-workflowbase.md
> +|isSchedulingEnabled|Boolean|If true, the `workflow` engine executes the workflow on the schedule defined by tenant settings. |
This is really good feedback. I have implemented the suggested change and updated the branch/PR.

2022-09-29 20:38 UTC, vibatra commented on changelog/Microsoft.AAD.LCM.json
> +        },
I have implemented the suggested change and updated the branch/PR.

2022-09-29 20:38 UTC, vibatra commented on changelog/Microsoft.AAD.LCM.json
> +          "Description": "Added the `isEnabled` property to the [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/workflowBase?view=graph-rest-beta) resource.",
I have implemented the suggested change and updated the branch/PR.

2022-09-29 20:38 UTC, vibatra commented on changelog/Microsoft.AAD.LCM.json
> +          "Description": "Added the `isSchedulingEnabled` property to the [workflowBase](https://docs.microsoft.com/en-us/graph/api/resources/workflowBase?view=graph-rest-beta) resource.",
I have implemented the suggested change and updated the branch/PR.

2022-09-29 20:39 UTC, opbld31 commented
Learn Build status updates of commit _[c1bfe73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1bfe733f89aff27dfca6e02c315493d24ae24b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowversion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowversion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowversion?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209292037186604-18388/BuildReport?accessString=618c6f11917fb7f3375d905147b81aa22824fbf01eebcfd57ae32e03d091ea1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 20:40 UTC, vibatra commented on api-reference/beta/resources/identitygovernance-workflow.md
> -|isSchedulingEnabled|Boolean|If true, the `workflow` engine executes the workflow on the schedule defined by tenant settings. |
I have implemented the suggestions and updated branch/PR.

2022-09-29 20:42 UTC, opbld34 commented
Learn Build status updates of commit _[a571998](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a571998588b6cf334d56a79862688d30edd0179e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowversion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowversion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowversion?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209292039185855-18388/BuildReport?accessString=f94a289802bc8829bf58d5e2a24df60103fe8c70388b748178caf7d64feeaee8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 20:45 UTC, opbld34 commented
Learn Build status updates of commit _[68b7ac2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68b7ac221346b9e3cc482867de08e1c21172f8f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowversion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowversion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowversion?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209292043476349-18388/BuildReport?accessString=37dfe3af3e5db7775d2636129e5c60e5403d94d579642a48dc25321ee52bc8b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 07:13 UTC, opbld31 commented
Learn Build status updates of commit _[e3703be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3703be5c911c15038b430a8c1a7622d3fdbbce8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8c1d661c)

<a id="8c1d661c"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit e3703be5c911c15038b430a8c1a7622d3fdbbce8 in branch vibatra/lcw-workflowbase-workflow-updates of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 55f1c6ea5e50db871f8f917d43ba4e02fc355b05). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209300712354231-18388/BuildReport?accessString=210f846699d4f258c2a4b15b3fa72ce1e1ec02dc24fb5e2413fed692cac1db48).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 07:13 UTC, FaithOmbongi approved these changes
Pushed one commit to update the doc links in line with recent RUL changes.

Approved for merge.

2022-09-30 07:23 UTC, opbld32 commented
Learn Build status updates of commit _[aa775a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa775a35e48170d34dc0880bace84a15b6b50ab9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowversion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowversion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowversion?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209300720549503-18388/BuildReport?accessString=a9a3dd29cc28690f1125800c65604e279fd88f591f1c9b2d8bccda65524b2df5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 21:00 UTC, FaithOmbongi commented
Hi @vibatra - Your schema PR was merged almost 3 weeks ago but somehow the changes are yet to reflect in both stagingBeta and beta. Any idea why? Will the changes go live before Ignite?

2022-10-04 21:37 UTC, vibatra commented
> Hi @vibatra - Your schema PR was merged almost 3 weeks ago but somehow the changes are yet to reflect in both stagingBeta and beta. Any idea why? Will the changes go live before Ignite?

Hello Faith, we had to revert the last build due to a bug and thus had to revert the schema changed before they were pushed out to Production. I have a PR open to get the schema changes in the Thursday's deployment window.

2022-10-04 21:37 UTC, opbld31 commented
Learn Build status updates of commit _[f43e2ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f43e2ca0a840b24c6407362f210c761239420c77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowversion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowversion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowversion?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210042135166484-18388/BuildReport?accessString=7feb78fb065deef1cbb5b2a1fca11d083c16d132b34d422720a2a28ef70b07ca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 01:32 UTC, opbld30 commented
Learn Build status updates of commit _[f07ac6c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f07ac6cac0dc05a634c5cc942f961247269a62d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowversion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowversion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowversion?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210110130084303-18388/BuildReport?accessString=f572922002ba64e6fb0366b3cd4289b28f9496755b2adde8b8b32feae340227a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 02:29 UTC, opbld30 commented
Learn Build status updates of commit _[9fbd2c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fbd2c0753b523d1e1e55f1411ce7403b5e5b1ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/concepts/data-connect-faq.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-18388) | [Details](#user-content-7c4919152535e56d32e4da992ec86104-728e7336)
[concepts/data-connect-troubleshooting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/concepts/data-connect-troubleshooting.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/data-connect-troubleshooting?branch=pr-en-us-18388) | [Details](#user-content-a17edba7c0f1c9b7a34884a24de18a5b-728e7336)
[api-reference/beta/api/identitygovernance-workflow-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflow-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflow-list-versions?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/api/identitygovernance-workflowversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/api/identitygovernance-workflowversion-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-workflowversion-get?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflow.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflow?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowbase.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowbase?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[api-reference/beta/resources/identitygovernance-workflowversion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/api-reference/beta/resources/identitygovernance-workflowversion.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-workflowversion?view=graph-rest-beta&branch=pr-en-us-18388) (graph-rest-beta) |
[changelog/Microsoft.AAD.LCM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/changelog/Microsoft.AAD.LCM.json) | :white_check_mark:Succeeded | |

<a id="7c4919152535e56d32e4da992ec86104-728e7336"></a>
### [concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/vibatra/lcw-workflowbase-workflow-updates/concepts/data-connect-faq.md)
 - **Line 50, Column 57**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#regions' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 67, Column 101**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 73, Column 82**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#datasets' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 79, Column 301**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#datasets' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 105, Column 108**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#datasets' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 123, Column 104**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/data-connect-quickstart?tabs=Microsoft365' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 156, Column 27**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/data-connect-quickstart?tabs=Microsoft365' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 50, Column 57**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#regions' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 67, Column 101**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 73, Column 82**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#datasets' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 79, Column 301**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#datasets' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 105, Column 108**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/data-connect-datasets#datasets' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 123, Column 104**: **[Suggestion: docs-link-absolute - [S [...]

2022-10-11 02:32 UTC, merged