Delete Role Assignable Groups
microsoftgraph/microsoft-graph-docs pull request #18464
Opened 2022-09-13 21:29 UTC by psaffaie

adding a note for role assignable group deletion. Role assignable groups can apparently only be deleted by Users who created the group or are a global admin or privileged role admin. This is documented internally in a troubleshooting wiki, can be validated using DS explorer, and is mentioned under the Group page for MS Graph but isn't mentioned on the MS Graph Delete Group documentation.

The reasoning for this is if I as a customer attempted to make a request to delete a group and a 403 was returned, a reasonable first instinct would be to check the documentation for the deletion action first, rather than the overview page defining everything about a group. Since this is a side effect caused by the property being set, it wouldn't be immediately clear that this property in the cause.

2022-09-13 21:32 UTC, opbld33 commented
Docs Build status updates of commit _[1a0f0f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a0f0f15f4c0ee5b6e21c029d9cedbf2703cb72f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-18464) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-3bc4d40e)

<a id="a10b0358399fc0f83f37a8db1c76d74d-3bc4d40e"></a>
### [api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete group' is duplicated with other articles: 'v1.0/api/group-delete.md(10,1), v1.0/api/termstore-group-delete.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209132129491725-18464/BuildReport?accessString=cf3e910121f15b47f012951b4eb297ecfb72e6d476e5487d0958a85450d939ea).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 10:14 UTC, FaithOmbongi requested changes
Hi @psaffaie - I've left a change suggestion inline. Please move the text after the permissions table.

2022-09-15 10:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/group-delete.md
> +Note: Role assignable groups can only be deleted by users who created the group, are a global administrator, or a privileged role administartor. The caller must be assigned the RoleManagement.ReadWri
- Suggestion to move this note after the permissions table because it's privilege-related.
- Q: For delegated, it is creator or owner? Please confirm.
- Also recommending that we call out privileges for app-only

```suggestion
The following conditions apply for apps to delete role-assignable groups:
+ For delegated scenarios, the app must be assigned the _RoleManagement.ReadWrite.Directory_ delegated permission, and the calling user must be the creator of the group or a global administrator or a privileged role administrator.
+ For app-only scenarios, the calling app must be the owner of the group or be assigned the _RoleManagement.ReadWrite.Directory_ application permission or be assigned the Global Administrator or Privileged Role Administrator Azure AD role.
```

2022-09-15 22:28 UTC, opbld33 commented
Docs Build status updates of commit _[455881b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/455881b8cfd2aa35852bf915ff524d59d8c74534)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-18464) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-23255540)

<a id="a10b0358399fc0f83f37a8db1c76d74d-23255540"></a>
### [api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete group' is duplicated with other articles: 'v1.0/api/group-delete.md(10,1), v1.0/api/termstore-group-delete.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152225352158-18464/BuildReport?accessString=422e652b1592e7d8cd56f68c1c30fd17b615c3e07925d7fec2904a99ffcc38e7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 17:07 UTC, opbld32 commented
Docs Build status updates of commit _[3d5885f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d5885f5035b5a8e1a1600dfcd1083927d4d8431)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-18464) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-22498ff1)

<a id="a10b0358399fc0f83f37a8db1c76d74d-22498ff1"></a>
### [api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete group' is duplicated with other articles: 'v1.0/api/group-delete.md(10,1), v1.0/api/termstore-group-delete.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209191703329572-18464/BuildReport?accessString=ed0d7af4467293cf1d81d22651669449b94440cc17cb779805013a2533a527d8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 23:24 UTC, psaffaie reviewed
@FaithOmbongi  let me know what else I need to do to implement the changes you recommended.

2022-09-20 05:28 UTC, FaithOmbongi commented on api-reference/v1.0/api/group-delete.md
> +
@psaffaie - Pending feedback: Please move this after the permissions table below where the context is privileges and permissions.

2022-09-20 05:28 UTC, FaithOmbongi approved these changes
Hi @psaffaie - Just one pending feedback. Please move the block of text after the permissions table where the context fits.

Otherwise, approved with suggestions.

2022-09-21 05:18 UTC, opbld34 commented
Docs Build status updates of commit _[f0c7fb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0c7fb50bbdfdf15eb0f8df6fae20380e582a1d7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 05:21 UTC, opbld30 commented
Docs Build status updates of commit _[94a11fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94a11fa7b2f6571effb45e5a84bb84ab0c8a4f9d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-18464) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-ce53f6e4)

<a id="a10b0358399fc0f83f37a8db1c76d74d-ce53f6e4"></a>
### [api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete group' is duplicated with other articles: 'v1.0/api/group-delete.md(10,1), v1.0/api/termstore-group-delete.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210516384491-18464/BuildReport?accessString=510483d36c36b151046185fb0aebecb90d451d6e0d008eddac7e4c44ebd8a3cc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 08:01 UTC, opbld33 commented
Docs Build status updates of commit _[f8622c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8622c13a87d784d17dabc474535aab56e2259ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-18464) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-c53b5181)
[api-reference/beta/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/beta/api/group-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-beta&branch=pr-en-us-18464) (graph-rest-beta) |

<a id="a10b0358399fc0f83f37a8db1c76d74d-c53b5181"></a>
### [api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/psaffaie-patch-1/api-reference/v1.0/api/group-delete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete group' is duplicated with other articles: 'v1.0/api/group-delete.md(10,1), v1.0/api/termstore-group-delete.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209270758384724-18464/BuildReport?accessString=3b4fc281caae1a70236042c0e1cb8faeee4a59e5c5eab539765b5615d20e5ccc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 02:24 UTC, merged