Permissions table update for Return and Update outcome pages
microsoftgraph/microsoft-graph-docs pull request #18494
Opened 2022-09-14 20:55 UTC by cristobal-buenrostro

Application permissions updated

2022-09-14 20:58 UTC, opbld33 commented
Docs Build status updates of commit _[7ff888c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ff888c007d38a4302cd510e5446cd581c1e4608)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142055345903-18494/BuildReport?accessString=7eb240b875277a2eefea6c06d2d9fe3e7e6fa400b94bb635652a3259f9db7e4a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 23:49 UTC, opbld31 commented
Docs Build status updates of commit _[e23886c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e23886ca8f3bba7a7833334471a85c21bbf3ca94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209232347006938-18494/BuildReport?accessString=c59e527310ef4a8035b01cb89a7331bc906cb8fc219eb2a048daebfd59448b5c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-30 15:35 UTC, isvargasmsft approved these changes

2022-10-01 03:02 UTC, Lauragra commented
@cristobal-buenrostro , please add a changelog entry for the new permissions before we merge this PR. Thanks.

2022-10-04 02:39 UTC, Lauragra commented
@cristobal-buenrostro , please include changelog entries to call out that support for application permissions was added for these APIs.

2022-10-04 17:44 UTC, cristobal-buenrostro commented
> @cristobal-buenrostro , please include changelog entries to call out that support for application permissions was added for these APIs.

@Lauragra   , changelog added

2022-10-04 17:45 UTC, opbld31 commented
Learn Build status updates of commit _[9e447ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e447edd761eeef550919d2360b97b693fec5e8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041742465105-18494/BuildReport?accessString=5388cb284d61d3794f51829e75a13652bd49da1dac22d986917ef070d20a74d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 20:26 UTC, isvargasmsft commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationOutcome"
Changelog: @cristobal-buenrostro please follow examples 14 and 15 here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples. 

Specifically, please take a look at the ChangedApiName values.

2022-10-04 20:26 UTC, isvargasmsft requested changes
Hi @cristobal-buenrostro, just 1 more detail, please follow the examples 14 and 15 in the [changelog guide](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples).

2022-10-06 18:02 UTC, opbld34 commented
Learn Build status updates of commit _[0d0dc72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d0dc722067eee02d87232aee9e3ac0ba2a30240)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210061759406845-18494/BuildReport?accessString=925d942b9e35e8145aecbacec2a96effcce673beb08c66a461c8d129e4425392).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 18:03 UTC, cristobal-buenrostro commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationOutcome"
done

2022-10-06 18:06 UTC, opbld30 commented
Learn Build status updates of commit _[f2a449f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2a449f77589c8044cc2eef889c75fc1795e4823)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210061803180726-18494/BuildReport?accessString=2afbe507aa65acf7bdefc01cdc60d16e14d10303cb9a63813d00b4d11afa774d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 19:33 UTC, isvargasmsft approved these changes

2022-10-07 03:39 UTC, opbld33 commented
Learn Build status updates of commit _[e3c7910](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3c7910b7d18cfbdc5d1904973f2dc6fc0733bd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-18494) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-return.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-return?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-18494) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cristobalb/app-return-grading/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210070337280131-18494/BuildReport?accessString=6bf48b61d0f163a717ff56f4cbd0241bf19d0a9f03c4a28f35274c872c5ab503).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 03:51 UTC, merged