[CloudPC]Onboard new canary error type: UdpConnectivityCheckStunUrlNotAllowListed,UdpConnectivityCheckUnknownError
microsoftgraph/microsoft-graph-docs pull request #18505
Opened 2022-09-15 11:44 UTC by Emma0727

[CloudPC]Onboard new canary error type: UdpConnectivityCheckStunUrlNotAllowListed,UdpConnectivityCheckUnknownError

2022-09-15 11:46 UTC, opbld30 commented
Docs Build status updates of commit _[5083031](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5083031a1667c9596b6ed843c90535211de5ca4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-18505) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209151144103679-18505/BuildReport?accessString=ca925856c8bd11fc132d9febe5e3b82e79abe8e4622d9a8dd2cb18798659fc38).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 03:25 UTC, RuiHou105 requested changes
@Emma0727 
1.Please also update the changelog/Microsoft.CloudManagedDesktop.json. 
2. Please create a roadmap workitem and attach the workitem number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If you don't have access, please do these firstly:
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-10-08 07:25 UTC, AshleyYangSZ requested changes
Please add change-log @Emma0727

2022-10-14 07:56 UTC, opbld31 commented
Learn Build status updates of commit _[c303a66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c303a666acba634c7482e9cf5034d9a3acb61fdb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-18505) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210140753071747-18505/BuildReport?accessString=e8f2411fbf4d80634d9c3e95bddd29f5160c348d498139ad6628b074b0e63cb2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 03:43 UTC, AshleyYangSZ approved these changes

2022-10-26 07:45 UTC, opbld33 commented
Learn Build status updates of commit _[0d233a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d233a08f6be608dc49dc897af4d4b79f6557a60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-18505) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210260733365655-18505/BuildReport?accessString=46079720f8494a415a25d5e28991a93a6e74243b373fcef392acd1959c1e28ed).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 07:48 UTC, opbld31 commented
Learn Build status updates of commit _[1c3dcdf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c3dcdffdaa65255e72f5dd539893907cb03b292)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-18505) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210260734344173-18505/BuildReport?accessString=122991aad2ed5b6968ecc3a2f6cab7b44841b2868379385b6b181b5255c078e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-03 06:32 UTC, RuiHou105 approved these changes

2022-11-03 20:08 UTC, dodaromike commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|udpConnectivityCheckStunUrlNotAllowListed|Your current network configuration does not allow the use of UDP direct connect (STUN). This will not prevent the use of Cloud PCs but may prevent optimal p
The acronym STUN is not defined.  Please add definition.

2022-11-03 20:09 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|udpConnectivityCheckStunUrlNotAllowListed|Your current network configuration does not allow the use of UDP direct connect (STUN). This will not prevent the use of Cloud PCs but may prevent optimal p
Following this comment, please also add the definition of UDP.

2022-11-03 20:28 UTC, isvargasmsft requested changes
Hello @Emma0727, 

Thank you very much for your work in this PR. Very complete. 

We just wanted to have a definition of the STUN acronym that is not clear to us. Could you please add the definition of the acronym? 

Please feel free to ping me on the side if you have questions. 

Kind regards, 

Isaac and Mike.

2022-12-08 02:28 UTC, Emma0727 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|udpConnectivityCheckStunUrlNotAllowListed|Your current network configuration does not allow the use of UDP direct connect (STUN). This will not prevent the use of Cloud PCs but may prevent optimal p
sorry, I missed this comment, will add definition.

2022-12-09 02:49 UTC, opbld34 commented
Learn Build status updates of commit _[27861a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27861a67eb22d5e78ed1dff7f03c02a72baa0ee1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-18505) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212090245424284-18505/BuildReport?accessString=85b674666a9b692e4733406a16178c0eba313b46cd9e430dda0c1709393d25af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 14:21 UTC, isvargasmsft approved these changes

2022-12-09 14:24 UTC, opbld34 commented
Learn Build status updates of commit _[f0e91b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0e91b1feb45882cd139c49d9949393bb2291624)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-18505) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/wenyqiu/20220915/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091421298464-18505/BuildReport?accessString=9a241e760d96c830aa271343ec6399edeb00afd97ccd9a9d9b6fbeb1561bb725).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-13 20:38 UTC, merged