Adding service principal lock configuration property
microsoftgraph/microsoft-graph-docs pull request #18517
Opened 2022-09-16 00:54 UTC by madansr7

2022-09-16 00:56 UTC, opbld30 commented
Docs Build status updates of commit _[733a15d](https://github.com/madansr7/microsoft-graph-docs/commits/733a15df79359089a71cf1b1d40c7b0baa83ee75)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) | [Details](#user-content-d18e6d86567a97ecd4e28c205b03fcb6-9110347a)
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |

<a id="d18e6d86567a97ecd4e28c205b03fcb6-9110347a"></a>
### [api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md)
 - **Line 7, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'saumadan' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160054216850-18517/BuildReport?accessString=b7a5b9e7994f37d589374e10da4817752d718353bb5aa2cc01c5259547e6f38f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 22:17 UTC, opbld33 commented
Docs Build status updates of commit _[d2f5f19](https://github.com/madansr7/microsoft-graph-docs/commits/d2f5f1914ce7fd28d115fe21e2871951eabb65bb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 22:20 UTC, opbld34 commented
Docs Build status updates of commit _[ee049ae](https://github.com/madansr7/microsoft-graph-docs/commits/ee049ae7b9e0a90c808570201d0031807a18afca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202216393803-18517/BuildReport?accessString=de73d86d827d5eca19031df2471363f3ed9b22dfea19cf4a45b9798a6c06b878).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-11-07 19:19 UTC, opbld31 commented
Learn Build status updates of commit _[01c090e](https://github.com/madansr7/microsoft-graph-docs/commits/01c090e78d78f98e7dc6af3eaaf2ab7c8b04782b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211071914326351-18517/BuildReport?accessString=982ba5d8423cf72384eb31650ca9ad5364438567332219e582ba1e7c95dbf01a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 21:30 UTC, madansr7 commented
@FaithOmbongi can you please review and approve?

2022-11-08 09:15 UTC, FaithOmbongi requested changes
Hi @madansr7 - I've left some inline suggestions and aspects that need clarification.

Also, add the property to the [Update application](https://review.learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-18517&tabs=http#request-body) doc as an updatable property.

2022-11-08 09:15 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [servicePrincipalLockConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta) resource",
Tooling bug
```suggestion
          "Description": "Added the **servicePrincipalLockConfiguration** property to the [application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta) resource.",
```

2022-11-08 09:15 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": "Directory management"
```suggestion
      "WorkloadArea": "Applications",
      "SubArea": ""
```

2022-11-09 00:49 UTC, opbld30 commented
Learn Build status updates of commit _[86f7f7e](https://github.com/madansr7/microsoft-graph-docs/commits/86f7f7e3e8faac40ac375277afef2821ae0e0c8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211090037093187-18517/BuildReport?accessString=87631c3320144f77f19522613942b3a3b41921d92f5d5664df3eb18c23925083).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 00:52 UTC, opbld32 commented
Learn Build status updates of commit _[3a5671c](https://github.com/madansr7/microsoft-graph-docs/commits/3a5671c60b5d7a24e15f19b5f52038c77fd5b0b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211090037294889-18517/BuildReport?accessString=b0fda82f3404a167ab8554c9dfb645c59d6e0139b4761ab73b40873085cc1009).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 17:32 UTC, FaithOmbongi approved these changes
Thank you @madansr7. I've left inline comments to clarify one question you asked and suggest changes for one oversight.

Otherwise, **approved with changes.**

PS: I notice that you copied an existing doc and used it as a template for the new resource type. I strongly recommend that you always use doc stubs to start authoring and avoid duplicating an existing doc. Doc stubs are always generated in your engineer's schema PR. Using the template helps ensure that you aren't inheriting any template "bugs" from existing docs.

2022-11-09 17:32 UTC, FaithOmbongi commented on api-reference/beta/resources/servicePrincipalLockConfiguration.md
> +Basic profile information of the application.
@madansr7 - Please see the suggested update that matches this description with the description in line 3.
```suggestion
Specifies the sensitive properties of the app that are locked for editing on the service principal. You can disable this configuration to allow the properties to be updated.
```

2022-11-09 17:32 UTC, FaithOmbongi commented on api-reference/beta/resources/servicePrincipalLockConfiguration.md
> +   "isEnabled": "Boolean",
nit
```suggestion
   "@odata.type": "#microsoft.graph.servicePrincipalLockConfiguration",
   "isEnabled": "Boolean",
```

2022-11-09 17:58 UTC, opbld30 commented
Learn Build status updates of commit _[19b1234](https://github.com/madansr7/microsoft-graph-docs/commits/19b12343b98c6da0e9dd7b63e509aa61ab2f7168)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211091755116665-18517/BuildReport?accessString=f64338f0f352370637acb7f14788e4872b5f4444c0d463250775a9c963407496).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 18:00 UTC, opbld34 commented
Learn Build status updates of commit _[63a76d3](https://github.com/madansr7/microsoft-graph-docs/commits/63a76d3463843d38e57ede4fe45454d982ee0879)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211091755342315-18517/BuildReport?accessString=6e2a48d5ee9bf97571325c572588cfa5c2b0d4adceedee719e46e74df8413762).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 19:05 UTC, opbld33 commented
Learn Build status updates of commit _[d2f7711](https://github.com/madansr7/microsoft-graph-docs/commits/d2f771102dbed19344475c37f551aca4ac2b0ca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211091902588897-18517/BuildReport?accessString=6d3dc25f7e207de6726e2a5f0d2cd2012fe22d18279ba8a98f3457f090062d1a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 03:02 UTC, opbld31 commented
Learn Build status updates of commit _[1b6abd4](https://github.com/madansr7/microsoft-graph-docs/commits/1b6abd489652d423bd8951d196e87903cdb9772e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[api-reference/beta/resources/servicePrincipalLockConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/api-reference/beta/resources/servicePrincipalLockConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/serviceprincipallockconfiguration?view=graph-rest-beta&branch=pr-en-us-18517) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/spfreeze/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211100258563736-18517/BuildReport?accessString=69844a3097c4e94091360cd5df4203ae16bb60d91b852d82e4f22a9026df9647).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 03:14 UTC, merged