[CloudPC]Add CloudPC reports related API
microsoftgraph/microsoft-graph-docs pull request #18518
Opened 2022-09-16 01:49 UTC by AshleyYangSZ

2022-09-16 01:51 UTC, opbld32 commented
Docs Build status updates of commit _[4caaaac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4caaaacee314c2fd93bf4c66f66d8e00a5a07ed6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-d94c9085)
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-86ded4e4a72198270e42c43a7f5a7c20-d94c9085)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-d94c9085"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="86ded4e4a72198270e42c43a7f5a7c20-d94c9085"></a>
### [api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md)
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/cloudpcreports-list-exportjobs.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160149448192-18518/BuildReport?accessString=b7df5fa4b705de12acfe1c4f95f6b4f8bb1d47bef7556d76cfb238aa1e5d68ea).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question [...]

2022-09-16 02:05 UTC, opbld34 commented
Docs Build status updates of commit _[e73024d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e73024d50e8eca153a900a664707b962d9b82c91)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-e2a0c0a0)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-e2a0c0a0"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160202331688-18518/BuildReport?accessString=e5ca59c92cf565448f28ae2e40e49a8c8e507a93f6d15499162cc99b28676324).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 02:51 UTC, opbld33 commented
Docs Build status updates of commit _[b64e867](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b64e867778f6d83bbef0346f25fc23b3b38bcacc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-15bd7200)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-15bd7200)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-15bd7200"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="0817dce4456c16725d5333633847d38f-15bd7200"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160247180633-18518/BuildReport?accessString=580bee34d353eb9d97cd73ed9d65b3c23c65895a454944b53ae4ff3db27fdda0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validat [...]

2022-09-16 04:17 UTC, opbld30 commented
Docs Build status updates of commit _[447cade](https://github.com/microsoftgraph/microsoft-graph-docs/commits/447cadead3bf2690a247565695ef5c9fa5c3a0fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-f260c286)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f260c286)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-f260c286"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0817dce4456c16725d5333633847d38f-f260c286"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160413396364-18518/BuildReport?accessString=557ed4a25d4292f067fe66c82563891be02e49d3157df2efc36c5ceb925ef2aa).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></l [...]

2022-09-16 04:47 UTC, opbld32 commented
Docs Build status updates of commit _[39d2c78](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39d2c787279be55f757903712b523bf495504513)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-9991521e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9991521e)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-9991521e"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````
 - **Line 49, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpcexportjob.md/'.`````

<a id="0817dce4456c16725d5333633847d38f-9991521e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160445454686-18518/BuildReport?accessString=7dc76289e20468b2c6f9604b72faad0c3c7f18afdbe4e6e6f2f3117ae9e223c7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages- [...]

2022-09-16 11:27 UTC, opbld33 commented
Docs Build status updates of commit _[7b45354](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b453545a95bb67f9ed83d37530b1212b4393f3e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-f604ac36)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f604ac36)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-f604ac36"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0817dce4456c16725d5333633847d38f-f604ac36"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209161123415115-18518/BuildReport?accessString=5f6ff9706e84d8500b89ad881bcef5a1baa72f04fd2017295d59612a68ffc2b8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></l [...]

2022-09-16 12:03 UTC, opbld34 commented
Docs Build status updates of commit _[70ea2d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70ea2d8396e2fccfe7c7c8db4ecb55edf32acdea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-8f7e5a5f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8f7e5a5f)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-8f7e5a5f"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0817dce4456c16725d5333633847d38f-8f7e5a5f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209161200546691-18518/BuildReport?accessString=0d8eea13723e2c3d0e3d85810607dd930e197cee84ead6b003be1f3190d1175c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></l [...]

2022-09-27 04:02 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcreports.md
> +|[getRemoteConnectionHistoricalReports](../api/cloudpcreports-getremoteconnectionhistoricalreports.md)|Stream|Get a Cloud PC's the remote connection historical reports like signInDateTime, signOutDat
```suggestion
|[getRemoteConnectionHistoricalReports](../api/cloudpcreports-getremoteconnectionhistoricalreports.md)|Stream|Get a Cloud PC's remote connection historical reports like signInDateTime, signOutDateTime and usageInHour in a given period.|
```

2022-09-27 07:48 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md
> +Get the real time connection latency related information like RTT and etc of Cloud PC.s
```suggestion
Get the real time connection latency related information like RTT and etc of  a Cloud PC.
```

2022-09-27 07:52 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md
> +description: "Get the real time connection latency related information like RTT and etc of Cloud PC."
```suggestion
description: "Get the real time connection latency related information like RTT and etc of a Cloud PC."
```

2022-09-27 07:59 UTC, RuiHou105 requested changes
Please resolve all comments.

2022-09-27 13:39 UTC, opbld30 commented
Docs Build status updates of commit _[207b93b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/207b93ba22583b5af103048ae93c25bb35cdea3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-90e39284)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-90e39284"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209271336525518-18518/BuildReport?accessString=23773b8fc144c75be902afc6c91c0d69c794c8d89b5e84b9ffee245473a517ba).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-30 15:59 UTC, isvargasmsft commented
Hello @AshleyYangSZ @RuiHou105 would you be so kind to update the roadmap item and add the CSDL PR, please?

2022-09-30 23:33 UTC, AshleyYangSZ commented
> Hello @AshleyYangSZ @RuiHou105 would you be so kind to update the roadmap item and add the CSDL PR, please?

Thanks @isvargasmsft, already added.
Roadmap Id: 15183
CSDL PR: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6788638
api.md PR: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/10831

2022-10-04 14:21 UTC, isvargasmsft commented
> > Hello @AshleyYangSZ @RuiHou105 would you be so kind to update the roadmap item and add the CSDL PR, please?
> 
> Thanks @isvargasmsft, already added. Roadmap Id: 15183

Removing the links as those links are confidential. 

Thank you Ashley :)

2022-10-04 14:27 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Target": "virtualEndpoint"
Fixing entry:
```suggestion
                    "Id": "a74bf4db-93a3-4a4c-98b0-400bac1e2131",
                    "ApiChange": "Relationship",
                    "ChangedApiName": "reports",
                    "ChangeType": "Addition",
                    "Description": "Added the **reports** relationship to the [virtualEndpoint](https://docs.microsoft.com/en-us/graph/api/resources/intune-virtualEndpoint?view=graph-rest-beta) resource.",
                    "Target": "virtualEndpoint"
```

2022-10-04 14:30 UTC, opbld32 commented
Learn Build status updates of commit _[4da2571](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4da2571b685e318f56f7d71f3018614308949e14)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-8479b76b)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-8479b76b"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041428140725-18518/BuildReport?accessString=7f5cf10906be3a5d0d7f224b4b083a28dccffca2cf833dc7cbe7ad6dd16fbcba).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 14:37 UTC, opbld30 commented
Learn Build status updates of commit _[f34c76f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f34c76f42f73602f2b5ea29ae6779e3d24022707)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-235de151)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-235de151"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041433049631-18518/BuildReport?accessString=933bb0440498be8a390ec0b956735e25188e2e6b55853231adf10efc381e5496).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 16:58 UTC, opbld33 commented
Learn Build status updates of commit _[c1cee66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1cee66878ea24d1c6a9657246e13271043efd07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) | [Details](#user-content-e5ab6ac50543ced0aff5bc6e2e917ac7-35f400a9)
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="e5ab6ac50543ced0aff5bc6e2e917ac7-35f400a9"></a>
### [api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041656155483-18518/BuildReport?accessString=3daa601b5d7d70bdaaba966ee04d9eadd9a133a1e5d865cc39f1769581813b5e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 19:40 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcreports-post-exportjobs.md
> +
Please complete this table. Replace the TO DO placeholders with the corresponding permissions.

2022-10-04 19:43 UTC, opbld31 commented
Learn Build status updates of commit _[bdba9c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bdba9c45cb613cfd155a0eac744bcd1a90b2eff6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041940467355-18518/BuildReport?accessString=0126b1e72caf1f9a16478ff2b847cc45e39bf11d1a5a8ec8c2e1dff0fc07989f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 19:46 UTC, opbld30 commented
Learn Build status updates of commit _[b309c33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b309c33aa0fba0d16c82ef92de584724b65364ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041944118659-18518/BuildReport?accessString=7147e7cc4007dccca0a4f3eda1a20158c43219c615738138d8541a5090a56339).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 19:51 UTC, opbld31 commented
Learn Build status updates of commit _[5548766](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55487667e189d8ad1ca66171ba90291df21c23ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041948530181-18518/BuildReport?accessString=409d0a9ac69a1aec3098d0dcf7f5e9600b11e7fd81d9a85333d43fad23f7a5a1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 19:55 UTC, isvargasmsft requested changes
Hi @AshleyYangSZ, 

Thank you very much for your work in this PR. Very complete overall. 

Please take a look at a few comments I left:
1. Please clarify if the member 'failed' should be removed from this documentation as it is not included in the CSDL PR. 
2. Please complete the permissions table in the Create exportJobs topic. 

Feel free to ping me if you have questions. 

Always happy to help. 

Isaac

2022-10-04 19:59 UTC, opbld32 commented
Learn Build status updates of commit _[9dbf39d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dbf39d07b040f0cef7cd053901d41841dac4a40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041957210682-18518/BuildReport?accessString=bbb1f5690c4c1d3999613ca4c61c8df79afa341fc18dfdac837b22d4f6644706).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 07:22 UTC, opbld32 commented
Learn Build status updates of commit _[428acb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/428acb11f05ed20eef0faba8567cde7a56b29f94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080716245678-18518/BuildReport?accessString=4f4a052c40f842463e3967620e6de9d729e41b8a83694bb8db04fa0cad6c293a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 07:23 UTC, AshleyYangSZ commented
> Please resolve all comments.

@RuiHou105 Already resolved please help review again. Thanks

2022-10-08 07:24 UTC, AshleyYangSZ commented
> Hi @AshleyYangSZ,
> 
> Thank you very much for your work in this PR. Very complete overall.
> 
> Please take a look at a few comments I left:
> 
> 1. Please clarify if the member 'failed' should be removed from this documentation as it is not included in the CSDL PR.
> 2. Please complete the permissions table in the Create exportJobs topic.
> 
> Feel free to ping me if you have questions.
> 
> Always happy to help.
> 
> Isaac

Hi @isvargasmsft Already resolved the comments, please help review again. Thanks a lot!

2022-10-08 07:25 UTC, opbld34 commented
Learn Build status updates of commit _[ccf7a14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccf7a14167b46b1e4366be26e4ecf87f6aeb003c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080723279668-18518/BuildReport?accessString=52945eeb3bb999b008dde4aedef687832e0503f41f04f31516a14a238b8fa0e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 00:38 UTC, opbld32 commented
Learn Build status updates of commit _[00938ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00938ffe5cbee8adbfb21b57e793b83fad0c6c2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210100036089063-18518/BuildReport?accessString=fb28603e5dd99d9a4895105de94647bc630b6e81f0772e55969c81e74b7495a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 00:42 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcexportjob.md
> +|failed|The export job is failed. |
@isvargasmsft Thanks, you help find out a mistake here. Actually, failed is already reviewed in another design api.md PR https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11593, and I also added in schema with this https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6881283. So, let's keep it here.

2022-10-13 06:34 UTC, opbld34 commented
Learn Build status updates of commit _[1b665b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b665b7d72df0f825ead728e58c7d10939a39969)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210130631254416-18518/BuildReport?accessString=35634a9108fa163ef782445495d5f9251445588a95cc6bfb41b6b74e10d24359).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 19:52 UTC, isvargasmsft approved these changes

2022-10-14 19:54 UTC, isvargasmsft commented
@AshleyYangSZ approved :)

2022-10-18 06:11 UTC, opbld34 commented
Learn Build status updates of commit _[78b537c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78b537cae68e51d80c08b91c346013a40d9b9548)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180609432861-18518/BuildReport?accessString=9219bd3e8d29089293f275f4e30f9f9d5c66c3258970ae328145feb0c56dccbf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 01:43 UTC, opbld30 commented
Learn Build status updates of commit _[4012024](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4012024f6a3c013fd36f7fb2a4ab6d00fc3162d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210200131306243-18518/BuildReport?accessString=c4ccd4d9be915a2b0cafac79d4ea4e5b7ba18155be8d8fdf62de32a3d6839810).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 03:39 UTC, opbld34 commented
Learn Build status updates of commit _[5061a59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5061a5958f4375b708cd8fc21e491de768e48287)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210200328087574-18518/BuildReport?accessString=a471667f32cbd7e360c8468aaae1fc9c92c6c88ddbaaa90a61172a68d1b9b56d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 03:41 UTC, opbld32 commented
Learn Build status updates of commit _[143ddec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/143ddece9e5fada928d87130a7ca5a25096b4c7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcexportjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcexportjob-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionlatency?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getrealtimeremoteconnectionstatus?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getremoteconnectionhistoricalreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-gettotalaggregatedremoteconnectionreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/api/cloudpcreports-post-exportjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/api/cloudpcreports-post-exportjobs.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-post-exportjobs?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/cloudpcreports.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcreports?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcexportjob-get?view=graph-rest-beta&branch=pr-en-us-18518) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/unifiedDashboard/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210200332311237-18518/BuildReport?accessString=27665dafb0c2b3d87750b9b858963ea45cd84f7c5517c2b5bcbaabe9ad436abf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 03:45 UTC, merged