Change for feature First Line Worker
microsoftgraph/microsoft-graph-docs pull request #18537
Opened 2022-09-19 08:52 UTC by Guoan-Tang

2022-09-19 09:09 UTC, opbld31 commented
Docs Build status updates of commit _[71463ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71463ab9c9c9073c593108dd65053a8ebd696076)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209190852364064-18537/BuildReport?accessString=ccb9bbe85cfdfc630a2863745e987bbe4dc8585dbf76fcbd2c965b3472cf5a5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 01:04 UTC, AshleyYangSZ commented
@Guoan-Tang Please add the change-log and make this PR pass microsoft-graph-docs apidoctor-beta build .

2022-09-20 01:06 UTC, AshleyYangSZ requested changes
As you added a new entity sharedUseServicePlan you need to update the toc.yml as well.

2022-09-20 01:08 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-list-shareduseserviceplan.md
> +# List sharedUseServicePlans
In your design PR, you also add get sharedUseServicePlan API, so please add the doc for it as well

2022-09-20 03:04 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|provisioningType|cloudPcProvisioningType|Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. Possible values are dedicated and shared. It will be dedicated by de
cloudPcProvisioningType is a newly added enum. Please add it down below.

2022-09-20 03:08 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcshareduseserviceplan.md
> +## Methods
According to your [design](https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11609), cloudPcSharedUseServicePlan only supports List and GET. So please remove extra methods here.

2022-09-20 03:09 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcshareduseserviceplan.md
> +| [List provisioningPolicies](../api/virtualendpoint-list-provisioningpolicies.md)        | [cloudPcProvisioningPolicy](../resources/cloudpcprovisioningpolicy.md) collection | List properties and rel
should be `sharedUseServicePlans`, not `provisioningPolicies`. Same errors down below.

2022-09-20 03:10 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcshareduseserviceplan.md
> +| [Get cloudPcProvisioningPolicy](../api/cloudpcprovisioningpolicy-get.md)                | [cloudPcProvisioningPolicy](../resources/cloudpcprovisioningpolicy.md)            | Read the properties and
Should be `cloudPcSharedUseServicePlan `, not `cloudPcProvisioningPolicy`

2022-09-20 03:12 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
> +|provisioningType|cloudPcProvisioningType|Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. Possible values are dedicated and shared. It will be dedicated by de
Please refer the `cloudPcProvisioningType `to correct enum in ( ... ).

2022-09-20 03:15 UTC, RuiHou105 commented
Please create a roadmap workitem and attach the wormitem number in comment.  Here is amn example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14845/

If you don't have access, please do these two first:|
Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-09-27 09:26 UTC, opbld32 commented
Docs Build status updates of commit _[f946cee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f946ceeb412d8e3282844869a8b111b27bb7761a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-18d75838)

<a id="18d75838"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit f946ceeb412d8e3282844869a8b111b27bb7761a in branch guoan/flw of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit bf84f700989247200c76fb5b290d5472443886dc). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209270925486863-18537/BuildReport?accessString=4ac23d564412d9bc71b274813dffdf2e98e4e0bb565e9c39080870387a64df03).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 02:20 UTC, opbld34 commented
Docs Build status updates of commit _[ee6e23e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee6e23e180ea7b7a4e5a534be04e4cbb05a04021)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-d41b0f0c)
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-1222137994597eed72f1e4a0648d90c2-d41b0f0c)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-d41b0f0c)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="697cad2e2e5111f612c2f6c776737a98-d41b0f0c"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md)
 - **Line 62, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#CloudPcProvisioningType-values' in 'beta/resources/cloudpcprovisioningpolicy.md', did you mean '#cloudpcprovisioningtype-values'?`````

<a id="1222137994597eed72f1e4a0648d90c2-d41b0f0c"></a>
### [api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md)
 - **Line 62, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#CloudPcProvisioningType-values' in 'beta/resources/cloudpcprovisioningpolicy.md', did you mean '#cloudpcprovisioningtype-values'?`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-d41b0f0c"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 47, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#CloudPcProvisioningType-values' in 'beta/resources/cloudpcprovisioningpolicy.md', did you mean '#cloudpcprovisioningtype-values'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209280217495618-18537/BuildReport?accessString=48380cc53f6055200398e35663f2d4e7d7f9b36121590c5d901fd225da8875e7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-08 07:33 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcshareduseserviceplan-get.md
> +author: "AshleyYangSZ"
Please update the author to yourself. Not me.

2022-10-08 07:46 UTC, AshleyYangSZ requested changes

2022-10-08 07:46 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcshareduseserviceplan-get.md
> +    "totalCount": "Integer"
Please update the response with real value not the "String"

2022-10-08 07:46 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Id": "933f075d-490f-474f-a6e6-037ab1e8703c",
1. Please only include your changes corresponding log here, not others
2. Please do not update existed change list.

2022-10-09 11:22 UTC, opbld30 commented
Learn Build status updates of commit _[1f906aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f906aaf729755e4d097c8785dfaf8c7519dee8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-3468cddf)
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-1222137994597eed72f1e4a0648d90c2-3468cddf)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-3468cddf)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3468cddf)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="697cad2e2e5111f612c2f6c776737a98-3468cddf"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md)
 - **Line 62, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#CloudPcProvisioningType-values' in 'beta/resources/cloudpcprovisioningpolicy.md', did you mean '#cloudpcprovisioningtype-values'?`````

<a id="1222137994597eed72f1e4a0648d90c2-3468cddf"></a>
### [api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md)
 - **Line 62, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#CloudPcProvisioningType-values' in 'beta/resources/cloudpcprovisioningpolicy.md', did you mean '#cloudpcprovisioningtype-values'?`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-3468cddf"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 47, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#CloudPcProvisioningType-values' in 'beta/resources/cloudpcprovisioningpolicy.md', did you mean '#cloudpcprovisioningtype-values'?`````

<a id="0817dce4456c16725d5333633847d38f-3468cddf"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml)
 - **Line 10459, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualendpoint-list-cloudpcshareduseserviceplan.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210091120406733-18537/BuildReport?accessString=91e47b9cdd2e03a5abc554157bd3176df4b9a894ac4302823eb61de01d3f8612).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.co [...]

2022-10-09 11:37 UTC, Guoan-Tang commented
WorkItem: [Feature 15375](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15375): [DEVICES AND APPS][CLOUD PC] Add new entity cloudPcSharedUseServicePlan

2022-10-09 11:53 UTC, opbld31 commented
Learn Build status updates of commit _[94aebfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94aebfd03294f615491be74325fe27b9da246a48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-495a4f86)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-495a4f86"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml)
 - **Line 10459, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualendpoint-list-cloudpcshareduseserviceplan.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210091151015581-18537/BuildReport?accessString=0779c45c1dfba7a8a98c2a76093f8748789fd75c66322d76010f41410f580bdf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 02:11 UTC, opbld33 commented
Learn Build status updates of commit _[204eb09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/204eb09418e46ba0c6bd72b1dc6f79a25e96e4d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3d96fdfa)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-3d96fdfa"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml)
 - **Line 10459, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualendpoint-list-shareduseserviceplan.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120208430161-18537/BuildReport?accessString=9d03fced508c3986c970511b3e180b982edc0de9fa9f70a1188bfca151511980).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 02:13 UTC, opbld34 commented
Learn Build status updates of commit _[d3770b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3770b342bba5e5fb610e9984eb61adcd716ce98)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d8e67fea)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d8e67fea"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml)
 - **Line 10459, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/virtualendpoint-list-shareduseserviceplan.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120209385648-18537/BuildReport?accessString=3425ebb5bc298f5e1ad0d27577aa1f55e5902d8359258515770f3a957aa0019c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 08:12 UTC, opbld34 commented
Learn Build status updates of commit _[9e8261f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e8261f770b7ffefb1a958c283be123fbb8c6726)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120810211769-18537/BuildReport?accessString=f180642f3074809508a9c8b81ef92e16334e551e9cb3aa2bddb234eab9f5ba0f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 08:31 UTC, opbld34 commented
Learn Build status updates of commit _[f5a509e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5a509e34549b7eb77d275c26a98be7d1cff1fa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120828290304-18537/BuildReport?accessString=e0147b60e4734621cc41452da392853cc315c23b0631b96f9feddb400bf01812).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 09:06 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|Membername|Description|Value|
```suggestion
|Membername|Value|Description|
```

2022-10-12 09:07 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|`dedicated`|0|Defaultvalue.Indicatesthepolicyshouldusethededicated,peruserlicensesfortheprovisioningpolicywhenprovisioningCloudPCsforusers.|
For these members descriptions here, your sentences don't have any punctuation. Please add properly.

2022-10-12 09:09 UTC, opbld30 commented
Learn Build status updates of commit _[9011ffb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9011ffb1053ca4b7f9aa21c178fc411ea2080a29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120906367751-18537/BuildReport?accessString=ea7efb4f6a6addc77a2b60bbf381b954b98ec85f9ded99b067f4a759839f3a92).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 09:15 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcshareduseserviceplan.md
> +description: "Represents a Cloud PC Shared Use ServicePlan."
```suggestion
description: "Represents a Cloud PC Shared Use Service Plan."
```

2022-10-12 09:15 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcshareduseserviceplan.md
> +Represents a Cloud PC Shared Use ServicePlan.
```suggestion
Represents a Cloud PC shared use service plan.
```

2022-10-12 09:18 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md
> +description: "View the properties and relationships of all Cloud PC Shared Use ServicePlans."
```suggestion
description: "List properties of cloudPcSharedUseServicePlan] objects"
```

2022-10-12 09:21 UTC, RuiHou105 requested changes
Please resolve comments.

2022-10-12 09:22 UTC, opbld33 commented
Learn Build status updates of commit _[73f44dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73f44dc962d852a2fe1cb5cdd0726e83ee1e1619)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120919209643-18537/BuildReport?accessString=ecd824bf6e92ee356ad4defd753847e4be91185b8b415cc20a4fc56dc9507e8b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 09:24 UTC, opbld31 commented
Learn Build status updates of commit _[1bd12bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bd12bc491a920d5d1f51a0f477381dcc88b2641)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120919316025-18537/BuildReport?accessString=518ed5f62b23ca9d6c3c453097c80c56f3ecb5ed77e03ac94c03f4b170a825c1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 09:28 UTC, Guoan-Tang commented
WorkItem: [Feature 15375](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15375): [DEVICES AND APPS][CLOUD PC] Add new entity cloudPcSharedUseServicePlan

2022-10-12 10:37 UTC, opbld34 commented
Learn Build status updates of commit _[1b9e034](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b9e0341e9666933835be4e75fc789df69f9e15d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210121034320808-18537/BuildReport?accessString=e6b2071c3130ade61e18a3d628d6b1b9e46a7354fecc6df0ef69f65912d332b5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 02:33 UTC, opbld33 commented
Learn Build status updates of commit _[be7007c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be7007c08245dee8d1e54f09f07231d3598b9626)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210130229538475-18537/BuildReport?accessString=03e943db6073ad6f4216f959abe6a5d811095f8c21e1eb83ae7b0cce8be5d6ad).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 03:00 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|`dedicated`|0|Defaultvalue.Indicatesthepolicyshouldusethededicated,peruserlicensesfortheprovisioningpolicywhenprovisioningCloudPCsforusers.|
@Guoan-Tang  Please update these definitions properly. They lack **punctuations** and white space after `,`

2022-10-28 01:16 UTC, AshleyYangSZ commented
Please add the roadmap link to this PR. Refer to https://www.intunewiki.com/wiki/CPC_Graph_Onboarding#Prepare_public_doc_PR

2022-11-09 06:14 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcprovisioningpolicy-update.md
@Guoan-Tang Could you read though the wiki aka.ms/ongraph to see if unkownFutureValue should be included in the description or not? Thanks a lot!

2022-11-09 06:17 UTC, AshleyYangSZ approved these changes

2022-12-06 13:21 UTC, Guoan-Tang commented on api-reference/beta/api/cloudpcprovisioningpolicy-update.md
![image](https://user-images.githubusercontent.com/66197601/205923538-10e10b91-1503-43b6-9fcd-48def5de5aa7.png)
yes, it should be

2022-12-06 13:44 UTC, opbld30 commented
Learn Build status updates of commit _[dc1979d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc1979dd76c361cbd75df610bc440e5940cc41b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/cloudpcshareduseserviceplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/cloudpcshareduseserviceplan-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcshareduseserviceplan-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-shareduseserviceplans?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcmanagementgroupassignmenttarget?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcshareduseserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/resources/cloudpcshareduseserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcshareduseserviceplan?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-18537) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/flw/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212061341485356-18537/BuildReport?accessString=ef1b9945d3ca2f6868171c73edcf4c470f82ee28beb98d43ce833f7f3f6f1998).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-15 02:51 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the `servicePlanId` property to the [cloudPcManagementGroupAssignmentTarget](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcManagementGro
In your changelog, the links are wrong. They shouldn't be like intune-....These links cannot be opened. Please refer to other links in changelog to fix yours.e.g., https://learn.microsoft.com/en-us/graph/api/resources/virtualEndpoint?view=graph-rest-beta

2022-12-15 02:53 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|provisioningType|[cloudPcProvisioningType](#cloudpcprovisioningtype-values)|Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. Possible values are dedicated and
Please remove extra definition: Possible values are dedicated and shared.

2022-12-15 02:54 UTC, RuiHou105 requested changes
@Guoan-Tang  Please help resolve comments, thanks

2022-12-15 03:36 UTC, AshleyYangSZ commented
@Guoan-Tang Sorry I forgot this. You need to update virtualEndpoint resource file as well to include List sharedUseServicePlans API to method table, and include sharedUseServicePlan to relationships table as well. https://learn.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta

2022-12-15 03:37 UTC, AshleyYangSZ requested changes
Please update virtualEndpoint resource file as well.

2023-01-03 03:11 UTC, Guoan-Tang commented
WorkItem: [15375](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15375): [DEVICES AND APPS][CLOUD PC] Add new entity cloudPcSharedUseServicePlan

2023-01-18 21:54 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcshareduseserviceplan.md
> +description: "Represents a shared-use service plan that can be used by up to three Cloud PCs."
For clarity, I have rephrased this sentence. Please, le me know if you don't agree with this change.

2023-01-18 21:54 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +| dedicated           | Indicates that a dedicated license is used for provisioning Cloud PCs. Default value. |
For clarity, I rephrased this description. Please, let me know if you don't agree with this change.

Original sentence: Indicates the policy should use the dedicated, per user licenses for the provisioning policy when provisioning Cloud PCs for users.

2023-01-18 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +| shared              | Indicates that a shared license is used for provisioning Cloud PCs.                   |
For clarity, I rephrased this description. Please, let me know if you don't agree with this change.

Original sentence: Indicates using the Shared use licenses for the provisioning policy when provisioning Cloud PCs forusers.

2023-01-18 21:55 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|provisioningType|[cloudPcProvisioningType](#cloudpcprovisioningtype-values)|Specifies the type of license used when provisioning Cloud PCs using this policy. By default, the license type is `dedicat
For clarity, I rephrased this description. Please, let me know if you don't agree with this change.

Original sentence: Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. Possible values are dedicated and shared. It will be dedicated by default if it's not specified when creating provisioningPolicy. The possible values are: `dedicated`, `shared`.

2023-01-18 21:55 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcprovisioningpolicy-update.md
> +|provisioningType|[cloudPcProvisioningType](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)|Specifies the type of license used when provisioning Cloud PCs using this policy.
For consistency and more clarity, please add this property to the JSON object in the request body.

2023-01-18 21:56 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the **sharedUseServicePlans** relationship to the [virtualEndpoint](https://learn.microsoft.com/en-us/graph/api/resources/virtualEndpoint?view=graph-rest-bet
This PR doesn't include this addition. Please, add this relationship to the virtualEndpoint resource topic.

2023-02-01 03:48 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcprovisioningpolicy-update.md
> +|provisioningType|[cloudPcProvisioningType](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)|Specifies the type of license used when provisioning Cloud PCs using this policy.
@Guoan-Tang  Please help resolve the comment

2023-02-03 03:04 UTC, Guoan-Tang commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +| dedicated           | Indicates that a dedicated license is used for provisioning Cloud PCs. Default value. |
good to me

2023-02-03 03:05 UTC, Guoan-Tang commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +| shared              | Indicates that a shared license is used for provisioning Cloud PCs.                   |
good to me

2023-02-03 03:05 UTC, Guoan-Tang commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|provisioningType|[cloudPcProvisioningType](#cloudpcprovisioningtype-values)|Specifies the type of license used when provisioning Cloud PCs using this policy. By default, the license type is `dedicat
good to me

2023-02-03 03:26 UTC, Guoan-Tang commented on api-reference/beta/api/cloudpcprovisioningpolicy-update.md
> +|provisioningType|[cloudPcProvisioningType](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)|Specifies the type of license used when provisioning Cloud PCs using this policy.
This property can not be changed once the entity is created. I have clarified it at each description.

2023-02-06 22:18 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcprovisioningpolicy-update.md
> +|provisioningType|[cloudPcProvisioningType](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)|Specifies the type of license used when provisioning Cloud PCs using this policy.
If this property can't be modified, then we don't need to list it here. You should only list here, the properties that can be update.

2023-02-06 22:58 UTC, JarbasHorst commented
@Lauragra, this PR is ready for final review.

2023-02-07 03:34 UTC, Lauragra approved these changes

2023-02-08 03:29 UTC, RuiHou105 approved these changes

2023-02-11 02:00 UTC, merged