Added CSS styling
microsoftgraph/microsoft-graph-docs pull request #18546
Opened 2022-09-20 01:27 UTC by AlexanderMars

2022-09-20 01:31 UTC, opbld30 commented
Docs Build status updates of commit _[8741339](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87413390207eb1900a2748e3f65ff8e16ae40bd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200127170047-18546/BuildReport?accessString=096a0b0f83a0aecec188797fe290a2675e50f57751f20cd6dd5d4a7a2251599d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 01:59 UTC, opbld31 commented
Docs Build status updates of commit _[4a01208](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a012086eaf95fee77641541a10c28870e7194e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/includes/loginPageLayoutConfiguration](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/includes/loginPageLayoutConfiguration) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200155030947-18546/BuildReport?accessString=20a6c65e134030a7d03e255c5aaad3d2641356aac03fb7d0acd2bbffcfa09bc0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 02:02 UTC, opbld33 commented
Docs Build status updates of commit _[a8c3c10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8c3c10aa7f0002a61b790c2ce6fd5c3c0f0a6f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/includes/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/includes/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/loginPageLayoutConfiguration](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200157361458-18546/BuildReport?accessString=a4198bc8afc4edb1443fbd27731802e2c229d21ac235869b70f2381f4d64e8a3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 02:04 UTC, opbld32 commented
Docs Build status updates of commit _[82f5364](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82f5364858b7f9433e402deb85280be39f7bef49)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-29d34c2f)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="53df00f725a7c0327200a214f8bc5838-29d34c2f"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200200527732-18546/BuildReport?accessString=57a5ba936be2cca0f2d0bf8fdccb9086568bfb19f4bf91b7284473cf77db2d17).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 02:07 UTC, opbld33 commented
Docs Build status updates of commit _[4169da8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4169da880f249ac6c2e5351980c0de526dcef1b6)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-ec4f62ad)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="53df00f725a7c0327200a214f8bc5838-ec4f62ad"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200202369924-18546/BuildReport?accessString=117fa3ffb34565017b247f2618a25d80ddf23f7bdad6c716a6888b06b34327af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 03:35 UTC, opbld31 commented
Docs Build status updates of commit _[2a97497](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a9749759cb01355ee5e29a3fc771b7c51b70d7d)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-408076cd)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="53df00f725a7c0327200a214f8bc5838-408076cd"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200332571195-18546/BuildReport?accessString=3e1339a89b613a13a565334cce97ede7c149d795134fec7723ec7d44af73badb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 03:37 UTC, opbld33 commented
Docs Build status updates of commit _[892a206](https://github.com/microsoftgraph/microsoft-graph-docs/commits/892a20619ac086809c12f3d507e9b93e6dbf504b)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-3c37be51)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="53df00f725a7c0327200a214f8bc5838-3c37be51"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200335353486-18546/BuildReport?accessString=88938b100168fc94842e4d55e29938d4f824c1eebc57621a8c891cb9e8badb1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 00:46 UTC, opbld30 commented
Docs Build status updates of commit _[21122a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21122a6a57675033d92033587ad6af843382b96d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 00:50 UTC, opbld31 commented
Docs Build status updates of commit _[7b1eb17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b1eb1706e184b20123b020964173ec04e9282cc)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-b1eb3cda)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="53df00f725a7c0327200a214f8bc5838-b1eb3cda"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210047363534-18546/BuildReport?accessString=4de5cc71a0bcd03b7e1d259674946a18b5453a10de9125eb7595e04da96f59bd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:12 UTC, opbld34 commented
Docs Build status updates of commit _[8afb6ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8afb6ec6d7ef1bdc53e3e238b71dbaa5c8d338f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-57b405dd)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="53df00f725a7c0327200a214f8bc5838-57b405dd"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 22, Column 24**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'layoutTemplateType.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210109085984-18546/BuildReport?accessString=bd30d3b365f5cfd81485ed52c90b8cc4a57ddbb7aab55caf55d0dd69b4704cff).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:24 UTC, opbld30 commented
Docs Build status updates of commit _[94599e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94599e7d4c32f7eb5a1f73965c0040e418adbc1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-18c51fc2)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-18c51fc2)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-18c51fc2"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'loginPageLayoutConfiguration resource type' is duplicated with other articles: 'beta/resources/layoutTemplateType.md(10,1), beta/resources/loginPageLayoutConfiguration.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 25, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-18c51fc2"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'loginPageLayoutConfiguration resource type' is duplicated with other articles: 'beta/resources/layoutTemplateType.md(10,1), beta/resources/loginPageLayoutConfiguration.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210121295830-18546/BuildReport?accessString=fdb82303ab1025b8b02558e92b84480ffc44015d100f4271db3b9848d07aebb1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:27 UTC, opbld33 commented
Docs Build status updates of commit _[191d269](https://github.com/microsoftgraph/microsoft-graph-docs/commits/191d26986b4daf55b84b714f3d8c1d0f9b8291ec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-6870149d)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-6870149d)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-6870149d"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'loginPageLayoutConfiguration resource type' is duplicated with other articles: 'beta/resources/layoutTemplateType.md(10,1), beta/resources/loginPageLayoutConfiguration.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 25, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-6870149d"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'loginPageLayoutConfiguration resource type' is duplicated with other articles: 'beta/resources/layoutTemplateType.md(10,1), beta/resources/loginPageLayoutConfiguration.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210124260156-18546/BuildReport?accessString=3a4052e8582cfc3426c3ffaf7542375c205c4225d1ef33a5c9f8585982db8ced).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:43 UTC, opbld34 commented
Docs Build status updates of commit _[0559de5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0559de5887f1cc76c7eb465eab753592671e8817)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-ea515a0e)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-ea515a0e)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-ea515a0e"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'loginPageLayoutConfiguration resource type' is duplicated with other articles: 'beta/resources/layoutTemplateType.md(10,1), beta/resources/loginPageLayoutConfiguration.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-ea515a0e"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'loginPageLayoutConfiguration resource type' is duplicated with other articles: 'beta/resources/layoutTemplateType.md(10,1), beta/resources/loginPageLayoutConfiguration.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210140241314-18546/BuildReport?accessString=4c1f293853532ae1c3053d51eba7d7a56181af37d03f77dc6e1ab1a4c28b205e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:46 UTC, opbld30 commented
Docs Build status updates of commit _[c5e28ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5e28ff1bc19d71c6c51e9fbb32e7f2478d13632)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-3ed91147)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-3ed91147)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-3ed91147"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-3ed91147"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210141079997-18546/BuildReport?accessString=df675ab9677019fddf990fb12002442c27e8708c4c95f364829de31f50907845).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:49 UTC, opbld31 commented
Docs Build status updates of commit _[b660121](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6601214ba98564f6ae92bbb3ffd633f20b0b916)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-be0b9b82)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-be0b9b82)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-be0b9b82"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-be0b9b82"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210143527288-18546/BuildReport?accessString=77ac72fe5087d2b1571cce5bbeb6b309396b49ce1b6f37f42d217630a15db4c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 01:55 UTC, opbld32 commented
Docs Build status updates of commit _[fc123d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc123d6801796f0b60e65dccdf318abe0a72e20d)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-d10ad49e)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-d10ad49e)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-d10ad49e"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-d10ad49e"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210152079294-18546/BuildReport?accessString=06a3d80c2ea4486336b7a219eec6966dabe6392254dbf98e679e9e2ffede1da4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 18:26 UTC, opbld34 commented
Docs Build status updates of commit _[97af7ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97af7edb30c51a959c2f930135631cb402250e85)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-64e1cc0b)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-64e1cc0b)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-64e1cc0b"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-64e1cc0b"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209211821378735-18546/BuildReport?accessString=c6bfdf29c82cc2d09dbfc0dab39009fb8f5035655ea4fb452fa62ad9b20bcde3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[b384d04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b384d04e8f31595de207f4bbcb779e3464985b06)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-3e49a366)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-3e49a366)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-3e49a366"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-3e49a366"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209211825480566-18546/BuildReport?accessString=4eb64872bdfda38bc546f7cdd9603747b47ee72e7691567f1614eb2c84f84127).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 18:47 UTC, opbld33 commented
Docs Build status updates of commit _[5d63f24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d63f2411f77078aa832225287ad52b56967b4c0)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-ea7b4d24)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-ea7b4d24)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-ea7b4d24"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-ea7b4d24"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209211842300271-18546/BuildReport?accessString=9b8f75406abcd490db0253e32be17783f064cc31a98a98d96c1a95ed8a84e147).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:13 UTC, opbld34 commented
Docs Build status updates of commit _[48846b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48846b1bcde7cbd49ad47a415cbef4b9b9965cd5)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-abb2e4fe)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-abb2e4fe)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-abb2e4fe"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-abb2e4fe"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221810256967-18546/BuildReport?accessString=8a64b2e2c3ae9bc57384b8380e4e72eb658be0bbb56238913cd96b9c6e80d7af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:25 UTC, opbld31 commented
Docs Build status updates of commit _[4e972cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e972cf9c91ff273ce7279a8a0e574528a932192)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-258fabd1)
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-258fabd1)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-258fabd1)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="07280cc683676b06b71713506b889387-258fabd1"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 61, Column 34**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageLayoutConfiguration.md'.`````

<a id="c4c7abf81e54495975bcac7bc1e00f7c-258fabd1"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-258fabd1"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221821267652-18546/BuildReport?accessString=185a8141cd63e7079a71459c5022e3bbb510b2e1c6f7af8b7b1cc0a9316352f0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:30 UTC, opbld31 commented
Docs Build status updates of commit _[e81b1ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e81b1ed34e2c6fb7f881efbdb2d75257f3d43fa8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-9beac201)
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-9beac201)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-9beac201)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="07280cc683676b06b71713506b889387-9beac201"></a>
### [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md)
 - **Line 61, Column 34**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'loginPageLayoutConfiguration.md'.`````

<a id="c4c7abf81e54495975bcac7bc1e00f7c-9beac201"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-9beac201"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221825038632-18546/BuildReport?accessString=0c1ee2b22f5dce27904d8e8fd5c039f13f4cf9d9d3e4538be448b502b030341d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:40 UTC, opbld32 commented
Docs Build status updates of commit _[d699a01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d699a019cb22e680355c66b761ab4e9ab913dd58)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-21500910)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-21500910)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-21500910"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-21500910"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221834389837-18546/BuildReport?accessString=00f5dfa7b0f35c01de3979e915bddec403525858b77870fa6b2ea3ba98327a5a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:44 UTC, opbld30 commented
Docs Build status updates of commit _[46217e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46217e4feaa45be5b6cd0d1b086e4a4fcb1e3286)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-968b697c)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-968b697c)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-968b697c"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-968b697c"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221837117323-18546/BuildReport?accessString=47cc59e140fa6728bc557eabc1dbc319652b4d7af81fbfda5af12a87d1e61d84).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 18:48 UTC, opbld32 commented
Docs Build status updates of commit _[22c189d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22c189df763ba58001a53cfe9b88175d31f4d29f)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-4b82cb6e)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-4b82cb6e)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-4b82cb6e"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-4b82cb6e"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221842547427-18546/BuildReport?accessString=5454f1b24776b36e1c3395ff7cf42e3318e16f5046c26cbfe9c1b3ed2cee8af6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 02:29 UTC, opbld32 commented
Docs Build status updates of commit _[6983c67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6983c6742a925615f9c2e24c18726bf767f11a99)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-5ca71002)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-5ca71002)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-5ca71002"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-5ca71002"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209230226218269-18546/BuildReport?accessString=c5a0f5bca766676168a1ef9af2ea3f954e7bbfeb9289de0a2004c37a286732b4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 22:37 UTC, opbld32 commented
Docs Build status updates of commit _[e2978e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2978e30577983a5024a47fbfba8fb454f0554c1)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-4f9f9691)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-4f9f9691)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-4f9f9691"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-4f9f9691"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209262234143712-18546/BuildReport?accessString=b57b3dd2737699fb34ac5b30d8ee92f4b26a60e69c360bfe45f483340b131e11).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 22:40 UTC, opbld30 commented
Docs Build status updates of commit _[b8cbe4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8cbe4d115a0bf638a89f7c9a7966bf2e50d457e)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-c812bf4c)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-c812bf4c)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-c812bf4c"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-c812bf4c"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209262236206181-18546/BuildReport?accessString=7b06a63931c1bbb5e5c37a8021f8f985340ab6e094c0622cd943d56363b8df96).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 22:43 UTC, opbld30 commented
Docs Build status updates of commit _[609dc5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/609dc5d6568c6952db11276a00996adf4cbdb52c)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-0d73b70b)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-0d73b70b)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-0d73b70b"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-0d73b70b"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209262237549236-18546/BuildReport?accessString=cf41dacc277784314e8ba685a2df007f6ab64794798ba81d0ed4eec5d018064e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 22:46 UTC, opbld30 commented
Docs Build status updates of commit _[0357438](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0357438ce27caa69a4ca5d64f892d945d6ab51d9)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-d48172f5)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-d48172f5)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-d48172f5"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-d48172f5"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209262240462032-18546/BuildReport?accessString=99a0145ae5e20f70cfbd3da07e31bb649c45628db129ab8035334b9fdcd5a8d3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 22:47 UTC, AlexanderMars commented
Added "headerLogo" and "headerLogoRelativeUrl" properties.

2022-09-26 22:50 UTC, opbld30 commented
Docs Build status updates of commit _[c5e082f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5e082f91067d5dd38119492a0d81bda38b2a059)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-98b07068)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-98b07068)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-98b07068"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-98b07068"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209262244414108-18546/BuildReport?accessString=828e8312c9518cd423ead2ab7a83de0d055b12cb5fa255b0d43010eed33ca0dd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 22:55 UTC, opbld34 commented
Docs Build status updates of commit _[b75849c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b75849c6da26369ac2401bc9e8ea755a4062b330)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-80f42ee0)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-80f42ee0)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-80f42ee0"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-80f42ee0"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209262247294902-18546/BuildReport?accessString=d053964ae1e2d42e6ff7e2bbbbe85376fc0b83de77380d8527f2e3e50013546e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-08 16:22 UTC, opbld33 commented
Learn Build status updates of commit _[45c9ea4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45c9ea423805dc42567ef7d10eb7761117763a43)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-92ab03f3)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-92ab03f3)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-92ab03f3"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-92ab03f3"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210081619245787-18546/BuildReport?accessString=d48d7f550ac16fc816f48e9de5e371618968ac448a15f0f116046a75f4c6d43c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 21:48 UTC, opbld32 commented
Learn Build status updates of commit _[0870c8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0870c8de67594aff2fe86910dd4340f7734fe784)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-bf593178)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-bf593178)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-bf593178"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-bf593178"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210122145029382-18546/BuildReport?accessString=c09b3cbc499e29a3f7bffacd4128fe19910e435e84b7bb8cf2acaac1fa7b90c1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 10:42 UTC, FaithOmbongi requested changes
Thank you, @AlexanderMars, for your work on this PR.

Two gaps:

1. The changelog. Please copy it from the schema PR.
2. Document the layoutTemplateType enumeration in the enums.md file

I've also left suggestions for fixes inline. Please apply those that should also be propagated to the child resources.

2022-10-14 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandingproperties.md
> +| customCSS | Stream | CSS styling that appears on the sign-in page. The allowed format is .css format only and not larger than 25KB. |
nit
Apso apply to the child resource docs
```suggestion
| customCSS | Stream | CSS styling that appears on the sign-in page. The allowed format is `.css` format only and not larger than 25 KB. |
```

2022-10-14 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandingproperties.md
>    "headerBackgroundColor": "String",
Also add the two other properties to the JSON representation
Also apply to the child resource docs

2022-10-14 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/loginPageLayoutConfiguration.md
> +description: "Contains details of the organization's branding."
```suggestion
description: "Contains details of the layout of the sign-in page for a tenant."
```

2022-10-14 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/loginPageLayoutConfiguration.md
> +Represents the various text strings that can be hidden on the sign-in page for a tenant.
I suggest the same description as in the metadata because this resource doesn't just expose hiding capabilities, but also layout options

2022-10-14 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/loginPageLayoutConfiguration.md
> +| layoutTemplateType | [layoutTemplateType](layoutTemplateType.md) | Represents the layout template to be displayed on the login page for a tenant. |
This is an enum, not a complex type
```suggestion
| layoutTemplateType | layoutTemplateType | Represents the layout template to be displayed on the login page for a tenant. |
```

2022-10-14 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/loginPageLayoutConfiguration.md
> +  "layoutTemplateType": "string",
nit
```suggestion
  "layoutTemplateType": "String",
```

2022-10-14 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/layoutTemplateType.md
> +---
Please delete the doc. layoutTemplateType is an enum, please add it to the beta/resources/enums.md doc instead.

2022-12-02 16:34 UTC, opbld34 commented
Learn Build status updates of commit _[5715e75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5715e7549896e07810fda42f7772b48e5f80d73a)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-64b41102)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-64b41102)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-64b41102"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-64b41102"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021631183697-18546/BuildReport?accessString=b9fb20dafb4977e2bdabfe96462341d11489a054bbbb5256c13ce14d273e478f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 16:37 UTC, opbld32 commented
Learn Build status updates of commit _[2eeca10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eeca1006421f0ab97b43fb49d1326445fc73e85)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-034147a5)
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-53df00f725a7c0327200a214f8bc5838-034147a5)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-034147a5"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

<a id="53df00f725a7c0327200a214f8bc5838-034147a5"></a>
### [api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginPageLayoutConfiguration.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021631390301-18546/BuildReport?accessString=b4f80d03648746da8d8a5b6e36b50fc1d040c2f9ce4ee14a074dd4cb223e436a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 16:41 UTC, opbld30 commented
Learn Build status updates of commit _[5b69c32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b69c326668456157ca7c6ea14e1b78e38eeb4a8)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-3a41fdbc)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-3a41fdbc"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021635342015-18546/BuildReport?accessString=11724ac140df8a2b6b7903e2b0f9e64f27a4cb598c6468eb577c6ae8246dd1ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 16:55 UTC, opbld31 commented
Learn Build status updates of commit _[78b8e31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78b8e3143959ebd840cb4788a541680efe595f74)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-2a8e850b)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-2a8e850b"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021652344297-18546/BuildReport?accessString=278acc69d98c0542c530bd9d1715012662975cbbac174210c33f18fca5877e0c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 16:55 UTC, AlexanderMars commented on api-reference/beta/resources/organizationalbrandingproperties.md
>    "headerBackgroundColor": "String",
done

2022-12-02 16:58 UTC, opbld32 commented
Learn Build status updates of commit _[39fb015](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39fb01598d080da8235e8c44ad67499997baf788)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-86fbb042)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-86fbb042"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021655421887-18546/BuildReport?accessString=ab43ed8266fce6cc8420c6459a0d2935c1a2dc7dd34451bd14a4ffd1f01fe93e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 16:59 UTC, AlexanderMars commented on api-reference/beta/resources/loginPageLayoutConfiguration.md
> +Represents the various text strings that can be hidden on the sign-in page for a tenant.
done

2022-12-02 17:02 UTC, opbld31 commented
Learn Build status updates of commit _[12160c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12160c51532ac4bd7939d4abc37cb82ee8a9d020)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-ceb39506)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-ceb39506"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021659328567-18546/BuildReport?accessString=4186fddeee5d0b52846af6cc43b50669ffb373c53cc756a4e418a6fffa31fdd2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 17:20 UTC, opbld33 commented
Learn Build status updates of commit _[b544fa7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b544fa705eba5823403f52fa2e90bf674c87e014)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-76ca4040)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-76ca4040"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021718055030-18546/BuildReport?accessString=b392ac2ac98a66d154c3a2fb4d1c4591684f4db701703306914202327e37e4d4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 17:25 UTC, opbld32 commented
Learn Build status updates of commit _[4c2e455](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c2e455f59a8f716d77a6fadffbbf1298afb289a)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/layouttemplatetype?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) | [Details](#user-content-c4c7abf81e54495975bcac7bc1e00f7c-2bd93ac2)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

<a id="c4c7abf81e54495975bcac7bc1e00f7c-2bd93ac2"></a>
### [api-reference/beta/resources/layoutTemplateType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/layoutTemplateType.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Contains details of the organization's branding.' is duplicated in 'beta/resources/layoutTemplateType.md(3,14)', 'beta/resources/loginpagetextvisibilitysettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021722415035-18546/BuildReport?accessString=7dd615a619e177a854a4bb6f67fadea94e8e342fa6c6461935db7b2f2632575d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 17:26 UTC, AlexanderMars commented on api-reference/beta/resources/layoutTemplateType.md
> +---
done

2022-12-02 17:28 UTC, opbld31 commented
Learn Build status updates of commit _[d0f9180](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0f9180f6bb5842b9cb3192740d1351d1526cc48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021725502926-18546/BuildReport?accessString=e0a798b226eb6afc8f2bb298789cdbaebfbb2dc8bf849efe032b7cc2cd0d0176).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 22:10 UTC, opbld31 commented
Learn Build status updates of commit _[e1261ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1261abc572da40be9d49945588f9b08c4251089)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212022208076751-18546/BuildReport?accessString=f6fe730a5aba2c134773ae0146845934fa88583c4ee7a10049d110c6a9e05efb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 22:17 UTC, opbld34 commented
Learn Build status updates of commit _[183103b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/183103b23ad2992b489b3907f684b043d5bcf251)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212022215400597-18546/BuildReport?accessString=3aeb9e7b6271e2b8b3e69cf6bf5c7e7d7756aeb68e4534775fb6ea9a688771bd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 22:24 UTC, AlexanderMars commented
@FaithOmbongi thanks a lot for all your comments. They are incorporated now. Changelog is added and the PR is ready for a second pass.

cc: @KuiGithui

2022-12-06 12:22 UTC, opbld33 commented
Learn Build status updates of commit _[267f92a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/267f92a746a4158b2a267258841aa86c782c1772)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212061219407622-18546/BuildReport?accessString=00ffd105c5033dd678a6c2c7eb6f49814e8a3b429f8934000f320042462ae72f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 14:57 UTC, opbld30 commented
Learn Build status updates of commit _[6c9e6b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c9e6b9ca16eeaae9c71f9bede809c568d4be030)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212061454404212-18546/BuildReport?accessString=410e5d1704326393c237e9c2bb1b80f5455775f083fee3d990b60347f53ca0fb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 02:43 UTC, opbld33 commented
Learn Build status updates of commit _[bd7dbdf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd7dbdf1862ddd9819d2525e654af21812cc2d85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/loginPageLayoutConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/loginPageLayoutConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/loginpagelayoutconfiguration?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-18546) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AlexanderMars-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212070240094294-18546/BuildReport?accessString=cb88879c67191abd4f4d2a9a7009429778e62761353ff9fc82581e4e4e8e7cb4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 02:48 UTC, merged