Adding Federation Related Notes to Associated Pages
microsoftgraph/microsoft-graph-docs pull request #18630
Opened 2022-09-25 05:17 UTC by evanypark

Adding federated chat related notes to associated API documentations:
- GetChat
- ListChatMessages
- UpdateChatMessage
- ListChats
- ListChatMembers

2022-09-25 05:20 UTC, opbld34 commented
Docs Build status updates of commit _[ea61586](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea615863389f55bc35644c5a678d12e5cd017507)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209250517220550-18630/BuildReport?accessString=deb73d2bc387046a3cf2ecdb9c24a640f703259ce0a121e82307a05842b3c881).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-25 05:53 UTC, RamjotSingh requested changes

2022-09-25 05:53 UTC, RamjotSingh commented on api-reference/beta/api/chat-get.md
> +Cross-tenant federation is not supported for this API. At least one chat member must be part of caller application tenant.
I think it is rather confusing to say we don't support federation then say that you can access. Instead for APIs where cross tenant calls do work, we should note that
`This API supports federation. To access chat (you can change APIs here) at least one member must be part of the calling tenant'.

2022-09-25 05:53 UTC, RamjotSingh commented on api-reference/v1.0/api/chat-list-messages.md
> +Federation is only supported in delegated context for this API. If request is made in application context, request will fail.
To list chat messages in application context, request must be made from tenant which owns the chat (represented by `tenantId` property on the chat).

2022-09-25 07:49 UTC, opbld32 commented
Docs Build status updates of commit _[732b4b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/732b4b061e4b36b9d1e87756c4a87632934d2aa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209250747068456-18630/BuildReport?accessString=5c27ae8edd99550386ebcec88bd7a95fd93e07860e20367d7c0860d7b0bb46c1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-05 21:51 UTC, opbld32 commented
Learn Build status updates of commit _[67a62c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67a62c4bcd1b3cc41505cf7768963fd9a547b4fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052149295881-18630/BuildReport?accessString=ccfddcd129bb8dec0d403653acaf8f26ee57d255a006faf4723336e7a99a55a3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 20:55 UTC, opbld32 commented
Learn Build status updates of commit _[c7e3330](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7e3330023c6ac9d0429bcc380a2dd2f6836b4df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210132045572942-18630/BuildReport?accessString=a12a85f811bf8dee73a6a344fdd11ab0b6e3c010c82a12a207cc28bf0bcecb8e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 21:39 UTC, opbld30 commented
Learn Build status updates of commit _[6dbfa79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6dbfa799daa4509d50b79319375efbdebef806df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210142136526130-18630/BuildReport?accessString=c641394e56b00df0a2e765d603ba93b05579cd779d28185968df1f0d56005ab3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 21:41 UTC, opbld33 commented
Learn Build status updates of commit _[5f622d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f622d884babbcc752a9d2b4bd93796f06594f06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210142138114108-18630/BuildReport?accessString=9eeb1c15e16fbde04e1b1b866e3a67500d870cd9a9ec006369bf035272a4f3e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 00:52 UTC, Lauragra commented on api-reference/beta/api/channel-list.md
> +This method supports federation. Any shared channel that the request initiator tenant is part of will be included in the response.
Does the word "tenant" belong here? Do we mean that any channels the request initiator is part of, or do we mean any channels that are in the tenant? Please clarify.

2022-10-15 00:56 UTC, opbld30 commented
Learn Build status updates of commit _[b4e91be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4e91befbd90644dde2ce741a4614c5f4787258a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150053476929-18630/BuildReport?accessString=27fd7f3b059d9c56f33254affcf8ad2956aaac7ca950d807bbf39c453813d1b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 01:09 UTC, opbld31 commented
Learn Build status updates of commit _[3c6172a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c6172a17a3ecaccdc3c3e9cbba35b95e8387a88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150101079685-18630/BuildReport?accessString=94e85617b1802c3e4cf74c2f10c9e0996e75afb3947c764291b9ca22755fbc41).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 01:12 UTC, opbld33 commented
Learn Build status updates of commit _[c324349](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c324349dd1846af792ddbbcf2dc3c4a4bbdd2f42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150102164207-18630/BuildReport?accessString=c70292f5d196c98de6a39f9e65f557cc24c5602564229c071508327f4d5aae8b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 01:18 UTC, opbld32 commented
Learn Build status updates of commit _[0a4288a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a4288a705710d20b624a6a65c6a8634c7bf3903)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150115428702-18630/BuildReport?accessString=fecdfaa86ae0d43a2c3a7345cf5a7fc0f83be75e37d8759956421c7dc8286714).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 01:23 UTC, opbld30 commented
Learn Build status updates of commit _[acf3f40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acf3f409ae3e5e13895b856b9eccddd8f77c926d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150120259389-18630/BuildReport?accessString=092578851e2fcbf724d28e85cd20d7059412ea7d13f96d802fbc37dfa99cd60c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 01:26 UTC, Lauragra commented on api-reference/v1.0/api/channel-list.md
> +This method supports federation. Any shared channel that the request initiator tenant belongs to will be included in the response.
Should we remove the word "tenant" here?

2022-10-15 01:26 UTC, opbld30 commented
Learn Build status updates of commit _[7dd7299](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dd72997e70b40ddedbfeffda7037cb78b3ae202)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150121152665-18630/BuildReport?accessString=9f8ba80738432032d5288af34eca3f5446fc81c34e03e0ccaf1577b37e2e92e5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 01:31 UTC, Lauragra commented on api-reference/v1.0/api/chat-list.md
> +## Federation
Please do not add any custom H2s to the API topics because they follow a specific structure. Can this be added to the summary section where we mention federation support?

2022-10-15 01:31 UTC, opbld31 commented
Learn Build status updates of commit _[bea16b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bea16b9d58fa32667adb1bbe762f1a0650746bff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150127242827-18630/BuildReport?accessString=28ba130ad2276e482457aa85c8810576a5e16c110e73d25f37ddb2b288d09fb0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 01:32 UTC, Lauragra commented on api-reference/v1.0/api/chat-list.md
> +Cross-tenant federation is not supported for this API. Targetted user must be part of caller application tenant.
I think this is saying the same thing as the text added in the summary, right? So do you want to just explicitly mention that cross-tenant federation is not supported? We don't seem to mention that in the other API topics.

2022-10-15 01:33 UTC, Lauragra commented on api-reference/v1.0/api/chat-list.md
> +> **Note**: \* This scenario is only supported for the following call: `GET /users/{user-id | user-principal-name}/chats`
Not sure what scenario you're referring to here, unless it's cross-tenant federation, but we've said that that is not supported. Please clarify.

2022-10-15 01:34 UTC, opbld33 commented
Learn Build status updates of commit _[30ed92b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30ed92b5945adebbff6ad7a74af8fb0132d73dd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210150130554515-18630/BuildReport?accessString=8be0b0652f07edb2274a006da9423b58bb880cdee7defc2a696889e410c3dfb7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-16 03:19 UTC, evanypark commented on api-reference/v1.0/api/chat-list.md
> +> **Note**: \* This scenario is only supported for the following call: `GET /users/{user-id | user-principal-name}/chats`
I've made mistake to remove H2 section while moving/rephrasing it to summary section. will remove

2022-10-17 01:37 UTC, evanypark commented on api-reference/v1.0/api/chat-list.md
> +Cross-tenant federation is not supported for this API. Targetted user must be part of caller application tenant.
Removed

2022-10-17 01:44 UTC, opbld34 commented
Learn Build status updates of commit _[b84963e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b84963ea1baa008c64c0912d73ae3bd59752aeea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210170142230469-18630/BuildReport?accessString=895e9ebad8c10fb5fe76990b71052ec31a6e462a538bd9b2a78d65bc8ce437a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 01:49 UTC, evanypark commented on api-reference/v1.0/api/channel-list.md
> +This method supports federation. Any shared channel that the request initiator tenant belongs to will be included in the response.
"tenant" removed

2022-10-17 01:49 UTC, evanypark commented on api-reference/beta/api/channel-list.md
> +This method supports federation. Any shared channel that the request initiator tenant is part of will be included in the response.
"tenant" removed

2022-10-17 01:58 UTC, opbld31 commented
Learn Build status updates of commit _[46eb0aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46eb0aa3446a73e8b1b07c632dcefa80eb1881c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-18630) (graph-rest-beta) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-09-24-federation-support-update/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-18630) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210170155412379-18630/BuildReport?accessString=fbd45ff7174437587f64ee7d7b1e487978766ff534c667e3a829f3e73f850f75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 16:25 UTC, Lauragra approved these changes

2022-10-18 03:30 UTC, merged