Chentong xiang support collapse
microsoftgraph/microsoft-graph-docs pull request #18706
Opened 2022-09-30 11:43 UTC by Chentong-Xiang

2022-09-30 11:45 UTC, opbld32 commented
Learn Build status updates of commit _[f10b2e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f10b2e78cf30c139ac264146365507bb5b1f0618)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/collapseproperty.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) | [Details](#user-content-809f5aa08dbd30d1e94c278c60c170a6-5226708d)
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/collapseSpec.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseSpec.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapsespec?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/v1.0/resources/collapseSpec](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/collapseSpec) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/search-concept-xrank.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-xrank.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-xrank?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

<a id="809f5aa08dbd30d1e94c278c60c170a6-5226708d"></a>
### [api-reference/v1.0/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/collapseproperty.md)
 - **Line 20, Column 11**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'collapseSpec.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209301143149719-18706/BuildReport?accessString=122f65644a20776336d3ac121f3ed7f0fc1fd354ebbf65c41855c883e75f9b27).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-01 01:34 UTC, Lauragra commented
@Chentong-Xiang , FYI, we asked that PRs that are targeting Ignite be opened and set to ready for content review by early September. Because this PR was opened past the requested date, we can't guarantee that it will be published in time for Ignite.

2022-10-02 08:05 UTC, opbld34 commented
Learn Build status updates of commit _[3b0fc52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b0fc52637f41bf5638fc277139ac58d60edba87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/collapseSpec.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseSpec.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapsespec?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/v1.0/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/collapseSpec.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/collapseSpec.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapsespec?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210020802437715-18706/BuildReport?accessString=4f9b762f104c76df004e2369cd2bfaf02ab3738438ed02c2dc5d9740065afdcf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 02:37 UTC, opbld34 commented
Learn Build status updates of commit _[ab44e96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab44e96a1d5b00dde542953497cdcc64bb4dcf3b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-700f74d5)

<a id="700f74d5"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit ab44e96a1d5b00dde542953497cdcc64bb4dcf3b in branch Chentong-Xiang-SupportCollapse of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit d721f5fd0a1ec610dda4b16c52f80a22f164ce3d). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080236364120-18706/BuildReport?accessString=15b4bf60f3c085c0c5378211044a358c702c67b3d4609d908f22acac714b80a1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 05:20 UTC, opbld33 commented
Learn Build status updates of commit _[e2c01bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2c01bcc09a1fd53b056f3f563c25f7dffb84a91)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) | [Details](#user-content-8c4a1282820c7bbefcdb68e839f88195-ca719174)
[concepts/search-concept-xrank.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-xrank.md) | :bulb:Suggestion |n/a (file deleted or renamed) | [Details](#user-content-8ae0ba497c286f9890319a0ec44ce6e6-ca719174)
[api-reference/beta/resources/collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapse?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/collapseOption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseOption.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseoption?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

<a id="8c4a1282820c7bbefcdb68e839f88195-ca719174"></a>
### [api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md)
 - **Line 119, Column 166**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'collapseProperty.md'.`````

<a id="8ae0ba497c286f9890319a0ec44ce6e6-ca719174"></a>
### [concepts/search-concept-xrank.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-xrank.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.learn.microsoft.com/en-us/help/platform/validation-ref/file-not-redirected?branch=main)]** `````File concepts/search-concept-xrank.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080518116492-18706/BuildReport?accessString=d0cf7fb6faa38a69b7e90c9064cf24b1d7c239b57922490846235743fe706fcc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 05:38 UTC, opbld30 commented
Learn Build status updates of commit _[5eaf2ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5eaf2ead5b5db855ab2ed946451cd3ff1b6e034b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) | [Details](#user-content-8c4a1282820c7bbefcdb68e839f88195-83242162)
[concepts/search-concept-xrank.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-xrank.md) | :bulb:Suggestion |n/a (file deleted or renamed) | [Details](#user-content-8ae0ba497c286f9890319a0ec44ce6e6-83242162)
[api-reference/beta/resources/collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapse?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/collapseOption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseOption.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseoption?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-concept-xrank.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/v1.0/resources/search-concept-xrank.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-concept-xrank?view=graph-rest-1.0&branch=pr-en-us-18706) (>= graph-rest-1.0) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

<a id="8c4a1282820c7bbefcdb68e839f88195-83242162"></a>
### [api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md)
 - **Line 119, Column 166**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'collapseProperty.md'.`````

<a id="8ae0ba497c286f9890319a0ec44ce6e6-83242162"></a>
### [concepts/search-concept-xrank.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-xrank.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.learn.microsoft.com/en-us/help/platform/validation-ref/file-not-redirected?branch=main)]** `````File concepts/search-concept-xrank.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080536080200-18706/BuildReport?accessString=6eb157c7091df2fe321aa16050b63d954287214bc5d83d2eddac5b73233d42e1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 05:55 UTC, opbld33 commented
Learn Build status updates of commit _[1fe6896](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fe6896964bcc43bac34d97cbd8638be8eb87915)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) | [Details](#user-content-8c4a1282820c7bbefcdb68e839f88195-5f66fc63)
[api-reference/beta/resources/collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapse?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/collapseOption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseOption.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseoption?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

<a id="8c4a1282820c7bbefcdb68e839f88195-5f66fc63"></a>
### [api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md)
 - **Line 119, Column 166**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'collapseProperty.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080553082444-18706/BuildReport?accessString=ce094626971fe79c48d35ee5b560601bc23fec1376018eea075eb90bdab5d52a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 07:38 UTC, opbld30 commented
Learn Build status updates of commit _[5e096c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e096c26f54d0cfe6c0af090a4ead689741678a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapse?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/collapseOption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseOption.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseoption?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080736105552-18706/BuildReport?accessString=6ece3f37e10a26c646132c27f886db023b9fd35ab28424e285bde9216b8b9ee1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 12:47 UTC, isvargasmsft commented on api-reference/beta/resources/collapse.md
> +# collapse resource type
This element is defined as a property of searchRequest complex type in the CSDL, not as a resource on its own. Would you be so kind to clarify or update this PR accordingly, please?

2022-10-10 12:47 UTC, isvargasmsft commented on api-reference/beta/resources/collapseOption.md
> +---
Missing in this PR: Changelog entries for both the new property and the new complex type.

2022-10-10 19:43 UTC, isvargasmsft requested changes
Hello @Chentong-Xiang, 

Thank you very much for your work in this PR. 

Please make sure this PR is aligned with the definitions in the CSDL PR.

Feel free to ping me on the side if you have questions.

Kind regards, 

Isaac

2022-10-20 11:45 UTC, opbld33 commented
Learn Build status updates of commit _[c6a9430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6a9430d01e60bb6ccf1631970f68248e4bbb288)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseProperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseProperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210201142549650-18706/BuildReport?accessString=5ec455ca6b77a0cfdc30ee93a4cd775df6a6b7161d502bf87a6ffb74bf74faae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 12:40 UTC, opbld30 commented
Learn Build status updates of commit _[f40e4ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f40e4ff78d64ec86852e16df39dfdc151521c99e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseProperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseProperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210201237175320-18706/BuildReport?accessString=febe1761d3604388de8d0d7587ec4dbeca3387cbb1b7e921d0f2fd4b3506823c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 09:29 UTC, opbld34 commented
Learn Build status updates of commit _[55aad2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55aad2f4e971f9edba3a3d5b12b40582369cf190)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-05047035)

<a id="05047035"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 55aad2f4e971f9edba3a3d5b12b40582369cf190 in branch Chentong-Xiang-SupportCollapse of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit cc1c703bbaf6a7720b1c959b54cfd5e2e8fe9bac). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210210928395011-18706/BuildReport?accessString=0a864009bafb13a27c88e1e6df0368f4186a672a2ae7664f66eb43234ca8e7bc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 09:14 UTC, opbld34 commented
Learn Build status updates of commit _[2feb4f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2feb4f77e68fd3fed00745616dd190aef46013ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseProperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseProperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210240911598024-18706/BuildReport?accessString=b472bb12462391d230502a81fb8a79e72da019cc9b7c97e730dcab5ed7add6e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 15:44 UTC, opbld33 commented
Learn Build status updates of commit _[926b88c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/926b88c4be5e5cb8d6d4075c0744185309b58588)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210251542294820-18706/BuildReport?accessString=9deaf4f0f88dba7a5e1c20881ecb359cd490fea0201c45dfb54c707cb2e8f5bc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 15:51 UTC, isvargasmsft commented on api-reference/beta/resources/searchrequest.md
> +|collapseProperties|[collapseProperty](collapseProperty.md) collection|Contains the ordered collection of fields and limit to collapse results. Optional.|
```suggestion
|collapseProperties|[collapseProperty](collapseproperty.md) collection|Contains the ordered collection of fields and limit to collapse results. Optional.|
```

2022-10-25 15:53 UTC, isvargasmsft commented on concepts/search-concept-collapse.md
> +#### Request
Please add an H4 Response section to each example.

2022-10-25 15:55 UTC, opbld33 commented
Learn Build status updates of commit _[5585dfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5585dfa5cb361a4c7dbfdd2ad12430229eb21e4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210251542467282-18706/BuildReport?accessString=4d6639628698b1047d4670f57c862e833971e9d42dcd8beb9204edc99da6ef5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 15:57 UTC, opbld34 commented
Learn Build status updates of commit _[6eff05a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6eff05af90cf85ec9881397fd8d6ed98399bd6a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210251551464061-18706/BuildReport?accessString=da6921892b0d1004a92a9cbf2873dab3e65119f84e458786df7bedd8e72c6a3d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 06:10 UTC, njerigrevious requested changes
@Chentong-Xiang - please update and resubmit before handoff to content review team. Thanks!

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +- The **collapseProperties** property is not supported for the following resources: **message**,**chatMessage**, **event**, **person**, or **externalItem**.
The **collapseProperties** property is not supported for the following resources: **message**,**chatMessage**, **event**, **person**, **externalItem**, **bookmark**, **acronym**.

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +- The **collapseProperties** property is only supported for sortable/refinable property.
Please confirm that we don't support for retrievable or queryable.

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +### Example: Compound Collapse
Update to "Multi-level Collapse"

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +#### Request
@isvargasmsft the collapse property only affects the presence and number of results, not the response schema. the example tables provided easily illustrate what's happening here since this feature is quite complex in how it works. Adding full response bodies would severely clutter the documentation and make it hard for customers to read - see this documentation that customers find helpful that explains the exact same concepts using tables: https://learn.microsoft.com/en-us/sharepoint/dev/general-development/customizing-search-results-in-sharepoint?redirectedfrom=MSDN#collapse-similar-search-results-using-the-collapsespecification-property

That being said, can we just provide request bodies and use tables instead of response bodies? or is there a requirement on this? Please advise - thanks!

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +First, group the items based on **title** and show the top two (hence "limit": 3) for each group. Then, for each **title**, show a corresponding item of **createdBy** (hence second level "limit": 1).
Explain why each table row is included/excluded and how that relates to ranking.

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +First, group the items based on both **title** and **createdBy**. Then, show each combination within the limit size 2 (hence "limit": 2). This should return the following results.
Explain why each table row is included/excluded and how that relates to ranking.

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +Group the items based on **title** and show the top three (hence "limit": 3) for each group. This should return the following results.
Explain why each table row is included/excluded and how that relates to ranking.

2022-10-26 06:10 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +|**Basic Collapse**|Collapse by any single sortable/refinable property.|"collapseProperties":[{"fields":["title"],"limit":3}]|
Include details on max size for number of fields and limit integer.

2022-10-26 06:10 UTC, njerigrevious commented on api-reference/beta/resources/search-api-overview.md
> +The collapseProperties property takes a collection of collapseProperty that can contain multiple fields and limit size, which evaluated together specify a set of criteria used for collapsing. And col
Rephrase to "The collapseProperties property contains a set of criteria, fields and limit size, which is used for collapsing results in a response body. Using collapseProperties only impacts the recall but not ranking/sorting."

2022-10-26 06:10 UTC, njerigrevious commented on api-reference/beta/resources/search-api-overview.md
> +Note that collapsing results is currently only supported on the following SharePoint and OneDrive types: [driveItem](driveitem.md), [listItem](listitem.md), [drive](drive.md), [list](list.md), [site]
Add a link to the below limitations section here too so customers know what it is not supported for.

2022-10-26 14:54 UTC, Chentong-Xiang commented on api-reference/beta/resources/search-api-overview.md
> +Note that collapsing results is currently only supported on the following SharePoint and OneDrive types: [driveItem](driveitem.md), [listItem](listitem.md), [drive](drive.md), [list](list.md), [site]
In overview page, I think we should provide a brief summary of feature, and customers can find more information from link in line 127. And if we add a same link here, would it be duplicate?

2022-10-27 15:54 UTC, Chentong-Xiang commented on concepts/search-concept-collapse.md
> +- The **collapseProperties** property is only supported for sortable/refinable property.
For collapse design docs that I could find, they all stress on collapsing has to be supported for sortable/refinable property, but do not mention retrievable, queryable or searchable properties. So I think we can say that it's only supported for sortable/refinable properties and push to the public.
BTW, I've started a thread to ask for it.

2022-10-27 16:00 UTC, opbld32 commented
Learn Build status updates of commit _[534c41a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/534c41a5c3cd5deae8f06a3ed47ae16e81f1a7d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271557414875-18706/BuildReport?accessString=a9bb98058b98ae6bfe8c4d56b51a26656fb9fd21230486c3a9468145fb6f8fe0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 16:13 UTC, opbld30 commented
Learn Build status updates of commit _[983ec93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/983ec93e75671bb99e6de14bdeffc2b96799a757)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271611370273-18706/BuildReport?accessString=7455ae7e02a08a218fc49556f0151a4d66369ab954950621cc0be8a406676d02).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 23:12 UTC, njerigrevious requested changes
Please fix per the requested changes - thank you!

2022-10-27 23:12 UTC, njerigrevious commented on concepts/search-concept-collapse.md
> +First, group the items based on **title** and show the top three (hence "limit": 3) for each group. Then, for each **title**, show a corresponding item of **createdBy** (hence second level "limit": 1
replace whole paragraph with "In below table, the ranking is still maintained, but we collapse first on title and then do a second collapse on createdBy. For the first level collapse on title with a limit of 3, this results in keeping the first 3 rows excluding rows 4 and 5 and keeping the last 3 rows as is. And then for the second level collapse with a limit of 1, we don't need to change the first 3 rows we kept because each has a unique createdBy value, but we do need to exclude row 8 because James is listed again as createdBy and we only need unique values for that property.

2022-10-28 04:24 UTC, opbld30 commented
Learn Build status updates of commit _[0ced182](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ced18286a2675b43fac2bc28335186bdc980b2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210280422235921-18706/BuildReport?accessString=a39b34def01184322d8fd5e1ef6fa6b42092247d770c4ab970b73051278320d5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 04:30 UTC, opbld31 commented
Learn Build status updates of commit _[61e5375](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61e537568b7ae1182f8d5f66288454d02d1a9bec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210280427050860-18706/BuildReport?accessString=5fe8908d434d0e2d5f90513f550248460bef5732947032812e1911ef54b50777).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 16:45 UTC, isvargasmsft commented on changelog/Microsoft.MicrosoftSearch.json
> +          "Description": "Added the `collapseProperties` property to the [searchRequest](https://docs.microsoft.com/en-us/graph/api/resources/searchRequest?view=graph-rest-beta) resource.",
```suggestion
          "Description": "Added the **collapseProperties** property to the [searchRequest](https://learn.microsoft.com/en-us/graph/api/resources/searchRequest?view=graph-rest-beta) resource.",
```

2022-10-31 16:46 UTC, isvargasmsft commented on api-reference/beta/resources/search-api-overview.md
> +The [query](../api/search-query.md) method lets you customize the collapse property by specifying the **collapseProperties** on the `requests` parameter, which is collection of [collapseProperty](col
```suggestion
The [query](../api/search-query.md) method lets you customize the collapse property by specifying the **collapseProperties** on the `requests` parameter, which is collection of [collapseProperty](collapseproperty.md). This allows you to specify a set of one or more collapse property.
```

2022-10-31 16:48 UTC, isvargasmsft commented on concepts/search-concept-collapse.md
> +| :----: | :----: | :----: | :----: |
```suggestion
## Examples of using collapseProperties
The following table shows a sample list in SharePoint. The next set of examples use this list to show how the collapseProperties property works.

| Title | Created By | Subject | Rank |
| :----: | :----: | :----: | :----: |
```

2022-10-31 16:48 UTC, opbld30 commented
Learn Build status updates of commit _[02c34bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02c34bd7891d7aedb086e7d1f73bd55b31e45da1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210311645302803-18706/BuildReport?accessString=488821f344de283abd20c92de55fa04d3c744cd3a4458f0a21acdaad0bc5ccdd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 16:50 UTC, opbld31 commented
Learn Build status updates of commit _[8469fcb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8469fcbb1b0134760d2ed5e41eaf32dcdeddc2ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210311646462582-18706/BuildReport?accessString=53e8dc0518e52acc062523db094bd44f5bd40d5bb4d283ac78d5c5297f3a0421).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 16:55 UTC, isvargasmsft commented on concepts/search-concept-collapse.md
> +|Note|Andy|Poetry|1|
```suggestion
Group the items based on **title** and show the top three (hence "limit": 3) for each group. As you can see in the below table, the ranking is maintained, and the top three rows and last 3 rows are kept but rows 4 and 5 are excluded because the collapseProperties limit is 3.

| Title | Created By | Subject | Rank |
| :----: | :----: | :----: | :----: |
|Note|Andy|Poetry|1|
```

2022-10-31 16:57 UTC, opbld31 commented
Learn Build status updates of commit _[ccd02ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccd02ba7ed4582f0a71fbcc2cdc1b8022517d57c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210311655178266-18706/BuildReport?accessString=28005801d268dc6dc3e3b43b34af24fdb9902b59105976c63d94c19fd4274358).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 17:00 UTC, opbld31 commented
Learn Build status updates of commit _[deb445b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/deb445b7ac2e1b468a00eb1f57c14004218febe4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210311656199042-18706/BuildReport?accessString=4cb8db870cb2d6053b842e22f7b57c27487165a50afd239de0ed8080547fd91b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 17:08 UTC, opbld34 commented
Learn Build status updates of commit _[8667cc4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8667cc4202b6993ce76a51052f5e06854c664dc9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210311705448484-18706/BuildReport?accessString=24cc6dbd94a7406079ce3ecf00bd82712f0f547559bfa81d741d9270ccab5202).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 17:34 UTC, isvargasmsft commented on changelog/Microsoft.MicrosoftSearch.json
> +        {
```suggestion
          "ChangedApiName": "collapseProperty",
          "ChangeType": "Addition",
          "Description": "Added the [collapseProperty](https://learn.microsoft.com/en-us/graph/api/resources/collapseProperty?view=graph-rest-beta) resource type.",
          "Target": "collapseProperty"
        },
        {
```

2022-10-31 17:37 UTC, opbld34 commented
Learn Build status updates of commit _[7b03c1f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b03c1f14360406c9e0a9723844145cb73eb0610)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210311734508463-18706/BuildReport?accessString=f236ee6fcd9c5f654b45d80d094caee32c7bb743e8b702a3c620aa4731c9ee21).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 17:38 UTC, isvargasmsft approved these changes

2022-11-01 02:08 UTC, opbld34 commented
Learn Build status updates of commit _[1778eb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1778eb1f59739a89c6140838f7687cc3a544b6e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211010205389895-18706/BuildReport?accessString=d6ac97cbfd3205380e57593274f2dec85ea8edb331a77ea6fc8a16588bc81a5a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-01 02:11 UTC, Lauragra commented on api-reference/beta/resources/search-api-overview.md
> +The properties on which the collapse clause are applied need to be sortable/refinable in the SharePoint [search schema](/sharepoint/manage-search-schema). If each limit size of property specified in
Can you please clarify the second sentence here? I'm not sure what you're conveying, specifically the phrase "is not satisfied with decreased by level". Is a word missing?

2022-11-01 02:11 UTC, opbld33 commented
Learn Build status updates of commit _[696ca5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/696ca5b333f83157401cc17ccf74220897bf45f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211010209313440-18706/BuildReport?accessString=03ba9baa1219f40bc3f87a12470aaf06ef5194fe6a23db08d30efe5f2b285345).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-01 05:25 UTC, opbld34 commented
Learn Build status updates of commit _[65fc82f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65fc82f36701fa20c8a0076322bbde6767a7bdba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/collapseproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/collapseproperty.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/collapseproperty?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-18706) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-collapse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/search-concept-collapse.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chentong-Xiang-SupportCollapse/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-collapse?branch=pr-en-us-18706) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211010523035066-18706/BuildReport?accessString=11d9a025e93c8db0c2250601cf8d5b55f8d5c430c2dd5ef70204eee7495ff2d3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-02 01:41 UTC, merged