GA chat message preview, chat viewpoint, hide/unhide chat APIs, mark chat as read/unread APIs
microsoftgraph/microsoft-graph-docs pull request #18721
Opened 2022-10-03 16:37 UTC by jessiechan27

2022-10-03 16:40 UTC, opbld30 commented
Learn Build status updates of commit _[8fcedac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fcedac97d98362971ea1d2e91f6943b7e4628e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210031637596983-18721/BuildReport?accessString=fbf3394d80f66b827549919c6dcc5b54434bc9804e70644e22c21053e856e867).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 18:18 UTC, opbld34 commented
Learn Build status updates of commit _[0d73bdd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d73bdd289c3fd06b730a7ab4577aa2f5f41ba6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210031814236270-18721/BuildReport?accessString=ada593e17e3ec197923d72def60959b9fa304c18e32ca3fc047437e50067d13b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 18:34 UTC, opbld31 commented
Learn Build status updates of commit _[c3cb810](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3cb8106c5b2c56c51487633e33af6dc6f33535f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210031831523602-18721/BuildReport?accessString=d6f5e327d76927291500c088789f83ba7df354454966e66e112e70d63ecad0ee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 10:04 UTC, opbld32 commented
Learn Build status updates of commit _[8e5d20e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e5d20e43ed0be0dff1cfc4a0178afed501eff2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051001521599-18721/BuildReport?accessString=31677d62ea0f000e6ade01446793e943045dbaa2fd4efae2875adb617568be8f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 10:17 UTC, opbld34 commented
Learn Build status updates of commit _[7ad0e80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ad0e80f11b6720cf02113006b43e13057be1baa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051014410741-18721/BuildReport?accessString=5811af248700a284b4471f23e92eb5e9969ec854ad2003f5cce8d1c235d2b467).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 14:16 UTC, isvargasmsft commented on api-reference/v1.0/api/chat-markchatunreadforuser.md
> +  },
```suggestion
    "id" : "d864e79f-a516-4d0f-9fee-0eeb4d61fdc2",
    "tenantId": "2a690434-97d9-4eed-83a6-f5f13600199a"
  },
```

2022-10-05 14:38 UTC, opbld32 commented
Learn Build status updates of commit _[45bfd4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45bfd4dc63f3083ea20b815da5f80ef0a045e720)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051436113169-18721/BuildReport?accessString=880e928b52ff866ad8b2f1af3fef7bfbca2da129eaca2425042b3e9b1e43ef8c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 18:05 UTC, opbld34 commented
Learn Build status updates of commit _[85cf51d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85cf51d717be59eb2f4b87ba6f333cd097800891)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051754557070-18721/BuildReport?accessString=a8861c8c188b18dc883abf5301ed3cba12bd2ed92e161245804db1fb7937265b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 20:45 UTC, opbld33 commented
Learn Build status updates of commit _[32e59d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32e59d9744c1202b93353408145efb398e602c3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052043481374-18721/BuildReport?accessString=06d53a5a6a88478adf1cd5e30db22b0605c0cd328154b99b8571ba4625b2fd41).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 22:04 UTC, opbld30 commented
Learn Build status updates of commit _[496c94e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/496c94e81efde64f71f0a2ced071b3b5c8ea1c9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052202114767-18721/BuildReport?accessString=8cefe40354360e0bab9ee2f3baa01ba22cc288edea653cdc5920e22dc6561323).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 22:06 UTC, opbld30 commented
Learn Build status updates of commit _[eaaf001](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaaf001548835c726b965a73fa1215ec77065e5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052204195132-18721/BuildReport?accessString=b61bf58419b1bd82fbb759444b386bdcdb08bcf98514d72a7138d03f07a60d12).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 22:11 UTC, RamjotSingh approved these changes

2022-10-05 22:11 UTC, RamjotSingh commented on api-reference/v1.0/api/chat-get.md
>      "tenantId": "2432b57b-0abd-43db-aa7b-16eadd115d35",
Add example of expanding lastMessagePreview

2022-10-05 22:28 UTC, opbld34 commented
Learn Build status updates of commit _[586bdad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/586bdada9e259d0f2d2657bb9434c4ef5c2a46c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052226236902-18721/BuildReport?accessString=518fe99f08a1359fcc68dbc3ee2239054ea7ac8f10c513fd93bb16afda5ac2de).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 14:37 UTC, isvargasmsft commented on api-reference/beta/api/chat-get.md
> +```msgraph-interactive
```suggestion
```http
```

2022-10-06 14:41 UTC, opbld31 commented
Learn Build status updates of commit _[d6cb2a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6cb2a3ef91604f48c8b5ab7527edca5564d8fa8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210061439114184-18721/BuildReport?accessString=2d4cb4da49560946e31cf19a3a383eea0ee652fd898e7566416ddc5edf2c1747).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 14:57 UTC, opbld32 commented
Learn Build status updates of commit _[f878f23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f878f23d16b99558006affa49b2d87d8792cc994)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210061455104160-18721/BuildReport?accessString=7fa7813239fe1fe4b1a5d4bfe3446a9700180ea1c81738518e3f62509b2c5f07).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 15:07 UTC, isvargasmsft commented on api-reference/v1.0/api/chat-get.md
> +```msgraph-interactive
```suggestion
```http
```

2022-10-06 15:19 UTC, isvargasmsft commented on api-reference/v1.0/resources/chat.md
>  | Relationship | Type |Description|
Please add the new property viewPoint to the properties table and the JSON representation of this file. In addition, please add it to the examples of methods that return the chat resource in the response body. In addition, please add the new property to the examples in the Get chat topic.

2022-10-06 15:35 UTC, isvargasmsft commented on api-reference/v1.0/resources/chatmessageinfo.md
> +## Properties
This is an entity type, hence it requires a section for Methods. 
```suggestion

Namespace: microsoft.graph

Represents a preview of a [chatMessage](../resources/chatmessage.md) resource. This object can only be fetched as part of a list of [chats](../resources/chat.md).

## Methods
None.

## Properties
```

2022-10-06 16:14 UTC, opbld34 commented
Learn Build status updates of commit _[4000654](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4000654a3640f754b583c786e2dc2a7a11aa7304)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210061611364019-18721/BuildReport?accessString=506ceb3296d0802528bd0df3ccf5a87fe1ff0aaae50309cb47b9ad77e1a7e576).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 16:20 UTC, opbld30 commented
Learn Build status updates of commit _[092afb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/092afb2dd14e81d2497327f070bbf82c7b1eef2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210061614126705-18721/BuildReport?accessString=a24930910fc085853ba1786f341b352a8dac5d8bd8d4c8a911bec47857964615).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 15:22 UTC, isvargasmsft requested changes
Hello @jessiechan27, 

Thank you for your work in this PR. Very complete overall. 

Please add the missing property I indicated in the comments and arrange the properties table in alphabetical order. 

Feel free to ping me on the side if you have questions. 

Kind regards, 

Isaac

2022-10-07 16:42 UTC, opbld33 commented
Learn Build status updates of commit _[f31da6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f31da6d535bfde690b87f102351b30581dd80887)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210071640085034-18721/BuildReport?accessString=1c2bdeae90af8dbd1943b0fe70236ff9cb715f0918d59906254688024ce7bb58).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 16:55 UTC, opbld31 commented
Learn Build status updates of commit _[05402e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05402e3c49fe3899503a4d850680c80100028e2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210071652116662-18721/BuildReport?accessString=d9658ef2cf1830b25f5e59efe658e41a70ba2a10f4e28357a81817241549a09c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 17:44 UTC, isvargasmsft approved these changes

2022-10-11 02:14 UTC, Lauragra commented
@jessiechan27 , if you would like to publish this PR, please remove the **do not merge** label and add **ready to merge**.

2022-10-11 13:59 UTC, opbld30 commented
Learn Build status updates of commit _[440d4a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/440d4a2b7f6e18b716914209a991d2c768aaae3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210111357330145-18721/BuildReport?accessString=0d64e776bfc06d193df02268342a2f04900f3afd0737bd5e7555c5e6e02ae26d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 02:17 UTC, opbld34 commented
Learn Build status updates of commit _[b1d429a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1d429a4b9bcfde6f53008a69c510bf8c4082b96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/beta/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/beta/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-beta&branch=pr-en-us-18721) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&branch=pr-en-us-18721) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/move-user-tenantid-and-ga-chat-additions/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120215351117-18721/BuildReport?accessString=fc387671ac257056cfe060cffe7f0f05ee16b2407d9ea183aa309b931f272982).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 04:09 UTC, merged