Updated allowDeletedIdentitiesDataRemoval
microsoftgraph/microsoft-graph-docs pull request #18730
Opened 2022-10-04 14:47 UTC by suawat

Description for allowDeletedIdentitiesDataRemoval is updated to Not Implemented yet to minimize customer friction.

2022-10-04 14:49 UTC, opbld32 commented
Learn Build status updates of commit _[98b9194](https://github.com/suawat/microsoft-graph-docs/commits/98b9194058ea5c254edbb1453c242e2d536891bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041447089152-18730/BuildReport?accessString=2be2b54e8c46e4f21bbf2b5dec3d75c72750bc6cc458f48ef3766af5bd26681f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 15:06 UTC, opbld30 commented
Learn Build status updates of commit _[0323db8](https://github.com/suawat/microsoft-graph-docs/commits/0323db8f7751736926765e210e781e96aa92e2cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041504381941-18730/BuildReport?accessString=2da37200f85f30f005ee3dad4c2fe8bbcf2188c4025fff5124f1b37785224705).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 16:42 UTC, mmcadamsms commented on api-reference/beta/resources/externalidentitiespolicy.md
> +|allowDeletedIdentitiesDataRemoval|Boolean|<!--Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home te
Do we want to say its not implemented yet?  I mean its in the API, just the propagation of the delete is not implemented.

2022-10-06 16:42 UTC, mmcadamsms commented on api-reference/beta/api/externalidentitiespolicy-get.md
> -    "allowDeletedIdentitiesDataRemoval": false,
So this is still in the API on Get

2022-10-06 17:11 UTC, suawat commented on api-reference/beta/resources/externalidentitiespolicy.md
> +|allowDeletedIdentitiesDataRemoval|Boolean|<!--Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home te
If there is a better way to convey that message, I am happy to update this.

2022-10-06 20:20 UTC, alvarorahul requested changes

2022-10-06 20:20 UTC, alvarorahul commented on api-reference/beta/resources/externalidentitiespolicy.md
> +|allowDeletedIdentitiesDataRemoval|Boolean|<!--Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home te
+1 there aren't plans yet to implement this.

Can we instead say "Reserved for future use.".

2022-10-06 20:20 UTC, alvarorahul commented on api-reference/beta/api/externalidentitiespolicy-update.md
> -|allowDeletedIdentitiesDataRemoval|Boolean|Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home tenant
we shouldn't remove it entirely... instead have the same message as the other file... since customers will see this in the API response

2022-10-06 20:20 UTC, alvarorahul commented on api-reference/beta/api/externalidentitiespolicy-get.md
> -    "allowDeletedIdentitiesDataRemoval": false,
let's leave it in the API response since we're still returning it.. we'll need to follow deprecation process in order to deprecate it

2022-10-06 20:44 UTC, opbld34 commented
Learn Build status updates of commit _[df47f10](https://github.com/suawat/microsoft-graph-docs/commits/df47f1071dd1d32d4c09a0ad832af48cafa147ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-get.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/externalidentitiespolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/externalidentitiespolicy-get?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210062042477649-18730/BuildReport?accessString=1bdea52a600374de4d97b12c4fa414223cd12c2b906bb1fbee4ec28790629d6a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 20:47 UTC, suawat commented on api-reference/beta/resources/externalidentitiespolicy.md
> +|allowDeletedIdentitiesDataRemoval|Boolean|<!--Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home te
yes agreed. Updated the description to say "Reserved for future use". I like that better.

2022-10-06 20:48 UTC, suawat commented on api-reference/beta/api/externalidentitiespolicy-get.md
> -    "allowDeletedIdentitiesDataRemoval": false,
sounds good. No change here then

2022-10-17 19:55 UTC, mmcadamsms commented on api-reference/beta/api/externalidentitiespolicy-update.md
> -|allowDeletedIdentitiesDataRemoval|Boolean|Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home tenant
|allowDeletedIdentitiesDataRemoval|Boolean|**Reserved for future use.**|

2022-10-17 19:56 UTC, mmcadamsms commented on api-reference/beta/resources/externalidentitiespolicy.md
> +|allowDeletedIdentitiesDataRemoval|Boolean|<!--Notifies Azure AD whether to clean up the user information about the external identity, from the guest tenant, when the user is deleted in their home te
|allowDeletedIdentitiesDataRemoval|Boolean|**Reserved for future use.**|

2022-10-17 20:40 UTC, mmcadamsms approved these changes
Fine by me

2022-10-17 20:52 UTC, opbld33 commented
Learn Build status updates of commit _[e0e97a1](https://github.com/suawat/microsoft-graph-docs/commits/e0e97a17deb220da9a7fe3a7c7a33684c0400920)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210172036320406-18730/BuildReport?accessString=5c93e002d915ce09626cf910e6f6d46eadb11f2a29348d8ffc66655086cf0abd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 20:55 UTC, opbld30 commented
Learn Build status updates of commit _[b749b9c](https://github.com/suawat/microsoft-graph-docs/commits/b749b9c650b207188919252cb76b596584754822)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210172039155195-18730/BuildReport?accessString=a1a6c72ca9205bc522c2109083552632fd6f4a466ec9431d8c58ef796e648fe9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 19:21 UTC, opbld33 commented
Learn Build status updates of commit _[f1e011f](https://github.com/suawat/microsoft-graph-docs/commits/f1e011f8d24cb9e2a514325f7617148760d5cc69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalidentitiespolicy-update.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/externalidentitiespolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/externalidentitiespolicy-update?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |
[api-reference/beta/resources/externalidentitiespolicy.md](https://github.com/suawat/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/externalidentitiespolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalidentitiespolicy?view=graph-rest-beta&branch=pr-en-us-18730) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210201918555438-18730/BuildReport?accessString=123e37561f912a2b9460f76b2cac475a080b88c0155c10f5956f6a25643b25eb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 00:41 UTC, merged