Adding new chat manage delete permissions
microsoftgraph/microsoft-graph-docs pull request #18778
Opened 2022-10-07 01:10 UTC by sweta-thapliyal

2022-10-07 01:13 UTC, opbld34 commented
Learn Build status updates of commit _[7502012](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75020121385a4df5bdbc43cde4dab1bc7d4965c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sthapliyal/addingChatManageDeletionPermission/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sthapliyal/addingChatManageDeletionPermission/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18778) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210070110439922-18778/BuildReport?accessString=e20525e521f5af6670623de491be9e547291f9e7fc14956191d4436bb798327c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 00:07 UTC, opbld32 commented
Learn Build status updates of commit _[60862f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60862f37037e374f1e68fc6c814f526d89db6b5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sthapliyal/addingChatManageDeletionPermission/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sthapliyal/addingChatManageDeletionPermission/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18778) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210080005154734-18778/BuildReport?accessString=5207a1fc46d98d7d32893c734981d56343ab8c51f67a4c0b798d7d3e7debc2c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 01:10 UTC, AkJo approved these changes

2022-10-08 01:26 UTC, AkJo approved these changes

2022-10-17 15:35 UTC, isvargasmsft commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added new permissions [Chat.ManageDeletion.All](https://docs.microsoft.com/en-us/graph/permissions-reference#Chat-permissions).",
Are these permissions used by an API set? We usually add the changelog entries about permissions referencing the method we are adding the permission to. For an example, see example 14 here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

2022-10-17 16:55 UTC, isvargasmsft commented on concepts/permissions-reference.md
> +|_Chat.ManageDeletion.All_ |Delete and recover deleted chats.  |Allows the app to delete and recover deleted chats, on behalf of the signed-in user. |Yes | No |
Are these permissions used by an API set? Did we update those permissions tables already? If not, please add the new permissions to the method topics that use them.

2022-10-17 16:56 UTC, isvargasmsft requested changes
Hello @sweta-thapliyal, 

Thank you very much for these updates. 

Please clarify if there are methods using these properties already. 

Thank you!

2022-10-25 19:22 UTC, isvargasmsft approved these changes
Methods will be introduced to Microsoft Graph eventually.

2023-05-05 02:44 UTC, merged