Add partner agent installation status and graph api for retry partner agent
microsoftgraph/microsoft-graph-docs pull request #18829
Opened 2022-10-12 04:26 UTC by jannyma

2022-10-12 04:29 UTC, opbld32 commented
Learn Build status updates of commit _[0c218d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c218d42e5f85765ff560f372f92aaf5585e1599)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) | [Details](#user-content-1138b774fdf9a311a5491f2f0c733a5d-595ef086)
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) | [Details](#user-content-e7005aa51b09a21baf17befdb8c14783-595ef086)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

<a id="1138b774fdf9a311a5491f2f0c733a5d-595ef086"></a>
### [api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-reprovision.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPC: reprovision' is duplicated with other articles: 'beta/api/cloudpc-reprovision.md(10,1), beta/api/cloudpc-retrypartneragentinstallation.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e7005aa51b09a21baf17befdb8c14783-595ef086"></a>
### [api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPC: reprovision' is duplicated with other articles: 'beta/api/cloudpc-reprovision.md(10,1), beta/api/cloudpc-retrypartneragentinstallation.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120426538505-18829/BuildReport?accessString=05e246ac925decd2fb5f4cc7158d3b101cc3da99724087e215e275dc6bc07f5a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 04:35 UTC, opbld32 commented
Learn Build status updates of commit _[39d9381](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39d938177d1218524e69d74352c058208a50988f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) | [Details](#user-content-1138b774fdf9a311a5491f2f0c733a5d-7c11de61)
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) | [Details](#user-content-e7005aa51b09a21baf17befdb8c14783-7c11de61)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

<a id="1138b774fdf9a311a5491f2f0c733a5d-7c11de61"></a>
### [api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-reprovision.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPC: reprovision' is duplicated with other articles: 'beta/api/cloudpc-reprovision.md(10,1), beta/api/cloudpc-retrypartneragentinstallation.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e7005aa51b09a21baf17befdb8c14783-7c11de61"></a>
### [api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPC: reprovision' is duplicated with other articles: 'beta/api/cloudpc-reprovision.md(10,1), beta/api/cloudpc-retrypartneragentinstallation.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120432545456-18829/BuildReport?accessString=0ff8c3aacf4a3f9a4aab2b8e0a46dc02402a7dfa5e9263e98e71fb1dc08bc823).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 04:38 UTC, opbld32 commented
Learn Build status updates of commit _[8e2b922](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e2b9229523970ec3349271bcabd92fe26eea917)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120435371980-18829/BuildReport?accessString=ea663bea006a7e89da27a04a555db3f7b53ea4154f4623c778bb1f2e043bec5b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 04:52 UTC, opbld32 commented
Learn Build status updates of commit _[8284982](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8284982c1a89ffc0d5e35344be272270e9a8f288)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120449508017-18829/BuildReport?accessString=72fb2fc4a68f9ae82c822f727094d5ff78e1cb6954b25f11dcf01f6d0fa83c77).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 05:12 UTC, opbld31 commented
Learn Build status updates of commit _[540c241](https://github.com/microsoftgraph/microsoft-graph-docs/commits/540c2417b630d89fafb213655216509a15db3ad8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120510032631-18829/BuildReport?accessString=e3a3daa5b44f071d5f5b26179fdfca4fff963452a32cb7fcd8e2b412e692974f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 05:26 UTC, opbld33 commented
Learn Build status updates of commit _[bf404ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf404acbb9336ff810b3bb2a9696594c9f570f20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120523460969-18829/BuildReport?accessString=55fef38e1a2427cce3a45600df96e1b0ba99015863b99456dd577f50dbb511cb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 05:35 UTC, opbld34 commented
Learn Build status updates of commit _[8c4e612](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c4e6123da6dd5e3b7c09288720b1e7866b6d9dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120533109806-18829/BuildReport?accessString=0cb1ac857324151b2b27bfb92ec3a6b5ef7393383d67230835264bc71eefb85b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 05:56 UTC, AshleyYangSZ commented
@jannyma Please add the change-log as well.

2022-10-12 06:14 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +Describe the detail of one partner agent installation result on a cloud pc.
```suggestion
Describe installation result details for a partner agent on a Cloud PC.
```

2022-10-12 06:17 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-retrypartneragentinstallation.md
> +|Content-Type|application/json. Required.|
Remove this line as this action doesn't pass any json body to backend.

2022-10-12 06:19 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-retrypartneragentinstallation.md
> +# [C#](#tab/csharp)
Please remove this part line 71 - 93. As these scripts will be automatically generated by tool after this PR gets merged. We don't need to add them manually.

2022-10-12 06:23 UTC, RuiHou105 requested changes
@jannyma 
1. please resolve comments in this PR.
2. Please also update the changelog/Microsoft.CloudManagedDesktop.json file later.
3. Please create a roadmap workitem and attach the workitem number in comments. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If no access, please do these two steps firstly.
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-10-12 06:25 UTC, opbld34 commented
Learn Build status updates of commit _[ba0460e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba0460e56e98317a50a5d62d9a8b0c94b45583e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120623315888-18829/BuildReport?accessString=0c23efddb0829136ff9c3db22e81ef5703ab3596c670b450e5f9518d239c9c0c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 10:43 UTC, opbld33 commented
Learn Build status updates of commit _[d62fd15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d62fd15d0c2a9064d334df5039b918811407c449)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210121041275228-18829/BuildReport?accessString=55e79e22e4cb46e4a0e69bbbf02a9809e225e45e8a8e53e553bfe2bb1a82e08a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 15:35 UTC, Danielabom commented
Reached out to Jingyi @jannyma to get started.

2022-10-13 21:34 UTC, Danielabom commented on api-reference/beta/api/cloudpc-retrypartneragentinstallation.md
> +description: "Attempt to re-install party partner agents in a Cloud PC which were failed to install."
```suggestion
description: "Attempts to re-install party partner agents in a Cloud PC failed to install."
```

2022-10-13 21:45 UTC, Danielabom commented on api-reference/beta/api/cloudpc-retrypartneragentinstallation.md
> +Attempt to re-install party partner agents in a Cloud PC which were failed to install.
```suggestion
Attempts to re-install party partner agents in a Cloud PC failed to install.
```

2022-10-14 04:26 UTC, jannyma commented
Roadmap work item no: 15432
https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15432

2022-10-14 04:40 UTC, opbld34 commented
Learn Build status updates of commit _[fc1b9fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc1b9fe2f5267d2e81f2e9b848dc14a784eb36b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210140431190107-18829/BuildReport?accessString=37d9cf6bd4c6262b9888d21ec44c8677e920bf8fb80ca96959b6814c81134331).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 02:49 UTC, opbld34 commented
Learn Build status updates of commit _[847083b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/847083bb212d616614b9a9ea8dec99692f125d2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210170247115914-18829/BuildReport?accessString=9db8eb2af4e785dd4eb27054d4fcf49cb824cd46fbf5d1142e68bdd9f1d4674f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 15:06 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +description: "Describe installation result details for a partner agent on a Cloud PC."
```suggestion
description: "Provides installation results for a partner agent on a Cloud PC."
```

2022-10-17 15:06 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +Namespace: microsoft.graph
```suggestion
Namespace: microsoft.graph
```

2022-10-17 15:07 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +Describe installation result details for a partner agent on a Cloud PC.
```suggestion
Provides installation results for a partner agent on a Cloud PC.
```

2022-10-18 15:55 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|partnerAgentName|[cloudPcPartnerAgentName](#cloudpcpartneragentname-values)|Indicates the name of a partner agent, right now it's just Citrix, which is third-party. And it includes first-party and t
```suggestion
|partnerAgentName|[cloudPcPartnerAgentName](#cloudpcpartneragentname-values)|Indicates the name of a partner agent and includes first-party and third-party. Currently, Citrix is the only third-party value. Read-Only.|
```

2022-10-18 15:56 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|citrix|Indicates that a third-party-partner named Citrix.|
```suggestion
|citrix|Indicates a third-party-partner named Citrix.|
```

2022-10-18 15:58 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|installStatus|[cloudPcPartnerAgentInstallStatus](#cloudpcpartneragentinstallstatus-values)|Indicates the status of a partner agent installation, possible value are: installed, installFailed, install
```suggestion
|installStatus|[cloudPcPartnerAgentInstallStatus](#cloudpcpartneragentinstallstatus-values)|Indicates the status of a partner agent installation. Possible values are: installed, installFailed, installing, uninstalling, uninstallFailed, and licensed. Read-Only.|
```

2022-10-18 16:00 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|isThirdPartyPartner|Boolean|Indicates if the partner agent is third-party. When 'TRUE', the agent is a third-party (non-Microsoft) agent.  When 'FALSE', the agent is a Microsoft agent or is not know
```suggestion
|isThirdPartyPartner|Boolean|Indicates if the partner agent is a third party. When 'TRUE', the agent is a third-party (non-Microsoft) agent. When 'FALSE', the agent is a Microsoft agent or is not known. The default value is 'FALSE'.|
```

2022-10-18 16:01 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|retriable|Boolean|Indicates whether the partner agent installation should be retried. If the installStatus is 'installFailed' or 'licensed' then 'TRUE' indicates the installation should be retried.
```suggestion
|retriable|Boolean|Indicates if the partner agent is a third party. When 'TRUE', the agent is a third-party (non-Microsoft) agent. When 'FALSE', the agent is a Microsoft agent or is not known. The default value is 'FALSE'.|
```

2022-10-18 16:08 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|unknownFutureValue|volvable enumeration sentinel value. Do not use.|
```suggestion
|unknownFutureValue|Evolvable enumeration sentinel value. Do not use.|
```

2022-10-18 16:11 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|installFailed|Indicates the partner agent installation failed although the license has been assigned.|
```suggestion
|installFailed|Indicates the partner agent installation failed, although a license was assigned.
```

2022-10-18 16:13 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|uninstallFailed|Indicates the partner agent uninstallation failed although the license has already unassigned.|
```suggestion
|uninstallFailed|Indicates the partner agent uninstallation failed, although a license was already unassigned.|
```

2022-10-18 16:14 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|licensed|Indicates the partner license was assigned to this Cloud PC, but the third-party-partner agent is not installed yet.|
```suggestion
|licensed|The partner license was assigned to this Cloud PC, but the third-party partner agent is not yet installed.|
```

2022-10-18 16:18 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|installed|Indicates the partner agent has been installed.|
```suggestion
|installed|The partner agent has been installed.|
```

2022-10-18 16:18 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|installing|Indicates the partner agent is installing.|
```suggestion
|installing|The partner agent is installing.|
```

2022-10-18 16:18 UTC, Danielabom commented on api-reference/beta/resources/cloudpcpartneragentinstallresult.md
> +|uninstalling|Indicates that the partner agent will automatically be removed.  This occurs when there is no third-party-partner license but the third-party-partner agent was previously installed.|
```suggestion
|uninstalling|The partner agent will automatically be removed.  This occurs when there is no third-party-partner license but the third-party-partner agent was previously installed.|
```

2022-10-18 16:29 UTC, Danielabom requested changes
Hi @jannyma, thank you for working on this PR. Please review my comments. Thanks!

2022-10-20 02:46 UTC, opbld34 commented
Learn Build status updates of commit _[c3e9ab5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3e9ab508914e86f7b1756be2560e386aa2e19e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210200244304973-18829/BuildReport?accessString=87351ea9ddffde57d0189bd3f3c199c21b17c28f39ce4d3337c7d68431c9eb1d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 02:59 UTC, opbld34 commented
Learn Build status updates of commit _[d0bf766](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0bf766836469da6711f87fc79cc7890813c68e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210200247417448-18829/BuildReport?accessString=8ddf0ba84a7f145882e73ba142d9587615d998693b4204a84115fd7a17946b26).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-20 16:07 UTC, Danielabom approved these changes
Thank you for addressing my comments @jannyma. Changes look good.

2022-10-20 16:10 UTC, opbld34 commented
Learn Build status updates of commit _[824a4c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/824a4c008d2a5bcefca10cb99b27051f5602e41d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210201607288783-18829/BuildReport?accessString=0c627b8a792196cc362949b16d014b3931f04e4b46ff1ce2bb7fd50f81b7d1aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 03:36 UTC, opbld32 commented
Learn Build status updates of commit _[25d99d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25d99d21421b236e9eb67469fcbf084325fbe7d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210240333284024-18829/BuildReport?accessString=c3a53a6a381002c25299fab314e2c9d7a29b2fc6501cdd088babde52a6d6e7cb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 05:14 UTC, opbld31 commented
Learn Build status updates of commit _[ffe47db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffe47db3341e3ccf36a3090c49a1ef0bb3443b4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140459521456-18829/BuildReport?accessString=9d844d950b9db215ea34ffb14717a65ecf873d79a27900acd56009f20579270c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 05:19 UTC, jannyma commented
> @jannyma
> 
> 1. please resolve comments in this PR.
> 2. Please also update the changelog/Microsoft.CloudManagedDesktop.json file later.
> 3. Please create a roadmap workitem and attach the workitem number in comments. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If no access, please do these two steps firstly.
> 
> * Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
> * Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-11-14 05:30 UTC, opbld33 commented
Learn Build status updates of commit _[ffe47db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffe47db3341e3ccf36a3090c49a1ef0bb3443b4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140519179749-18829/BuildReport?accessString=7704774d00bd9ef2f4b9354bbf45688e6bf0ba70bcdd8ebc2669b9508daee4c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 05:35 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ChangList": [
For the changelog, you lack two: add new complex type `cloudPcPartnerAgentInstallResult`, new enum `cloudPcPartnerAgentInstallStatus`, `cloudPcPartnerAgentName`. Please add them here too

2022-11-14 05:37 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +          - name: RetryPartnerAgentInstallation
```suggestion
          - name: Retry partner agent installation
```

2022-11-14 05:41 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-retrypartneragentinstallation.md
> +Attempts to re-install party partner agents in a Cloud PC failed to install.
```suggestion
Retry installation for the partner agents which failed to install on the Cloud PC. Service side will check which agent installation failed firstly and retry.
```

2022-11-14 05:42 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Retry partner agent installation](../api/cloudpc-retrypartneragentinstallation.md)|None|Attempt to re-install party partner agents in a [cloudPC](../resources/cloudpc.md) which were failed to insta
Please rephrase the description: Retry installation for the partner agents which failed to install on the Cloud PC.

2022-11-14 06:19 UTC, opbld34 commented
Learn Build status updates of commit _[0574a43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0574a4346a7721a282b3f95c326f61fe690a9b55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140617235236-18829/BuildReport?accessString=8a017b17f0c6a291464f9d271ce2de6637453067e22bcc3f3b92e08d0f85db98).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 06:30 UTC, opbld32 commented
Learn Build status updates of commit _[15a0ae4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15a0ae42685986fc1f7f4120e012933ecfd26e0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140627065365-18829/BuildReport?accessString=a79b1ec430ddec462f64cf2715d64fd5d094ecf431412e98965b34158c326960).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 06:44 UTC, opbld32 commented
Learn Build status updates of commit _[64ba042](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64ba042a25d9d12ca655a5e583b6ec4df59624a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140642221563-18829/BuildReport?accessString=4fc6c6f2e8a904026910b6b3130285351b5555c9621ad63ebb8121b945778707).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 06:51 UTC, RuiHou105 approved these changes

2022-11-16 16:22 UTC, opbld31 commented
Learn Build status updates of commit _[e723bde](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e723bdec27714085a164ab15dfd58c16600ae2f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211161620068474-18829/BuildReport?accessString=3d22e3e7ec2f053183d2f86191915281135dd045c4ad6b6faa81d37cd0c2f040).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 06:56 UTC, opbld32 commented
Learn Build status updates of commit _[be59c8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be59c8af19d5b3900fc223d9c132278e7d06c297)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211170654327656-18829/BuildReport?accessString=1999f1b5ce7ad5ec89d539719fa122ad77d559c717032f6e52e76df860e526d5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-22 17:46 UTC, Danielabom commented
@RuiHou105, @jannyma  is there a particular reason why you removed the "content review complete" label?

2022-11-23 02:36 UTC, opbld30 commented
Learn Build status updates of commit _[da0a27d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da0a27d1b0c32e62563aa64b857c104b9a487a4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211230234302389-18829/BuildReport?accessString=1172fb61da8b3b74bc9db76935eb4323d29bf51778f9c93763eeed61c0e45934).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 03:02 UTC, opbld31 commented
Learn Build status updates of commit _[208c7c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/208c7c556700360fe3d86b48d4ca6226bfaca4aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-retrypartneragentinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/api/cloudpc-retrypartneragentinstallation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcpartneragentinstallresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/resources/cloudpcpartneragentinstallresult.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcpartneragentinstallresult?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-retrypartneragentinstallation?view=graph-rest-beta&branch=pr-en-us-18829) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jannyma/retryPartnerAgentInstallation/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212080300049110-18829/BuildReport?accessString=ad366f1d8b89127f969bc9c59752bcf8cc81b7d920f55bdbade3444a2a4d5a1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 05:47 UTC, merged