Add New Permission For Search API
microsoftgraph/microsoft-graph-docs pull request #18831
Opened 2022-10-12 05:52 UTC by ZChristine

2022-10-12 05:54 UTC, opbld32 commented
Learn Build status updates of commit _[80ac190](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80ac190d1e606afa0ba274803e684bf12c72ea88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-18831) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120552094372-18831/BuildReport?accessString=3a32aa1eff2ed4da85f0e33f848fd400136e9bf02aa7ff452aaee6ecde1431d4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 12:48 UTC, isvargasmsft requested changes
Hello @ZChristine, 

Thank you very much for these updates. 

Please include a changelog entry in this PR for each permission, following the example 14 here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

Feel free to ping me if you have any questions.

Isaac

2022-11-30 07:55 UTC, ZChristine commented on api-reference/beta/api/search-query.md
> +| Delegated (work or school account)     | Mail.Read, Calendars.Read, Files.Read.All, Sites.Read.All, ExternalItem.Read.All, Bookmark.Read.All, Acronym.Read.All |
Hi, @isvargasmsft. The change log has already existed in current change log.
![image](https://user-images.githubusercontent.com/33659566/204738719-7cf06352-c721-43ec-8a3e-5f3145509486.png)
![image](https://user-images.githubusercontent.com/33659566/204738788-532ba218-970e-45df-85fa-30a135f4744d.png)

2022-12-06 15:18 UTC, isvargasmsft approved these changes
Changelog was added in the past. 

<img width="459" alt="image" src="https://user-images.githubusercontent.com/70350956/205951188-c1698712-31b7-4baa-ae76-7a9cf5af545d.png">

2022-12-07 02:41 UTC, merged