Iopana configurable msa
microsoftgraph/microsoft-graph-docs pull request #18838
Opened 2022-10-12 16:48 UTC by IoanPana

Adding new state property to builtinidentityprovider and allow MSA to update the new property.

2022-10-12 16:51 UTC, opbld33 commented
Learn Build status updates of commit _[1cbe7ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cbe7ef7922a5184552e2ef8ee5f13b5f545ca60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-delete?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) | [Details](#user-content-7f2bb5525d4718bb01ba6f52ff0b66a4-68a48b16)
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) | [Details](#user-content-df134e41f5600caba601e37f7325b857-68a48b16)
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) | [Details](#user-content-109e42dfae6e402881696cafdf9102f1-68a48b16)
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) | [Details](#user-content-317af5eaf64a576579a94b977e1073b8-68a48b16)
[api-reference/v1.0/api/builtinidentityprovider-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/api/builtinidentityprovider-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-18838) (>= graph-rest-1.0) | [Details](#user-content-64a1e8dcf2a07d102bd4d85a2dbbcc58-68a48b16)
[api-reference/v1.0/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/api/builtinidentityprovider-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-1.0&branch=pr-en-us-18838) (>= graph-rest-1.0) | [Details](#user-content-dc48e7eb15189d2135610c4142aca118-68a48b16)
[api-reference/v1.0/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/api/builtinidentityprovider-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-1.0&branch=pr-en-us-18838) (>= graph-rest-1.0) | [Details](#user-content-c11a712e6f32cfaf70b1398d95bed953-68a48b16)
[api-reference/v1.0/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/api/builtinidentityprovider-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-1.0&branch=pr-en-us-18838) (>= graph-rest-1.0) | [Details](#user-content-b82117e8e8a95bf7f11fbd96776eaa17-68a48b16)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-18838) (>= graph-rest-1.0) |

<a id="7f2bb5525d4718bb01ba6f52ff0b66a4-68a48b16"></a>
### [api-reference/beta/api/builtinidentityprovider-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-delete.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="df134e41f5600caba601e37f7325b857-68a48b16"></a>
### [api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="109e42dfae6e402881696cafdf9102f1-68a48b16"></a>
### [api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="317af5eaf64a576579a94b977e1073b8-68a48b16"></a>
### [api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: [...]

2022-10-12 20:06 UTC, opbld33 commented
Learn Build status updates of commit _[a931cf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a931cf97fbf90706078516865ce568fa62d8d0a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-18838) (>= graph-rest-1.0) | [Details](#user-content-60c6062de545134a623d9bba3de4fc43-4474ca44)
[api-reference/beta/api/builtinidentityprovider-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-delete?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |

<a id="60c6062de545134a623d9bba3de4fc43-4474ca44"></a>
### [api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/resources/builtinidentityprovider.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-list.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-get.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-update.md'.`````
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-delete.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'v1.0/api/security-ediscoverycustodian-removehold.md(3,14)', 'v1.0/resources/builtinidentityprovider.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210122003430499-18838/BuildReport?accessString=87ee8fee30890d99a3f595078ca2c7f0bbfce7fcf36ed4203855e2b561ad2a4f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 20:24 UTC, opbld31 commented
Learn Build status updates of commit _[6ccef91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ccef917552775a63dba538218e6734046f2601f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-18838) (>= graph-rest-1.0) | [Details](#user-content-60c6062de545134a623d9bba3de4fc43-d4325e32)
[api-reference/beta/api/builtinidentityprovider-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-delete?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |

<a id="60c6062de545134a623d9bba3de4fc43-d4325e32"></a>
### [api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/v1.0/resources/builtinidentityprovider.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-list.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-get.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-update.md'.`````
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/builtinidentityprovider-delete.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'v1.0/api/security-ediscoverycustodian-removehold.md(3,14)', 'v1.0/resources/builtinidentityprovider.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210122022202730-18838/BuildReport?accessString=91056517110ee56de6c118fd613d17cc5ad3140757708fd76221260bd55740fa).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 20:28 UTC, opbld34 commented
Learn Build status updates of commit _[b409d5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b409d5a3840510b70d800cf620d8271749c84f9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-delete?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210122026086149-18838/BuildReport?accessString=f6c937fe62761424b95a9e2b007a78f503681dcced1a59aecb21a79f2b67992e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 17:11 UTC, opbld33 commented
Learn Build status updates of commit _[2c78add](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c78addc937a00ee461d8d002b0b9d32e1242ff0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210131708563040-18838/BuildReport?accessString=82e1c30ba4f51ec2e9197efb296ddeafa9d273e1bb0bcfa4d735706ebe51a383).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 22:02 UTC, opbld30 commented
Learn Build status updates of commit _[13eecc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13eecc0e14944e01fee2788412e9348c803303d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210132159301106-18838/BuildReport?accessString=ba0014c15635092b934f899a44ebbf8db852203ce527a41824ffc4f5edf30f31).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 22:06 UTC, opbld34 commented
Learn Build status updates of commit _[d36c379](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d36c379488c7a28bd4ac3f19ffbe9d947a8c96e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210132204092028-18838/BuildReport?accessString=ffb9f4c515660bcc8558d0d2eb618477b5e35f69ab4d9c92bee048dd99b7907b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 23:54 UTC, opbld31 commented
Learn Build status updates of commit _[9d77d5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d77d5df2744a411d1baf7e8705e1b6c812cfc00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[changelog/Microsoft.CPIM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/changelog/Microsoft.CPIM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210132352012007-18838/BuildReport?accessString=658a976613438341c8bb884be31662fb6642b2395d0304f05c988e9882027364).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 00:04 UTC, opbld34 commented
Learn Build status updates of commit _[469c8b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/469c8b40295491d346fd6856c7a877aa22b230bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[changelog/Microsoft.CPIM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/changelog/Microsoft.CPIM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210140001538867-18838/BuildReport?accessString=ed382e646ea79c2298614dbab4cc0d36701ff0971592513e4ae3a6362c075067).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 01:06 UTC, opbld31 commented
Learn Build status updates of commit _[5b08e23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b08e23be2af0b9dfcac2411b1c0570bead67935)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[changelog/Microsoft.CPIM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/changelog/Microsoft.CPIM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210140103428173-18838/BuildReport?accessString=d6e8f7864a91dd75da073b23869d53c469a336089d38e0ec9a107b3c0fc9726d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 01:25 UTC, opbld31 commented
Learn Build status updates of commit _[05f6b71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05f6b71a29c3d0bbe19a68d7f065e412614ca746)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[changelog/Microsoft.CPIM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/changelog/Microsoft.CPIM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210140123511870-18838/BuildReport?accessString=ff7dd4d46f48256272b5bb182c8c31216abfd79cc8685df01163751a501b7cea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 20:26 UTC, opbld33 commented
Learn Build status updates of commit _[57c4891](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57c489193370ceb5c21d4fd5be7a0524b314ccac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[changelog/Microsoft.CPIM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/changelog/Microsoft.CPIM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210242023234204-18838/BuildReport?accessString=9c6b61e65f0935aecc7da79fedf677ceb7aeb2a6947be693f78aba6decc2558d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 14:12 UTC, Danielabom commented
Chatted with @IoanPana, and the PR is not ready for review. He'll reach out later.

2022-10-27 15:10 UTC, IoanPana commented
CSDL changes: https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/6905649
Internal roadmap item: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1841904
Purpose/objective of the PR: Making MSA IdentityProvider configurable at tenant level.

2022-10-27 15:13 UTC, opbld33 commented
Learn Build status updates of commit _[00edc58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00edc58e751229a925f3049f212480e08c3ecf7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[changelog/Microsoft.CPIM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/changelog/Microsoft.CPIM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271510516505-18838/BuildReport?accessString=edd4d8a1ae00e617fb663fc652363e543f4a6576b4699be85132f7cbfbfbfedd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 01:02 UTC, Lauragra commented
@IoanPana , please only set the ready to merge label after your content reviewer has approved your PR and your APIs are publicly available. If your APIs have shipped but your PR is not yet approved, you can set the schema live label.

2022-10-28 16:30 UTC, opbld33 commented
Learn Build status updates of commit _[84e6634](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84e6634e8935c8c214eb367c242d53f0254f82b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/builtinidentityprovider-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-get?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-list?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/api/builtinidentityprovider-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/api/builtinidentityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/builtinidentityprovider-update?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18838) (graph-rest-beta) |
[changelog/Microsoft.CPIM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/iopana-configurable-msa/changelog/Microsoft.CPIM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210281628229745-18838/BuildReport?accessString=1b5fc5846192a1eba620263bf0bd2a01ef8ec6bdae7f99cab9298b047152c3ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-01 18:26 UTC, FaithOmbongi requested changes
Thank you @IoanPana for your work in this PR.

Some clarification: Based on our initial documentation of the APIs which we handled with Namrata, we don't need to document new APIs. Instead, all functionality for the derived types should piggy back on the existing APIs. Therefore, please delete the three new files in the api subfolder.

For update builtInIdentityProvider: Because you can only update the state property of a buildInIdentityProvider type and the property only applies to MSA IdP, make the changes to this doc instead [Update identityProvider](https://learn.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&tabs=http). Feel free to add an Example 4 to show what you can update for builtInIdentityProvider.

In addition, in [response object of Example 1 of List configured identity providers](https://learn.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&tabs=http#response-1), add the state property to the MicrosoftAccount response object. Same sentiment for the [response object of Example 2 of Get identityProvider](https://learn.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&tabs=http#example-2-retrieve-a-specific-built-in-identity-provider-only-for-azure-ad).

Please feel free to ping me internally for any clarification.

2022-11-01 18:26 UTC, FaithOmbongi commented on api-reference/beta/api/builtinidentityprovider-get.md
> +---
Delete file as per the explanation I gave in the resource doc

2022-11-01 18:26 UTC, FaithOmbongi commented on api-reference/beta/api/builtinidentityprovider-list.md
> +---
Delete file as per the explanation I gave in the resource doc

2022-11-01 18:26 UTC, FaithOmbongi commented on api-reference/beta/api/builtinidentityprovider-update.md
> +---
Delete file as per the explanation I gave in the resource doc.

Instead, update the [Update identityProvider](https://learn.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta) doc by indicating where applicable about the only update operation allowed which is update for the MSA IdP.

2022-11-01 18:26 UTC, FaithOmbongi commented on changelog/Microsoft.CPIM.json
> +          "Description": "Added the `state` property to the [builtInIdentityProvider](https://docs.microsoft.com/en-us/graph/api/resources/builtInIdentityProvider?view=graph-rest-beta) resource.",
Recommended enhancement.
```suggestion
          "Description": "Added the **state** property to the [builtInIdentityProvider](https://docs.microsoft.com/en-us/graph/api/resources/builtInIdentityProvider?view=graph-rest-beta) resource. Use this property to enable or disable the Microsoft accounts built-in identity provider in your tenant.",
```

2023-01-09 15:01 UTC, closed without merging

2023-03-17 09:32 UTC, FaithOmbongi commented
The changes are live. Removing the changes requested label to avoid unactionable notifications.