Initial commit
microsoftgraph/microsoft-graph-docs pull request #18884
Opened 2022-10-15 14:01 UTC by yadavgaurav121

2022-10-15 14:04 UTC, opbld31 commented
Learn Build status updates of commit _[a1c999a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1c999a33b1627fdad3725a6f8b6337467ab3162)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-38551576)

<a id="18ce0e3c0f583d09102a386bee5dc7ff-38551576"></a>
### [api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md)
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/attacksimulationroot-list-payload.md'.`````
 - **Line 28, Column 2**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/attacksimulationroot-get-payload.md'.`````
 - **Line 33, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#simulationstatus-values' in 'beta/resources/payload.md'.`````
 - **Line 31, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210151401451504-18884/BuildReport?accessString=54b74e50ff8f79fc9cfc79ef251c8bfaa3bfd4e4ebd554071e0065d01385ca87).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-22 06:02 UTC, opbld30 commented
Learn Build status updates of commit _[8315a8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8315a8e5951969c9606940e1d3aabdd11738b8c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-9b56d3b8)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-9b56d3b8)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-9b56d3b8)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-9b56d3b8)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-9b56d3b8)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-9b56d3b8)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-9b56d3b8)
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-280b50d4c25098acdc228c082b8ded32-9b56d3b8)
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-aada65d52906304776093f8573d5b778-9b56d3b8)
[api-reference/beta/resources/coachmarkLocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/coachmarkLocation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/coachmarklocation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-e14461338cf0beedd049cf016b1bd723-9b56d3b8)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-9b56d3b8)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-9b56d3b8)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-9b56d3b8)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-9b56d3b8)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-refe [...]

2022-12-08 11:38 UTC, opbld32 commented
Learn Build status updates of commit _[d8ede81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8ede81f0c15d343362523b2ff038c67c33b33eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-8da3c6ad)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-8da3c6ad)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-8da3c6ad)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-8da3c6ad)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-8da3c6ad)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-8da3c6ad)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-8da3c6ad)
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-280b50d4c25098acdc228c082b8ded32-8da3c6ad)
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-aada65d52906304776093f8573d5b778-8da3c6ad)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-8da3c6ad)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-8da3c6ad)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-8da3c6ad)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-8da3c6ad)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-8da3c6ad)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attack [...]

2022-12-08 12:26 UTC, opbld30 commented
Learn Build status updates of commit _[b23e93e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b23e93e1b908a05fd52c645861db96a815ec5aff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-a0a61562)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-a0a61562)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-a0a61562)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-a0a61562)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-a0a61562)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-a0a61562)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-a0a61562)
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-280b50d4c25098acdc228c082b8ded32-a0a61562)
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-aada65d52906304776093f8573d5b778-a0a61562)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-a0a61562)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-a0a61562)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-a0a61562)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-a0a61562)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-a0a61562)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attack [...]

2022-12-08 13:45 UTC, opbld34 commented
Learn Build status updates of commit _[8d8be3c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d8be3c67dc95d084fca06604ac59b9d9199e3af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-5847f32e)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-5847f32e)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-5847f32e)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-5847f32e)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-5847f32e)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-5847f32e)
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-aada65d52906304776093f8573d5b778-5847f32e)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-5847f32e)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-5847f32e)
[api-reference/beta/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/longrunningoperation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-0b27cb215bc223737d38519e261b51c3-5847f32e)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-5847f32e)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-5847f32e)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-5847f32e)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-5847f32e)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-lis [...]

2022-12-08 14:01 UTC, opbld32 commented
Learn Build status updates of commit _[19acab7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19acab7c84f7a7908eb26fc4c0dde470fc9d893e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-74eb10f7)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-74eb10f7)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-74eb10f7)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-74eb10f7)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-74eb10f7)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-74eb10f7)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-74eb10f7)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-74eb10f7)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-74eb10f7)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-74eb10f7)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-74eb10f7)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-74eb10f7)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 14:15 UTC, opbld32 commented
Learn Build status updates of commit _[c6eaaba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6eaabafaf4e43102848d997ff3f5d1042d26266)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-95a81349)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-95a81349)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-95a81349)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-95a81349)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-95a81349)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-95a81349)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-95a81349)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-95a81349)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-95a81349)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-95a81349)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-95a81349)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-95a81349)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 14:28 UTC, opbld31 commented
Learn Build status updates of commit _[6a35373](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a353739771836cc104cd0c7941d1b1d80a7f566)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-b05fa523)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-b05fa523)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-b05fa523)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-b05fa523)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-b05fa523)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-b05fa523)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-b05fa523)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-b05fa523)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-b05fa523)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-b05fa523)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-b05fa523)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-b05fa523)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 14:31 UTC, opbld31 commented
Learn Build status updates of commit _[9668c63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9668c63309f8403a97b7673eaddffa113182c4cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-2b9c2f79)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-2b9c2f79)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-2b9c2f79)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-2b9c2f79)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-2b9c2f79)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-2b9c2f79)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-2b9c2f79)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-2b9c2f79)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-2b9c2f79)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-2b9c2f79)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-2b9c2f79)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-2b9c2f79)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 14:46 UTC, opbld33 commented
Learn Build status updates of commit _[17d3066](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17d30668edd8666ba890fe5d2d6b9d8c5a2f6974)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-3c76c609)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-3c76c609)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-3c76c609)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-3c76c609)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-3c76c609)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-3c76c609)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-3c76c609)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-3c76c609)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-3c76c609)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-3c76c609)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-3c76c609)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-08 15:28 UTC, opbld34 commented
Learn Build status updates of commit _[8f49500](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f4950082e67bc722e38f861646c3ba1b2013593)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-0fd539a9)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-0fd539a9)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-0fd539a9)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-0fd539a9)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-0fd539a9)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-0fd539a9)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-0fd539a9)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-0fd539a9)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-0fd539a9)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-0fd539a9)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-0fd539a9)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-0fd539a9)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 16:59 UTC, opbld33 commented
Learn Build status updates of commit _[9a90039](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a900392ea6872ba2a114acf17b9399e3069791f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-3df68aba)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-3df68aba)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-3df68aba)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-3df68aba)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-3df68aba)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-3df68aba)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-3df68aba)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-3df68aba)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-3df68aba)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-3df68aba)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-3df68aba)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-3df68aba)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 17:12 UTC, opbld33 commented
Learn Build status updates of commit _[7d0f24c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d0f24c7e3188c80a93d6d5fd11d8ce286ab4cf9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-fa9c4ea9)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-fa9c4ea9)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-fa9c4ea9)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-fa9c4ea9)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-fa9c4ea9)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-fa9c4ea9)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-fa9c4ea9)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-fa9c4ea9)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-fa9c4ea9)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-fa9c4ea9)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-fa9c4ea9)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-fa9c4ea9)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 17:26 UTC, opbld33 commented
Learn Build status updates of commit _[b3be66a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3be66ad3142c55ad12785ed6d10f7239999fd2b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-280ff4b8)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-280ff4b8)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-280ff4b8)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-280ff4b8)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-280ff4b8)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-280ff4b8)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-280ff4b8)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-280ff4b8)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-280ff4b8)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-280ff4b8)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-280ff4b8)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-280ff4b8)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 17:36 UTC, opbld33 commented
Learn Build status updates of commit _[8014873](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8014873987ee89f76fe3103360be27f815e3b6e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-af6b58d5)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-af6b58d5)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-af6b58d5)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-af6b58d5)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-af6b58d5)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-af6b58d5)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-af6b58d5)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-af6b58d5)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-af6b58d5)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-af6b58d5)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-af6b58d5)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-af6b58d5)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 17:42 UTC, opbld32 commented
Learn Build status updates of commit _[f7b97ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7b97edf54a71da6fd8edd3d576efffb255ca26a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-6db48975)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-6db48975)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-6db48975)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-6db48975)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-6db48975)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-6db48975)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-6db48975)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-6db48975)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-6db48975)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-6db48975)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-6db48975)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-6db48975)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 17:47 UTC, opbld33 commented
Learn Build status updates of commit _[d9ed51c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9ed51c0b3a0967055913f8fb670b4b2f739c865)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-d2d85bc1)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-d2d85bc1)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-d2d85bc1)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-d2d85bc1)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-d2d85bc1)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-d2d85bc1)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-d2d85bc1)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-d2d85bc1)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-d2d85bc1)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-d2d85bc1)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-d2d85bc1)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-d2d85bc1)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-08 18:13 UTC, opbld32 commented
Learn Build status updates of commit _[007b761](https://github.com/microsoftgraph/microsoft-graph-docs/commits/007b761e2953c7f249094c0426424eda7e7528e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-91e55d08)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-91e55d08)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-91e55d08)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-91e55d08)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-91e55d08)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-91e55d08)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-91e55d08)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-91e55d08)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-91e55d08)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-91e55d08)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-91e55d08)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-91e55d08)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-09 07:57 UTC, opbld34 commented
Learn Build status updates of commit _[e7d18ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7d18aced102977b7a5fb6a612233056213621c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-4eea56f0)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-4eea56f0)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-4eea56f0)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-4eea56f0)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-4eea56f0)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-4eea56f0)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-4eea56f0)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-4eea56f0)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-4eea56f0)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-4eea56f0)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-4eea56f0)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-4eea56f0)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-09 08:18 UTC, opbld34 commented
Learn Build status updates of commit _[2124683](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21246830f25e6d65e73140910620c24fe3822802)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-d6c7ba5c)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-d6c7ba5c)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-d6c7ba5c)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-d6c7ba5c)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-d6c7ba5c)
[api-reference/beta/resources/payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payload.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-18ce0e3c0f583d09102a386bee5dc7ff-d6c7ba5c)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-d6c7ba5c)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-d6c7ba5c)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-d6c7ba5c)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-d6c7ba5c)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-d6c7ba5c)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-d6c7ba5c)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review. [...]

2022-12-09 08:24 UTC, opbld30 commented
Learn Build status updates of commit _[784e538](https://github.com/microsoftgraph/microsoft-graph-docs/commits/784e538ef5b15770a2d41a81fdb98aef58f5fae0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-d67c812f)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-d67c812f)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-d67c812f)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-d67c812f)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-d67c812f)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-d67c812f)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-d67c812f)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-d67c812f)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-d67c812f)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-d67c812f)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-d67c812f)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 08:39 UTC, opbld34 commented
Learn Build status updates of commit _[69129b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69129b0dcf7042ecd2f26c72f5093d8d097dee00)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-badfa0fc)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-badfa0fc)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-badfa0fc)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-badfa0fc)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-badfa0fc)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-badfa0fc)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-badfa0fc)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-badfa0fc)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-badfa0fc)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-badfa0fc)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-badfa0fc)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 08:57 UTC, opbld32 commented
Learn Build status updates of commit _[f7eab3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7eab3a6db5fb557f9c1f31322ce6213386cde34)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-06fe555e)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-06fe555e)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-06fe555e)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-06fe555e)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-06fe555e)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-06fe555e)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-06fe555e)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-06fe555e)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-06fe555e)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-06fe555e)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-06fe555e)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 09:00 UTC, opbld30 commented
Learn Build status updates of commit _[9943b75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9943b756d1d664beab3fc393eadefc133ee19b9c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-aa26dfc9)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-aa26dfc9)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-aa26dfc9)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-aa26dfc9)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-aa26dfc9)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-aa26dfc9)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-aa26dfc9)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-aa26dfc9)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-aa26dfc9)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-aa26dfc9)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-aa26dfc9)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 09:09 UTC, opbld34 commented
Learn Build status updates of commit _[87f7e6c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87f7e6ca002acec20470614a2214a6cc9b727abd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-30294b6c)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-30294b6c)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-30294b6c)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-30294b6c)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-30294b6c)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-30294b6c)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-30294b6c)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-30294b6c)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-30294b6c)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-30294b6c)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-30294b6c)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 09:18 UTC, opbld30 commented
Learn Build status updates of commit _[33a3854](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33a38543ff0fac5e90ce2c7f8a1371f677251b20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-144458e1)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-144458e1)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-144458e1)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-144458e1)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-144458e1)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-144458e1)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-144458e1)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-144458e1)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-144458e1)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-144458e1)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-144458e1)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 09:20 UTC, opbld30 commented
Learn Build status updates of commit _[93e6e83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93e6e830e233d2616d17a330f5cfb92ff280e963)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-00d24751)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-00d24751)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-00d24751)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-00d24751)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-00d24751)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-00d24751)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-00d24751)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-00d24751)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-00d24751)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-00d24751)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-00d24751)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 18:00 UTC, opbld30 commented
Learn Build status updates of commit _[f5ae303](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5ae303ebb9048dd997f362061edc09dc320e5c4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-a7668038)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-a7668038)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-a7668038)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-a7668038)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-a7668038)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-a7668038)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-a7668038)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-a7668038)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-a7668038)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-a7668038)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-a7668038)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-09 18:35 UTC, opbld34 commented
Learn Build status updates of commit _[f8697b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8697b25cbff1a362a3c4b6fb4ba935f71511ba9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-create-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-create-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-create-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-54d6b4c0cfaed7601c26a45b609177ee-9c5ec62a)
[api-reference/beta/api/attacksimulationroot-delete-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-delete-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-delete-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-850f559abea85bea51955e6c003bbca1-9c5ec62a)
[api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-excludedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-9e19a9bb7ca91cd90cecec78318887d0-9c5ec62a)
[api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-includedaccounttarget?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-14dd8383fc87008371f7197ec92c0edb-9c5ec62a)
[api-reference/beta/api/attacksimulationroot-update-simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-update-simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-update-simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-001de1e9524f89b5eaec92658377b4c3-9c5ec62a)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-9c5ec62a)
[api-reference/beta/resources/accounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/accounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d0f09dcedbecb8738eba37e566a331f1-9c5ec62a)
[api-reference/beta/resources/addressbookaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/addressbookaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/addressbookaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-175fa01304df9bb928a5c4a82172d9cf-9c5ec62a)
[api-reference/beta/resources/emailPayloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/emailPayloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/emailpayloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-1f0fb06df7ed01d5a804af62dd824966-9c5ec62a)
[api-reference/beta/resources/includeallaccounttargetcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/includeallaccounttargetcontent.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/includeallaccounttargetcontent?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-d67c709b1f48b103c5fc5e107a7817d0-9c5ec62a)
[api-reference/beta/resources/payloadDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/payloadDetail.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/payloaddetail?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) | [Details](#user-content-ea84dd6729acb0930f3421c2edee35cb-9c5ec62a)
[api-reference/beta/api/attacksimulationroot-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-operation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payload.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payload?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-get-payloadsdetails?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-payloads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-payloads.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-payloads?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attackSimulationOperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attackSimulationOperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/attacksimulationoperation?view=graph-rest-beta&branch=pr-en-us-18884) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/attacksim_createsim_changes/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.micros [...]

2022-12-16 23:39 UTC, JarbasHorst commented on api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
> +        "jeff.watson@microsoft.com"
Please use approved fictitious names (display names, domains, email address): https://microsoft.sharepoint.com/sites/CELAWeb-Copyrights-Trademarks-And-Patents/SitePages/trademarks-fictitious-names.aspx

Same here:
- api-reference/beta/api/attacksimulationroot-create-simulation.md
- api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md
- api-reference/beta/api/attacksimulationroot-get-payload.md
- api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md
- api-reference/beta/api/attacksimulationroot-list-payloads.md
- api-reference/beta/api/attacksimulationroot-update-simulation.md

2022-12-16 23:39 UTC, JarbasHorst commented on api-reference/beta/resources/addressbookaccounttargetcontent.md
> +    "type" : "addressBook",
1) For consistency, the JSON representation should not contain examples. Please, fix the values for type and accountTargetEmails. 

2) Also, please show the properties here in alphabetical order. You don't need to change the position of @odata.type…

Same here:
- api-reference/beta/resources/attackSimulationOperation.md
- api-reference/beta/resources/emailPayloadDetail.md
- api-reference/beta/resources/includeallaccounttargetcontent.md
- api-reference/beta/resources/payload.md
- api-reference/beta/resources/payloadCoachmark.md
- api-reference/beta/resources/payloadDetail.md
- api-reference/beta/resources/simulation.md

2022-12-16 23:39 UTC, JarbasHorst commented on api-reference/beta/resources/coachmarkLocation.md
> +---
Please, add the missing and required JSON Representation section to this resource topic.

2022-12-16 23:39 UTC, JarbasHorst commented on api-reference/beta/resources/payloadCoachmark.md
> +{
Please, apply formatting to this JSON object.

2022-12-16 23:39 UTC, JarbasHorst commented on api-reference/beta/resources/attackSimulationOperation.md
> +---
Some filenames aren’t following the filename patterns for the Microsoft Graph docs. Please, provide the filename in lowercase format. In this case, ...attackSimulationOperation... should be ...attacksimulationoperation...

Same here:
- api-reference/beta/resources/coachmarkLocation.md
- api-reference/beta/resources/emailPayloadDetail.md
- api-reference/beta/resources/payloadCoachmark.md
- api-reference/beta/resources/payloadDetail.md

2022-12-16 23:39 UTC, JarbasHorst commented on api-reference/beta/resources/attacksimulationroot.md
>  |simulationAutomations|[simulationAutomation](../resources/simulationautomation.md) collection|Represents simulation automation created to run on a tenant.|
For consistency and to improve scanning, properties in the Properties table should be in alphabetical order. Please, alphabetize the list.

Same here:
- api-reference/beta/resources/emailPayloadDetail.md
- api-reference/beta/resources/payload.md
- api-reference/beta/resources/payloadCoachmark.md
- api-reference/beta/resources/payloadDetail.md
- api-reference/beta/resources/simulation.md

2022-12-16 23:39 UTC, JarbasHorst commented on api-reference/beta/resources/accounttargetcontent.md
> +title: "Account target content resource type"
The title should have the same value as the H1. So, "Account target content resource type" should be "accountTargetContent resource type".

Same here:
- api-reference/beta/resources/addressbookaccounttargetcontent.md
- api-reference/beta/resources/attackSimulationOperation.md
- api-reference/beta/resources/coachmarkLocation.md
- api-reference/beta/resources/emailPayloadDetail.md
- api-reference/beta/resources/includeallaccounttargetcontent.md

2022-12-19 10:18 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
> +        "jeff.watson@microsoft.com"
addressed

2022-12-19 10:40 UTC, yadavgaurav121 commented on api-reference/beta/resources/addressbookaccounttargetcontent.md
> +    "type" : "addressBook",
updated

2022-12-19 10:45 UTC, yadavgaurav121 commented on api-reference/beta/resources/coachmarkLocation.md
> +---
updated

2022-12-19 10:45 UTC, yadavgaurav121 commented on api-reference/beta/resources/payloadCoachmark.md
> +{
updated

2022-12-19 10:49 UTC, yadavgaurav121 commented on api-reference/beta/resources/attackSimulationOperation.md
> +---
updated

2022-12-19 11:36 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationroot.md
>  |simulationAutomations|[simulationAutomation](../resources/simulationautomation.md) collection|Represents simulation automation created to run on a tenant.|
updated

2022-12-19 11:38 UTC, yadavgaurav121 commented on api-reference/beta/resources/accounttargetcontent.md
> +title: "Account target content resource type"
updated

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/addressbookaccounttargetcontent.md
> +description: "Represents an included or excluded users from attack simulation training campaign."
This description is used here and in the following resource topic "api-reference/beta/resources/accounttargetcontent.md". Descriptions should be unique across all resource topics. Please, rephrase this description to be unique and to describe this resource. Suggested revision as per the api.md file:

- Represents account targets for an attack simulation training campaign.

Please, update also the description in line 14.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/addressbookaccounttargetcontent.md
> +Attack simulation and training is a service available as part of [Microsoft Defender for Office 365](/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide&preserve-v
This and the following paragraph already exist in the "api-reference/beta/resources/accounttargetcontent.md" topic. For simplicity and to simplify the docs maintenance, I recommend you to remove these two paragraphs from this resource topic as the information already exists in the accountTargetContent resource topic and doesn't add any new information to readers. Readers can access the accountTargetContent topic via the link provided in line 20.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/includeallaccounttargetcontent.md
> +description: "Represents an included or excluded users from attack simulation training campaign."
This description is used here and in the following resource topic "api-reference/beta/resources/accounttargetcontent.md". Descriptions should be unique across all resource topics. Please, rephrase this description to be unique and to describe this resource.

Please, update also the description in line 14.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/includeallaccounttargetcontent.md
> +Attack simulation and training is a service available as part of [Microsoft Defender for Office 365](/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide&preserve-v
This and the following paragraph already exist in the "api-reference/beta/resources/accounttargetcontent.md" topic. For simplicity and to simplify the docs maintenance, I recommend you to remove these two paragraphs from this resource topic as the information already exists in the accountTargetContent resource topic and doesn't add any new information to readers. Readers can access the accountTargetContent topic via the link provided in line 18.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/accounttargetcontent.md
> +|:---|:---|
According to the CSDL file, this enum should also have the two additional members "unknown" and "unknownFutureValue". Please, add the missing members to this enum.

Please, update also the possible values for this enum in line 30 (description for the type property) and in the following file:
- api-reference/beta/resources/includeallaccounttargetcontent.md (Properties table)

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/emailPayloadDetail.md
> +description: "Represents the detail of a payload."
Descriptions should be unique (also used here beta/resources/payloadDetail.md) across resource topics and they should describe the resources properly. Please, update this description to be more descriptive and unique.

Please, update also the description in line 16.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/payloadDetail.md
> +description: "Represents the detail of a payload."
Descriptions should be unique (also used here beta/resources/emailPayloadDetail.md) across resource topics and they should describe the resources properly. Please, update this description to be more descriptive and unique.

Please, update also the description in line 16.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/accounttargetcontent.md
> +---
Please, include an update to the toc.yml file in the beta folder, to surface the APIs (Get includedAccountTarget and Get excludedAccountTarget) in the TOC.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/attackSimulationOperation.md
> +title: "attackSimulationOperation resource type"
Please, include an update to the toc.yml file in the beta folder, to surface the API (Get operation) in the TOC.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/includeallaccounttargetcontent.md
> +description: "Represents included or excluded users from an attack simulation training campaign."
This description is used here and in the following resource topic "api-reference/beta/resources/accounttargetcontent.md". Descriptions should be unique across all resource topics. Please, rephrase this description to be unique and to describe this resource.

Please, update also the description in line 16.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/emailpayloaddetail.md
> +description: "Represents details of a payload."
Descriptions should be unique (also used here beta/resources/payloadDetail.md) across resource topics and they should describe the resources properly. Please, update this description to be more descriptive and unique.

Please, update also the description in line 16.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/payloaddetail.md
> +description: "Represents the detail of a payload."
Descriptions should be unique (also used here beta/resources/emailPayloadDetail.md) across resource topics and they should describe the resources properly. Please, update this description to be more descriptive and unique.

Please, update also the description in line 16.

2022-12-20 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/attacksimulationoperation.md
> +---
Please, include an update to the toc.yml file in the beta folder, to surface the API (Get operation) in the TOC.

2022-12-20 22:54 UTC, JarbasHorst commented
Hi @yadavgaurav121, thanks for addressing my previous comments. I left additional ones. Please, take a look when you will have time. 

Please, don't readd the label "Ready for content review" once the content review is in progress. Readding the label might confuse our colleagues.

2022-12-21 03:45 UTC, yadavgaurav121 commented on api-reference/beta/resources/addressbookaccounttargetcontent.md
> +description: "Represents an included or excluded users from attack simulation training campaign."
updated

2022-12-21 03:46 UTC, yadavgaurav121 commented on api-reference/beta/resources/addressbookaccounttargetcontent.md
> +Attack simulation and training is a service available as part of [Microsoft Defender for Office 365](/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide&preserve-v
updated

2022-12-21 03:50 UTC, yadavgaurav121 commented on api-reference/beta/resources/accounttargetcontent.md
> +|:---|:---|
updated

2022-12-21 03:52 UTC, yadavgaurav121 commented on api-reference/beta/resources/includeallaccounttargetcontent.md
> +description: "Represents included or excluded users from an attack simulation training campaign."
updated

2022-12-21 03:53 UTC, yadavgaurav121 commented on api-reference/beta/resources/emailpayloaddetail.md
> +description: "Represents details of a payload."
updated

2022-12-21 03:54 UTC, yadavgaurav121 commented on api-reference/beta/resources/payloaddetail.md
> +description: "Represents the detail of a payload."
updated the email payload detail.

2022-12-21 03:58 UTC, yadavgaurav121 commented on api-reference/beta/resources/accounttargetcontent.md
> +---
updated

2022-12-21 03:58 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationoperation.md
> +---
updated

2022-12-21 07:23 UTC, yadavgaurav121 commented
@Jarbas-MSFT I have addressed your comments, please have a look.

2022-12-21 23:52 UTC, JarbasHorst commented on api-reference/beta/resources/longrunningoperation.md
> +
The longRunningOperationStatus enum already exists in the enums.md file. In this case, you don't need to readd it here. I have removed the longRunningOperationStatus  entry from this resource topic.

Also, the simulationStatus enum has already been documented in the simulation resource topic and it doesn't need to be readded to this resource topic. I have removed the simulationStatus entry from this resource topic.

2022-12-21 23:52 UTC, JarbasHorst commented on api-reference/beta/resources/attacksimulationoperation.md
> +description: "Represents an attack simulation training operation."
For clarity, I recommend you to rephrase this sentence. Suggested revision:

- Represents the status of a long-running attack simulation training operation.

Please, apply this change also to line 16.

2022-12-21 23:52 UTC, JarbasHorst commented on api-reference/beta/resources/attacksimulationoperation.md
> +|id|String|The unique identifier for the training. Inherited from [entity](../resources/entity.md).|
Does this ID represent the unique identifier for a training or for a long-running operation? Please, update the description to be more clear. Suggested revision:

- The unique identifier for the operation.

2022-12-21 23:52 UTC, JarbasHorst commented on api-reference/beta/resources/attacksimulationroot.md
>  |[List simulationAutomations](../api/attacksimulationroot-list-simulationautomations.md)|[simulationAutomation](../resources/simulationautomation.md) collection|Get a list of attack simulation automa
Please, add the Get payloadDetail (api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md) and  Delete simulations (api-reference/beta/api/attacksimulationroot-delete-simulation.md) methods to this table.

2022-12-21 23:52 UTC, JarbasHorst commented on api-reference/beta/resources/emailpayloaddetail.md
> +|subject|String|Email address of the user.|
Please, update the description of this property.

2022-12-21 23:52 UTC, JarbasHorst commented on api-reference/beta/resources/emailpayloaddetail.md
> +|isExternalSender|String|Email address of the user.|
According to the CSDL file, this property is of type Boolean. Also, please update the description of this property.

2022-12-21 23:54 UTC, JarbasHorst commented on api-reference/beta/resources/payload.md
> +|deliveryPlatform|[payloadDeliveryPlatform](#payloaddeliveryplatform-values)|The payload delivery platform for a simulation. Possible values are: `unknown`, `sms`, `email`, `teams`, `unknownFutureVal
In the CSDL file, this property is called "platform". Please, ensure this table shows the correct name for the property.

2022-12-23 07:37 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|deliveryPlatform|[payloadDeliveryPlatform](#payloaddeliveryplatform-values)|The payload delivery platform for a simulation. Possible values are: `unknown`, `sms`, `email`, `teams`, `unknownFutureVal
This seems to be overwritten. Addressed it.

2022-12-23 07:38 UTC, yadavgaurav121 commented on api-reference/beta/resources/emailpayloaddetail.md
> +|isExternalSender|String|Email address of the user.|
updated

2022-12-23 07:39 UTC, yadavgaurav121 commented on api-reference/beta/resources/emailpayloaddetail.md
> +|subject|String|Email address of the user.|
updated

2022-12-23 07:42 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationroot.md
>  |[List simulationAutomations](../api/attacksimulationroot-list-simulationautomations.md)|[simulationAutomation](../resources/simulationautomation.md) collection|Get a list of attack simulation automa
Added Delete simulations. 
Get payloadDetail is not attacksimulationroot property. It will be accessed as /payloads/{id}/detail

2022-12-23 07:43 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationoperation.md
> +|id|String|The unique identifier for the training. Inherited from [entity](../resources/entity.md).|
updated

2022-12-23 07:44 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationoperation.md
> +description: "Represents an attack simulation training operation."
updated

2022-12-23 08:03 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|attackTechnique|[simulationAttackTechnique](../resources/simulation.md#simulationattacktechnique-values)|The social engineering technique used in the attack simulation and training campaign. Support
updated

2022-12-23 08:04 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|language|String|Unique identifier for the attack simulation payload.|
updated

2022-12-23 08:08 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|Property|Type|Description|
updated

2022-12-23 08:13 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|source|[simulationContentSource](../resources/simulation.md#simulationstatus-values)|Status of the attack simulation and training campaign. Supports `$filter` and `$orderby`.Inherited from [simulati
updated

2022-12-28 14:24 UTC, isvargasmsft commented on api-reference/beta/resources/payload.md
> +|:---|:---|:---|
Please order these table alphabetically.

2022-12-28 14:24 UTC, isvargasmsft commented on api-reference/beta/resources/payload.md
> +|language|String|Unique identifier for the attack simulation payload.|
Please update the description for the language property. It doesn't seem right.

2022-12-28 14:32 UTC, isvargasmsft commented on api-reference/beta/resources/attacksimulationoperation.md
> +|updateSimulation| The simulation update operation. |
Please update the values of attackSimulationOperationType. The CSDL defines it as:

      <EnumType Name="attackSimulationOperationType">
        <Member Name="createSimualation" Value="0" />
        <Member Name="updateSimulation" Value="1" />
        <Member Name="unknownFutureValue" Value="2" />
      </EnumType>

Suggestion
```suggestion
|type|attackSimulationOperationType|The attack simulation operation type. Possible values are: `createSimulation`, `updateSimulation`, `unknownFutureValue`.|

### attackSimulationOperationType values

|Member|Description |
|:---|:---|
|createSimulation| The simulation creation operation. |
|updateSimulation| The simulation update operation. |
|unknownFutureValue| The operation is not defined. |
```

2022-12-28 14:32 UTC, isvargasmsft commented on api-reference/beta/resources/attacksimulationoperation.md
> +|updateSimulation| The simulation update operation. |
Please update the values of attackSimulationOperationType. The CSDL defines it as:

      <EnumType Name="attackSimulationOperationType">
        <Member Name="createSimualation" Value="0" />
        <Member Name="updateSimulation" Value="1" />
        <Member Name="unknownFutureValue" Value="2" />
      </EnumType>

Suggestion
```suggestion
|type|attackSimulationOperationType|The attack simulation operation type. Possible values are: `createSimulation`, `updateSimulation`, `unknownFutureValue`.|

### attackSimulationOperationType values

|Member|Description |
|:---|:---|
|createSimulation| The simulation creation operation. |
|updateSimulation| The simulation update operation. |
|unknownFutureValue| The operation is not defined. |
```

2022-12-28 14:32 UTC, isvargasmsft commented on api-reference/beta/resources/attacksimulationoperation.md
> +
Please update the values of attackSimulationOperationType. The CSDL defines it as:

      <EnumType Name="attackSimulationOperationType">
        <Member Name="createSimualation" Value="0" />
        <Member Name="updateSimulation" Value="1" />
        <Member Name="unknownFutureValue" Value="2" />
      </EnumType>

Suggestion
```suggestion
|type|attackSimulationOperationType|The attack simulation operation type. Possible values are: `createSimulation`, `updateSimulation`, `unknownFutureValue`.|

### attackSimulationOperationType values

|Member|Description |
|:---|:---|
|createSimulation| The simulation creation operation. |
|updateSimulation| The simulation update operation. |
|unknownFutureValue| The operation is not defined. |
```

2022-12-28 14:51 UTC, isvargasmsft commented on api-reference/beta/resources/accounttargetcontent.md
> +
According to the CSDL this resource is a complex type. Do these methods belong to this complex type or should they be documented in a different entity type?

2022-12-28 14:52 UTC, isvargasmsft commented on api-reference/beta/resources/accounttargetcontent.md
> +|type|[accountTargetContentType](#accounttargetcontenttype-values)| The type of account target content. Possible values are: `unknown`, `addressBook`, `includeAll`, `unknownFutureValue`.|
```suggestion
|type|[accountTargetContentType](#accounttargetcontenttype-values)| The type of account target content. Possible values are: `unknown`, `includeAll`, `addressBook`, `unknownFutureValue`.|
```

2022-12-28 15:03 UTC, isvargasmsft commented on api-reference/beta/resources/payload.md
> +|unknownFutureValue| Evolvable enumeration sentinel value. Do not use. |
This one is already documented in the enums.md file.

```suggestion
```

2022-12-28 15:05 UTC, isvargasmsft commented on api-reference/beta/resources/simulation.md
> +|unknownFutureValue| Evolvable enumeration sentinel value. Do not use. |
Please order them as defined in the CSDL. 
```suggestion
### simulationContentSource values

|Member|Description |
|:---|:---|
|unknown| The simulation content source is not defined. |
|global| The simulation content status is global. |
|tenant| The simulation content source is tenant. |
|unknownFutureValue| Evolvable enumeration sentinel value. Do not use. |
```

2022-12-28 15:09 UTC, isvargasmsft commented on api-reference/beta/api/attacksimulationroot-create-simulation.md
> +In the request body, supply a JSON representation of **customers** object.
Please add a link to the customers resource type and include a table with the necessary properties to be initiated.

2022-12-28 15:10 UTC, isvargasmsft commented on api-reference/beta/api/attacksimulationroot-delete-simulation.md
> +In the request body, supply a JSON representation of **simulation** object.
Does this operation really need a JSON representation in the request body? It is a delete, usually just the ID in the path is enough. Please clarify or update the sentence.

2022-12-28 15:13 UTC, isvargasmsft commented on api-reference/beta/api/attacksimulationroot-update-simulation.md
> +In the request body, supply a JSON representation of **simulation** object.
Please provide a link to the simulation resource type and add a table with the properties. You can copy the properties table from the resource topic.

2022-12-28 15:16 UTC, isvargasmsft requested changes
Hello @yadavgaurav121, 

Thank you very much for your hard work in this PR. It is in very good shape in general. 

Please take a look at some final comments I left for completeness and consistency. 

In addition, if you have the time, we'd deeply appreciate if you can add an example using the $select query parameters in the GET operations. We want to promote the use of $select to make calls more efficient. 

Thank you, 

Isaac

2022-12-29 04:11 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|language|String|Unique identifier for the attack simulation payload.|
updated

2022-12-29 04:11 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|:---|:---|:---|
updated

2022-12-29 04:13 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationoperation.md
> +|updateSimulation| The simulation update operation. |
updated

2022-12-29 04:15 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationoperation.md
> +|updateSimulation| The simulation update operation. |
updated

2022-12-29 04:15 UTC, yadavgaurav121 commented on api-reference/beta/resources/attacksimulationoperation.md
> +
this seems duplicate comment

2022-12-29 04:17 UTC, yadavgaurav121 commented on api-reference/beta/resources/accounttargetcontent.md
> +|type|[accountTargetContentType](#accounttargetcontenttype-values)| The type of account target content. Possible values are: `unknown`, `addressBook`, `includeAll`, `unknownFutureValue`.|
updated

2022-12-29 04:18 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|unknownFutureValue| Evolvable enumeration sentinel value. Do not use. |
removed from here

2022-12-29 04:19 UTC, yadavgaurav121 commented on api-reference/beta/resources/simulation.md
> +|unknownFutureValue| Evolvable enumeration sentinel value. Do not use. |
updated

2022-12-29 04:23 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-update-simulation.md
> +In the request body, supply a JSON representation of **simulation** object.
updated

2022-12-29 04:25 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-delete-simulation.md
> +In the request body, supply a JSON representation of **simulation** object.
removed the request portion

2022-12-29 04:25 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-create-simulation.md
> +In the request body, supply a JSON representation of **customers** object.
updated

2022-12-29 04:28 UTC, yadavgaurav121 commented on api-reference/beta/resources/accounttargetcontent.md
> +
makes sense, moved it to simulation.md

2022-12-29 06:12 UTC, yadavgaurav121 commented
@isvargasmsft Thanks for looking into the pr and helping us close this. 
I have addressed your comments. Please have a re-look.

2022-12-29 13:30 UTC, isvargasmsft commented on api-reference/beta/resources/attacksimulationoperation.md
> +|unknownFutureValue| The operation is not defined. |
```suggestion
|unknownFutureValue| Evolvable enumeration sentinel value. Do not use. |
```

2022-12-29 13:35 UTC, isvargasmsft commented on api-reference/beta/api/attacksimulationroot-create-simulation.md
> +|status|[simulationStatus](../resources/simulation.md#simulationstatus-values)|Status of the attack simulation and training campaign. Supports `$filter` and `$orderby`. Possible values are: `unknown`
Are all of these properties **required** to create the simulation object?

2022-12-29 13:54 UTC, isvargasmsft approved these changes

2022-12-30 13:49 UTC, isvargasmsft approved these changes

2023-01-02 22:25 UTC, JarbasHorst commented on api-reference/beta/resources/payload.md
> +|brand|[payloadBrand](#payloadbrand-values)|The branch of a payload. Possible values are: `unknown`, `americanExpress`, etc|
Unfortunately, we can't just add "etc" to describe the possible values for an enum. Please, add the full list of supported values for this enum.

Same for:
- industry
- theme

2023-01-02 22:25 UTC, JarbasHorst commented on api-reference/beta/resources/emailpayloaddetail.md
> +|isExternalSender|Boolean|Email address of the user.|
Please, update the description of the isExternalSender property.

2023-01-02 22:32 UTC, JarbasHorst commented
Hello @yadavgaurav121, I checked your PR again and left some comments. Please, take a look when you will have time.

2023-01-03 03:20 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-delete-simulation.md
> +## Optional query parameters
updated

2023-01-03 03:21 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-delete-simulation.md
> +|Content-Type   |application/json         |
removed

2023-01-03 03:25 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
> +
It doesn't support the optional query params. Same is applicable for other two ref shared.

2023-01-03 03:33 UTC, yadavgaurav121 commented on changelog/Microsoft.Security.AttackSimulation.json
> +          "ChangedApiName": "accountType",
accountType,addressBookAccountType : is not used anywhere in docs or in api.md : removed from changelog
payloadSource and payloadStatus property are removed and simulationContentSource. simulationContentStatus  is used instead.

2023-01-03 03:37 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|other| Payload payloadTheme as other|
updated

2023-01-03 03:38 UTC, yadavgaurav121 commented on api-reference/beta/resources/simulation.md
> +|global| The simulation content status is global. |
updated

2023-01-03 03:42 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +### payloadBrand values
Yes it is a brand. 
It is being modelled in backend and graph as SyrinxCloud only. Cannot accept the suggestion.

2023-01-03 03:43 UTC, yadavgaurav121 commented on api-reference/beta/resources/emailpayloaddetail.md
> +|isExternalSender|Boolean|Email address of the user.|
updated

2023-01-03 03:59 UTC, yadavgaurav121 commented on api-reference/beta/resources/payload.md
> +|brand|[payloadBrand](#payloadbrand-values)|The branch of a payload. Possible values are: `unknown`, `americanExpress`, etc|
updated

2023-01-03 04:01 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-list-payloads.md
> +Get a list of attack simulation campaigns payload.
updated

2023-01-03 04:04 UTC, yadavgaurav121 commented
@Jarbas-MSFT I have addressed the comments but its not very good experience as after the approval we thought this pr doesn't need any active effort. 
Having said that I do understand your thoughts and thanks for heling us through this pr. Just one suggestion is to provide the feedback in one go instead of giving comments in chunks. 
I have addressed your comments and hope it doesn't need more effort.

2023-01-03 04:15 UTC, yadavgaurav121 commented
@Jarbas-MSFT 
Due to recent changes as suggested I am getting "Failed to parse table. Index was outside the bounds of the array." 
This seems due to adding all enum values as example. Please help fix it.

2023-01-03 23:27 UTC, JarbasHorst commented
Thanks for addressing the remaining comments, @yadavgaurav121. I replied to your previous feedback via Teams.

2023-01-20 04:04 UTC, merged