Update application-saml-sso-configure-api.md
microsoftgraph/microsoft-graph-docs pull request #18890
Opened 2022-10-17 06:04 UTC by v-hgampala

2022-10-17 06:22 UTC, opbld31 commented
Learn Build status updates of commit _[72571c0](https://github.com/v-hgampala/microsoft-graph-docs/commits/72571c0e43dfb163e9ceb71b0c99f3f8003abd19)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) | [Details](#user-content-45e18454e22c196d15654c03302ecd71-f6d02130)

<a id="45e18454e22c196d15654c03302ecd71-f6d02130"></a>
### [concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md)
 - **Line 685, Column 110**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/keycredential?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210170604247578-18890/BuildReport?accessString=4d36e4c87da0697fe36d4e02745308cf506e8386b71c03ecefb4e19b7da8cfb9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 08:01 UTC, opbld33 commented
Learn Build status updates of commit _[0214b62](https://github.com/v-hgampala/microsoft-graph-docs/commits/0214b621ab09dba0a5773ed1b1a0d6ac98920670)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210170732301453-18890/BuildReport?accessString=c56942874e706dfd7ab798030f442e83ca5cc859c9f496fecca0ddb9b0943ebf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 04:53 UTC, opbld30 commented
Learn Build status updates of commit _[09f2b3c](https://github.com/v-hgampala/microsoft-graph-docs/commits/09f2b3c1c4d8fb20fa58b625a25971a82f0221cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180442536859-18890/BuildReport?accessString=f267899616dfe380de87df868df0aa954dcba9a23515c302d3567a2f99922cd2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 05:11 UTC, opbld30 commented
Learn Build status updates of commit _[f4c48be](https://github.com/v-hgampala/microsoft-graph-docs/commits/f4c48bebf67b4d54575d76bd70dfc62518e030c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180459395355-18890/BuildReport?accessString=ce52baf561aa622d0f1f21f271dc6eb4194ff81049f6853433c706bbb94299cd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 05:19 UTC, v-hgampala commented
> @v-hgampala This heading " Create a signing certificate (AzureAD)" should be replaced with " Create a signing certificate generated by AzureAD". Otherwise everything else looks good to me.

@jeevansd, the heading is changed as suggested, please review it again. Thanks

2022-10-18 07:16 UTC, FaithOmbongi commented
@AllisonAm for technical review

2022-10-19 20:12 UTC, jeevansd commented
@FaithOmbongi I have reviewed this and looks good. @AllisonAm Can you please take a look at it?

2022-10-19 20:13 UTC, jeevansd commented
@AllisonAm Also need your sign off here. Providing visibility to @eringreenlee as you are our doc champ here!! Yes, and you got a new badge today, Erin!!

2022-10-21 20:59 UTC, jeevansd commented
#sign-off

2022-10-31 08:02 UTC, FaithOmbongi commented
Hi @AllisonAm, @eringreenlee - could you complete the technical review and approve the PR so I can do the content review? Thanks.

2022-11-01 21:38 UTC, jeevansd commented
@AllisonAm Can you please approve this PR?

2022-11-07 07:16 UTC, FaithOmbongi requested changes
Thank you @v-hgampala for your work on this PR. I've requested a few changes prior to approval.

2022-11-07 07:16 UTC, FaithOmbongi commented on concepts/application-saml-sso-configure-api.md
> +### Create a custom signing certificate
```suggestion
### Option 2: Create a custom signing certificate
```

2022-11-07 07:16 UTC, FaithOmbongi commented on concepts/application-saml-sso-configure-api.md
> +### Add a custom signing key
You've confirmed internally that this is required step when you use the C# code
```suggestion
#### Add a custom signing key
```

2022-11-07 07:16 UTC, FaithOmbongi commented on concepts/application-saml-sso-configure-api.md
> +Add the following information to the service principal:
```suggestion
After running the previous code, extract the values for the following parameters from the PFX file. You will add this information to the service principal:
```

2022-11-07 07:16 UTC, FaithOmbongi commented on concepts/application-saml-sso-configure-api.md
> +Extract the private and public key Base64 encoded from the PFX file. To learn more about the properties, see [keyCredential resource type](/graph/api/resources/keycredential?view=graph-rest-1.0&prese
```suggestion
For more information about the properties, see [keyCredential resource type](/graph/api/resources/keycredential).
```

2022-11-07 07:16 UTC, FaithOmbongi commented on concepts/application-saml-sso-configure-api.md
> +{
```suggestion
<!-- {
  "blockType": "request",
  "name": "tutorial_configure_saml_sso_add_credentials"
}-->
```http
PATCH https://graph.microsoft.com/v1.0/servicePrincipals/f47a6776-bca7-4f2e-bc6c-eec59d058e3e
Content-type: application/json

{
```

2022-11-07 07:16 UTC, FaithOmbongi commented on concepts/application-saml-sso-configure-api.md
> +#### Request
```suggestion
##### Request
```

2022-11-07 07:16 UTC, FaithOmbongi commented on concepts/application-saml-sso-configure-api.md
> +} -->
```suggestion
##### Response

<!-- {
  "blockType": "response",
  "truncated": true
} -->
```

2022-11-07 23:13 UTC, jeevansd commented
Changes looks correct to me. But Allison needs to sign off here.

2022-11-21 19:49 UTC, AllisonAm approved these changes
Changes look good to me!

2022-11-23 07:59 UTC, FaithOmbongi commented
Hi @v-hgampala - Allison has given her technical approval. Please address the content feedback so we can merge the doc.

2022-11-23 09:16 UTC, opbld33 commented
Learn Build status updates of commit _[05bdc72](https://github.com/v-hgampala/microsoft-graph-docs/commits/05bdc72860a1a42002865e527c126dd85f8b9ad6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) | [Details](#user-content-45e18454e22c196d15654c03302ecd71-f67d1973)

<a id="45e18454e22c196d15654c03302ecd71-f67d1973"></a>
### [concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md)
 - **Line 930, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211230914138206-18890/BuildReport?accessString=5e255d3dc4399d0f3d6a47640d5e507b3f9d8edbe922a90a79881290a4299548).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 09:31 UTC, v-hgampala commented
> Hi @v-hgampala - Allison has given her technical approval. Please address the content feedback so we can merge the doc.

Please merge the PR, content modified as suggested.

2022-11-23 09:35 UTC, opbld31 commented
Learn Build status updates of commit _[fe11bab](https://github.com/v-hgampala/microsoft-graph-docs/commits/fe11bab5549ab65af80831b9d56459a93f4bfdd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) | [Details](#user-content-45e18454e22c196d15654c03302ecd71-fad12747)

<a id="45e18454e22c196d15654c03302ecd71-fad12747"></a>
### [concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md)
 - **Line 930, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211230932478790-18890/BuildReport?accessString=0017d986f6fd6f74844027ec44c606d7746792d0c8243ae2fa0967b80f9d1ab2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 15:06 UTC, opbld34 commented
Learn Build status updates of commit _[fed1607](https://github.com/v-hgampala/microsoft-graph-docs/commits/fed16079f3355d0b5f476d085c4f669084fbbc8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211231503470901-18890/BuildReport?accessString=46fafe7caa7a7efb822292a3841373564e642f3cc29afa56ab5d6a7c1236a586).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 15:51 UTC, opbld34 commented
Learn Build status updates of commit _[8da5bf9](https://github.com/v-hgampala/microsoft-graph-docs/commits/8da5bf96e4fa30e27ba4e95e6270d5a01a5f7434)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/application-saml-sso-configure-api.md](https://github.com/v-hgampala/microsoft-graph-docs/blob/saml-sso-configure-api/concepts/application-saml-sso-configure-api.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?branch=pr-en-us-18890) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211231548588183-18890/BuildReport?accessString=5d78b7da05f319b8b6f81314c560b5b062b2d2eeaa6c042f72292499a8394236).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 16:49 UTC, FaithOmbongi approved these changes

2022-11-23 16:55 UTC, merged