Adding SharePoint Premium API Docs
microsoftgraph/microsoft-graph-docs pull request #18908
Opened 2022-10-18 00:26 UTC by AdwoodMicrosoft

Adding TOC and relevant docs for monetized APIs

2022-10-18 00:29 UTC, opbld32 commented
Learn Build status updates of commit _[fcd1303](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/commits/fcd130303fa6a26823283e6e910cba9d9c2400b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-18908) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-6f863ef4)
[concepts/onedrive-sharepoint-payment-overview](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/onedrive-sharepoint-payment-overview) | :white_check_mark:Succeeded | |

<a id="d6641161fd46c78dd4128bccd65500b6-6f863ef4"></a>
### [concepts/toc.yml](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/toc.yml)
 - **Line 305, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'onedrive-sharePoint-payment-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180026128199-18908/BuildReport?accessString=cc6c2524dfabc3c04ed6e859d4c2190cc3f16078e1074aa5eca89bfbb249d4d8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 00:31 UTC, opbld34 commented
Learn Build status updates of commit _[065deef](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/commits/065deef0944794810bead70cb899cd73629e046b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-18908) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-30073f01)
[concepts/onedrive-sharepoint-payment-overview](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/onedrive-sharepoint-payment-overview) | :white_check_mark:Succeeded | |

<a id="d6641161fd46c78dd4128bccd65500b6-30073f01"></a>
### [concepts/toc.yml](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/toc.yml)
 - **Line 305, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'onedrive-sharePoint-payment-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210180029304305-18908/BuildReport?accessString=ca56fc94c0031dcc9bdfcc7a64c43d3dcca93555da12226d2cf7b4aa46dcceca).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 23:10 UTC, angelgolfer-ms commented on concepts/onedrive-sharepoint-payment-overview
> +
Line 7 and GLOBAL:
@AdwoodMicrosoft , from the Microsoft Graph API release perspective, APIs that exist in the beta metadata and not marked hidden are in public preview. And, Microsoft Graph docs in general do not include private preview APIs. For these reasons, we cannot represent this API here as in "private preview". That would confuse our internal folks and external customers.

2022-11-10 23:12 UTC, angelgolfer-ms commented on concepts/onedrive-sharepoint-payment-overview
> +# Payment requirements for the OneDrive and SharePoint APIs
This topic file needs to be specified with a .md extension. Otherwise it's not staging.

2022-11-10 23:20 UTC, angelgolfer-ms commented on concepts/toc.yml
>              href: onedrive-addressing-driveitems.md
Per our discussion during the walkthrough, since some customers have assumed "Files" <-> OneDrive APIs and "Sites and lists" <-> SharePoint APIs as exposed on Microsoft Graph, i.e., "sites and lists" are not only about sites and lists but also files that exist on SP document libraries. From that perspective, and from the perspective that the topic title and introduction mention both OneDrive and SharePoint, please add an entry point to this concept topic under the "Sites and lists" node as well in the conceptual section.

2022-11-10 23:23 UTC, angelgolfer-ms requested changes
@AdwoodMicrosoft , I did a superficial review based on our discussions at the walkthrough. Please take a look at my comments.
Laura will be able to provide her feedback as the main content reviewer.

2022-11-11 00:32 UTC, opbld34 commented
Learn Build status updates of commit _[3bece05](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/commits/3bece050ef1b5c97e56d259bd9741ea82a55a914)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/onedrive-sharepoint-payment-overview.md](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/onedrive-sharepoint-payment-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/onedrive-sharepoint-payment-overview?branch=pr-en-us-18908) | [Details](#user-content-e5a86ab5a6e79966e0d9deabce2de5ee-fc5637dd)
[concepts/toc.yml](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/onedrive-sharepoint-payment-overview?branch=pr-en-us-18908) |

<a id="e5a86ab5a6e79966e0d9deabce2de5ee-fc5637dd"></a>
### [concepts/onedrive-sharepoint-payment-overview.md](https://github.com/AdwoodMicrosoft/microsoft-graph-docs/blob/main/concepts/onedrive-sharepoint-payment-overview.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 9, Column 17**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory//' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 9, Column 172**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscriptionp://' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 17, Column 55**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'hhttps://learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&tabs=httpttp://' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 341**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/cost-management-billing/microsoft-customer-agreementp://' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 27, Column 294**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/cost-management-billing' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 29, Column 31**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/marketplace/azure-consumption-commitment-enrollment' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'hhttps://learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&tabs=httpttp://' references a disallowed domain 'hhttps://learn.microsoft.com'. This poses a security risk.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 7, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'http://https://learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 9, Column 17**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory//' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 9, Column 172**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscriptionp://' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 55**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'hhttps://learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&tabs=httpttp://' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 55**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: hhttps://learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&tabs=httpttp://`````
 - **Line 24, Column 341**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/cost-management-billing/microsoft-customer-agreementp://' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 27, Column 294**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/cost-management-billing' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 29, Column 31**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/marketplace/azure-consumption-commitment-enrollment' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211110029278611-18908/BuildReport?accessString=73784cfc3f56255dd2b79ef03a25bb6054d3d02e27567dbc987b632bc8ea515e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub or [...]

2022-11-11 03:43 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> +- [AssignSensitivityLabel API](http://https://learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&tabs=http "AssignSensitivityLabel API") [Private Preview] – Asy
What do we mean when we say that this API is in "private preview"? In the assignSensitivityLabel topic, we mention that it's a protected API and that users need to request access. However, the API is exposed in the public metadata and is not hidden, so it's not technically "private".

Is there a relationship between the fact that the API is protected/requires users to request access, and the fact that the API has consumption charges? 

I recommend that instead of labeling the API as Private Preview here, you add a note similar to callout in the API topic that mentions that the API is protected, and users must request access.

2022-11-11 03:54 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> +# Payment requirements for the OneDrive and SharePoint APIs
This title might convey that the OneDrive and SharePoint APIs require payment, when in fact only some/one API is monetized. Consider changing the title to "Licensing and payment model for OneDrive and SharePoint APIs".

2022-11-11 03:58 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> +This article describes the licensing and payment requirements for the SharePoint and OneDrive APIs in Microsoft Graph.
We mention that this article describes licensing and payment requirements for SharePoint and OneDrive APIs. However, the article seems to be specific to the sensitivity label API, without providing the overall context around licensing and billing for use of APIs. Do you expect that there will be more monetized APIs for SharePoint and OneDrive in the future? If so, I recommend that you make this content general to the licensing requirements and payment model that applies/will apply to these APIs.

2022-11-11 04:01 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> +## Licensing model at General Availability
The API is currently only available in beta/preview. So are you saying that the billing model will only apply when the API reaches GA? And what do we mean by "licensing" model here when in the text you reference "billing" model? What is the licensing requirement for the API, and does the licensing requirement apply while the API is in beta or only when it reaches GA?

If the latter, does it make sense to wait to publish information about the licensing model until the API is GA? And in the meantime, mention in the API topic that "licensing and payment requirements will apply to the API when it reaches GA"?

2022-11-11 04:04 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> +The following APIs have consumption charges:
I recommend covering the payment model in general in this article before getting into the specific list of monetized APIs. For example, what are the charges per call, is there any seeded capacity, where can BDMs go to learn about what the charges will be? Then the article might have a list a bit later of the APIs that entail payment requirements or require some sort of a license.

2022-11-11 04:15 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> + Note: You must [associate](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory// "associate") or [create](https://docs.micros
Will this apply to any/all monetized APIs in the future? If so, I recommend phrasing this as a general requirement for current and future APIs. This might fall under a heading like "Prerequisites for using monetized APIs", and the text can be along the lines of the following:

"Before you can use premium OneDrive or SharePoint APIs, you must associate your Azure subscription with your tenant, or create a new Azure subscription and associate it with your tenant. While the APIs are in preview, an Azure billing statement will be created for you to see the details of the transactions; however, you will not be charged for API calls until the APIs are generally available."

Will all monetized APIs for OneDrive and SharePoint require users to enroll in a private preview, or is that unique/specific to assignSensitivityLabel? If the former, then you might want to add a generalized statement such as:

"To start using premium APIs while they are in preview, you must first request access."

{I think we're referring to monetized APIs as "premium" APIs. If that is the public term that has been established, we should use it in this context.)

2022-11-11 04:17 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> +For your application to enroll in the Preview to call [AssignSensitivityLabel](hhttps://learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&tabs=httpttp:// "Assi
Because we already call out that they must enroll/request access in the API topic, do we need to repeat that information here? Unless it applies more generally to future premium API, in which case, you might want to make a more general statement, per my previous comment.

2022-11-11 04:28 UTC, Lauragra commented on concepts/onedrive-sharepoint-payment-overview.md
> +# Payment requirements for the OneDrive and SharePoint APIs
You'll want to update the assignSensititvityLabel API topic to include a cross-reference to this topic, which I imagine will have more general information about premium APIs for SharePoint and OneDrive. In that topic currently, we mention that the API is protected, and requires users to request access, but we don't specifically mention that it will be a premium (monetized) API, when it reaches GA.

2023-01-18 15:01 UTC, closed without merging