#ATCP Added list call
microsoftgraph/microsoft-graph-docs pull request #18906
Opened 2022-10-17 21:35 UTC by ManojReddy-MSFT

Added an example which shows how to retrieve the custom security attributes. We do not display the information by default and it's not intuitive so added it to the document

2022-10-17 22:13 UTC, opbld31 commented
Learn Build status updates of commit _[9304c76](https://github.com/ManojReddy-MSFT/microsoft-graph-docs/commits/9304c7663b50251ee23eca6d1d1a281146af229a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/custom-security-attributes-examples.md](https://github.com/ManojReddy-MSFT/microsoft-graph-docs/blob/patch-2/concepts/custom-security-attributes-examples.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/custom-security-attributes-examples?branch=pr-en-us-18906) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210172135178885-18906/BuildReport?accessString=bf2f8b933a1718b23fc568ee90a2f8faa2b2eef9bff0826d2dbb55be01f4470d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 00:27 UTC, Lauragra commented
@ManojReddy-MSFT , can you please follow the Get started steps to set yourself up to be a contributor to the repo? https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started

2022-10-18 06:50 UTC, FaithOmbongi requested changes
Thank you @ManojReddy-MSFT for your proposed changes. I've left suggestions for minor fixes.

(Suggestion) We should also consider an example of LIST that applies $filter.

2022-10-18 06:50 UTC, FaithOmbongi commented on concepts/custom-security-attributes-examples.md
> +### Example 1: List a single-valued custom security attribute assigned to a user
"Get" over "List" for showing /users/{id}. List is more suitable for /users collection.
```suggestion
### Example 1: Get the custom security attributes assigned to a user
```

2022-10-18 06:50 UTC, FaithOmbongi commented on concepts/custom-security-attributes-examples.md
> +The following example shows how to list a custom security attribute assignment assigned to the user.
```suggestion
The following example shows how to list a custom security attribute assignment assigned to the user. The custom security attribute is a multi-string value with the following settings:
```

2022-10-18 06:50 UTC, FaithOmbongi commented on concepts/custom-security-attributes-examples.md
> +- Attribute value: `Redmond`
Let's show that this is a multi-string value
```suggestion
- Attribute data type: Collection of Strings
- Attribute value: ["Redmond"]
```

2022-10-18 06:50 UTC, FaithOmbongi commented on concepts/custom-security-attributes-examples.md
> +  "name": "customsecurityattribute_remove_from_user_singlevalue"
```suggestion
  "name": "customsecurityattribute_get_for_user"
```

2022-10-18 06:50 UTC, FaithOmbongi commented on concepts/custom-security-attributes-examples.md
> +  "name": "customsecurityattribute__from_user_singlevalue"
Maintain the example name for traceability
```suggestion
  "name": "customsecurityattribute_remove_from_user_singlevalue"
```

2022-10-27 19:31 UTC, opbld31 commented
Learn Build status updates of commit _[847e667](https://github.com/ManojReddy-MSFT/microsoft-graph-docs/commits/847e6679571edb848766e6f216949a6d2cdc2e89)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/custom-security-attributes-examples.md](https://github.com/ManojReddy-MSFT/microsoft-graph-docs/blob/patch-2/concepts/custom-security-attributes-examples.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/custom-security-attributes-examples?branch=pr-en-us-18906) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271928135048-18906/BuildReport?accessString=5e5eb31008a7169cdd48b7a04580fb275560ec683a51db3593fd1748a3ee78cb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 19:33 UTC, ManojReddy-MSFT commented
Thanks for the suggestions. I have committed them.  I will create another PR to add the filter example to this

2022-10-27 19:33 UTC, opbld33 commented
Learn Build status updates of commit _[23e2f6c](https://github.com/ManojReddy-MSFT/microsoft-graph-docs/commits/23e2f6c33a8fdb212aef88aa419c7d60e44e6ada)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/custom-security-attributes-examples.md](https://github.com/ManojReddy-MSFT/microsoft-graph-docs/blob/patch-2/concepts/custom-security-attributes-examples.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/custom-security-attributes-examples?branch=pr-en-us-18906) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271928333626-18906/BuildReport?accessString=1b7ebfda09418558acb0b0e3c3113f9026cce822e01bd3245808f535b43b531f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 07:19 UTC, FaithOmbongi approved these changes
Thank you @ManojReddy-MSFT. Approved for merge.

2022-11-01 02:10 UTC, merged