Update onpremisespublishing.md
microsoftgraph/microsoft-graph-docs pull request #18942
Opened 2022-10-21 20:50 UTC by dhruvinrshah

App Segments related changes for Complex Apps GA

2022-10-21 21:06 UTC, opbld30 commented
Learn Build status updates of commit _[fb648a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb648a12989e298371e6857f7063ef997344a47c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-72d237eb)

<a id="72d237eb"></a>
###
 - **Line 0, Column 0**: **[Error: git-clone-failed]** `````Failure to clone the repository `https://github.com/MicrosoftDocs/azure-docs/#main`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````
 - **Line 0, Column 0**: **[Error: git-clone-failed]** `````Failure to clone the repository `https://github.com/MicrosoftDocs/azure-docs/#main`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210212050451044-18942/BuildReport?accessString=a5789b720c552e055bffa0de379a036edb6ab9ec9e38e9b165ab8ec9f7342a04).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 20:07 UTC, opbld34 commented
Learn Build status updates of commit _[c8809dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8809dd6fd305e0b04c217f2bcd28aff04cedee9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210272004359735-18942/BuildReport?accessString=7217adc5239561cbf9f6169f2d6bc405032f680b63b590ad17aa6cbd11965f41).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 20:18 UTC, opbld32 commented
Learn Build status updates of commit _[dba4b99](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dba4b99d3bd9a89f02000dfbfc236a7fd9797fc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210272015464743-18942/BuildReport?accessString=fe48c1b2dff94a4d8718cd967117915d2c8f12dec345f74addc4a27878066660).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 21:00 UTC, opbld32 commented
Learn Build status updates of commit _[38e1645](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38e1645c9b1fc40a5c187cadc2617929acaa0c00)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-349a98d540ddf811f1da1205fd2aef0f-b7d83b91)
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="349a98d540ddf811f1da1205fd2aef0f-b7d83b91"></a>
### [api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md)
 - **Line 43, Column 24**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'segmentsConfiguration.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210312058166918-18942/BuildReport?accessString=cf53cabeabd092fd003932a42cb7955a48272b6ae5761727e9391927b2853863).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 21:03 UTC, opbld30 commented
Learn Build status updates of commit _[8cffffb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cffffbd8da163eebe7a00c959b44d52b5af2955)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-349a98d540ddf811f1da1205fd2aef0f-5ec4fd76)
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="349a98d540ddf811f1da1205fd2aef0f-5ec4fd76"></a>
### [api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md)
 - **Line 43, Column 24**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'segmentsConfiguration.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210312100149757-18942/BuildReport?accessString=9ed1072879ba57fcedd66fcb56517a4b5c9031a3d54b2f6655364260a0f46687).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 21:06 UTC, opbld33 commented
Learn Build status updates of commit _[12c28ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12c28ac9b2612888059c291900934976b0d5095f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-349a98d540ddf811f1da1205fd2aef0f-edde1785)
[api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="349a98d540ddf811f1da1205fd2aef0f-edde1785"></a>
### [api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md)
 - **Line 43, Column 24**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'segmentsConfiguration.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210312101234436-18942/BuildReport?accessString=a67500b562324d467f7e5918343f01dfe143614e155d1f48d660b7a204e9fff8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 21:23 UTC, opbld33 commented
Learn Build status updates of commit _[8cefc0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cefc0e7d998baa21fe323e149af7c693ab01866)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/segmentsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/segmentsConfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/segmentsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-f007f7154e93521dd2a71b3a403a0741-f2e71071)
[api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="f007f7154e93521dd2a71b3a403a0741-f2e71071"></a>
### [api-reference/beta/resources/segmentsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/segmentsConfiguration.md)
 - **Line 17, Column 3**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'webApplicationSegment.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210312120390088-18942/BuildReport?accessString=11cca0db8a9a8f43737cc1e53e1f9534ebd1b035fa2b0d9c4e8642f3465094b1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 21:37 UTC, opbld30 commented
Learn Build status updates of commit _[0fbf05e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0fbf05e1d233e1e1d6fa9a5feda384f166bbdbbd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/webApplicationSegment.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/webapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-04fd334639e86ddeecc6e6677676c5c5-f5c257d1)
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-ac7308234340062c362fc591099b6f0d-f5c257d1)
[api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/segmentsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/segmentsConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/segmentsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="04fd334639e86ddeecc6e6677676c5c5-f5c257d1"></a>
### [api-reference/beta/resources/webApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/webApplicationSegment.md)
 - **Line 25, Column 21**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'corsconfigurationv2.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents onPremisesApplicationSegment object when publishing an on-premises wildcard application with Azure AD Application Proxy.' is duplicated in 'beta/resources/onpremisesapplicationsegment.md(3,14)', 'beta/resources/webApplicationSegment.md(3,14)'.`````

<a id="ac7308234340062c362fc591099b6f0d-f5c257d1"></a>
### [api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents onPremisesApplicationSegment object when publishing an on-premises wildcard application with Azure AD Application Proxy.' is duplicated in 'beta/resources/onpremisesapplicationsegment.md(3,14)', 'beta/resources/webApplicationSegment.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210312135373879-18942/BuildReport?accessString=a4150e43cf93efd9ffb8b6e759e28f55521d51c175809359dd08b7ed68e09059).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 21:58 UTC, dhruvinrshah commented on api-reference/beta/resources/segmentsConfiguration.md
> ++ [webApplicationSegment](webApplicationSegment.md)
Change to WebSegmentConfiguration

2022-10-31 22:02 UTC, dhruvinrshah commented on api-reference/beta/resources/webApplicationSegment.md
> +Inherits from [segmentsConfiguration](segmentsConfiguration.md).
Add applicationSegment and link here

2022-10-31 22:07 UTC, dhruvinrshah commented on api-reference/beta/resources/segmentsConfiguration.md
> ++ [webApplicationSegment](webApplicationSegment.md)
WebSegmentConfiguration -- ApplicationSegment as collection

2022-10-31 22:09 UTC, opbld33 commented
Learn Build status updates of commit _[d5dbbe4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5dbbe466f77e778ac473dfbd070ed3b09401c69)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/webApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/webApplicationSegment.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/webapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-04fd334639e86ddeecc6e6677676c5c5-8d7d487e)
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-ac7308234340062c362fc591099b6f0d-8d7d487e)
[api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/segmentsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/segmentsConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/segmentsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="04fd334639e86ddeecc6e6677676c5c5-8d7d487e"></a>
### [api-reference/beta/resources/webApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/webApplicationSegment.md)
 - **Line 25, Column 21**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'corsconfigurationv2.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents onPremisesApplicationSegment object when publishing an on-premises wildcard application with Azure AD Application Proxy.' is duplicated in 'beta/resources/onpremisesapplicationsegment.md(3,14)', 'beta/resources/webApplicationSegment.md(3,14)'.`````

<a id="ac7308234340062c362fc591099b6f0d-8d7d487e"></a>
### [api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents onPremisesApplicationSegment object when publishing an on-premises wildcard application with Azure AD Application Proxy.' is duplicated in 'beta/resources/onpremisesapplicationsegment.md(3,14)', 'beta/resources/webApplicationSegment.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210312138256114-18942/BuildReport?accessString=96d0f1f3bbcdd272ccfe7be06539175be9006705839e23fb3e918d0b9eff551d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 22:11 UTC, opbld32 commented
Learn Build status updates of commit _[c7d4400](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7d4400c28338fd10f0a7b02871a0d795c4b472c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-2200a8f589c650105097e71d6f6ede83-6c36588d)
[api-reference/beta/resources/corsconfigurationv2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfigurationv2.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/corsconfigurationv2?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-0a046d28f9a9fc1c4eece110be0e861f-6c36588d)
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-ac7308234340062c362fc591099b6f0d-6c36588d)
[api-reference/beta/resources/webApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/webApplicationSegment.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/webapplicationsegment?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) | [Details](#user-content-04fd334639e86ddeecc6e6677676c5c5-6c36588d)
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[api-reference/beta/resources/segmentsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/segmentsConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/segmentsconfiguration?view=graph-rest-beta&branch=pr-en-us-18942) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="2200a8f589c650105097e71d6f6ede83-6c36588d"></a>
### [api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'corsConfiguration resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/corsconfiguration.md(2,8), beta/resources/corsconfigurationv2.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsconfiguration.md(3,14)', 'beta/resources/corsconfigurationv2.md(3,14)'.`````

<a id="0a046d28f9a9fc1c4eece110be0e861f-6c36588d"></a>
### [api-reference/beta/resources/corsconfigurationv2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfigurationv2.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'corsConfiguration resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/corsconfiguration.md(2,8), beta/resources/corsconfigurationv2.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsconfiguration.md(3,14)', 'beta/resources/corsconfigurationv2.md(3,14)'.`````

<a id="ac7308234340062c362fc591099b6f0d-6c36588d"></a>
### [api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents onPremisesApplicationSegment object when publishing an on-premises wildcard application with Azure AD Application Proxy.' is duplicated in 'beta/resources/onpremisesapplicationsegment.md(3,14)', 'beta/resources/webApplicationSegment.md(3,14)'.`````

<a id="04fd334639e86ddeecc6e6677676c5c5-6c36588d"></a>
### [api-reference/beta/resources/webApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/webApplicationSegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents onPremisesApplicationSegment object when publishing an on-premises wildcard application with Azure AD Application Proxy.' is duplicated in 'beta/resources/onpremisesapplicationsegment.md(3,14)', 'beta/resources/webApplicationSegment.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210312148004803-18942/BuildReport?accessString=fce072a89c11e72e0a0efe855f344b93a55242760cc127cf1d5438a2a7fc1004).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any [...]

2022-11-01 05:57 UTC, opbld30 commented
Learn Build status updates of commit _[8e8e205](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e8e205ffbb566e7ea2b5a63210ba80d5e400629)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9d64f43e)

<a id="9d64f43e"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 8e8e205ffbb566e7ea2b5a63210ba80d5e400629 in branch dhruvinrshah-patch-1 of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit eddc3a33d917c62e99b44e571e13cdf36928a766). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211010556554728-18942/BuildReport?accessString=7b77780e73ce06f6e2061bef28c8e680c824fe5271c00373fcb62b7c6bd433e2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-25 14:35 UTC, FaithOmbongi requested changes
Thank you @dhruvinrshah for your work on this PR.

I've left suggestions inline for changes to descriptions. Please verify technical accuracy and feel free to suggest clearer descriptions.

- Add the isDefaultAccessEnabled property to the [onPremisesPublishingProfile resource type](https://learn.microsoft.com/en-us/graph/api/resources/onpremisespublishingprofile?view=graph-rest-beta).
- You're deprecating the onPremisesApplicationSegments property but it hasn't been retired yet. So keep it in the docs until you officially stop returning it in the API.

General question: Do you publish with app proxy or through app proxy? Is app proxy a publishing service? I have little understanding of on-prem.

2023-01-25 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationsegment.md
> +description: "Represents applicationsegment object when publishing an on-premises wildcard application with Azure AD Application Proxy."
```suggestion
description: "An abstract type that exposes properties used to configure segment configurations that are allowed for an on-premises wildcard application that's published through Azure AD Application Proxy."
```

2023-01-25 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationsegment.md
> +This is an abstract type noting the application segment types when publishing an on-premises wildcard application with Azure AD Application Proxy. The following types are derived from this abstract t
For the first sentence, apply what you apply in Line 3

2023-01-25 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationsegment.md
> +  "id": "String"
```suggestion
  "id": "String (identifier)"
```

2023-01-25 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/onpremisesapplicationsegment.md
> +# onPremisesApplicationSegment resource type (deprecated)
Required for Line 2 (the title) as well

2023-01-25 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/onpremisesapplicationsegment.md
> +|corsConfigurations (deprecated)|[corsConfiguration](corsconfiguration.md) collection|CORS Rule definition for a particular application segment.|
No need for this change here. The title in Line 10 already says "deprecated" and it's a given that all downstream objects, unless explicitly used by other objects/APIs are also deprecated.
```suggestion
|corsConfigurations|[corsConfiguration](corsconfiguration.md) collection|CORS Rule definition for a particular application segment.|
```

2023-01-25 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/corsconfiguration.md
> +# corsConfiguration resource type (deprecated)
Same change in Line 2 (the title)

2023-01-25 14:35 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      ],
Add the deprecation object
```suggestion
        },
        {
      "Id": "448b4105-a8c6-46d6-b2ae-9dee9e9b5f14",
      "ApiChange": "Property",
      "ChangedApiName": "onPremisesApplicationSegments",
      "ChangeType": "Deprecation",
      "Description": "Deprecated the **onPremisesApplicationSegments** property of the [onPremisesPublishing](https://learn.microsoft.com/en-us/graph/api/resources/onPremisesPublishing?view=graph-rest-beta) resource. The **onPremisesApplicationSegments** property will stop returning data on June 1, 2023. Use the **segmentsConfiguration** property instead.",
      "Target": "onPremisesPublishing"
    }
      ],
```

2023-01-25 18:46 UTC, dhruvinrshah commented on api-reference/beta/resources/corsconfiguration.md
> +# corsConfiguration resource type (deprecated)
done

2023-01-25 18:53 UTC, dhruvinrshah commented on api-reference/beta/resources/corsconfiguration_v2.md
> +|allowedOrigins|String Collection|The origin domains that are permitted to make a request against the service via CORS. The origin domain is the domain from which the request originates. The origin m
ty for catching the typo... changed it to "user agent"

2023-01-25 18:56 UTC, dhruvinrshah commented on api-reference/beta/resources/onpremisesapplicationsegment.md
> +# onPremisesApplicationSegment resource type (deprecated)
done

2023-01-26 07:57 UTC, dhruvinrshah commented on api-reference/beta/resources/applicationsegment.md
> +description: "Represents applicationsegment object when publishing an on-premises wildcard application with Azure AD Application Proxy."
Updated as suggested

2023-01-26 07:58 UTC, dhruvinrshah commented on api-reference/beta/resources/applicationsegment.md
> +This is an abstract type noting the application segment types when publishing an on-premises wildcard application with Azure AD Application Proxy. The following types are derived from this abstract t
done

2023-01-26 08:14 UTC, dhruvinrshah commented on api-reference/beta/resources/webapplicationsegment.md
> +Represents a [webApplicationSegment](webapplicationsegment.md) object when publishing an on-premises wildcard application with Azure AD Application Proxy. This resource is used for setting an applica
Added the comment ... removed " that's accessed using HHTP" as application proxy today only support web traffic (HTTP/HTTPS)

2023-01-26 08:14 UTC, dhruvinrshah commented on api-reference/beta/resources/webapplicationsegment.md
> +description: "Represents webApplicationSegment object when publishing an on-premises wildcard application with Azure AD Application Proxy."
Added the comment ... removed " that's accessed using HHTP" as application proxy today only support web traffic (HTTP/HTTPS)

2023-01-26 08:22 UTC, dhruvinrshah commented on api-reference/beta/resources/webapplicationsegment.md
> +|internalUrl|String |The internal URL of the application segment; for example, https://intranet/.|
done

2023-01-26 08:25 UTC, dhruvinrshah commented on api-reference/beta/resources/websegmentconfiguration.md
> +Represents a [webSegmentConfiguration](websegmentconfiguration.md) object when publishing an on-premises wildcard application with Azure AD Application Proxy. This resource is used for setting an app
updated

2023-01-26 08:26 UTC, dhruvinrshah commented on api-reference/beta/resources/websegmentconfiguration.md
> +description: "Represents webSegmentConfiguration object when publishing an on-premises wildcard application with Azure AD Application Proxy."
updated

2023-01-26 08:27 UTC, dhruvinrshah commented on api-reference/beta/resources/websegmentconfiguration.md
> +|applicationSegments|[webApplicationSegment](webapplicationsegment.md) collection|Represents a [webApplicationSegment](webapplicationsegment.md) object when publishing an on-premises wildcard applica
done

2023-01-26 08:29 UTC, dhruvinrshah commented on api-reference/beta/resources/onpremisespublishing.md
> -  "onPremisesApplicationSegments":[{"@odata.type":"microsoft.graph.onPremisesApplicationSegment"}],
added back

2023-01-26 08:33 UTC, dhruvinrshah commented
#feedback-addressed

2023-01-26 08:44 UTC, dhruvinrshah commented
Hi @FaithOmbongi,

Have addressed all the changes requested, kindly review once more and let me know if any further changes are required.

to address open questions --

Add the isDefaultAccessEnabled property to the [onPremisesPublishingProfile resource type](https://learn.microsoft.com/en-us/graph/api/resources/onpremisespublishingprofile?view=graph-rest-beta).
-- This will be added later along with "ipSegmentConfiguration" as it is related to product feature not publicly announced.

General question: Do you publish with app proxy or through app proxy? Is app proxy a publishing service? 
-- Both have been used, technically through is correct (have updated the document to reflect same)

2023-01-26 14:35 UTC, FaithOmbongi approved these changes
Hi @dhruvinrshah - I've left suggestions for minor fixes. Also, I pushed a commit to remove isDefaultAccessEnabled from the changelog because you're not publishing it in this PR. When you document it later, you'll need to add a changelog object for it at that time.

Approved with suggestions.

2023-01-26 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/segmentconfiguration.md
> +An abstract type for defining application segments when publishing an on-premises wildcard application with Azure AD Application Proxy. The following types are derived from this abstract type:
nit
```suggestion
description: "An abstract type for defining application segments when publishing an on-premises wildcard application through Azure AD Application Proxy."
ms.localizationpriority: medium
author: "dhruvinshah"
ms.prod: "applications"
doc_type: "resourcePageType"
---

# segmentConfiguration resource type

Namespace: microsoft.graph

[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]

An abstract type for defining application segments when publishing an on-premises wildcard application through Azure AD Application Proxy. The following types are derived from this abstract type:
```

2023-01-26 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/webapplicationsegment.md
> +## Relationships
nit - space after table
```suggestion

## Relationships
```

2023-01-26 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/webapplicationsegment.md
> +  "externalUrl": "String",
Relationships aren't structural properties so they aren't added to the JSON representation
```suggestion
  "alternateUrl": "String",
  "externalUrl": "String",
```

2023-01-26 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/corsconfiguration_v2.md
> +# corsConfiguration resource type
should match name in schema - otherwise, breaks even downstream SDKs
```suggestion
title: "corsConfiguration_v2 resource type"
description: "Represents the CORS settings for an on-premises web application segment published via Application Proxy."
ms.localizationpriority: medium
author: "dhruvinshah"
ms.prod: "applications"
doc_type: "resourcePageType"
---

# corsConfiguration_v2 resource type
```

2023-01-26 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationsegment.md
> +|id|String|The unique identifier that is assigned to aa application segment by Azure AD. Not nullable. Read-only. Supports `$filter` (`eq`).  |
```suggestion
|id|String|The unique identifier that is assigned to an application segment by Azure AD. Not nullable. Read-only. Supports `$filter` (`eq`).  |
```

2023-01-26 14:35 UTC, FaithOmbongi approved these changes

2023-01-27 03:03 UTC, merged