[Cloud PC] Add the **provisioningType** property to the
microsoftgraph/microsoft-graph-docs pull request #18960
Opened 2022-10-24 09:50 UTC by xinliu22

2022-10-24 09:53 UTC, opbld34 commented
Learn Build status updates of commit _[c541dd6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c541dd682ce49dca524440ccef644029b2393f3a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-84266eaa)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-a9854c9f614e4703ed375d736557d7fd-84266eaa)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-84266eaa)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="8c19544f8e60e9a7f35cfc34390e88df-84266eaa"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a9854c9f614e4703ed375d736557d7fd-84266eaa"></a>
### [api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/virtualendpoint-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0094819f09e3340df09eb0358fea0d24-84266eaa"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/resources/cloudpc.md)
 - **Line 70, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcprovisioningtype-values' in 'beta/resources/cloudpcprovisioningpolicy.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210240950556964-18960/BuildReport?accessString=38fa179f1851edb6c83e109b73aa19399b9c7a4c219181bd3a466064e24db230).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 06:09 UTC, AshleyYangSZ requested changes
@xinliu22 There's build error please update to make the build green

2022-11-09 06:30 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|provisioningType|[cloudPcProvisioningType](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)|Specifies the type of licenses to be used when provisioning Cloud PCs using this
```suggestion
|provisioningType|[cloudPcProvisioningType](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)|Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. Possible values are: `dedicated`, `shared`, `unknownFutureValue`. Default value is dedicated if it's not specified when creating provisioningPolicy. |
```

2022-11-09 06:33 UTC, RuiHou105 requested changes
@xinliu22  Please create a roadmap workitem and attach the workitem number in the comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If you don't have access, please do this firstly to gain access:
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-11-15 06:49 UTC, xinliu22 commented on api-reference/beta/resources/cloudpc.md
> +|provisioningType|[cloudPcProvisioningType](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)|Specifies the type of licenses to be used when provisioning Cloud PCs using this
Applied, thanks for your suggestion!

2022-11-15 06:50 UTC, opbld32 commented
Learn Build status updates of commit _[b6980a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6980a3b6dac85bf7cc6b63e65a659e86ccf41aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-a486332a)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-a9854c9f614e4703ed375d736557d7fd-a486332a)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-a486332a)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="8c19544f8e60e9a7f35cfc34390e88df-a486332a"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a9854c9f614e4703ed375d736557d7fd-a486332a"></a>
### [api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/virtualendpoint-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0094819f09e3340df09eb0358fea0d24-a486332a"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/resources/cloudpc.md)
 - **Line 70, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcprovisioningtype-values' in 'beta/resources/cloudpcprovisioningpolicy.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150648041646-18960/BuildReport?accessString=b1efebed13bfa806e2960238599f41fb10b895013c9a3e7052bce2cff0ee21b8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 06:54 UTC, opbld30 commented
Learn Build status updates of commit _[b3969c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3969c747f30c49eee6364d26f749150312fd486)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-fcf393ee)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-a9854c9f614e4703ed375d736557d7fd-fcf393ee)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-fcf393ee)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18960) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="8c19544f8e60e9a7f35cfc34390e88df-fcf393ee"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a9854c9f614e4703ed375d736557d7fd-fcf393ee"></a>
### [api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/api/virtualendpoint-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0094819f09e3340df09eb0358fea0d24-fcf393ee"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ningjing/addProvisioningTypeResourceApiDoc1/api-reference/beta/resources/cloudpc.md)
 - **Line 70, Column 19**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcprovisioningtype-values' in 'beta/resources/cloudpcprovisioningpolicy.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150649336963-18960/BuildReport?accessString=cfe717858c36763b430a58c63b7fd14b090bd700754b5c60dc613b8a9a9f3ea9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 07:25 UTC, xinliu22 commented
This PR depends on another [PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18537) that under review.

2022-12-15 06:36 UTC, RuiHou105 commented
@xinliu22  @ningjingbogithub  This PR is marked as draft and blocked. Could you please set it as Open and move forward?

2022-12-15 06:47 UTC, xinliu22 commented
@RuiHou105 We are waiting for this [PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18537) being merge, or the "microsoft-graph-docs apidoctor-beta" will always fail. Or is that okay lefting this PR in failure status?

2022-12-15 06:50 UTC, xinliu22 commented
And I'm wondering if we could combine these two PRs as single one.

2023-02-14 05:07 UTC, ningjingbogithub commented
roadmap: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/16483

2023-02-15 04:07 UTC, RuiHou105 approved these changes

2023-02-15 04:08 UTC, RuiHou105 commented
@Lauragra  @JarbasHorst  Hope you can help review this PR when you got time, thanks!

2023-02-22 01:13 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2023-02-28 20:50 UTC, Lauragra approved these changes

2023-03-01 02:12 UTC, AshleyYangSZ approved these changes

2023-03-01 04:34 UTC, merged