add shiftWorkCloudPcAccessState.md in resource and cloudpc-getshiftwo…
microsoftgraph/microsoft-graph-docs pull request #19008
Opened 2022-10-27 04:04 UTC by andrewku0409

…rkcloudpcaccessstate.md in api

2022-10-27 04:06 UTC, opbld31 commented
Learn Build status updates of commit _[ba2c47e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba2c47e233b7acbd7283889804a3a48c4a82bbbd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tsku/addNewGraphApiGetShiftWorkCloudPCAccessStateDocs/api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md) | :x:Error | | [Details](#user-content-43fe0cd622ab0a1ca5933078063d100c-62e7dd57)
[api-reference/beta/resources/shiftWorkCloudPcAccessState.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tsku/addNewGraphApiGetShiftWorkCloudPCAccessStateDocs/api-reference/beta/resources/shiftWorkCloudPcAccessState.md) | :warning:Warning | | [Details](#user-content-2d7deb24a46d58d2c4f4eb4c3baa4f16-62e7dd57)

<a id="43fe0cd622ab0a1ca5933078063d100c-62e7dd57"></a>
### [api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tsku/addNewGraphApiGetShiftWorkCloudPCAccessStateDocs/api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md)
 - **Line 63, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/cloudpcthisgetshiftworkcloudpcaccessstate-csharp-snippets.md'.`````
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/cloudpcthisgetshiftworkcloudpcaccessstate-javascript-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/cloudpcthisgetshiftworkcloudpcaccessstate-java-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/cloudpcthisgetshiftworkcloudpcaccessstate-go-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/cloudpcthisgetshiftworkcloudpcaccessstate-powershell-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/cloudpcthisgetshiftworkcloudpcaccessstate-php-snippets.md'.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 427**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="2d7deb24a46d58d2c4f4eb4c3baa4f16-62e7dd57"></a>
### [api-reference/beta/resources/shiftWorkCloudPcAccessState.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tsku/addNewGraphApiGetShiftWorkCloudPCAccessStateDocs/api-reference/beta/resources/shiftWorkCloudPcAccessState.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'ningjingbo' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210270404192260-19008/BuildReport?accessString=fa6df5a7f2829e54d04e346978a9aa328b84ccab101dfa21a5711428ac1f8e03).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 06:46 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +# [C#](#tab/csharp)
You don't need to manually add this part `# [C#](#tab/csharp)...# [PHP](#tab/php)` as tool will automatically generate it once PR gets merged. So please remove them.

2022-11-09 06:50 UTC, RuiHou105 requested changes
@andrewku0409  
1.Please create a roadmap workitem and attach the workitem number in the comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If you don't have access, please do this firstly to gain access:

- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2.Please also update the changelog

2022-12-15 06:40 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +        - name: Get shift work cloudPc's access state
All APIs should be sorted alphabetically. So please place it after `Get launch info`

2022-12-15 06:42 UTC, RuiHou105 commented
@ningjingbogithub  Please also update the changelog.

2023-02-03 08:42 UTC, RuiHou105 commented
@Lauragra , @JarbasHorst , could you please help review this PR? And one build error: 
![image](https://user-images.githubusercontent.com/77313233/216552763-0d056fc5-c667-4962-bbdc-0841953a3f2a.png)
We're not sure the root cause. Thanks!

2023-02-06 15:12 UTC, Danielabom commented
Contacted author to get info.

2023-02-07 06:44 UTC, ningjingbogithub commented
> @andrewku0409 1.Please create a roadmap workitem and attach the workitem number in the comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If you don't have access, please do this firstly to gain access:
> 
> * Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
> * Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .
> 
> 2.Please also update the changelog

2023-02-07 06:45 UTC, ningjingbogithub commented
roadmap:https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/16438

2023-02-21 21:07 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|[Get shift work cloudPc's access state](../api/cloudpc-getshiftworkcloudpcaccessstate.md)|[shiftWorkCloudPcAccessState](#shiftworkcloudpcaccessstate-values)|Get the access state of the shift work Cl
I am not clear about this operation. If a shift represents a unit of scheduled work, the operation's name might be redundant.

2023-02-21 21:11 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|noLicensesAvailable|Indicates the shift work Cloud PC cannot be assigned any sharedUseLicenses as all shared use licenses are in use as of now.|
Is shareUseLicences a reference to another topic?

2023-02-21 21:19 UTC, Danielabom requested changes
Before I can move on with this review, please add the changelog. Thanks!

2023-02-22 02:44 UTC, ningjingbogithub commented on api-reference/beta/resources/cloudpc.md
> +|[Get shift work cloudPc's access state](../api/cloudpc-getshiftworkcloudpcaccessstate.md)|[shiftWorkCloudPcAccessState](#shiftworkcloudpcaccessstate-values)|Get the access state of the shift work Cl
Windows365 Shift work is a new kind of cloud PC t provide customers' shift work employees, which allows 3 users per cloud PC license with 1 user logged in at a time.

2023-02-22 02:45 UTC, ningjingbogithub commented on api-reference/beta/resources/cloudpc.md
> +|noLicensesAvailable|Indicates the shift work Cloud PC cannot be assigned any sharedUseLicenses as all shared use licenses are in use as of now.|
yes, it is a refer for [microsoft-graph-docs/cloudpcprovisioningpolicy.md at main · microsoftgraph/microsoft-graph-docs (github.com)](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)

2023-02-22 08:40 UTC, ningjingbogithub commented
> 

change log added

2023-02-23 09:21 UTC, RuiHou105 approved these changes

2023-02-23 10:01 UTC, ningjingbogithub commented
@Danielabom changelog added, need your review.

2023-02-24 06:39 UTC, ningjingbogithub commented
@Danielabom , build successfully, need your approve and merge, thank you.

2023-02-27 23:10 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +
Lines 3 and 15:
Hi @andrewku0409 , @ningjingbogithub ,
I work with @Danielabom on the Microsoft Graph docs and she suggested some ways to improve the effectiveness of the description in line 15. I thought I would reply here so to be clearer in the communication; after all, either of you would be the person to take the action to incorporate the feedback.

For line 15 - in general, helpful descriptions should provide more context than just the words that appear in the name of the API element (in this case, the function name). The current description in line 15, or the first sentence in line 3, doesn't explain anything about your main scenario here, "shift work cloud PC", and the who and what for the "access" to make "state" a relevant thing.
Just based on this PR without other info, such as any existing docs about "shift work", I can suggest the following, but if I miss some other pertinent info, please add to the description:
"Get the state of a user's attempt to access a Cloud PC that has been provisioned for sharing for shift work.

For more information about provisioning a Cloud PC for sharing, see the **provisioningType** property of cloudPcProvisioningPolicy {include link to that resource please}."

2023-02-27 23:14 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +If successful, this function returns a `200 OK` response code and a [shiftWorkCloudPcAccessState](../resources/cloudpc.md#shiftworkcloudpcaccessstate-values) object in the response body.
After line 46:
I see in line 3, you mentioned this: "fail with 400 when calling it with dedicated Cloud PC".

You can incorporate that info as a separate paragraph under the "Response" section here.
"If the Cloud PC has been provisioned as a dedicated device, this method returns `400 Bad request`."

2023-02-27 23:18 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +
About the extra content in line 3:
FYI in general, line 3 serves SEO, and we put only the main description (line 15) there. Line 3 shouldn't be a large paragraph of other info, so not to confuse developers why pertinent info is only viewable if they view the source file in MD.
In particular, if the following is helpful for developers, then you'd need to provide more context, for example, what portal are you referring to, etc.
"Current usage scenario: web client needs to support shift work Cloud PC. `SharedCloudPcAccessState` is used to validate the bookmark scenario. If the tab is launched and the sharedCloudPcAccessState is not active/activating, web client will pop the "Bad bookmark" UI to go back to IWPortal to access the Cloud PC.""

2023-02-28 07:36 UTC, ningjingbogithub commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +
@angelgolfer-ms, thanks for your comments, I added more detail description, need your review

2023-03-01 17:27 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +description: "This API is used to get the access state of a shift work Cloud PC, caller can use this API to get the latest shift work Cloud PC accessState and determine if this shift work CloudPC is
```suggestion
description: "Get the access state of a shift work Cloud PC. Callers can get the latest shift work Cloud PC accessState and determine if the shift work CloudPC is accessible to the user."
```

2023-03-01 17:38 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +Shift work Cloud PC is a new type of Cloud PC with new license type "shared" to enable customers' front line. LicenseType see provisioningType property of cloudPcProvisioningPolicy {https://github.co
Shift work Cloud PC is a new type of Cloud PC with a shared-use license that enables _______. Let's find a better description for "front line" because it is not a socialized term in our docs.

2023-03-01 17:51 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +When 'shared' license purchased, allows three users per license with one user logged in at a time. This API is used to get the access state of a shift work Cloud PC, caller can use this API to get th
Please validate if this is the expected flow, for example: is the word message applicable?
```suggestion
Shared-use licenses allow three users per license, with one user logged in at a time. If a web client needs to connect to a shift work Cloud PC, the SharedCloudPcAccessState validates the bookmarked scenario. If sharedCloudPcAccessState is not active/activating/hibernated, the web client shows a "bad bookmark" message and returns to the IWPortal to access the Cloud PC. 
```

2023-03-01 17:51 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +When 'shared' license purchased, allows three users per license with one user logged in at a time. This API is used to get the access state of a shift work Cloud PC, caller can use this API to get th
I am not familiar with the "IW portal" term.

2023-03-01 17:53 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +Current usage: Web Client needs to support shift work Cloud PC connect. SharedCloudPcAccessState is used to validate the bookmark scenario. If the tab is launched and the sharedCloudPcAccessState is
Please validate if this is the expected flow, for example, is the word "message applicable?"
```suggestion
If a web client needs to connect to a shift work Cloud PC, the SharedCloudPcAccessState validates the bookmarked scenario. If sharedCloudPcAccessState is not active/activating/hibernated, the web client shows a "bad bookmark" message and returns to the IWPortal to access the Cloud PC.
```

2023-03-01 17:54 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +Current usage: Web Client needs to support shift work Cloud PC connect. SharedCloudPcAccessState is used to validate the bookmark scenario. If the tab is launched and the sharedCloudPcAccessState is
I am not familiar with the term "IW Portal" what's the official name?

2023-03-01 17:56 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +description: "This API is used to get the access state of a shift work Cloud PC, caller can use this API to get the latest shift work Cloud PC accessState and determine if this shift work CloudPC is
GLOBAL COMMENT (applies to the entire PR): I've seen "cloudpc", "Cloud PC", "CloudPC", "cloud PC" and other variations. What's the valid term?

2023-03-01 17:57 UTC, Danielabom requested changes
@ningjingbogithub , thank you for addressing our comments in such a mindful way. Please see my new observations.

2023-03-02 02:23 UTC, ningjingbogithub commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +description: "This API is used to get the access state of a shift work Cloud PC, caller can use this API to get the latest shift work Cloud PC accessState and determine if this shift work CloudPC is
The valid term should be "Cloud PC", I will uniform them.

2023-03-02 03:42 UTC, ningjingbogithub commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +Current usage: Web Client needs to support shift work Cloud PC connect. SharedCloudPcAccessState is used to validate the bookmark scenario. If the tab is launched and the sharedCloudPcAccessState is
'and returns to the IWPortal to access the Cloud PC'  this information is not important, I will remve this.

2023-03-02 03:43 UTC, ningjingbogithub commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +Shift work Cloud PC is a new type of Cloud PC with new license type "shared" to enable customers' front line. LicenseType see provisioningType property of cloudPcProvisioningPolicy {https://github.co
I changed front line to shift work, which is more easy to understand.

2023-03-02 14:25 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +Shared-use licenses allows three users per license, with one user logged in at a time. Callers can get the latest shift work Cloud PC accessState and determine if the shift work Cloud PC is accessibl
```suggestion
Shared-use licenses allow three users per license, with one user logged in at a time. Callers can get the latest shift work Cloud PC accessState and determine if the shift work Cloud PC is accessible to the user. 
```

2023-03-02 14:29 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +If a web client needs to connect to a shift work Cloud PC, the SharedCloudPcAccessState validates the bookmark scenario. If sharedCloudPcAccessState is not active/activating/hibernated, the web clien
```suggestion
If a web client needs to connect to a shift work Cloud PC, the sharedCloudPcAccessState validates the bookmark scenario. If sharedCloudPcAccessState is not active/activating/hibernated, the web client shows a "bad bookmark".
```

2023-03-02 14:38 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +Fail with 400 when calling it with dedicated Cloud PC.
```suggestion
If the Cloud PC has been provisioned as a dedicated device, this method returns  `400 Bad request`.
```

2023-03-02 17:09 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|hibernated|Indicates the shift work Cloud PC is in the hibernated state before it's shutdown and deallocated. Shift work Cloud PC in hibernated state is still accessible by end user.|
This value did not come up in the CSDL or the api.md files. Please confirm if it is a valid value. Thanks.

2023-03-02 17:12 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|[Get shift work cloudPc's access state](../api/cloudpc-getshiftworkcloudpcaccessstate.md)|[shiftWorkCloudPcAccessState](#shiftworkcloudpcaccessstate-values)|Get the access state of the shift work Cl
```suggestion
|[Get shift work cloudPCs access state](../api/cloudpc-getshiftworkcloudpcaccessstate.md)|[shiftWorkCloudPcAccessState](#shiftworkcloudpcaccessstate-values)|Get the access state of the shift work Cloud PC.|
```

2023-03-02 17:38 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|unassigned|Default. Set to unassigned if the Cloud PC is not consuming any shared use licenses.|
```suggestion
|unassigned|Default. Set to unassigned if the Cloud PC is not consuming any shared-use licenses.|
```

2023-03-02 18:01 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|unassigned|Default. Set to unassigned if the Cloud PC is not consuming any shared-use licenses.|
Which is the default value? Assigned or unassigned? I recommend: 
```suggestion
|unassigned| Set to unassigned if the Cloud PC is not consuming any shared-use licenses. The default value is ________.|
```

2023-03-02 18:31 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|activating|Indicates the shift work Cloud PC is in activating state after the user requests to connect this Cloud PC, service is working on starting the Cloud PC.|
```suggestion
|activating|Indicates that a user is requesting to connect the Cloud PC and the service is starting.|
```

2023-03-02 18:35 UTC, Danielabom commented on api-reference/beta/toc.yml
> +        - name: Get shift work cloudPc's access state
```suggestion
        - name: Get shift work cloudPCs access state
```

2023-03-03 00:15 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
> +For more information, see [cloudPcProvisioningPolicy] (../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)
```suggestion
For more information, see [cloudPcProvisioningPolicy](../resources/cloudpcprovisioningpolicy.md#cloudpcprovisioningtype-values)
```

2023-03-03 02:10 UTC, ningjingbogithub commented on api-reference/beta/resources/cloudpc.md
> +|hibernated|Indicates the shift work Cloud PC is in the hibernated state before it's shutdown and deallocated. Shift work Cloud PC in hibernated state is still accessible by end user.|
the api.md is here: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding?path=/reviews/CMX/CloudManagedDesktop/6377-3-cloudPc-entity-api/api.md&version=GBmaster&line=734&lineEnd=734&lineStartColumn=22&lineEndColumn=29&lineStyle=plain&_a=contents
the CSDL roll out to test/_cpc_sh: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/7707908?_a=files

2023-03-03 04:55 UTC, ningjingbogithub commented on api-reference/beta/resources/cloudpc.md
> +|noLicensesAvailable|Indicates the shift work Cloud PC cannot be assigned any sharedUseLicenses as all shared use licenses are in use as of now.|
fixed

2023-03-03 04:55 UTC, ningjingbogithub commented on api-reference/beta/resources/cloudpc.md
> +|activationFailed|Indicates the shift work Cloud PC activation failed after user requested the shift work Cloud PC.|
fixed

2023-03-03 04:56 UTC, ningjingbogithub commented on api-reference/beta/toc.yml
> +        - name: Get shift work cloudPc's access state
fixed

2023-03-03 14:14 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|hibernated|Indicates the shift work Cloud PC is in the hibernated state before it's shutdown and deallocated. Shift work Cloud PC in hibernated state is still accessible by end user.|
For security purposes, I removed the links you shared. Thanks!

2023-03-03 14:30 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|hibernated|Indicates the shift work Cloud PC is in the hibernated state before it's shutdown and deallocated. Shift work Cloud PC in hibernated state is still accessible by end user.|
```suggestion
|hibernated|Indicates the shift work Cloud PC is in the hibernated state before it's shut down and deallocated. A Shift work Cloud PC in hibernated state is still accessible by the end user.|
```

2023-03-03 14:31 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ApiChange": "Enumeration",
```suggestion
            "ApiChange": "Member",
```

2023-03-03 14:32 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Description": "Added 'hibernated' in **shiftWorkCloudPcAccessState** enumeration type.",
```suggestion
            "Description": "Added the 'hibernated' member to the **shiftWorkCloudPcAccessState** enumeration type.",
```

2023-03-03 14:36 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Target": "getShiftWorkCloudPcAccessState"
```suggestion
            "Target": shiftWorkCloudPcAccessState"
```

2023-03-03 14:38 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ChangedApiName": "shiftWorkCloudPcAccessState",
```suggestion
            "ChangedApiName": "hibernated",
```

2023-03-03 14:40 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ChangedApiName": "getShiftWorkCloudPcAccessState",
```suggestion
            "ChangedApiName": "shiftWorkCloudPcAccessState",
```

2023-03-03 14:42 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Target": "getShiftWorkCloudPcAccessState"
```suggestion
            "Target": "shiftWorkCloudPcAccessState"
```

2023-03-03 23:59 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|[Get shift work cloudPCs access state](../api/cloudpc-getshiftworkcloudpcaccessstate.md)|[shiftWorkCloudPcAccessState](#shiftworkcloudpcaccessstate-values)|Get the access state of the shift work Clo
Since the return type of this function is an evolvable enum type, please document it accordingly. Here's the link with the steps: [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations](url)

2023-03-04 00:00 UTC, Danielabom requested changes
@ningjingbogithub, I've made most of the changes myself, but please review my comment about evolvable enums. Thanks!

2023-03-21 03:48 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get shift work access state
We are surfacing this method under Users in the TOC, but not under the Cloud PC node under Device and app management. I think we need an entry for it in the Cloud PC node as well, under the cloudpc resource topic.

2023-03-21 06:24 UTC, ningjingbogithub commented on api-reference/beta/toc.yml
> +        - name: Get shift work access state
fixed it.

2023-03-22 01:47 UTC, merged