Adding support for alternate key in device entity
microsoftgraph/microsoft-graph-docs pull request #19013
Opened 2022-10-27 13:25 UTC by JohnMaina

2022-10-27 13:27 UTC, opbld31 commented
Learn Build status updates of commit _[c5d65a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5d65a2c9d62c83c36bd404d01e42a955349d99f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-59877e00f6faa5d9977dc5d85f63d955-5aa86ff3)
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2152d35db03748b4b8837bbded390627-5aa86ff3)
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2f500f193b0fdd6c4e077c44c72eaa7f-5aa86ff3)
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |

<a id="59877e00f6faa5d9977dc5d85f63d955-5aa86ff3"></a>
### [api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md)
 - **Line 60, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="2152d35db03748b4b8837bbded390627-5aa86ff3"></a>
### [api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md)
 - **Line 62, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="2f500f193b0fdd6c4e077c44c72eaa7f-5aa86ff3"></a>
### [api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md)
 - **Line 68, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271325218676-19013/BuildReport?accessString=8424d8295564b239e5ba4b82b01cc017c31fc6493cf7ff4e9a8f94e03653eff0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 13:31 UTC, opbld30 commented
Learn Build status updates of commit _[f2c6619](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2c6619f16049c88740e9ea88905e7a0e60b5391)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-59877e00f6faa5d9977dc5d85f63d955-31bdf43d)
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2152d35db03748b4b8837bbded390627-31bdf43d)
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2f500f193b0fdd6c4e077c44c72eaa7f-31bdf43d)
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |

<a id="59877e00f6faa5d9977dc5d85f63d955-31bdf43d"></a>
### [api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md)
 - **Line 60, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="2152d35db03748b4b8837bbded390627-31bdf43d"></a>
### [api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md)
 - **Line 62, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="2f500f193b0fdd6c4e077c44c72eaa7f-31bdf43d"></a>
### [api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md)
 - **Line 68, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271329259379-19013/BuildReport?accessString=72dfdfd6941cd4465b64602151f2ac98c7557a6e9f86c5bf2c86d5ff9f2c74d5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 13:35 UTC, opbld31 commented
Learn Build status updates of commit _[6eec4ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6eec4efe11a8ebd81d65bc231a0798379aa7a42f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-59877e00f6faa5d9977dc5d85f63d955-9269113a)
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2f500f193b0fdd6c4e077c44c72eaa7f-9269113a)
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |

<a id="59877e00f6faa5d9977dc5d85f63d955-9269113a"></a>
### [api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md)
 - **Line 60, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="2f500f193b0fdd6c4e077c44c72eaa7f-9269113a"></a>
### [api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md)
 - **Line 68, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271333003447-19013/BuildReport?accessString=bb99ed9a797502ede5e069db05ca959823e6bf0c892b98d89bb7f70001d7e362).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 14:34 UTC, opbld31 commented
Learn Build status updates of commit _[103c021](https://github.com/microsoftgraph/microsoft-graph-docs/commits/103c021e44f2203362adcf024d6c8b09a3a6a2c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2152d35db03748b4b8837bbded390627-8cfdb826)
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2f500f193b0fdd6c4e077c44c72eaa7f-8cfdb826)
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-eddab72315328aed485ddded01053ea9-8cfdb826)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-ab1cc3d3f45240292ab3131e10d1e066-8cfdb826)
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-9a6ca02d7fbeb0fcec1b2b6dad743306-8cfdb826)
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |

<a id="2152d35db03748b4b8837bbded390627-8cfdb826"></a>
### [api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md)
 - **Line 158, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="2f500f193b0fdd6c4e077c44c72eaa7f-8cfdb826"></a>
### [api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md)
 - **Line 221, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="eddab72315328aed485ddded01053ea9-8cfdb826"></a>
### [api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="ab1cc3d3f45240292ab3131e10d1e066-8cfdb826"></a>
### [api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md)
 - **Line 143, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="9a6ca02d7fbeb0fcec1b2b6dad743306-8cfdb826"></a>
### [api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md)
 - **Line 141, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271432132274-19013/BuildReport?accessString=5de2dd2e8441eede37e824473efdd9676d46cad9c90fa18a43736f85597a0026).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><l [...]

2022-10-27 14:43 UTC, opbld31 commented
Learn Build status updates of commit _[01df887](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01df8871d90dfea480e266637d37bb03dafe5c03)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2152d35db03748b4b8837bbded390627-f40ee28b)
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2f500f193b0fdd6c4e077c44c72eaa7f-f40ee28b)
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-eddab72315328aed485ddded01053ea9-f40ee28b)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-ab1cc3d3f45240292ab3131e10d1e066-f40ee28b)
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-9a6ca02d7fbeb0fcec1b2b6dad743306-f40ee28b)
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |

<a id="2152d35db03748b4b8837bbded390627-f40ee28b"></a>
### [api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md)
 - **Line 158, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="2f500f193b0fdd6c4e077c44c72eaa7f-f40ee28b"></a>
### [api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md)
 - **Line 221, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="eddab72315328aed485ddded01053ea9-f40ee28b"></a>
### [api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="ab1cc3d3f45240292ab3131e10d1e066-f40ee28b"></a>
### [api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md)
 - **Line 143, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="9a6ca02d7fbeb0fcec1b2b6dad743306-f40ee28b"></a>
### [api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md)
 - **Line 141, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271440456424-19013/BuildReport?accessString=686fa06ad50cef890603dca538e58fdef9984fa31ec23a320d319e28f0cfc72e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation [...]

2022-10-28 06:55 UTC, opbld30 commented
Learn Build status updates of commit _[5d78f45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d78f455e8bf31b875cd191e38129b9904ca0865)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2152d35db03748b4b8837bbded390627-65b25c10)
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2f500f193b0fdd6c4e077c44c72eaa7f-65b25c10)
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-eddab72315328aed485ddded01053ea9-65b25c10)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-ab1cc3d3f45240292ab3131e10d1e066-65b25c10)
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-9a6ca02d7fbeb0fcec1b2b6dad743306-65b25c10)
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |

<a id="2152d35db03748b4b8837bbded390627-65b25c10"></a>
### [api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md)
 - **Line 159, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="2f500f193b0fdd6c4e077c44c72eaa7f-65b25c10"></a>
### [api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md)
 - **Line 223, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="eddab72315328aed485ddded01053ea9-65b25c10"></a>
### [api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="ab1cc3d3f45240292ab3131e10d1e066-65b25c10"></a>
### [api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="9a6ca02d7fbeb0fcec1b2b6dad743306-65b25c10"></a>
### [api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md)
 - **Line 142, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210280652351832-19013/BuildReport?accessString=b0bbb92d8fb8e831a5ad30415fb185d463ee55e4f6d26c6491e9da3ff3f8f349).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation [...]

2022-10-28 10:09 UTC, opbld33 commented
Learn Build status updates of commit _[fc1642f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc1642f47a60e70fc69b8b2450064ce7006cc765)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2152d35db03748b4b8837bbded390627-93838b9d)
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-2f500f193b0fdd6c4e077c44c72eaa7f-93838b9d)
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-eddab72315328aed485ddded01053ea9-93838b9d)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-ab1cc3d3f45240292ab3131e10d1e066-93838b9d)
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-9a6ca02d7fbeb0fcec1b2b6dad743306-93838b9d)
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="2152d35db03748b4b8837bbded390627-93838b9d"></a>
### [api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md)
 - **Line 159, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="2f500f193b0fdd6c4e077c44c72eaa7f-93838b9d"></a>
### [api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md)
 - **Line 223, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="eddab72315328aed485ddded01053ea9-93838b9d"></a>
### [api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="ab1cc3d3f45240292ab3131e10d1e066-93838b9d"></a>
### [api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md)
 - **Line 144, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="9a6ca02d7fbeb0fcec1b2b6dad743306-93838b9d"></a>
### [api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md)
 - **Line 142, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210281006362690-19013/BuildReport?accessString=b67d643fbc9ebea1d9c3726ad2a4e83d65928bb8db438b2cd599d35242815e16).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when ex [...]

2022-10-28 12:31 UTC, ngash commented on api-reference/beta/resources/device.md
> +|deviceId|String| Unique Identifier set by Azure Device Registration Service at the time of registration. This is an alternte key, meaning it can be used in the place of `id`. Also Supports `$filter`
```suggestion
|deviceId|String| Unique Identifier set by Azure Device Registration Service at the time of registration. This is an alternate key, meaning it can be used in the place of `id`. Also Supports `$filter` (`eq`, `ne`, `not`, `startsWith`). |
```

2022-10-28 12:34 UTC, ngash requested changes

2022-10-28 12:34 UTC, ngash commented on api-reference/beta/api/device-delete.md
> +
nit: extra space

2022-11-08 15:52 UTC, opbld30 commented
Learn Build status updates of commit _[4be3cf3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4be3cf39576fbdc74b12f3fe7e925da08de8599c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211081549247770-19013/BuildReport?accessString=d408467fc43c7b9f2733b525e9a266feebaa778b54f8f2528c082e712f5c79c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 16:12 UTC, FaithOmbongi commented
To validate queries once the API goes live.

The documented syntax violates the OData-defined syntax for alternate keys: https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#_Toc31360936

2022-11-14 16:29 UTC, opbld30 commented
Learn Build status updates of commit _[ac69409](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac6940906d013955f49e2c5e948afac54dffe6de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211141626461158-19013/BuildReport?accessString=e0e3e897bf679e6d4f2f57ca9684fd7b5f33989d64362b6acdb68035313815fd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 04:46 UTC, opbld30 commented
Learn Build status updates of commit _[4e64fee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e64fee2e868be26b8e96ab33119433d730c034e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150444418579-19013/BuildReport?accessString=4c8bc53f94f369badc26e9d8547994166a9912df9b3d6f0a79d5876d297a0f9a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-16 19:48 UTC, opbld34 commented
Learn Build status updates of commit _[89785f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89785f9161fb9bdcf38529724a5c7ce2fbdb5b97)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure_docs/includes/lifecycle-workflows-tasks-table.md](https://github.com/MicrosoftDocs/azure-docs//blob/main/includes/lifecycle-workflows-tasks-table.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-lifecycleworkflows-overview?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) | [Details](#user-content-b785375b5caed854220727a089baf481-7df55952)
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="b785375b5caed854220727a089baf481-7df55952"></a>
### [azure_docs/includes/lifecycle-workflows-tasks-table.md](https://github.com/MicrosoftDocs/azure-docs//blob/main/includes/lifecycle-workflows-tasks-table.md)
 - **Line 15, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#send-welcome-email-to-new-hire' will not be built because it is not included in build scope.`````
 - **Line 16, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#send-onboarding-reminder-email' will not be built because it is not included in build scope.`````
 - **Line 17, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#generate-temporary-access-pass-and-send-via-email-to-users-manager' will not be built because it is not included in build scope.`````
 - **Line 18, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#add-user-to-groups' will not be built because it is not included in build scope.`````
 - **Line 19, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#add-user-to-teams' will not be built because it is not included in build scope.`````
 - **Line 20, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#enable-user-account' will not be built because it is not included in build scope.`````
 - **Line 21, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#run-a-custom-task-extension' will not be built because it is not included in build scope.`````
 - **Line 22, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#disable-user-account' will not be built because it is not included in build scope.`````
 - **Line 23, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle- [...]

2022-11-17 20:52 UTC, FaithOmbongi approved these changes

2022-11-29 02:09 UTC, opbld34 commented
Learn Build status updates of commit _[12115e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12115e78479badf5b22a59ab4921d96c34d5a2e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211290206159013-19013/BuildReport?accessString=015d51fbebe113336c6dadd0c86bf663b52bfb942f0e2d7776d6f9755dd43fd5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 02:40 UTC, opbld32 commented
Learn Build status updates of commit _[41f89da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41f89da865ec17003e42475e97042beef87dda20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredowners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredowners?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-post-registeredusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-post-registeredusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-post-registeredusers?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-19013) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jokamau/alternate-keys/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211290238040527-19013/BuildReport?accessString=658a4c047f2ce1844d6e54939b48489877c643afaf0cd678a5a47dac2b4afd94).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 02:43 UTC, merged