Adding Business Scenario Related API documentation
microsoftgraph/microsoft-graph-docs pull request #19015
Opened 2022-10-27 15:54 UTC by TarkanSevilmis

Creating the documentation for Business Scenarios and Planner extensions for Business Scenarios.

2022-10-27 15:57 UTC, opbld31 commented
Learn Build status updates of commit _[58d3f89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58d3f898221779da804c90ccdd18dc352633c95f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-4efbf196)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-4efbf196)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-4efbf196)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-4efbf196)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-4efbf196)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-4efbf196)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-4efbf196)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-4efbf196)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-4efbf196)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-4efbf196)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-4efbf196)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-4efbf196)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-4efbf196)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-4efbf196)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-4efbf196)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-4efbf196)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-10-28 22:09 UTC, opbld31 commented
Learn Build status updates of commit _[2449354](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24493540f3602ebbaf8b2fa2d0426460b9a04f7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-4694425f)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-4694425f)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-4694425f)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-4694425f)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-4694425f)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-4694425f)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-4694425f)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-4694425f)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-4694425f)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-4694425f)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-4694425f)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-4694425f)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-4694425f)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-4694425f)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-4694425f)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-4694425f)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-10-28 23:57 UTC, opbld34 commented
Learn Build status updates of commit _[6939c81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6939c81e76150cdc918438f32b1af6746d1571f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-955ef687)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-955ef687)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-955ef687)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-955ef687)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-955ef687)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-955ef687)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-955ef687)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-955ef687)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-955ef687)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-955ef687)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-955ef687)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-955ef687)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-955ef687)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-955ef687)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-955ef687)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-955ef687)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-10-31 05:48 UTC, opbld33 commented
Learn Build status updates of commit _[c16a905](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c16a905ec8cf00dc3596b39ae7669a41fff69d95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-f7dfe73e)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-f7dfe73e)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-f7dfe73e)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-f7dfe73e)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-f7dfe73e)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-f7dfe73e)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-f7dfe73e)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-f7dfe73e)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-f7dfe73e)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-f7dfe73e)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-f7dfe73e)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-f7dfe73e)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-f7dfe73e)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-f7dfe73e)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-f7dfe73e)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-f7dfe73e)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-10-31 22:27 UTC, opbld30 commented
Learn Build status updates of commit _[7e5d04e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e5d04ed8dbbe5464528277d4795210e61b51b74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-5e33bd90)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-5e33bd90)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-5e33bd90)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-5e33bd90)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-5e33bd90)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-5e33bd90)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-5e33bd90)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-5e33bd90)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-5e33bd90)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-5e33bd90)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-5e33bd90)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-5e33bd90)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-5e33bd90)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-5e33bd90)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-5e33bd90)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-5e33bd90)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-10-31 22:31 UTC, opbld33 commented
Learn Build status updates of commit _[23f498e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23f498ec9c9735b8fcca6cd2f1893d859dfb766e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-2c16e9f1)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-2c16e9f1)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-2c16e9f1)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-2c16e9f1)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-2c16e9f1)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-2c16e9f1)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-2c16e9f1)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-2c16e9f1)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-2c16e9f1)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-2c16e9f1)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-2c16e9f1)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-2c16e9f1)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-2c16e9f1)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-2c16e9f1)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-2c16e9f1)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-2c16e9f1)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-10-31 23:46 UTC, opbld33 commented
Learn Build status updates of commit _[a14e7a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a14e7a6774f4e6b30d47049579bdc9a71a30ba4c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7f1bd249)
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-7f1bd249)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-7f1bd249)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-7f1bd249)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-7f1bd249)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-7f1bd249)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-7f1bd249)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-7f1bd249)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-7f1bd249)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-7f1bd249)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-7f1bd249)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-7f1bd249)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-7f1bd249)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-7f1bd249)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-7f1bd249)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-7f1bd249)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-7f1bd249)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-B [...]

2022-11-04 22:46 UTC, opbld30 commented
Learn Build status updates of commit _[b8cc868](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8cc8680d74bfe19375d8150ffb6a44667c7aeac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-bb332245)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-bb332245)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-bb332245)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-bb332245)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-bb332245)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-bb332245)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-bb332245)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-bb332245)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-bb332245)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-bb332245)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-bb332245)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-bb332245)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-bb332245)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-bb332245)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-bb332245)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-bb332245)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-04 23:13 UTC, opbld32 commented
Learn Build status updates of commit _[6287e66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6287e665de393dfca7aa1067c1b6003ccb767a34)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-aeaf8615)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-aeaf8615)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-aeaf8615)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-aeaf8615)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-aeaf8615)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-aeaf8615)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-aeaf8615)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-aeaf8615)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-aeaf8615)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-aeaf8615)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-aeaf8615)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-aeaf8615)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-aeaf8615)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-aeaf8615)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-aeaf8615)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-aeaf8615)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-04 23:25 UTC, opbld31 commented
Learn Build status updates of commit _[b030d2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b030d2b9c8b78cac09b1988eb1d7703def9f3720)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-180d1286)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-180d1286)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-180d1286)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-180d1286)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-180d1286)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-180d1286)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-180d1286)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-180d1286)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-180d1286)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-180d1286)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-180d1286)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-180d1286)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-180d1286)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-180d1286)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-180d1286)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-180d1286)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-08 00:56 UTC, opbld32 commented
Learn Build status updates of commit _[67c5f31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67c5f311bf67a1843794bbc2d9dedca67567592a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-ad69e08c)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-ad69e08c)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-ad69e08c)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-ad69e08c)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-ad69e08c)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-ad69e08c)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-ad69e08c)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-ad69e08c)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-ad69e08c)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-ad69e08c)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-ad69e08c)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-ad69e08c)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-ad69e08c)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-ad69e08c)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-ad69e08c)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-ad69e08c)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-08 02:23 UTC, opbld30 commented
Learn Build status updates of commit _[4c70e00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c70e00d6a2e2dba9847d52c447b8d2f4dc96725)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-472ee522)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-472ee522)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-472ee522)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-472ee522)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-472ee522)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-472ee522)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-472ee522)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-472ee522)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-472ee522)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-472ee522)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-472ee522)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-472ee522)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-472ee522)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-472ee522)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-472ee522)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-472ee522)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-08 05:33 UTC, opbld33 commented
Learn Build status updates of commit _[fa9dc49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa9dc4910fd9a17b386c87098c70fbccb14a5937)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-abae6e9d)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-abae6e9d)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-abae6e9d)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-abae6e9d)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-abae6e9d)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-abae6e9d)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-abae6e9d)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-abae6e9d)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-abae6e9d)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-abae6e9d)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-abae6e9d)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-abae6e9d)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-abae6e9d)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-abae6e9d)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-abae6e9d)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-abae6e9d)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-08 05:38 UTC, opbld34 commented
Learn Build status updates of commit _[56298b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56298b6f5836271263bc7fecdeefe79403145db2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-0ab91dc4)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-0ab91dc4)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-0ab91dc4)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-0ab91dc4)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-0ab91dc4)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-0ab91dc4)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-0ab91dc4)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-0ab91dc4)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-0ab91dc4)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-0ab91dc4)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-0ab91dc4)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-0ab91dc4)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-0ab91dc4)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-0ab91dc4)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-0ab91dc4)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-0ab91dc4)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-08 05:40 UTC, opbld34 commented
Learn Build status updates of commit _[de0ed8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de0ed8dbc7df1668da7501402bc963abce1cb3f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-9fc9036b)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-9fc9036b)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-9fc9036b)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-9fc9036b)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-9fc9036b)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-9fc9036b)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-9fc9036b)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-9fc9036b)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-9fc9036b)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-9fc9036b)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-9fc9036b)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-9fc9036b)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-9fc9036b)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-9fc9036b)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-9fc9036b)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-9fc9036b)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-08 22:28 UTC, opbld32 commented
Learn Build status updates of commit _[96484e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96484e83619de8ff0a26873bc697012013e93cad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-66f1f472)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-66f1f472)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-66f1f472)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-66f1f472)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-66f1f472)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-66f1f472)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-66f1f472)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-66f1f472)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-66f1f472)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-66f1f472)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-66f1f472)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-66f1f472)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-66f1f472)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-66f1f472)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-66f1f472)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-66f1f472)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-10 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/plannerbucketpropertyrule.md
> +description: "**TODO: Add Description**"
Please, provide the missing information for description, author, and the descriptions under Properties.

2022-11-10 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/plannerplanconfiguration.md
> +|:---|:---|:---|
According to the api.md file, this resource topic should also have a create and delete plannerPlanConfiguration. Please, ensure that these two API topics exist in this PR and that they are correctly listed in this Methods table.

2022-11-10 21:29 UTC, opbld32 commented
Learn Build status updates of commit _[9e90095](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e9009569a73feac07857cd8c6a86787d87a554a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-9a066d3a)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-9a066d3a)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-9a066d3a)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-9a066d3a)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-9a066d3a)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-9a066d3a)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-9a066d3a)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-9a066d3a)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-9a066d3a)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-9a066d3a)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-9a066d3a)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-9a066d3a)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-9a066d3a)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-9a066d3a)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-9a066d3a)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-9a066d3a)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-10 21:39 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenario.md
> +Inherits from [entity](../resources/entity.md).
Entity is the global base class for everything in Graph. So, it is technically correct. It is coming from the generated stubs, I can remove it because it doesn't really add anything to the documentation.

2022-11-10 21:42 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenariogrouptarget.md
> +Represents targeting a [group](../resources/group.md) for a creating tasks in a scenario.
Updating wording to be clearer.

2022-11-10 21:52 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenarioplanreference.md
> +|Property|Type|Description|
APi.md is wrong in this case.

2022-11-10 21:53 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenarioproperties.md
> +|:---|:---|:---|
Api.md is incorrect. The document is correct, I added Required for the items that are actually required.

2022-11-10 22:00 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenariotask.md
> +|businessScenarioProperties|[businessScenarioProperties](../resources/businessscenarioproperties.md)|**TODO: Add Description**|
Oops, I didn't notice these.

2022-11-10 22:02 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerbucketpropertyrule.md
> +description: "**TODO: Add Description**"
This shouldn't exist, it is not being exposed right now (it is in the schema, but no type, or request references it). Deleted the file

2022-11-10 22:03 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerbucketpropertyrule.md
> +description: "**TODO: Add Description**"
Same for planner plan property rule

2022-11-10 22:04 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerplanconfiguration.md
> +|:---|:---|:---|
Another instance of api.md being wrong, this is a resource that is created with the scenario, cannot be deleted or created independently.

2022-11-10 22:13 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenariotask.md
> +|businessScenarioProperties|[businessScenarioProperties](../resources/businessscenarioproperties.md)|**TODO: Add Description**|
Pushed new changes

2022-11-10 22:13 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenario.md
> +Inherits from [entity](../resources/entity.md).
Let me know if I should remove these or not

2022-11-10 22:16 UTC, opbld31 commented
Learn Build status updates of commit _[cbd4375](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbd4375a9a507caeaa6f2bb4433515a130b9f23c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-14f9e158)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-14f9e158)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-14f9e158)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-14f9e158)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-14f9e158)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-14f9e158)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-14f9e158)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-14f9e158)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-14f9e158)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-14f9e158)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-14f9e158)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-14f9e158)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-14f9e158)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-14f9e158)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-14f9e158)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-14f9e158)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-15 00:36 UTC, JarbasHorst commented on api-reference/beta/resources/businessscenario.md
> +title: "businessScenario resource type"
The api.md file describes a set of new permission scopes (BusinessScenarioConfig.Read.All etc.) that should also be documented. Please, update the [Microsoft Graph permissions reference](https://learn.microsoft.com/en-us/graph/permissions-reference) to include the new permissions.

2022-11-15 00:36 UTC, JarbasHorst commented on api-reference/beta/api/businessscenario-get.md
> +GET https://graph.microsoft.com/beta/solutions/businessScenarios/{businessScenarioId}
Global: Please, apply this change to all API topics.

For clarity, please replace the placeholders, such as {businessScenarioId}, with a real-looking ID. Examples with real-looking values in the request URL, requests and response bodies help customers understand the API better. That's also the consistency bar for Microsoft Graph API docs.

2022-11-15 00:36 UTC, JarbasHorst commented on api-reference/beta/api/businessscenario-update.md
> +**TODO: Remove properties that don't apply**
Please, take a look at the open To-Dos.

Same here:
- api-reference/beta/api/plannerplanconfiguration-post-localizations.md
- api-reference/beta/api/plannerplanconfiguration-update.md
- api-reference/beta/api/plannerplanconfigurationlocalization-update.md
- api-reference/beta/api/plannertaskconfiguration-update.md

2022-11-15 00:36 UTC, JarbasHorst commented on api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md
> +GET ** Collection URI for microsoft.graph.plannerPlanConfiguration not found
Lines 33 and 61: Request URL missing

Same here:
- api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md

2022-11-15 00:36 UTC, JarbasHorst commented on api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
> +|Delegated (work or school account)|**TODO: Provide applicable permissions.**|
**TODO: Provide applicable permissions.**

Same for lines 23 and 24, and
- api-reference/beta/api/plannerplanconfiguration-get.md
- api-reference/beta/api/plannerplanconfiguration-list-localizations.md
- api-reference/beta/api/plannerplanconfiguration-post-localizations.md
- api-reference/beta/api/plannerplanconfiguration-update.md
- api-reference/beta/api/plannerplanconfigurationlocalization-get.md
- api-reference/beta/api/plannerplanconfigurationlocalization-update.md
- api-reference/beta/api/plannertaskconfiguration-get.md
- api-reference/beta/api/plannertaskconfiguration-update.md

2022-11-15 00:36 UTC, JarbasHorst commented on api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
> +author: "**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**"
Author missing!

Same here:
- api-reference/beta/api/plannerplanconfiguration-get.md
- api-reference/beta/api/plannerplanconfiguration-list-localizations.md
- api-reference/beta/api/plannerplanconfiguration-post-localizations.md
- api-reference/beta/api/plannerplanconfiguration-update.md
- api-reference/beta/api/plannerplanconfigurationlocalization-get.md
- api-reference/beta/api/plannerplanconfigurationlocalization-update.md
- api-reference/beta/api/plannertaskconfiguration-get.md
- api-reference/beta/api/plannertaskconfiguration-update.md

2022-11-15 00:36 UTC, JarbasHorst commented on api-reference/beta/api/businessscenario-get.md
> +{
Global: Please, apply this changes to all API topics.

The request and response bodies should not contain the JSON representation of the objects. Please, update the response and request bodies to contain real-looking values.

2022-11-15 00:36 UTC, JarbasHorst commented on changelog/Microsoft.Office.Tasks.json
> +          "ChangedApiName": "plannerBucketPropertyRule",
I noticed that you have removed the plannerPlanPropertyRule and plannerBucketPropertyRule resource types from this PR. However, they are both visible in the CSDL as additions. Should these resource topics be part of this PR?

2022-11-15 00:36 UTC, opbld32 commented
Learn Build status updates of commit _[04765a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04765a7404e6e3e3c1bf96d0c8a28b1489d588a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-a58fce33)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-a58fce33)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-a58fce33)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-a58fce33)
[api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-planconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-planconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-2401ab66effb7f34e553d3dfec54599e-a58fce33)
[api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get-taskconfiguration.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get-taskconfiguration?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-1342373a904260abc8732065fc03ad38-a58fce33)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-a58fce33)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-a58fce33)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-a58fce33)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-a58fce33)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-a58fce33)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-a58fce33)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-a58fce33)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-a58fce33)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-a58fce33)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-a58fce33)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-l [...]

2022-11-15 09:26 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenarioplanreference.md
> +|[getPlan](../api/businessscenarioplanner-getplan.md)|[businessScenarioPlanReference](../resources/businessscenarioplanreference.md)|Get the reference to the plan that corresponds to the given target
Hi @TarkanSevilmis , I'm curious if this topic was generated by Graph Studio?

From the consistency perspective across method topics in Microsoft Graph - I wasn't expecting that the return type topic (this topic) would include the getPlan action in its Methods table. 

I would expect that the businessScenarioPlanner (the type of the bindingParameter) topic would include the getPlan action.

2022-11-15 09:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/plannerplanconfiguration.md
> +Represents the configuration of [plannerPlans](../resources/plannerplan.md) created for a [businessScenario](../resources/businessscenario.md).
Line 16:
Trying to understand how the APIs work so I can do my part (for the TOC entry point) - I see that you mention "plannerPlans" here. Is that a typo?
I got from the blog post (section on "App isolation") and from the api.me (section {2.1}) that each business scenario is mapped to one plannerPlan. Is that correct?

If so, then please clarify in line 16, for example, please say:
"Represents the configuration of the dedicated plannerPlan created for a businessScenario." (Include the 2 links.)

If not, and you if you do mean plural number of plans, then you would have to say:
"... of plannerPlan resources created for..."

The link text which is a single instance of plannerPlan needs to match the linked topic, which is a single Planner plan.

2022-11-15 18:14 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannertaskconfiguration.md
> +|[Get plannerTaskConfiguration](../api/plannertaskconfiguration-get.md)|[plannerTaskConfiguration](../resources/plannertaskconfiguration.md)|Read the properties and relationships of a [plannerTaskCon
No, API md is incorrect, it only supports patch and get.

2022-11-15 18:23 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-update.md
> +**TODO: Remove properties that don't apply**
Sorry missed this section.

2022-11-15 18:32 UTC, TarkanSevilmis commented on changelog/Microsoft.Office.Tasks.json
> +          "ChangedApiName": "plannerBucketPropertyRule",
They will not be discoverable at this time. Nothing will return them nothing will accept them.

2022-11-15 18:35 UTC, opbld34 commented
Learn Build status updates of commit _[4121287](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41212871e452117025de7a4ffe8c80dcdfadeb71)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-53d410eb)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-53d410eb)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-53d410eb)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-53d410eb)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-53d410eb)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-53d410eb)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-53d410eb)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-53d410eb)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-53d410eb)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-53d410eb)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-53d410eb)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-53d410eb)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-53d410eb)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-53d410eb)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-53d410eb)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-53d410eb)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-15 18:37 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenarioplanreference.md
> +|[getPlan](../api/businessscenarioplanner-getplan.md)|[businessScenarioPlanReference](../resources/businessscenarioplanreference.md)|Get the reference to the plan that corresponds to the given target
Looks like I added it manually. The generated ones didn't make sense (they don't exist), so when I removed them the section was left empty, so I added this action which is the only operation that returns this type.

2022-11-15 18:50 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerplanconfiguration.md
> +Represents the configuration of [plannerPlans](../resources/plannerplan.md) created for a [businessScenario](../resources/businessscenario.md).
It is plural, updating.

2022-11-15 23:57 UTC, TarkanSevilmis commented on api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
> +|Delegated (work or school account)|**TODO: Provide applicable permissions.**|
Yeah I missed a ton of files apparently. fixed those

2022-11-15 23:58 UTC, TarkanSevilmis commented on api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
> +author: "**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**"
Fixed

2022-11-16 00:12 UTC, opbld32 commented
Learn Build status updates of commit _[48514cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48514cb18fab8d3e9d92b0b154d8291925e80340)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-bb381c05)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-bb381c05)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-bb381c05)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-bb381c05)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-bb381c05)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-bb381c05)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-bb381c05)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-bb381c05)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-bb381c05)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-bb381c05)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-bb381c05)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-bb381c05)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-bb381c05)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-bb381c05)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-bb381c05)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-bb381c05)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-16 00:35 UTC, opbld32 commented
Learn Build status updates of commit _[546bf5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/546bf5e8e8e14658140f21929f0f51eb200ee098)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-90db2d28)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-90db2d28)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-90db2d28)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-90db2d28)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-90db2d28)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-90db2d28)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-90db2d28)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-90db2d28)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-90db2d28)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-90db2d28)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-90db2d28)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-90db2d28)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-90db2d28)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-90db2d28)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-90db2d28)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-90db2d28)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-16 01:11 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenario.md
> +---
added

2022-11-16 01:30 UTC, JarbasHorst commented on changelog/Microsoft.Office.Tasks.json
> +          "ChangedApiName": "plannerBucketPropertyRule",
@TarkanSevilmis, if the resource topics will be public available (not hidden), then we should have the documentation for them. What are your future plans for these two resource topics? Are they going to be removed or hidden?

2022-11-16 01:30 UTC, JarbasHorst commented on api-reference/beta/resources/businessscenario.md
> +Inherits from [entity](../resources/entity.md).
We don't need to remove them. Thank you for the clarification.

2022-11-16 01:35 UTC, opbld30 commented
Learn Build status updates of commit _[fe020f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe020f14533df3919f4c5f0a25a118a41fb6aa80)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-545f7308)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-545f7308)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-545f7308)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-545f7308)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-545f7308)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-545f7308)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-545f7308)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-545f7308)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-545f7308)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-545f7308)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-545f7308)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-545f7308)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-545f7308)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-545f7308)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-545f7308)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-545f7308)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-16 01:45 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenario.md
> +title: "businessScenario resource type"
Added

2022-11-16 01:46 UTC, opbld33 commented
Learn Build status updates of commit _[09d6fa6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09d6fa65ae7283f7a54a5145df55d9662062be9f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-227b58d7)

<a id="227b58d7"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 09d6fa65ae7283f7a54a5145df55d9662062be9f in branch 2022-01-27-BusinessScenarioAPI of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 8b5b2cde2b6e14e29a6b5abbe40a4c9b2811b68b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211160145389618-19015/BuildReport?accessString=e1eae1af56210f58f6fcb401387b581e045665b9559ae49be58649050400bf78).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-16 04:00 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenarioplanreference.md
> +|[getPlan](../api/businessscenarioplanner-getplan.md)|[businessScenarioPlanReference](../resources/businessscenarioplanreference.md)|Get the reference to the plan that corresponds to the given target
I see. I asked just to get a better understanding what Graph Studio is generating these days; the onboarding folks who own Graph Studio don't necessarily tell us if they change what they generate. I only recall in the past, the generated entity topics wouldn't include methods that return those entities. 
IMO, adding the method to this entity topic makes sense and is helpful to customers. It's not consistent though, ... would customers start expecting an entity that's a return type of a method would include that method in its Methods table... they may.  Let me start an email with the Graph Studio folks and API Doctor owner. For the time being, we'll just leave the getPlan method in this Methods table.

2022-11-16 23:41 UTC, opbld33 commented
Learn Build status updates of commit _[92b36b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92b36b02efb0f0d3e64e1e53154626685231eaef)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c54debb7)

<a id="c54debb7"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 92b36b02efb0f0d3e64e1e53154626685231eaef in branch 2022-01-27-BusinessScenarioAPI of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 8b5b2cde2b6e14e29a6b5abbe40a4c9b2811b68b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211162341030775-19015/BuildReport?accessString=d02913448a2270f6cb29f872ccef7c0b6ce28aed8ec5c3abb8ba1257ae6e0fc4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 00:17 UTC, opbld34 commented
Learn Build status updates of commit _[0168cd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0168cd2fea79447e2440f6fcf3670430c4ee19c9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-821cac5f)

<a id="821cac5f"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 0168cd2fea79447e2440f6fcf3670430c4ee19c9 in branch 2022-01-27-BusinessScenarioAPI of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 8b5b2cde2b6e14e29a6b5abbe40a4c9b2811b68b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211170017058325-19015/BuildReport?accessString=18f880f1094dc1f46d2bdd64f573fa63795a4d1d255d10ec8f75df3e90a7c7d1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 00:29 UTC, JarbasHorst commented on api-reference/beta/api/businessscenarioplanner-getplan.md
> +Get information about the [plannerPlan](../resources/plannerplan.md) mapped to a given target.
According to the api.md file, this API creates a new, default Planner plan for the business scenario if it doesn't exist at the time of calling. If that is the case, I recommend you to add this extra information to the summary section of this API topic. Suggested revision:

- If a \*\*plannerPlan\*\* doesn't exist at the time of the request, a new, default plan will be created for the \[businessScenario\](../resources/businessscenario.md).

2022-11-17 00:29 UTC, JarbasHorst commented on api-reference/beta/api/businessscenario-get.md
> +---
According to the api.md file, we should also have documentation for the subscription use case: "App can subscribe to change notifications for scenario tasks". Is that a supported use case?

2022-11-17 00:29 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +* _BusinessScenarioConfig.Read.OwnedBy_: Create a new business scenario (`POST /solutions/businessScenarios`)
According to the documentation, the POST operation for Business Scenario only supports the BusinessScenarioConfig.ReadWrite.OwnedBy permission. If that is correct, please update this permission.

2022-11-17 00:29 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +* _BusinessScenarioConfig.ReadWrite.OwnedBy_: Update the Planner plan configuration for a business scenario (`PATCH /solutions/businessScenarios(uniqueName='com.contoso.orderManagement')/planner/plan
The documentation for this PATCH operation doesn't contain a URL with uniqueName as a supported request URL. The current supported request URL is:
- PATCH /solutions/businessScenarios/{businessScenarioId}/planner/planConfiguration

Is this use case also supported? If yes, please update the following documentation to include this request URL + example for uniqueName:
- api-reference/beta/api/plannerplanconfiguration-update.md

2022-11-17 00:29 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +* _BusinessScenarioData.ReadWrite.OwnedBy_: Delete a Planner task in a business scenario (`DELETE /solutions/businessScenarios(uniqueName='com.contoso.sampleScenario')/planner/tasks(externalObjectId=
The documentation for this DELETE operation shows /$ref as a required part of the request URL. If this is required, please update the URL in this example to include /$ref.

2022-11-17 00:42 UTC, opbld33 commented
Learn Build status updates of commit _[70841fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70841fe771a925b29c427ca97a166fda09a1fa12)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-43a983e2)

<a id="43a983e2"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 70841fe771a925b29c427ca97a166fda09a1fa12 in branch 2022-01-27-BusinessScenarioAPI of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 8b5b2cde2b6e14e29a6b5abbe40a4c9b2811b68b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211170042176274-19015/BuildReport?accessString=7c8c8f5911287b33ee697d81941bf522cf722ee353e890558ae80e3f6254c3a4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 00:48 UTC, opbld31 commented
Learn Build status updates of commit _[7bfa848](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bfa8484097624e44d746f0affefeec68101d669)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cdd803c7)

<a id="cdd803c7"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 7bfa8484097624e44d746f0affefeec68101d669 in branch 2022-01-27-BusinessScenarioAPI of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 8b5b2cde2b6e14e29a6b5abbe40a4c9b2811b68b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211170048335310-19015/BuildReport?accessString=c6980e70276ac6a2995116e74f1a7b65a4fbdb19633514ffa951bffa2a8b5f2f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 00:59 UTC, opbld30 commented
Learn Build status updates of commit _[dd2ff88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd2ff88ac5166fac6853589d85d28e0593f9b634)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-cae58ce4)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-cae58ce4)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-cae58ce4)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-cae58ce4)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-cae58ce4)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-cae58ce4)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-cae58ce4)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-cae58ce4)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-cae58ce4)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-cae58ce4)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-cae58ce4)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-cae58ce4)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-cae58ce4)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-cae58ce4)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-cae58ce4)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-cae58ce4)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-17 01:03 UTC, TarkanSevilmis commented on concepts/permissions-reference.md
> +* _BusinessScenarioData.ReadWrite.OwnedBy_: Delete a Planner task in a business scenario (`DELETE /solutions/businessScenarios(uniqueName='com.contoso.sampleScenario')/planner/tasks(externalObjectId=
Fixed the delete document I don't know why the tool generated it, it isn't correct.

2022-11-17 01:04 UTC, opbld31 commented
Learn Build status updates of commit _[23a1ca5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23a1ca5a25208768ff4ea4a4f5cedcc4461f0d76)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-88919aa7)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-88919aa7)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-88919aa7)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-88919aa7)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-88919aa7)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-88919aa7)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-88919aa7)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-88919aa7)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-88919aa7)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-88919aa7)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-88919aa7)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-88919aa7)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-88919aa7)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-88919aa7)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-88919aa7)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-88919aa7)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-17 01:05 UTC, TarkanSevilmis commented on concepts/permissions-reference.md
> +* _BusinessScenarioConfig.Read.OwnedBy_: Create a new business scenario (`POST /solutions/businessScenarios`)
Yeah, the permission document sample should have been readwrite. fixing

2022-11-17 01:16 UTC, TarkanSevilmis commented on concepts/permissions-reference.md
> +* _BusinessScenarioConfig.ReadWrite.OwnedBy_: Update the Planner plan configuration for a business scenario (`PATCH /solutions/businessScenarios(uniqueName='com.contoso.orderManagement')/planner/plan
updating a bunch of these, yes they should all have the alternate key option.

2022-11-17 01:16 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +---
That will come out later, with a separate document update when it is available

2022-11-17 01:36 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +---
No, API md is correct, but I'm not really sure how to document this. So, task details is inherited from plannerTask which is the base type of the scenario type, so ability to edit the contained navigations come from the task, and is not really specific to business scenario API. Should we specifically create copy specific to the business scenario side access? I guess that makes the most sense.

2022-11-17 01:38 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenariotask-get.md
> +GET /solutions/businessScenarios/{businessScenarioId}/planner/tasks/{businessScenarioTaskId}
Unfortunately, AGS has a bug right now, so this won't work for the external id. We can update the docs when it is fixed.

2022-11-17 01:41 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenarioplanner-getplan.md
> +Get information about the [plannerPlan](../resources/plannerplan.md) mapped to a given target.
Added with minor changes.

2022-11-17 01:46 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +GET https://graph.microsoft.com/beta/solutions/businessScenarios/{businessScenarioId}
Added these

2022-11-17 01:47 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +{
Working on the responses, the URLs should be up to date

2022-11-17 01:49 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenarioplanreference.md
> +|[getPlan](../api/businessscenarioplanner-getplan.md)|[businessScenarioPlanReference](../resources/businessscenarioplanreference.md)|Get the reference to the plan that corresponds to the given target
Sounds good. I kind of feel like people wouldn't be going around checking pages for whether they are consistent or not, they would be just looking at whether the page helped me or not. but that may just be me.

2022-11-17 01:51 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenarioplanner-post-tasks.md
> +If successful, this method returns a `201 Created` response code and a [businessScenarioTask](../resources/businessscenariotask.md) object in the response body.
Did you mean "post localizations" in the second sample? 201s are correct.  POST operations need to respond with 201 created, not 200 OK.

2022-11-17 01:53 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenarioplanner.md
> +|Method|Return type|Description|
Update doesn't exist since there is nothing to update, I missed that when I was removing stuff. Get does exist, but it isn't very helpful (this type has no properties, it exists because we want the url segment). I can keep it or remove it.

2022-11-17 01:56 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +GET /solutions/businessScenarios/{businessScenarioId}
Both are supported. I'll update the urls, but I'll update the samples later with adding sample content to them.

2022-11-17 02:29 UTC, opbld30 commented
Learn Build status updates of commit _[91dffa2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91dffa248c7cdc0ca75e6b3a2900b5f85c7e3f51)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-efba4982)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-efba4982)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-efba4982)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-efba4982)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-efba4982)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-efba4982)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-efba4982)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-efba4982)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-efba4982)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-efba4982)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-efba4982)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-efba4982)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-efba4982)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-efba4982)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-efba4982)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-efba4982)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-17 04:24 UTC, angelgolfer-ms commented on concepts/businessscenarios-concept-overview.md
> +# Business Scenarios API overview (preview)
Hi @TarkanSevilmis , FYI please use sentence case for feature names such as "business scenarios". 
These are the capitalization rules in docs:  https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357

BTW, just to be clear and reiterate so as not to cause anybody confusion, @Jarbas-MSFT is the content reviewer for this PR. I am entering comments as I happen to go over the PR to get a good understanding of the feature/API set. You guys might find that I comment in some places but not in others that have a similar issue, and that's because I am not in a position with the given time to do a thorough read of the entire PR.

2022-11-17 04:38 UTC, angelgolfer-ms commented on concepts/businessscenarios-concept-overview.md
> +Business Scenarios allow integration of real work business processes into native Microsoft Graph entities. Business Scenarios allow applications to create data in the tenant that looks like any other
Line 11:
For the first sentence, is it correct if we say this instead:
"The business scenarios API allows apps to model and integrate real work business processes with a Microsoft 365 service over Microsoft Graph."

"allow integration" would be more informative if we can indicate "who is doing the integration".
Also, integrating a _process_ into a REST API entity is a little vague.
Making the changes would be in line with [Microsoft Voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25356), being crisp and clear removing any ambiguity where we can.

Also the second sentence talks about creating data which implicitly means such data would reside in some Microsoft Graph resources.

2022-11-18 01:18 UTC, JarbasHorst commented on api-reference/beta/resources/businessscenarioplanner.md
> +|Method|Return type|Description|
Thanks for removing the update method. We don't need to remove the GET method if this is supported.

2022-11-18 01:18 UTC, JarbasHorst commented on api-reference/beta/api/businessscenarioplanner-getplan.md
> +Get information about the [plannerPlan](../resources/plannerplan.md) mapped to a given target.
Thanks.

2022-11-18 01:34 UTC, JarbasHorst commented on api-reference/beta/api/businessscenarioplanner-delete-tasks.md
> +``` http
Should this API also support the request using the uniqueName? Asking because the example in the permissions-reference.md file shows a request URL with the uniqueName and the externalObjectId.

BTW, if externalObjectId isn't support currently, please, update the example in the permissions-reference.md file to just include the task  ID.

2022-11-18 01:48 UTC, JarbasHorst commented on api-reference/beta/resources/businessscenario-planner-overview.md
> +---
Based on our internal discussion per email, this concept topic will be surfaced as a service overview topic. In this case, please restructure this content to align with the requirements for service topics. For an example, see https://learn.microsoft.com/en-us/graph/browser-edge-concept-overview?view=graph-rest-beta

Missing content:
- Value proposition: https://devblogs.microsoft.com/microsoft365dev/announcing-updates-to-the-planner-api-in-microsoft-graph/#business-scenario-capabilities-for-planner-in-microsoft-graph
- API reference
- Next steps

2022-11-18 01:48 UTC, JarbasHorst commented on concepts/businessscenarios-concept-overview.md
> +---
For consistency, I think it would be valuable to add the value proposition for the central configuration use case: https://devblogs.microsoft.com/microsoft365dev/announcing-updates-to-the-planner-api-in-microsoft-graph/#principles-of-business-scenarios

2022-11-18 01:48 UTC, JarbasHorst commented on api-reference/beta/resources/businessscenario-overview.md
> +
For consistency, please add to this article the "Common use cases" section. For an exmaple, see https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/browser-edge-api-overview.md#common-use-cases

2022-11-18 01:50 UTC, opbld34 commented
Learn Build status updates of commit _[5175f0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5175f0dac5974207043d954b3bdaa8fa71161ba1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-f31c76e8)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-f31c76e8)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-f31c76e8)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-f31c76e8)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-f31c76e8)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-f31c76e8)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-f31c76e8)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-f31c76e8)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-f31c76e8)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-f31c76e8)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-f31c76e8)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-f31c76e8)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-f31c76e8)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-f31c76e8)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-f31c76e8)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-f31c76e8)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-18 18:17 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +GET https://graph.microsoft.com/beta/solutions/businessScenarios/{businessScenarioId}
Yeah sorry missed that one, it is kind of hard to track everything in a large PR in folders that contain 1000+ files. Anyway, fixed now, will push when I can fix more comments.

2022-11-18 18:20 UTC, TarkanSevilmis commented on api-reference/beta/api/plannertaskconfiguration-update.md
> +**TODO: Remove properties that don't apply**
I'm likely going to miss some, it is hard to keep track of all the files, please add a comment whenever you see one of these.

2022-11-18 23:16 UTC, opbld34 commented
Learn Build status updates of commit _[7328bb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7328bb44fb023ba251378dffe7dec8e8c3eda692)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-ce12a052)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-ce12a052)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-ce12a052)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-ce12a052)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-ce12a052)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-ce12a052)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-ce12a052)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-ce12a052)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-ce12a052)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-ce12a052)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-ce12a052)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-ce12a052)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-ce12a052)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-ce12a052)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-ce12a052)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-ce12a052)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-18 23:19 UTC, JarbasHorst commented on api-reference/beta/resources/planner-task-rules-overview.md
> +---
Based on our email discussion, this concept topic should be added to the conceptual section under Tasks and Plans. In this case, please move this file from the `/resources` folder to the `/concepts` folder and add a new TOC entry to surface this topic under the conceptual section under Tasks and Plans.

2022-11-24 23:55 UTC, opbld32 commented
Learn Build status updates of commit _[88380a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88380a8d3c91cd0c6c7e01ed4a3c75b835d32319)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-af2cf94a)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-af2cf94a)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-af2cf94a)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-af2cf94a)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-af2cf94a)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-af2cf94a)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-af2cf94a)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-af2cf94a)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-af2cf94a)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-af2cf94a)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-af2cf94a)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-af2cf94a)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-af2cf94a)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-af2cf94a)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-af2cf94a)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-af2cf94a)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-25 00:25 UTC, opbld30 commented
Learn Build status updates of commit _[1d16728](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d1672861f6d08aeab719f735b64433b0248aee3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-c9efc990)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-c9efc990)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-c9efc990)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-c9efc990)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-c9efc990)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-c9efc990)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-c9efc990)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-c9efc990)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-c9efc990)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-c9efc990)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-c9efc990)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-c9efc990)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-c9efc990)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-c9efc990)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-c9efc990)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-c9efc990)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-11-25 00:48 UTC, JarbasHorst commented on api-reference/beta/api/businessscenario-get.md
> +---
@TarkanSevilmis, I have included a see also section here "api-reference/beta/api/businessscenariotask-update.md" to provide the support for /details.

2022-11-25 01:22 UTC, JarbasHorst commented on concepts/businessscenarios-concept-overview.md
> +Business scenarios allow integration of real work business processes into native Microsoft Graph entities. Business scenarios allow applications to create data in the tenant that looks like any other
Readding Angela's comment:

Line 11:
For the first sentence, is it correct if we say this instead:
"The business scenarios API allows apps to model and integrate real work business processes with a Microsoft 365 service over Microsoft Graph."

"allow integration" would be more informative if we can indicate "who is doing the integration".
Also, integrating a process into a REST API entity is a little vague.
Making the changes would be in line with [Microsoft Voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25356), being crisp and clear removing any ambiguity where we can.

We can then let the second sentence to elaborate - the app creating data in Microsoft Graph entities, and specify behaviors for the data and so on.
Is that correct?

2022-11-25 01:22 UTC, JarbasHorst commented on concepts/planner-task-rules-overview.md
> +Depending on the specific entry has either a collection of values or a [fieldRules](plannerfieldrules.md) is specified. Field rules specify a collection of values as default, and provides separate co
Please, rephrase the first sentence to be more specific and clear.

2022-11-25 01:22 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +          href: resources/businessscenario-overview.md
Please, include an update to this toc.yml file to surface the APIs in the TOC.

2022-11-25 01:22 UTC, opbld32 commented
Learn Build status updates of commit _[e0679fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0679fd0f681b647c05db4868f9cf3811611f65c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-46020db3)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-46020db3)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-46020db3)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-46020db3)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-46020db3)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-46020db3)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-46020db3)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-46020db3)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-46020db3)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-46020db3)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-46020db3)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-46020db3)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-46020db3)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-46020db3)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-46020db3)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-46020db3)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-02 20:49 UTC, TarkanSevilmis commented on concepts/businessscenarios-concept-overview.md
> +# Business Scenarios API overview (preview)
Seems to be globally fixed now

2022-12-02 20:57 UTC, TarkanSevilmis commented on concepts/businessscenarios-concept-overview.md
> +Business Scenarios allow integration of real work business processes into native Microsoft Graph entities. Business Scenarios allow applications to create data in the tenant that looks like any other
Tried to clarify this a bit.

2022-12-02 21:33 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenarioplanner-delete-tasks.md
> +``` http
updated permissions reference.md to not use the alternate keys.

2022-12-02 22:40 UTC, opbld32 commented
Learn Build status updates of commit _[4f52c67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f52c6710e9112ad917f22ea0dc98237a5cd6d6a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4daf334a)

<a id="4daf334a"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 4f52c6710e9112ad917f22ea0dc98237a5cd6d6a in branch 2022-01-27-BusinessScenarioAPI of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 2d241bac741e63f010ff1f2183263b27e1d3160e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212022240281857-19015/BuildReport?accessString=00aea7a0a0f81d13d25e6c06c6eca9cfbbb2b8c896d085e1c16c532b717145fe).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 22:51 UTC, opbld30 commented
Learn Build status updates of commit _[4fd81ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fd81ceddfdee3fdb6fe1868186c8cb551635178)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-51f5e97c)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-51f5e97c)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-51f5e97c)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-51f5e97c)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-51f5e97c)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-51f5e97c)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-51f5e97c)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-51f5e97c)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-51f5e97c)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-51f5e97c)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-51f5e97c)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-51f5e97c)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-51f5e97c)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-51f5e97c)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-51f5e97c)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-51f5e97c)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-02 22:57 UTC, TarkanSevilmis commented on api-reference/beta/toc.yml
> +          href: resources/businessscenario-overview.md
Sorry I don't follow this comment

2022-12-02 23:00 UTC, TarkanSevilmis commented on changelog/Microsoft.Office.Tasks.json
> +          "ChangedApiName": "plannerBucketPropertyRule",
I removed these from the changelog as well. Them being in CSDL is a mistake. Nothing accepts or returns these right now. They are hidden by nature; they are going to be used later with another feature.

2022-12-02 23:15 UTC, Jarbas-MSFT commented on api-reference/beta/toc.yml
> +          href: resources/businessscenario-overview.md
We should add to this TOC section all resource topics and their supported methods. For an example, see https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta.

2022-12-03 01:23 UTC, opbld33 commented
Learn Build status updates of commit _[23c946d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23c946d4ec8d0411f661c572632443fd097cbb6c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-0e2d4817)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-0e2d4817)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-0e2d4817)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-0e2d4817)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-0e2d4817)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-0e2d4817)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-0e2d4817)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-0e2d4817)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-0e2d4817)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-0e2d4817)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-0e2d4817)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-0e2d4817)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-0e2d4817)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-0e2d4817)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-0e2d4817)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-0e2d4817)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 05:03 UTC, angelgolfer-ms commented on concepts/planner-task-rules-overview.md
> +
GLOBAL for this topic:
@TarkanSevilmis , please fix the links in this topic that point to reference topics. Because now that this topic is in the conceptual section, those pre-existing links to topics in the reference section are broken.

2022-12-03 05:19 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-planner-overview.md
> +
@TarkanSevilmis , I recall from our Teams meeting on 11/18, you mentioned that a notable value of the business scenarios API is to allow customers to bring in custom data as new entities in Microsoft Graph.

Is this the topic where you can more clearly point that out, such as in the summary in line 11?

2022-12-03 05:55 UTC, opbld31 commented
Learn Build status updates of commit _[846f1b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/846f1b964eec593736fbd05a2acf843c7129f526)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-d3e27089)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-d3e27089)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-d3e27089)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-d3e27089)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-d3e27089)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-d3e27089)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-d3e27089)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-d3e27089)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-d3e27089)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-d3e27089)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-d3e27089)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-d3e27089)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-d3e27089)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-d3e27089)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-d3e27089)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-d3e27089)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 05:58 UTC, opbld31 commented
Learn Build status updates of commit _[6590eb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6590eb9e2749f727d2c3533899b62d9a103af929)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-8f9fc073)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-8f9fc073)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-8f9fc073)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-8f9fc073)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-8f9fc073)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-8f9fc073)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-8f9fc073)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-8f9fc073)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-8f9fc073)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-8f9fc073)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-8f9fc073)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-8f9fc073)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-8f9fc073)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-8f9fc073)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-8f9fc073)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-8f9fc073)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 08:44 UTC, opbld33 commented
Learn Build status updates of commit _[39d7920](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39d792015ce73698856b77d8470eb5ff55f57fb0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-e17f4f9b)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-e17f4f9b)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-e17f4f9b)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-e17f4f9b)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-e17f4f9b)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-e17f4f9b)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-e17f4f9b)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-e17f4f9b)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-e17f4f9b)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-e17f4f9b)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-e17f4f9b)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-e17f4f9b)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-e17f4f9b)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-e17f4f9b)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-e17f4f9b)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-e17f4f9b)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 08:58 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-overview.md
> +Business scenarios currently support creating content for the following services:
@TarkanSevilmis , FYI, per Microsoft Writing Style Guide, we cannot have a bullet list (or any list) with only one item.
I think you might be trying to make it more obvious that as other services support the business scenarios API, they should follow the structure?

2022-12-03 09:02 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-overview.md
> +Business scenarios currently support creating content for the following services:
Line 21:
If you want to use "business scenario" to refer to this feature, and not just any business scenarios in natural language, I think we should refer to the "business scenarios API" instead.

FYI I am going to make this change in the PR. If there's a reason we shouldn't be doing that, please let me know on Teams. I will let @Jarbas-MSFT  continue to follow up on the comments and incorporation in this PR, so I probably won't be actively checking the progress of this PR.

2022-12-03 09:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-overview.md
> +
Line 17:
"configurations for entities that can be managed with the scenario" - do you mean "configurations for entities that you can manage for the scenario"? ("You" being the app developer, which is the default audience for the Microsoft Graph docs.)

FYI "can be managed" in passive voice is an example of what we generally want to avoid in docs writing. Using passive voice lacks a well-defined subject and makes the content vague and ambiguous.

2022-12-03 09:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-overview.md
> +
Line 17:
Also, in the prior phrase - "The business scenario contains general information about the scenario..." - I think you're referring to the businessScenario entity contains general info... In this case, FYI you cannot use the term styled as normal text which implies indeed business scenario in natural language. It's ambiguous, and Loc will probably get it just as confusing. Instead you'd have to style it as bold which is the way we style names of a resource, property, action, and function in the Microsoft Graph API.
For efficiency, I'm just going ahead to fix this. 

(Just to be clear, what I'm trying to do right now is not exactly editing per se. I am trying to verify the learning experience by navigating the few conceptual and API overview topics as we add them to the TOCs, and as part of that, I wanted to make sure the content in each overview topic does its job, at least per what I understand about the API.)

2022-12-03 09:46 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-overview.md
> +
Line 17:
The last phrase - "which allows the scenario to be accessed by the application independent of the instance-specific identifier" - are you referring to the recommendation of using the reverse domain name format in assigning a value to the uniqueName property to access that **businessScenario** instance, instead of using the id property? 

Assuming that's the case, I can rephrase it to make this a bit clearer. Please let me know if that's incorrect.

2022-12-03 10:31 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-planner-overview.md
> +---
On closer look at the content of this topic, and responding to @TarkanSevilmis in an 12/2 email, the content of this topic is actually not so much about value proposition of using the business scenarios API in Planner, but instead describing Planner's integration with the API.
So I suggest the following:
(a) Because we're currently nesting the business scenarios API as a subnode under Planner, for the time being, we'll list this topic as a second API-level overview under the "Business scenarios" subnode. (I have done this step in the PR tonight.)

(b) As for the value proposition in the service-level overview (planner-concept-overview.md), that's still a necessity.  @TarkanSevilmis , can you please add a subsection under [Why integrate with Planner tasks](https://review.learn.microsoft.com/en-us/graph/planner-concept-overview?branch=pr-en-us-19015#why-integrate-with-planner-tasks) to expose the value brought about by Planner's support of the business scenarios API?

Thanks. And sorry for the confusion. Staging the overview topics helps verifying the experience and content more clearly.

2022-12-03 10:36 UTC, angelgolfer-ms commented on api-reference/beta/resources/businessscenario-planner-overview.md
> +
Lines 11 and 15:
FYI I am going to rephrase these sentences to refer to "business scenarios" or "the business scenarios API" more unambiguously. The reason is as mentioned in a couple of comments above for the businessscenario-overview.md topic, such as this [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/19015/files#r1038754714).

2022-12-03 10:44 UTC, opbld30 commented
Learn Build status updates of commit _[8552ffa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8552ffac71b7ee79adc4c1fa821e6305597c69b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-25b87e16)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-25b87e16)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-25b87e16)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-25b87e16)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-25b87e16)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-25b87e16)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-25b87e16)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-25b87e16)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-25b87e16)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-25b87e16)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-25b87e16)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-25b87e16)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-25b87e16)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-25b87e16)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-25b87e16)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-25b87e16)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 10:53 UTC, opbld32 commented
Learn Build status updates of commit _[2b7b279](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b7b27941bb0d78bfb1c86ee332ad98ae971057a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-172431a1)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-172431a1)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-172431a1)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-172431a1)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-172431a1)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-172431a1)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-172431a1)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-172431a1)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-172431a1)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-172431a1)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-172431a1)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-172431a1)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-172431a1)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-172431a1)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-172431a1)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-172431a1)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 11:01 UTC, angelgolfer-ms requested changes
Hi @TarkanSevilmis , @Jarbas-MSFT , FYI I added a few more topics to the reference TOC, including now 2 API-level overviews under the "Business scenarios" subnode under "Tasks and plans". I added a few entities and some of their CRUD operations just to verify the learning experience when navigating the TOC. 
Please make sure to **add any remaining CRUD operations** to the reference under the "Business scenarios" subnode. Please also check if I left out any entities there and add them and their methods accordingly to the TOC, but I think I might have added all the applicable entities.

Please also note I reordered the pre-existing subnodes in the reference under "Tasks and plans" to follow the order specified in this [topic](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title) as follows:
"Order resource nodes alphabetically, except if a resource node is the main entity for that API set, in which case list the main entity first. For example, under the Mail TOC node, list the main entity Message for the mail API first, and order the other entities alphabetically."

2022-12-03 22:10 UTC, opbld30 commented
Learn Build status updates of commit _[0af9b9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0af9b9ac0157729d52bfdeb82a6af6eba33c5be0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-91f669b0)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-91f669b0)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-91f669b0)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-91f669b0)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-91f669b0)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-91f669b0)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-91f669b0)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-91f669b0)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-91f669b0)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-91f669b0)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-91f669b0)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-91f669b0)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-91f669b0)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-91f669b0)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-91f669b0)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-91f669b0)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 22:24 UTC, opbld31 commented
Learn Build status updates of commit _[877c512](https://github.com/microsoftgraph/microsoft-graph-docs/commits/877c51268b5fb188ec4517ca568ff3754ecd4cd4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-d342da06)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-d342da06)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-d342da06)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-d342da06)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-d342da06)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-d342da06)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-d342da06)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-d342da06)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-d342da06)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-d342da06)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-d342da06)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-d342da06)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-d342da06)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-d342da06)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-d342da06)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-d342da06)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 22:31 UTC, opbld33 commented
Learn Build status updates of commit _[934ea50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/934ea500eaa66b77c9850571646a18d55054cd2a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-8e6aa5d2)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-8e6aa5d2)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-8e6aa5d2)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-8e6aa5d2)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-8e6aa5d2)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-8e6aa5d2)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-8e6aa5d2)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-8e6aa5d2)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-8e6aa5d2)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-8e6aa5d2)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-8e6aa5d2)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-8e6aa5d2)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-8e6aa5d2)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-8e6aa5d2)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-8e6aa5d2)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-8e6aa5d2)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 22:36 UTC, opbld34 commented
Learn Build status updates of commit _[bfc0ccb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfc0ccbeb25d2eda1afe4d525f5ec422de94689e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-a5e8946a)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-a5e8946a)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-a5e8946a)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-a5e8946a)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-a5e8946a)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-a5e8946a)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-a5e8946a)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-a5e8946a)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-a5e8946a)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-a5e8946a)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-a5e8946a)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-a5e8946a)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-a5e8946a)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-a5e8946a)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-a5e8946a)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-a5e8946a)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-03 22:51 UTC, Jarbas-MSFT commented on api-reference/beta/toc.yml
> +          href: resources/businessscenario-overview.md
Angela has already started to apply the required changes to the TOC, however, we still need the additional supported methods for each resource topic. Additionally, the resource topic about localization (api-reference/beta/resources/plannerplanconfigurationbucketlocalization.md) and its supported methods should also be added to the TOC.

2022-12-05 21:42 UTC, opbld31 commented
Learn Build status updates of commit _[0610afa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0610afac819b58fa857a08d6a2204232398d6476)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-1ee475a3)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-1ee475a3)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-1ee475a3)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-1ee475a3)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-1ee475a3)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-1ee475a3)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-1ee475a3)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-1ee475a3)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-1ee475a3)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-1ee475a3)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-1ee475a3)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-1ee475a3)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-1ee475a3)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-1ee475a3)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-1ee475a3)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-1ee475a3)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-07 01:24 UTC, opbld30 commented
Learn Build status updates of commit _[d6716a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6716a641d789e1942ce15dc680a358592464c21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-c0612299)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-c0612299)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-c0612299)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-c0612299)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-c0612299)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-c0612299)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-c0612299)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-c0612299)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-c0612299)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-c0612299)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-c0612299)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-c0612299)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-c0612299)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-c0612299)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-c0612299)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-c0612299)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-08 19:36 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +{
All sample requests are updated now

2022-12-08 19:37 UTC, opbld31 commented
Learn Build status updates of commit _[bf591b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf591b5ad1da9b3644b24e647e0aa46ff64aa51e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-e442d35d)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-e442d35d)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-e442d35d)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-e442d35d)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-e442d35d)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-e442d35d)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-e442d35d)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-e442d35d)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-e442d35d)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-e442d35d)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-e442d35d)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-e442d35d)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-e442d35d)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-e442d35d)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-e442d35d)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-e442d35d)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-09 00:50 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenario-planner-overview.md
> +---
Added content in planner concept overview to mention and link to business scenario concept overview.

2022-12-09 01:03 UTC, opbld30 commented
Learn Build status updates of commit _[c1263bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1263bd567ef27f2d95f28961db88af954163997)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-24522d96)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-24522d96)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-24522d96)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-24522d96)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-24522d96)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-24522d96)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-24522d96)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-24522d96)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-24522d96)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-24522d96)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-24522d96)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-24522d96)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-24522d96)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-24522d96)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-24522d96)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-24522d96)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-09 02:56 UTC, TarkanSevilmis commented on api-reference/beta/resources/businessscenario-overview.md
> +
These all look good, thanks.

2022-12-09 03:20 UTC, opbld31 commented
Learn Build status updates of commit _[08df363](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08df363441fe7c27345d325dab84bd89cb35601e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-ca7d1af2)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-ca7d1af2)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-ca7d1af2)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-ca7d1af2)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-ca7d1af2)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-ca7d1af2)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-ca7d1af2)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-ca7d1af2)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-ca7d1af2)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-ca7d1af2)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-ca7d1af2)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-ca7d1af2)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-ca7d1af2)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-ca7d1af2)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-ca7d1af2)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-ca7d1af2)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-09 16:57 UTC, opbld31 commented
Learn Build status updates of commit _[ad85f62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad85f622035e1a187af7d9a627f11429bd002014)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-5e7ed25b)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-5e7ed25b)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-5e7ed25b)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-5e7ed25b)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-5e7ed25b)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-5e7ed25b)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-5e7ed25b)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-5e7ed25b)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-5e7ed25b)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-5e7ed25b)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-5e7ed25b)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-5e7ed25b)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-5e7ed25b)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-5e7ed25b)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-5e7ed25b)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-5e7ed25b)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-09 17:24 UTC, opbld33 commented
Learn Build status updates of commit _[034c12a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/034c12aa19f728a05a38d03500384536f537f099)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-e50763e0)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-e50763e0)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-e50763e0)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-e50763e0)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-e50763e0)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-e50763e0)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-e50763e0)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-e50763e0)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-e50763e0)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-e50763e0)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-e50763e0)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-e50763e0)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-e50763e0)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-e50763e0)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-e50763e0)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-e50763e0)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-09 17:26 UTC, opbld31 commented
Learn Build status updates of commit _[cda5109](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cda51095e658ae8e594a11efe44dbc57f39039f7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-3c36286917a8d29ddc4322ba5a545021-bf8ce0a7)
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-38a80c0baaab7216c9be46f9df7ab51d-bf8ce0a7)
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce931d3c8525a4ef42ca41c2f44ba354-bf8ce0a7)
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-6722d832d4b9a8a69ad1b27c4ecabce0-bf8ce0a7)
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-06e40d3339149056d02299a4ae1da31f-bf8ce0a7)
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-09781ed720b6ea0d7107c2ca3b134049-bf8ce0a7)
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-f39de8523a0280ceb248c5e44a27a810-bf8ce0a7)
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d217796daa07520bdcc4795413dd2d79-bf8ce0a7)
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-5b6e5492b68844a91f541917548641b1-bf8ce0a7)
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-ce087c608aa751eba115e28667a2eb34-bf8ce0a7)
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-34db77eb6a637010ca78c171c40e4c81-bf8ce0a7)
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-511e41746348cf62c070b44c9e676d75-bf8ce0a7)
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-54ce05cec9bc0e9f2097904ce1cf527f-bf8ce0a7)
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-d3e414c6098c72a2a44fc0474c2da6c4-bf8ce0a7)
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-225841a297d8a7e2fa94b146dcf49968-bf8ce0a7)
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user-content-66e5a1ad24bd9e1056f377ccc1d02ba5-bf8ce0a7)
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) | [Details](#user- [...]

2022-12-09 20:59 UTC, opbld33 commented
Learn Build status updates of commit _[5bd8b26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bd8b2614aaa208eb6825f57da5874bf8f3ba8c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-3c989d21)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-3c989d21)
[api-reference/beta/api/businessscenario-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenarioplanner-delete-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-delete-tasks.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-delete-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenarioplanner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenarioplanner-getplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-getplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-getplan?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenarioplanner-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-list-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenarioplanner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenarioplanner-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenarioplanner-post-tasks?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenariotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenariotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenariotask-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenariotask-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/businessscenario-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/businessscenario-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/businessscenario-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannerplanconfiguration-delete-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-delete-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-delete-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannerplanconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannerplanconfiguration-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-list-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannerplanconfigurationlocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannerplanconfigurationlocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfigurationlocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfigurationlocalization-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannerplanconfiguration-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-post-localizations?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannerplanconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannerplanconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannerplanconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannertaskconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/plannertaskconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-01-27-BusinessScenarioAPI/api-reference/beta/api/plannertaskconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/plannertaskconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19015) (graph-rest-beta) |
[api-reference/beta/api/solutionsroot-delete-bu [...]

2022-12-13 23:27 UTC, JarbasHorst commented
Hello @isvargasmsft, hello @Lauragra, this PR is ready for final review. Please, take a final look at it before approving it.

2022-12-14 16:04 UTC, isvargasmsft commented
Hello @TarkanSevilmis, 

This PR is in Draft state. Please move it to Open state if you want to publish it. 

In addition, please address the API Doctor errors. You can request help in the API Doctor channel. 

Feel free to ping me on the side if you need help accessing the channel.

2022-12-15 13:20 UTC, isvargasmsft commented on api-reference/beta/resources/plannerpropertyrule.md
> +An abstract base type of all entity rule definitions for Microsoft Planner. For more details, see [plannerTaskPropertyRule](plannertaskpropertyrule.md).
```suggestion
An abstract base type of all entity rule definitions for Microsoft Planner. 

Base type of [plannerTaskPropertyRule](plannertaskpropertyrule.md).
```

2022-12-15 20:56 UTC, isvargasmsft commented on api-reference/beta/api/businessscenario-get.md
> +---
Missing in this PR:
- Resource topics and changelog entries for plannerBucketPropertyRule and plannerPlanPropertyRule complex types.

2022-12-15 21:55 UTC, isvargasmsft commented
Hello @TarkanSevilmis, please also address the API Doctor errors in the PR. You can request assistance in the API Doctor channel in Teams.

2023-01-10 17:29 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +---
These are omitted intentionally. These types were accidentally included in the CSDL, they are not returned or accepted by any operation today. They will be documented when we add functions to use them

2023-01-10 19:16 UTC, TarkanSevilmis commented on api-reference/beta/api/businessscenario-get.md
> +---
These are intentionally omitted. They were accidentally included in the CSDL, and no operation will return or accept them today. They will be documented when we have operations that actually use them

2023-01-11 05:30 UTC, Lauragra approved these changes

2023-01-11 05:31 UTC, merged