Add description for alert workflow
microsoftgraph/microsoft-graph-docs pull request #19059
Opened 2022-11-01 07:36 UTC by zhishending

2022-11-01 07:39 UTC, opbld32 commented
Learn Build status updates of commit _[044abbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/044abbf93521ffdd1ff74308efa96447a816b6aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDescriptions/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-19059) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211010736540145-19059/BuildReport?accessString=db2c39063b60b48f9f91663618caed703d9cfd55d9e889583ad60c5c9fb632b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-01 07:55 UTC, AshleyYangSZ approved these changes

2022-11-01 08:25 UTC, kennywangms approved these changes

2022-11-03 16:08 UTC, isvargasmsft commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +description: "Represents the entry point entity type to access all alert-related resources. The monitoring APIs provide a programatic alert experience in Microsoft Endpoint Manager(MEM) admin center.
Please move this description to line 16.

2022-11-03 16:08 UTC, isvargasmsft commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +description: "Represents the entry point entity type to access all alert-related resources. The monitoring APIs provide a programatic alert experience in Microsoft Endpoint Manager(MEM) admin center.
Please move this description to line 16.

2022-11-03 16:09 UTC, isvargasmsft commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +description: "Represents the entry point entity type to access all alert-related resources. The monitoring APIs provide a programatic alert experience in Microsoft Endpoint Manager(MEM) admin center.
Please move this description to line 16.

2022-11-03 16:13 UTC, isvargasmsft requested changes
Hello @zhishending, 

Please move the description to line 16 where it is visible for customers. The description in the topic metadata (line 3 in this case) is used for search engines mostly.

Kind regards,

Isaac Vargas

2022-11-12 01:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +description: "Represents the entry point entity type to access all alert-related resources. The monitoring APIs provide a programatic alert experience in Microsoft Endpoint Manager(MEM) admin center.
Line 3:
@zhishending , wanted to explain this - line 3 is metadata that is not displayed to customers on the docs site. Everything from lines 1-9 is not visible there.
In general, it's useful to check how your content looks to customers by going to the staging site. When your commit is built successfully, the OPS build info (prefixed with opbldxx, like "opbld32") would show a table of the topics that have been built. That table has a "Preview URL" column, and each topic that has been built has a "View" link. Click that link to see how the topic is staged on the staging site for your PR.

2022-11-12 02:05 UTC, angelgolfer-ms commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +description: "Represents the entry point entity type to access all alert-related resources. The monitoring APIs provide a programatic alert experience in Microsoft Endpoint Manager(MEM) admin center.
I have some more feedback in an email about the content that would be helpful for customers to gain enough context. I will send it in a short while.

2022-11-12 11:44 UTC, angelgolfer-ms requested changes
Hi @zhishending , thank you for the follow-up. I entered a few comments, and emailed some more feedback for the content and the TOC issue we had discussed on Teams. Please take a look. Thank you!

2022-11-22 08:33 UTC, opbld30 commented
Learn Build status updates of commit _[a9b5e18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9b5e18ee14045b68152541cf2b5312b2620677d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDescriptions/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-19059) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDescriptions/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-19059) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDescriptions/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-19059) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDescriptions/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-19059) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDescriptions/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-19059) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDescriptions/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-19059) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211220821426762-19059/BuildReport?accessString=350ad0d22160cb48426ed4e9e4328d8c3554123789cb514074dac5cab1c0669e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-16 22:44 UTC, angelgolfer-ms commented on api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
Line 16:
@zhishending , I know the first  sentence of this line has already been published as is. I think we can clarify this better though - the portalNotification type doesn't characterize a notification with any "status" (there's no "status" property), and therefore saying something like setting some "status" to "published" can mislead customers to expect and look for some kind of status-related property, which they won't find. On the other hand, there's this explicit property isPortalNotificationSent. In this case, I think we should just say:
"Set the sent-status of a notification on the Microsoft EndPoint Manager admin center by modifying the **isPortalNotificationSent** property to `true` for the user specified in the request. "

2022-12-16 22:50 UTC, angelgolfer-ms commented on api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
Still line 16:
I see you included "for the user specified in the request".
Can you clarify which request you're referring to?

If I look at the query URL of this methods, there's no segment that represents any user. Can you clarify which user specified where?

2022-12-20 02:58 UTC, angelgolfer-ms commented on api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
In the interest of time, FYI I went through the metadata and it doesn't seem to me a request like the following specifies any particular user:
`POST https://graph.microsoft.com/beta/deviceManagement/monitoring/alertRecords/{alertRecordId}/setPortalNotificationAsSent`

So I am going to remove the phrase "for the user specified in the request". If that's an oversight on my part, please let me know on Teams.

2022-12-20 03:04 UTC, angelgolfer-ms commented on api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
Related to the concept of some specified user - I see that in devicemanagement-portalnotification.md, you had specified as the description:
"Represents the portal notification associated with the alert record of a user." 

How is some user specified in this context of your API?

2022-12-21 07:44 UTC, merged