Change of wording due to upcoming change in behavior for trending APIs
microsoftgraph/microsoft-graph-docs pull request #19064
Opened 2022-11-01 12:33 UTC by einarmr

Changed one paragraph and added one paragraph regarding the consequences of disabling item insights. The service change is already communicated to M365 enterprise customers and will roll out on December 1, 2022.

2022-11-01 12:45 UTC, opbld31 commented
Learn Build status updates of commit _[58354a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58354a255bc614be9cd98053f4841ba03c86c24b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211011233081568-19064/BuildReport?accessString=5b63a5e9c13c454a838133fcdaeba9940161e11ae50adc0cf56948135a92c36e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-01 13:23 UTC, elmakhmu commented on concepts/item-insights-overview.md
> +* Note that _your_ access to experiences showing trending content is _not_ revoked, while _your activities_ are protected from being shared. In other words, when you have item insights disabled you a
Maybe it's worth to highlight the change and specify the difference in experiences before/after 1Dec plus wrap it using
> [!NOTE]
>

what do you think @angelgolfer-ms ?

2022-11-01 13:23 UTC, elmakhmu commented on concepts/item-insights-overview.md
>  ![disabled item insights in Delve](images/disabled-item-insights-in-delve.PNG)
we might need +1 screenshot displaying Delve->Me page changes

2022-11-03 12:00 UTC, opbld32 commented
Learn Build status updates of commit _[0ff7188](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ff71887e628286410f257303e475bd4fe663b45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211031158107378-19064/BuildReport?accessString=c9b997a7a6cf98a5f76081e1dca67d219897dcb39fd1e81f6ca2338f42a90043).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-03 12:01 UTC, einarmr commented on concepts/item-insights-overview.md
> +* Note that _your_ access to experiences showing trending content is _not_ revoked, while _your activities_ are protected from being shared. In other words, when you have item insights disabled you a
Yes, thanks for the tip. I highlighted the upcoming change in a NOTE section now.

2022-11-03 12:12 UTC, einarmr commented on concepts/item-insights-overview.md
>  ![disabled item insights in Delve](images/disabled-item-insights-in-delve.PNG)
I think the "NOTE" section that I added should be sufficient. Let's not make a bigger thing out of it.

2022-11-05 01:39 UTC, Lauragra commented on concepts/item-insights-overview.md
> +1. Note that _your_ access to experiences showing trending content is _not_ revoked, while _your activities_ are protected from being shared. In other words, when you have item insights disabled you
Remove "Note that" from the text here.

2022-11-05 01:39 UTC, Lauragra commented on concepts/item-insights-overview.md
> +1. Disabling item insights will stop [suggested meeting hours](https://support.microsoft.com/office/update-your-meeting-hours-using-the-profile-card-0613d113-d7c1-4faa-bb11-c8ba30a78ef1) from being c
We've already set the context that item insights is disabled, so please rephrase this as:
Suggested meeting hours will no longer be calculated and shown to the user on their persona card.

2022-11-05 01:41 UTC, Lauragra commented on concepts/item-insights-overview.md
> +> Item [4] in the list above is a change in behavior that was put into effect on December 1, 2022. Previously, users who had item insights turned off were not themselves able to use experiences with
I'm not sure that we want to specify a date here as over time this will get outdated unless we remove it later. We can just publish this update on December 1. If you want to call attention to the change, you can publish a blog post that describes the change and links to this topic.

2022-11-05 02:40 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
>  ![disabled item insights in recommended in office](images/disabled-item-insights-in-office.PNG)
Line 60:
I just noticed this was from a previous update, not this PR - FYI I tweaked the last part of the sentence because technically, when we bold a term which appears in the UI ("Recommended"), we should refer to the term as a UI string so that it's not ambiguous for Loc. 

I changed the original phrase "such as the **Recommended** files in Office.com and Delve"
to "such as the **Recommended** section of files in Office.com and Delve".

2022-11-05 03:13 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +1. Your colleagues can still see files that you have shared with them from OneDrive for Business and SharePoint in experiences such as Delve and [the profile cards in Microsoft 365](https://support.m
Line 62:
Again, I know my next comment applies to something added in a previous PR, nonetheless, there might be room for clarification. 
Regarding the phrase "To avoid seeing shared files in these places", does replacing the phrase by "to prevent these places from displaying shared files" cover the behavior?
I find it a bit odd to say "to avoid seeing", because technically, one can just avert or close their eyes, not go to Delve, nor open any profile card. I also wonder how different languages have handled this (even though I'm not about to check every localized language now...).

2022-11-05 03:28 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> -* Microsoft stops using your signals when computing recommendations for others. Your colleagues stop receiving item insights based on activities that you perform in shared workspaces, and your collea
Lines 60-66:
FYI in docs, when we number the items in a list, we're saying there's an order for the items. In our developer docs, typically we use numbered lists to show steps in a process. For more info, see this topic in the Microsoft Writing Style Guide: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=56575

So, please change this back to a bullet list.

2022-11-05 03:53 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +1. Disabling item insights will stop [suggested meeting hours](https://support.microsoft.com/office/update-your-meeting-hours-using-the-profile-card-0613d113-d7c1-4faa-bb11-c8ba30a78ef1) from being c
Line 66:
1 comment and 2 questions: 
FYI I changed the first part of the sentence from future tense to present tense. That is "Disabling item insights will stop..." has become "Disabling item insights stops..."
This is because in docs, as long as the behavior is already implemented, even though there is a cause and effect relationshop between the 2 actions, we still use present tense. 

Questions:
(a) Regarding "... shown to the user...", are you referring to any user who is viewing a specific user's persona card, not just a user's viewing his/her own persona card and stop seeing suggested meeting hours, right?
If that's the case, then please rephrase as:
"Disabling item insights stops suggested meeting hours from being calculated and displayed on a user's persona card shown for other users."

(b) Regarding "persona card" - do you mean profile card as described here: https://support.microsoft.com/en-us/office/profile-cards-in-microsoft-365-e80f931f-5fc4-4a59-ba6e-c1e35a85b501

FYI searching for "persona card" on the internet in the context of Microsoft 365 is not returning me any relevant results. I just want to make sure we're using a term that end users and admin users recognize, and is used in end user and admin docs as well.

2022-11-05 04:12 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +1. Experiences that show content trending around you is inaccessible to others, in places such as Delve and Outlook mobile’s **Discover** section. The lack of the trending insights also affect your p
Line 63:
1 comment and 1 question:
FYI the verb "affect" would have to be "affects", because the subject is actually "the lack of ..." which is uncountable. The subject is not "trending insights". :-)

Question:
I know the use of the "affect" verb is from a previous PR. Nonetheless, is there another verb that is less vague than "affect", such as "reduces your personalized relevance..."?

2022-11-05 04:47 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +1. Note that _your_ access to experiences showing trending content is _not_ revoked, while _your activities_ are protected from being shared. In other words, when you have item insights disabled you
May I tag on and suggest a further revision?
Perhaps we shouldn't associate _not_ sharing any data about oneself with the word "protected", allowing the room for customers to interpret that sharing would be a bad thing and the user is unprotected or less protected?  
After all, our uber message for these insights features is, there's sufficient control and customers should not be concerned as long as they use those controls depending on their preference. 

Also, in the first sentence, I think "activities" may be a bit broad, because in the context of Microsoft Graph, there are many other well-known activities, such as messaging, meeting, etc.

So, what about:
"Insights about your file-based activities are no longer shared with others. "
Or even:
"File-based insights about you are not longer shared with others."

Just picking one of the above two and continuing:
"Insights about your file-based activities are no longer shared with others, protecting you from undesirable discovery of your data. On the other hand, your access to experiences showing trending content is not revoked. You can see the activities and data of users who have not disabled item insights."

2022-11-05 05:27 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +> Item [4] in the list above is a change in behavior that was put into effect on December 1, 2022. Previously, users who had item insights turned off were not themselves able to use experiences with
I agree with Lauragra's comment - this type of information about transitioning from one behavior to another behavior should go to a blog post. FYI, in general, documentation should show the current behavior with no ambiguity. This is the expectation that has been set up for customers about docs over the years.

2022-11-05 05:35 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +> Item [4] in the list above is a change in behavior that was put into effect on December 1, 2022. Previously, users who had item insights turned off were not themselves able to use experiences with
Nonetheless, the following comment is for your blog draft:
You have used the terms "empty page" or "remain empty" for Delve. 
I don't have admin control to see what the experience actually is, perhaps indeed Delve doesn't display any trending documents anyway. In this case, at two levels:
- I would hope the Delve UI actually has a short message that says something to the effect of "there are no documents to display for your organization as your admin has disabled display of popular documents", or just some message. IMO a real empty page in Delve without any message may make customers think that Delve is broken or still trying to return results.
- In your eventual blog draft, instead of "empty", you can please say something to the effect of, "Delve doesn't display documents trending in the organization".

2022-11-05 05:42 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +
Extending my last comment about not describing historical changes in docs, since it's been a while that the mechanism for admins to disable displaying insights has come  into effect, @elmakhmu or @einarmr , can you please look into removing this Background section in the other concept topic: https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=main#background

We let that get into the docs initially to call out actions taken to address customers' concerns about privacy. Since the change has been in place for a while now, as Lauragra and I mentioned above, we can snap back into consistency. 

If either of you can plan to do that in the near future, that would be good. Thanks in advance.

2022-11-05 05:49 UTC, angelgolfer-ms requested changes
Thanks for the PR. I have a few comments, please take a look. As a heads-up, some of my comments apply to updates in the same section that came from a previous PR. I hope @einarmr, or an appropriate person on your team, doesn't mind addressing them. In general, even after initial publishing, docs do change to better support customers' needs.

2022-11-05 18:51 UTC, opbld32 commented
Learn Build status updates of commit _[2220b7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2220b7f42b55011c1c5d32910fba2f0331cb1f14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211051848405450-19064/BuildReport?accessString=21dc2b2bfdf61f3046d462b542c5197626ac9ce2f8aa99ea9189344bdde340b5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-05 18:53 UTC, opbld33 commented
Learn Build status updates of commit _[6e34d32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e34d32512b54b46d5cad677d9d13057ddfb229d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211051849009422-19064/BuildReport?accessString=bf2913d853f5675a9190d39fdbb19eb34058c441e6dbb552e5f8410053f814c7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 09:10 UTC, einarmr commented on concepts/item-insights-overview.md
>  ![disabled item insights in recommended in office](images/disabled-item-insights-in-office.PNG)
Very well, thanks

2022-11-07 09:11 UTC, elmakhmu commented on concepts/item-insights-overview.md
> +1. Note that _your_ access to experiences showing trending content is _not_ revoked, while _your activities_ are protected from being shared. In other words, when you have item insights disabled you
Can I add my 2 cents, can we be even more precise saying "Insights about your file-based activities **from collaborative workspace** are no longer shared with others." 

maybe also worth to mention that ACLs are untouched and other users still will have access to the documents (in search for example)

2022-11-07 09:22 UTC, opbld33 commented
Learn Build status updates of commit _[00ed53e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00ed53e07f8b7957daa5df27cf498813d0dde665)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211070908549003-19064/BuildReport?accessString=af1063a9cfe03deecd0aa1b20b2c3c65cba740d4e47deeff84550d986feac720).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 09:22 UTC, einarmr commented on concepts/item-insights-overview.md
> +1. Disabling item insights will stop [suggested meeting hours](https://support.microsoft.com/office/update-your-meeting-hours-using-the-profile-card-0613d113-d7c1-4faa-bb11-c8ba30a78ef1) from being c
Thanks, done

2022-11-07 09:24 UTC, opbld32 commented
Learn Build status updates of commit _[634de5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/634de5dac6feb6541b58b9e9bc490b20bb502180)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211070922234545-19064/BuildReport?accessString=d20af8a097bda6e690d033172c2568415d0abe0852b51ae48f3e491cb5298b9d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 10:31 UTC, einarmr commented on concepts/item-insights-overview.md
> +1. Note that _your_ access to experiences showing trending content is _not_ revoked, while _your activities_ are protected from being shared. In other words, when you have item insights disabled you
Thanks @elmakhmu, @Lauragra, @angelgolfer-ms. I merged your suggestions, I think it looks great now. 
@elmakhmu, regarding your point on ACLs, I think this is already very well described in the earlier paragraphs (especially in the paragraph with Alice, Robert, Kate), so I chose to skip that.

2022-11-07 10:43 UTC, opbld32 commented
Learn Build status updates of commit _[9d01118](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d01118fa07529b48bb99f7a73f55b7f080ace98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211071030302971-19064/BuildReport?accessString=bb1c6a5f5cb22e65facbd905933448732b35c6614aec6bcc4f3c901c0b4b7677).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 10:50 UTC, einarmr commented on concepts/item-insights-overview.md
> +> Item [4] in the list above is a change in behavior that was put into effect on December 1, 2022. Previously, users who had item insights turned off were not themselves able to use experiences with
Thanks @angelgolfer-ms, @Lauragra. I consulted with Melinda Jackson and Bill Bär earlier, and they instructed me to publish a message center post to tenants 30 days ahead of the change, as well as to update the documentation. Their view was that no additional communication was needed (like blog posts, etc.). Adding to that, I do not really _want_ to draw much attention towards this change. In case a customer ever wonders (and contacts Microsoft with their questions), we can refer to the updated documentation, and that should be sufficient.

With that context, I will simply remove this "NOTE" section. Please let me know if you (strongly) disagree. @elmakhmu FYI.

Please also note that users with item insights disabled will see an informational banner in Delve from December 1st, with wording along the lines of "Starting Dec 1, 2022, you are permitted to use Delve even though Item Insights is disabled. Your own activities are not being shared. For more information, see the [documentation](https://learn.microsoft.com/en-us/graph/item-insights-overview).

2022-11-07 11:53 UTC, einarmr commented on concepts/item-insights-overview.md
> +1. Your colleagues can still see files that you have shared with them from OneDrive for Business and SharePoint in experiences such as Delve and [the profile cards in Microsoft 365](https://support.m
Done, thanks

2022-11-07 11:54 UTC, opbld31 commented
Learn Build status updates of commit _[d8488f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8488f6dffd1a84a98b3f57176efc9c2c6980548)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211071151407958-19064/BuildReport?accessString=d3894fa9c447055175b091b932c88cdf058a752f9ec95671756e6c747d8b206e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 11:56 UTC, opbld33 commented
Learn Build status updates of commit _[34c4ed9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34c4ed9b627044ed6c0ad476698c4ec6ab272107)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211071153365256-19064/BuildReport?accessString=2acfdeda64b94685c00812b3197d3e77757785b5025e3d42939a50e6c4f9c4d8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 11:56 UTC, einarmr commented on concepts/item-insights-overview.md
> +1. Experiences that show content trending around you is inaccessible to others, in places such as Delve and Outlook mobile’s **Discover** section. The lack of the trending insights also affect your p
Agree, thanks

2022-11-07 11:59 UTC, opbld30 commented
Learn Build status updates of commit _[dcbd909](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcbd90918bd84c57a70989223e9d66e8f36bfd5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211071156350110-19064/BuildReport?accessString=e893d876be8a5af3caae17221d4bf9cf53948f3c5553167ba212f75718c7ba19).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 12:00 UTC, einarmr commented on concepts/item-insights-overview.md
> +1. Disabling item insights will stop [suggested meeting hours](https://support.microsoft.com/office/update-your-meeting-hours-using-the-profile-card-0613d113-d7c1-4faa-bb11-c8ba30a78ef1) from being c
(a) Yes.
(b) Yes.
I also changed this to "**your** profile card", since all the other items refer to "your this" and "your that".

2022-11-07 12:03 UTC, opbld30 commented
Learn Build status updates of commit _[ca26ed7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca26ed7ba0a78d407e2b135548c0fbed1324813f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211071201134808-19064/BuildReport?accessString=8cad2433f1012bfc09ce1c90738393405fd1fad8bf119ee9a64dceeb1415d6d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 12:10 UTC, einarmr commented on concepts/item-insights-overview.md
> +
I agree, this should be fixed. I will keep it outside this PR, though. 
(I see that there is a note in [Transition period](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=main#transition-period) that should be removed too.)

2022-11-08 06:26 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
@einarmr , this question/comment is for the section that starts at line 46:
Is it true that the approaches - admin center, PowerShell, REST API - described in the [customize item insights privacy](https://learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy) topic are all still in public preview?
If so , then per our guidance to apply "(preview)" tag to content in the docs, I think the section describing disabling item insights (starting with line 46) should also be tagged with "(preview)".

I am adding that tagging to line 46 for now. Please confirm.

2022-11-08 07:55 UTC, einarmr commented on concepts/item-insights-overview.md
Very good question. 😊 I believe the best person to answer this is @elmakhmu... Elvira, may I suggest that we just remove the word "preview" from that [other page](https://learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy)? We could do that in a separate PR to keep things clean, though.

2022-11-08 08:24 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
Just to be clear, the docs use "preview" to identify APIs or behaviors that  apply to only beta but not v1. 

So are the capabilities described for the admin center, PowerShell, REST API in the [customize item insights privacy](https://learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy) topic all still in public preview?

2022-11-08 09:14 UTC, opbld34 commented
Learn Build status updates of commit _[0f714a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f714a390cb514fa48c3d01c5c6c73eb31bb5db1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211080912199432-19064/BuildReport?accessString=bfc523c01b74a359f62b7e52360dd8b1aebd7b138452aac6a3094b999ab2c801).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 09:21 UTC, opbld33 commented
Learn Build status updates of commit _[b79ff5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b79ff5ee3ef54606d547017be3868d21b46e0222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211080919310941-19064/BuildReport?accessString=c648caeb3b07e55cd06a000fde5b9968242038360b5e7ed97dd8baa1d4a0067d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 09:23 UTC, einarmr commented on concepts/item-insights-overview.md
Yes, you are correct. This stuff is only exists on 'beta', not on v1.0.

2022-11-08 09:31 UTC, opbld32 commented
Learn Build status updates of commit _[f85b184](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f85b184097513ff22bcc032564d335080fe9d868)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211080928229680-19064/BuildReport?accessString=68944720d0ee65819680fa88538dd5b6c882acfe8cec5d03906a7d9cb0da17b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 09:32 UTC, einarmr commented on concepts/item-insights-overview.md
> +After disabling item insights, the following happens:
@angelgolfer-ms, I changed this line back to the original again. The section above describes how a user can disable item insights herself, while the paragraph above describes that an admin can do so too (and that the admin control "wins" if they're in conflict). 

In other words, there are actually three ways (in total) to have item insights disabled. The admin can disable it for everyone in the organization, the admin can disable it for a security group within the organization, or the user can disable it herself.

2022-11-08 09:34 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +After disabling item insights, the following happens:
@einarmr , I see, I guess you're referring to using REST API or PowerShell to change the insights settings for a user, right?

2022-11-08 09:41 UTC, einarmr commented on concepts/item-insights-overview.md
> +After disabling item insights, the following happens:
Yes. (The screenshot in the section above (from MyAccount) is the user-consented switch.)

2022-11-08 09:42 UTC, elmakhmu commented on concepts/item-insights-overview.md
Confirming that API is still only in beta, however UI toggles in MyAccount and MAC are on prod and even in some Sovereign rings. We are blocked by other service, this issue I hope will be solved in CY2023

2022-11-09 06:46 UTC, opbld34 commented
Learn Build status updates of commit _[83e5ccf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83e5ccfd3282851d6164dbc76fd29b6b97cac7cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211090643156694-19064/BuildReport?accessString=2c060cbad081117790fe682534dafa358371a92d7d46f249e9cb44fc57bb6994).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 06:51 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
Thanks for the confirmation, @elmakhmu .
FYI I left the "(preview)" tag in the topic and TOC titles for the [customize item insights privacy](https://learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy) topic. 

Technically, if the topic title doesn't include "in Microsoft Graph", I would just gauge the contents of the topic (which includes the admin center experience that is generally available to admins) and not tag the topic as "(preview)". However, in Microsoft Graph which offers PowerShell and REST APIs, indeed those APIs are in beta only, so it's accurate to tag that title as "preview". And we keep "in Microsoft Graph" in the topic title for SEO.

2022-11-09 07:08 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +* Microsoft stops using your signals when computing recommendations for others. Your colleagues stop receiving item insights based on activities that you perform in shared workspaces. Your colleagues
Line 59:
Thanks for reminding me that disabling item insights is not an admin-only task.
The following comments are FYI just in case anyone wonders why I changed from "After disabling item insights" to "After your item insights are disabled" :-)
- For reminding readers that as in line 54, we're talking about disabling "your item insights", as the section continues with that perspective beyond line 59.
- Grammatically, if we start a sentence with a gerund phrase, like "Skipping sleep last night", then the next phrase of the same sentence needs a subject, as in, "Skipping sleep last night, I am sleepy today", to clarify who "skipped sleep". So similarly, if we say "After disabling item insights", or "After disabling your item insights", then the next phrase must start with a subject to clarify who does the disabling in the first phrase, but the next phrase doesn't right now. 
- So if we say "After your item insights are disabled", the subject of that phrase becomes "your item insights" (even though it's in passive voice and we generally want to avoid passive voice), so the next phrase doesn't have to clarify the subject of the first phrase anymore.

2022-11-09 07:30 UTC, einarmr commented on concepts/item-insights-overview.md
> +* Microsoft stops using your signals when computing recommendations for others. Your colleagues stop receiving item insights based on activities that you perform in shared workspaces. Your colleagues
Thanks for the great advice 😊

2022-11-09 08:44 UTC, angelgolfer-ms approved these changes
I think the PR looks good now.
Please let me know if you notice any issues otherwise.

2022-11-10 04:14 UTC, opbld33 commented
Learn Build status updates of commit _[59fc280](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59fc28094e4d70943d831d070103f2b6dbc3e751)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211100411245162-19064/BuildReport?accessString=186cf02e24cadcd6468d1cbf61a5d0565bfdde29aac0bcc6d401f070eba7fbe5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 04:16 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +After disabling item insights, the following happens:
While closing my opened browsers for this PR, I discovered your last comment. At a point a couple of days ago, I did find the various ways weren't the clearest anymore especially when skimming the published topic. So FYI I made another commit. 
That would be it for the time being unless anyone finds any issues. Thanks.

2022-11-10 04:16 UTC, opbld30 commented
Learn Build status updates of commit _[f34e27f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f34e27f037ea5ffe0129b6bd4411be2a1fece609)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211100412472105-19064/BuildReport?accessString=0b10fed2b379e79dc4df0cae5fe75e853d006915c13ebd0d0ef8234b6e4959a9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 04:27 UTC, angelgolfer-ms commented
@einarmr , I made another [commit](https://github.com/microsoftgraph/microsoft-graph-docs/pull/19064/commits/59fc28094e4d70943d831d070103f2b6dbc3e751) today to make some more clarifications. I am done for my review unless anyone sees any more issues for now.
When you're ready to publish (the behavior goes live), please follow step 8 of the [content review workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow) to set the PR label to ready to publish.

2022-11-10 04:31 UTC, opbld34 commented
Learn Build status updates of commit _[ca0f30d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca0f30d78296355d0d6b96b589249e34763eaf72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211100428486639-19064/BuildReport?accessString=a3b674797c71eea059a417d4951c2374b80b6e38ddf6ea6a5e6b2906365190c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 08:54 UTC, einarmr commented
Thanks @angelgolfer-ms! I made another minor adjustment to your commit in insights-customize-item-insights-privacy.md. Feel free to make changes to this again 😊

2022-11-10 08:55 UTC, opbld31 commented
Learn Build status updates of commit _[ae1baac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae1baacc15dbd8192ae5ac7293ffef877a5cdc54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211100852521551-19064/BuildReport?accessString=868b4bc8593ad822b5074f93b1907a5957861d17502cf42491973da151c6e5ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 13:07 UTC, opbld31 commented
Learn Build status updates of commit _[7490214](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7490214d62ab5c1372723687084267e6185b7282)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211151304556455-19064/BuildReport?accessString=f1997e0a24004ba14e0aad2363761ac9b1cae69009a7ef481235604f36150e3c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-22 07:58 UTC, opbld34 commented
Learn Build status updates of commit _[1a50360](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a50360b7d2c6ac6b653ef680c2413cfa7ca1bd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211220756261691-19064/BuildReport?accessString=ed26a8e04482c0a0e054652c38e80dd271b77000120ee75eaf734e798c9df86d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 13:52 UTC, opbld32 commented
Learn Build status updates of commit _[e3edef5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3edef58570e8fe9949e743b8b4ec730ded07898)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211241349448247-19064/BuildReport?accessString=707867f6a6e0b97e0998c4a1453060c060fd4993f975fd5242b84533a7f53900).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 08:27 UTC, opbld31 commented
Learn Build status updates of commit _[9a70fe8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a70fe84fac229c56817614e90d7610e9ad148fa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/auth-cloudsolutionprovider.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/auth-cloudsolutionprovider?branch=pr-en-us-19064) | [Details](#user-content-9eb948b1d10d872c914b766f88d74b6f-3f3db4e7)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-19064) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-3f3db4e7)
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-19064) | [Details](#user-content-3577f03000bf8c5ecd840f860e25d5b7-3f3db4e7)
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-19064) | [Details](#user-content-d1b6bde2773610941114fe8704ec4ff2-3f3db4e7)

<a id="9eb948b1d10d872c914b766f88d74b6f-3f3db4e7"></a>
### [concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/auth-cloudsolutionprovider.md)
 - **Line 34, Column 543**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#region' in 'auth-cloudsolutionprovider.md'.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://partner.microsoft.com/cloud-solution-provider' references a disallowed domain 'https://partner.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://portal.azure.com' references a disallowed domain 'https://portal.azure.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://www.powershellgallery.com/packages/AzureAD' references a disallowed domain 'https://www.powershellgallery.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://partnercenter.microsoft.com/partner/developer' references a disallowed domain 'https://partnercenter.microsoft.com'. This poses a security risk.`````
 - **Line 34, Column 535**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'a' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 126, Column 2**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'a' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="25f5577e9853acc2648990df5c8a6d5c-3f3db4e7"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/insights-customize-item-insights-privacy.md)
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://myaccount.microsoft.com/settingsandprivacy/privacy' references a disallowed domain 'https://myaccount.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://www.powershellgallery.com/packages/Microsoft.Graph' references a disallowed domain 'https://www.powershellgallery.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://dotnet.microsoft.com/download/dotnet-framework' references a disallowed domain 'https://dotnet.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://support.microsoft.com/office/connect-and-collaborate-in-office-delve-46f92806-b52c-4187-b60e-b3bf8d25f73e' references a disallowed domain 'https://support.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://support.microsoft.com/office/are-my-documents-safe-in-office-delve-f5f409a2-37ed-4452-8f61-681e5e1836f3' references a disallowed domain 'https://support.microsoft.com'. This poses a security risk.`````

<a id="3577f03000bf8c5ecd840f860e25d5b7-3f3db4e7"></a>
### [concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/item-insights-overview.md)
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://support.microsoft.com/en-us/office/profile-cards-in-microsoft-365-e80f931f-5fc4-4a59-ba6e-c1e35a85b501' references a disallowed domain 'https://support.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://myaccount.microsoft.com/settingsandprivacy/privacy' references a disallowed domain 'https://myaccount.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://support.microsoft.com/office/update-your-meeting-hours-using-the-profile-card-0613d113-d7c1-4faa-bb11-c8ba30a78ef1' references a disallowed domain 'https://support.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://developer.microsoft.com/graph/graph-explorer' references a disallowed domain 'https://developer.microsoft.com'. This poses a security risk.`````

<a id="d1b6bde2773610941114fe8704ec4ff2-3f3db4e7"></a>
### [concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/u/einarmr/item-insights-pay2play/concepts/whats-new-overview.md)
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://developer.microsoft.com/graph/changelog/' references a disallowed domain 'https://developer.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://admin.microsoft.com/' references a disallowed domain 'https://admin.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://developer.microsoft.com/en-us/graph/changelog/?search=&from=2022-10-01&to=2022-10-31' references a disallowed domain 'https://developer.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://aka.ms/graphfeedback' references a disallowed domain 'https://aka.ms'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://aka.ms/m365-dev-call' references a disallowed domain 'https://aka.ms'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://developer.microsoft.com/office/dev-program' references a disallowed domain 'https://developer.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://developer.microsoft.com/graph/blogs/' references [...]

2022-11-29 01:54 UTC, merged