Add property allowedPrincipalTypes to unfiedRoleDefinition entity
microsoftgraph/microsoft-graph-docs pull request #19079
Opened 2022-11-02 03:56 UTC by cubika

Add a new read-only property allowedPrincipalTypes which demonstrates the type of role assignees.

2022-11-02 04:06 UTC, opbld31 commented
Learn Build status updates of commit _[8a65842](https://github.com/cubika/microsoft-graph-docs/commits/8a658426e89bac970badd867df317084a20cffd2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) | [Details](#user-content-705939e19cde9f36f33ff2ab0713064d-9531f60e)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.EnterpriseRbac.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.EnterpriseRbac.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PIM.AzureRBAC.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.PIM.AzureRBAC.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.SharePoint.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.SharePoint.json) | :white_check_mark:Succeeded | |

<a id="705939e19cde9f36f33ff2ab0713064d-9531f60e"></a>
### [api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List roleDefinitions - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/intune-rbac-roledefinition-list.md(2,8), v1.0/api/rbacapplication-list-roledefinitions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List roleDefinitions' is duplicated with other articles: 'v1.0/api/intune-rbac-roledefinition-list.md(10,1), v1.0/api/rbacapplication-list-roledefinitions.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211020356171296-19079/BuildReport?accessString=53d6bc6a281514034a14f9c9379126801739640388f97f0425a89026b6204834).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-02 04:15 UTC, opbld30 commented
Learn Build status updates of commit _[a631b40](https://github.com/cubika/microsoft-graph-docs/commits/a631b406060a5058897bbd4bf86e59cde19c2e2a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) | [Details](#user-content-705939e19cde9f36f33ff2ab0713064d-41f02ea1)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.EnterpriseRbac.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.EnterpriseRbac.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PIM.AzureRBAC.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.PIM.AzureRBAC.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.SharePoint.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.SharePoint.json) | :white_check_mark:Succeeded | |

<a id="705939e19cde9f36f33ff2ab0713064d-41f02ea1"></a>
### [api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List roleDefinitions - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/intune-rbac-roledefinition-list.md(2,8), v1.0/api/rbacapplication-list-roledefinitions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List roleDefinitions' is duplicated with other articles: 'v1.0/api/intune-rbac-roledefinition-list.md(10,1), v1.0/api/rbacapplication-list-roledefinitions.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211020400203798-19079/BuildReport?accessString=796d03ceaf6f3410a9bc5d4ad2675f6eaa75ece2bd68fbf0fee1cc2c1eff1c4d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-02 05:33 UTC, opbld33 commented
Learn Build status updates of commit _[40d04fc](https://github.com/cubika/microsoft-graph-docs/commits/40d04fcd33f0595b8cf9372c1a124ab3e553e3ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) | [Details](#user-content-705939e19cde9f36f33ff2ab0713064d-263f9013)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-19079) (graph-rest-beta) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-19079) (>= graph-rest-1.0) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.EnterpriseRbac.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.EnterpriseRbac.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PIM.AzureRBAC.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.PIM.AzureRBAC.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.SharePoint.json](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/changelog/Microsoft.SharePoint.json) | :white_check_mark:Succeeded | |

<a id="705939e19cde9f36f33ff2ab0713064d-263f9013"></a>
### [api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/cubika/microsoft-graph-docs/blob/unified_rbac_add_role_type/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List roleDefinitions - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/intune-rbac-roledefinition-list.md(2,8), v1.0/api/rbacapplication-list-roledefinitions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List roleDefinitions' is duplicated with other articles: 'v1.0/api/intune-rbac-roledefinition-list.md(10,1), v1.0/api/rbacapplication-list-roledefinitions.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211020524444036-19079/BuildReport?accessString=f2a4e4fdf8db2893d5a9498febadf1ac66f72658e97b1a4831d9957c37d07cb8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 17:46 UTC, FaithOmbongi requested changes
Thank you @cubika for your work on this PR.

I've left a few change suggestions inline plus:

- In the unifiedRoleDefinition.md file (beta +v1.0), all the allowedPrincipalTypes property to the JSON representation section.
- Question: How comes the API returns values in a different casing from the enums casing? i.e. "User" instead of "user"?
- Does this new property support $filter. For example with the `has` operator for enums?

2022-11-07 17:46 UTC, FaithOmbongi commented on api-reference/beta/resources/unifiedroledefinition.md
> +|allowedPrincipalTypes|rolePrincipalTypes|Principal types for role assignees, read-only. The possible values are: `user`, `servicePrincipal`, `group`, `unknownFutureValue`. Optional.|
- Suggestion
- Given this is a flagged enum, confirm the maximum number of values that can be in the string.
- Also add the property to the JSON representation section

```suggestion
|allowedPrincipalTypes|rolePrincipalTypes|Types of principals that can be assigned the role. Read-only. The possible values are: `user`, `servicePrincipal`, `group`, `unknownFutureValue`. This is a multi-valued enumeration that can contain up to three values as a comma-separated string. For example, `user, group`. Optional.|
```

2022-11-07 17:46 UTC, FaithOmbongi commented on api-reference/v1.0/resources/unifiedroledefinition.md
> +|allowedPrincipalTypes|rolePrincipalTypes|Principal types for role assignees, read-only. The possible values are: `user`, `servicePrincipal`, `group`, `unknownFutureValue`. Optional.|
Suggestion.
Given this is a flagged enum, confirm the maximum number of values that can be in the string.
Also add to the JSON representation.
```suggestion
|allowedPrincipalTypes|rolePrincipalTypes|Types of principals that can be assigned the role. Read-only. The possible values are: `user`, `servicePrincipal`, `group`, `unknownFutureValue`. This is a multi-valued enumeration that can contain up to three values as a comma-separated string. For example, `user, group`. Optional.|
```

2022-11-07 17:46 UTC, FaithOmbongi commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +            "allowedPrincipalTypes": "User, Group",
GLOBAL: How comes the API returns values in a different casing from the enums casing?

2022-11-07 17:46 UTC, FaithOmbongi commented on changelog/Microsoft.EnterpriseRbac.json
> +      "SubArea": ""
```suggestion
      "WorkloadArea": "Identity and access",
      "SubArea": "Directory management"
```

2022-11-07 17:46 UTC, FaithOmbongi commented on changelog/Microsoft.EnterpriseRbac.json
> +      "SubArea": ""
```suggestion
      "WorkloadArea": "Identity and access",
      "SubArea": "Directory management"
```

2022-11-07 17:46 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +      "SubArea": "Identity governance"
```suggestion
      "WorkloadArea": "Identity and access",
      "SubArea": "Governance"
```

2022-11-07 17:46 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +      "SubArea": "Identity governance"
```suggestion
      "SubArea": "Governance"
```

2022-11-08 08:47 UTC, cubika commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +            "allowedPrincipalTypes": "User, Group",
I updated all return values to be camelcase.

2022-11-08 08:58 UTC, cubika commented
> Thank you @cubika for your work on this PR.
> 
> I've left a few change suggestions inline plus:
> 
> * In the unifiedRoleDefinition.md file (beta +v1.0), all the allowedPrincipalTypes property to the JSON representation section.
> * Question: How comes the API returns values in a different casing from the enums casing? i.e. "User" instead of "user"?
> * Does this new property support $filter. For example with the `has` operator for enums?

Added the property to the JSON representation. Yes, this property should support $filter, that's the main scenario.

2022-11-25 16:54 UTC, FaithOmbongi commented
Hi @cubika - If this PR is ready for a re-review, please select the **re-request review** icon and add the **review feedback addressed** label.

2023-02-07 15:01 UTC, closed without merging