[CloudPC]add singleSignOn into ProvisioningPolicy and OrganizationSetting
microsoftgraph/microsoft-graph-docs pull request #19104
Opened 2022-11-03 08:56 UTC by Guoan-Tang

2022-11-03 09:07 UTC, opbld31 commented
Learn Build status updates of commit _[7ab41bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ab41bc3b776aba8667024805f5b56a429bd565c)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-5035c07c15a37958f69142ab9b9e0d3c-036521c4)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-036521c4)
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-c0624c6eac38d673f569f47792d35b61-036521c4)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-036521c4)
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |

<a id="5035c07c15a37958f69142ab9b9e0d3c-036521c4"></a>
### [api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-update.md)
 - **Line 46, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="697cad2e2e5111f612c2f6c776737a98-036521c4"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-update.md)
 - **Line 52, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="c0624c6eac38d673f569f47792d35b61-036521c4"></a>
### [api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md)
 - **Line 25, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-036521c4"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 31, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211030857025509-19104/BuildReport?accessString=37c590f44db2fb06dbf2f8729f9aece8b6c1ed56c87d53ad6a1dd234b82f8e3b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 03:05 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcorganizationsettings.md
> +|enableSingleSignOn|Boolean|True if the provisioned Cloud PC can be accessed by single sign-on option, false if the provisioned Cloud PC don't support this feature. Default value is false. Through si
Please update all description to: 
```suggestion
|enableSingleSignOn|Boolean|Describle......When TRUE, indicate...When FALSE, indicate... Default value is.......Through single sign-on, Windows 365 users can authenticate to Azure AD with passwordless options (like FIDO keys) to access their Cloud PC.|No|No|No|
```

2022-11-29 03:06 UTC, AshleyYangSZ commented
@Guoan-Tang Please add change-log which is required for schema PR.

2022-11-29 03:07 UTC, RuiHou105 requested changes
@Guoan-Tang  please 
1.create roadmap workitem and attach the workitem number in comment.
2.Update the changelog to describe all your changes.

2022-12-01 01:51 UTC, opbld33 commented
Learn Build status updates of commit _[b380f78](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b380f7838ee421045c3900b979b41ec55b0cb117)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-c0624c6eac38d673f569f47792d35b61-3428a69e)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-3428a69e)
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c0624c6eac38d673f569f47792d35b61-3428a69e"></a>
### [api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md)
 - **Line 25, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-3428a69e"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 31, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212010149483821-19104/BuildReport?accessString=498ab475d206492792c60f93023c1153a57ec053dbdf62c11eb484982e807190).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-01 01:56 UTC, Guoan-Tang commented
roadmap workitem: 15771

2022-12-02 06:55 UTC, RuiHou105 approved these changes

2022-12-02 06:58 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcorganizationsettings-get.md
> +    "enableSingleSignOn": "true",
It's a boolean, not string
```suggestion
    "enableSingleSignOn": true,
```

2022-12-02 06:59 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +    "enableSingleSignOn": "true",
It's a boolean, not string

```suggestion
    "enableSingleSignOn": true,
```

2022-12-02 06:59 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +    "enableSingleSignOn": "true",
```suggestion
    "enableSingleSignOn": true,
```

2022-12-02 06:59 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +    "enableSingleSignOn": "true",
```suggestion
    "enableSingleSignOn": true,
```

2022-12-02 07:01 UTC, RuiHou105 requested changes
Please resolve all remaining comments.

2022-12-02 07:08 UTC, opbld33 commented
Learn Build status updates of commit _[469ddb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/469ddb80b2824b3ca0557edc9404eac0397838d7)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-c0624c6eac38d673f569f47792d35b61-35a30ae4)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-35a30ae4)
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c0624c6eac38d673f569f47792d35b61-35a30ae4"></a>
### [api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md)
 - **Line 25, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-35a30ae4"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 31, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020706499280-19104/BuildReport?accessString=4a2774547cb4575fbb45181328f86a8aeb5a63e36e04dc20468e4855b174d308).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 07:11 UTC, opbld30 commented
Learn Build status updates of commit _[9398cb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9398cb898757b9382562c8ebaa8b1f8b41e226e6)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-c0624c6eac38d673f569f47792d35b61-81c04cae)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-81c04cae)
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c0624c6eac38d673f569f47792d35b61-81c04cae"></a>
### [api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md)
 - **Line 25, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-81c04cae"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 31, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020707222964-19104/BuildReport?accessString=97fce4311b599a90e6352b180536a3645e456ff4f5516176bc227492eff261e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 07:34 UTC, opbld33 commented
Learn Build status updates of commit _[dd6841b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd6841b6d2ea5f95daec49fffaea1499781498c4)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-c0624c6eac38d673f569f47792d35b61-60e7c66a)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-60e7c66a)
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-19104) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c0624c6eac38d673f569f47792d35b61-60e7c66a"></a>
### [api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcorganizationsettings.md)
 - **Line 25, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-60e7c66a"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/sso/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 31, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020731265159-19104/BuildReport?accessString=f192948ee4b99d68c0e3134ad499b02183dc8043af18c382f7cca139f4031e75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 07:37 UTC, RuiHou105 approved these changes

2023-02-06 23:46 UTC, JarbasHorst commented
@Lauragra, this PR is ready for final review.

2023-02-07 03:33 UTC, Lauragra approved these changes

2023-02-11 03:33 UTC, merged