Add isExactMatchRequired property
microsoftgraph/microsoft-graph-docs pull request #19117
Opened 2022-11-03 23:48 UTC by emzho

2022-11-03 23:50 UTC, opbld34 commented
Learn Build status updates of commit _[3a56705](https://github.com/emzho/microsoft-graph-docs/commits/3a56705a7d84aaa0a088fff215419eb2a4c052db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211032348248561-19117/BuildReport?accessString=fd6e859cbc3db37b93d0e0370dbcd73ee863ba940c505f74abf386d189e27a1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-04 18:57 UTC, opbld30 commented
Learn Build status updates of commit _[2082372](https://github.com/emzho/microsoft-graph-docs/commits/2082372ef27f4eb490d2bf1b1a6c08c27ba52b24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211041854289722-19117/BuildReport?accessString=e45e060ecee325beaf2d14349a25344bb732baf293dcc9d03e361cd35db53dd9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 20:17 UTC, isvargasmsft commented on changelog/Microsoft.Search.json
> +          "Description": "Added the **isExactMatchRequired** property to the [property](https://learn.microsoft.com/en-us/graph/api/resources/property?view=graph-rest-beta) entity.",
```suggestion
          "Description": "Added the **isExactMatchRequired** property to the [property](https://learn.microsoft.com/en-us/graph/api/resources/property?view=graph-rest-beta) resource.",
```

2022-11-07 20:20 UTC, opbld30 commented
Learn Build status updates of commit _[3a5eac8](https://github.com/emzho/microsoft-graph-docs/commits/3a5eac857ecb8aba13f2265024cbf761806cffc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211072018024678-19117/BuildReport?accessString=84c3b6fdaaf1d91a0fe8c8c34197366ef5a52a79f70ccc49987118a16fc087ed).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 20:25 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +### Exact Match Required
```suggestion
### Exact match required
```

2022-11-07 20:31 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +If exact matching is specified for a property, then the full string value will be indexed. Only non-searchable properties can specify exact matching.
Line 78, second sentence: It sound like the property is the one that specifies. Could you please rephrase to indicate what is the desired action from the developer? How can the developer specify this? 

Sugestion:
```suggestion
If exact matching is specified for a property, then the full string value will be indexed. Only non-searchable properties can by specified for exact matching.
```

2022-11-07 20:32 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +- Querying "ticketId:CTS" will NOT return the item with ticket ID "CTS-ce913b61"
```suggestion
- Querying "ticketId:CTS-ce913b61" will return the item with a ticket ID property "CTS-ce913b61".
- Querying "ticketId:CTS" will NOT return the item with ticket ID "CTS-ce913b61".
```

2022-11-07 20:32 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +- Querying "tags:contoso" will NOT return items with the tag "contoso ticket"
```suggestion
- Querying "tags:contoso" will return any item with the tag "contoso".
- Querying "tags:contoso" will NOT return items with the tag "contoso ticket".
```

2022-11-07 20:35 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +For example, there may be a scenario where the item property is a GUID-formatted string. If this property must be matched exactly for item queries, then please specify that `isExactMatchRequired` is
In general, we avoid using the word "please" unless we are requesting the user to perform an inconvenient action.
Details here: https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/please

```suggestion
For example, there may be a scenario where the item property is a GUID-formatted string. If this property must be matched exactly for item queries, specify that `isExactMatchRequired` is true.
```

2022-11-07 20:37 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +The `title` property does not specify exact matching. If nothing is specified, then the `isExactMatchRequired` is false. The `title` property will be tokenized based on the item content language's to
Suggestion:
```suggestion
The `title` property does not specify exact matching. If nothing is specified, then `isExactMatchRequired` is false. The `title` property will be tokenized based on the tokenization rules of the language of the item content.
```

2022-11-07 20:38 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +- Querying "title:Contoso Title" will return any item containing "Contoso" or "Title" in the `title` property
```suggestion
- Querying "title:Contoso Title" will return any item containing "Contoso" or "Title" in the `title` property.
```

2022-11-07 20:40 UTC, isvargasmsft requested changes
Hello @emzho, 

Very good job with this PR, very complete. 

Please take a look at a couple of suggestions we are adding to the conceptual topic. Feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2022-11-07 20:52 UTC, opbld34 commented
Learn Build status updates of commit _[0c98f36](https://github.com/emzho/microsoft-graph-docs/commits/0c98f361f367ec73c470aa5b0c3508a59a69c5ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211072049451655-19117/BuildReport?accessString=c975e95bc634715fddb35ec051dbe1b5ede2b6f87b2ee704700ebb5b0e562df7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 20:55 UTC, opbld31 commented
Learn Build status updates of commit _[0dc1225](https://github.com/emzho/microsoft-graph-docs/commits/0dc1225f7b59c3690accd2958b00db36f81de1ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211072052536133-19117/BuildReport?accessString=80b901a9703a05703bc3d3377b1aaa456d3e8a2685d32c831ff3cc6100eb02cc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 20:58 UTC, opbld33 commented
Learn Build status updates of commit _[e55b899](https://github.com/emzho/microsoft-graph-docs/commits/e55b89940ff331b68457473a44d314b8e6c1875f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211072054175366-19117/BuildReport?accessString=8e021b28e5edc0bd83801bf6fc6eee668099bccf5068c24bae2e13797f1a0abe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-07 21:23 UTC, isvargasmsft approved these changes

2022-11-08 17:57 UTC, dodaromike commented on concepts/connecting-external-content-manage-schema.md
> +If exact matching is specified for a property, then the full string value will be indexed. Only non-searchable properties can specify exact matching.
There is a typo in this revision: 
If exact matching is specified for a property, then the full string value will be indexed. Only non-searchable properties can >>by<< specified for exact matching.
Should be: If exact matching is specified for a property, then the full string value will be indexed. Only non-searchable properties can be specified for exact matching.

2022-11-08 18:53 UTC, isvargasmsft commented on concepts/connecting-external-content-manage-schema.md
> +If exact matching is specified for a property, then the full string value will be indexed. Only non-searchable properties can specify exact matching.
Great catch @dodaromike. Fixed. Thank you!

2022-11-19 01:33 UTC, opbld31 commented
Learn Build status updates of commit _[4083742](https://github.com/emzho/microsoft-graph-docs/commits/4083742ecd9470cf50c99d465e8a653ddd72219e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211190130360095-19117/BuildReport?accessString=04fd6c90e4d0cffb0a42bd99324a27ef9536afe85d38db1d1d199a52ca4cf920).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-19 01:36 UTC, opbld33 commented
Learn Build status updates of commit _[846dcdf](https://github.com/emzho/microsoft-graph-docs/commits/846dcdfcdb93e9af7bff622f26b2f81686c688ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211190131251100-19117/BuildReport?accessString=720464ee5c4004975c31e415e413b804b8683324315b3310b3f156cbfab04351).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-19 01:41 UTC, opbld34 commented
Learn Build status updates of commit _[3c26204](https://github.com/emzho/microsoft-graph-docs/commits/3c2620437a548f983f4a8895065929e91f25af3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-property.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/api-reference/beta/resources/externalconnectors-property.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-beta&branch=pr-en-us-19117) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addIsExactMatchRequired/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-19117) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211190139279733-19117/BuildReport?accessString=bbe397c28c3c6c561109a4214e99bbdcc2a823648005b9b7b43a650d372e1681).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-19 01:45 UTC, merged