Add ExternalSource to Planner Task, Plan and Bucket
microsoftgraph/microsoft-graph-docs pull request #19154
Opened 2022-11-08 00:56 UTC by danlucuiPlanner

2022-11-08 00:59 UTC, opbld34 commented
Learn Build status updates of commit _[2d8e1c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d8e1c9b826e62b192a26c3f742b62fe4b47e783)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211080056401299-19154/BuildReport?accessString=4355740c9ca692e8d00b2460a53ced49c2c546e3b2cd1200e5dc9ebe659e37d4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 00:29 UTC, opbld32 commented
Learn Build status updates of commit _[5033fb7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5033fb7e835e11d71c5e9cadf15ad26d13eda8e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211090026258468-19154/BuildReport?accessString=29909767ccc06612f6f7ac09dee8c79835a917d31b331fc102b091950b2767cd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 17:35 UTC, dodaromike commented on api-reference/beta/resources/plannertaskcreation.md
> +|creationSourceKind|plannerCreationSourceKind|Specifies what kind of creation source the task is created with. |
Please add the list of possible values following the guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211747/Enumerations?anchor=examples

2022-11-24 17:41 UTC, isvargasmsft commented on api-reference/beta/resources/plannertaskcreation.md
>  |Property|Type|Description|
Line 15: Please add a note indicating that this entity is base type of plannerTeamsPublicationInfo resource. And also, add a similar note to the plannerTeamsPublicationInfo topic, indicating that the resource now inherits from plannerTaskCreation, and add the inherited properties to the Properties table, indicating that those are inherited from plannerTaskCreation.

2022-11-24 17:49 UTC, dodaromike commented on api-reference/beta/resources/plannerexternaltasksource.md
> +
Please add note that indicates this type is derived from plannerTaskCreation.  Also add the inherited properties to the properties table.

2022-11-24 17:53 UTC, dodaromike commented on api-reference/beta/resources/plannerplancreation.md
> +The resources that derive from plannerPlanCreation contains information about the origin of the [plannerPlan](plannerplan.md). Apps do not need to know the origin of the plan to be able to work with
```suggestion
The resources that derive from plannerPlanCreation contain information about the origin of the [plannerPlan](plannerplan.md). Apps do not need to know the origin of the plan to be able to work with it; however, some apps can use the additional information to provide specific experiences around these plans.
```

2022-11-24 17:55 UTC, dodaromike commented on api-reference/beta/resources/plannerplancreation.md
> +|creationSourceKind|plannerCreationSourceKind|Specifies what kind of creation source the plan is created with.|
Please include a list of possible values of the enum in the description.

2022-11-24 17:57 UTC, dodaromike commented on api-reference/beta/resources/plannerbucketcreation.md
> +The resources that derive from plannerBucketCreation contains information about the origin of the [plannerBucket](plannerbucket.md). Apps do not need to know the origin of the bucket to be able to wo
```suggestion
The resources that derive from plannerBucketCreation contain information about the origin of the [plannerBucket](plannerbucket.md). Apps do not need to know the origin of the bucket to be able to work with it; however, some apps can use the additional information to provide specific experiences around these buckets.
```

2022-11-24 18:02 UTC, dodaromike requested changes
Looks good but please review comments and add a few things.

2022-12-01 21:06 UTC, opbld31 commented
Learn Build status updates of commit _[8f2e258](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f2e258c539b7d2944bab49656d7a39089b17dfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212012103241254-19154/BuildReport?accessString=6c4173bcc3c1413b5930b5593098cae6669e4294db08d930056084c71db94cb3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-01 22:28 UTC, opbld32 commented
Learn Build status updates of commit _[eeedacc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eeedacce74fb41dad58bc2bf3aa5255ac957de81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212012226213627-19154/BuildReport?accessString=85ac620a9291eb9f69cecfe76fa18158caab57202cee7a35ae666dc5a5fe22f1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-01 22:33 UTC, victorliu-microsoft commented on api-reference/beta/resources/plannerexternaltasksource.md
> +
should the note be in the Relationships section? or is it enough to put it in the description?

2022-12-05 23:24 UTC, opbld34 commented
Learn Build status updates of commit _[744492a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/744492a1890a114783ddc257c6e92862da628e7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212052321354645-19154/BuildReport?accessString=feaed190c55aa4fa87e3138a70d0155beed90bd6d0ab3f52915cb049cec91619).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 21:12 UTC, opbld31 commented
Learn Build status updates of commit _[24055f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24055f7101898533203a0be9ee51b5165700153f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212072110137614-19154/BuildReport?accessString=f48d6c9c5bd25d2d7d84840d65f1656753e5162a391a298c1b45ac83f274f9a4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 18:32 UTC, dodaromike commented on api-reference/beta/resources/plannerexternaltasksource.md
> +
Seems best to put it in the description where all users will be looking.

2022-12-08 18:35 UTC, dodaromike approved these changes
Thanks for changes.  Sorry about the delay.

2022-12-08 19:03 UTC, opbld32 commented
Learn Build status updates of commit _[b850f9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b850f9e41e33dcb663ce70a52597319b7ca27b5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212081900486775-19154/BuildReport?accessString=062ae64b73b172b55f06cff3ccb2a1e497c6229e3ee036087b37c8e37836cccb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 20:32 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerexternalbucketsource.md
> +|contextScenarioId|String| Nullable. An identifier for the scenario associated with this external source. This will generally take the form of "com.contoso.myapp".|
This should mention the reverse dns format is recommended. The sample and "generally take form of" isn't informative enough. We can this to be self applied by people as a guideline.

2022-12-08 20:33 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerexternalbucketsource.md
> +|externalObjectId|String| Nullable. The id of the entity that an external service associates with a bucket.|
We need to mention somewhere contextscenarioId + externalobject id is enforced to be unique.

2022-12-08 22:41 UTC, opbld32 commented
Learn Build status updates of commit _[c3be430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3be430b571776faac58dba0e7d3782366e6362a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212082238536267-19154/BuildReport?accessString=e2da3e72f14e163bc581c29572eb09f3d3dbb80672ff5ea9248f1facfefa7bb6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 22:45 UTC, opbld30 commented
Learn Build status updates of commit _[e3a9a08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3a9a08c7b7619b6e52c793f2bf8ebdfb749019a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212082242326267-19154/BuildReport?accessString=7ea5488547cabdce8417231331ff1109adffc7f49374bb53106ad4c9ba0dc9e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 22:53 UTC, victorliu-microsoft commented
@isvargasmsft @dodaromike how did the changelog links suddenly fail?

2022-12-08 23:04 UTC, dodaromike approved these changes
Looks fine.  I have not reviewed the changelog links.

2022-12-09 13:53 UTC, opbld31 commented
Learn Build status updates of commit _[f43186f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f43186ff46f2aa1ec51fe9696c8b93ee738a4653)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091351248577-19154/BuildReport?accessString=1b9782839a7c6c6a5927e33ea2136b1743845feec7f55e14ec401facfaaee2bd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 13:57 UTC, opbld34 commented
Learn Build status updates of commit _[0dee7c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0dee7c1b194813f417f19d7df7f3e56fd7ab7c86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091354507459-19154/BuildReport?accessString=a31978105a5b09946dab0aa4bd0c86508049f3913b9e084125c6bacafc7ecb1d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 16:51 UTC, opbld31 commented
Learn Build status updates of commit _[92347f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92347f3605dd48a0f5628b2be46dbe64929b7e00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091647428258-19154/BuildReport?accessString=72c69cf5e6bff1a276b6c4920b3947348e9f109234208ddb0d176f934560ee51).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 19:45 UTC, opbld31 commented
Learn Build status updates of commit _[ae314a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae314a826feffb09c7158dabcc2c87102ff6c6f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091942236768-19154/BuildReport?accessString=6916698fae576a3f3a23d0eedbdf630da7f3dbaf18ddd9ee69a178d7609f84bb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 19:45 UTC, TarkanSevilmis approved these changes
Looks technically acccurate.

2022-12-09 20:04 UTC, opbld34 commented
Learn Build status updates of commit _[cc652ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc652ecff7fba61e9418614810606a26f23acfe4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212092000390747-19154/BuildReport?accessString=498b4eed14f830d82e516d710bbfdbef9b26bc0e6f84e1f6627cc5038265fba3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 20:13 UTC, isvargasmsft approved these changes

2022-12-10 02:08 UTC, opbld32 commented
Learn Build status updates of commit _[2f3afd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f3afd21c0d53cd987c80f5279cfb7398dc4aa31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucket.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucket?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerbucketcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerbucketcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerbucketcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalbucketsource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalbucketsource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalbucketsource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternalplansource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternalplansource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternalplansource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerexternaltasksource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerexternaltasksource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerexternaltasksource?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerplancreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerplancreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-19154) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/danlucui/externalcreationsource/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212100206260756-19154/BuildReport?accessString=0c8efaa58ac354948a52c866af978d0a3e6572e6f05febae54fc886fadcc3f00).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-10 02:16 UTC, merged