Add doc support for interleaving search in Graph Search API
microsoftgraph/microsoft-graph-docs pull request #19155
Opened 2022-11-08 01:01 UTC by yiwenwang-ms

2022-11-08 01:04 UTC, opbld30 commented
Learn Build status updates of commit _[3a7444d](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/3a7444d16ee4b9664dc70726733bb3465503156c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) | [Details](#user-content-1b0322051436ef8575ab0a740346f82b-f68ddbef)
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

<a id="1b0322051436ef8575ab0a740346f82b-f68ddbef"></a>
### [concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md)
 - **Line 11, Column 1**: **[Warning: h1-not-first - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Supported Entity Combination'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211080101354619-19155/BuildReport?accessString=ee0baec992060d33863829174c18ff6b08bb7eb8cf00da35d85820dcfbe073a7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 06:11 UTC, opbld31 commented
Learn Build status updates of commit _[cba8a74](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/cba8a746077808c8f47961f4b562b8b51c0576da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211090607394402-19155/BuildReport?accessString=b53f76d85748e71cbd297d0b4146c54b82f7e7fdfd0b84a78b5b4d03028dd1a2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 19:56 UTC, njerigrevious requested changes

2022-11-09 19:56 UTC, njerigrevious commented on concepts/search-concept-interleaving.md
> +
These are great limitations - could you please clarify if QueryTemplate is supported or not?

2022-11-09 19:56 UTC, njerigrevious commented on concepts/search-concept-interleaving.md
> +- Specify a signle connection in content source is not supported, there is a plan to change the behavior to allow single connection interleaving search in the future. Please specify only "/external/c
Replace with "Specifying a single connection in content source is not supported, so please only use "/external/connections/*" in contentSource. Note that there is a plan to change the behavior to allow single connection interleaving search in the future."

2022-11-09 19:56 UTC, njerigrevious commented on concepts/search-concept-interleaving.md
> +The following is an example of the response, which contains one message that matches the search criterion.
not sure what is meant by this - should be rephrased to something like "This is an example of a response where each of the specified entitytypes are present in the results"
But is this what you mean here?

2022-11-10 10:45 UTC, yiwenwang-ms commented on concepts/search-concept-interleaving.md
> +- Specify a signle connection in content source is not supported, there is a plan to change the behavior to allow single connection interleaving search in the future. Please specify only "/external/c
Done

2022-11-10 10:45 UTC, yiwenwang-ms commented on concepts/search-concept-interleaving.md
> +
Clarified, could you please double check?

2022-11-10 10:46 UTC, yiwenwang-ms commented on concepts/search-concept-interleaving.md
> +The following is an example of the response, which contains one message that matches the search criterion.
Changed, could you please double check the statement.

2022-11-10 10:47 UTC, opbld31 commented
Learn Build status updates of commit _[d346fd9](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/d346fd9cbea2b568d38cfe4eae716e3aa7eb1930)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211101045039376-19155/BuildReport?accessString=5eab6cc7e4b5df0c76584cb14a1a4825b9466db90365b905edced1a4d9414359).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-11 02:31 UTC, njerigrevious approved these changes
Thanks for making the updates!

2022-11-17 07:42 UTC, opbld34 commented
Learn Build status updates of commit _[3b8d4b3](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/3b8d4b36c3fe06834f6012abf8279ea43b0bd541)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211170728598258-19155/BuildReport?accessString=7fb58942a2cc277675c3549c92600c7df49ea70955cc14898053b36d72477eba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 02:04 UTC, opbld34 commented
Learn Build status updates of commit _[e2a85c3](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/e2a85c306a8e7c9e63015ddb6a2b361555047bb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211210202035747-19155/BuildReport?accessString=e946d842600a20dc83118da446e9ad1ea12fbe68b2e12851a32c3be333e8383f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 13:38 UTC, isvargasmsft commented on api-reference/beta/resources/search-api-overview.md
> +  - [search interleaving results](/graph/search-concept-interleaving)
```suggestion
  - [Search interleaving results](/graph/search-concept-interleaving)
```

2022-11-23 13:41 UTC, opbld31 commented
Learn Build status updates of commit _[35c9ad0](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/35c9ad0803552445bf0bb9baf25055447a0e949a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211231339063090-19155/BuildReport?accessString=df03b6cc4fe96a3e7fa09e5610daca074af342b49a87d514af2bafcbbd50e031).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 13:42 UTC, isvargasmsft commented on concepts/search-concept-interleaving.md
> +| Entity Type |message     | chatMessage| drive       | driveItem  | event      |externalItem | list       | listItem   | person     | site       |
Please move this table to an H2, add the title "Use the Microsoft Search API to search with interleaved results" as an H1 and include a quick introduction to the article.

2022-11-23 13:43 UTC, isvargasmsft commented on concepts/search-concept-interleaving.md
> +| Entity Type |message     | chatMessage| drive       | driveItem  | event      |externalItem | list       | listItem   | person     | site       |
In addition, please add a quick introduction (context) to this table.

2022-11-23 13:46 UTC, opbld30 commented
Learn Build status updates of commit _[2b0f574](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/2b0f57431c32e66ffd645a0497b65553ec436ffa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211231343267284-19155/BuildReport?accessString=3027c577cb72aafa4817f2eb1bbb84d8c3109159c2275fcc5bfc58ddf8d2b58e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 13:49 UTC, opbld31 commented
Learn Build status updates of commit _[a38dda4](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/a38dda4e9dcd683132b5beba30eabdc8dfd99f9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211231345280614-19155/BuildReport?accessString=25211be1800f1111e196b732d1b74f4b3bf49c748595c82bc994ce6e2f335490).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 13:52 UTC, isvargasmsft requested changes
Hi @yiwenwang-ms, 

Thank you very much for your work in this PR. 

Please remove the changelog edits and address some structural suggestions I left. 

Feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac

2022-11-23 13:52 UTC, opbld33 commented
Learn Build status updates of commit _[c496e48](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/c496e48985633761d513859440d19ac30059eb49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211231348234111-19155/BuildReport?accessString=e99c9b7c735800ae462f58faddf5e70a72c621f3bc9aae6a74f144cb30ba8895).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 08:42 UTC, opbld31 commented
Learn Build status updates of commit _[ff5b5b4](https://github.com/yiwenwang-ms/microsoft-graph-docs/commits/ff5b5b41344c5cb7b78b652e8cf546ecf4a0c67c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-19155) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-interleaving.md](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/search-concept-interleaving.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |
[concepts/toc.yml](https://github.com/yiwenwang-ms/microsoft-graph-docs/blob/2022-11-07-GraphSearchInterleaving/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/search-concept-interleaving?branch=pr-en-us-19155) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211240840111088-19155/BuildReport?accessString=9c9513c942919b5c8e3471bbfd77dccee8976ccf87d0ef49bb3fe45dca5fe201).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 09:04 UTC, closed without merging