[WIP] Add regionName to onPremisesConnection
microsoftgraph/microsoft-graph-docs pull request #19158
Opened 2022-11-08 06:45 UTC by hyc3z

2022-11-08 06:48 UTC, opbld34 commented
Learn Build status updates of commit _[40f2cf1](https://github.com/hyc3z/microsoft-graph-docs/commits/40f2cf1f3297fe9676991aa48a1188a0c9b1df7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211080645371493-19158/BuildReport?accessString=f945bf9692e6ead6e9b2d557fa28d49faba69499e04976268f0489613fff7c8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 06:55 UTC, opbld30 commented
Learn Build status updates of commit _[e6c86b5](https://github.com/hyc3z/microsoft-graph-docs/commits/e6c86b5798a10a29d7a0395be52707d66905db18)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211080652367062-19158/BuildReport?accessString=82f8625399a9a6643b5a68af8f486afdac1b99f4e4b8ab24f9a8374aece157f8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 05:14 UTC, opbld33 commented
Learn Build status updates of commit _[46d80af](https://github.com/hyc3z/microsoft-graph-docs/commits/46d80af1d7d852064fbf8947401ab362b5d3b093)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150511367634-19158/BuildReport?accessString=c38d7151bb4b04e09eb33d45164a09605b6290163567547b20bd2be98e82f6f1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 05:56 UTC, opbld32 commented
Learn Build status updates of commit _[26a8bf7](https://github.com/hyc3z/microsoft-graph-docs/commits/26a8bf7b562353cdf5fae13e462f70f7f6b92553)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150553359333-19158/BuildReport?accessString=8924d515226b1db3e32587e7089a693ad162c137658ceef37d5a80ce82bbb572).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-16 03:04 UTC, RuiHou105 requested changes
@hyc3z 
1.Please also update the `changelog/Microsoft.CloudManagedDesktop.json` file.
2.In the description you only need to add the roadmap workitem number. In this work item, you can describe the review PR and graph schema PR link

2022-11-16 05:15 UTC, opbld33 commented
Learn Build status updates of commit _[682064e](https://github.com/hyc3z/microsoft-graph-docs/commits/682064e86680df131c5dbdb79298fb6db8a1cb1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211160512514413-19158/BuildReport?accessString=9a36b07981fa19ab4e7e0a01e8f7c22f5295a9366189c7f5af8a89fbd4b81e18).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-16 05:16 UTC, hyc3z commented
Updated @RuiHou105 please have a look, thanks

2022-12-02 07:27 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ChangeList": [
@hyc3z  
As your change only includes `virtualNetworkLocation` Property, so please only include this one in changelog: 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/77313233/205238566-4096dbb3-6d21-4192-b5ba-387c38cb07ed.png">

2022-12-09 05:28 UTC, opbld32 commented
Learn Build status updates of commit _[c0c9d2f](https://github.com/hyc3z/microsoft-graph-docs/commits/c0c9d2f4693f646d93bd4d7cb3bae4e5df82dc14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212090525552241-19158/BuildReport?accessString=d44037c98349009e9d1c00baa2e21bc9b9ddd7887c947e8751e5d3e789f0d094).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 05:36 UTC, hyc3z commented
Updated

2022-12-09 17:39 UTC, opbld33 commented
Learn Build status updates of commit _[15ed787](https://github.com/hyc3z/microsoft-graph-docs/commits/15ed787a72cf572989888c39063ce89af40b9033)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-19158) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/hyc3z/microsoft-graph-docs/blob/yichong/2022-11-08-addRegionToOnPremisesConnection/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091737369000-19158/BuildReport?accessString=9725a3cdfccc2f60cf9f5f1ddac4d76039681a1cea80d46a77f1fccaa85a6d4c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-15 02:24 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the `virtualNetworkLocation` property to the [cloudPcOnPremisesConnection](https://docs.microsoft.com/en-us/graph/api/resources/intune-cloudPcOnPremisesConnectio
The link for cloudPcOnPremisesConnection is wrong. Could you please help fix it?

2022-12-15 06:32 UTC, RuiHou105 approved these changes

2022-12-15 18:54 UTC, Danielabom commented
Contacted author to get info.

2022-12-21 18:32 UTC, Danielabom commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|virtualNetworkLocation|String|Indicates resource location of the target virtual network(Readonly, computed value).|
```suggestion
|virtualNetworkLocation|String|Indicates resource location of the virtual target network (Read-only, computed value).|
```

2022-12-21 18:35 UTC, Danielabom commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|virtualNetworkLocation|String|Indicates resource location of the virtual target network (Read-only, computed value).|
```suggestion
|virtualNetworkLocation|String|Indicates resource location of the virtual target network. Read-only, computed value.|
```

2022-12-21 18:58 UTC, Danielabom approved these changes
@hyc3z , thank you for working on this PR. Everything looks good. PR approved.

2023-01-18 04:12 UTC, merged