eDiscovery : Update purge beta gesture and add purge to v1 toc
microsoftgraph/microsoft-graph-docs pull request #19186
Opened 2022-11-09 17:55 UTC by SeunginLyu

CSDL : 
- [beta](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads?path=/Workloads/Microsoft.Compliance.Ediscovery/override/schema-Prod-beta.csdl&_a=history)
- [v1](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads?path=/Workloads/Microsoft.Compliance.Ediscovery/override/schema-Prod-v1.0.csdl)

PR:
- [beta](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/7054056)
- [v1](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/7115930?_a=files&path=/Workloads/Microsoft.Compliance.Ediscovery/override)

2022-11-09 17:58 UTC, opbld30 commented
Learn Build status updates of commit _[cbac46b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbac46bdc18726e0ce9daa1901c83351d7d0e13f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-8ed9713a)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-8ed9713a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml)
 - **Line 6721, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-ediscoverysearch-purgedata.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211091755297846-19186/BuildReport?accessString=624dcc4fd31a582f65532acd5bd51943e16f32817ad5770f0884fcf00bdb819b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 00:17 UTC, opbld30 commented
Learn Build status updates of commit _[8cbc932](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cbc932530a122bea27fd8a44e7a00333c6edfaa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-197e7312)
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-197e7312"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml)
 - **Line 6721, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-ediscoverysearch-purgedata.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211100014400025-19186/BuildReport?accessString=2968f7166156ee137917e7b7698b9f188a481bd0dcc0a81a81520640f3d611b7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 00:32 UTC, opbld30 commented
Learn Build status updates of commit _[aa56529](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa565293399e27b1b62be503ec338f99a9026c3e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1c9bcc44)
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-1c9bcc44"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml)
 - **Line 6721, Column 19**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-ediscoverysearch-purgedata.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211100029429941-19186/BuildReport?accessString=d847b517558166ff3cb052e23f9cb3c9cc07c270250656e9217dfebce488b9b3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 22:30 UTC, opbld34 commented
Learn Build status updates of commit _[6e99786](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e997863d931d9db67b44c8433b49982377294ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211102227328610-19186/BuildReport?accessString=01d13e2b632925666546703c394ceb1c07f05c380b72f87a71ceebaced2c20e8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 21:37 UTC, dodaromike commented on api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md
> +# ediscoveryPurgeDataOperation resource type
Please provide a CSDL PR that introduces this new resource into the v1 endpoint.

2022-11-14 21:41 UTC, dodaromike commented on api-reference/beta/resources/security-ediscoverypurgedataoperation.md
> +
Please add list item for unknownFutureValue in both enumerations.

2022-11-14 21:44 UTC, dodaromike commented on api-reference/beta/resources/security-ediscoverypurgedataoperation.md
> +
Please update these descriptions to reflect the actual members.

2022-11-14 21:45 UTC, dodaromike commented on api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md
> +
Please include changelog entries for all these additions in the PR.

2022-11-14 21:48 UTC, isvargasmsft commented on api-reference/beta/api/security-ediscoverysearch-purgedata.md
> +|PurgeAreas|String| Options to define the locations to be in scope of the purge action. Possible values are: `mailboxes`, `teamsMessages`. |
Are these new enumerations only used as parameters of this action? If so, please include unknownFutureValue in the list of possible values. If other resources use these enums, please indicate which ones.

2022-11-14 21:50 UTC, isvargasmsft requested changes
Hello @SeunginLyu, 

Thank you very much for your work in this PR. 

Please review a few comments Mike and I left, mostly around completeness. 

Please feel free to ping us on the side if you have questions. 

Kind regards, 

Mike and Isaac

2022-11-14 23:46 UTC, SeunginLyu commented on api-reference/v1.0/api/security-ediscoverysearch-purgedata.md
> +
provided in description

2022-11-14 23:47 UTC, SeunginLyu commented on api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md
> +# ediscoveryPurgeDataOperation resource type
added to PR description

2022-11-14 23:49 UTC, SeunginLyu commented on api-reference/beta/api/security-ediscoverysearch-purgedata.md
> +|PurgeAreas|String| Options to define the locations to be in scope of the purge action. Possible values are: `mailboxes`, `teamsMessages`. |
yes used only for this action

2022-11-14 23:58 UTC, opbld34 commented
Learn Build status updates of commit _[7fb1e2d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fb1e2d07239c8e8e705f79c3e3e7f68e0ebf14f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211142355371544-19186/BuildReport?accessString=a740823d7e88a610fb4951dfe72f09ace579607a2bbc60181700a9fbbf3ceb29).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 05:16 UTC, SeunginLyu commented on api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md
> +
Trying to get the auto generated changelog

2022-11-15 18:52 UTC, opbld30 commented
Learn Build status updates of commit _[81aae50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81aae50ba6ce4a424c5a6061fd79c988d96d9bbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[changelog/Microsoft.Security.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/changelog/Microsoft.Security.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211151850184953-19186/BuildReport?accessString=e19704e8f50d1a410a2353053e7fb95eb6411c48576d682126b87f52cb8c7aa9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 19:02 UTC, SeunginLyu commented
@isvargasmsft Could you take a lookt at the PR again? addressed your feedback.

2022-11-17 21:17 UTC, isvargasmsft commented on api-reference/beta/api/security-ediscoverysearch-purgedata.md
> +|PurgeAreas|microsoft.graph.security.purgeAreas| Option to define the locations to be in scope of the purge action. Possible values are: `mailboxes`, `teamsMessages`,`unknownFutureValue`. |
```suggestion
|purgeType|microsoft.graph.security.purgeType| Options that control whether to the action is soft delete or hard delete. Possible values are `recoverable`, `permanentlydeleted`,`unknownFutureValue`. |
|purgeAreas|microsoft.graph.security.purgeAreas| Option to define the locations to be in scope of the purge action. Possible values are: `mailboxes`, `teamsMessages`,`unknownFutureValue`. |
```

2022-11-17 21:29 UTC, opbld30 commented
Learn Build status updates of commit _[a8e925d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8e925dffd857108ca4c627393b0196284c1ca9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[changelog/Microsoft.Security.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/changelog/Microsoft.Security.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211172117179880-19186/BuildReport?accessString=bd00de95548dbd9ca4f3415fbd070586b58af3e6a1da9c15debbcdf30be22d4f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 21:43 UTC, opbld33 commented
Learn Build status updates of commit _[5847edb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5847edb12fce392e8d6ea9aeaf3fb35e2c470a79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[changelog/Microsoft.Security.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/changelog/Microsoft.Security.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211172128170185-19186/BuildReport?accessString=414cf8240c669913d2a810f9eae0bff09c76d748efafb6dcfed84b9fdaac4c10).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 05:42 UTC, opbld34 commented
Learn Build status updates of commit _[29ea93a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29ea93ac398fe71aec4c16125cd817f76ee2ff6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[changelog/Microsoft.Security.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/changelog/Microsoft.Security.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211290539120943-19186/BuildReport?accessString=0d361e361c36aacaef234a88ed77c61a631a2911b70949e996184ec0dda2f61a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 03:26 UTC, opbld32 commented
Learn Build status updates of commit _[ba41d3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba41d3f2c2583ca2cd6cd8833bf6f2ced39bb748)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[changelog/Microsoft.Security.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/changelog/Microsoft.Security.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211300324182507-19186/BuildReport?accessString=b6be5747eb2f871985352646d454dd3ed5c08681483f2d82d977c46bbaad5d2f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 03:35 UTC, opbld30 commented
Learn Build status updates of commit _[fa8735e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa8735e2fa47b52961fa49343352376fb5742d2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[changelog/Microsoft.Security.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/changelog/Microsoft.Security.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211300326344634-19186/BuildReport?accessString=5e6f40c2d6d085c213fb236b991d0d33e02c0c67e20a4ce1e0297faa01160e43).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 03:37 UTC, opbld32 commented
Learn Build status updates of commit _[73fd7c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73fd7c18f83da5d15db7ae6d7ea04e097eb1ec8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-beta&branch=pr-en-us-19186) (graph-rest-beta) |
[api-reference/v1.0/api/security-ediscoverysearch-purgedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/api/security-ediscoverysearch-purgedata.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/resources/security-ediscoverypurgedataoperation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ediscoverypurgedataoperation?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-ediscoverysearch-purgedata?view=graph-rest-1.0&branch=pr-en-us-19186) (>= graph-rest-1.0) |
[changelog/Microsoft.Security.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nickrob-purgetov1/changelog/Microsoft.Security.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211300328550302-19186/BuildReport?accessString=d851769a64b48eb2f99594c2c71f64a91a20de3474493b386d6464afceac8a03).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 03:41 UTC, merged