docs: update the provider documentation for MGT Providers
microsoftgraph/microsoft-graph-docs pull request #19229
Opened 2022-11-14 11:28 UTC by musale

Updates the providers documentation to indicate the usage of the new `baseURL` property in the various providers. This property allows a provider to change the base URL used in the graph client.

2022-11-14 11:30 UTC, opbld32 commented
Learn Build status updates of commit _[ba59b7f](https://github.com/musale/microsoft-graph-docs/commits/ba59b7f998f4b3030adb9c45f1ba14ccbb9ec29d)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/electron.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-19229) | [Details](#user-content-7d28a94f3628e9e23d823bfdca7571b5-24c19e37)
[concepts/toolkit/providers/msal.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/msal.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-19229) | [Details](#user-content-0cecf8888c9db7ceec4eb9fe610ec6f9-24c19e37)
[concepts/toolkit/providers/msal2.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/msal2.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-19229) | [Details](#user-content-8fe9657dc2f3ae8529124460a7490a14-24c19e37)
[concepts/toolkit/providers/teams.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-19229) | [Details](#user-content-71b4e9123d0247864a2fe65ea87105e1-24c19e37)
[concepts/toolkit/providers/teams-msal2.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teams-msal2.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-19229) | [Details](#user-content-472dbdbe2d4137451397090499347dcc-24c19e37)
[concepts/toolkit/providers/sharepoint.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-19229) |
[concepts/toolkit/providers/teamsfx.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teamsfx.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/teamsfx?branch=pr-en-us-19229) |

<a id="7d28a94f3628e9e23d823bfdca7571b5-24c19e37"></a>
### [concepts/toolkit/providers/electron.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/electron.md)
 - **Line 57, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 64, Column 92**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/enterprise/microsoft-365-endpoints?view=o365-worldwide`````

<a id="0cecf8888c9db7ceec4eb9fe610ec6f9-24c19e37"></a>
### [concepts/toolkit/providers/msal.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/msal.md)
 - **Line 48, Column 92**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/enterprise/microsoft-365-endpoints?view=o365-worldwide`````

<a id="8fe9657dc2f3ae8529124460a7490a14-24c19e37"></a>
### [concepts/toolkit/providers/msal2.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/msal2.md)
 - **Line 45, Column 92**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/enterprise/microsoft-365-endpoints?view=o365-worldwide`````

<a id="71b4e9123d0247864a2fe65ea87105e1-24c19e37"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teams.md)
 - **Line 86, Column 92**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/enterprise/microsoft-365-endpoints?view=o365-worldwide`````

<a id="472dbdbe2d4137451397090499347dcc-24c19e37"></a>
### [concepts/toolkit/providers/teams-msal2.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teams-msal2.md)
 - **Line 105, Column 92**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/enterprise/microsoft-365-endpoints?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211141128032457-19229/BuildReport?accessString=6137a0186fc372b99114b86cc35842570aaf65d8e8bd40b85d8391cf05d32f6d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validatio [...]

2022-11-14 11:40 UTC, opbld32 commented
Learn Build status updates of commit _[f7ddf2c](https://github.com/musale/microsoft-graph-docs/commits/f7ddf2c9a251178308051fd1840d70d56c76c160)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-19229) |
[concepts/toolkit/providers/msal.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-19229) |
[concepts/toolkit/providers/msal2.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-19229) |
[concepts/toolkit/providers/sharepoint.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-19229) |
[concepts/toolkit/providers/teams.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-19229) |
[concepts/toolkit/providers/teamsfx.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teamsfx.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/teamsfx?branch=pr-en-us-19229) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/musale/microsoft-graph-docs/blob/musale/update-provider-docs/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-19229) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211141138259681-19229/BuildReport?accessString=67b564a3bcfe5b4e206ed1abbb4d7d4140371c2b07a2dd5d4caefde85a041ded).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-04-06 16:40 UTC, musale commented
@Mnickii @gavinbarron @sebastienlevert quite an old one.

2023-04-06 19:26 UTC, sebastienlevert commented
I guess we should be re-opening, right?

2023-04-06 19:29 UTC, sebastienlevert requested changes

2023-04-06 19:29 UTC, sebastienlevert commented on concepts/toolkit/providers/electron.md
> +| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [Microsoft 365 endpoints](/microsoft-365/enterprise/microsoft-365-endpoints). The default value is `https://
```suggestion
| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [National cloud deployments](/graph/deployments). The default value is `https://graph.microsoft.com`.                                                          |
```

2023-04-06 19:29 UTC, sebastienlevert commented on concepts/toolkit/providers/msal.md
> +| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [Microsoft 365 endpoints](/microsoft-365/enterprise/microsoft-365-endpoints). The default value is `https://
```suggestion
| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [National cloud deployments](/graph/deployments). The default value is `https://graph.microsoft.com`.    
```

2023-04-06 19:29 UTC, sebastienlevert commented on concepts/toolkit/providers/msal2.md
> +| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [Microsoft 365 endpoints](/microsoft-365/enterprise/microsoft-365-endpoints). The default value is `https://
```suggestion
| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [National cloud deployments](/graph/deployments). The default value is `https://graph.microsoft.com`.    
```

2023-04-06 19:29 UTC, sebastienlevert commented on concepts/toolkit/providers/teams-msal2.md
> +| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [Microsoft 365 endpoints](/microsoft-365/enterprise/microsoft-365-endpoints). The default value is `https://
```suggestion
| base-url | The graph endpoint to be used for graph calls. It can be any of the supported [National cloud deployments](/graph/deployments). The default value is `https://graph.microsoft.com`.    
```

2023-04-24 18:45 UTC, sebastienlevert approved these changes

2023-04-25 02:19 UTC, Lauragra approved these changes

2023-04-25 02:43 UTC, merged