Get Supported CloudPc Remote Actions
microsoftgraph/microsoft-graph-docs pull request #19228
Opened 2022-11-14 05:12 UTC by jannyma

2022-11-14 05:15 UTC, opbld31 commented
Learn Build status updates of commit _[472f6c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/472f6c678b2bab47964afec64a477aeab0a83a21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-getsupportedcloudpcremoteactions?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-6c313a28f29e5b97ee80310df6b3c2b1-755a9b85)

<a id="6c313a28f29e5b97ee80310df6b3c2b1-755a9b85"></a>
### [api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140512303389-19228/BuildReport?accessString=dce87c61374fafdfef9ee7c5957798694e897d09b9c9e82a91cbda78fb3e7d2b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 05:25 UTC, opbld30 commented
Learn Build status updates of commit _[553cfee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/553cfee96b46369c9e4bb0d264a1fc68cb0ec1db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-getsupportedcloudpcremoteactions?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-6c313a28f29e5b97ee80310df6b3c2b1-7f6f0ff2)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="6c313a28f29e5b97ee80310df6b3c2b1-7f6f0ff2"></a>
### [api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140522314323-19228/BuildReport?accessString=8976de12816ded9c8fc479e248b461c914fc09f2fbad7a8df3fdc10745ae1d0e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 05:55 UTC, opbld31 commented
Learn Build status updates of commit _[451e659](https://github.com/microsoftgraph/microsoft-graph-docs/commits/451e6595417ee4138552eb2a24e9ca5fdf7d4fa1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-getsupportedcloudpcremoteactions?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-6c313a28f29e5b97ee80310df6b3c2b1-0af4e8d2)
[api-reference/beta/resources/cloudpcremoteactioncapability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpcremoteactioncapability.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcremoteactioncapability?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-b3f29ea19eb352050fbb962eca745c42-0af4e8d2)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="6c313a28f29e5b97ee80310df6b3c2b1-0af4e8d2"></a>
### [api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="b3f29ea19eb352050fbb962eca745c42-0af4e8d2"></a>
### [api-reference/beta/resources/cloudpcremoteactioncapability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpcremoteactioncapability.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Hank Chang' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140552375447-19228/BuildReport?accessString=3f589192f0bd76d19d3f913862e302a1f7748e0df5064208486936ea919b22d3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 06:07 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ApiChange": "Method",
The changelog didn't  include all changes. Please also add changelog for: new resource `cloudPcRemoteActionCapability`, new enum `actionCapability `and `cloudPcRemoteActionName`

2022-11-14 06:20 UTC, RuiHou105 requested changes
@hanky0301 
1.The format of this PR doesn't follow the standard one. e.g., the headers should start with ## or ###...So could you please follow this [example ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18829)to update yours?
2.As you add a new API, please also update the toc.yml file, like the example above does. 
3.Please create a roadmap workitem and attach the workitem number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If no access, please do these two steps firstly.
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-11-14 06:28 UTC, opbld30 commented
Learn Build status updates of commit _[62a561c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62a561c7c679e27493214d7564384998b9fae23e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-getsupportedcloudpcremoteactions?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-6c313a28f29e5b97ee80310df6b3c2b1-540de18b)
[api-reference/beta/resources/cloudpcremoteactioncapability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpcremoteactioncapability.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcremoteactioncapability?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-b3f29ea19eb352050fbb962eca745c42-540de18b)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="6c313a28f29e5b97ee80310df6b3c2b1-540de18b"></a>
### [api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="b3f29ea19eb352050fbb962eca745c42-540de18b"></a>
### [api-reference/beta/resources/cloudpcremoteactioncapability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpcremoteactioncapability.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Hank Chang' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140626082285-19228/BuildReport?accessString=f3c739116807ec9e17440e3b1d8692cd7b16213282b6fa6037992667b9986c95).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 06:49 UTC, opbld32 commented
Learn Build status updates of commit _[1de4e00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1de4e0010032b9cb6c4718b3a25375493e1a3f83)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-getsupportedcloudpcremoteactions?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-6c313a28f29e5b97ee80310df6b3c2b1-97b34d26)
[api-reference/beta/resources/cloudpcremoteactioncapability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpcremoteactioncapability.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcremoteactioncapability?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) | [Details](#user-content-b3f29ea19eb352050fbb962eca745c42-97b34d26)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="6c313a28f29e5b97ee80310df6b3c2b1-97b34d26"></a>
### [api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Hank Chang' is not a valid GitHub ID.`````

<a id="b3f29ea19eb352050fbb962eca745c42-97b34d26"></a>
### [api-reference/beta/resources/cloudpcremoteactioncapability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpcremoteactioncapability.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Hank Chang' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140646549543-19228/BuildReport?accessString=919909fefbfab59e050c48866cb76bf0f78cc5e53dc6acaa64ccfeb003beadbb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 06:58 UTC, hanky0301 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ApiChange": "Method",
Done

2022-11-14 07:17 UTC, jannyma commented
Roadmap work item no: 15657
https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15657

2022-11-14 07:23 UTC, opbld34 commented
Learn Build status updates of commit _[05e8149](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05e8149b800855aca53e22cc97c3ae71b2b3e813)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-getsupportedcloudpcremoteactions?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcremoteactioncapability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/resources/cloudpcremoteactioncapability.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcremoteactioncapability?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-getsupportedcloudpcremoteactions?view=graph-rest-beta&branch=pr-en-us-19228) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hank/GetSupportedCloudPcRemoteActions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211140721277634-19228/BuildReport?accessString=1fb30a3774e465c382422da8485c7b8a1b4546039741c31c569a5c1d885a7871).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-15 02:58 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +          - name: Get supported remote actions
@hanky0301  Please place this API after `Get review status`, as all APIs should be sorted alphabetically.

2022-12-15 03:01 UTC, RuiHou105 commented
According to the [build failure](https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=102483&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e), there are two errors. So could you please help fix them? Thanks.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/77313233/207762461-55439abb-336d-414a-9cf5-dad0ea239f36.png">

2022-12-15 09:21 UTC, hanky0301 commented on api-reference/beta/toc.yml
> +          - name: Get supported remote actions
Will fix it right away

2023-01-18 01:22 UTC, Jarbas-MSFT commented
@Lauragra, this PR is ready for a final review.

2023-01-18 02:18 UTC, Lauragra approved these changes

2023-01-18 04:06 UTC, merged