Documentation for new setStatusMessage action and presenceStatusMessage type
microsoftgraph/microsoft-graph-docs pull request #19239
Opened 2022-11-14 23:55 UTC by afedorov-msft

2022-11-14 23:58 UTC, opbld34 commented
Learn Build status updates of commit _[40f5c0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40f5c0ddf9990dcfd627f40e0d7a4639b0f12680)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :x:Error | | [Details](#user-content-1227d79d3667be02cb646039283b5401-4841dcb2)

<a id="1227d79d3667be02cb646039283b5401-4841dcb2"></a>
### [api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md)
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-java-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-go-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-powershell-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-php-snippets.md'.`````
 - **Line 146, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 150, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 154, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-xml-sanitization-java-snippets.md'.`````
 - **Line 158, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-xml-sanitization-go-snippets.md'.`````
 - **Line 162, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 166, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-xml-sanitization-php-snippets.md'.`````
 - **Line 267, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 271, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 275, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-xml-sanitization-java-snippets.md'.`````
 - **Line 279, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-xml-sanitization-go-snippets.md'.`````
 - **Line 283, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 287, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-xml-sanitization-php-snippets.md'.`````
 - **Line 47, Column 21**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'presenceStatusMessage.md'.`````
 - **Line 337, Column 51**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Get-your-own-presence-information' in 'beta/api/presence-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211142355593679-19239/BuildReport?accessString=ee410de22a0ff8d4b92214d6db4548bb68942a9fb201422e732db46e70d2f366).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 00:23 UTC, opbld34 commented
Learn Build status updates of commit _[b4eb3ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4eb3ad3670ac7f20fac28448c0f7027240d9783)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :x:Error | | [Details](#user-content-1227d79d3667be02cb646039283b5401-23bd7f17)

<a id="1227d79d3667be02cb646039283b5401-23bd7f17"></a>
### [api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md)
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-java-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-go-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-powershell-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-php-snippets.md'.`````
 - **Line 146, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 150, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 154, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-xml-sanitization-java-snippets.md'.`````
 - **Line 158, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-xml-sanitization-go-snippets.md'.`````
 - **Line 162, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 166, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-xml-sanitization-php-snippets.md'.`````
 - **Line 267, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 271, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 275, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-xml-sanitization-java-snippets.md'.`````
 - **Line 279, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-xml-sanitization-go-snippets.md'.`````
 - **Line 283, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 287, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-xml-sanitization-php-snippets.md'.`````
 - **Line 337, Column 51**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Example-1-Get-your-own-presence-information' in 'beta/api/presence-get.md', did you mean '#example-1-get-your-own-presence-information'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150012206614-19239/BuildReport?accessString=67798ec5e9b84ab713c040b7e3580a7b43928951ac785b8e926939273f879e57).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 00:27 UTC, opbld32 commented
Learn Build status updates of commit _[691443b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/691443bf03c22c0763d46ad156dad4b230b0e3b2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :x:Error | | [Details](#user-content-1227d79d3667be02cb646039283b5401-791a1dab)

<a id="1227d79d3667be02cb646039283b5401-791a1dab"></a>
### [api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md)
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-java-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-go-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-powershell-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-php-snippets.md'.`````
 - **Line 146, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 150, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 154, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-xml-sanitization-java-snippets.md'.`````
 - **Line 158, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-xml-sanitization-go-snippets.md'.`````
 - **Line 162, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 166, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-xml-sanitization-php-snippets.md'.`````
 - **Line 267, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setStatusMessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 271, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setStatusMessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 275, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setStatusMessage-xml-sanitization-java-snippets.md'.`````
 - **Line 279, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setStatusMessage-xml-sanitization-go-snippets.md'.`````
 - **Line 283, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setStatusMessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 287, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setStatusMessage-xml-sanitization-php-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150024500799-19239/BuildReport?accessString=37a1e75e739c85cfa39ecfbda0d3dc59a90bda8703bfea9e63d458d8c3087ce8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 00:36 UTC, opbld31 commented
Learn Build status updates of commit _[fffa618](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fffa6188e88c447565680f6ed8eab85e956e1d5d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :x:Error | | [Details](#user-content-1227d79d3667be02cb646039283b5401-c123803d)

<a id="1227d79d3667be02cb646039283b5401-c123803d"></a>
### [api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md)
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setstatusmessage-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setstatusmessage-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setstatusmessage-java-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setstatusmessage-go-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setstatusmessage-powershell-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setstatusmessage-php-snippets.md'.`````
 - **Line 146, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setstatusmessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 150, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setstatusmessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 154, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setstatusmessage-xml-sanitization-java-snippets.md'.`````
 - **Line 158, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setstatusmessage-xml-sanitization-go-snippets.md'.`````
 - **Line 162, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setstatusmessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 166, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setstatusmessage-xml-sanitization-php-snippets.md'.`````
 - **Line 267, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setstatusmessage-another-user-csharp-snippets.md'.`````
 - **Line 271, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setstatusmessage-another-user-javascript-snippets.md'.`````
 - **Line 275, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setstatusmessage-another-user-java-snippets.md'.`````
 - **Line 279, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setstatusmessage-another-user-go-snippets.md'.`````
 - **Line 283, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setstatusmessage-another-user-powershell-snippets.md'.`````
 - **Line 287, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setstatusmessage-another-user-php-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150033480624-19239/BuildReport?accessString=153f7f2567354ac7c83c714813c345818a82cbe8e7406e61e856ecef8ebbf3ad).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 00:40 UTC, opbld33 commented
Learn Build status updates of commit _[52bc5f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52bc5f93ffc940776e7d08a0afd12bb9260f4d99)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :x:Error | | [Details](#user-content-1227d79d3667be02cb646039283b5401-1b8f6719)

<a id="1227d79d3667be02cb646039283b5401-1b8f6719"></a>
### [api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md)
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setstatusmessage-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setstatusmessage-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setstatusmessage-java-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setstatusmessage-go-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setstatusmessage-powershell-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setstatusmessage-php-snippets.md'.`````
 - **Line 146, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setstatusmessage-xml-sanitization-csharp-snippets.md'.`````
 - **Line 150, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setstatusmessage-xml-sanitization-javascript-snippets.md'.`````
 - **Line 154, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setstatusmessage-xml-sanitization-java-snippets.md'.`````
 - **Line 158, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setstatusmessage-xml-sanitization-go-snippets.md'.`````
 - **Line 162, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setstatusmessage-xml-sanitization-powershell-snippets.md'.`````
 - **Line 166, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setstatusmessage-xml-sanitization-php-snippets.md'.`````
 - **Line 267, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/setstatusmessage-another-user-csharp-snippets.md'.`````
 - **Line 271, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/setstatusmessage-another-user-javascript-snippets.md'.`````
 - **Line 275, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/setstatusmessage-another-user-java-snippets.md'.`````
 - **Line 279, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/setstatusmessage-another-user-go-snippets.md'.`````
 - **Line 283, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/setstatusmessage-another-user-powershell-snippets.md'.`````
 - **Line 287, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/setstatusmessage-another-user-php-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211150038359394-19239/BuildReport?accessString=c7a56cfe3dcc98c6d7b8781dc8a2431a0658e0042234a95be7d58fe5261ccbca).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 19:11 UTC, satyakonmsft commented on api-reference/beta/api/presence-setstatusmessage.md
> +The following request sets the user status message as "Hey I'm currently in a meeting." for user `fa8bf3dc-eca7-46b7-bad1-db199b62afc3`, with the expiration on 2022-10-18 at 17:05:33.2079781 Pacific
pl double check that the id is not a real user and a random guid

2022-11-15 19:12 UTC, satyakonmsft commented on api-reference/beta/api/presence-setstatusmessage.md
> +The following request sets the user status message as "Hey I'm currently in a meeting." for user `fa8bf3dc-eca7-46b7-bad1-db199b62afc3`, with the expiration on 2022-10-18 at 17:05:33.2079781 Pacific
in other places in this PR too

2022-11-15 19:18 UTC, satyakonmsft commented on api-reference/beta/api/presence-setstatusmessage.md
> +      "content": "<html>Hello world a<b</html>",
IMO we should give high level examples and do not need to give corner cases as examples.

Can we check with the UPS team if we they even want us to document the sanitization aspects. I am wondering if we are going to encourage bad actors if we detail too much on our sanitization strategy

2022-11-15 19:21 UTC, satyakonmsft commented on api-reference/beta/api/presence-setstatusmessage.md
> +| `statusMessage` | [microsoft.graph.presenceStatusMessage](../resources/presenceStatusMessage.md) | Status message that can be set to display a text message in presence. |
wondering if the term "text message" might confusing. Can we just call it the Teams' Presence Status Message

2022-11-15 19:21 UTC, satyakonmsft commented on api-reference/beta/api/presence-setstatusmessage.md
> +| `statusMessage` | [microsoft.graph.presenceStatusMessage](../resources/presenceStatusMessage.md) | Status message that can be set to display a text message in presence. |
and keep the naming consistent in all the PR docs

2022-11-15 19:26 UTC, satyakonmsft commented on api-reference/beta/resources/presenceStatusMessage.md
> +| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Moment in time of when status message expires.<br/>If not provided the status message will not expire.<br/><br/>Please min
>Please **note** that `expiryDateTime.dateTime` should not include time zone

2022-11-15 19:29 UTC, satyakonmsft commented on api-reference/beta/resources/presenceStatusMessage.md
> +| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Moment in time of when status message expires.<br/>If not provided the status message will not expire.<br/><br/>Please min
`expiryDateTime.timeZone` may occur to be different from previously set value when using [Get presence](../api/presence-get.md) or [Get presence of multiple users](../api/cloudcommunications-getpresencesbyuserid.md) requests

This is confusing IMO. Any other ideas on making this more clear? Perhaps take Laura's help?

2022-11-15 19:30 UTC, satyakonmsft commented on api-reference/beta/resources/presenceStatusMessage.md
> +| publishedDateTime | Edm.DateTimeOffset | Moment in time of when status message was published. Read-only.<br/><br/>`publishedDateTime` is not available when requesting presence of another user. |
Can "Read-only" be in a new line for clarity

2022-11-15 19:31 UTC, satyakonmsft commented on api-reference/beta/resources/presence.md
> +| statusMessage | [microsoft.graph.presenceStatusMessage](presenceStatusMessage.md) | The status message of a user. |
The Teams Presence Status message of a user?

2022-11-15 19:31 UTC, satyakonmsft commented on api-reference/beta/resources/presence.md
> +| [Set user status message](../api/presence-setstatusmessage.md) | | Set status message text for a user. |
Set the Teams Presence Status Message for a user

2022-11-15 19:36 UTC, opbld31 commented
Learn Build status updates of commit _[4694275](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4694275f5436b693ae595654b4c016cdc355afc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211151933373643-19239/BuildReport?accessString=122135c1056312e29d54821a01cad4e49756bbbee9b1d4f8e600e97c1e965197).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 20:22 UTC, opbld30 commented
Learn Build status updates of commit _[d623ed5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d623ed59c8468a1ec486fabeec44c6a13e008e14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211152019230238-19239/BuildReport?accessString=de04d704d7d9b5fdf48322ef356ed07f4bdc896f6a84471e2ae8494b591bd862).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 20:33 UTC, afedorov-msft commented on api-reference/beta/resources/presenceStatusMessage.md
> +| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Moment in time of when status message expires.<br/>If not provided the status message will not expire.<br/><br/>Please min
@Lauragra could you please help to clarify this paragraph:
> `expiryDateTime.timeZone` may occur to be different from previously set value when using [Get presence](../api/presence-get.md) or [Get presence of multiple users](../api/cloudcommunications-getpresencesbyuserid.md) requests.

In presence-setstatusmessage.md we have:
> Status message text can be xml-sanitized which leads to having a different status message applied.

The thing is that the sanitization is performed by another service which we do not control.
They have a work item to clarify the sanitization mechanism in a different doc.

Meanwhile it would be surprising for our customers to discover this behaviour.
That's why I am trying to carefully mention sanitization.
Could you please help to make a proper text here?

2022-11-15 21:12 UTC, afedorov-msft commented on api-reference/beta/api/presence-setstatusmessage.md
> +      "content": "<html>Hello world a<b</html>",
The motivation for this example was to visualize what xml sanitization could be to bring more clarity to API behavior.
That could be useful for those customers who want to encode some data in the presence note.

I posted a question to UPS team as well.

Could you please clarify "bad actors"?

2022-11-15 21:14 UTC, afedorov-msft commented on api-reference/beta/api/presence-setstatusmessage.md
> +The following request sets the user status message as "Hey I'm currently in a meeting." for user `fa8bf3dc-eca7-46b7-bad1-db199b62afc3`, with the expiration on 2022-10-18 at 17:05:33.2079781 Pacific
This id is already used in setPreferredPresence, I took it from there.
How could I check that id is real user id or not?

2022-11-15 21:23 UTC, opbld30 commented
Learn Build status updates of commit _[d551837](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d551837ac38b04a3864273f8fcbfb3a237a95c2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211152120046233-19239/BuildReport?accessString=0a6152e057f470cd2dd0fcf173ae7e340857a5ba1b6ae52cfe568af9c1bdd3e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 21:25 UTC, opbld30 commented
Learn Build status updates of commit _[caa415d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/caa415d79544b759e8de2f860dba0e49e4ed6568)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211152121586182-19239/BuildReport?accessString=12773e6fc162cf6e8942c75ebf15069064b9e3fa61e3be66bb8e42a6ff163a98).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 21:28 UTC, satyakonmsft commented on api-reference/beta/api/presence-setstatusmessage.md
> +The following request sets the user status message as "Hey I'm currently in a meeting." for user `fa8bf3dc-eca7-46b7-bad1-db199b62afc3`, with the expiration on 2022-10-18 at 17:05:33.2079781 Pacific
if it is the same id, then it should have already been checked. There is no way for us to check it now

2022-11-15 22:48 UTC, opbld34 commented
Learn Build status updates of commit _[cd8fc0f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd8fc0f0d392557160496acf9e687ac57a0a3212)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211152245045124-19239/BuildReport?accessString=434ab0f47af4039db2c442a70eaa291066dc7ae8bc11695644ba437b7908c291).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 22:57 UTC, satyakonmsft approved these changes

2022-11-15 23:05 UTC, afedorov-msft commented on api-reference/beta/resources/presenceStatusMessage.md
> +| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Moment in time of when status message expires.<br/>If not provided the status message will not expire.<br/><br/>Please min
Please disregard the request above since we will remove any sanitization related text/examples and reconsider adding them when UPS team updates their docs.

2022-11-16 23:12 UTC, opbld33 commented
Learn Build status updates of commit _[27eac26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27eac2689db4ca502d6b6337ea36d339225ac593)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure_docs/includes/lifecycle-workflows-tasks-table.md](https://github.com/MicrosoftDocs/azure-docs//blob/main/includes/lifecycle-workflows-tasks-table.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-lifecycleworkflows-overview?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) | [Details](#user-content-b785375b5caed854220727a089baf481-022c987a)
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="b785375b5caed854220727a089baf481-022c987a"></a>
### [azure_docs/includes/lifecycle-workflows-tasks-table.md](https://github.com/MicrosoftDocs/azure-docs//blob/main/includes/lifecycle-workflows-tasks-table.md)
 - **Line 15, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#send-welcome-email-to-new-hire' will not be built because it is not included in build scope.`````
 - **Line 16, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#send-onboarding-reminder-email' will not be built because it is not included in build scope.`````
 - **Line 17, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#generate-temporary-access-pass-and-send-via-email-to-users-manager' will not be built because it is not included in build scope.`````
 - **Line 18, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#add-user-to-groups' will not be built because it is not included in build scope.`````
 - **Line 19, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#add-user-to-teams' will not be built because it is not included in build scope.`````
 - **Line 20, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#enable-user-account' will not be built because it is not included in build scope.`````
 - **Line 21, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#run-a-custom-task-extension' will not be built because it is not included in build scope.`````
 - **Line 22, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#disable-user-account' will not be built because it is not included in build scope.`````
 - **Line 23, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#remove-user-from-selected-groups' will not be built because it is not included in build scope.`````
 - **Line 24, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#remove-users-from-all-groups' will not be built because it is not included in build scope.`````
 - **Line 25, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#remove-user-from-teams' will not be built because it is not included in build scope.`````
 - **Line 26, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#remove-users-from-all-teams' will not be built because it is not included in build scope.`````
 - **Line 27, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#remove-all-license-assignments-from-user' will not be built because it is not included in build scope.`````
 - **Line 28, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#delete-user' will not be built because it is not included in build scope.`````
 - **Line 29, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#send-email-to-manager-before-user-last-day' will not be built because it is not included in build scope.`````
 - **Line 30, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workflow-tasks.md [../azure_docs]' referenced by link '../articles/active-directory/governance/lifecycle-workflow-tasks.md#send-email-on-users-last-day' will not be built because it is not included in build scope.`````
 - **Line 31, Column 2**: **[Warning: link-out-of-scope]** `````File '../azure_docs/articles/active-directory/governance/lifecycle-workf [...]

2022-11-17 00:28 UTC, afedorov-msft commented
Hi @Lauragra !
Could you please help to clarify these errors by api doctor?
I did not do any relateed changes.

![image](https://user-images.githubusercontent.com/114033730/202324362-49137e50-ce2d-4cf6-a6ce-086511ffccc4.png)

2022-11-17 03:38 UTC, Lauragra commented
> 

Hi, this is likely an issue with the example in the topic. We can take a closer look when we start on the content review. Now that you've set the label, this PR will be in the queue for a content reviewer.

2022-11-23 21:12 UTC, Danielabom commented on api-reference/beta/api/presence-setstatusmessage.md
> +description: "Set the Teams Presence Status Message for a user"
```suggestion
description: "Set presence status message for a user.".
```

2022-11-23 21:14 UTC, Danielabom commented on api-reference/beta/api/presence-setstatusmessage.md
> +Set the Teams Presence Status Message for a user. Optional expiration date and time can be supplied as well.
```suggestion
"Set presence status message for a user. An optional expiration date and time can be supplied.
```

2022-11-23 21:22 UTC, Danielabom commented on api-reference/beta/resources/presenceStatusMessage.md
> +description: "Represents Teams Presence Status Message for a user's presence"
```suggestion
description: Represents a presence status message for a user's presence on Teams".
```

2022-11-23 21:25 UTC, Danielabom commented on api-reference/beta/resources/presenceStatusMessage.md
> +Represents the Teams Presence Status Message related to the [presence](presence.md) of a user.
```suggestion
Represents a presence status message related to the [presence](presence.md) of a user on Teams.
```

2022-11-23 21:32 UTC, Danielabom commented on api-reference/beta/resources/presenceStatusMessage.md
> +| message | [microsoft.graph.itemBody](itemBody.md) | Status message item.<br/><br/> The only supported format at the moment is `message.contentType = 'text'`. |
```suggestion
| message | [microsoft.graph.itemBody](itemBody.md) | Status message item.<br/><br/> The only supported format currently is `message.contentType = 'text'`. |
```

2022-11-23 21:34 UTC, Danielabom commented on api-reference/beta/resources/presenceStatusMessage.md
> +| publishedDateTime | Edm.DateTimeOffset | Moment in time of when status message was published.<br/>Read-only.<br/><br/>`publishedDateTime` is not available when requesting presence of another user.
```suggestion
| publishedDateTime | Edm.DateTimeOffset |Time in which the status message was published.<br/>Read-only.<br/><br/>`publishedDateTime` is not available when requesting presence of another user. |
```

2022-11-24 18:24 UTC, opbld33 commented
Learn Build status updates of commit _[b0147b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0147b9955709193cd92d2a3f6c2bdaa593193ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) | [Details](#user-content-1227d79d3667be02cb646039283b5401-ab45ea04)
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="1227d79d3667be02cb646039283b5401-ab45ea04"></a>
### [api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 56**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211241822112675-19239/BuildReport?accessString=c753bcab7395de35c7239e62aa0763c35b498b53d36f90aac016609b725a5fad).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 18:27 UTC, opbld32 commented
Learn Build status updates of commit _[a53b683](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a53b683cb591ec40c6751df53fd96e5b47b73d4c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) | [Details](#user-content-1227d79d3667be02cb646039283b5401-eaa8a839)
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) | [Details](#user-content-2122a0ae77b17fb32b2636d0ad45893c-eaa8a839)
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="1227d79d3667be02cb646039283b5401-eaa8a839"></a>
### [api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 56**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="2122a0ae77b17fb32b2636d0ad45893c-eaa8a839"></a>
### [api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 95**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211241822185758-19239/BuildReport?accessString=daacfa2d83e515f413aff77d01ae5b14025aa0075d7da544477412606d45206c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 18:34 UTC, opbld30 commented
Learn Build status updates of commit _[8cfb685](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cfb6858d90c7735f49806cd9296422fc8d6ea21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) | [Details](#user-content-2122a0ae77b17fb32b2636d0ad45893c-9bcb01ef)
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="2122a0ae77b17fb32b2636d0ad45893c-9bcb01ef"></a>
### [api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 95**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211241831468621-19239/BuildReport?accessString=d56007627b71372aa9cddb2e7fdb05fe4020b0d87bf2f13e5a2730949d80fc0e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 18:40 UTC, opbld32 commented
Learn Build status updates of commit _[89a47e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89a47e7a10c89c7d584bc1c4bf85c039cc64ecbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211241838107870-19239/BuildReport?accessString=dd93055bc89d09ae9817a1e720d2040b10d856d5fb2a1b5be35358c494478f3a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 18:53 UTC, afedorov-msft commented
Hi @Danielabom !
Could you please help to clarify the source of the error in the apidoctor logs?

2022-11-24 22:49 UTC, opbld30 commented
Learn Build status updates of commit _[a4473b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4473b17639ff522e2875be7ca0758b2a1b2d3fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211242246282950-19239/BuildReport?accessString=5933643ef803e712079bebf6000e9b11ccd0b14773df89068c8473015cfeb1e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-25 15:26 UTC, Danielabom commented on api-reference/beta/resources/presenceStatusMessage.md
> +| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Moment in time of when status message expires.<br/>If not provided the status message will not expire.<br/><br/>`expiryDat
```suggestion
| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Time in which the status message expires.<br/>If not provided, the status message does not expire.<br/><br/>`expiryDateTime.dateTime` should not include time zone.<br/><br/>`expiryDateTime` is not available when requesting presence of another user. |
```

2022-11-25 15:29 UTC, Danielabom commented on api-reference/beta/resources/presence.md
> +| [Set user status message](../api/presence-setstatusmessage.md) | | Set the Teams Presence Status Message for a user. |
```suggestion
| [Set user status message](../api/presence-setstatusmessage.md) | | Set the Teams presence status message for a user. |
```

2022-11-28 14:47 UTC, Danielabom commented on api-reference/beta/resources/presence.md
> +| statusMessage | [microsoft.graph.presenceStatusMessage](presenceStatusMessage.md) | The the Teams Presence Status Message of a user. |
```suggestion
| statusMessage | [microsoft.graph.presenceStatusMessage](presenceStatusMessage.md) | The Teams presence status message of a user. |
```

2022-11-28 14:52 UTC, Danielabom commented on api-reference/beta/resources/presenceStatusMessage.md
> +| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Moment in time of when status message expires.<br/>If not provided the status message will not expire.<br/><br/>`expiryDat
```suggestion
| expiryDateTime | [microsoft.graph.dateTimeTimeZone](dateTimeTimeZone.md) | Time in which status message expires.<br/>If not provided, the status message does not expire.<br/><br/>`expiryDateTime.dateTime` should not include time zone.<br/><br/>`expiryDateTime` is not available when requesting presence of another user. |
```

2022-11-28 14:52 UTC, Danielabom commented on api-reference/beta/api/presence-setstatusmessage.md
> +"Set presence status message for a user. An optional expiration date and time can be supplied.
```suggestion
Sets presence status message for a user. An optional expiration date and time can be supplied.
```

2022-11-28 14:54 UTC, Danielabom commented on api-reference/beta/api/presence-setstatusmessage.md
> +| `statusMessage` | [microsoft.graph.presenceStatusMessage](../resources/presenceStatusMessage.md) | Status message that can be set to display a Teams Presence Status Message of a user. |
```suggestion
| `statusMessage` | [microsoft.graph.presenceStatusMessage](../resources/presenceStatusMessage.md) |It can be set to display the Teams presence status message of a user. |
```

2022-11-28 14:59 UTC, Danielabom requested changes
@afedorov-msft, please take a look at my comments. Thanks!

2022-11-28 15:02 UTC, opbld31 commented
Learn Build status updates of commit _[66544ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66544caef3c2086db21b1a5575ccf8dbfb8649a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/concepts/auth-cloudsolutionprovider.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/auth-cloudsolutionprovider?branch=pr-en-us-19239) | [Details](#user-content-9eb948b1d10d872c914b766f88d74b6f-76242e6a)
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) | [Details](#user-content-2122a0ae77b17fb32b2636d0ad45893c-76242e6a)
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="9eb948b1d10d872c914b766f88d74b6f-76242e6a"></a>
### [concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/concepts/auth-cloudsolutionprovider.md)
 - **Line 34, Column 543**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#region' in 'auth-cloudsolutionprovider.md'.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://partner.microsoft.com/cloud-solution-provider' references a disallowed domain 'https://partner.microsoft.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://portal.azure.com' references a disallowed domain 'https://portal.azure.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://www.powershellgallery.com/packages/AzureAD' references a disallowed domain 'https://www.powershellgallery.com'. This poses a security risk.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-domain]** `````Url 'https://partnercenter.microsoft.com/partner/developer' references a disallowed domain 'https://partnercenter.microsoft.com'. This poses a security risk.`````
 - **Line 34, Column 535**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'a' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 126, Column 2**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'a' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="2122a0ae77b17fb32b2636d0ad45893c-76242e6a"></a>
### [api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md)
 - **Line 22, Column 76**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 22, Column 81**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 23, Column 91**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 23, Column 106**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 23, Column 111**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 24, Column 125**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 24, Column 181**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 24, Column 186**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 24, Column 246**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 24, Column 251**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'br' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211281459528864-19239/BuildReport?accessString=c638706dbd57b2ecbed97cee74f0158298e8fb987fc8a95009d24e0ee86ca945).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above b [...]

2022-11-28 19:08 UTC, opbld31 commented
Learn Build status updates of commit _[e420d9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e420d9fd97e94d0f3b120376d25722f90f257d4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211281905465902-19239/BuildReport?accessString=810b61bf41fefe2ddb73fc7f7a2d10264ed77942fd672aad9149cf1412d148aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 21:37 UTC, Danielabom approved these changes
Thank you for working on this PR. The changes look good. Thanks.

2022-12-07 18:51 UTC, opbld32 commented
Learn Build status updates of commit _[33075a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33075a25b5e49b333c1f6e7c814fae62adb29bb8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-setstatusmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/api/presence-setstatusmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[api-reference/beta/resources/presenceStatusMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/api-reference/beta/resources/presenceStatusMessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/presencestatusmessage?view=graph-rest-beta&branch=pr-en-us-19239) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/afedorov-presence-setstatusmessage/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212071847551880-19239/BuildReport?accessString=e17e7864c969eecc84045c4745be7927b408f0e3401d1eb0a13302c1c2965335).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-13 19:53 UTC, afedorov-msft commented
@Lauragra could you please tell us ETA for merging this PR?

2022-12-13 21:11 UTC, isvargasmsft commented
Hello @afedorov-msft, would you be so kind to address the API Doctor errors in this PR? 

In addition, I'd deeply appreciate if you could address the broken links in the changelog. Broken links are in lines: 679,687,1525,1533,1551,1837,2117,2177,2185,2219,2319,2377,2385,2393,2401,2409,2417,2425,2475,2671,2697.

Thank you very much. 

CC: @Danielabom

2022-12-14 20:08 UTC, afedorov-msft commented
Hi @isvargasmsft !

1. Could you please help to clarify apidoctor issues since its errors logs seem confusing?
2. For the invalid links, most of the lines mentioned are not changed by this PR and are the same as in master.
    The changelog update for status message feature was generated by AG workloads build.
    Could you please clarify what exactly needs to be done to them?

2022-12-14 22:22 UTC, millicentachieng commented on api-reference/beta/resources/presence.md
>     "outOfOfficeSettings":{"@odata.type": "#microsoft.graph.outOfOfficeSettings"}
Add a comma at the end of this line

2022-12-15 18:45 UTC, afedorov-msft commented on api-reference/beta/resources/presence.md
>     "outOfOfficeSettings":{"@odata.type": "#microsoft.graph.outOfOfficeSettings"}
Thanks @millicentachieng !

2022-12-16 15:13 UTC, isvargasmsft commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the [setStatusMessage](https://learn.microsoft.com/en-us/graph/api/presence?view=graph-rest-beta) method to the [presence](https://learn.microsoft.com/en-us/graph/api/
```suggestion
          "Description": "Added the [setStatusMessage](https://learn.microsoft.com/en-us/graph/api/presence-setstatusmessage?view=graph-rest-beta) method to the [presence](https://learn.microsoft.com/en-us/graph/api/presence?view=graph-rest-beta) resource.",
```

2022-12-16 15:55 UTC, isvargasmsft commented on changelog/Microsoft.Skype.Calling.json
> +    },
```suggestion
```

2022-12-16 19:05 UTC, afedorov-msft commented on changelog/Microsoft.Skype.Calling.json
> +    },
Removed datetimetimezone

2022-12-16 19:37 UTC, isvargasmsft approved these changes

2022-12-16 20:47 UTC, merged