Update AuthenticationMethodsPolicy
microsoftgraph/microsoft-graph-docs pull request #19255
Opened 2022-11-15 20:10 UTC by jpettere

Add public preview changes

2022-11-15 20:13 UTC, opbld33 commented
Learn Build status updates of commit _[8a6e864](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a6e8648f24871372e095d686438ec93fc56c36d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.AuthenticationMethodsPolicy.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/changelog/Microsoft.AuthenticationMethodsPolicy.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211152010276529-19255/BuildReport?accessString=ec2d9bcf2929d9c77aac98de58d5f489e35f90c60fa861e8effd81d71a0d2be5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 02:38 UTC, opbld33 commented
Learn Build status updates of commit _[b5dae1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5dae1a862955d9df9c397172360102c36d925fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/voiceauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=p [...]

2022-11-29 02:41 UTC, opbld32 commented
Learn Build status updates of commit _[0f99b85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f99b85f98e331e35c9238bd24dd08c93d87347e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/voiceauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=p [...]

2022-11-29 02:57 UTC, opbld32 commented
Learn Build status updates of commit _[80fabd6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80fabd60779b5830a15470eaace0d4bdc9ca84ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/softwareoathauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-19255) (graph-rest-beta) |
[api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-11-16-jupetter-authmethodspolicy/api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/voiceauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=p [...]

2022-12-02 11:19 UTC, FaithOmbongi requested changes
Thank you @jpettere for your work on this PR. I've left suggestions inline in addition to the following comments.

_PS: With regard to my suggestions for includeTargets, I'm not sure what get's enforced immediately vs what's in transition until Jan 2024._

1. Changelog - Add the changelog as a standalone object in the file. Don't overwrite an existing changelog object.
2. For the **excludeTargets** property description, I understand that you can only specify groups, not individual users. Please indicate so in the authenticationmethodconfiguration.md and apply that string across all references.
3. **GLOBAL:** For [excludeTarget complex type](https://learn.microsoft.com/en-us/graph/api/resources/excludetarget?view=graph-rest-beta), should **id** therefore only indicate group? Should **targetType** say `user` isn't supported?
4. **GLOBAL:** For **includeTargets** property description - Not in the scope of this PR but I believe you should only specify either all users or specific groups, unlike today where you can specify individual users (correct me if I'm wrong). Should the [authenticationmethodtarget ](https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta) resource type be updated as well? For example: will **id** only be for a group? **targetType** is an enum that includes `user`. Should we say this value is no longer supported?
5. Update the TOC -  Surface the phone call and software oath policies.

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md
> +Read the properties and relationships of a [softwareOathAuthenticationMethodConfiguration](../resources/softwareoathauthenticationmethodconfiguration.md) object, which represents the Third-Party Soft
```suggestion
Read the properties and relationships of a [softwareOathAuthenticationMethodConfiguration](../resources/softwareoathauthenticationmethodconfiguration.md) object, which represents the third-party software OATH authentication method policy for the Azure AD tenant.
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethodconfiguration-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Mention specific query parameters; If none, say ".. method does not support OData query ...."

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md
> +|Application|Policy.ReadWrite.AuthenticationMethod|
Call our RBAC

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md
> +>**Note:** The response object shown here might be shortened for readability.
nit
```suggestion
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/smsauthenticationmethodconfiguration-update.md
> +>**Note:** The response object shown here might be shortened for readability.
nit
```suggestion
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodconfiguration.md
> +description: "Represents a Phone Call authenticaiton methods policy"
```suggestion
description: "Represents a phone call authentication methods policy."
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodconfiguration.md
> +Represents a Phone Call authentication methods policy. Authentication methods policies define configuration settings and users or groups that are enabled to use the authentication method.
```suggestion
Represents a phone call authentication methods policy. Authentication methods policies define configuration settings and users or groups that are enabled to use the authentication method.
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodconfiguration.md
> +|excludeTargets|[excludeTarget](../resources/excludetarget.md) collection|A collection of users or groups of users that are excluded from a policy.|
Same comment about groups only, no individual users

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodconfiguration.md
> +|isOfficePhoneAllowed|Boolean|`true` if users can register office phones, otherwise, `false`|
```suggestion
|isOfficePhoneAllowed|Boolean|`true` if users can register office phones, otherwise, `false`. |
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodconfiguration.md
> +|includeTargets|[voiceAuthenticationMethodTarget](../resources/voiceauthenticationmethodtarget.md) collection|A collection of users or groups who are enabled to use the authentication method. Expande
Same comment about groups or all users only. No individual users.

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md
> +Remove changes made to the [Phone Call authentication method policy](../resources/voiceauthenticationmethodconfiguration.md) by reverting the policy to its default configuration.
```suggestion
Revert the [phone call authentication method policy](../resources/voiceauthenticationmethodconfiguration.md) b to its default configuration.
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/voiceauthenticationmethodconfiguration-delete.md
> +>**Note:** The response object shown here might be shortened for readability.
nit
```suggestion
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/voiceauthenticationmethodconfiguration-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Call out the supported query parameters; If none, say "... method does not support OData query .."

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/voiceauthenticationmethodconfiguration-update.md
> +Update the properties of a [voiceAuthenticationMethodConfiguration](../resources/voiceauthenticationmethodconfiguration.md) object, which represents the Phone Call authentication method policy for th
```suggestion
Update the properties of a [voiceAuthenticationMethodConfiguration](../resources/voiceauthenticationmethodconfiguration.md) object, which represents the phone call authentication method policy for the Azure AD tenant.
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/voiceauthenticationmethodconfiguration-update.md
> +>**Note:** The response object shown here might be shortened for readability.
nit
```suggestion
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethodconfiguration-update.md
> +Update the properties of a [softwareOathAuthenticationMethodConfiguration](../resources/softwareoathauthenticationmethodconfiguration.md) object, which represents the Third-Party Software OATH authen
```suggestion
Update the properties of a [softwareOathAuthenticationMethodConfiguration](../resources/softwareoathauthenticationmethodconfiguration.md) object, which represents the third-party software OATH authentication method policy for the Azure AD tenant.
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/smsauthenticationmethodtarget.md
>  |isUsableForSignIn|Boolean|Determines if the users or groups can use this authentication method to sign in to Azure AD. The value is always `true`.|
- isUsableForSignIn can now be turned off, I believe - update the reference.
- Indicate what true and false correspond to. I see from your presentation it's:

true - can be used for MFA, SSPR, and first factor
false- can be used for MFA and SSPR only. First-factor not supported.

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodtarget.md
> +description: "A collection of users or groups enabled to use Phone Call authentication methods policy."
Same comment about groups or all users, not specific users.
```suggestion
description: "A collection of users or groups enabled to use phone call authentication method via policy."
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodtarget.md
> +A collection of users or groups enabled to use [Phone call authentication methods policy](../resources/voiceAuthenticationMethodConfiguration.md) in Azure AD.
Same comment as in the metadata also applies
```suggestion
A collection of users or groups enabled to use phone call authentication via the [phone call authentication methods policy](../resources/voiceAuthenticationMethodConfiguration.md) in Azure AD.
```

2022-12-02 11:19 UTC, FaithOmbongi commented on api-reference/beta/resources/voiceauthenticationmethodtarget.md
> +|targetType|authenticationMethodTargetType|The possible values are: `user`, `group`, and `unknownFutureValue`. Inherited from [authenticationMethodTarget](authenticationMethodTarget.md).|
For id and targetType - My comments about group and now individual users applies.

2022-12-12 23:30 UTC, jpettere commented on api-reference/beta/api/softwareoathauthenticationmethodconfiguration-delete.md
> +|Application|Policy.ReadWrite.AuthenticationMethod|
Not sure what you mean by this comment.

2022-12-13 00:29 UTC, jpettere commented
@FaithOmbongi thanks for your help reviewing. I addressed most of your comments and sent you a question about how to fix the validation issues for the changelog.

RE targeting of groups and not users. We updated the UI to only support targeting new groups (previously targeted users will remain) but have not made the same change at the API layer because its quite difficult to implement. We're ironing out plans to update the API and UI to basically ask customers who previously targeted individual users to "fix" a given method policy if they want to update it and when we do this we'll update the docs. For now, technically documenting that we don't support targeting users in MS Graph is inaccurate, but we could avoid mentioning it given the plans. What do you think?

2022-12-13 23:24 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
>  |registrationEnforcement|[registrationEnforcement](../resources/registrationenforcement.md)|Enforce registration at sign-in time. This property can be used to remind users to set up targeted authenti
If the two properties are marked as hidden in the schema, shouldn't they be hidden from the public graph schema.

2022-12-16 13:23 UTC, FaithOmbongi requested changes
Hi @jpettere - I've left some 5 comments of oversights - one will resolve the validation error.
Also document the authenticationMethodTargetType enumeration in the enums.md file.
I've also pushed a commit to fix some incorrectly autogenerated change entries.

2022-12-16 13:23 UTC, FaithOmbongi commented on api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
> +    "isSoftwareOathEnabled": "true",
This will resolve the validation warning.
```suggestion
    "isSoftwareOathEnabled": true,
```

2022-12-19 18:43 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
>  |registrationEnforcement|[registrationEnforcement](../resources/registrationenforcement.md)|Enforce registration at sign-in time. This property can be used to remind users to set up targeted authenti
Yeah the team expects them to be hidden from the graph schema too. Do we need to talk to someone else about this?

2022-12-19 19:17 UTC, jpettere commented on api-reference/beta/resources/excludetarget.md
> +|targetType|authenticationMethodTargetType|The type of the authentication method target. Possible values are: `group` and `unknownFutureValue`.|
Checked with engineering and it shouldn't be noted. They'll remove it from the schema.

2022-12-20 07:04 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationmethodspolicy.md
>  |registrationEnforcement|[registrationEnforcement](../resources/registrationenforcement.md)|Enforce registration at sign-in time. This property can be used to remind users to set up targeted authenti
Probably chat with the Graph onboarding team. There must be something engineers aren't doing on their end because this issue doesn't affect all objects.

2022-12-20 07:21 UTC, FaithOmbongi commented on api-reference/beta/resources/excludetarget.md
> +|targetType|authenticationMethodTargetType|The type of the authentication method target. Possible values are: `group` and `unknownFutureValue`.|
That's interesting. I wonder if it'll be possible to deprecate it given the enumeration type is already in the live schema because it has been used by includeTargets for years.  From my understanding, removing it today would be a breaking change.

2022-12-20 07:25 UTC, FaithOmbongi approved these changes
Hi @jpettere - I'm approving this PR but with one comment, about the authenticationMethodTargetType enum. You've mentioned that the team is removing the `user` member from this enum but that looks suspiciously like a breaking change, which I don't think then API reviewers would encourage.

Once your schema PR is approved and merged, verify what goes live for this enum and if it doesn't match the docs at that time, please make the necessary fixes.

Approved with comments.

2022-12-22 19:53 UTC, isvargasmsft commented on changelog/Microsoft.AuthenticationMethodsPolicy.json
> +      "CreatedDateTime": "2022-12-20T00:00:00.1642286Z",
```suggestion
      "CreatedDateTime": "2022-12-22T00:00:00.1642286Z",
```

2022-12-22 19:59 UTC, merged