User Story 154682|User Story 154680| Doc customer scenarios
microsoftgraph/microsoft-graph-docs pull request #19300
Opened 2022-11-18 19:53 UTC by AshwaniBansal1

Direct deep link to the assignment

Update data in Assignments and grades

2022-11-18 19:56 UTC, opbld34 commented
Learn Build status updates of commit _[f8fd0cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8fd0cfad2e78079cc94236c5fc8d72b45c2467f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-4825e68e)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-4825e68e"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 16, Column 112**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 112**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211181953401931-19300/BuildReport?accessString=268c732a3ae48fec91c60ae603642f13d846ec66bd45ea56c082ee56c82e66ed).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 21:57 UTC, cristobal-buenrostro requested changes

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +description: "Get direct deep link to the assignment for reporting, communication and automation tools."
"Use Microsoft Graph to get ...."

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +author: "ashwani-bansal"
your github account; please consider it for all pages you create in the repository

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +**Note:** You can use [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to test the [Education APIs](https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplore
> ** Note:**

the ">" sign will display the paragraph as note.

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +## API to use for classes and members information
Get classes and members information

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +## Direct deep link for the assignment
Get direct deep link for the assignment

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +## Direct deep link for the submission
Get direct deep link for the submission

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +## Permissions required
just "Permissions"

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +## Scenario
remove this line

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +description: "Use microsoft Graph to update data in assignments and grades for reporting, communication and automation tools."
**M**icrosoft

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +## Scenario
remove

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +**Note:** You can use [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to test the [Education APIs](https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplore
prefix ">" similar to the other scenario

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +## API to use for classes and members information
Get classes and members information

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +## Permissions required
Permissions

2022-11-21 21:57 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +**Note:** Since Student Information and Grade information is sensitive data, it needs to be verified if AppOnly data is what is needed for the scenario.
prefix ">"

2022-11-22 20:27 UTC, cristobal-buenrostro approved these changes

2022-12-01 17:46 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +description: "Use Microsoft Graph to gx et direct deep link to the assignment for reporting, communication and automation tools."
```suggestion
description: "Use Microsoft Graph to get a deep direct link to the assignment for reporting, communication, and automation tools."
```

2022-12-01 17:54 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +# Get direct deep link to the assignment
```suggestion
# Get a deep direct link to the assignment.
```

2022-12-01 17:57 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +Education institutions have custom tools that are used for the students, user needs to provide a direct deep link to the assignment, so students can directly view more details or complete the given a
```suggestion
Education institutions have custom tools for students and users who need to obtain a deep direct link to the assignment, so students can directly view more details or complete a given assignment.
```

2022-12-01 18:11 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +All the assignments and grades information is part of the team in Microsoft Teams. You can get information about classes, members, and roles (student or teacher) in a team by using the following Team
```suggestion
All assignments and grading information are part of a team in Microsoft Teams. You can get information about classes, members, and roles (student or teacher) in a team by using the following Teams APIs:
```

2022-12-01 18:13 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +After you get the relevant class and member information, you can get the assignment and grade information that you need.
```suggestion
After you get the relevant class and member information, you can get the assignment and grade information you need.
```

2022-12-01 18:15 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +## Get direct deep link for the assignment
```suggestion
## Get a deep direct link for the assignment.
```

2022-12-01 18:19 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +The [Assignment Property](/graph/api/resources/educationassignment#properties) webURL returns the authenticated deep link to the selected assignments. For user within Teams it will open the assignmen
```suggestion
The [Assignment Property](/graph/api/resources/educationassignment#properties) returns the authenticated deep link to the selected assignments. For Teams' users, the assignments open directly.
```

2022-12-01 18:23 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +The [Submission Property](/graph/api/resources/educationsubmission#properties) webURL returns the authenticated deep link to the submission.
```suggestion
The [Submission Property](/graph/api/resources/educationsubmission#properties) web URL returns the authenticated deep link to the submission.
```

2022-12-01 18:27 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +Assignments APIs supports both delegated (per user) and AppOnly (per App) permission. For ease of use for the student and teacher Apponly is preferred as this allows for only approval of your app to
```suggestion
Assignments APIs support both delegated (per user) and AppOnly (per App) permission. We recommend using Apponly as it only permits your app to retrieve data.
```

2022-12-02 16:23 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +The [Submission Property](/graph/api/resources/educationsubmission#properties) webURL returns the authenticated deep link to the submission.
WebURL is the name of the property.
 no change.

2022-12-02 16:27 UTC, opbld31 commented
Learn Build status updates of commit _[1785bc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1785bc1c412524025cb11adea6c918c0bb327453)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-2475105c)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-2475105c"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021625060209-19300/BuildReport?accessString=fd49af2cbe85cb635b88114a2a95313339463f5ab04c731a231eb8d11a4cc070).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 16:29 UTC, opbld30 commented
Learn Build status updates of commit _[006f308](https://github.com/microsoftgraph/microsoft-graph-docs/commits/006f3081bc106e52810fdb8302679d9a5d3a9e16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-52421323)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-52421323"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021626242586-19300/BuildReport?accessString=9cec51da1b9940f01755a53f7e8a66fa93f1a627cbc2387cea5a67ce764a0c14).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 16:32 UTC, opbld32 commented
Learn Build status updates of commit _[b177f94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b177f944edf1f1350183d956eee4cded90d85091)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-d8150950)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-d8150950"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021627383876-19300/BuildReport?accessString=8e2bc939eb997846aa11bd6f37ac7f2ceab7e97071b393893031549f819fde70).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 20:10 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +---
Please add the .md extension to this file.

2022-12-02 20:14 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +description: "Use Microsoft Graph to get a deep direct link to the assignment for reporting, communication, and automation tools."
"Deep direct link" is not commonly used in our docs. Is "deep link" good enough? If so, please make the changes in the files.

2022-12-02 20:18 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +# Get a deep direct link to the assignment.
```suggestion
# Get a deep direct link to the assignment
```

2022-12-02 20:20 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +## Get a deep direct link for the assignment.
```suggestion
## Get a deep direct link for the assignment
```

2022-12-02 20:21 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +The [Assignment Property](/graph/api/resources/educationassignment#properties) returns the authenticated deep link to the selected assignments. For Teams' users, the assignments open directly.
```suggestion
The [Assignment property](/graph/api/resources/educationassignment#properties) returns the authenticated deep link to the selected assignments. For Teams' users, the assignments open directly.
```

2022-12-02 20:21 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +##  Get a deep direct link for the submission.
```suggestion
##  Get a deep direct link for the submission
```

2022-12-02 20:22 UTC, opbld30 commented
Learn Build status updates of commit _[2c9f836](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c9f8369ffa5f2022dedbdd6f49f6fc7bd3ab709)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-82ef0704)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-82ef0704"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212022019260686-19300/BuildReport?accessString=663570a66f2d740393b715db7bbb635a89dcff9eff1c57c1a70a6b1b2b7c6c6e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 20:22 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +The [Submission Property](/graph/api/resources/educationsubmission#properties) webURL returns the authenticated deep link to the submission.
```suggestion
The [Submission property](/graph/api/resources/educationsubmission#properties) webURL returns the authenticated deep link to the submission.
```

2022-12-02 20:25 UTC, opbld30 commented
Learn Build status updates of commit _[d665c64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d665c640e58a373ea5ec91977a1a6f363d4f8071)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-d541d328)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-d541d328"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212022020390723-19300/BuildReport?accessString=bf0fcb1511dca7f6a9274a1f70118480b7554a08ffe6c9792ed934b7f8488d1f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 20:28 UTC, Danielabom commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +Education institutions have custom tools that needs to update assignments and grades data; for example, user needs to create an assignment with custom tool, or update grades data ( outcome) for the s
```suggestion
Education institutions have custom tools to update assignments and grading data. For example, a user may need to create an assignment or update grading data (outcome) with a custom tool for students to submit them.
```

2022-12-02 20:29 UTC, Danielabom commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +All the assignments and grades information is part of the team in Microsoft Teams. You can get information about classes, members, and roles (student or teacher) in a team by using the following Team
```suggestion
All the assignments and grading information are part of the team in Microsoft Teams. You can get information about classes, members, and roles (student or teacher) in a team by using the following Teams APIs:
```

2022-12-02 20:29 UTC, Danielabom commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +After you get the relevant class and member information, you can get the assignment and grade information that you need.
```suggestion
After you get the relevant class and member information, you can get the assignment and grade information you need.
```

2022-12-02 20:36 UTC, Danielabom commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +For update of data in assignments user get support for both delegated (per user) and AppOnly (per App). AppOnly support is currently only for Beta version.
```suggestion
Delegated (per user) and AppOnly (per App) permissions are required to update data in assignments. AppOnly permissions are currently supported in beta versions only.
```

2022-12-02 20:45 UTC, Danielabom commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +> **Note:** Since Student Information and Grade information is sensitive data, it needs to be verified if AppOnly data is what is needed for the scenario.
```suggestion
> **Note:**  Since student and grade information is sensitive data, please verify which permissions are required. 
```

2022-12-02 20:47 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +Assignments APIs support both delegated (per user) and AppOnly (per App) permission. We recommend using Apponly as it only permits your app to retrieve data.
```suggestion
Assignments APIs support both delegated and application permissions. We recommend using application permissions as it only permits your app to retrieve data.
```

2022-12-02 20:48 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +---
Please update the TOC.

2022-12-02 20:49 UTC, Danielabom requested changes
Thank you for working on this PR. Please review my comments.

2022-12-06 16:28 UTC, opbld30 commented
Learn Build status updates of commit _[3b191b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b191b03378cf7465cf6b138a135281017ba6ad1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-4972366c)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-4972366c"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212061626268534-19300/BuildReport?accessString=7acdcfe34eafd91997039abecc7fd90f5a08819cee579ad2f754ff1eb6fd8ba8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 16:30 UTC, opbld33 commented
Learn Build status updates of commit _[11e56e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11e56e5dc9deb0ba278266c8c515ee1c9a12be97)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-05b18702)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-05b18702"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212061626523168-19300/BuildReport?accessString=9de78f1947f7efeefde0ec561311ca3702e2909160a365b29f46208ac6b0a4e8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 16:32 UTC, opbld34 commented
Learn Build status updates of commit _[efd0569](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efd056954c8dc494d090d707f4d254245ef683f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-3f98669f)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-3f98669f"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212061628475684-19300/BuildReport?accessString=59244cfc0c7bd66653d24c11191ca2dace98d2e35f718f993df68c7a2db47df9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 18:36 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +---
@AshwaniBansal1, please address the comment above. Thanks!

2022-12-06 18:36 UTC, opbld34 commented
Learn Build status updates of commit _[b2b6666](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2b66664fe9fe2d41c496125ca3e26f7cccae372)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-1ac5b225)
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool) | :white_check_mark:Succeeded | |

<a id="c4d6b0d1e6f2164471b45715f22a9048-1ac5b225"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212061833221769-19300/BuildReport?accessString=2c9f09cacf67b21ae7f501b35ff28708d301af28d4aff95770745bf4d1a3e6b4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 18:36 UTC, Danielabom commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool
> +description: "Use Microsoft Graph to get a deep direct link to the assignment for reporting, communication, and automation tools."
@AshwaniBansal1, please address the comment above. Thanks.

2022-12-06 18:39 UTC, Danielabom requested changes
@AshwaniBansal1, please address the first two comments, as they are important for the overall review. And, please add the TOC. Thanks!

2022-12-07 14:47 UTC, opbld34 commented
Learn Build status updates of commit _[21e250c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21e250cfbda73e6c6ab9c0a0b6d12f2a25c94514)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-5a331572)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-5a331572)

<a id="9c4d2e161d3a7de93c91c77e385570fb-5a331572"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-5a331572"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212071445021457-19300/BuildReport?accessString=730133b06d1342309374a2c59a8bc0b11a59498e1b7fa337b037668a9d2eebe0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 18:46 UTC, Danielabom approved these changes
Thank you for addressing my comments @AshwaniBansal1. Based on our chat, the TOC will be updated in a different PR. 
PR approved.

2022-12-07 18:49 UTC, opbld34 commented
Learn Build status updates of commit _[a10e96b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a10e96b3352760560cfef0a29abb1787efa43198)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-6f176d53)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-6f176d53)

<a id="9c4d2e161d3a7de93c91c77e385570fb-6f176d53"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-6f176d53"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212071847067420-19300/BuildReport?accessString=7f36dc67f2902cb85ab29700846771018c8966b1990ba364b5901d734dd0d3ff).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 02:56 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +# Get a deep link to the assignment
I wonder if this is the right title/H1, since you cover getting class and member information, and getting links for assignments and submissions. I recommend expanding the title: "Get class and member information and links to assignments and submissions". It's a bit long though.

2022-12-09 02:56 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +description: "Use Microsoft Graph to get a deep link to the assignment for reporting, communication, and automation tools."
Note that text that you include in the description only shows in SERP. Do you want to mention reporting, communication, and automation tools in the text of the article?

2022-12-09 02:58 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +## Get classes and members information
If this is a prerequisite to the main purpose of getting the assignment link, be sure to make that clear in the text.

2022-12-09 02:59 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +The [submission property](/graph/api/resources/educationsubmission#properties) webURL returns the authenticated deep link to the submission.
Please double-check this. I don't see a submission property. Did you mean to refer to the educationSubmission resource? I also don't see any mention of a webUrl in that resource topic.

2022-12-09 03:00 UTC, opbld31 commented
Learn Build status updates of commit _[b3122f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3122f82844109168d6fd30e3c6ba3028b41341b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-d13a10b6)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-d13a10b6)

<a id="9c4d2e161d3a7de93c91c77e385570fb-d13a10b6"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-d13a10b6"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212090257473719-19300/BuildReport?accessString=2c26b615458d3ae9f71af961b4614fc8716a35038627c88b44dd885de9c11b23).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 03:03 UTC, Lauragra commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +- [educationAssignment resource type](/graph/api/resources/educationassignment): Lists all data for assignments in a class.
Did you mean to link to List and Get method topics here?

2022-12-09 03:03 UTC, Lauragra commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +# Update data in assignments and grades
Does this article mention anything about updating the data? The APIs mentioned are about getting information, not updating it.

2022-12-09 03:04 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +title: "Get a deep link to an assignment"
Please surface these topics in the TOC under Learn/Teamwork and communications.

2022-12-09 03:04 UTC, Lauragra requested changes
Please see my review comments. Thanks.

2022-12-09 16:23 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +title: "Get a deep link to an assignment"
We are going to update the same in the another PR, the file is still not merged into main. Once it is merged we are going to merge the file with new pages.

2022-12-09 16:29 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +The [submission property](/graph/api/resources/educationsubmission#properties) webURL returns the authenticated deep link to the submission.
https://learn.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta#properties : Still the property needs to be updated in v1.0

2022-12-09 18:24 UTC, opbld31 commented
Learn Build status updates of commit _[e35b6f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e35b6f93e9931ca18eae41f36b9ea73d756a8750)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-31c76fc0)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-31c76fc0)

<a id="9c4d2e161d3a7de93c91c77e385570fb-31c76fc0"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-31c76fc0"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091822424442-19300/BuildReport?accessString=391cae83c38a0465483ec55848e92ef1edf4f867929cf6ce79fb60bfbe709f5d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 18:30 UTC, opbld32 commented
Learn Build status updates of commit _[db94717](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db947175b8e680667c272960146b4b8b1a9c019e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-12fc0924)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-12fc0924)

<a id="9c4d2e161d3a7de93c91c77e385570fb-12fc0924"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-12fc0924"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212091827511098-19300/BuildReport?accessString=ff08f54d015ccfbf24c4a2b886ab3fb0de81582eb9840766fd144e81e4d76db2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 23:11 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +The [submission webURL property](/graph/api/resources/educationsubmission#properties) returns an authenticated deep link to a submission.
I still don't see the referenced webURL property in the topic you're linking to here.

2022-12-09 23:13 UTC, opbld34 commented
Learn Build status updates of commit _[84ca6f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84ca6f2a1ac60233af4b0146ec909def7825b172)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-f400b8e3)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-f400b8e3)

<a id="9c4d2e161d3a7de93c91c77e385570fb-f400b8e3"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-f400b8e3"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212092310492494-19300/BuildReport?accessString=1a0077c528248f6bb8ac80bec212e7d7212f5f9442014e72dc76d1bb75ba365b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 23:27 UTC, opbld34 commented
Learn Build status updates of commit _[6608e5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6608e5abe4eb8879102d8be934bfead81d7b2ee0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-42301b75)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-42301b75)

<a id="9c4d2e161d3a7de93c91c77e385570fb-42301b75"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-42301b75"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212092324058616-19300/BuildReport?accessString=3e368740e839817d7e36388a015b6aa8fa3a28f36d8ef2e0230b0dca4f5ddbc0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 23:30 UTC, opbld30 commented
Learn Build status updates of commit _[283c5d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/283c5d4fee9bd8f088180cf61b4313a156e0d126)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-caf0a089)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-caf0a089)

<a id="9c4d2e161d3a7de93c91c77e385570fb-caf0a089"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-caf0a089"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212092326569941-19300/BuildReport?accessString=9dc861ed4ad5f31c277ac131f32d9e7adb6ddf40e762eae80c02616584c77e77).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 23:31 UTC, Lauragra commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +- [educationAssignment resource type](/graph/api/resources/educationassignment): Lists all the methods available for assignments in a class.
These are not list/get operation topics, they are links to resources. Are you linking to the right topics here?

2022-12-09 23:32 UTC, Lauragra commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +The outcome data will be recalculated based on changes in the property values. To update student points outcome data, see [update a points outcome](/graph/api/educationoutcome-update?#example-2-updat
I'm not sure if these is completely clear. You might want to provide some more detail here about how the values actually change - what is the recalculation based on? 

Per my earlier comment, this topic would also benefit from and end-to-end example rather than just links to other topics.

2022-12-09 23:33 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +title: "Get links to assignments and submissions"
FYI before we can publish this PR, we will need TOC entries. The TOC should be updated in the same PR that adds the new topics.

2022-12-09 23:33 UTC, opbld32 commented
Learn Build status updates of commit _[8e69377](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e69377fd243967862d6fe19383fbeb6f30552f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-get-direct-deep-link-to-assignment-for-tool?branch=pr-en-us-19300) | [Details](#user-content-9c4d2e161d3a7de93c91c77e385570fb-30e094dd)
[concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-update-assignment-grade-data-for-tool?branch=pr-en-us-19300) | [Details](#user-content-c4d6b0d1e6f2164471b45715f22a9048-30e094dd)

<a id="9c4d2e161d3a7de93c91c77e385570fb-30e094dd"></a>
### [concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md)
 - **Line 14, Column 115**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 115**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="c4d6b0d1e6f2164471b45715f22a9048-30e094dd"></a>
### [concepts/msgraph-customer-update-assignment-grade-data-for-tool.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AsBansal/CustomerScenarios/concepts/msgraph-customer-update-assignment-grade-data-for-tool.md)
 - **Line 16, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212092330538111-19300/BuildReport?accessString=3c7620d6be34bd475bd3994d28f5491034a1d1ab0f59b937238f04c0f358e7a0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-21 16:16 UTC, Danielabom commented
Hi @AshwaniBansal1, @Lauragra posted some comments. Let me know if you have any questions.

2023-01-06 17:50 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +The [submission webURL property](/graph/api/resources/educationsubmission#properties) returns an authenticated deep link to a submission.
currently only in beta updated the statement

2023-01-06 17:50 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +The [assignment property](/graph/api/resources/educationassignment#properties) returns the authenticated deep link to selected assignments. For Teams users, the assignments open directly.
updated

2023-01-06 17:51 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +- [educationAssignment resource type](/graph/api/resources/educationassignment): Lists all the methods available for assignments in a class.
linking to the education assignments and submissions for the required methods

2023-01-06 17:51 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +The outcome data will be recalculated based on changes in the property values. To update student points outcome data, see [update a points outcome](/graph/api/educationoutcome-update?#example-2-updat
updated

2023-01-13 02:44 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +---
Global: These file names are a bit long and will result in long URLs, which is not ideal for SEO. Can we try to shorten the file names? For example: get-assignment-deep-link, update-assignment-grade.

2023-01-13 03:00 UTC, Lauragra commented on concepts/msgraph-customer-update-assignment-grade-data-for-tool.md
> +Education institutions have custom tools to update assignment and grade data. For example, a user might need to create an assignment or update a grade (outcome) with a custom tool for students to sub
The second sentence is not clear. See if this suggested revision is accurate: "For example, a teacher might need to make an update to an assignment before students submit them, or make a change to a grade (outcome) by using a custom tool."

2023-01-13 03:06 UTC, Lauragra commented on concepts/msgraph-customer-get-direct-deep-link-to-assignment-for-tool.md
> +---
Please include an update to the TOC to surface these two new topics, as we've already merged the PR that introduced the new TOC section. Please also add these as additional scenarios to the following topic: https://learn.microsoft.com/en-us/graph/msgraph-customer-scenarios

2023-01-13 18:23 UTC, Lauragra commented on concepts/msgraph-assignment-deeplink-for-tool.md
> +title: "Get links to assignments and submissions"
Regarding the file name updates, do we need the "for-tool" part in the file name or can that be covered in the content?

Please add a hyphen between deep-link and change "gradefortool" to "grade" or "grade-for-tool" (not sure that the for-tool is necessary).

2023-01-18 03:51 UTC, Lauragra commented on concepts/assignment-deeplink-for-tool.md
> +title: "Get links to assignments and submissions"
Please update the file name here to this: get-links-to-assignments-and-submissions. Note that file names are part of the topic URLs, and we should follow best practices to help with SEO/content discovery. Please also update any links (Build validations will flag any broken links).

2023-01-18 03:55 UTC, Lauragra commented on concepts/msgraph-customer-scenarios.md
> +- [Get data from assignments and grades](/graph/msgraph-customer-assignmentgradedatafortool)
I suggest we update the file name for this topic to: connect-to-assignments-and-grades, to better align with the title and content.

2023-01-18 03:57 UTC, Lauragra commented on concepts/update-assignment-grade-for-tool.md
> +title: "Update assignment and grade data"
The file name here can simply be: update-assignment-and-grade-data.

2023-01-19 03:15 UTC, Lauragra approved these changes

2023-01-19 03:16 UTC, merged