Take new Alerts, Incidents & Hunting APIs to GA.
microsoftgraph/microsoft-graph-docs pull request #19339
Opened 2022-11-22 17:37 UTC by BenAlfasi

2022-11-22 18:15 UTC, opbld33 commented
Learn Build status updates of commit _[2098eea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2098eeaef478b561f820062dc1cc86db01314e49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-9d656d80)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-9d656d80)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-9d656d80)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-9d656d80)
[api-reference/v1.0/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-incidents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-5bdb399ddd09ee62ae52f2f8d70c5309-9d656d80)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-9d656d80)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-9d656d80)
[api-reference/v1.0/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-4e5a7c36dc5bf50bcd58e08d66bf0f2a-9d656d80)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9d656d80)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-9d656d80)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View]( [...]

2022-12-01 07:33 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/security-alert.md
> +
@BenAlfasi , after line 18, there should be a note to bring awareness to the section in the security-api-overview.md topic, that disambiguates the two types of alerts. 
Even though I guess we don't want to point customers to use the old alerts, but the fact is from the customers' perspective, the old alert is still side-by-side with the new alerts without any indication that the old alert is being deprecated. So the pattern we used in the beta docs to disambiguate should apply in v1 as well, to avoid the confusion of having now two types of alerts in v1.

The beta note is in the include file called alerts-callout-two-types.md. That applies to the beta version only.

The v1 note would have to be created similarly, except that it should say "v1.0 version" instead of "beta version", and the link should go to the security-api-overview.md in v1.

2022-12-01 07:34 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/security-alert.md
> +
In addition to updating security-alert.md, that note should also appear in alert.md, in the v1 version.

2022-12-01 07:55 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/security-alert.md
> +
And one more comment about alert.md in the v1 version - other than adding the note I mentioned above, please take a look at the delta for that file alert.md in your PR 14745. There are other updates that you should please make to that file as well.

2022-12-04 12:21 UTC, opbld30 commented
Learn Build status updates of commit _[346dc1f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/346dc1f25289c4248159889ca5b8d8c09daba0be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-75c8753d)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-75c8753d)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-75c8753d)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-75c8753d)
[api-reference/v1.0/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-incidents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-5bdb399ddd09ee62ae52f2f8d70c5309-75c8753d)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-75c8753d)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-75c8753d)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-75c8753d)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-1.0&bran [...]

2022-12-07 06:40 UTC, opbld34 commented
Learn Build status updates of commit _[ebc59f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebc59f1e10f3dbe0b6534f268af0306e3ff7adcf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-2cf61f57)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-2cf61f57)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-2cf61f57)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-2cf61f57)
[api-reference/v1.0/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-incidents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-5bdb399ddd09ee62ae52f2f8d70c5309-2cf61f57)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-2cf61f57)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-2cf61f57)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-2cf61f57)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums-security?view=g [...]

2022-12-07 06:42 UTC, opbld32 commented
Learn Build status updates of commit _[9e10601](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e106016aafd8d4a20661d70c482db56277725ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-08221eac)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-08221eac)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-08221eac)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-08221eac)
[api-reference/v1.0/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-incidents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-5bdb399ddd09ee62ae52f2f8d70c5309-08221eac)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-08221eac)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-08221eac)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-08221eac)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums-security?view=g [...]

2022-12-07 06:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alertevidence.md
> +| notFound                   | The evidence was not found.                    |
Since you removed a few of these enum members, where this enum is used (i.e., remediationStatus property in line 31), you also need to remove those possible values.
I'm going ahead to do that since I have the file open in front of me, to save us a round trip. :-)

2022-12-07 09:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-incident.md
For the 3 changes to the 3 resources in the beta version, @BenAlfasi , can you please add them to the changelog?
You'll need to add a changelog record for these 3 changes for the beta version (i.e., the changelog record would have  "Version": "beta"). Each change would be in its own changelist record, total of 3 changelist records for that changelog record.
More info: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-properties

2022-12-07 09:09 UTC, angelgolfer-ms commented on api-reference/v1.0/api/security-incident-post-comments.md
> +# Create comment for incident
Line 11:
FYI, I overlooked this topic title before. Per topic title guidance for a create operation, the topic title should be just "Create comment". The TOC title can be more descriptive as is (i.e., "Create comment for incident").

I made the change to each of the v1 and beta version of the topic.

2022-12-07 09:19 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-ipevidence.md
FYI since you added a new property, then you'd also need to add that definition to the "JSON representation" section.
I have done that on your behalf.
Otherwise if you have an example that includes that property, API Doctor would return an error. The "JSON representation" section is primarily for API Doctor to cross-check property existence and type.

More info here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211782/Set-up-for-API-Doctor-validation?anchor=set-up-for-api-doctor-in-a-resource-topic

2022-12-07 09:50 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/security-api-overview.md
>  The Microsoft Graph security API provides key features as described in the following sections.
This comment is for the beta version of security-api-overview.md, any other topics, and the TOC:
For the 3 sets of API that you're making available in v1 as well, you need to make sure they are no longer marked as "(preview)". For example, in security-api-overview.md, you need to search for "(preview)" and remove those tags. Same with the TOC.

To save us turnaround, on your behalf, I removed those "(preview)" tags in security-api-overview.md and toc.yml in the beta version.

2022-12-07 09:52 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/security-api-overview.md
>  The Microsoft Graph security API provides key features as described in the following sections.
FYI, you can find a list of things to check when GA-ing an API set here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211781/Moving-docs-from-beta-to-v1.0

2022-12-07 10:32 UTC, opbld33 commented
Learn Build status updates of commit _[0bc7f3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0bc7f3fe6ba12e3e60ff8106987cbd8952012798)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-cf854bb2)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-cf854bb2)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-cf854bb2)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-cf854bb2)
[api-reference/v1.0/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-incidents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-5bdb399ddd09ee62ae52f2f8d70c5309-cf854bb2)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-cf854bb2)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-cf854bb2)
[api-reference/v1.0/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-03ac5f3bb5a8a5ce2b8fecf3f0a79d95-cf854bb2)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-cf854bb2)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/g [...]

2022-12-07 10:32 UTC, angelgolfer-ms requested changes
Hi @BenAlfasi , I haven't finished going through all the topics yet, but I thought you might want to take the time to address a couple of comments where I requested your follow-up. 
Please take a look at what I have updated in your PR as well.
Thanks.

2022-12-08 03:24 UTC, opbld32 commented
Learn Build status updates of commit _[f79f372](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f79f372dbb39f80886cb4968e8855dc6a67ffd8c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-c4313a42)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-c4313a42)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-c4313a42)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-c4313a42)
[api-reference/v1.0/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-incidents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-5bdb399ddd09ee62ae52f2f8d70c5309-c4313a42)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-c4313a42)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-c4313a42)
[api-reference/v1.0/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-03ac5f3bb5a8a5ce2b8fecf3f0a79d95-c4313a42)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-c4313a42)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/g [...]

2022-12-08 03:32 UTC, angelgolfer-ms commented on api-reference/v1.0/toc.yml
> +        href: resources/alert.md
Line 6880:
FYI the guidance of TOC title for a resource topic is to use the actual resource name, i.e., "Alert".
If we leave lines 6879 and 6880, the publishing platform would insert a TOC title by the same name "Legacy alert", but unfortunately there's not such resource name as legacyAlert in Graph... 
Anyway, I changed these few lines to mirror how we did that in beta.

2022-12-08 04:15 UTC, opbld30 commented
Learn Build status updates of commit _[6e37c6c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e37c6c696c66d2363ece82129528754209e9374)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-bf6111a6)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-bf6111a6)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-bf6111a6)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-bf6111a6)
[api-reference/v1.0/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-list-incidents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-5bdb399ddd09ee62ae52f2f8d70c5309-bf6111a6)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-bf6111a6)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-bf6111a6)
[api-reference/v1.0/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-03ac5f3bb5a8a5ce2b8fecf3f0a79d95-bf6111a6)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-bf6111a6)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/g [...]

2022-12-08 04:43 UTC, angelgolfer-ms commented on api-reference/v1.0/api/security-list-incidents.md
> +# [HTTP](#tab/http)
@BenAlfasi ,
This is one of the files that had the build warning "Line 77, Column 1: [Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)] Duplicate tab id: (http, 2)."

I am not sure why this warning is only called out for this topic that has two examples, and not in those other topics in v1 in this PR that have only one example each. But I'll try to fix this by removing line 77.

FYI technically, when you're creating a new example (or in this case, copying an example to a new v1 topic), you'd want to remove these language-specific tabs like the one for "HTTP" (REST API) in line 77. When there's only the REST API example, that HTTP tab is not necessary.

The normal process is, after your PR is published, within the week, when the snippet tool runs, it inserts language tabs and language-specific code snippets to any new example or example with a request that has been modified.

2022-12-08 04:59 UTC, opbld33 commented
Learn Build status updates of commit _[cf9df56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf9df5631d62b012f8798843e3afd09ca8d6b0a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-ca563d26)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-ca563d26)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-ca563d26)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-ca563d26)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-ca563d26)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-ca563d26)
[api-reference/v1.0/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-03ac5f3bb5a8a5ce2b8fecf3f0a79d95-ca563d26)
[api-reference/v1.0/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-security-runhuntingquery.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-da5b9a1566329927f6f50b51b9a239e5-ca563d26)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?v [...]

2022-12-08 05:01 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/security-api-overview.md
> +
Line 100:
This line triggered a build warning: "Line 100, Column 1: [Warning: multiple-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)] Multiple H1s(H1 'Incidents') are not allowed. You can only have one top-level heading."

FYI the way to fix this is indeed not keep the first level heading (i.e., "#") as there's already one in line 10, the topic title, and change that to "##".

2022-12-08 05:09 UTC, opbld32 commented
Learn Build status updates of commit _[c136731](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1367319bdf3b9779f2b977f66f40e449015f2c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e93b162aee90e20076d84a27b8e77e5d-a8a230c5)
[api-reference/v1.0/api/alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-f001a30db8b090cedc258a2c5a8f5477-a8a230c5)
[api-reference/v1.0/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-bcfa7f4be8fa3375763b2b3919e74caa-a8a230c5)
[api-reference/v1.0/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-adb727bcad22a87a0bca3a3c78e3d37c-a8a230c5)
[api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-e09ff4206be46c1e4e572f4da97f4474-a8a230c5)
[api-reference/v1.0/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/resources/security-alert.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) | [Details](#user-content-b399e62312e92dfebe9f2bfb5d47b7e1-a8a230c5)
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/api/security-security-runhuntingquery.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-19339) (graph-rest-beta) |
[api-reference/v1.0/api/security-alert-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-alert-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-alert-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-post-comments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-post-comments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-post-comments?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-SecurityGraph-GA/api-reference/v1.0/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-1.0&branch=pr-en-us-19339) (>= graph-rest-1.0) |
[api-reference/v1.0/api/security-list-alerts_v2.md](https://gi [...]

2022-12-08 05:20 UTC, angelgolfer-ms commented on api-reference/v1.0/api/security-list-incidents.md
> +# [HTTP](#tab/http)
FYI removing line 77 was the fix.
Please just keep this in mind for the future - do not copy tabs or INCLUDE lines for code snippets from another file. These are auo-generated post-publishing.

2022-12-08 05:23 UTC, angelgolfer-ms requested changes
@BenAlfasi , I have finished reviewing this PR and made a number of fixes on your behalf, to save us time iterating so that the docs can go live sooner, as the v1 metadata already reflects these APIs.
Please take a look at my comments for future application.
I think there's at least one comment for your action in the changelog: https://github.com/microsoftgraph/microsoft-graph-docs/pull/19339#discussion_r1041939352

Please check if there are any other comments actionable by you though.

Thanks.

2022-12-13 20:36 UTC, BenAlfasi commented on api-reference/beta/resources/security-alertevidence.md
> +| notFound                   | The evidence was not found.                    |
Thank you!

2022-12-13 20:54 UTC, BenAlfasi commented on api-reference/v1.0/api/security-incident-post-comments.md
> +# Create comment for incident
Thanks!

2022-12-13 20:55 UTC, BenAlfasi commented on api-reference/beta/resources/security-ipevidence.md
Thank you!

2022-12-13 20:56 UTC, BenAlfasi commented on api-reference/v1.0/resources/security-api-overview.md
>  The Microsoft Graph security API provides key features as described in the following sections.
Thanks!

2022-12-13 20:58 UTC, BenAlfasi commented on api-reference/v1.0/toc.yml
> +        href: resources/alert.md
Thanks!

2022-12-13 20:59 UTC, BenAlfasi commented on api-reference/v1.0/api/security-list-incidents.md
> +# [HTTP](#tab/http)
Thanks!

2022-12-13 21:00 UTC, BenAlfasi commented on api-reference/v1.0/resources/security-api-overview.md
> +
Thanks for the fix!

2022-12-15 09:28 UTC, angelgolfer-ms commented on changelog/Microsoft.M365.Defender.json
> +			"ChangeList": [
Lines 425-458:
FYI these lines all belong to the same changelog record. The "Id" property within the same changelog record should all share the same value; that value is unique to that changelog record.

See https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-properties.

On your behalf, to save us another iteration, I'm fixing this issue.

2022-12-15 09:41 UTC, angelgolfer-ms commented on changelog/Microsoft.M365.Defender.json
> +					"Id": "de54d2e0-f6ea-485c-9b8d-85f7b484cddb",
Lines 428-433:
This changelist record is about removing enum members. Can you confirm if this was generated by Graph Studio, or did you manually create it?

Technically, AFAIK, the design was to have the following, so that each of the removed enum member is filterable:
"ApiChange" should be "Member".
"ChangedApiName" is the name of an impacted enum member, and only one at a time.
"ChangeType" would be "Deletion".
"Description" would be "Deleted {member name} from the evidenceRemediationStatus enumeration."
"Target" would be "evidenceRemediationStatus".

That being said, perhaps we can try the approach you used by specifying this as a "Change" to the enumeration.
One of the things that still needs to change is, because only the description is displayed to the customer in the changelog, it should be clear - you need to include the enum name!

I'll add this on your behalf to save us another iteration.

2022-12-15 09:43 UTC, angelgolfer-ms commented on changelog/Microsoft.M365.Defender.json
> +					"Target": "incident"
Line 440:
FYI per Microsoft Writing Style Guide, the correct styling for properties is bold, so tags and customTags should be bold instead of being enclosed in tick marks.
I'll fix this on your behalf to save us another iteration.

2022-12-15 09:50 UTC, angelgolfer-ms commented on changelog/Microsoft.M365.Defender.json
> +					"Id": "de54d2e0-f6ea-485c-9b8d-85f7b484cddb",
Lines 436-441:
This changelist record should be documented as a change to the property, rather than a change to the parent resource. See a similar example, example 11, in this CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

2022-12-15 09:54 UTC, angelgolfer-ms commented on changelog/Microsoft.M365.Defender.json
> +          "Id": "de26487d-676f-4dd1-b4b3-55d39ee37879",
Lines 444-449:
This changelist record should be documented as an addition of a property. See Example 2 of the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

I'll fix this to save us an iteration.

2022-12-15 10:08 UTC, merged