[CloudPC]add new property domainJoinConfiguration list for policy
microsoftgraph/microsoft-graph-docs pull request #19364
Opened 2022-11-24 05:38 UTC by Guoan-Tang

2022-11-24 05:40 UTC, opbld31 commented
Learn Build status updates of commit _[7f08523](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f085239567979dc54919aac13d7c32200568716)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/ancs/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-19364) (graph-rest-beta) | [Details](#user-content-1222137994597eed72f1e4a0648d90c2-41f9d7f3)
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/ancs/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-19364) (graph-rest-beta) | [Details](#user-content-0a9fdcfab19a29e8fcd334d07d810ac9-41f9d7f3)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/ancs/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-19364) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/ancs/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-19364) (graph-rest-beta) |

<a id="1222137994597eed72f1e4a0648d90c2-41f9d7f3"></a>
### [api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/ancs/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md)
 - **Line 52, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="0a9fdcfab19a29e8fcd334d07d810ac9-41f9d7f3"></a>
### [api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/guoan/ancs/api-reference/beta/resources/cloudpcprovisioningpolicy.md)
 - **Line 31, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211240538176269-19364/BuildReport?accessString=83df3822386382e3a6d7fe95149735bbd6d97d9be45cfe15959c6a0af03e9f76).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-03 15:06 UTC, Danielabom commented
Reached out to the author to get info.

2023-01-04 16:16 UTC, Danielabom commented
The author will reach out as soon as this PR is ready for review.

2023-01-19 17:18 UTC, Danielabom commented
Team, please give me a heads-up as soon as this PR is ready for review. Thanks!

2023-01-31 11:32 UTC, AshleyYangSZ requested changes
Please add changelog asap

2023-02-03 07:41 UTC, Guoan-Tang commented
RoadMap
[Feature 16396](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/16396): [DEVICES AND APPS][CLOUD PC] Add new property domainJoinConfiguration list for policy

2023-02-06 14:27 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the `domainJoinConfigurations` member to the [cloudPcProvisioningPolicy](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view
```suggestion
                    "Description": "Added the **domainJoinConfigurations** property to the [cloudPcProvisioningPolicy](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta) resource",
```

2023-02-06 14:42 UTC, Danielabom approved these changes
Thank you for working on this PR @Guoan-Tang. I made a small change in the changelog. PR approved.

2023-02-28 03:47 UTC, Lauragra commented on api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
> +|domainJoinConfigurations|Collection([microsoft.graph.cloudPcDomainJoinConfiguration](../resources/cloudpcdomainjoinconfiguration.md))|Specifies a list ordered by priority on how Cloud PCs will join
Please remove the extra columns in this line with the three Nos. What are you trying to convey there?

2023-02-28 03:49 UTC, Lauragra commented on api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
> +|imageId|String|The ID of the OS image you want to provision on Cloud PCs. The format for a gallery type image is: {publisher_offer_sku}. Supported values for each of the parameters are as follows:<u
Please spell out OS as operating system. Also, please style the values with tic marks (`) so that they are formatted as inline code. For the sku, are those all one value or multiple different sku values?

2023-02-28 03:50 UTC, Lauragra commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|domainJoinConfigurations|Collection(microsoft.graph.cloudPcDomainJoinConfiguration)|Specifies a list ordered by priority on how Cloud PCs will join Azure AD.|No|No|No|
Please remove the No columns here.

2023-03-01 17:17 UTC, Danielabom commented
Contacted author and asked him to please review Laura's final comments.

2023-03-16 05:01 UTC, Guoan-Tang commented on api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
> +|imageId|String|The ID of the OS image you want to provision on Cloud PCs. The format for a gallery type image is: {publisher_offer_sku}. Supported values for each of the parameters are as follows:<u
these are multiple different sku values

2023-03-22 14:04 UTC, Danielabom approved these changes
Thank you for working on this PR, @Guoan-Tang. Changes approved.

2023-04-13 00:28 UTC, Danielabom commented
@Guoan-Tang, please add the "ready to merge" label as soon as you are ready.

2023-05-09 03:31 UTC, merged