Python SDK updates
microsoftgraph/microsoft-graph-docs pull request #19409
Opened 2022-11-28 21:54 UTC by isvargasmsft

https://github.com/microsoftgraph/msgraph-sdk-python

2022-11-28 21:57 UTC, opbld30 commented
Learn Build status updates of commit _[ebe6653](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebe66534f871a71a380bebc2e9398dcf8e4b4826)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-c6d38e12)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |

<a id="7d5aa985017c36a056202b2f70e4cb46-c6d38e12"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211282154320685-19409/BuildReport?accessString=6f67cf6cab5e4bd8887f7ce16a764d0c31d18663ec6320fa914ce3c177f8e9e9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 16:02 UTC, opbld32 commented
Learn Build status updates of commit _[ec6f514](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec6f514d4bbaddec99415fb4d6c619d948f7f87f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-b61886a2)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-b61886a2)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-b61886a2"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 782, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 884, Column 47**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /python/api/azure-identity/azure.identity.aio?view=azure-python`````
 - **Line 884, Column 158**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /python/api/azure-identity/azure.identity.aio.environmentcredential?view=azure-python`````

<a id="7d5aa985017c36a056202b2f70e4cb46-b61886a2"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211301600009704-19409/BuildReport?accessString=95256e2815e94af952d715f8867fc67e4720fb4f2359459cb6c887f62c3bc53e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 16:31 UTC, opbld32 commented
Learn Build status updates of commit _[5312675](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5312675f9d6cf4160fc26f6ba9b98848201d5bf9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-ef62add7)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-ef62add7)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-ef62add7"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 782, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7d5aa985017c36a056202b2f70e4cb46-ef62add7"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211301629489538-19409/BuildReport?accessString=d87a93fd973133aeb3188a29e56f10807e839b2e21e8ed983fa6ad1c1972bfe0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 17:34 UTC, opbld31 commented
Learn Build status updates of commit _[af67c05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af67c0570475453be6ae8f1af3104c1a26e9eb95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-84c94a28)
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) | [Details](#user-content-878283baecec6f81169f978b83dce1c5-84c94a28)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-84c94a28)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-list.md) | :white_check_mark:Succeeded | |
[concepts/sdks/includes/snippets/python/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-84c94a28"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 385, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 488, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 619, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 687, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 811, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="878283baecec6f81169f978b83dce1c5-84c94a28"></a>
### [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md)
 - **Line 91, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 121, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 149, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 177, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 205, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 233, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 261, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 289, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7d5aa985017c36a056202b2f70e4cb46-84c94a28"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211301731356627-19409/BuildReport?accessString=be785cd535c4029db7b986954394e519d5d896824bee9ce77aa6768d45aadead).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken [...]

2022-11-30 17:59 UTC, opbld32 commented
Learn Build status updates of commit _[7dc4a49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dc4a495aaeab2fcebf9676a595d2e8612a80245)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-d55c1a7c)
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) | [Details](#user-content-878283baecec6f81169f978b83dce1c5-d55c1a7c)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-d55c1a7c)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-index.md) | :white_check_mark:Succeeded | |
[concepts/sdks/includes/snippets/python/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-d55c1a7c"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 385, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 488, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 619, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 687, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 811, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="878283baecec6f81169f978b83dce1c5-d55c1a7c"></a>
### [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md)
 - **Line 127, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 155, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 183, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 211, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 239, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 267, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 295, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7d5aa985017c36a056202b2f70e4cb46-d55c1a7c"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211301757112086-19409/BuildReport?accessString=afa2837352583e6f8a9e751a719c0f9b7ffd904270adbb5d4b0a8bf7a009c505).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your Git [...]

2022-11-30 21:14 UTC, opbld30 commented
Learn Build status updates of commit _[045fc93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/045fc9386ad882e3c924ef2dc280e4df8d9921b6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-908fc79b)
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) | [Details](#user-content-878283baecec6f81169f978b83dce1c5-908fc79b)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-908fc79b)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-908fc79b"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 385, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 488, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 619, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 687, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 811, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="878283baecec6f81169f978b83dce1c5-908fc79b"></a>
### [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md)
 - **Line 297, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 325, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7d5aa985017c36a056202b2f70e4cb46-908fc79b"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/20221130210349980 [...]

2022-12-01 21:47 UTC, opbld32 commented
Learn Build status updates of commit _[e719f1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e719f1e1256191447e9f38c85e186ec6d043dab3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-46c5135a)
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) | [Details](#user-content-878283baecec6f81169f978b83dce1c5-46c5135a)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-46c5135a)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-46c5135a"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 385, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 488, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 619, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 687, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 811, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="878283baecec6f81169f978b83dce1c5-46c5135a"></a>
### [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md)
 - **Line 297, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 325, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7d5aa985017c36a056202b2f70e4cb46-46c5135a"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/20221201214532601 [...]

2022-12-01 22:04 UTC, opbld34 commented
Learn Build status updates of commit _[df37386](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df37386918f6a3eea7e56a6395b9ca6cacaea002)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-2d8c6fc6)
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) | [Details](#user-content-878283baecec6f81169f978b83dce1c5-2d8c6fc6)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-2d8c6fc6)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-2d8c6fc6"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 507, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 638, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 706, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 830, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="878283baecec6f81169f978b83dce1c5-2d8c6fc6"></a>
### [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md)
 - **Line 297, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 325, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7d5aa985017c36a056202b2f70e4cb46-2d8c6fc6"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212012201475123-19409/BuildReport?accessString=d8fdff9a1ef46640efa1f69afa49ede78e5f605b12ee28a3355b62a4b064dd6e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHu [...]

2022-12-02 14:03 UTC, opbld34 commented
Learn Build status updates of commit _[a6681f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6681f91e1851e7165f7c5d2e8e2010558ba5ea2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) | [Details](#user-content-bc201e57710acc174780333454d7410d-4f196483)
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) | [Details](#user-content-878283baecec6f81169f978b83dce1c5-4f196483)
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-19409) | [Details](#user-content-7d5aa985017c36a056202b2f70e4cb46-4f196483)
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/includes/snippets/python/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/includes/snippets/python/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-19409) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-19409) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-19409) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-19409) |

<a id="bc201e57710acc174780333454d7410d-4f196483"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/choose-authentication-providers.md)
 - **Line 509, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 640, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 708, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 832, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="878283baecec6f81169f978b83dce1c5-4f196483"></a>
### [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/create-requests.md)
 - **Line 297, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 325, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="7d5aa985017c36a056202b2f70e4cb46-4f196483"></a>
### [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-pythonSDKupdates/concepts/sdks/customize-client.md)
 - **Line 185, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021359334201-19409/BuildReport?accessString=e48012ba67ba1aa855fc3bc8f9c0c7c7973abd5b7896bfe96d6106ceadd0ec45).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHu [...]

2023-01-26 10:32 UTC, samwelkanda commented on concepts/sdks/choose-authentication-providers.md
> +You can choose from any of the classes listed [here](/python/api/azure-identity/azure.identity.aio?view=azure-python&preserve-view=true). In the following example we are using [EnvironmentCredential]
Users might interpret that we only support async credentials since this only links to the `azure_identity.aio` package. Maybe [this](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity?view=azure-python) would work betters since we support both `sync` and `async` credentials.

2023-01-26 10:35 UTC, samwelkanda commented on concepts/sdks/choose-authentication-providers.md
> +You can choose from any of the classes listed [here](/python/api/azure-identity/azure.identity.aio?view=azure-python&preserve-view=true). In the following example we are using [EnvironmentCredential]
> In the following example we are using [EnvironmentCredential](/python/api/azure-identity/azure.identity.aio.environmentcredential

The example actually uses `AuthorizationCodeCredential`

2023-01-26 10:53 UTC, samwelkanda requested changes

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/choose-authentication-providers.md
> +You can choose from any of the classes listed [here](/python/api/azure-identity/azure.identity.aio?view=azure-python&preserve-view=true). In the following example we are using [EnvironmentCredential]
Same issues as above

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-headers.md
> +events = asyncio.run(client.me()
```suggestion
events = asyncio.run(client.me
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-headers.md
> +                     .events()
```suggestion
                     .events
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-index.md
> +message = asyncio.run(client.me()
```suggestion
message = asyncio.run(client.me
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-list.md
> +messages = asyncio.run(client.me()
```suggestion
messages = asyncio.run(client.me
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-list.md
> +                       .messages()
```suggestion
                       .messages
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-queryparams.md
> +calendar = asyncio.run(client.me()
```suggestion
calendar = asyncio.run(client.me
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-queryparams.md
> +                       .calendar_view()
```suggestion
                       .calendar_view
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-read.md
> +user = asyncio.run(client.me().get())
```suggestion
user = asyncio.run(client.me.get())
```

2023-01-26 10:53 UTC, samwelkanda commented on concepts/sdks/includes/snippets/python/create-requests-select.md
> +user = asyncio.run(client.me()
```suggestion
user = asyncio.run(client.me
```

2023-01-27 19:03 UTC, jasonjoh approved these changes

2023-01-30 10:12 UTC, samwelkanda commented on concepts/sdks/choose-authentication-providers.md
> +Not applicable.
```suggestion
```python
from azure.identity import DeviceCodeCredential
from kiota_authentication_azure.azure_identity_authentication_provider import AzureIdentityAuthenticationProvider

# Create authentication provider object. Used to authenticate request
credential = DeviceCodeCredential(client_id = 'CLIENT_ID')
scopes = ['https://graph.microsoft.com/.default']
auth_provider = AzureIdentityAuthenticationProvider(credential, scopes=scopes)
```
```

2023-01-31 02:49 UTC, merged