[Azure AD] Cross-tenant identity sync policy
microsoftgraph/microsoft-graph-docs pull request #19433
Opened 2022-11-30 20:48 UTC by rolyon

2022-11-30 20:51 UTC, opbld34 commented
Learn Build status updates of commit _[4ebfffa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ebfffa7c92a52c8d2c9427b6e7bd5e2c52c7da5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-d3866278c421e517814db4a6487c6d26-d3e8585f)
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-034e4db6fad5c3dbce8f4e8fc47c4111-d3e8585f)
[api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-20a6372efa8e79aaf1b1fc5b48ba98d3-d3e8585f)
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-c6eb28b32cf8d64c92bdb41c054066e5-d3e8585f)
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-785de6f5aa9adc7e15230a38d4a576f8-d3e8585f)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |

<a id="d3866278c421e517814db4a6487c6d26-d3e8585f"></a>
### [api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create crossTenantIdentitySyncPolicyPartner - Microsoft Graph beta' is duplicated in: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(2,8), beta/api/crosstenantidentitysyncpolicy-post-partners.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create crossTenantIdentitySyncPolicyPartner' is duplicated with other articles: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(10,1), beta/api/crosstenantidentitysyncpolicy-post-partners.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Create a new crossTenantIdentitySyncPolicyPartner object.' is duplicated in 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(3,14)', 'beta/api/crosstenantidentitysyncpolicy-post-partners.md(3,14)'.`````

<a id="034e4db6fad5c3dbce8f4e8fc47c4111-d3e8585f"></a>
### [api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md)
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="20a6372efa8e79aaf1b1fc5b48ba98d3-d3e8585f"></a>
### [api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create crossTenantIdentitySyncPolicyPartner - Microsoft Graph beta' is duplicated in: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(2,8), beta/api/crosstenantidentitysyncpolicy-post-partners.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create crossTenantIdentitySyncPolicyPartner' is duplicated with other articles: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(10,1), beta/api/crosstenantidentitysyncpolicy-post-partners.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 3 [...]

2022-12-01 23:55 UTC, opbld33 commented
Learn Build status updates of commit _[bf3dbc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf3dbc7bbf3ab672b962564f3af909f325600a69)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-d3866278c421e517814db4a6487c6d26-f6204625)
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-034e4db6fad5c3dbce8f4e8fc47c4111-f6204625)
[api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-20a6372efa8e79aaf1b1fc5b48ba98d3-f6204625)
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-c6eb28b32cf8d64c92bdb41c054066e5-f6204625)
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-785de6f5aa9adc7e15230a38d4a576f8-f6204625)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |

<a id="d3866278c421e517814db4a6487c6d26-f6204625"></a>
### [api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create crossTenantIdentitySyncPolicyPartner - Microsoft Graph beta' is duplicated in: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(2,8), beta/api/crosstenantidentitysyncpolicy-post-partners.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create crossTenantIdentitySyncPolicyPartner' is duplicated with other articles: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(10,1), beta/api/crosstenantidentitysyncpolicy-post-partners.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Create a new crossTenantIdentitySyncPolicyPartner object.' is duplicated in 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(3,14)', 'beta/api/crosstenantidentitysyncpolicy-post-partners.md(3,14)'.`````

<a id="034e4db6fad5c3dbce8f4e8fc47c4111-f6204625"></a>
### [api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md)
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="20a6372efa8e79aaf1b1fc5b48ba98d3-f6204625"></a>
### [api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create crossTenantIdentitySyncPolicyPartner - Microsoft Graph beta' is duplicated in: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(2,8), beta/api/crosstenantidentitysyncpolicy-post-partners.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create crossTenantIdentitySyncPolicyPartner' is duplicated w [...]

2022-12-02 00:17 UTC, opbld32 commented
Learn Build status updates of commit _[14e2239](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14e223959962952d8da435c909eb4729ad5ad89c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-d3866278c421e517814db4a6487c6d26-1af2e4e4)
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-034e4db6fad5c3dbce8f4e8fc47c4111-1af2e4e4)
[api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-20a6372efa8e79aaf1b1fc5b48ba98d3-1af2e4e4)
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-c6eb28b32cf8d64c92bdb41c054066e5-1af2e4e4)
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-785de6f5aa9adc7e15230a38d4a576f8-1af2e4e4)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |

<a id="d3866278c421e517814db4a6487c6d26-1af2e4e4"></a>
### [api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create crossTenantIdentitySyncPolicyPartner - Microsoft Graph beta' is duplicated in: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(2,8), beta/api/crosstenantidentitysyncpolicy-post-partners.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create crossTenantIdentitySyncPolicyPartner' is duplicated with other articles: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(10,1), beta/api/crosstenantidentitysyncpolicy-post-partners.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Create a new crossTenantIdentitySyncPolicyPartner object.' is duplicated in 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(3,14)', 'beta/api/crosstenantidentitysyncpolicy-post-partners.md(3,14)'.`````

<a id="034e4db6fad5c3dbce8f4e8fc47c4111-1af2e4e4"></a>
### [api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md)
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="20a6372efa8e79aaf1b1fc5b48ba98d3-1af2e4e4"></a>
### [api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicy-post-partners.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create crossTenantIdentitySyncPolicyPartner - Microsoft Graph beta' is duplicated in: 'beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md(2,8), beta/api/crosstenantidentitysyncpolicy-post-partners.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create crossTenantIdentitySyncPolicyPartner' is duplicated w [...]

2022-12-02 00:35 UTC, opbld30 commented
Learn Build status updates of commit _[7f4631d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f4631daf206029a318aa7c719b73ba9ff30ae20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-d3866278c421e517814db4a6487c6d26-f708124e)
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-034e4db6fad5c3dbce8f4e8fc47c4111-f708124e)
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-c6eb28b32cf8d64c92bdb41c054066e5-f708124e)
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) | [Details](#user-content-785de6f5aa9adc7e15230a38d4a576f8-f708124e)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |

<a id="d3866278c421e517814db4a6487c6d26-f708124e"></a>
### [api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md)
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="034e4db6fad5c3dbce8f4e8fc47c4111-f708124e"></a>
### [api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md)
 - **Line 47, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="c6eb28b32cf8d64c92bdb41c054066e5-f708124e"></a>
### [api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/crosstenantidentitysyncpolicypartner.md(3,14)', 'beta/resources/crosstenantusersyncinbound.md(3,14)'.`````

<a id="785de6f5aa9adc7e15230a38d4a576f8-f708124e"></a>
### [api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/crosstenantidentitysyncpolicypartner.md(3,14)', 'beta/resources/crosstenantusersyncinbound.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020033087758-19433/BuildReport?accessString=08dd83e1ebdd720e85c84a6d3c56eb8646e6412c72f41bb8dca205e30201a0b8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href [...]

2022-12-02 00:53 UTC, opbld30 commented
Learn Build status updates of commit _[ef528b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef528b27ad155ddefa489d353171509d3b0e3c1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020051113168-19433/BuildReport?accessString=81709bd5260d3bf471fcb3808dd2109287e148093b2b36506ee964bf0a0ab0ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 01:11 UTC, opbld32 commented
Learn Build status updates of commit _[26d103e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26d103eaf2035461886c3991ad6c5d095e67ec25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020109184453-19433/BuildReport?accessString=50c54791fbc324e62ee0706a185b42224e16d7c1dc3e7c49d399ee5213e57c68).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 19:28 UTC, opbld34 commented
Learn Build status updates of commit _[3a9037c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a9037cf51ba52b3d29d403dab5946e312e4037a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021925440159-19433/BuildReport?accessString=a39ac9f3bbae16b6569221699aab98cd1f8bda284d4fda4bfecdc5c97105d4f7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 20:00 UTC, opbld31 commented
Learn Build status updates of commit _[6a7051c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a7051cce0e7aab4d9f476bef936b93b03bf34d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212021957223414-19433/BuildReport?accessString=648ef2185e670cacd82fd77e2e374272c360a169ff27233242a8e7a67a4886d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 00:06 UTC, opbld34 commented
Learn Build status updates of commit _[059dba0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/059dba014eaccc9489fb46225527c9444d02af04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212050004037934-19433/BuildReport?accessString=1473692b41e0ecc719403afbf9d4bd4c42a746bdef15134ca8e9255644a27a70).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 00:36 UTC, opbld32 commented
Learn Build status updates of commit _[62dac0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62dac0cf47665031ab3832b5c28e31f46bd4820c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212050033453510-19433/BuildReport?accessString=05e97573ed29dbfbf256240c09bc5ac5fdc52d64ace2ad5eac18d220cb6d430d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 00:52 UTC, opbld34 commented
Learn Build status updates of commit _[d6a92d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6a92d4a37d300175cdf55cb5f01c780aa9d4388)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212050050213988-19433/BuildReport?accessString=160d1eecab3a16e63d9187d632eacc9721852e6908e9fe979554252927aaf5d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 18:12 UTC, ArvindHarinder1 commented on api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
> +If you set `isSyncAllowed` to false, any current user synchronization from the source tenant to the target tenant will stop. Also, user objects that already been synchronized will not be cleaned up.
Rather than saying "will not be cleaned up", could we say that there will be no impact to existing B2B users or something along those lines. Basically, framing it in a positive way.

2022-12-05 18:12 UTC, ArvindHarinder1 commented on api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
> +|displayName|String|Display name for the cross-tenant user synchronization policy. Optional.|
We can add that generally this should be the target tenant name.

2022-12-05 21:27 UTC, rolyon commented on api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
> +|displayName|String|Display name for the cross-tenant user synchronization policy. Optional.|
@ArvindHarinder1 I think this should be the "source" tenant name and not the "target" tenant name. Correct?

2022-12-05 21:36 UTC, opbld32 commented
Learn Build status updates of commit _[e9bd0d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9bd0d4ea36176791fb4c70d80141bc0073daecc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212052133344590-19433/BuildReport?accessString=d2f7eb681708c75163b0dd6d8b7009e66dffcd5cb404db72d374f4bece18bc01).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 08:14 UTC, opbld34 commented
Learn Build status updates of commit _[0b6d1a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b6d1a2623f17e320a404cb050ab0d9ff4ec5b71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-get?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantidentitysyncpolicypartner-update?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantidentitysyncpolicypartner?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantusersyncinbound.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/resources/crosstenantusersyncinbound.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantusersyncinbound?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-19433) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-mto-crosstenantidentitysyncpolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212090812171550-19433/BuildReport?accessString=c72bda97e9d44b79e9352dbebf8d8146d47b641783f0ed3feeac4646eb0fde12).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-16 11:24 UTC, FaithOmbongi requested changes
Thank you @rolyon for your work on this PR. I've left review feedback inline + the following comments:
- [Subject to confirming this will be in the new schema] Add the crossTenantIdentitySyncPolicy relationship to the [policyRoot](https://learn.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta) resource.
- Document the **crossTenantIdentitySyncPolicy** entity and its **crossTenantIdentitySyncPolicyPartner** relationship. Indicate it supports $expand.
- Add the **identitySynchronization** relationship to [crossTenantAccessPolicyConfigurationPartner](https://learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta).
- It's possible that crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md file isn't required. See the inline comments.
- Rename crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md to crosstenantaccesspolicyconfigurationpartner-put-identitysynchronization.md.
- Rename crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md to crosstenantidentitysyncpolicypartner-delete.md.
- Update the [XTAP overview](https://learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta) and add references to this sync policy and how it enabled MTO.

2022-12-16 11:24 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
> +|tenantId|String|Tenant identifier for the partner Azure AD organization. Read-only.|
List only updatable properties.
```suggestion
```

2022-12-16 11:24 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
> +If you set `isSyncAllowed` to false, any current user synchronization from the source tenant to the target tenant will stop. There is no impact to existing users that have already been synchronized.
Move this to the property description above.
```suggestion
```

2022-12-16 11:24 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md
> +---
I see the syntax for delete doesn't include $ref, so this file name should be crosstenantidentitysyncpolicypartner-delete.md as per the file naming guidelines.

2022-12-16 11:24 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md
> +
Add RBAC

2022-12-16 11:24 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
> +If a configuration includes a [user synchronization policy](../resources/crosstenantidentitysyncpolicypartner.md), you must first [delete the user synchronization policy](./crosstenantaccesspolicycon
Move this to the description in Line 16.
```suggestion
If a configuration includes a [user synchronization policy](../resources/crosstenantidentitysyncpolicypartner.md), you must first [delete the user synchronization policy](./crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md) before you can delete the partner-specific configuration.
```

2022-12-16 11:24 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
> +|[Delete crossTenantIdentitySyncPolicyPartner](../api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md)|None|Delete the user synchronization policy for a partner-specific
From my comments in the respective files:

+ LIST isn't supported
+ Rename Create file to *-put-*; Update the title.
+ Rename DELETE

2022-12-16 11:24 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
When you fix the add the missing relationships and files, add their records to the changelog as well.

2022-12-16 20:40 UTC, rolyon commented on api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
> +If you set `isSyncAllowed` to false, any current user synchronization from the source tenant to the target tenant will stop. Also, user objects that already been synchronized will not be cleaned up.
Changed to the following:
There is no impact to existing users that have already been synchronized.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/e9bd0d4ea36176791fb4c70d80141bc0073daecc

2022-12-16 20:41 UTC, rolyon commented on api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
> +|displayName|String|Display name for the cross-tenant user synchronization policy. Optional.|
Added the following:
Generally, this should be the tenant name of the partner Azure AD organization.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/e9bd0d4ea36176791fb4c70d80141bc0073daecc

2022-12-17 01:25 UTC, rolyon commented on api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
> +Defines the user synchronization policy for partner configurations within cross-tenant access settings.
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/3c45b141d03df4e0515cb44d9f572830eb964b38

2022-12-17 01:25 UTC, rolyon commented on api-reference/beta/resources/crosstenantusersyncinbound.md
> +Defines the inbound user synchronization for partner configurations within cross-tenant access settings.
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/3c45b141d03df4e0515cb44d9f572830eb964b38

2022-12-17 01:27 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md
> +---
Deleted List doc
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/af5978cc7f4fa703fa74d3702f450b2acbe4381a

2022-12-17 01:28 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md
> +title: "Create crossTenantIdentitySyncPolicyPartner"
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/24490f14a9638cbb28de22ff3ef9c54e8429e8e2

2022-12-17 01:28 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md
> +# Create crossTenantIdentitySyncPolicyPartner
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/24490f14a9638cbb28de22ff3ef9c54e8429e8e2

2022-12-17 01:30 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md
> +
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/a9da2ec49ade3818a0ebac9d7f20b6c86d5d4501

2022-12-17 01:30 UTC, rolyon commented on api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md
> +
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/a9da2ec49ade3818a0ebac9d7f20b6c86d5d4501

2022-12-17 01:31 UTC, rolyon commented on api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
> +
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/a9da2ec49ade3818a0ebac9d7f20b6c86d5d4501

2022-12-17 01:31 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md
> +
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/a9da2ec49ade3818a0ebac9d7f20b6c86d5d4501

2022-12-17 01:33 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md
> +---
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/3e0a93e5b1203fb6d0611feb22629a297d91bcc7

2022-12-17 01:33 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md
> +---
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/3e0a93e5b1203fb6d0611feb22629a297d91bcc7

2022-12-17 01:34 UTC, rolyon commented on api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/630c822aafb8b2d5db3a5bd3fad5941403d73f6f

2022-12-17 01:35 UTC, rolyon commented on api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
> +|[Delete crossTenantIdentitySyncPolicyPartner](../api/crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md)|None|Delete the user synchronization policy for a partner-specific
See commits
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/af5978cc7f4fa703fa74d3702f450b2acbe4381a
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/3e0a93e5b1203fb6d0611feb22629a297d91bcc7

2022-12-17 01:36 UTC, rolyon commented on changelog/Microsoft.DirectoryServices.json
> +        }
See commit
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/c100db7c40b113c58e5ea46d60247e07efef40d9

2022-12-17 01:59 UTC, rolyon commented
Hi @FaithOmbongi - See responses to your comments.

[Subject to confirming this will be in the new schema] Add the crossTenantIdentitySyncPolicy relationship to the [policyRoot](https://learn.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta) resource.
Robert - crossTenantIdentitySyncPolicy is part of deprecated API that we dont want to include.

Document the crossTenantIdentitySyncPolicy entity and its crossTenantIdentitySyncPolicyPartner relationship. Indicate it supports $expand.
Robert - We don't want to include crossTenantIdentitySyncPolicy. 

Add the identitySynchronization relationship to [crossTenantAccessPolicyConfigurationPartner](https://learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta).
Robert - Added relationship
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/c100db7c40b113c58e5ea46d60247e07efef40d9

It's possible that crosstenantaccesspolicyconfigurationpartner-list-identitysynchronization.md file isn't required. See the inline comments.
Robert - Deleted List partners for user sync policy and updated List partners for cross-tenant access policy
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/af5978cc7f4fa703fa74d3702f450b2acbe4381a

Rename crosstenantaccesspolicyconfigurationpartner-post-identitysynchronization.md to crosstenantaccesspolicyconfigurationpartner-put-identitysynchronization.md.
Rename crosstenantaccesspolicyconfigurationpartner-delete-identitysynchronization.md to crosstenantidentitysyncpolicypartner-delete.md.
Robert - Renamed Create and Delete files
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/3e0a93e5b1203fb6d0611feb22629a297d91bcc7

Update the [XTAP overview](https://learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta) and add references to this sync policy and how it enabled MTO.
Robert - Added cross-tenant sync section to settings overview
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/b130c891bcadcac7c286e5a5ba7319bfe41d04f6

2023-01-12 18:42 UTC, FaithOmbongi commented
Added to my re-review queue.

2023-01-13 08:09 UTC, FaithOmbongi approved these changes
Hi @rolyon - Looks good to go. Just three minor changes prior to merge.

Approved.

2023-01-13 08:09 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
> +If a configuration includes a [user synchronization policy](../resources/crosstenantidentitysyncpolicypartner.md), you must first [delete the user synchronization policy](./crosstenantidentitysyncpol
Append this to Line 16 where it'll be more visible.

2023-01-13 08:09 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +You can enable cross-tenant synchronization to synchronize users from a partner tenant.  Cross-tenant synchronization is one-way synchronization service in Azure AD that automates creating, updating,
nit
```suggestion
You can enable cross-tenant synchronization to synchronize users from a partner tenant. Cross-tenant synchronization is a one-way synchronization service in Azure AD that automates creating, updating, and deleting B2B collaboration users across tenants in an organization. You create a user synchronization policy to streamline collaboration between users in multi-tenant organizations. Partner user synchronization settings are defined using the [crossTenantIdentitySyncPolicyPartner](../resources/crosstenantidentitysyncpolicypartner.md) resource type.
```

2023-01-14 21:31 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
> +If a configuration includes a [user synchronization policy](../resources/crosstenantidentitysyncpolicypartner.md), you must first [delete the user synchronization policy](./crosstenantidentitysyncpol
Added text to line 16
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/bf9e2e7880bf4991222f508c516c25d7a0648b41

2023-01-24 02:43 UTC, Lauragra commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
> +Get a list of all partner configurations within a cross-tenant access policy. List the user synchronization policy for all partner configurations.
A summary with two sentences like this makes it a little unclear as to what this API does. Would this suggested revision for the second sentence work:

You can also use the `expand` parameter with this API to list the user synchronization policies for all partner configurations.

2023-01-24 03:04 UTC, rolyon commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
> +Get a list of all partner configurations within a cross-tenant access policy. List the user synchronization policy for all partner configurations.
See the following update
https://github.com/microsoftgraph/microsoft-graph-docs/pull/19433/commits/bcc512417e59f124e6a85962859af4cbc6f2e009

2023-01-24 03:24 UTC, rolyon commented
Hi @Lauragra 
The broken changelog link is not in this pull request, but it looks okay to me:
changelog/Microsoft.DirectoryServices.json: Line(s) 26

Here is the link it references:
https://learn.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta
Here is the link in main:
https://review.learn.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta&branch=main

Maybe a publish delay?
thanks

2023-01-24 03:27 UTC, Lauragra commented
> Hi @Lauragra The broken changelog link is not in this pull request, but it looks okay to me: changelog/Microsoft.DirectoryServices.json: Line(s) 26
> 
> Here is the link it references: https://learn.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta Here is the link in main: https://review.learn.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta&branch=main
> 
> Maybe a publish delay? thanks

That's interesting, that file isn't on the live site. I kept the reference in the entry but removed the link. I think if we get a good build we can merge. FYI, we have a contractor helping us clean up some broken links in the changelog files. Thanks!

2023-01-24 03:32 UTC, rolyon commented
Hi @Lauragra 
Okay, thanks for the information. It would be great, if we can merge this pull request this evening. Engineering has already deployed this feature earlier today.
thanks

2023-01-24 03:41 UTC, merged

2023-01-24 03:43 UTC, rolyon commented
thanks!