Added "getSharedUseLicenseUsageReport" API to and updated "cloudPcRep…
microsoftgraph/microsoft-graph-docs pull request #19458
Opened 2022-12-02 04:25 UTC by rbayetov

Added "getSharedUseLicenseUsageReport" API to and updated "cloudPcReportName" enum. +changelog

2022-12-02 04:29 UTC, opbld33 commented
Learn Build status updates of commit _[f0ed433](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0ed43303041eb53339b8f1f7ce8fbd874fec0b6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) | [Details](#user-content-98d093c5f0e28ccb56cf49699ee5a31d-f54f9634)
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="98d093c5f0e28ccb56cf49699ee5a31d-f54f9634"></a>
### [api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Rustem Bayetov (rbayetov)' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020426007238-19458/BuildReport?accessString=e55a82295c3ea0f08b1e68439a375819ad150cdcf71b4d46d1038bd4757ea957).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 04:37 UTC, opbld33 commented
Learn Build status updates of commit _[bce26c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bce26c28482b02ace2c2c9298b476d9c3fae9ebe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020434517285-19458/BuildReport?accessString=948defcbe54cb8ee1b60299e114fbaeb06d68e8e3842db35e35683cd5e3af025).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 06:45 UTC, opbld31 commented
Learn Build status updates of commit _[8bb413b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bb413b074e3e8aaedf4d3a9d335cde09070f7c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212020642584033-19458/BuildReport?accessString=35c339ec3025fce683d1606236833b816df9c2dc01e046515e46e605c6b21929).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-04 22:09 UTC, opbld31 commented
Learn Build status updates of commit _[4a706bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a706bb948e0be97a6db60c03ac33bf3d9e1640c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212042207466162-19458/BuildReport?accessString=6ef105e1c6d78f53bcfd0d635e2214f9c58cdd27076a76fd57f129e30e3cab2f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 03:03 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md
> +# [HTTP](#tab/http)
Please remove this line.

2022-12-05 03:05 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md
> +# [C#](#tab/csharp)
You don't need to include C#, JavaScript, Java, Go, PowerShell, PHP part since once this PR gets merged, the tool will automatically generate these scripts for you. So please remove this part.

2022-12-05 03:07 UTC, RuiHou105 commented
As you added a new API `getSharedUseLicenseUsageReport`, please also update the `toc.yml `file to include this API. 
![image](https://user-images.githubusercontent.com/77313233/205540882-61b1342d-e089-4cb7-be56-3a01e47fe7f1.png)

2022-12-05 03:12 UTC, RuiHou105 requested changes
@rbayetov 
1.Please help resolve all comments.
2.Please create a roadmap workitem and attach the work item number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If you don't have access, please do this firstly 
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-12-05 15:37 UTC, opbld32 commented
Learn Build status updates of commit _[ef92f05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef92f05a1bebe34c5b25040374ab35eabecca99a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212051535016213-19458/BuildReport?accessString=216d545ec156a426a14ec0be2c62dcf965451b0523b9ff9d6d44197d2f353220).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-06 20:58 UTC, rbayetov commented
> @rbayetov 1.Please help resolve all comments. 2.Please create a roadmap workitem and attach the work item number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If you don't have access, please do this firstly
> 
> * Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
> * Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

Created Roadmap item: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15843

Thanks Rui

> @rbayetov 1.Please help resolve all comments. 2.Please create a roadmap workitem and attach the work item number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/). If you don't have access, please do this firstly
> 
> * Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
> * Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

Created roadmap item: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/15843
Thanks Rui

2022-12-06 21:01 UTC, opbld30 commented
Learn Build status updates of commit _[ef92f05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef92f05a1bebe34c5b25040374ab35eabecca99a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212062058575461-19458/BuildReport?accessString=306e307bf070782acd6364512688a1a1718d00ce1238d77b7e9ed0178eb437fb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 09:32 UTC, RuiHou105 approved these changes

2022-12-09 22:25 UTC, opbld30 commented
Learn Build status updates of commit _[e7fd0b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7fd0b969e84fe5fa6ebed200abea2562c0ffaca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcexportjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/resources/cloudpcexportjob.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpcexportjob?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpcreports-getshareduselicenseusagereoport?view=graph-rest-beta&branch=pr-en-us-19458) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rbayetov/cloudpc-sharedUseLicenseReport/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212092222207160-19458/BuildReport?accessString=9caf9d084c93b6e1fd6bdbc7eb7ab030b47657bcb9289de4c5cb2eae60759e5f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-10 02:10 UTC, Lauragra commented
@rbayetov , removing ready to merge until we finish the content review. @Jarbas-MSFT , please take a look at this and when all issues are resolved, you can set ready to merge. Thanks!

2022-12-14 23:57 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md
> +---
According to the api.md file, the sessionId parameter was removed from the getDailyAggregatedRemoteConnectionReports action. However, this parameter isn't listed as a supported parameter [here](https://learn.microsoft.com/en-us/graph/api/cloudpcreports-getdailyaggregatedremoteconnectionreports?view=graph-rest-beta&tabs=http#request-body). Have customers been using the sessionId parameter? Or was it so, that this parameter has never been documentation (was hidden)?

2022-12-14 23:57 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md
> +title: "cloudPcReports: getSharedUseLicenseUsageReport"
Please, fix the name of this file:
- api-reference/beta/api/cloudpcreports-getshareduselicenseusage**reoport**.md

Correct would be:
- api-reference/beta/api/cloudpcreports-getshareduselicenseusage**report**.md

After fixing this filename, please update also the reference link for this method in the TOC (toc.yml).

2022-12-14 23:57 UTC, JarbasHorst commented
Hello @rbayetov, I reviewed your PR and left some comments. Please, take a look when you will have time.

2022-12-19 17:28 UTC, rbayetov commented
> 

Hi Jarbas. Resolved all your comments.

2022-12-19 21:24 UTC, JarbasHorst commented
@Lauragra, @isvargasmsft, this PR is ready for a final review. Please, take a look before final approving it.

2022-12-20 13:33 UTC, isvargasmsft approved these changes

2023-01-02 21:16 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "CreatedDateTime": "2022-12-01T10:36:40.1525853Z",
```suggestion
            "CreatedDateTime": "2023-01-02T10:36:40.1525853Z",
```

2023-01-03 13:43 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "CreatedDateTime": "2023-01-02T10:36:40.1525853Z",
```suggestion
            "CreatedDateTime": "2023-01-03T10:36:40.1525853Z",
```

2023-01-03 13:56 UTC, merged