Python SDK: updates to whats new
microsoftgraph/microsoft-graph-docs pull request #19469
Opened 2022-12-02 20:32 UTC by isvargasmsft

Adding information about the Python SDK release to whats new topic. 

Blog post here: https://devblogs.microsoft.com/microsoft365dev/introducing-the-microsoft-graph-python-sdk-now-available-for-public-preview/

2022-12-13 00:12 UTC, angelgolfer-ms commented on concepts/whats-new-overview.md
> +- Type annotations, both sync and async experiences and HTTP2 support.
Line 25, please use synchronous and asynchronous.

2022-12-13 00:14 UTC, angelgolfer-ms requested changes
The language use looks good. Sorry I'm on my way out to pick up my mom. Please make sure the content side reflects what customers need to know as top takeaway.

2022-12-14 19:02 UTC, angelgolfer-ms commented on concepts/whats-new-overview.md
> +> **Note:** The Microsoft Graph Python SDK is currently in public preview. Don't use this SDK in production environments. For details see [SDKs in preview or GA status](https://learn.microsoft.com/en
Line 31:
Let's not use the '>' styling for the note. The reason is the what's new page contains many new items for other workloads, it's better to maintain a more neutral purview over all the what's new items, not calling one out more than others.

2022-12-14 20:19 UTC, angelgolfer-ms requested changes
One comment, please take a look.

2022-12-14 21:57 UTC, isvargasmsft commented on concepts/whats-new-overview.md
> +**Note**: The Microsoft Graph Python SDK is currently in public preview. Don't use this SDK in production environments. For details see [SDKs in preview or GA status](https://learn.microsoft.com/en-u
```suggestion
**Note**: The Microsoft Graph Python SDK is currently in public preview. Don't use this SDK in production environments. For details see [SDKs in preview or GA status](/graph/sdks/sdks-overview#sdks-in-preview-or-ga-status).
```

2022-12-14 21:58 UTC, angelgolfer-ms approved these changes
Your last fixes for the warnings look good.

2022-12-14 22:05 UTC, angelgolfer-ms commented on concepts/whats-new-overview.md
> +**Note**: The Microsoft Graph Python SDK is currently in public preview. Don't use this SDK in production environments. For details see [SDKs in preview or GA status](/graph/sdks/sdks-overview#sdks-i
Line 27:
FYI I called this out by just bolding "Note" to decrease the distraction from the rest of the non-Python-SDK items on the rest of the page. I also moved the note to this location for 2 reasons: 
- To make sure customers are aware if they're only interested in tools (SDK) they can use in a production app, then they don't have to proceed with the "get started" part. The flip side is true too, if they don't mind trying this out only in non-production apps, then they can follow the call to action ("get started").
- To leave the call to action ("get started") to the last with respect to this item, in this case. Usually we do that as the last thing, as the customer may leave this topic at this point.

2022-12-14 22:11 UTC, merged