USER STORY 154686|USER STORY 154688 customer scenarios
microsoftgraph/microsoft-graph-docs pull request #19534
Opened 2022-12-07 20:04 UTC by AshwaniBansal1

USER STORY 154686|USER STORY 154688 customer scenarios

2022-12-07 20:07 UTC, opbld33 commented
Learn Build status updates of commit _[889567b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/889567bd6a6f64c7d15b7358545cfaeb698b1d65)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment?branch=pr-en-us-19534) | [Details](#user-content-028168ed3ecb38b8596584949b819440-869e411f)
[concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-create-assignment-with-teamsapp-content-for-application?branch=pr-en-us-19534) | [Details](#user-content-ba1c6cb54b1da0e23d801ff1edf8af84-869e411f)

<a id="028168ed3ecb38b8596584949b819440-869e411f"></a>
### [concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Use Microsoft Graph to create assignments with teams app resource using your own application' is duplicated in 'msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md(3,14)', 'msgraph-customer-create-assignment-with-teamsapp-content-for-application.md(3,14)'.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="ba1c6cb54b1da0e23d801ff1edf8af84-869e411f"></a>
### [concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Use Microsoft Graph to create assignments with teams app resource using your own application' is duplicated in 'msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md(3,14)', 'msgraph-customer-create-assignment-with-teamsapp-content-for-application.md(3,14)'.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212072004320750-19534/BuildReport?accessString=cb7ba703a4998c3344b74ea5e1676d89c2c8bab6d01f293795edc75e4929b493).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 16:17 UTC, sharad-sharma-msft requested changes

2022-12-08 16:17 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
> +## Information to download files from sharepoint
sharepoint-> SharePoint

2022-12-08 16:17 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +- [Add app to team](/graph/api/educationclass-list-members): Lists information about adding the app to team.
how is this adding a teams app?

2022-12-08 16:17 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +If user want to create an assignment with a Teams App resource from his own application, this can be done using Graph API.
It is not clear what we are trying to do here.

2022-12-08 16:17 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +title: "Create assignments with teams app from my application"
using your own application

2022-12-08 16:17 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +# Create assignments with teams app from my application
Create assignments with teams app resource does not belong here in this article. This article is about download of SPO resources. We should find a new home for this segment.

2022-12-08 17:07 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +Use [Eduducation teams app resource](/graph/api/resources/educationteamsappresource) to create and share assignments with embedded Teams applications.
the sample in that page is showing how to do that, probably Ashwani can clarify it after the link.
Something like: 

"Use the [create teams app resource](/api/educationassignment-post-resources#example-7-create-an-educationteamsappresource) endpoint to create and load the resource into an assignment. You will need to provide an [educationResource](/graph/api/resources/educationteamsappresource) for the request body.

2022-12-08 20:38 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +- [Add app to team](/graph/api/educationclass-list-members): Lists information about adding the app to team.
updated

2022-12-08 20:40 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +# Create assignments with teams app from my application
SPO resource is the second file , this is for teams app content

2022-12-08 20:45 UTC, opbld32 commented
Learn Build status updates of commit _[f1128f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1128f5742bd3286a6bd0169200d4da76357fdc4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment?branch=pr-en-us-19534) | [Details](#user-content-028168ed3ecb38b8596584949b819440-e706f45c)
[concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/msgraph-customer-create-assignment-with-teamsapp-content-for-application?branch=pr-en-us-19534) | [Details](#user-content-ba1c6cb54b1da0e23d801ff1edf8af84-e706f45c)

<a id="028168ed3ecb38b8596584949b819440-e706f45c"></a>
### [concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Use Microsoft Graph to create assignments with teams app resource using your own application' is duplicated in 'msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md(3,14)', 'msgraph-customer-create-assignment-with-teamsapp-content-for-application.md(3,14)'.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

<a id="ba1c6cb54b1da0e23d801ff1edf8af84-e706f45c"></a>
### [concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CustomerScenarios_NewItems/concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md)
 - **Line 14, Column 114**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Use Microsoft Graph to create assignments with teams app resource using your own application' is duplicated in 'msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md(3,14)', 'msgraph-customer-create-assignment-with-teamsapp-content-for-application.md(3,14)'.`````
 - **Line 14, Column 114**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/graph/msgraph-onboarding-graphexplorer' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212082043097613-19534/BuildReport?accessString=1caa35f36091a28495f62ed6fb33bd2c1f53689df504b294c3ba0c6fd4850bba).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 20:55 UTC, sharad-sharma-msft requested changes

2022-12-08 20:55 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +Adding Teams app as a resource to your assignments would require the teacher permissions.
Teacher is a role and delegate/application is permission. You may want to be clearer here.

2022-12-08 20:55 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +- [Add app to Teams](/graph/api/team-post-installedapps): Lists information about adding the app to Teams.
nit: how to add

2022-12-08 20:55 UTC, sharad-sharma-msft commented on concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
> +title: "Build a tool to download all resources from a set of assignments"
change to "How to download".

there is no tool in this article yet.

2022-12-08 21:24 UTC, sharad-sharma-msft approved these changes

2023-01-04 23:21 UTC, JarbasHorst commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +- [Add app to Teams](/graph/api/team-post-installedapps): Lists information about how to add the app to Teams.
Please, update the description for this API topic as it doesn't list information, rather, it allows you to install an app to the specified team.

2023-01-04 23:21 UTC, JarbasHorst commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +- [Get installed apps in Teams](/graph/api/team-get-installedapp): Lists information about installed apps.
This link is broken. Please update it.

2023-01-04 23:21 UTC, JarbasHorst commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +If you want to create an assignment and attach a Teams app as a resource from your own application, this can be done using Graph API.
Please, provide one or two sentences to explain why one would want to do the following "Create assignments with adding Teams app as a resource using your own application".

2023-01-04 23:21 UTC, JarbasHorst commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +## Permissions
I would recommend you to restructure this article. First provide the Permissions required and how to install a Teams app as a prerequisite (well, actually, why do I need to install a Teams app; the guidance could be actually only about retrieving the Teams app ID that will be required in the step about creating an app resource), then describe the next steps. I think you can use the following article as a reference: https://learn.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?view=graph-rest-1.0.

2023-01-04 23:21 UTC, JarbasHorst commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +Use the [create teams app resource](/api/educationassignment-post-resources#example-7-create-an-educationteamsappresource) endpoint to create and load the resource into an assignment. You will need t
Please, add graph before "/graph" before "/api".

2023-01-04 23:21 UTC, JarbasHorst commented
Hello @AshwaniBansal1, I reviewed your PR and left some comments. Please, take a look when you will have time.

2023-01-09 20:13 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
> +---
We currently have other PRs being reviewed for similar customer scenarios and the TOC entries will be updated in the separate PR.

2023-01-10 23:15 UTC, JarbasHorst commented on concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
> +description: "Use Microsoft Graph to create assignments with a Teams app resource using your own application."
This description doesn't seem to be related to this concept topic. Please, provide a description that better describes this concept topic.

2023-01-10 23:15 UTC, JarbasHorst commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +title: "Share assignments with embedded Teams applications"
I have renamed this concept topic from "Create assignments with adding Teams app as a resource using your own application" to "Share assignments with embedded Teams applications". Please, let me know if this is not correct.

2023-01-10 23:15 UTC, JarbasHorst commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +Use the following APIs to install the application in a specific Microsoft Teams team:
Why do I need this step in this article? I understand that I need an appId to create an educationAssignmentResource, but why do I need to install this app to a team. Can you please provide more information to this section? For example, it is not clear what app we are talking about here (a specific app or any app).

2023-01-10 23:15 UTC, JarbasHorst commented on concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
> +The education API in Microsoft Graph uses feedback resource folders as a destination for feedback files. You can use the [submission feedback information](/graph/education-upload-feedback-resource-ov
Why do I need this section? The link provided under "submission feedback information" refers to a concept topic but not to an API as described in the sentence. 

Also, what is the value of the "List outcomes" sentence? I see that it helps to retrieve the list of... but why do I need that?

2023-01-10 23:16 UTC, JarbasHorst commented
Hello @AshwaniBansal1, I have reworked both concept topics and I would suggest you to review my changes as they are significant. Also, please take a look at the new comments. Thanks!

2023-01-11 21:20 UTC, AshwaniBansal1 commented on concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
> +The education API in Microsoft Graph uses feedback resource folders as a destination for feedback files. You can use the [submission feedback information](/graph/education-upload-feedback-resource-ov
Removed the word API from the sentence.

Shows the info. required for the educationfeedbackoutcome and educationfeedbackresourceoutcome

2023-01-12 18:06 UTC, cristobal-buenrostro commented on concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
> +Use the following APIs to install the application in a specific Microsoft Teams team:
more detail added about why the step is needed, and the steps is not specific to an app, these steps must be done for the any app that could be required for the team.

2023-01-12 21:18 UTC, JarbasHorst commented
@Lauragra, this PR is ready for a final review.

2023-01-18 02:44 UTC, Lauragra commented on concepts/msgraph-create-assignmentwithteamsapp-content.md
> +# Share assignments with an embedded Teams application
Would a more accurate title for this article be: "Embed a Teams app in an assignment"? The current title implies an action to share an assignment, but the intent of this article is to include or attach an app to an assignment.

2023-01-18 02:45 UTC, Lauragra commented on concepts/msgraph-create-assignmentwithteamsapp-content.md
> +This article describes how to use the Microsoft Graph APIs to create an assignment and attach a Teams app as a resource from your own application to add more functionalities.
This sentence is not completely clear because it refers to both an "app" and an "application". Would this be an accurate revision: "This article describes how to use Microsoft Graph to embed a Teams app in an assignment to add additional functionality."

2023-01-18 02:46 UTC, Lauragra commented on concepts/msgraph-create-assignmentwithteamsapp-content.md
> +description: "Use Microsoft Graph to create assignments with Teams app resource using your own application."
Suggested revision: "Learn how to use Microsoft Graph to embed a Teams app resource in an assignment."

2023-01-18 03:08 UTC, Lauragra commented on concepts/msgraph-customer-scenarios.md
> +- [Share assignments with an embedded Teams application](/graph/msgraph-create-assignmentwithteamsapp-content)
Please update the title here too.

2023-01-18 03:43 UTC, Lauragra commented on concepts/msgraph-tool-to-download-all-resources.md
> +title: "Download all resources from a set of assignments"
Why do we have "tool" in the file name here? This article doesn't mention a tool, it just links to APIs. I suggest we change the file name here to download-resources-from-assignment (and update links).

2023-01-18 17:05 UTC, AshwaniBansal1 commented on concepts/msgraph-create-assignmentwithteamsapp-content.md
> +title: "Share assignments with an embedded Teams application"
changed

2023-01-18 17:06 UTC, AshwaniBansal1 commented on concepts/msgraph-tool-to-download-all-resources.md
> +title: "Download all resources from a set of assignments"
done

2023-01-24 02:48 UTC, merged