Add PIM PAG API documentation in graph beta
microsoftgraph/microsoft-graph-docs pull request #19585
Opened 2022-12-12 23:53 UTC by mandardalvi

2023-01-11 19:56 UTC, rkarim-ms approved these changes

2023-01-16 18:37 UTC, FaithOmbongi requested changes
Thank you @rkarim-ms for your work on this PR. 

Because this PR is quite large, I share review feedback in batches. This is Batch 1:

- In the [identitygovernance.md](https://learn.microsoft.com/en-us/graph/api/resources/identitygovernance?view=graph-rest-beta) file, document the **privilegedAccess** relationship and add it to the intro statement.
- "author" metadata - I understand Mandar's best intentions of putting himself down as the author. Because this metadata value helps us establish feature ownership, responsibility/accountability, and POC for customer issues, let Mandar and Ilya agree on who should take ownership of these docs. "Author" isn't just the person who authored the docs/PR, but also the POC for all issues going forward.
- Comment: I've seen we're moving away from the term "privileged access group" (rightfully so because it's very confusing), and instead calling the feature "PIM for groups". Let's avoid the term "privileged access group" in the API reference docs as well.
-

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessroot.md
> +|group|[privilegedAccessGroup](../resources/privilegedaccessgroup.md)|The navigation entity which contains the privileged access group APIs.|
```suggestion
|group|[privilegedAccessGroup](../resources/privilegedaccessgroup.md)|A group that's governed through Privileged Identity Management (PIM) for groups.|
```

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroup.md
> +description: "The navigation entity which contains the privileged access group APIs."
```suggestion
description: "The entry point for all resources related to Privileged Identity Management (PIM) for groups."
```

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroup.md
> +The navigation entity which contains the privileged access group APIs.
Same as what you apply in Line 3

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroup.md
> +|id|String|The unique identifier of the privileged access group. Inherited from [entity](../resources/entity.md).|
NOTE: I've seen we're moving away from the term "privileged access group" (rightfully so because it's very confusing, and instead calling the feature "PIM for groups". Let's avoid the term "privileged access group" in the API reference docs as well.

Technically, this isn't the ID of the group. It is an ID of an object in the request, schedule instance, schedule, etc. Putting down a placeholder suggestion (is it technically sound?) and may circle back.
```suggestion
|id|String|The unique identifier of an object in PIM governance for a group. Inherited from [entity](../resources/entity.md).|
```

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroup.md
> +|[List eligibilitySchedules](../api/privilegedaccessgroup-list-eligibilityschedules.md)|[privilegedAccessGroupEligibilitySchedule](../resources/privilegedaccessgroupeligibilityschedule.md) collection
All these will/should be documented in the respective resource documentation.
```suggestion
None.
```

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroup.md
> +|eligibilitySchedules|[privilegedAccessGroupEligibilitySchedule](../resources/privilegedaccessgroupeligibilityschedule.md) collection|The eligibility schedules to activate a just-in-time privileged a
Hmm - I feel like objects starting with "assignment" represent perpetual assignments. Do you still need to activate your perpetual assignment? If yes, I'll circle back to this after I've inspected the descriptions for your APIs.

I'll also circle back on eligibilities.
```suggestion
|assignmentScheduleInstances|[privilegedAccessGroupAssignmentScheduleInstance](../resources/privilegedaccessgroupassignmentscheduleinstance.md) collection|The instances of assignment schedules to activate a just-in-time privileged access.|
|assignmentScheduleRequests|[privilegedAccessGroupAssignmentScheduleRequest](../resources/privilegedaccessgroupassignmentschedulerequest.md) collection|The schedule requests for operations to create, update, delete, extend, and renew an assignment.|
|assignmentSchedules|[privilegedAccessGroupAssignmentSchedule](../resources/privilegedaccessgroupassignmentschedule.md) collection|The assignment schedules to activate a just-in-time privileged access.|
|eligibilityScheduleInstances|[privilegedAccessGroupEligibilityScheduleInstance](../resources/privilegedaccessgroupeligibilityscheduleinstance.md) collection|The instances of eligibility schedules to activate a just-in-time privileged access.|
|eligibilityScheduleRequests|[privilegedAccessGroupEligibilityScheduleRequest](../resources/privilegedaccessgroupeligibilityschedulerequest.md) collection|The schedule requests for operations to create, update, delete, extend, and renew an eligibility.|
|eligibilitySchedules|[privilegedAccessGroupEligibilitySchedule](../resources/privilegedaccessgroupeligibilityschedule.md) collection|The eligibility schedules to activate a just-in-time privileged access.|
```

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessschedulerequest.md
> +description: "Represents a request for asynchronized operations to create, update, delete, extend, renew, activate, or deactivate a privileged access eligibility or assignment."
Suggestion - because this is just an abstract type and exposes shared objects. It's the downstream objects that are "active" for create, update, delete, etc operations.
```suggestion
description: "An abstract type that exposes properties used to configure access eligibility and assignment in privileged identity management (PIM) governance operations for groups."
```

2023-01-16 18:37 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessschedulerequest.md
> +Inherits from [request](../resources/request.md).
Suggestion - apply what you apply in Line 3 above + Show linkage to downstream objects + maintain the inheritance statement as autogenerated.
```suggestion
An abstract type that exposes properties used to configure access eligibility and assignment in privileged identity management (PIM) governance operations for groups.

This is an abstract type from which the [privilegedAccessGroupAssignmentScheduleRequest](privilegedaccessgroupassignmentschedulerequest.md) and [privilegedAccessGroupEligibilityScheduleRequest](privilegedaccessgroupeligibilityschedulerequest.md) resource types inherit.

Inherits from [request](../resources/request.md).
```

2023-01-17 18:48 UTC, FaithOmbongi requested changes
Hi @rkarim-ms, @mandardalvi - This is Batch 2 of feedback relating to all assignmentSchedule* objects. To refer to Batch 1 relating to feedback on the container objects, start here https://github.com/microsoftgraph/microsoft-graph-docs/pull/19585#pullrequestreview-1250523525

PS: I've lost my review summary twice because Chrome shut down unexpectedly. But please refer to the inline comments which reflect all the feedback. For feedback prefixed with "GLOBAL", it means applying the suggestion across the entire PR.

For all suggestions, I defer to you for technical accuracy.

---------------
**The major thing,** we need an API Overview for PIM for groups. This set of APIs can't stand on it's own without us providing some form of a journey map that we only do through an API Overview. Also, I'd like us to call out how PIM for groups affects the members and owners relationships of a group. And also linkage to other capabilities like change tracking and notifications. Let's sync internally to discuss more.

-----------------------
Batch 3 will be for docs relating to eligibilitySchedule* objects.

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-filterbycurrentuser.md
> +description: "Retrieve the schedules of privileged access to a group relationship assignment for which the signed-in user is the principal."
I've only tweaked the suggestion in the "request" filterByCurrentUser doc.
Suggestion to avoid "signed-in" because there's no sign in in app-scenarios.
```suggestion
description: "In PIM for groups, retrieve the schedules for access assignments for the calling principal to groups that are governed by PIM."
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-filterbycurrentuser.md
> +Retrieve the schedules of privileged access to a group relationship assignment for which the signed-in user is the principal.
Match with Line 3

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-filterbycurrentuser.md
> +|Delegated (work or school account)|PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup|
Proper order

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-filterbycurrentuser.md
> +
Add RBAC

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-filterbycurrentuser.md
> +GET /identityGovernance/privilegedAccess/group/assignmentSchedules/filterByCurrentUser
Same as the request filterByCurrentUser API - I believe the function parameters are mandatory. Therefore, update this URL to add the function parameters.

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-filterbycurrentuser.md
> +GET https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/assignmentSchedules/filterByCurrentUser(on='parameterValue')
Replace "parameterValue" with an actual value - In this cause only `principal` is supported.

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-filterbycurrentuser.md
> +{
Replace with payload that matches the updated request URL above

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessscheduleinstance.md
> +description: "A privilegedAccessScheduleInstance represents the actual provisioned instance of privileged access."
This is not the actual provisioned object type (which is privilegedAccessGroupAssignmentScheduleInstance). This is just an abstract type that exposes shared properties. 
```suggestion
description: "An abstract type that exposes properties relating to the instances of access assignments and eligibilities to groups that are governed by PIM."
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessscheduleinstance.md
> +This is an abstract type.
```suggestion
An abstract type that exposes properties relating to the instances of access assignments and eligibilities to groups that are governed by PIM. This abstract type is inherited by the following derived types:
+ [privilegedAccessGroupAssignmentScheduleInstance](privilegedaccessgroupassignmentscheduleinstance.md)
+ [privilegedAccessGroupEligibilityScheduleInstance](privilegedaccessgroupeligibilityscheduleinstance.md)
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessscheduleinstance.md
> +|startDateTime|DateTimeOffset|When this instance starts. Required.|
```suggestion
|endDateTime|DateTimeOffset|When the schedule instance ends. Required.|
|id|String|The identifier of the access assignment schedule instance. Required. Inherited from [entity](../resources/entity.md).|
|startDateTime|DateTimeOffset|When this instance starts. Required.|
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupassignmentscheduleinstance.md
> +description: "Represents an instance of privilegedAccessGroupAssignmentSchedule."
```suggestion
description: "Represents an instance of a provisioned access assignment in PIM for groups."
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupassignmentscheduleinstance.md
> +Represents an instance of privilegedAccessGroupAssignmentSchedule.
Match with Line 3

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupassignmentscheduleinstance.md
> +|principalId|String|The id of the principal to which the assignment is granted. Required.|
Add inherited properties (and maintain alphabetical order)

```suggestion
|accessId|privilegedAccessGroupRelationships|The identifier of the access assignment relationship to the group. Required. The possible values are: `owner`, `member`,  `unknownFutureValue`.|
|assignmentScheduleId|String|The identifier of the [privilegedAccessGroupAssignmentSchedule](privilegedaccessgroupassignmentschedule.md) from which this instance was created. Required.|
|assignmentType|privilegedAccessGroupAssignmentType|Indicates whether the assignment is granted through activation or direct assignment. Required. The possible values are: `assigned`, `activated`, `unknownFutureValue`.|
|groupId|String|The identifier of the group representing the scope of the access assignment through PIM for groups. Optional.|
|memberType|privilegedAccessGroupMemberType| Indicates whether the assignment is derived from a group assignment. It can further imply whether the caller can manage the assignment schedule. Required. The possible values are: `direct`, `group`, `unknownFutureValue`.|
|principalId|String|The identifier of the principal whose access assignment to the group is managed through PIM for groups. Required.|
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupassignmentscheduleinstance.md
> +|principal|[directoryObject](../resources/directoryobject.md)|Property referencing the assigned principal. Provided so callers can get the principal using $expand at the same time as getting the sche
```suggestion
|activatedUsing|[privilegedAccessGroupEligibilityScheduleInstance](../resources/privilegedaccessgroupeligibilityscheduleinstance.md)|When the request activates an access assignment in PIM for groups, this object represents the eligibility access policy for the group. Otherwise, it is `null`.|
|group|[group](../resources/group.md)|References the group that is the scope of the access assignment through PIM for groups. Supports `$expand`.|
|principal|[directoryObject](../resources/directoryobject.md)|References the principal that's in the scope of this access assignment request through the group that's governed by PIM. Supports `$expand`.|
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupassignmentscheduleinstance.md
> +|[List privilegedAccessGroupEligibilityScheduleInstance](../api/privilegedaccessgroup-list-eligibilityscheduleinstances.md)|[privilegedAccessGroupEligibilityScheduleInstance](../resources/privilegeda
The "eligibility" object will be listed in the eligibility doc
```suggestion
|[List assignmentScheduleInstances](../api/privilegedaccessgroup-list-assignmentscheduleinstances.md)|[privilegedAccessGroupAssignmentScheduleInstance](../resources/privilegedaccessgroupassignmentscheduleinstance.md) collection|Get a list of the [privilegedAccessGroupAssignmentScheduleInstance](../resources/privilegedaccessgroupassignmentscheduleinstance.md) objects and their properties.|
|[Get privilegedAccessGroupAssignmentScheduleInstance](../api/privilegedaccessgroupassignmentscheduleinstance-get.md)|[privilegedAccessGroupAssignmentScheduleInstance](../resources/privilegedaccessgroupassignmentscheduleinstance.md)|Read the properties and relationships of a [privilegedAccessGroupAssignmentScheduleInstance](../resources/privilegedaccessgroupassignmentscheduleinstance.md) object.|
|[filterByCurrentUser](../api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md)|[privilegedAccessGroupAssignmentScheduleInstance](../resources/privilegedaccessgroupassignmentscheduleinstance.md) collection|Return assignment schedule instances for the calling principal.|
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentscheduleinstances.md
> +# List privilegedAccessGroupAssignmentScheduleInstances
```suggestion
title: "List assignmentScheduleInstances"
description: "Get a list of the privilegedAccessGroupAssignmentScheduleInstance objects and their properties."
author: "mandardalvi"
ms.localizationpriority: medium
ms.prod: "governance"
doc_type: apiPageType
---

# List assignmentScheduleInstances
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentscheduleinstances.md
> +|Delegated (work or school account)|PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup|
Proper order

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentscheduleinstances.md
> +
Add RBAC

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentscheduleinstances.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Indicate the supported query parameters

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentscheduleinstances.md
> +    {
Read payload, please

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-get.md
> +|Delegated (work or school account)|PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup|
Proper order

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-get.md
> +
Add RBAC after table

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
GLOBAL: Indicate supported query parameters

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-get.md
> +This method requires either the principalId or groupId filter property.
This can't be true. Single GET requests don't support filter. Filter applies only to collections (LIST). Please confirm.

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-get.md
> +GET https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/assignmentScheduleInstances?$filter=groupId eq '14b9e371-5c2c-4ee5-a4a5-2980060d4f4e'
This request is for a LIST operation, not a GET. Add this syntax as Example 2 in the List doc. Also use $select.

For this doc, have Example 1 as an example using the basic syntax, then Example 2 using $select and $expand, if $expand is supported.

GLOBAL: Real payloads, please!

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md
> +description: "Retrieve the schedule instances of privileged access to a group relationship assignment for the calling principal."
```suggestion
description: "In PIM for groups, retrieve the schedule instances for access assignments for the calling principal to groups that are governed by PIM."
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md
> +Retrieve the schedule instances of privileged access to a group relationship assignment for the calling principal.
Match with Line 3

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md
> +|Delegated (work or school account)|PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup|
Proper order, please.

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md
> +GET /identityGovernance/privilegedAccess/group/assignmentScheduleInstances/filterByCurrentUser
I believe the function parameters are required. Apply that to this URL.

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md
> +The following table shows the parameters that can be used with this function.
```suggestion
The following table shows the parameters that are required with this function.
```

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md
> +GET https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/assignmentScheduleInstances/filterByCurrentUser(on='parameterValue')
Replace 'parameterValue' with 'principal'

2023-01-17 18:48 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentscheduleinstance-filterbycurrentuser.md
> +{
Real payload, please!

2023-01-18 14:25 UTC, FaithOmbongi requested changes
@rkarim-ms, @mandardalvi - This is Batch 3 of feedback against the eligibilitySchedule* docs. For previous batches of feedback, see [Batch 1](https://github.com/microsoftgraph/microsoft-graph-docs/pull/19585#pullrequestreview-1250523525) (container objects) and [Batch 2](https://github.com/microsoftgraph/microsoft-graph-docs/pull/19585#pullrequestreview-1251205670) (assignmentSchedule* docs).

In summary: Most suggestions are consistent with the suggestions against the assignmentSchedule* docs.

- For the suggestions to add real requests and payloads, please run the requests in Graph Explorer and don't copy-paste payloads from the API.md. This will ensure you document exactly what customers will see when they call these APIs. Between API.md preparation and API deployment, we tend to see many changes to the structure of the API.

- GLOBAL: Add all inherited properties for resources that inherit from some base type.
- For LIST operations: Add an Example 2 that uses $select (at a minimum) and optionally, other query parameters like $filter and $expand. For GET, maybe $select and $expand.
- For CREATE/POST operations: Add Example 2 for a different scenario. For example, an example for a principal-initiated action.
- GLOBAL: Permissions tables with PrivilegedAccess.Read.AzureADGroup and PrivilegedAccess.ReadWrite.AzureADGrou - List the permissions in the proper order (least to most privilege).
- GLOBAL: Add RBAC information after each table. That's the admin roles required to readcall the API. For filterByCurrentUser functions, can the principal get their own objects without admin roles? Let's call this out.
- GLOBAL for filterByCurrentUser requests: Please add an "Optional query parameters" section before the "Request headers" section. I believe filterByCurentUser requests should support the same OData query parameters that LIST requests support.
- I've suggested to be intentional instead of saying "access assignment", say "membership or ownership assignment". I'm working under the assumption that PIM for groups involves members and owners object only. If this scope can change to include other group attributes, you can say "access assignment".
- Enums.md; I've suggested deleted a few of the enums because they are duplicates of what already exists in the [enums.md](https://learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0) file. I think this overgeneration may be due to a missing "mastered in" relationship in your CSDL file, because all the affected are mastered in other workload CSDL files like AccessReviews and Outlook CSDL files. You may want to confirm with the Graph onboarding team how to fix the problem.

Next batch of feedback will be against the TOC and the changelog

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityscheduleinstances.md
> +# List privilegedAccessGroupEligibilityScheduleInstances
```suggestion
title: "List eligibilityScheduleInstances"
description: "Get a list of the privilegedAccessGroupEligibilityScheduleInstance objects and their properties."
author: "mandardalvi"
ms.localizationpriority: medium
ms.prod: "governance"
doc_type: apiPageType
---

# List eligibilityScheduleInstances
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityscheduleinstances.md
> +|Delegated (work or school account)|PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup|
Proper order, please

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityscheduleinstances.md
> +
Add RBAC

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityscheduleinstances.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Indicate supported query parameters

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityscheduleinstances.md
> +  "value": [
Real payload, please

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityscheduleinstances.md
> +
Add Example 2 as suggested in previous LIST operations docs

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-get.md
> +|Delegated (work or school account)|PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup|
Proper order

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-get.md
> +
Add RBAC

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Indicate supported query parameters

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-get.md
> +Note: this method requires either the principalId or groupId filter property.
Same comment as before applies to this statement

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-get.md
> +### Example 1: Get all privileged access eligibility schedule instances for a specific privileged access group.
```suggestion
### Example 1: Get all eligibility schedule instances
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-get.md
> +GET https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/eligibilityScheduleInstances?$filter=groupId eq 'd5f0ad2e-6b34-401b-b6da-0c8fc2c5a3fc'
Same comment as before: $filter doesn't work on Single GET and this example is best as Example 2 of the LIST doc.
```suggestion
GET https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/eligibilityScheduleInstances/b88fc7b0-a4ff-45fc-82c4-1d31a807315e
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-get.md
> +
Add Example 2 for using $select and maybe $expand

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +description: "Retrieve the eligibility schedule instances of privileged access to a group relationship assignment for the calling principal."
```suggestion
description: "Return instances of membership and ownership eligibility schedules for the calling principal."
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +Retrieve the eligibility schedule instances of privileged access to a group relationship assignment for the calling principal.
Match Line 3

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +|Delegated (work or school account)|PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.Read.AzureADGroup|
Proper order

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +
RBAC

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +GET /identityGovernance/privilegedAccess/group/eligibilityScheduleInstances/filterByCurrentUser
Add required function parameters to the syntax

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +The following table shows the parameters that can be used with this function.
```suggestion
The following table shows the parameters that must be used with this function.
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +Note: This method requires either the principalId or groupId filter property.
Same comment as in other instances of this statement
```suggestion
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +### Example 1
```suggestion
### Example 1: Retrieve schedule instances for the calling principal
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +  "value": [
Real payload, please

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +### Request
I believe you intended to have an "Example 2 section here? I've put a placeholder title.
```suggestion
### Example 2: Retrieve schedule instances for the calling principal and filter by the group and accessId

#### Request
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +  "name": "privilegedaccessgroupeligibilityscheduleinstancethis.filterbycurrentuser"
Give it a unique name so it doesn't conflict with Example 1 above

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +GET https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/eligibilityScheduleInstances/filterByCurrentUser(on='principal')
This is a duplicate of Example 1's URL. You can change this to use $select, $filter, and $expand

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityscheduleinstance-filterbycurrentuser.md
> +{
Then replace this with the exact payload, please

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +|saturday|
This already exists
```suggestion
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +|afterDuration|
Already exists
```suggestion
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +|relativeYearly|
Exists
```suggestion
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +|unknownFutureValue|
Duplicate
```suggestion
```

2023-01-18 14:25 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +
Duplicate
```suggestion
```

2023-01-18 14:25 UTC, FaithOmbongi requested changes
@rkarim-ms, @mandardalvi - This is Batch 3 of feedback against the eligibilitySchedule* docs. For previous batches of feedback, see [Batch 1](https://github.com/microsoftgraph/microsoft-graph-docs/pull/19585#pullrequestreview-1250523525) (container objects) and [Batch 2](https://github.com/microsoftgraph/microsoft-graph-docs/pull/19585#pullrequestreview-1251205670) (assignmentSchedule* docs).

In summary: Most suggestions are consistent with the suggestions against the assignmentSchedule* docs.

- For the suggestions to add real requests and payloads, please run the requests in Graph Explorer and don't copy-paste payloads from the API.md. This will ensure you document exactly what customers will see when they call these APIs. Between API.md preparation and API deployment, we tend to see many changes to the structure of the API.

- GLOBAL: Add all inherited properties for resources that inherit from some base type.
- For LIST operations: Add an Example 2 that uses $select (at a minimum) and optionally, other query parameters like $filter and $expand. For GET, maybe $select and $expand.
- For CREATE/POST operations: Add Example 2 for a different scenario. For example, an example for a principal-initiated action.
- GLOBAL: Permissions tables with PrivilegedAccess.Read.AzureADGroup and PrivilegedAccess.ReadWrite.AzureADGrou - List the permissions in the proper order (least to most privilege).
- GLOBAL: Add RBAC information after each table. That's the admin roles required to readcall the API. For filterByCurrentUser functions, can the principal get their own objects without admin roles? Let's call this out.
- GLOBAL for filterByCurrentUser requests: Please add an "Optional query parameters" section before the "Request headers" section. I believe filterByCurentUser requests should support the same OData query parameters that LIST requests support.
- I've suggested to be intentional instead of saying "access assignment", say "membership or ownership assignment". I'm working under the assumption that PIM for groups involves members and owners object only. If this scope can change to include other group attributes, you can say "access assignment".
- Enums.md; I've suggested deleted a few of the enums because they are duplicates of what already exists in the [enums.md](https://learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0) file. I think this overgeneration may be due to a missing "mastered in" relationship in your CSDL file, because all the affected are mastered in other workload CSDL files like AccessReviews and Outlook CSDL files. You may want to confirm with the Graph onboarding team how to fix the problem.

Next batch of feedback will be against the TOC and the changelog

2023-01-18 14:29 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +          - name: assignment schedules
GLOBAL in the TOC: Start with caps
```suggestion
          - name: Assignment schedules
```

2023-01-18 14:31 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +    },
Prior to approval, I'll push a commit to clean up the changelog of duplicates, add missing periods, and clean up some mismatches.

2023-02-03 01:25 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroup.md
> +|eligibilitySchedules|[privilegedAccessGroupEligibilitySchedule](../resources/privilegedaccessgroupeligibilityschedule.md) collection|The eligibility schedules to activate a just-in-time privileged a
tagging @mandardalvi for guidance here.

2023-02-03 01:26 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupassignmentschedulerequest.md
> +description: "The schedule requests for operations to create, update, delete, extend, and renew an assignment."
asking @mandardalvi for input on this suggestion.

2023-02-03 01:27 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupassignmentschedulerequest.md
> +|targetSchedule|[privilegedAccessGroupEligibilitySchedule](../resources/privilegedaccessgroupeligibilityschedule.md)|Schedule created by this request.|
requesting guidance from @mandardalvi about this question.

2023-02-03 01:29 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupassignmentschedulerequest.md
> +|targetScheduleId|String|The id of schedule which gets created from request. Optional.|
tagging @mandardalvi on whether there are missing properties from the autogenerated stubs.

2023-02-03 01:33 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md
> +|targetScheduleId|String|The id of schedule which gets created from request. Optional.|
asking @mandardalvi for help in answering these questions.

2023-02-03 01:34 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md
> +In the following request, an assignment schedule request is created to assign an active member access.
tagging @mandardalvi for insight into these questions.

2023-02-03 01:35 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md
> +
asking @mandardalvi to help provide additional 2 examples here.

2023-02-03 01:37 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupassignmentschedulerequest-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
including @mandardalvi for acknowledgment here.

2023-02-03 01:37 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupassignmentschedulerequest-filterbycurrentuser.md
> +description: "Retrieve the requests for privileged access to a group relationship assignment for a particular principal."
asking @mandardalvi for confirmation in this assumption.

2023-02-03 01:46 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessschedule.md
> +description: "A privilegedAccessSchedule represents the schedule of privileged access."
@mandardalvi

2023-02-03 02:14 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupassignmentschedule.md
> +|principalId|String|The id of the principal to which the assignment is granted. Required.|
@mandardalvi

2023-02-03 02:17 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-get.md
> +Note: this method requires either the principalId or groupId filter property.
@mandardalvi

2023-02-06 06:03 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupeligibilityschedulerequest.md
> +|targetScheduleId|String|The id of schedule which gets created from request. Optional.|
@mandardalvi

2023-02-06 06:08 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupassignmentschedule.md
> +|principal|[directoryObject](../resources/directoryobject.md)|Property referencing the assigned principal. Provided so callers can get the principal using $expand at the same time as getting the sche
@mandardalvi

2023-02-06 17:56 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupassignmentschedule.md
> +|principalId|String|The id of the principal to which the assignment is granted. Required.|
@FaithOmbongi

2023-02-13 23:43 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md
> +|targetScheduleId|String|The id of schedule which gets created from request. Optional.|
added responses inline to questions.

2023-02-14 04:10 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupassignmentschedule.md
> +|principalId|String|The id of the principal to which the assignment is granted. Required.|
Added inherited properties and groupId is required (as noted in the docs now.)

2023-03-06 14:05 UTC, FaithOmbongi commented
Close and Reopen to retrigger build and clear up OPS issue.

2023-03-06 16:52 UTC, FaithOmbongi requested changes
Hi @mandardalvi, @rkarim-ms,

I've re-reviewed and this is the summary of feedback. Most are carry-forwards from the previous review. A few, like RBAC-related questions are new.

- [c/f] Please add the **privilegedAccess** relationship to the [identitygovernance.md](https://learn.microsoft.com/en-us/graph/api/resources/identitygovernance?view=graph-rest-beta) file in this PR. Also, add it to the intro statement. Add it to this PR so it doesn't get blocked at a later stage. I hope you managed to resolve the authorization issue. If not, you can use the GitHub UI to make the change.
- [c/f] The TOC changes where we change the current title to "PIM for Azure AD roles" and create a new node "PIM for groups" and next all these docs under this new node.
   - Remember to maintain the proper casing: begin the title with a capital letter
- [c/f]: Update requestschedule.md and ticketinfo.md to indicate PIM for groups as well.
- [c/f]: GLOBAL: For resources that inherit from some other resource, ensure you document the inherited properties as well. 
    - Indicate from where they are inherited from.
    - I see you have the inherited properties in the JSON representation but not the properties table. For example, privilegedaccessschedulerequest.md (for this one, you can copy the inherited properties from privilegedaccessgroupassignmentschedulerequest.md).
    - Remove references to "roles". We should be saying groups instead, no? For example, see the descriptions of action, status, ticketInfo and scheduleInfo properties.
- Where you've expounded on the meaning of the action values, I see we're mentioning "roles" as applies to PIM for Azure AD roles. I believe the context here is PIM for groups instead?
- Housekeeping: In all resource docs where we've commented out the methods tables, please remove the tables. 
- GLOBAL: I've left a suggestion for the RBAC statement. 
   - It should explicitly call out that is applies to "delegated scenarios"
   - The RBAC is assigned to the user in delegated scenarios, not the app
   - If there's a lesser privileged role than the Global Admin, let's not mention the Global Amdin role. We are running a team initiative to reduce overpriv scenarios relating to which RBAC roles we document. Please let me know if you have concerns with the change I've requested.
- Q: RBAC: For READ operations, I see Privileged Role Administrator isn't the only role. There's also Security Reader, Security Operator, Security Administrator, and Global Reader...at least as per [the RBAC permissions doc](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference). Can you verify?
- Q: RBAC: For filterByCurrentUser - does the calling principal still need PRA or one of the above read roles, or can any principal get their instances, schedules, and schedule requests? If any calling principal can get theirs as long as they have the permissions (and don't require RBAC), we need to explicitly call this out.
- QQ: For CREATE operations, do users trying to activate/renew etc their group membership or ownership also need the Privileged Role Administrator role?
- [c/f] A few permissions tables have their permissions listed in the wrong order. Please verify.
- /assignmentSchedules, /assignmentScheduleInstances, /eligibilitySchedules, /eligibilityScheduleInstances APIs:
   - The LIST APIs seem to require groupId and/or principalId when I ran the requests. But this isn't in the documentation. Can you verify and call out where required?
   - The GET API shouldn't require a filter (I think - at least I haven't  seen any instance in Graph). 

- I'd wondered why you mentioned MFA rule in the isValidationOnly property description. Then I checked the IT Admin docs and we have rules in PIM for groups as well.
   - Q: Are these the same [policies as PIM for Azure AD roles](https://learn.microsoft.com/en-us/graph/api/resources/unifiedrolemanagementpolicy?view=graph-rest-1.0)?
   - If not, I don't see a related set of rules APIs.....
- I've pushed a commit to clean up the changelog.

If there are any questions I need to clarify, let's follow up internally.

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-get.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/privilegedAccess/group/assignmentSchedule/$entity",
Response object is for a single GET, but the request is a LIST. Doesn't add up.

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-get.md
> +### Example 2: Retrieve an assignment schedule that's scoped to a principal
This title and the request are for LIST operation; While the payload is for a GET request. Don't match.

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-get.md
> +### Example 1: Retrieve an assignment schedule that's scoped to a group
Correct example in the wrong doc?

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupassignmentscheduleinstance.md
> +|:---|:---|:---|
Add the inherited properties

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentscheduleinstances.md
> +GET /identityGovernance/privilegedAccess/group/assignmentScheduleInstances
Again, got curious and ran the request.
This is the error message

<img width="823" alt="image" src="https://user-images.githubusercontent.com/14026935/223165374-5983d572-6b30-4fdf-891e-b80f7b9ddc7a.png">

Looks like the request _requires_ a filter

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentscheduleinstances.md
> +GET https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/assignmentScheduleInstances
same comment about the valid syntax

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupeligibilityschedulerequest.md
> +|action|String|Represents the type of the operation on the role assignment request. The possible values are: `adminAssign`, `adminUpdate`, `adminRemove`, `selfActivate`, `selfDeactivate`, `adminExten
"roles" vs "groups"

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupeligibilityschedulerequest.md
> +|id|String|The unique identifier for the **privilegedAccessGroupAssignmentScheduleRequest** object. Key, not nullable, Read-only. Inherited from [entity](../resources/entity.md). Supports `$filter` (
```suggestion
|id|String|The unique identifier for the **privilegedAccessGroupEligibilityScheduleRequest** object. Key, not nullable, read-only. Inherited from [entity](../resources/entity.md). Supports `$filter` (`eq`, `ne`).|
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupeligibilityschedulerequest.md
> +|isValidationOnly|Boolean|Determines whether the call is a validation or an actual call. Only set this property if you want to check whether an activation is subject to additional rules like MFA befo
I don't see the APIs relating to rules/policies for PIM for groups. What we have are for PIM for Azure AD roles. Please clarify.

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupeligibilityschedulerequest.md
> +|justification|String|A message provided by users and administrators when create they create the **privilegedAccessGroupAssignmentScheduleRequest** object.|
Oversight or incorrect suggestion?
```suggestion
|justification|String|A message provided by users and administrators when create they create the **privilegedAccessGroupEligibilityScheduleRequest** object.|
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedaccessgroupeligibilityschedulerequest.md
> +|ticketInfo|[ticketInfo](../resources/ticketinfo.md)|Ticket details linked to the role assignment request including details of the ticket number and ticket system.|
roles vs groups

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md
> +### Example 1
```suggestion
### Example 1: Retrieve all the eligibility requests
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md
> +### Example 2
```suggestion
### Example 2: Retrieve specific properties of all eligibility requests
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +The calling app must also have the Global Administrator or Privileged Role Administrator role.
Same comment as the one I left in the assignmentRequest doc: 
1. Remove Global Admin if we can
2. Do I need an RBAC role for "self" actions?
3. Can a group owner run this request without having Privileged Role Administrator

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +|targetScheduleId|String|The identifier of the schedule that's created from the request. Optional.|
action, scheduleInfo, justification are required
targetScheduleId isn't because no one can know it but the system or in a GET/LIST request

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +|groupId|String|The identifier of the group representing the scope of the membership or ownership eligibility through PIM for groups. Optional.|
I believe we said groupId is required?

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +### Example 1: Create an eligible schedule request (Admin adds eligible assignment for user)
```suggestion
### Example 1: An admin creates an eligible group ownership request for a principal
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +### Example 2: Extend eligible request
```suggestion
### Example 2: An admin extends an eligible group membership for a principal
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +### Response
```suggestion
#### Response
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +### Response
```suggestion
#### Response
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-get.md
> +
Same Q about group owner and "self" instances - if they require Privileged Role Administrator

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-get.md
> +### Example 1
```suggestion
### Example 1: Get all eligibility schedule requests
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-get.md
> +### Example 2
```suggestion
### Example 2: Get specific properties of all eligibility schedule requests
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-cancel.md
> +
Q: Can a group owner cancel a request if they don't have Privileged Role Administrator?
Q: Can the principal cancel their own request (where they are indicated in the principalId?)

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-cancel.md
> +POST https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/ligibilityScheduleRequests/f4b57a8c-da56-4ae0-8aef-65c3a043dab4/cancel
```suggestion
POST https://graph.microsoft.com/beta/identityGovernance/privilegedAccess/group/eligibilityScheduleRequests/f4b57a8c-da56-4ae0-8aef-65c3a043dab4/cancel
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedules.md
> +### Example 1
```suggestion
### Example 1: Retrieve all eligibility schedules
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedules.md
> +### Request
```suggestion
#### Request
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedules.md
> +### Response
```suggestion
#### Response
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedules.md
> +### Example 2
```suggestion
### Example 2: Retrieve specific properties of all eligibility schedules
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedules.md
> +### Request
```suggestion
#### Request
```

2023-03-06 16:52 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +          - name: assignment schedule requests
All the previous suggestions apply.
1. Change the existing PIM node to PIM for Azure AD roles; Add a new node called PIM for groups and all these new APIs should be nested under it.
2. Start with a capital letter

2023-03-14 18:52 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md
> +The calling app must also have the Global Administrator or Privileged Role Administrator role.
added references to the include files as discussed on Teams.

2023-03-14 18:52 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupassignmentschedulerequest-get.md
> +The calling app must also have the Global Administrator or Privileged Role Administrator role.
added references to include files as discussed on Teams.

2023-03-14 19:02 UTC, rkarim-ms commented on api-reference/beta/resources/privilegedaccessgroupeligibilityschedulerequest.md
> +|isValidationOnly|Boolean|Determines whether the call is a validation or an actual call. Only set this property if you want to check whether an activation is subject to additional rules like MFA befo
Noted in Teams discussion, will add to a future iteration of docs changes.

2023-03-14 19:04 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +The calling app must also have the Global Administrator or Privileged Role Administrator role.
Added references to include files as discussed on Teams.

2023-03-14 19:08 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-cancel.md
> +
Added references to include files as discussed on Teams.

2023-03-14 19:08 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-get.md
> +
Added references to include files as discussed on Teams.

2023-03-14 19:09 UTC, rkarim-ms commented on api-reference/beta/toc.yml
> +          - name: assignment schedule requests
Addressed, but would appreciate additional review in case nested incorrectly.

2023-03-14 19:34 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
> +|targetScheduleId|String|The identifier of the schedule that's created from the request. Optional.|
Updated

2023-03-14 19:47 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-get.md
> +### Example 1: Retrieve an assignment schedule that's scoped to a group
Requesting additional clarification @FaithOmbongi

2023-03-14 19:47 UTC, rkarim-ms commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-get.md
> +### Example 2: Retrieve an assignment schedule that's scoped to a principal
Moved example to List assignment schedules API page

2023-03-15 13:39 UTC, FaithOmbongi commented on api-reference/beta/api/privilegedaccessgroupassignmentschedule-get.md
> +### Example 1: Retrieve an assignment schedule that's scoped to a group
"scoped to a group" applies for LIST with $filter=groupId
```suggestion
### Example 1: Retrieve an assignment schedule
```

2023-05-06 00:48 UTC, merged