PartnerTenantType on Organization
microsoftgraph/microsoft-graph-docs pull request #19596
Opened 2022-12-13 15:12 UTC by akshukla25

2023-01-04 02:25 UTC, Lauragra commented
@akshukla25 , please follow the Get started steps to set yourself up to be a contributor. This PR needs to go through a content review process; it currently has a validation error.

https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started

2023-01-04 17:49 UTC, akshukla25 commented
> @akshukla25 , please follow the Get started steps to set yourself up to be a contributor. This PR needs to go through a content review process; it currently has a validation error.
> 
> https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started

completed these steps.

2023-01-04 18:22 UTC, Lauragra commented
> > @akshukla25 , please follow the Get started steps to set yourself up to be a contributor. This PR needs to go through a content review process; it currently has a validation error.
> > https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started
> 
> completed these steps.

Thank you. When you're ready for us to review your PR, please set the **ready for content review** label. It looks like this PR is failing validation because we do not have a resource topic for the partnerTenantType resource - please investigate.

2023-01-04 20:37 UTC, akshukla25 commented
> > > @akshukla25 , please follow the Get started steps to set yourself up to be a contributor. This PR needs to go through a content review process; it currently has a validation error.
> > > https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started
> > 
> > 
> > completed these steps.
> 
> Thank you. When you're ready for us to review your PR, please set the **ready for content review** label. It looks like this PR is failing validation because we do not have a resource topic for the partnerTenantType resource - please investigate.

Could you please help me understand what is resource topic here and what am I missing?

2023-01-04 23:05 UTC, Lauragra commented
> > > > @akshukla25 , please follow the Get started steps to set yourself up to be a contributor. This PR needs to go through a content review process; it currently has a validation error.
> > > > https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started
> > > 
> > > 
> > > completed these steps.
> > 
> > 
> > Thank you. When you're ready for us to review your PR, please set the **ready for content review** label. It looks like this PR is failing validation because we do not have a resource topic for the partnerTenantType resource - please investigate.
> 
> Could you please help me understand what is resource topic here and what am I missing?

If there is a schema PR associated with this content change, the associated stub topics should have been generated as part of that PR. You can find information about resource topics in the CDK, here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/344038/Reference-topic-templates?anchor=template-for-an-entity

2023-01-24 14:02 UTC, FaithOmbongi commented
Hi @akshukla25 - I've come across this PR and see it's related to an Identity workload. Because the schema is already live, kindly ping me internally so I can guide you to close this docs gap.

2023-01-26 16:35 UTC, FaithOmbongi requested changes
Thank you @akshukla25 for your work on this PR.
The two major pieces of feedback:

- The definition of partnerTenantType isn't clear. Please check and address.
- Document the partnerTenantType enumeration as a H3 after the properties table. That should resolve your validation errors. I've shared with you the guidance for documenting enums.
- GLOBAL: For all API docs where you've added the property to the payload, instead of "String", replace with one of the possible values or `null`.

2023-01-26 16:35 UTC, FaithOmbongi commented on api-reference/beta/resources/organization.md
> +|partnerTenantType|partnerTenantType| Type of the partner tenant.The possible values are: `microsoftSupport`, `syndicatePartner`, `breadthPartner`, `breadthPartnerDelegatedAdmin`, `resellerPartnerDel
- It's not clear what "partner tenant" is. Are these Microsoft Partners? Can we make it clearer?
- Follow Option 2 of the enumeration guidance to document the enums in a H3 section after the properties table. The anchor link I added will point to it.
  - This fix will also resolve the validation error.

```suggestion
|partnerTenantType|partnerTenantType| Type of the partner tenant. The possible values are: `microsoftSupport`, `syndicatePartner`, `breadthPartner`, `breadthPartnerDelegatedAdmin`, `resellerPartnerDelegatedAdmin`, `valueAddedResellerPartnerDelegatedAdmin`, `unknownFutureValue`. Nullable. For more information about the possible types, see [partnerTenantType values](#partnertenanttype-values).|
```

2023-01-26 16:35 UTC, FaithOmbongi commented on api-reference/v1.0/api/organization-get.md
> +    "partnerTenantType": "String",
GLOBAL: Change to a real value or `null`

2023-01-26 16:35 UTC, FaithOmbongi commented on api-reference/v1.0/resources/organization.md
> +| partnerTenantType | Type of the partner tenant. The possible values are: `microsoftSupport`, `syndicatePartner`, `breadthPartner`, `breadthPartnerDelegatedAdmin`, `resellerPartnerDelegatedAdmin`, `
Apply the same suggestions provided in the beta doc

2023-01-27 07:42 UTC, FaithOmbongi requested changes

2023-01-27 07:42 UTC, FaithOmbongi commented on api-reference/beta/resources/organization.md
> +| partnerTenantType | partnerTenantType | Type of the partner tenant that has a partnership with the given tenant where user's group in a partner tenant are given an ability to manage the given tenan
Is partnerTenantType returned for the Microsoft Partner or is it returned for the customer that has a relationship with the Microsoft Partner?
```suggestion
| partnerTenantType | partnerTenantType | Type of the tenant that has a delegated partnership with the given tenant where user's group in a partner tenant are given the ability to manage the given tenant. The possible values are: `microsoftSupport`, `syndicatePartner`, `breadthPartner`, `breadthPartnerDelegatedAdmin`, `resellerPartnerDelegatedAdmin`, `valueAddedResellerPartnerDelegatedAdmin`, `unknownFutureValue`. Nullable. For more information about the possible types, see [partnerTenantType values](#partnertenanttype-values).|
```

2023-01-27 07:42 UTC, FaithOmbongi commented on api-reference/beta/resources/organization.md
> +The following table lists the members of an [evolvable enumeration](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations). You must use the `Prefer: include-unknown-enum-me
As per your schema and the description above, there's no value after the `unknownFutureValue`; So Example 2 of Option 2 in the guidance was the suitable one.
```suggestion
```

2023-01-27 07:42 UTC, FaithOmbongi commented on api-reference/beta/resources/organization.md
> +| unknownFutureValue | Evolvable enumeration sentinel value. Do not use. |
Exact syntax that's used in the API and schema please.
```suggestion
| microsoftSupport | Legacy support tenant of Microsoft which was used to provide administrative support to all the customer tenants. |
| breadthPartner | Partner has the ability to provide administrative support for their customers. However, the partner is not allowed to resell to or request delegated admin permissions from customers. |
| breadthPartnerDelegatedAdmin | Similar to Breadth Parther except they can request for delegated admin permissions (DAP) from customer tenants. |
| syndicatePartner | Partner that exclusively resells and manages O365 and Intune for their customers. The customer cannot buy additional direct subscriptions from Microsoft or from other partners. |
| resellerPartnerDelegatedAdmin | Partner that can resell and manage O365 and Intune for their customers. There is no exclusivity clause unlike in the case of SyndicationPartners. The customer can buy additional direct subscriptions from Microsoft or from other partners. |
| valueAddedResellerPartnerDelegatedAdmin | ValueAddedReseller are tier 2 partners, they will themselves be a partner while having a relationship with another partner (generally a reseller), that's why they are "value added reseller". |
| unknownFutureValue | Evolvable enumeration sentinel value. Do not use. |
```

2023-01-27 07:42 UTC, FaithOmbongi commented on api-reference/v1.0/resources/organization.md
> +| Member | Description |
Apply the same suggestions I shared in beta

2023-01-30 18:08 UTC, FaithOmbongi approved these changes
LGTM. Approved!

2023-01-31 04:10 UTC, merged