Add app permissions and attachment api - To Do API
microsoftgraph/microsoft-graph-docs pull request #19591
Opened 2022-12-13 07:07 UTC by avijityadav

2022-12-15 19:08 UTC, Danielabom commented
Contacted author to get info.

2022-12-28 15:02 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _Tasks.Read.All_        | Read all users’ tasks and tasklist | Allows the app to read all users’ tasks and task lists in your organization, without a signed-in user | Yes  | No |
```suggestion
| _Tasks.Read.All_        | Read all users’ tasks and tasklist | Allows the app to read all users’ tasks and task lists in your organization without a signed-in user | Yes  | No |
```

2022-12-28 15:04 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _Tasks.ReadWrite.All_   | Read and write all users’ tasks and tasklists | Allows the app to create, read, update and delete all users’ tasks and task lists in your organization, without a signed-in
```suggestion
| _Tasks.ReadWrite.All_   | Read and write all users’ tasks and tasklists | Allows the app to create, read, update and delete all users’ tasks and task lists in your organization without a signed-in user | Yes  | No |
```

2022-12-28 15:05 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _Tasks.Read.All_        | Read all users’ tasks and tasklist | Allows the app to read all users’ tasks and task lists in your organization without a signed-in user | Yes  | No |
```suggestion
| _Tasks.Read.All_        | Read all users’ tasks and tasklists| Allows the app to read all users’ tasks and task lists in your organization without a signed-in user. | Yes  | No |
```

2022-12-28 15:06 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _Tasks.ReadWrite.All_   | Read and write all users’ tasks and tasklists | Allows the app to create, read, update and delete all users’ tasks and task lists in your organization without a signed-in
```suggestion
| _Tasks.ReadWrite.All_   | Read and write all users’ tasks and tasklists | Allows the app to create, read, update and delete all users’ tasks and task lists in your organization without a signed-in user. | Yes  | No |
```

2022-12-28 18:29 UTC, Danielabom requested changes
Dear @avijityadav , thank you for working on this PR. 
I have some questions/comments, please clarify. Thanks! 

1. I see differences between CSDL files and what we have on the api.md files. for example: I could not find any info about the taskFileAttachment resource type on the api.md file. but I see the new entity on the CSDL.

2. I believe we are missing two relationships on the api-reference/v1.0/resources/todotask.md: 

<NavigationProperty Name="attachments" Type="Collection(graph.attachmentBase)" ContainsTarget="true"/>
<NavigationProperty Name="attachmentSessions" Type="Collection(graph.attachmentSession)" ContainsTarget="true"/>

3. I do not see the changelog in this PR and I need it to properly complete my review.

2022-12-28 18:38 UTC, Danielabom commented on api-reference/v1.0/resources/todotask.md
> +|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date and time in the specified time zone at which the task is scheduled to start.|
I believe we are missing the    <Property Name="hasAttachments" Type="Edm.Boolean" /> property here.

2023-01-09 15:28 UTC, Danielabom commented
Checking on the status of this PR. Hi @avijityadav , let me know if you have plans to make any changes this week.

2023-01-19 21:04 UTC, avijityadav commented on api-reference/v1.0/resources/todotask.md
> +|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date and time in the specified time zone at which the task is scheduled to start.|
Hi @Danielabom, Added it in the latest commit.

2023-01-19 21:11 UTC, avijityadav commented
Hi @Danielabom , 

Thanks for reviewing the PR. Answering to your questions.

**I see differences between CSDL files and what we have on the api.md files. for example: I could not find any info about the taskFileAttachment resource type on the api.md file. but I see the new entity on the CSDL.**

Avijit - There were some renaming  of few resources that API council suggested after the review was completed. Hence, please consider CSDL names as final that went in the code. 

**I believe we are missing two relationships on the api-reference/v1.0/resources/todotask.md: attachments 
  attachmentSessions**

Avijit - Added the attachments relationship. I have not added attachmentSessions here since its not a developer facing resource  and its is used internally to upload an attachment. 

**I do not see the changelog in this PR and I need it to properly complete my review.**

Avijit - Updated the changelog.

2023-01-25 18:20 UTC, Danielabom commented on changelog/Microsoft.Todo.json
> +          "Description": "Added the `hasAttachments` property to the [todoTask](https://docs.microsoft.com/en-us/graph/api/resources/todoTask?view=graph-rest-1.0) resource.",
```suggestion
          "Description": "Added the **hasAttachments** property to the [todoTask](https://docs.microsoft.com/en-us/graph/api/resources/todoTask?view=graph-rest-1.0) resource.",
```

2023-01-25 18:21 UTC, Danielabom commented on changelog/Microsoft.Todo.json
> +          "Description": "Added the `startDateTime` property to the [todoTask](https://docs.microsoft.com/en-us/graph/api/resources/todoTask?view=graph-rest-1.0) resource.",
```suggestion
          "Description": "Added the **startDateTime** property to the [todoTask](https://docs.microsoft.com/en-us/graph/api/resources/todoTask?view=graph-rest-1.0) resource.",
```

2023-01-25 18:23 UTC, Danielabom commented on changelog/Microsoft.Todo.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-01-25 18:24 UTC, Danielabom commented on changelog/Microsoft.Todo.json
> +          "Description": "Added the **attachments** relationship to the [todoTask](https://docs.microsoft.com/en-us/graph/api/resources/todoTask?view=graph-rest-1.0) resource.",
```suggestion
          "Description": "Added the **attachments** navigation property to the [todoTask](https://docs.microsoft.com/en-us/graph/api/resources/todoTask?view=graph-rest-1.0) resource.",
```

2023-01-25 18:29 UTC, Danielabom commented on changelog/Microsoft.Todo.json
> +          "Target": "todoTask"
Is this a duplicated entry? Please see lines 46 to 51.

2023-01-25 21:03 UTC, Danielabom commented on changelog/Microsoft.Todo.json
> +          "Description": "Added support for the application permission of `Tasks.Read.All` to the read operations of the [todoTasklist](https://learn.microsoft.com/en-us/graph/api/resources/todotaskl
Please review the description. I believe that it should be "Added support for the delegated permission."

2023-01-25 21:25 UTC, Danielabom requested changes
@avijityadav, thank you for working on this PR. I just have a couple of questions; please review them. Thanks!

2023-01-27 05:32 UTC, avijityadav commented on changelog/Microsoft.Todo.json
> +          "Description": "Added support for the application permission of `Tasks.Read.All` to the read operations of the [todoTasklist](https://learn.microsoft.com/en-us/graph/api/resources/todotaskl
@Danielabom , We are adding only application permission. Delegated permission were included when To Do API was introduced in the year 2020.

2023-01-27 05:35 UTC, avijityadav commented on changelog/Microsoft.Todo.json
> +          "Target": "todoTask"
Yes, this is duplicated. I'll remove it.

2023-01-27 13:48 UTC, Danielabom approved these changes
@avijityadav, thank you for addressing my comments. PR approved.

2023-01-31 03:59 UTC, Lauragra commented on api-reference/v1.0/api/taskfileattachment-createuploadsession.md
> +title: "taskFileAttachment: createUploadSession"
Global: The taskFileAttachment resource topic and the new methods we're adding need to be surfaced in the v1.0 TOC. Please update the TOC to include the new APIs.

2023-01-31 04:00 UTC, Lauragra commented on changelog/Microsoft.Todo.json
> +      "Version": "v1.0",
We don't have a changelog entry for the permission updates that we're making for beta. Please add a new ChangeList item to call out the new application permission for the beta topics.

2023-01-31 18:14 UTC, avijityadav commented
@Lauragra , I made the edits as needed. Can you please take a look and merge if everything looks okay ?

2023-01-31 18:49 UTC, Lauragra approved these changes

2023-02-01 01:46 UTC, merged