Fixing Update operation as per bugs created by Graph team
microsoftgraph/microsoft-graph-docs pull request #19605
Opened 2022-12-13 23:06 UTC by sseth-msft

1. https://github.com/microsoftgraph/microsoft-graph-docs/issues/19370
2. https://github.com/microsoftgraph/microsoft-graph-docs/issues/18939

2022-12-14 08:20 UTC, FaithOmbongi approved these changes

2022-12-14 08:24 UTC, FaithOmbongi commented
Hi @sseth-msft - Please update the examples as well to remove the read-only properties. Also, best practice for examples is to use actual payloads, not the placeholder values like "String", "createdBy": {"@odata.type": "microsoft.graph.identitySet"} etc that was autogenerated in the doc stub. You can use Graph Explorer to run the requests and paste the actual request URL/body and response payloads.

Adding @Danielabom @isvargasmsft to help with this compliance PR.

2023-02-22 15:22 UTC, Danielabom approved these changes
As per the author, no schema changes. PR approved.

2023-02-28 20:22 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-retentioneventtype.md
> +When a [retention event](../resources/security-retentionevent.md) is created, it is associated with a specific event type which in turn is associated with a [retention label](../resources/security-re
Link for retentionLabel seems broken as per API Doctor error.

2023-02-28 20:24 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-eventpropagationresult.md
> +|status|microsoft.graph.security.eventPropagationStatus|Indicates the status of the event creation request. The possible values are: `none`, `inProcessing`, `failed`, `success`.|
This enumeration type (eventPropagationStatus) seems to not be defined in the docs. Please add it to the enums.md file of your subnamespace or define it below the properties table. 

Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211748/Enums-in-subnamespaces

2023-02-28 20:25 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-eventqueries.md
> +|queryType|microsoft.graph.security.queryType|Represents the type of query associated with an event. 'files' for SPO and ODB and 'messages' for EXO.The possible values are: `files`, `messages`, `unkn
This enum seems to not be defined in the docs. Similar comment above. 

Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211748/Enums-in-subnamespaces

2023-02-28 20:26 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-retentioneventstatus.md
> +|status|microsoft.graph.security.eventStatusType|The status of the distribution. The possible values are: `pending`, `error`, `success`, `notAvaliable`.|
Similar as the comments above, this enumeration seems to not be defined in the docset.

2023-03-01 20:08 UTC, isvargasmsft commented on api-reference/beta/api/security-retentioneventtype-update.md
> -|lastModifiedDateTime|DateTimeOffset|The latest date time when the retentionEventType was modified. Optional.|
Why are we removing these resources from these methods?

2023-03-01 20:09 UTC, isvargasmsft commented on api-reference/beta/api/security-retentionlabel-update.md
>  |defaultRecordBehavior|microsoft.graph.security.defaultRecordBehavior|Specifies the locked or unlocked state of a record label when it is created.The possible values are: `startLocked`, `startUnlocke
Please clarify why are we removing these resources from the method.

2023-03-01 20:15 UTC, isvargasmsft commented on api-reference/v1.0/resources/enums-security.md
> +|unknownFutureValue|
I don't see these 3 enums in the CSDL PR, would you please clarify why are we adding them or provide the CSDL PR that introduces them to v1?

2023-03-01 20:21 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-eventpropagationresult.md
> +|status|microsoft.graph.security.eventPropagationStatus|Indicates the status of the event creation request. The possible values are: `none`, `inProcessing`, `failed`, `success`.|
```suggestion
|status|microsoft.graph.security.eventPropagationStatus|Indicates the status of the event creation request. The possible values are: `none`, `inProcessing`, `failed`, `success`, `unknownFutureValue`.|
```

2023-03-01 20:23 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-retentioneventtype.md
> +When a [retention event](../resources/security-retentionevent.md) is created, it is associated with a specific event type which in turn is associated with a [retention label](../resources/security-re
```suggestion
When a [retention event](../resources/security-retentionevent.md) is created, it is associated with a specific event type which in turn is associated with a [retention label](/graph/beta/resources/security-retentionlabel.md). Only content with that retention label applied will be retained for the specified retention period.
```

2023-03-01 20:28 UTC, isvargasmsft commented on api-reference/v1.0/api/security-retentionevent-post.md
> +|eventQueries|[microsoft.graph.security.eventQueries](../resources/security-eventqueries.md) collection| Represents the workload (SharePoint Online, OneDrive for Business, Exchange Online) and identi
```suggestion
|eventQueries|[microsoft.graph.security.eventQuery](../resources/security-eventquery.md) collection| Represents the workload (SharePoint Online, OneDrive for Business, Exchange Online) and identification information associated with a retention event.|
```

2023-03-01 20:41 UTC, isvargasmsft commented on api-reference/v1.0/api/security-retentionevent-post.md
> +|eventQueries|[microsoft.graph.security.eventQuery](../resources/security-eventquery.md) collection| Represents the workload (SharePoint Online, OneDrive for Business, Exchange Online) and identifica
```suggestion
|eventQueries|[microsoft.graph.security.eventQueries](../resources/security-eventquery.md) collection| Represents the workload (SharePoint Online, OneDrive for Business, Exchange Online) and identification information associated with a retention event.|
```

2023-03-01 20:46 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-retentionevent.md
> +|eventQueries|[microsoft.graph.security.eventQueries](../resources/security-eventqueries.md) collection| Represents the workload (SharePoint Online, OneDrive for Business, Exchange Online) and identi
```suggestion
|eventQueries|[microsoft.graph.security.eventQueries](../resources/security-eventquery.md) collection| Represents the workload (SharePoint Online, OneDrive for Business, Exchange Online) and identification information associated with a retention event.|
```

2023-03-01 20:48 UTC, isvargasmsft commented on api-reference/v1.0/resources/security-retentioneventtype.md
> +When a [retention event](../resources/security-retentionevent.md) is created, it is associated with a specific event type which in turn is associated with a [retention label](/graph/beta/resources/se
```suggestion
When a [retention event](../resources/security-retentionevent.md) is created, it is associated with a specific event type which in turn is associated with a [retention label](/graph/api-reference/beta/resources/security-retentionlabel.md). Only content with that retention label applied will be retained for the specified retention period.
```

2023-03-01 21:01 UTC, isvargasmsft requested changes
Hello @sseth-msft, 

Please clarify why are we removing all of those resources from the tables in the beta files and why is the complexType eventQuery defined in singular in the CSDL but in plural everywhere else. 

Kind regards, 

Isaac

2023-03-01 21:36 UTC, sseth-msft commented on api-reference/beta/api/security-retentioneventtype-update.md
> -|lastModifiedDateTime|DateTimeOffset|The latest date time when the retentionEventType was modified. Optional.|
This is as per feedback received from Graph team: https://gist.github.com/henrymbuguakiarie/ae926a8bd01b272ad2c3bd64860501f1#sseth-msft

2023-03-01 21:37 UTC, sseth-msft commented on api-reference/beta/api/security-retentionlabel-update.md
>  |defaultRecordBehavior|microsoft.graph.security.defaultRecordBehavior|Specifies the locked or unlocked state of a record label when it is created.The possible values are: `startLocked`, `startUnlocke
THis is as per bugs: https://gist.github.com/henrymbuguakiarie/ae926a8bd01b272ad2c3bd64860501f1#sseth-msft suggested by Graph team, to remove any methods that users cannot update from the Patch operation.

2023-03-01 21:38 UTC, sseth-msft commented on api-reference/v1.0/resources/security-retentioneventstatus.md
> +|status|microsoft.graph.security.eventStatusType|The status of the distribution. The possible values are: `pending`, `error`, `success`, `notAvaliable`.|
The enumeration is defined, it was previously missing.

2023-03-01 21:52 UTC, sseth-msft commented
> Hello @sseth-msft,
> 
> Please clarify why are we removing all of those resources from the tables in the beta files and why is the complexType eventQuery defined in singular in the CSDL but in plural everywhere else.
> 
> Kind regards,
> 
> Isaac

Clarified the asks in individual comments, removing properties as per feedback from Graph review team on Patch/update operation to remove properties that cannot be changed: https://gist.github.com/henrymbuguakiarie/ae926a8bd01b272ad2c3bd64860501f1#sseth-msft
 and made changes to the eventQuery name to match the CSDL definition.

2023-03-01 22:57 UTC, isvargasmsft commented on api-reference/v1.0/resources/enums-security.md
> +
Pending explanation about these enums not present in the CSDL PR.

2023-03-07 19:52 UTC, isvargasmsft approved these changes

2023-03-08 02:55 UTC, Lauragra commented on changelog/Microsoft.Compliance.RecordsManagement.json
> +      "Version": "v1.0",
It looks like you're editing an existing ChangeList record in this changelog file. Instead, please add a new ChangeList item for these changes, and leave the existing ChangeList records as-is, so that our Changelog has a historical record of the changes for this API.

2023-03-08 02:58 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +      - name: Records management
Please update the TOC file in the beta folder to remove "(preview") from the Records management node, now that the API is GA.

2023-03-10 00:00 UTC, sseth-msft commented on api-reference/v1.0/toc.yml
> +      - name: Records management
fixed

2023-03-10 00:00 UTC, sseth-msft commented on changelog/Microsoft.Compliance.RecordsManagement.json
> +      "Version": "v1.0",
Aligned with Laura on this

2023-03-10 05:23 UTC, merged