Updated Go paging snippets for latest SDK
microsoftgraph/microsoft-graph-docs pull request #19621
Opened 2022-12-14 21:53 UTC by jasonjoh

2022-12-14 22:19 UTC, maisarissi approved these changes

2022-12-14 22:23 UTC, baywet requested changes

2022-12-14 22:23 UTC, baywet commented on concepts/sdks/paging.md
> +query := me.MeMessagesRequestBuilderGetQueryParameters{
```suggestion
query := me.MessagesRequestBuilderGetQueryParameters{
```

And other instances, sorry we just released a fix today

2022-12-15 14:15 UTC, jasonjoh commented on concepts/sdks/paging.md
> +query := me.MeMessagesRequestBuilderGetQueryParameters{
I see the `Headers` field changed as well. I've updated accordingly.

2022-12-15 14:21 UTC, baywet approved these changes

2022-12-15 15:09 UTC, baywet approved these changes

2022-12-15 20:47 UTC, merged