Added watermark doc to onlineMeeting and participant in beta.
microsoftgraph/microsoft-graph-docs pull request #19629
Opened 2022-12-15 01:29 UTC by zihzhan-msft

2023-01-13 21:08 UTC, yuyaolian-msft approved these changes

2023-02-03 06:29 UTC, zihzhan-msft commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the [onlineMeetingRestricted](https://learn.microsoft.com/en-us/graph/api/resources/onlineMeetingRestricted?view=graph-rest-beta) resource type.",
should this be docs.microsoft.com or learn.microsoft.com

2023-02-03 06:32 UTC, yuyaolian-msft commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the [onlineMeetingRestricted](https://learn.microsoft.com/en-us/graph/api/resources/onlineMeetingRestricted?view=graph-rest-beta) resource type.",
learn, doc will violate build policy

2023-02-07 04:45 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +title: "Watermark meeting in the cloud communications API"
"Support for Watermark for sensitive Teams meetings in the cloud communications APIs"

2023-02-07 05:12 UTC, satyakonmsft requested changes

2023-02-07 05:12 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +
Can we add a GET example?

2023-02-07 05:12 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Get list of participants in a call
Can we rename this title to say "Restricted Experience when joining Watermark meetings using the Cloud Communications APIs"

2023-02-07 05:12 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +
When a watermark is in use, applications using the Cloud Communications Calling APIs [insert hyperlink to https://learn.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=http] will get a restricted media experience.

To indicate this restricted media experience, each participant[insert hyperlink] in the list participants api[insert hyperlink] will have a new restrictedExperience[insert hyperlink] property, which shows watermarkProtection as the reason for the restricted media experience.

2023-02-07 06:36 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +title: "Watermark meeting in the cloud communications API"
updated per comment

2023-02-07 06:39 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +![screenshot](images/communications-watermark-meeting-option.png)
description updated per comment. images removed.

2023-02-07 06:49 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +Use Case 1: The organizer has Teams Enterprise license
added this note in the description section.

2023-02-07 06:50 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +Use Case 1: The organizer has Teams Enterprise license
removed all mentions of licensing in this doc

2023-02-07 06:50 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +    }
removed.

2023-02-07 07:13 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +}
removed

2023-02-07 07:13 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +
added

2023-02-07 07:16 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +
Updated description per comment.

2023-02-07 07:16 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Get list of participants in a call
updated title per comment.

2023-02-07 21:16 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +Please note updating the Watermark properties will have no affect on meeting calls that have already started.
There is a special way to indicate a Note. Like this:
![image](https://user-images.githubusercontent.com/67333557/217367419-401574d0-9c77-4332-b33e-3b54a4bb0957.png)

2023-02-07 21:18 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Create an online meeting with new meeting options
Create an online meeting with the new Watermark option

2023-02-07 21:21 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Update meeting options
Update Watermark option in an onlinemeeting

2023-02-07 21:21 UTC, satyakonmsft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Get meeting options
Get the Watermark option in an onlinemeeting

2023-02-07 21:23 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Create an online meeting with new meeting options
udpated

2023-02-07 21:23 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Get meeting options
updated

2023-02-07 21:23 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +#### Update meeting options
updated

2023-02-07 21:34 UTC, satyakonmsft approved these changes

2023-02-10 01:54 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +      "ChangeList": [
Please, add the missing changelog entries for the changes applied to the onlineMeeting and participant resources.

2023-02-11 00:15 UTC, JarbasHorst commented on concepts/cloud-communications-watermark-meeting.md
> +PATCH /me/onlineMeetings/{meetingId}
Please,  update the request body for this example to contain the updates to the watermarkProtection property.

2023-02-11 00:15 UTC, JarbasHorst commented on concepts/cloud-communications-watermark-meeting.md
> +To indicate this restricted experience, each [participant](/graph/api/resources/participant) in the [call roster](/graph/api/application-post-calls?view=graph-rest-1.0&preserve-view=true#notification
Should "view=graph-rest-1.0" be replaced with "view=graph-rest-beta" considering that the new properties are only available for the BETA APIs.

2023-02-11 00:17 UTC, JarbasHorst commented
Hello @zihzhan-msft, I reviewed your PR and left some comments. Please, take a look when you will have time.

2023-02-11 05:23 UTC, yuyaolian-msft commented on api-reference/beta/resources/onlinemeetingrestricted.md
> +author: "zihzhan"
updated author to zihzhan-msft in these 3 instances.

2023-02-11 05:29 UTC, yuyaolian-msft commented on changelog/Microsoft.Skype.Calling.json
> +      "ChangeList": [
Hi @JarbasHorst these 2 changes are at the bottom of this file diff. I cant remember exactly why but those are of different change id.

2023-02-11 05:30 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +To indicate this restricted experience, each [participant](/graph/api/resources/participant) in the [call roster](/graph/api/application-post-calls?view=graph-rest-1.0&preserve-view=true#notification
updated to be graph-rest-beta.

2023-02-11 05:31 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +PATCH /me/onlineMeetings/{meetingId}
updated per comment.

2023-02-11 05:38 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +---
We typically truncate responses for those APIs as the body will get too long otherwise. (the documents have note saying the response is truncated). So I think it is ok to not show these in other api docs. @zihzhan-msft any suggestions?

2023-02-11 05:41 UTC, yuyaolian-msft commented on concepts/cloud-communications-watermark-meeting.md
> +---
Hi @Jarbas-MSFT  can you elaborate a little on what is the required change? I didnt seem to find a path called Lean/Teamwork and the other 2 you mentioned.

2023-02-13 21:38 UTC, zihzhan-msft commented on changelog/Microsoft.Skype.Calling.json
> +      "ChangeList": [
We've inclued new added change in change log, but few of are not at the very top. is it ok we keep current change? or need to sort them based on time?

2023-02-13 23:10 UTC, JarbasHorst commented on concepts/cloud-communications-watermark-meeting.md
> +---
The TOC file is located here: "concepts/toc.yml" and the position in the TOC is "Learn/Teamwork and communications/Calls and online meetings". In interest of the time, I have updated the TOC.

2023-02-13 23:25 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +      "ChangeList": [
All changes introduced via a PR should be documented in one changelog record. In interest of the time, I fixed the entries.

2023-02-13 23:47 UTC, JarbasHorst commented
@Lauragra, this PR is ready for final review.

2023-02-14 03:23 UTC, Lauragra approved these changes

2023-02-15 03:05 UTC, merged