[AudioRoutingGroup] publish beta doc to v1
microsoftgraph/microsoft-graph-docs pull request #19623
Opened 2022-12-14 22:14 UTC by Hank-TNguyen

2022-12-14 22:51 UTC, HankNguyen-MSFT commented
@Lauragra @zihzhan-msft can you help review this PR?

2022-12-16 02:40 UTC, zihzhan-msft approved these changes

2023-01-19 17:28 UTC, Danielabom commented
Reached out to the author to get info.

2023-01-26 16:01 UTC, Danielabom commented
@Hank-TNguyen, we need the changelog entries for v.1. Thanks!

2023-01-26 17:19 UTC, Danielabom commented on api-reference/v1.0/resources/audioroutinggroup.md
> +
The methods table on the audioroutinggroup.md shows more operations. Please check.

2023-01-26 17:26 UTC, Danielabom commented on api-reference/v1.0/resources/audioroutinggroup.md
> +description: "The audio routing group stores a private audio route between participants in a multiparty conversation. Source is the participant itself and the receivers are a subset of other particip
```suggestion
description: "The audio routing group stores a private audio route between participants in a multiparty conversation. The source is the participant itself, and the receivers are a subset of other participants in the multiparty conversation."
```

2023-01-26 17:30 UTC, Danielabom commented on api-reference/v1.0/resources/audioroutinggroup.md
> +> - `multicast` - source has one participant but there are multiple receivers. Receivers list may be updated.
```suggestion
> - `multicast` - sources have one participant, but multiple receivers exist. The receivers list may be updated.
```

2023-01-26 17:33 UTC, Danielabom commented on api-reference/v1.0/resources/audioroutinggroup.md
> +The audio routing group stores a private audio route between participants in a multiparty conversation. Source is the participant itself and the receivers are a subset of other participants in the mu
```suggestion
The audio routing group stores a private audio route between participants in a multiparty conversation. The source is the participant itself, and the receivers are a subset of other participants in the multiparty conversation.
```

2023-01-26 17:35 UTC, Danielabom commented on api-reference/v1.0/resources/audioroutinggroup.md
> +> **Note:** Routing mode determines the restrictions on the sources and receivers. Only the following routing groups are supported.
Could we take this note out of the note format and leave it as regular text? @Lauragra

2023-01-26 17:39 UTC, Danielabom commented on api-reference/v1.0/resources/audioroutinggroup.md
> +> **Note:** If you create many audio routing groups (e.g. a bot per participant), only the audio of the top 4 dominant speakers is forwarded. It means even with customized audio routing group, if the
```suggestion
> **Note:** If you create many audio routing groups (e.g., a bot per participant), only the audio of the top 4 dominant speakers is forwarded. For example, if the speaker is not loud enough in the main mixer of a customized audio routing group, the bot will not hear it, even if there is a private audio group just for this speaker and the bot.
```

2023-01-26 18:03 UTC, Danielabom commented on api-reference/v1.0/resources/participantmixerlevel.md
> +title: "participantMixerLevel resource type"
I could not find any info about this resource in the files you shared. Please post the links on our Teams chat.

2023-01-26 18:51 UTC, Danielabom commented on api-reference/v1.0/resources/audioduckingconfiguration.md
> +title: "audioDuckingConfiguration resource type"
I could not find any info about this resource in the files you shared. Please post the links on our Teams chat.

2023-01-26 18:55 UTC, Danielabom requested changes
Thank you for working on this PR @Hank-TNguyen. I added some comments, please review them.
Also, please add the following files: 
1. The changelog
2. The call.md

2023-01-30 22:19 UTC, Danielabom commented on changelog/Microsoft.Teams.Core.json
> +    },
Please add the two missing methods from the call.md file.

2023-01-30 22:19 UTC, Danielabom requested changes
@Hank-TNguyen, thank you for working on this PR. Please check out my comments.

2023-02-21 18:47 UTC, Danielabom commented
Hi @Hank-TNguyen, I noticed you removed the "changes requested" label. Were you able to take a look at my comments? Thanks!

2023-03-01 17:10 UTC, Danielabom requested changes
It seems that my comments were not reviewed. This is a big PR, so feel free to reach out for further clarification.

2023-03-01 17:10 UTC, Danielabom commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added audioroutinggroups operation to the [call](https://learn.microsoft.com/graph/api/resources/call?view=graph-rest-v1.0) resource.",
This entry is incorrect:
1. The resource call already exists in v1. 
2. audioroutinggroups does not exist, it is called audioRoutingGroup and it is not an operation. 
3. Please update the changelog with the 2 missing operations for the call,md resource file (I added a similar comment before.) Thanks!

2023-03-01 17:11 UTC, Danielabom commented
@Hank-TNguyen, I added some comments. Also, please fix the build conflicts.

2023-03-15 20:32 UTC, Hank-TNguyen commented on api-reference/v1.0/resources/audioroutinggroup.md
> +
There is no list operation, and this is intended. The Id for an audio routing group is constructed using the source participant id and arg type. User can create and query for it.

2023-03-21 00:07 UTC, Danielabom approved these changes
Thank you for working on this PR @Hank-TNguyen. Note: Based on a conv with Hank, the operations that appeared as new on the call.md file had been on v1 for a long time. Therefore, they should not be on the changelog.

2023-03-31 04:14 UTC, Lauragra commented on api-reference/v1.0/includes/snippets/csharp/create-audioroutinggroup-from-call-csharp-snippets.md
> +---
Why is this PR adding the SDK snippets? These are generally added via the weekly automation after PRs are merged into the main branch. Contributors don't add these snippets to topics manually. For details, see https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211752/Generate-code-snippets.

2023-04-04 02:10 UTC, Lauragra commented on api-reference/beta/api/call-list-audioroutinggroups.md
> +GET https://graph.microsoft.com/v1.0/communications/calls/{id}/audioRoutingGroups
This is a beta topic, why are we changing the example request to use v1.0? Please use beta in the URLs for beta topics.

2023-04-04 02:11 UTC, Lauragra commented on api-reference/v1.0/api/audioroutinggroup-delete.md
> +##### Request
Global: Please change all the Request and Response headings to H3s instead of H5s. Heading should go in order.

2023-04-04 02:12 UTC, Lauragra commented on api-reference/v1.0/api/call-post-audioroutinggroups.md
> +##### Request
Here, because you have H3s for multiple examples, the Request and Response headings should be H4s.

2023-04-20 02:46 UTC, Danielabom commented on api-reference/v1.0/api/participant-configuremixer.md
> +##### Request
```suggestion
### Request
```

2023-04-20 02:48 UTC, Danielabom commented on api-reference/v1.0/api/participant-configuremixer.md
> +##### Response
```suggestion
### Response
```

2023-04-20 02:49 UTC, Danielabom commented on api-reference/v1.0/api/participant-configuremixer.md
> +##### Notification - operation completed
```suggestion
#### Notification - operation completed
```

2023-04-20 02:57 UTC, Danielabom commented on api-reference/v1.0/includes/snippets/csharp/create-audioroutinggroup-from-call-csharp-snippets.md
> +---
@Hank-TNguyen, I just reviewed the latest changes on this PR and updated a couple of missing things. The only comment I cannot resolve is the one above that @Lauragra entered. Please review it. Thanks :)

2023-04-20 03:24 UTC, Danielabom commented
@Hank-TNguyen , please review this build error:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: Failed to validate all JSON files.

2023-05-24 20:34 UTC, Danielabom commented
Hi @Hank-TNguyen, please let us know who will take over this PR, so this person can look at the build error and help us complete the review. Thanks!

2023-05-26 01:03 UTC, Lauragra commented on api-reference/v1.0/api/audioroutinggroup-delete.md
> +# Delete audio routing group
We use the actual resource names in the title so this should be "Delete audioRoutingGroup". Please also update the title field.

2023-05-26 01:04 UTC, Lauragra commented on api-reference/v1.0/api/audioroutinggroup-delete.md
> +# [C#](#tab/csharp)
Globlal: When we bring files from beta to v1.0, we don't copy the SDK snippets. Those will get added via the weekly snippet automation process. Please remove the links and the snippet files from this PR. Please also remove the HTTP tabs for now (line 50 in this topic).

2023-05-26 01:04 UTC, Lauragra commented on api-reference/v1.0/api/audioroutinggroup-get.md
> +# Get audio routing group
Global: Please update all the titles to use the resource names instead of separate words like this.

2023-06-07 15:33 UTC, Danielabom commented on api-reference/v1.0/api/audioroutinggroup-delete.md
> +title: "Delete audio routing group"
```suggestion
title: "Delete audioRoutingGroup"
```

2023-06-22 19:25 UTC, Lauragra commented on api-reference/v1.0/includes/snippets/go/participant-configuremixer-go-snippets.md
> +---
Global: Please remove the SDK snippet files. Those will get added via automation.

2023-06-29 01:17 UTC, Danielabom commented
Contacted @Hank-TNguyen via Teams.

2023-07-06 03:52 UTC, Lauragra commented on api-reference/v1.0/api/audioroutinggroup-delete.md
> +# Delete audioRoutingGroup
Global: Please update the TOC file in the v1.0 folder to surface these APIs in the v1.0 TOC.

2023-07-27 03:49 UTC, merged

2023-07-27 08:32 UTC, jeroenbernaerts commented
This doc update contains a reference to the "configureMixer" endpoint, but I think it has been deprecated and should be removed (see: https://github.com/microsoftgraph/microsoft-graph-docs/issues/16417). I have been trying to use the configureMixer without success (in v1 and beta). `/communications/calls/{call-id}/participants/configureMixer` returns a 404 not-found.

Is the configureMixer endpoint (or something similar) still available?