Documentation and change logs for pronouns settings
microsoftgraph/microsoft-graph-docs pull request #19632
Opened 2022-12-15 09:08 UTC by aymen-ms

This PR adds support to include pronouns settings resource for Microsoft 365. Roadmap # 15937.

2022-12-15 11:30 UTC, aymen-ms commented
This PR adds support to include pronouns settings resource for Microsoft 365. Roadmap # 15937.

2022-12-15 12:55 UTC, antonsegh commented on api-reference/beta/api/pronounssettings-update.md
> +|isEnabledInOrganization|Boolean|`true` if the specified type of insights are enabled for the organization; `false` if the specified type of insights are disabled for all users without exceptions. Re
copied from insights, needs fixing

2022-12-15 13:00 UTC, antonsegh commented on api-reference/beta/resources/organizationsettings.md
> +|pronouns|[pronounsSettings](../resources/pronounssettings.md)|Contains the properties that are configured by an administrator as a tenant-level control whether to display pronouns in an organization
the tope part of this docs seems missing pronouns

2022-12-15 13:01 UTC, antonsegh commented on api-reference/beta/resources/pronounssettings.md
> +description: "This resource represents a Setting to control the availability of Pronouns in the tenant"
does this have to start with a capital ?

2022-12-15 13:06 UTC, antonsegh commented on api-reference/beta/resources/pronounssettings.md
> +Represents a Setting to control the availability of Pronouns in the tenant.
needs some extra text about logic

2022-12-15 13:06 UTC, antonsegh commented on api-reference/beta/resources/pronounssettings.md
> +
do we have somewhere part about global admin role ?

2022-12-15 13:09 UTC, antonsegh commented on api-reference/beta/api/pronounssettings-get.md
> +>**Note:** Using delegated permissions for this operation requires the signed-in user to have a tenant administrator or global administrator role.
can remove tenant administrator - its the same thing

2022-12-15 13:09 UTC, antonsegh commented on api-reference/beta/api/pronounssettings-update.md
> +
add note about global administrator

2022-12-16 08:25 UTC, aymen-ms commented on api-reference/beta/resources/pronounssettings.md
> +description: "This resource represents a Setting to control the availability of Pronouns in the tenant"
lower case seems to be the norm

2022-12-16 12:08 UTC, antonsegh commented on api-reference/beta/resources/organizationsettings.md
> +| [Get pronounsSettings](../api/pronounssettings-get.md)|[pronounsSettings](../resources/pronounssettings.md) collection|Get the pronounsSettings resources from the pronouns navigation property.|
is graph convention to call all List ?

2022-12-16 14:25 UTC, antonsegh commented on api-reference/beta/api/pronounssettings-get.md
> +    "@odata.type": "#microsoft.graph.pronounsSettings",
we can omit odata from sample

2022-12-16 14:25 UTC, antonsegh commented on api-reference/beta/api/pronounssettings-get.md
> +    "isEnabledInOrganization": "Boolean"
should say "true" as its a sample

2022-12-16 14:26 UTC, antonsegh commented on api-reference/beta/api/pronounssettings-update.md
> +  "@odata.type": "#microsoft.graph.pronounsSettings",
we should not need odata in request

2022-12-16 14:26 UTC, antonsegh commented on api-reference/beta/api/pronounssettings-update.md
> +  "isEnabledInOrganization": "Boolean"
should be value

2022-12-19 19:52 UTC, antonsegh commented on concepts/pronouns-configure-pronouns-availability.md
> +title: "Enabling or disabling pronouns in Microsoft 365 (preview)"
is this redundant ? others dont have it

2022-12-19 20:29 UTC, antonsegh commented on concepts/pronouns-configure-pronouns-availability.md
> +If you are a global administrator, you can enable and disable showing pronouns in your organization. Pronouns are **off** by default. When pronouns are enabled, users can add, update, and delete pron
does these map to any actions we expose or its a form of speech ?

2022-12-19 20:30 UTC, antonsegh commented on concepts/pronouns-configure-pronouns-availability.md
> +## Confirm your current settings
Looking at docs for itemInsights, we will have also powershell commands when we expose to beta, maybe we can document powershell rather on this page ?

2022-12-19 20:32 UTC, antonsegh commented on concepts/pronouns-configure-pronouns-availability.md
> +When you turn off pronouns in your organization, pronouns are immediately hidden in Microsoft apps, but the data can persist for up to 30 days on Microsoft servers. If you choose to enable pronouns b
i wonder if there should be any commas or similar in this sentence

2022-12-19 20:36 UTC, antonsegh commented on changelog/Microsoft.People.json
> +				"Description": "Added the [pronounsSettings](https://docs.microsoft.com/en-us/graph/api/resources/pronounsSettings?view=graph-rest-beta) resource",
should it be more here ?

2022-12-19 20:37 UTC, antonsegh commented on api-reference/beta/resources/pronounssettings.md
> +description: "This resource represents a Setting to control the availability of Pronouns in the tenant"
so will you fix ?

2022-12-19 20:41 UTC, antonsegh commented on api-reference/beta/resources/pronounssettings.md
> +Represents _settings_ to control the availability of Pronouns in the tenant. Pronouns are *off* by default. When pronouns are enabled, users can add, update, and delete pronouns on their profile card
not sure if card supports delete per say, also we should not mention probably card here as its one of experices. If we mention it maybe should be "experiences such as profile card"

2022-12-19 20:46 UTC, antonsegh commented on api-reference/beta/api/organizationsettings-list-pronounssettings.md
> +title: "Get pronounsSettings"
can you check in all files the consistency of using Get vs List vs Read, seems it differs

2022-12-19 20:46 UTC, antonsegh commented on api-reference/beta/api/organizationsettings-list-pronounssettings.md
> +---
why this files is called organizationsettings-list-.. and for update pronounssettings-update.md ?

2022-12-19 20:48 UTC, antonsegh commented on api-reference/beta/api/organizationsettings-list-pronounssettings.md
> +  "value": {
do we actually have the word "value" ?

2022-12-20 08:18 UTC, aymen-ms commented on api-reference/beta/api/organizationsettings-list-pronounssettings.md
> +---
because list is for the organization collection and update for the is for the resource

2022-12-20 12:07 UTC, aymen-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +If you are a global administrator, you can enable and disable showing pronouns in your organization. Pronouns are **off** by default. When pronouns are enabled, users can add, update, and delete pron
Just as an intro to the guide

2022-12-22 15:51 UTC, antonsegh commented on concepts/pronouns-configure-pronouns-availability.md
> +title: "Enabling or disabling pronouns (preview)"
this file is still missing in TOC if you go to this link https://review.learn.microsoft.com/en-us/graph/api/pronounssettings-update?view=graph-rest-beta&branch=pr-en-us-19632 and then try to expand API Beta Reference -> People and Workplace Intelligence - it wont be there

2022-12-27 10:37 UTC, antonsegh commented on concepts/pronouns-configure-pronouns-availability.md
> +When pronouns are turned off in your organization, pronouns will be hidden in Microsoft apps and services. However, the data may persist on Microsoft servers for up to 30 days. If you decide to re-en
we should add explicitly that they will be deleted as well.

2023-01-04 20:26 UTC, Danielabom commented
Reached out to @aymen-ms to get info. Cc: @antonsegh.

2023-01-04 21:55 UTC, Danielabom commented on api-reference/beta/resources/pronounssettings.md
> +description: "This resource represents a Setting to control the availability of Pronouns in the tenant"
```suggestion
description: "Represents a setting to control the availability of pronouns in the tenant"
```

2023-01-04 21:58 UTC, Danielabom commented on api-reference/beta/resources/pronounssettings.md
> +Represents _settings_ to control the availability of Pronouns in the tenant. By default, pronouns are **disabled**. If enabled, users will be able to add and update pronouns in Microsoft 365.
```suggestion
Represents _settings_ to control the availability of pronouns in the tenant. By default, pronouns are **disabled**. If enabled, users can add and update pronouns in Microsoft 365.
```

2023-01-04 21:59 UTC, Danielabom commented on api-reference/beta/resources/pronounssettings.md
> +|[Update pronounsSettings](../api/pronounssettings-update.md)|[pronounsSettings](../resources/pronounssettings.md)|Update the properties of a [pronounsSettings](../resources/pronounssettings.md) reso
```suggestion
|[Update pronounsSettings](../api/pronounssettings-update.md)|[pronounsSettings](../resources/pronounssettings.md)|Update the properties of a [pronounsSettings](../resources/pronounssettings.md) resource to manage the display of pronouns in an organization.|
```

2023-01-04 22:04 UTC, Danielabom commented on api-reference/beta/resources/pronounssettings.md
> +|[List pronounsSettings](../api/organizationsettings-list-pronounssettings.md)|[pronounsSettings](../resources/pronounssettings.md)|Get the _settings_ in [pronounsSettings](../resources/pronounssetti
FYI: The api.md file shows "List" as not supported.

2023-01-04 22:13 UTC, Danielabom commented on api-reference/beta/resources/pronounssettings.md
> +|isEnabledInOrganization|Boolean|`true` if the specified settings are enabled for the organization; `false` if the specified settings are disabled for all users. Default is `false`.|
```suggestion
|isEnabledInOrganization|Boolean| Indicates whether the specified setting is enabled or disabled for the organization. Default value is `false`.|
```

2023-01-04 22:19 UTC, Danielabom commented on api-reference/beta/resources/organizationsettings.md
> +|pronouns|[pronounsSettings](../resources/pronounssettings.md)|Contains the properties that are configured by an administrator as a tenant-level control whether to display pronouns in an organization
```suggestion
|pronouns|[pronounsSettings](../resources/pronounssettings.md)|Contains the properties configured by an administrator as a tenant-level control on whether to display pronouns in an organization.|
```

2023-01-04 22:34 UTC, Danielabom commented on api-reference/beta/api/pronounssettings-update.md
> +PATCH https://graph.microsoft.com/beta/organization/{organizationId}/settings/pronouns
FYI: The api.md file shows a "patch" method as supported.

2023-01-04 23:06 UTC, Danielabom commented on changelog/Microsoft.People.json
> +				  "Description": "Added a [list](https://learn.microsoft.com/en-us/graph/api/organizationsettings-list-pronounssettings?view=graph-rest-beta&tabs=http) operation to the [pronounsSettings](https:/
```suggestion
				  "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/organizationsettings-list-pronounssettings?view=graph-rest-beta&tabs=http) operation to the [pronounsSettings](https://docs.microsoft.com/en-us/graph/api/resources/pronounssettings?view=graph-rest-beta) resource, to get the tenant-level settings for pronouns",
```

2023-01-04 23:08 UTC, Danielabom commented on changelog/Microsoft.People.json
> +				  "Description": "Added an [udpate](https://learn.microsoft.com/en-us/graph/api/pronounssettings-update?view=graph-rest-beta&tabs=http) operation to the [pronounsSettings](https://docs.microsoft.
```suggestion
				  "Description": "Added the [udpate](https://learn.microsoft.com/en-us/graph/api/pronounssettings-update?view=graph-rest-beta&tabs=http) operation to the [pronounsSettings](https://docs.microsoft.com/en-us/graph/api/resources/pronounssettings?view=graph-rest-beta) resource, to update the tenant-level settings for pronouns",
```

2023-01-05 15:38 UTC, Danielabom commented on concepts/pronouns-configure-pronouns-availability.md
> +title: "Customize pronouns availability (preview) (preview)"
This is more of a question than an observation. Is there a particular reason why the word "preview" appears twice?

2023-01-05 15:39 UTC, Danielabom commented on concepts/pronouns-configure-pronouns-availability.md
> +description: "Configure availability of pronouns by using the REST API pronounsSettings resource."
```suggestion
description: "Configure the availability of pronouns by using the REST API pronounsSettings resource."
```

2023-01-05 15:41 UTC, Danielabom commented on concepts/pronouns-configure-pronouns-availability.md
> +If you are a global administrator, you have the ability to turn on or off the display of pronouns in your organization. By default, pronouns are **off**. If you turn pronouns on, users will be able t
```suggestion
If you are a global administrator, you can turn on or off the display of pronouns in your organization. By default, pronouns are **off**. If you turn pronouns on, users will be able to add and update pronouns in Microsoft 365.
```

2023-01-05 15:58 UTC, Danielabom requested changes
Thank you for working on this PR. Please address a few comments that I added. Please review the build errors as well.

2023-01-05 18:16 UTC, aymen-ms commented on api-reference/beta/resources/pronounssettings.md
> +
that is mentioned in the get/patch actions

2023-01-05 18:20 UTC, aymen-ms commented on api-reference/beta/resources/pronounssettings.md
> +|[List pronounsSettings](../api/organizationsettings-list-pronounssettings.md)|[pronounsSettings](../resources/pronounssettings.md)|Get the _settings_ in [pronounsSettings](../resources/pronounssetti
Used "List" to make it consistent with other entries in the `orgnaizationsettings`

2023-01-05 18:45 UTC, aymen-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +## Confirm your current settings
For the cmdlets to be generated we need to have the api published, we can update that once we have the api published

2023-01-05 23:38 UTC, Danielabom commented
I've escalated the build error accordingly. Will follow-up tomorrow.

2023-01-09 14:05 UTC, millicentachieng commented on api-reference/beta/api/pronounssettings-update.md
> +}
You need to specify the response type here e.g. `@odata.type": "microsoft.graph.pronounsSettings"`

2023-01-09 15:14 UTC, Danielabom commented on api-reference/beta/api/pronounssettings-update.md
> +}
@aymen-ms , before we approve this PR, please review this build error.

2023-01-10 17:42 UTC, Danielabom commented
@aymen-ms, the build keeps failing. Please check.

2023-01-10 18:12 UTC, aymen-ms commented
> @aymen-ms, the build keeps failing. Please check.

@Danielabom ,  Seems like it was a transient issue, I re-run it has succeeded.

2023-01-10 18:14 UTC, Danielabom approved these changes
The build conflicts were resolved, and my comments were addressed. Thanks @aymen-ms

2023-01-14 03:32 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +If you are a global administrator, you can turn on or off the display of pronouns in your organization. By default, pronouns are **off**. If you turn pronouns on, users will be able to add and update
@aymen-ms , this comment is to follow my email this afternoon, asking if there's any pre-existing docs for end users or administrators about the experience and support for pronouns in Microsoft 365 - normally, our developer docs do not assume that all customers are completely familiar with existing end user or admin experience related to that feature, if that applies. In the case of pronouns support, that definitely applies. 
If there's such pre-existing Microsoft docs for pronouns, please include a link. Otherwise, I'm assuming there isn't (as I have searched). In that case, this concept topic needs to introduce the pronouns feature (part of the value of such support is indeed on the end user experience). We can't just begin by assuming customers are clear what the support is like for Microsoft services.

2023-01-14 03:33 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +> [!NOTE]
Lines 14-15:
For consistency, please remove this note. 

It's not because the note is incorrect. The docs have [explained](https://learn.microsoft.com/en-us/graph/versioning-and-support?view=graph-rest-beta#preview-status) and tried to consistently build the expectations for customers that is something is tagged as "preview", the implications that your note spells out apply. So we don't want to dilute that convention, and cause some customers to mistake that where the note is NOT spelled out, then even if a feature or API is just tagged as "preview", it's ok to use in production apps.

2023-01-14 03:45 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +If you are a global administrator, you can turn on or off the display of pronouns in your organization. By default, pronouns are **off**. If you turn pronouns on, users will be able to add and update
So in the interest of time, I am going to attempt to add a preceding paragraph to explain (a) the purpose of pronouns, (b) what the support is like for end users.
As a heads-up, I might overlook and not have the most up-to-date understanding of pronouns, so please feel free to let me know and make adjustments.

2023-01-14 05:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationsettings.md
> +|pronouns|[pronounsSettings](../resources/pronounssettings.md)|Contains the properties configured by an administrator as a tenant-level control on whether to display pronouns in an organization.|
Line 43:
There are some repetitions in the description (e.g., "tenant-level", "in an organization"), and "display pronouns in an organization" is too broad a context. We certainly don't mean in other forms of expression within an organization, like in an email body or document, this setting controls whether users can convey their preferred pronouns. 

I think we can reword the description as:
"Represents administrator settings that control the display of pronouns in users' profile cards within an organization."

(There are a couple of other descriptions in this table that can be simplified too.)

2023-01-14 05:40 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationsettings.md
> +| [List pronounsSettings](../api/organizationsettings-list-pronounssettings.md)|[pronounsSettings](../resources/pronounssettings.md) resource|Get the pronounsSettings resources from the pronouns navi
Line 27:
That description technically just explained syntactically what a GET operation does.
I think more meaningful for developers (who should be familiar with REST GET operations in general) is what this GET operation does for them, what pronounsSettings do for them.

Can you rephrase the description as:
"Get the properties of the pronounsSettings resource for an organization, that controls the display of pronouns in profile cards within the organization."

Please continue to include a link for pronounsSettings.

2023-01-14 05:43 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-list-pronounssettings.md
> +
Line 15:
Hm, per how pronunsSettings is defined right now, with only the isEnabledInOrganization property, it seems to me the API doesn't have anything to do with "returning pronouns", as in, returning which user has which pronouns set up in their profile card.

Can you please rephrase this description as:
"Get the properties of the pronounsSettings resource for an organization, that controls the display of pronouns in users' profile cards within the organization."

Please continue to include a link for pronounsSettings."

2023-01-14 05:55 UTC, angelgolfer-ms commented on api-reference/beta/resources/pronounssettings.md
> +
Line 29:
This comment is about the use of the term "specified setting". Technically, just by being a property of the parent pronounsSettings object, there is no extra "specifying" necessary. 
Because at debut for this pronouns API, this property is what the API set is all about, I think developers would find it more helpful if the description is more direct.

Can you rephrase the description as:
"`True` if any set pronouns are displayed in users' profile cards in an organization, `false` otherwise. The default is `false`."

2023-01-14 06:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/pronounssettings.md
> +
Line 16:
I think using "available" or "availability" can be ambiguous, if I understand your feature correctly. (BTW, speaking of which, typically partner teams provide an api.md for the docs for the debut of any API, just so as reviewers, we don't misunderstand how the feature and API behave.)

For example - even if my organization has enabled the display of pronouns, if I don't set pronouns for myself, other users in the organization would not know my pronouns. In other words, my pronouns are still not available because I choose not to or just haven't set them.

It seems to me the setting is about supporting the display of pronouns.

Also, "pronouns in Microsoft 365" is vague and not helpful, especially for a feature like pronouns that impact end user experience - where do pronouns appear in Microsoft 365? 

Can you rephrase the description as:
"Represents the _settings_ to control the display of pronouns in users' profile cards within an organization. By default, pronouns are disabled and not displayed. If enabled, users can optionally add or update their pronouns.

(Separate paragraph) For more information, see Manage display of pronouns using the Microsoft Graph API (and link to your concept topic)."

You can please communicate me offline in case my suggestion about specifying profile cards is incorrect (as we're not supposed to expose future product plans in the public on Github).

2023-01-14 06:18 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +
Line 10:
Can we retitle the topic as:
"Manage display of pronouns in profile cards using the Microsoft Graph API (preview)"?

The reasons are in a [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/19632/files#r1070223623) in pronounssettings.md.

2023-01-14 06:22 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +description: "Configure the availability of pronouns by using the REST API pronounsSettings resource."
Line 2:
Please specify the same value as the topic title.
Per my comment below, I'm suggesting the topic title to be:
"Manage the display of pronouns in profile cards using the Microsoft Graph API"

2023-01-14 06:35 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +description: "Configure the availability of pronouns by using the REST API pronounsSettings resource."
Since I'm going to make a commit in this PR for this topic, I will include the title change to the commit.

Please let me know if you see an issue with the retitling.

2023-01-14 06:36 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +
Since I'm going to make a commit in this PR for this topic, I will include the title change to the commit.

Please let me know if you see an issue with the retitling.

2023-01-14 06:37 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +> [!NOTE]
Since I'm going to make a commit in this PR for this topic, I will remove this note in the commit.

2023-01-14 06:39 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +
Line 40:
Per my comment in the pronounssettings.md topic, I think "available" is ambiguous. 
Since I'm going to make a commit to this topic, I'll add my rephrase. Please let me know if you see an issue with the rephrase.

2023-01-14 06:44 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +When you turn pronouns on or off, it can take up to six hours for users to see changes. For example, if you turn pronouns on, users won’t be able to see the option to add pronouns on their profile fo
Line 97, 99 - please use present tense even when you're describing a sequence of events.

FYI in general, we refrain from using future tense in documentation. After all, the behavior (involved in a sequence of events) is already implemented and is a fact. From that perspective, docs that describe current behaviors of a feature should simply use present tense.

When you take into account localization, future tense can create ambiguity.

2023-01-14 06:45 UTC, angelgolfer-ms commented on concepts/toc.yml
> +            href: pronouns-configure-pronouns-availability.md
Line 505:
Please use "Customize pronouns display (preview)"

2023-01-14 07:14 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +## Important
Lines 95-99:
FYI I'm going to move this note further up in the topic in my upcoming commit.
In general, important information (like you characterized it) should not be all the way at the end of a topic. Customers mostly skim and may miss this info.

2023-01-14 07:15 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +When you turn pronouns on or off, it can take up to six hours for users to see changes. For example, if you turn pronouns on, users won’t be able to see the option to add pronouns on their profile fo
Since I'm going to make a commit to this topic, I'll fix the tense.

2023-01-14 07:16 UTC, angelgolfer-ms commented on concepts/toc.yml
> +            href: pronouns-configure-pronouns-availability.md
Since I'm going to make a commit to this PR, I'll make this change in the TOC file.

2023-01-14 07:55 UTC, angelgolfer-ms requested changes
Hi @aymen-ms ,
The original plan was for me to review the IA/TOC, but in doing that, I needed to gain a bit more understanding about this content. As a side effect, I noticed the concept topic could either point customers to, or include content about, how Microsoft 365 supports pronouns. Since I couldn't find much existing relevant Microsoft docs about pronouns, I did some internal research and suggested the content in a commit. Please take a look at the concept topic and let me know if there's anything I overlooked or misunderstood.

As well, please take a look at my comments in the reference topics as well.

2023-01-19 03:48 UTC, angelgolfer-ms commented on concepts/toc.yml
> +            href: pronouns-configure-pronouns-availability.md
Per Anton's email on 1/18 that displaying pronouns is one result of toggling on, I'm scoping down to a specific section in the concept topic where I list the exact effects of "enabling" pronouns, and for other places, like the topic and TOC titles, I try not to tie them to "display" anymore.
FYI I'm changing the TOC title to "Enable or disable pronouns".

2023-01-19 03:50 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +description: "Configure the availability of pronouns by using the REST API pronounsSettings resource."
Per Anton's email on 1/18 that displaying pronouns is one result of toggling on, I'm scoping down to a specific section in the concept topic where I list the exact effects of "enabling" pronouns, and for other places, like the topic and TOC titles, I try not to tie them to "display" anymore.
FYI I'm changing the topic title to "Manage pronouns settings for an organization using the Microsoft Graph API".

2023-01-19 03:51 UTC, angelgolfer-ms commented on concepts/pronouns-configure-pronouns-availability.md
> +
Per Anton's email on 1/18 that displaying pronouns is one result of toggling on, I'm scoping down to a specific section in the concept topic where I list the exact effects of "enabling" pronouns, and for other places, like the topic and TOC titles, I try not to tie them to "display" anymore.
FYI I'm changing the topic title to "Manage pronouns settings for an organization using the Microsoft Graph API".

2023-01-19 06:04 UTC, angelgolfer-ms commented on api-reference/beta/resources/pronounssettings.md
> +
Per Anton's email on 1/18 that displaying pronouns is one result of toggling on, I'm scoping down to a specific section in the concept topic where I list the exact effects of "enabling" pronouns, and for other places, I try not to tie them to "display" anymore. Instead, I point customers back to the concept topic.

So for line 16, I suggest:
"Represents the settings that manage the support of pronouns in an organization. By default, pronouns are disabled. 

(Separate paragraph) For more information, see Manage pronouns settings for an organization using the Microsoft Graph API (and link to your concept topic)."

2023-01-19 06:42 UTC, angelgolfer-ms commented on api-reference/beta/resources/pronounssettings.md
> +
Per Anton's email on 1/18..., slight rephrase:
"`True` to enable pronouns settings in the organization, `false` otherwise. The default is `false`, pronouns are disabled."

2023-01-19 07:13 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-list-pronounssettings.md
> +
Per Anton's email on 1/18..., I suggest rephrasing this description as:
"Get the properties of the pronounsSettings (link to pronounssettings.md) resource for an organization. For more information on settings to manage pronouns support, see Manage pronouns settings for an organization using the Microsoft Graph API (and link to your concept topic)."

2023-01-19 07:18 UTC, angelgolfer-ms commented on api-reference/beta/api/pronounssettings-update.md
> +
Line 52:
Please rephrase the description as follows, as explained in the prounounssetting.md topic:
"`True` to enable pronouns in the organization, `false` otherwise. The default is `false`, pronouns are disabled."

2023-01-19 07:22 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationsettings.md
> +|pronouns|[pronounsSettings](../resources/pronounssettings.md)|Contains the properties configured by an administrator as a tenant-level control on whether to display pronouns in an organization.|
Line 43:
Per Anton's email on 1/18,... I suggest rephrasing the description as follows:
"Represents administrator settings that manage the support of pronouns in an organization."

2023-01-20 23:36 UTC, angelgolfer-ms commented on changelog/Microsoft.People.json
> +			"WorkloadArea": "People and workplace intelligence",
Lines 170, 171:
@aymen-ms , FYI I am manually changing these two properties to "Directory management" and "Organization settings" respectively.
Reasons: Graph Studio doesn't know where your API is exposed in the TOC. It can only deduce from the corresponding changelog JSON file that you're using where your customers would likely find your API in the TOC. That's an internal issue that needs to be solved if we don't want to have to occasionally manually make such updates like in this case.
On the other hand, the purpose of these two properties is to indicate in the generated changelog, where customers can find the corresponding API in the TOC. In your case, indeed the API is exposed in the TOC under "Directory management" >> "Organization settings".

2023-01-20 23:48 UTC, angelgolfer-ms approved these changes
@aymen-ms , thanks for incorporating my earlier comments. FYI I made some last fixes, and added a comment as an FYI for you for the changelog. Unless other folks have more feedback (e.g., for the concept topic), from my perspective, the PR is good for publishing.
When your API is live, please follow step 8 of the [workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow) and set the PR to ready to publish. The PR would be published in the next daily publishing.

2023-02-28 04:11 UTC, merged