Alphabetize 12 15 22
microsoftgraph/microsoft-graph-docs pull request #19639
Opened 2022-12-15 22:35 UTC by dodaromike

Alphabetizing API V1.0 for 12-15-2022

2022-12-19 20:14 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/assignedplan.md
>  |:---------------|:--------|
This is an example of an enum. Please don't reorder enum tables. Even though we want developer customers to refer to enum members by their string names, each of the members is mapped to a numerical value in ascending order. So please don't reorder the members in these tables.

2022-12-19 20:16 UTC, dodaromike commented on api-reference/v1.0/resources/assignedplan.md
>  |:---------------|:--------|
Yes, you mentioned that and I have been leaving the enums alone.

2022-12-19 20:21 UTC, dodaromike commented on api-reference/v1.0/resources/assignedplan.md
>  |:---------------|:--------|
On second look, there might be a few |Member | Description | items that I changed.  I'll revert them back to what they were.

2022-12-19 20:25 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/calendarpermission.md
>  | Member        | Description |
This is another example of an enum table. Please don't reorder enum tables.

2022-12-19 20:34 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/channel.md
Yes, this is another example of an enum table. Please don't reorder.
In particular, newer enums that define "unknownFutureValue" are called evolvable enums. The location of  "unknownFutureValue" relative to the rest of the enum members is important, we can't move it anywhere else. This is explained here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations

2022-12-19 20:49 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/chat.md
This is another example of an enum table.  Please exclude enum tables from reordering please.

2022-12-19 20:55 UTC, angelgolfer-ms requested changes
Per our chat on Teams, please do not reorder enum members in their tables.
Methods also follow a different order than plain alphabetical order. I would suggest leaving that from the main task. Further reasons in our Teams chat.
The ordering of the properties and nav properties look good. Caveat: I only browsed the diff, and not the staged topics, so if there's any oversight such as missing a nav properties table, I wouldn't have picked that out and would love to leave that to your eye for detail :-)

2022-12-19 21:12 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/applemanagedidentityprovider.md
> +
This is an example of a Methods table that you have updated. The original order is actually correct per our guidance. Please revert. 

In general:
Methods tables actually take a different order, not as straight forward as just alphabetizing. The order is - list the CRUD operations first, in the order of list, create, get, update, delete, where applicable. Then list any other actions or functions alphabetically. You can find this guidance in the CDK here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title.

2022-12-19 21:16 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/applemanagedidentityprovider.md
> +
I'd strongly recommend leaving the Methods tables alone for this pass, so that completing the reordering of properties and nav properties in complex type and entity topics is attainable within a reasonable time. The scope creep would extend this project; there could be other tasks that our manager might prioritize higher. As described in our Teams chat, the ordering of methods (or lack of a consistent order) doesn't affect customers as much as for properties and nav properties.

2022-12-20 00:48 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/applemanagedidentityprovider.md
> +
Thanks for reverting.

2022-12-20 04:06 UTC, dodaromike commented on api-reference/v1.0/resources/applemanagedidentityprovider.md
> +
Reverted the methods table.

2023-01-03 21:57 UTC, Danielabom approved these changes
No enums or methods were reordered. 
Alphabetial order of the properties and nav properties: OK
Tables' format: OK
PR approved.

2023-01-04 03:43 UTC, merged