Release Qna Search
microsoftgraph/microsoft-graph-docs pull request #19762
Opened 2023-01-04 08:26 UTC by ZChristine

2023-01-05 15:36 UTC, njerigrevious requested changes
Looks good - please fix minor corrections per the comments. Thanks!

2023-01-05 15:36 UTC, njerigrevious commented on concepts/search-concept-qna.md
> +After qnas are created, to search for them, in the [searchRequest](/graph/api/resources/searchrequest), in the **entityTypes** property, specify `qna` as the value.
Please rephrase to "Once you create your QnAs, you can use the Graph Search API to search for them. To do this, specify "qna" as the value in the entityTypes property in your search request body and then provide a relevant query string. See below for an example."

2023-01-05 15:36 UTC, njerigrevious commented on concepts/search-concept-qna.md
> +
Please add limitation "Markdown is currently not supported for the qna description. Please use plain text and '\n'."

2023-01-08 13:08 UTC, ZChristine commented on concepts/search-concept-qna.md
> +
\n is invisible as carriage return in defined string

2023-01-08 13:09 UTC, ZChristine commented on concepts/search-concept-qna.md
> +After qnas are created, to search for them, in the [searchRequest](/graph/api/resources/searchrequest), in the **entityTypes** property, specify `qna` as the value.
updates

2023-01-10 01:56 UTC, njerigrevious approved these changes
Approved. Thanks!

2023-01-12 00:14 UTC, Lauragra commented on concepts/search-concept-qna.md
> +# Use the Microsoft Search API to search qnas
I suggest that it will be more clear to users to refer to "questions and answers" instead of qnas in the title - unless you specifically mean to refer to the resource name? 

Also, I see that in the [qna ](https://review.learn.microsoft.com/en-us/graph/api/resources/search-qna?view=graph-rest-beta&branch=pr-en-us-19762) resource topic, we refer to it as Q&As. I'm not sure if that is clear to a global audience. In that topic, you might want to make the summary statement: "Represents questions and answers (Q&As) in Microsoft Search.

2023-01-12 00:15 UTC, Lauragra commented on concepts/search-concept-qna.md
> +You can use the Microsoft Search API in Microsoft Graph to search qnas. Administrators can create qnas in the [Microsoft 365 admin center](https://admin.microsoft.com/Adminportal/Home#/MicrosoftSearc
Here, too, it's not clear as to whether you're referring to the qna resource, or to "questions and answers". I think that you mean the latter; please verify.

2023-01-12 00:19 UTC, Lauragra commented on concepts/search-concept-qna.md
> +Once you create your QnAs, you can use the Graph Search API to search for them. To do this, specify `qna` as the value in the **entityTypes** property in your search request body and then provide a r
For clarity, please change "Once" to "After". Also, I'm not sure that QnAs spelled that way is clear/accurate. It will be most clear to spell out as "questions and answers" or perhaps shorten to Q&As after first mention. Also, please also precede Graph with "Microsoft" - "Microsoft Graph Search API".

2023-01-12 00:21 UTC, Lauragra commented on concepts/search-concept-qna.md
> +Once you create your QnAs, you can use the Graph Search API to search for them. To do this, specify `qna` as the value in the **entityTypes** property in your search request body and then provide a r
Revise the second sentence "... relevant query string, as shown in the following example."

2023-01-12 00:22 UTC, Lauragra commented on concepts/search-concept-qna.md
> +## Example: Search qnas
qnas here should either be Q&As or questions and answers.

2023-01-12 00:28 UTC, Lauragra commented on concepts/search-concept-qna.md
> +- Sorting, aggregation, and pagination are not supported for qna searches.
Again, clarify whether this is a reference to the resource name (in which case it should have bold formatting applied) or Q&A. Please do the same for the reference in the third bullet point.

2023-01-12 01:10 UTC, ZChristine commented on concepts/search-concept-qna.md
> +## Example: Search qnas
Update to clarify in the front section that qnas represent questions and answers(Q&As). Questions and answers map the permission description and it also has same meaning as Q&As in Microsoft Search.

2023-01-12 01:16 UTC, ZChristine commented on concepts/search-concept-qna.md
> +# Use the Microsoft Search API to search qnas
Update

2023-01-12 01:17 UTC, ZChristine commented on concepts/search-concept-qna.md
> +Once you create your QnAs, you can use the Graph Search API to search for them. To do this, specify `qna` as the value in the **entityTypes** property in your search request body and then provide a r
Update

2023-01-12 01:17 UTC, ZChristine commented on concepts/search-concept-qna.md
> +- Sorting, aggregation, and pagination are not supported for qna searches.
Updates

2023-01-12 03:04 UTC, Lauragra approved these changes

2023-01-12 03:20 UTC, merged