Added 'employeeLeaveDateTime' to 'User' object.
microsoftgraph/microsoft-graph-docs pull request #19778
Opened 2023-01-05 01:21 UTC by rajadineshmurugesan-microsoft

2023-02-27 15:03 UTC, FaithOmbongi requested changes
Thank you @rajadineshmurugesan-microsoft for your work on this PR.

I've suggested some edits to the descriptions in beta. Please apply the edits to v1.0. Also left some other minor change requests.

2023-02-27 15:03 UTC, FaithOmbongi commented on concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md
>      Select-MgProfile -Name "beta"
Update to use v1.0
```suggestion
    Select-MgProfile -Name "v1.0"
```

2023-03-01 02:56 UTC, OWinfreyATL commented
Hey @FaithOmbongi 

Is there a way to see where an error is in the changelog? Started getting this vague error:
![image](https://user-images.githubusercontent.com/85191667/222033361-e97e6902-dd42-45f1-a04f-29f412eaa464.png)

When merging suggested changes into this PR.

thanks.

2023-03-01 11:24 UTC, FaithOmbongi commented
> Hey @FaithOmbongi
> 
> Is there a way to see where an error is in the changelog? Started getting this vague error: ![image](https://user-images.githubusercontent.com/85191667/222033361-e97e6902-dd42-45f1-a04f-29f412eaa464.png)
> 
> When merging suggested changes into this PR.
> 
> thanks.

I think it's because of the merge conflict in the changelog. Try resolving that and see if it fixes the issue.

2023-03-01 16:07 UTC, FaithOmbongi commented
Hi @OWinfreyATL - Please apply the changes in beta to the v1.0 docs as well.

2023-03-01 16:58 UTC, FaithOmbongi approved these changes
LGTM! Approved!

2023-03-02 04:37 UTC, merged