add new type cloudPcManagementUserAssignmentResult
microsoftgraph/microsoft-graph-docs pull request #19783
Opened 2023-01-05 03:54 UTC by Guoan-Tang

2023-02-15 06:56 UTC, AshleyYangSZ requested changes
Please update title to [CloudPC] Add assignedUsers to cloudPcManagementUserAssignmentResult .
Do remember to add change-log

2023-02-23 03:48 UTC, AshleyYangSZ requested changes
@Guoan-Tang  This doc PR doesn't reflect the API change. Please update the doc according to what you updated in the schema. It's adding assignedUsers in policyAssignment resource instead of adding a userassignmentresult.
And please do add change-log

2023-02-23 10:50 UTC, AshleyYangSZ approved these changes

2023-03-16 19:40 UTC, Lauragra commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|alternateResourceUrl|String|The URL of the alternate resource that links to this provisioning policy. Read-only. Supports: $filter, $select, $orderBy.|
Global: Please format the query parameters with tic marks, i.e. `$filter`, for consistency. Otherwise, this looks okay!

2023-03-30 06:00 UTC, Guoan-Tang commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|alternateResourceUrl|String|The URL of the alternate resource that links to this provisioning policy. Read-only. Supports: $filter, $select, $orderBy.|
fixed

2023-04-04 18:31 UTC, Lauragra approved these changes

2023-05-09 02:59 UTC, merged