taskProcessingResults for run API
microsoftgraph/microsoft-graph-docs pull request #19787
Opened 2023-01-05 15:40 UTC by OWinfreyATL

2023-01-25 17:54 UTC, FaithOmbongi requested changes
Hi @OWinfreyATL,

I've investigated why this new doc and the changes you're making and identified some oversights from the initial publishing:

- This doc https://learn.microsoft.com/en-us/graph/api/identitygovernance-run-list-taskprocessingresults?view=graph-rest-beta should be documenting the syntax you're introducing in this PR (in identitygovernance-list-run-taskprocessingresults.md)
- We should have a new doc with the file name identitygovernance-userprocessingresult-list-taskprocessingresults in which you document the `GET /identityGovernance/lifecycleWorkflows/workflows/{workflowId}/runs/{runId}/userProcessingResults/{userProcessingResultId}/taskProcessingResults` syntax which exists in the current doc.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/14026935/214645638-99435ff3-c22e-4c80-aa35-0c85fb386828.png">

Let me know if this makes sense. I don't mind spinning up a new branch against your branch so you can review the suggestions. LMK what works for you.

2023-01-26 12:54 UTC, OWinfreyATL commented
> Hi @OWinfreyATL,
> 
> I've investigated why this new doc and the changes you're making and identified some oversights from the initial publishing:
> 
> * This doc https://learn.microsoft.com/en-us/graph/api/identitygovernance-run-list-taskprocessingresults?view=graph-rest-beta should be documenting the syntax you're introducing in this PR (in identitygovernance-list-run-taskprocessingresults.md)
> * We should have a new doc with the file name identitygovernance-userprocessingresult-list-taskprocessingresults in which you document the `GET /identityGovernance/lifecycleWorkflows/workflows/{workflowId}/runs/{runId}/userProcessingResults/{userProcessingResultId}/taskProcessingResults` syntax which exists in the current doc.
> 
> <img alt="image" width="810" src="https://user-images.githubusercontent.com/14026935/214645638-99435ff3-c22e-4c80-aa35-0c85fb386828.png">
> 
> Let me know if this makes sense. I don't mind spinning up a new branch against your branch so you can review the suggestions. LMK what works for you.
> 
> On another note, I've tested the doc stubs regeneration and the dentitygovernance-userprocessingresult-list-taskprocessingresults.md file isn't generated. I don't know why it isn't. But I wonder if that would mean the related cmdlet and other SDKs won't be generated either.

Hey Faith I can do this. One thing is that there is already a document named identitygovernance-userprocessingresult-list-taskprocessingresults located here: https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-list-taskprocessingresults?view=graph-rest-beta&tabs=http

Which documents:
GET /identityGovernance/lifecycleWorkflows/workflows/{workflowId}/userProcessingResults/{userProcessingResultId}/taskProcessingResults

2023-01-26 14:02 UTC, FaithOmbongi commented
> Hey Faith I can do this. One thing is that there is already a document named identitygovernance-userprocessingresult-list-taskprocessingresults located here: https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-list-taskprocessingresults?view=graph-rest-beta&tabs=http
> 
> Which documents: GET /identityGovernance/lifecycleWorkflows/workflows/{workflowId}/userProcessingResults/{userProcessingResultId}/taskProcessingResults

Awesome! Thanks, @OWinfreyATL.
I didn't notice the other file exists. I then recommend that you add `GET /identityGovernance/lifecycleWorkflows/workflows/{workflowId}/runs/{runId}/userProcessingResults/{userProcessingResultId}/taskProcessingResults` as an additional syntax in [that doc](https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-list-taskprocessingresults?view=graph-rest-beta&tabs=http) and some explainer - especially if the two URLs return different (like a subset of) results.

2023-01-27 15:43 UTC, OWinfreyATL commented
> > Hey Faith I can do this. One thing is that there is already a document named identitygovernance-userprocessingresult-list-taskprocessingresults located here: https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-list-taskprocessingresults?view=graph-rest-beta&tabs=http
> > Which documents: GET /identityGovernance/lifecycleWorkflows/workflows/{workflowId}/userProcessingResults/{userProcessingResultId}/taskProcessingResults
> 
> Awesome! Thanks, @OWinfreyATL. I didn't notice the other file exists. I then recommend that you add `GET /identityGovernance/lifecycleWorkflows/workflows/{workflowId}/runs/{runId}/userProcessingResults/{userProcessingResultId}/taskProcessingResults` as an additional syntax in [that doc](https://learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-list-taskprocessingresults?view=graph-rest-beta&tabs=http) and some explainer - especially if the two URLs return different (like a subset of) results.

Hey @FaithOmbongi . I havent removed the other file yet, but added portions of it to the new article as you suggested. Would the changes made [here](https://review.learn.microsoft.com/en-us/graph/api/identitygovernance-userprocessingresult-list-taskprocessingresults?view=graph-rest-beta&branch=pr-en-us-19787&tabs=http) be the way to go?

thanks again!

Ortagus

2023-01-27 16:39 UTC, FaithOmbongi requested changes
Hi @OWinfreyATL - Yep, the changes you've made are the way to go. I've just highlighted some minor issues to resolve.

2023-01-27 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-userprocessingresult-list-taskprocessingresults.md
> +GET https://graph.microsoft.com/beta/IdentityGovernance/lifecycleWorkflows/workflows/14879e66-9ea9-48d0-804d-8fea672d0341/runs/72885f91-2cf0-44b1-b3ed-bd145af0192c/userProcessingResults/78b83505-6967
nit
```suggestion
GET https://graph.microsoft.com/beta/identityGovernance/lifecycleWorkflows/workflows/14879e66-9ea9-48d0-804d-8fea672d0341/runs/72885f91-2cf0-44b1-b3ed-bd145af0192c/userProcessingResults/78b83505-6967-4168-a7ea-4921c0543ce9/taskProcessingResults
```
```suggestion
GET https://graph.microsoft.com/beta/IdentityGovernance/lifecycleWorkflows/workflows/14879e66-9ea9-48d0-804d-8fea672d0341/runs/72885f91-2cf0-44b1-b3ed-bd145af0192c/userProcessingResults/78b83505-6967-4168-a7ea-4921c0543ce9/taskProcessingResults
```

2023-01-27 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-userprocessingresult-list-taskprocessingresults.md
> +  "name": "lifecycleworkflows_list_workflow_userprocessingresult_taskprocessingresult_select"
Make sure all the names are unique to avoid conflicts in autogenerated snippets

2023-01-27 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-userprocessingresult-list-taskprocessingresults.md
> +  "name": "lifecycleworkflows_list_workflow_userprocessingresult_taskprocessingresult_select"
Same comment

2023-01-27 16:39 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-userprocessingresult-list-taskprocessingresults.md
> +GET https://graph.microsoft.com/beta/identityGovernance/lifecycleWorkflows/workflows/15239232-66ed-445b-8292-2f5bbb2eb833/runs/e65e08a0-d68d-41dc-915b-8c4019af5cc2/userProcessingResults/40efc576-840f
nit
```suggestion
GET https://graph.microsoft.com/beta/identityGovernance/lifecycleWorkflows/workflows/15239232-66ed-445b-8292-2f5bbb2eb833/runs/e65e08a0-d68d-41dc-915b-8c4019af5cc2/userProcessingResults/40efc576-840f-47d0-ab95-5abca800f8a2/taskProcessingResults?$select=id,failureReason,processingStatus,subject,task
```
```suggestion
GET https://graph.microsoft.com/beta/identityGovernance/lifecycleWorkflows/workflows/15239232-66ed-445b-8292-2f5bbb2eb833/runs/e65e08a0-d68d-41dc-915b-8c4019af5cc2/userProcessingResults/40efc576-840f-47d0-ab95-5abca800f8a2//taskProcessingResults?$select=id,failureReason,processingStatus,subject,task
```

2023-01-27 16:39 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +                - name: List task processing results
Remember to remove this reference and the file

2023-01-27 16:39 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.LCM.json
> +    {
Hmm, I think we can avoid the changelog in this PR. It's just adding a new syntax; You haven't really introduced a new operation like the previous PR.

2023-01-30 18:41 UTC, FaithOmbongi approved these changes
Just one hanging statement to resolve.

2023-01-30 18:41 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-userprocessingresult-get.md
> +GET
Runaway statement?

2023-01-31 03:37 UTC, merged