introduce a new set APIs to create/update/delete page sections
microsoftgraph/microsoft-graph-docs pull request #19844
Opened 2023-01-11 08:46 UTC by sangle7

2023-01-12 10:37 UTC, liun27 commented on api-reference/beta/api/horizontalsection-delete.md
> +|Delegated (work or school account) | Sites.ReadWrite.All    |
align the "|"?

2023-01-12 10:37 UTC, liun27 commented on api-reference/beta/api/horizontalsection-create.md
> +| Content-Type  | application/json. Required. |
I am not sure whether we should use `pplication/json;odata.metadata=none` here?

2023-01-12 10:37 UTC, liun27 commented on api-reference/beta/api/verticalsection-get.md
> +    "@odata.type": "#microsoft.graph.textWebPart",
do we still want to document odata here?

2023-01-12 10:37 UTC, liun27 commented on api-reference/beta/api/verticalsection-update.md
> +  "webparts":[
will response carry the body if no expand option provided?

2023-01-17 06:05 UTC, sangle7 commented on api-reference/beta/api/horizontalsection-create.md
> +| Content-Type  | application/json. Required. |
No we don't need the header here

2023-02-02 15:01 UTC, Danielabom commented
Removed the "content review in progress" label and reached out to the author to get info.

2023-02-03 17:59 UTC, Danielabom commented on api-reference/beta/api/verticalsection-create.md
> +---
@sangle7, please update the file name accordingly. Here's a link to the guidelines: [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming]

2023-02-03 18:00 UTC, Danielabom commented on api-reference/beta/api/verticalsection-create.md
> +description: "Create a verticalSection in page"
```suggestion
description: "Create a verticalSection in a page"
```

2023-02-03 18:10 UTC, Danielabom commented on api-reference/beta/api/verticalsection-delete.md
> +# Delete a vertical section from a page
Can we leave this as "Delete verticalSection"? Or is there a reason we need to specify that we are deleting a vertical from a page?

2023-02-03 18:12 UTC, Danielabom commented on api-reference/beta/api/verticalsection-delete.md
> +Removes a [verticalSection][] from the [sitePage][]
Please add the links of the resources.

2023-02-03 18:13 UTC, Danielabom commented on api-reference/beta/api/verticalsection-delete.md
> +[verticalSection]: ../resources/verticalSection.md
Please insert the links in line 16 accordingly.

2023-02-03 18:13 UTC, Danielabom commented on api-reference/beta/api/verticalsection-delete.md
> +[sitePage]: ../resources/sitepage.md
Please insert the link in line 16 accordingly.

2023-02-03 18:20 UTC, Danielabom commented on api-reference/beta/api/verticalsection-delete.md
> +
Please confirm there isn't any info to add in the ## Request headers section.

2023-02-03 18:21 UTC, Danielabom commented on api-reference/beta/api/verticalsection-delete.md
> +If successful, this call returns a `204 No Content` response to indicate that the resource was deleted and there was nothing to return.
```suggestion
If successful, this call returns a `204 No Content`. It does not return anything in the response body.
```

2023-02-03 19:48 UTC, Danielabom commented on api-reference/beta/api/horizontalsection-create.md
> +---
Please update the file name accordingly. Here's a link to the guidelines: [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming]

2023-02-03 19:48 UTC, Danielabom commented on api-reference/beta/api/horizontalsection-create.md
> +description: "Create a horizontalSection in page"
```suggestion
description: "Create a horizontalSection in a page"
```

2023-02-03 19:50 UTC, Danielabom commented on api-reference/beta/api/horizontalsection-delete.md
> +# Delete a horizontal section from a page
Can we leave this as "Delete horizontalSection"? Or is there a reason we need to specify that we are deleting a horizontal section from a page?

2023-02-03 19:51 UTC, Danielabom commented on api-reference/beta/api/horizontalsection-delete.md
> +Removes a [horizontalSection][] from the [sitePage][]
Please insert the links to the resources.  I believe the links are below.

2023-02-03 19:52 UTC, Danielabom commented on api-reference/beta/api/horizontalsection-delete.md
> +
I just want to make sure that we don't need the ## Request headers section. Do we?

2023-02-03 20:02 UTC, Danielabom requested changes
Thank you for working on this PR @sangle7. Please review my comments.

2023-02-08 06:43 UTC, sangle7 commented on api-reference/beta/api/horizontalsection-delete.md
> +
Yes, we won't need specfic headers when calling `delete`

2023-02-21 18:40 UTC, Danielabom commented
Hi @sangle7, I wanted to follow up on this PR. Please review my comments, thanks!

2023-02-23 07:27 UTC, sangle7 commented
> Hi @sangle7, I wanted to follow up on this PR. Please review my comments, thanks!

Thanks @Danielabom. Will take a look soon

2023-02-26 13:48 UTC, sangle7 commented on api-reference/beta/api/horizontalsection-delete.md
> +
But it looks good to me to have a ## Request headers section mentioned that we only need the 'Authorization' header

2023-02-26 13:48 UTC, sangle7 commented on api-reference/beta/api/verticalsection-delete.md
> +
Updated

2023-02-26 13:50 UTC, sangle7 commented on api-reference/beta/api/horizontalsection-create.md
> +---
Thanks, renamed to 'sitepage-post-horizontalsection'

2023-02-26 13:51 UTC, sangle7 commented on api-reference/beta/api/verticalsection-create.md
> +---
Thanks, renamed to 'sitepage-post-verticalsection'

2023-02-26 13:53 UTC, sangle7 commented
Hi @Danielabom, I addressed your comments. Could you help to take a look again? Thanks!

2023-02-28 01:07 UTC, Danielabom commented
@sangle7, I noticed you've been making changes. Please change the label to "review feedback addressed" as soon as you feel ready. Thanks :)

2023-03-01 16:48 UTC, Danielabom approved these changes
Thank you for working on this PR @sangle7. PR approved.

2023-03-02 18:43 UTC, Danielabom commented
@sangle7, just one more thing. There are some build conflicts. Please review.

2023-03-14 22:32 UTC, Danielabom commented
@sangle7, friendly reminder to add the "ready to merge" label to this PR as soon as you are ready to publish. Thanks!

2023-04-12 02:50 UTC, sangle7 commented
Hey folks, We're waiting for code changes reach prod as well as the schema change. It might take longer since we want several features to go alive as the same time.

2023-07-06 03:53 UTC, Lauragra commented on api-reference/beta/api/horizontalsection-delete.md
> +# Delete horizontal section from a page
Please change the title and H1 to "Delete horizonalSection".

2023-07-06 03:54 UTC, Lauragra commented on api-reference/beta/api/horizontalsection-delete.md
> +Removes a [horizontalSection]( ../resources/horizontalSection.md) from the [sitePage](../resources/sitepage.md).
Please revise as follows:
Remove a [horizontalSection](../resources/horizontalsection.md) from a [sitePage](../resources/sitepage.md).

2023-07-06 03:55 UTC, Lauragra commented on api-reference/beta/api/horizontalsection-delete.md
> +##### Request
Please change the request and response sections to H3s - ###.

2023-07-06 03:58 UTC, Lauragra commented on api-reference/beta/api/verticalsection-delete.md
> +# Delete vertical section from a page
Please update the title and H1 to: "Delete verticalSection".

2023-07-06 03:58 UTC, Lauragra commented on api-reference/beta/api/verticalsection-delete.md
> +Removes a [verticalSection](../resources/verticalSection.md) from the [sitePage](../resources/sitepage.md).
Revise as:
Remove a [verticalSection](../resources/verticalsection.md) from a [sitePage](../resources/sitepage.md).

2023-07-06 03:59 UTC, Lauragra commented on api-reference/beta/api/verticalsection-delete.md
> +##### Request
Changes these to H3s.

2023-07-06 04:00 UTC, Lauragra commented on api-reference/beta/resources/horizontalsection.md
> +| [Create horizontalSection](../api/sitepage-post-horizontalsection.md)    | [horizontalSection](../resources/horizontalsection.md)            | Create a new [horizontalSection](../resources/horizont
We should list the operations in this order: List, Create, Get, Update, Delete.

2023-07-06 04:00 UTC, Lauragra commented on api-reference/beta/resources/verticalsection.md
> +| [Create verticalSection](../api/sitepage-post-verticalsection.md)    | [verticalSection](../resources/verticalsection.md)            | Create a new [verticalSection](../resources/verticalsection.md
Update the order here too: List, Create, Get, Update, Delete.

2023-07-06 04:01 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: Create
Please update here too for consistency - move the Create before the Get entry in both sections.

2023-07-07 01:59 UTC, merged