Execution Scope API
microsoftgraph/microsoft-graph-docs pull request #19864
Opened 2023-01-12 13:26 UTC by OWinfreyATL

2023-01-20 17:28 UTC, AlexFilipin commented on api-reference/beta/api/identitygovernance-list-executionscope.md
> +Get the user resources for which a workflow has run, or will run, for.
@OWinfreyATL We should add more details here based on the email thread information

2023-01-20 17:48 UTC, AlexFilipin commented on api-reference/beta/api/identitygovernance-list-executionscope.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users",
@OWinfreyATL  This looks like a reduced set of attributes that got returned for the user, was this example run with. I just tested and my response looks different. no matter if its done with User.ReadBasic.All or User.Read.All

2023-02-01 09:58 UTC, FaithOmbongi requested changes
Thank you @OWinfreyATL for your work on this PR. I've left suggestions inline. A few things to call out:
- Permissions: I've asked a few questions and shared options. Please look at them.
- File name changes: identitygovernance-list-executionscope.md => workflow-list-executionscope.md

2023-02-01 09:58 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-list-executionscope.md
> +### Example 1: Retrieve the execution scope (users that fall under scope to be processed) of a workflow
```suggestion
### Example 1: Retrieve the users that fall in scope of a workflow
```

2023-02-01 09:58 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-list-executionscope.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users(id)",
nit: I think this would indicate the actual ID instead of (id). But I stand corrected.

2023-02-01 09:58 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.LCM.json
> +          "Target": "workflowExecutionConditions"
workflowExecutionConditions is a complex type that can't expose methods. The closest is linking to the workflow object.
```suggestion
          "Description": "Added the **List** operation to [retrieve users that are in scope of execution conditions of a workflow](https://learn.microsoft.com/en-us/graph/api/identitygovernance-list-executionscope?view=graph-rest-beta) in Lifecycle Workflows.",
          "Target": "workflow"
```

2023-02-02 01:05 UTC, OWinfreyATL commented on api-reference/beta/api/identitygovernance-list-executionscope.md
> +|Application|LifecycleWorkflows.Read.All, LifecycleWorkflows.ReadWrite.All and User.Read.All|
I was able to confirm that I am able to get a reply and response without users :)

2023-02-02 07:23 UTC, FaithOmbongi approved these changes

2023-02-03 03:40 UTC, merged