add chat history flag to onlinemeeting
microsoftgraph/microsoft-graph-docs pull request #19895
Opened 2023-01-16 19:01 UTC by yuyaolian-msft

2023-04-12 17:05 UTC, Danielabom commented on api-reference/beta/resources/onlinemeeting.md
> +| shareMeetingChatHistoryDefault | [meetingChatHistoryDefaultMode](#meetingchathistorydefaultmode-values) | Specifies whether meeting chat history is shared with participants. |
Please see step 2 on this wiki and update the enum accordingly: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

2023-04-12 17:05 UTC, Danielabom commented on api-reference/beta/resources/onlinemeeting.md
> +| unknownFutureValue | Unknown future value.                                                  |
Please see step 2 on this wiki and update the enum accordingly: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

2023-04-12 17:06 UTC, Danielabom requested changes
Thank you for working on this PR @yuyaolian-msft. I added a couple of comments, please review them.

2023-04-12 20:22 UTC, yuyaolian-msft commented
Hello @Danielabom I have updated the doc per your comment, please let me know if there are any other concerns. Thanks!

2023-04-13 00:48 UTC, Danielabom approved these changes
@yuyaolian-msft , thanks for reviewing my comments. PR approved.

2023-04-20 00:44 UTC, Danielabom commented
@yuyaolian-msft, do not forget to add the "ready to merge" label as soon as you are ready to publish.

2023-04-21 01:20 UTC, merged