requestSignatureVerification property added to Application Page v1.0
microsoftgraph/microsoft-graph-docs pull request #19894
Opened 2023-01-16 18:30 UTC by rahul-nagraj

2023-03-08 08:33 UTC, FaithOmbongi commented
Waiting for the API.md and schema PR links to be added to the content review work item.

2023-03-10 07:16 UTC, msewaweru commented
@rahul-nagraj - the link to the schema PR takes me to the api.md while the API.md link is not the actual PR link. Please update the links on the [work item](https://dev.azure.com/msft-skilling/Content/_workitems/edit/69030/)  accordingly.

2023-03-14 10:29 UTC, msewaweru requested changes
@rahul-nagraj - Thanks for the work on this PR.

 I have reviewed it and here are the suggested updates:

1. The properties for the requestsignatureVerification resource differ between the schema and the API.md. Consider updating the API.md file for future reference.
2. Remove the preview tag, if any, on docs.

2023-03-14 10:29 UTC, msewaweru commented on api-reference/v1.0/resources/requestsignatureverification.md
> +|allowedWeakAlgorithms|weakAlgorithms|Specifies whether this application accepts weak algorithms. <br><br> The possible values are: `rsaSha1`, `unknownFutureValue`.|
The description of the property can be interpreted as a boolean type.  Also, consider updating the api.md file for future references as it has a difference in properties defined.
```suggestion
|allowedWeakAlgorithms|weakAlgorithms|Specifies which weak algorithms are allowed. <br><br> The possible values are: `rsaSha1`, `unknownFutureValue`.|
```

2023-03-24 18:15 UTC, rahul-nagraj commented
#feedback-addressed

2023-03-27 14:24 UTC, FaithOmbongi requested changes
Hi @rahul-nagraj - just one change. Please add the new property to the JSON representation section of the application.md file.

2023-03-27 15:27 UTC, FaithOmbongi approved these changes
Hi @rahul-nagraj - LGTM! I've only pushed one commit to change the changelog to "Applications"

Thank you @msewaweru !

2023-03-27 16:17 UTC, rahul-nagraj commented
#sign-off

2023-03-28 02:13 UTC, merged