Add Teams Team Report
microsoftgraph/microsoft-graph-docs pull request #19900
Opened 2023-01-17 10:34 UTC by airicaruss

2023-01-18 00:56 UTC, Danielabom commented
Reached out to the author to get info.

2023-01-18 20:01 UTC, Danielabom commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +title: "reportRoot: getTeamsTeamCounts"
Please add the method to the methods table of the respective topic,

2023-01-18 23:28 UTC, Danielabom commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +description: "Get the Teams Team count by Teams type."
We need to make capitalization changes, I suggest:
```suggestion
description: "Get the Teams team count by teams type."
```

2023-01-18 23:29 UTC, Danielabom commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +Get the Teams Team count by Teams type.
We need to make capitalization changes, I suggest:
```suggestion
Get the Teams team count by team type.
```

2023-01-18 23:31 UTC, Danielabom commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +| period    | string | Specifies the length of time over which the report is aggregated. The supported values for {period_value} are: `D7`, `D30`, `D90`, and `D180`. These values follow the format D*
```suggestion
| period    | string | Specifies the length of time over which the report is aggregated. The supported values for {period_value} are: `D7`, `D30`, `D90`, and `D180`. These values follow the format D*n*, where *n* represents the number of days over which the report is aggregated. Required. |
```

2023-01-18 23:33 UTC, Danielabom commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +If successful, this method returns a `302 Found` response that redirects to a preauthenticated download URL for the report. That URL can be found in the `Location` header in the response.
```suggestion
If successful, this method returns a `302 Found` response that redirects to a pre-authenticated download URL for the report. That URL can be found in the `Location` header in the response.
```

2023-01-18 23:34 UTC, Danielabom commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +Preauthenticated download URLs are only valid for a short period of time (a few minutes) and do not require an `Authorization` header.
```suggestion
Pre-authenticated download URLs are only valid for a short period (a few minutes) and do not require an `Authorization` header.
```

2023-01-18 23:38 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the [getTeamsTeamCounts](https://learn.microsoft.com/graph/api/reportroot-getTeamsTeamCounts?view=graph-rest-beta) method.",
The description must link the method to its resource. Please see example #6 here: [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog]

2023-01-18 23:39 UTC, Danielabom requested changes
Hi @airicaruss, thank you for working on this PR. I added some comments; please review them. 
Thanks!

2023-01-19 10:34 UTC, airicaruss commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +title: "reportRoot: getTeamsTeamCounts"
Added the function to the table

2023-01-19 10:35 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the [getTeamsTeamCounts](https://learn.microsoft.com/graph/api/reportroot-getTeamsTeamCounts?view=graph-rest-beta) method.",
Added the description

2023-01-19 10:35 UTC, airicaruss commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +description: "Get the Teams Team count by Teams type."
Fixed

2023-01-19 10:36 UTC, airicaruss commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +Get the Teams Team count by Teams type.
Fixed

2023-01-19 10:36 UTC, airicaruss commented
@Danielabom Thank you for your comments. I have fixed the comments. Please let me know if you have any other comments

2023-01-19 15:09 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the [getTeamsTeamCounts](https://learn.microsoft.com/graph/api/reportroot-getTeamsTeamCounts?view=graph-rest-beta) method to [MicrosoftTeamsTeamActivityReport](https://lear
```suggestion
			  "Description": "Added the [getTeamsTeamCounts](https://learn.microsoft.com/graph/api/reportroot-getTeamsTeamCounts?view=graph-rest-beta) method to the [MicrosoftTeamsTeamActivityReport](https://learn.microsoft.com/en-us/graph/api/resources/microsoft-teams-team-usage-reports?view=graph-rest-beta) resource.",
```

2023-01-19 15:11 UTC, Danielabom approved these changes
@airicaruss, thanks for the quick follow-up. PR approved.

2023-01-21 04:03 UTC, Lauragra commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +## Response
We are missing the required H2 section "Request body". API topics adhere to a defined structure so that users can easily find the information they're looking for. Please add the missing section.

2023-01-21 04:17 UTC, Lauragra commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +Get the Teams team count by team type.
I suggest that we reword this description to avoid using the word "team" three times and help clarify this statement a bit. For example, would this suggested revision be accurate: 

"Get the number of teams of a particular type in an instance of Microsoft Teams."

Also, how do they specify the team "type"?

2023-01-21 04:18 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: Get team team counts
I think that we can shorten this TOC entry to "Get team counts".

2023-01-21 04:29 UTC, Lauragra commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the [getTeamsTeamCounts](https://learn.microsoft.com/graph/api/reportroot-getTeamsTeamCounts?view=graph-rest-beta) method to the [MicrosoftTeamsTeamActivityReport](https://
Is that an actual resource name? It appears to be linking to what looks like a concept topic/anchor for that section of the TOC. Please clarify this changelog entry.

2023-01-25 03:24 UTC, Lauragra commented
@airicaruss , please see my comments on this PR and address them; this is currently blocking publishing. Thanks!

2023-01-26 03:03 UTC, Lauragra commented
@airicaruss , FYI, I've removed the ready to merge label. When you get a chance to address the comments, please set ready to merge again. Thanks.

2023-01-30 09:45 UTC, airicaruss commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +Get the Teams team count by team type.
The type could be 'Private Teams', 'Active Private Teams', 'Public Teams', 'Active Public Teams'

2023-01-30 09:49 UTC, airicaruss commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +## Response
Added

2023-01-30 19:14 UTC, Lauragra commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +Get the Teams team count by team type.
@airicaruss , where do we describe this in the docs? Is there a place that we can link to?

2023-02-07 09:58 UTC, airicaruss commented
@Lauragra could you please let me know if there is any other change required from my side?

2023-02-07 21:59 UTC, Lauragra commented on api-reference/beta/api/reportroot-getteamsteamcounts.md
> +Get the number of teams of a particular type in an instance of Microsoft Teams.
Can you provide a link here to where we list the applicable types of teams?

2023-02-07 22:00 UTC, Lauragra commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the [getTeamsTeamCounts](https://learn.microsoft.com/graph/api/reportroot-getTeamsTeamCounts?view=graph-rest-beta) method to the [MicrosoftTeamsTeamActivityReport](https://
The link to MicrosoftTeamsTeamActivityReport that we're calling a resource is not a resource. It's an overview topic. Please clarify this changelog entry.

2023-02-21 18:38 UTC, Danielabom commented
@airicaruss, Laura Graham added some feedback. Please review it. Thanks!

2023-02-24 10:45 UTC, airicaruss commented
> @airicaruss, Laura Graham added some feedback. Please review it. Thanks!

@Danielabom could you please help with my comment?

2023-03-01 03:32 UTC, Lauragra commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the [getTeamsTeamCounts](https://learn.microsoft.com/graph/api/reportroot-getTeamsTeamCounts?view=graph-rest-beta) method to the **MicrosoftTeamsTeamActivityReport** resour
Please verify the name of the resource here - the binding parameter in the CSDL is reportRoot and I'm not finding a resource named MicrosoftTeamsTeamActivityReport. I think we have an issue with the reportRoot resource type topic not linking to the functions that have the reportRoot binding type. Also, the reportRoot resource topic is not currently surfaced in the TOC. @airicaruss  and @Danielabom , can you please sort this out? Thanks.

2023-03-06 06:42 UTC, airicaruss commented
Hi @Lauragra , could you please help to review and comment if there is any further changes required?

2023-03-06 18:36 UTC, Lauragra commented
> Hi @Lauragra , could you please help to review and comment if there is any further changes required?

Hi @airicaruss , I had one remaining comment about clarifying/linking to the types of teams. I'm not sure what that means. Do you think it will be clear to your customers? If you don't plan to fix, we can approve and publish this PR. Thanks.

2023-03-07 03:38 UTC, airicaruss commented
> out clarifying/lin

Is there any 

> > Hi @Lauragra , could you please help to review and comment if there is any further changes required?
> 
> Hi @airicaruss , I had one remaining comment about clarifying/linking to the types of teams. I'm not sure what that means. Do you think it will be clear to your customers? If you don't plan to fix, we can approve and publish this PR. Thanks.

Is there any suggestion if we describe it in another way? @Zhiliqiao888 need your confirm if this description is good for publish.

2023-03-16 07:28 UTC, airicaruss commented
> to

@Lauragra  synced internally and we would like to get this doc checked in first. We don't have good idea to modify the description now. We will optimize the doc later if customer found it confusing. Could you please help to approve and merge this change?

2023-03-16 22:25 UTC, Lauragra approved these changes

2023-03-17 03:18 UTC, merged