Add Group Report Change
microsoftgraph/microsoft-graph-docs pull request #19902
Opened 2023-01-17 11:08 UTC by airicaruss

2023-01-26 21:52 UTC, Danielabom requested changes
Thank you for working on this PR @airicaruss . I have a couple of questions. The api.md shows that you are adding properties, but they appear as methods in the changelog and they are not listed in the resource file. 
On the other hand, the methods are not listed in the resource file or the changelog.

2023-01-30 10:09 UTC, airicaruss commented
> Thank you for working on this PR @airicaruss . I have a couple of questions. The api.md shows that you are adding properties, but they appear as methods in the changelog and they are not listed in the resource file. On the other hand, the methods are not listed in the resource file or the changelog.

@Danielabom updated the change to 'Property'. Please let me know if further change required

2023-01-31 15:45 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsChannelMessages**, **teamsMeetingsOrganized** property to the **getOffice365GroupsActivityCounts** resource.",
One property per entry and the correct format in the description is: "Added the **property name** property to the [entity](https://learn.microsoft.com/en-us/graph/api/resources/entity?view=graph-rest-beta) resource.",

2023-01-31 15:58 UTC, Danielabom requested changes
@airicaruss, please read my comments. 
Based on the CSDL, these new properties belong to an entity called "office365GroupsActivityDetail", so please update the resource file.

2023-01-31 15:58 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsChannelMessagesCount**, **teamsMeetingsOrganizedCount** property to the **getOffice365GroupsActivityDetail** resource.",
Please see my comments on the entry above.

2023-01-31 15:58 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityDetail"
Please see my comments on the entry above.

2023-02-07 10:39 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "ChangedApiName": "getOffice365GroupsActivityCounts",
Fixed

2023-02-07 10:39 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsChannelMessages**, **teamsMeetingsOrganized** property to the **getOffice365GroupsActivityCounts** resource.",
Fixed

2023-02-07 10:42 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityCounts"
The target resource is what I listed here. This is the CSDL. I found the doc said I can put the resource name here. Should I add some different value here? https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads?path=/Workloads/Microsoft.O365Reporting/override/schema-Prod-beta.csdl&version=GC4872263e3a2ab3f080eceeedc9de37e1cf6a993b

2023-02-07 10:43 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "ChangedApiName": "getOffice365GroupsActivityDetail",
Fixed

2023-02-07 10:43 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsChannelMessagesCount**, **teamsMeetingsOrganizedCount** property to the **getOffice365GroupsActivityDetail** resource.",
Fixed

2023-02-08 10:50 UTC, airicaruss commented
@Danielabom please let me know if you have any other questions.

2023-02-21 18:21 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityCounts"
Hi @airicaruss, your CSDL mentions that the entity resource name is **"office365GroupsActivityDetail**".
If you go to the topic [office365GroupsActivityDetail resource type - Microsoft Graph beta | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitydetail?view=graph-rest-beta), you'll find a Properties table. New properties should be listed there.

2023-02-21 18:23 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganized** property to the [getOffice365GroupsActivityCounts(https://learn.microsoft.com/en-us/graph/api/reportroot-getoffice365groupsactivitycounts?vie
On the other hand, **getOffice365GroupsActivityCounts** is not a resource; it is a function. Your description indicates something different.

2023-02-21 18:25 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityDetail"
Global comment: Please update your target.

2023-02-21 18:34 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganizedCount** property to the [getOffice365GroupsActivityDetail(https://learn.microsoft.com/en-us/graph/api/reportroot-getoffice365groupsactivitydetai
**getOffice365GroupsActivityDetail** is not a resource but a function. And this property belongs to an entity/resource called **office365GroupsActivityDetail**

2023-02-21 18:35 UTC, Danielabom requested changes
hi @airicaruss, please review my comments.

2023-02-22 12:24 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganized** property to the [getOffice365GroupsActivityCounts(https://learn.microsoft.com/en-us/graph/api/reportroot-getoffice365groupsactivitycounts?vie
Thank you for your comment. Fixed

2023-02-22 12:24 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityDetail"
Thank you for your comment. Fixed

2023-02-22 12:24 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganizedCount** property to the [getOffice365GroupsActivityDetail(https://learn.microsoft.com/en-us/graph/api/reportroot-getoffice365groupsactivitydetai
Thank you for your comment. Fixed

2023-02-22 12:38 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganizedCount** property to the [getOffice365GroupsActivityDetail(https://learn.microsoft.com/en-us/graph/api/reportroot-getoffice365groupsactivitydetai
@Danielabom updated the resource name. Could you please check?

2023-02-24 00:38 UTC, Danielabom requested changes
One more question, is there a particular reason why you are adding the properties to operations and not the resources?

2023-02-24 10:44 UTC, airicaruss commented
> One more question, is there a particular reason why you are adding the properties to operations and not the resources?

@Danielabom no specific reason. Do you suggest to make changes on resource? What should I do in this scenario? Should I make change changes to this file as well? https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitydetail?view=graph-rest-beta

2023-03-01 03:13 UTC, Lauragra commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityDetail"
I think that per Dani's comment, the value of the Target field should be the resource name, not the function name. Also, we need to update the two resource topics to include the new properties.

2023-03-02 12:42 UTC, airicaruss commented
> 

@Danielabom updated the resource file. Please take a look.

2023-03-02 18:46 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityDetail"
```suggestion
			  "Target": "Office365GroupsActivityDetail"
```

2023-03-02 18:47 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganizedCount** property to the [office365GroupsActivityDetail(https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitydetail?view=
```suggestion
			  "Description": "Added the **teamsMeetingsOrganizedCount** property to the [office365GroupsActivityDetail] (https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitydetail?view=graph-rest-beta) resource.",
```

2023-03-02 18:53 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganizedCount** property to the [office365GroupsActivityDetail] (https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitydetail?vie
```suggestion
			  "Description": "Added the **teamsMeetingsOrganizedCount** property to the [office365GroupsActivityDetail](https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitydetail?view=graph-rest-beta) resource.",
```

2023-03-02 18:55 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityDetail"
```suggestion
			  "Target": "Office365GroupsActivityDetail"
```

2023-03-02 18:56 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityCounts"
```suggestion
			  "Target": "Office365GroupsActivityCounts"
```

2023-03-02 18:57 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Description": "Added the **teamsMeetingsOrganized** property to the [office365GroupsActivityCounts]https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitycounts?view=graph
```suggestion
			  "Description": "Added the **teamsMeetingsOrganized** property to the [office365GroupsActivityCounts](https://learn.microsoft.com/en-us/graph/api/resources/office365groupsactivitycounts?view=graph-rest-beta) resource.",
```

2023-03-02 18:58 UTC, Danielabom commented on changelog/Microsoft.O365Reporting.json
> +			  "Target": "getOffice365GroupsActivityCounts"
```suggestion
			  "Target": "Office365GroupsActivityCounts"
```

2023-03-02 19:56 UTC, Danielabom approved these changes
Applying changes and approving PR.

2023-03-03 03:42 UTC, merged