[Doc Improvement][Update List and Publish teamsApp]
microsoftgraph/microsoft-graph-docs pull request #19904
Opened 2023-01-17 11:45 UTC by v-ypalikila

Updated documentation for both for beta and v1, to be aligned with the schema mentioned [teamsApp resource](https://learn.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-beta).

Removed version property from JSON response.

2023-01-19 17:30 UTC, Danielabom commented
Reached out to the author to get info for Mike Dodaro.

2023-01-23 18:45 UTC, dodaromike commented
@Danielabom I can't see the schema, but assuming the version property is not in the TeamsApp entity, this PR is ready to merge.

2023-01-24 23:33 UTC, angelgolfer-ms commented on api-reference/beta/api/appcatalogs-list-teamsapps.md
> +
@v-ypalikila , FYI, there isn't a purpose of inserting blank lines like line 90, 95, and so on. 
The lines like 74, and 84-114, are all inserted by an internal tool that runs weekly to add or update these code snippets where necessary. 
Please take a look at this topic in the onboarding docs (CDK): https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211752/Generate-code-snippets

2023-01-24 23:39 UTC, angelgolfer-ms commented on api-reference/beta/api/appcatalogs-list-teamsapps.md
> +      "distributionMethod": "Organization"
Line 217:
@v-ypalikila , what is the purpose of this change?
If you look at the beta metadata, the distribution property is of type teamsAppDistributionMethod, which is an enum appropriately defined with values using camel case. 
As a matter of fact, all API terms in Microsoft Graph, including names of resources, methods, properties, enumerations, and enum values, should all use camel case.

So this change is inappropriate and may confuse users, even if beneath the covers, Microsoft Graph can handle this type of inconsistencies. On the other hand, docs should model the correct use.

2023-01-25 00:28 UTC, angelgolfer-ms requested changes
Hi @v-ypalikila , can you please take a look at my comments?
Seems to me the updates to teamsapp-publish.md are necessary, but not those for the list operation. 
Please clarify if there was something else you meant to fix.
Thanks.

2023-01-30 12:10 UTC, v-ypalikila commented on api-reference/beta/api/appcatalogs-list-teamsapps.md
> +      "distributionMethod": "Organization"
Removed the capital case for the distribution property. I will ensure to check and not submit such updates.

2023-02-22 20:38 UTC, dodaromike commented
It looks like @v-ypalikila has addressed changes requested by @angelgolfer-ms .  I will approve this PR.

2023-02-22 22:19 UTC, dodaromike commented
@v-ypalikila @angelgolfer-ms I will try to address the warnings before approving this PR.  The warnings are coming from main.

2023-02-23 22:16 UTC, dodaromike approved these changes

2023-03-16 03:30 UTC, Lauragra commented on api-reference/beta/api/teamsapp-publish.md
> +# [CSharp](#tab/csharp)
Why are you adding this tab and snippets? The SDK snippets are generated via the weekly snippet automation; we don't add the snippets to the topics manually. Please remove the manual snippets.

2023-05-25 03:03 UTC, Lauragra approved these changes

2023-05-25 03:10 UTC, merged