Update task within workflow API
microsoftgraph/microsoft-graph-docs pull request #19913
Opened 2023-01-17 16:33 UTC by OWinfreyATL

2023-01-18 04:11 UTC, Lauragra commented
@OWinfreyATL , please follow our content workflow process: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow

Before we set **ready to merge** on a PR, set the **ready for content review** label. A member of the docs v-team will review your PR, provide any feedback, and/or approve, and then we can publish. In this case, you will need an update to the changelog with this PR to mention the new method.

2023-01-18 18:12 UTC, FaithOmbongi requested changes
Thank you @OWinfreyATL for your work on this PR. I've left a few inline suggestions for fixes.
Also, add the Update operation to the [methods table](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-task?view=graph-rest-beta&branch=pr-en-us-19913#methods).

Is this an oversight from the initial docs PR or was this operation enabled recently? If the latter, please add the changelog. Because there wouldn't be a related schema update, I've added a sample changelist you can use 👇🏾; You can add the required missing parts to make up a complete changelog object.

```
{
      "Id": "7b152ed8-1442-4c0a-85df-9f0e7c1e4bb4",
      "ApiChange": "Method",
      "ChangedApiName": "PATCH",
      "ChangeType": "Addition",
      "Description": "Added the [update](https://learn.microsoft.com/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta) operation to the [task](https://learn.microsoft.com/graph/api/resources/identitygovernance-task?view=graph-rest-beta) resource.",
      "Target": "task"
    },
```

2023-01-18 18:12 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-task-update.md
> +# [HTTP](#tab/http)
nit
```suggestion
```

2023-01-18 18:12 UTC, FaithOmbongi commented on api-reference/beta/api/identitygovernance-task-update.md
> +}
Only show the two updatable properties. Otherwise, it will send the message to customers that all these properties are updatable

2023-01-18 18:12 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +              href: api/identitygovernance-task-update.md
Move this to the specified location

<img width="179" alt="image" src="https://user-images.githubusercontent.com/14026935/213259654-2e5c2437-9357-4ef6-86ee-940bf3c8fe37.png">

2023-01-19 22:17 UTC, OWinfreyATL commented
> Thank you @OWinfreyATL for your work on this PR. I've left a few inline suggestions for fixes. Also, add the Update operation to the [methods table](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-task?view=graph-rest-beta&branch=pr-en-us-19913#methods).
> 
> Is this an oversight from the initial docs PR or was this operation enabled recently? If the latter, please add the changelog. Because there wouldn't be a related schema update, I've added a sample changelist you can use 👇🏾; You can add the required missing parts to make up a complete changelog object.
> 
> ```
> {
>       "Id": "7b152ed8-1442-4c0a-85df-9f0e7c1e4bb4",
>       "ApiChange": "Method",
>       "ChangedApiName": "PATCH",
>       "ChangeType": "Addition",
>       "Description": "Added the [update](https://learn.microsoft.com/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta) operation to the [task](https://learn.microsoft.com/graph/api/resources/identitygovernance-task?view=graph-rest-beta) resource.",
>       "Target": "task"
>     },
> ```

Hey @FaithOmbongi 

Thanks! I was able to get most suggestions in. This one remains a tricky one though. Speaking with the PM Alex this call existed with our original push, but we did not include it because engineering still wanted to test it. Now that it has been tested, we are adding it to documentation. Would this be added to the changelist section of the changelog with the original ID used with every other item that originally was added to the list?

2023-01-20 07:56 UTC, FaithOmbongi commented
> > Thank you @OWinfreyATL for your work on this PR. I've left a few inline suggestions for fixes. Also, add the Update operation to the [methods table](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-task?view=graph-rest-beta&branch=pr-en-us-19913#methods).
> > Is this an oversight from the initial docs PR or was this operation enabled recently? If the latter, please add the changelog. Because there wouldn't be a related schema update, I've added a sample changelist you can use 👇🏾; You can add the required missing parts to make up a complete changelog object.
> > ```
> > {
> >       "Id": "7b152ed8-1442-4c0a-85df-9f0e7c1e4bb4",
> >       "ApiChange": "Method",
> >       "ChangedApiName": "PATCH",
> >       "ChangeType": "Addition",
> >       "Description": "Added the [update](https://learn.microsoft.com/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta) operation to the [task](https://learn.microsoft.com/graph/api/resources/identitygovernance-task?view=graph-rest-beta) resource.",
> >       "Target": "task"
> >     },
> > ```
> 
> Hey @FaithOmbongi
> 
> Thanks! I was able to get most suggestions in. This one remains a tricky one though. Speaking with the PM Alex this call existed with our original push, but we did not include it because engineering still wanted to test it. Now that it has been tested, we are adding it to documentation. Would this be added to the changelist section of the changelog with the original ID used with every other item that originally was added to the list?

Hi @OWinfreyATL - No, I recommend a new changelog record with new IDs and all. Don't update the original one.

2023-01-20 15:26 UTC, OWinfreyATL commented
> > > Thank you @OWinfreyATL for your work on this PR. I've left a few inline suggestions for fixes. Also, add the Update operation to the [methods table](https://review.learn.microsoft.com/en-us/graph/api/resources/identitygovernance-task?view=graph-rest-beta&branch=pr-en-us-19913#methods).
> > > Is this an oversight from the initial docs PR or was this operation enabled recently? If the latter, please add the changelog. Because there wouldn't be a related schema update, I've added a sample changelist you can use 👇🏾; You can add the required missing parts to make up a complete changelog object.
> > > ```
> > > {
> > >       "Id": "7b152ed8-1442-4c0a-85df-9f0e7c1e4bb4",
> > >       "ApiChange": "Method",
> > >       "ChangedApiName": "PATCH",
> > >       "ChangeType": "Addition",
> > >       "Description": "Added the [update](https://learn.microsoft.com/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta) operation to the [task](https://learn.microsoft.com/graph/api/resources/identitygovernance-task?view=graph-rest-beta) resource.",
> > >       "Target": "task"
> > >     },
> > > ```
> > 
> > 
> > Hey @FaithOmbongi
> > Thanks! I was able to get most suggestions in. This one remains a tricky one though. Speaking with the PM Alex this call existed with our original push, but we did not include it because engineering still wanted to test it. Now that it has been tested, we are adding it to documentation. Would this be added to the changelist section of the changelog with the original ID used with every other item that originally was added to the list?
> 
> Hi @OWinfreyATL - No, I recommend a new changelog record with new IDs and all. Don't update the original one.

Hey @FaithOmbongi if this change was present with the initial Public preview push, wouldnt any changelog I generate now for it be the exact same as the original one? Or are new ID's generated whenever I generate a changelog in Graphstudio?

2023-01-20 15:46 UTC, FaithOmbongi commented
> > > Hey @FaithOmbongi
> > > Thanks! I was able to get most suggestions in. This one remains a tricky one though. Speaking with the PM Alex this call existed with our original push, but we did not include it because engineering still wanted to test it. Now that it has been tested, we are adding it to documentation. Would this be added to the changelist section of the changelog with the original ID used with every other item that originally was added to the list?
> > 
> > 
> > Hi @OWinfreyATL - No, I recommend a new changelog record with new IDs and all. Don't update the original one.
> 
> Hey @FaithOmbongi if this change was present with the initial Public preview push, wouldnt any changelog I generate now for it be the exact same as the original one? Or are new ID's generated whenever I generate a changelog in Graphstudio?

Hi @OWinfreyATL - Unfortunately, you can't generate a changelog for a live schema, also because there isn't a related schema update. That's why you have to create the changelog manually. If you were to add the object to the previous changelog, you would have used the previous changelog's ID. But because we're adding as a new changelog object, we use a unique ID.

A general answer: New IDs are generated per schema PR build. So if your schema PR is rebuilt multiple times, for example when you push multiple commits or close/open, the changelogs would be generated with different GUIDs each time. Same applies when you generate the changelog locally.

2023-01-20 16:51 UTC, OWinfreyATL commented
> > > > Hey @FaithOmbongi
> > > > Thanks! I was able to get most suggestions in. This one remains a tricky one though. Speaking with the PM Alex this call existed with our original push, but we did not include it because engineering still wanted to test it. Now that it has been tested, we are adding it to documentation. Would this be added to the changelist section of the changelog with the original ID used with every other item that originally was added to the list?
> > > 
> > > 
> > > Hi @OWinfreyATL - No, I recommend a new changelog record with new IDs and all. Don't update the original one.
> > 
> > 
> > Hey @FaithOmbongi if this change was present with the initial Public preview push, wouldnt any changelog I generate now for it be the exact same as the original one? Or are new ID's generated whenever I generate a changelog in Graphstudio?
> 
> Hi @OWinfreyATL - Unfortunately, you can't generate a changelog for a live schema, also because there isn't a related schema update. That's why you have to create the changelog manually. If you were to add the object to the previous changelog, you would have used the previous changelog's ID. But because we're adding as a new changelog object, we use a unique ID.
> 
> A general answer: New IDs are generated per schema PR build. So if your schema PR is rebuilt multiple times, for example when you push multiple commits or close/open, the changelogs would be generated with different GUIDs each time. Same applies when you generate the changelog locally.

Got it! and one more question. My new changelog that I create would it be replacing Microsoft.AAD.LCM.Json or would I create a completely new json file and place it as its own file within the changelog folder?

2023-01-20 17:24 UTC, FaithOmbongi commented
> > > > > Hey @FaithOmbongi
> > > > > Thanks! I was able to get most suggestions in. This one remains a tricky one though. Speaking with the PM Alex this call existed with our original push, but we did not include it because engineering still wanted to test it. Now that it has been tested, we are adding it to documentation. Would this be added to the changelist section of the changelog with the original ID used with every other item that originally was added to the list?
> > > > 
> > > > 
> > > > Hi @OWinfreyATL - No, I recommend a new changelog record with new IDs and all. Don't update the original one.
> > > 
> > > 
> > > Hey @FaithOmbongi if this change was present with the initial Public preview push, wouldnt any changelog I generate now for it be the exact same as the original one? Or are new ID's generated whenever I generate a changelog in Graphstudio?
> > 
> > 
> > Hi @OWinfreyATL - Unfortunately, you can't generate a changelog for a live schema, also because there isn't a related schema update. That's why you have to create the changelog manually. If you were to add the object to the previous changelog, you would have used the previous changelog's ID. But because we're adding as a new changelog object, we use a unique ID.
> > A general answer: New IDs are generated per schema PR build. So if your schema PR is rebuilt multiple times, for example when you push multiple commits or close/open, the changelogs would be generated with different GUIDs each time. Same applies when you generate the changelog locally.
> 
> Got it! and one more question. My new changelog that I create would it be replacing Microsoft.AAD.LCM.Json or would I create a completely new json file and place it as its own file within the changelog folder?

Hi @OWinfreyATL - Oh, don't overwrite the existing changelog records. Instead, append to the file. I'll share with you a link to a short demo video via Teams.

2023-01-24 15:20 UTC, AlexFilipin approved these changes

2023-01-24 18:26 UTC, FaithOmbongi approved these changes
Hi @OWinfreyATL - I pushed a commit to move the changelog to be a standalone object before approving the PR.

2023-01-25 02:59 UTC, merged