Multigeo site enumeration API support
microsoftgraph/microsoft-graph-docs pull request #19923
Opened 2023-01-18 15:28 UTC by tushar20

2023-03-22 19:54 UTC, Danielabom commented
Contacted author to get info.

2023-03-30 00:25 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +---
The correct format for the file name is: sites-getallsites

2023-03-30 00:46 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +---
The correct file name for this operation would be: sites-getallsites

2023-03-30 01:13 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +title: "Enumerate sites across geographies"
```suggestion
title: "sites: getallsites"
```

2023-03-30 01:14 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +# Enumerate multigeo sites
```suggestion
# sites: getAllSites
```

2023-03-30 01:15 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +List all available [sites][] across geographies in an organization.
Please add the link to the resource. 
```

2023-03-30 01:17 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +For more guidance about building applications that use site discovery for scanning purposes please see https://aka.ms/scanguidance.
```suggestion
For more guidance about building applications that use site discovery for scanning purposes please see (https://aka.ms/scanguidance).
```

2023-03-30 01:23 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +[sites]: ../resources/site.md
I believe this link goes in line 14.

2023-03-30 01:24 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +
Please add the beta disclaimer.

2023-03-30 01:30 UTC, Danielabom commented on api-reference/v1.0/api/sites-list-all-rootsites-multigeo.md
> +---
Please see the comments I added for the beta version of this file.

2023-03-30 01:31 UTC, Danielabom commented on api-reference/v1.0/resources/site.md
> +| [List root sites across geographies][] |  collection of site  | List sites across all geographies in an organization
```suggestion
| [List root sites across geographies][] |  collection of site  | List sites across all geographies in an organization.
```

2023-03-30 01:33 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [getAllsites](https://learn.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta) method to the site resource to fetch all sites across all geographie
Please add the link to the resource. You may use example 7 on this wiki: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-03-30 01:35 UTC, Danielabom requested changes
Hi @tushar20, thank you so much for working on this PR. Please review my comments.

2023-03-30 14:52 UTC, Danielabom commented on api-reference/beta/api/sites-list-all-rootsites-multigeo.md
> +For more guidance about building applications that use site discovery for scanning purposes please see https://aka.ms/scanguidance.
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance.md).
```

2023-03-30 23:38 UTC, tushar20 commented
Hi @Danielabom, updated the PR with the suggested changes. Kindly take a look.

2023-04-03 13:38 UTC, Danielabom commented on api-reference/beta/api/sites-getallsites.md
> +For more guidance about building applications that use site discovery for scanning purposes please see <https://aka.ms/scanguidance>.
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance.md).
```

2023-04-03 13:42 UTC, Danielabom requested changes
@tushar20, the changes look good. Now that you have updated the file names. Please update the TOC for both versions accordingly. Here's our TOC wiki: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title)

2023-04-13 00:40 UTC, Danielabom commented
Following up on my previous comment: @tushar20, the changes look good. Now that you have updated the file names. Please update the TOC for both versions accordingly. Here's our TOC wiki: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title)

2023-04-20 00:43 UTC, Danielabom commented
@tushar20, please add the TOC as soon as you can. Thanks.

2023-05-04 01:36 UTC, Danielabom commented on api-reference/beta/api/sites-getallsites.md
> +author: tkanaujia
```suggestion
author: tushar20
```

2023-05-04 01:38 UTC, Danielabom commented on api-reference/beta/api/sites-getallsites.md
> +ms.date: 24/03/2023
```suggestion
ms.date: 5/3/2023
```

2023-05-04 01:39 UTC, Danielabom commented on api-reference/v1.0/api/sites-getallsites.md
> +author: tkanaujia
```suggestion
author: tushar20
```

2023-05-04 01:39 UTC, Danielabom commented on api-reference/v1.0/api/sites-getallsites.md
> +ms.date: 24/03/2023
```suggestion
ms.date: 5/3/2023
```

2023-05-04 02:04 UTC, Danielabom commented on api-reference/beta/toc.yml
> +          href: api/sites-getallsites.md
```suggestion
          href: api/site-getallsites.md
```

2023-05-04 02:12 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [getAllsites](https://learn.microsoft.com/en-us/graph/api/sites-getallsites?view=graph-rest-1.0) method to the [site](https://learn.microsoft.com/en-us/graph/api/r
```suggestion
          "Description": "Added the [getAllsites](https://learn.microsoft.com/en-us/graph/api/site-getallsites?view=graph-rest-1.0) method to the [site](https://learn.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0) resource.",
```

2023-05-04 02:33 UTC, Danielabom commented on api-reference/beta/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online.md).
```

2023-05-04 02:35 UTC, Danielabom commented on api-reference/v1.0/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online.md).
```

2023-05-04 02:39 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +[sites-getallsites.md]: sites-getallsites.md
```suggestion
[site-getallsites.md]: site-getallsites.md
```

2023-05-04 02:40 UTC, Danielabom commented on api-reference/v1.0/api/site-list.md
> +[sites-getallsites.md]: sites-getallsites.md
```suggestion
[site-getallsites.md]: site-getallsites.md
```

2023-05-04 02:41 UTC, Danielabom commented on api-reference/beta/resources/site.md
> +| [List root sites across geographies][]            | GET /sites/getAllSites                                      |
```suggestion
| [List root sites across geographies][]            | GET /site/getAllSites                                      |
```

2023-05-04 02:42 UTC, Danielabom commented on api-reference/v1.0/resources/site.md
> +[List root sites across geographies]: ../api/sites-getallsites.md
```suggestion
[List root sites across geographies]: ../api/site-getallsites.md
```

2023-05-04 02:44 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +If you want to list all sites across all geographies, refer to [sites-getallsites.md][].
```suggestion
If you want to list all sites across all geographies, refer to [site-getallsites.md][].
```

2023-05-04 02:45 UTC, Danielabom commented on api-reference/beta/resources/site.md
> +[List root sites across geographies]: ../api/sites-getallsites.md
```suggestion
[List root sites across geographies]: ../api/site-getallsites.md
```

2023-05-17 17:54 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +[site-getallsites.md]: site-getallsites.md
```suggestion
[getallsites]: ../api/site-getallsites.md
```

2023-05-17 17:55 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +If you want to list all sites across all geographies, refer to [site-getallsites.md][].
```suggestion
If you want to list all sites across all geographies, refer to [getallsites][../api/site-getallsites.md].
```

2023-05-17 18:01 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +[getallsites]: ../api/site-getallsites.md
```suggestion
[site-getallsites]: ../api/site-getallsites.md
```

2023-05-17 21:35 UTC, Danielabom commented on api-reference/beta/api/site-getallsites.md
> +GET /sites/getAllSites
```suggestion
GET /site/getAllSites
```

2023-05-17 21:36 UTC, Danielabom commented on api-reference/beta/api/site-getallsites.md
> +GET /sites/getAllSites
```suggestion
GET /site/getAllSites
```

2023-05-17 21:36 UTC, Danielabom commented on api-reference/v1.0/api/site-getallsites.md
> +GET /sites/getAllSites
```suggestion
GET /site/getAllSites
```

2023-05-17 21:37 UTC, Danielabom commented on api-reference/v1.0/api/site-getallsites.md
> +GET /sites/getAllSites
```suggestion
GET /site/getAllSites
```

2023-05-17 21:43 UTC, Danielabom commented on api-reference/v1.0/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](../concepts/scan-guidance?view=odsp-graph-online.md).
```

2023-05-17 21:44 UTC, Danielabom commented on api-reference/beta/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](../concepts/scan-guidance?view=odsp-graph-online.md).
```

2023-05-17 22:15 UTC, Danielabom commented on api-reference/beta/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](../concepts/scan-guidance?view=odsp-graph-online.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](../onedrive/developer/rest-api/concepts/scan-guidance.md).
```

2023-05-17 22:21 UTC, Danielabom commented on api-reference/v1.0/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](../concepts/scan-guidance?view=odsp-graph-online.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](../onedrive/developer/rest-api/concepts/scan-guidance.md).
```

2023-05-17 23:33 UTC, Danielabom commented on api-reference/beta/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](../onedrive/developer/rest-api/concepts/scan-guidance.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance).
```

2023-05-17 23:34 UTC, Danielabom commented on api-reference/v1.0/api/site-getallsites.md
> +For more details, see [Best practices for discovering files and detecting changes at scale](../onedrive/developer/rest-api/concepts/scan-guidance.md).
```suggestion
For more details, see [Best practices for discovering files and detecting changes at scale](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance).
```

2023-05-17 23:45 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +If you want to list all sites across all geographies, refer to [site-getallsites][../api/site-getallsites.md].
```suggestion
If you want to list all sites across all geographies, refer to [site-getallsites][].
```

2023-05-17 23:47 UTC, Danielabom commented on api-reference/beta/api/site-list.md
>  For more guidance about building applications that use site discovery for scanning purposes, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/con
```suggestion
For more guidance about building applications that use site discovery for scanning purposes, see [Best practices for discovering files and detecting changes at scale](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance).
```

2023-05-17 23:48 UTC, Danielabom commented on api-reference/v1.0/api/site-list.md
>  For more guidance about building applications that use site discovery for scanning purposes, see [Best practices for discovering files and detecting changes at scale](/onedrive/developer/rest-api/con
```suggestion
For more guidance about building applications that use site discovery for scanning purposes, see [Best practices for discovering files and detecting changes at scale](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance).
```

2023-05-17 23:52 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +[site-getallsites]: ../api/site-getallsites.md
```suggestion
[getallsites]: ../api/site-getallsites.md
```

2023-05-17 23:52 UTC, Danielabom commented on api-reference/v1.0/api/site-list.md
> +[site-getallsites]: ../api/site-getallsites.md
```suggestion
[getallsites]: ../api/site-getallsites.md
```

2023-05-18 00:08 UTC, Danielabom commented on api-reference/beta/api/site-list.md
> +If you want to list all sites across all geographies, refer to [site-getallsites][../api/site-getallsites.md].
```suggestion
If you want to list all sites across all geographies, refer to [site-getallsites][].
```

2023-05-18 00:09 UTC, Danielabom commented on api-reference/v1.0/api/site-list.md
> +If you want to list all sites across all geographies, refer to [site-getallsites][../api/site-getallsites.md].
```suggestion
If you want to list all sites across all geographies, refer to [site-getallsites][].
```

2023-05-19 14:38 UTC, Danielabom commented
Dear @tushar20 ,
I am reaching out to you today regarding the GitHub pull request #PR 19923 that we have been working on. We have noticed some build issues that need your attention to ensure the successful completion of the PR. As an FYi, I’ve fixed most of the issues, but need some collaboration from your side. 
These build issues are blocking the PR from being merged, and it is crucial that we resolve them as soon as possible. Your expertise and attention to detail are greatly appreciated in resolving these problems effectively.

To assist you in troubleshooting the build issues, I recommend the following steps:

1.	Review the error messages or logs provided to gain a deeper understanding of the problem.

2.	Examine the changes made in the PR and identify any potential conflicts or compatibility issues with the existing codebase.

3.	Verify that all necessary dependencies and libraries are correctly included and up to date.

4.	Attempt to reproduce the build issues locally to gain insights into their root causes.

5.	Make the necessary adjustments and modifications to address the identified build issues.

Once you have made the required fixes, please request a review and I’ll get the PR back. 

Thank you in advance for your prompt attention to these build issues.

2023-05-20 01:47 UTC, merged