Planner task completion requirements documentation beta
microsoftgraph/microsoft-graph-docs pull request #19952
Opened 2023-01-20 09:08 UTC by prasad5596

Documentation for planner task completion requirements

2023-01-28 00:11 UTC, TarkanSevilmis requested changes
Added a few comments.

2023-01-28 00:11 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerTaskCompletionRequirements.md
> +|unknownFutureValue|2|The unknownFutureValue for evolvable enum.|
There is a specific text that needs to be put here, see examples of other enums

2023-01-28 00:11 UTC, TarkanSevilmis commented on api-reference/beta/resources/plannerTaskCompletionRequirementDetails.md
> +This is the structure that stores requirements for the [plannerTask](plannertask.md) completion.
These should be written from the perspective of the consumer. What do I need to know so that I can successfully use this? What does this property mean for me?

2023-01-31 08:18 UTC, prasad5596 commented on api-reference/beta/resources/plannerChecklistRequirement.md
> +author: "TarkanSevilmis"
Copy paste :) will wix

2023-02-03 09:06 UTC, prasad5596 commented on api-reference/beta/resources/plannerTaskCompletionRequirements.md
> +|unknownFutureValue|2|The unknownFutureValue for evolvable enum.|
I have copied what i fount in other documentation

2023-02-07 08:30 UTC, prasad5596 commented on api-reference/beta/resources/plannerTaskCompletionRequirementDetails.md
> +This is the structure that stores requirements for the [plannerTask](plannertask.md) completion.
Rephrased it a bit. Does this look ok? Or should we explain on end to end usage of this field

2023-02-07 08:31 UTC, prasad5596 commented on api-reference/beta/resources/plannerTaskCompletionRequirementDetails.md
> +This is the structure that stores requirements for the [plannerTask](plannertask.md) completion.
![image](https://user-images.githubusercontent.com/16847728/217192561-cc763c1f-e43a-4281-8a43-050b86cea07e.png)

2023-04-04 05:07 UTC, JarbasHorst commented on api-reference/beta/resources/plannerchecklistrequirement.md
> +---
Please, include an update to the changelog file to surface the new changes (for example, plannerChecklistRequirement and plannerTaskCompletionRequirementDetails are new changes)  in the Microsoft Graph Changelog.

2023-04-04 05:09 UTC, JarbasHorst commented
Hello @prasad5596, I reviewed your PR and left one comment. Please, take a look when you will have time. Your PR is currently in draft mode. Can you please update the status to Open?

I cannot find your in Microsoft Teams. Can you please reach out to me via Teams and share with me there the CSDL and api.md files for your PR? Thanks :)

2023-04-06 11:00 UTC, prasad5596 commented on api-reference/beta/resources/plannerchecklistrequirement.md
> +---
Added changelog. Some existing link validations are failing in changelog. I am not sure how to fix those. can you help

2023-04-17 04:58 UTC, JarbasHorst commented on api-reference/beta/resources/plannertaskpropertyrule.md
> +|completionRequirements|String collection|  |
Please add a description to the completionRequirements property. The description should also mention the allowed values for this property.

2023-04-17 04:58 UTC, JarbasHorst commented on concepts/planner-task-rules-overview.md
>  Specifies whether the task **percentComplete** property can be changed. Accepted values are:
For consistency, please add a new section under the Configurable actions after checkLists to provide detailed information about the completionRequirements action/property.

2023-04-17 05:00 UTC, JarbasHorst commented
Hi @prasad5596, thanks for addressing my previous comment. I left additional ones. Please, take a look when you will have time.

2023-04-17 08:59 UTC, prasad5596 commented on concepts/planner-task-rules-overview.md
>  Specifies whether the task **percentComplete** property can be changed. Accepted values are:
Added. Thanks

2023-04-18 03:48 UTC, Jarbas-MSFT commented
Hi @Lauragra, this PR is ready for final review.

@prasad5596, based on the api.md file and the changes applied to the "percentComplete" section of the concepts/planner-task-rules-overview.md, I added "overrideRequirements" as an accepted value for the **percentComplete** property. Consider fixing it, if this is not correct.

2023-04-19 01:02 UTC, Lauragra approved these changes

2023-06-08 02:32 UTC, merged