Bringing changes back from other broken branch
microsoftgraph/microsoft-graph-docs pull request #20032
Opened 2023-01-26 22:07 UTC by JeremyKelley

This is a new branch to fix the user error created problems in the old one.  This has already incorporated feedback from the original PR.

2023-01-30 21:58 UTC, jasonjoh requested changes

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +Some APIs and services included in Microsoft Graph are metered by Azure-meters and require payment for use.
"Azure-meters" looks suspect to me. I can't find this term in Azure docs. Closest I've found is "billing meters", so maybe this should be "Azure billing meters"?

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +Use the following steps to create and link a Microsoft.GraphServices/accounts Azure Resource to your application:
```suggestion
Use the following steps to create and link a **Microsoft.GraphServices/accounts** Azure Resource to your application:
```

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +![Azure Subscriptions in the Azure Portal](images/metered-apis/azure-subscription.png)
This is a global comment on the screenshots in this topic as a whole. I suggest taking a very critical look at what is absolutely necessary here and cutting the rest. Screenshots are a pain to maintain as UI changes, and they aren't localized.

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +![Azure Subscriptions in the Azure Portal](images/metered-apis/azure-subscription.png)
For example, this first one is probably not needed. The Subscriptions link is literally the first one when you login to the portal.

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +![Choose an Azure Subscription for API consumption charges](images/metered-apis/choose-subscription.png)
Also probably not needed.

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +![Choose Cloud Shell](images/metered-apis/cloud-shell.png)
I'd cut this one too

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +![May need to create a storage account to access Cloud Shell](images/metered-apis/no-storage.png)
Cut this one too.

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +![Successfully associated application to Azure Subscription](images/metered-apis/cloud-shell-success.png)
This one's too small, you can't read the text. I'd cut this and replace it with the actual success text from the shell command, something like:

```bash
here's my success output...
```

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +After you have enabled your app to consume Microsoft Graph Azure-metered APIs and services, the app can start to successfully make API calls for metered APIs. Charges generated from those requests wi
```suggestion
After you have enabled your app to consume Microsoft Graph Azure-metered APIs and services, the app can start making API calls for metered APIs. Charges generated from those requests will be charged to the Azure Subscription associated with the app.
```

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-onboarding.md
> +The invoice will include the following elements: Service Family, Service Name, Meter Category, Subcategory, consumed qty, included qty, price, and extended amount. For more details, see [Understand y
The list of elements is inconsistent. Some are title-cased, some are lower-cased, some use abbreviations - is this from Azure's UI?

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-overview.md
> +Microsoft Graph includes APIs that are both available at no additional cost with user subscription licenses as well as APIs and services that are metered with an Azure-meter. Azure-metered APIs and s
Same comment on "Azure-meter".

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-overview.md
> +Customer Data ownership: Customer data belongs to the customer. Learn more about how [Microsoft categorizes customer data](https://www.microsoft.com/en-us/trust-center/privacy/customer-data-definitio
This section isn't rendering like I suspect you want. Consecutive lines in Markdown do not generate line-breaks in the rendered HTML. A bulleted list may work here.

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-overview.md
> +Standard: This category includes the broad set of APIs used to perform “CRUD” (create, read, update, delete) operations on customer content and administrative endpoints for service configuration. We
A bulleted list may be called for here too. As it is, the categories don't stand out to me. I'd suggest either a bulleted list, or making each category an H3 header and putting the rest of the text underneath.

2023-01-30 21:58 UTC, jasonjoh commented on concepts/metered-api-list.md
> +| API | Protected API form |
Table is missing data in the second column

2023-01-30 22:31 UTC, JeremyKelley commented on concepts/metered-api-list.md
> +| API | Protected API form |
Next up on my to-do list.

2023-01-30 22:32 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +Some APIs and services included in Microsoft Graph are metered by Azure-meters and require payment for use.
We should definitely raise this with Jenn Cockrell, she gave me the "Azure-metered" term this morning to use.

2023-01-30 22:35 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +![Choose Cloud Shell](images/metered-apis/cloud-shell.png)
You're referring to the images not the text right?

2023-01-30 22:36 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +The invoice will include the following elements: Service Family, Service Name, Meter Category, Subcategory, consumed qty, included qty, price, and extended amount. For more details, see [Understand y
I'll do a quick check in the Azure UX, this was from the original doc I got.

2023-01-30 22:38 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +Some APIs and services included in Microsoft Graph are metered by Azure-meters and require payment for use.
Actually I think I see how this specific context is weird, I'm going to adjust it.

2023-01-31 00:16 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +Use the following steps to create and link a Microsoft.GraphServices/accounts Azure Resource to your application:
Was making other changes so added this in another commit.

2023-01-31 00:17 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +![Successfully associated application to Azure Subscription](images/metered-apis/cloud-shell-success.png)
Got fresh output from dev and stuck in the placeholder values where they would go.

2023-01-31 21:54 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +- Customer Data ownership: Customer data belongs to the customer. Learn more about how [Microsoft categorizes customer data](https://www.microsoft.com/en-us/trust-center/privacy/customer-data-definit
Remove the data after the # in the URL.
``#:~:text=It%20includes%20customer%20content%2C%20which%20is%20the%20data,site%20content%2C%20or%20instant%20messaging%20conversations.%20Personal%20data``

2023-01-31 21:55 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +We want to ensure that our customers and developers have access to data at scale. This category includes purpose-built, bulk-export services like [Teams Export APIs](https://docs.microsoft.com/micros
We should move the docs.microsoft.com links over to learn.microsoft.com

2023-01-31 22:17 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +- Customer Data ownership: Customer data belongs to the customer. Learn more about how [Microsoft categorizes customer data](https://www.microsoft.com/en-us/trust-center/privacy/customer-data-definit
remove en-us from the URL

2023-01-31 22:18 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +With the working principles in place, there are three categories of use cases represented in Microsoft Graph. Note that these categories are useful for illustration but don’t reflect any formal namin
Should we say "guiding principles" instead? working principles seems like they're not that firm in my mind.

2023-01-31 22:20 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +This category includes the broad set of APIs used to perform “CRUD” (create, read, update, delete) operations on customer content and administrative endpoints for service configuration. We continue t
I think we should drop "CRUD" I don't think we use that elsewhere. We could just say "broad set of APIs used to perform standard operations (e.g. create, read, update, delete) on customer content and administrative.. "

2023-01-31 22:34 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +We want to ensure that our customers and developers have access to data at scale. This category includes purpose-built, bulk-export services like [Teams Export APIs](https://learn.microsoft.com/micro
I wonder if we're going to confuse people by mentioning MGDC and Connectors here, since they aren't monetized using the same associate app to subscription mechanism that we're talking about in this doc set.

2023-01-31 22:34 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +We want to ensure that our customers and developers have access to data at scale. This category includes purpose-built, bulk-export services like [Teams Export APIs](https://learn.microsoft.com/micro
Similar feedback about using ACS as the example below.

2023-01-31 22:39 UTC, rgregg-msft commented on concepts/metered-api-overview.md
> +When building an app that leverages Azure-metered APIs it is important to remember that Azure-metered APIs may return errors related to your subscription status in addition to other more common error
I think another consideration when using metered APIs:

- Metered APIs are billed according to how much usage occurs on the API. Developers should understand the metering unit to understand how to estimate costs associated with a particular API.

Should we go as far as recommending a limited cache of data retrieved via these APIs? Would that run into issues with TOU around 'otherwise create copies of any data accessed or obtained using the Microsoft APIs, except as necessary to enable an intended usage scenario for your Application;'
-

2023-01-31 22:41 UTC, rgregg-msft commented on concepts/metered-api-list.md
> +| API | Protected API form |
Should we add a link to the information about billing and license requirements for each API too?

2023-01-31 22:42 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +See [List of Microsoft Graph Azure-metered APIs](metered-api-list.md) for the full list of APIs that may require payment.
"for the full list of metered APIs."

2023-01-31 22:43 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +To consume Azure-metered APIs and services, the Azure Active Directory registration for the application consuming the APIs must be associated to an Azure Subscription which will be billed for any con
Can we simplify this a bit and say "Azure Active Directory app registration consuming the APIs..."

2023-01-31 22:43 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +To consume Azure-metered APIs and services, the Azure Active Directory registration for the application consuming the APIs must be associated to an Azure Subscription which will be billed for any con
I think we should standardize on 'meter/metered' instead of 'consumption related'.

2023-01-31 22:46 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +To consume Azure-metered APIs and services, the Azure Active Directory registration for the application consuming the APIs must be associated to an Azure Subscription which will be billed for any con
I think "will enable" should be re-written in present tense. "In addition to enabling usage of metered APIs, the association you to use [Azure Cost Management + Billing](https://learn.microsoft.com/en-us/azure/cost-management-billing/) to understand and manage the costs of this application."

2023-01-31 22:51 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +To enable an application to call Azure-metered APIs or take advantage of Azure-metered services it must be associated with an Azure Subscription. To create this association, an Azure resource of type
"take advantage" seems like the wrong phrase.

2023-01-31 22:53 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +To enable an application to call Azure-metered APIs or take advantage of Azure-metered services it must be associated with an Azure Subscription. To create this association, an Azure resource of type
I'm not sure that map 1:1 is that meaningful of a term to customers. Perhaps "The Azure resource connects the Azure Active Directory app registration with the Azure Subscription where the application's usage of metered APIs is billed."

2023-01-31 22:53 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +Note: If you're using Cloud Shell for the first time you might need to create a storage account.  Select an Azure subscription, choose **Create** and follow the instructions to create a storage accou
You can also use the Azure command line interface from your local machine to perform these steps.

2023-01-31 22:56 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +4. To register the **Microsoft.GraphServices** resource provider to your active subscription so an Azure resource can be created, copy the command below, paste into Cloud Shell and type  <**Enter**>.
"4. Use the `Register-AzResourceProvider` command to register the **Microsoft.GraphServices** resource provider on your active subscription."

2023-01-31 22:57 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +az resource create --resource-group myRG --name myGraphAppBilling --resource-type Microsoft.GraphServices/accounts --properties  "{`"appId\`": `"myAppGUID`"}" --latest-include-preview --location Glob
is there no PowerShell command for az resource create? It's weird that we're using `az` CLI app here and above we used `Register-AzResourceProvider` power shell commandlet. Let's standardize on one approach. I prefer 'az' because it's not specific to PowerShell and works if you choose another cloud shell type.

2023-01-31 22:58 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +4. To register the **Microsoft.GraphServices** resource provider to your active subscription so an Azure resource can be created, copy the command below, paste into Cloud Shell and type  <**Enter**>.
Suggest change this to `az provider register` command. https://learn.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az-provider-register

2023-01-31 22:59 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +5. Copy the command below, paste into Cloud Shell and replace the highlighted text with your own value, type <**Enter**>. The result will be a JSON representation of your Microsoft.GraphServices/acco
The step should describe what we're doing.

5. Use [az resource create]() to create a new instance of `Microosft.GraphServices/accounts` resource type to associate your app registration with the active subscription.

2023-01-31 23:01 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +A successful result will look something like this:
"If the command succeeds, the response will include a JSON representation of the newly created resource."

2023-01-31 23:03 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +After you have enabled your app to consume Microsoft Graph Azure-metered APIs and services, the app can start making API calls for metered APIs. Charges generated from those requests will be charged
Once you have associated your app registration and subscription, your app can start using metered Microsoft Graph APIs and services.

Note: Your application may need to request a new OAuth access token before requests to metered APIs will be allowed.

2023-01-31 23:25 UTC, JeremyKelley commented on concepts/metered-api-list.md
> +| API | Protected API form |
> Should we add a link to the information about billing and license requirements for each API too?

I think so, one thing we need to address with that is how Beta APIs that don't yet have pricing information should appear.  Set Label is in this state now, it says it's protected but not that it requires payment.

2023-01-31 23:32 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +| myAppGUID | The Application (client) ID of the application being enabled |
what format is the GUID supposed to be in?

2023-01-31 23:32 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +az resource create --resource-group myRG --name myGraphAppBilling --resource-type Microsoft.GraphServices/accounts --properties  "{`"appId\`": `"myAppGUID`"}" --latest-include-preview --location Glob
Does it need "--latest-include-preview" flag?

2023-01-31 23:34 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +After the subscription billing cycle runs, typically on the 5th day of the month, a subscription owner or users with role-based permissions can download an invoice. For details, see [View and downloa
Is the 5th day of the month documented in Azure docs somewhere? I don't want to promise something on behalf of Azure about when the invoices are sent.

2023-01-31 23:35 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +The invoice will include details that allow you to understand the amount of usage your application generates and for multi-tenant applications where that usage is happening. For more details, see [Un
Not for MVP, but we should make sure to track adding a topic on how to determine the costs per tenant for your metered API scenario.

2023-02-02 00:08 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +After you have enabled your app to consume Microsoft Graph Azure-metered APIs and services, the app can start making API calls for metered APIs. Charges generated from those requests will be charged
Incorporated this suggestion.

2023-02-02 00:09 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +az resource create --resource-group myRG --name myGraphAppBilling --resource-type Microsoft.GraphServices/accounts --properties  "{`"appId\`": `"myAppGUID`"}" --latest-include-preview --location Glob
Confirmed with Fernando that this is needed until GA.

2023-02-02 20:24 UTC, BrianTJackett commented on concepts/metered-api-list.md
> +|:--------------------------|:--------------------------|:----------------------------------------|
eDiscovery endpoint for AddToReviewSet also will have an Azure meter associated (meter not yet created).  Details already in public blog though.  Recommend adding with an asterisk or some callout though.
https://learn.microsoft.com/graph/api/security-ediscoveryreviewset-addtoreviewset
https://devblogs.microsoft.com/microsoft365dev/ediscovery-api-for-microsoft-graph-is-now-generally-available/

2023-02-02 20:29 UTC, BrianTJackett commented on concepts/metered-api-onboarding.md
> +- Make sure that you have permissions for managing both the application registration and the Azure Subscription you wish to use.
Suggest more clarity on specific admin roles / permissions required for Azure subscription and Azure AD tenant in order to proceed.

2023-02-02 20:33 UTC, BrianTJackett commented on concepts/metered-api-onboarding.md
> +  "id": "/subscriptions/c771ae10-b7c4-4030-a87e-cca9e154c340/resourceGroups/myRG/providers/Microsoft.GraphServices/accounts/myGraphAppBilling",
Do we need to mask / redact the subscriptionId and appId from this sample response?

2023-02-02 20:34 UTC, BrianTJackett commented on concepts/metered-api-onboarding.md
> +Cost and usage of Azure-metered APIs and services can be monitoring through [Azure Cost Management + Billing](/azure/cost-management-billing/). This provides access to costs within the subscription,
Suggest "monitored" instead of -ing

2023-02-02 20:43 UTC, BrianTJackett commented on concepts/metered-api-onboarding.md
> +After the subscription billing cycle runs, typically on the 5th day of the month, a subscription owner or users with role-based permissions can download an invoice. For details, see [View and downloa
Found this in Azure docs,
"Invoice date - Date that the invoice was generated, typically on the same day of the month that the Azure account was created. However, they sometimes get generated a day or two later than day of the month that the Azure account was created."
https://learn.microsoft.com/azure/cost-management-billing/understand/understand-invoice#account-information

2023-02-03 01:52 UTC, adnivart commented on concepts/metered-api-list.md
> +# List of Microsoft Graph Metered APIs
nit: Shouldn't it say Azure-metered in this title too

2023-02-03 01:53 UTC, adnivart commented on concepts/metered-api-list.md
> +| SharePoint [assignSensitivityLabel](/graph/api/driveitem-assignsensitivitylabel.md) | Coming Soon | [SharePoint request](https://aka.ms/PreviewSPOPremiumAPI) |
nit: This should probably be something more clear like "SharePoint preview enrollment form"

2023-02-03 01:58 UTC, adnivart commented on concepts/metered-api-onboarding.md
> +Note: The following steps can be completed either by signing in to https://portal.azure.com and choosing **Cloud Shell** or using your local Azure command-line interface. When using Cloud Shell for t
nit: Could be useful to put a link to how to use Cloud Shell in the MSFT docs

2023-02-03 02:01 UTC, adnivart commented on concepts/metered-api-onboarding.md
> +  "id": "/subscriptions/c771ae10-b7c4-4030-a87e-cca9e154c340/resourceGroups/myRG/providers/Microsoft.GraphServices/accounts/myGraphAppBilling",
Yes please. Same for the resource name at the end of the ID.

2023-02-03 02:03 UTC, adnivart commented on concepts/metered-api-onboarding.md
> +Once you have associated your app registration and subscription, your app can start using metered Microsoft Graph APIs and services. Charges generated from those requests will be charged to the Azure
nit: I see a few instances where it says "app" instead of "application". For this kind of documentation, we should avoid abbreviations, right?

2023-02-03 13:35 UTC, BrianTJackett commented on concepts/metered-api-onboarding.md
> +Note: The following steps can be completed either by signing in to https://portal.azure.com and choosing **Cloud Shell** or using your local Azure command-line interface. When using Cloud Shell for t
Ex. overview page for Azure Cloud Shell
https://learn.microsoft.com/azure/cloud-shell/overview

2023-02-08 00:36 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +  "id": "/subscriptions/c771ae10-b7c4-4030-a87e-cca9e154c340/resourceGroups/myRG/providers/Microsoft.GraphServices/accounts/myGraphAppBilling",
I'll redact the subscription ID, I replaced the other "real" values with the placeholders and missed that one since it wasn't a user provided value. I'll redact the other GUID's as well below.

2023-02-08 00:37 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +Cost and usage of Azure-metered APIs and services can be monitoring through [Azure Cost Management + Billing](/azure/cost-management-billing/). This provides access to costs within the subscription,
Good catch.  My grammar radar was off on that one.

2023-02-08 00:41 UTC, JeremyKelley commented on concepts/metered-api-onboarding.md
> +Once you have associated your app registration and subscription, your app can start using metered Microsoft Graph APIs and services. Charges generated from those requests will be charged to the Azure
Thanks, I think I got all the "apps" now.

2023-02-08 00:48 UTC, JeremyKelley commented on concepts/metered-api-list.md
> +# List of Microsoft Graph Metered APIs
Fixed the language with the latest from marketing.

2023-02-10 23:25 UTC, Lauragra commented on concepts/metered-api-list.md
> +# List of Microsoft Graph Metered APIs
The title field and the H1 title here don't match. Would this be an appropriate title to use: "Metered APIs in Microsoft Graph".

2023-02-10 23:26 UTC, Lauragra commented on concepts/metered-api-list.md
> +description: "The list of metered Microsoft 365 APIs and services on Microsoft Graph."
The description should be a complete sentence - this is what might show up as the search description. Suggested revision: "Find out which Microsoft 365 APIs and services in Microsoft Graph are metered."

Are we metering both APIs and services?

2023-02-10 23:30 UTC, Lauragra commented on concepts/metered-api-list.md
> +The following is the list of metered Microsoft 365 APIs and services. Calling these APIs and services requires an active Azure Subscription associated with the calling application. See [Metered APIs
If we're only metering Microsoft 365 APIs, do we need to make a statement here about that, i.e. "Currently only Microsoft 365 APIs in Microsoft Graph are metered."

2023-02-10 23:32 UTC, Lauragra commented on concepts/metered-api-list.md
> +| API | Billing and License information | Protected API form |
Would it be helpful to add some context about the Protected API form? For example, a sentence like, "To get access to metered APIs, submit a request by using the Protected API form. Also, should that be "Metered" API instead of "Protected", or are they two different categories? If so, you'll want to explain what a protected API is.

2023-02-15 00:53 UTC, Lauragra commented on concepts/metered-api-onboarding.md
> +See [List of metered Microsoft 365 APIs](metered-api-list.md) for the full list of Microsoft 365 APIs that may require payment.
Why are we publishing a separate topic to list all the metered APIs, instead of including the full list here? Is it because we think the list will get a lot longer? It doesn't seem user friendly to provide examples here but require users to click to another topic to get the full list. Also, the separate topic only appears to have one additional API in the list.

Would it make sense to provide the full list of metered APIs here or alternatively, in the overview topic? At this point it might be okay to consolidate and separate later if/when we have a longer list.

2023-02-15 01:32 UTC, Lauragra commented on concepts/metered-api-list.md
> +| Teams [chat](/graph/api/chats-getallmessages.md) export | [Microsoft Teams API Licensing and Payment Requirements](teams-licenses.md) | [Microsoft Teams request](teams-protected-apis.md) |
We should have a note in each API topic that calls out that these are metered APIs. A proposed include file is in PR #18602. I assume we will change "premium" to "metered". We'll need a similar file for the non-Teams APIs.

Do we want to do that as part of this PR, or create a separate PR?

2023-02-15 01:40 UTC, Lauragra commented on concepts/metered-api-list.md
> +Some metered Microsoft 365 APIs and services might also require that you submit a protected API request. For those APIs, the link to the submission form is included in the table.
It might be helpful to provide a bit of context about protected APIs here, i.e. "You must have additional validation beyond permissions and consent before you can use protected APIs."

2023-02-15 02:33 UTC, Lauragra commented on concepts/metered-api-overview.md
> +## Guiding principles
Are these guiding principles something that we want or need to expose externally to customers? These seem like principles that we apply internally and/or something that would be covered in the Terms of use. Note that it is not Microsoft style to use the first-person plural ("we"). Also, some of these principles don't appear to be specific to the topic of metered APIs. 

Having a section like this also sets a tone that we expect some amount of concern or pushback from customers, and we're trying to explain or reassure. That might be relevant for a point-in-time communication like a blog post, but less relevant for a more permanent article. I suggest summarizing the relevant points here in the introduction and removing this section. For example:

"Metering some APIs helps to ensure the health of the current and future Microsoft Graph ecosystem by balancing platform access and cost. Microsoft will not charge for generally available APIs that are currently free without following the [policy for breaking changes](versioning-and-support.md)."

Is the definition of "ecosystem" clear in this context?

2023-02-15 17:03 UTC, rgregg-msft commented on concepts/metered-api-onboarding.md
> +See [List of metered Microsoft 365 APIs](metered-api-list.md) for the full list of Microsoft 365 APIs that may require payment.
We do expect the list to get longer. I think we can remove the list of examples here and just link to the separate topic with the list of metered APIs.

2023-02-15 17:04 UTC, rgregg-msft commented on concepts/metered-api-list.md
> +| Teams [chat](/graph/api/chats-getallmessages.md) export | [Microsoft Teams API Licensing and Payment Requirements](teams-licenses.md) | [Microsoft Teams request](teams-protected-apis.md) |
Let's make this a separate PR.

2023-02-15 20:46 UTC, Lauragra commented on concepts/metered-api-overview.md
> +## Categories of services
How do we define "services" in this context? Is it something different than APIs?

2023-02-15 20:47 UTC, Lauragra commented on concepts/metered-api-overview.md
> +With the working principles in place, there are three categories of use cases represented in Microsoft Graph. Note that these categories are useful for illustration but don’t reflect any formal namin
I'm not sure that we need that second sentence, it seems clear enough that the categories are "descriptive" rather than official brands.

2023-02-15 20:52 UTC, Lauragra commented on concepts/metered-api-overview.md
> +This category includes the broad set of APIs used to perform standard operations (e.g. create, read, update, delete) on customer content and administrative endpoints for service configuration. We con
Suggested revision for this paragraph:

Most Microsoft Graph APIs are standard APIs. These APIs perform standard operations (create, read, update, delete) on customer content and administrative endpoints. Reasonable access limits for these APIs are defined based the documented usage thresholds. This helps to ensure a positive customer experience and encourages efficient API usage patterns. Access to standard APIs within the defined usage thresholds is available as part of the user license without additional costs.

2023-02-15 21:05 UTC, Lauragra commented on concepts/metered-api-overview.md
> +We want to ensure that our customers and developers have access to data at scale. This category includes purpose-built, bulk-export services like [Teams Export APIs](/microsoftteams/export-teams-cont
Suggested revision for this paragraph:

High-capacity APIs are purposefully built bulk-export services, such as the [Teams export APIs](/microsoftteams/export-teams-content#license-requirements-for-teams-export-apis). These APIs help to ensure that you and your customers have access to data at scale.

What can we say about whether these are metered APIs or free? Also, should we have content about the export APIs in the Microsoft Graph content set instead of linking to the Teams docs?

2023-02-15 21:08 UTC, Lauragra commented on concepts/metered-api-overview.md
> +The third category represents access to data that’s enriched or aggregated by Microsoft or offers access to advanced functionality extended directly from Microsoft 365 infrastructure, [Azure Communic
Suggested revision for this paragraph:

Advanced APIs provide access to enriched or aggregated data, or advanced functionality that extends from Microsoft 365; for example, [Azure Communication Services](https://azure.microsoft.com/products/communication-services/#overview).

What are examples of Microsoft Graph APIs that are "advanced"? Are these metered or no cost?

2023-02-15 22:54 UTC, Lauragra commented on concepts/metered-api-overview.md
> +- Metered APIs can return errors related to your subscription status in addition to other common errors. For details about Microsoft Graph errors, see [Microsoft Graph errors and resource types](erro
Is it okay that this errors topic doesn't cover subscription-related errors, or should we add that information to the errors topic?

2023-02-15 22:55 UTC, Lauragra commented on concepts/metered-api-overview.md
> +- Metered APIs are billed according to API usage. Be sure to understand the metering unit so that you can estimate the costs associated with a particular API.
Do we have a link to where they can go to understand the "metering unit" for a particular API?

2023-02-15 23:08 UTC, Lauragra commented on concepts/metered-api-overview.md
> +title: "Overview of metered APIs in Microsoft Graph"
Should the title here include "Microsoft 365", or do we expect that non-Microsoft 365 APIs will be metered and also covered by this topic in the future?

2023-02-15 23:21 UTC, Lauragra commented on concepts/metered-api-onboarding.md
> +## Known limitations
This content might be better placed in the overview topic, because it's more general information about metered APIs and not specific to onboarding. 

Regarding the first bullet, is it accurate that the APIs are not available at all in national clouds, or they are available but not metered? Either way, we should call this out in the API topics, where we also mention that the APIs are metered. (We have a separate effort in progress to document API availability and behavior differences in national clouds.)

2023-02-15 23:57 UTC, Lauragra commented on concepts/metered-api-list.md
> +| Teams [chat](/graph/api/chats-getallmessages.md) export | [Teams API payment models and licensing requirements](teams-licenses.md) | [Microsoft Teams request](teams-protected-apis.md) |
Do you want to link directly to the request form instead of the Protected APIs topic? That would be fewer clicks for the user. Then you can just have a link to the topic as a general cross-reference.

2023-02-16 23:49 UTC, rgregg-msft commented on concepts/teams-licenses.md
> +> Active pricing events for these APIs started on July 5th, 2022.  Please follow the instructions on [Onboard to metered Microsoft 365 APIs and services](/graph/metered-api-onboarding) to set up an a
"Active pricing events" seems unclear to me. Are we trying to say "Billing began..." ?

2023-02-16 23:50 UTC, rgregg-msft commented on concepts/teams-licenses.md
> +You can also use the pie charts near the bottom to further break down the costs for analysis. Note that for Microsoft Graph metered APIs, the **Resource GUID** is the app ID; **Resource Groups** or *
The resource GUID is not the App ID in self-service onboarding.

2023-02-16 23:52 UTC, rgregg-msft commented on concepts/teams-licenses.md
> +This section describes how to monitor the number of messages billed for the metered Microsoft Teams APIs.  Unlike the previous section, this allows you to analyze also the usage of the messages withi
You don't need "Unlike the previous section" here, you could say "Unlike with Cost Analysis," if you want to clarify why this is different.

2023-02-16 23:52 UTC, rgregg-msft commented on concepts/teams-licenses.md
> +A subscription owner, or anyone with appropriate [RBAC (Roles Based Access Control) permissions](/azure/cost-management-billing/costs/assign-access-acm-data), can set up a report, in CSV format, with
Is it appropriate permissions, or the required permissions?

2023-02-16 23:56 UTC, rgregg-msft commented on concepts/teams-licenses.md
> +This section describes how to look up the number of messages in your Microsoft Teams.  This is useful when you haven't used the metered APIs yet and just want to have a high level estimate of what th
I'd change the second sentence to be more like: "This is useful when you are considering using the metered APIs and want to estimate the cost for using these APIs."

The sentence "Please note.." doesn't explain why that would happen, I think a clarifying example would be useful.

Many of our customers are ISVs - what do we suggest they do, since this information isn't available to them?

2023-02-17 00:18 UTC, erichui-ms commented on concepts/teams-licenses.md
> +> Active pricing events for these APIs started on July 5th, 2022.  Please follow the instructions on [Onboard to metered Microsoft 365 APIs and services](/graph/metered-api-onboarding) to set up an a
Doc updated.  Thanks.

2023-02-17 00:19 UTC, erichui-ms commented on concepts/teams-licenses.md
> +You can also use the pie charts near the bottom to further break down the costs for analysis. Note that for Microsoft Graph metered APIs, the **Resource GUID** is the app ID; **Resource Groups** or *
@fercobo-msft , could you confirm and update this pull request accordingly, please.

(I got this info from the current user guide PDF.)

2023-02-17 00:19 UTC, erichui-ms commented on concepts/teams-licenses.md
> +This section describes how to monitor the number of messages billed for the metered Microsoft Teams APIs.  Unlike the previous section, this allows you to analyze also the usage of the messages withi
Doc updated.  Thanks.

2023-02-17 00:19 UTC, erichui-ms commented on concepts/teams-licenses.md
> +A subscription owner, or anyone with appropriate [RBAC (Roles Based Access Control) permissions](/azure/cost-management-billing/costs/assign-access-acm-data), can set up a report, in CSV format, with
Doc updated.  Thanks.

2023-02-17 00:21 UTC, erichui-ms commented on concepts/teams-licenses.md
> +This section describes how to look up the number of messages in your Microsoft Teams.  This is useful when you haven't used the metered APIs yet and just want to have a high level estimate of what th
I've updated the second sentence and added an example.

Let me ask in the channel to see if anyone has a suggestion for ISVs.

Thanks!

2023-02-18 02:59 UTC, Lauragra commented on concepts/teams-licenses.md
> +> Billing for these APIs started on July 5th, 2022.  Please follow the instructions on [Onboard to metered Microsoft 365 APIs and services](/graph/metered-api-onboarding) to set up an active Azure su
@erichui-ms , before we can merge this PR, we need to revert the changes to this topic. Please restore the version of this file that's in the main branch, and apply your changes to the updated version of this topic in PR #18601.

2023-02-21 23:53 UTC, AndriiSnihyrMSFT commented on concepts/metered-api-setup.md
> +  az resource create --resource-group myRG --name myGraphAppBilling --resource-type Microsoft.GraphServices/accounts --properties  "{`"appId\`": `"myAppGUID`"}" --latest-include-preview --location Gl
@JeremyKelley , I beleive you are missing a dash in the `subscription` parameter. It should be `--subscription`.
https://learn.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-create (see global parameters section)

2023-02-28 00:49 UTC, Lauragra commented on concepts/metered-api-overview.md
> +There are three categories of use cases represented in Microsoft Graph APIs.
How about if we make the H2 here "API categories and metering", to help clarify the connection to the subject of the article?

And for the introduction, to clarify the context a bit, perhaps we revise as:
Microsoft Graph APIs fall into three categories, and metering applies based on the category of the API.

2023-02-28 02:31 UTC, JeremyKelley commented on concepts/metered-api-setup.md
> +## Known limitations
The second bullet is important when picking the application that is being setup, so I duplicated this section over to the overview as I think we want to reinforce these two items in both places until we can remove the limitations from the product.

2023-02-28 04:17 UTC, angelgolfer-ms commented on concepts/metered-api-setup.md
> +## Known limitations
@JeremyKelley , since this content should get a fair amount of attention, to help tighten the maintenance in the future, it would be good to use an "include" file for repeated content rather than duplicating it manually. More info here: https://review.learn.microsoft.com/en-us/help/platform/includes-best-practices?toc=%2Fhelp%2Fplatform%2Ftoc.json&bc=%2Fhelp%2Fplatform%2Fbreadcrumb%2Ftoc.json&branch=main

2023-02-28 04:28 UTC, Lauragra approved these changes

2023-02-28 04:29 UTC, merged

2023-02-28 04:42 UTC, angelgolfer-ms commented on concepts/metered-api-list.md
> +- [Enable Microsoft 365 metered APIs and services](/graph/metered-api-onboarding)
Line 30:
@JeremyKelley , there isn't a metered-api-onboarding.md file in your branch. Per the link text, I think you mean metered-api-setup.md. Please update as appropriate.

2023-02-28 04:50 UTC, angelgolfer-ms commented on concepts/metered-api-list.md
> +|:--------------------------|:--------------------------|:----------------------------------------|
@BrianTJackett , @JeremyKelley , I have a question regarding this which I'll take offline on Teams.

2023-02-28 09:01 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +Microsoft Graph includes APIs that are both available at no additional cost with user subscription licenses as well as APIs and services that are metered. Metered Microsoft 365 APIs and services incu
Line 11:
As is, the first sentence is structured to refer to a subset of APIs that are _both_ (a) entail no extra cost, and (b) are metered.
Did you really mean to refer to only that subset in the opening sentence?
Since this is the overview topic, and the monetization subject is likely to grab the attention of many customers who may or may not use metered APIs, the first sentence should not just address metered APIs. That sentence should describe a more complete picture of Microsoft Graph APIs: (a) APIs that do not entail additional cost to use aside from service subscription costs, (b) APIs that are metered, and (c) APIs that can be (a) or (b), like the Teams evaluation mode APIs.
So if you agree we should cover the fuller picture instead, the first 2 sentences can be rephrased as something like this:

>> 
Microsoft Graph includes APIs that are available at no additional cost with [user subscription licenses](/microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings?view=o365-worldwide&preserve-view=true), that are metered, or that are metered only beyond a certain level of usage.

2023-02-28 09:05 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +Microsoft Graph includes APIs that are both available at no additional cost with user subscription licenses as well as APIs and services that are metered. Metered Microsoft 365 APIs and services incu
Notice that I added a link to "user subscription licenses" because we're placing this content in the "Explore" section of the TOC. For new customers, or customers accustomed to other monetization models, it would be helpful to make our concepts crystal clear to reduce misconception.

2023-02-28 09:14 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +Whether metered or not, APIs in Microsoft Graph are provided based on the following two principles.
Line 13:
Can we say the following instead:
"Whether metered or not, APIs in Microsoft Graph follow the following two principles:"

Generally in docs, we try to avoid passive voice as much as possible. Passive voice without the object can be a problem for localization as well.

2023-02-28 09:39 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +
Line 17:
Is this sentence intentionally vague or ominous-sounding:
"Microsoft will not charge for generally available APIs that are currently free without following the [breaking change policy](versioning-and-support.md)."

As it's worded, and quite certainly when localized, customers can take this sentence to mean, "Microsoft promises not to charge APIs that are currently free in v1.0, except that when they decide to charge such APIs, they will increment the version number (which is what that versioning-and-support.md topic explains), and revise that API in the new version to start charging." 
There are 2 issues - (a) existing apps will have to migrate to use v2 and pay, (b) using the link text "breaking change" is ominous, making customers think that their production apps will definitely break.

Is (a) what you really mean to convey now? I'm asking because the related [blog post](https://devblogs.microsoft.com/microsoft365dev/principles-for-monetizing-selected-microsoft-365-apis/) tries to allay doubts if what's currently "free" will change at some point in the future:
"...we are not changing how we license or charge for existing, generally available, Microsoft Graph APIs"
"...We continue to define and update the limits of reasonable access based on documented usage thresholds to protect our customer experience and encourage good API usage patterns. We will continue to include access to this category of APIs within the defined limits as part of the user license without any additional costs to developers. This will continue to be the default category for most new endpoints. "

Please confirm and we can see how we should clarify this.

2023-02-28 09:45 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +Most Microsoft Graph APIs are standard APIs. These APIs perform standard operations (create, read, update, delete) on customer content and administrative endpoints. Reasonable access limits for these
Line 23:
By "usage thresholds", do you mean the [throttling limits](https://learn.microsoft.com/en-us/graph/throttling-limits)? If so, please link to that topic for clarity. 
Just to be clear, I know there's an earlier link to the same topic with the link text "defined limits", which we shouldn't assume newer customers to be aware we mean the same thing.

2023-02-28 09:48 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +High-capacity APIs ensure that customers and developers have access to data at scale. This category includes purpose-built, bulk export or import endpoints and Microsoft Graph services. These APIs ma
Line 26:
Would the getAllMessages functions for chat and channel be examples? If so, please provide them with links here.

2023-02-28 09:52 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +Advanced APIs provide access to enriched or aggregated data, or advanced functionality that extends from Microsoft 365. The [assignSensitivityLabel](/graph/api/driveitem-assignsensitivitylabel.md) Ap
Line 29:
Regarding linking to assignSensitivityLabel, please see my comment in metered-api-list.md for this SharePoint API. If only partial info is available (e.g., it's currently not monetized, there's no reliable timeline and cost structure to publicize), then it's better to hold off to provide this as an example until the info is more complete and actionable for customers to do any planning.

2023-02-28 09:54 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +
Lines 41-46:
As mentioned in metered-api-setup.md, please use an "include" file for these known limitations to make sure any future updates will be consistent between the two files that contain this same info.

2023-02-28 10:01 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +- Metered APIs are billed according to API usage. Be sure to understand the metering unit so that you can estimate the costs associated with a particular API.
+1.

2023-02-28 10:07 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +- Metered APIs can return errors related to your subscription status in addition to other common errors. For details about Microsoft Graph errors, see [Microsoft Graph errors and resource types](erro
+1. What errors are you referring to in line 38? 
In general, we shouldn't send customers to another topic if it's not obvious in that topic what or where they should look. I tried to do some searches and it seems I'd have to read through the entire topic if I want to identify if anything is specific to "errors related to subscription status".

2023-02-28 10:22 UTC, angelgolfer-ms commented on concepts/metered-api-setup.md
> +Some Microsoft 365 APIs and services in Microsoft Graph are metered and require payment for use. For a current list of APIs that require payment, see [Metered Microsoft 365 APIs and services](metered
Line 11:
Please use the text "metered and require payment for use" as link text to the metered-api-overview.md topic.

This would be really necessary if customers get to this topic first (by search, for example, or by getting to the "Develop" section and noticing this topic there. 
Per my email regarding the TOC organization, I have suggested adding this topic to the "Develop" section, as the process in this topic is relevant to that stage of the developer's journey. On the other hand, the other 2 new topics (overview and list of metered APIs) are going to the "Explore" section.

2023-02-28 22:06 UTC, JeremyKelley commented on concepts/metered-api-list.md
> +|:--------------------------|:--------------------------|:----------------------------------------|
Making the change to back out the eDiscovery inclusion on the list in the new branch.

2023-02-28 22:07 UTC, JeremyKelley commented on concepts/metered-api-list.md
> +- [Enable Microsoft 365 metered APIs and services](/graph/metered-api-onboarding)
Thanks! Someone else updated the name of the file and must not have checked for links. Will fix in new branch.

2023-03-02 18:43 UTC, BrianTJackett commented on concepts/metered-api-list.md
> +- [Enable Microsoft 365 metered APIs and services](/graph/metered-api-onboarding)
Was just about to comment on this as I found broken link while navigating today.

2023-03-02 19:45 UTC, JeremyKelley commented on concepts/metered-api-overview.md
> +Advanced APIs provide access to enriched or aggregated data, or advanced functionality that extends from Microsoft 365. The [assignSensitivityLabel](/graph/api/driveitem-assignsensitivitylabel.md) Ap
The API itself is available and requires setup for payment as part of the Beta API in Public Preview (although the billing amount may be $0). I believe I have a link from Adriana for the payment info so I plan to include that in the table.

2023-03-02 19:46 UTC, JeremyKelley commented on concepts/metered-api-overview.md
> +- Metered APIs can return errors related to your subscription status in addition to other common errors. For details about Microsoft Graph errors, see [Microsoft Graph errors and resource types](erro
Working with Jason to coordinate getting the 402 error added to that page so it's accurate.

2023-03-02 19:47 UTC, JeremyKelley commented on concepts/metered-api-overview.md
> +- Metered APIs are billed according to API usage. Be sure to understand the metering unit so that you can estimate the costs associated with a particular API.
We don't have a consolidated page yet, today I'm just linking in the list of APIs to the individual pricing info.  Eventually marketing will provide us an Azure.com page that is the permanent home of that information.

2023-03-03 01:50 UTC, angelgolfer-ms commented on concepts/metered-api-overview.md
> +Advanced APIs provide access to enriched or aggregated data, or advanced functionality that extends from Microsoft 365. The [assignSensitivityLabel](/graph/api/driveitem-assignsensitivitylabel.md) Ap
Oh, so there's still no extra cost at this time to use the API. Do they know when the metering will become a reality?