Add sendNotification parameter to createlink api to enable email sending feature for createlink
microsoftgraph/microsoft-graph-docs pull request #20049
Opened 2023-01-30 06:04 UTC by yifanwu-microsoft

Onboarding Review PR: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/12389

Graph already has createLink API in Graph API. 
One is Sites and Lists createlink: https://learn.microsoft.com/en-us/graph/api/listitem-createlink. 
And another one is driveitem https://docs.microsoft.com/en-us/graph/api/driveitem-createlink

"SendNotification" field in the request body will enable createlink to send email to the recipients.
This API change is open for SharePoint and ODB user. For SharePoint and ODB user, this feature could be disabled by tenant admin.
If recipients are provided and sendNotification = true, it will send the emails to the recipients. If recipients are not provided and sendNotification = true, it will throw an exception.

2023-02-01 02:46 UTC, k-tsoi requested changes
Sentences are a little casual.
Public documentation usually does not pronouns like we, you etc.

2023-02-01 02:46 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +|sendNotification|Boolean|Optional. If true, a [sharing link](../resources/permission.md#sharing-links) is sent to the recipient. Only works with recipients on OneDrive for Business and SharePoint fo
remove "for now" for public documentation

2023-02-01 02:46 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +For OneDrive for Business and SharePoint user, we can use sendNotification parameter to create a sharing link and send this sharing link to the recipients with your email.
Change to something like "For OneDrive for Business and SharePoint, use sendNotification parameter to create a sharingLink, sharingLink is then sent to recipients via email"

2023-02-01 02:46 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +|sendNotification|Boolean|Optional. If true, a [sharing link](../resources/permission.md#sharing-links) is sent to the recipient. Only works with recipients on OneDrive for Business and SharePoint fo
remove "for now"

2023-02-01 02:46 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +For OneDrive for Business and SharePoint user, we can use sendNotification parameter to create a sharing link and send this sharing link to the recipients with your email.
Make the same to as driveitem-createLink

2023-02-01 08:11 UTC, yifanwu-microsoft commented on api-reference/beta/api/driveitem-createlink.md
> +|sendNotification|Boolean|Optional. If true, a [sharing link](../resources/permission.md#sharing-links) is sent to the recipient. Only works with recipients on OneDrive for Business and SharePoint fo
Done. Thanks!

2023-02-01 08:12 UTC, yifanwu-microsoft commented on api-reference/beta/api/driveitem-createlink.md
> +For OneDrive for Business and SharePoint user, we can use sendNotification parameter to create a sharing link and send this sharing link to the recipients with your email.
Done

2023-02-01 08:27 UTC, yifanwu-microsoft commented on api-reference/beta/api/listitem-createlink.md
> +|sendNotification|Boolean|Optional. If true, a [sharing link](../resources/permission.md#sharing-links) is sent to the recipient. Only works with recipients on OneDrive for Business and SharePoint fo
Done

2023-02-01 08:27 UTC, yifanwu-microsoft commented on api-reference/beta/api/listitem-createlink.md
> +For OneDrive for Business and SharePoint user, we can use sendNotification parameter to create a sharing link and send this sharing link to the recipients with your email.
Done

2023-02-01 21:16 UTC, k-tsoi requested changes
Need to add a change to the changelog
https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/changelog/Microsoft.FileServices.json

MSGraph team has documentation on how to create changelogs

2023-02-02 23:20 UTC, k-tsoi commented
> How can I generate example code in here, since I add a new parameter in the examples:
> 
> https://github.com/microsoftgraph/microsoft-graph-docs/blob/ba4449dfa5ef668a191b06d793d9b9848237f704/api-reference/beta/includes/snippets/javascript/driveitem-createlink-javascript-snippets.md
> 
> https://github.com/microsoftgraph/microsoft-graph-docs/blob/ba4449dfa5ef668a191b06d793d9b9848237f704/api-reference/beta/includes/snippets/csharp/driveitem-createlink-csharp-snippets.md
> 
> https://github.com/microsoftgraph/microsoft-graph-docs/blob/ba4449dfa5ef668a191b06d793d9b9848237f704/api-reference/beta/includes/snippets/java/create-link-scoped-java-snippets.md



I would check with one of the Graph reviewers, but I dont think you need to edit the snippets, think they are auto generated

2023-02-02 23:22 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "Target": "driveItem"
I don't need either of the deletion  comments.

2023-02-02 23:24 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Method",
APIChange should be "Parameter" not "method"

this change is to add a new "sendNotification" parameter to the existing CreateLink Method.
Not to add a new CreateLink Method

2023-02-02 23:27 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [createLink](https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) method to the [driveItem](https://learn.microsoft.com/en-us/gra
Description would be something like "Added the **sendNotification** parameter to the [createLink](docLink) action."

2023-02-02 23:30 UTC, k-tsoi requested changes
change changeLog entries

2023-02-02 23:30 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Method",
remove

2023-02-02 23:30 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [createLink](https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) method to the [driveItem](https://learn.microsoft.com/en-us/gra
Description would be something like `Added` the **sendNotification** parameter to the [createLink](docLink) action.`

2023-02-02 23:30 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Method",
APIChange should be "Parameter" not "method"

this change is to add a new "sendNotification" parameter to the existing CreateLink Method.
Not to add a new CreateLink Method

2023-02-02 23:30 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "ChangedApiName": "createLink",
I don't need either of the deletion  comments.
Right now this changeLog is saying you are removing the /createLink method and adding a /createLink method which would not make sense as a reader, 
the deletion and addition would cancel each other out.

2023-02-02 23:30 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Method",
Reference - Example 8: Add a parameter to a method
https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2023-02-03 01:58 UTC, yifanwu-microsoft commented
Hi, k-tsoi. Thanks for your comments about the changelog. 
It seems that this is auto-generated by pipeline here:
https://msazure.visualstudio.com/One/_build/results?buildId=68070481&view=artifacts&pathAsName=false&type=publishedArtifacts

If you think we should try other way rather than this pipeline, please feel free to comment. I will fix it.

2023-02-03 04:06 UTC, k-tsoi commented
> Hi, k-tsoi. Thanks for your comments about the changelog. It seems that this is auto-generated by pipeline here: https://msazure.visualstudio.com/One/_build/results?buildId=68070481&view=artifacts&pathAsName=false&type=publishedArtifacts
> 
> If you think we should try other way rather than this pipeline, please feel free to comment. I will fix it.



I think my sugestion makes more sense, but you ask one of the Graph engineers what they suggest.
You need to add tag the MSFTBot said to add in order to get this reviewed by them

2023-02-03 04:21 UTC, yifanwu-microsoft commented
> > Hi, k-tsoi. Thanks for your comments about the changelog. It seems that this is auto-generated by pipeline here: https://msazure.visualstudio.com/One/_build/results?buildId=68070481&view=artifacts&pathAsName=false&type=publishedArtifacts
> > If you think we should try other way rather than this pipeline, please feel free to comment. I will fix it.
> 
> I think my sugestion makes more sense, but you ask one of the Graph engineers what they suggest. You need to add tag the MSFTBot said to add in order to get this reviewed by them

I think your suggestions make sense. I will try to modify those change log. 
After the modification, I will add tag for them to review.
Thanks!

2023-02-05 22:01 UTC, k-tsoi approved these changes

2023-02-06 16:47 UTC, Danielabom commented
Contacted author to get info.

2023-02-07 06:35 UTC, yifanwu-microsoft commented
Reply on teams. 
Please feel free to tell me if any more info is needed. 

Thanks!

2023-02-08 14:35 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the **sendNotification** properties on the [createLink](https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) action on a [driveItem](
Please follow the guidelines in this wiki https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog; you can go to example #8.

2023-02-08 14:36 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the **sendNotification** properties on the [createLink](https://learn.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta) action on a [listitem](ht
Please follow the guidelines in this wiki https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog; you can go to example https://github.com/microsoftgraph/microsoft-graph-docs/pull/8.

2023-02-08 14:40 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Property",
The CSDL indicates that you are adding a parameter. Please update this entry.

2023-02-08 14:41 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Property",
The CSDL indicates that you are adding a parameter. Please update this entry.

2023-02-09 04:26 UTC, angelgolfer-ms commented on api-reference/beta/api/driveitem-createlink.md
>  |recipients|[driveRecipient](../resources/driverecipient.md) collection|Optional. A collection of recipients who will receive access to the sharing link.|
Hi @yifanwu-microsoft , can you please make sure this action topic documents the same parameters that are already defined in the beta metadata? It's currently missing the message and retainInheritedPermissions.

<Action Name="createLink" IsBound="true">
<Parameter Name="bindingParameter" Type="graph.driveItem"/>
<Parameter Name="type" Type="Edm.String" Unicode="false"/>
<Parameter Name="scope" Type="Edm.String" Unicode="false"/>
<Parameter Name="expirationDateTime" Type="Edm.DateTimeOffset"/>
<Parameter Name="password" Type="Edm.String" Unicode="false"/>
<Parameter Name="message" Type="Edm.String" Unicode="false"/>
<Parameter Name="recipients" Type="Collection(graph.driveRecipient)"/>
<Parameter Name="retainInheritedPermissions" Type="Edm.Boolean"/>
<ReturnType Type="graph.permission"/>
</Action>

2023-02-09 04:28 UTC, angelgolfer-ms commented on api-reference/beta/api/driveitem-createlink.md
>  |recipients|[driveRecipient](../resources/driverecipient.md) collection|Optional. A collection of recipients who will receive access to the sharing link.|
And please also indicate if any of those parameters are optional.

Optional or not, please also include those parameters in the example request body.

2023-02-09 04:30 UTC, angelgolfer-ms commented on api-reference/beta/api/listitem-createlink.md
> +|sendNotification|Boolean|Optional. If true, a [sharing link](../resources/permission.md#sharing-links) is sent to the recipient. Only works with recipients on OneDrive for Business and SharePoint.|
@yifanwu-microsoft , for this action, please also include the retainInheritancePermissions parameter in the "Request body" section.
Please indicate whether it's  optional.
Please include  the parameters in the example request body.

2023-02-09 04:31 UTC, yifanwu-microsoft commented on api-reference/beta/api/driveitem-createlink.md
>  |recipients|[driveRecipient](../resources/driverecipient.md) collection|Optional. A collection of recipients who will receive access to the sharing link.|
Hi, @angelgolfer-ms Thanks for your reply.

So I am not the owner of the parameter "message and retainInheritedPermissions".
May I ask that do I need also to unify all the parameter across the createlink api? Because I don't have any context of those parameters.

2023-02-09 04:32 UTC, angelgolfer-ms submitted a review, later dismissed
Hi @yifanwu-microsoft , @Danielabom brought my attention to this PR. I added a few comments about the existing parameters for the createLink action topics. Please take a look.
You can please follow up with @Danielabom on these comments, or ping us on Teams if you have any questions. She remains your content reviewer to see this PR through.

2023-02-09 10:58 UTC, yifanwu-microsoft commented
For the message, I think the previous owner was added by mistake. 
I already contact the owner. I will ask the owner to remove the message in his next PR.

2023-02-10 05:18 UTC, angelgolfer-ms commented on api-reference/beta/api/driveitem-createlink.md
>  |recipients|[driveRecipient](../resources/driverecipient.md) collection|Optional. A collection of recipients who will receive access to the sharing link.|
HI @yifanwu-microsoft , thanks for researching into the 2 properties missing in this Properties table, and adding the docs for retainInheritedPermissions. 
On our Teams chat, I suggested what we should do with the message parameter.

2023-02-10 05:19 UTC, angelgolfer-ms commented on api-reference/beta/api/driveitem-createlink.md
> +| retainInheritedPermissions |  boolean                       | If `true`, any current existing inherited permissions are retained on the shared item when sharing this item for the first time. If `fa
Line 62:
@yifanwu-microsoft , please change the sentence "`true` is by default" to "The default is `true`."

2023-02-10 05:20 UTC, angelgolfer-ms commented on api-reference/beta/api/listitem-createlink.md
> +| retainInheritedPermissions |  boolean                       | If `true`, any current existing inherited permissions are retained on the shared item when sharing this item for the first time. If `fa
Line 62:
@yifanwu-microsoft , please change the sentence "`true` is by default" to "The default is `true`."

2023-02-10 05:32 UTC, angelgolfer-ms commented on api-reference/beta/api/driveitem-createlink.md
>  |recipients|[driveRecipient](../resources/driverecipient.md) collection|Optional. A collection of recipients who will receive access to the sharing link.|
Oh, @yifanwu-microsoft , can you also add the retainInheritedPermissions to the v1.0 topic as well? Thanks.

2023-02-16 15:01 UTC, Danielabom commented
Contacted author @yifanwu-microsoft to follow up.

2023-02-21 14:30 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the **sendNotification** Parameter to the [createLink](https://learn.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta) action on a [listitem](htt
```suggestion
          "Description": "Added the `sendNotification` parameter to the [createLink](https://learn.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta) method.",
```

2023-02-21 14:37 UTC, Danielabom commented on api-reference/beta/api/driveitem-createlink.md
> +| retainInheritedPermissions |  boolean                       | If `true`, any current existing inherited permissions are retained on the shared item when sharing this item for the first time. If `fa
```suggestion
| retainInheritedPermissions |  boolean                       | If `true`, any current inherited permissions are retained on the shared item when sharing the item for the first time. If `false`, all current permissions are removed when sharing for the first time. The default is `true`. Optional. |
```

2023-02-21 14:39 UTC, Danielabom commented on api-reference/beta/api/driveitem-createlink.md
> +For OneDrive for Business and SharePoint user, use sendNotification parameter to create a sharingLink, sharingLink is then sent to recipients via email.
```suggestion
For OneDrive for Business and SharePoint users, use the sendNotification parameter to create a sharingLink, the sharingLink is then sent to recipients via email.
```

2023-02-21 14:40 UTC, Danielabom commented on api-reference/beta/api/listitem-createlink.md
> +| retainInheritedPermissions |  boolean                       | If `true`, any current existing inherited permissions are retained on the shared item when sharing this item for the first time. If `fa
```suggestion
| retainInheritedPermissions |  boolean                       | If `true`, any current inherited permissions are retained on the shared item when sharing the item for the first time. If `false`, all current permissions are removed when sharing for the first time. The default is `true`. Optional. |
```

2023-02-21 14:40 UTC, Danielabom commented on api-reference/beta/api/listitem-createlink.md
> +For OneDrive for Business and SharePoint user, use sendNotification parameter to create a sharingLink, sharingLink is then sent to recipients via email.
```suggestion
For OneDrive for Business and SharePoint users, use the sendNotification parameter to create a sharingLink, sharingLink is then sent to recipients via email.
```

2023-02-21 16:13 UTC, Danielabom commented on api-reference/beta/api/driveitem-createlink.md
>  |recipients|[driveRecipient](../resources/driverecipient.md) collection|Optional. A collection of recipients who will receive access to the sharing link.|
hi @yifanwu-microsoft, I still don't see the parameter "message". I'll appreciate that if you cannot address any of our observations to add a comment next to our feedback.

2023-02-21 16:16 UTC, Danielabom commented on api-reference/v1.0/api/driveitem-createlink.md
> +| **retainInheritedPermissions** |  boolean                       | If `true`, any current existing inherited permissions are retained on the shared item when sharing this item for the first time. If
```suggestion
| **retainInheritedPermissions** |  boolean                       | If `true`, any current inherited permissions are retained on the shared item when sharing this item for the first time. If `false`, all current permissions are removed when sharing for the first time. The default is `true`. Optional. |
```

2023-02-23 22:38 UTC, Danielabom approved these changes
@yifanwu-microsoft, thank you for working on this PR. Changes approved.

2023-02-28 01:34 UTC, Danielabom commented
@yifanwu-microsoft , please add the "ready to merge label" as soon as you want the content to get published.

2023-03-02 04:55 UTC, merged