Promote LCW Beta to 1.0 Documentation
microsoftgraph/microsoft-graph-docs pull request #20058
Opened 2023-01-30 17:21 UTC by OWinfreyATL

2023-02-14 02:03 UTC, OWinfreyATL commented
@FaithOmbongi 

Hey Faith. This is promoting LCW from BETA to v1.0. Vast majority of these articles are just an update move from beta to v1.0 with a few changes:

1. emailsettings.md added
2.customExtensionAuthenticationConfiguration.md is inherited by [azureAdPopTokenAuthentication] with v1.0 but still azureADTokenAuthentication with BETA
3.New custom example being added with  create new version for customized email in identitygovernance-workflow-createnewversion.md

Still a few weeks off, but moving to review now as API schema passed review.

2023-02-14 08:48 UTC, FaithOmbongi commented
> @FaithOmbongi
> 
> Hey Faith. This is promoting LCW from BETA to v1.0. Vast majority of these articles are just an update move from beta to v1.0 with a few changes:
> 
> 1. emailsettings.md added
>    2.customExtensionAuthenticationConfiguration.md is inherited by [azureAdPopTokenAuthentication] with v1.0 but still azureADTokenAuthentication with BETA
>    3.New custom example being added with  create new version for customized email in identitygovernance-workflow-createnewversion.md
> 
> Still a few weeks off, but moving to review now as API schema passed review.

Thanks for the headsup @OWinfreyATL. Can you create a review work item in my ADO? https://aka.ms/msgraph-identity-workitem

Thanks!

2023-02-14 17:17 UTC, OWinfreyATL commented
> > @FaithOmbongi
> > Hey Faith. This is promoting LCW from BETA to v1.0. Vast majority of these articles are just an update move from beta to v1.0 with a few changes:
> > 
> > 1. emailsettings.md added
> >    2.customExtensionAuthenticationConfiguration.md is inherited by [azureAdPopTokenAuthentication] with v1.0 but still azureADTokenAuthentication with BETA
> >    3.New custom example being added with  create new version for customized email in identitygovernance-workflow-createnewversion.md
> > 
> > Still a few weeks off, but moving to review now as API schema passed review.
> 
> Thanks for the headsup @OWinfreyATL. Can you create a review work item in my ADO? https://aka.ms/msgraph-identity-workitem
> 
> Thanks!

Done Here: https://dev.azure.com/msft-skilling/Content/_workitems/edit/63881 

thanks! :)

2023-03-03 19:03 UTC, msewaweru requested changes
Hi @OWinfreyATL - This is batch 1 of the review. Please see main the highlights captured: 
1. GLOBAL: LifecycleWorkflowsContainer no longer inherits from entity v1.0. Remove all reference to this inheritance.
2. Remove tabs on all the HTTP examples.
3. authorizedApps property has been used extensively and is not in the schema. Please confirm its validity.
4. GLOBAL: Consider removing the Global Admin role from the LCW docs. There is an team initiative to stop document using it if there are lesser privileged roles.
5. GLOBAL: Casing for the role names should be capitalized for each word.
6. GLOBAL: Remove the tabs in all examples. These are inserted by the snippets generator.
7. GLOBAL: Seems inheritance from entity was removed in v1.0. Please remove these in 3 places the resource and the Id property descriptions and the JSON baseType representation.
8. Where I have highlighted missing properties, check beta side to update as well.

2023-03-07 15:05 UTC, msewaweru requested changes
@OWinfreyATL, this is batch 2 and final part of cycle 1 of the review. Main highlights as below. Thanks.
1. Remove the preview tag from the beta TOC.
2. Remove the differentiation in the page titles as done for the beta docs.

2023-03-08 19:37 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-userprocessingresult.md
> +|[List taskProcessingResults](../api/identitygovernance-userprocessingresult-list-taskprocessingresults.md)|[microsoft.graph.identityGovernance.taskReport](../resources/identitygovernance-taskprocess
We had a discussion around this and we decided it would remain under the userprocessingresults section as the call goes through user processing(the call checks for the task processing results of a user processing result).

2023-03-08 19:38 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-run.md
> +|[List task processing results of a run](../api/identitygovernance-run-list-taskprocessingresults.md)|[microsoft.graph.identityGovernance.taskReportSummary](../resources/identitygovernance-taskproces
As noted above this was decided to be listed under run as the call lists the task processing results of a workflow run.

2023-03-08 20:29 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-run.md
> +|[Get user processing result](../api/identitygovernance-run-summary.md)|[microsoft.graph.identityGovernance.userProcessingResult](../resources/identitygovernance-userprocessingresult.md)|Get a user p
Updated.

2023-03-08 21:55 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-workflow.md
> +|[List versions](../api/identitygovernance-workflow-list-versions.md)|[microsoft.graph.identityGovernance.workflowVersion](../resources/identitygovernance-workflowversion.md) collection|Get a list of
These are present in the subset resource pages and nodes, but as these nodes are a subset of the workflow we had them listed here.

2023-03-09 07:47 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-customtaskextensioncallbackconfiguration.md
> +|authorizedApps|microsoft.graph.application collection| Unique identifier for the application object. Inherited from [customExtensionCallbackConfiguration](../resources/customextensioncallbackconfigu
I believe this is being added with another schema. Keeping it here for now, but will remove from the public preview refresh PR that will incorporate feedback from here.

2023-03-09 07:51 UTC, OWinfreyATL commented
@msewaweru Hey Eunice. Good feedback. I have addressed all of them(pending authorizedAPPs here).

This feature will have another round of public preview with these changes(BETA only) which I have incorporated into a PR here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/20510

As that one will be the active one that will be with changes deploying this week I am not sure if I should request a look at the changes here or there :)

thanks again!

2023-03-09 16:22 UTC, OWinfreyATL commented on api-reference/v1.0/resources/customextensioncallbackconfiguration.md
> +|authorizedApps|microsoft.graph.application collection| Unique identifier for the application object.|
I have confirmed it was added in this schema change: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/12515?_a=files

2023-03-10 09:17 UTC, msewaweru commented
> @msewaweru Hey Eunice. Good feedback. I have addressed all of them(pending authorizedAPPs here).
> 
> This feature will have another round of public preview with these changes(BETA only) which I have incorporated into a PR here: #20510
> 
> As that one will be the active one that will be with changes deploying this week I am not sure if I should request a look at the changes here or there :)
> 
> thanks again!

@OWinfreyATL - thanks for the good job on the updates. I'm still learning the process here and would like to hear what @FaithOmbongi thinks on the second PR. She will be back Monday next week and we can agree on a way forward then. Thanks.

2023-05-30 17:46 UTC, closed without merging