AndrewYang/shareSnapshotAPI
microsoftgraph/microsoft-graph-docs pull request #20075
Opened 2023-01-31 09:22 UTC by jannyma

2023-02-02 03:10 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|snapshotType| [cloudPcSnapshotType](#cloudpcsnapshottype-values)   | The type of snapshot, Indicates how is the snapshot be created. Possible value is `automatic` and `manual`. Default value is auto
```suggestion
|snapshotType| [cloudPcSnapshotType](#cloudpcsnapshottype-values)   | The type of snapshot. Indicates how the snapshot can be created. Possible value are `automatic`, `manual`. Default value is automatic.|
```

2023-02-02 03:11 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the `snapshotType` member to the [cloudPcSnapshot](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta).",
```suggestion
                    "Description": "Added the `snapshotType` property to the [cloudPcSnapshot](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta).",
```

2023-02-02 03:11 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the `expirationDateTime` member to the [cloudPcSnapshot](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta).",
```suggestion
                    "Description": "Added the `expirationDateTime` property to the [cloudPcSnapshot](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta).",
```

2023-02-02 03:12 UTC, RuiHou105 requested changes
1.Please resolve comments in this pr.
2.Please create roadmap workitem and attach the workitem number in the comment

2023-02-06 07:24 UTC, AndrewYangMS commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|snapshotType| [cloudPcSnapshotType](#cloudpcsnapshottype-values)   | The type of snapshot, Indicates how is the snapshot be created. Possible value is `automatic` and `manual`. Default value is auto
fixed.

2023-02-06 07:25 UTC, AndrewYangMS commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the `expirationDateTime` member to the [cloudPcSnapshot](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta).",
fixed.

2023-02-09 08:01 UTC, AndrewYangMS commented
> 1.Please resolve comments in this pr. 2.Please create roadmap workitem and attach the workitem number in the comment

https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/16459 , roadmap workitem for this pr.

2023-02-09 08:23 UTC, RuiHou105 approved these changes

2023-02-15 20:56 UTC, dodaromike approved these changes

2023-02-16 03:37 UTC, RuiHou105 commented
@Lauragra  Please help review/approve this PR as the graph schema already went alive, thanks! :)

2023-02-16 17:18 UTC, dodaromike commented
@Lauragra I reviewed this PR following Isaac's checklist, adding an enum property to an entity.  Probably good idea for you to check it.

2023-02-17 18:39 UTC, Lauragra commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|snapshotType| [cloudPcSnapshotType](#cloudpcsnapshottype-values)   | The type of snapshot, Indicates how the snapshot be created. Possible values are `automatic`, `manual`. Default value is automati
We list the properties in the Properties table in alphabetical order. Please make sure that these properties are alphabetized. Also, there are some typos in the description. Please revise as:

The type of snapshot to be created. Possible values are `automatic`, `manual`. Default value is `automatic`.

2023-02-17 18:40 UTC, Lauragra commented on api-reference/beta/resources/cloudpcsnapshot.md
> +Describe the type of cloud pc snapshot.
Do we need this introductory sentence? If so, let's match the description in the properties table, i.e. "Indicates the type of Cloud PC snapshot." Note that Cloud PC is capitalized.

2023-02-17 18:40 UTC, Lauragra commented on api-reference/beta/resources/cloudpcsnapshot.md
> +| `unknownFutureValue` | `2`   | Evolvable enumeration sentinel value. Do not use..    |
Please remove the extra period here.

2023-02-17 18:41 UTC, Lauragra commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the `snapshotType` property to the [cloudPcSnapshot](https://learn.microsoft.com/en-us/graph/api/resources/cloudpcsnapshot?view=graph-rest-beta).",
Please format property names as bold instead of inline code (we use inline code for values).

2023-02-20 07:28 UTC, AndrewYangMS commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|snapshotType| [cloudPcSnapshotType](#cloudpcsnapshottype-values)   | The type of snapshot, Indicates how the snapshot be created. Possible values are `automatic`, `manual`. Default value is automati
Thank you Lauragra for your valuable suggestions!

Updated it per your suggestions, would you like to help review it again?
Thanks!

2023-02-20 12:30 UTC, AndrewYangMS commented on api-reference/beta/resources/cloudpcsnapshot.md
> +Describe the type of cloud pc snapshot.
Resolved. @Lauragra , could you help to review it again? thanks.

2023-02-27 02:43 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcsnapshot.md
> +|snapshotType| [cloudPcSnapshotType](#cloudpcsnapshottype-values)   | The type of snapshot, Indicates how the snapshot to be created. Possible values are `automatic`, `manual`. Default value is `auto
```The type of snapshot, Indicates how the snapshot to be created.```
```The type of snapshot, **i**ndicates how the snapshot to be created.```

2023-02-27 02:44 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcsnapshot.md
> +| Member name          | Value | Description                                           |
No need for value column. Could you help remove?

2023-02-27 02:44 UTC, AshleyYangSZ approved these changes

2023-02-28 04:21 UTC, merged