add new property into policy entity
microsoftgraph/microsoft-graph-docs pull request #20082
Opened 2023-02-01 02:18 UTC by Guoan-Tang

2023-02-01 02:25 UTC, RuiHou105 requested changes
@Guoan-Tang  Please also create a roadmap workitem and attach the workitem number.

2023-02-15 06:35 UTC, AshleyYangSZ requested changes
1. Please update PR title to [CloudPC] Add cloudPcNamingTemplate to policy entity
2. Do remember to add change-log

2023-02-23 10:49 UTC, AshleyYangSZ approved these changes

2023-04-10 18:54 UTC, dodaromike commented
> @Guoan-Tang Please also create a roadmap workitem and attach the workitem number.

@Guoan-Tang  Has this request been fixed?

2023-04-24 20:37 UTC, dodaromike approved these changes

2023-05-09 03:53 UTC, merged