Create include file - access reviews filter by scope
microsoftgraph/microsoft-graph-docs pull request #20089
Opened 2023-02-01 14:21 UTC by FaithOmbongi

2023-02-01 18:31 UTC, isabelleatmsft requested changes
some input on correctness needed from eng

2023-02-01 18:31 UTC, isabelleatmsft commented on api-reference/includes/accessreviews-definition-filter-scope.md
> +|`roleAssignmentScheduleInstances`  |List every accessReviewScheduleDefinition for service principals assigned to a privileged role.|
I think this description is incorrect. From levi's message to the customer, 'roleAssignmentScheduleInstances' returns every review for a privileged role, not just those scoped to service principals. @leherpel could you confirm whether this is true?

2023-02-01 18:31 UTC, isabelleatmsft commented on api-reference/includes/accessreviews-definition-filter-scope.md
> +|`/groups/{group id}`  |List every accessReviewScheduleDefinition on a specific group (excludes definitions scoped to all Microsoft 365 groups with guest users).|
@leherpel  does this syntax apply to all review types. Ex: what about roleassignmentscheduleinstances/roleID ?

2023-02-01 18:31 UTC, isabelleatmsft commented on api-reference/includes/accessreviews-definition-filter-scope.md
> +|Value|Description|
@leherpel what about filtering on reviews of applications and Azure roles? The Azure roles one is tricky, since these are created using ARM APIs and not graph so we definitely wouldnt support that filter on create/list definition - but does the review history report allow for filtering by this type?

2023-02-06 23:01 UTC, leherpel commented on api-reference/includes/accessreviews-definition-filter-scope.md
> +|`/groups/{group id}`  |List every accessReviewScheduleDefinition on a specific group (excludes definitions scoped to all Microsoft 365 groups with guest users).|
This currently only is supported in group reviews and access package assignment reviews, i.e: /identityGovernance/accessReviews/definitions?$filter=scope/query eq '/beta/identityGovernance/entitlementManagement/accessPackageAssignments?$filter=(accessPackageId eq ''137e09cc-10a5-492d-8c7b-4b1315027704'' and assignmentPolicyId eq ''810490ac-a438-40b4-9114-ef8eeec628b2'' and catalogId eq ''d0f10d34-05c2-4786-af64-c59795a84631'')'

2023-02-06 23:06 UTC, leherpel commented on api-reference/includes/accessreviews-definition-filter-scope.md
> +|`/groups/{group id}`  |List every accessReviewScheduleDefinition on a specific group (excludes definitions scoped to all Microsoft 365 groups with guest users).|
However a customer can create a review of this type using our Graph API: https://learn.microsoft.com/en-us/graph/accessreviews-scope-concept

2023-02-06 23:08 UTC, leherpel commented on api-reference/includes/accessreviews-definition-filter-scope.md
> +|Value|Description|
We don't support a scope for applications yet in reports as that's not supported in our Graph API: https://learn.microsoft.com/en-us/graph/accessreviews-scope-concept

We do support an Azure role scope but not through our Graph API a user would have to call our ARM API to create the Azure role review and review history report. However, the objects and properties are the same in our ARM and Graph API, i.e `accessReviewScheduleDefinition`

2023-02-13 21:00 UTC, isabelleatmsft approved these changes

2023-02-15 02:13 UTC, merged