Update callRecords changelog with new sessions pageSize
microsoftgraph/microsoft-graph-docs pull request #20111
Opened 2023-02-02 01:13 UTC by mcm223

The callRecords API now has a maximum page size of 60 for returned sessions in both beta and v1.0.

2023-03-02 01:18 UTC, Danielabom commented
Contacted author to get info.

2023-03-08 18:59 UTC, Danielabom commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Change maximum page size to 60 sessions for a [callRecords query](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.
```suggestion
                    "Description": "Change the maximum page size to 60 sessions in a query for the [callRecords](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0) resource.",
```

2023-03-08 19:09 UTC, Danielabom commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Change maximum page size to 60 sessions for a [callRecords query](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-be
```suggestion
                    "Description": "Changed the maximum page size to 60 sessions in a query for the [callRecords](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta) resource.",
```

2023-03-08 19:32 UTC, Danielabom requested changes
Thank you for working on this PR.  I added some comments, please review them. Just one more thing: I assume that the previous size was expected or the default behavior. Wouldn't updating the resource's topic with a note be important?

2023-03-08 21:05 UTC, mcm223 commented
Thank you @Danielabom! I've committed your suggested language changes.

> I assume that the previous size was expected or the default behavior. Wouldn't updating the resource's topic with a note be important?

I reviewed our other API docs and we don't currently specify maximum page sizes for any of them. We do make a more general comment that truncated results will have a ```odata.nextLink``` value. I have a rather large batch of doc updates planned so I can include max page sizes for all our endpoints in a future PR, as I agree I think it would be good to have them all explicitly listed, but I don't have them all handy at the moment and I'd prefer not to have them inconsistently documented.

2023-03-14 20:54 UTC, Danielabom approved these changes
Thank you for working on this PR and thank you for addressing my comments. PR approved. Thanks.

2023-03-15 00:45 UTC, Lauragra commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Changed the maximum page size to 60 sessions in a query for the [callRecords](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=g
This is a link to the API overview topic, not the callRecords resource topic. I don't see anywhere in either the callRecords or the session resource topics where we mention a maximum page size. Please add updates to the associated documentation to this PR before we merge, and update the links to target the appropriate updated docs. Thanks.

2023-03-16 00:18 UTC, mcm223 commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Changed the maximum page size to 60 sessions in a query for the [callRecords](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=g
I've updated the links and added the page size where we discuss pagination in getting the call record.

2023-03-21 17:57 UTC, Danielabom commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Target": "callRecord"
```suggestion
                    "Target": "callRecords"
```

2023-03-21 17:57 UTC, Danielabom commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Target": "callRecord"
```suggestion
                    "Target": "callRecords"
```

2023-03-21 18:01 UTC, Danielabom approved these changes
@Lauragra, it seems that all the changes you requested are in. Thanks!

2023-03-21 20:50 UTC, Danielabom commented
@mcm223, thank you for addressing our comments. Your PR is almost ready; however, the build keeps failing. Please look into it.

2023-03-23 02:50 UTC, merged