App auth method policy GA docs
microsoftgraph/microsoft-graph-docs pull request #20127
Opened 2023-02-03 00:54 UTC by madansr7

2023-02-13 11:44 UTC, FaithOmbongi commented
Hi @madansr7 - Please open a content review work item in my ADO via this link https://aka.ms/msgraph-identity-workitem.

2023-02-13 23:49 UTC, madansr7 commented
@FaithOmbongi created ADO workitem. 
Also, i don't know why the change log is failing. I am not able to see the exact error. Can you help.

2023-02-24 18:22 UTC, madansr7 commented
@FaithOmbongi can you please review these docs.

2023-02-27 15:26 UTC, msewaweru commented
> @FaithOmbongi can you please review these docs.

@madansr7, the link to the schema PR has not been added to [the work item](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63741). Please update.

2023-03-08 15:46 UTC, madansr7 commented
@FaithOmbongi could we get this reviewed please? I am waiting on docs to send the GA announcement.

2023-03-08 17:45 UTC, FaithOmbongi requested changes
Thank you @madansr7 for your work on this PR. I've left suggestions inline plus the following:

**Beta**
- Surface **Delete appliesTo** in the Methods table of appmanagementpolicy.md file (beta).

**v1.0**

- Surface the **appManagementPolicies** relationship in serviceprincipal.md and application.md.
- Surface the **appManagementPolicies** and **defaultAppManagementPolicy** relationships in policyroot.md.
- **GLOBAL:** Remove all the `# [HTTP](#tab/http)` tab lines that remained from copying the files from beta. This line is added by the snippet generator. These leftover lines mess up how snippets are added to your files.
- **GLOBAL**: All URLs in v1.0 docs should be updated from beta to v1.0. There are too many cases left over from beta.
- For LIST and GET files, we got the file names wrong the first time. Should be policyroot-list-appmanagementpolicies.md and policyroot-post-appmanagementpolicies.md.
   - You can either fix the file names in both beta and v1.0, then [add redirects](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/redirects/.openpublishing.redirection.changedapi.json) for beta
   - Or you can leave them as they are and I can raise a PR to fix beta and [add redirects](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/redirects/.openpublishing.redirection.changedapi.json) later.
- GLOBAL: Please lowercase all the file names.


I've also pushed a commit to clean up the changelog.

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/tenantappmanagementpolicy-get.md
> +# [HTTP](#tab/http)
remove

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/tenantappmanagementpolicy-get.md
> +GET https://graph.microsoft.com/beta/policies/defaultAppManagementPolicy
v1.0

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/tenantappmanagementpolicy-get.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#policies/defaultAppManagementPolicy/$entity",
v1.0

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/tenantappmanagementpolicy-update.md
> +> Service principals with a createdDateTime `null` are treated as having being created on 01/01/2019.
same comment I left in beta applies here

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/tenantappmanagementpolicy-update.md
> +> Service principals with a createdDateTime `null` are treated as having being created on 01/01/2019.
comment I left in beta applies here

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appManagementPolicy.md
> +---
lowercase the file name

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appManagementPolicy.md
> +description: "An application auth method policy for enforcing app management restrictions on specific application or service principals."
```suggestion
description: "An application auth method policy for enforcing app management restrictions on specific applications or service principals."
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appManagementPolicy.md
> +| [Assign appliesTo](../api/appManagementPolicy-post-appliesTo.md)| None |Returns a list of applications and service principals to which the policy is applied. |
```suggestion
| [List](../api/appManagementPolicy-list.md)      | [appManagementPolicy](../resources/appManagementPolicy.md) | Return a list of app management policies created for applications and service principals along with their properties. |
| [Create](../api/appManagementPolicy-post.md)    | [appManagementPolicy](../resources/appManagementPolicy.md) | Create an app management policy that can be assigned to an application or service principal object.                   |
| [Get](../api/appManagementPolicy-get.md)       | [appManagementPolicy](../resources/appManagementPolicy.md) | Get a single app management policy object.                                                                            |
| [Update](../api/appManagementPolicy-update.md) | None                                                                       | Update an app management policy.                                                                                      |
| [Delete](../api/appManagementPolicy-delete.md) | None                                                                       | Delete an app management policy from the collection of policies in appManagementPolicies.                             |
| [List appliesTo](../api/appManagementPolicy-list-appliesTo.md)| [appManagementPolicy](../resources/appManagementPolicy.md)|Return a list of applications and service principals to which the policy is applied. |
| [Assign appliesTo](../api/appManagementPolicy-post-appliesTo.md)| None |Return a list of applications and service principals to which the policy is applied. |
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appManagementPolicy.md
> +| appliesTo    | [directoryObject](directoryobject.md) | Collection of application and service principals to which a policy is applied. |
```suggestion
| appliesTo    | [directoryObject](directoryobject.md) | Collection of applications and service principals to which the policy is applied. |
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appManagementPolicy.md
> +| id           | String                                                      | The policy identifier.                                                 |
```suggestion
| id           | String                                                      | Identifier for the policy.                                                 |
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-list.md
> +---
We got this file name wrong in beta. I don't know if you want to fix it in this PR + in beta and then add redirects so customers don't get 404s?

The correct file name should have been policyroot-list-appmanagementpolicies.md as per the file naming guidance.

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-post.md
> +---
Same as the LIST file, we got this file name wrong in beta. Should be policyroot-post-appmanagementpolicies.md

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-post.md
> +> Service principals with a createdDateTime `null` are treated as having being created on 01/01/2019.
Same comment made earlier applies.

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-post.md
> +In the request body, provide a JSON representation of an [appManagementPolicy](../resources/appManagementPolicy.md).
This section should actually be listing the properties that can be specified during Create operation and whether they are Optional or Required. Oversight in beta review.

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appManagementPolicy-update.md
> +For best performance, don't include existing values that haven't changed.
We changed this boilerplate to an include file to help with downstream automation.
```suggestion
[!INCLUDE [table-intro](../../includes/update-property-table-intro.md)]
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appManagementPolicy-list-appliesTo.md
> +---
all lowercase the file name

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appManagementPolicy-delete.md
> +---
lowercase the file name

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appManagementPolicy-list-appliesTo.md
> +List application and service principal objects assigned an [appManagementPolicy](../resources/appManagementPolicy.md) policy object.
```suggestion
List application and service principal objects that are assigned an [appManagementPolicy](../resources/appManagementPolicy.md) policy object.
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appManagementPolicy-list-appliesTo.md
> +
```suggestion
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appManagementPolicy-list-appliesTo.md
> +```msgraph-interactive
nit: GLOBAL: Any of these requests that requires an ID, consider removing `msgraph-interactive` and replacing with `http`.

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
> +description: "Remove a policy to application or service principal object."
```suggestion
description: "Remove an appManagementPolicy from an application or service principal object."
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
> +Remove an [appManagementPolicy](../resources/appManagementPolicy.md) policy object to an application or service principal object. The application or service principal adopts this policy over the tena
Same change I requested in beta
```suggestion
Remove an [appManagementPolicy](../resources/appManagementPolicy.md) policy object from an application or service principal object. When you remove the appManagementPolicy, the application or service principal adopts the tenant-wide [tenantAppManagementPolicy](../resources/tenantappmanagementpolicy.md) setting. 
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
> +The following is an example of the request to remove an appManagementPolicy to an application.
```suggestion
The following is an example of the request to remove an appManagementPolicy from an application.
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
> +### Example 1: Remove an appManagementPolicy to an application object
```suggestion
### Example 1: Remove an appManagementPolicy from an application object
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
> +The following is an example of the request to remove an appManagementPolicy to a service principal.
```suggestion
### Example 2: Remove an appManagementPolicy from a service principal object

#### Request

The following is an example of the request to remove an appManagementPolicy from a service principal.
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/beta/api/appmanagementpolicy-delete-appliesto.md
> +### Example 1: Remove an appManagementPolicy to an application object
```suggestion
### Example 1: Remove an appManagementPolicy from an application object
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/beta/api/appmanagementpolicy-delete-appliesto.md
> +The following is an example of the request to remove an appManagementPolicy to an application.
```suggestion
The following is an example of the request to remove an appManagementPolicy from an application.
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/beta/api/appmanagementpolicy-delete-appliesto.md
> +The following is an example of the request to remove an appManagementPolicy to a service principal.
```suggestion
### Example 2: Remove an appManagementPolicy from a service principal object

#### Request

The following is an example of the request to remove an appManagementPolicy from a service principal.
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-post-appliesto.md
> +description: "Assign a policy to application or service principal object."
```suggestion
description: "Assign an appManagementPolicy to an application or service principal object."
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +              - name: Delete appliesTo
Lowercase the file names please
```suggestion
              href: resources/applicationauthenticationmethodpolicy.md
            - name: Tenant app management policy
              items:
              - name: Tenant app management policy
                href: resources/tenantappmanagementpolicy.md
              - name: Get
                href: api/tenantappmanagementpolicy-get.md
              - name: Update
                href: api/tenantappmanagementpolicy-update.md
            - name: App management policy
              items:
              - name: App management policy
                href: resources/appmanagementpolicy.md
              - name: List
                href: api/appmanagementpolicy-list.md
              - name: Get
                href: api/appmanagementpolicy-get.md
              - name: Create
                href: api/appmanagementpolicy-post.md
              - name: Update
                href: api/appmanagementpolicy-update.md
              - name: Delete
                href: api/appmanagementpolicy-delete.md
              - name: Create applies to
                href: api/appmanagementpolicy-post-appliesTo.md
              - name: List applies to
                href: api/appmanagementpolicy-list-appliesTo.md
              - name: Delete applies to
```

2023-03-08 17:45 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +                href: api/appmanagementpolicy-delete-appliesTo.md
```suggestion
                href: api/appmanagementpolicy-delete-appliesto.md
```

2023-03-09 17:29 UTC, madansr7 commented on api-reference/beta/api/tenantappmanagementpolicy-update.md
> +
me too. :-)

2023-03-10 19:55 UTC, madansr7 commented on api-reference/v1.0/api/appmanagementpolicy-list.md
> +---
Could we track it as a separate PR. I didn't realize the naming was wrong.

2023-03-12 16:54 UTC, madansr7 commented on api-reference/beta/api/appmanagementpolicy-post.md
> +> Service principals with a createdDateTime `null` are treated as having being created on 01/01/2019.
I think it is important to tell since it affects the enforcement of the policy.

2023-03-12 16:55 UTC, madansr7 commented on api-reference/beta/api/tenantappmanagementpolicy-update.md
> +
Resolving, let me know if you disagree.

2023-03-12 17:00 UTC, madansr7 commented on api-reference/v1.0/api/appManagementPolicy-delete.md
> +---
updated.

2023-03-12 17:03 UTC, madansr7 commented on api-reference/v1.0/api/appManagementPolicy-list-appliesTo.md
> +---
Done. This naming thing seems like something that should be built in the graph docs processing. Humans will inadvertently do this repeatedly, it would be better to fix it for them rather than asking them to make changes. Most developers are used to lower camel casing for file names.

2023-03-12 17:05 UTC, madansr7 commented on api-reference/v1.0/api/appmanagementpolicy-list.md
> +---
Curious to know if we are changing the names of other policies under the policy endpoint?

2023-03-12 17:06 UTC, madansr7 commented on api-reference/v1.0/api/appmanagementpolicy-post.md
> +> Service principals with a createdDateTime `null` are treated as having being created on 01/01/2019.
It is important, because customers have tripped on this in preview.

2023-03-12 17:10 UTC, madansr7 commented on api-reference/v1.0/api/appmanagementpolicy-post.md
> +In the request body, provide a JSON representation of an [appManagementPolicy](../resources/appManagementPolicy.md).
Can you provide an example of a page where this is done.

2023-03-12 17:18 UTC, madansr7 commented on api-reference/v1.0/api/tenantappmanagementpolicy-get.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#policies/defaultAppManagementPolicy/$entity",
updated.

2023-03-12 17:18 UTC, madansr7 commented on api-reference/v1.0/api/tenantappmanagementpolicy-get.md
> +GET https://graph.microsoft.com/beta/policies/defaultAppManagementPolicy
updated

2023-03-12 17:19 UTC, madansr7 commented on api-reference/v1.0/api/tenantappmanagementpolicy-get.md
> +# [HTTP](#tab/http)
updated.

2023-03-12 17:22 UTC, madansr7 commented on api-reference/v1.0/resources/tenantAppManagementPolicy.md
> +---
updated.

2023-03-12 17:23 UTC, madansr7 commented on api-reference/v1.0/resources/tenantAppManagementPolicy.md
> +| servicePrincipalRestrictions | [appManagementConfiguration](../resources/appManagementConfiguration.md) | Restrictions that apply as default to all service principal objects in the tenant. |
updated.

2023-03-12 17:24 UTC, madansr7 commented on api-reference/v1.0/resources/appManagementPolicy.md
> +---
updated.

2023-03-12 18:09 UTC, madansr7 commented on api-reference/v1.0/api/appmanagementpolicy-post.md
> +In the request body, provide a JSON representation of an [appManagementPolicy](../resources/appManagementPolicy.md).
updated.

2023-03-12 18:15 UTC, madansr7 commented on api-reference/v1.0/api/appmanagementpolicy-post.md
> +---
We should treat this one separately. I am worried about delaying these docs.

2023-03-12 18:18 UTC, madansr7 commented
@FaithOmbongi , all comments have been addressed. Please re-review.
I made all suggested changes except for renaming the resources under policyRoot which would require a redirect setup. I am worried that we are mixing two issues and efforts which might delay these docs.

2023-03-16 08:15 UTC, FaithOmbongi commented
> @madansr7, your content reviewer has requested changes to your pull request. Please review feedback and address accordingly as soon as possible to keep your pull request moving forward.
> 
> Once you have addressed the feedback, please add the `review feedback addressed` label and select the **Re-request review** icon.
> 
> If you cannot add labels, please add a comment with `#feedback-addressed` to the pull request.
> 
> Check the content review workflow [here](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow?anchor=content-review-process-summary).

Hmm @madansr7 - I didn't know you were waiting on a re-review because the PR doesn't have "signals" 👆🏾. I've added it to my re-review queue.

2023-03-16 11:40 UTC, FaithOmbongi commented on api-reference/v1.0/api/appmanagementpolicy-list.md
> +---
> Curious to know if we are changing the names of other policies under the policy endpoint?

Yep, we've fixed some. Others will be fixed when they are GAing or when we have enough bandwidth to clean up the docs.

2023-03-16 15:27 UTC, FaithOmbongi approved these changes
Hi @madansr7 - I've pushed [a commit](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20127/commits/b07918703ecb452038d87e1356c418d39ae1366f) to resolve comments left over from [this feedback](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20127#pullrequestreview-1331030004) then approved.

2023-03-17 20:51 UTC, madansr7 commented
@msewaweru , this PR is waiting your approval. Can you please approve.

2023-03-21 07:18 UTC, msewaweru approved these changes
Thank you, @madansr7.

2023-03-23 03:05 UTC, merged