Add user-scoping permissions
microsoftgraph/microsoft-graph-docs pull request #20134
Opened 2023-02-03 15:19 UTC by microzon

User-scoping permissions are for getting DataLossPrevention policies and InformationProtection configurations for a specific user.

2023-02-03 15:23 UTC, microzon commented
> @microsoft-github-policy-service agree company="Microsoft"

@microsoft-github-policy-service agree company="Microsoft"

2023-02-06 10:15 UTC, FaithOmbongi commented
Hi @microzon - Please follow the [Get started steps](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started?anchor=get-started-steps) to set yourself up as an internal contributor. Takes ~2mins.

@Danielabom - Can you pick this up for review? Thanks!

2023-02-06 15:00 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _DataLossPrevention.Read_ | Read data loss prevention policies applicable to a user | Allows an app to read data loss prevention policies, on behalf of the signed-in user. | Yes |
```suggestion
| _DataLossPrevention.Read_ | Read data loss prevention policies applicable to a user | Allows an app to read data loss prevention policies on behalf of the signed-in user. | Yes |
```

2023-02-06 15:01 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _InformationProtectionConfig.Read_ | Read information protection configurations applicable to a user | Allows an app to read information protection configurations, on behalf of the signed-in user.
```suggestion
| _InformationProtectionConfig.Read_ | Read information protection configurations applicable to a user | Allows an app to read information protection configurations on behalf of the signed-in user. | Yes |
```

2023-02-06 15:04 UTC, Danielabom requested changes
Thank you for working on this PR @microzon. Please review my comments: 
We need a changelog entry for each new permission. See example 14 from this link:  [(https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)
I need to confirm somewhere the APi topics that will use these permissions, like an Api.md file or a roadmap item.

2023-02-06 17:12 UTC, microzon commented
> Thank you for working on this PR @microzon. Please review my comments: We need a changelog entry for each new permission. See example 14 from this link: [(https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog) I need to confirm somewhere the APi topics that will use these permissions, like an Api.md file or a roadmap item.

@Danielabom : The api.md where the APIs that will use the new permissions are defined: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding?path=%2Freviews%2F213-Add-data-classification-service-API-to-Graph%2Fapi.md&version=GBmaster&_a=preview.

Specific PRs for adding the 2 new APIs:
1. https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11857
2. https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11990

2023-02-08 01:48 UTC, Danielabom commented on changelog/Microsoft.DataClassificationService.json
> +          "Description": "Added support for the application permission of `DataLossPrevention.Read.All` to get the data loss prevention policies for the user resource.",
Hi, please follow the description format listed in example 14 of this wiki [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog]. 

 "Description": "Added support for the policy-based application permission of `DataLossPrevention.Read.All` to the read operations of the [_**_resource_**_](https://learn.microsoft.com/en-us/graph/api/resources/**_resourcename_**?view=graph-rest-**_version_**) resource.",

2023-02-08 01:52 UTC, Danielabom commented on changelog/Microsoft.DataClassificationService.json
> +          "Description": "Added support for the delegated permission of `DataLossPrevention.Read` to get the data loss prevention policies for the user resource.",
Hi, please follow the description format listed in example 14 of this wiki [https://dev.azure.com/msazure/One/wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog].
You are missing the resource links; check this example:
"Added support for the policy-based application permission of OnlineMeetings.ReadWrite.All to the read and write operations of the resource name (_resource link__) resource.",

2023-02-08 01:52 UTC, Danielabom commented on changelog/Microsoft.DataClassificationService.json
> +          "Description": "Added support for the delegated permission of `InformationProtectionConfig.Read` to get the information protection configurations for the user resource.",
Hi, please follow the description format listed in example 14 of this wiki [https://dev.azure.com/msazure/One/wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog].
You are missing the resource links; check this example:
"Added support for the policy-based application permission of OnlineMeetings.ReadWrite.All to the read and write operations of the resource name (_resource link__) resource.",

2023-02-08 01:54 UTC, Danielabom requested changes
Please review my comments. Thanks. 
By the way, the GS tool is not expected to automatically create changelog entries for new permissions. Those are always added manually.

2023-02-08 17:27 UTC, microzon commented on changelog/Microsoft.DataClassificationService.json
> +          "Description": "Added support for the application permission of `DataLossPrevention.Read.All` to get the data loss prevention policies for the user resource.",
Updated as suggested.

2023-02-08 17:28 UTC, microzon commented on changelog/Microsoft.DataClassificationService.json
> +          "Description": "Added support for the delegated permission of `DataLossPrevention.Read` to get the data loss prevention policies for the user resource.",
Updated as suggested.

2023-02-08 17:28 UTC, microzon commented on changelog/Microsoft.DataClassificationService.json
> +          "Description": "Added support for the delegated permission of `InformationProtectionConfig.Read` to get the information protection configurations for the user resource.",
Updated as suggested.

2023-02-08 18:16 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _InformationProtectionConfig.Read_ | Read information protection configurations applicable to a user | Allows an app to read information protection configurations on behalf of the signed-in user. |
```suggestion
| _InformationProtectionConfig.Read_ | Read information protection configurations applicable to a user | Allows an app to read information protection configurations on behalf of the signed-in user. | Yes|
```

2023-02-08 18:25 UTC, Danielabom approved these changes
Changes look good. Thanks, @microzon

2023-02-15 15:27 UTC, Danielabom commented
Contacted the author via email to follow-up.

2023-03-14 06:37 UTC, microzon commented
Closing the pull request as Graph team suggested to rename "DataLossPrevention.Read" due to hash collision with MSA permission.

2023-03-14 06:37 UTC, closed without merging