[CloudPC] Documentation update for new API - GetProvisionedCloudPCs
microsoftgraph/microsoft-graph-docs pull request #20183
Opened 2023-02-09 10:07 UTC by SleepIsImportant

2023-02-10 02:09 UTC, AshleyYangSZ requested changes
Please add changelog to Microsoft.CloudManageDesktop.json.
Please update toc.yml to include the cloudpc-getprovisionedcloudpcs api entry point https://learn.microsoft.com/en-us/graph/api/resources/cloudpcreviewstatus?view=graph-rest-beta.
![image](https://user-images.githubusercontent.com/72924235/217982533-df001d9c-7a5c-468f-9457-c25b0933cde1.png)

2023-02-10 02:09 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-getprovisionedcloudpcs.md
> +# [C#](#tab/csharp)
Remove line 77 to line  99. No need to add this.

2023-03-06 07:04 UTC, AshleyYangSZ commented
apidoctor build failed, please help resolve.

2023-03-07 08:08 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-getprovisionedcloudpcs.md
> +|groupId|Guid|The unique identifier for Azure Active Directory (AAD) user group.|
Update Guid to String. Same for below parameter.

2023-03-07 08:11 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-getprovisionedcloudpcs.md
> +# [HTTP](#tab/http)
Remove this extra line.

2023-03-07 09:33 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +          - name: Get provisioned cloudPCs by groupId and servicePlanId
Please move this one after `- name: Get launch info for user`, as all functions/actions should be ordered alphabetically.

2023-03-23 02:48 UTC, RuiHou105 requested changes
@SleepIsImportant  Please also update the changelog to describe your change.

2023-03-31 09:13 UTC, paulodero commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "getProvisionedCludPcs",
Should be `getprovisionedcloudpcs`?

2023-05-24 03:35 UTC, AshleyYangSZ requested changes

2023-05-24 03:35 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the [getProvisionedCloudPcs](https://learn.microsoft.com/en-us/graph/api/cloudpc?view=graph-rest-beta) method to the [cloudPC](https://learn.microsoft.com/en
The link is not correct, it should link to API file not cloudpc resource file
`[getProvisionedCloudPcs](https://learn.microsoft.com/en-us/graph/api/cloudpc?view=graph-rest-beta) method`

2023-05-30 14:21 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the [getProvisionedCloudPcs](https://learn.microsoft.com/en-us/graph/api/cloudpc?view=graph-rest-beta) method to the [cloudPC](https://learn.microsoft.com/en
```suggestion
                    "Description": "Added the [getProvisionedCloudPcs](https://learn.microsoft.com/en-us/graph/api/cloudpc-getprovisionedcloudpcs?view=graph-rest-beta) method to the [cloudPC](https://learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta) for end-user.",
```

2023-05-30 14:24 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getprovisionedcloudpcs.md
> +|groupId|Guid|The unique identifier for Azure Active Directory (AAD) user group.|
@SleepIsImportant, I do not see Rui's comments applied. Please review.

2023-05-30 14:25 UTC, Danielabom requested changes
@SleepIsImportant, thank you for working on this PR. Please review my comments.

2023-06-01 22:49 UTC, Danielabom approved these changes
PR approved.

2023-06-07 23:29 UTC, Danielabom commented on api-reference/beta/api/cloudpc-getprovisionedcloudpcs.md
> +|groupId|Guid|The unique identifier for Azure Active Directory (AAD) user group.|
@SleepIsImportant @RuiHou105, reposting: I am confused about Rui's comment. Should the type be updated or not? Please make sure all technical reviewer comments have been resolved before moving to the content review. Thanks!

2023-06-08 01:32 UTC, SleepIsImportant commented
> 
fixed changedLog thank you

2023-06-08 01:33 UTC, SleepIsImportant commented
> @SleepIsImportant Please also update the changelog to describe your change.

Fixed, thank you

2023-06-08 17:48 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the [getProvisionedCloudPcs](https://learn.microsoft.com/en-us/graph/api/cloudpc-getprovisionedcloudpcs?view=graph-rest-beta) method to the [cloudPC](https:/
```suggestion
                    "Description": "Added the [getProvisionedCloudPcs](https://learn.microsoft.com/en-us/graph/api/cloudpc-getprovisionedcloudpcs?view=graph-rest-beta) method to the [cloudPC](https://learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta) resource.",
```

2023-06-08 17:50 UTC, Danielabom commented on api-reference/beta/toc.yml
> +          - name: Get provisioned cloudPCs by groupId and servicePlanId
```suggestion
          - name: Get provisioned Cloud PCs by group Id and service plan id
```

2023-06-08 17:51 UTC, Danielabom approved these changes
PR approved.

2023-06-26 16:13 UTC, Danielabom commented
'@SleepIsImportant, please add the "ready-to-merge" label if you are ready to publish.

2023-06-27 02:01 UTC, merged