MV Extension API Updates
microsoftgraph/microsoft-graph-docs pull request #20186
Opened 2023-02-09 12:01 UTC by rahul-nagraj

2023-04-05 16:09 UTC, rahul-nagraj commented
#sign-off

2023-04-12 16:09 UTC, FaithOmbongi requested changes
Thank you @rahul-nagraj for your work on this PR. I've left feedback inline plus the following:
- Also, add the property to the properties table and JSON representation of [extensionproperty.md](https://learn.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-beta). And indicate that it supports $filter with eq.
- Add the property to the payloads in the LIST and GET examples.

NOTE: Let's sync internally so I can:
+ Update the comparison table in the [extensions overview article](https://learn.microsoft.com/en-us/graph/extensibility-overview?view=graph-rest-1.0&tabs=http#choose-an-extension-type-for-your-application) and document that directory extensions can be multi-valued.
+ Update the examples relating to directory extensions to show this property. It'll also be good to add an example of how to filter when the property is multivalued. Let's not allow this capability to go unnoticed.

2023-04-12 16:09 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the `isMultiValued` property to the [extensionProperty](https://learn.microsoft.com/en-us/graph/api/resources/extensionProperty?view=graph-rest-beta) resource.",
Suggestion to enhance the description to improve the discoverability of this capability. Dan has called out this capability for directory extensions and coming soon for schema extensions.
```suggestion
          "Description": "Added the `isMultiValued` property to the [extensionProperty](https://learn.microsoft.com/en-us/graph/api/resources/extensionProperty?view=graph-rest-beta) resource. You can now store a collection of values in a directory extension property.",
```

2023-04-12 17:29 UTC, rahul-nagraj commented
#feedback-addressed

2023-05-03 13:40 UTC, FaithOmbongi approved these changes

2023-05-23 02:14 UTC, merged