[CloudPC] Documentation update for cloudPcStatus.movingRegion
microsoftgraph/microsoft-graph-docs pull request #20184
Opened 2023-02-09 10:31 UTC by SleepIsImportant

2023-02-10 02:14 UTC, AshleyYangSZ requested changes
Please add change log

2023-03-06 07:01 UTC, AshleyYangSZ commented
The build failed for this PR, please help resolve.

2023-03-07 03:40 UTC, AshleyYangSZ approved these changes

2023-03-07 05:53 UTC, RuiHou105 approved these changes

2023-05-29 16:55 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|movingRegion|Indicates that Cloud PC is being moved from one region to another one.|
```suggestion
|movingRegion|Indicates that Cloud PC is being moved from one region to another.|
```

2023-05-29 17:29 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|movingRegion|Indicates that Cloud PC is being moved from one region to another.|
In line 71 of the properties table, please add the "unknown future value" member and follow step 3 of this wiki: [Evolvable enums](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-3%3A-add-clarification-if-one-or-more-members-follow-unknownfuturevalue)

2023-05-29 17:30 UTC, Danielabom requested changes
Hi @SleepIsImportant, please review my comments. thanks!

2023-06-01 05:23 UTC, SleepIsImportant commented on api-reference/beta/resources/cloudpc.md
> +|movingRegion|Indicates that Cloud PC is being moved from one region to another.|
> In line 71 of the properties table (status), please add the "unknown future value" member and follow step 3 of this wiki: [Evolvable enums](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-3%3A-add-clarification-if-one-or-more-members-follow-unknownfuturevalue)

fixed, thank you

2023-06-01 22:58 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|status|[cloudPcStatus](#cloudpcstatus-values)|The status of the Cloud PC. Possible values are: `notProvisioned`, `provisioning`, `provisioned`, `upgrading`, `inGracePeriod`, `deprovisioning`, `faile
@SleepIsImportant. The update is not correct. 
The value of the new member "movingRegion is greater than "unknown future value". And for that reason, you need to follow step 3 in this wiki [Evolvable-enumerations](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

2023-06-07 23:47 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|movingRegion|Indicates that Cloud PC is being moved from one region to another.|
@SleepIsImportant, would you mind taking a second look at the wiki? The value movingRegion is greater than unknownFutureValue (based on what I see on the metadata), meaning there is a specific format for that. You will find the steps that you need to follow here: [Evolvable enums](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-3%3A-add-clarification-if-one-or-more-members-follow-unknownfuturevalue)

2023-06-08 20:56 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|status|[cloudPcStatus](#cloudpcstatus-values)|The status of the Cloud PC. Possible values include: `notProvisioned`, `provisioning`, `provisioned`, `inGracePeriod`, `deprovisioning`, `failed`, `prov
```suggestion
|status|[cloudPcStatus](#cloudpcstatus-values)|The status of the Cloud PC. The possible values are: `notProvisioned`, `provisioning`, `provisioned`, `inGracePeriod`, `deprovisioning`, `failed`, `provisionedWithWarnings`, `resizing`, `pendingProvision`, `restoring`, and `unknownFutureValue`. Note that you must use the `Prefer: include-unknown-enum-members` request header to get the following value in this `[evolvable enum](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations)`: `movingRegion`.|
```

2023-06-26 16:20 UTC, Danielabom commented
PR approved.

2023-06-27 02:01 UTC, merged