[CloudPC] Update document for new API - ValidateBulkResize
microsoftgraph/microsoft-graph-docs pull request #20199
Opened 2023-02-10 09:06 UTC by SleepIsImportant

2023-03-23 03:01 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Validate bulk resize](../api/cloudpc-validatebulkresize.md)|[cloudPcResizeValidateResult](../resources/cloudPcResizeValidationResult.md) collection|Validate selected a bulk of [cloudPC](../resource
```suggestion
|[Validate bulk resize](../api/cloudpc-validatebulkresize.md)|[cloudPcResizeValidateResult](../resources/cloudPcResizeValidationResult.md) collection|Validate selected [cloudPC](../resources/cloudpc.md) to see if their states meet the requirements to perform Bulk Resize.|
```

2023-03-23 03:07 UTC, RuiHou105 commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +Represents the validation result of single resized Cloud PC in bulk resize action.
I believe when performing `validateBulkResize `API, this Cloud PC actually hasn't been resized at all, right? So the word "resized" is not so accurate.

```suggestion
Represents the validation result of single Cloud PC in bulk resize action.
```

2023-03-23 03:09 UTC, RuiHou105 commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|validationResult|[cloudPcResizeValidationCode](#cloudpcresizevalidationcode-values)|The validation result for the Cloud PC resize action.|
```suggestion
|validationResult|[cloudPcResizeValidationCode](#cloudpcresizevalidationcode-values)|Describes  a list of the validation result for the Cloud PC resize action. Possible values are: ...|
```

2023-03-23 03:10 UTC, RuiHou105 commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|Member|Value|Description|
Please remove the column "Value" from the table.

2023-03-23 03:11 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +Validate selected a bulk of [cloudPC](../resources/cloudpc.md) to see if their states meet the requirements to perform Bulk Resize.
```suggestion
Validate a bulk of selected [cloudPC](../resources/cloudpc.md) to see if their states meet the requirements to perform Bulk Resize.
```

2023-03-23 03:13 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +|cloudPcIds|String collection|The identifier id of a set of Cloud PC.|
```suggestion
|cloudPcIds|String collection|The Cloud PC id list for selected Cloud PC devices to be validated. Max count is 2000..|
```

2023-03-23 03:14 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +|targetServicePlanId|String|The identifier id of targeted resized service plan.|
```suggestion
|targetServicePlanId|String|The target service plan id of the resize configuration with new vCPU and storage size.|
```

2023-03-23 03:16 UTC, RuiHou105 requested changes
@SleepIsImportant  Please create a roadmap workitem and attach the workitem number. Then please help resolve comments in this PR.

2023-05-24 08:08 UTC, AshleyYangSZ approved these changes

2023-05-24 18:06 UTC, Danielabom commented
Contacted author to get info.

2023-05-25 19:58 UTC, Danielabom commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +author: "Aria Zhang (yuzhang3)"
Please use a valid Github alias.

2023-05-25 19:58 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +author: "Aria Zhang (yuzhang3)"
Please use a valid Github alias.

2023-05-25 20:15 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +---
The filename must be in lowercase.

2023-05-25 20:17 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +description: "Represents the validation result of single resized Cloud PC in bulk resize action."
```suggestion
description: "Represents the validation result of a single resized Cloud PC during the bulk-resize action ."
```

2023-05-25 20:17 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +Represents the validation result of single Cloud PC in bulk resize action.
```suggestion
Represents the validation result of a single resized Cloud PC during the bulk-resize action .
```

2023-05-25 20:20 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|cloudPcId|String|The id of [cloudPC](../resources/cloudpc.md) with the result refers to.|
```suggestion
|cloudPcId|String|The [cloudPC](../resources/cloudpc.md) id that corresponds to its unique identifier.|
```

2023-05-25 20:22 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|success|Indicates that resize validation is success.|
```suggestion
|success|Indicates that the resize validation was successful.|
```

2023-05-25 20:23 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|operationConflict|Indicates that resize action has conflict with other action.|
```suggestion
|operationConflict|Indicates that resize action has a conflict with other action.|
```

2023-05-25 20:23 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|targetLicenseHasAssigned|Indicates that the target license has already been assigned to the User.|
```suggestion
|targetLicenseHasAssigned|Indicates that the target license has already been assigned to the user.|
```

2023-05-25 20:23 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|internalServerError|Indicates that the validation is failed with internal server error.|
```suggestion
|internalServerError|Indicates that the validation failed with an internal server error.|
```

2023-05-25 20:26 UTC, Danielabom commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +description: "Validate selected devices to see if their states meet the requirements to perform Bulk Resize."
```suggestion
description: "Validate the selected devices to see if their states meet the requirements to perform a bulk resize action."
```

2023-05-25 20:28 UTC, Danielabom commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +Validate a bulk of selected [cloudPC](../resources/cloudpc.md) to see if their states meet the requirements to perform Bulk Resize.
```suggestion
Validate the selected [cloudPC](../resources/cloudpc.md) devices to see if their states meet the requirements to perform a bulk resize action.
```

2023-05-25 20:29 UTC, Danielabom commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +To validate a set of [cloudPC](../resources/cloudpc.md) to see if they can be bulk resized in the organization using delegated permission:
```suggestion
To validate if a set of [cloudPC](../resources/cloudpc.md) can be bulk-resized in the organization using delegated permissions:
```

2023-05-25 21:27 UTC, Danielabom commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +|cloudPcIds|String collection|The Cloud PC id list for selected Cloud PC devices to be validated. Max count is 2000.|
```suggestion
|cloudPcIds|String collection|The selected Cloud PC id list to be validated. The max count is 2000.|
```

2023-05-25 23:01 UTC, Danielabom commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +|targetServicePlanId|String|The target service plan id of the resize configuration with new vCPU and storage size.|
```suggestion
|targetServicePlanId|String|The target service plan id of the resize configuration with the new vCPU and storage size.|
```

2023-05-25 23:10 UTC, Danielabom requested changes
@SleepIsImportant thank you for working on this PR. Please review my comments.

2023-06-01 23:00 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +---
@SleepIsImportant, please review my comment above.

2023-06-07 23:50 UTC, Danielabom commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +|validationResult|[cloudPcResizeValidationCode](#cloudpcresizevalidationcode-values)|Describes a list of the validation result for the Cloud PC resize action. Possible values are: `success`, `cloudPc
```suggestion
|validationResult|[cloudPcResizeValidationCode](#cloudpcresizevalidationcode-values)|Describes a list of the validation result for the Cloud PC resize action. The possible values are: `success`, `cloudPcNotFound`, `operationCnflict`, `operationNotSupported`, `targetLicenseHasAssigned`, `internalServerError`, `unknownFutureValue`.|
```

2023-06-07 23:56 UTC, Danielabom approved these changes
@SleepIsImportant, thank you for working on this PR. PR approved.

2023-06-26 17:38 UTC, Danielabom commented
@SleepIsImportant, please add the "ready to merge" label as soon as you are ready to publish.

2023-06-28 00:03 UTC, Lauragra commented on api-reference/beta/api/cloudpc-validatebulkresize.md
> +To validate if a set of [cloudPC](../resources/cloudpc.md) can be bulk-resized in the organization using delegated permissions:
I'm not sure that we need this introductory sentence because we're only providing one HTTP syntax. Generally if we provide multiple possible syntaxes in a method topic, we might introduce each. Okay to delete this sentence?

2023-06-28 00:04 UTC, Lauragra commented on api-reference/beta/resources/cloudPcResizeValidationResult.md
> +title: "cloudPcResizeValidationResult resource type"
Please delete this file. It looks like instead of renaming it, a new file with an all lowercase file name was added to the PR.

2023-06-28 02:05 UTC, RuiHou105 approved these changes

2023-06-29 00:27 UTC, merged