[CloudPC] Documentation update for new API - BulkResize
microsoftgraph/microsoft-graph-docs pull request #20200
Opened 2023-02-10 09:29 UTC by SleepIsImportant

2023-03-23 03:21 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +          - name: Bulk resize
In toc.yml, all methods except CRUD should sorted alphabetically. So please please this one before `- name: Bulk-restore remotely`

2023-03-23 03:24 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk resize](../api/cloudpc-retrypartneragentinstallation.md)|[cloudPcRemoteActionResult](../resources//cloudpcremoteactionresult.md) collection|Perform bulk resize for a set of Cloud PCs which pas
```suggestion
|[Bulk resize](../api/cloudpc-retrypartneragentinstallation.md)|[cloudPcRemoteActionResult](../resources//cloudpcremoteactionresult.md) collection|Perform bulk resize for a set of Cloud PCs which passed validateBulkResize. If some devices can't be resized, then they will be marked as resize failed, while others will proceed to be provisioned.|
```

2023-03-23 03:25 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-bulkresize.md
> +|cloudPcIds|String collection|The identifier id of a set of Cloud PC.|
```suggestion
|cloudPcIds|String collection|The Cloud PC id list for selected Cloud PC devices to be set as pending resize.|
```

2023-03-23 03:26 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-bulkresize.md
> +|targetServicePlanId|String|The identifier id of targeted resized service plan.|
```suggestion
|targetServicePlanId|String|The target service plan id of the resize configuration with new vCPU and storage size.|
```

2023-03-23 03:28 UTC, RuiHou105 requested changes
@SleepIsImportant 
1.Please create a roadmap workitem and attach the woekitem number.
2.Please resolve comments.

2023-03-31 02:24 UTC, SleepIsImportant commented
> @SleepIsImportant 1.Please create a roadmap workitem and attach the woekitem number. 2.Please resolve comments.

Where to create the roadmap work item?

2023-05-24 18:05 UTC, Danielabom commented
Contacted author to get info.

2023-05-25 17:54 UTC, Danielabom commented on api-reference/beta/api/cloudpc-bulkresize.md
> +Perform bulk resize for a set of [cloudPC](../resources/cloudpc.md) which passed BulkResizePreview (cloudPC: validateBulkResize). If some devices cannot be resized, then they will be marked as resize
```suggestion
Perform a bulk resize action to resize a group of [cloudPCs](../resources/cloudpc.md) that have successfully passed the BulkResizePreview validation (cloudPC: validateBulkResize). If there are any devices that cannot be resized, they will be labeled as "resize failed," while the remaining devices will be `provisioned` for the resize process.
```

2023-05-25 17:58 UTC, Danielabom commented on api-reference/beta/api/cloudpc-bulkresize.md
> +|cloudPcIds|String collection|The Cloud PC id list for selected Cloud PC devices to be set as pending resize.|
```suggestion
|cloudPcIds|String collection|The list of Cloud PC ids that contain the selected Cloud PC devices that will be marked as pending to be resized.|
```

2023-05-25 17:59 UTC, Danielabom commented on api-reference/beta/api/cloudpc-bulkresize.md
> +|targetServicePlanId|String|The target service plan id of the resize configuration with new vCPU and storage size.|
```suggestion
|targetServicePlanId|String|The target service plan ID refers to the configuration for resizing, including the desired number of virtual CPUs (vCPU) and storage size.|
```

2023-05-25 18:01 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk resize](../api/cloudpc-retrypartneragentinstallation.md)|[cloudPcRemoteActionResult](../resources//cloudpcremoteactionresult.md) collection|Perform bulk resize for a set of Cloud PCs which pas
```suggestion
|[Bulk resize](../api/cloudpc-retrypartneragentinstallation.md)|[cloudPcRemoteActionResult](../resources//cloudpcremoteactionresult.md) collection|erform a bulk resize action to resize a group of [cloudPCs](../resources/cloudpc.md) that have successfully passed the BulkResizePreview validation (cloudPC: validateBulkResize). If any devices cannot be resized, they will be labeled as "resize failed," while the remaining devices will be `provisioned` for the resize process.|
```

2023-05-25 18:03 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|resizePendingLicense|Indicates that the Cloud PC resize is triggered, has not been licensed with target license, pending customer action.|
```suggestion
|resizePendingLicense|Indicates that the Cloud PC resize process has been initiated but cannot be completed because the target license has not been properly licensed yet. It is currently awaiting customer action to resolve the licensing issue.|
```

2023-05-25 18:09 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|resizePendingLicense|Indicates that the Cloud PC resize is triggered, has not been licensed with target license, pending customer action.|
@SleepIsImportant, please review step 3 in this wiki [Evolvable enums](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations) and update the "status" property description if necessary.

2023-05-25 18:11 UTC, Danielabom requested changes
Hi @SleepIsImportant, please review my comments and commit my suggestions if you agree with the changes.

2023-06-01 23:05 UTC, Danielabom approved these changes
PR approved.

2023-06-26 17:52 UTC, Danielabom commented
@SleepIsImportant, please add the "ready-to-merge" label as soon as you are ready to publish.

2023-06-27 05:58 UTC, RuiHou105 approved these changes

2023-06-28 00:28 UTC, Lauragra commented on api-reference/beta/api/cloudpc-bulkresize.md
> +Perform a bulk resize action to resize a group of [cloudPCs](../resources/cloudpc.md) that have successfully passed the BulkResizePreview validation (cloudPC: validateBulkResize). If any devices cann
Please revise as:
Perform a bulk resize action to resize a group of [cloudPCs](../resources/cloudpc.md) that have successfully passed [validation](cloudpc-validatebulkresize.md). If any devices cannot be resized, the response will indicate `resize failed`. The remaining devices will be `provisioned` for the resize process.

2023-06-28 01:34 UTC, Lauragra commented on api-reference/beta/api/cloudpc-bulkresize.md
> +|cloudPcIds|String collection|The list of Cloud PC ids that contain the selected Cloud PC devices that will be marked as pending to be resized.|
Would it be accurate to revise the description as: "A list of the IDs for the Cloud PC devices that are to be resized."

2023-06-28 01:35 UTC, Lauragra commented on api-reference/beta/api/cloudpc-bulkresize.md
> +|targetServicePlanId|String|The target service plan ID refers to the configuration for resizing, including the desired number of virtual CPUs (vCPU) and storage size.|
Delete the first part of the description that repeats the name of the property and start with "The configuration...".

2023-06-28 01:35 UTC, Lauragra commented on api-reference/beta/resources/cloudpc.md
> +|[Bulk resize](../api/cloudpc-retrypartneragentinstallation.md)|[cloudPcRemoteActionResult](../resources//cloudpcremoteactionresult.md) collection|Perform a bulk resize action to resize a group of [c
This description can just be: Perform a bulk resize action to resize a group of [cloudPCs](https://github.com/microsoftgraph/microsoft-graph-docs/pull/resources/cloudpc.md) that have successfully passed [validation](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20200/cloudpc-validatebulkresize.md).

2023-06-28 01:37 UTC, Lauragra commented on api-reference/beta/resources/cloudpc.md
> +|resizePendingLicense|Indicates that the Cloud PC resize process has been initiated but cannot be completed because the target license has not been properly licensed yet. It is currently awaiting cus
Let's rephrase "target license has not been properly licensed yet". Can we say "because the target license hasn't been identified"?

2023-06-29 01:05 UTC, merged