Add PIM Alert Graph API docs to Beta
microsoftgraph/microsoft-graph-docs pull request #20204
Opened 2023-02-10 19:28 UTC by weijie-lin

2023-03-07 19:06 UTC, FaithOmbongi requested changes
Thank you @weijie-lin, @rkarim-ms for your excellent work on this PR. I've left a inline suggestions plus the following summary:
- For all suggestions, I defer to your technical expertise to ensure they're technically accurate
- We need to add information about security alerts to the Overview article. 
    - Can you schedule a session we go over the API structure? I can handle the doc update.
- In identityGovernance.md, also add security alerts for Azure AD roles to the list at the top of the article.
- In unifiedRoleManagementAlertConfiguration, please ensure to mention all its derived types.
- GLOBAL: Some suggestions to update the description metadata is because of the 160 characters limit.
- For all the 7 types that derive from unifiedRoleManagementAlertConfiguration, I've suggested changes to the property and relationship descriptions in invalidLicenseAlertConfiguration.md only, but those same suggestions apply to the other 6 derived types.
- `/identityGovernance/roleManagementAlerts/alertConfigurations` doesn't work. I got curious and tested and even though I have both the permissions and both the GA and PRA roles, I got this error message.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/14026935/223491316-11d4079b-ecba-46a3-aad4-494abffc303d.png">

- The /identityGovernance/roleManagementAlerts/alertConfigurations/{id} also doesn't work for the same reason as above. Please confirm.
- GLOBAL for READ operations: For RBAC roles, are you sure PRA, GA, and member users are the only roles? What about Security Reader, Security Operator, Security Administrator, and Global Reader...at least as per [the RBAC permissions doc](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference)?
- List alertDefinitions seems to require filters. Please verify
<img width="811" alt="image" src="https://user-images.githubusercontent.com/14026935/223502225-7e9b5681-8447-42d5-a6d7-c2b12fa8727d.png">

- GET alert definitions returns  403 even though I have both the Graph permissions and two privileged roles. Please confirm.
- Qu out of curiosity: If the GA role is assigned to a group and the group has both users and service principals so they become global admins by inheritance; Then if the alert is triggered - does the tooManyGlobalAdminsAssignedToTenantAlertIncident  object indicate the different members of the group or does it indicate the group?
- unifiedRoleManagementAlertIncident : In the description, list and link to all derived types.
- GLOBAL: For suggestions to assigneeDisplayName, assigneeId, and assigneeUserPrincipalName, the suggestions apply to other *incident-related resources as well.
- I'm getting 403 testing the List and Get alerts endpoints. Please confirm.
- GLOBAL: While you're indicating support for $filter and $expand by different properties, you're not showing in the resource docs (the property descriptions) the properties that support $filter and $expand. Please also indicate inline in the property descriptions. See the PIM for Azure AD roles or LCW docs for guidance.
- GLOBAL for LIST/GET operations: I love how you're showing usage of query parameters. However, as a best practice, we recommend that the first example is always the default URL, then additional examples can show use of query parameters.
- Update longRunningOperation.md to add a Methods table and surface the GET operation there.

2023-03-07 19:06 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +              href: api/unifiedrolemanagementalert-update.md
nit: update before refresh
```suggestion
            - name: Update
              href: api/unifiedrolemanagementalert-update.md
            - name: Refresh
              href: api/unifiedrolemanagementalert-refresh.md
```

2023-03-07 19:06 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +            - name: Update rule
```suggestion
            - name: Update
```

2023-03-07 19:06 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +        },
I don't think this is in this PR

2023-03-07 19:06 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +        },
Not in your PR. It already existed.

2023-03-07 19:06 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +          "Description": "Added the [refresh](https://learn.microsoft.com/en-us/graph/api/unifiedRoleManagementAlert?view=graph-rest-beta) method to the [unifiedRoleManagementAlert](https://learn.mic
Fix the link to the refresh file. This is a generation bug.
Same comment applies to the others as well.

2023-03-07 19:06 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +          "Description": "Added the [remediate](https://learn.microsoft.com/en-us/graph/api/unifiedRoleManagementAlertIncident?view=graph-rest-beta) method to the [unifiedRoleManagementAlertIncident]
Fix link to remediate file

2023-03-07 19:06 UTC, FaithOmbongi commented on changelog/Microsoft.PIM.AzureRBAC.json
> +      "SubArea": "Identity governance"
To map to the docs and changelog taxonomy
```suggestion
      "SubArea": "Governance"
```

2023-03-07 19:07 UTC, FaithOmbongi requested changes
Thank you @weijie-lin, @rkarim-ms for your excellent work on this PR. I've left a inline suggestions plus the following summary:
- For all suggestions, I defer to your technical expertise to ensure they're technically accurate
- We need to add information about security alerts to the Overview article. 
    - Can you schedule a session we go over the API structure? I can handle the doc update.
- In identityGovernance.md, also add security alerts for Azure AD roles to the list at the top of the article.
- In unifiedRoleManagementAlertConfiguration, please ensure to mention all its derived types.
- GLOBAL: Some suggestions to update the description metadata is because of the 160 characters limit.
- For all the 7 types that derive from unifiedRoleManagementAlertConfiguration, I've suggested changes to the property and relationship descriptions in invalidLicenseAlertConfiguration.md only, but those same suggestions apply to the other 6 derived types.
- `/identityGovernance/roleManagementAlerts/alertConfigurations` doesn't work. I got curious and tested and even though I have both the permissions and both the GA and PRA roles, I got this error message.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/14026935/223491316-11d4079b-ecba-46a3-aad4-494abffc303d.png">

- The /identityGovernance/roleManagementAlerts/alertConfigurations/{id} also doesn't work for the same reason as above. Please confirm.
- GLOBAL for READ operations: For RBAC roles, are you sure PRA, GA, and member users are the only roles? What about Security Reader, Security Operator, Security Administrator, and Global Reader...at least as per [the RBAC permissions doc](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference)?
- List alertDefinitions seems to require filters. Please verify
<img width="811" alt="image" src="https://user-images.githubusercontent.com/14026935/223502225-7e9b5681-8447-42d5-a6d7-c2b12fa8727d.png">

- GET alert definitions returns  403 even though I have both the Graph permissions and two privileged roles. Please confirm.
- Qu out of curiosity: If the GA role is assigned to a group and the group has both users and service principals so they become global admins by inheritance; Then if the alert is triggered - does the tooManyGlobalAdminsAssignedToTenantAlertIncident  object indicate the different members of the group or does it indicate the group?
- unifiedRoleManagementAlertIncident : In the description, list and link to all derived types.
- GLOBAL: For suggestions to assigneeDisplayName, assigneeId, and assigneeUserPrincipalName, the suggestions apply to other *incident-related resources as well.
- I'm getting 403 testing the List and Get alerts endpoints. Please confirm.
- GLOBAL: While you're indicating support for $filter and $expand by different properties, you're not showing in the resource docs (the property descriptions) the properties that support $filter and $expand. Please also indicate inline in the property descriptions. See the PIM for Azure AD roles or LCW docs for guidance.
- GLOBAL for LIST/GET operations: I love how you're showing usage of query parameters. However, as a best practice, we recommend that the first example is always the default URL, then additional examples can show use of query parameters.
- Update longRunningOperation.md to add a Methods table and surface the GET operation there.

2023-04-18 16:46 UTC, rkarim-ms commented on api-reference/beta/api/rolemanagementalert-list-alertconfigurations.md
> +The calling user must be a member user or have the Privileged Role Administrator Azure AD role.
Confirmed as per @weijie-lin's comment earlier on Teams. (READ operations - only PRA, GA, and non-guest users within the tenant)

2023-04-18 16:59 UTC, rkarim-ms commented on api-reference/beta/resources/unifiedrolemanagementalertconfiguration.md
> +|[Update unifiedRoleManagementAlertConfiguration](../api/unifiedrolemanagementalertconfiguration-update.md)|[unifiedRoleManagementAlertConfiguration](../resources/unifiedrolemanagementalertconfigurat
tagging @FaithOmbongi and @weijie-lin for re-review of this comment.

2023-04-18 17:04 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
> +If successful, this action returns a `200 OK` response code.
Confirmed - as per @weijie-lin's comment on Teams, "it's by design that remediate action does not require a body because all our service need to know for this action is the AlertId and IncidentId of that alert. Both information are already provided in the url path."

2023-04-18 17:04 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
> +```
Confirmed in Q above.

2023-04-19 04:06 UTC, rkarim-ms commented on api-reference/beta/resources/unifiedrolemanagementalertconfiguration.md
> +|scopeType|String|The type of scope where the alert is created. DirectoryRole is the only currently supported scope type for Azure AD Roles. New types like Application and Group may be introduced lat
Adding @weijie-lin's comments from Teams for reference: 

- The alertConfiguration api requires the scopeId where the scopeId currently is provided as the tenant id; however, I will make the change to allow customer to provide just the '/' as scopeId for tenant-wide scope.

- The configuration only has information about the config itself. It has the reference to the alertDefinition(Id) because then people will know which alert this configuration is used for. (All alert information like display name, description, etc are in the alert definition but not in the alert configuration)

2023-04-19 04:11 UTC, rkarim-ms commented on api-reference/beta/resources/redundantassignmentalertconfiguration.md
> +description: "Represents an alert configuration that is triggered if a user goes over a specified number of days without activating a role. Users that have been assigned privileged roles they do not
tagging @weijie-lin for input on this question.

2023-04-19 04:17 UTC, rkarim-ms commented on api-reference/beta/resources/redundantassignmentalertconfiguration.md
> +description: "Represents an alert configuration that is triggered if a user goes over a specified number of days without activating a role. Users that have been assigned privileged roles they do not
Adding guidance from our PIM portal docs. This alert is triggered if a user goes over a specified number of days without activating a role. It does not apply to sign-in activity (that would be the stale sign in alert configuration instead).

2023-04-19 04:18 UTC, rkarim-ms commented on api-reference/beta/resources/redundantassignmentalertconfiguration.md
> +description: "Represents an alert configuration that is triggered if a user goes over a specified number of days without activating a role. Users that have been assigned privileged roles they do not
https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-how-to-configure-security-alerts

2023-04-19 04:19 UTC, rkarim-ms commented on api-reference/beta/resources/redundantassignmentalertconfiguration.md
> +Represents an alert configuration that is triggered if a user goes over a specified number of days without activating a role. Users that have been assigned privileged roles they do not need increases
Addressed above.

2023-04-19 04:23 UTC, rkarim-ms commented on api-reference/beta/resources/toomanyglobaladminsassignedtotenantalertconfiguration.md
> +|globalAdminCountThreshold|Int32|Threshold for the number of global admin roles. Triggers an alert if the number of global admins in tenant reaches or crosses this threshold value.|
@weijie-lin for input on whether this includes eligible Global Admin assignments?

2023-04-19 04:39 UTC, rkarim-ms commented on api-reference/beta/resources/toomanyglobaladminsassignedtotenantalertconfiguration.md
> +|percentageOfGlobalAdminsOutOfRolesThreshold|Int32|Threshold of the percentage of global admins out of all the role assignments in tenant. Triggers an alert if the percentage in tenant reaches or cro
Both criteria must be met to trigger the alert. If you only meet one of these measurements, the alert doesn't appear. (src: PIM portal docs) API docs now updated to clearly indicate this as well.)

2023-04-19 04:46 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalert-update.md
> +|isActive|Boolean|False by default. True if the alert is active. Set to false to dismiss the alert. Required.|
@weijie-lin for confirmation on this discrepancy between portal and API.

2023-04-19 04:58 UTC, rkarim-ms commented on api-reference/beta/resources/invalidlicensealertconfiguration.md
> +|scopeType|String|The type of scope where the alert is created. DirectoryRole is the only currently supported scope type for Azure AD Roles. New types like Application and Group may be introduced lat
Applied globally.

2023-04-19 06:09 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalertconfiguration-update.md
> +|isEnabled|Boolean|True if the alert is enabled. Setting to false will disable scanning for the specific alert. Optional.|
Acknowledged. Also adding @weijie-lin to confirm updated list of properties is complete here.

2023-04-19 17:33 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalertconfiguration-get.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alertConfigurations/DirectoryRole_67b47f38-0f0b-4e62-a3be-859140c2061f_TooManyGlobalAdminsAssignedToTenantAlert
including @weijie-lin for confirmation.

2023-05-08 02:51 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalert-refresh.md
> +Content-Type: application/json
Confirmed with @weijie-lin that these are both body parameters. Updated docs accordingly.

2023-05-08 02:59 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalertconfiguration-get.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alertConfigurations/DirectoryRole_67b47f38-0f0b-4e62-a3be-859140c2061f_TooManyGlobalAdminsAssignedToTenantAlert
Confirmed by @weijie-lin over Teams - pasting comment here for reference :"The /identityGovernance/roleManagementAlerts/alertConfigurations call did not work even though you have both the permissions and both the GA and PRA roles because in the url, the scopeId in the filter should be with the tenant Id where your signed-in user resides. 403 is the right message because the user did not provide the correct scopeId, which means the user's trying to access a resource that not supposed to be accessed."

2023-05-08 03:24 UTC, rkarim-ms commented on api-reference/beta/api/rolemanagementalert-list-alertdefinitions.md
> +GET /identityGovernance/roleManagementAlerts/alertDefinitions
Updated with required filters.

2023-05-08 03:25 UTC, rkarim-ms commented on api-reference/beta/api/rolemanagementalert-list-alertdefinitions.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alertDefinitions
Updated.

2023-05-08 03:25 UTC, rkarim-ms commented on api-reference/beta/api/unifiedrolemanagementalertdefinition-get.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alertDefinitions/DirectoryRole_67b47f38-0f0b-4e62-a3be-859140c2061f_TooManyGlobalAdminsAssignedToTenantAlert
tagging @weijie-lin for verification.

2023-05-08 03:32 UTC, rkarim-ms commented on api-reference/beta/resources/unifiedrolemanagementalert.md
> +|scopeType|String|The type of scope where the alert is created. DirectoryRole is the only currently supported scope type for Azure AD Roles. New types like Application and Group may be introduced lat
requesting review from @weijie-lin for these questions.

2023-05-08 03:33 UTC, rkarim-ms commented on api-reference/beta/resources/nomfaonroleactivationalertincident.md
> +Represents an alert incident that is triggered if roles do not require multi-factor authentication for activation. Without multi-factor authentication, privileged roles can be activated more easily b
including @weijie-lin for guidance on whether custom roles trigger alerts here.

2023-05-08 03:49 UTC, rkarim-ms commented on api-reference/beta/resources/toomanyglobaladminsassignedtotenantalertincident.md
> +|id|String|The identifier for an alert incident. For example, it could be a role assignment id if the incident represents a role assignment Inherited from [entity](../resources/entity.md).|
Updated across all relevant files.

2023-05-08 03:53 UTC, rkarim-ms commented on api-reference/beta/resources/unifiedrolemanagementalertincident.md
> +This is an abstract type.
Applied.

2023-05-08 04:04 UTC, rkarim-ms commented on api-reference/beta/resources/redundantassignmentalertincident.md
> +Represents an alert incident that is triggered if a user goes over a specified number of days without activating a role. Users that have been assigned privileged roles they do not need increases the
Done.

2023-05-08 04:07 UTC, rkarim-ms commented on api-reference/beta/resources/rolesassignedoutsideprivilegedidentitymanagementalertincident.md
> +|roleTemplateId|String|The identifier for a directory role template.|
Applied.

2023-05-08 04:07 UTC, rkarim-ms commented on api-reference/beta/resources/sequentialactivationrenewalsalertincident.md
> +|roleTemplateId|String|The identifier for a directory role template.|
Done.

2023-05-08 04:08 UTC, rkarim-ms commented on api-reference/beta/resources/stalesigninalertincident.md
> +|roleTemplateId|String|The identifier for a directory role template.|
Done.

2023-05-08 04:12 UTC, rkarim-ms commented on api-reference/beta/resources/stalesigninalertincident.md
> +Inherits from [unifiedRoleManagementAlertIncident](../resources/unifiedrolemanagementalertincident.md).
Added.

2023-05-08 04:13 UTC, rkarim-ms commented on api-reference/beta/api/rolemanagementalert-list-alerts.md
> +GET /identityGovernance/roleManagementAlerts/alerts
Yes, updated to reflect required filters.

2023-05-08 04:14 UTC, rkarim-ms commented on api-reference/beta/api/rolemanagementalert-list-alerts.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alerts?$filter=scopeId eq '67b47f38-0f0b-4e62-a3be-859140c2061f' and scopeType eq 'DirectoryRole'&$expand=alertDefinition,
including @weijie-lin for help on this question.

2023-06-02 22:02 UTC, weijie-lin commented on api-reference/beta/api/longrunningoperation-get.md
> +    "resourceLocation": "https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alerts/DirectoryRole_67b47f38-0f0b-4e62-a3be-859140c2061f_StaleSignInAlert",
The "resourceLocation" header will only have the resource url if the scan succeeded.

Here is the example response for "running" status:
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/roleManagementAlerts/operations/$entity",
    "id": "refresh:DirectoryRole_19356be4-7e93-4ed6-a7c6-0ae28454d125_StaleSignInAlert",
    "createdDateTime": "2023-06-02T21:56:39.9688468Z",
    "lastActionDateTime": "2023-06-02T21:59:34.8169926Z",
    "resourceLocation": "",
    "status": "running",
    "statusDetail": ""
}

Here is the response for "succeeded" status:
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/roleManagementAlerts/operations/$entity",
    "id": "refresh:DirectoryRole_19356be4-7e93-4ed6-a7c6-0ae28454d125_StaleSignInAlert",
    "createdDateTime": "2023-06-02T21:56:39.9688468Z",
    "lastActionDateTime": "2023-06-02T21:59:37.632065Z",
    "resourceLocation": "https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alerts/DirectoryRole_19356be4-7e93-4ed6-a7c6-0ae28454d125_StaleSignInAlert",
    "status": "succeeded",
    "statusDetail": ""
}

2023-06-02 22:54 UTC, weijie-lin commented on api-reference/beta/api/rolemanagementalert-list-alertconfigurations.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alertConfigurations?$filter=scopeId eq '67b47f38-0f0b-4e62-a3be-859140c2061f' and scopeType eq 'DirectoryRole'&$expand=ale
With current implementation, passing tenant id will not work anymore. User will need to pass scopeId eq '/'. Need to make change in all related files accordingly.

2023-06-02 23:00 UTC, weijie-lin commented on api-reference/beta/api/rolemanagementalert-list-alerts.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alerts?$filter=scopeId eq '67b47f38-0f0b-4e62-a3be-859140c2061f' and scopeType eq 'DirectoryRole'&$expand=alertDefinition,
@FaithOmbongi , @rkarim-ms , 403 can be because your app did not have the permission. If your app had the permission, please try it again with 

GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alerts?$filter=scopeId eq '/' and scopeType eq 'DirectoryRole'&$expand=alertDefinition,alertConfiguration,alertIncidents

because we made the implementation change to support '/' as scopeId for tenant width.

2023-06-02 23:06 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalert-get.md
> +GET /identityGovernance/roleManagementAlerts/alerts?$filter=scopeId eq 'scopeId' and scopeType eq 'scopeType' and alertDefinitionId eq 'alertDefinitionId'
@FaithOmbongi , @rkarim-ms 
This is a GET call instead of List, so I think it should be get by id. 

`GET /identityGovernance/roleManagementAlerts/alerts/{unifiedRoleManagementAlertId}`

You can take the GET Policy page as a reference: https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicy-get?view=graph-rest-1.0&tabs=http

2023-06-02 23:09 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalert-get.md
> +GET https://graph.microsoft.com/betaidentityGovernance/roleManagementAlerts/alerts?$filter=scopeId eq '67b47f38-0f0b-4e62-a3be-859140c2061f' and scopeType eq 'DirectoryRole' and alertDefinitionId eq
It's get by id, so example should be something like below: 
`GET https://graph.microsoft.com/betaidentityGovernance/roleManagementAlerts/alerts/DirectoryRole_67b47f38-0f0b-4e62-a3be-859140c2061f_TooManyGlobalAdminsAssignedToTenantAlert?$expand=alertDefinition,alertConfiguration,alertIncidents`

2023-06-02 23:17 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalert-refresh.md
> +|scopeId|String|The ID of the scope where the alert applies. For example, directory ID or application ID.|
Currently we only support '/' as scopeId.

2023-06-02 23:41 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalertconfiguration-update.md
> +|isEnabled|Boolean|True if the alert is enabled. Setting to false will disable scanning for the specific alert. Optional.|
@FaithOmbongi , @rkarim-ms , I agreed with Faith on making this page similar to what we have for [Update unifiedRoleManagementPolicyRule](https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicyrule-update?view=graph-rest-1.0&tabs=http#request-body), where at the top it has links to all derived types. In the request body for alert configuration. We only need to show the updatable properties.

alertDefinitionId, scopeType and scopeId are not updatable.

All updatable properties are: isEnabled (from the base type), duration (redundantAssignmentAlertConfiguration, staleSignInAlertConfiguration), timeIntervalBetweenActivations (sequentialActivationRenewalsAlertConfiguration), sequentialActivationCounterThreshold (sequentialActivationRenewalsAlertConfiguration), globalAdminCountThreshold (tooManyGlobalAdminsAssignedToTenantAlertConfiguration), percentageOfGlobalAdminsOutOfRolesThreshold (tooManyGlobalAdminsAssignedToTenantAlertConfiguration).

2023-06-02 23:42 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalertdefinition-get.md
> +GET https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alertDefinitions/DirectoryRole_67b47f38-0f0b-4e62-a3be-859140c2061f_TooManyGlobalAdminsAssignedToTenantAlert
@FaithOmbongi Please use list alert definitions endpoint to get all the alert definitions, then use one of the id from the response to call this endpoint.

2023-06-03 00:01 UTC, weijie-lin commented on api-reference/beta/resources/unifiedrolemanagementalertconfiguration.md
> +|[Update unifiedRoleManagementAlertConfiguration](../api/unifiedrolemanagementalertconfiguration-update.md)|[unifiedRoleManagementAlertConfiguration](../resources/unifiedrolemanagementalertconfigurat
@FaithOmbongi , @rkarim-ms, If we don't need links from resource page back to the api page, I think we can follow what the
 [unifiedrolemanagementpolicyrule](https://learn.microsoft.com/en-us/graph/api/resources/unifiedrolemanagementpolicyrule?view=graph-rest-beta) page for this and have it None under Methods.

2023-06-03 00:09 UTC, weijie-lin commented on changelog/Microsoft.PIM.AzureRBAC.json
> +    {
@FaithOmbongi , @rkarim-ms , we may need to also include the new permissions in this change log. Can Faith please confirm?

The two new permissions to be added in change log: RoleManagementAlert.Read.Directory and RoleManagementAlert.ReadWrite.Directory

2023-06-12 09:09 UTC, weijie-lin commented on changelog/Microsoft.PIM.AzureRBAC.json
> +    {
@FaithOmbongi , @rkarim-ms . I added the two permissions in the change log as well.

2023-06-12 09:11 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalert-refresh.md
> +|scopeId|String|The ID of the scope where the alert applies. For example, directory ID or application ID.|
@FaithOmbongi , @rkarim-ms , I made the change including the examples on all docs to have '/' as scopeId

2023-06-12 09:12 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalert-get.md
> +GET https://graph.microsoft.com/betaidentityGovernance/roleManagementAlerts/alerts?$filter=scopeId eq '67b47f38-0f0b-4e62-a3be-859140c2061f' and scopeType eq 'DirectoryRole' and alertDefinitionId eq
Made the change

2023-06-12 09:12 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalert-get.md
> +GET /identityGovernance/roleManagementAlerts/alerts?$filter=scopeId eq 'scopeId' and scopeType eq 'scopeType' and alertDefinitionId eq 'alertDefinitionId'
I made the change.

2023-06-12 09:14 UTC, weijie-lin commented on api-reference/beta/api/longrunningoperation-get.md
> +    "resourceLocation": "https://graph.microsoft.com/beta/identityGovernance/roleManagementAlerts/alerts/DirectoryRole_67b47f38-0f0b-4e62-a3be-859140c2061f_StaleSignInAlert",
I made the change to improve the GET long running operation page, also taking into account that longrunningoperation is a shared entity with other teams.

2023-06-20 06:15 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
> +Remediate or mitigate an incident of an alert. The alert incident can be one of the following types that are derived from the [unifiedRoleManagementAlertIncident](../resources/unifiedrolemanagemental
@FaithOmbongi , this correspond to the "Fix" menus and its effect is on a specific alert incident; therefore, we do apply the mitigation steps programmatically when the user call this API.

The "Dismiss" is documented in the **unifiedrolemanagementalert-update.md** file, and its effect is on the whole alert. The user call Patch on unifiedrolemanagementalert to update the "isActive" property of the unifiedrolemanagementalert to "false" to dismiss the alert. Once the alert is dismissed, the "pausing future notifications" of the specific alert will last until the next alert refresh. Because our service has a background job to automatically refresh the alert in a day if the user hasn't refreshed the alert through the API in the past 1 day, the maximum time duration of "pausing future notifications" is one day.

2023-06-20 07:01 UTC, weijie-lin commented on api-reference/beta/resources/unifiedrolemanagementalertdefinition.md
> +|[List unifiedRoleManagementAlertDefinitions](../api/rolemanagementalert-list-alertdefinitions.md)|[unifiedRoleManagementAlertDefinition](../resources/unifiedrolemanagementalertdefinition.md) collect
@FaithOmbongi This is identical with what we have for other pages like https://learn.microsoft.com/en-us/graph/api/resources/unifiedrolemanagementpolicy?view=graph-rest-beta

If we change it to alertDefinitions, we will have to do it for other entities and other methods to math the url path name as well. I suggest keep it as is here.

2023-06-20 07:45 UTC, weijie-lin commented on api-reference/beta/resources/invalidlicensealertconfiguration.md
> +|scopeId|String|The identifier of the scope where the alert is related. For example, directory ID or application ID. Inherited from [unifiedRoleManagementAlertConfiguration](../resources/unifiedrolem
@FaithOmbongi , I made the corresponding change.

2023-06-20 07:45 UTC, weijie-lin commented on api-reference/beta/resources/unifiedrolemanagementalertincident.md
> +None.
@FaithOmbongi , I made the corresponding change.

2023-06-20 08:25 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
> +Remediate or mitigate an incident of an alert. The alert incident can be one of the following types that are derived from the [unifiedRoleManagementAlertIncident](../resources/unifiedrolemanagemental
@weijie-lin - I've updated the suggestion based on your clear description. Please review.

2023-06-21 01:13 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
> +Remediate or mitigate an incident of an alert. The alert incident can be one of the following types that are derived from the [unifiedRoleManagementAlertIncident](../resources/unifiedrolemanagemental
@FaithOmbongi We will automatically apply the recommended **mitigationSteps** only for the alert whose expanded alert definition has isRemediatable property set to true.

2023-06-21 07:48 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
> +Remediate or mitigate an incident of an alert. The alert incident can be one of the following types that are derived from the [unifiedRoleManagementAlertIncident](../resources/unifiedrolemanagemental
This is a good limitation to call out. I've updated the suggestion.

2023-06-21 07:50 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
> +If successful, this action returns a `200 OK` response code.
@weijie-lin 
```suggestion
If successful, this action returns a `200 OK` response code. Calling this API for an incident that has an alert definition with **isRemediatable** set to `false` returns in a `400 Bad Request` error response.
```

2023-06-21 07:52 UTC, FaithOmbongi approved these changes
Hi @weijie-lin - I've added two suggestions related to your comments on remediate action. Please look at those.

Otherwise, everything else looks good and I've approved with suggestions.

2023-06-22 02:54 UTC, merged