Adds on-premises directory synchronization documentation for MSGraph v1.0
microsoftgraph/microsoft-graph-docs pull request #20213
Opened 2023-02-13 00:35 UTC by Mwongela

2023-02-15 15:21 UTC, ngash commented on api-reference/v1.0/resources/onpremisesaccidentaldeletionprevention.md
> +Contains the accidental deletion prevention configuration for a tenant. This configuration is geared at administrators who accidentally make an on-premises Active Directory change which results in de
nit: 
```suggestion
Contains the accidental deletion prevention configuration for a tenant. This configuration is geared at administrators who accidentally make an on-premises Active Directory change which results in deleting a large number of objects on Azure Active Directory.
```

2023-02-16 08:53 UTC, FaithOmbongi requested changes
Thank you @Mwongela for your work on this PR. A few review feedback:

1. GLOBAL: Delete all snippets and related snippet lines that you copied from beta. The snippets are added automatically the first Tuesday after your docs go live.
2. RBAC roles: Is Global Admin the only role that can work with these APIs? Can we document lesser-privileged roles?

2023-02-16 08:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/onpremisesaccidentaldeletionprevention.md
> +| synchronizationPreventionType | onPremisesDirectorySynchronizationDeletionPreventionType | The status of the accidental deletion prevention feature. The possible values are: `disabled`, `enabledFor
Please add the sentinel unknownFutureValue as well.
Add to the beta doc as well.
```suggestion
| synchronizationPreventionType | onPremisesDirectorySynchronizationDeletionPreventionType | The status of the accidental deletion prevention feature. The possible values are: `disabled`, `enabledForCount`, `enabledForPercentage`, `unknownFutureValue`.               |
```

2023-02-16 08:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/onpremisesdirectorysynchronization-get.md
> +For delegated scenarios, the user needs to be assigned the *Global administrator* [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles).
Q: Is Global Admin still the only role that can work with these APIs? If not, can we document lesser-privileged roles?
```suggestion
For delegated scenarios, the user needs to be assigned the *Global Administrator* [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles).
```

2023-02-16 08:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/onpremisesdirectorysynchronization-get.md
> +# [HTTP](#tab/http)
GLOBAL: This line will be added by the snippets generator. Please delete.
```suggestion
```

2023-02-16 08:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/onpremisesdirectorysynchronization-get.md
> +---
GLOBAL: Same thing - the snippets lines will be added by the generator. Please delete these lines.
```suggestion
```

2023-02-16 08:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/onpremisesdirectorysynchronization-update.md
> +For delegated scenarios, the user needs to be assigned the *Global administrator* [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles).
Same comment about RBAC roles

2023-02-16 08:53 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ApiChange": "Resource",
Stub bug: Please apply the suggested change.
```suggestion
          "ApiChange": "Relationship",
```

2023-02-16 14:28 UTC, Mwongela commented on api-reference/v1.0/api/onpremisesdirectorysynchronization-get.md
> +For delegated scenarios, the user needs to be assigned the *Global administrator* [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles).
Yes. We enabled two roles for these APIs: Global admin and directory account synchronizers role. Since the directory account synchronizers role is only used by AD Connect, we documented the global administrator only

2023-02-16 14:31 UTC, Mwongela commented on changelog/Microsoft.DirectoryServices.json
> +          "ApiChange": "Resource",
Updated.

2023-02-16 14:31 UTC, Mwongela commented on api-reference/v1.0/api/onpremisesdirectorysynchronization-get.md
> +---
Removed.

2023-02-16 14:56 UTC, FaithOmbongi approved these changes

2023-02-17 13:25 UTC, ngash approved these changes

2023-02-28 04:35 UTC, merged