Update TeamsFx provider doc for v3.0.0
microsoftgraph/microsoft-graph-docs pull request #20247
Opened 2023-02-15 01:45 UTC by SLdragon

2023-02-15 19:42 UTC, gavinbarron requested changes

2023-02-15 19:42 UTC, gavinbarron commented on concepts/toolkit/providers/teamsfx.md
> +    ->
Is this arrow here intentional?

2023-02-16 01:40 UTC, SLdragon commented on concepts/toolkit/providers/teamsfx.md
> +    ->
Yes, it means that code should be updated and use new API:
![image](https://user-images.githubusercontent.com/5545529/219243102-693ef8a4-a41c-4736-94f1-dbfcf99a5645.png)

2023-02-21 16:07 UTC, gavinbarron approved these changes

2023-02-21 16:08 UTC, merged