Add new synchronization permissions
microsoftgraph/microsoft-graph-docs pull request #20242
Opened 2023-02-14 17:07 UTC by ArvindHarinder1

2023-02-15 17:37 UTC, FaithOmbongi requested changes
Hi @ArvindHarinder1 -

In the spirit of encouraging least privilege, we're avoiding documenting _Directory.Read.All_ and _Directory.ReadWrite.All_ if an API doesn't **need** either. If _Synchronization.Read.All_ and _Synchronization.ReadWrite.All_ are enough for the synchronization operations, please remove the Directory.* permissions from the permissions tables. Let me know if we need to document either.

Let one suggestion for the changelog.

2023-02-15 17:37 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the `Synchronization.Read.All` application and permission to read synchronization settings.",
Suggestion
```suggestion
          "Description": "Added the `Synchronization.ReadWrite.All` application and delegated permissions to configure [synchronization settings](https://learn.microsoft.com/en-us/graph/api/resources/synchronization-overview?view=graph-rest-beta).",
          "Target": "synchronization"
        },
        {
          "Id": "00c006a9-0eaf-423f-9ed1-ge86808382ab",
          "ApiChange": "Permission",
          "ChangedApiName": "Synchronization.Read.All",
          "ChangeType": "Addition",
          "Description": "Added the `Synchronization.Read.All` application and delegated permissions to read [synchronization settings](https://learn.microsoft.com/en-us/graph/api/resources/synchronization-overview?view=graph-rest-beta).",
```

2023-02-17 19:24 UTC, ArvindHarinder1 commented
> Hi @ArvindHarinder1 -
> 
> * In the spirit of encouraging least privilege, we're avoiding documenting _Directory.Read.All_ and _Directory.ReadWrite.All_ if an API doesn't **need** either. If _Synchronization.Read.All_ and _Synchronization.ReadWrite.All_ are enough for the synchronization operations, please remove the Directory.* permissions from the permissions tables. Let me know if we need to document either.
> * Also, document the new permissions in the [permissions reference](https://learn.microsoft.com/en-us/graph/permissions-reference).
> * Left one suggestion for the changelog.

@FaithOmbongi  thanks for the feedback. I've gone ahead and addressed the feedback.

2023-02-28 14:54 UTC, FaithOmbongi commented
Selected the re-request review icon.

2023-02-28 17:20 UTC, FaithOmbongi approved these changes
Thank you @ArvindHarinder1 for your work on this PR. Approved.

2023-03-01 04:24 UTC, merged