Update authenticationmethodspolicy-get.md
microsoftgraph/microsoft-graph-docs pull request #20260
Opened 2023-02-16 01:00 UTC by msft-poulomi

2023-02-22 17:53 UTC, chocomochiko commented on api-reference/beta/api/authenticationmethodspolicy-get.md
> +                }
Nit: remove extra space

2023-02-22 17:54 UTC, chocomochiko commented on api-reference/beta/resources/systemcredentialpreferences.md
> +|includeTarget|[includeTarget](../resources/excludetarget.md) collection|A single entity that is included in this feature.|
Should this be "includetarget.md"?

2023-02-22 17:57 UTC, chocomochiko commented on api-reference/beta/resources/systemcredentialpreferences.md
> +|excludeTarget|[excludeTarget](../resources/excludetarget.md) collection|A single entity that is excluded from this feature.|
On the API level, both include/exclude targets are a list of groups/roles/AUs, not a single entity. This is also reflected on the current PM spec: https://microsoftgraph.visualstudio.com/_git/onboarding?path=/reviews/3027-auth-method-policy/api.md&version=GBmaster&_a=preview&anchor=systemcredentialpreferences

2023-02-22 18:05 UTC, chocomochiko commented on api-reference/beta/resources/systemcredentialpreferences.md
> +None.
Question: should Include/Exclude Targets be in relationships as well?

2023-02-25 00:48 UTC, msft-poulomi commented
#hold-off

2023-03-08 05:56 UTC, JarbasHorst commented on api-reference/beta/api/authenticationmethodspolicy-update.md
> +    "@odata.type": "microsoft.graph.systemCredentialPreferences"
For clarity, please replace "@odata.type": "microsoft.graph.systemCredentialPreferences" with a real-looking value that users might get in the response object (like in api-reference/beta/api/authenticationmethodspolicy-get.md). Examples with real-looking values in the request URL, requests and response bodies help customers understand the API better. That's also the consistency bar for Microsoft Graph API docs.

2023-03-08 05:56 UTC, JarbasHorst commented on api-reference/beta/resources/authenticationmethodspolicy.md
> +  "systemCredentialPreferences": {
Please, update the Properties table to contain the **systemCredentialPreferences** property.

2023-03-08 05:56 UTC, JarbasHorst commented on api-reference/beta/resources/systemcredentialpreferences.md
> +**TODO: Add Description**
Please, add the missing description and update line 3 to contain the correct description for this resource topic.

2023-03-08 06:04 UTC, JarbasHorst commented on api-reference/beta/resources/systemcredentialpreferences.md
> +|includeTarget|[includeTarget](../resources/includetarget.md) collection|Users and groups excluded from the preferred authentication method experience of the system.|
I can't find a resource type called "includeTarget" \[includeTarget\](../resources/includetarget.md) in the Microsoft Graph docs. Is this a new resource topic that you will introduce with this PR?

2023-03-09 05:15 UTC, JarbasHorst commented
Hi @msft-poulomi, I reviewed your PR and left some comments. Please, take a look when you will have time.

2023-03-12 07:32 UTC, msft-poulomi commented on api-reference/beta/api/authenticationmethodspolicy-update.md
> +    "@odata.type": "microsoft.graph.systemCredentialPreferences"
Should the real-looking value be  "https://graph.microsoft.com/beta/$metadata#authenticationMethodsPolicy"?

2023-03-13 05:42 UTC, Jarbas-MSFT commented on api-reference/beta/api/authenticationmethodspolicy-update.md
> +    "@odata.type": "microsoft.graph.systemCredentialPreferences"
Hi @msft-poulomi, the real-looking value should be similar to what this API would return in a call.

2023-03-13 21:37 UTC, msft-poulomi commented on api-reference/beta/resources/authenticationmethodspolicy.md
> +  "systemCredentialPreferences": {
Added

2023-03-13 21:38 UTC, msft-poulomi commented on api-reference/beta/resources/systemcredentialpreferences.md
> +**TODO: Add Description**
Added description

2023-03-13 21:39 UTC, msft-poulomi commented on api-reference/beta/resources/systemcredentialpreferences.md
> +|includeTarget|[includeTarget](../resources/includetarget.md) collection|Users and groups excluded from the preferred authentication method experience of the system.|
Updated now

2023-03-14 07:54 UTC, JarbasHorst commented on api-reference/beta/resources/authentication.md
> +| systemCredentialPreferences               | [systemCredentialPreferences](../resources/systemcredentialpreferences.md)                                                                  | Prompt user
According to the api.md file, systemCredentialPreferences isn't a relationship of the authentication resource. Is the api.md for PR 20260 correct? If yes, please remove this entry from this resource topic.

2023-03-15 05:21 UTC, msft-poulomi commented on api-reference/beta/resources/authentication.md
> +| systemCredentialPreferences               | [systemCredentialPreferences](../resources/systemcredentialpreferences.md)                                                                  | Prompt user
Removed.

2023-03-15 05:24 UTC, msft-poulomi commented on api-reference/beta/api/authenticationmethodspolicy-update.md
> +|systemCredentialPreferences|[systemCredentialPreferences](../resources/systemcredentialpreferences.md)|Prompt users with the most preferred authentication method that they are registered with.
Both are correct. But I have changed it to make it consistent.

2023-03-16 05:21 UTC, JarbasHorst commented on api-reference/beta/api/authentication-get.md
> +---
Can you please share with me via Teams the api.md file that contains the addition of a new GET operation for the authentication resource?

2023-03-16 05:21 UTC, JarbasHorst commented on api-reference/beta/api/authentication-get.md
> +|Delegated (work or school account)|**TODO: Provide applicable permissions.**|
GLOBAL: Please, replace the **TODO:** with proper values.

2023-03-16 05:21 UTC, JarbasHorst commented on api-reference/beta/api/authentication-get.md
> +      "@odata.type": "microsoft.graph.signInPreferences"
Please, add here a real-looking value for the signInPreferences property that customers might get when requesting this API.

2023-03-16 05:21 UTC, JarbasHorst commented on api-reference/beta/api/authenticationmethodspolicy-update.md
> +    "id": "systemCredentialPreferences",
Does systemCredentialPreferences really have an ID? I don't see this in the CSDL or api.md file.

2023-03-16 05:21 UTC, JarbasHorst commented on api-reference/beta/resources/systemcredentialpreferences.md
> +|includeTargets|[includeTarget](../resources/includetarget.md) collection|Users and groups included in the preferred authentication method experience of the system.|
According to the api.md and CSDL files the includeTargets property is of type "includeTarget"; however, this resource topic hasn't been released in our Microsoft Graph docs yet. It includeTarget the correct type for this property?

2023-03-16 05:23 UTC, JarbasHorst commented
Hi @msft-poulomi, thanks for addressing my previous comments. I left additional ones. Please, take a look when you will have time.

2023-03-17 05:51 UTC, msft-poulomi commented on api-reference/beta/resources/signinpreferences.md
> +title: "signInPreferences resource type"
This file will be updated by Julia as the feature signInPreferences is owned by her

2023-03-17 05:58 UTC, JarbasHorst commented on api-reference/beta/resources/signinpreferences.md
> +title: "signInPreferences resource type"
Thank for this information. Just to clarify, Julia should update this file before we merge this PR. Can you please follow up with her on this?

2023-03-20 17:00 UTC, jpettere commented on api-reference/beta/resources/signinpreferences.md
> +title: "signInPreferences resource type"
@msft-poulomi I don't own signInPreferences. Please document signInPreferences, since it has a system preferred property: "isSystemPreferredAuthenticationMethodEnabled". I will later add another property to signInPreferences but you should document yours first since you're in public preview.

2023-03-21 05:54 UTC, JarbasHorst commented on api-reference/beta/resources/signinpreferences.md
> +title: "signInPreferences resource type"
Thanks for the clarification, @jpettere. In this case @msft-poulomi, please replace the **TODO:** with proper values. For an example, see api-reference/beta/resources/systemcredentialpreferences.md.

2023-03-23 07:21 UTC, JarbasHorst commented on api-reference/beta/resources/authentication.md
> +|signInPreferences|[signInPreferences](../resources/signinpreferences.md)||
Please, add a description to this property.

2023-03-23 07:21 UTC, JarbasHorst commented on api-reference/beta/api/authentication-get.md
> +---
Can you please share with me via Teams the api.md file that contains the addition of a new GET operation for the authentication resource?

2023-03-23 07:21 UTC, JarbasHorst commented on api-reference/beta/api/authentication-get.md
> +      "@odata.type": "microsoft.graph.signInPreferences"
Please, add here a real-looking value for the signInPreferences property that customers might get when requesting this API. The signInPreferences contains the property **isSystemPreferredAuthenticationMethodEnabled**, so a response object that contains the signInPreferences property should also return either true or false for the isSystemPreferredAuthenticationMethodEnabled property.

2023-03-23 07:21 UTC, JarbasHorst commented on api-reference/beta/resources/systemcredentialpreferences.md
> +|includeTargets|[includeTarget](../resources/includetarget.md) collection|Users and groups included in the preferred authentication method experience of the system.|
@msft-poulomi the type for includeTargets is wrong or something is missing!!! According to the api.md and CSDL files the includeTargets property is of type "includeTarget"; however, this resource topic hasn't been released in our Microsoft Graph docs yet. It includeTarget the correct type for this property?

We can't release the docs with a wrong type that apparently doesn't exist. This wrong type is also the reason why API Doctor is not validating correctly!

2023-03-23 07:22 UTC, JarbasHorst commented
Hi @msft-poulomi, thanks for addressing some of my previous comments. I left additional ones. Please, take a look when you will have time.

2023-03-29 01:47 UTC, Lauragra approved these changes

2023-04-05 08:32 UTC, FaithOmbongi requested changes
Hi @msft-poulomi - I've left markers where to delete the references to authentication-get.md because the file no longer exists. Resolving the issues will resolve the validation error as well.

2023-04-05 08:32 UTC, FaithOmbongi commented on api-reference/beta/resources/authentication.md
> +|:------ |:----------- |:----------- |
```suggestion
None.
```

2023-04-05 08:32 UTC, FaithOmbongi commented on api-reference/beta/resources/user.md
>  | **Calendar** |||
Delete authentication-get.md; This will resolve the API doctor error.
```suggestion
| [Remove appRoleAssignment](../api/user-delete-approleassignments.md) | None | Remove an app role assignment from a user. |
| **Calendar** |||
```

2023-04-05 08:32 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
>          - name: Get delta
Delete authentication-get.md to resolve the API doctor error
```suggestion
          href: api/user-changepassword.md
        - name: Get delta
```

2023-04-06 07:11 UTC, FaithOmbongi approved these changes
Hi @msft-poulomi - LGTM!

2023-04-12 01:54 UTC, merged