app and creds last used dtaedocs
microsoftgraph/microsoft-graph-docs pull request #20289
Opened 2023-02-17 18:05 UTC by madansr7

2023-04-20 16:18 UTC, FaithOmbongi commented
Hi @madansr7 - I know this PR isn't yet ready for content review, but a heads up - please _always_ use the autogenerated doc stubs for any new API reference documentation.

2023-04-21 17:36 UTC, madansr7 commented
@FaithOmbongi , the doc stub generator tool does not genreate docs for apis in private preview (with hidden properties). So, i could not go back and find anything. I've tried to run Graph studio locally but that doesn't work either. 
Barring the warnings from the recent build, I think i am ready for a review.

2023-05-08 22:12 UTC, madansr7 commented
@FaithOmbongi , the API doctor errors here aren't related to my PR. Not sure what's going on.

2023-05-09 08:04 UTC, FaithOmbongi commented
Hi @Jarbas-MSFT - This is now also ready for review.

2023-05-11 17:16 UTC, madansr7 commented
@Jarbas-MSFT any comments or feedback here?

2023-05-16 16:36 UTC, madansr7 commented on api-reference/beta/resources/appCredentialSignInActivity.md
> +| [List appCredentialSignInActivity](../api/appcredentialsigninactivity-list.md) | appCredentialSignInActivity | Retrieve a list of appCredentialSignInActivity objects.                    |
I believe this is how the doc stub added it. I took everything from whatever was in the stub generator.

2023-05-16 16:44 UTC, madansr7 commented on api-reference/beta/resources/appCredentialSignInActivity.md
> +| [List appCredentialSignInActivity](../api/appcredentialsigninactivity-list.md) | appCredentialSignInActivity | Retrieve a list of appCredentialSignInActivity objects.                    |
updated

2023-05-16 16:46 UTC, madansr7 commented on api-reference/beta/resources/servicePrincipalSignInActivity.md
> +| Property                                        | Type                                             | Description
updated.

2023-05-16 18:37 UTC, madansr7 commented on api-reference/beta/resources/appCredentialSignInActivity.md
> +  "@odata.type": "#microsoft.graph.appCredentialSignInActivity",
Updated.

2023-05-16 18:39 UTC, madansr7 commented on api-reference/beta/resources/appCredentialSignInActivity.md
> +| [List appCredentialSignInActivity](../api/appcredentialsigninactivity-list.md) | appCredentialSignInActivity | Retrieve a list of appCredentialSignInActivity objects.                    |
updated.

2023-05-16 18:40 UTC, madansr7 commented on api-reference/beta/resources/appCredentialSignInActivity.md
> +---
updated.

2023-05-16 18:42 UTC, madansr7 commented on api-reference/beta/api/appcredentialsigninactivity-get.md
> +GET https://graph.microsoft.com/beta/reports/appCredentialSignInActivities/{appCredentialSignInActivityId}
updated.

2023-05-16 18:59 UTC, madansr7 commented on api-reference/beta/resources/reportroot.md
> +  "id": "String (identifier)"
This is not part of my change. I don't believe report root has an id of its own but this change probably came as part of docstub.

2023-05-16 19:00 UTC, madansr7 commented on api-reference/beta/resources/reportroot.md
> +  "id": "String (identifier)"
I removed it because it is not in published docs either.

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/appcredentialsigninactivity-get.md
> +
HTML comment block for this response example is missing here. Please include it.

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/appcredentialsigninactivity-get.md
> +
HTML comment block for this request example is missing here. Please include it.

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/appcredentialsigninactivity-get.md
> +
HTML comment block for this response example is missing here. Please include it.

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/appcredentialsigninactivity-list.md
> +
HTML comment block for this response example is missing here. Please include it.

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/serviceprincipalsigninactivity-get.md
> +  "@odata.type": "microsoft.graph.signIn"
Odata.type as signIn? Should we use servicePrincipalSignInActivity instead?

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/serviceprincipalsigninactivity-get.md
> +  "@odata.type": "microsoft.graph.signIn"
Odata.type as signIn? Should we use servicePrincipalSignInActivity instead?

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/serviceprincipalsigninactivity-list.md
> +
HTML comment block for this request example is missing here. Please include it.

2023-05-17 07:03 UTC, Jarbas-MSFT commented on api-reference/beta/api/serviceprincipalsigninactivity-list.md
> +
HTML comment block for this response example is missing here. Please include it.

2023-05-17 07:05 UTC, Jarbas-MSFT commented
Hello @madansr7, I reviewed your PR and left some comments. Please, take a look when you will have time.

2023-05-17 20:43 UTC, madansr7 commented on api-reference/beta/api/appcredentialsigninactivity-get.md
> +
Sorry, why do we need HTML blocks? I have the http block. Isn't that what we need?

2023-05-18 11:38 UTC, JarbasHorst commented on api-reference/beta/api/appcredentialsigninactivity-get.md
> +
The API Doctor relies on the HTML comment blocks to validate the examples (request and response). This automatism via the API Doctor helps us, authors and content reviewers, to ensure a good docs quality and experience for our customers. Please, address these comments, so we can move forward with the content review process and publishing. Thanks :)

2023-05-18 21:12 UTC, madansr7 commented on api-reference/beta/api/serviceprincipalsigninactivity-get.md
> +  "@odata.type": "microsoft.graph.signIn"
updated.

2023-05-22 04:27 UTC, Jarbas-MSFT commented
Hi @Lauragra, hi @FaithOmbongi, this PR is ready for final review.

2023-05-22 15:52 UTC, madansr7 commented
@Jarbas-MSFT can you please mark it approve? 
Can i change the label to 'ready to merge'?

2023-05-22 18:33 UTC, FaithOmbongi requested changes
Hi @madansr7,

- I've left a few comments on issues to look into.
- The files for LIST operations aren't appropriately named as per the file naming guidance. They should be:
   - reportroot-list-appcredentialsigninactivities.md
   - reportroot-list-serviceprincipalsigninactivities.md

   Please fix these and the related links.

- I also notice that though the schema was merged two weeks ago, it isn't live yet nor is it in staging. Could there be a problem with the deployment?

I stumbled on this issue that looks like a bug - the properties return dates instead of IDs, please investigate it.

<img width="425" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/30e6cb63-3ad5-445d-9ebe-8bd063cef718">

2023-05-22 18:33 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalsigninactivity-get.md
> +This method supports the `$top`, `$filter`, and `$orderBy` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Same comment as the other GET
```suggestion
This method does not support OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2023-05-22 18:33 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalsigninactivity-list.md
The proper file name as per the file naming guidance and that would have been autogenerated as a doc stub should be _reportroot-list-serviceprincipalsigninactivities.md_

2023-05-22 18:33 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalsigninactivity-list.md
> +The following example shows how to get a **servicePrincipalSignInActivity** object filtered by **applicationId**.
```suggestion
### Example 2: Get a servicePrincipalSignInActivity filtered by appId

The following example shows how to get a **servicePrincipalSignInActivity** object filtered by **appId**.
```

2023-05-22 18:44 UTC, madansr7 commented on api-reference/beta/resources/appcredentialsigninactivity.md
> +| appObjectId              | String                                           | The ID of the credential application instance.                                                        |
No, app object id is also available in the tenant where the app is provisioned. The provisioned tenant gets its own app object id.

2023-05-22 20:48 UTC, madansr7 commented on api-reference/beta/api/serviceprincipalsigninactivity-list.md
updated.

2023-05-22 20:48 UTC, madansr7 commented on api-reference/beta/api/appcredentialsigninactivity-list.md
updated.

2023-05-22 20:56 UTC, madansr7 commented
@FaithOmbongi can you tell me where you found the appid being returned as a date. 
I just did a test in graph explorer and i see appid as GUID.

2023-05-23 08:11 UTC, FaithOmbongi commented
> @FaithOmbongi can you tell me where you found the appid being returned as a date. I just did a test in graph explorer and i see appid as GUID.

Hi @madansr7 - Though Graph Explorer. I got it again this morning.

<img width="803" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/c37c4bc5-c430-4d1b-ba33-10bf4911ff3d">

To debug:

"client-request-id": "47866b2d-fb98-b472-77b5-b44650537d48"
"request-id": "6d05a57f-e585-45d7-8bba-52498534b6e8"

2023-05-23 08:15 UTC, FaithOmbongi commented on api-reference/beta/resources/appcredentialsigninactivity.md
> +| appObjectId              | String                                           | The ID of the credential application instance.                                                        |
Hmm, interesting. I thought the other tenant only has the service principal and therefore the SP object ID. Good to know that's not the case.

2023-05-23 08:15 UTC, FaithOmbongi approved these changes
Hi @madansr7 - LGTM!

2023-05-26 01:44 UTC, merged