changes to docs
microsoftgraph/microsoft-graph-docs pull request #20295
Opened 2023-02-18 01:32 UTC by sponnada

2023-03-08 18:54 UTC, sponnada commented on api-reference/beta/resources/verifiablecredentialretrieved.md
> +Used for the **credentialType** property of [verifiable credential settings](verifiablecredentialsettings.md).
used for verifiableCredentialRequirementStatus property of accessPackageAssignmentRequestRequirements

2023-03-17 22:51 UTC, markwahl-msft requested changes

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +                "expiryDateTime": "2022-05-10T23:32:47.8232759Z",
spurious comma

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-get.md
> +# [HTTP](#tab/http)
I believe all but the HTTP ones will be added automatically by a bot

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-get.md
> +        "issuers": ["did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W<SNIP>…"],
suggest remove "<SNIP>...".  This isn't intended to be a real value in the string.

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +    "verifiableCredentialSettings": {}
why si this {} and the one above it null?  shouldn't this be null?

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +  },
spurious comma

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +      "issuers": ["did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W<SNIP>…"],
see earlier comment on strings in examples

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +      "credentialType": "VerifiedCredentialExpert"
this is Expert not Export, correct?  Is this an enum or an arbitrary value from the issuer?

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/resources/enums.md
> +|request_retrieved|
why not camelCase?

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/resources/verifiablecredentialrequired.md
> +|url|String| The deep link URL that directs the user to Authenticator to provide the desired credentials.|
this is Graph API, can't assume the reader's users are using Authenticator app.

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/resources/verifiablecredentialrequirementstatus.md
> +Abstract type representing the verifiable credential requirement status for an access package.
Do you want to mention some of its sub-classes that inherit from it?

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/resources/verifiablecredentialsettings.md
> +|credentialTypes|[verifiableCredentialType](verifiableCredentialType.md) collection| List of verifiable credential type references.|
filenames should be lower case

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/resources/verifiablecredentialtype.md
> +|issuers|String collection| List of accepted issuers authority as identified by DID, for example, 'did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W\<SNIP\>…' |
see earlier comments on snip.  If snip is not significant then don't include it.

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/resources/verifiedCredentialData.md
> +---
change filename to be lowercase verifiedcredentialdata.md

2023-03-17 22:51 UTC, markwahl-msft commented on api-reference/beta/resources/verifiedCredentialData.md
> +|type|String Collection| The list of credential types provided by the issuer. |
word collection lower case

2023-03-21 16:24 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +    "verifiableCredentialSettings": {}
@mahajanudit-microsoft can you confirm?

2023-03-21 16:25 UTC, sponnada commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +      "credentialType": "VerifiedCredentialExpert"
Yup it's supposed to be expert and it's also an arbitrary value from the issuer.

2023-03-21 16:27 UTC, sponnada commented on api-reference/beta/resources/enums.md
> +|request_retrieved|
@mahajanudit-microsoft is there a reason we're not using camel case for all of them?

2023-03-22 20:34 UTC, mahajanudit-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +    "verifiableCredentialSettings": {}
Either works for us @markwahl-msft. Null or empty JSON.

2023-03-22 21:53 UTC, mahajanudit-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-get.md
> +# [HTTP](#tab/http)
Removed

2023-03-22 22:06 UTC, mahajanudit-microsoft commented on api-reference/beta/resources/verifiablecredentialrequirementstatus.md
> +Abstract type representing the verifiable credential requirement status for an access package.
Can you provide exact verbiage to be used to describe that this class is implemented by so and so classes?

2023-03-22 22:08 UTC, mahajanudit-microsoft commented on api-reference/beta/resources/verifiablecredentialtype.md
> +|issuers|String collection| List of accepted issuers authority as identified by DID, for example, 'did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W\<SNIP\>…' |
This pattern is already being used in VC public docs: [VC Payload](https://learn.microsoft.com/en-us/azure/active-directory/verifiable-credentials/presentation-request-api#presentation-request-payload)
Please advise.

2023-03-23 08:21 UTC, FaithOmbongi commented
Hi @sponnada - When this PR is ready for content review, remember to add the **ready for content review** label. Thanks.

2023-03-24 20:10 UTC, mahajanudit-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-get.md
> +        "issuers": ["did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W<SNIP>…"],
Leaving this as it is based on offline conversation since VC public doc uses the same "<SNIP>..." pattern

2023-03-24 20:12 UTC, mahajanudit-microsoft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +      "issuers": ["did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W<SNIP>…"],
Leaving this as it is based on offline conversation since VC uses the same "<SNIP>..." pattern

2023-03-24 20:14 UTC, mahajanudit-microsoft commented on api-reference/beta/resources/verifiablecredentialrequired.md
> +|url|String| The deep link URL that directs the user to Authenticator to provide the desired credentials.|
Changed to "A URL that launches the digital wallet app and starts the presentation process. You can present this URL to the user if they can't scan the QR code"

2023-03-30 14:46 UTC, FaithOmbongi requested changes
Thank you @sponnada for your work on this PR. I've left change suggestions inline plus the following comments:

**NOTE:** All through, I defer to you for technical accuracy.

- Is the Verified ID service only for EM? Or do we foresee the VC-related complex types being used by other services apart from EM?
   - If the latter, I recommend making the descriptions service-agnostic and mentioning EM as an example.
- **GLOBAL:** JSON representations in resource type docs shouldn't be confused with Examples. The JSON representation only indicates the return types. Please restore all JSONs in this section based on what you have in the autogenerated doc stubs.
- For verifiedCredentialsData, I recommend you show a sample in a response object, just like you've done for the other properties. Maybe update an example response in the [List accessPackageAssignmentRequests](https://review.learn.microsoft.com/en-us/graph/api/entitlementmanagement-list-accesspackageassignmentrequests?view=graph-rest-beta&branch=pr-en-us-20295&tabs=http) or the GET API doc?
- Please verify whether verifiableCredentialPresentationStatusCode needs to be published. It doesn't seem to be the return type of any property.
- Add the changelog

2023-03-30 14:46 UTC, FaithOmbongi commented on api-reference/beta/resources/verifiablecredentialrequired.md
> +Used for the **verifiableCredentialRequirementStatus** property of [access package assignment request requirements](accessPackageAssignmentRequestRequirements.md).
- Match the first sentence with metadata description.
- Indicate the upstream object

```suggestion
Verifiable credential requirements status indicating that credentials verification is required and returns the information required to initiate the credential verification process. Used for the **verifiableCredentialRequirementStatus** property of [access package assignment request requirements](accessPackageAssignmentRequestRequirements.md).

Inherits from [verifiableCredentialRequirementStatus](verifiableCredentialRequirementStatus.md).
```

2023-03-30 14:46 UTC, FaithOmbongi commented on api-reference/beta/resources/verifiedcredentialdata.md
> +description: "Data containing the metadata of the issuing authority, presented credentials and the verified claims."
```suggestion
description: "Represents the metadata of the verifiable credential including the issuing authority, presented credentials, and the verified claims."
```

2023-03-30 14:46 UTC, FaithOmbongi commented on api-reference/beta/resources/verifiedcredentialdata.md
> +Data containing the metadata of the issuing authority, presented credentials and the verified claims.
Match with Line 3

2023-03-30 14:46 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +### verifiableCredentialPresentationStatusCode values
Q: This enum has popped up but isn't defined as the return type of any parent property. I notice the same thing in the schema. Is it meant to be made public? Its values also seem to already be handled by the three types that are derived from verifiableCredentialRequirementStatus.

2023-04-11 21:26 UTC, mahajanudit-microsoft commented on api-reference/beta/resources/enums.md
> +|request_retrieved|
These values are sent directly from the DID service. We are defining them as we receive for our call back APIs

2023-04-11 21:26 UTC, mahajanudit-microsoft commented on api-reference/beta/resources/enums.md
> +### verifiableCredentialPresentationStatusCode values
This enum is sent to our callback API. Eventually we want to onboard that API to graph but as part of this PR, it is not. 
Do you suggest we remove this?

2023-04-11 21:33 UTC, mahajanudit-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-get.md
> +### Example 4: Retrieve a policy that contains a verifiable credentials requirement
Done

2023-04-11 21:33 UTC, mahajanudit-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
Can you update the title and close the comment?

2023-04-11 21:34 UTC, mahajanudit-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +### Example 4: Remove the verifiable credentials requirement from a policy
Done. I have updated the example 2 as "### Example 2: Remove the customExtensionHandlers, verifiableCredentialSettings from a policy"

2023-04-11 21:35 UTC, mahajanudit-microsoft commented on api-reference/beta/resources/verifiablecredentialsettings.md
> +}
Updated

2023-04-11 21:35 UTC, mahajanudit-microsoft commented on api-reference/beta/resources/verifiablecredentialtype.md
> +    "did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W<SNIP>…"
Updated

2023-04-14 08:52 UTC, FaithOmbongi approved these changes
Hi @sponnada , @mahajanudit-microsoft - Left suggestions for minor fixes.
Approved with suggestions.

Please sync your branch with the main branch and address the merge conflict so the PR is in a mergeable state.

2023-04-14 08:52 UTC, FaithOmbongi commented on api-reference/beta/resources/verifiablecredentialtype.md
> +|credentialType|String| The type of credential issued, for example, `BusinessCardCredential'`.|
```suggestion
|Property|Type|Description|
|:---|:---|:---|
|issuers|String collection| List of the accepted issuers authority as identified by the Microsoft Entra Verified ID service, for example, `did:ion:EiAlrenrtD3Lsw0GlbzS1O2YFdy3Xtu8yo35W\<SNIP\>...`. |
|credentialType|String| The type of credential issued, for example, `BusinessCardCredential`.|
```

2023-04-14 08:52 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +      "SubArea": "Identity governance"
To match the TOC
```suggestion
      "SubArea": "Governance"
```

2023-04-19 20:35 UTC, mahajanudit-microsoft approved these changes

2023-04-21 01:25 UTC, merged