Update Speller And Answer
microsoftgraph/microsoft-graph-docs pull request #20327
Opened 2023-02-22 03:39 UTC by ZChristine

1. update speller doc that if speller suggestion is disabled while speller modification is enabled, and there're results back in the search response for the original query with typo, speller suggestion can be returned in the response.
2. remove raw markdown description is not support
3. update answer doc that multiple answer search is supported

2023-02-22 13:39 UTC, njerigrevious requested changes
Please review the proposed changes and make sure we discuss in team meeting before finalizing. Thanks!

2023-02-22 13:39 UTC, njerigrevious commented on concepts/search-concept-speller.md
> +If speller suggestion is disabled while speller modification is enabled, and there're results back in the search response for the original query with typo, speller suggestion can be returned in the r
Rephrase to "If speller suggestion is disabled while speller modification is enabled, then results in the response will still contain the speller suggestion for the original query with the typo. This is by design since it is part of the feature to provide the spelling suggestion if spelling modification is enabled."

2023-02-22 13:39 UTC, njerigrevious commented on concepts/search-concept-acronym.md
> +- Combination search can only support in bookmark, qna and acronym.
Rephrase to "Combination search with non-Answer entityTypes (i.e. driveItem, list) is not supported. Only combination search with the other Answer entityTypes bookmarks, qna and acronym is supported."

2023-02-22 13:39 UTC, njerigrevious commented on concepts/search-concept-bookmark.md
> +- Combination search can only support in bookmark, qna and acronym.
Rephrase to "Combination search with non-Answer entityTypes (i.e. driveItem, list) is not supported. Only combination search with the other Answer entityTypes bookmarks, qna and acronym is supported."

2023-02-22 13:39 UTC, njerigrevious commented on concepts/search-concept-qna.md
> +- Combination search can only support in bookmark, qna and acronym.
Rephrase to "Combination search with non-Answer entityTypes (i.e. driveItem, list) is not supported. Only combination search with the other Answer entityTypes bookmarks, qna and acronym is supported."

2023-02-27 06:04 UTC, ZChristine commented on concepts/search-concept-qna.md
> +- Combination search can only support in bookmark, qna and acronym.
update.

2023-02-27 06:04 UTC, ZChristine commented on concepts/search-concept-bookmark.md
> +- Combination search can only support in bookmark, qna and acronym.
updates

2023-02-27 06:05 UTC, ZChristine commented on concepts/search-concept-acronym.md
> +- Combination search can only support in bookmark, qna and acronym.
update

2023-02-27 06:09 UTC, ZChristine commented on concepts/search-concept-speller.md
> +If speller suggestion is disabled while speller modification is enabled, and there're results back in the search response for the original query with typo, speller suggestion can be returned in the r
update

2023-02-27 14:36 UTC, njerigrevious requested changes
Please make the final corrections and then it'll be okay to submit!

2023-02-27 14:36 UTC, njerigrevious commented on concepts/search-concept-speller.md
> +If speller suggestion is disabled while speller modification is enabled, and there're results back in the search response for the original query with typo, then results in the response can still cont
Replace lines 19-22 with "If speller suggestion is disabled while speller modification is enabled, then results can still contain the speller suggestion for the original query with the typo. This is by design since feature provides the spelling suggestion by default if spelling modification is enabled."

2023-03-01 14:14 UTC, ZChristine commented
> Please make the final corrections and then it'll be okay to submit!

update

2023-03-01 15:14 UTC, njerigrevious approved these changes
Looks great - thanks for making the changes!

2023-03-07 04:47 UTC, Lauragra approved these changes

2023-03-07 05:41 UTC, merged