Article refresh: Get access on behalf of a user
microsoftgraph/microsoft-graph-docs pull request #20332
Opened 2023-02-22 13:25 UTC by FaithOmbongi

Refresh this article + address customer feedback.

2023-02-28 13:57 UTC, FaithOmbongi commented
#assign-reviewer: @marcusca10

2023-03-01 14:24 UTC, marcusca10 requested changes
@FaithOmbongi I included my comments for auth-concepts.md, I still need to look into auth-v2-user.md.
Please to use them as you feel it makes sense.

2023-03-01 14:24 UTC, marcusca10 commented on concepts/auth/auth-concepts.md
>  > An app can also get permissions through [Azure AD built-in roles](/azure/active-directory/roles/permissions-reference). These permissions don't limit the app to calling Microsoft Graph APIs.
I would remove "built-in" as it may be any Azure AD role including custom roles.
Notes:
-  Suggestion: "An app can also get permissions through Azure AD role-based access control" -> link https://learn.microsoft.com/en-us/azure/active-directory/roles/custom-overview
- It's still relevant to mention built in roles reference! -> /azure/active-directory/roles/permissions-reference
- I don't think I get what this means: "These permissions don't limit the app to calling Microsoft Graph APIs."

2023-03-01 14:43 UTC, marcusca10 requested changes
@FaithOmbongi comments for auth-v2-user.md. I would also include "Open ID Connect" in the beginning of the document as we use OIDC twice. It should be better from a SEO perspective.

2023-03-01 14:43 UTC, marcusca10 commented on concepts/auth-v2-user.md
>  2. Get authorization.
Request an authorization code.

2023-03-01 14:43 UTC, marcusca10 commented on concepts/auth-v2-user.md
>  3. Get an access token.
Request an access token.

2023-03-01 14:43 UTC, marcusca10 commented on concepts/auth-v2-user.md
> +- A redirect URI (or reply URL) for the app to receive responses from Azure AD.
Move up in the list (before line 43) to match the order of the other article. ;)

2023-03-01 14:43 UTC, marcusca10 commented on concepts/auth-v2-user.md
> +Although the access token is opaque to the app, the response contains a list of the permissions that the access token is good for in the `scope` parameter. The response is similar to the following sa
Again opaque :).
"Although the access token is opaque to the app," -> I prefer to make it clear it's not meant to be used by the calling app.

2023-03-01 14:43 UTC, marcusca10 commented on concepts/auth-v2-user.md
>  5. Use a refresh token to get a new access token.
"Use the refresh token to renew an expired access token."

2023-03-06 06:55 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +Microsoft Graph is a protected web API endpoint for accessing data in Microsoft cloud services like Azure AD and Microsoft 365. It's protected by the Microsoft identity platform.
Yep, you're right here. I see a similar mistake somewhere else - will fix.

2023-03-06 07:25 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +An application makes an authentication request to get access tokens that it uses to call an API. Access tokens that the Microsoft identity platform issues contain information (claims). Web APIs secur
Hmm, for 1st comment: should it be Azure AD or the Microsoft identity platform?  I understand Azure AD is the IAM. But the identity platform is the one that issues tokens and handled authN/Z. Or is the request to Azure AD which then talks to the identity platform in the backend? Need to be sure about when to refer to one over the other.

2023-03-06 07:26 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +We recommend that you use authentication libraries to manage your token interactions with the Microsoft identity platform. Authentication libraries abstract many protocol details like validation, coo
Sounds good. Since our user persona is the developer anyway.

2023-03-06 08:14 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
>  2. Get authorization.
Fixed.

2023-03-06 08:14 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
>  3. Get an access token.
Fixed

2023-03-06 08:16 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
>  5. Use a refresh token to get a new access token.
Fixed.

2023-03-06 08:17 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +- A redirect URI (or reply URL) for the app to receive responses from Azure AD.
Done.

2023-03-06 08:55 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
>  Delegated permissions, also called *scopes*, allow the application to act on behalf of the signed-in user. Application permissions, also called *app roles*, allow the app to access data on its own, w
Fixed.

2023-03-13 08:43 UTC, mwongerapk commented on concepts/auth/auth-concepts.md
> +An application makes an authentication request to the Microsoft identity platform get access tokens that it uses to call an API. Access tokens that the Microsoft identity platform issues contain deta
```suggestion
An application makes an authentication request to the Microsoft identity platform *get access tokens* that it uses to call an API. Access tokens that the Microsoft identity platform issues contain details about the application and the user, known as *claims*. Web APIs secured by the Microsoft identity platform, such as Microsoft Graph, use the claims to validate the caller and to ensure that the caller has the proper permissions to perform the operation they're requesting. The caller should treat access tokens as opaque strings because the contents of the token are intended for the API only. When calling Microsoft Graph, always protect access tokens by transmitting them over a secure channel that uses transport layer security (TLS).
```

2023-03-13 08:43 UTC, mwongerapk commented on concepts/auth/auth-concepts.md
> +We recommend that you use authentication libraries to manage your token interactions with the Microsoft identity platform. Authentication libraries abstract many protocol details like validation, coo
```suggestion
We recommend that you use authentication libraries to manage your token interactions with the Microsoft identity platform. Authentication libraries abstract many protocol details like validation, cookie handling, token caching, and maintaining secure connections, that lets you focus your development on your app's functionality. Microsoft publishes open-source client libraries and server middleware.
```

2023-03-13 08:43 UTC, mwongerapk commented on concepts/auth/auth-concepts.md
> +You don't need to use an authentication library to get an access token. To learn about directly using the Microsoft identity platform endpoints without the help of an authentication library, see the
Should this be highlighted more as a Note ?

2023-05-12 00:06 UTC, Jackson-Woods approved these changes
Looks good, please see comments. Mainly cleanup and clarification, nothing fundamental.

2023-05-12 00:06 UTC, Jackson-Woods commented on concepts/auth-v2-user.md
> +| ext_expires_in    | Indicates an extended lifetime for the access token (in seconds) and used to support resiliency when the token issuance service isn't responding.
why is it an "extended" lifetime? is there a regular lifetime too?

2023-05-25 14:30 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +The Microsoft identity platform must authorize any app that calls Microsoft Graph. This authorization is presented in the form of an *access token*, an artifact that proves that the calling app is au
Good callout. I've applied the first feedback which is shorter and keeps this article in context.

2023-05-25 14:40 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +- **Client secret**: A password that your app uses to authenticate with the Microsoft identity platform. You can optionally use a certificate or a federated identity credential. This property isn't n
Since you can configure the secret using either the UI or Graph, the option to configure it is technically available.

2023-05-25 17:20 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +We recommend that you use authentication libraries to manage your token interactions with the Microsoft identity platform. Authentication libraries abstract many protocol details like validation, coo
Good call. Applied.

2023-05-25 17:23 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +You don't need to use an authentication library to get an access token. To learn about directly using the Microsoft identity platform endpoints without the help of an authentication library, see the
Not for this one. It would have been better as a "Next step", but we can't have both "Next steps" and "See also" in the same article. I'll get some more insights from the curation team and come back to this.

2023-05-25 17:24 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
>  Apps get privileges to call Microsoft Graph with their own identity through one of the following ways:
Hmm, I'd like to avoid the term "authorized" because there's more to authorization than permissions and privileges right? Let's pick this discussion internally.

2023-05-25 17:25 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +This article details the raw HTTP requests involved for an app to get access on behalf of a user using a popular flow called the [OAuth 2.0 authorization code grant flow](/azure/active-directory/deve
Good catch. Fixed.

2023-05-25 17:29 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +5. Use the refresh token to renew an expired access token.
Makes sense. Applied.

2023-05-25 17:30 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +- A client (application) secret (password), a certificate, or a federated identity credential. This property isn't needed for public clients like native, mobile and single page applications.
Yep, you're right. Applied.

2023-05-25 17:31 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +## 2. Request an authorization code
Agree. Applied.

2023-05-25 17:34 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +- A client (application) secret (password), a certificate, or a federated identity credential. This property isn't needed for public clients like native, mobile and single page applications.
We can revisit this. The source of this info is the identity platform docs https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications#:~:text=Public%20client%20applications

2023-05-25 17:43 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +| ext_expires_in    | Indicates an extended lifetime for the access token (in seconds) and used to support resiliency when the token issuance service isn't responding.
Yeah. There's the default of 1 hour and you can configure longer timelines using the token lifetime policy.

2023-05-25 17:46 UTC, FaithOmbongi commented on concepts/auth/auth-concepts.md
> +> An app can also get permissions through Azure AD role-based access control (Azure AD RBAC). To get the list of permissions that are available through Azure AD RBAC, see [Azure AD roles](/azure/acti
I see that Exchange AppAccessPolicies will soon be replaced by RBAC https://learn.microsoft.com/en-us/powershell/module/exchange/new-applicationaccesspolicy?view=exchange-ps. Is this the general trend?

2023-05-25 17:49 UTC, FaithOmbongi commented on concepts/auth-v2-user.md
> +After the app sends the authorization request, the user is asked to enter their credentials to authenticate with Microsoft. The Microsoft identity platform v2.0 endpoint ensures that the user has con
Applied the second.

2023-05-25 19:24 UTC, FaithOmbongi commented
Hi @Jackson-Woods, @marcusca10 - Thank you both for your well thought feedback. I've applied most of it bar one or two that I'll bring up for further discussion.

2023-05-26 01:09 UTC, merged