USQ docs to Beta
microsoftgraph/microsoft-graph-docs pull request #20349
Opened 2023-02-24 01:51 UTC by BarryShehadeh

Add USQ docs to BETA.

2023-02-24 22:25 UTC, ificator approved these changes

2023-03-03 00:18 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +description: The unifiedStorageQuota resource providers an aggregate view of a user's quota information across multiple services.
```suggestion
description: The unifiedStorageQuota resource providers an aggregate view of a user's quota information across multiple services.
```

2023-03-03 00:18 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +The unifiedStorageQuota resource providers an aggregate view of a user's quota information across multiple services.
```suggestion
The unifiedStorageQuota resource provides an aggregate view of a user's quota information across multiple services.
```

2023-03-03 00:53 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|id|String|the user id|
```suggestion
|id|String|the user id.|
```

2023-03-03 01:03 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|remaining|Int64| Total space remaining before reaching the quota limit, in bytes. |
```suggestion
|remaining|Int64| Total space remaining before reaching the quota limit in bytes. |
```

2023-03-03 01:03 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|total|Int64| Total allowed storage space, in bytes. |
```suggestion
|total|Int64| Total allowed storage space in bytes. |
```

2023-03-03 01:04 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|used|Int64| Total space used, in bytes. |
```suggestion
|used|Int64| Total space used in bytes. |
```

2023-03-03 01:05 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|services|[serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) collection| The of services contributing to the user's quota usage. |
Please review this description. I am not clear, thanks!

2023-03-03 17:37 UTC, Danielabom commented on api-reference/v1.0/resources/quota.md
> +The **quota** resource provides details about space constrains on a [drive](drive.md) resource. The values will reflect the overall total/used unified storage quota across multiple Microsoft services
```suggestion
The **quota** resource provides details about space constraints on a [drive](drive.md) resource. The values reflect the total/used unified storage quota across multiple Microsoft services.
```

2023-03-06 20:04 UTC, BarryShehadeh commented on api-reference/beta/resources/unifiedstoragequota.md
> +|services|[serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) collection| The of services contributing to the user's quota usage. |
Sorry we didn't notice the word got accidentally deleted. I just fixed it. Appreciate it @Danielabom

2023-03-07 18:40 UTC, Danielabom commented on changelog/Microsoft.UnifiedStorageQuota.json
> +          "Description": "Added the servicestoragequotabreakdown-get method to the serviceStorageQuotaBreakdown resource.",
Global comments: Please add the links to the descriptions. Follow example 6 on this wiki: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2023-03-07 18:40 UTC, Danielabom commented on changelog/Microsoft.UnifiedStorageQuota.json
> +          "Description": "Added the unifiedstoragequota-get method to the unifiedstoragequota resource.",
Global comment: Please add the links to the descriptions. Follow example 6 on this wiki: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2023-03-08 14:22 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +description: The unifiedStorageQuota resource provides an aggregate view of a user's quota information across multiple services.
```suggestion
description: unifiedStorageQuota provides an aggregate view of a user's quota information across multiple services.
```

2023-03-08 14:23 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +The unifiedStorageQuota resource provides an aggregate view of a user's quota information across multiple services.
```suggestion
unifiedStorageQuota provides an aggregate view of a user's quota information across multiple services.
```

2023-03-08 14:24 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|[Get unifiedStorageQuota](../api/unifiedstoragequota-get.md)|[unifiedStorageQuota](../resources/unifiedstoragequota.md)|Read the properties and relationships of an [unifiedStorageQuota](../resources
```suggestion
|[Get unifiedStorageQuota](../api/unifiedstoragequota-get.md)|[unifiedStorageQuota](../resources/unifiedstoragequota.md)|Read the properties and relationships of a [unifiedStorageQuota](../resources/unifiedstoragequota.md) object.|
```

2023-03-08 14:47 UTC, Danielabom requested changes
Asked author to confirm I am using the correct links for this review: 
or example:
On the CSDL, the complex type called unifiedStorageQuota shows a relationship, but I do not see that on the PR.
On the api.md the complex type, unifiedStorageQuota shows just one property, contrary to the CSDL and the PR. 
**Please do not post any links here that may contain API info, or sensitive data**. Thanks :)

2023-03-09 15:01 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|[List services](../api/servicestoragequotabreakdown-list.md)|[serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) collection|Get the serviceStorageQuotaBreakdown resources fr
```suggestion
|[List services](../api/servicestoragequotabreakdown-list.md)|[serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) collection|Get the serviceStorageQuotaBreakdown contributing to the user's quota usage.|
```

2023-03-09 15:17 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|id|String|the user id.|
This property did not come up in any of the CSDLs.

2023-03-09 15:18 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|:---|:---|:---|
The CSDL shows this property:  Property Name="deleted" Type="Edm.Int64".
Please add it.

2023-03-09 15:19 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|id|String|the user id.|
```suggestion
|id|String|The user id.|
```

2023-03-09 15:27 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +| Value          |
Please edit the column headers. The correct headers are "Member" and "Description".

2023-03-09 15:28 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +### usqState values
In the properties table: for a property of that enumeration type {enum-type}, specify that enumeration as the property type, and link to the H3 that has the enum table. Specifying the possible values in the description is not required but is convenient for customers.

2023-03-09 16:05 UTC, Danielabom commented on api-reference/beta/resources/servicestoragequotabreakdown.md
> +description: "The serviceStorageQuotaBreakdown resource represents a proportion of the unified storage quota associated with a specific service."
```suggestion
description: "Represents a proportion of the unified storage quota associated with a specific service."
```

2023-03-09 16:05 UTC, Danielabom commented on api-reference/beta/resources/servicestoragequotabreakdown.md
> +The serviceStorageQuotaBreakdown resource represents a proportion of the unified storage quota associated with a specific service.
```suggestion
Represents a proportion of the unified storage quota associated with a specific service.
```

2023-03-09 16:25 UTC, Danielabom commented on api-reference/beta/resources/servicestoragequotabreakdown.md
> +|displayName|String|The name of the breakdown that can be displayed to users. Localized. Read-only.|
```suggestion
|displayName|String|The breakdown name displayed to users. Localized. Read-only.|
```

2023-03-09 16:26 UTC, Danielabom commented on api-reference/beta/resources/servicestoragequotabreakdown.md
> +|id|String|The id of the breakdown. Read-only.|
```suggestion
|id|String|The breakdown id. Read-only.|
```

2023-03-09 16:29 UTC, Danielabom commented on api-reference/beta/api/unifiedstoragequota-get.md
> +description: "Read the properties and relationships of an unifiedStorageQuota object."
```suggestion
description: "Read the properties and relationships of a unifiedStorageQuota object."
```

2023-03-09 16:31 UTC, Danielabom commented on api-reference/beta/api/unifiedstoragequota-get.md
> +Read the properties and relationships of an [unifiedStorageQuota](../resources/unifiedstoragequota.md) object.
```suggestion
Read the properties and relationships of a [unifiedStorageQuota](../resources/unifiedstoragequota.md) object.
```

2023-03-09 16:31 UTC, Danielabom commented on api-reference/beta/api/unifiedstoragequota-get.md
> +If successful, this method returns a `200 OK` response code and an [unifiedStorageQuota](../resources/unifiedstoragequota.md) object in the response body.
```suggestion
If successful, this method returns a `200 OK` response code and a [unifiedStorageQuota](../resources/unifiedstoragequota.md) object in the response body.
```

2023-03-09 16:33 UTC, Danielabom commented on api-reference/beta/api/servicestoragequotabreakdown-list.md
> +description: "Get a list of the serviceStorageQuotaBreakdown objects and their properties."
```suggestion
description: "Get a list of serviceStorageQuotaBreakdown objects and their properties."
```

2023-03-09 16:34 UTC, Danielabom commented on api-reference/beta/api/servicestoragequotabreakdown-list.md
> +Get a list of the [serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) objects and their properties.
```suggestion
Get a list of [serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) objects and their properties.
```

2023-03-09 16:35 UTC, Danielabom commented on api-reference/beta/api/servicestoragequotabreakdown-list.md
> +|Name|Description|
The correct headers are: Name | Type | Description |

2023-03-09 17:36 UTC, Danielabom commented on changelog/Microsoft.UnifiedStorageQuota.json
> +          "ChangedApiName": "unifiedStorageQuota",
```suggestion
          "ChangedApiName": "get",
```

2023-03-09 17:54 UTC, Danielabom commented on changelog/Microsoft.UnifiedStorageQuota.json
> +          "ChangedApiName": "unifiedStorageQuota",
```suggestion
          "ChangedApiName": "GET",
```

2023-03-09 17:58 UTC, Danielabom commented on changelog/Microsoft.UnifiedStorageQuota.json
> +          "Description": "Added the [servicestoragequotabreakdown-get](https://learn.microsoft.com/en-us/graph/api/servicestoragequotabreakdown-get?view=graph-rest-beta) method to the [serviceStorage
```suggestion
          "Description": "Added the [get](https://learn.microsoft.com/en-us/graph/api/servicestoragequotabreakdown-get?view=graph-rest-beta) operation to the [serviceStorageQuotaBreakdown](https://learn.microsoft.com/en-us/graph/api/resources/serviceStorageQuotaBreakdown?view=graph-rest-beta) resource.",
```

2023-03-09 20:00 UTC, BarryShehadeh commented on api-reference/beta/resources/unifiedstoragequota.md
> +| Value          |
Discussed offline. Keeping just this enum as is.

2023-03-09 20:04 UTC, BarryShehadeh commented on api-reference/beta/resources/unifiedstoragequota.md
> +|:---|:---|:---|
Will be added later. As it's not yet ready to be published.

2023-03-09 22:29 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +| Value          |
We need natural language descriptions. The member names are not intuitive. 
For example: What does nearing mean? Is nearing a valid word? 
The enums topic in the CDK  mentions that we should not show numerical values in customer-facing docs. 
Please make the corresponding changes.

2023-03-09 23:05 UTC, Danielabom commented on api-reference/beta/api/servicestoragequotabreakdown-list.md
> +title: "List serviceStorageQuotaBreakdown"
Please rename this file.
The CSDL file indicates that the parent entity of your navigation property is unifiedStorageQuota. Please follow this format:  parententityname-list-navigationpropertyname. Make the corresponding changes in the entity topic and the changelog.

2023-03-09 23:15 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|[List services](../api/servicestoragequotabreakdown-list.md)|[serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) collection|Get the serviceStorageQuotaBreakdown resources fr
```suggestion
|[List services](../api/servicestoragequotabreakdown-list.md)|[unifiedStorageQuota](#usqState-values) collection|Get a list of services in the serviceStorageQuotaBreakdown.|
```

2023-03-09 23:25 UTC, Danielabom requested changes
Just a couple more changes, and we're done. Please review my comments. Thanks!

2023-03-09 23:59 UTC, BarryShehadeh commented on api-reference/beta/api/servicestoragequotabreakdown-list.md
> +|Name|Description|
Discussed offline, leaving them to match current OneDrive docs

2023-03-09 23:59 UTC, BarryShehadeh commented on api-reference/beta/api/unifiedstoragequota-get.md
> +|Name|Description|
Discussed offline, leaving them to match current OneDrive docs.

2023-03-10 00:00 UTC, BarryShehadeh commented on api-reference/beta/resources/servicestoragequotabreakdown.md
> +|[Get serviceStorageQuotaBreakdown](../api/servicestoragequotabreakdown-get.md)|[serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md)|Read the properties and relationships of a
You are right, I had it in the parent entity instead. Just fixed it.

2023-03-10 00:07 UTC, BarryShehadeh reviewed
The rest should be good.

2023-03-10 00:07 UTC, BarryShehadeh commented on api-reference/beta/resources/quota.md
> +The **quota** resource provides details about space constraints on a [drive](drive.md) resource. In OneDrive Personal, the values reflect the total/used unified storage quota across multiple Microsof
@Danielabom Just you are aware, I added "In OneDrive Personal, " beside your review comments here.

2023-03-14 20:40 UTC, Danielabom commented on api-reference/beta/api/unifiedstoragequota-get-services.md
> +---
Hi @BarryShehadeh, I asked you to change the filename of a list operation, and you did it. I appreciate it!
However, this method was fine as it was. Is there a reason in particular why you decided to make this change?

2023-03-14 20:42 UTC, Danielabom commented on api-reference/beta/api/unifiedstoragequota-get-services.md
> +title: "Get serviceStorageQuotaBreakdown"
Hi @BarryShehadeh, I asked you to change the filename of a list operation, and you did it. I appreciate it!
However, this method was fine as it was. Is there a reason in particular why you decided to make this change?

2023-03-14 20:46 UTC, BarryShehadeh commented on api-reference/beta/api/unifiedstoragequota-get-services.md
> +title: "Get serviceStorageQuotaBreakdown"
@Danielabom the only difference between the two is one a "get" and the other is a "list". So I thought it would be the same?

2023-03-14 20:49 UTC, Danielabom requested changes
@BarryShehadeh, perhaps you need to step back and review my comments one by one. You changed the name of a file, that was fine unless you make changes on the CSDL again. Also, please review line 6 on each one of your files. Is that a valid name? Because your build is popping some warnings. Thanks in advance.

2023-03-16 00:36 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +
|[List serviceStorageQuotaBreakdown](../api/unifiedstoragequota-list-services.md)| [serviceStorageQuotaBreakdown](../resources/servicestoragequotabreakdown.md) collection|Get the list of services in serviceStorageQuotaBreakdown.|

2023-03-16 00:43 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +
```suggestion
|[List serviceStorageQuotaBreakdown](https://github.com/microsoftgraph/microsoft-graph-docs/pull/api/unifiedstoragequota-list-services.md)| [serviceStorageQuotaBreakdown](https://github.com/microsoftgraph/microsoft-graph-docs/pull/resources/servicestoragequotabreakdown.md) collection|Get the list of services in serviceStorageQuotaBreakdown.|
```

2023-03-16 03:46 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +|state|[usqState](#usqstate-values)| Enumeration value that indicates the state of the storage space. |
```suggestion
|state|[usqState](#usqstate-values)| Indicates the state of the storage space. The possible values are: 'normal'      'nearing', 'critical', 'full' and 'overLimit'.|
```

2023-03-16 03:48 UTC, Danielabom approved these changes
Barry informed me that he could not add descriptions to the enum value members at this time. PR approved.

2023-03-16 04:40 UTC, Danielabom commented on api-reference/beta/resources/unifiedstoragequota.md
> +ms.prod: "unified-storage-quota"
```suggestion
ms.prod: files
```

2023-03-16 04:41 UTC, Danielabom commented on api-reference/beta/resources/servicestoragequotabreakdown.md
> +ms.prod: "unified-storage-quota"
```suggestion
ms.prod: files
```

2023-03-16 04:42 UTC, Danielabom commented on api-reference/beta/api/unifiedstoragequota-list-services.md
> +ms.prod: "unified-storage-quota"
```suggestion
ms.prod: files
```

2023-03-16 04:43 UTC, Danielabom commented on api-reference/beta/api/unifiedstoragequota-get.md
> +ms.prod: "unified-storage-quota"
```suggestion
ms.prod: files
```

2023-03-16 04:43 UTC, Danielabom commented on api-reference/beta/api/servicestoragequotabreakdown-get.md
> +ms.prod: "unified-storage-quota"
```suggestion
ms.prod: files
```

2023-03-16 05:04 UTC, Danielabom commented on api-reference/beta/toc.yml
> +           href: resources/quota.md
```suggestion
          href: resources/quota.md
```

2023-03-16 05:11 UTC, Danielabom commented on api-reference/beta/toc.yml
> +              name: List
```suggestion
              - name: List
```

2023-03-16 18:30 UTC, BarryShehadeh commented on api-reference/beta/toc.yml
> +              href: api/unifiedstoragequota-list-services.md
```suggestion
        - name: Quota
          items:
          - name: Unified Storage Quota
            href: resources/unifiedstoragequota.md
            items:
            - name: Get
              href: api/unifiedstoragequota-get.md
            - name: List
              href: api/unifiedstoragequota-list-services.md
          - name: Service Storage Quota Breakdown 
            href: resources/servicestoragequotabreakdown.md
            items:
            - name: Get
              href: api/servicestoragequotabreakdown-get.md
            - name: List
              href: api/unifiedstoragequota-list-services.md
```

2023-03-17 03:39 UTC, merged