Add permission reference for PeopleSettings
microsoftgraph/microsoft-graph-docs pull request #20358
Opened 2023-02-24 12:13 UTC by aymen-ms

2023-04-12 16:57 UTC, Danielabom requested changes
@aymen-ms, thank you for working on this PR. The description format in the changelog needs to be corrected; we need the links. Also, your build keeps failing; please review it. Thanks!

2023-04-13 15:28 UTC, aymen-ms commented
> @aymen-ms, thank you for working on this PR. The description format in the changelog needs to be corrected; we need the links. Also, your build keeps failing; please review it. Thanks!

we have not yet published the api that will use this permissions so I can't link it at the moment

2023-04-20 00:37 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Added support for the policy-based application permission of `PeopleSettings.Read.All` to read tenant-wide peoplesettings resource.",
@aymen-ms, please follow the correct format and add the links of the resources/methods by these permissions. 
See example #14 from this wiki (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-04-20 00:38 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Added support for the policy-based application permission of `PeopleSettings.Read.All` to the read and write tenant-wide peoplesettings resource.",
@aymen-ms, please follow the correct format and add the links of the resources/methods by these permissions.
See example https://github.com/microsoftgraph/microsoft-graph-docs/pull/14 from this wiki (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-04-20 00:39 UTC, Danielabom requested changes
@aymen-ms, please review my comments and follow the changelog guidelines. Thanks!

2023-05-16 23:12 UTC, Danielabom commented
Following up on this PR. Please reach out if you have questions @aymen-ms.

2023-06-29 01:22 UTC, Danielabom commented
Hi @aymen-ms, please let us know if we need to contact someone else so that we can follow up on this PR. Thanks!

2023-06-29 16:33 UTC, aymen-ms commented on changelog/Microsoft.People.json
> +					"Description": "Added support for the policy-based application permission of `PeopleSettings.Read.All` to the read and write tenant-wide peoplesettings resource.",
Merged to #21404

2023-06-29 16:35 UTC, aymen-ms commented
Merged the changes in this PR to #21404

2023-06-29 16:35 UTC, closed without merging