[CloudPC] Added User\CloudPC Start and Stop methods
microsoftgraph/microsoft-graph-docs pull request #20362
Opened 2023-02-24 19:00 UTC by rbayetov

Added Start and Stop methods under User\CloudPC

2023-02-27 01:20 UTC, AshleyYangSZ requested changes

2023-02-27 01:20 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-start.md
> +Start specific Cloud PC. This is to cover Shift Work CloudPC end user scenarios.
Start your own Cloud PC. Currently, only Shift Work Cloud PC is supported.

2023-02-27 01:20 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-start.md
> +To start the [cloudPC](../resources/cloudpc.md) of the specified user (who is the signed-in user) in the organization using delegated permission:
using this API.

2023-02-27 01:20 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-stop.md
> +Stop specific Cloud PC. This is to cover Shift Work CloudPC end user scenarios.
Stop your own Cloud PC. Currently, only Shift Work Cloud PC is supported.

2023-02-27 01:20 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-stop.md
> +To stop the [cloudPC](../resources/cloudpc.md) of the specified user (who is the signed-in user) in the organization using delegated permission:
using this API.

2023-02-27 02:51 UTC, rbayetov commented on api-reference/beta/api/cloudpc-start.md
> +Start specific Cloud PC. This is to cover Shift Work CloudPC end user scenarios.
changed

2023-02-27 02:51 UTC, rbayetov commented on api-reference/beta/api/cloudpc-stop.md
> +Stop specific Cloud PC. This is to cover Shift Work CloudPC end user scenarios.
changed

2023-03-02 07:24 UTC, RuiHou105 approved these changes

2023-04-04 04:18 UTC, JarbasHorst commented
Hello @rbayetov, I reviewed your PR and left some comments. Please, take a look when you will have time.

2023-04-04 18:26 UTC, rbayetov commented on api-reference/beta/api/cloudpc-stop.md
> +POST /me/cloudPCs/{cloudPCId}/stop
no. It does not. It only supports /me/cloudPC/... path

2023-04-04 18:28 UTC, rbayetov commented on api-reference/beta/api/cloudpc-start.md
> +description: "Start a specific Cloud PC."
updated

2023-04-04 18:28 UTC, rbayetov commented on api-reference/beta/api/cloudpc-stop.md
> +description: "Stop a specific Cloud PC."
updated

2023-04-05 03:29 UTC, JarbasHorst commented
Hi @Lauragra, this PR is ready for final review.

2023-04-11 00:27 UTC, Lauragra commented on api-reference/beta/api/cloudpc-start.md
> +To start the [cloudPC](../resources/cloudpc.md) of the specified user (who is the signed-in user) in the organization using delegated permission:
Why do we have an introductory sentence here if there's only one syntax? Generally we add an introduction when we have more than one possible syntax.

2023-04-11 00:28 UTC, Lauragra commented on api-reference/beta/api/cloudpc-start.md
> +Start a specific Cloud PC for a user. Currently, only shift work Cloud PC is supported.
Can you clarify, what is a "shift work Cloud PC"?

2023-04-11 00:29 UTC, Lauragra commented on api-reference/beta/api/cloudpc-stop.md
> +Stop a specific Cloud PC for a user. Currently, only shift work Cloud PC is supported.
Please clarify what a shift work Cloud PC is here as well.

2023-04-11 00:30 UTC, Lauragra commented on api-reference/beta/api/cloudpc-stop.md
> +To stop the [cloudPC](../resources/cloudpc.md) of the specified user (who is the signed-in user) in the organization using delegated permission:
Not sure that we need an introductory sentence here.

2023-04-11 15:42 UTC, rbayetov commented on api-reference/beta/api/cloudpc-stop.md
> +To stop the [cloudPC](../resources/cloudpc.md) of the specified user (who is the signed-in user) in the organization using delegated permission:
updated

2023-04-11 15:42 UTC, rbayetov commented on api-reference/beta/api/cloudpc-start.md
> +Start a specific Cloud PC for a user. Currently, only shift work Cloud PC is supported.
Updated "shift work" (legacy name) to "Frontline" new branding and added link to resource to know more

2023-04-11 15:43 UTC, rbayetov commented on api-reference/beta/api/cloudpc-stop.md
> +Stop a specific Cloud PC for a user. Currently, only shift work Cloud PC is supported.
Updated "shift work" (legacy name) to "Frontline" new branding and added link to resource to know more

2023-04-12 03:10 UTC, Lauragra approved these changes

2023-04-13 02:48 UTC, merged