New files
microsoftgraph/microsoft-graph-docs pull request #20367
Opened 2023-02-25 00:46 UTC by msft-poulomi

2023-02-27 22:22 UTC, jpettere requested changes
Added comments. I also think you're missing documenting the API call that can be made on an individual user to get their signInPreferences so let's make sure to add that. 

https://graph.microsoft.com/beta/users/{user UPN or ID}/authentication/signInPreferences

The /authentication/signInPreferences is not changed in this feature and is hence not available in doc stubs. This was confirmed by the engineer.

2023-02-27 22:22 UTC, jpettere commented on api-reference/beta/api/authenticationmethodspolicy.md
> +|systemCredentialPreferences|[systemCredentialPreferences](../resources/systemcredentialpreferences.md)|"Credential preference for all user authentications is calculated at runtime and prompted to th
This file already exists (link below). You should find the existing one and add systemCredentialPreferences to it. 

https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicy?view=graph-rest-beta

2023-02-27 22:22 UTC, jpettere commented on api-reference/beta/api/systemcredentialpreferences.md
> +title: "authenticationMethodsPolicy resource type"
Update the resource type.

2023-02-27 22:22 UTC, jpettere commented on api-reference/beta/api/systemcredentialpreferences.md
> +**TODO: Add Description**
Make sure to do all of the TODO's.

2023-02-27 22:22 UTC, jpettere commented on api-reference/beta/api/systemcredentialpreferences.md
> +|state|advancedConfigState|Enable or disable the feature. Possible values are: `default`, `enabled`, `disabled`, `unknownFutureValue`. The `default` value is used when the configuration hasn't been e
Just double checking but the MS default value is "disabled" to start?

2023-03-07 06:57 UTC, msft-poulomi commented on api-reference/beta/api/systemcredentialpreferences.md
> +title: "authenticationMethodsPolicy resource type"
Updated

2023-03-07 07:01 UTC, msft-poulomi commented on api-reference/beta/api/systemcredentialpreferences.md
> +|state|advancedConfigState|Enable or disable the feature. Possible values are: `default`, `enabled`, `disabled`, `unknownFutureValue`. The `default` value is used when the configuration hasn't been e
Yes

2023-03-07 07:06 UTC, msft-poulomi commented on api-reference/beta/api/systemcredentialpreferences.md
> +**TODO: Add Description**
Updated

2023-03-08 01:19 UTC, jpettere requested changes
I think you're still missing documenting the API for:

https://graph.microsoft.com/beta/users/{UPN or ID}/authentication/signInPreferences

2023-03-08 01:19 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
> +|Property|Type|Description|Required|ReadOnly
If I look at the rich diff the properties table doesn't render. You should remove the required and read-only column headers.

2023-03-08 01:19 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
> +|state|microsoft.graph.advancedConfigState|The configuration state of the system preferred authentication method experience.|Yes|No
these properties (state, includeTargets and excludeTargets) should be unchanged. They are properties of authenticationmethodspolicy, not system preferred auth.

2023-03-08 01:19 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
> +|systemCredentialPreferences|[systemCredentialPreferences](../resources/systemcredentialpreferences.md)|"Credential preference for all user authentications is calculated at runtime and prompted to th
This seems to be missing part of the definition and remove the quotes.

2023-03-08 01:19 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
> +    "systemCredentialPreferences": {
indent this back 1 tab.

2023-04-03 03:35 UTC, Jarbas-MSFT commented
Hi everyone, closing this PR because this content already exists in PR #20260.

2023-04-03 03:35 UTC, closed without merging