AuthenticationStrengthv1
microsoftgraph/microsoft-graph-docs pull request #20366
Opened 2023-02-24 22:59 UTC by InbarckMS

Moving Auth Strength to v1 and depreacting functions from beta

2023-02-27 18:13 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md
> +  > The `findByMethodMode` function is only available in `/beta` and will not become available in `/v1.0`. To get a list of  [authenticationStrengthPolicy](../resources/authenticationstrengthpolicy.m
```suggestion
  > The `findByMethodMode` function is only available in `/beta` and will not become available in `/v1.0`. To get a list of [authenticationStrengthPolicy](../resources/authenticationstrengthpolicy.md) filtered to only include policies that include the authentication method mode specified in the request, use XXX instead
```

2023-03-08 13:48 UTC, FaithOmbongi requested changes
Thank you @InbarckMS for your work on this PR.

I've left suggestions inline plus the following:
- Question: Are updateAllowedCombinations action and findByMethodMode function getting deprecated in beta or is it that they won't be promoted to v1.0? 
   - If it's the latter, remove the "(deprecated)" statement from both the TOC and the titles.
   - If the former, also ensure that your schema PR includes the deprecation annotations. That will be required for approval of the docs PR.
- Add the **authenticationStrengthPolicies** relationship to [policyRoot](https://learn.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-1.0).
- GLOBAL: The enums like authenticationMethodModes, authenticationStrengthPolicyType, and authenticationStrengthRequirements haven't been defined in the enums.md file . This is the cause for many (if not all) of the API doctor errors in the v1.0 files.
- GLOBAL: I mentioned a while back that we need to start calling out the RBAC roles for delegated access READ vs WRITE. That way, customers don't have to use Global Admin, dig around, or report 403s. Let me know once you have the info available and I can guide you on this.
   - Let's do that for GA in this PR. You can raise a separate PR for beta.
- GLOBAL: Delete all the `# [HTTP](#tab/http)` in examples. These will be added by the snippets generator.
- Couldn't find neither the **usage** function nor the **authenticationStrengthUsage** complex type in the v1.0 schema PR. Please verify.
- Couldn't find the **authenticationStrength** relationship of conditionalAccessGrantControls in the schema either. Please verify.
- GLOBAL: I see some docs are still assigned to Michael. Please reassign them to yourself. Even the beta docs.
  - Also, only 1 alias is allowed in the "author" field.
- GLOBAL: None of the resources inherited from entity in v1.0. Please make sure you remove any "Inherits from entity/Inherited from entity/"baseType": "microsoft.graph.entity"" entries.
- GLOBAL: I see you moved all CA-related URLs from `/identity/conditionalAccess/authenticationStrengths/` (plural Strengths) to `/identity/conditionalAccess/authenticationStrengths/` (singular Strength). However, there are many left over instances even in beta.
   - Please do a search and replace to replace all these instances in both v1.0 and beta.
   - For response objects, the @odata.context also contains the plural form. Make sure to change to the singular form `...#identity/conditionalAccess/authenticationStrength/`.
   - This isn't a breaking change because you're not blocking the API side. But let's document the endpoint that you want customers to use going forward.
- Add the changelog please. Remember to download it from your schema PR in time. The artifacts expire after 15 days of a successful build and if the schema PR is merged and 15 days pass before you get the files, you will need to create the changelog manually.

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationstrengthpolicy.md
> +|[Create authenticationCombinationConfiguration](../api/authenticationstrengthpolicy-post-combinationconfigurations.md)|[authenticationCombinationConfiguration](../resources/authenticationcombination
Not here. They should be in the authenticationCombinationConfiguration.md file.
```suggestion
```

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationstrengthusage.md
> +---
This object isn't in the v1.0 schema. Please verify.
Once fixed, reassign the doc to yourself.

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationstrengthpolicy-updateallowedcombinations.md
> +author: "mmcla; inbarckMS"
Only one author.

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationcombinationconfiguration.md
> +An authentication combination configuration sets restrictions on specific types, modes, versions, etc. of an authentication method that is tied to specific auth method combinations used in an [authen
```suggestion
An authentication combination configuration sets restrictions on specific types, modes, and versions of an authentication method that is tied to specific auth method combinations used in an [authentication strength](authenticationstrengths-overview.md).
```

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationcombinationconfiguration.md
> +|id|String|A unique system-generated identifier. Inherited from [entity](../resources/entity.md).|
```suggestion
|id|String|A unique system-generated identifier.|
```

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationcombinationconfiguration.md
> +  "baseType": "microsoft.graph.entity",
For same reason indicated above
```suggestion
```

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationmethodmodedetail.md
> +Inherits from [entity](../resources/entity.md).
Not anymore

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationmethodmodedetail.md
> +|id|String|The system-generated identifier for this mode. Inherited from [entity](../resources/entity.md).|
Same reason as above
```suggestion
|id|String|The system-generated identifier for this mode. |
```

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationmethodmodedetail.md
> +  "baseType": "microsoft.graph.entity",
Same reason as above
```suggestion
```

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationstrengthroot-list-authenticationmethodmodes.md
> +author: "mmcla;inbarckMS"
Only One

2023-03-08 13:48 UTC, FaithOmbongi commented on api-reference/v1.0/resources/conditionalaccessgrantcontrols.md
> +| authenticationStrength | [authenticationStrengthPolicy](authenticationstrengthpolicy.md) | The authentication strength required by the conditional access policy. Optional.|
This change isn't in the v1.0 schema PR. Please verify.

2023-03-10 19:47 UTC, InbarckMS commented on api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md
> +# authenticationStrengthPolicy: updateAllowedCombinations
We ended up not depreacting updateAllowedCombinations, only findByMethod.

2023-03-10 20:58 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationstrengthpolicy-usage.md
> +description: "The `usage` function allows the caller to see which Conditional Access policies reference a specified authentication strength policy"
Updated

2023-03-10 20:58 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationstrengthpolicy-usage.md
> +The `usage` function allows the caller to see which Conditional Access policies reference a specified authentication strength policy. The policies are returned in two collections, one containing Cond
Updated

2023-03-10 21:02 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationstrengthroot-list-policies.md
> +
These are the RBAC:

-	Conditional Access administrator (R/W)
-	Security Administrator (R/W)
-	Security Reader (Read only)

Can you share an example I can modify for auth strength?

2023-03-13 19:45 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthpolicy.md
> +|[List usage](../api/authenticationstrengthpolicy-usage.md)|[authenticationStrengthUsage](../resources/authenticationstrengthusage.md)|Find all [conditionalAccessPolicies](../resources/conditionalacc
We are going to add it to the PR, I'm keeping this discussion open until we do.

2023-03-13 19:53 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthpolicy.md
> +|[Create authenticationCombinationConfiguration](../api/authenticationstrengthpolicy-post-combinationconfigurations.md)|[authenticationCombinationConfiguration](../resources/authenticationcombination
I see them already in authenticationCombinationConfiguration, so I'm going to only remove them from here.

2023-03-13 20:00 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthpolicy.md
> +|allowedCombinations|authenticationMethodModes collection|A collection of authentication method modes that are required be used to satify this authentication strength.|
Updated. Will check API doctor again after the next commit.

2023-03-13 20:01 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthpolicy.md
> +|id|String|The system-generated identifier for this mode. Inherited from [entity](../resources/entity.md).|
Updated.

2023-03-13 20:02 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthroot.md
> +Inherits from [entity](../resources/entity.md).
Updated

2023-03-13 20:02 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthroot.md
> +|id|String|A system-generated identifier. Inherited from [entity](../resources/entity.md).|
Updated

2023-03-13 20:03 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthroot.md
> +  "baseType": "microsoft.graph.entity",
Updated

2023-03-13 20:03 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengths-overview.md
> +author: "mmcla"
Updated

2023-03-13 20:04 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengths-overview.md
> +ms.date: 12/10/2022
Updated to today, but this is likely going to be published in April. Is that OK?

2023-03-13 20:05 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthusage.md
> +---
We need to add to the v1 PR, will keep this comment open until we address in the PR.

2023-03-13 21:45 UTC, InbarckMS commented
> @FaithOmbongi - thanks for the review. I've gone over the comment and global comment and addressed the feedback.

Here is additional info regarding your question:
Question: Are updateAllowedCombinations action and findByMethodMode function getting deprecated in beta or is it that they won't be promoted to v1.0?
Answer: We ended up only deprecating findByMethodMode; I've asked the engineers to update the PR. Will circle back once it is done,

Add the authenticationStrengthPolicies relationship to policyRoot >> Done.

GLOBAL: The enums haven't been defined in the enums.md file  >> Done.

GLOBAL: RBAC --> I've responded to your comment with the permissions. Can you share an example I should follow?

GLOBAL: Delete all the # [HTTP](#tab/http) in examples. >> Done.

Couldn't find neither the usage function nor the authenticationStrengthUsage complex type in the v1.0 schema PR
+ Couldn't find the authenticationStrength relationship of conditionalAccessGrantControls in the schema either. 
 >> These are missing from the PR, waiting for the engineers to update and will circle back.

Please verify.
GLOBAL: Author - Update the docs to my name.

GLOBAL: None of the resources inherited from entity in v1.0.  >> Done.

GLOBAL: Lefovers /identity/conditionalAccess/authenticationStrengths/  >> Done.

changelog >> Done.

Please review, I will also circle back once the missing portions from the schema PR are updated.

2023-03-17 16:02 UTC, FaithOmbongi requested changes
Hi @InbarckMS - A few feedback items, mostly clean up; See inline +
- GLOBAL: Restore all snippet files to what they were. The snippets will be autogenerated because the tooling will detect that your examples have changed.
- GLOBAL: Confirm the URLs in all the v1.0 docs. I see URLs for beta endpoints in v1.0 docs.
- For the RBAC statement, I've pushed a commit to create the include file and add a sample to one doc. For the READ statement, check out authenticationstrengthroot-list-policies.md; For WRITE statement, check out authenticationstrengthroot-delete-policies.md.

2023-03-17 20:11 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationcombinationconfiguration-get.md
> +GET https://graph.microsoft.com/beta/identity/conditionalAccess/authenticationStrength/policies/0e371351-6419-4c8a-8047-61eef0212ffb/combinationConfigurations/133b68c4-503b-4e87-839a-6c286a27381b
Updated.

2023-03-17 20:12 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationcombinationconfiguration-update.md
> +If successful, this method returns a `204 NO CONTENT` response code.
Updated.

2023-03-17 20:12 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationcombinationconfiguration-update.md
> +PATCH https://graph.microsoft.com/beta/identity/conditionalAccess/authenticationStrength/policies/0e371351-6419-4c8a-8047-61eef0212ffb/combinationConfigurations/4643f174-fe85-42b8-8b84-516775750a30
Updated.

2023-03-17 20:13 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationstrengthpolicy-list-combinationconfigurations.md
> +author: "mmcla;inbarckMS"
Updated.

2023-03-17 20:13 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationstrengthpolicy-post-combinationconfigurations.md
> +author: "mmcla;inbarckMS"
Updated.

2023-03-17 20:14 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationstrengthpolicy-update.md
> +If successful, this method returns a `204 NO CONTENT` response code.
Updated

2023-03-17 20:41 UTC, InbarckMS commented on api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md
> +> `GET /policies/authenticationStrengthPolicies?$filter[allowedCombinations/any(x:x has 'sms, password')]`
Updated

2023-03-17 20:41 UTC, InbarckMS commented on api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md
> +Get a list of the [authenticationStrengthPolicy](../resources/authenticationstrengthpolicy.md) objects and their properties filtered to only include policies that include the authentication method mo
Updated

2023-03-17 21:05 UTC, InbarckMS commented on api-reference/v1.0/api/authenticationstrengthroot-list-policies.md
> +
RBAC is updated in beta and v1. Thanks for creating the includes files.

2023-03-17 21:06 UTC, InbarckMS commented on api-reference/beta/api/authenticationmethodmodedetail-get.md
Updated

2023-03-20 17:09 UTC, InbarckMS commented on api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md
We have end point for /combinationConfigurations (for example FIDO2 advanced settings) and for /combinations  (that replaces authenticationCombinations). This is combinationConfigurations

2023-03-20 17:11 UTC, InbarckMS commented on api-reference/v1.0/resources/authenticationstrengthpolicy.md
> +|[List usage](../api/authenticationstrengthpolicy-usage.md)|[authenticationStrengthUsage](../resources/authenticationstrengthusage.md)|Find all [conditionalAccessPolicies](../resources/conditionalacc
authenticationStrengthUsage is now added. Closing this comment.

2023-03-20 17:12 UTC, InbarckMS commented on api-reference/v1.0/resources/conditionalaccessgrantcontrols.md
> +| authenticationStrength | [authenticationStrengthPolicy](authenticationstrengthpolicy.md) | The authentication strength required by the conditional access policy. Optional.|
Auth strength is now updated in the CA API schema. Closing this comment.

2023-03-21 09:29 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md
Ah understood. Thanks.

2023-03-21 13:44 UTC, FaithOmbongi commented
Hi @InbarckMS - Please use the latest changelog stubs. Because the engineer added a few more changes to his schema PR, there are some missing objects that should have been generated - including the deprecation of findByMethodMode for beta.

2023-03-22 18:03 UTC, FaithOmbongi approved these changes
Hi @InbarckMS - This is good to go when the schema is live.

I've retained the changes to the snippets. The team has confirmed that they'll overwrite and replace all of them but changing it in this PR has no effect.

2023-04-06 13:25 UTC, FaithOmbongi commented
PR is on hold as we wait for the API to be deployed.

2023-04-21 01:14 UTC, merged