Adding new custom extensibility changes  with new models with a request resume action
microsoftgraph/microsoft-graph-docs pull request #20374
Opened 2023-02-26 03:52 UTC by vikama-microsoft

CSDL PR : https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/7624750

API Review PR's :
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/10817
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11936
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/12207
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/12605
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/12876

2023-02-27 01:37 UTC, vikama-microsoft commented
Service API's are not live yet , would like to get this merged as soon as the API's are live ..

2023-03-10 17:57 UTC, markwahl-msft requested changes

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-delete.md
> +2. Use the access package catalog ID and retrieve the ID of the **accessPackageCustomWorkflowExtension** object that you want to delete by running the [LIST accessPackageCustomWorkflowExtensions](acc
Do not use All caps

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-delete.md
> +|Delegated (work or school account)|EntitlementManagement.Read.All EntitlementManagement.ReadWrite.All |
I do not think EntitlementManagement.Read.All should give permissions to delete this.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-delete.md
> +|Application|EntitlementManagement.Read.All EntitlementManagement.ReadWrite.All |
I do not think EntitlementManagement.Read.All should give permissions to delete this.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-get.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
lets make the example a little less realistic

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-get.md
> +### Access package assignment request
This is confusing because the reader will think that the section heading is the data type. Could the section heading be Retrieve a custom extension for use with an access package assignment request

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-get.md
> +### Access package assignment
This is confusing because the reader will think that the section heading is the data type. Could the section heading be Retrieve a custom extension for use with an access package assignment

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-get.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/7ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
lets use less realistic samples

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accessPackagecustomworkflowextension-update.md
> +### Access package assignment request
See comments I left in get article above, those also apply in this article

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +# accessPackageAssignmentRequest: resume
Shouldn't the verb be first in the article title? Take a look at other articles about functions ...

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), when a access package policy has been enabled to call out custom extension and is excepted and the request proces
This first sentence did not parse.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +|type|String|Indicate at which stage the custom callout extension was executed.The possible values are: `microsoft.graph.accessPackageCustomExtensionStage.ssignmentRequestCreated`, `microsoft.graph.a
missing a in assignmentRequetsCreated

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +    "customExtensionStageInstanceDetail": "Protentail risk user based on the SOD check"
typo potential

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackagecatalog-list-accesspackagecustomworkflowextensions.md
> +This method supports the `$select` and `$filter` OData query parameters to help customize the response. For example, to search for access packages with a particular name, include a filter such as `$f
This example does not seem to apply to this article.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackagecatalog-post-accesspackagecustomworkflowextensions.md
> +# Create accessPackageCustomWorkflowExtensions
probably should be singular

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +### Example 4: Create a policy and specify the stages to trigger pre-defined custom workflow extensions (This property is currently in deprecation path)
let's remove the whole example then.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accessPackageAssignmentRequestWorkflowExtension.md
> +---
filename is not all lower case.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accessPackageAssignmentRequestWorkflowExtension.md
> +- When an [access package request is approved](accesspackageassignmentrequest.md)
shouldn't this one come above the previous line?

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accessPackageAssignmentRequestWorkflowExtension.md
> +|createdBy|String|Identity with UPN as display name who created the entity.|
This description doesn't parse.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accessPackageAssignmentRequestWorkflowExtension.md
> +|lastModifiedBy|String|Identity with UPN as display name who modified entity. |
See previous comment

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignmentpolicy.md
> +|customExtensionHandlers|[customExtensionHandler](../resources/customextensionhandler.md) collection| The collection of stages when to execute one or more custom access package workflow extensions. S
Check if this is the official way to say that, I'm not seen "deprecation path" before. Is it deprecated or not?

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignmentrequestcallbackdata.md
> +|customExtensionStageInstanceId|String|Unique Id of the callout to the custom extension that was nade at a stage of request processing.|
typo  made?

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignmentworkflowextension.md
> +|createdBy|String|Identity with UPN as display name who created the entity.|
See earlier comments, check with the description of createdBy on another resource like the AP itself

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignmentworkflowextension.md
> +|id|String|Identifier for the customAccessPackageWorkflowExtension object. Inherited from [entity](../resources/entity.md).|
Don't need inherited from entity

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/azureadpoptokenauthentication.md
> +|Property|Type|Description|
No properties?

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/customextensioncallbackconfiguration.md
> +|timeoutDuration|Duration|The max duration that Azure AD will wait for a resume action for the callout that was sent by Azure AD is represented in ISO 8601 format. The Valid range for entitlement man
5 minutes and 14 days does not need to be in quotes since those strings are not what is sent in the field.  Missing period from end of sentence.

2023-03-10 17:57 UTC, markwahl-msft commented on api-reference/beta/resources/customextensioncalloutinstance.md
> +Defines the custom extension callout instane record information.
typo

2023-03-10 18:16 UTC, vikama-microsoft commented on api-reference/beta/api/accessPackagecustomworkflowextension-delete.md
> +|Application|EntitlementManagement.Read.All EntitlementManagement.ReadWrite.All |
copy paste issue

2023-03-10 18:22 UTC, vikama-microsoft commented on api-reference/beta/api/accessPackagecustomworkflowextension-get.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
these random values

2023-03-10 18:23 UTC, vikama-microsoft commented on api-reference/beta/api/accessPackagecustomworkflowextension-get.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/7ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
these random values

2023-03-10 18:31 UTC, vikama-microsoft commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +# accessPackageAssignmentRequest: resume
Looked at these two examples and they are doing the similar way.
https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&tabs=http
https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0

2023-03-10 18:31 UTC, vikama-microsoft commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), when a access package policy has been enabled to call out custom extension and is excepted and the request proces
it did get parsed  and this is also same in other action docs 
![image](https://user-images.githubusercontent.com/36014352/224395961-c916db6b-1427-4c02-a53e-b010be24035a.png)

2023-03-10 19:19 UTC, vikama-microsoft commented on api-reference/beta/resources/azureadpoptokenauthentication.md
> +|Property|Type|Description|
yes no properties  for now

2023-03-13 20:07 UTC, FaithOmbongi requested changes
Hi @vikama-microsoft -

I've only left feedback for items related to the LCW schema. I'll proceed to review the rest EM-specific.

2023-03-13 20:07 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadpoptokenauthentication.md
> +  "@odata.type": "microsoft.graph.azureAdPopTokenAuthentication"
```suggestion
  "baseType": "microsoft.graph.customExtensionAuthenticationConfiguration",
  "@odata.type": "microsoft.graph.azureAdPopTokenAuthentication"
```

2023-03-13 21:11 UTC, AlexFilipin commented on api-reference/beta/resources/azureadpoptokenauthentication.md
> +Defines Proof Of Possession (PoP) token authetication model to authenticate a logic app with a [accessPackageAssignmentRequestWorkflowExtensions](../resources/accessPackageAssignmentRequestWorkflowEx
Yes this would be possible with https://learn.microsoft.com/en-us/graph/api/resources/identitygovernance-customtaskextension?view=graph-rest-beta , in contrast to EM we only have one resource derived from custom callout extension and our single resource will support both (https://learn.microsoft.com/en-us/graph/api/resources/azureadtokenauthentication?view=graph-rest-beta and PoP) in beta as https://learn.microsoft.com/en-us/graph/api/resources/customextensionauthenticationconfiguration?view=graph-rest-beta

2023-03-13 21:11 UTC, AlexFilipin commented on api-reference/beta/resources/azureadpoptokenauthentication.md
> +|:---|:---|:---|
We removed nonce , it should no longer be there

2023-03-13 21:15 UTC, FaithOmbongi requested changes
Thank you @vikama-microsoft for your work on this PR. I've left some suggestions inline plus the following:
- I don't know how soon you want to merge this PR, so I recommend that you download the docStubs folder from the schema PR. That's good insurance for you while you're still working on this docs PR.
- For resources that are shared by LCW and EM, please ensure you maintain information related to both sets of APIs.
- Update [customCalloutExtension ](https://learn.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta)  and add the two new derived types: accessPackageAssignmentWorkflowExtension and accessPackageAssignmentRequestWorkflowExtension
- I haven't reviewed any of the 5 API files that you included in the Methods table of accesspackageassignmentworkflowextension.md and accesspackageassignmentrequestworkflowextension.md because they aren't the correct files. Please fix them first.
   - Note: If the expected files aren't/weren't generated by the stub generator, please reach out internally so we discuss and investigate the correct API files.
- If any of the entities expose APIs, they should be surfaced on the TOC.

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
> +In the following example, the pre-defined **accessPackageCustomWorkflowExtension** object is triggered when an access package assigned request is created and when it's granted.  The identifier provid
```suggestion
In the following example, the pre-defined **accessPackageCustomWorkflowExtension** object is triggered when an access package assignment request is created and when it's granted.  The identifier provided within the **customExtension** field is the **accessPackageCustomWorkflowExtension** object's ID.
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-overview.md), when a access package policy has been enabled to call out custom extension and is excepted and the request proces
Hmm, this description isn't clear. Please review.

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +|type|String|Indicate at which stage the custom callout extension was executed.The possible values are: `microsoft.graph.accessPackageCustomExtensionStage.assignmentRequestCreated`, `microsoft.graph.
```suggestion
|type|String|Indicate at which stage the custom callout extension was executed. The possible values are: `microsoft.graph.accessPackageCustomExtensionStage.assignmentRequestCreated`, `microsoft.graph.accessPackageCustomExtensionStage.assignmentRequestApproved`, `microsoft.graph.accessPackageCustomExtensionStage.assignmentRequestGranted`, `microsoft.graph.accessPackageCustomExtensionStage.assignmentRequestRemoved`|
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +|data|[customExtensionData](../resources/customextensiondata.md)|[Access Package Assignment Request Callback Data](../resources/accesspackageassignmentrequestcallbackdata.md)|
```suggestion
|data|[customExtensionData](../resources/customextensiondata.md)| Contains information about the instance of the callout that was made to the customer endpoint. |
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +### Resume a request
```suggestion
### Example 1: Resume an access package assignment request

#### Request
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +### Response
```suggestion
#### Response
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +### Deny an access package assignment request
```suggestion
### Example 2: Deny an access package assignment request

#### Request
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-resume.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestcallbackdata.md
> +description: "Access package assignment request workflow calllback back that custom extension endpoint callback, derived from [customextensiondata](../resources/customextensiondata.md)"
```suggestion
description: "Data for an access package assignment request workflow callback."
```

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestcallbackdata.md
> +Access package assignment request workflow calllback back that custom extension endpoint callback, derived from [customextensiondata](../resources/customextensiondata.md)
Match Line 3

2023-03-13 21:15 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestcallbackdata.md
> +|state|String|Allow extension to be able to deny or cancel the request submitted by the requestor. Supported values: `Denied`, `Canceled`. This property can only be set for `assignmentRequestCreated`
```suggestion
|customExtensionStageInstanceId|String|Unique identifier of the callout to the custom extension.|
|customExtensionStageInstanceDetail|String|Details for the callback.|
|stage|accessPackageCustomExtensionStage|Indicates the stage at which the custom callout extension will be executed. The possible values are: `assignmentRequestCreated`, `assignmentRequestApproved`, `assignmentRequestGranted`, `assignmentRequestRemoved`, `assignmentFourteenDaysBeforeExpiration`, `assignmentOneDayBeforeExpiration`, `unknownFutureValue`.|
|state|String|Allow the extension to be able to deny or cancel the request submitted by the requestor. The supported values are `Denied` and `Canceled`. This property can only be set for an `assignmentRequestCreated` stage.|
```

2023-03-13 21:15 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +      "SubArea": "Identity governance"
```suggestion
      "SubArea": "Governance"
```

2023-03-15 17:19 UTC, vikama-microsoft commented on api-reference/beta/api/accesspackagecatalog-list-accesspackagecustomworkflowextensions.md
> +
Add missing portions for list sections

2023-03-16 17:21 UTC, vikama-microsoft commented
> Thank you @vikama-microsoft for addressing the initial feedback. Your PR has all the files it needs, most feedback in this round is clean up. But take note of the following:
> 
> * GLOBAL: For all example responses, replace the autogenerated boilerplate with real examples.
   
> * Update [customCalloutExtension](https://review.learn.microsoft.com/en-us/graph/api/resources/customCalloutExtension?view=graph-rest-beta&branch=pr-en-us-20374) by adding the two new derived types **accessPackageAssignmentRequestWorkflowExtension** and **accessPackageAssignmentWorkflowExtension** in the list.
>   
>   * Q: Who owns customAuthenticationExtension? I see the derived type is also in the schema but has never been documented.
> * Suggestion: Because accesspackagecatalog-list-accesspackagecustomworkflowextensions.md returns objects that can be one of two types, I suggest you add an Example 2 that shows filter by one of the derived types - if that's supported.
> * Comment about accesspackageassignmentrequestcallbackdata > stage property: I notice in your examples that you use PascalCase for the possible values (e.g. AssignmentRequestCreated) while the schema defines them in camelCase (e.g. assignmentRequestCreated). I should point out that we've had a few historical customer issues relating to the case-sensitivity of a number of enums in EM. So, I strongly advise that these values not be case-sensitive if this hasn't been handled yet.

2023-03-16 17:33 UTC, vikama-microsoft commented on api-reference/beta/api/accesspackagecatalog-list-accesspackagecustomworkflowextensions.md
> +```
not supported at this time and I would update when supported

2023-03-16 19:33 UTC, FaithOmbongi requested changes
Hi @vikama-microsoft -

A few pre-approval comments like cleaning up internal URLs.

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequestworkflowextension-get.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
GLOBAL: Clean up internal URLs from public docs
```suggestion
       "url":"https://portal.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequestworkflowextension-update.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```suggestion
         "url":"https://portal.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentworkflowextension-get.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/7ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```suggestion
         "url":"https://portal.azure.com:443/workflows/7ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentworkflowextension-update.md
> +         "url":"https://prod-31.eastus.logic.azure.com:443/workflows/7ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```suggestion
         "url":"https://portal.azure.com:443/workflows/7ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-list-accesspackagecustomworkflowextensions.md
> +            "url":"https://prod-31.eastus.logic.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```suggestion
            "url":"https://portal.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-list-accesspackagecustomworkflowextensions.md
> +            "url":"https://prod-31.eastus.logic.azure.com:443/workflows/9ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```suggestion
            "url":"https://portal.azure.com:443/workflows/9ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-post-accesspackagecustomworkflowextensions.md
> +### Response
```suggestion
#### Response
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-post-accesspackagecustomworkflowextensions.md
> +
#### Request

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-post-accesspackagecustomworkflowextensions.md
> +### Response
```suggestion
#### Response
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-post-accesspackagecustomworkflowextensions.md
> +
```suggestion
#### Request
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignment.md
Add customExtensionCalloutInstances property in the JSON representation section as well.

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackagecatalog.md
> +|accessPackageCustomWorkflowExtensions|[customCalloutExtension](../resources/customcalloutextension.md) collection|The attributes of a logic app, which can be called at various stages of an access pa
nit: alphabetical order

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/resources/customcalloutextension.md
> +- [accesspackageassignmentworkflowextension](../resources/accesspackageassignmentworkflowextension.md)
nit: same casing as the schema
```suggestion
- [accessPackageAssignmentRequestWorkflowExtension](accesspackageassignmentrequestworkflowextension.md)
- [accessPackageAssignmentWorkflowExtension](../resources/accesspackageassignmentworkflowextension.md)
```

2023-03-16 19:33 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentpolicy-get.md
> +                    "url": "https://prod-31.eastus.logic.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```suggestion
                    "url": "https://portal.azure.com:443/workflows/8ccffea766ae48e680gd9a22d1549bbc/triggers/manual/paths/invoke?api-version=2016-10-01"
```

2023-03-18 01:30 UTC, merged