Auth method policy v1.0 updates
microsoftgraph/microsoft-graph-docs pull request #20437
Opened 2023-03-02 23:04 UTC by jpettere

2023-03-08 16:14 UTC, FaithOmbongi requested changes
Thank you @jpettere for your work on this PR. I've left a few suggestions inline, mostly clean ups. 

Also:
- reconfirmationInDays is still in beta. And is also part of the v1.0 schema PR. Please confirm why we're deleting it from the beta doc?
- Please reassign all necessary docs from Michael to yourself.
- Update the Overview (authenticationmethodspolicies-overview.md)

2023-03-08 16:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/voiceauthenticationmethodconfiguration-delete.md
> +|Application|**TODO: Provide applicable permissions.**|
Missing Graph permissions + RBAC after the table.

2023-03-08 16:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/voiceauthenticationmethodconfiguration-delete.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2023-03-08 16:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/voiceauthenticationmethodconfiguration-update.md
> +For the list of properties, see [voiceAuthenticationMethodConfiguration](../resources/softwareoathauthenticationmethodconfiguration.md).
Replace with the include file, then the table with updatable properties only.

2023-03-08 16:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/voiceauthenticationmethodconfiguration-update.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2023-03-13 18:14 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
> -|reconfirmationInDays|Int32|Days before the user will be asked to reconfirm their method. |
The property isn't used nor is it returned by any API calls so we're going to remove it. Sherry will be doing the work to remove it from the schema.

https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2458134

2023-03-13 20:07 UTC, jpettere commented on api-reference/beta/resources/voiceauthenticationmethodconfiguration.md
> -Inherits from [authenticationMethodConfiguration](../resources/authenticationmethodconfiguration.md).
Added back into all resource configuration files.

2023-03-13 20:07 UTC, jpettere commented on api-reference/v1.0/api/voiceauthenticationmethodconfiguration-delete.md
> +|Application|**TODO: Provide applicable permissions.**|
Added.

2023-03-13 21:11 UTC, jpettere commented on api-reference/v1.0/api/voiceauthenticationmethodconfiguration-update.md
> +For the list of properties, see [voiceAuthenticationMethodConfiguration](../resources/softwareoathauthenticationmethodconfiguration.md).
Addressed. Please review though.

2023-03-13 22:12 UTC, jpettere commented on api-reference/beta/resources/authenticationmethodspolicy.md
> -|reconfirmationInDays|Int32|Days before the user will be asked to reconfirm their method. |
We thought it wasn't used / returned but looks like it is possible to patch. Sherry and I are following up with Dan about this offline. Will leave in the docs for now.

2023-03-17 14:40 UTC, FaithOmbongi approved these changes
Thank you @jpettere for addressing the review feedback. I've left suggestions for three fixes. Please address them before setting this PR for ready to merge.

Approved with comments.

2023-03-17 14:40 UTC, FaithOmbongi commented on api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md
> -[!INCLUDE [table-intro](../../includes/update-property-table-intro.md)]
Oops - I accidentally left a delete suggestion for the include statement. My apologies. 
Keep the include statement; Delete the next statement because it's already in the include file.

2023-03-21 04:06 UTC, merged