Assignment and submission state transition
microsoftgraph/microsoft-graph-docs pull request #20438
Opened 2023-03-02 23:11 UTC by AshwaniBansal1

Assignment and submission state transition [USER STORY 162332](https://1edu.visualstudio.com/Homeroom/_workitems/edit/162332)

2023-05-08 23:16 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +Assignments and submissions are an important part in the interaction between teachers and students' actions. This article describes the changes in the assignment and submission states during the proc
done

2023-05-08 23:16 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +An assignment represents a task or unit of work assigned to a student or team members in a class as part of their study. Only teachers or team owners can create, copy, or schedule assignments. These
done

2023-05-08 23:17 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +| Scheduled | Status when the teacher scheduled the assignment to publish in a future time. | `PATCH /education/classes/{id}/assignments/{id}`<br/>`POST /education/classes/{id}/assignments/{id}/publi
done

2023-05-08 23:20 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +| Pending | Background processing status when a new assignment is being copied from an existing one. | `POST /education/classes/{id}/assignments/{id}/copy`<br/>`PATCH /education/classes/{id}/assignme
I rencently got feedback from Chenrui to remove "copy" endpoint only, let me double check and will remove if needed.

2023-05-08 23:39 UTC, cristobal-buenrostro commented on concepts/assignments-submissions-states-transition.md
> +## Get all the assignmets and their corresponding submission belonging to the student
good catch, thank you

2023-05-08 23:39 UTC, cristobal-buenrostro commented on concepts/assignments-submissions-states-transition.md
> +## Get all the assignmets for teacher and then submissions for each assignment
done

2023-05-08 23:50 UTC, cristobal-buenrostro commented on concepts/assignments-submissions-states-transition.md
> +# State transiton for Student and Teacher role
makes sense

2023-05-09 16:50 UTC, richardle798 requested changes

2023-05-09 16:50 UTC, richardle798 commented on concepts/assignments-states-transition.md
> +Assignments and submissions are an important part of the interaction between teachers and students' actions. This article describes the changes in the assignment and submission states during the proc
Remove part saying that this article talks about submission states

2023-05-09 16:50 UTC, richardle798 commented on concepts/assignments-states-transition.md
> +| Assigned | After finishing the publish, the assignment is moved to Assigned state and is available for the students, or the assignment is active again. | `POST /education/classes/{id}/assignments/{
*After publish has finished

2023-05-09 16:50 UTC, richardle798 commented on concepts/assignments-submissions-states-transition.md
> +Then, for each of the assignments use `classses/id/assignments/id/submissions` to get the submission status (one assignment will contain n number of submissions, where n is the class size) .
Not necessarily.  A teacher could create an assignment for a subset or students or groups of students

2023-05-09 21:55 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +Assignments and submissions are an important part of the interaction between teachers and students' actions. This article describes the changes in the assignment and submission states during the proc
done

2023-05-09 21:55 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +| Assigned | After finishing the publish, the assignment is moved to Assigned state and is available for the students, or the assignment is active again. | `POST /education/classes/{id}/assignments/{
done

2023-05-09 22:03 UTC, cristobal-buenrostro commented on concepts/assignments-submissions-states-transition.md
> +Then, for each of the assignments use `classses/id/assignments/id/submissions` to get the submission status (one assignment will contain n number of submissions, where n is the class size) .
makes sense

2023-05-15 21:12 UTC, sharad-sharma-msft requested changes

2023-05-15 21:12 UTC, sharad-sharma-msft commented on concepts/assignments-states-transition.md
> +Assignments and submissions are an important part of the interaction between teachers and students' actions. This article describes the changes in the assignment states during the process flow and wh
Assignments and submissions ->  assignments

2023-05-15 21:12 UTC, sharad-sharma-msft commented on concepts/assignments-states-transition.md
> +| API | Sync or async | Mechanism to get latest state |
instead of saying Sync or async, shall we say it involves Backend job or not?

2023-05-15 21:12 UTC, sharad-sharma-msft commented on concepts/assignments-states-transition.md
> +* The maximum size allowed for resources is 50 MB overall or 10 resources.
are these current limits? check with Leif.

2023-05-15 22:46 UTC, richardle798 commented on concepts/assignments-states-transition.md
> +| API | Sync or async | Mechanism to get latest state |
That's an implementation detail that doesn't make sense to surface to the graph consumer IMO

2023-05-15 22:47 UTC, richardle798 commented on concepts/submissions-states-transition.md
> +Assignments and submissions are an important part in the interaction between teachers and students' actions. This article describes the changes in the submission states during the process flow and wh
If you're going to change above from "assignments and submissions" => assignments, this should be changed to submissions as well

2023-05-18 19:41 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +Assignments and submissions are an important part of the interaction between teachers and students' actions. This article describes the changes in the assignment states during the process flow and wh
done

2023-05-18 19:42 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +| API | Sync or async | Mechanism to get latest state |
agree with Richard on this. Keeping as sync/async

2023-05-18 19:43 UTC, cristobal-buenrostro commented on concepts/submissions-states-transition.md
> +Assignments and submissions are an important part in the interaction between teachers and students' actions. This article describes the changes in the submission states during the process flow and wh
got it, done

2023-05-18 19:48 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationclass-post-assignment.md
> +* [State transiton for Student and Teacher role](/graph/assignments-submissions-states-transition)
I'm keeping the original link preferably

2023-05-23 22:30 UTC, cristobal-buenrostro commented on concepts/assignments-states-transition.md
> +* The maximum size allowed for resources is 50 MB overall or 10 resources.
updated

2023-05-23 22:37 UTC, richardle798 approved these changes

2023-05-25 19:02 UTC, sharad-sharma-msft approved these changes

2023-05-26 20:42 UTC, dodaromike approved these changes

2023-05-26 20:43 UTC, dodaromike commented
Only small changes to sentence structure in this one.  Back to you @Danielabom

2023-06-01 18:15 UTC, Danielabom commented on concepts/assignments-states-transition.md
> +| Assigned | After publish has finished, the assignment is moved to Assigned state and is available for the students, or the assignment is active again. | `POST /education/classes/{id}/assignments/{i
```suggestion
| Assigned | After publishing has finished, the assignment is moved to an Assigned state and is available for the students, or the assignment is active again. | `POST /education/classes/{id}/assignments/{id}/publish`<br/>`POST /education/classes/{id}/assignments/{id}/activate` | Submissions |
```

2023-06-01 19:05 UTC, Danielabom commented on concepts/assignments-states-transition.md
> +Synchronous operations are performed one at a time, and only after one operation is completed can the following operation start. The result is not returned until the last operation is completed. With
Synchronous operations are executed one at the time. Each operation must be completed before the next one can begin, and the final result is only returned once all operations have finished.
Asynchronous operations allow multiple tasks to run concurrently. While one operation is in progress, another operation can start before the previous one is finished. Asynchronous operations typically involve background activities, and the caller needs to actively check for the result by polling or monitoring until it becomes available.

2023-06-01 19:06 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +description: "Learn about on how to get the assignments and related submissions for Teachers and Students with state transition rules."
```suggestion
description: "Learn about how to get the assignments and related submissions for Teachers and Students with state transition rules."
```

2023-06-01 19:07 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +This article describes student and teacher roles for the assignment and submission state transition and related transition rules.
```suggestion
This article describes student and teacher roles for the assignment, submission state transition, and related transition rules.
```

2023-06-01 20:41 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +## Get all the assignments and their corresponding submissions belonging to the student
```suggestion
## Get all the assignments and their respective submissions that belong to a specific student
```

2023-06-01 20:51 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +Use the following call for the student action:
Make the following request to get the student's action:

2023-06-01 20:51 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +Use the following call for the student action:
```suggestion
Make the following request to get the student's action:
```

2023-06-01 20:53 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +Code sample for student account with [Education assignment using Microsoft Graph SDK](https://github.com/microsoft/edu-assignments-graph-sdk/blob/main/samples/csharp/MicrosoftEduGraphSamples/Workflow
```suggestion
Code sample for students' account with [Education assignment using Microsoft Graph SDK](https://github.com/microsoft/edu-assignments-graph-sdk/blob/main/samples/csharp/MicrosoftEduGraphSamples/Workflows/AssignmentWorkflow.cs#L62)
```

2023-06-01 21:09 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +> For student account isTeacher parameter needs to be set to false.
```suggestion
> For student accounts, the isTeacher parameter needs to be set to false.
```

2023-06-01 21:33 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +Use the following call for the teacher action:
```suggestion
Make the following request to get the teacher's actions:
```

2023-06-01 21:38 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +Then, for each of the assignments use `classses/id/assignments/id/submissions` to get submissions status (one assignment will contain n number of submissions, where n is the number of students. It ca
```suggestion
Then, for each of the assignments, use `classses/id/assignments/id/submissions` to get the submissions status (one assignment will contain n number of submissions, where n is the number of students. It can be a single student, a group of students or the entire class).
```

2023-06-01 21:39 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +Code sample for student account with [Education assignment using Microsoft Graph SDK](https://github.com/microsoft/edu-assignments-graph-sdk/blob/main/samples/csharp/MicrosoftEduGraphSamples/Workflow
```suggestion
See a code sample for a student account with [Education assignment using Microsoft Graph SDK](https://github.com/microsoft/edu-assignments-graph-sdk/blob/main/samples/csharp/MicrosoftEduGraphSamples/Workflows/AssignmentWorkflow.cs#L62)
```

2023-06-01 21:40 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +See the the code sample for a teacher account with [Education assignment using Microsoft Graph SDK](https://github.com/microsoft/edu-assignments-graph-sdk/blob/main/samples/csharp/MicrosoftEduGraphSa
```suggestion
See the code sample for a teacher account with [Education assignment using Microsoft Graph SDK](https://github.com/microsoft/edu-assignments-graph-sdk/blob/main/samples/csharp/MicrosoftEduGraphSamples/Workflows/AssignmentWorkflow.cs#L62).
```

2023-06-01 21:41 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +The following state transition rules are applicable for both student and teacher:
```suggestion
The following state transition rules are applicable for both student and teacher roles: 
```

2023-06-01 21:42 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +For a student, an assignment is actionable if the corresponding submission is in *Working*, *Returned* or *Reassigned* state. For a teacher, an assignment is actionable if any of the submissions of t
```suggestion
For a student, an assignment is actionable if the corresponding submission is in a *working*, *returned* or *reassigned* state. For a teacher, an assignment is actionable if any of the submissions of that assignment are in a *Submitted* state.
```

2023-06-01 21:43 UTC, Danielabom commented on concepts/assignments-submissions-states-transition.md
> +* The *Return for Revision* action makes the submission state as *reassigned*.
```suggestion
* The *return for revision* action makes the submission state as *reassigned*.
```

2023-06-01 21:51 UTC, Danielabom commented on concepts/assignments-states-transition.md
> +The following limits apply to all API calls:
```suggestion
The following limits apply to all API requests:
```

2023-06-01 21:59 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +description: "Learn about the changes in the submission states during the process flow and which education APIs in Microsoft Graph are involved."
```suggestion
description: "Learn about the changes in the submission states during the process flow and which education APIs in Microsoft Graph are involved."
```
```suggestion
description: "Learn about the transitions that occur in the submission states throughout the process flow and which education APIs in Microsoft Graph are involved."
```

2023-06-01 22:00 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +Submissions are an important part in the interaction between teachers' and students' actions. This article describes the changes in the submission states during the process flow and which education A
```suggestion
Submissions are an important part in the interaction between teachers' and students' actions. about the changes in the submission states during the process flow and which education APIs in Microsoft Graph are involved.
```

2023-06-01 22:01 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +The status is a read-only property in the submission.  Status changes based on the actions of students and teachers.
```suggestion
The status is a read-only property in the submission. It changes based on the actions of students and teachers.
```

2023-06-01 22:02 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +| Submitted	| State after student turns in the assignment. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/submit` |
```suggestion
| Submitted	| State after the student turns in the assignment. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/submit` |
```

2023-06-01 22:02 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +| Submitted	| State after student turns in the assignment. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/submit` |
```suggestion
| Submitted	| The state after the student turns in the assignment. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/submit` |
```

2023-06-01 22:03 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +| Returned | State after the teacher has returned an assignment back to the student. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/return` |
```suggestion
| Returned | The state after the teacher has returned an assignment to the student. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/return` |
```

2023-06-01 22:03 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +| Reassigned | State after the teacher has returned the assignment  to the student for revision. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/reassign` |
```suggestion
| Reassigned | The state after the teacher has returned the assignment to the student for revision. | `POST /education/classes/{id}/assignments/{id}/submissions/{id}/reassign` |
```

2023-06-01 22:06 UTC, Danielabom commented on concepts/submissions-states-transition.md
> +In this case, all the calls are asynchronous, which means that the operation starts and another operation can start before the first one finishes. The asynchronous operation performs some background
```suggestion
In this case, all the calls are asynchronous, which means the operation starts, and another operation can begin before the first one finishes. The asynchronous operation performs some background activity, and the caller must be polling to get the result.  
```

2023-06-01 22:07 UTC, Danielabom commented on concepts/toc.yml
> +              - name: Assignment states transition
```suggestion
              - name: Assignment states transitions
```

2023-06-01 22:12 UTC, Danielabom approved these changes
Applied multiple edits to this PR. Approved.

2023-06-02 04:55 UTC, merged