Promote FileServices > Tenant Settings API from beta to v1.0
microsoftgraph/microsoft-graph-docs pull request #20488
Opened 2023-03-07 19:15 UTC by liamfernandez

We are ready to promote the SharePoint Tenant Admin Settings API from beta to v1.0. As such we need to remove '(preview)' tags from beta doc pages and add the doc pages to the v1.0 directory.

2023-03-07 19:16 UTC, liamfernandez commented
Still need to generate and add Changelog

2023-03-21 16:18 UTC, Danielabom commented on api-reference/v1.0/resources/tenantadmin-settings.md
> +| isLoopEnabled                                      | Boolean                      | Indicates whetherif Fluid Framework is allowed on SharePoint sites.
```suggestion
| isLoopEnabled                                      | Boolean                      | Indicates whether if Fluid Framework is allowed on SharePoint sites.                                                                                                                                            |
```

2023-03-21 16:41 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Target": "admin"
I do not see a file with this addition. Please verify.

2023-03-21 16:44 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [sharepoint](https://learn.microsoft.com/en-us/graph/api/resources/tenantadmin-sharepoint?view=graph-rest-1.0) resource type.",
I do not see a file for the resource "sharepoint" in this PR. Please verify.

2023-03-21 17:33 UTC, Danielabom submitted a review, later dismissed
Hi @liamfernandez, thank you for working on this PR. I could not find a couple of items mentioned on the changelog. Please take a look at my comments. I appreciate it.

2023-03-21 19:18 UTC, Danielabom commented on api-reference/v1.0/resources/tenantadmin-settings.md
> +| imageTaggingOption                                 | [tenantAdmin.imageTaggingChoice](../resources/tenantadmin-settings.md#imagetaggingchoice-values) | Specifies the image tagging option for the te
Global comment (applies to all the properties which have enums as return types, and this might require an update on the beta resource file: 
The following link takes you to our Evolvable Enums wiki, please see Step 3 as you need to add a clarification: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-3%3A-add-clarification-if-one-or-more-members-follow-unknownfuturevalue )

2023-03-28 19:52 UTC, Mengke-Gh approved these changes

2023-03-28 19:58 UTC, Mengke-Gh approved these changes

2023-04-04 23:14 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Id": "5348d8d7-63da-44f6-a85b-96fe17fe342f",
Based on the updates of the PR, it seems that the admin resource already exists in v1.

2023-04-04 23:17 UTC, Danielabom commented on api-reference/v1.0/resources/sharepointSettings.md
> +### imageTaggingChoice values
Please look at step 2 on this wiki to make a clarification about evolvable enum values: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

2023-04-04 23:19 UTC, Danielabom requested changes
@Mengke-Gh, thank you for working on this PR. I appreciate your efforts. Just take a look at my final comments.

2023-04-22 10:03 UTC, Mengke-Gh commented on api-reference/v1.0/resources/sharepointSettings.md
> +### imageTaggingChoice values
> Please look at step 2 on this wiki to make a clarification about evolvable enum values: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

Thanks Daniel. I've checked the wiki and these enum values are not newly evolved values.

2023-04-26 22:42 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [admin](https://learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-1.0) resource",
Based on the updates of the PR, it seems that the admin resource already exists in v1.

2023-04-28 01:07 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [admin](https://learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-1.0) resource",
```suggestion
          "Description": "Added the [sharepointSettings](https://learn.microsoft.com/en-us/graph/api/resources/sharepointSettings?view=graph-rest-1.0) resource",
```

2023-04-28 01:48 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the **sharepointSettings** navigation property to the [admin](https://learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-1.0)  resource",
```suggestion
          "Description": "Added the **sharepointSettings** navigation property to the [admin](https://learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-1.0) resource",
```

2023-05-02 19:31 UTC, Mengke-Gh approved these changes

2023-05-02 21:13 UTC, Mengke-Gh commented
Hello,
LiamFernadez left Microsoft. I am working on this change now. Below is my reply


@microsoft-github-policy-service agree company="Microsoft"

Thanks,
Mengke
SharePoint Admin Platform wiki: https://aka.ms/spacwiki
Tenant Admin team site: https://microsoft.sharepoint.com/teams/TenantAdminVnext

From: microsoft-github-policy-service[bot] ***@***.***>
Sent: Tuesday, May 2, 2023 1:59 PM
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Mengke Li ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoftgraph/microsoft-graph-docs] Promote FileServices > Tenant Settings API from beta to v1.0 (PR #20488)


@liamfernandez<https://github.com/liamfernandez> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree [company="{your company}"]

Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree

  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term "You" includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"
Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement ("Agreement") is agreed to by the party signing below ("You"),
and conveys certain license rights to Microsoft Corporation and its affiliates ("Microsoft") for Your
contributions to Microsoft open source projects. This Agreement is effective as of the latest signature
date below.

  1.  Definitions.
"Code" means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to Microsoft under this Agreement.
"Project" means any of the projects owned or managed by Microsoft and offered under a license
approved by the Open Source Initiative (www.opensource.org<http://www.opensource.org/>).
"Submit" is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as "Not a Submission."
"Submission" means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.
  2.  Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.
  3.  Originality of Work. You represent that each of Your Submissions is entirely Your original work.
Should You wish to Submit materials that are not Your original work, You may Submit them separately
to the Project if You (a) retain all copyright and license information that was in the materials as You
received them, (b) in the description accompanying Your Submission, include the phrase "Submission
containing materials of a third party:" followed by the names of the third party and any licenses or other
restrictions of which You are aware, and (c) follow any other instructions in the Project's written
guidelines concerning Submissions.
  4.  Your Employer. References to "employer" in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term "You" in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.
  5.  Licenses.

  *   Copyright License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
parties.
  *   Patent License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.
  *   Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

  1.  Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
  2.  Notice to Microsoft. You agree to notify Microsoft in writing of any facts or circumstances of which
You later become aware that would make Your representations in this Agreement inaccurate in any
respect.
  3.  Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.
  4.  Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
defenses of lack of personal jurisdiction and forum non-conveniens.
  5.  Entire Agreement/Assignment. This Agreement is the entire agreement between the parties, and
supersedes any and all prior agreements, understandings or communications, written or ora [...]

2023-05-02 21:32 UTC, Danielabom commented on api-reference/v1.0/resources/sharepointsettings.md
> +# settings resource type
```suggestion
# Sharepointsettings resource type
```

2023-05-02 21:40 UTC, Danielabom commented on api-reference/beta/toc.yml
>            - name: Settings
```suggestion
          - name: Sharepoint Settings
```

2023-05-02 21:45 UTC, Danielabom commented on api-reference/beta/resources/sharepointsettings.md
> +# sharepointSettings resource type
```suggestion
# SharepointSettings resource type
```

2023-05-02 21:47 UTC, Danielabom commented on api-reference/beta/toc.yml
>            - name: Get settings
```suggestion
          - name: Get Sharepoint settings
```

2023-05-02 21:47 UTC, Danielabom commented on api-reference/beta/toc.yml
>            - name: Update settings
```suggestion
          - name: Update Sharepoint settings
```

2023-05-02 21:48 UTC, Danielabom commented on api-reference/v1.0/toc.yml
> +          - name: Get settings
```suggestion
          - name: Get Sharepoint settings
```

2023-05-02 21:48 UTC, Danielabom commented on api-reference/v1.0/toc.yml
> +          - name: Update settings
```suggestion
          - name: Update Sharepoint settings
```

2023-05-03 02:56 UTC, merged