Add user, group and contact service provisioning errors.
microsoftgraph/microsoft-graph-docs pull request #20490
Opened 2023-03-07 19:38 UTC by PaulEkirapa

2023-04-05 08:34 UTC, FaithOmbongi commented
Hi @PaulEkirapa - Please create a PR review request here https://aka.ms/msgraph-identity-workitem and include in it the links to the API.md and schema PR.

2023-04-11 07:08 UTC, millicentachieng requested changes

2023-04-11 07:08 UTC, millicentachieng commented on api-reference/beta/resources/serviceprovisioningerror.md
> +
Add resource metadata here, as in the screenshot below:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/25274795/231082951-be2e3a86-4ef7-456a-a967-1180eeb2dac4.png">

2023-04-25 16:58 UTC, msewaweru requested changes
@PaulEkirapa - Great work on the PR. I have left a few comments for you to action. Thanks.

2023-04-25 16:58 UTC, msewaweru commented on api-reference/beta/resources/serviceprovisioningerror.md
> +| errorDetail     | String         | Error Information published by the Federated Service as an xml string .                              |
This property is shown to belong to serviceProvisionXmlError resource and not this one. And serviceProvisioningError does not inherit from serviceProvisionXmlError. Please confirm the same on the schema.

2023-04-25 16:58 UTC, msewaweru commented on api-reference/beta/resources/serviceprovisioningerror.md
> +  "errorDetail": "<a/>",
Confirm as per my previous comment.

2023-04-25 16:58 UTC, msewaweru commented on api-reference/beta/resources/orgcontact.md
> +| serviceProvisioningErrors | [serviceProvisioningError](serviceprovisioningerror.md) collection | Errors published by a federated service describing a non-transient, service-specific error regarding
Please check if the description should go hand in hand with the resource we are adding the property to.
```suggestion
| serviceProvisioningErrors | [serviceProvisioningError](serviceprovisioningerror.md) collection | Errors published by a federated service describing a non-transient, service-specific error regarding the properties or link from an orgContact object . <br> Supports `$filter` (`eq`, `not`, for isResolved and serviceInstance).|
```

2023-04-25 16:58 UTC, msewaweru commented on api-reference/beta/resources/group.md
> +| serviceProvisioningErrors   | [serviceProvisioningError](serviceprovisioningerror.md) collection | Errors published by a federated service describing a non-transient, service-specific error regardi
Please check this as per my previous comment.
```suggestion
| serviceProvisioningErrors   | [serviceProvisioningError](serviceprovisioningerror.md) collection | Errors published by a federated service describing a non-transient, service-specific error regarding the properties or link from a group object . <br><br> Supports `$filter` (`eq`, `not`, for isResolved and serviceInstance).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
```

2023-04-27 13:13 UTC, PaulEkirapa commented on api-reference/beta/resources/serviceprovisioningerror.md
> +| errorDetail     | String         | Error Information published by the Federated Service as an xml string .                              |
I have removed the property and added serviceProvisionXmlError that inherits from serviceProvisionXmlError.

2023-04-27 13:13 UTC, PaulEkirapa commented on api-reference/beta/resources/serviceprovisioningerror.md
> +  "errorDetail": "<a/>",
Removed the property from this resource.

2023-04-27 13:14 UTC, PaulEkirapa commented on api-reference/beta/resources/group.md
> +| serviceProvisioningErrors   | [serviceProvisioningError](serviceprovisioningerror.md) collection | Errors published by a federated service describing a non-transient, service-specific error regardi
Updated.

2023-05-03 14:54 UTC, msewaweru commented on api-reference/beta/resources/orgcontact.md
> +  "serviceProvisioningErrors": [{"@odata.type": "microsoft.graph.serviceProvisioningXmlError"}],
The return type for this property should be serviceProvisioningError as per the schema.
```suggestion
  "serviceProvisioningErrors": [{"@odata.type": "microsoft.graph.serviceProvisioningError"}],
```

2023-05-03 15:41 UTC, PaulEkirapa commented on api-reference/beta/resources/orgcontact.md
> +  "serviceProvisioningErrors": [{"@odata.type": "microsoft.graph.serviceProvisioningXmlError"}],
@msewaweru we expect serviceProvisioningXmlError to be the return type here since serviceProvisioningError is an abstract model and the API returns a derived type of serviceProvisioningXmlError  by default.

2023-05-03 15:51 UTC, msewaweru approved these changes
@PaulEkirapa - thanks for your work on the PR. LGTM!

2023-05-04 03:38 UTC, Lauragra commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +### Example 1: Retry group serviceProvisioning with groupId
We generally don't have an H3 with a numbered example unless we include multiple examples in a topic. Did you intent to add another example? If not, then we can remove this H3.

2023-05-04 03:38 UTC, Lauragra commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +#### Request
If you remove the Example 1 H3 heading, make this an H3 instead of an H4. Also, it's standard to separate the request and response, so add another H3/H4 heading called Response, where you show the response example.

2023-05-04 03:39 UTC, Lauragra commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +```http
Please add the HTML comment to ignore the HTTP syntax.

2023-05-04 03:39 UTC, Lauragra commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +
Please add the comments for API Doctor to validate the request and response example.

2023-05-04 03:41 UTC, Lauragra commented on api-reference/beta/api/orgcontact-retryserviceprovisioning.md
> +### Example 1: Retry orgContact serviceProvisioning with orgContactId
Global: Please apply the same fixes to the Examples sections that I commented on in the previous topic.

2023-05-04 03:41 UTC, Lauragra commented on api-reference/beta/api/orgcontact-retryserviceprovisioning.md
> +Retries [orgContact](../resources/orgContact.md) service provisioning.
Global: Use a second person singular verb form for method topics, so this would be "Retry the... ".

2023-05-04 03:42 UTC, Lauragra commented on api-reference/beta/resources/serviceprovisioningxmlerror.md
> +Here is a JSON representation of the resource.
The standard boilerplate text for this section is "The following is a JSON representation of the resource."

2023-05-04 13:40 UTC, PaulEkirapa commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +### Example 1: Retry group serviceProvisioning with groupId
Updated.

2023-05-04 13:40 UTC, PaulEkirapa commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +#### Request
Updated.

2023-05-04 13:40 UTC, PaulEkirapa commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +```http
Added.

2023-05-04 13:41 UTC, PaulEkirapa commented on api-reference/beta/api/group-retryserviceprovisioning.md
> +
Added.

2023-05-04 13:41 UTC, PaulEkirapa commented on api-reference/beta/api/orgcontact-retryserviceprovisioning.md
> +### Example 1: Retry orgContact serviceProvisioning with orgContactId
Updated.

2023-05-04 13:41 UTC, PaulEkirapa commented on api-reference/beta/api/orgcontact-retryserviceprovisioning.md
> +Retries [orgContact](../resources/orgContact.md) service provisioning.
Updated.

2023-05-04 13:41 UTC, PaulEkirapa commented on api-reference/beta/resources/serviceprovisioningxmlerror.md
> +Here is a JSON representation of the resource.
Updated.

2023-05-12 01:54 UTC, merged