[CloudPC] Add powerState in CloudPC entity
microsoftgraph/microsoft-graph-docs pull request #20511
Opened 2023-03-09 04:01 UTC by SleepIsImportant

2023-03-09 09:36 UTC, AshleyYangSZ requested changes

2023-03-09 09:36 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpc.md
> +|powerState|[cloudPcPowerState](#cloudpcpowerstate-values)|The Power State of the Cloud PC. Possible values include running, poweredOff. This is only supported for Cloud PCs with the provisioningType
This is only supported for shift work CloudPCs.

2023-03-10 02:20 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPCPowerState",
```suggestion
                    "ChangedApiName": "cloudPcPowerState",
```

2023-04-06 08:18 UTC, SleepIsImportant commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPCPowerState",
Fixed thaks

2023-05-06 05:15 UTC, SleepIsImportant reviewed
fixed

2023-05-24 18:02 UTC, Danielabom commented
Contacted author to get info.

2023-05-24 18:05 UTC, Danielabom commented
Contacted author to get info.

2023-05-25 17:11 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|powerState|[cloudPcPowerStatus](#cloudpcpowerstatus-values)|The Power State of the Cloud PC. Possible values include `running`, `poweredOff`, `deallocated`, `hibernated`, `unknown`. This is only sup
```suggestion
|powerState|[cloudPcPowerStatus](#cloudpcpowerstatus-values)|The power state of a Cloud PC. The possible values are: `running`, `poweredOff`, `deallocated`, `hibernated`, `unknown`. This property only supports shift work CloudPCs.|
```

2023-05-25 17:19 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|hibernated|The Cloud PCstatus is hibernated.|
The members "deallocated" and "hibernated" are not mentioned in the CSDL or the api.md files. Please confirm if these are valid members.

2023-05-25 17:20 UTC, Danielabom requested changes
Thank you for working on this PR @SleepIsImportant. Please review my comments.

2023-06-26 05:05 UTC, SleepIsImportant commented
> Thank you for working on this PR @SleepIsImportant. Please review my comments.

@Danielabom Seems i've resolved all comments, could you pls kindly help check it again

2023-06-28 01:56 UTC, merged