Public Preview Refresh Documentation
microsoftgraph/microsoft-graph-docs pull request #20510
Opened 2023-03-09 02:27 UTC by OWinfreyATL

2023-03-09 07:53 UTC, OWinfreyATL commented
This PR contains addressed feedback from https://github.com/microsoftgraph/microsoft-graph-docs/pull/20058

2023-03-17 18:18 UTC, msewaweru requested changes
@OWinfreyATL, thanks for the work on this PR. The highlights of the review are as below. I will complete reviewing the change log on Monday. Thanks.
1. Resolve the build warning on this PR.
2. Maintain indentation on the files you updated to remove it. It hugely affects readability.
3. Confirm the updates that are removing the  baseType entity in the JSON file.

2023-03-17 18:18 UTC, msewaweru commented on api-reference/beta/resources/identitygovernance-lifecycleworkflowscontainer.md
> -  "baseType": "microsoft.graph.entity",
Confirm this inheritance.

2023-03-17 18:18 UTC, msewaweru commented on api-reference/beta/resources/identitygovernance-run.md
>  |workflowExecutionType|String|The execution type of the workflows associated with the run. The possible values are: `scheduled`, `onDemand`, `unknownFutureValue`.<br><br>Supports `$filter`(`eq`, `ne`
Correct the type of this property.

2023-03-17 18:18 UTC, msewaweru commented on api-reference/beta/resources/identitygovernance-run.md
>  |processingStatus|String|The run execution status. The possible values are: `queued`, `inProgress`, `completed`, `completedWithErrors`, `canceled`, `failed`, `unknownFutureValue`.<br><br>Supports `$f
As commented above. Return type ss property is wrong.

2023-03-19 18:44 UTC, OWinfreyATL commented on api-reference/beta/resources/identitygovernance-run.md
>  |workflowExecutionType|String|The execution type of the workflows associated with the run. The possible values are: `scheduled`, `onDemand`, `unknownFutureValue`.<br><br>Supports `$filter`(`eq`, `ne`
Im seeing the same type as totalUsersCount:
![image](https://user-images.githubusercontent.com/85191667/226199765-c3f6b3e0-175f-4654-95cc-690e99fd770c.png)

2023-03-21 07:36 UTC, msewaweru requested changes
@OWinfreyATL, I have completed the review on the change log. See my comments and update. Thanks.

2023-03-21 07:36 UTC, msewaweru commented on changelog/Microsoft.AAD.LCM.json
>        "ChangeList": [
@OWinfreyATL - This change log replicates the v1 change log that is currently on hold. Please reset the change log to only capture the emailsettings change (download the change log from Drake's PR) and extensibility resources change.

2023-03-21 10:27 UTC, msewaweru commented
@FaithOmbongi - as discussed, I have reviewed the changes and all is ok except the pending items, change log and [this comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20510#discussion_r1140531077) that I marked as unresolved.

2023-03-21 18:19 UTC, FaithOmbongi approved these changes
Hi @OWinfreyATL - This looks good to go. Approved.

@msewaweru - Thank you for your extensive review of this PR.

2023-03-22 02:07 UTC, merged