Topics in search
microsoftgraph/microsoft-graph-docs pull request #20532
Opened 2023-03-09 22:24 UTC by watermelonT

Add documentation for returning topics in search API.

2023-03-14 21:54 UTC, ajacks-msft approved these changes
Very helpful doc! My comments are all minor.

2023-03-14 21:54 UTC, ajacks-msft commented on api-reference/beta/resources/search-topic.md
> +| primaryName | microsoft.graph.topicName | The object representing the most relevant name and its metadata. |
"most relevant" is fairly internal data science wording. Shall we say "most accurate"? Also on the next line.

2023-03-14 21:54 UTC, ajacks-msft commented on api-reference/beta/resources/search-topic.md
> +| languageInfos | Collection(microsoft.graph.topicLanguageInfo) | Other available language infos of the current topic, with language name and the URL to visit topic page using given language. |
I don't understand what a language info is. Is there a more descriptive way to document this?

2023-03-14 21:54 UTC, ajacks-msft commented on api-reference/beta/resources/search-topic.md
> +| lastModifiedBy | microsoft.graph.identity | The last modifier of the topic, if the topic has been modified |
"The last user to edit this topic" would be more clear. Or you use "curator" later in this doc.

2023-03-14 21:54 UTC, ajacks-msft commented on api-reference/beta/resources/search-topic.md
> +| languageTags | Collection(Edm.String) | The list hosting a set of language tags mined for this file. |
What format are language tags in? Is this like "en-us"?

2023-03-14 21:54 UTC, ajacks-msft commented on api-reference/beta/resources/search-topic.md
> +| lastModifiedBy | microsoft.graph.identity | The last curator of the file, if the file has been curated |
Would it help to say "manually curated"?

2023-04-13 19:09 UTC, njerigrevious requested changes
Looks good - would like some additional clarification on the request body mechanism per my comment. Thanks!

2023-04-13 19:09 UTC, njerigrevious commented on api-reference/beta/api/topicsearch-post.md
> +Do not supply a request body for this method.
Why does it say "do not supply a request body for this method"? Shouldn't  users be able to provide a querystring that will be used to find relevant topics that will be displayed in the response? Please provide more info on how this works and the intended use of the request body for this feature. Thanks!

2023-06-20 15:01 UTC, closed without merging