Viva Learning Course Activity Public Preview Graph Documentation
microsoftgraph/microsoft-graph-docs pull request #20557
Opened 2023-03-12 03:30 UTC by udbach

This request contains documentation of Learner course apis to be released in Viva Learning Course Activity Public Preview. Learner course operations are performed on learningCourseActivity entity which can be of type learningAssignment or learningSelfInitiatedCourse.

Below are the list of different Learner course apis:
1.Create a new learning course activity in Viva Learning.
2. Get details of learning course activity by using learningCourseActivityId.
3. Get details of learning course activity by using externalCourseActivityId.
4. Update details of learning course activity by using learningCourseActivityId.
5. Delete learning course activity
6. Get the list of the courses for a user
7. Get details of a course for a user by using learningCourseActivityId

2023-03-21 20:27 UTC, dodaromike commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +
Properties under Request Body should be in alphabetical order.

2023-03-21 20:32 UTC, dodaromike commented on api-reference/beta/api/learningcourseactivity-update.md
> +
Properties under Request body should be in alphabetical order.

2023-03-21 21:11 UTC, dodaromike commented
@udbach Changelog updates are needed for these documents.   Please see https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2023-03-21 21:31 UTC, dodaromike requested changes

2023-03-21 21:31 UTC, dodaromike commented on api-reference/beta/resources/learningassignment.md
> +
@udbach Properties should be in alphabetical order in both the table and JSON representation.

2023-03-21 21:31 UTC, dodaromike commented on api-reference/beta/resources/learningcourseactivity.md
> +
@udbach Properties should be in alphabetical order in both the table and JSON representation.

2023-03-23 18:04 UTC, dodaromike commented on api-reference/beta/resources/learningselfinitiatedcourse.md
> +```
Properties and JSON representations should be in alphabetical order.

2023-03-23 18:28 UTC, dodaromike commented on api-reference/beta/resources/learningassignment.md
> +
@udbach I alphabetized learning assignment.md.  You should do the same with other lists of properties and JSON representations.

2023-03-26 04:26 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +
updated

2023-03-26 04:27 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-update.md
> +
updated

2023-03-26 04:27 UTC, udbach commented on api-reference/beta/resources/learningassignment.md
> +
thanks, i updated for other commented files

2023-03-26 04:27 UTC, udbach commented on api-reference/beta/resources/learningselfinitiatedcourse.md
> +```
updated

2023-03-27 16:55 UTC, dodaromike commented on api-reference/beta/resources/learningcourseactivity.md
> +
@udbach These properties also need to be in alphabetical order.

2023-03-27 16:57 UTC, dodaromike commented on api-reference/beta/resources/learningselfinitiatedcourse.md
> +```
@udbach All properties and JSON representations need to be in alphabetical order.

2023-03-27 16:59 UTC, dodaromike commented
@udbach Thanks for changes.  But there are still more properties and JSON representations that need to be in alphabetical order.

2023-03-27 20:11 UTC, dodaromike approved these changes

2023-03-29 01:57 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +Learning course activity is of two types. Assignment and Self-initiated.
Please fix the punctuation and capitalization here: 

Learning course activity is of two types:
- Assignment 
- Self-initiated

Can you clarify how this information is relevant? For example; "Use this method to create either type of activity."

2023-03-29 02:07 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +## Create assigned learning course activity
Please do not add H2 sections that are not part of the reference topic template. This is a custom H2. You don't need to repeat the permissions as that's covered in the Permissions section. It should also be clear in the Request body section that they can set the @odata.type value to create an assignment activity.

Note that values are enclosed in tic marks ( ` ), not apostrophes.

2023-03-29 02:14 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +In the request body, supply a JSON representation of the [learningCourseActivity](../resources/learningcourseactivity.md) object.
In this section, you will want to mention that they can set the type to either learningAssignment or learningSelfInitiatedCourse, depending on what type of activity they want to create.

2023-03-29 02:26 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +The following is an example of the response
Please add the missing period at the end of the sentence.

2023-03-29 02:30 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +## Create self-initiated learning course activity
Per my earlier comment, please just describe how to create both types of activities in the Request body section. You can include two different examples in the Examples section to show the request and response for both types. You don't need to repeat these sections.

To include two examples, add H3 sections under the Examples H2; i.e.:

## Examples
### Example 1: Create an assigned learning course activity
#### Request
#### Response
### Example 2: Create a self-initiated learning course activity
#### Request
#### Response

2023-03-29 02:31 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +The following is an example of the response
Global: Please add the missing period throughout; I won't comment on each occurrence.

2023-04-04 00:02 UTC, Lauragra commented on api-reference/beta/resources/assignmentType.md
> +title: "assignmentType resource type"
We don't document enums in standalone topics. Please see the guidance for documenting enums here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211747/Enumerations

2023-04-04 00:04 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +
This topic is missing two required H2 sections:
## Request body
## Response

Please make sure that you include all required section. If you use the stub topics generated by Graph Studio, the required sections will be prepopulated.

2023-04-04 00:06 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +#### Request
Global: In all method topics, we need to include the HTML comments for API Doctor validation. For details about those comments, see this CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211782/Set-up-for-API-Doctor-validation

2023-04-04 00:07 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +``` http
Global: For all method topics, add the HTML comment to ignore the HTTP request example. This is the HTML comment to add:

<!-- { "blockType": "ignored" } -->

2023-04-04 00:17 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +POST https://graph.microsoft.com/v1.0/employeeExperience/learningProviders/{registrationId}/learningCourseActivities
Global: These are beta APIs; please make sure that all examples call the beta endpoint and not v1.0.

2023-04-05 03:39 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +Retrieves course activity details for a user using courseActivityId.
It seems like we have two different descriptions for this topic; can you combine these into a single summary description?

2023-04-05 03:40 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +|Delegated (work or school account)|**LearningAssignedCourse.Read,LearningSelfInitiatedCourse.Read**|
Please remove the bold formatting from the permission names and add a space after the commas in the table.

2023-04-05 03:43 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +Request for a provider to retrieve course activity details of a given user. Appropriate Application permission of course activity type is required to access the api.
Do we need the second sentence in this and the following section? We mention the permissions in the previous section.  For the first sentence, revise as follows:

To retrieve the course activity details for a user:

2023-04-05 03:45 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +
Revise the first sentence as:
To retrieve course activity details for the signed-in user:

2023-04-05 03:45 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Global: Ideally, for List and Get operation topics, we mention which query parameters are supported.

2023-04-05 03:47 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +GET https://graph.microsoft.com/beta/users/{user-id}/employeeExperience/learningCourseActivities/{id}
Please have only one request and one response per example. Not sure if you need to show both here.

Also, global comment: Please use real-looking values instead of placeholders in the example.

2023-04-06 20:47 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-get.md
> +Retrieves the Course Activity via CourseActivity id that is sent by VivaLearning in the Create
We have two descriptions in this topic as well. The second description on line 16 is more standard; the description on line 13 is not completely clear. Please update to a single clear summary description.

2023-04-06 20:52 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-get.md
> +The following is an example of request and response of an assigned learning course activity.
This sentence is misplaced. Are you introducing both the request and the response? Then please move this under the Examples heading and clarify. I think you might mean to say: "The following example shows a request and the response to get an assigned learning course activity."

2023-04-06 21:09 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-get.md
> +The following is an example of request and response of an self-initiated learning course activity.
When you have two examples in a topic you need to create separate H3 sections for each example. So you would have:

\### Example 1: Get an assigned learning course activity
\#### Request
\#### Response
\### Example 2: Get a self-initiated learning course activity
\#### Request
\#### Response

2023-04-06 21:13 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +# Get employeeExperience
This title does not appear to be accurate/correct. Please update. Is this actually a duplicate of learningcourseactivity-get? The file name here doesn't look correct either.

2023-04-06 21:19 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-getByExternalCourseActivityId.md
> +title: "Get learningCourseActivityByExternalCourseActivityId"
I don't see this action or function defined in the metadata. Can you point me to it? The title and H1 here doesn't appear to be correct based on the file name. The correct title would be "learningCourseActivity: getByExternalCourseActivityId". For details, see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=toc-and-topic-titles

2023-04-06 21:19 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-getByExternalCourseActivityId.md
> +Retrieves the Course Activity using ExternalCourseActivityId that is sent by learning provider in the Create course activity api call.
If we keep this topic, we need to update the summary description; we have the same problem here of two different summary descriptions.

2023-04-06 21:49 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-list.md
> +Get a list of the [learningCourseActivity](../resources/learningcourseactivity.md) courses (assigned, recommended, and self-initiated) for a user.
Did you mean learningCourseActivity courses here, or, do you mean learning course activities? It seems like the activities are different than a course? Also, I don't see a reference to "recommended" learning course activities elsewhere in the docs; is that a valid type of activity in addition to assigned and self-initiated?

2023-04-06 21:49 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-list.md
> +Request for the signed-in user to retrieve all the course activities belonging to the user:
Please see my previous comment about this structure and update accordingly.

2023-04-06 22:35 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +After creating a course activity in Viva Learning, Provider should have ability to update the following properties using the Viva Learning CourseActivity Id generated when
Do we need the second sentence here? Does it add anything to the description? In line 13, please change "Updates" to "Update".

2023-04-06 22:36 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +Below properties are eligible to update a learning assignment course activity:
Revise this sentence as: "The following table lists the properties of a learning course activity that can be updated."

2023-04-11 18:59 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-details.md
> +# Get employeeExperience
fixed description. Tis api returns learning course activity details belonging to a user.

2023-04-11 19:01 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-details.md
> +|Delegated (work or school account)|**LearningAssignedCourse.Read,LearningSelfInitiatedCourse.Read**|
fixed

2023-04-11 19:04 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-details.md
> +Request for a provider to retrieve course activity details of a given user. Appropriate Application permission of course activity type is required to access the api.
fixed

2023-04-11 19:04 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-details.md
> +
fixed

2023-04-11 19:06 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-details.md
> +GET https://graph.microsoft.com/beta/users/{user-id}/employeeExperience/learningCourseActivities/{id}
fixed

2023-04-11 19:21 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-get.md
> +The following is an example of request and response of an self-initiated learning course activity.
not required to show different example as the request format is common for both types. Fixed the example.

2023-04-11 19:23 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-getByExternalCourseActivityId.md
> +title: "Get learningCourseActivityByExternalCourseActivityId"
fixed, share csdl and api.md links offline. FYI 6th scenario in api.md

2023-04-11 19:24 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-getByExternalCourseActivityId.md
> +Retrieves the Course Activity using ExternalCourseActivityId that is sent by learning provider in the Create course activity api call.
fixed

2023-04-11 19:25 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-list.md
> +Get a list of the [learningCourseActivity](../resources/learningcourseactivity.md) courses (assigned, recommended, and self-initiated) for a user.
required or recommended are assignmentTypes of learningAssigned course activity. It is not a separate learning course activity type.

2023-04-11 19:28 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-list.md
> +Request for the signed-in user to retrieve all the course activities belonging to the user:
fixed

2023-04-11 19:37 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-update.md
> +Below properties are eligible to update a learning assignment course activity:
fixed

2023-04-11 19:37 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-update.md
> +After creating a course activity in Viva Learning, Provider should have ability to update the following properties using the Viva Learning CourseActivity Id generated when
fixed

2023-04-13 03:23 UTC, Lauragra commented on api-reference/beta/resources/learningcourseactivity.md
> +Represents the metadata of learner course activities for employee learning.
We should mention in this topic that this is the base type for learningAssignment and learningSelfInitiatedCourse.

2023-04-13 03:24 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +{
Please check this response example; the OData type of learningSelfInitiatedCourse is missing.

2023-04-13 03:26 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-getByExternalCourseActivityId.md
> +``` http
We're missing the response HTML comment for this example.

2023-04-13 03:27 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +``` http
This response is missing the HTML comment.

2023-04-13 03:28 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +``` http
This response is missing the HTML comment.

2023-04-13 03:28 UTC, Lauragra commented on api-reference/beta/resources/courseStatus.md
> +# courseStatus enum type
Please add this enum and values to the enums.md file and remove this topic.

2023-04-13 14:01 UTC, udbach commented on api-reference/beta/resources/learningcourseactivity.md
> +Represents the metadata of learner course activities for employee learning.
done

2023-04-13 14:08 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-update.md
> +``` http
added

2023-04-13 14:08 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-update.md
> +``` http
added

2023-04-13 17:28 UTC, udbach commented on api-reference/beta/resources/courseStatus.md
> +# courseStatus enum type
removed topic and added to enums.md

2023-04-13 22:07 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +- Assignment
For more context here, we should use the resource names and link to those resources.

2023-04-13 22:14 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|Id|String|The resultant ID of this request can be used to make further interactions to the course activity APIs.|
Can you please clarify the description here? Is this a generated ID that can be used for subsequent API calls?

2023-04-13 22:16 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|learningContentId|String| The ID of the learning content received when Learning Content is created on Viva Learning using LearningContent graph API’s.|
This description needs to be clarified as well. Do you mean, "The ID of the learning content when it is created on Viva Learning." Does this API support learning content in sources other than Viva Learning?

2023-04-13 22:16 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|learnerUserId|String|The user ID of the learner.|
Is the definition of the learner clear? Is this for example the individual to whom the activity is assigned?

2023-04-13 22:19 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|startedDateTime|DateTimeOffset|The date time value on which the self-initiated course was started by the learner.|
Do some of these properties apply to an assigned and some to a self-initiated activity? And if so, would it be more clear to separate the properties into two tables, one for each type of activity?

2023-04-13 22:20 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|assignedDateTime|DateTimeOffset|Assigned date for the course activity. Optional. |
Global: We're listing some properties as Option, but for others, we're not specifying that they are required. To remove any possible ambiguity, please add "Required." to the descriptions for required properties.

2023-04-13 22:22 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +# [HTTP](#tab/http)
Global: Please remove the HTTP tab from the examples. This gets added when we add the SDK snippets to the examples via the weekly automation, when we merge into main. Until we add the other snippets, this will appear as a single tab.

2023-04-13 22:23 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +The following example creates a [learningSelfInitiated](../resources/learningselfinitiatedcourse.md) course.
Please fix the name of the resource here.

2023-04-13 22:34 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +In the request body, supply a JSON representation of the [learningCourseActivity](../resources/learningcourseactivity.md) object.
Do you need to state here that they provide a JSON representation of either a learningAssignment or a learningSelfInitiatedCourse object, depending on which type of activity they're creating?

2023-04-13 22:35 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +If successful, this method returns a `201 Created` response code and a [learningCourseActivity](../resources/learningcourseactivity.md) object in the response body.
Here too, do you need to mention that the response will be one of the subtypes?

2023-04-13 22:36 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +POST /employeeExperience/learningProviders/{registrationId}/learningCourseActivities
Global: Do you need to explain where the registrationId value comes from?

2023-04-13 22:37 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-delete.md
> +DELETE /employeeExperience/learningProviders/{registrationId}/learningCourseActivities/{id}
We generally use more specific names for the placeholders, like {learningCourseActivityId}, especially when the syntax includes multiple placeholders.

2023-04-13 22:38 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +POST https://graph.microsoft.com/beta/employeeExperience/learningProviders/{registrationId}/learningCourseActivities
Generally we use real-looking values instead of placeholders in examples, so please add a value for {registrationId} here.

2023-04-13 22:45 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-get.md
> +Retrieves the Course Activity via CourseActivity id that is sent by VivaLearning in the Create
The issue is actually still here in the file.

2023-04-13 22:47 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-details.md
> +# Get learningCourseActivity details for a user
We should have only one topic for the GET operation on learningCourseActivity. You can include multiple different syntaxes for that operation, either on the user or the signed-in user, or the object ID. Did the tool generate this topic or did you add it manually? The title and file name are not consistent with our standards. Anyway, please combine the content with learningcourseactivity-get.

2023-04-14 02:10 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Global: this is the standard boilerplate but ideally we can be more specific about whether query parameters are supported and which ones (or none).

2023-04-14 02:20 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-getByExternalCourseActivityId.md
> +title: "learningCourseActivity: getByExternalCourseActivityId"
This method is not defined in the CSDL or api.md file. Please verify that this topic should be included, and message me to point me to the CSDL where it is defined.

2023-04-14 02:25 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|Application|LearningAssignedCourse.ReadWrite.All, LearningSelfInitiatedCourse.ReadWrite.All|
Please document the new permissions in the permissions-reference.md file in the /concepts folder.

2023-04-14 02:27 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-list.md
> +Get a list of the [learningCourseActivity](../resources/learningcourseactivity.md) courses (assigned or self-initiated) for a user.
Is a learningCourseActivity an actual course? It seems like the word "course" might be out of place here, because this is an activity. What is the relationship between an activity and a course? Make sure that that distinction is clear to your users.

2023-04-14 02:39 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +The following table lists the properties of a assigned learning course activity that can be updated:
This section needs to go in the Request body section, not the example section.

2023-04-14 02:40 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +### Request
Be sure to follow the heading levels. The Request and Response headings should be H4s (\####).

2023-04-14 02:41 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +|@odata.type|String|Type to determine if it’s a [learningAssignment](../resources/learningassignment.md) or [learningSelfInitiated](../resources/learningselfinitiatedcourse.md) course.|
Please apply the edits I made to the property descriptions in the POST operation topic to the descriptions in this table.

2023-04-14 02:45 UTC, Lauragra commented on api-reference/beta/resources/learningassignment.md
> +|@odata.type|String|Type to determine if it’s a [learningAssignment](../resources/learningassignment.md) or [learningSelfInitiated](../resources/learningselfinitiatedcourse.md) course.|
Please apply the edits to the property descriptions in this table as well.

2023-04-14 02:59 UTC, Lauragra commented on api-reference/beta/resources/learningassignment.md
> +Represents the metadata of assigned course activity record of learner.
Would this be an accurate description: "Represents the details of a learning activity assigned to a user."

2023-04-14 03:00 UTC, Lauragra commented on api-reference/beta/resources/learningselfinitiatedcourse.md
> +Represents the metadata of self-initiated course activity record of learner.
Would this be an accurate description: "Represents the details of a learning activity self-initiated by a user."

2023-04-14 03:01 UTC, Lauragra commented on api-reference/beta/resources/learningassignment.md
> +description: "Represents learner assignment record"
Global: Note that where we update a summary description in the article, we also need to update the description here to be consistent.

2023-04-14 03:03 UTC, Lauragra commented on api-reference/beta/resources/learningcourseactivity.md
> +Represents the metadata of learner course activities for employee learning. This is the base type of [learningAssignment](../resources/learningassignment.md) or [learningSelfInitiated](../resources/l
Would this be an accurate description: "Represents the details of a learning activity that is part of a course in Viva Learning."

2023-04-14 03:05 UTC, Lauragra commented on api-reference/beta/resources/learningcourseactivity.md
> +|[Create learningCourseActivity](../api/employeeexperienceuser-post-learningcourseactivities.md)|[learningCourseActivity](../resources/learningcourseactivity.md)|Create a new [learningCourseActivity]
Please list the methods in the standard order: List, create, get, update, delete. A few methods I'm not sure need to be here so if we remove those topics, we need to remove them from this table as well.

2023-04-14 03:10 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-list.md
> +
We're missing the HTML comment for the response here.

2023-04-14 03:11 UTC, Lauragra commented on api-reference/beta/resources/learningcourseactivity.md
> +|@odata.type|String|**Type to determine if it’s a LearningAssignment or SelfInitiated course.**
Please remove the bold formatting from the property descriptions in each row, and apply the edits to the property descriptions here.

2023-04-14 03:12 UTC, Lauragra commented on api-reference/beta/resources/learningassignment.md
> +  "status": "@odata.type: microsoft.graph.courseStatus"
The startedDateTime property is missing here.

2023-04-14 03:20 UTC, Lauragra commented on api-reference/beta/resources/learningcourseactivity.md
> +## Error Conditions and Messages
This is a non-standard H2. We don't list error messages in resource topics. If you want to provide error message info, you can create a concept topic that we can surface under Teamwork and communications in the concept TOC, and we can link to this information in the Response section of the method topics.

Also, please remove the bold formatting from the descriptions.

2023-04-14 03:20 UTC, Lauragra commented on api-reference/beta/resources/learningcourseactivity.md
> +  "@odata.type": "#microsoft.graph.learningCourseActivity",
This JSON representation doesn't match the list of properties in the Properties table - please verify.

2023-04-14 03:21 UTC, Lauragra commented on api-reference/beta/resources/learningselfinitiatedcourse.md
> +|@odata.type|String|Type to determine if it’s a [learningAssignment](../resources/learningassignment.md) or [learningSelfInitiated](../resources/learningselfinitiatedcourse.md) course.|
Please apply the edits to the property descriptions.

2023-04-14 03:22 UTC, Lauragra commented on api-reference/beta/resources/viva-learning-api-overview.md
> +- [Learner course records](learningcourseactivity.md) to upload and manage learner course activity records from your LMS or learning provider in Viva Learning.
Should the link text be "Learning course activities"?

2023-04-14 03:25 UTC, Lauragra commented on api-reference/beta/resources/viva-learning-api-overview.md
> +- ## Manage learning providers.
We need to fix the formatting here. We can't have headings that are bullets. I think you can remove the headings here and just have introductory sentences, followed by a colon, to introduce the bulleted items.

2023-04-14 03:26 UTC, Lauragra requested changes
Please review and address comments. This PR also need an update to the toc.yml file in the beta folder to surface the new resources and methods, and we need a ChangeList record added to the changelog JSON file so the new APIs will be listed in the changelog. That record should be generated as an artifact of your schema PR.

2023-04-18 11:15 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +- Assignment
fixed

2023-04-18 11:16 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +POST /employeeExperience/learningProviders/{registrationId}/learningCourseActivities
actually not required as the navigation and content for consumer to reach learning course activities comes from learning provider and content apis which are already GA

2023-04-18 11:21 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +In the request body, supply a JSON representation of the [learningCourseActivity](../resources/learningcourseactivity.md) object.
its intuitive for system integrators as there are two different types which are derived from base entity. We also gave separate examples below.

2023-04-18 12:56 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|assignedDateTime|DateTimeOffset|Assigned date for the course activity. Optional. |
updated.

2023-04-18 12:56 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|Id|String|The resultant ID of this request can be used to make further interactions to the course activity APIs.|
updated

2023-04-18 12:57 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|learnerUserId|String|The user ID of the learner.|
updated

2023-04-18 12:59 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|startedDateTime|DateTimeOffset|The date time value on which the self-initiated course was started by the learner.|
updated the description. Each of the types have individual tables under resources and reference in this document too.

2023-04-18 12:59 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +If successful, this method returns a `201 Created` response code and a [learningCourseActivity](../resources/learningcourseactivity.md) object in the response body.
updated.

2023-04-18 13:10 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +# [HTTP](#tab/http)
done

2023-04-18 13:12 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +POST https://graph.microsoft.com/beta/employeeExperience/learningProviders/{registrationId}/learningCourseActivities
updated

2023-04-18 13:14 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-delete.md
> +DELETE /employeeExperience/learningProviders/{registrationId}/learningCourseActivities/{id}
its the same property returned in response when created learning course activity and same is mentioned in attributes table. Hence aligning with that.

2023-04-18 13:16 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-getByExternalCourseActivityId.md
> +title: "learningCourseActivity: getByExternalCourseActivityId"
moved to get api as suggested above.

2023-04-18 13:21 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-list.md
> +
fixed

2023-04-18 13:30 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-update.md
> +|@odata.type|String|Type to determine if it’s a [learningAssignment](../resources/learningassignment.md) or [learningSelfInitiated](../resources/learningselfinitiatedcourse.md) course.|
updated

2023-04-18 13:36 UTC, udbach commented on api-reference/beta/resources/learningassignment.md
> +Represents the metadata of assigned course activity record of learner.
fixed

2023-04-18 13:37 UTC, udbach commented on api-reference/beta/resources/learningassignment.md
> +  "status": "@odata.type: microsoft.graph.courseStatus"
its optional.

2023-04-18 13:44 UTC, udbach commented on api-reference/beta/resources/learningcourseactivity.md
> +## Error Conditions and Messages
updated

2023-04-18 13:44 UTC, udbach commented on api-reference/beta/resources/learningcourseactivity.md
> +|@odata.type|String|**Type to determine if it’s a LearningAssignment or SelfInitiated course.**
fixed

2023-04-18 13:46 UTC, udbach commented on api-reference/beta/resources/learningcourseactivity.md
> +  "@odata.type": "#microsoft.graph.learningCourseActivity",
updated with required attributes

2023-04-18 13:47 UTC, udbach commented on api-reference/beta/resources/learningselfinitiatedcourse.md
> +Represents the metadata of self-initiated course activity record of learner.
rephrased and updated.

2023-04-18 13:47 UTC, udbach commented on api-reference/beta/resources/learningselfinitiatedcourse.md
> +|@odata.type|String|Type to determine if it’s a [learningAssignment](../resources/learningassignment.md) or [learningSelfInitiated](../resources/learningselfinitiatedcourse.md) course.|
updated

2023-04-18 13:48 UTC, udbach commented on api-reference/beta/resources/viva-learning-api-overview.md
> +- [Learner course records](learningcourseactivity.md) to upload and manage learner course activity records from your LMS or learning provider in Viva Learning.
updated

2023-04-18 13:49 UTC, udbach commented on api-reference/beta/resources/viva-learning-api-overview.md
> +- ## Manage learning providers.
updated

2023-04-18 13:53 UTC, udbach commented on api-reference/beta/resources/learningassignment.md
> +description: "Represents learner assignment record"
updated at other places too.

2023-04-18 13:55 UTC, udbach commented on api-reference/beta/api/learningcourseactivity-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
added parameters supported

2023-04-18 14:00 UTC, udbach commented on api-reference/beta/resources/learningcourseactivity.md
> +|[Create learningCourseActivity](../api/employeeexperienceuser-post-learningcourseactivities.md)|[learningCourseActivity](../resources/learningcourseactivity.md)|Create a new [learningCourseActivity]
fixed

2023-04-18 19:59 UTC, Lauragra commented on api-reference/beta/api/learningcourseactivity-update.md
> +The following table lists the properties of a assigned learning course activity that can be updated:
This is the wrong place in the topic for this content. I will fix.

2023-04-18 20:15 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|learnerUserId|String|The user ID of the learner to whom the activity is assigned. Required.|
Should learningProviderId be included here?

2023-04-18 20:36 UTC, Lauragra commented on changelog/Microsoft.Viva.Learning.json
> +          "Id": "79b38947-d95a-41ce-aa48-2394f5d7e1fc",
The ChangeList record should include entries for each of the new resources and the new enums as well; please add those.

2023-04-19 08:33 UTC, udbach commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +|learnerUserId|String|The user ID of the learner to whom the activity is assigned. Required.|
thanks added

2023-04-19 18:28 UTC, Lauragra approved these changes

2023-04-20 02:21 UTC, merged