[Doc Improvement][Breaking changes for call transcript]
microsoftgraph/microsoft-graph-docs pull request #20584
Opened 2023-03-14 12:14 UTC by v-sdhakshina

2023-03-16 15:19 UTC, v-sdhakshina commented on api-reference/beta/resources/calltranscript.md
>  ## JSON representation
updated as suggested.

2023-03-17 10:27 UTC, mankadnandan commented on api-reference/beta/api/calltranscript-get.md
> +> The document format for transcripts will be deprecated in 60 days. As a result, example 4 and 5 will be removed.
The "docx" format for transcripts...

2023-03-17 10:29 UTC, mankadnandan commented on api-reference/beta/api/calltranscript-get.md
> +>**Note:** As document format is getting deprecated, the `Accept` header will also be deprecated.
As "docx" format is getting deprecated...

2023-03-17 10:29 UTC, mankadnandan commented on api-reference/beta/api/calltranscript-get.md
> +>**Note:** As document format is getting deprecated, the `$format` query parameter will also be deprecated.
Same as above

2023-03-20 10:34 UTC, v-sdhakshina commented on api-reference/beta/api/calltranscript-get.md
> +>**Note:** As document format is getting deprecated, the `$format` query parameter will also be deprecated.
Updated as suggested

2023-03-20 10:37 UTC, v-sdhakshina commented on api-reference/beta/api/calltranscript-get.md
> +> The document format for transcripts will be deprecated in 60 days. As a result, example 4 and 5 will be removed.
Updated as suggested

2023-03-21 18:59 UTC, Danielabom commented
Contacted author to get info.

2023-03-27 15:00 UTC, Danielabom commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **metadataContent** property to the [callTranscript](https://learn.microsoft.com/en-us/graph/api/resources/calltranscript) resource.",
Would you mind validating this link? We are adding a property to the beta version of the resource, correct?

2023-03-27 15:27 UTC, Danielabom requested changes
Hi @v-sdhakshina, thank you for working oh this PR. Please take a look at my comments.

2023-03-28 17:05 UTC, v-sdhakshina commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **metadataContent** property to the [callTranscript](https://learn.microsoft.com/en-us/graph/api/resources/calltranscript) resource.",
Yes, the property is for the beta version.

2023-03-30 01:37 UTC, Danielabom commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **metadataContent** property to the [callTranscript](https://learn.microsoft.com/en-us/graph/api/resources/calltranscript) resource.",
```suggestion
          "Description": "Added the **metadataContent** property to the [callTranscript](https://learn.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta) resource.", 
```

2023-03-30 01:39 UTC, Danielabom approved these changes
Updated the link. PR approved.

2023-04-03 09:39 UTC, v-habibaumme approved these changes

2023-04-03 09:41 UTC, surbhigupta12 approved these changes

2023-04-04 02:31 UTC, Lauragra commented on api-reference/beta/api/calltranscript-get.md
> +> The docx format for transcripts will be deprecated in 60 days. As a result, example 4 and 5 will be removed.
The statement of 60 days is not going to be helpful for readers because they don't know the date at which this statement was added to the docs. Instead, can we please provide a date on which the docx format will be removed (not deprecated). For example, I suggest revising this as follows:

The docx format for transcripts is deprecated and will no longer be supported on {date}. 

We don't need to state that the examples will be removed; simply remove those two examples when the date arrives.

2023-04-04 02:36 UTC, Lauragra commented on api-reference/beta/api/calltranscript-get.md
> +>**Note:** As docx format is getting deprecated, the `Accept` header will also be deprecated.
Please revise. Note that something is deprecated for a period of time before it is removed/unsupported. I assume that the current state is that the format is deprecated, and the future state is removal of support. Suggested revision:

The docx format and `Accept` header are currently deprecated and will no longer be supported effective {date}. 

I notice that we do not mention the Accept header in the Request headers section; not sure if we need to, depending on the timing of the deprecation. Please also see the general guidance for deprecation: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211775/Deprecate-docs

2023-04-04 02:37 UTC, Lauragra commented on api-reference/beta/api/calltranscript-get.md
> +>**Note:** As docx format is getting deprecated, the `$format` query parameter will also be deprecated.
Similar suggested revision here:

The docx format and `$format` query parameter are currently deprecated and will no longer be supported effective {date}.

2023-04-04 02:37 UTC, Lauragra commented on api-reference/beta/api/calltranscript-get.md
> +``` http
Please add the missing HTML comments for API Doctor to the request and response examples here.

2023-04-04 13:05 UTC, v-sdhakshina commented on api-reference/beta/api/calltranscript-get.md
> +``` http
Added HTML comments.

2023-04-04 13:05 UTC, v-sdhakshina commented on api-reference/beta/api/calltranscript-get.md
> +>**Note:** As docx format is getting deprecated, the `$format` query parameter will also be deprecated.
Updated as suggested.

2023-04-04 13:05 UTC, v-sdhakshina commented on api-reference/beta/api/calltranscript-get.md
> +>**Note:** As docx format is getting deprecated, the `Accept` header will also be deprecated.
Updated as suggested.

2023-04-04 16:07 UTC, andrueastman commented on api-reference/beta/api/calltranscript-get.md
> +WEBVTT
First line of the http response would need to be the status code. Check line 375 for reference.

2023-04-04 17:01 UTC, v-sdhakshina commented on api-reference/beta/api/calltranscript-get.md
> +WEBVTT
updated as suggested

2023-04-05 01:43 UTC, Lauragra commented on api-reference/beta/api/calltranscript-get.md
> +> The docx format for transcripts will be deprecated from May 31, 2023.
This is still not quite clear. Do you mean, the format is not currently deprecated, but it will be deprecated starting on May 31? Or is it currently deprecated and will no longer be supported effective May 31? If you mean the former, revise as follows:

The docx format for transcripts will be deprecated starting on May 31, 2023.

If you mean the latter, revise as follows:

The docx format for transcripts is deprecated and will no longer be supported effective May 31, 2023.

Generally we update the docs when something is actually deprecated, not in advance of the deprecation.

2023-04-05 10:58 UTC, v-sdhakshina commented on api-reference/beta/api/calltranscript-get.md
> +> The docx format for transcripts will be deprecated from May 31, 2023.
Updated as "The docx format for transcripts will be deprecated starting May 31, 2023."

2023-04-06 00:10 UTC, Danielabom approved these changes
@v-sdhakshina, thank you for addressing Laura's comments. PR approved

2023-04-06 02:45 UTC, merged