Add signInActivity to v1
microsoftgraph/microsoft-graph-docs pull request #20594
Opened 2023-03-14 23:08 UTC by besiler

Adding the signInActivity resource to v1 docs

2023-03-16 15:59 UTC, FaithOmbongi requested changes
Thank you @besiler for your work on this PR. 

I've left a few suggestions to fix minor issues imported from beta.

2023-03-16 15:59 UTC, FaithOmbongi commented on api-reference/v1.0/resources/user.md
> +|signInActivity | [signInActivity](signinactivity.md) | Get the last signed-in date and request ID of the sign-in for a given user. Read-only.<br><br>Returned only on `$select`. Supports `$filter` (`
nit: Consolidating all notes
```suggestion
|signInActivity | [signInActivity](signinactivity.md) | Get the last signed-in date and request ID of the sign-in for a given user. Read-only.<br><br>Returned only on `$select`. Supports `$filter` (`eq`, `ne`, `not`, `ge`, `le`) *but* not with any other filterable properties. <br><br>**Note:** <br/><li>Details for this property require an Azure AD Premium P1/P2 license and the **AuditLog.Read.All** permission.<li>There's a [known issue](/graph/known-issues#license-check-errors-for-azure-ad-activity-reports) with retrieving this property.<li>This property is not returned for a user who has never signed in or last signed in before April 2020.|
```

2023-03-16 15:59 UTC, FaithOmbongi commented on api-reference/v1.0/resources/user.md
Add signInActivity to the JSON representation section as well.

2023-03-16 15:59 UTC, FaithOmbongi commented on api-reference/v1.0/resources/signinactivity.md
> +Provides the last interactive or non-interactive sign-in time for a specific [user](user.md). Since signInActivity describes a property of the user object, Azure AD stores signinactivity for your use
nit
```suggestion
Provides the last interactive or non-interactive sign-in time for a specific [user](user.md). Since signInActivity describes a property of the user object, Azure AD stores sign in activity for your users for as long as the user object exists. 
```

2023-03-16 15:59 UTC, FaithOmbongi commented on api-reference/v1.0/resources/signinactivity.md
> +  "lastSignInDateTime": "String (timestamp)",
nit
```suggestion
  "@odata.type": "#microsoft.graph.signInActivity",
  "lastSignInDateTime": "String (timestamp)",
```

2023-03-16 15:59 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the [signInActivity](https://learn.microsoft.com/en-us/graph/api/resources/signInActivity?view=graph-rest-v1) resource and its associated methods to v1. SignInActivity
fix changelog
signInActivity is a complex type so doesn't have methods.
```suggestion
          "Description": "Added the [signInActivity](https://learn.microsoft.com/en-us/graph/api/resources/signInActivity?view=graph-rest-1.0) resource. **signInActivity** allows you to see the last time a user signed in, letting you identify and manage stale user accounts.",
```

2023-03-16 15:59 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      "SubArea": "Directory management"
```suggestion
      "WorkloadArea": "Users",
      "SubArea": ""
```

2023-03-16 15:59 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the **signInActivity** property to the [user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-v1) resource.",
```suggestion
          "Description": "Added the **signInActivity** property to the [user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) resource.",
```

2023-03-18 04:08 UTC, besiler commented
@FaithOmbongi I added an example to the v1 GET user file as well

2023-03-21 15:33 UTC, FaithOmbongi approved these changes
Hi @besiler - Approved. Remember to replace the **do not merge** with the **ready to merge** label.

2023-03-31 05:00 UTC, merged