Docs for GAing app-scoped chat subscriptions
microsoftgraph/microsoft-graph-docs pull request #20603
Opened 2023-03-15 18:21 UTC by eddie-lee-msft

Docs for GAing app-scoped chat subscriptions

2023-03-20 19:31 UTC, Danielabom requested changes
Hi @eddie-lee-msft, thank you for working on this PR. Please review my comments on the changelog.

2023-03-20 19:39 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Enabled change notifications support to [get](https://docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-v1.0) or [list](https://docs.microsoft.com/en-us/gr
Hey @Danielabom thanks for the review. I actually copied these from when we first released in /beta and modified for V1. :D But sure, let me split into two instead of just one.

2023-03-27 14:43 UTC, Danielabom commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Enabled change notifications support to [get](https://docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-v1.0) or [list](https://docs.microsoft.com/en-us/gr
Hi Eddie, I appreciate it, and I apologize for the overhead. 
Laura Graham is our publisher, and perhaps the last changelog changes were approved when she was enjoying some time off. Plus, a couple of us onboarded the Docs Team over the previous two years, so that one might have slipped our internal QA process.

2023-04-03 23:55 UTC, Danielabom approved these changes
Changes approved.

2023-04-05 18:47 UTC, Danielabom commented on concepts/includes/change-notifications-supported-resources-expanded.md
> +| Teams [chatMessage][] | Changes to chat messages in all channels in all teams: `/teams/getAllMessages` <br><br> Changes to chat messages in a specific channel: `/teams/{id}/channels/{id}/messages`
```suggestion
| Teams [chatMessage][] | Changes to chat messages in all channels in all teams: `/teams/getAllMessages` <br><br> Changes to chat messages in a specific channel: `/teams/{id}/channels/{id}/messages` <br><br> Changes to chat messages in all chats: `/chats/getAllMessages`  <br><br> Changes to chat messages in a specific chat: `/chats/{id}/messages` <br><br> Changes to chat messages in all chats a particular user is part of: `/users/{id}/chats/getAllMessages` | Maximum subscription quotas: <li> Per app and channel or chat combination: 1 subscription. <li>To track chat messages in all chats by subscription, each user is part of: 10 subscriptions<li> Per organization: 10,000 total subscriptions. |
```

2023-04-05 20:00 UTC, Danielabom approved these changes

2023-04-05 20:00 UTC, Danielabom approved these changes
PR approved

2023-04-06 03:16 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +        {
Global: Can each item be included in a single changelist, so they all render in one table instead of multiple separate tables? It seems like we want these to all be grouped together.

2023-04-10 20:40 UTC, erichui-ms commented
Hi, @eddie-lee-msft .  Any reason why /teams/getAllMembers is not added on this page?

2023-04-10 21:29 UTC, eddie-lee-msft commented
> Hi, @eddie-lee-msft . Any reason why /teams/getAllMembers is not added on this page? Also, will https://learn.microsoft.com/en-us/graph/api/resources/webhooks be updated with similar updates as well? (For example, I don't see "appCatalogs" there currently.) Thanks!

@erichui-ms , not sure why. Perhaps it's not GA'd? It's on the beta page but not the v1 page. Check with Abhishek, I think he would have more context on team related webhooks. Either way, that is out of scope for this PR so please check with him and open another PR if needed.

2023-04-11 01:09 UTC, merged