Rename toc node: Customer relationship management > Partner customer administration
microsoftgraph/microsoft-graph-docs pull request #20653
Opened 2023-03-20 17:49 UTC by JulCsc

2023-03-21 07:27 UTC, angelgolfer-ms requested changes
Thanks for your fixes, @JulCsc . I added one comment, please take a look.

2023-03-21 15:09 UTC, JulCsc commented on api-reference/beta/toc.yml
> -      - name: Customer relationship management
Done on both beta and v1.0. Thanks!

2023-03-22 13:34 UTC, JulCsc commented
> This pull request has conflicting changes, the author must resolve the conflicts before this pull request can be merged.

@angelgolfer-ms @Lauragra - please advise.

2023-03-23 09:13 UTC, merged

2023-03-23 09:15 UTC, angelgolfer-ms commented
Merged to main after @FaithOmbongi helped fix the merge conflicts. Just so this PR won't have to run into another unexpected wave of merge conflicts to the TOC files.