Correct errors within code snippets tab section
microsoftgraph/microsoft-graph-docs pull request #20652
Opened 2023-03-20 16:41 UTC by millicentachieng

2023-03-21 06:56 UTC, angelgolfer-ms reviewed
Hi @millicentachieng , the 22 files you have included in this PR look good to me, thanks.
Most of these files exhibit one problem - missing HTTP tag while the other language tabs are present. 

Please confirm if you were able to identify any files that have this other problem - an HTTP tag present while other language tabs are missing. Please also see the related email thread from me.

2023-03-21 21:20 UTC, millicentachieng commented
Hi @angelgolfer-ms. You are right, most of the files were missing a HTTP tab. We only had one [file](https://learn.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&tabs=http) with duplicated HTTP tab.

I didn't encounter any lone HTTP tab in my tests.

2023-03-24 02:32 UTC, angelgolfer-ms commented on api-reference/v1.0/api/drive-get-specialfolder.md
> +### Get children of a special folder
Line 81:
@millicentachieng ,  please precede this line with "Example 1: ", like "Example 1: Get children of a special folder".

2023-03-24 03:03 UTC, angelgolfer-ms commented on api-reference/beta/api/drive-get-specialfolder.md
> -## HTTP Request
@millicentachieng ,
FYI many of the OneDrive and SharePoint API topics have not followed our API reference topic templates. This is one of them.
In this particular file (beta version), line 37 (blocktype...) is wrong to start with. This is the "HTTP request" section that's supposed to show syntax, not an example request. So instead of building upon something that's already wrong and consequently got code snippets generated for it, please help correct and make line 37 the blockType as ignored, and remove the rest of that line 37. And the remaining updates - adding an H3 "Example 1" heading, etc., the existing code snippet lines that were injected by mistake, none of that applies. Please remove them.

As you move on to subsequent lines, you would see this topic which intends to show multiple ways to get a special folder, should have grouped all the syntax lines and present them in one "HTTP request" section, as in the "HTTP request" section in message-get.md. The way they have done this all this time is virtually having multiple sub-topics within the same API topic. I think for our purpose of cleaning up issues around code snippet tabs, we can avoid scope creep as long as the file still satisfies any API Doctor checks. :-(

2023-03-24 03:06 UTC, angelgolfer-ms commented on api-reference/beta/api/drive-get.md
> -## Get current user's OneDrive
@millicentachieng , this OneDrive topic has the problem I described in an earlier [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20652/files#r1147071631). Please remove the inappropriate lines that had assumed the HTTP request lines were examples, and any code snippet lines that have been previously inserted.

2023-03-24 03:10 UTC, angelgolfer-ms commented on api-reference/beta/api/drive-list-following.md
> -## HTTP request
@millicentachieng , this OneDrive topic has the problem I described in an earlier [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20652/files#r1147071631). Please remove the inappropriate lines that had assumed the HTTP request lines were examples, and any code snippet lines that have been previously inserted.

Also, while lines 55-56 seem to be appropriate for a "Response" section, the topic is missing a matching example request for the example response in lines 60-80. Would you be able to add back an example request please?

2023-03-24 03:37 UTC, angelgolfer-ms commented on api-reference/beta/api/drive-list.md
@millicentachieng , this OneDrive topic has the problem I described in an earlier [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20652/files#r1147071631). Please remove the inappropriate lines that had assumed the HTTP request lines were examples, and any code snippet lines that have been previously inserted.

In addition, lines 195-224 seems to be an example response without a matching example request. I suppose the example response corresponds to a request like in line 152, GET /me/drives. Would you mind adding an example request section? As a reminder, the example request requires a fully qualified domain, not just /me/drives.

2023-03-24 03:39 UTC, angelgolfer-ms commented on api-reference/beta/api/drive-recent.md
> -## HTTP request
@millicentachieng , this OneDrive topic has the problem I described in an earlier [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20652/files#r1147071631). Please remove the inappropriate lines that had assumed the HTTP request lines were examples, and any code snippet lines that have been previously inserted.

In addition, lines 65-102 seem to be an example response without a matching example request. I suppose the example response corresponds to a request like in line 39. Would you mind adding an example request section? As a reminder, the example request requires a fully qualified domain.

2023-03-24 03:41 UTC, angelgolfer-ms commented on api-reference/beta/api/drive-sharedwithme.md
> -## HTTP request
@millicentachieng , this OneDrive topic has the problem I described in an earlier [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20652/files#r1147071631). Please remove the inappropriate lines that had assumed the HTTP request lines were examples, and any code snippet lines that have been previously inserted.

In addition, lines 63-97 seem to be an example response without a matching example request. I suppose the example response corresponds to a request like in line 38. Would you mind adding an example request section? As a reminder, the example request requires a fully qualified domain.

2023-03-24 04:00 UTC, angelgolfer-ms requested changes
Hi @millicentachieng , upon more careful review of the OneDrive files, I noticed their inconsistent topic structure has made them now confusing even to ourselves. Basically, what should be the "HTTP request" was somehow mistaken (by some author?) to serve as an example request, which then got the code snippets inappropriately added to those syntax lines. An API topic must have an 'HTTP request" section that shows the syntax, and that section is separate from any example request section. 

Another common problem is those topics have a "stray" example response section that doesn't have a corresponding example request section. If you don't mind, it would be good that you can add the matching example request section. The alternative, if you don't want to incur this task, then we'd have to comment out the example response and message the owner team to make the fix themselves.

I commented those beta OneDrive API files that you included in this PR. I didn't go through the v1 OneDrive API files, but in all likelihood, the v1 files would have the similar problem (as authors typically promote API docs from beta to v1 by copying whatever's in the beta folder and then make appropriate changes for v1). Would you please check the v1 OneDrive API files and make the appropriate fixes?

Thank you. Please let me know on Teams if you have questions.

2023-03-26 20:38 UTC, millicentachieng commented
Thank you for your review @angelgolfer-ms. I've added example requests where necessary.

2023-04-14 07:38 UTC, angelgolfer-ms approved these changes
Thanks, @millicentachieng , the updates look good to me.

2023-04-15 02:06 UTC, merged