add document for inline webpart
microsoftgraph/microsoft-graph-docs pull request #20659
Opened 2023-03-21 03:26 UTC by sangle7

2023-03-21 19:25 UTC, Danielabom commented
Contacted author to get info.

2023-03-22 15:43 UTC, Danielabom requested changes
Dear Hanbing, 
The published metadata shows two existing properties which are: 
data
webPartType

However, the api.md file, mentions two existing properties which are: 
Id
WedPartType
Please reconcile those differences.
And, if you are adding a new property called "containerTextWebPartId", please include a changelog entry. 
Reach out if you have questions. Thanks!

2023-03-22 15:44 UTC, Danielabom commented on api-reference/beta/resources/standardwebpart.md
> +| containerTextWebPartId | string                                     | Instance identifier of the container text webPart. Only works for inline standard webPart in rich text webPart. |
```suggestion
| containerTextWebPartId | string                                     | The instance identifier of the container text webPart. Only works for inline standard webPart in rich text webPart. |
```

2023-03-22 15:46 UTC, Danielabom commented on api-reference/beta/resources/standardwebpart.md
> +| containerTextWebPartId | string                                     | The instance identifier of the container text webPart. Only works for inline standard webPart in rich text webPart. |
```suggestion
| containerTextWebPartId | string                                     | The instance identifier of the container text webPart. It only works for inline standard webPart in rich text webPart. |
```

2023-03-22 15:48 UTC, Danielabom commented on api-reference/beta/resources/standardwebpart.md
> +| webPartType            | String                                     | A Guid which indicates the type of the webParts                                                                 |
```suggestion
| webPartType            | String                                     | A Guid that indicates the webPart type.                                                         |
```

2023-03-23 03:20 UTC, sangle7 commented
@Danielabom  Hi, the published schema and the `api.md` files are aligned. This `standardWebPart` model has these properties: `id, data, webPartType, containerTextWebPartId(newly add)`. The `data` is a navigation property so it shows up in the `Relationships` section.

2023-03-23 14:50 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the `containerTextWebPartId` property to the [standardWebPart](https://learn.microsoft.com/en-us/graph/api/resources/standardWebPart?view=graph-rest-beta) resource.",
```suggestion
          "Description": "Added the **containerTextWebPartId** property to the [standardWebPart](https://learn.microsoft.com/en-us/graph/api/resources/standardWebPart?view=graph-rest-beta) resource.",
```

2023-03-23 14:52 UTC, Danielabom commented on api-reference/beta/resources/standardwebpart.md
> +| containerTextWebPartId | string                                     | The instance identifier of the container text webPart. It only works for inline standard webPart in rich text webPart. |
```suggestion
| containerTextWebPartId | string                                     | The instance identifier of the container text webPart. It only works for inline standard webPart in rich text webParts. |
```

2023-03-23 14:53 UTC, Danielabom approved these changes
Thank you for working on this PR @sangle7. Everything looks good.

2023-04-05 23:09 UTC, Danielabom commented
@sangle7, friendly reminder: Add the "Ready to merge" label as soon as you are ready to publish.

2023-07-06 04:09 UTC, merged