Add ssoCheckKerberosConfigurationError type in cloudPcOnPremisesConne…
microsoftgraph/microsoft-graph-docs pull request #20674
Opened 2023-03-22 06:57 UTC by Monica-Ji

…ctionHealthCheckErrorType for sso check item

2023-03-22 07:07 UTC, Monica-Ji commented
road map item id:  16824

2023-03-22 07:37 UTC, RuiHou105 requested changes
@Monica-Ji  Please also update the changelog to describe your change.

2023-03-31 08:06 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the **ssoCheckKerberosConfigurationError** property to the [cloudPcOnPremisesConnectionHealthCheckErrorType](https://learn.microsoft.com/en-us/graph/api/reso
```suggestion
                    "Description": "Added the **ssoCheckKerberosConfigurationError** member to the [cloudPcOnPremisesConnectionHealthCheckErrorType](https://learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta#cloudpconpremisesconnectionhealthcheckerrortype-values) resource.",
```

2023-04-25 07:00 UTC, Guoan-Tang approved these changes

2023-04-26 02:25 UTC, merged