GraphDoc_ActiveInactiveAssignments
microsoftgraph/microsoft-graph-docs pull request #20670
Opened 2023-03-21 22:43 UTC by AshwaniBansal1

Documentation for Active-InactiveAssignments

2023-03-25 14:22 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-get.md
> +  "isCollection": true
remove this line, it is indicating that the response will return a collection, that's the reason it's expecting a "value" property.

2023-03-25 14:22 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-get.md
> +  "isCollection": true
same here, remove this line

2023-03-25 14:22 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-activate.md
> +  "isCollection": true
remove

2023-03-25 14:22 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-deactivate.md
> +  "isCollection": true
remove this line

2023-03-25 14:22 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-deactivate.md
> +  "isCollection": true
remove

2023-03-27 16:12 UTC, cristobal-buenrostro approved these changes

2023-03-27 17:06 UTC, richardle798 requested changes

2023-03-27 17:06 UTC, richardle798 commented on api-reference/beta/api/educationassignment-deactivate.md
> +title: "Deactive educationAssignment"
Deactivate

2023-03-27 17:06 UTC, richardle798 commented on api-reference/beta/resources/educationassignment.md
> +|[Activate assignment](../api/educationassignment-deactivate.md) |[educationAssignment](educationassignment.md) | Mark an assigned **educationAssignment** as inactive to signal that the assignment ha
Deactivate assignment

2023-03-28 00:17 UTC, richardle798 approved these changes

2023-04-19 23:15 UTC, dodaromike commented
Lines 18,26 in the changelog need to be fixed.

2023-04-21 19:57 UTC, dodaromike commented
@cristobal-buenrostro Broken links need to be fixed at changelog/Microsoft.EducationAssignment.json: Line(s) 18,26.  @AshwaniBansal1 says you are now working on this PR.  I've tried fix the links but failed.

2023-04-24 20:45 UTC, dodaromike approved these changes

2023-04-24 20:48 UTC, dodaromike requested changes
@cristobal-buenrostro Broken links need to be fixed at changelog/Microsoft.EducationAssignment.json: Line(s) 18,26. @AshwaniBansal1 says you are now working on this PR. I've tried fix the links but failed.

2023-04-26 20:34 UTC, cristobal-buenrostro commented
> @cristobal-buenrostro Broken links need to be fixed at changelog/Microsoft.EducationAssignment.json: Line(s) 18,26. @AshwaniBansal1 says you are now working on this PR. I've tried fix the links but failed.

@dodaromike , links are fixed now.

2023-04-26 20:51 UTC, dodaromike commented
Thanks @cristobal-buenrostro for link fixes.  The new problems don't appear to be caused by the current PR.  I'll approve it.

2023-04-29 02:22 UTC, Lauragra commented on api-reference/beta/api/educationassignment-activate.md
> +If successful, this method returns a `200 OK` response code and a [status](/graph/api/resources/educationassignment?#properties) value of `assigned` in the response body.
To be clear, from the example, it looks like and educatioAssignment object is returned in the response body, and the status property has a value of `assigned`. Please clarify what is returned in the response.

2023-04-29 02:25 UTC, Lauragra commented on api-reference/beta/api/educationassignment-deactivate.md
> +| Content-Type  | application/json. Required. |
This header isn't included when there isn't a request body. Also, this section doesn't list the optional Prefer header described in the examples. Please make sure that the Request headers section is accurate.

2023-04-29 02:26 UTC, Lauragra commented on api-reference/beta/api/educationassignment-deactivate.md
> +### Example 1: Mark assignment inactive-request without optional Prefer header
Can you explain why they would and would not include this request header?

2023-04-29 02:26 UTC, Lauragra commented on api-reference/beta/api/educationassignment-activate.md
> +| Content-Type  | application/json. Required. |
We should remove this header if it's not used in the request.

2023-04-29 02:27 UTC, Lauragra commented on api-reference/beta/api/educationassignment-get.md
> +## Example 2: Get assignment in inactive state with optional Prefer header
Please update the Request headers section and add context about using this optional header. Also, this should be an H3, not an H2.

2023-05-01 18:41 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-activate.md
> +If successful, this method returns a `200 OK` response code and a [status](/graph/api/resources/educationassignment?#properties) value of `assigned` in the response body.
updated

2023-05-01 18:44 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-activate.md
> +| Content-Type  | application/json. Required. |
added in the request

2023-05-01 18:47 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-deactivate.md
> +| Content-Type  | application/json. Required. |
added content type in the request body.
And added prefer as optional.

2023-05-01 19:01 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-deactivate.md
> +### Example 1: Mark assignment inactive-request without optional Prefer header
done

2023-05-01 19:10 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-get.md
> +## Example 2: Get assignment in inactive state with optional Prefer header
updated to H3, more context added in the description about the optional parameter.

2023-05-04 04:09 UTC, Lauragra approved these changes

2023-05-04 16:15 UTC, dodaromike commented
@cristobal-buenrostro  Please set this PR "Ready to merge".

2023-05-05 02:41 UTC, Lauragra commented on api-reference/beta/api/educationassignment-activate.md
> +| Content-Type  | application/json. Required. |
Why is the header used in the request when the request doesn't have a JSON body?

2023-05-05 02:41 UTC, Lauragra commented on api-reference/beta/api/educationassignment-deactivate.md
> +Content-type: application/json
Same question here - there is no request body.

2023-05-05 02:43 UTC, Lauragra commented
@AshwaniBansal1 , this PR has API Doctor errors that appear to be related to the inclusion of the request headers. Can you please fix and make sure that the PR passes validation before we publish? Thanks.

2023-05-05 15:13 UTC, dodaromike commented
> @AshwaniBansal1 , this PR has API Doctor errors that appear to be related to the inclusion of the request headers. Can you please fix and make sure that the PR passes validation before we publish? Thanks.

Including @cristobal-buenrostro

2023-05-06 01:10 UTC, merged