doc changelog
microsoftgraph/microsoft-graph-docs pull request #20702
Opened 2023-03-23 21:35 UTC by phoebeweiser

Changelog for msi sign in logs documentation

2023-03-27 08:52 UTC, FaithOmbongi requested changes
Hi @phoebeweiser - Please make the relevant changes to the core docs as well. i.e.
Add managedServiceIdentity to the signIn resource type doc + add the related complex type.

2023-03-27 08:53 UTC, FaithOmbongi requested changes
Hi @phoebeweiser - Please make the relevant changes to the core docs as well. i.e.
Add managedServiceIdentity to the signIn resource type doc + add the related complex type.

2023-03-28 00:48 UTC, besiler commented on api-reference/beta/resources/managedIdentity.md
> +|associatedResourceId|String|The resource Id of the Azure resource associated with the managed identity used for signin.|
```suggestion
|associatedResourceId|String|The ARM resource ID of the Azure resource associated with the managed identity used for signin.|
```

Recommend specifying this is an ARM ID rather than one of our normal GUID IDs. The azure resource monitor team seems to use ARM ID in their doc so it should be easy for customers to search it: https://learn.microsoft.com/en-us/rest/api/resources/resources/get-by-id#definitions

2023-03-28 00:48 UTC, besiler commented on api-reference/beta/api/signin-get.md
> +          "associatedResourceId":"/subscriptions/a89523b8-b5db-4697-9c1b-2f7dcfd074d9/resourcegroups/Scenario-TestRPToKeyVaultSAJob_USCentral/providers/Providers.Test/msiStateful/testrp30964"
This looks like a real ARM ID - just checking that you don't mind having it made public

2023-03-28 00:48 UTC, besiler commented on api-reference/beta/resources/managedIdentity.md
> +description: "Managed Identity resource type has 2 properties for managed identity type and associated resource Id. "
```suggestion
description: "Managed Identity resource type has 2 properties for managed identity type and associated resource Id."
```

2023-03-28 00:48 UTC, besiler commented on api-reference/beta/resources/signin.md
> +|managedServiceIdentity|[managedIdentity](../resources/managedidentity.md)|Contains information about the managed identity used for sign-in including managed identity type and associated Azure resour
```suggestion
|managedServiceIdentity|[managedIdentity](../resources/managedidentity.md)|Contains information about the managed identity used for the sign in, including managed identity type and associated Azure ARM resource ID.|
```

2023-03-28 00:58 UTC, besiler commented on api-reference/beta/api/signin-get.md
> +          "associatedResourceId":"/subscriptions/a89523b8-b5db-4697-9c1b-2f7dcfd074d9/resourcegroups/Scenario-TestRPToKeyVaultSAJob_USCentral/providers/Providers.Test/msiStateful/testrp30964"
You could make a fake GUID if you didn't already

2023-03-29 10:00 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      "WorkloadArea": "Reports and audit",
Autogenerated value is because of an incorrect representation in the workload-mapping.json file in the schema file. It will be good if the reference can be fixed for future changelogs.
```suggestion
      "WorkloadArea": "Reports",
```

2023-04-04 02:56 UTC, merged