Add ranking hints docs
microsoftgraph/microsoft-graph-docs pull request #20711
Opened 2023-03-24 17:38 UTC by emzho

API review work item ID: 15776
Private preview PR ID: 7832911
(beta PR coming soon)

2023-04-04 23:43 UTC, Danielabom commented on api-reference/beta/resources/externalconnectors-property.md
> +| labels        | microsoft.graph.externalConnectors.label collection | Specifies one or more well-known tags added against a property. Labels help Microsoft Search understand the semantics of the da
Quick question, why did you remove "unkownFutureValue"?

2023-04-04 23:48 UTC, Danielabom commented on api-reference/beta/resources/externalconnectors-property.md
> +| rankingHint   | [microsoft.graph.externalConnectors.rankingHint](externalconnectors-rankinghint.md) | Specifies the property ranking hint. Developers can specify which properties are most important
Since you have previously applied the best practice of listing the possible values, we recommend the same in this case , here's the evolvable enums wiki: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

2023-04-04 23:49 UTC, Danielabom requested changes
Hi @emzho, this PR is in great shape. Please review my comments. Thanks!

2023-04-04 23:52 UTC, emzho commented on api-reference/beta/resources/externalconnectors-property.md
> +| labels        | microsoft.graph.externalConnectors.label collection | Specifies one or more well-known tags added against a property. Labels help Microsoft Search understand the semantics of the da
I thought about removing, because it is not a valid value for a partner to pass in, it's only a valid value that our API would return. We've gotten some bad requests from clients calling, trying to set the property value as "unknownFutureValue" which is not correct. I thought removal would be less ambiguous, because the above language seems to imply that unknownFutureValue is a valid value. What are your thoughts around updating this guidance?

2023-04-04 23:53 UTC, emzho commented on api-reference/beta/resources/externalconnectors-property.md
> +| rankingHint   | [microsoft.graph.externalConnectors.rankingHint](externalconnectors-rankinghint.md) | Specifies the property ranking hint. Developers can specify which properties are most important
"rankingHint" isn't an enum, which is why I didn't list out possible values here. I did so in the externalconnectors-rankinghints.md file instead when describing importancesScore

2023-04-05 00:03 UTC, Danielabom commented on api-reference/beta/resources/externalconnectors-property.md
> +| labels        | microsoft.graph.externalConnectors.label collection | Specifies one or more well-known tags added against a property. Labels help Microsoft Search understand the semantics of the da
I understand, and it makes sense. However, since it is an evolvable enum, listing  "unkownFutureValue" as a possible value is a requirement. I'll follow up on Teams.

2023-04-05 02:35 UTC, Danielabom commented on api-reference/beta/resources/externalconnectors-property.md
> +| labels        | microsoft.graph.externalConnectors.label collection | Specifies one or more well-known tags added against a property. Labels help Microsoft Search understand the semantics of the da
@angelgolfer-ms

2023-04-05 19:11 UTC, Danielabom approved these changes
@emzho, thank you for working on this PR and always clearing my doubts. PR approved.

2023-04-13 02:58 UTC, merged