Update membershipOutlierInsight.md
microsoftgraph/microsoft-graph-docs pull request #20739
Opened 2023-03-27 21:48 UTC by shresthabuddha

Added property lastModifiedById and lastModifiedBy to track who modified the record. This will be the guid of user who modified the record and would be a directoryObject.

2023-03-29 01:15 UTC, shubhamguptacal commented on api-reference/beta/resources/membershipOutlierInsight.md
> +| lastModifiedById | String | Indicates the identifier of the user who modified the record. |
Is this field nullable?

2023-03-29 02:49 UTC, Lauragra commented
@shresthabuddha , it looks like this PR hasn't had a content review. Adding @FaithOmbongi . We'll need a changelog entry to call out the new properties.

2023-03-29 07:08 UTC, FaithOmbongi commented
Hi @shresthabuddha - I see the changes in this PR aren't yet in the public schema.  To allow us to schedule this work for review, create a content review work item at https://aka.ms/msgraph-identity-workitem and add the links to the API.md and Schema PR in the work item description.

Also, add the changelog entry to this PR. You'll get the changelog stubs from your schema PR's build artifacts.

Hi @msewaweru - kindly assist to review this PR when it's ready to. Thanks.

2023-03-29 22:50 UTC, shresthabuddha commented on api-reference/beta/resources/membershipOutlierInsight.md
> +| lastModifiedById | String | Indicates the identifier of the user who modified the record. |
it will not be null as a default value will be added to it.

2023-03-30 10:54 UTC, msewaweru commented
@shresthabuddha, please mark PR ready for review once you have added the change log. Thanks.

2023-04-04 07:42 UTC, msewaweru requested changes
Hi @shresthabuddha, please check the return type of the new relationship as per the schema.

Also, add the change log for this update.

2023-04-04 07:42 UTC, msewaweru commented on api-reference/beta/resources/membershipOutlierInsight.md
> +|lastModifiedBy|[directoryObject](../resources/directoryobject.md)| Navigation link to a member object who modified the record. For example, to a user.|
Schema indicates the return type to be user not directoryobject. Please update.

2023-04-04 23:25 UTC, shresthabuddha commented
> Hi @shresthabuddha, please check the return type of the new relationship as per the schema.
> 
> Also, add the change log for this update.

@msewaweru added changelog + changed relationship type. Please check. Thank you for comment.

2023-04-06 09:52 UTC, msewaweru requested changes
@shresthabuddha - thanks for the updates. A few final comments:

- Suggested that new relation return type be user instead of directoryObject as per the schema.
- The API change in the changelog should be relationship instead of resource.

2023-04-06 09:52 UTC, msewaweru commented on changelog/Microsoft.AAD.Reporting.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-04-06 09:52 UTC, msewaweru commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the **lastModifiedBy** relationship to the [membershipOutlierInsight](https://learn.microsoft.com/en-us/graph/api/resources/membershipOutlierInsight?view=graph-rest-be
```suggestion
          "Description": "Added the **lastModifiedBy** navigation property to the [membershipOutlierInsight](https://learn.microsoft.com/en-us/graph/api/resources/membershipOutlierInsight?view=graph-rest-beta) resource.",
```

2023-04-06 09:52 UTC, msewaweru commented on api-reference/beta/resources/membershipOutlierInsight.md
> +|lastModifiedBy|[directoryObject](../resources/user.md)| Navigation link to a member object who modified the record. For example, to a user.|
```suggestion
|lastModifiedBy|[user](../resources/user.md)| Navigation link to a member object who modified the record. For example, to a user.|
```

2023-04-06 10:06 UTC, msewaweru requested changes

2023-04-06 10:06 UTC, msewaweru commented on changelog/Microsoft.AAD.Reporting.json
> +      "WorkloadArea": "Reports and audit",
```suggestion
      "WorkloadArea": "Reports",
```

2023-04-06 21:29 UTC, shresthabuddha commented
> @shresthabuddha - thanks for the updates. A few final comments:
> 
> * Suggested that new relation return type be user instead of directoryObject as per the schema.
> * The API change in the changelog should be relationship instead of resource.

Thank you @msewaweru for the suggestions. Applied all of them.

2023-04-12 05:55 UTC, msewaweru approved these changes
Thanks, @shresthabuddha for the updates. LGTM!

2023-05-03 02:16 UTC, merged