User/mandar/pag
microsoftgraph/microsoft-graph-docs pull request #20734
Opened 2023-03-27 19:24 UTC by mandardalvi

2023-04-12 18:34 UTC, rkarim-ms approved these changes

2023-05-04 13:51 UTC, FaithOmbongi requested changes
Hi @mandardalvi, @ilyalushnikov - 

I've left a few comments to address prior to approval. Please review them.

2023-05-04 18:35 UTC, ilyalushnikov commented on api-reference/beta/api/privilegedaccessgroupassignmentschedulerequest-get.md
> +|Application|PrivilegedAssignmentSchedule.ReadWrite.AzureADGroup|
For all "xxxScheduleRequest entity" related endpoints in PIM for Groups API, we need ReadWrite permission for GET, LIST, filterbycurrentuser, and between Create and cancel.
Current version is accurate.

2023-05-04 18:36 UTC, ilyalushnikov commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md
> +|Application|PrivilegedEligibilitySchedule.ReadWrite.AzureADGroup|
For all "xxxScheduleRequest entity" related endpoints in PIM for Groups API, we need ReadWrite permission for GET, LIST, filterbycurrentuser, and between Create and cancel.
Current version is accurate.

2023-05-04 18:36 UTC, ilyalushnikov commented on api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md
> +|Application|PrivilegedEligibilitySchedule.ReadWrite.AzureADGroup|
For all "xxxScheduleRequest entity" related endpoints in PIM for Groups API, we need ReadWrite permission for GET, LIST, filterbycurrentuser, and between Create and cancel.
Current version is accurate.

2023-05-04 18:36 UTC, ilyalushnikov commented on api-reference/beta/api/privilegedaccessgroup-list-assignmentschedulerequests.md
> +|Application|PrivilegedAssignmentSchedule.ReadWrite.AzureADGroup|
For all "xxxScheduleRequest entity" related endpoints in PIM for Groups API, we need ReadWrite permission for GET, LIST, filterbycurrentuser, and between Create and cancel.
Current version is accurate.

2023-05-04 23:16 UTC, ilyalushnikov commented on api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-get.md
> +|Application|PrivilegedEligibilitySchedule.ReadWrite.AzureADGroup|
correct, Read permission isn't enough here

2023-05-05 07:52 UTC, FaithOmbongi approved these changes
Hi @mandardalvi, @ilyalushnikov - Approved.

Let us sync internally about the casing issue.

Also, let's follow up with some tutorials, how-to articles, and guidance on working with rules. We have guidance for [rules for Azure AD roles](https://learn.microsoft.com/en-us/graph/identity-governance-pim-rules-overview) and I believe PIM for groups also has rules?

2023-05-06 00:48 UTC, merged