Deprecating previous custom extension modles
microsoftgraph/microsoft-graph-docs pull request #20747
Opened 2023-03-28 07:12 UTC by vikama-microsoft

This is the follow up PR to add deprecation tag to the old models
We have already added this tag in CSDL

2023-03-29 10:30 UTC, FaithOmbongi requested changes
Thank you @vikama-microsoft for your work on this PR. I've left suggestions for fixes inline plus the following:

1. I've revisited the deprecation guidance and learn that you also need to mark the methods ( metadata title and H1 title) as deprecated + add the deprecation banner. The TOC remains with just the one update you made.
2. Upgrade the banner to a CAUTION banner. I've left the suggestion inline.
3. I don't see a deprecation annotation for customExtensionClientConfiguration in the schema. Please verify.

Please also add a changelog. I've manually created an object that you use 👇🏾; I haven't added the object for which I can't trace the annotation - add it to the changelog when you can confirm it's also deprecated.

```json
{
      "ChangeList": [
        {
          "Id": "58686064-7128-45ec-aaf4-e7650c0023a9",
          "ApiChange": "Resource",
          "ChangedApiName": "Resource",
          "ChangeType": "Deprecation",
          "Description": "Deprecated the [customAccessPackageWorkflowExtension](https://learn.microsoft.com/en-us/graph/api/resources/customAccessPackageWorkflowExtension?view=graph-rest-beta) resource type and its associated methods for intergrating entitlement management and Azure Logic Apps. Use the [accessPackageAssignmentRequestWorkflowExtension](https://learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestworkflowextension?view=graph-rest-beta) and [accessPackageAssignmentWorkflowExtension](https://learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentworkflowextension?view=graph-rest-beta) resource types and their associated methods instead.",
          "Target": "customAccessPackageWorkflowExtension"
        },
        {
          "Id": "58686064-7128-45ec-aaf4-e7650c0023a9",
          "ApiChange": "Resource",
          "ChangedApiName": "customExtensionHandlerInstance",
          "ChangeType": "Addition",
          "Description": "Added the [customExtensionHandlerInstance](https://learn.microsoft.com/en-us/graph/api/resources/customExtensionHandlerInstance?view=graph-rest-beta) resource type.",
          "Target": "customExtensionHandlerInstance"
        },
        {
          "Id": "58686064-7128-45ec-aaf4-e7650c0023a9",
          "ApiChange": "Resource",
          "ChangedApiName": "customExtensionHandler",
          "ChangeType": "Addition",
          "Description": "Added the [customExtensionHandler](https://learn.microsoft.com/en-us/graph/api/resources/customExtensionHandler?view=graph-rest-beta) resource type.",
          "Target": "customExtensionHandler"
        }
      ],
      "Id": "58686064-7128-45ec-aaf4-e7650c0023a9",
      "Cloud": "Prod",
      "Version": "beta",
      "CreatedDateTime": "2023-03-30T00:00:00.2731454Z",
      "WorkloadArea": "Identity and access",
      "SubArea": "Governance"
    }
```

2023-03-29 10:30 UTC, FaithOmbongi commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +> The customAccessPackageWorkflowExtension resource type and its associated methods is deprecated and will be retired on "2023-12-31". Use the [accessPackageAssignmentRequestWorkflowExtension](../res
```suggestion
> The customAccessPackageWorkflowExtension resource type and its associated methods is deprecated and will be retired on December 31, 2023. Use the [accessPackageAssignmentRequestWorkflowExtension](../resources/accesspackageassignmentrequestworkflowextension.md)  and [accessPackageAssignmentWorkflowExtension](../resources/accesspackageassignmentworkflowextension.md) resource types and their associated methods.
```

2023-03-29 10:30 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +          - name: Custom access package workflow extensione (deprecated)
```suggestion
          - name: Custom access package workflow extension (deprecated)
```

2023-03-29 10:30 UTC, FaithOmbongi commented on api-reference/beta/resources/customaccesspackageworkflowextension.md
> +> [!IMPORTANT]
Suggestion to upgrade to a caution banner because we have a set retirement date.
```suggestion
> [!CAUTION]
```

2023-03-29 10:30 UTC, FaithOmbongi commented on api-reference/beta/resources/customextensionclientconfiguration.md
> +title: "customExtensionClientConfiguration resource type (deprecated)"
Hmm, I don't see a deprecation annotation for this object in the schema. Please verify.

2023-04-03 15:51 UTC, markwahl-msft reviewed
@vikama-microsoft  I was expecting to also see deprecation comments on the API method md files as well.  Is that going to be in a subsequent PR?

2023-06-08 17:17 UTC, FaithOmbongi commented
Hi @vikama-microsoft - Please address the review feedback on this PR to unblock Ortagus' PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/21571. Thanks.

2023-07-18 08:02 UTC, FaithOmbongi commented
re-requested review.

2023-07-18 16:33 UTC, FaithOmbongi approved these changes
Hi @vikama-microsoft - I've pushed a few commits then approved.

2023-07-18 21:14 UTC, merged