Fixing Sync API docs
microsoftgraph/microsoft-graph-docs pull request #20765
Opened 2023-03-29 18:27 UTC by rahuln3223

2023-03-30 16:51 UTC, FaithOmbongi requested changes
Hi @rahuln3223 - Thanks for handling these changes. I've left suggestions for fixes prior to approving the PR.

2023-03-30 16:51 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronization-stringkeylongvaluepair.md
> +|key|String| The mapping of the user type from source to target.|
I notice samples in the tracker. Should we document them?
```suggestion
|key|String| The mapping of the user type from the source system to the target system. For example:<br/><li>`User to User` - For Azure AD to Azure AD synchronization <br/><li>`worker to user` - For Workday to Azure AD synchronization. <br/> |
```

2023-03-30 16:51 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronization-synchronizationsecretkeystringvaluepair.md
> +|SkipOutOfScopeDeletions |Determines if accounts that go out of scope will/won’t be disabled in the target.|
This value isn't listed in the table above but it's valid. See my comment above.

2023-04-06 15:10 UTC, rahuln3223 commented on api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
> +|templateId|String| Defines default settings for the provisioning configuration.|
If not implemented, take it out of beta schema as well.
Or document it, and say not implemented.

2023-04-06 15:25 UTC, FaithOmbongi approved these changes
Thank you @rahuln3223. Approved!

2023-04-07 02:39 UTC, merged