education grading categories
microsoftgraph/microsoft-graph-docs pull request #20764
Opened 2023-03-29 15:49 UTC by AshwaniBansal1

education grading categories in assignment settings.

2023-03-29 17:48 UTC, abgreg requested changes

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/resources/assignment-gradingcategories.md
> +description: "A Grading Categories to the existing class-wide settings to weight assignments differently when computing a class average grade."
```suggestion
description: "Add Grading Categories to the existing class-wide settings to weight assignments differently when computing a class average grade."
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/resources/assignment-gradingcategories.md
> +A Grading Categories to the existing class-wide settings to weight assignments differently when computing a class average grade.
```suggestion
Add Grading Categories to the existing class-wide settings to weight assignments differently when computing a class average grade.
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/resources/assignment-gradingcategories.md
> +|id|String|The grading category's ID. This separate ID allows teachers to rename a grading category without losing the link to each assignment.|
```suggestion
|id|String|The grading category's ID.|
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/resources/assignment-gradingcategories.md
> +|id|String|The grading category's ID. This separate ID allows teachers to rename a grading category without losing the link to each assignment.|
I notice that in the doc for an Assignment resource, it also says "Inherited from [entity](https://learn.microsoft.com/en-us/graph/api/resources/entity?view=graph-rest-beta). Read-only." That's also true for this id, so maybe we should add it?

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignmentsettings-update.md
> +### Example 2: Crreate grading categories
```suggestion
### Example 2: Create grading categories
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignmentsettings-update.md
> +            "id": "8bfb6d7f-8634-4f3b-9b6a-b6b6ff663f01",
Please remove the "id" from each category. The standard pattern is that the caller doesn't give an id and the service generates one.
Also maybe we can use names that help the reader to understand a possible use-case. So maybe "Lab", "Homework", "Test"?

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignmentsettings-update.md
> +    "@odata.context": "https://canary.graph.microsoft.com/testprodbetaeduasg_wus2gradingcategories/$metadata#education/classes('37d99af7-cfc5-4e3b-8566-f7d40e4a2070')/assignmentSettings/$entity",
At every point that we're adding "https://canary.graph.microsoft.com/testprodbetaeduasg_wus2gradingcategories", we should probably change it to something more conventional, like "https://graph.microsoft.com/beta".

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/resources/assignment-gradingcategories.md
> +|[Add gradingCategory](../api/educationassignment-add-gradingcategories.md) | [gradingCategory](assignment-gradingcategories.md) | Add a new **gradingCategory**.|
Add link to the Settings page so they can see how to configure the grading categories, not just how to link them to assignments.

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-add-gradingcategories.md
> +description: "Add gradingCategory to the assignments."
```suggestion
description: "Add a gradingCategory to an assignment."
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-add-gradingcategories.md
> +Adds gradingCategory to an [educationAssignment](../resources/educationassignment.md). Only teachers can perform this operation.
```suggestion
Adds a [gradingCategory](../resources/assignment-gradingcategories.md) to an [educationAssignment](../resources/educationassignment.md). Only teachers can perform this operation.
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-add-gradingcategories.md
> +title: "Add gradingCategory"
What determines which folder this page appears under? I'm hoping it'll be under "Assignment" like [this one](https://learn.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta) for clarity.

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-add-gradingcategories.md
> +```
This request body feels more like the example section. Instead here we could mimic what the existing Add Category doc says: 
"In the request body, supply the odata.id of the existing [gradingCategory](../resources/assignment-gradingCategories.md) object to add to this assignment."

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-remove-gradingcategories.md
> +description: "Remove gradingCategory from the assignments."
```suggestion
description: "Remove gradingCategory from the assignment."
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-updatesingle-gradingcategories.md
> +description: "Update single gradingCategory to the assignments."
```suggestion
description: "Update a single gradingCategory."
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-updatesingle-gradingcategories.md
> +title: "Update gradingCategory"
What folder will this appear under? This one seems like it should live under Assignment Settings.

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-updatesingle-gradingcategories.md
> +Update single gradingCategory to an [educationAssignment](../resources/educationassignment.md). Only teachers can perform this operation.
```suggestion
Update a single gradingCategory on the [educationAssignmentSettings](../resources/educationassignmentsettings.md). Only teachers can perform this operation.
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignment-updatesingle-gradingcategories.md
> +If successful, this method returns a `200 OK` response code and an updated [gradingCategory](../resources/educationrubric.md) object in the response body
```suggestion
If successful, this method returns a `200 OK` response code and an updated [gradingCategory](../resources/assignment-gradingcategories.md) object in the response body.
```

2023-03-29 17:48 UTC, abgreg commented on api-reference/beta/api/educationassignmentsettings-update.md
>  ```
We should also have an example that uses a delta payload to delete and modify. It could be one example that deletes, modifies, and adds grading categories so callers can see the full power of the delta payload. i.e.

```json
{
    "gradingCategories@delta": [
        {
            "id": "{modifiedId}",
            "displayName": "New name"
        },
        {
            "@odata.context": "https://graph.microsoft.com/beta/edu/$metadata#gradingCategories/$deletedEntity",
            "id": "{deletedId}",
            "reason": "deleted"
        },
        {
            "displayName": "New name",
            "percentageWeight": "80"
        }
    ]
}
```

2023-04-13 18:06 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-updatesingle-gradingcategories.md
> +title: "Update gradingCategory"
yes, it will be there, including add and remove pages.
Three pages have been added under assignments in the left side menu.

2023-04-18 20:49 UTC, abgreg commented on api-reference/beta/api/educationassignment-add-gradingcategories.md
> +In the request body, supply the odata.id of the existing [gradingCategory](../resources/assignment-gradingcategories.md) object(s) to add to this assignment.
```suggestion
In the request body, supply the odata.id of the existing [gradingCategory](../resources/assignment-gradingcategories.md) object to add to this assignment.
```

2023-04-18 20:49 UTC, abgreg commented on api-reference/beta/api/educationassignment-remove-gradingcategories.md
> +Remove gradingCategory from an [educationAssignment](../resources/educationassignment.md). Only teachers can perform this operation.
```suggestion
Remove a [gradingCategory](../resources/assignment-gradingcategories.md) from an [educationAssignment](../resources/educationassignment.md). Only teachers can perform this operation.
```

2023-04-18 20:49 UTC, abgreg commented on api-reference/beta/api/educationassignment-updatesingle-gradingcategories.md
> +Update a single gradingCategory on the [educationAssignmentSettings](../resources/educationassignmentsettings.md). Only teachers can perform this operation.
```suggestion
Update a single [gradingCategory](../resources/assignment-gradingcategories.md) on the [educationAssignmentSettings](../resources/educationassignmentsettings.md). Only teachers can perform this operation.
```

2023-04-18 20:49 UTC, abgreg commented on api-reference/beta/api/educationassignmentsettings-update.md
> +            "displayName": "Lab Test"
Consider adding comments to each of these objects, like "// Change this grading category's name" and "// Delete this grading category", etc.

2023-04-24 19:19 UTC, dodaromike commented
@AshwaniBansal1 You'll need changelog entries for these new methods.  Please see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2023-04-26 20:05 UTC, cristobal-buenrostro commented
> @AshwaniBansal1 You'll need changelog entries for these new methods. Please see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

@dodaromike , changelog has been added.

2023-04-26 20:28 UTC, dodaromike commented
@AshwaniBansal1 Changelog says "Added the **gradingCategory** relationship to the [educationAssignment] resource.  I think you need to add this relationship to https://learn.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta .

2023-05-01 20:07 UTC, cristobal-buenrostro commented
> @AshwaniBansal1 Changelog says "Added the **gradingCategory** relationship to the [educationAssignment] resource. I think you need to add this relationship to https://learn.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta .
> 
> Including @cristobal-buenrostro

Hi @dodaromike , I added the missed changes according to the changelog, please check and let me know if any further change is needed. Thank you

2023-05-02 22:07 UTC, cristobal-buenrostro commented
@dodaromike added relationship with assignment resource page

2023-05-02 22:53 UTC, dodaromike approved these changes

2023-05-04 03:44 UTC, Lauragra commented
@Danielabom , can you please review this PR before we merge? The file names and titles don't look like they conform to our standards.

2023-05-04 17:59 UTC, cristobal-buenrostro commented
> @Danielabom , can you please review this PR before we merge? The file names and titles don't look like they conform to our standards.


@Danielabom Which ones are not following the standards? I can take a look at those files.

2023-05-08 16:14 UTC, Danielabom commented on api-reference/beta/resources/educationgradingcategory.md
> +description: "Add Grading Categories to the existing class-wide settings to weight assignments differently when computing a class average grade."
```suggestion
description: "Add grading categories to the existing class-wide settings to weight assignments differently when computing a class average grade."
```

2023-05-08 16:16 UTC, Danielabom commented on api-reference/beta/resources/educationgradingcategory.md
> +Add Grading Categories to the existing class-wide settings to weight assignments differently when computing a class average grade.
```suggestion
Add grading categories to the existing class-wide settings to weight assignments differently when computing a class average grade.
```

2023-05-08 17:24 UTC, Danielabom commented on api-reference/beta/resources/educationassignmentsettings.md
>  |:---|:---|:---|
Please add this resource's new methods (List educationGradingCategory and Update educationGradingCategory) in the changelog. See example  6 on this wiki: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2023-05-08 17:30 UTC, Danielabom commented on api-reference/beta/resources/educationassignmentsettings.md
>  ## Relationships
The CSDL indicates that the resource educationAssignmentSettings has a nav property called "gradingCategories". If so, please add it to the resource file and create a changelog entry.

2023-05-08 17:32 UTC, Danielabom commented on api-reference/beta/resources/educationassignment.md
> +|Grading categories|[educationGradingCategory](educationgradingcategory.md) collection| When set, enables users to weight assignments differently when computing a class average grade.|
```suggestion
|grading categories|[educationGradingCategory](educationgradingcategory.md) collection| When set, enables users to weight assignments differently when computing a class average grade.|
```

2023-05-08 17:35 UTC, Danielabom commented on api-reference/beta/resources/educationassignment.md
> +|[List educationGradingCategory](../api/educationassignment-list-gradingcategory.md)|[educationGradingCategory](../resources/educationgradingcategory.md) collection|Get the educationGradingCategory r
Please add this resource's new methods (List educationGradingCategory, Update educationGradingCategory and Remove educationGradingCategory ) in the changelog. See example 6 on this wiki: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2023-05-08 17:40 UTC, Danielabom commented on api-reference/beta/resources/educationassignment.md
> +|grading categories|[educationGradingCategory](educationgradingcategory.md) collection| When set, enables users to weight assignments differently when computing a class average grade.|
```suggestion
|grading categories|[educationGradingCategory](educationgradingcategory.md) collection| When set, it enables users to weight assignments differently when computing a class average grade.|
```

2023-05-08 17:43 UTC, Danielabom commented on api-reference/beta/resources/educationassignment.md
> +|grading categories|[educationGradingCategory](educationgradingcategory.md) collection| When set, it enables users to weight assignments differently when computing a class average grade.|
```suggestion
|grading categories|[educationGradingCategory](educationgradingcategory.md) collection| When set, enables users to weight assignments differently when computing a class average grade.|
```

2023-05-08 17:47 UTC, Danielabom commented on api-reference/beta/resources/educationassignment.md
>  ## Relationships
The CSDL indicates that there's another nav property called  "resources", and the beta and v1 docs also show it. Was it deleted by mistake? Please check.

2023-05-08 17:49 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-05-08 17:49 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-05-08 17:59 UTC, Danielabom commented on api-reference/beta/resources/educationassignment.md
> +|grading categories|[educationGradingCategory](educationgradingcategory.md) collection| When set, enables users to weight assignments differently when computing a class average grade.|
The api.md and the CSDL files indicate that the nav property name is gradingCategory. Please verify.

2023-05-08 18:09 UTC, Danielabom commented on api-reference/beta/api/educationassignmentsettings-update.md
> +### Request
```suggestion
#### Request
```

2023-05-08 18:12 UTC, Danielabom commented on api-reference/beta/api/educationassignmentsettings-update.md
> +### Response
```suggestion
#### Response
```

2023-05-08 18:13 UTC, Danielabom commented on api-reference/beta/api/educationassignmentsettings-update.md
> +### Request
```suggestion
#### Request
```

2023-05-08 18:13 UTC, Danielabom commented on api-reference/beta/api/educationassignmentsettings-update.md
> +### Response
```suggestion
#### Response
```

2023-05-08 18:23 UTC, Danielabom commented on api-reference/beta/resources/educationgradingcategory.md
> +
Please confirm whether the method Educationassignment-list-gradingcategory needs to be in this table or not.

2023-05-08 18:26 UTC, Danielabom commented on api-reference/beta/api/educationassignment-list-gradingcategory.md
> +GET /education/classes/{educationClassId}/assignmentSettings/gradingCategories
GLOBAL COMMENT: Please confirm throughout the entire PR if you have the correct name:  "gradingCategory" or "gradingCategories"

2023-05-08 18:28 UTC, Danielabom requested changes
Hi @cristobal-buenrostro, thank you so much for working on this PR. Please review my comments and please address the following concern: 

GLOBAL COMMENT (applies to all the files in the PR): Please confirm throughout the entire PR if you have the correct name: "gradingCategory" or "gradingCategories". Compare the info on the api.md and the CSDL files.

2023-05-09 23:55 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Added the [Update educationGradingCategory](https://learn.microsoft.com/graph/api/educationgradingcategory-update?view=graph-rest-beta) operation to the [educationAssignment
```suggestion
          "Description": "Added the [Update] (https://learn.microsoft.com/graph/api/educationgradingcategory-update?view=graph-rest-beta) operation to the [educationAssignmentSettings](https://learn.microsoft.com/en-us/graph/api/resources/educationassignmentsettings?view=graph-rest-beta) resource.",
```

2023-05-09 23:56 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Added the [Update educationGradingCategory](https://learn.microsoft.com/graph/api/educationgradingcategory-update?view=graph-rest-beta) operation to the [educationAssignment
```suggestion
          "Description": "Added the [Update] (https://learn.microsoft.com/graph/api/educationgradingcategory-update?view=graph-rest-beta) operation to the [educationAssignmentSettings](https://learn.microsoft.com/en-us/graph/api/resources/educationassignmentsettings?view=graph-rest-beta) resource.",
```

2023-05-09 23:56 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Added the [Update] (https://learn.microsoft.com/graph/api/educationgradingcategory-update?view=graph-rest-beta) operation to the [educationAssignmentSettings](https://learn.
```suggestion
          "Description": "Added the [update] (https://learn.microsoft.com/graph/api/educationgradingcategory-update?view=graph-rest-beta) operation to the [educationAssignmentSettings](https://learn.microsoft.com/en-us/graph/api/resources/educationassignmentsettings?view=graph-rest-beta) resource.",
```

2023-05-10 00:02 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationAssignment"
```suggestion
          "Target": "educationAssignmentSettings"
```

2023-05-10 00:02 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationAssignment"
```suggestion
          "Target": "educationAssignmentSettings"
```

2023-05-10 00:04 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Added the [Remove educationGradingCategory](https://learn.microsoft.com/graph/api/educationassignment-delete-gradingcategory?view=graph-rest-beta) operation to the [educatio
```suggestion
          "Description": "Added the [Remove] (https://learn.microsoft.com/graph/api/educationassignment-delete-gradingcategory?view=graph-rest-beta) operation to the [educationAssignment](https://learn.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta) resource.",
```

2023-05-10 00:05 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Added the [Remove] (https://learn.microsoft.com/graph/api/educationassignment-delete-gradingcategory?view=graph-rest-beta) operation to the [educationAssignment](https://lea
```suggestion
          "Description": "Added the [remove] (https://learn.microsoft.com/graph/api/educationassignment-delete-gradingcategory?view=graph-rest-beta) operation to the [educationAssignment](https://learn.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta) resource.",
```

2023-05-10 00:37 UTC, Danielabom commented on changelog/Microsoft.EducationAssignment.json
> +      "CreatedDateTime": "2023-04-26T16:40:45.6092486Z",
```suggestion
      "CreatedDateTime": "2023-05-09T16:40:45.6092486Z",
```

2023-05-10 00:39 UTC, Danielabom approved these changes
@cristobal-buenrostro, thank you for working on this PR. I just made a couple of final changes. Please look at the build errors and let me know when you are done so I can add the corresponding label. Looks like issues with a couple of response examples.

2023-05-10 18:47 UTC, Danielabom commented
APi Doctor keeps failing with the following error:   Error: list_educationgradingcategory:
      Failed to locate collection property 'value' in response.
@cristobal-buenrostro, indicated that you discussed the issue with @Lauragra. PR approved.

2023-05-16 03:59 UTC, merged