docs: update how to theme components with mgt-toggle-theme
microsoftgraph/microsoft-graph-docs pull request #20777
Opened 2023-03-30 12:49 UTC by musale

Closes https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/2086

2023-03-30 12:50 UTC, musale commented
CC @sebastienlevert @gavinbarron @Mnickii for your review. I don't have assign permissions.

2023-04-01 01:29 UTC, Lauragra commented
@musale , if you'rea ready for us to review and/or merge your PRs. please set the **ready for content review** and **ready to merge** labels. Thanks.

2023-04-04 14:27 UTC, Mnickii commented on concepts/toolkit/customize-components/style.md
>      <article><mgt-agenda></mgt-agend></article>
```suggestion
    <article><mgt-agenda></mgt-agenda></article>
```

2023-04-06 19:25 UTC, sebastienlevert requested changes
I'd love to see a part of this article to cover the programmatical way to toggle theming without the toggle component. This will be super important for Teams tabs, Office.com apps, etc.

2023-04-12 13:21 UTC, musale commented
> @musale , if you'rea ready for us to review and/or merge your PRs. please set the **ready for content review** and **ready to merge** labels. Thanks.

@Lauragra I'm unable to edit the labels. Could you grant me the permissions?

2023-04-18 09:39 UTC, musale commented
> I'd love to see a part of this article to cover the programmatical way to toggle theming without the toggle component. This will be super important for Teams tabs, Office.com apps, etc.

I have added this @sebastienlevert , you can check it out :)

2023-04-19 23:54 UTC, gavinbarron commented on concepts/toolkit/customize-components/style.md
> +Two themes are available - `light` and `dark`. These themes are supported out of the box because the mgt components are upgraded to use [Fluent UI web elements](/fluent-ui/web-components/) under the
We also have teams-light and teams-dark options available for code based theming. 
However I'm pretty comfortable not documenting those yet as we need to do work to align them better with the Teams themes. 
@sebastienlevert thoughts on this?

2023-04-24 18:38 UTC, sebastienlevert commented on concepts/toolkit/customize-components/style.md
> +Two themes are available - `light` and `dark`. These themes are supported out of the box because the mgt components are upgraded to use [Fluent UI web elements](/fluent-ui/web-components/) under the
It seems we support "default", "light", "dark" and "contrast" today. I'd document only "light" and "dark" until we have a stronger Teams story here.

2023-04-24 18:46 UTC, sebastienlevert approved these changes

2023-04-26 02:25 UTC, Lauragra approved these changes

2023-04-26 02:25 UTC, merged