Subscriptions API and SubscribedSkus API
microsoftgraph/microsoft-graph-docs pull request #20804
Opened 2023-03-31 21:39 UTC by arp19690

2023-04-01 01:49 UTC, Lauragra commented
@arp19690 , please follow the get started steps to set yourself up to contribute to the repo: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started. When you're ready for use to review your PR, please set the **ready for content review** label; for details, see the content workflow topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow.

2023-04-08 02:42 UTC, mercur1114 commented
Hasan pekyürek

2023-04-19 07:24 UTC, FaithOmbongi commented
Hi @arp19690 - Please open a content review work item here https://aka.ms/msgraph-identity-workitem

Also, while this PR hasn't yet been approved, remember to download, and save the docStubs folder before they are deleted 15 days after the last run. It will help you just in case you find you're missing a file or a changelog in this PR.

2023-04-20 16:07 UTC, FaithOmbongi requested changes
Hi @arp19690 - I notice that the schema PRs you linked to are all for private preview. Are these features really targeting public preview? Please clarify.

If the features are targeting public preview:

- Please raise schema PRs making these features live through the schema-Prod-beta.csdl file.
- On the docs PR, doc stubs will be autogenerated. Please _always_ start new documentation from doc stubs.
- Please refer to the contributor guide https://aka.ms/msgraphcdk for guidance on the end-to-end process.

Feel free to ping me on Teams to answer any questions. Thank you.

2023-05-05 03:53 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +          - name: Company Subscriptions
The position of "Company subscriptions" in the TOC is different in the v1.0 and BETA TOCs. Please, ensure that "Company subscriptions" endpoints are in the right place in the TOC.

2023-05-05 03:55 UTC, JarbasHorst commented
Hello @arp19690, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [21190](https://github.com/microsoftgraph/microsoft-graph-docs/pull/21190) into your branch to include my fixes and before addressing my comments.

2023-05-08 03:53 UTC, Jarbas-MSFT commented on api-reference/beta/api/companysubscriptions-get.md
> +author: "**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**"
TODO: Provide Github Name. 🙂

Same here: 
- api-reference/beta/api/companySubscriptions-list.md
- api-reference/v1.0/api/companySubscriptions-get.md
- api-reference/v1.0/api/companySubscriptions-list.md
- api-reference/beta/resources/companySubscriptions.md
- api-reference/v1.0/resources/companySubscriptions.md

2023-05-08 03:53 UTC, Jarbas-MSFT commented on api-reference/beta/api/companysubscriptions-get.md
> +ms.prod: "**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**"
TODO: Add MS prod. 🙂

Same here: 
- api-reference/beta/api/companySubscriptions-list.md
- api-reference/v1.0/api/companySubscriptions-get.md
- api-reference/v1.0/api/companySubscriptions-list.md
- api-reference/beta/resources/companySubscriptions.md
- api-reference/v1.0/resources/companySubscriptions.md

2023-05-08 03:53 UTC, Jarbas-MSFT commented on api-reference/beta/api/companysubscriptions-get.md
> +GET https://graph.microsoft.com/beta/directory/subscriptions/{ocpSubscriptionId}
For clarity, please replace the placeholders, such as {ocpSubscriptionId}, with a real-looking ID. Examples with real-looking values in the, request URL, requests and response bodies help customers understand the API better. That's also the consistency bar for Microsoft Graph API docs.

2023-05-08 03:53 UTC, Jarbas-MSFT commented on api-reference/beta/toc.yml
> +          - name: Company subscriptions
The position of "Company subscriptions" in the TOC is different in the v1.0 and BETA TOCs. Please, ensure that "Company subscriptions" endpoints are in the right place in the TOC.

2023-05-08 03:53 UTC, Jarbas-MSFT commented on api-reference/beta/resources/companysubscriptions.md
> +| Property                | Type                                             | Description                                                                |
The **companySubscriptions** resource inherits from **directoryObject**. In this case, please add the **deletedDateTime** property to the Properties table and the JSON representation section.

Same here: 
- api-reference/v1.0/resources/companysubscriptions.md

2023-05-08 03:55 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +|appliesTo|String| For example, `User` or `Company`. |
Please, provide a description that better describes this property.

2023-05-08 03:55 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +|capabilityStatus|String| Possible values are: `Enabled`, `Warning`, `Suspended`, `Deleted`, `LockedOut`. The **capabilityStatus** is `Enabled` if the **prepaidUnits** property has at least one unit
Please, provide a sentence in the Description that explains the capabilityStatus property.

2023-05-10 04:44 UTC, JarbasHorst commented on changelog/Microsoft.DirectoryServices.json
> +    {
Please, add also the **companySubscriptions** resource to the changelog. Note that you should have two changelog records: one for the BETA and another for the v1.0 changes.

2023-05-11 18:34 UTC, arp19690 commented on api-reference/beta/resources/companysubscriptions.md
> +| Property                | Type                                             | Description                                                                |
I don't think we want to expose deletedDateTime in the API response.
The internal API reviews does not say so

2023-05-15 03:46 UTC, Jarbas-MSFT commented on api-reference/beta/api/subscribedsku-list.md
> +      "accountName": "accountName-value",
Please, replace the values for **accountName**, **accountId**, **appliesTo**, **skuPartNumber**, and **subscriptionIds** with real-looking values.

2023-05-15 03:46 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +|appliesTo|String| For example, `User` or `Company`. |
Please, provide a description that better describes this property.

2023-05-15 03:46 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +|capabilityStatus|String| Possible values are: `Enabled`, `Warning`, `Suspended`, `Deleted`, `LockedOut`. The **capabilityStatus** is `Enabled` if the **prepaidUnits** property has at least one unit
Please, provide a sentence in the Description that explains the capabilityStatus property.

2023-05-15 03:46 UTC, Jarbas-MSFT commented on changelog/Microsoft.DirectoryServices.json
> +    {
Please, add also the **companySubscriptions** resource to the changelog. Note that you should have two changelog records: one for the BETA and another for the v1.0 changes.

2023-05-15 03:49 UTC, Jarbas-MSFT commented
Hello @arp19690, thanks for addressing some of my previous comments. Please, take a look at the remaining comments when you will have time. 

Also, please take a look at Faith's comment: https://github.com/microsoftgraph/microsoft-graph-docs/pull/20804#pullrequestreview-1394334693

2023-06-01 04:42 UTC, Jarbas-MSFT commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **subscriptions** relationship to the [directory](https://learn.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta) resource.",
If this change should be introduced via this PR, please update the directory resource topic to include this new subscription. Otherwise, remove this entry from the changelog.

Same for line 13652.

2023-06-01 04:42 UTC, Jarbas-MSFT commented on api-reference/beta/api/subscribedsku-list.md
> +      "accountName": "accountName-value",
Please, replace the values for **accountName**, **accountId**, **appliesTo**, **skuPartNumber**, and **subscriptionIds** with real-looking values.

2023-06-01 04:42 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +|appliesTo|String| For example, `User` or `Company`. |
Please, provide a description that better describes this property.

2023-06-01 04:42 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +|capabilityStatus|String| Possible values are: `Enabled`, `Warning`, `Suspended`, `Deleted`, `LockedOut`. The **capabilityStatus** is `Enabled` if the **prepaidUnits** property has at least one unit
Please, provide a sentence in the Description that explains the capabilityStatus property.

2023-06-13 20:20 UTC, arp19690 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **subscriptions** relationship to the [directory](https://learn.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta) resource.",
Updated.

2023-06-15 07:22 UTC, FaithOmbongi commented
Hi @Jarbas-MSFT - The work item now has links to the PROD schemas and this PR can now be reviewed.

2023-06-19 05:13 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +| accountId        | String                                           | The unique ID of the account this SKU belongs to.
Please, share with me a pointer to the PROD schema in BETA that contains the addition of these properties to the **subscribedsku** resource. In the work item you shared, I can only find the changes for v1.0.

2023-06-19 05:13 UTC, Jarbas-MSFT commented on api-reference/v1.0/resources/companysubscriptions.md
> +---
Please, share with me a pointer to the PROD schema in v1.0 that contains the addition of this resource. In the work item you shared, I can only find the changes for BETA.

2023-06-19 05:13 UTC, Jarbas-MSFT commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **subscriptions** relationship to the [directory](https://learn.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-1.0) resource.",
I don't see any associated documentation update for this relationship. Please, update this docs accordingly.

Please, share with me a pointer to the PROD schema in v1.0 that contains the addition of this resource. In the work item you shared, I can only find the changes for BETA.

2023-06-19 05:13 UTC, Jarbas-MSFT commented
Hi @arp19690, I reviewed your PR again and left some comments. Please, take a look when you will have time.

2023-06-19 17:26 UTC, arp19690 commented on api-reference/beta/resources/subscribedsku.md
> +| accountId        | String                                           | The unique ID of the account this SKU belongs to.
It is already shared in the work-item, pasting it here as well.
https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/8107428

2023-06-19 17:28 UTC, arp19690 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **subscriptions** relationship to the [directory](https://learn.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-1.0) resource.",
We have not rolled it out on Prod yet, because the partners are currently integrating on Prod-beta and once the integration tests are done, then we will roll it out on Prod-v1.

2023-06-19 17:28 UTC, arp19690 commented on api-reference/v1.0/resources/companysubscriptions.md
> +---
We have not rolled it out on Prod yet, because the partners are currently integrating on Prod-beta and once the integration tests are done, then we will roll it out on Prod-v1.

2023-06-19 17:29 UTC, arp19690 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **lockedOut** property to the [licenseUnitsDetail](https://learn.microsoft.com/en-us/graph/api/resources/licenseUnitsDetail?view=graph-rest-1.0) resource.",
Updated licenseUnitsDetail.md for both Beta and V1.

2023-06-19 17:36 UTC, arp19690 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **subscriptions** relationship to the [directory](https://learn.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-1.0) resource.",
Updated directory.md for both Beta and V1.

We have not rolled it out on Prod yet, because the partners are currently integrating on Prod-beta and once the integration tests are done, then we will roll it out on Prod-v1.

2023-06-20 05:18 UTC, Jarbas-MSFT commented on api-reference/beta/resources/licenseunitsdetail.md
> +| lockedOut | Int32 | The number of units that are locked out because the customer cancelled their subscription. SKU.
The description ends with ". SKU." which isn't clear. For clarity, I recommend the following revision:

- "...because the customer cancelled their subscription of the service SKU."

Same for api-reference/v1.0/resources/licenseunitsdetail.md

2023-06-20 05:18 UTC, Jarbas-MSFT commented on api-reference/beta/resources/subscribedsku.md
> +| accountId        | String                                           | The unique ID of the account this SKU belongs to.
@arp19690, this work item is only about "exposing more properties on SubscribedSkus - ProdV1". We need basically the same, but for schema-Prod-beta.csdl.

2023-06-20 05:18 UTC, Jarbas-MSFT commented on api-reference/v1.0/resources/companysubscriptions.md
> +---
I will check internally how to continue with the review in this case. Usually, we don't expose documentation for features that haven't been rolled out yet.

Same here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/20804#discussion_r1234310234

2023-06-22 03:35 UTC, Jarbas-MSFT commented on api-reference/beta/api/companysubscriptions-get.md
> +GET /directory/subscriptions/{ocpSubscriptionId}
Now that the property name has changed, should this placeholder "{ocpSubscriptionId}" be replaced with "{commerceSubscriptionId}"?

Same for api-reference/v1.0/api/companysubscriptions-get.md

2023-06-23 04:29 UTC, Jarbas-MSFT commented on api-reference/beta/api/companysubscription-get.md
> +GET /directory/subscriptions/{ocpSubscriptionId}
Now that the property name has changed, should this placeholder "{ocpSubscriptionId}" be replaced with "{commerceSubscriptionId}"?

Same for api-reference/v1.0/api/companysubscriptions-get.md

2023-07-12 19:05 UTC, FaithOmbongi requested changes
Thank you @arp19690 for your work on this PR. I've left a few suggestions inline.

**I've only reviewed the beta API docs. But all the feedback applies to the v10 companySubscription docs as well.**

**Suggestion:** With the latest announcement about [retirement of the MSOL licensing APIs](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/migrate-your-apps-to-access-the-license-managements-apis-from/ba-p/2464366), there have been a lot of customer questions relating to licensing. I don't understand the entire mass of the licensing APIs in Graph, but I have a suggestion: _If you think it'll benefit customers to have a how-to about tenant license management capabilities on Graph, I'm happy to work with you on that. Let's talk about this internally._


PS: This API hasn't been deployed in v1.0, and even the schema PR 8315348 is still in draft. If you don't intend to release both beta and v1.0 at the same time, you can remove the v1.0 changes from your branch, publish the beta docs, then when ready to publish v1.0 docs, raise a separate PR for v1.0. The GA process is as simple as copy-paste from beta and you won't need to start from the doc stubs.

2023-07-12 21:30 UTC, arp19690 commented on api-reference/beta/resources/directory.md
> +| subscriptions                      | [subscription](companysubscription.md) collection                                       | List of commercial subscriptions that an organization has acquired.
Subscriptions can be acquired by users and company both, that is why we want it to be called companySubscription explicitly.

2023-07-12 21:37 UTC, arp19690 commented on api-reference/beta/toc.yml
> +            href: api/companysubscription-get.md
Thanks for the suggestion. We would like to keep uniformity at all the places, all our internal docs, and communication with our partners. We would like to keep it Company Subscription for now.

2023-07-13 00:30 UTC, arp19690 commented on api-reference/beta/resources/companysubscription.md
> +| ownerType              | String                                           | Indicates the entity that **ownerId** belongs to, for example, "User".
They are there, here is the PR for it:
https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/8387913

2023-07-13 00:33 UTC, arp19690 commented on api-reference/beta/resources/subscribedsku.md
> +| subscriptionsIds | String collection                                | A list of all subscription IDs associated with this SKU.
An SKU can be in multiple Subscriptions while the vice-versa can't be the case, therefore these 2 APIs are very similar to each other but with a minor difference.

2023-07-13 00:41 UTC, arp19690 commented on api-reference/beta/resources/companysubscription.md
> +Represents subscriptions for a tenant.
These 2 APIs are similar and being exposed on MS Graph as a part of BEC --> MSGraph migrations. SubscribedSkus was already exposed on MS Graph, it just needs minor change while Subscriptions needs to be rolled out as a totally new API. We have existing clients and partners using the BEC version of these APIs and to help them onboard on MS Graph we are exposing these APIs along with their exact structure to MS Graph to help them onboard sooner. As you have already noticed that there is only minor differences between the responses of these 2 APIs, we would still want to keep both of these to continue to provide support to our clients and partners.

2023-07-13 15:34 UTC, arp19690 commented on api-reference/beta/resources/subscribedsku.md
> +| accountId        | String                                           | The unique ID of the account this SKU belongs to.
The account ID will be the tenantId except for system subscriptions where it will be an empty Guid

2023-07-13 15:35 UTC, arp19690 commented on api-reference/beta/resources/companysubscription.md
> +| nextLifecycleDateTime  | DateTimeOffset                                   | The date and time of the next lifecycle event for this subscription. The DateTimeOffset type represents date and time inf
nextLifecycleDateTime  would be the date when the subscription will move to the next state if not renewed by the tenant, that is managed by commerce, the subscriptions will move through warning, suspended, lockedout and deleted. Not sure it would make sense to have documentation in AAD for this as they are managed from commerce/azure?

2023-07-13 16:00 UTC, arp19690 commented
> Thank you @arp19690 for your work on this PR. I've left a few suggestions inline.
> 
> **I've only reviewed the beta API docs. But all the feedback applies to the v10 companySubscription docs as well.**
> 
> **Suggestion:** With the latest announcement about [retirement of the MSOL licensing APIs](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/migrate-your-apps-to-access-the-license-managements-apis-from/ba-p/2464366), there have been a lot of customer questions relating to licensing. I don't understand the entire mass of the licensing APIs in Graph, but I have a suggestion: _If you think it'll benefit customers to have a how-to about tenant license management capabilities on Graph, I'm happy to work with you on that. Let's talk about this internally._
> 
> PS: This API hasn't been deployed in v1.0, and even the schema PR 8315348 is still in draft. If you don't intend to release both beta and v1.0 at the same time, you can remove the v1.0 changes from your branch, publish the beta docs, then when ready to publish v1.0 docs, raise a separate PR for v1.0. The GA process is as simple as copy-paste from beta and you won't need to start from the doc stubs.

Removed companySubscription from v1.0

2023-07-18 07:49 UTC, FaithOmbongi commented
Re-requested review.

2023-07-18 15:13 UTC, FaithOmbongi commented on api-reference/beta/resources/companysubscription.md
> +Represents subscriptions for a tenant.
Hmm noted. Then we need to find a way to have both co-exist without confusion. Can we say companySubscriptio is recommended API for new users? Is there intent to maybe deprecated subscribedSkus? Or is it the customers' choice and the only reason we have both is as you've explained to help BEC users migrate?

2023-07-18 15:33 UTC, FaithOmbongi approved these changes
Hi @arp19690 -

I've left mostly minor suggestions based on your last feedback. The only two major suggestions relate to the changelog and the TOC grouping.

Otherwise, approved with comments.

2023-07-18 15:33 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +            href: api/companysubscription-get.md
I understand your feedback about the term "subscription" and how it'll support consistency. What about "Tenant subscriptions"?

So it will be :

> Tenant subscriptions
>       Subscribed SKU
>            LIST
>            GET
>       Company subscription
>            LIST
>            GET


My thinking is that these two sets of APIs can be used concurrently and clearly twins. We need to help with their discoverability. And in case we can publish an API Overview, it'll be easier if it's one overview for all subscription/license management features in Graph.

2023-07-18 15:45 UTC, FaithOmbongi approved these changes
Hi @arp19690 - I noticed in your new schema PR 8387913 that you introduced two alternate keys. So I've left suggestions for calling them out in the documentation.

Again, approved with suggestions.

2023-07-18 15:45 UTC, FaithOmbongi commented on api-reference/beta/resources/companysubscription.md
> +| commerceSubscriptionId | String                                           | The ID of this subscription in the commerce system.
```suggestion
| commerceSubscriptionId | String                                           | The ID of this subscription in the commerce system. Alternate key.                                                                                                                                                                                                   |
```

2023-07-18 15:45 UTC, FaithOmbongi commented on api-reference/beta/resources/companysubscription.md
> +| ownerId                | String                                           | The object ID of the account admin.
Document the ocpSubscriptionId here and in the JSON representation section. Make sure to mark it as "Alternate key".

2023-07-18 15:45 UTC, FaithOmbongi commented on api-reference/beta/api/companysubscription-get.md
> +GET /directory/subscriptions/{commerceSubscriptionId}
The syntax for alternate keys is very different from the syntax for the ID key. You must document all the key syntaxes because there's a reason you're supporting all of them.

You can refer to the [Get application](https://learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=http#http-request) doc where appId is also an alternate key.
```suggestion
GET /directory/subscriptions/{companySubscriptionId}
GET /directory/subscriptions(commerceSubscriptionId={'commerceSubscriptionId'})
GET /directory/subscriptions(ocpSubscriptionId={'ocpSubscriptionId'})
```

2023-07-18 20:58 UTC, merged