Ship queryTemplate to v1.0 doc
microsoftgraph/microsoft-graph-docs pull request #20829
Opened 2023-04-04 08:14 UTC by yiwenwang-ms

2023-04-11 07:08 UTC, FaithOmbongi commented
Hi @angelgolfer-ms, @Jarbas-MSFT, @Danielabom - FYI

2023-04-13 00:56 UTC, Danielabom commented
Contacted author to get info.

2023-04-14 01:19 UTC, Danielabom commented on api-reference/v1.0/api/search-query.md
> +The following example shows how to perform a search to get expected connector items.
```suggestion
The following example shows how to search for expected connector items.
```

2023-04-14 01:20 UTC, Danielabom commented on api-reference/v1.0/api/search-query.md
> +POST https://graph.microsoft.com/beta/search/query
Quick question, why did you change the version?  Thanks.

2023-04-17 12:00 UTC, yiwenwang-ms commented on api-reference/v1.0/api/search-query.md
> +POST https://graph.microsoft.com/beta/search/query
Thank you, that's a mistake. Corrected.

2023-04-18 17:50 UTC, Danielabom requested changes
@yiwenwang-ms, thank you for working on this PR. Please review my comments.

2023-04-18 17:50 UTC, Danielabom commented on changelog/Microsoft.Search.json
> +          "Description": "Added queryTemplate to the search [query](https://learn.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0).",
This is the link for the action and the "queryTemplate" property belongs to the searchQuery resource, please update the link in the description. Thanks.

2023-04-19 09:27 UTC, yiwenwang-ms commented on changelog/Microsoft.Search.json
> +          "Description": "Added queryTemplate to the search [query](https://learn.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0).",
Thanks, done!

2023-04-20 02:38 UTC, merged