Update deviceregistrationpolicy.md
microsoftgraph/microsoft-graph-docs pull request #20845
Opened 2023-04-05 04:20 UTC by SanDeo-MSFT

2023-04-05 13:17 UTC, myra-ramdenbourg approved these changes

2023-04-12 17:00 UTC, FaithOmbongi requested changes
Thank you @SanDeo-MSFT for your work on this PR.

Your API.md and schema PR don't match with regard to localadminpasswordsettings. Please match them so the docs can be compared with them.

For the changelog, you should add it as a separate object in the collection, not inside an existing object.

2023-04-12 17:00 UTC, FaithOmbongi commented on changelog/Microsoft.DeviceRegistrationPolicies.json
> +                },
If localAdminPasswordSettings complex type has an isEnabled property, then delete this changelog object. The reason this object was generated is because according to your schema PR (which differs from the API.md in this matter), localAdminPasswordSettings  no longer exposes a property.

2023-04-12 17:00 UTC, FaithOmbongi commented on changelog/Microsoft.DeviceRegistrationPolicies.json
Add the changelog as a separate object in the collection, not inside an existing object.

WorkloadArea will be "Identity and access"
SubArea will be "Identity and sign-in"

To align with the information architecture.

2023-04-12 19:21 UTC, michaelrm97 commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +PATCH https://graph.microsoft.com/beta/deviceRegistrationPolicy
PATCH is not currently supported for deviceRegistrationPolicy

2023-04-12 19:30 UTC, michaelrm97 commented on api-reference/beta/resources/localadminpasswordsettings.md
Was an error in the schema PR which I have since fixed

2023-04-14 08:09 UTC, FaithOmbongi requested changes
Hi @SanDeo-MSFT - One oversight from the previous review: please surface the API docs in the TOC.

2023-04-14 18:14 UTC, SanDeo-MSFT commented
> Hi @SanDeo-MSFT - One oversight from the previous review: please surface the API docs in the TOC.

Device registration policy (preview) is already present in the TOC.

2023-04-18 10:04 UTC, FaithOmbongi approved these changes
LGTM!

2023-04-19 00:50 UTC, merged