[Doc Improvement] [Updates teams app settings]
microsoftgraph/microsoft-graph-docs pull request #20848
Opened 2023-04-05 07:19 UTC by v-ganr

2023-04-11 17:57 UTC, Danielabom commented
Contacted author to get info.

2023-04-13 00:37 UTC, Danielabom commented on api-reference/beta/api/teamsappsettings-update.md
> +|allowUserRequestsForAppAccess|Boolean|Indicates whether Teams users are allowed to request unavailable Teams apps.|
I am a little confused here. Are the users no longer requesting access to the app but requesting an unavailable app download?

2023-04-13 00:37 UTC, Danielabom commented on api-reference/beta/resources/teamsappsettings.md
> +|allowUserRequestsForAppAccess|Boolean|Indicates whether Teams users are allowed to request unavailable Teams apps.|
I am a little confused here. Are the users no longer requesting access to the app but requesting an unavailable app download?

2023-04-13 00:38 UTC, Danielabom requested changes
Hi @v-ganr, thank you for working on this PR. I just have a couple of questions. Thanks!

2023-04-18 05:34 UTC, v-ganr commented on api-reference/beta/resources/teamsappsettings.md
> +|allowUserRequestsForAppAccess|Boolean|Indicates whether Teams users are allowed to request unavailable Teams apps.|
Hi @Danielabom 

I have updated the description as " Indicates whether users are allowed to request access to unavailable Teams apps"

2023-04-18 05:35 UTC, v-ganr commented on api-reference/beta/api/teamsappsettings-update.md
> +|allowUserRequestsForAppAccess|Boolean|Indicates whether Teams users are allowed to request unavailable Teams apps.|
Hi @Danielabom 

I have updated the description as " Indicates whether users are allowed to request access to unavailable Teams apps."

2023-04-20 00:23 UTC, Danielabom approved these changes
Thank you for working on this PR @v-ganr. PR approved.

2023-04-21 01:17 UTC, merged