Updating CallRecords API documentation - New fields added
microsoftgraph/microsoft-graph-docs pull request #20859
Opened 2023-04-05 23:13 UTC by Datar89

We're including 8 new properties to the current response. We're not changing any behavior as part of these changes. The new properties that you will find are:

- New property for microsoft.graph.callRecords.session
    - isTest: Flag to indicate if the session corresponded to a session within test call.

- New properties for microsoft.graph.callRecords.participantEndpoint
    - name: Name of the device used by the media endpoint.
    - cpuName: CPU name used by the media endpoint.
    - cpuCoresCount: CPU cores count for the device used by the media endpoint.
    - cpuProcessorSpeedInMhz: CPU processor speed for the device used by the media endpoint.

- New properties for microsoft.graph.callRecords.mediaStream
    - rmsFreezeDuration: Root mean square for the received freeze duration related with the video stream.
    - averageFreezeDuration: Average for the received freeze duration related with video stream.
    - isAudioForwardErrorCorrectionUsed: Flag to indicate if the forward error correction (FEC) was used at some point in the call session.

**As part of this PR, we're updating** the examples for our API and definitions of the entities where the new fields were defined.

----------------------------------------------------------------

API Review: [Pull request 13002: 16271-adding-p1-fields-to-call-records-api - Repos (visualstudio.com)](https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/13002?path=/reviews/3806-ic3-data-platform-call-records-api-schema-extension/api.md&discussionId=156383)

CSDL File: [Pull request 7869180: [Beta] Adding new approved fields for CallRecords API - Repos (azure.com)](https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/7869180?path=/Workloads/Microsoft.IC3.DataPlatform/override/schema-Prod-beta.csdl)

Roadmap item: Feature 16881 https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/16881

2023-04-06 02:12 UTC, Lauragra commented
@Datar89 , please include a changelog record to call out the addition of the new properties. Thanks.

2023-04-06 03:25 UTC, GageAmes requested changes

2023-04-06 03:25 UTC, GageAmes commented on api-reference/beta/resources/callrecords-mediastream.md
> +|rmsFreezeDuration|Duration|Root mean square for the received freeze duration related with video stream.|
It appears `rmsFreezeDuration` may have been missed in the JSON representation below: https://github.com/microsoftgraph/microsoft-graph-docs/blob/13cfa77476bc58d4e2548a07fd2d5a2d2ea033b7/api-reference/beta/resources/callrecords-mediastream.md?plain=1#L91-L92

2023-04-06 03:25 UTC, GageAmes commented on api-reference/beta/resources/callrecords-participantendpoint.md
> +    "userAgent": {"@odata.type": "microsoft.graph.callRecords.userAgent"},"feedback": {"@odata.type": "microsoft.graph.callRecords.userFeedback"},"name": "String",
Please place the `feedback` and `name` properties on separate lines

2023-04-11 17:20 UTC, Datar89 commented on api-reference/beta/resources/callrecords-participantendpoint.md
> +    "userAgent": {"@odata.type": "microsoft.graph.callRecords.userAgent"},"feedback": {"@odata.type": "microsoft.graph.callRecords.userFeedback"},"name": "String",
Done @GageAmes. Thanks!

2023-04-11 18:30 UTC, Danielabom commented
Contacted author to get info.

2023-04-11 19:00 UTC, mcm223 approved these changes

2023-04-13 00:08 UTC, Danielabom commented on api-reference/beta/resources/callrecords-session.md
> +|isTest|Boolean|True if session correspond to a test.|
Suggested description: Specifies if the session is a test.
And if there's a default value,  The default value is _______.

2023-04-13 00:18 UTC, Danielabom commented on api-reference/beta/resources/callrecords-mediastream.md
> +|averageFreezeDuration|Duration|Average for the received freeze duration related with video stream.|
```suggestion
|averageFreezeDuration|Duration|Average of the received freeze duration related to the video stream.|
```

2023-04-13 00:20 UTC, Danielabom commented on api-reference/beta/resources/callrecords-mediastream.md
> +|isAudioForwardErrorCorrectionUsed|Boolean|True if the forward error correction (FEC) was used at some point during session, false otherwise. Null if no information was registered.|
```suggestion
|isAudioForwardErrorCorrectionUsed|Boolean|Indicates if the forward error correction (FEC) was used at some point during the session. Null if no information was registered.|
```

2023-04-13 00:21 UTC, Danielabom commented on api-reference/beta/resources/callrecords-mediastream.md
> +|isAudioForwardErrorCorrectionUsed|Boolean|Indicates if the forward error correction (FEC) was used at some point during the session. Null if no information was registered.|
@Datar89 does the property have a default value?

2023-04-13 00:22 UTC, Danielabom commented on api-reference/beta/resources/callrecords-mediastream.md
> +|rmsFreezeDuration|Duration|Root mean square for the received freeze duration related with video stream.|
```suggestion
|rmsFreezeDuration|Duration|Root mean square of the received freeze duration related to the video stream.|
```

2023-04-13 00:23 UTC, Danielabom requested changes
@Datar89, thank you for working on this PR. I added comments; please review them. Thanks!

2023-04-14 01:10 UTC, Danielabom commented on api-reference/beta/resources/callrecords-session.md
> +|isTest|Boolean|True if session correspond to a test otherwise false.|
```suggestion
|isTest|Boolean|Specifies if the session is a test.|
```

2023-04-14 01:12 UTC, Danielabom commented on api-reference/beta/resources/callrecords-mediastream.md
> +|isAudioForwardErrorCorrectionUsed|Boolean|True if the forward error correction (FEC) was used at some point during session, false otherwise. The default value is null in the case that no information
```suggestion
|isAudioForwardErrorCorrectionUsed|Boolean|Indicates if the forward error correction (FEC) was used at some point during the session. The default value is null.|
```

2023-04-14 01:14 UTC, Danielabom approved these changes
Thank you for working on this PR @Datar89. PR approved.

2023-04-25 03:20 UTC, merged