FilePlanDescriptors for RetentionLabels
microsoftgraph/microsoft-graph-docs pull request #20879
Opened 2023-04-07 23:50 UTC by sseth-msft

2023-04-13 16:34 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-appliedcategory.md
> +title: "appliedCategory resource type"
This complex type appears as `filePlanAppliedCategory` in the api.md file. Please review.

2023-04-13 16:36 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-appliedcategory.md
> +description: "Represents the unique category applied to a retention label."
```suggestion
description: "Represents a unique category applied to a retention label."
```

2023-04-13 17:22 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-appliedcategory.md
> +|subCategory|[microsoft.graph.security.subCategory](../resources/security-fileplandescriptor-subcategory.md)|**TODO: Add Description**|
Please add a description.

2023-04-13 17:37 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authority.md
> +description: "Represents the unique authority applied to a retention label."
```suggestion
description: "Represents a unique authority applied to a retention label."
```

2023-04-13 17:38 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authority.md
> +Represents the unique authority applied to a retention label.
```suggestion
Represents a unique authority applied to a retention label.
```

2023-04-13 17:42 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authority.md
> +|displayName|String|Unique string that defines a authority name. Inherited from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).|
```suggestion
|displayName|String|Unique string that defines an authority name. Inherited from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).|
```

2023-04-13 17:58 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +description: "**Represents the 'authority' file plan descriptor for retention labels."
```suggestion
description: "Represents the authority file plan descriptor for retention labels."
```

2023-04-13 18:05 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +Represents the 'authority' file plan descriptor for retention labels.
```suggestion
Represents the authority file plan descriptor for retention labels.
```

2023-04-13 18:08 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +description: "Represents the authority file plan descriptor for retention labels."
What is the purpose of the authority template? We have 4 nouns together, and it might confuse users. Perhaps, we can come up with a better description.

2023-04-13 18:08 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +Represents the authority file plan descriptor for retention labels.
What is the purpose of the authority template? We have 4 nouns together, and it might confuse users. Perhaps, we can come up with a better description.

2023-04-13 18:29 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +|Method|Return type|Description|
I wanted to confirm that we have the correct methods here, but I did not find them in the api.md file.

2023-04-13 23:16 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +|displayName|String|Unique string that defines a authority name. Inherited from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).|
```suggestion
|displayName|String|Unique string that defines an authority name. Inherited from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).|
```

2023-04-13 23:16 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-categorytemplate.md
> +description: "Represents the 'category' file plan descriptor for retention labels."
```suggestion
description: "Represents the category file plan descriptor for retention labels."
```

2023-04-13 23:17 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-categorytemplate.md
> +Represents the 'category' file plan descriptor for retention labels.
```suggestion
Represents the category file plan descriptor for retention labels.
```

2023-04-13 23:29 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-categorytemplate.md
> +Represents the category file plan descriptor for retention labels.
What is the purpose of the categoryTemplate? We have 4 nouns together, and it might confuse users. Perhaps, we can come up with a better description.

2023-04-13 23:30 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-categorytemplate.md
> +description: "Represents the category file plan descriptor for retention labels."
What is the purpose of the categoryTemplate? We have 4 nouns together, and it might confuse users. Perhaps, we can come up with a better description.

2023-04-13 23:32 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +|Method|Return type|Description|
Since the filenames of the resources are incorrect, some method names need to be corrected as well.

2023-04-13 23:35 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-appliedcategory.md
> +---
The filenames are incorrect, please review the following wiki: (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace)

2023-04-13 23:36 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-categorytemplate.md
> +|Method|Return type|Description|
Since the filenames of the resources are incorrect, some method names need to be corrected as well.

2023-04-13 23:39 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-categorytemplate.md
> +|subCategories|[microsoft.graph.security.subCategoryTemplate](../resources/security-fileplandescriptor-subcategorytemplate.md) collection|**TODO: Add Description**|
Please add a valid description.

2023-04-13 23:41 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-citation.md
> +|citationUrl|String|**TODO: Add Description**|
Please add a valid description.

2023-04-13 23:42 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-citation.md
> +description: "Represents the unique citation applied to a retention label."
```suggestion
description: "Represents a unique citation applied to a retention label."
```

2023-04-13 23:45 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-citationtemplate.md
> +description: "Represents the 'citation' file plan descriptor for retention labels."
Please apply the same changes reflected in previous resource descriptions.

2023-04-13 23:46 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-citationtemplate.md
> +Represents the 'citation' file plan descriptor for retention labels.
Please apply the same changes reflected in previous resource descriptions.

2023-04-13 23:46 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-citationtemplate.md
> +|:---|:---|:---|
Global comment to all the resources with methods: I wanted to confirm that we have the correct methods here, but I did not find them in the api.md file.

2023-04-13 23:49 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-citationtemplate.md
> +|citationJurisdiction|String|**TODO: Add Description**|
Please add a valid description.

2023-04-13 23:49 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-citationtemplate.md
> +|citationUrl|String|**TODO: Add Description**|
Please add a valid description.

2023-04-13 23:50 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-department.md
> +description: "Represents the unique department applied to a retention label."
```suggestion
description: "Represents a unique department applied to a retention label."
```

2023-04-13 23:51 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-department.md
> +Represents the unique department applied to a retention label.
```suggestion
Represents a unique department applied to a retention label.
```

2023-04-13 23:55 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-departmenttemplate.md
> +description: "Represents the 'department' file plan descriptor for retention labels."
Please apply the same changes reflected in previous resource descriptions.

2023-04-13 23:55 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-departmenttemplate.md
> +Represents the 'department' file plan descriptor for retention labels.
Please apply the same changes reflected in previous resource descriptions.

2023-04-13 23:56 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-departmenttemplate.md
> +|:---|:---|:---|
Since the filenames of the resources are incorrect, some method names need to be corrected as well.

2023-04-14 00:52 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-fileplanreference.md
> +description: "Represents the unique filePlanReference applied to a retention label."
```suggestion
description: "Represents a unique filePlanReference applied to a retention label."
```

2023-04-14 00:52 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-fileplanreference.md
> +Represents the unique filePlanReference applied to a retention label.
```suggestion
Represents a unique filePlanReference applied to a retention label.
```

2023-04-14 01:01 UTC, Danielabom requested changes
@sseth-msft, thank you for working on this PR. The PR did not meet our first review requirements.
Please note that:
The filenames of the resources are incorrect, resulting in incorrect changelog links, and some methods' names are likely to be incorrect. 
I found many empty descriptions in the files; please add valid descriptions.
Most of the comments in this PR are global, meaning that the comments posted apply to all the resources in this PR. 
I decided not to review the methods until their names are updated. Thanks.

2023-04-17 21:52 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor-authoritytemplate.md
> +description: "Represents the authority file plan descriptor for retention labels."
```suggestion
description: "Represents the authority file plan descriptor for retention labels."
```
```suggestion
description: "Represents the file plan descriptor of type authority for retention labels."
```

2023-04-17 23:11 UTC, sseth-msft commented on api-reference/beta/resources/security-fileplandescriptor-appliedcategory.md
> +|subCategory|[microsoft.graph.security.subCategory](../resources/security-fileplandescriptor-subcategory.md)|**TODO: Add Description**|
Represents the unique subcategory under this category that is applied to a retention label.

Added this in the new PR.

2023-04-19 00:30 UTC, Danielabom commented on api-reference/beta/resources/security-authoritytemplate.md
> +description: "Read the properties and relationships of a microsoft.graph.security.authorityTemplate object."
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the authorityTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations. Also, I believe you attempted to add the link to the resource, but we do not need it in here. We add in the second description, which is line 16.

2023-04-19 00:30 UTC, Danielabom commented on api-reference/beta/resources/security-authoritytemplate.md
> +Read the properties and relationships of a [microsoft.graph.security.authorityTemplate](../resources/security-authoritytemplate.md) object.
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the authorityTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations.

2023-04-19 00:30 UTC, Danielabom commented on api-reference/beta/resources/security-authoritytemplate.md
> +|:---|:---|:---|
Since the names of the methods need to be corrected, the links to the operations listed below must be updated.

2023-04-19 00:30 UTC, Danielabom commented on api-reference/beta/resources/security-categorytemplate.md
> +description: "Read the properties and relationships of a microsoft.graph.security.categoryTemplate object."
Perhaps, I am confused, but this sounds like the description of a method instead of a resource. What is the categoryTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations. Also, I believe you attempted to add the link to the resource, but we do not need it here. We add in the second description, which is line 16.

2023-04-19 00:30 UTC, Danielabom commented on api-reference/beta/resources/security-categorytemplate.md
> +Read the properties and relationships of a [microsoft.graph.security.categoryTemplate](../resources/security-categorytemplate.md) object.
Perhaps, I am confused, but this sounds like the description of a method instead of a resource. What is the categoryTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-categorytemplate.md
> +|:---|:---|:---|
Since the names of the methods need to be corrected, the links of the operations listed below must be updated.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-categorytemplate.md
> +|subCategories|[microsoft.graph.security.subCategoryTemplate](../resources/security-subcategorytemplate.md) collection|**TODO: Add Description**|
Global comment: Please add the missing descriptions.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-citationtemplate.md
> +description: "Read the properties and relationships of a microsoft.graph.security.citationTemplate object."
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the citationTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations. Also, I believe you attempted to add the link to the resource, but we do not need it here. We add in the second description, which is line 16.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-citationtemplate.md
> +Read the properties and relationships of a [microsoft.graph.security.citationTemplate](../resources/security-citationtemplate.md) object.
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the citationTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-citationtemplate.md
> +|:---|:---|:---|
Since the names of the methods need to be corrected, the links of the operations listed below must be updated.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-departmenttemplate.md
> +description: "Read the properties and relationships of a microsoft.graph.security.departmentTemplate object."
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the departmentTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations. Also, I believe you attempted to add the link to the resource, but we do not need it here. We add in the second description, which is line 16.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-departmenttemplate.md
> +Read the properties and relationships of a [microsoft.graph.security.departmentTemplate](../resources/security-departmenttemplate.md) object.
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the departmentTemplate resource? What does it represent? Or what does it provide?

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-departmenttemplate.md
> +|:---|:---|:---|
Since the names of the methods need to be corrected, the links of the operations listed below must be updated.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +description: "**TODO: Add Description**"
Please add valid descriptions.

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|authority|[microsoft.graph.security.authority](../resources/security-authority.md)|Specifies the underlying authority that describes the type of content to be retained and the retention schedule for
```suggestion
|authority|[microsoft.graph.security.authority](../resources/security-authority.md)|Specifies the underlying authority that describes the type of content to be retained and its retention schedule. |
```

2023-04-19 00:31 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|category|[microsoft.graph.security.appliedCategory](../resources/security-appliedcategory.md)|Specifies a group of similar types of content in a certain department.|
```suggestion
|category|[microsoft.graph.security.appliedCategory](../resources/security-appliedcategory.md)|Specifies a group of similar types of content in a particular department.|
```

2023-04-19 00:32 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|citation|[microsoft.graph.security.citation](../resources/security-citation.md)|Specifies the unique identification defining a rule or regulation, following which, the label and content to which it
This description needs to be updated; it might need to be clarified for readers.

2023-04-19 00:32 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|department|[microsoft.graph.security.department](../resources/security-department.md)|Specifies the parent business vertical or department of an organization for a label and in turn the content to w
This description needs to be updated; it might need to be clarified for readers.

2023-04-19 00:32 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|filePlanReference|[microsoft.graph.security.filePlanReference](../resources/security-fileplanreference.md)|Specifies a unique identifier of a label category which co-relates it to the that organizat
This description needs to be updated; it might need to be clarified for readers.

2023-04-19 00:33 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|authorityTemplate|[microsoft.graph.security.authorityTemplate](../resources/security-authoritytemplate.md)|Represent the properties of 'authority' file plan descriptor.|
I cannot comment on the property until the description of the authorityTemplate file is updated.

2023-04-19 00:34 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|categoryTemplate|[microsoft.graph.security.categoryTemplate](../resources/security-categorytemplate.md)|Represent the properties of 'category' file plan descriptor.|
I cannot comment on the property until the description of the categoryTemplate file is updated.
```

2023-04-19 00:34 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|citationTemplate|[microsoft.graph.security.citationTemplate](../resources/security-citationtemplate.md)|Represent the properties of 'citation' file plan descriptor.|
```suggestion
I cannot comment on the property until the description of the citationTemplate file is updated.

2023-04-19 00:35 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|departmentTemplate|[microsoft.graph.security.departmentTemplate](../resources/security-departmenttemplate.md)|Represent the properties of 'department' file plan descriptor.|
I cannot comment on the property until the description of the departmentTemplate file is updated.


```

2023-04-19 00:36 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|filePlanReferenceTemplate|[microsoft.graph.security.filePlanReferenceTemplate](../resources/security-fileplanreferencetemplate.md)|Represent the properties of 'file plan reference identification' fi
I cannot comment on the property until the description of the filePlanReferenceTemplate file is updated.

2023-04-19 00:40 UTC, Danielabom commented on api-reference/beta/resources/security-fileplanreferencetemplate.md
> +description: "Read the properties and relationships of a microsoft.graph.security.filePlanReferenceTemplate object."
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the filePlanReferenceTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations. Also, I believe you attempted to add the link to the resource, but we do not need it here. We add in the second description, which is line 16.

2023-04-19 00:41 UTC, Danielabom commented on api-reference/beta/resources/security-fileplanreferencetemplate.md
> +Read the properties and relationships of a [microsoft.graph.security.filePlanReferenceTemplate](../resources/security-fileplanreferencetemplate.md) object.
Perhaps, I am confused but this sounds like the description of a method instead of a resource. What is the filePlanReferenceTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations. Also, I believe you attempted to add the link to the resource, but we do not need it here. We add in the second description, which is line 16.

2023-04-19 01:03 UTC, Danielabom commented on api-reference/beta/resources/security-subcategory.md
> +description: "Represents the unique subcategory applied to a retention label."
```suggestion
description: "Represents a unique subcategory applied to a retention label."
```

2023-04-19 01:04 UTC, Danielabom commented on api-reference/beta/resources/security-subcategory.md
> +Represents the unique subcategory applied to a retention label.
```suggestion
Represents a unique subcategory applied to a retention label.
```

2023-04-19 01:04 UTC, Danielabom commented on api-reference/beta/resources/security-subcategorytemplate.md
> +description: "Read the properties and relationships of a [microsoft.graph.security.subcategoryTemplate object."
Perhaps, I am confused, but this sounds like the description of a method instead of a resource. What is the subCategoryTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations. Also, I believe you attempted to add the link to the resource, but we do not need it here. We add in the second description, which is line 16.

2023-04-19 01:04 UTC, Danielabom commented on api-reference/beta/resources/security-subcategorytemplate.md
> +Read the properties and relationships of a [microsoft.graph.security.subcategoryTemplate](../resources/security-subcategorytemplate.md) object.
Perhaps, I am confused, but this sounds like the description of a method instead of a resource. What is the subCategoryTemplate resource? What does it represent? Or what does it provide? We normally use the verb read to describe "Get" operations.

2023-04-19 01:26 UTC, Danielabom requested changes
Hi Sam, 
Thank you for updating the files on the PR.
I am concerned about feedback not being addressed in the first round, which may create confusion and prevent us from completing the review. Previously, I mentioned that we need full descriptions to approve or enhance them together. Having "TODO: Add description" phrases as placeholders would typically be a reason to consider that a PR is not ready for review. 

I could not review the TOC because I need to make we are placing the correct methods under the correct parent entities. 

Regarding the methods' names:
Please review the file naming wiki previously shared (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming), and update the file names that do not follow the guidelines. I commented on one of the methods with an example that applies to that specific operation.

2023-04-19 19:36 UTC, sseth-msft commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|citation|[microsoft.graph.security.citation](../resources/security-citation.md)|Specifies the unique identification defining a rule or regulation, following which, the label and content to which it
Specifies the unique rule or regulation published by a jurisdiction, following which, the label and content to which it is applied is scheduled to be retained or to be deleted. Additionally, you can specify a direct link to the citation and the jurisdiction or agency which published it.
@Danielabom does this sound better?

2023-04-19 20:13 UTC, sseth-msft commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|department|[microsoft.graph.security.department](../resources/security-department.md)|Specifies the parent business vertical or department of an organization for a label and in turn the content to w
@Danielabom - any suggestions on this?

2023-04-21 15:12 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|citation|[microsoft.graph.security.citation](../resources/security-citation.md)|Specifies the unique rule or regulation published by a jurisdiction, following which, the label and content to which i
```suggestion
|citation|[microsoft.graph.security.citation](../resources/security-citation.md)|The specific rule or regulation created by a jurisdiction used to determine whether certain labels and content should be retained or deleted. 
```

2023-04-21 15:13 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|citation|[microsoft.graph.security.citation](../resources/security-citation.md)|Specifies the unique rule or regulation published by a jurisdiction, following which, the label and content to which i
@sseth-msft, would it be valuable to update the "citation" complex type description, too?

2023-04-21 15:17 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|department|[microsoft.graph.security.department](../resources/security-department.md)|Specifies the parent business vertical or department of an organization for a label and in turn the content to w
A label assigned to content based on the department or business unit it belongs to within an organization

2023-04-21 15:23 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|:---|:---|:---|
@sseth-msft  since we are updating the properties' descriptions and these at the same are either entities or complex types. Consider updating the descriptions in the corresponding files. Let me know if you have questions.

2023-04-21 15:41 UTC, sseth-msft commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|filePlanReference|[microsoft.graph.security.filePlanReference](../resources/security-fileplanreference.md)|Specifies a unique identifier of a label category which co-relates it to the that organizat
modified the desc

2023-04-21 16:18 UTC, sseth-msft commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|:---|:---|:---|
done

2023-04-21 16:21 UTC, sseth-msft commented
> Hi Sam, Thank you for updating the files on the PR. I am concerned about feedback not being addressed in the first round, which may create confusion and prevent us from completing the review. Previously, I mentioned that we need full descriptions to approve or enhance them together. Having "TODO: Add description" phrases as placeholders would typically be a reason to consider that a PR is not ready for review.
> 
> I could not review the TOC because I need to make we are placing the correct methods under the correct parent entities.
> 
> Regarding the methods' names: Please review the file naming wiki previously shared (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming), and update the file names that do not follow the guidelines. I commented on one of the methods with an example that applies to that specific operation.

Addressed all the feedbacks you've shared so far.

2023-04-24 15:07 UTC, Danielabom commented on api-reference/beta/resources/security-appliedcategory.md
> +description: "Represents the file plan descriptor of type category applied to a particular retention labels."
```suggestion
description: "Represents the file plan descriptor of type category applied to a particular retention labels."
```
```suggestion
description: "Represents the file plan descriptor of type category applied to a particular retention label."
```

2023-04-24 15:10 UTC, Danielabom commented on api-reference/beta/resources/security-appliedcategory.md
> +|subCategory|[microsoft.graph.security.subCategory](../resources/security-subcategory.md)|Represents the file plan descriptor of type subcategory under this category that is applied to a particular
```suggestion
|subCategory|[microsoft.graph.security.subCategory](../resources/security-subcategory.md)|Represents the file plan descriptor for a subcategory under a specific category, which has been assigned to a particular retention label.|
```

2023-04-24 15:12 UTC, Danielabom commented on api-reference/beta/resources/security-appliedcategory.md
> +Represents the file plan descriptor of type category applied to a particular retention labels.
```suggestion
Represents the file plan descriptor of type category applied to a particular retention labels.
```
```suggestion
Represents the file plan descriptor of the type category applied to a particular retention label.
```

2023-04-24 15:12 UTC, Danielabom commented on api-reference/beta/resources/security-appliedcategory.md
> +description: "Represents the file plan descriptor of type category applied to a particular retention label."
```suggestion
description: "Represents the file plan descriptor of type category applied to a particular retention label."
```
```suggestion
description: "Represents the file plan descriptor of the type category applied to a particular retention label."
```

2023-04-24 15:17 UTC, Danielabom commented on api-reference/beta/resources/security-appliedcategory.md
> +description: "Represents the file plan descriptor of the type category applied to a particular retention label."
```suggestion
description: "Represents the file plan descriptor of type category applied to a particular retention label."
```

2023-04-24 15:33 UTC, Danielabom commented on api-reference/beta/api/security-authoritytemplate-list.md
> +description: "Get a list of the microsoft.graph.security.authorityTemplate objects and their properties."
```suggestion
description: "Get a list of the microsoft.graph.security.authorityTemplate objects and their properties."
```

2023-04-24 15:37 UTC, Danielabom commented on api-reference/beta/api/security-authoritytemplate-get.md
> +description: "Read the properties and relationships of a microsoft.graph.security.authorityTemplate object."
_**GLOBAL COMMENT: As mentioned before**_, this seems to be an attempt to copy the description from line 15. Descriptions in line 3 do not have links. Please use the correct resource names. For example: 
Instead of using  microsoft.graph.security.authorityTemplate object, use .authorityTemplate

2023-04-24 15:38 UTC, Danielabom commented on api-reference/beta/api/security-authoritytemplate-list.md
> +description: "Get a list of the microsoft.graph.security.authorityTemplate objects and their properties."
**As mentioned before,** this seems to be an attempt to include the link. Descriptions in line 3 do not have links. Please use the correct format of the resource name here, example: 
Instead of microsoft.graph.security.authorityTemplate, use authorityTemplate

2023-04-24 19:12 UTC, Danielabom commented on api-reference/beta/resources/security-categorytemplate.md
> +|[List categoryTemplates](../api/security-categorytemplate-list.md)|[microsoft.graph.security.categoryTemplate](../resources/security-categorytemplate.md) collection|Get a list of the [microsoft.grap
_**GLOBAL COMMENT: As mentioned before,**_ by updating the method names, the links in the methods table of the resource files also needed to be updated.

2023-04-24 19:20 UTC, Danielabom commented on api-reference/beta/api/security-categorytemplate-list-subcategories.md
> +Get the subCategoryTemplate resources from the subCategories navigation property.
Please add the corresponding links in this description.

2023-04-24 19:23 UTC, Danielabom commented on api-reference/beta/api/security-categorytemplate-list.md
> +description: "Get a list of the microsoft.graph.security.categoryTemplate objects and their properties."
As mentioned before, please update this description format.

2023-04-24 19:28 UTC, Danielabom commented on api-reference/beta/resources/security-citation.md
> +description: "Represents the file plan descriptor of type citation applied to a particular retention labels."
```suggestion
description: "Represents the file plan descriptor of type citation applied to a particular retention label."
```

2023-04-25 15:59 UTC, Danielabom requested changes
Hi @sseth-msft, we are having issues with the method names. I am trying to give you the correct file names but we are missing files. Please add the labelsRoot file with the new navigation properties. I also added some Global comments, which are the last review's callouts. Please make sure to address them. Also, did you manually create these files?

2023-04-26 17:29 UTC, sseth-msft commented
> Hi @sseth-msft, we are having issues with the method names. I am trying to give you the correct file names but we are missing files. Please add the labelsRoot file with the new navigation properties. I also added some Global comments, which are the last review's callouts. Please make sure to address them. Also, did you manually create these files?

Can you please point me to where the labelsroot file is needed? Sometimes there are files with same content generated and the labelsroot was a duplicate that way. I have not created any new files myself, I may have deleted the ones that are not needed. 
I can address the issue with the right file if understand the context. Fixes all other comments regarding descriptions.

2023-04-26 22:29 UTC, Danielabom requested changes
Sam, I can point you to the CSDL file you shared. Please look up the entity ¨labelsRoot¨. There, you'll find the nav properties that need to be documented in green. I suggest going through the entire CSDL and making sure that you've added all the files we need.

2023-05-09 16:31 UTC, Danielabom commented on api-reference/beta/resources/security-citationtemplate.md
> +he specific rule or regulation created by a jurisdiction used to determine whether certain labels and content should be retained or deleted.
```suggestion
The specific rule or regulation created by a jurisdiction used to determine whether certain labels and content should be retained or deleted.
```

2023-05-09 17:06 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|appliedcategory|[microsoft.graph.security.appliedCategory](../resources/security-appliedcategory.md)|Represents the file plan descriptor of type category applied to a particular retention labels.|
Your api.md and csdl show the name of this property as just "category".

2023-05-09 17:07 UTC, Danielabom commented on api-reference/beta/resources/security-citationtemplate.md
> +|Property|Type|Description|
The api.md shows a property called "descriptor" not listed here. Please review.

2023-05-09 17:08 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|appliedcategory|[microsoft.graph.security.appliedCategory](../resources/security-appliedcategory.md)|Represents the file plan descriptor of type category applied to a particular retention labels.|
```suggestion
|appliedcategory|[microsoft.graph.security.appliedCategory](../resources/security-appliedcategory.md)|Represents the file plan descriptor of type category applied to a particular retention label.|
```

2023-05-09 17:08 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|department|[microsoft.graph.security.department](../resources/security-department.md)|Represents the file plan descriptor of type department applied to a particular retention labels.|
```suggestion
|department|[microsoft.graph.security.department](../resources/security-department.md)|Represents the file plan descriptor of type department applied to a particular retention label.|
```

2023-05-09 17:10 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|appliedcategory|[microsoft.graph.security.appliedCategory](../resources/security-appliedcategory.md)|Represents the file plan descriptor of type category applied to a particular retention label.|
Your api.md and csdl show the name of this property as just "category".

2023-05-09 17:13 UTC, Danielabom commented on api-reference/beta/resources/security-fileplanreference.md
> +description: "Represents the file plan descriptor of type filePlanReference applied to a particular retention labels."
```suggestion
description: "Represents the file plan descriptor of type filePlanReference applied to a particular retention label."
```

2023-05-09 17:14 UTC, Danielabom commented on api-reference/beta/resources/security-fileplanreference.md
> +Represents the file plan descriptor of type filePlanReference applied to a particular retention labels.
```suggestion
Represents the file plan descriptor of type filePlanReference applied to a particular retention label.
```

2023-05-09 17:19 UTC, Danielabom commented on api-reference/beta/resources/security-labelsroot.md
> +description: "Represents the entry point for retention labels resource type."
```suggestion
description: "Represents the entry point for the retentionLabels resource type."
```

2023-05-09 17:19 UTC, Danielabom commented on api-reference/beta/resources/security-labelsroot.md
> +Represents the entry point for retention labels resource type.
```suggestion
Represents the entry point for the retentionLabels resource type.
```

2023-05-09 17:21 UTC, Danielabom commented on api-reference/beta/resources/security-labelsroot.md
> +|
Does the resource have properties, or should it be "none"? Please update the section accordingly.

2023-05-09 17:47 UTC, Danielabom commented on api-reference/beta/resources/security-retentionlabel.md
> +|eventType|[microsoft.graph.security.retentionEventType](../resources/security-retentioneventtype.md)|Represents the type associated with a retention event.|
Based on the CSDL and the api.md files, the name of this nav property is "retentionEventType."

2023-05-09 22:37 UTC, Danielabom requested changes
Regarding the new file names:
I've made all the changes related to file naming issues. Please be aware that all the file naming changes require changes from your side, like updating the methods' names and links (only those with new file names). 

Missing files:
As explained before, whatever appears as "new ..." in the CSDL and the api.md files needs to be documented in the PR.

In this case, we are missing:
An entity called filePlanDescriptorTemplate
A complex type called filePlanDescriptorBase 

In the changelog:
Add new methods (list and create) for retentionLabel
Add the new resource labelsRoot

In the api-reference/beta/resources/security-retentionlabel.md file:
According to the CSDL, "dispositionReviewStages" is not a property. It is a nav property, already documented in relationships.
Based on the CSDL and the api.md files, the name of this nav property is "retentionEventType."
FYi, the api.md file indicates that the dispositionReviewStage resource only supports a create operation, not an update operation. 

In the api-reference/beta/resources/security-fileplandescriptor.md file: 
FYI, the resource filePlanDescriptor appears as filePlanDescriptors in the api.md file dot MD file.
FYI, the api.md and csdl show the property “appliedcategory” as just "category".

In the api-reference/beta/resources/security-labelsroot.md file:
Does the resource have properties, or should it be "none"? Please update the section accordingly.

TOC
Now, that you have the correct file names, please update the TOC accordingly. Here's the link to the TOC guidelines: [ToC and topic title - Overview (azure.com)](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title)

2023-05-18 01:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-authoritytemplate.md
> +Inherits from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).
Line 18 and similar lines for the other 5 resources that represent templates that are based on filePlanDescriptorTemplate resource:
Hi @sseth-msft ,
Just a quick note as your reviewer has asked me to look at a few things in this PR, and I happened to notice this - for all 6 resources derived from filePlanDescriptorTemplate as defined in your schema, this line should say "Inherits from microsoft.graph.security.filePlanDescriptorTemplate, not microsoft.graph.security.filePlanDescriptor.

Can you update all such 6 instances?

2023-05-18 01:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-authority.md
> +Inherits from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).
Line 19 and similar lines in the other 5 resources derived from filePlanDescriptorBase in your schema:
This line should say microsoft.graph.security.filePlanDescriptorBase, not microsoft.graph.security.filePlanDescriptor.

For that reason, you should also document filePlanDescriptorBase.

2023-05-18 01:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-authoritytemplate.md
> +Inherits from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).
Also, please document filePlanDescriptorTemplate.

2023-05-19 16:30 UTC, sseth-msft commented on api-reference/beta/resources/security-authoritytemplate.md
> +Inherits from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).
Added the file and made the suggested changes in all 6 files.

2023-05-19 16:31 UTC, sseth-msft commented on api-reference/beta/resources/security-authority.md
> +Inherits from [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md).
Made changes to all 6 files.

2023-05-19 22:34 UTC, Danielabom commented on changelog/Microsoft.Security.RecordsManagement.json
> +            "ApiChange": "LIST",
```suggestion
            "ApiChange": "GET",
```

2023-05-19 22:45 UTC, Danielabom commented on changelog/Microsoft.Security.RecordsManagement.json
> +            "Description": "Added the [list filePlanDescriptor](https://learn.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta) operation to [retentionLabel](https://le
```suggestion
            "Description": "Added the [list]](https://learn.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta) operation to [retentionLabel](https://learn.microsoft.com/en-us/graph/api/resources/security-retentionLabel?view=graph-rest-beta) resource",
```

2023-05-19 23:26 UTC, Danielabom commented on changelog/Microsoft.Security.RecordsManagement.json
> +            "Description": "Added the [post filePlanDescriptor](https://learn.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta) operation to [retentionLabel](https://le
```suggestion
            "Description": "Added the [post] (https://learn.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta) operation to [retentionLabel](https://learn.microsoft.com/en-us/graph/api/resources/security-retentionLabel?view=graph-rest-beta) resource",
```

2023-05-19 23:53 UTC, Danielabom commented on api-reference/beta/resources/security-retentionlabel.md
> +|[Create filePlanDescriptor](../api/security-retentionlabel-post.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md)|Create a new filePlanDescriptor object.
```suggestion
|[Create filePlanDescriptor](../api/security-labelsroot-post-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md)|Create a new filePlanDescriptor object.|
```

2023-05-20 00:13 UTC, Danielabom commented on api-reference/beta/resources/security-retentionlabel.md
> +|[List filePlanDescriptor](../api/security-retentionlabel-list.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get the filePlanDescriptor res
```suggestion
|[List filePlanDescriptor](../api/security-retentionlabel-list.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get the filePlanDescriptor resources from the descriptors navigation property.|
```
```suggestion
|[List filePlanDescriptor](../api/security-labelsroot-list-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get the filePlanDescriptor resources from the descriptors navigation property.|
```

2023-05-20 00:16 UTC, Danielabom commented on api-reference/beta/resources/security-retentionlabel.md
>  ## Properties
@sseth-msft, please address the comment above I left last week. Thanks!

2023-05-20 00:50 UTC, Danielabom commented on api-reference/beta/resources/security-labelsroot.md
> +|[List retentionLabels](../api/security-retentionlabel-list.md)|[microsoft.graph.security.retentionLabel](../resources/security-retentionlabel.md) collection|Get a list of the [retentionLabel](../res
```suggestion
|[List retentionLabels](../api/security-retentionlabel-list.md)|[microsoft.graph.security.retentionLabel](../resources/security-labelsroot-list-retentionlabel.md) collection|Get a list of the [retentionLabel](../resources/security-retentionlabel.md) objects and their properties.|
```

2023-05-20 00:51 UTC, Danielabom commented on api-reference/beta/resources/security-labelsroot.md
> +|[Create retentionLabel](../api/security-retentionlabel-post.md)|[microsoft.graph.security.retentionLabel](../resources/security-retentionlabel.md)|Create a new [retentionLabel](../resources/security
```suggestion
|[Create retentionLabel](../api/security-labelsroot-post-retentionlabel.md)|[microsoft.graph.security.retentionLabel](../resources/security-retentionlabel.md)|Create a new [retentionLabel](../resources/security-retentionlabel.md) object.|
```

2023-05-20 02:26 UTC, Danielabom commented on api-reference/beta/resources/security-labelsroot.md
> +|[List retentionLabels](../api/security-retentionlabel-list.md)|[microsoft.graph.security.retentionLabel](../resources/security-labelsroot-list-retentionlabel.md) collection|Get a list of the [retent
```suggestion
|[List retentionLabels](../api/security-labelsroot-list-retentionlabel.md)|[microsoft.graph.security.retentionLabel](../resources/security-labelsroot-list-retentionlabel.md) collection|Get a list of the [retentionLabel](../resources/security-retentionlabel.md) objects and their properties.|
```

2023-05-20 02:35 UTC, Danielabom commented on api-reference/beta/resources/security-subcategorytemplate.md
> +|[Delete subCategories](../api/security-categorytemplate-post-subcategories.md)|None|Delete a [microsoft.graph.security.subCategoryTemplate](../resources/security-subcategorytemplate.md) object.|
```suggestion
|[Delete subCategories](../api/security-categorytemplate-delete-subcategories.md)|None|Delete a [microsoft.graph.security.subCategoryTemplate](../resources/security-subcategorytemplate.md) object.|
```

2023-05-22 14:08 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|[List filePlanDescriptors](../api/security-retentionlabel-list.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get a list of the [microsoft.
```suggestion
|[List filePlanDescriptors](../api/security-labelsroot-list-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get a list of the [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) objects and their properties.|
```

2023-05-22 14:09 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|[Create filePlanDescriptor](../api/security-retentionlabel-post.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md)|Create a new [microsoft.graph.security.
```suggestion
|[Create filePlanDescriptor](../api/security-labelsroot-post-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md)|Create a new [microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) object.|
```

2023-05-22 19:35 UTC, Danielabom commented on api-reference/beta/resources/security-fileplandescriptortemplate.md
> +
@sseth-msft, why are we not exposing these methods in the TOC?

2023-05-23 02:37 UTC, sseth-msft commented on api-reference/beta/resources/security-fileplandescriptortemplate.md
> +
Hi Dani, the file plan descriptor is a collection under which we have the 6 descriptors, they are all individually added to the toc.

2023-05-30 18:21 UTC, Lauragra commented on api-reference/beta/api/security-authoritytemplate-get.md
> +Read the properties and relationships of a [microsoft.graph.security.authorityTemplate](../resources/security-authoritytemplate.md) object.
Global: We only fully qualify the type name in specific places in the topics. In the summary statement, we just use the resource name without fully qualifying the namespace, for readability. Please update throughout.

2023-05-30 23:07 UTC, Lauragra commented on api-reference/beta/api/security-authoritytemplate-get.md
> +The following is an example of the response
Global: Please add a period to the end of the sentence in the Response section.

2023-05-30 23:09 UTC, Lauragra commented on api-reference/beta/api/security-categorytemplate-delete-subcategories.md
> +>**Note:** The response object shown here might be shortened for readability.
Global: When there's no response body as for delete operations. we don't include this note because the response body is not shortened.

2023-05-30 23:12 UTC, Lauragra commented on api-reference/beta/api/security-categorytemplate-list-subcategories.md
> +Get the [microsoft.graph.security.subCategoryTemplate](../resources/security-subcategorytemplate.md) resources from the subCategories navigation property.
Global: This boilerplate description is not that useful. A more useful description might be something like: "Get a list of subcategories associated with a category template."

2023-05-30 23:15 UTC, Lauragra commented on api-reference/beta/api/security-categorytemplate-list-subcategories.md
> +If successful, this method returns a `200 OK` response code and a collection of [subCategoryTemplate](../resources/security-subcategorytemplate.md) objects in the response body.
Global: In the Response H2 section, we do use the fully qualified subamespace. Please consistently use the fully qualified name in the Response section (but not in the summary description). See the guidelines for subnamespaces: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace

2023-05-30 23:16 UTC, Lauragra commented on api-reference/beta/api/security-categorytemplate-post-subcategories.md
> +|displayName|String|**TODO: Add Description** Inherited from [microsoft.graph.security.filePlanDescriptorTemplate](../resources/security-fileplandescriptor.md). Optional.|
Please replace the TODO here with the description.

2023-06-01 03:23 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List file plan descriptors
Why aren't we using "List retention label" and "Create retention label" for the TOC entries here?

2023-06-01 03:27 UTC, Lauragra commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|[List filePlanDescriptors](../api/security-labelsroot-list-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get a list of the
The two methods you're linking to here are List and Create retentionLabels. If there should be List and Create methods on the filePlanDescriptors resource, are we missing those method topics?

2023-06-01 03:28 UTC, Lauragra commented on api-reference/beta/resources/security-retentionlabel.md
> +|[List filePlanDescriptor](../api/security-labelsroot-list-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get the filePlanDes
In this topic it looks like you're linking to the same methods (list and create retentionLabel) twice, with different method names. Seems like we are missing the files that should go with list and create filePlanDescriptor.

2023-06-01 03:32 UTC, Lauragra commented on api-reference/beta/toc.yml
> +            - name: File plan reference
Should this TOC entry be File plan reference template, to match the resource name?

2023-06-02 17:35 UTC, sseth-msft commented on api-reference/beta/api/security-authoritytemplate-get.md
> +Read the properties and relationships of a [microsoft.graph.security.authorityTemplate](../resources/security-authoritytemplate.md) object.
fixed on all method/api files.

2023-06-02 17:37 UTC, sseth-msft commented on api-reference/beta/api/security-authoritytemplate-get.md
> +The following is an example of the response
fixed

2023-06-02 17:42 UTC, sseth-msft commented on api-reference/beta/api/security-categorytemplate-delete-subcategories.md
> +>**Note:** The response object shown here might be shortened for readability.
Removed from all delete operations. All other operations - get, list, post have a response.

2023-06-02 17:48 UTC, sseth-msft commented on api-reference/beta/api/security-categorytemplate-list-subcategories.md
> +Get the [microsoft.graph.security.subCategoryTemplate](../resources/security-subcategorytemplate.md) resources from the subCategories navigation property.
updated as per the suggestion.

2023-06-02 19:37 UTC, sseth-msft commented on api-reference/beta/api/security-categorytemplate-list-subcategories.md
> +If successful, this method returns a `200 OK` response code and a collection of [subCategoryTemplate](../resources/security-subcategorytemplate.md) objects in the response body.
fixed for all APIs/method files.

2023-06-02 19:37 UTC, sseth-msft commented on api-reference/beta/api/security-categorytemplate-post-subcategories.md
> +|displayName|String|**TODO: Add Description** Inherited from [microsoft.graph.security.filePlanDescriptorTemplate](../resources/security-fileplandescriptor.md). Optional.|
added description.

2023-06-08 16:13 UTC, sseth-msft commented on api-reference/beta/toc.yml
> +          - name: List file plan descriptors
discussed with Laura, OK to remove this and CREATE option under it.

2023-06-08 16:14 UTC, sseth-msft commented on api-reference/beta/resources/security-fileplandescriptor.md
> +|[List filePlanDescriptors](../api/security-labelsroot-list-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get a list of the
same as above.

2023-06-08 16:18 UTC, sseth-msft commented on api-reference/beta/toc.yml
> +            - name: File plan reference
check the links to the file, should link to the correct file.

2023-06-08 17:03 UTC, sseth-msft commented on api-reference/beta/toc.yml
> +          - name: List file plan descriptors
removed from TOC.

2023-06-08 18:04 UTC, sseth-msft commented on api-reference/beta/resources/security-retentionlabel.md
> +|[List filePlanDescriptor](../api/security-labelsroot-list-retentionlabel.md)|[microsoft.graph.security.filePlanDescriptor](../resources/security-fileplandescriptor.md) collection|Get the filePlanDes
done.

2023-06-08 18:04 UTC, sseth-msft commented on api-reference/beta/toc.yml
> +            - name: File plan reference
done

2023-07-01 01:56 UTC, Lauragra approved these changes

2023-07-01 01:56 UTC, merged