Update session page details and revise more doc ownership
microsoftgraph/microsoft-graph-docs pull request #20877
Opened 2023-04-07 20:22 UTC by mcm223

This change revises the following:
* Corrects language in session page size to reflect that 60 is the maximum page size.
* Adds language explaining `$expand` and session page size at the top of the `callrecord-get.md` page
* Specifies the exact query parameters we support instead of just saying "some" are supported.
* Adds supported Prefer header values for page size and unknown enums.
* Fixes a typo in the UserAgent resource.
* Updates doc ownership of more callRecords resources.
* Fixes misaligned update times in the changelog.

2023-05-24 23:38 UTC, Datar89 commented on api-reference/beta/api/callrecords-callrecord-get.md
> +| Prefer: include-unknown-enum-members | Enables evolveable enum values beyond the sentinal value. See [Best Practices](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations
Is it sentinel?

2023-05-24 23:41 UTC, Datar89 commented on api-reference/beta/api/callrecords-callrecord-get.md
> +| $select | Use the `$select` query parameter to return a set of properties that are different than the default set for an individual resource or a collection of resources. Only supported for `callRe
Do you think that it might be good to add an example of how to use it? Or there are other documentations available for that?

2023-06-30 18:12 UTC, mcm223 commented on api-reference/beta/api/callrecords-callrecord-get.md
> +| $select | Use the `$select` query parameter to return a set of properties that are different than the default set for an individual resource or a collection of resources. Only supported for `callRe
There are examples on how to use $select in the query parameters documentation linked a few lines above: https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#select-parameter

2023-07-05 16:12 UTC, Datar89 approved these changes

2023-07-22 02:37 UTC, Danielabom commented on api-reference/v1.0/api/callrecords-callrecord-get.md
> +| $select | Use the `$select` query parameter to return a set of properties that are different than the default set for an individual resource or a collection of resources. Only supported for `callRe
Please add changelog entries for each new parameter. See example 9 on this wiki: [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-07-22 02:38 UTC, Danielabom commented on api-reference/v1.0/api/callrecords-session-list.md
> +|:----------|:----------|
Please add changelog entries for each new parameter. See example 9 on this wiki: [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-07-22 02:39 UTC, Danielabom commented on api-reference/beta/api/callrecords-session-list.md
> +|:----------|:----------|
Please add changelog entries for each new parameter. See example 9 on this wiki: [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-07-22 02:39 UTC, Danielabom commented on api-reference/beta/api/callrecords-callrecord-get.md
> +|:----------|:----------|
Please add changelog entries for each new parameter. See example 9 on this wiki: [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-07-22 02:40 UTC, Danielabom requested changes
Thank you for working on this PR @mcm223. Please review my comments.

2023-07-24 17:32 UTC, mcm223 commented
Hi @Danielabom -- Just a clarification: these aren't new parameters we're adding. These query parameters have been supported for a long time, I'm just documenting them more fully as the support was ambiguously worded previously. Do we still need changelog entries for them if they aren't new functionality?

2023-07-28 17:45 UTC, mcm223 commented on api-reference/v1.0/api/callrecords-callrecord-get.md
> +| $select | Use the `$select` query parameter to return a set of properties that are different than the default set for an individual resource or a collection of resources. Only supported for `callRe
Confirmed over chat this is not needed as the parameters are not new functionality.

2023-07-28 17:46 UTC, mcm223 commented on api-reference/v1.0/api/callrecords-session-list.md
> +|:----------|:----------|
Confirmed over chat this is not needed as the parameters are not new functionality.

2023-07-28 17:46 UTC, mcm223 commented on api-reference/beta/api/callrecords-session-list.md
> +|:----------|:----------|
Confirmed over chat this is not needed as the parameters are not new functionality.

2023-07-28 17:46 UTC, mcm223 commented on api-reference/beta/api/callrecords-callrecord-get.md
> +|:----------|:----------|
Confirmed over chat this is not needed as the parameters are not new functionality.

2023-08-01 23:15 UTC, Danielabom approved these changes
Thank you for working on this PR @mcm223. PR approved.

2023-08-02 04:00 UTC, merged