Promote customSecurityAttributeDefinition from beta to v1.0
microsoftgraph/microsoft-graph-docs pull request #20894
Opened 2023-04-11 11:01 UTC by CecilyK

Tracked via this content review work item [86489](https://dev.azure.com/msft-skilling/Content/_queries/edit/86489/?triage=true) in the Skilling ADO.

2023-04-12 18:26 UTC, FaithOmbongi commented
Hi @CecilyK - Please create a content review work item @ https://aka.ms/msgraph-identity-workitem and share the required info in the work item description. Thank you.

2023-05-15 05:11 UTC, Jarbas-MSFT commented on api-reference/beta/resources/custom-security-attributes-overview.md
>  > [!IMPORTANT]
Do we still need this note here? Please, remove or update this note.

2023-05-15 05:13 UTC, JarbasHorst commented
Hello @CecilyK, I reviewed your PR and left one comment. Please, take a look when you will have time.

2023-05-15 07:20 UTC, CecilyK commented on api-reference/beta/resources/custom-security-attributes-overview.md
>  > [!IMPORTANT]
@Jarbas-MSFT We do not need the note. I've removed it.

2023-05-23 04:16 UTC, JarbasHorst commented on api-reference/beta/api/allowedvalue-get.md
>  ---
Hi @CecilyK, I noticed this entry outside of the Microsoft Graph repository that I think you should also update: https://learn.microsoft.com/en-us/azure/role-based-access-control/conditions-overview#status-of-condition-features

2023-05-23 04:17 UTC, JarbasHorst commented on concepts/custom-security-attributes-examples.md
>  > [!IMPORTANT]
Do we still need this note? Please, remove or update this note.

2023-05-28 11:38 UTC, CecilyK commented on concepts/custom-security-attributes-examples.md
>  > [!IMPORTANT]
Removed

2023-05-30 05:17 UTC, Jarbas-MSFT commented
Hi @Lauragra, hi @FaithOmbongi, this PR is ready for final review;

2023-05-30 06:04 UTC, CecilyK commented on api-reference/beta/api/allowedvalue-get.md
>  ---
This will be updated on the azure-docs-pr repo by @rolyon

2023-05-30 18:09 UTC, FaithOmbongi requested changes
Hi @Jarbas-MSFT - Thanks for the review. Everything looks good, just two minor edits.

@CecilyK - I've left two comments, please address them. Before approving, I'll also push a commit to move the RBAC information into include files for ease of maintenance.

2023-05-30 19:10 UTC, CecilyK commented on concepts/custom-security-attributes-examples.md
This has been updated.

2023-05-30 19:14 UTC, CecilyK commented
#feedback-addressed

2023-05-31 11:13 UTC, CecilyK commented
> Hi @CecilyK - I've pushed a few commits to use include files for the RBAC information.
> 
> Approved.

Thanks @FaithOmbongi

2023-06-01 02:24 UTC, merged