Fix API Doctor errors flagged by new version
microsoftgraph/microsoft-graph-docs pull request #20922
Opened 2023-04-13 17:35 UTC by millicentachieng

This PR fixes the following:
- Casing of path segments
- Paths to use key as path segment format
- Remove Objective C code snippets
- Use fully qualified type name for properties not in `microsoft.graph` namespace
- Add sample keys

2023-04-13 18:58 UTC, FaithOmbongi requested changes
Hi @millicentachieng - There are some changes that I suspect aren't valid. The syntaxes that were documented are syntaxes for alternate keys and the syntaxes you propose aren't valid for those particular keys. Please validate those particular files.

2023-04-13 18:58 UTC, FaithOmbongi commented on api-reference/beta/api/attachment-get.md
> +GET https://graph.microsoft.com/beta/me/messages/AAMkADA1M-zAAA=/attachments/AAMkADA1M-CJKtzmnlcqVgqI=
Please verify if this really needs to change. 
I think what was documented was the correct OData syntax that uses alternate key syntax.

2023-04-13 18:58 UTC, FaithOmbongi commented on api-reference/beta/api/event-post-attachments.md
> +POST https://graph.microsoft.com/beta/me/events/AAMkAGI1AAAt9AHjAAA=/attachments
Same comment about alternate key

2023-04-14 08:57 UTC, millicentachieng commented on api-reference/beta/api/attachment-get.md
> +GET https://graph.microsoft.com/beta/me/messages/AAMkADA1M-zAAA=/attachments/AAMkADA1M-CJKtzmnlcqVgqI=
For alternate keys, we expect the name of the property to be specified e.g. `/messages(key='AAMkADA1M-zAAA=')`. In this case, the ids are not alternate keys and they should be added as path segments as in v1.0 docs.

2023-04-14 09:29 UTC, millicentachieng commented on api-reference/beta/api/attachment-get.md
> +GET https://graph.microsoft.com/beta/me/messages/AAMkADA1M-zAAA=/attachments/AAMkADA1M-CJKtzmnlcqVgqI=
The documented syntax is correct but for consistency, we need all keys to be added as path segments unless they are alternate keys. 

Another example, 
- `https://graph.microsoft.com/v1.0/users('6e7b768e-07e2-4810-8459-485f84f8f204')` 
- `https://graph.microsoft.com/v1.0/users/6e7b768e-07e2-4810-8459-485f84f8f204` 

Both are correct, but the latter is used in the documentation.

2023-04-15 01:38 UTC, merged