Refresh advanced query capabilities articles
microsoftgraph/microsoft-graph-docs pull request #20932
Opened 2023-04-14 10:34 UTC by FaithOmbongi

+ Refresh tables
+ Add $count eq 0/1 in separate section
+ Use H2 to surface in right TOC

2023-04-14 18:43 UTC, Licantrop0 requested changes

2023-04-14 18:43 UTC, Licantrop0 commented on includes/filter-directory-objects.md
> +| extensionAttributes/extensionAttribute1          | ![Advanced][AQP] | ![NotSupported][NS] |                  | ![Advanced][AQP]    |
If we collapsed these for `user`, we should do it also for device.

2023-04-14 18:43 UTC, Licantrop0 commented on includes/filter-directory-objects.md
>  | Open extensions                    |                  |                  |                  |
if this is not filterable, we should not put it here

2023-04-14 18:43 UTC, Licantrop0 commented on includes/filter-directory-objects.md
>  | Directory extensions               | ![Default][RDS]  |                  | ![Advanced][AQP] |
can we add a link to the documentation on what it is?

2023-04-14 18:43 UTC, Licantrop0 commented on includes/filter-directory-objects.md
>  The following table shows support for `$filter` by extension properties on the **user** object.
I don't think it's worthwhile to separate this in another table, the columns are the same.

2023-04-14 18:43 UTC, Licantrop0 commented on includes/filter-directory-objects.md
> +| Directory object | Property                            | eq Count 0       | eq Count 1          |
maybe we should put this separated under each entity so developers don't have to scroll all the way down to see this

2023-04-15 01:41 UTC, Lauragra commented
@FaithOmbongi , it looks like there are some requested changes; can you take a look before I merge? Thanks.

2023-04-17 22:30 UTC, Licantrop0 commented on includes/filter-directory-objects.md
> +| servicePrincipal | owners/$count                       |                  | ![Advanced][AQP]    |
Please also remove servicePrincipal `ownedObjects/$count` and `owners/$count`, they have the same issues as group's owners. I forgot to remove them from the testing suite.

2023-04-18 13:08 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +As Azure Active Directory (Azure AD) continues to deliver more capabilities and improvements in stability, availability, and performance, Microsoft Graph also continues to evolve and scale to efficie
That's pending the official announcement.

2023-04-18 13:10 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
> +| mdmAppId                                         | ![Default][RDS]  |                     |                  |                     |
Fixed.

2023-04-18 13:11 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
>  | Open extensions                    |                  |                  |                  |
Let me put Not supported.

2023-04-18 13:15 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
>  | Directory extensions               | ![Default][RDS]  |                  | ![Advanced][AQP] |
Good idea. Done.

2023-04-18 13:18 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
>  The following table shows support for `$filter` by extension properties on the **user** object.
The challenge is that three of the extensions aren't structural properties, but they get added because the user entity is an open type. And then their names are dependent on the developer.

If the tool adds extensions to the properties list, then I'll no longer need this section. We can consider this for the next update.

2023-04-18 13:47 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
> +| Directory object | Property                            | eq Count 0       | eq Count 1          |
I think it all depends on the scrolling behavior of different customers. For others, the H2 will pop out in the article. For others, for example someone interested in service principals, they'll scroll through the table relating to service principals to identity all listed properties and finally end up seeing the section relating to $count for collections.

But I've applied your suggestion.

2023-04-18 13:49 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
> +| extensionAttributes/extensionAttribute1          | ![Advanced][AQP] | ![NotSupported][NS] |                  | ![Advanced][AQP]    |
Hmm, not sure I understand. All the extension attributes are listed for all entities.

2023-04-18 16:22 UTC, Licantrop0 commented on concepts/aad-advanced-queries.md
> +The following table summarizes support for `$orderby` by properties of directory objects and indicates where sorting is supported through advanced query capabilities.
maybe we should re-iterate here that requires $count=true parameter and ConsistencyLevel = eventual header.
Also, we need to tell that even if the property supports $orderby by default, if is used in combination with $filter, the advanced queries parameters are needed.

2023-04-18 16:32 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +The following table summarizes support for `$orderby` by properties of directory objects and indicates where sorting is supported through advanced query capabilities.
Good call.

2023-04-18 16:38 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
> +| onPremisesExtensionAttributes/extensionAttribute1          | ![Advanced][AQP]    | ![NotSupported][NS] |                  | ![Advanced][AQP]    |
Addressed.

2023-04-18 17:42 UTC, Licantrop0 commented on includes/filter-directory-objects.md
> +| [Directory extensions](/graph/extensibility-overview#directory-azure-ad-extensions)      | ![Default][RDS]     |                     | ![Advanced][AQP]    |
can we add here also the `customSecurityAttributes`? see https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/users-custom-security-attributes#list-all-users-with-a-custom-security-attribute-assignment-that-equals-a-value

2023-04-18 17:45 UTC, Licantrop0 approved these changes
let's add the custom security attributes note and then we can merge! Thanks @FaithOmbongi

2023-04-18 17:46 UTC, FaithOmbongi commented on includes/filter-directory-objects.md
> +| [Directory extensions](/graph/extensibility-overview#directory-azure-ad-extensions)      | ![Default][RDS]     |                     | ![Advanced][AQP]    |
Hmm, sadly no. We had an internal discussion on whether to consider custom security attributes as another type of extension and we agreed not to.

We have a blue note in the extensions overview https://learn.microsoft.com/en-us/graph/extensibility-overview?tabs=http  and are currently making some updates to the [IT admin doc here](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/custom-security-attributes-overview#how-do-custom-security-attributes-compare-with-directory-extensions) to call out the differences without making apples to apples comparison.

2023-04-19 00:35 UTC, merged