Pages API phase 2 release
microsoftgraph/microsoft-graph-docs pull request #20977
Opened 2023-04-18 14:56 UTC by sangle7

Internal roadmap: 15124

2023-04-20 16:04 UTC, Danielabom requested changes
Hi @sangle7, please add the changelog. Thanks!

2023-04-21 01:41 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +description: This resource is a abstract type for site page
What does the resource represent or describe or maybe provide?

2023-04-21 01:41 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +This resource represents a baseSitePage in the site page library.
What does the resource represent or describe or maybe provide?

2023-04-21 01:45 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +| [Delete baseSitePage](../api/baseSitePage-delete.md) | None                                                    | Deletes a [baseSitePage](../resources/baseSitePage.md) object.
```suggestion
| [Delete baseSitePage](../api/baseSitePage-delete.md) | None                                                    | Delete a [baseSitePage](../resources/baseSitePage.md) object.                               |
```

2023-04-27 03:38 UTC, sangle7 commented on api-reference/beta/resources/basesitepage.md
> +description: This resource is a abstract type for site page
Hey @Danielabom, actually it's an abstract class which has some basic information about a page in SharePoint. But it doesn't have an instance. Instead, there are going to have a few sub types (`sitePage`, `topicPage`, 'newPage` ...) that represent a specific type of page.

2023-05-02 16:01 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +This resource represents a baseSitePage in the site page library.
In line 16, please add the links to the resources.

2023-05-02 16:19 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +title: BaseSitePage
```suggestion
title: "baseSitePage resource type"
```

2023-05-02 16:22 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +| Property             | Type                                                                 | Description
@sangle7, inherited properties should also have descriptions.

2023-05-02 16:36 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +| `microsoftReserved`  | The page is a special type, reserved for use by Microsoft only. |
```suggestion
| `microsoftReserved`  | The page is a special type reserved for Microsoft use only. |
```

2023-05-02 16:41 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
>  title: SitePage
```suggestion
title: sitePage resource type.```

2023-05-02 16:41 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
> +description: This resource represents a site page in the SitePages list.
```suggestion
description: This resource represents a site page in the sitePages list.
```

2023-05-03 02:54 UTC, Danielabom requested changes
@sangle7, please add the webpart methods to the webpart resource and update the changelog with the new webpart methods. Thanks

2023-05-12 16:26 UTC, Danielabom commented
hi @sangle7, please look at my comments and let me know when you are ready for me to do a final review. Thanks!

2023-05-15 06:45 UTC, sangle7 commented on api-reference/beta/resources/basesitepage.md
> +| Property             | Type                                                                 | Description
Thanks, addressed

2023-05-15 18:33 UTC, Danielabom commented on api-reference/beta/resources/webpart.md
> +| [Create webPart](../api/webpart-create.md)                                           | [webPart](../resources/webpart.md)                 | Create a new [webPart](../resources/webpart.md) object. |
```suggestion
| [Create webPart](../api/sitepage-create-webpart.md)                                           | [webPart](../resources/webpart.md)                 | Create a new [webPart](../resources/webpart.md) object. |
```

2023-05-15 18:35 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +              "Description": "Added the [create](https://learn.microsoft.com/en-us/graph/api/webpart-create?view=graph-rest-beta) method to the [webpart](https://learn.microsoft.com/en-us/graph/api/r
```suggestion
              "Description": "Added the [create](https://learn.microsoft.com/en-us/graph/api/sitepage-create-webpart?view=graph-rest-beta) method to the [webpart](https://learn.microsoft.com/en-us/graph/api/resources/webpart?view=graph-rest-beta) resource",
```

2023-05-15 23:47 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
> +| parentReference      | [itemReference](../resources/itemreference.md)                         | Inherited from [baseSitePage](../resources/baseSitePage.md).
We are missing a description here.

2023-05-15 23:54 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
> +description: This resource represents a site page in the sitePages list.
```suggestion
description: Represents a site page in the sitePages list.
```

2023-05-16 00:00 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
>  | canvasLayout       | [canvasLayout](../resources/canvaslayout.md)  | Indicates the layout of the content in a given SharePoint page, including horizontal sections and vertical section |
```suggestion
| canvasLayout       | [canvasLayout](../resources/canvaslayout.md)  | Indicates the layout of the content in a given SharePoint page, including horizontal sections and vertical sections. |
```

2023-05-16 00:08 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +| parentReference      | [itemReference](../resources/itemreference.md)                       | Inherited from [baseItem](../resources/baseitem.md).
We are missing a description here.

2023-05-16 00:21 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
> +| pageLayout           | [pageLayoutType](../resources/basesitepage.md#pagelayouttype-values)       | The name of the page layout of the page. The possible values are: `microsoftReserved`, `article`,
```suggestion
| pageLayout           | [pageLayout](../resources/basesitepage.md#pagelayouttype-values)       | The name of the page layout of the page. The possible values are: `microsoftReserved`, `article`, `home`, `unknownFutureValue`. |
```

2023-05-16 00:22 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
> -### pageLayoutType values
I need clarification about what happened here.
The CSDL does not show a property named webUrl for this resource, so  I see why you are removing it, but why are you adding it as an enum member? 
Did you intend to delete the enum pageLayoutType, or was it an error?  
If you want to keep the enum pageLayoutType, please remove webUrl from the enum members' table.

2023-05-16 00:26 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
We are missing two properties: "showComments" and "showRecommendedPages".

2023-05-16 00:37 UTC, Danielabom commented on api-reference/beta/resources/sitepage.md
> +| pageLayout           | [pageLayout](../resources/basesitepage.md#pagelayouttype-values)       | The name of the page layout of the page. The possible values are: `microsoftReserved`, `article`, `ho
```suggestion
| pageLayout           | [pageLayouttype](../resources/basesitepage.md#pagelayouttype-values)       | The name of the page layout of the page. The possible values are: `microsoftReserved`, `article`, `home`, `unknownFutureValue`. |
```

2023-05-16 00:37 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +| lastModifiedBy       | [identitySet](../resources/identityset.md)                           | TIdentity of the last modifier of this item. Read-only. Inherited from [baseItem](../resources/baseitem
```suggestion
| lastModifiedBy       | [identitySet](../resources/identityset.md)                           | The identity of the last modifier of this item. Read-only. Inherited from [baseItem](../resources/baseitem.md).                                                                            |
```

2023-05-16 00:42 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +
The CSDL shows a property called "publishingState", but I do not see it here. Please clarify.

2023-05-16 00:44 UTC, Danielabom commented on api-reference/beta/resources/basesitepage.md
> +| webUrl               | String                                                               | Inherited from [baseItem](../resources/baseitem.md).
We are missing a description here.

2023-05-16 01:43 UTC, Danielabom commented on api-reference/beta/api/webpart-update.md
> +description: "Update a new webPart"
```suggestion
description: "Update a webPart"
```

2023-05-16 01:46 UTC, Danielabom commented on api-reference/beta/api/sitepage-create-webpart.md
> +Create a new [webPart] at the specified position in the a [sitePage]
```suggestion
Create a new [webPart] at a specified position in the a [sitePage].
```

2023-05-16 01:47 UTC, Danielabom commented on api-reference/beta/api/sitepage-create-webpart.md
> +description: "Create a new webPart at the specified position in the a sitePage"
```suggestion
description: "Create a new webPart at a specified position in the a sitePage"
```

2023-05-16 01:48 UTC, Danielabom commented on api-reference/beta/api/sitepage-create-webpart.md
> +description: "Create a new webPart at the specified position in the a sitePage"
```suggestion
description: "Create a new webPart at a specified position in the sitePage"
```

2023-05-16 01:51 UTC, Danielabom commented on api-reference/beta/toc.yml
> +              href: api/webpart-create.md
```suggestion
              href: api/sitepage-create-webpart.md
```

2023-05-16 01:57 UTC, Danielabom requested changes
Hi @sangle7, my last comments are in. Please address them, so we can focus on the build issue. Thanks!

2023-05-24 20:59 UTC, Danielabom commented
Hi @sangle7, let me know when you are ready for me to do another review.

2023-06-01 06:17 UTC, sangle7 commented
@Danielabom  thanks! I'll have a look soon

2023-07-11 22:41 UTC, Danielabom commented on api-reference/beta/api/verticalsection-update.md
> +PATCH /sites/{site-id}/pages/{page-id}/microsoft.graph.sitePage/canvasLayout/verticalSection
My new feedback refers to this section: Hi Hanbing, 
"Please go to this do api-reference/beta/api/verticalsection-update.md and scroll to the HTTP request, the example shows a nav property called "microsoft.graph.sitePage" but it is not defined in the metadata. Also, is there a particular reason you wanted to define a nav property using the namespace?"

2023-07-11 22:42 UTC, Danielabom requested changes
@sangle7, Hi Hanbing, 
Please go to this do api-reference/beta/api/verticalsection-update.md and scroll to the HTTP request, the example shows a nav property called "microsoft.graph.sitePage" but it is not defined in the metadata. Also, is there a particular reason you wanted to define a nav property using the namespace?

2023-07-12 03:19 UTC, sangle7 commented
Hi @Danielabom, the `microsoft.graph.sitePage` is a subtype from `microsoft.graph.baseSitePage`. We're doing a type-cast here.

2023-07-12 12:42 UTC, isvargasmsft commented on api-reference/beta/api/basesitepage-list.md
> +```msgraph-interactive
Please use http instead of msgraph-interactive.
```suggestion
```http
```

2023-07-12 12:43 UTC, isvargasmsft commented on api-reference/beta/api/basesitepage-list.md
> +```msgraph-interactive
```suggestion
```http
```

2023-07-12 12:43 UTC, isvargasmsft commented on api-reference/beta/api/basesitepage-get.md
> +```msgraph-interactive
```suggestion
```http
```

2023-07-12 21:58 UTC, Danielabom approved these changes
PR approved.

2023-07-13 02:56 UTC, Lauragra commented on api-reference/beta/api/basesitepage-get.md
> +
We're missing the required H2 sections "Request body" and "Response" in this topic. For consistency we include standard H2 sections in all API topics. Please add the missing sections.

2023-07-13 02:59 UTC, Lauragra commented on api-reference/beta/api/basesitepage-list.md
> +## Available subtypes
Please don't add non-standard H2 headings to API topics. You can just make this part of the summary description by changing the heading to regular text that says "The following table lists the available subtypes."

Will there be more than one subtype in the future?

2023-07-13 03:00 UTC, Lauragra commented on api-reference/beta/api/basesitepage-get.md
> +GET /sites/{site-id}/pages/{page-id}
Global: Ideally, all examples use real-looking values instead of placeholders.

2023-07-13 03:01 UTC, Lauragra commented on api-reference/beta/api/basesitepage-list.md
> +## Example
Global: Please add the missing H2 sections to all topics to ensure that they all adhere to the standard structure for API topics.

2023-07-13 03:02 UTC, Lauragra commented on api-reference/beta/api/sitepage-create-webpart.md
> +## Example
This topic is just missing the H2 Response section.

2023-07-13 03:08 UTC, Lauragra commented on api-reference/beta/api/webpart-delete.md
> +<!-- { "blockType": "request", "name": "delete-webpart", "scopes": "sites.readwrite.all" } -->
The HTML comment should directly precede the example, so it should go under the Request H3 section.

2023-07-13 03:10 UTC, Lauragra commented on api-reference/beta/api/sitepage-create-webpart.md
> +```http
This request is missing the required HTML comment for API Doctor validation.

2023-07-13 03:11 UTC, Lauragra commented on api-reference/beta/api/webpart-update.md
> +```http
Please add the missing HTML comment for API Doctor validation.

2023-07-13 03:23 UTC, Lauragra commented on api-reference/beta/resources/basesitepage.md
> +An abstract type that represents a baseSitePage in the site page library.
This description uses the name of the resource itself. Can you make the description more clear to users? Do you need to explain what a base site page is?

2023-07-13 03:24 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Base Site page
We use sentence case for TOC entries, so please change this to "Base site page".

2023-07-13 21:39 UTC, Danielabom commented on api-reference/beta/api/basesitepage-delete.md
> +## Request headers
```suggestion
## Request headers
```

2023-07-14 01:32 UTC, merged