docs: adds taxonomy-picker.md to document mgt-taxonomy-picker
microsoftgraph/microsoft-graph-docs pull request #20975
Opened 2023-04-18 12:50 UTC by anoopt

Added documentation for `mgt-taxonomy-picker`

To do:
- [ ] `TermStore.Read.All` permission to be provided for the tenant used in the story book.
- [ ] Stories need to updated with correct term set id, term id and site id after that.

If this cannot be done, should the documentation be updated with images as per the [spec](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/next/fluentui/specs/mgt-taxonomy-picker.md)?

2023-04-18 14:51 UTC, musale commented
@anoopt I think images will do for now because we have no ETA on when the permissions will be set.

2023-04-24 18:56 UTC, sebastienlevert requested changes

2023-04-24 18:56 UTC, sebastienlevert commented on concepts/toolkit/components/taxonomy-picker.md
> +The taxonomy picker is a component that can query the [Microsoft Graph API for Taxonomy](/graph/api/resources/termstore-term?view=graph-rest-1.0) and render a dropdown control with terms, allowing se
```suggestion
The taxonomy picker is a component that can query the [Microsoft Graph API for Taxonomy](/graph/api/resources/termstore-term?view=graph-rest-beta) and render a dropdown control with terms, allowing selection of **a single** term based on the specified term set `id` or a combination of the specified term set `id` and the specified term `id`. 

```

2023-04-24 18:56 UTC, sebastienlevert commented on concepts/toolkit/components/taxonomy-picker.md
> +![mgt-taxonomy-picker-locale-term](./images/mgt-taxonomy-picker-locale-term.png)
To avoid going back to docs and edit, I'd use the same approach to iframe mgt.dev here and just showcase the default story.

2023-04-24 18:57 UTC, sebastienlevert commented on concepts/toolkit/components/taxonomy-picker.md
> +![mgt-taxonomy-picker-locale-term](./images/mgt-taxonomy-picker-locale-term.png)
Just realized the scope issues with the Sandbox... Let's leave it like this for now.

2023-05-10 18:04 UTC, sebastienlevert approved these changes

2023-05-11 09:33 UTC, musale approved these changes

2023-05-12 02:11 UTC, merged