add 2 new error type for UDP connectivity
microsoftgraph/microsoft-graph-docs pull request #21059
Opened 2023-04-25 06:14 UTC by xiaoxiye2022

add two error code for UDP connectivity

2023-04-25 06:15 UTC, xiaoxiye2022 commented
@microsoft-github-policy-service agree company="Microsoft"

2023-04-25 08:09 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "1625de52-ebc2-496e-a15c-87474fcc0e0e",
The three ids should be the same. Please fix it.

2023-04-25 08:11 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Target": "cloudPcOnPremisesConnection"
I believe the target should be `cloudPcOnPremisesConnectionHealthCheckErrorType`. Please help fix.

2023-04-25 08:14 UTC, RuiHou105 requested changes
@xiaoxiye2022 
1.Please resolve comments in the PR.
2.Please create a roadmap workitem and attach the workitem **number** in comment. Here is an [example ](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/)for you. If you don't have access, please do these firstly
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2023-04-26 03:49 UTC, xiaoxiye2022 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "1625de52-ebc2-496e-a15c-87474fcc0e0e",
fixed

2023-04-26 03:49 UTC, xiaoxiye2022 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Target": "cloudPcOnPremisesConnection"
fixed

2023-06-01 05:05 UTC, Jarbas-MSFT commented
Hi @Lauragra, this PR is ready for final review.

2023-06-03 00:05 UTC, Lauragra approved these changes

2023-06-06 03:51 UTC, merged