[Doc Feature][Get call recording API][2971340]
microsoftgraph/microsoft-graph-docs pull request #21144
Opened 2023-05-02 11:58 UTC by v-sdhakshina

2023-05-22 11:43 UTC, devjha-ms commented on api-reference/beta/api/callrecording-get.md
> +Content-type: text/vtt
Content-Type: video/mp4

2023-05-22 11:43 UTC, devjha-ms commented on api-reference/beta/api/callrecording-get.md
> +<v User Name>This is a recording test.</v>
Can we just write "binary content" here?  
When we call this API without "--out parameter then we get below warning :

Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.


We need to call this with --out parameter so that the content is written to the file. e.g

GET  'https://graph.microsoft.com/beta/users/b935e675-5e67-48b9-8d45-249d5f88e964/onlineMeetings/MSpiOTM1ZTY3NS01ZTY3LTQ4YjktOGQ0NS0yNDlkNWY4OGU5NjQqMCoqMTk6bWVldGluZ19ZbU0zTnpJNU9USXRZakU0WlMwME1tUTNMVGt6TVRRdFkyWm1PRGRtWmpsaVptRTNAdGhyZWFkLnYy/recordings/7e31db25-bc6e-4fd8-96c7-e01264e9b6fc/content' **--output meetingRecording1.mp4**

2023-05-22 12:21 UTC, v-sdhakshina commented on api-reference/beta/api/callrecording-get.md
> +<v User Name>This is a recording test.</v>
@Lauragra , request you to please provide your inputs on this comment. Devi requested you for the same.

2023-05-22 17:32 UTC, v-sdhakshina commented on api-reference/beta/api/callrecording-get.md
> +Retrieve a [callRecording](../resources/callrecording.md) object associated with an [onlineMeeting](../resources/onlinemeeting.md).
updated the docs as suggested

2023-05-22 17:33 UTC, v-sdhakshina commented on api-reference/beta/api/onlinemeeting-list-recordings.md
> +## Optional query parameters
Removed as suggested

2023-05-22 17:34 UTC, v-sdhakshina commented on api-reference/beta/api/callrecording-get.md
> +Content-type: text/vtt
Updated as suggested

2023-05-23 06:37 UTC, devjha-ms commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
Please remove "Microsoft.Teams.Shifts" and keep "SubArea": "" to maintain consistency

2023-05-23 07:04 UTC, v-sdhakshina commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
updated as suggested

2023-05-24 03:39 UTC, Anjali-Patle requested changes

2023-05-24 10:17 UTC, v-sdhakshina commented on api-reference/beta/api/callrecording-get.md
> +<v User Name>This is a recording test.</v>
As per Laura's confirmation, we need to check this with content reviewer.

2023-05-24 10:26 UTC, v-sdhakshina commented on concepts/transcripts-and-recordings.md
> +POST https://graph.microsoft.com/v1.0/subscriptions
updated the doc as suggested

2023-07-28 12:54 UTC, v-sdhakshina commented
Split the content and changes covered in other PRs

2023-07-28 12:54 UTC, closed without merging