Public Preview documentation for creating a multi-event policy (user flows)
microsoftgraph/microsoft-graph-docs pull request #21154
Opened 2023-05-02 21:29 UTC by nanguil

2023-05-11 11:59 UTC, FaithOmbongi requested changes
Hi @nanguil - 

- I've pushed a few commits for edits and clean ups. Please refer to the commit messages.
- For pending suggestions, see my comments inline.
  - PS: GitHub seems to be hiding some comments which really aren't resolved. So please check this view as well for comments and inline suggestions.
- All the pending errors relate to authenticationConditions  and authenticationEventListener which are in Steven's PR.
- You're missing the changelog: Please add it.
- Do you also need to document a List https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions/applications/includeApplications API doc? We don't have a List applications API doc (the TOC resolves to a broken link). Please confirm if we need it and document it.
- (Can be done after the initial merge) We need to document the query parameters that are supported by the entities. Also it'll be good to provide examples applying $filter.

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationconditionsapplications-delete-includeapplications.md
> +DELETE https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions/applications/includeApplications/{application-id}
Use real IDs in the URL

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationconditionsapplications-post-includeapplications.md
> +``` http
Use real IDs in the example URL and request body

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationconditionsapplications-post-includeapplications.md
> +{
Provide a real response object with read IDs

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-delete-attributes.md
> +DELETE https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAttributeCollection/microsoft.graph
URL with real IDs please

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-list-attributes.md
> +**TODO: should this return attributecollectioninputconfigurations?**
TO DO

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-list-attributes.md
> +GET https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAttributeCollection/microsoft.graph.on
Update URL with real IDs please

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-post-attributes.md
> +This requires two calls – a PATCH to add the attribute followed by a POST to add how the attribute will be displayed for sign-up. **TODO: HOW TO REPRESENT BOTH CALLS?**
To revisit

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-post-attributes.md
> +POST /identity/AuthenticationEventsFlows{authenticationEventsFlow-id}/externalUsersSelfServiceSignUpEventsFlow/onAttributeCollection/onAttributeCollectionExternalUsersSelfServiceSignUp/attributes/$re
To revisit

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-post-attributes.md
> +PATCH https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}
Real ID please

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-post-attributes.md
> +``` http
To revisit

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-delete-identityproviders.md
> +DELETE https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/OnAuthenticationMethodLoadStart/micro
Real IDs please

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-list-identityproviders.md
> +GET https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/OnAuthenticationMethodLoadStart/microsof
Real IDs please

2023-05-11 11:59 UTC, FaithOmbongi commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-post-identityproviders.md
> +POST https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microso
Real IDs please

2023-05-16 06:53 UTC, nanguil commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-post-identityproviders.md
> +POST https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microso
Done

2023-05-16 06:56 UTC, nanguil commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-list-identityproviders.md
> +GET https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/OnAuthenticationMethodLoadStart/microsof
done

2023-05-16 06:58 UTC, nanguil commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-delete-identityproviders.md
> +DELETE https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/OnAuthenticationMethodLoadStart/micro
done

2023-05-16 06:59 UTC, nanguil commented on api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-post-attributes.md
> +PATCH https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}
done

2023-05-16 08:16 UTC, nanguil commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-delete-identityproviders.md
> +DELETE https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/OnAuthenticationMethodLoadStart/micro
done

2023-05-16 08:17 UTC, nanguil commented on api-reference/beta/api/onauthenticationmethodloadstartexternalusersselfservicesignup-post-identityproviders.md
> +POST https://graph.microsoft.com/beta/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microso
done

2023-05-16 17:27 UTC, FaithOmbongi requested changes
Additional comments

2023-05-16 17:27 UTC, FaithOmbongi commented on api-reference/beta/resources/onattributecollectionlistener.md
> +|authenticationEventsFlowId|String| Inherited from [authenticationEventListener](../resources/authenticationeventlistener.md).|
- Fill descriptions for id, conditions, and authenticationEventsFlowId with what Steven put down in the base authenticationEventListener doc
- Keep alphabetical order, please.

2023-05-16 17:27 UTC, FaithOmbongi commented on api-reference/beta/resources/onauthenticationmethodloadstartlistener.md
> +|authenticationEventsFlowId|String| Inherited from [authenticationEventListener](../resources/authenticationeventlistener.md).|
- Fill descriptions for id, conditions, and authenticationEventsFlowId with what Steven put down in the base authenticationEventListener doc
- Keep alphabetical order, please.

2023-05-16 17:27 UTC, FaithOmbongi commented on api-reference/beta/resources/oninteractiveauthflowstartlistener.md
> +|authenticationEventsFlowId|String| Inherited from [authenticationEventListener](../resources/authenticationeventlistener.md).|
- Fill descriptions for id, conditions, and authenticationEventsFlowId with what Steven put down in the base authenticationEventListener doc
- Keep alphabetical order, please.

2023-05-16 17:27 UTC, FaithOmbongi commented on api-reference/beta/resources/onusercreatestartlistener.md
> +|authenticationEventsFlowId|String| Inherited from [authenticationEventListener](../resources/authenticationeventlistener.md).|
- Fill descriptions for id, conditions, and authenticationEventsFlowId with what Steven put down in the base authenticationEventListener doc
- Keep alphabetical order, please.

2023-05-17 09:27 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationconditionsapplications-delete-includeapplications.md
> +DELETE /identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions/applications/includeApplications/{application-id}
**Suggestion:** Please confirm that this API doesn't require `$ref` as the last segment in the URL. For most APIs with similar referencing, not including $ref ends up deleting the object (in this case the application) from the tenant instead of unlinking as the API intends.

2023-05-18 13:18 UTC, FaithOmbongi approved these changes

2023-05-19 03:33 UTC, merged