Public preview documentation for sponsors
microsoftgraph/microsoft-graph-docs pull request #21166
Opened 2023-05-03 17:29 UTC by sdshl

2023-05-08 09:37 UTC, FaithOmbongi requested changes
Thank you @sadia353 for your work on this PR and the well thought of changes. I've left suggestions inline plus the following:
- NOTE: For all suggestions, I defer to you for technical accuracy.
- I've left suggestions to explicitly say "guest user's" instead of just "user's" because I assume only guest users (user type = guest can have sponsors). Please confirm the technical accuracy of all the suggestions.

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/resources/user.md
> +|sponsors|[directoryObject](../resources/directoryobject.md) collection|The users and groups that are this user's sponsors. (HTTP Methods: GET, POST, DELETE.). Supports `$expand`.|
Let's try to explain without using the feature name
```suggestion
|sponsors|[directoryObject](../resources/directoryobject.md) collection|The users and groups that are responsible for this guest user's privileges in the tenant and keep the guest user's information and access updated. (HTTP Methods: GET, POST, DELETE.). Supports `$expand`.|
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/resources/user.md
> +  "sponsors": [{"@odata.type": "microsoft.graph.directoryObject"}],
No, only structural properties are added to the JSON representation. Please remove sponsors from here

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-sponsors.md
> +description: "Get user's sponsors. Returns the users or groups assigned as the user's sponsors."
```suggestion
description: "Get a guest user's sponsors."
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-sponsors.md
> +Get user's sponsors. Returns the users or groups assigned as the user's sponsors.
```suggestion
Get a guest user's sponsors. Sponsors are users and groups that are responsible for this guest user's privileges in the tenant and for keeping the guest user's information and access up to date.
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-sponsors.md
> +| Application                            | User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All |
Let's avoid documenting Directory.* permissions because they are too privileged, unless they are the only ones supported.
```suggestion
| Delegated (work or school account)     | User.Read.All, User.ReadWrite.All |
| Delegated (personal Microsoft account) | Not supported.                                                                 |
| Application                            | User.Read.All, User.ReadWrite.All|
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-sponsors.md
> +Get sponsors:
```suggestion
Get sponsors.
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-sponsors.md
> +> + You can specify `$select` inside `$expand` to select the individual sponsor's properties: `$expand=sponsors($select=id,displayName)`.
Great call out of nested $select!
No need for a note.  A regular sentence will do.
```suggestion
This method supports the `$select` and `$expand` [OData query parameters](/graph/query-parameters) to help customize the response. You can specify `$select` inside `$expand` to select the individual sponsor's properties: `$expand=sponsors($select=id,displayName)`.
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-sponsors.md
> +GET https://graph.microsoft.com/beta/users/{user-id}/sponsors
nit: You can replace `{user-id}` with a real-looking user ID.

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-post-sponsors.md
> +Assign a user or group as the user's sponsor.
```suggestion
Assign a user or group as the guest user's sponsor. Sponsors are users and groups that are responsible for this guest user's privileges in the tenant and for keeping the guest user's information and access up to date.
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-post-sponsors.md
> +|Application | User.ReadWrite.All, Directory.ReadWrite.All |
Q: If I want to assign a group as the user's sponsor, do I need _Group.Read.All_ permissions?

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-post-sponsors.md
> +### Request
Add an example 2 for group as sponsor. See the guidance for how to downgrade the heading levels when you have multiple examples so they are nested appropriately.

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-delete-sponsors.md
> +|Delegated (work or school account) | User.ReadWrite.All, Directory.ReadWrite.All    |
Q: To remove a user as sponsor, do I need *Group.Read.All* permissions?

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-delete-sponsors.md
> +> If `/$ref` is not appended to the request and the calling app has permissions to manage the sponsor object type, the sponsor object will also be deleted from Azure Active Directory (Azure AD); othe
Good call out
```suggestion
> If `/$ref` is not appended to the request and the calling app has permissions to manage the sponsor object type, the sponsor object will also be deleted from Azure Active Directory (Azure AD); otherwise, a `403 Forbidden` error is returned. For example, an app with *User.ReadWrite.All* permissions will delete a user who is a sponsor. You can restore specific objects through the [Restore deleted items API](directory-deleteditems-restore.md).
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-delete-sponsors.md
> +>**Note:** The response object shown here might be shortened for readability.
Nothing is returned so nothing is shortened
```suggestion
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-post-sponsors.md
> +description: "Assign a user or group as the user's sponsor."
Should we explicitly say "guest" or is this API supported for the _member_ user type as well?
```suggestion
description: "Assign a user or group as the guest user's sponsor."
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-delete-sponsors.md
> +description: "Remove a user's sponsor."
```suggestion
description: "Remove a guest user's sponsor."
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/api/user-delete-sponsors.md
> +Remove a user's sponsor.
```suggestion
Remove a guest user's sponsor.
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/resources/invitation.md
> +|invitedUserSponsors|[directoryObject](../resources/directoryobject.md) collection|The users or groups who are sponsors of the invited user. |
```suggestion
|invitedUserSponsors|[directoryObject](../resources/directoryobject.md) collection|The users or groups who are sponsors of the invited user. Sponsors are users and groups that are responsible for guest users' privileges in the tenant and for keeping the guest users' information and access up to date. |
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/resources/targetusersponsors.md
> +It is a subtype of [userSet](userset.md), in which the `@odata.type` value `#microsoft.graph.targetUserSponsors` indicates that a requesting user's sponsors are to be the approvers. When creating an
```suggestion
It is a subtype of [userSet](userset.md), in which the `@odata.type` value `#microsoft.graph.targetUserSponsors` indicates that a requesting user's sponsors are the approvers. When creating an access package assignment policy approval stage with **targetUserSponsors**, also include another approver, such as a single user or group member, in case the requesting user does not have sponsors.
```

2023-05-08 09:37 UTC, FaithOmbongi commented on api-reference/beta/resources/targetusersponsors.md
> +|isBackup|Boolean|For sponsors in an approval stage, indicates whether the sponsors are backup fallback approvers.Inherited from [userSet](../resources/userset.md).|
```suggestion
|isBackup|Boolean|For sponsors in an approval stage, indicates whether the sponsors are backup fallback approvers. Inherited from [userSet](../resources/userset.md).|
```

2023-05-08 09:37 UTC, FaithOmbongi commented on changelog/Microsoft.AADInviteMgr.json
> +      "SubArea": "Directory management"
```suggestion
      "WorkloadArea": "Users",
      "SubArea": ""
```

2023-05-08 09:37 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": "Directory management"
```suggestion
      "WorkloadArea": "Users",
      "SubArea": ""
```

2023-05-08 09:37 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +       "SubArea": "Identity governance"
```suggestion
       "WorkloadArea": "Identity and access",
       "SubArea": "Governance"
```

2023-05-23 21:50 UTC, sadia353 commented on api-reference/beta/api/user-delete-sponsors.md
> +description: "Remove a user's sponsor."
Sponsors is not restricted to external/guest users. So not sure if we need to have this. Let me check with PMs.

2023-05-23 22:01 UTC, sadia353 commented on api-reference/beta/api/user-post-sponsors.md
> +description: "Assign a user or group as the user's sponsor."
I'll remove guest.

2023-05-23 22:14 UTC, sadia353 commented on api-reference/beta/api/user-post-sponsors.md
> +description: "Assign a user or group as the user's sponsor."
Sponsors are not restricted to only external/guest users.

2023-05-25 08:32 UTC, sadia353 commented on api-reference/beta/api/user-delete-sponsors.md
> +|Delegated (work or school account) | User.ReadWrite.All, Directory.ReadWrite.All    |
_Group.Read.All_ is not needed to remove a user or group as a sponsor.

2023-06-30 17:33 UTC, sadia353 commented on api-reference/beta/api/user-delete-sponsors.md
> +description: "Remove a user's sponsor."
Based on discussion with PMs, keeping it as is.

2023-06-30 17:35 UTC, sadia353 commented on api-reference/beta/api/user-post-sponsors.md
> +description: "Assign a user or group as the user's sponsor."
Based on discussion with PMs not adding guest.

2023-07-10 09:18 UTC, FaithOmbongi approved these changes

2023-07-18 20:47 UTC, merged