Graph API reference docs for custom extensions and onTokenIssuanceStart
microsoftgraph/microsoft-graph-docs pull request #21193
Opened 2023-05-05 06:33 UTC by soneff

2023-05-11 20:10 UTC, FaithOmbongi requested changes
Hi @soneff - I've pushed a few commits and cross-linked to user flows where the authenticationeventsflow object is referenced. I've left feedback inline plus the following:

**GAPS:**
- Please add the changelog
- Document validateAuthenticationConfiguration action description and the required info in the API file.
- All example requests, request bodies, and response should be actual examples and not the placeholder stubs that were autogenerated.


- Every occurrence of the word "onTokenIssuanceStart", I've left suggestions to replace with a user-friendly but descriptive term for the actual event. onTokenIssuanceStart isn't a property, r/ship, or resource name so while very well named that the description can be inferred, better to use the spoken statements.
- I've pushed a few changes to use the term "custom authentication extension" (like you're identifying the feature in the TOC, instead of "custom extension". We already have an "extensions" confusion in Azure AD and we need to differentiate where possible in the descriptions as well.
- I see you also list permissions in the MSA (Delegated (personal Microsoft account)) column. Can you confirm that these APIs support MSA?
- ( To follow up after this initial PR) Can we document supported query capabilities? For example, do any of the APIs support $select, $filter, and $expand? For $filter, which operators? I notice this information isn't included in the API.md so we'll need engineering to provide this information.
   - Also we'll document at least one extra example in the LIST docs to show how to use the query parameters.




All through, I defer to you for technical accuracy.

2023-05-11 20:10 UTC, FaithOmbongi commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +The following table shows the parameters that can be used with this action. Supply a endpointConfiguration and authenticationConfiguration if querying at the root level. Otherwise, for a specific cus
Q: Should this action really be possible without an ID?

2023-05-11 20:10 UTC, FaithOmbongi commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +### Example 1:
If the action is possible both with and without a customAuthenticationExtension ID, please add a descriptive tile here.

2023-05-11 20:10 UTC, FaithOmbongi commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +### Example 2:
Add a descriptive title

2023-05-11 20:10 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +|CustomAuthenticationExtension.ReadWrite.All|Read and write your organization's custom authentication extensions|Allows the app to read or write your organization's custom authentication extensions o
Please confirm if these APIs can be called from MSA accounts. If _Delegated (personal Microsoft account)_ is truly supported, please update the last column of both rows to "Yes"

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/customauthenticationextension-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Same question about query params here

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/customauthenticationextension-get.md
> +      "@odata.type": "microsoft.graph.customExtensionEndpointConfiguration"
do we not need to show what example endpoint configuration looks like too?

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/authenticationeventlistener-get.md
> +|Delegated (work or school account)|CustomAuthenticationExtension.Read.All, Application.Read.All, CustomAuthenticationExtension.ReadWrite.All, Policy.ReadWrite.AuthenticationFlows, Application.ReadWr
is this RBAC really correct for listener? I think this might not be the case, This is a listener object so it doesn't always have to be related to custom extension

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/authenticationeventlistener-update.md
> +|conditions|[authenticationConditions](../resources/authenticationconditions.md)|The conditions on which this authenticationEventListener should trigger. Optional.|
there are other fields that can be updated correct? like the handler, etc.? 

How do we represent the API docs specifically for say token augmentation? Say token aug listener has extra fields it allows for create/update, how do we document those?

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +Supply a endpointConfiguration and authenticationConfiguration if querying at the root level.
how come we don't list the properties here?

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +POST /identity/customAuthenticationExtensions/{customAuthenticationExtensionId}/validateAuthenticationConfiguration
is this URL correct? in the example below we do not show custom extension id in the URL, and that probably makes more sense, you would check this before creating

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/identitycontainer-delete-authenticationeventlisteners.md
> +DELETE /identity/authenticationEventListeners/{authenticationEventListenerId}/$ref
what is `$ref` for?

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/identitycontainer-list-authenticationeventlisteners.md
> +                        "resourceId": "api://authenticationeventsAPI.azurewebsites.net/a13d0fc1-04ab-4ede-b215-63de0174cbb4"
are these existing APIs? should we use dummy values?

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/identitycontainer-list-customauthenticationextensions.md
> +GET /identity/customAuthenticationExtensions
inconsistent: we show relative path here unlike in the listener case.

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/identitycontainer-post-authenticationeventlisteners.md
> +|priority|Int32| The priority of this handler. Between 0 (lower priority) and 1000 (higher priority). Required.|
I think there are more properties you can supply

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/identitycontainer-post-authenticationeventlisteners.md
> +|priority|Int32| The priority of this handler. Between 0 (lower priority) and 1000 (higher priority). Required.|
such as handler

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/api/identitycontainer-post-authenticationeventlisteners.md
> +|priority|Int32| The priority of this handler. Between 0 (lower priority) and 1000 (higher priority). Required.|
I guess the base listener does not have a handler, so mm.. yeah kinda weird way of documenting this, but I understand now why

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/authenticationconditionsapplications.md
> +|includeApplications|[authenticationConditionApplication](../resources/authenticationconditionapplication.md) collection|Collection of the application conditions on which an authenticationEventListen
I don't think the includeApplications is a relationship here, not sure about the terminology, but includeApplications is the property of this entity, which has a list of applications links, does the whole collection count as a relationship?

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/authenticationconditionsapplications.md
> +  "includeAllApplications": "Boolean"
there is a nuance where for TokenAug we do not allow to set includeAllApplications flag, idk how we want to represent this

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/customauthenticationextension.md
> +Custom authentication extensions define interactions with external systems during a user authentication. This is an abstract type.
does user creation count as user authentication as well? I would just rename this to be something like 

`Custom authentication extensions define interactions with external systems during authentication pipeline`

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/customauthenticationextension.md
> +|[validateAuthenticationConfiguration](../api/customauthenticationextension-validateauthenticationconfiguration.md)|[authenticationConfigurationValidation](../resources/authenticationconfigurationval
is this a dup?

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/customauthenticationextension.md
> +|description|String|The description of the customAuthenticationExtension. Inherited from [customCalloutExtension](../resources/customcalloutextension.md).|
I don't see these fields present on `customCalloutExtension`

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/customextensionclientconfiguration.md
> +HTTP connection settings that define how long Azure AD can wait for a a response from an external app before it shuts down the connection when trying to trigger the external app. Only **timeoutInMill
This class does not imply HTTP, it is just defines the connection configurations for custom extension call

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/customextensionclientconfiguration.md
> +HTTP connection settings that define how long Azure AD can wait for a a response from an external app before it shuts down the connection when trying to trigger the external app. Only **timeoutInMill
meaning that we can theoretically use other means to connect to 3rd party resources, not just HTTP

2023-05-11 20:51 UTC, robezirg commented on api-reference/beta/resources/customextensionendpointconfiguration.md
> +- [httpRequestEndpoint](../resources/httprequestendpoint.md) - configure this object to [validate a custom authentication extension](../api/customauthenticationextension-validateauthenticationconfigu
I don't see the connection of this and `[validate a custom authentication extension]`. how is this required to validate custom auth extension?

2023-05-12 11:11 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationeventlistener-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
We'll do this in the follow up PR. The API.md doesn't explicitly call out the query capabilities so we'll need your team's help to confirm for all entities. We'll also add additional examples showing how to use the query capabilities.

2023-05-15 05:56 UTC, soneff commented on api-reference/beta/api/identitycontainer-delete-customauthenticationextensions.md
> +DELETE https://graph.microsoft.com/beta/identity/customAuthenticationExtensions/{customAuthenticationExtensionId}
An ID of a real custom extension? Wouldn't that value only make sense in my test tenant? Isn't a placeholder value more illustrative? And Graph explorer nicely reminds me to replace placeholders

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/authenticationeventlistener-get.md
> +GET https://graph.microsoft.com/beta/identity/authenticationEventListeners/{authenticationEventListenerId}
(not sure if my other comment posted)
Do you mean the ID value of a real custom extension? Wouldn't that value only make sense in my test tenant? Isn't a placeholder value more illustrative? (and Graph Explorer will nicely warn me about a placeholder value)

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/authenticationeventlistener-update.md
> +|conditions|[authenticationConditions](../resources/authenticationconditions.md)|The conditions on which this authenticationEventListener should trigger. Optional.|
@FaithOmbongi you added thumbs up, but I'm not sure what the answers to these questions are

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-get.md
> +      "@odata.type": "microsoft.graph.customExtensionEndpointConfiguration"
Will add a real payload per guidance from Faith

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +POST /identity/customAuthenticationExtensions/{customAuthenticationExtensionId}/validateAuthenticationConfiguration
Yes, it supports both with ID (validate existing), and without (validate a potential, with config in POST request body)

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +The following table shows the parameters that can be used with this action. Supply a endpointConfiguration and authenticationConfiguration if querying at the root level. Otherwise, for a specific cus
Yes, without an ID, this action validates a potential configure provided in the POST body. Will add descriptive titles below

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +### Example 1:
Ack

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +### Example 2:
Ack

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/identitycontainer-list-authenticationeventlisteners.md
> +                        "resourceId": "api://authenticationeventsAPI.azurewebsites.net/a13d0fc1-04ab-4ede-b215-63de0174cbb4"
@FaithOmbongi does your thumbs up mean that these should indeed be dummy or placeholder values? How does that reconcile with comments above for real payloads?

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/api/identitycontainer-list-customauthenticationextensions.md
> +GET /identity/customAuthenticationExtensions
@FaithOmbongi should these be relative or absolute paths?

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/resources/authenticationconditionsapplications.md
> +|includeApplications|[authenticationConditionApplication](../resources/authenticationconditionapplication.md) collection|Collection of the application conditions on which an authenticationEventListen
@FaithOmbongi are you able to provide insight on properties vs relationships? I was wondering similar to Robert...

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/resources/authenticationconditionsapplications.md
> +  "includeAllApplications": "Boolean"
That's good to know. Let me think about this ... could say here that some listeners can't trigger on all applications, and note it in the docs for specific listeners?

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/resources/authenticationeventlistener.md
> +description: "**TODO: Add Description**"
Oops, will add

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/resources/customauthenticationextension.md
> +|description|String|The description of the customAuthenticationExtension. Inherited from [customCalloutExtension](../resources/customcalloutextension.md).|
I see them in the current live public docs: https://learn.microsoft.com/en-us/graph/api/resources/customcalloutextension?view=graph-rest-beta

Did I mix something up?

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/resources/customextensionclientconfiguration.md
> +HTTP connection settings that define how long Azure AD can wait for a a response from an external app before it shuts down the connection when trying to trigger the external app. Only **timeoutInMill
Looks like Faith updated this, resolving

2023-05-15 06:23 UTC, soneff commented on api-reference/beta/resources/ontokenissuancestartcustomextension.md
> +description: "Custom extension to invoke when handling an onTokenIssuanceStart event."
I'll take a pass on the language on the next update

2023-05-15 10:13 UTC, FaithOmbongi requested changes

2023-05-15 10:13 UTC, FaithOmbongi commented on api-reference/beta/resources/customauthenticationextension.md
> +|description|String|The description of the customAuthenticationExtension. Inherited from [customCalloutExtension](../resources/customcalloutextension.md).|
Nope, we're good.

2023-05-15 10:13 UTC, FaithOmbongi commented on api-reference/beta/api/identitycontainer-delete-customauthenticationextensions.md
> +DELETE https://graph.microsoft.com/beta/identity/customAuthenticationExtensions/{customAuthenticationExtensionId}
Because we're showing real examples, customers prefer to see the ID in the URL and real values in the payloads. This is especially true when the ID isn't strictly a GUID. We're improving the docs Try It experience so Graph Explorer notifies the customer to update the specific IDs with their own values.

The placeholder is useful in the HTTP request section above.

2023-05-15 16:03 UTC, soneff commented on api-reference/beta/api/authenticationeventlistener-update.md
> +|conditions|[authenticationConditions](../resources/authenticationconditions.md)|The conditions on which this authenticationEventListener should trigger. Optional.|
OK, so I think this means we need to list the handler here, and document which subtypes it applies to? Do I understand that right?

2023-05-15 16:09 UTC, soneff commented on api-reference/beta/api/identitycontainer-post-authenticationeventlisteners.md
> +|priority|Int32| The priority of this handler. Between 0 (lower priority) and 1000 (higher priority). Required.|
Thanks for the example, I think that answers my question above ... will add handler here and we'll have document each custom extension handler type that supports it

2023-05-15 16:09 UTC, soneff commented on api-reference/beta/resources/customextensionendpointconfiguration.md
> +- [httpRequestEndpoint](../resources/httprequestendpoint.md) - configure this object to [validate a custom authentication extension](../api/customauthenticationextension-validateauthenticationconfigu
I think this is OK per Faith comment

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/authenticationeventlistener-update.md
> +{
Added

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/authenticationeventlistener-update.md
> +PATCH https://graph.microsoft.com/beta/identity/authenticationEventListeners/{authenticationEventListenerId}
Added

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/authenticationeventlistener-get.md
> +{
Added

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-update.md
> +  "@odata.type": "#microsoft.graph.customAuthenticationExtension",
Added

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +### Example 1:
Updated

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
> +### Example 2:
Updated

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/identitycontainer-delete-customauthenticationextensions.md
> +DELETE https://graph.microsoft.com/beta/identity/customAuthenticationExtensions/{customAuthenticationExtensionId}
Ack, updated

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/api/identitycontainer-list-authenticationeventlisteners.md
> +                        "resourceId": "api://authenticationeventsAPI.azurewebsites.net/a13d0fc1-04ab-4ede-b215-63de0174cbb4"
Done

2023-05-15 17:10 UTC, soneff commented on api-reference/beta/resources/authenticationconditionsapplications.md
> +  "includeAllApplications": "Boolean"
done

2023-05-15 19:40 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationeventlistener-update.md
> +|conditions|[authenticationConditions](../resources/authenticationconditions.md)|The conditions on which this authenticationEventListener should trigger. Optional.|
Correct.

2023-05-15 20:18 UTC, FaithOmbongi approved these changes
Hi @soneff - I've pushed a few commits and approved the PR for merge.

We can follow up on the pending items such as query capabilities and the API Overview after Build.

2023-05-15 21:03 UTC, soneff commented on api-reference/beta/api/authenticationeventlistener-update.md
> +|conditions|[authenticationConditions](../resources/authenticationconditions.md)|The conditions on which this authenticationEventListener should trigger. Optional.|
Added

2023-05-15 21:03 UTC, soneff commented on api-reference/beta/api/identitycontainer-post-authenticationeventlisteners.md
> +|priority|Int32| The priority of this handler. Between 0 (lower priority) and 1000 (higher priority). Required.|
Added

2023-05-16 03:47 UTC, merged