Adding OrgSettings Docs
microsoftgraph/microsoft-graph-docs pull request #21239
Opened 2023-05-09 22:21 UTC by zadinsmo

Adding documentation for org settings.

2023-05-10 17:13 UTC, jakeost-msft approved these changes

2023-05-11 16:08 UTC, zadinsmo commented
Adding Organization Settings to graph. These are organization wide settings for various M365 Apps.
Road Item # 17426.

2023-05-19 16:58 UTC, Danielabom commented
The author will make a change and let me know when to start the review.

2023-05-23 17:41 UTC, Danielabom commented on api-reference/beta/resources/todosettings.md
> +|isExternalJoinEnabled|Boolean|**Controls whether users can join lists from users external to your organization.**|
```suggestion
|isExternalJoinEnabled|Boolean|Controls whether users can join lists from users external to your organization.|
```

2023-05-23 17:41 UTC, Danielabom commented on api-reference/beta/resources/todosettings.md
> +|isExternalShareEnabled|Boolean|**Controls whether users can share lists to external users.**|
```suggestion
|isExternalShareEnabled|Boolean|Controls whether users can share lists with external users.|
```

2023-05-23 17:42 UTC, Danielabom commented on api-reference/beta/resources/todosettings.md
> +|isPushNotificationEnabled|Boolean|**Controls whether push notifications are enabled for your users or not.**|
```suggestion
|isPushNotificationEnabled|Boolean|Controls whether push notifications are enabled for your users.|
```

2023-05-23 17:42 UTC, Danielabom commented on api-reference/beta/resources/todosettings.md
> +description: "**Company wide settings for Microsoft Todo**"
```suggestion
description: "Company-wide settings for Microsoft Todo"
```

2023-05-23 17:44 UTC, Danielabom commented on api-reference/beta/resources/todosettings.md
> +**Company wide settings for Microsoft Todo**
```suggestion
Company-wide settings for Microsoft Todo.
```

2023-05-23 17:59 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +description: "**Company wide settings for Microsoft Forms**"
```suggestion
description: "Company-wide settings for Microsoft Forms"
```

2023-05-23 17:59 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +**Company wide settings for Microsoft Forms**
```suggestion
Company-wide settings for Microsoft Forms. 
```

2023-05-23 18:00 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +**Company wide settings for Microsoft Forms**
Please add the link to the parent entity for Microsoft Forms (if available).

2023-05-23 18:01 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +|isBingImageSearchEnabled|Boolean|**Controls whether users can add images from Bing to forms.**|
```suggestion
|isBingImageSearchEnabled|Boolean|Controls whether users can add images from Bing to forms.|
```

2023-05-23 18:01 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +|isExternalSendFormEnabled|Boolean|**Controls whether users can send a link to a form to an external user.**|
```suggestion
|isExternalSendFormEnabled|Boolean|Controls whether users can send a link to a form to an external user.|
```

2023-05-23 18:01 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +|isExternalShareCollaborationEnabled|Boolean|**Controls whether users can collaborate on a form layout and structure with an external user.**|
```suggestion
|isExternalShareCollaborationEnabled|Boolean|Controls whether users can collaborate on a form layout and structure with an external user.|
```

2023-05-23 18:04 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +|isExternalShareResultEnabled|Boolean|**Controls whether users can share form results with external users.**|
```suggestion
|isExternalShareResultEnabled|Boolean|Controls whether users can share form results with external users.|
```

2023-05-23 18:04 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +|isExternalShareTemplateEnabled|Boolean|**Controls whether users can shareform templates with external users.**|
```suggestion
|isExternalShareTemplateEnabled|Boolean|Controls whether users can share form templates with external users.|
```

2023-05-23 18:05 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +|isInOrgFormsPhishingScanEnabled|Boolean|**Controls whether phishing protection is run on forms created by users, blocking creation of forms if common phishing questions are detected.**|
```suggestion
|isInOrgFormsPhishingScanEnabled|Boolean|Controls whether phishing protection is run on forms created by users, blocking the creation of forms if common phishing questions are detected.|
```

2023-05-23 18:05 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +|isRecordIdentityByDefaultEnabled|Boolean|**Controls whether names of users who fill out forms are recorded.**|
```suggestion
|isRecordIdentityByDefaultEnabled|Boolean|Controls whether the names of users who fill out forms are recorded.|
```

2023-05-23 18:08 UTC, Danielabom commented on api-reference/beta/resources/customervoicesettings.md
> +**Company wide settings for Dynamics customer voice**
```suggestion
Company-wide settings for Dynamics customer voice.
```

2023-05-23 18:27 UTC, Danielabom commented on api-reference/beta/resources/customervoicesettings.md
> +description: "**Company wide settings for Dynamics customer voice**"
The branded name is Microsoft Dynamics 365 Customer Voice. The first time we use it in a doc, we must use the fully branded, and then we can go with Dynamics 365 Customer Voice.

2023-05-23 18:30 UTC, Danielabom commented on api-reference/beta/resources/customervoicesettings.md
> +|isInOrgFormsPhishingScanEnabled|Boolean|**Controls whether phishing protection is run on forms created by users, blocking creation of forms if common phishing questions are detected.**|
```suggestion
|isInOrgFormsPhishingScanEnabled|Boolean|Controls whether phishing protection is run on forms created by users, blocking the creation of forms if common phishing questions are detected.|
```

2023-05-23 18:31 UTC, Danielabom commented on api-reference/beta/resources/customervoicesettings.md
> +|isRecordIdentityByDefaultEnabled|Boolean|**Controls whether names of users who fill out forms are recorded.**|
```suggestion
|isRecordIdentityByDefaultEnabled|Boolean|Controls whether the names of users who fill out forms are recorded.|
```

2023-05-23 18:31 UTC, Danielabom commented on api-reference/beta/resources/customervoicesettings.md
> +|isRestrictedSurveyAccessEnabled|Boolean|**Controls whether only users inside your organization can submit a response.**|
```suggestion
|isRestrictedSurveyAccessEnabled|Boolean|Controls whether only users inside your organization can submit a response.|
```

2023-05-23 18:34 UTC, Danielabom commented on api-reference/beta/resources/appsandservicessettings.md
> +**Company wide settings for apps and services**
```suggestion
Company-wide settings for apps and services.
```

2023-05-23 18:37 UTC, Danielabom commented on api-reference/beta/resources/appsandservicessettings.md
> +|isOfficeStoreEnabled|Boolean|**Controls whether users can access the Office Store.**|
Office Store is not a branded name. Can you replace it with Microsoft Store?

2023-05-23 18:43 UTC, Danielabom commented on api-reference/beta/resources/formssettings.md
> +Company-wide settings for Microsoft Forms.
Is there a parent resource for Microsoft Forms? If so, please add it here.

2023-05-23 18:46 UTC, Danielabom commented on api-reference/beta/resources/admintodo.md
> +description: "**Company wide configuration for Microsoft Todo**"
```suggestion
description: "Company-wide configuration for Microsoft Todo"
```

2023-05-23 18:46 UTC, Danielabom commented on api-reference/beta/resources/admintodo.md
> +**Company wide configuration for Microsoft Todo**
```suggestion
Company-wide configuration for Microsoft Todo.
```

2023-05-23 18:47 UTC, Danielabom commented on api-reference/beta/resources/admintodo.md
> +|settings|[microsoft.graph.todoSettings](../resources/todosettings.md)|**Company wide settings for Microsoft Todo**|
```suggestion
|settings|[microsoft.graph.todoSettings](../resources/todosettings.md)|Company-wide settings for Microsoft Todo.|
```

2023-05-23 18:47 UTC, Danielabom commented on api-reference/beta/resources/admintodo.md
> +|id|String|**Unique Id** Inherited from [microsoft.graph.entity](../resources/entity.md).|
```suggestion
|id|String|Unique Id. Inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-05-23 18:49 UTC, Danielabom commented on api-reference/beta/resources/adminforms.md
> +---
Please add the entity and its method to the TOC.

2023-05-23 18:51 UTC, Danielabom commented on api-reference/beta/resources/admintodo.md
> +---
Please add the entity and its method to the TOC.

2023-05-23 18:51 UTC, Danielabom commented on api-reference/beta/resources/adminforms.md
> +description: "**Company wide configuration for Microsoft Forms**"
```suggestion
description: "Company-wide configuration for Microsoft Forms"
```

2023-05-23 18:52 UTC, Danielabom commented on api-reference/beta/resources/adminforms.md
> +**Company wide configuration for Microsoft Forms**
```suggestion
Company-wide configuration for Microsoft Forms.
```

2023-05-23 18:52 UTC, Danielabom commented on api-reference/beta/resources/adminforms.md
> +**Company wide configuration for Microsoft Forms**
Please add the link to the parent entity for Microsoft Forms.

2023-05-23 18:53 UTC, Danielabom commented on api-reference/beta/resources/adminforms.md
> +|id|String|**Unique Id** Inherited from [microsoft.graph.entity](../resources/entity.md).|
```suggestion
|id|String|Unique Id. Inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-05-23 20:47 UTC, Danielabom commented on api-reference/beta/resources/admindynamics.md
> +---
Since this is an entity with methods, please add the topics to the TOC.

2023-05-23 20:48 UTC, Danielabom commented on api-reference/beta/resources/admindynamics.md
> +description: "**Company wide configuration for Dynamics 365**"
```suggestion
description: "Company-wide configuration for Microsoft Dynamics 365"
```

2023-05-23 20:55 UTC, Danielabom commented on api-reference/beta/resources/admindynamics.md
> +**Company wide configuration for Dynamics 365**
```suggestion
Company-wide configuration for Microsoft Dynamics 365.
```

2023-05-23 20:58 UTC, Danielabom commented on api-reference/beta/resources/admindynamics.md
> +|customerVoice|[microsoft.graph.customerVoiceSettings](../resources/customervoicesettings.md)|**Company wide settings for Dynamics customer voice**|
```suggestion
|customerVoice|[microsoft.graph.customerVoiceSettings](../resources/customervoicesettings.md)|Company-wide settings for Microsoft Dynamics 365 Customer Voice.|
```

2023-05-23 20:58 UTC, Danielabom commented on api-reference/beta/resources/admindynamics.md
> +|id|String|**Unique Id** Inherited from [microsoft.graph.entity](../resources/entity.md).|
```suggestion
|id|String|Unique Id. Inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-05-23 21:06 UTC, Danielabom commented on api-reference/beta/resources/adminappsandservices.md
> +---
Please add this entity and its methods to the TOC.

2023-05-23 21:06 UTC, Danielabom commented on api-reference/beta/resources/adminappsandservices.md
> +description: "**Company wide configuration for apps and services**"
```suggestion
description: "Company-wide configuration for apps and services"
```

2023-05-23 21:07 UTC, Danielabom commented on api-reference/beta/resources/adminappsandservices.md
> +**Company wide configuration for apps and services**
```suggestion
Company-wide configuration for apps and services.
```

2023-05-23 21:08 UTC, Danielabom commented on api-reference/beta/resources/adminappsandservices.md
> +|id|String|**Unique id** Inherited from [microsoft.graph.entity](../resources/entity.md).|
```suggestion
|id|String|Unique id. Inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-05-23 21:08 UTC, Danielabom commented on api-reference/beta/resources/adminappsandservices.md
> +|settings|[microsoft.graph.appsAndServicesSettings](../resources/appsandservicessettings.md)|**Company wide settings for apps and services**|
```suggestion
|settings|[microsoft.graph.appsAndServicesSettings](../resources/appsandservicessettings.md)|Company-wide settings for apps and services.|
```

2023-05-24 15:25 UTC, Danielabom commented on api-reference/beta/resources/adminappsandservices.md
> +Company-wide configuration for apps and services.
Global comment (a global comment applies to all the files and the specific section in which the comment is inserted): Please add the links to the descriptions in lines 15 or 16 of the files.

2023-05-24 15:28 UTC, Danielabom commented on api-reference/beta/resources/admintodo.md
> +
Please add the update op to the methods table.

2023-05-24 15:28 UTC, Danielabom commented on api-reference/beta/api/admintodo-update.md
> +# Update adminTodo
Please add the op to the admintodo resource.

2023-05-24 15:30 UTC, Danielabom commented on api-reference/beta/resources/adminforms.md
> +|[Get adminForms](../api/adminforms-get.md)|[microsoft.graph.adminForms](../resources/adminforms.md)|Read the properties and relationships of a [microsoft.graph.adminForms](../resources/adminforms.md
Please add the update op in the methods table.

2023-05-24 15:31 UTC, Danielabom commented on api-reference/beta/resources/admindynamics.md
> +|[Get adminDynamics](../api/admindynamics-get.md)|[microsoft.graph.adminDynamics](../resources/admindynamics.md)|Read the properties and relationships of a [microsoft.graph.adminDynamics](../resource
Please add the update op in the methods table.

2023-05-24 15:35 UTC, Danielabom commented on api-reference/beta/api/admindynamics-get.md
> +|Delegated (work or school account)|**OrgSettings-DynamicsVoice.Read.All, OrgSettings-DynamicsVoice.ReadWrite.All**|
```suggestion
|Delegated (work or school account)|OrgSettings-DynamicsVoice.Read.All, OrgSettings-DynamicsVoice.ReadWrite.All|
```

2023-05-24 15:38 UTC, Danielabom commented on api-reference/beta/api/admintodo-update.md
> +|Delegated (work or school account)|**OrgSettings-Todo.ReadWrite.All**|
Global comment (applies to the same section in all the files): Please remove the bold format from the content in the permissions column of this table.```suggestion
|Delegated (work or school account)|OrgSettings-Todo.ReadWrite.All|
```

2023-05-24 15:39 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-update.md
> +# Update adminAppsAndServices
Please add this op in the methods table of the adminAppsAndServices of this resource file.

2023-05-24 15:43 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-get.md
> +|Delegated (work or school account)|**OrgSettings-AppsAndServices.Read.All, OrgSettings-AppsAndServices.ReadWrite.All**|
Global comment (applies to the same section in all the files): Please remove the bold format from the content in the permissions column of this table.```suggestion
|Delegated (work or school account)|OrgSettings-AppsAndServices.Read.All, OrgSettings-AppsAndServices.ReadWrite.All|
```

2023-05-24 15:45 UTC, Danielabom requested changes
@zadinsmo, thank you for working on this PR. Please review my comments. Thanks!

2023-06-06 17:51 UTC, Danielabom commented
@zadinsmo, please ping me once the changes are in. Thanks!

2023-06-07 21:22 UTC, jakeost-msft commented on api-reference/beta/api/adminappsandservices-get.md
> +|Delegated (work or school account)|**OrgSettings-AppsAndServices.Read.All, OrgSettings-AppsAndServices.ReadWrite.All**|
Updated.

2023-06-07 21:30 UTC, jakeost-msft commented on api-reference/beta/resources/adminappsandservices.md
> +|[Get adminAppsAndServices](../api/adminappsandservices-get.md)|[microsoft.graph.adminAppsAndServices](../resources/adminappsandservices.md)|Read the properties and relationships of a [microsoft.grap
Updated

2023-06-07 21:41 UTC, jakeost-msft commented on api-reference/beta/api/adminappsandservices-update.md
> +# Update adminAppsAndServices
updated

2023-06-07 21:42 UTC, jakeost-msft commented on api-reference/beta/api/admindynamics-get.md
> +|Delegated (work or school account)|**OrgSettings-DynamicsVoice.Read.All, OrgSettings-DynamicsVoice.ReadWrite.All**|
updated

2023-06-07 21:44 UTC, jakeost-msft commented on api-reference/beta/resources/admindynamics.md
> +|[Get adminDynamics](../api/admindynamics-get.md)|[microsoft.graph.adminDynamics](../resources/admindynamics.md)|Read the properties and relationships of a [microsoft.graph.adminDynamics](../resource
updated

2023-06-07 21:44 UTC, jakeost-msft commented on api-reference/beta/api/admindynamics-update.md
> +# Update adminDynamics
updated

2023-06-07 21:45 UTC, jakeost-msft commented on api-reference/beta/resources/adminforms.md
> +|[Get adminForms](../api/adminforms-get.md)|[microsoft.graph.adminForms](../resources/adminforms.md)|Read the properties and relationships of a [microsoft.graph.adminForms](../resources/adminforms.md
updated

2023-06-07 21:45 UTC, jakeost-msft commented on api-reference/beta/api/admintodo-update.md
> +|Delegated (work or school account)|**OrgSettings-Todo.ReadWrite.All**|
updated

2023-06-07 21:46 UTC, jakeost-msft commented on api-reference/beta/resources/admintodo.md
> +
updated

2023-06-07 21:46 UTC, jakeost-msft commented on api-reference/beta/api/admintodo-update.md
> +# Update adminTodo
updated

2023-06-16 21:22 UTC, zadinsmo commented on api-reference/beta/resources/formssettings.md
> +Company-wide settings for Microsoft Forms.
No, this follows the same pattern of the other settings

2023-06-16 21:23 UTC, zadinsmo commented on api-reference/beta/api/adminforms-update.md
> +# Update adminForms
updated

2023-06-16 21:24 UTC, zadinsmo commented on api-reference/beta/resources/adminappsandservices.md
> +Company-wide configuration for apps and services.
I'm not sure I understand this comment. What am I linking to?

2023-06-16 21:59 UTC, zadinsmo commented on api-reference/beta/resources/adminappsandservices.md
> +---
added

2023-06-16 22:00 UTC, zadinsmo commented on api-reference/beta/resources/admindynamics.md
> +---
added

2023-06-16 22:01 UTC, zadinsmo commented on api-reference/beta/resources/admintodo.md
> +---
added

2023-06-16 22:01 UTC, zadinsmo commented on api-reference/beta/resources/adminforms.md
> +---
added

2023-06-17 01:12 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-get.md
> +|Delegated (personal Microsoft account)|**Not supported.**|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2023-06-17 01:13 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-get.md
> +description: "Read the properties and relationships of a microsoft.graph.adminAppsAndServices object."
```suggestion
description: "Read the properties and relationships of a Microsoft Graph adminAppsAndServices object."
```

2023-06-17 01:15 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-update.md
> +description: "Update the properties of a microsoft.graph.adminAppsAndServices object."
```suggestion
description: "Update the properties of a Microsoft Graph adminAppsAndServices object."
```

2023-06-17 01:17 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-update.md
> +|Delegated (work or school account)|**OrgSettings-AppsAndServices.ReadWrite.All**|
```suggestion
|Delegated (work or school account)|OrgSettings-AppsAndServices.ReadWrite.All|
```

2023-06-17 01:18 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-update.md
> +|Delegated (personal Microsoft account)|**Not supported.**|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2023-06-17 01:18 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-update.md
> +|Application|**OrgSettings-AppsAndServices.ReadWrite.All**|
```suggestion
|Application|OrgSettings-AppsAndServices.ReadWrite.All|
```

2023-06-17 01:19 UTC, Danielabom commented on api-reference/beta/api/adminappsandservices-update.md
> +|settings|[microsoft.graph.appsAndServicesSettings](../resources/appsandservicessettings.md)|**Company wide settings for apps and services** Required.|
```suggestion
|settings|[microsoft.graph.appsAndServicesSettings](../resources/appsandservicessettings.md)|Company-wide settings for apps and services.Required.|
```

2023-06-17 01:56 UTC, Danielabom commented on api-reference/beta/api/admindynamics-get.md
> +description: "Read the properties and relationships of a microsoft.graph.adminDynamics object."
```suggestion
description: "Read the properties and relationships of a Microsoft Graph adminDynamics object."
```

2023-06-17 01:56 UTC, Danielabom commented on api-reference/beta/api/admindynamics-get.md
> +|Delegated (personal Microsoft account)|**Not supported.**|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2023-06-17 01:57 UTC, Danielabom commented on api-reference/beta/api/admindynamics-get.md
> +|Application|**OrgSettings-DynamicsVoice.Read.All, OrgSettings-DynamicsVoice.ReadWrite.All**|
```suggestion
|Application|OrgSettings-DynamicsVoice.Read.All, OrgSettings-DynamicsVoice.ReadWrite.All|
```

2023-06-17 01:58 UTC, Danielabom commented on api-reference/beta/api/admindynamics-update.md
> +description: "Update the properties of a microsoft.graph.adminDynamics object."
```suggestion
description: "Update the properties of a Microsoft Graph adminDynamics object."
```

2023-06-17 01:59 UTC, Danielabom commented on api-reference/beta/api/admindynamics-update.md
> +|Delegated (work or school account)|**OrgSettings-DynamicsVoice.ReadWrite.All**|
```suggestion
|Delegated (work or school account)|OrgSettings-DynamicsVoice.ReadWrite.All|
```

2023-06-17 01:59 UTC, Danielabom commented on api-reference/beta/api/admindynamics-update.md
> +|Delegated (personal Microsoft account)|**Not supported.**|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2023-06-17 01:59 UTC, Danielabom commented on api-reference/beta/api/admindynamics-update.md
> +|Application|**OrgSettings-DynamicsVoice.ReadWrite.All**|
```suggestion
|Application|**OrgSettings-DynamicsVoice.ReadWrite.All**|
```
```suggestion
|Application|OrgSettings-DynamicsVoice.ReadWrite.All|
```

2023-06-17 02:01 UTC, Danielabom commented on api-reference/beta/api/adminforms-get.md
> +description: "Read the properties and relationships of a microsoft.graph.adminForms object."
```suggestion
description: "Read the properties and relationships of a Microsoft Graph adminForms object."
```

2023-06-17 02:25 UTC, Danielabom commented on api-reference/beta/api/adminforms-get.md
> +|Delegated (work or school account)|**OrgSettings-Forms.Read.All, OrgSettings-Forms.ReadWrite.All**|
```suggestion
|Delegated (work or school account)|OrgSettings-Forms.Read.All, OrgSettings-Forms.ReadWrite.All|
```

2023-06-17 02:26 UTC, Danielabom commented on api-reference/beta/api/adminforms-get.md
> +|Delegated (personal Microsoft account)|**Not supported.**|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2023-06-17 02:26 UTC, Danielabom commented on api-reference/beta/api/adminforms-get.md
> +|Application|**OrgSettings-Forms.Read.All, OrgSettings-Forms.ReadWrite.All**|
```suggestion
|Application|OrgSettings-Forms.Read.All, OrgSettings-Forms.ReadWrite.All|
```

2023-06-17 02:27 UTC, Danielabom commented on api-reference/beta/api/adminforms-update.md
> +description: "Update the properties of a microsoft.graph.adminForms object."
```suggestion
description: "Update the properties of a Microsoft Graph.adminForms object."
```

2023-06-17 02:28 UTC, Danielabom commented on api-reference/beta/api/adminforms-update.md
> +|Delegated (work or school account)|**OrgSettings-Forms.ReadWrite.All**|
```suggestion
|Delegated (work or school account)|OrgSettings-Forms.ReadWrite.All|
```

2023-06-17 02:29 UTC, Danielabom commented on api-reference/beta/api/adminforms-update.md
> +|Delegated (personal Microsoft account)|**Not supported.**|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2023-06-17 02:29 UTC, Danielabom commented on api-reference/beta/api/adminforms-update.md
> +|Application|**OrgSettings-Forms.ReadWrite.All**|
```suggestion
|Application|OrgSettings-Forms.ReadWrite.All|
```

2023-06-17 02:30 UTC, Danielabom commented on api-reference/beta/api/adminforms-update.md
> +|settings|[microsoft.graph.formsSettings](../resources/formssettings.md)|**Company wide settings for Microsoft Forms** Required.|
```suggestion
|settings|[microsoft.graph.formsSettings](../resources/formssettings.md)|Company-wide settings for Microsoft Forms. Required.|
```

2023-06-17 02:31 UTC, Danielabom commented on api-reference/beta/api/admintodo-get.md
> +description: "Read the properties and relationships of a microsoft.graph.adminTodo object."
```suggestion
description: "Read the properties and relationships of a Microsoft Graph adminTodo object."
```

2023-06-17 02:31 UTC, Danielabom commented on api-reference/beta/api/admintodo-get.md
> +|Delegated (work or school account)|**OrgSettings-Todo.Read.All, OrgSettings-Todo.ReadWrite.All**|
```suggestion
|Delegated (work or school account)|OrgSettings-Todo.Read.All, OrgSettings-Todo.ReadWrite.All|
```

2023-06-17 02:32 UTC, Danielabom commented on api-reference/beta/api/admintodo-get.md
> +|Delegated (personal Microsoft account)|**Not supported.**|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2023-06-17 02:32 UTC, Danielabom commented on api-reference/beta/api/admintodo-get.md
> +|Application|**OrgSettings-Todo.Read.All, OrgSettings-Todo.ReadWrite.All**|
```suggestion
|Application|OrgSettings-Todo.Read.All, OrgSettings-Todo.ReadWrite.All|
```

2023-06-17 02:34 UTC, Danielabom commented on api-reference/beta/api/admindynamics-update.md
> +|customerVoice|[microsoft.graph.customerVoiceSettings](../resources/customervoicesettings.md)|**Company wide settings for Dynamics customer voice** Required.|
```suggestion
|customerVoice|[microsoft.graph.customerVoiceSettings](../resources/customervoicesettings.md)|Company-wide settings for Dynamics customer voice. Required.|
```

2023-06-17 02:35 UTC, Danielabom commented on api-reference/beta/api/admintodo-update.md
> +description: "Update the properties of a microsoft.graph.adminTodo object."
```suggestion
description: "Update the properties of a Microsoft Graph adminTodo object."
```

2023-06-17 02:36 UTC, Danielabom commented on api-reference/beta/api/admintodo-update.md
> +|settings|[microsoft.graph.todoSettings](../resources/todosettings.md)|**Company wide settings for Microsoft Todo** Required.|
```suggestion
|settings|[microsoft.graph.todoSettings](../resources/todosettings.md)|Company-wide settings for Microsoft Todo. Required.|
```

2023-06-17 02:47 UTC, Danielabom commented on api-reference/beta/toc.yml
> +      - name: Organization Settings
Why did you decide to place these titles and subtitles here? We have an org settings item TOC title. Please check.

2023-06-17 02:47 UTC, Danielabom requested changes
Many comments were not addressed, so I applied them. Please review my comments in the TOC. @zadinsmo @jakeost-msft

2023-06-20 17:19 UTC, zadinsmo commented on api-reference/beta/toc.yml
> +      - name: Organization Settings
I did not realize this, removed this title and moved the subtitles under the org settings item.

2023-06-27 18:42 UTC, Danielabom approved these changes
Thank you for working on this PR @zadinsmo. PR approved.

2023-07-01 01:02 UTC, Lauragra commented on api-reference/beta/api/adminappsandservices-get.md
> +Read the properties and relationships of a [microsoft.graph.adminAppsAndServices](../resources/adminappsandservices.md) object.
Global: We only fully qualify the resource type names when the APIs are defined in a subnamespace. These APIs aren't in a subnamespace, so please update the type names to remove "microsoft.graph.".

2023-07-01 01:04 UTC, Lauragra commented on api-reference/beta/api/admindynamics-get.md
> +The following is an example of the response
Global: Please make sure to add the missing period to this sentence.

2023-07-01 01:06 UTC, Lauragra commented on api-reference/beta/resources/adminappsandservices.md
> +|id|String|Unique id. Inherited from [microsoft.graph.entity](../resources/entity.md).|
Global: In text, we refer to an identifier as an ID (all caps). Please fix throughout.

2023-07-01 01:13 UTC, Lauragra commented on api-reference/beta/resources/adminappsandservices.md
> +Company-wide configuration for apps and services.
Can we male this description a bit more clear? It seems like this can easily be confused with appsAndServiceSettings, the difference being that one is a configuration and one is settings. In the case of the configuration, is that something the admin sets? I think a bit more detail will help make this clear to readers. Also, we generally start resource description with a verb form, i.e. represents/provides/contains, rather than just having a noun phrase.

2023-07-01 01:18 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: Microsoft Todo configuration
Let's streamline the TOC entries by removing "Microsoft" from the product names. Also, for CRUD operations, when the context of the parent resource is clear, we don't include the resource name in the TOC entry, just the verb, so the entries for the operations can just be Get and Update. This helps make the TOC more readable/scannable.

2023-07-01 01:19 UTC, Lauragra commented on changelog/Microsoft.OrgSettings.json
> +      "WorkloadArea": "Microsoft.OrgSettings",
You'll want to actually use the taxonomy values here, so "Identity and access" for the WorkloadArea, and "Directory management" for the SubArea.

2023-07-01 01:20 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: Microsoft Todo configuration
For consistency, these TOC nodes should also have (preview) appended, like the peer nodes in the TOC, since these APIs aren't yet available in v1.0.

2023-07-05 16:54 UTC, zadinsmo commented on api-reference/beta/resources/adminappsandservices.md
> +Company-wide configuration for apps and services.
I think part of the confusion comes from the API design decided in the Graph Api Review. Each of these objects is really just a collection of settings for the "application" (ex todo, forms). However, for apps and services these are just various M365 settings that weren't specifically related to a single app. For extensibility, the graph reviewers wanted this entity adminappsandservices to be a top level container that could potentially hold other things that aren't settings. Since these other things that aren't settings don't exist, I don't know a better word to describe a container that holds settings besides what it is currently described as, "configuration". If you can think of a better way to describe this please let me know, but I don't really think I can add much here.

2023-07-05 17:02 UTC, zadinsmo commented on api-reference/beta/api/adminappsandservices-get.md
> +Read the properties and relationships of a [microsoft.graph.adminAppsAndServices](../resources/adminappsandservices.md) object.
fixed

2023-07-05 17:03 UTC, zadinsmo commented on api-reference/beta/api/admindynamics-get.md
> +The following is an example of the response
added.

2023-07-05 17:03 UTC, zadinsmo commented on api-reference/beta/resources/adminappsandservices.md
> +|id|String|Unique id. Inherited from [microsoft.graph.entity](../resources/entity.md).|
fixed

2023-07-05 17:03 UTC, zadinsmo commented on api-reference/beta/toc.yml
> +          - name: Microsoft Todo configuration
Removed Microsoft, updated CRUD operation names

2023-07-05 17:03 UTC, zadinsmo commented on changelog/Microsoft.OrgSettings.json
> +      "WorkloadArea": "Microsoft.OrgSettings",
fixed

2023-07-05 17:03 UTC, zadinsmo commented on api-reference/beta/toc.yml
> +          - name: Microsoft Todo configuration
added.

2023-07-06 04:07 UTC, merged