Update organizationalbranding with contentCustomization property
microsoftgraph/microsoft-graph-docs pull request #21248
Opened 2023-05-10 20:55 UTC by AlexanderMars

Adding contentCustomization property for CIAM

<ComplexType Name="contentCustomization">
    <Property Name="attributeCollection" Type="Collection(microsoft.graph.keyValue)" />
    <Property Name="attributeCollectionRelativeUrl" Type="Edm.String" />
</ComplexType>

2023-05-25 09:40 UTC, FaithOmbongi requested changes
Thank you @AlexanderMars for your work on this PR. I've left suggestions inline plus the following two:

- Update organizationalbrandingproperties.md as well and add the new property.
- use lowercase for all file names

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
> +| contentCustomization | [contentCustomization](contentCustomization.md) | Represents the various content options to be customized throughout authentication for a tenant. <br/><br/>**NOTE:** Supporte
```suggestion
| contentCustomization | [contentCustomization](contentcustomization.md) | Represents the various content options to be customized throughout the authentication flow for a tenant. <br/><br/>**NOTE:** Supported by Azure Active Directory for customers tenants only. Inherited from [organizationalBrandingProperties](organizationalbrandingproperties.md). |
```

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandinglocalization.md
> +| contentCustomization | [contentCustomization](contentCustomization.md) | Represents the various content options to be customized throughout authentication for a tenant. <br/><br/>**NOTE:** Supporte
1. Same change as in organizationbranding.md
2. I think Nandita mentioned to me that user flow customization is currently supported only for the default locale. Did I hear correctly? If yes, let's add a note to this effect, something like "Only support for the default locale" or something. We can remove it once language-specific support is active.

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/resources/contentCustomization.md
> +description: "Contains details of the various content options for a tenant."
```suggestion
description: "Contains details of the various content options to be customized in the authentication flow for a tenant."
```

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/resources/contentCustomization.md
> +Contains details of the various content options for a tenant.
Match the description above.

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/resources/contentCustomization.md
> +| contentCustomization | Collection(microsoft.graph.keyValue) | Represents the various content options to be customized throughout authentication for a tenant.  |
You seem to be missing the actual properties going to public preview. Please confirm.

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/resources/contentCustomization.md
> +  "attributeCollection": "Collection(microsoft.graph.keyValue)"
Update this section as well. Please use the autogenerated doc stubs.

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/resources/contentCustomization.md
lowercase the file name, please. Always use the autogenerated doc stubs instead of manually creating new API or resource files to avoid hitting validation errors that will kick in soon.

2023-05-25 09:40 UTC, FaithOmbongi commented on api-reference/beta/api/organizationalbranding-update.md
> +| contentCustomization | [contentCustomization](../resources/contentCustomization.md) | Represents the various content options to be customized throughout authentication for a tenant. <br/><br/>**NOT
```suggestion
| contentCustomization | [contentCustomization](../resources/contentcustomization.md) | Represents the various content options to be customized throughout the authentication flow for a tenant. <br/><br/>**NOTE:** Supported by Azure Active Directory for customers tenants only. |
```

2023-05-25 14:39 UTC, AlexanderMars commented on api-reference/beta/resources/organizationalbrandinglocalization.md
> +| contentCustomization | [contentCustomization](contentCustomization.md) | Represents the various content options to be customized throughout authentication for a tenant. <br/><br/>**NOTE:** Supporte
It's not correct. contentCustomization is supported for all locales.

2023-05-25 14:40 UTC, AlexanderMars commented on api-reference/beta/resources/contentCustomization.md
> +  "attributeCollection": "Collection(microsoft.graph.keyValue)"
@FaithOmbongi Could you, please, remind how to get the autogenerated doc stubs? Thanks.

2023-06-06 17:27 UTC, FaithOmbongi commented on api-reference/beta/resources/contentcustomization.md
> +|attributeCollection|[keyValue](../resources/contentcustomization-attributecollection-keyvalue.md) collection| Represents the content options of External Identities to be customized throughout the au
Hi @AlexanderMars - The correct return type for attibuteCollection is actually the existing [keyValue complex type](https://learn.microsoft.com/en-us/graph/api/resources/keyvalue?view=graph-rest-beta). Please update the file to factor in branding-related changes (because it's shared by some 10+ APIs) and delete the new file you created.
```suggestion
|attributeCollection|[keyValue](../resources/keyvalue.md) collection| Represents the content options of External Identities to be customized throughout the authentication flow for a tenant.|
```

2023-06-07 07:42 UTC, FaithOmbongi approved these changes
LGTM overall.

@AlexanderMars - Pease let me know if this can benefit from a tutorial or how-to so I can plan for it while Nandita and I are doing the user flows conceptual articles.

2023-06-15 15:15 UTC, FaithOmbongi commented
Hi @millicentachieng - API Doctor validation is failing on this PR for no reason. Please help us resolve the issue. Thanks.

2023-06-16 07:37 UTC, FaithOmbongi commented
Close and reopen to trigger changelog and API Doctor revalidation.

2023-06-20 01:03 UTC, merged