Adding changes to Build your first MGDC application
microsoftgraph/microsoft-graph-docs pull request #21240
Opened 2023-05-09 23:35 UTC by rimisra2

Made changes to the first page https://learn.microsoft.com/en-us/graph/data-connect-quickstart?tabs=Microsoft365

2023-05-10 21:54 UTC, JarbasHorst commented
Hi @Lauragra, this PR is ready for final review.

2023-05-10 23:36 UTC, jthake-msft commented on includes/data-connect-quickstart-01.md
> +- One user in your Microsoft 365 tenant has the [Global Administrator](/azure/active-directory/roles/permissions-reference#global-administrator) role enabled. Going forward, this tutorial refers to t
I think this could be clearer. As they may use the global admin to do all this tutorial. The reason for having two users is that you can't self approve in the Microsoft 365 admin center.

2023-05-10 23:38 UTC, jthake-msft commented on includes/data-connect-quickstart-01.md
I think in the merging. we've lost the "You need a Microsoft 365 tenant and an Azure Subscription" is a prequisite. The following bullets go into the requirements of those.

2023-05-10 23:41 UTC, jthake-msft commented on includes/data-connect-quickstart-01.md
> +   - If your Azure subscription isn't in the same tenant as your Microsoft 365 tenant, you can associate your subscription with Azure AD in your Microsoft 365 tenant by following the steps listed in
As discussed. As this will effectively cost them money. we should have something at the beginning of the tutorial to frame what Azure resources are created. how much they'll cost and also that MGDC has licensing but this tutorial will not cross the 100,000 objects of a tenant that hasn't used MGDC before.

2023-05-10 23:44 UTC, jthake-msft commented on includes/data-connect-quickstart-03.md
>  1. On the sidebar navigation, select **Certificates & secrets** under **Manage**.
I think this step 1 needs deleting if we are deleting the instructions to create a secret. Don't we need the secret still so that we can create the integration later in tuturial. not just the service principal id?

2023-05-10 23:45 UTC, jthake-msft commented on includes/data-connect-quickstart-03.md
>  1. Verify that your account is listed as an application owner. If that isn't the case, add it to the list.
Which account are we referring to. If you are asking them as a Application Developer to create this, I think we should be clearer here.

2023-05-11 00:12 UTC, rimisra2 commented on includes/data-connect-quickstart-01.md
> +   - Access to atleast two user accounts, one that is a global administrator account who can access the
added

2023-05-11 16:11 UTC, jthake-msft commented on includes/data-connect-quickstart-03.md
this is no longer "the first step"

2023-05-11 16:20 UTC, jthake-msft commented on includes/data-connect-quickstart-05.md
> +    2. **Application ID:** Select from the Azure AD applications in the tenant or create a new one. Required.
for this tutorial you've made them create on called " Microsoft Graph Data Connect Data Transfer " it doesn't make sense to give them alternate instructions. I think this should be change to specifically that one.

2023-05-11 16:20 UTC, jthake-msft commented on includes/data-connect-quickstart-05.md
> +        - **Storage Account:** Select the Azure Storage Account where the data to provision with Data Connect will be located, or create a new Azure Storage Account. Required.
for this tutorial you've made them create one called "mgdcdemoap" it doesn't make sense to give them alternate instructions. I think this should be change to specifically that one.

2023-05-11 16:24 UTC, jthake-msft commented on includes/data-connect-quickstart-05.md
> +1. Open a browser, go to your [Microsoft 365 admin center](https://admin.microsoft.com/), and sign in with your "admin" user.
Lets add a big note format here that says, if you don't use the admin user you will get an error on approval You cannot self-approve your apps.

2023-05-11 16:26 UTC, jthake-msft commented on includes/data-connect-quickstart-09.md
> +In this section, you will build your first ASP.NET project application to process the Microsoft Graph Data Connect data that was exported.
this is still included in the tutorial steps on left hand side navigation I think it should be removed entirely.

2023-05-11 16:26 UTC, jthake-msft commented on concepts/data-connect-quickstart.yml
>    - title: Create your ASP.NET web application to process the exported data
I think we should remove this entirely.

2023-05-11 16:27 UTC, jthake-msft commented on concepts/data-connect-quickstart.yml
> +  - title: Microsoft Graph Data Connect Application Consent Overview
I don't understand why we've added this step to walk through the consent overview. We already have the admin approving it in the previous step. this is a tutorial where steps should lead to an end result. This feels like just documentation .

2023-05-11 16:28 UTC, jthake-msft requested changes
a few things we should discuss, didn't want to make them directly without discussion.

2023-05-11 23:59 UTC, rimisra2 reviewed
leaving comments for jeremy

2023-05-11 23:59 UTC, rimisra2 reviewed
leaving comments for jeremy

2023-05-12 00:02 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +    - **Resource group:** GraphDataConnect
Yes we should use the same resource group as previous steps . so we should say "Select the resource group you created previously `mgdc-app-resource`".

2023-05-12 00:03 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
>  1. Open a browser and go to the [Microsoft 365 admin center](https://admin.microsoft.com).
Itshould be changed to the Azure Portal as thats where you create the Azure Synapse Analytics resource.

2023-05-12 00:04 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +1. By default, Azure Synapse Analytics will use an integration runtime that auto-resolves the region. We recommend for the context of this tutorial in the developer tenant, to use default auto-resolv
I actually don't know the answer to this. I like the idea of simpler steps if we don't need a special Integration run time. I could test to see if it does work without creating a new one...? can we just ask the engineers to validate it auto-resolves?

2023-05-12 00:07 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +    1. Select the **Source** tab, and then select **New**.
I sent you a new screen shot if you want to use it. Snag_a11b4d2.png

2023-05-12 00:13 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +    1. In the dialog box, from the **Connect via integration runtime** dropdown, select the integration runtime you created, enter the Azure Active Directory (Azure AD) application's **Application ID
In the part where they create the AzureAD application, they are instructed to create a client secret in the "Certificates and secrets" section (current branch these steps were deleted :-( ).

The correct term to use is `client secret`.

2023-05-12 00:14 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +    1. In the dialog that appears, enter the previously created Azure Active Directory (Azure AD) application's **Application ID** and **Secret Value** in the **Service principal ID** and **Service p
Yes it should be **client secret**

2023-05-12 00:14 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +    1. In the dialog that appears, select the integration runtime you previously created in the **Connect via integration runtime** dropdown, enter the previously created Azure AD application's **App
**client secret value**

2023-05-12 00:16 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +            - **Service principal key**: enter the hashed key of the Azure AD application you previously created
should be **client secret value**

2023-05-12 00:17 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +1. By default, the Azure Data Factory will use an integration runtime that is auto-resolving the region. We recommend for the context of this tutorial in the developer tenant, to use the default auto
if auto resolve actually works. then yes.

2023-05-12 00:22 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +    1. Select the **Sink** tab. Choose **New**, select **Azure Blob Storage**, and then choose **Continue**.
I've taken them , in your msg box

2023-05-12 00:25 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +1. With the pipeline created, at the top of the designer, choose **Validate all**.
sent.

2023-05-12 00:27 UTC, jthake-msft commented on includes/data-connect-quickstart-06.md
> +1. After validating (and fixing any issues that were found), at the top of the designer, choose **Publish all**.
sent

2023-05-12 00:49 UTC, rimisra2 commented on includes/data-connect-quickstart-05.md
> +        - **Storage Account:** Select the Azure Storage Account where the data to provision with Data Connect will be located, or create a new Azure Storage Account. Required.
I think this should be resolved based on our discussion

2023-05-12 00:56 UTC, rimisra2 commented on includes/data-connect-quickstart-05.md
> +1. Open a browser, go to your [Microsoft 365 admin center](https://admin.microsoft.com/), and sign in with your "admin" user.
added

2023-05-12 01:03 UTC, rimisra2 commented on concepts/data-connect-quickstart.yml
>    - title: Create your ASP.NET web application to process the exported data
agreed and removed.

2023-05-15 20:48 UTC, Jarbas-MSFT commented on includes/data-connect-quickstart-07.md
>  1. Open a browser and go to the [Microsoft 365 admin center](https://admin.microsoft.com).
Please, verify whether this step is really needed.

2023-05-15 20:57 UTC, Jarbas-MSFT commented on includes/data-connect-quickstart-01.md
>  Data Connect is ideal for big data applications and machine learning as it allows you to develop applications for analytics, intelligence, and business process optimization by extending Microsoft 365
Feedback about images:

Please, add a red box to those images to indicate the areas that a user should click:
- concepts/images/data-connect-register-app-2.png
- concepts/images/data-connect-register-app-4.png
- concepts/images/data-connect-register-app-6.png

There is an extra highlighted section in the following image. If that isn't needed, then please remove it.
- concepts/images/data-connect-app-register-8.png =>

2023-05-15 22:57 UTC, rimisra2 commented on includes/data-connect-quickstart-07.md
>  1. Open a browser and go to the [Microsoft 365 admin center](https://admin.microsoft.com).
The step is needed but I simplified it in hopes it of making it more readable

2023-05-15 23:08 UTC, rimisra2 commented on includes/data-connect-quickstart-01.md
>  Data Connect is ideal for big data applications and machine learning as it allows you to develop applications for analytics, intelligence, and business process optimization by extending Microsoft 365
@Jarbas-MSFT  the user has nothing to click on those images, they are just sample images of how the information will look like.  We feel that concepts/images/data-connect-app-register-8.png is necessary since customers often have lots of apps and need to search for microsoft graph data connect so we will keep that as is.

2023-05-15 23:39 UTC, rimisra2 commented on includes/data-connect-quickstart-07.md
>  1. Open a browser and go to the [Microsoft 365 admin center](https://admin.microsoft.com).
actually this file is no longer needed since it's merged with file #6

2023-05-16 03:53 UTC, Lauragra commented on includes/data-connect-quickstart-01.md
> +![A screenshot that explains the onboarding flow.](../concepts/images/data-connect-overview-flowchart.png)
Please fix the branding errors in this image:
AAD -> Azure AD
MGDC -> Data Connect

2023-05-18 04:06 UTC, Lauragra approved these changes

2023-05-18 04:12 UTC, merged