[CloudPC] Add correlationId to CloudPcOnPremisesConnectionHealthCheck
microsoftgraph/microsoft-graph-docs pull request #21261
Opened 2023-05-11 09:33 UTC by ChyouChyou

2023-05-12 05:27 UTC, AshleyYangSZ commented
@ChyouChyou  Please add change-log, thanks!

2023-05-12 05:36 UTC, AshleyYangSZ requested changes
Please add change-log and the linked roadmap workitem

2023-05-23 01:50 UTC, Lauragra commented
@ChyouChyou , please be sure to request a content review of your PR before you set ready to merge. I just set the ready for content review label to add your PR to the review queue.

2023-05-23 02:20 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "CreatedDateTime": "2023-05-30T05:55:14.173894Z",
I believe the time should be when you created this PR. 5/30 is in the future

2023-05-23 02:23 UTC, RuiHou105 commented
@ChyouChyou  Please created a roadmap workitem and add its number in comment. Here is an example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/13986/

2023-05-23 02:24 UTC, ChyouChyou commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "CreatedDateTime": "2023-05-30T05:55:14.173894Z",
Thank you! I mistakenly thought that this time was the time of merge.

2023-05-23 02:28 UTC, RuiHou105 commented
> @ChyouChyou Please created a roadmap workitem and add its number in comment. Here is an example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/13986/

I see your roadmap. That's good.

2023-05-23 06:48 UTC, RuiHou105 approved these changes

2023-05-29 02:53 UTC, AshleyYangSZ approved these changes

2023-06-06 16:23 UTC, dodaromike approved these changes

2023-06-13 01:54 UTC, merged