[CloudPC] Add property resetEnabled into CloudPCUserSetting
microsoftgraph/microsoft-graph-docs pull request #21270
Opened 2023-05-12 04:00 UTC by Guoan-Tang

2023-05-12 04:47 UTC, AshleyYangSZ commented
@Guoan-Tang please add change-log in this pr.

2023-06-16 06:11 UTC, AshleyYangSZ requested changes

2023-06-16 06:11 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcusersetting-update.md
> +|resetEnabled|Boolean|Indicates whether an end-user is allowed to reset their Cloud PC. When `true`, the user is allowed to reset their Cloud PC. When `false`, end-user initiated reset is not allowed
Why add duplicate line for resetEnabled? 
Could you help me understand what's reset mean? Is it reprovision?

2023-06-16 06:11 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcusersetting-update.md
> +  "resetEnabled": "Boolean",
Please remove this

2023-06-16 06:11 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcusersetting.md
> +|resetEnabled|Boolean|Indicates whether an end-user is allowed to reset their Cloud PC. When `true`, the user is allowed to reset their Cloud PC. When `false`, end-user initiated reset is not allowed
Duplicate?

2023-06-16 06:11 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcusersetting.md
> +  "resetEnabled": "Boolean"
remove this

2023-06-16 06:38 UTC, xiaofuwahh commented on api-reference/beta/api/cloudpcusersetting-update.md
> +|resetEnabled|Boolean|Indicates whether an end-user is allowed to reset their Cloud PC. When `true`, the user is allowed to reset their Cloud PC. When `false`, end-user initiated reset is not allowed
will deleted soon, yes reset is reprovision, this property name is align to IWP

2023-07-04 07:01 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "WorkloadArea": "Devices and apps",
```suggestion
            "WorkloadArea": "Devices and app management",
```

2023-07-04 07:02 UTC, RuiHou105 commented
Please create roadmap workitem.

2023-07-04 07:03 UTC, RuiHou105 requested changes
Please resolve comments left in this PR.

2023-07-04 07:15 UTC, xiaofuwahh commented on api-reference/beta/resources/cloudpcusersetting.md
> +|resetEnabled|Boolean|Indicates whether an end-user is allowed to reset their Cloud PC. When `true`, the user is allowed to reset their Cloud PC. When `false`, end-user initiated reset is not allowed
deleted, thanks

2023-07-06 04:52 UTC, RuiHou105 approved these changes

2023-08-01 02:51 UTC, Lauragra approved these changes

2023-08-01 03:06 UTC, merged