Add sample keys
microsoftgraph/microsoft-graph-docs pull request #21281
Opened 2023-05-12 14:42 UTC by millicentachieng

2023-05-18 13:34 UTC, FaithOmbongi requested changes
Hi @millicentachieng - I've left comments on two docs, please confirm.

2023-05-18 13:34 UTC, FaithOmbongi commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +  "sampleKeys": ["DefaultReportSubmissionPolicy"]
It looks like the ID should be a GUID-like String so using `DefaultReportSubmissionPolicy` in the example doesn't accurately represent the API.

2023-05-29 07:51 UTC, millicentachieng commented on api-reference/beta/api/calltranscript-get.md
> +  "sampleKeys": ["ba321e0d-79ee-478d-8e28-85a19507f456", "MSo1N2Y5ZGFjYy03MWJmLTQ3NDMtYjQxMy01M2EdFGkdRWHJlQ/transcripts/MSMjMCMjNzU3ODc2ZDYtOTcwMi00MDhkLWFkNDItOTE2ZDNmZjkwZGY4"]
Good catch.

2023-05-29 08:43 UTC, millicentachieng commented on api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
> +  "sampleKeys": ["DefaultReportSubmissionPolicy"]
@FaithOmbongi If you look at the example in this [file](https://learn.microsoft.com/en-us/graph/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies?view=graph-rest-beta&tabs=http), `DefaultReportSubmissionPolicy` is an id in the response.

2023-05-29 09:29 UTC, FaithOmbongi approved these changes
LGTM!

2023-05-31 01:12 UTC, merged