user default method documentation
microsoftgraph/microsoft-graph-docs pull request #21310
Opened 2023-05-15 23:18 UTC by jpettere

This docs PR is tracked via this work item https://dev.azure.com/msft-skilling/Content/_workitems/edit/90516.

2023-05-24 17:14 UTC, FaithOmbongi requested changes
Hi @jpettere -

I've left suggestions in line.
In addition, I've re-reviewed the API.md with fresh eyes and I realize that I gave Poulomi bad advice when she published the original signInPreferences objects. To correct that:

- Surface the authentication.md resource file in the TOC
- Add the authentication-get.md file to your PR (I'll share the doc stub internally). Document signInPreferences-related examples there.

2023-05-24 17:14 UTC, FaithOmbongi commented on changelog/Microsoft.StrongAuthenticationAPI.json
> +          "ChangedApiName": "userDefaultAuthenticationMethodType",
Also add an entry for adding the new property userPreferredMethodForSecondaryAuthentication to the resource

2023-05-24 17:14 UTC, FaithOmbongi commented on changelog/Microsoft.StrongAuthenticationAPI.json
> +      "SubArea": ""
```suggestion
      "WorkloadArea": "Identity and access",
      "SubArea": "Identity and sign-in"
```

2023-05-25 02:01 UTC, jpettere commented on changelog/Microsoft.StrongAuthenticationAPI.json
> +          "ChangedApiName": "userDefaultAuthenticationMethodType",
The doc stubs I got unfortunately only had an entry for the enum. Can I manually add an entry with a random GUID as ID?

2023-05-25 07:43 UTC, FaithOmbongi commented on changelog/Microsoft.StrongAuthenticationAPI.json
> +          "ChangedApiName": "userDefaultAuthenticationMethodType",
Yes, manually craft and add an entry but with the same GUID as the entry for userDefaultAuthenticationMethodType.

2023-05-25 07:50 UTC, FaithOmbongi requested changes
Hi @jpettere - I've left suggestions for some fixes to the GET doc. You're on the right track.

2023-05-25 07:50 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-get.md
> +title: "Get signInPreferences"
I support this tweak. While ideally the title would be "Get authentication", this API can only be used to directly read signInPreferences and the endpoint can't end with /authentication. Also apply this change to the H1 title below.

2023-05-25 07:50 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-get.md
> +
Remember to add the include statement for the RBAC info.

2023-05-25 07:50 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-get.md
> +}
Hmm, please confirm this is the structure of the response payload. Test in Graph Explorer.

2023-05-25 07:50 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-get.md
> +  "@odata.type": "microsoft.strongAuthentication.authentication"
```suggestion
  "@odata.type": "microsoft.graph.signInPreferences"
```

2023-05-30 15:53 UTC, jpettere commented on api-reference/beta/api/authentication-get.md
> +
@FaithOmbongi is this the right link since the roles that can manage user auth methods can also get / update signInPreferences? 

[rbac-authentication-methods-apis-read-others](../includes/rbac-for-apis/rbac-authentication-methods-apis-read-others.md)

2023-05-31 03:07 UTC, jpettere commented on api-reference/beta/api/authentication-get.md
> +}
Updated.

2023-05-31 16:21 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-get.md
> +
Yep, this is the correct RBAC file @jpettere

2023-05-31 16:41 UTC, FaithOmbongi approved these changes
Hi @jpettere - I've left suggestions for minor fixes so approved with comments.

Also, I believe this requires you to also update the API Overview to remove [default method](https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta#:~:text=Examples-,Default%20method,-Represents%20the%20method) from the things not supported yet? Please confirm.

2023-05-31 16:41 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-update.md
> +# Update authentication
```suggestion
# Update signInPreferences
```

2023-05-31 16:41 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-update.md
> +HTTP/1.1 204 NO CONTENT
nit
```suggestion
HTTP/1.1 204 No Content
```

2023-05-31 16:41 UTC, FaithOmbongi commented on api-reference/beta/api/authentication-update.md
> +|userPreferredMethodForSecondaryAuthentication|userDefaultAuthenticationMethodType|The default second factor method used by the user when signing in. If a user is enabled for system preferred authent
```suggestion
|userPreferredMethodForSecondaryAuthentication|userDefaultAuthenticationMethodType|The default second-factor method used by the user when signing in. If a user is enabled for system-preferred authentication, then this value is ignored except for a few scenarios where a user is authenticating via NPS extension or ADFS adapter. Possible values are `push`, `oath`, `voiceMobile`, `voiceAlternateMobile`, `voiceOffice`, `sms`, and `unknownFutureValue`|
```

2023-06-01 02:56 UTC, Lauragra commented on api-reference/beta/api/authentication-get.md
> +title: "Get signInPreferences"
Please add these two new methods to the TOC by updating the toc.yml file in the beta folder. Please also verify the file names; it seems like they should be signinpreferences-get and signinpreferences-update.

2023-06-09 08:23 UTC, FaithOmbongi approved these changes
Changes LGTM! Thanks @jpettere!

2023-06-10 00:27 UTC, Lauragra approved these changes

2023-06-10 00:40 UTC, merged