Add Approval API docs for PAG
microsoftgraph/microsoft-graph-docs pull request #21325
Opened 2023-05-16 21:35 UTC by mandardalvi

2023-05-29 16:31 UTC, FaithOmbongi requested changes
Hi @mandardalvi , @ilyalushnikov - I've left feedback inline...please address them.

Also, document assignmentApprovals relationship in privilegedAccessGroup.md

Q: Aren't you documenting these APIs for PIM for Azure AD roles as well? 

I'm curious, how come v1 PIM for Azure AD roles doesn't have these approval capabilities? i.e. there's no approval relationship in the schema. Was this an oversight in the schema publication?

2023-05-29 16:31 UTC, FaithOmbongi commented on api-reference/beta/api/approval-list-steps.md
> +
```suggestion
List the [approvalStep](../resources/approvalstep.md) objects associated with an [approval](../resources/approval.md). This API request is made by an approver in the following scenarios:

- In [entitlement management](../resources/entitlementmanagement-overview.md), providing the identifier of the [access package assignment request](../resources/accesspackageassignmentrequest.md).
- In [PIM for groups](../resources/privilegedidentitymanagement-for-groups-api-overview.md), providing the identifier of the [assignment schedule request](../resources/privilegedaccessgroupassignmentschedulerequest.md).

```

2023-05-29 16:31 UTC, FaithOmbongi commented on api-reference/beta/api/approval-list-steps.md
> +### Permissions required for calling this API for entitlement management
```suggestion
### For entitlement management
```

2023-05-29 16:31 UTC, FaithOmbongi commented on api-reference/beta/api/approval-list-steps.md
> +### Permissions required for calling this API for PIM for groups
```suggestion
### For PIM for groups
```

2023-05-29 16:31 UTC, FaithOmbongi commented on api-reference/beta/api/approval-list-steps.md
>  | Name      |Description|
```suggestion
## HTTP request

To list the approval steps in entitlement management:

<!-- { "blockType": "ignored" } -->
```http
GET /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{id}/steps
```

To list the approval steps in PIM for groups:

<!-- { "blockType": "ignored" } -->
```http
GET /identityGovernance/privilegedAccess/group/assignmentApprovals/{id}/steps
```

## Request headers

| Name      |Description|
```

2023-05-29 16:31 UTC, FaithOmbongi commented on api-reference/beta/api/approval-list-steps.md
>  [!INCLUDE [sample-code](../includes/snippets/csharp/get-approvalstep-1-csharp-snippets.md)]
1 request to 1 response. You can keep the existing entitlement management example only or add an example 2 with request: response for PIM for groups.
```suggestion

```http
GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/abd306ef-f7b2-4a10-9fd1-493454322489/steps
```

# [C#](#tab/csharp)
[!INCLUDE [sample-code](../includes/snippets/csharp/get-approvalstep-1-csharp-snippets.md)]
```

2023-05-29 16:31 UTC, FaithOmbongi commented on api-reference/beta/api/approvalstep-get.md
All the comments in the other doc apply here

2023-05-29 16:31 UTC, FaithOmbongi commented on api-reference/beta/api/approvalstep-update.md
All the comments in the other doc apply here.

2023-05-30 07:16 UTC, ilyalushnikov commented on api-reference/beta/resources/privilegedidentitymanagement-for-groups-api-overview.md
> +| An approver approves or denies approval request by approving or denying approval step | [Update approvalStep](../api/approvalstep-get.md) |
"the steps to approve the request" isn't accurate IMHO. "steps to approve the request" gives an impression that these are steps that approver has to take. Which isn't true in this situation.
Can we keep "information about approval steps" in line 37 and implement rest of your suggestions?

2023-05-30 07:22 UTC, ilyalushnikov commented on api-reference/beta/resources/privilegedidentitymanagement-for-groups-api-overview.md
> +| approval | GET | PrivilegedAssignmentSchedule.Read.AzureADGroup <br/> PrivilegedAssignmentSchedule.ReadWrite.AzureADGroup |
In my opinion, this overview is incredibly useful for a reader.
I may have different background though: I didn't work on API documentation ever before, but I did publish a book and delivered hundreds of technical trainings. Documentation may be more dry and avoid repeating information, while in the book or working with live audience you go from broader strokes and get into details later. That's the reason I would like to keep this section if it doesn't break any rules.

2023-05-30 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedidentitymanagement-for-groups-api-overview.md
> +| An approver approves or denies approval request by approving or denying approval step | [Update approvalStep](../api/approvalstep-get.md) |
Ah, OK. No problem. I defer to you for technical accuracy.

2023-05-30 07:44 UTC, FaithOmbongi commented on api-reference/beta/resources/privilegedidentitymanagement-for-groups-api-overview.md
> +| approval | GET | PrivilegedAssignmentSchedule.Read.AzureADGroup <br/> PrivilegedAssignmentSchedule.ReadWrite.AzureADGroup |
Doesn't break any rules. If readers find this summary useful, we can continue to keep it.

2023-05-31 09:34 UTC, FaithOmbongi commented on api-reference/beta/api/approval-get.md
> +```http
```suggestion
To list the approval steps in entitlement management.
```http
GET /identityGovernance/entitlementManagement/accessPackageAssignmentApprovals/{id}
```

To list the approval steps in PIM for groups:
```http
```

2023-05-31 09:47 UTC, FaithOmbongi approved these changes
Pushed a few commits to fix the structure of the HTTP request syntax section then approved.

cc @mandardalvi, @ilyalushnikov

2023-06-01 03:09 UTC, merged