Add awaitingAction enum value to incidentStatus enum
microsoftgraph/microsoft-graph-docs pull request #21334
Opened 2023-05-17 07:33 UTC by BenAlfasi

2023-05-18 18:41 UTC, Danielabom commented
Contacted author to get info.

2023-05-19 15:00 UTC, Danielabom commented on api-reference/v1.0/resources/security-incident.md
> +|status|[microsoft.graph.security.incidentStatus](#incidentstatus-values)|The status of the incident. Possible values are: `active`, `resolved`, `inProgress`, `redirected`, `unknownFutureValue`, `awa
Since "awaiting action" is a value greater than "unknown future value", please follow step 3 from this [wiki](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

2023-05-19 15:00 UTC, Danielabom commented on api-reference/beta/resources/security-incident.md
> +|status|[microsoft.graph.security.incidentStatus](#incidentstatus-values)|The status of the incident. Possible values are: `active`, `resolved`, `inProgress`, `redirected`, `unknownFutureValue`, `awa
Since "awaiting action" is a value greater than "unknown future value", please follow step 3 from this [wiki](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations)

2023-05-19 15:01 UTC, Danielabom requested changes
Hi @BenAlfasi, thank you for working on this PR. Please see my comments.

2023-06-22 07:24 UTC, BenAlfasi commented on api-reference/v1.0/resources/security-incident.md
> +| awaitingAction      | This incident has required actions from Defender Experts awaiting your action. This status can only be set by Defender Experts.|
You're right, Microsoft 365 Defender experts is the correct term :)

2023-06-22 07:30 UTC, BenAlfasi commented on api-reference/beta/resources/security-incident.md
> +| awaitingAction      | This incident has required actions from Defender Experts awaiting your action. This status can only be set by Defender Experts.|
done

2023-06-22 07:31 UTC, BenAlfasi commented on api-reference/v1.0/resources/security-incident.md
> +|status|[microsoft.graph.security.incidentStatus](#incidentstatus-values)|The status of the incident. Possible values are: `active`, `resolved`, `inProgress`, `redirected`, `unknownFutureValue`, `awa
done

2023-06-22 07:36 UTC, BenAlfasi commented on api-reference/beta/resources/security-incident.md
> +|status|[microsoft.graph.security.incidentStatus](#incidentstatus-values)|The status of the incident. Possible values are: `active`, `resolved`, `inProgress`, `redirected`, `unknownFutureValue`, `awa
done

2023-06-27 02:37 UTC, Danielabom commented on changelog/Microsoft.M365.Defender.json
> +					"Description": "Added the `inProgress` member to the [incidentStatus](https://learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta#incidentstatus-values) enumerat
```suggestion
					"Description": "Added the `inProgress` member to the **incidentStatus** enumeration.",
```

2023-06-27 03:10 UTC, Danielabom commented on changelog/Microsoft.M365.Defender.json
> +          "Description": "Added the `awaitingAction` member to the [incidentStatus](https://learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-1.0#incidentstatus-values)
```suggestion
          "Description": "Added the `awaitingAction` member to the **incidentStatus** enumeration.",
```

2023-06-27 03:11 UTC, Danielabom commented on changelog/Microsoft.M365.Defender.json
> +          "Description": "Added the `awaitingAction` member to the [incidentStatus](https://learn.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta#incidentstatus-values)
```suggestion
          "Description": "Added the `awaitingAction` member to the **incidentStatus** enumeration.",
```

2023-06-27 03:13 UTC, Danielabom approved these changes
Thank you for working on this PR @BenAlfasi. PR approved.

2023-06-29 01:35 UTC, Danielabom commented
Hi @BenAlfasi, please add the "ready to merge" label as soon as you are ready to publish. Thanks!

2023-07-11 04:44 UTC, merged