Role settings management in PIM for Groups
microsoftgraph/microsoft-graph-docs pull request #21357
Opened 2023-05-19 04:33 UTC by weijie-lin

2023-05-25 07:13 UTC, ilyalushnikov approved these changes

2023-05-29 12:11 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
> +### Example 2: Retrieve rules of a policy for PIM for groups
```suggestion
### Example 2: Retrieve rules of a policy in PIM for groups
```

2023-05-29 12:13 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
> +### Example 1: Retrieve a rule defined for a policy for PIM for Azure AD roles
```suggestion
### Example 1: Retrieve a rule defined for a policy in PIM for Azure AD roles
```

2023-05-29 12:13 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
> +### Example 2: Retrieve a rule defined for a policy for PIM for groups
```suggestion
### Example 2: Retrieve a rule defined for a policy in PIM for groups
```

2023-05-29 12:14 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
> +### Example 1: Update a rule defined for a policy for PIM for Azure AD roles
```suggestion
### Example 1: Update a rule defined for a policy in PIM for Azure AD roles
```

2023-05-29 12:14 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
> +### Example 2: Update a rule defined for a policy for PIM for groups
```suggestion
### Example 2: Update a rule defined for a policy in PIM for groups
```

2023-05-29 17:09 UTC, FaithOmbongi commented on concepts/identity-governance-pim-rules-overview.md
> +In Microsoft Graph, the Azure AD role settings are called *rules*. These rules are grouped in and assigned to Azure AD roles through containers called policies.
I've created a PR to make changes to this article and the related how-to. Please review it, apply any changes, and feel free to merge it into your PR. https://github.com/microsoftgraph/microsoft-graph-docs/pull/21463/files

cc @ilyalushnikov , @weijie-lin

2023-05-30 23:42 UTC, ilyalushnikov commented on api-reference/beta/api/unifiedrolemanagementpolicy-update.md
> +Update the details of a role management policy [unifiedRoleManagementPolicy](../resources/unifiedrolemanagementpolicy.md) object.
Getting into technical accuracy, this may be considered not 100% correct:
1. Suggested text may give the impression that same policy can be applied to Azure AD roles or groups, which isn't true.
2. Today policy is already applied somewhere if it exists (in other words, policy is always applied). Saying that it _can_ be applied may be misleading to the reader.
3. _Multiple_ rules can also be misleading because each and every rule can be changed through this API call, but it doesn't have to be multiple rules, can be just one.
4. "Policy applied to groups" isn't 100% accurate because policy applies either to membership "role" or ownership "role", but not to the group as a whole.
5. Policy doesn't apply _through_ PIM, it applies _in_ PIM instead.

Because of all that, I suggest we may keep sentence as is to not get into these details.

2023-05-30 23:53 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +Get role management policies and their details. This API only applies to Azure AD roles, or Pim for Group membership and ownership. To retrieve policies that apply to Azure RBAC, use the [Azure REST
I believe original text is more technically accurate:
1. Policies don't apply _through_ PIM, but apply _in_ PIM
2. Policies don't apply to groups as a whole, but to ownership or membership separately. One policy is always for membership or for ownership for specific group, but never both.

2023-05-31 00:08 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +Get the details of all role management policy assignments including the policies and rules associated with the Azure AD roles, or Pim for Group membership and ownership.
@FaithOmbongi there are repeated phrased in a suggested change, not sure I get the idea, sorry.

Also, policy doesn't apply to group directly. Every policy applies either to membership or ownership of the group, never both at the same time.

2023-05-31 00:11 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +The following example retrieves details of all role management policy assignments that are scoped to the group and apply to PIM for groups membership and ownership.
I don't think "scoped to a group through PIM for groups" is technically accurate. Every policy assignment applies to either membership or ownership, but never to the group as a whole.

2023-05-31 00:13 UTC, ilyalushnikov commented on api-reference/beta/api/unifiedrolemanagementpolicy-get.md
> +To retrieve the details of a policy for either Azure AD roles or PIM for groups membership and ownership:
I believe original text is more accurate:
1. Policy doesn't apply to groups, policy applies to either membership or ownership (but not both at the same time)
2. Suggested change includes "groups in PIM for Azure AD roles" - may be a typo.

2023-05-31 00:24 UTC, ilyalushnikov commented on api-reference/beta/api/unifiedrolemanagementpolicy-update.md
> +|Application|Not supported.|
@weijie-lin  could you please check this one?

2023-05-31 00:25 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +This method requires the `$filter` (`eq`) query parameter to scope the request to a **scopeId** and a **scopeType**. To retrieve Azure AD roles policies, **scopeId** must be `/` and, **scopeType** ca
@weijie-lin  could you please validate this sentence: "This API also supports `$select` nested in `$expand` to return only specific properties of those rules."
If this is accurate, I agree with @FaithOmbongi 's suggestion.

2023-05-31 00:35 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +This method requires the `$filter` (`eq`) query parameter to scope the request to a **scopeId** and a **scopeType**. To retrieve Azure AD roles policies, **scopeId** must be `/` and, **scopeType** ca
@weijie-lin could you please validate this sentence: "This API also supports a nested `$expand` to retrieve the rules in policies and nested `$select` to return only specific properties of those rules."
If this is accurate, I agree with @FaithOmbongi 's suggestion..

2023-05-31 00:58 UTC, ilyalushnikov commented on api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
> +To retrieve the details of a policy assignment for either Azure AD roles or PIM for groups membership and ownership:
I believe original text is more accurate than suggestion. Policy assignment isn't made through PIM, but in PIM. Also, assignment is for either membership or ownership, but not group as a whole.

2023-05-31 00:59 UTC, ilyalushnikov commented on api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
> +To Retrieve a rule defined for a policy for either Azure AD roles or PIM for groups membership and ownership:
I don't think "through" PIM would be 100% accurate as policy exists in the PIM itself.

2023-05-31 05:55 UTC, weijie-lin commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +This method requires the `$filter` (`eq`) query parameter to scope the request to a **scopeId** and a **scopeType**. To retrieve Azure AD roles policies, **scopeId** must be `/` and, **scopeType** ca
@ilyalushnikov , yes, this API supports `$select` nested in `$expand` to return only specific properties of those rules, those properties are common properties like id and target. For example, user can make call along with $expand=rules($select=id) so that all the expanded rules will have id in it but not other properties.

2023-05-31 06:05 UTC, weijie-lin commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +This method requires the `$filter` (`eq`) query parameter to scope the request to a **scopeId** and a **scopeType**. To retrieve Azure AD roles policies, **scopeId** must be `/` and, **scopeType** ca
@ilyalushnikov , That's correct. Faith has an example below for it: https://graph.microsoft.com/beta/policies/roleManagementPolicyAssignments?$filter=scopeId eq '/' and scopeType eq 'Directory'&$expand=policy($expand=rules($select=id))

2023-05-31 06:17 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementpolicy-update.md
> +|Application|Not supported.|
@ilyalushnikov , @FaithOmbongi. This is not supported for update policy rule for Azure AD roles based. https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicyrule-update?view=graph-rest-1.0&tabs=http

I discussed with Mita before making this change. It's made consistent on update behavior between Policy and Policy Rule for Azure AD roles.

2023-05-31 06:22 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
> +Get the details of a role management policy assignment including the policy and rules associated with the Azure AD role, Pim for Group membership or ownership.
@ilyalushnikov @FaithOmbongi , I agreed with Ilya on this. The endpoint is about policy assignment so the details should be on the policy assignment, the detail of the policy (policy property) is through the $expand operation and it's optional. The only information regarding the policy that always returned in the response is the policy id so it's very minimal.

2023-05-31 06:31 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
> +To Retrieve a rule defined for a policy for either Azure AD roles or PIM for groups membership and ownership:
@ilyalushnikov , made the fix.

2023-05-31 06:47 UTC, ilyalushnikov commented on api-reference/beta/api/unifiedrolemanagementpolicy-update.md
> +|Application|Not supported.|
@weijie-lin I want to ensure I correctly understand you. Could you please elaborate on "It's made consistent on update behavior between Policy and Policy Rule for Azure AD roles."? Are you saying that lack of app permission is intentional?

2023-05-31 06:48 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +This method requires the `$filter` (`eq`) query parameter to scope the request to a **scopeId** and a **scopeType**. To retrieve Azure AD roles policies, **scopeId** must be `/` and, **scopeType** ca
thanks, committing suggestion

2023-05-31 06:52 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +This method requires the `$filter` (`eq`) query parameter to scope the request to a **scopeId** and a **scopeType**. To retrieve Azure AD roles policies, **scopeId** must be `/` and, **scopeType** ca
thanks, committing suggestion

2023-05-31 06:53 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +```
@weijie-lin could you please check this suggestion?

2023-05-31 06:53 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +```
@weijie-lin could you please check this suggestion?

2023-05-31 06:55 UTC, ilyalushnikov commented on api-reference/beta/resources/unifiedrolemanagementpolicyassignment.md
> +|roleDefinitionId|String|For Azure AD roles policy, it's the identifier of the [role definition](unifiedroledefinition.md) object where the policy applies. For PIM for groups membership and ownership
Checking this internally, more details in our Teams thread.

2023-05-31 08:56 UTC, FaithOmbongi commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +Get role management policies and their details. This API only applies to Azure AD roles, or Pim for Group membership and ownership. To retrieve policies that apply to Azure RBAC, use the [Azure REST
How about "_Get the details of the policies in PIM that can be applied to Azure AD roles or group membership or ownership._"

2023-05-31 09:00 UTC, weijie-lin commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +```
@FaithOmbongi @ilyalushnikov, Maybe we can enhance it later? We keep adding more and more example here and what's the best name for the snippet file. I don't have a strong opinion against more examples; however, at the same time I feel it's just basic OData thing and we explained it in the docs.

2023-05-31 09:05 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicy-get.md
> +To retrieve the details of a policy for either Azure AD roles or PIM for groups membership and ownership:
Edited. Please check for technical accuracy.

2023-05-31 09:06 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicy-get.md
> +### Example 2: Retrieve the details of a policy for PIM for groups
```suggestion
### Example 2: Retrieve the details of a policy in PIM for groups
```

2023-05-31 09:12 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicy-update.md
> +>**Note:** The response object shown here might be shortened for readability.
nit
```suggestion
```

2023-05-31 09:12 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicy-update.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2023-05-31 09:15 UTC, FaithOmbongi commented on api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
> +Get the details of a role management policy assignment including the policy and rules associated with the Azure AD role, Pim for Group membership or ownership.
Updated. Please re-review.

2023-05-31 09:24 UTC, FaithOmbongi commented on api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
> +```
@weijie-lin - The example you added suffices...I agree that it's not always best to add more and more examples, that's why I gave the option of enhancing option 2 so it uses query parameters. That would have been the simpler route and would have addressed customer questions regarding how query parameters are used.

2023-05-31 09:28 UTC, FaithOmbongi requested changes
Hi @weijie-lin, @ilyalushnikov - 

You make excellent points regarding the technical accuracy of the descriptions and that's why I defer to you for that. I've edited the suggested texts, please check if they help address some of my feedback.

2023-05-31 16:17 UTC, ilyalushnikov commented on concepts/identity-governance-pim-rules-overview.md
> +In Microsoft Graph, the Azure AD role settings are called *rules*. These rules are grouped in and assigned to Azure AD roles through containers called policies.
@FaithOmbongi  thanks a lot! Looks great to me. @weijie-lin  could you please take a look as well and if it works for you - merge into this PR.

2023-05-31 16:21 UTC, ilyalushnikov commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +Get role management policies and their details. This API only applies to Azure AD roles, or Pim for Group membership and ownership. To retrieve policies that apply to Azure RBAC, use the [Azure REST
@weijie-lin could you please make a change per @FaithOmbongi 's suggestion?

2023-05-31 18:23 UTC, FaithOmbongi approved these changes
Hi @weijie-lin, @ilyalushnikov - I think we're clear on the pending action items on the PR. Please address them before merging. 

Approved with suggestions.

2023-05-31 19:45 UTC, weijie-lin commented on api-reference/beta/api/unifiedrolemanagementpolicy-update.md
> +|Application|Not supported.|
@ilyalushnikov The lack of app permission is intentional to get it consistent with what we currently have for updating policy rule docs. However, I just tested it. Our implementation currently supports app-only for update policy rule and policy with one of the below permissions: RoleManagement.ReadWrite.Directory, RoleManagementPolicy.ReadWrite.Directory. Will update the docs accordingly.

2023-05-31 20:53 UTC, weijie-lin commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +Get role management policies and their details. This API only applies to Azure AD roles, or Pim for Group membership and ownership. To retrieve policies that apply to Azure RBAC, use the [Azure REST
@ilyalushnikov, @FaithOmbongi , I made the change to  "Get the details of the policies in PIM that can be applied to Azure AD roles or group membership or ownership."

2023-05-31 20:54 UTC, weijie-lin commented on api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
> +```
@ilyalushnikov , @FaithOmbongi , I made the change on example 2 to include expand with nested select

2023-05-31 21:05 UTC, weijie-lin commented on concepts/identity-governance-pim-rules-overview.md
> +In Microsoft Graph, the Azure AD role settings are called *rules*. These rules are grouped in and assigned to Azure AD roles through containers called policies.
@ilyalushnikov It looks good to me.

2023-06-07 07:09 UTC, FaithOmbongi approved these changes
LGTM!

2023-06-08 02:20 UTC, merged