Addition of reportSuspiciousActivitySettings
microsoftgraph/microsoft-graph-docs pull request #21393
Opened 2023-05-23 14:15 UTC by gregkmsft

This docs PR is tracked via this work item: https://dev.azure.com/msft-skilling/Content/_workitems/edit/91700

2023-05-24 09:38 UTC, FaithOmbongi requested changes
Thank you @gregkmsft for your work on this PR. I've left feedback to address inline.

2023-05-24 09:38 UTC, FaithOmbongi commented on api-reference/beta/resources/reportsuspiciousactivitysettings.md
> +Defines the report suspicious activity settings for the tenant, whether it is enabled and which group of users is enabled for use.  Report suspicious activity enables users to report a suspicious voi
The last sentence ... is there a linkage to either the [riskDetection](https://learn.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta) or [riskyUser](https://learn.microsoft.com/en-us/graph/api/resources/riskyuser?view=graph-rest-beta) APIs, specifically the riskEventType and riskDetail objects? Any new values being introduced? It's good to link back and call out any such new entries.

2023-05-24 09:38 UTC, FaithOmbongi commented on api-reference/beta/resources/reportsuspiciousactivitysettings.md
> +|state|advancedConfigState|Specifies the state of the reportSuspiciousActivitySettings object. The possible values are: `default`, `enabled`, `disabled`, `unknownFutureValue`.|
Please indicate what the default state means.

2023-05-24 09:38 UTC, FaithOmbongi commented on api-reference/beta/resources/reportsuspiciousactivitysettings.md
> +|voiceReportingCode|Int32|Specifics the number the user will enter on their phone to report the MFA prompt as suspicious.|
```suggestion
|voiceReportingCode|Int32|Specifies the number the user will enter on their phone to report the MFA prompt as suspicious.|
```

2023-05-24 09:38 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationmethodspolicy-update.md
> +|reportSuspiciousActivitySettings|[reportSuspiciousActivitySettings](../resources/reportsuspiciousactivitysettings.md)|Enable users to report voice or phone app multi-factor authentication notificati
Maintain alphabetical order please.
```suggestion
|registrationEnforcement|[registrationEnforcement](../resources/registrationenforcement.md)|Enforce registration at sign-in time. This property can be used to prompt users to set up targeted authentication methods.|
|reportSuspiciousActivitySettings|[reportSuspiciousActivitySettings](../resources/reportsuspiciousactivitysettings.md)|Enable users to report voice or phone app multi-factor authentication notifications as suspicious.|
|systemCredentialPreferences|[systemCredentialPreferences](../resources/systemcredentialpreferences.md)|Prompt users with their most-preferred credential for multifactor authentication.|
```

2023-05-24 09:38 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationmethodspolicy-get.md
> +    },
Reason for the failing validation.
```suggestion
    "reportSuspiciousActivitySettings": {
        "@odata.type": "#microsoft.graph.reportSuspiciousActivitySettings",
        "state": "enabled",
        "includeTarget": {
            "targetType": "group",
            "id": "all_users",
        },
        "voiceReportingCode": 0,
    },
```

2023-05-24 09:38 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationmethodspolicy-update.md
> +      "voiceReportingCode": 0,
```suggestion
  },
    "reportSuspiciousActivitySettings": {
      "state": "enabled",
      "includeTarget": {
          "targetType": "group",
          "id": "all_users",
      },
      "voiceReportingCode": 0,
```

2023-05-25 02:51 UTC, jpettere approved these changes

2023-05-25 02:52 UTC, jpettere commented
No additional feedback from me. Faith caught everything I saw.

2023-05-29 18:14 UTC, FaithOmbongi approved these changes
Hi @gregkmsft - I've pushed a few commits relating to cross-linking to the riskDetection API docs and to fixing the API Doctor error then approved.

2023-05-31 01:27 UTC, merged