Update Pronouns admin settings
microsoftgraph/microsoft-graph-docs pull request #21404
Opened 2023-05-24 07:04 UTC by aymen-ms

2023-05-25 16:34 UTC, antonsegh commented on api-reference/beta/resources/peoplesetting.md
> +title: "peopleSetting resource type"
is it peopleSetting or peopleSettingS ?

also havent review said 'peopleAdminSettings' ?

2023-05-25 19:56 UTC, aymen-ms commented on api-reference/beta/resources/peoplesetting.md
> +title: "peopleSetting resource type"
updated the resource name

2023-06-08 12:35 UTC, dodaromike commented
@aymen-ms Please resolve conflicts in this PR so we can proceed with review.

2023-06-27 20:05 UTC, dodaromike approved these changes

2023-07-06 14:32 UTC, Danielabom commented on concepts/permissions-reference.md
> +## People Settings permissions
```suggestion
## People settings permissions
```

2023-07-06 15:16 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"ChangedApiName": "peopleSetting",
```suggestion
					"ChangedApiName": "peopleAdminSetting",
```

2023-07-06 15:17 UTC, Danielabom commented on api-reference/beta/resources/peopleadminsettings.md
> +description: "Represents a setting to control the people related admin settings in the tenant"
```suggestion
description: "Represents a setting to control the people-related admin settings in the tenant"
```

2023-07-06 15:32 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Moved the **pronounsSettings** relationship to [peopleAdminSettings](https://learn.microsoft.com/en-us/graph/api/resources/peopleadminsettings?view=graph-rest-beta) resource.",
For this change, you need three entries:
1. To track that you are deleting a nav property from a resource. 
2. To track that you are adding a nav property to a resource.
3.  To show that you are renaming a nav property.

2023-07-06 15:38 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Added support for the policy-based application permission of `PeopleSettings.Read.All` to read tenant-wide [peoplesettings](https://learn.microsoft.com/en-us/graph/api/resources/
```suggestion
					"Description": "Added support for the policy-based application permission of `PeopleSettings.Read.All` to read tenant-wide operations of the [peopleSettings](https://learn.microsoft.com/en-us/graph/api/resources/peopleadminsettings?view=graph-rest-beta) resource.",
```

2023-07-06 15:39 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Added support for the policy-based application permission of `PeopleSettings.Read.All` to the read and write tenant-wide [peoplesettings](https://learn.microsoft.com/en-us/graph/
```suggestion
					"Description": "Added support for the policy-based application permission of `PeopleSettings.Read.All` to the read and write tenant-wide operations of the [peoplesettings](https://learn.microsoft.com/en-us/graph/api/resources/peopleadminsettings?view=graph-rest-beta) resource.",
```

2023-07-06 17:49 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _PeopleSettings.ReadWrite.All_ | Read and write tenant-wide people settings | Allows the application to read and write tenant-wide people settings, on behalf of the signed-in user. | Yes | No |
```suggestion
| _PeopleSettings.ReadWrite.All_ | Read and write tenant-wide people settings | Allows the application to read and write tenant-wide people settings on behalf of the signed-in user. | Yes | No |
```

2023-07-06 17:50 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _PeopleSettings.Read.All_ | Read tenant-wide people settings | Allows the application to read tenant-wide people settings, on behalf of the signed-in user. | Yes | No |
```suggestion
| _PeopleSettings.Read.All_ | Read tenant-wide people settings | Allows the application to read tenant-wide people settings on behalf of the signed-in user. | Yes | No |
```

2023-07-06 17:57 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _PeopleSettings.Read.All_ | Read all tenant-wide people settings | Allows the application to read tenant-wide people settings, without a signed-in user. | Yes |
```suggestion
| _PeopleSettings.Read.All_ | Read all tenant-wide people settings | Allows the application to read tenant-wide people settings without a signed-in user. | Yes |
```

2023-07-06 17:59 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _PeopleSettings.ReadWrite.All_ | Read and write all tenant-wide people settings | Allows the application to read and write tenant-wide people settings, without a signed-in user. | Yes |
```suggestion
| _PeopleSettings.ReadWrite.All_ | Read and write all tenant-wide people settings | Allows the application to read and write tenant-wide people settings without a signed-in user. | Yes |
```

2023-07-06 22:54 UTC, Danielabom commented on changelog/Microsoft.People.json
> +}
Please add a changelog entry to track that you deleted an operation from a resource.

2023-07-06 23:16 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Removed the **pronounsSettings** relationship from [organizationSettings](https://learn.microsoft.com/en-us/graph/api/resources/organizationSettings?view=graph-rest-beta) resourc
```suggestion
					"Description": "Removed the **pronounsSettings** relationship from the [organizationSettings](https://learn.microsoft.com/en-us/graph/api/resources/organizationSettings?view=graph-rest-beta) resource.",
```

2023-07-06 23:51 UTC, Danielabom commented on changelog/Microsoft.People.json
> +		}
Please add the entries for delegated permissions.

2023-07-06 23:59 UTC, Danielabom commented on api-reference/beta/resources/peopleadminsettings.md
> +title: "peopleAdminSettings resource type"
Please add this resource to the TOC, and its operations.

2023-07-07 00:00 UTC, Danielabom commented on changelog/Microsoft.People.json
> +					"Description": "Added the [udpate](https://learn.microsoft.com/en-us/graph/api/pronounssettings-update?view=graph-rest-beta&tabs=http) operation to the [pronounsSettings](https://learn.microsoft
```suggestion
					"Description": "Added the [udpate](https://learn.microsoft.com/en-us/graph/api/pronounssettings-update?view=graph-rest-beta&tabs=http) operation to the [pronounsSettings](https://learn.microsoft.com/en-us/graph/api/resources/pronounssettings?view=graph-rest-beta) resource, to update the tenant-level settings for pronouns",
```
```suggestion
					"Description": "Added the [udpate](https://learn.microsoft.com/en-us/graph/api/pronounssettings-update?view=graph-rest-beta&tabs=http) operation to the [pronounsSettings](https://learn.microsoft.com/en-us/graph/api/resources/pronounssettings?view=graph-rest-beta) resource",
```

2023-07-07 00:07 UTC, Danielabom requested changes
@aymen-ms, all my comments are in. Please review them. Thanks!

2023-07-07 00:18 UTC, Danielabom commented on api-reference/beta/api/peopleadminsettings-list-pronouns.md
> +title: "List pronounsSettings"
Please make you add a changelog entry to delete this method.

2023-07-10 15:33 UTC, Danielabom commented on api-reference/beta/toc.yml
> +        - name: People Admin Settings (preview)
```suggestion
        - name: People admin settings (preview)
```

2023-07-10 15:45 UTC, Danielabom approved these changes
Thank you for addressing my comments @aymen-ms. PR approved.

2023-07-11 05:05 UTC, merged