Support multiple entity request
microsoftgraph/microsoft-graph-docs pull request #21416
Opened 2023-05-25 01:31 UTC by ZChristine

2023-06-01 13:40 UTC, njerigrevious requested changes
Let's make some updates and clarifications here before finalizing. Thanks for this first draft!

2023-06-01 13:40 UTC, njerigrevious commented on concepts/search-concept-multipleRequest.md
> +Entity types in every search request in the request body should be contained in the entity types list: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. And
What is meant by the second sentence "And Entity types in every search request should follow the relationships defined in [interleaving search](search-concept-interleaving.md)"?

2023-06-01 13:40 UTC, njerigrevious commented on concepts/search-concept-multipleRequest.md
> +- Duplicate entitytype across different search requests in the request body is not allowed.
Does this mean that you cant have a single request body with a "listItem" block and another "listItem" block? If so, we should give an example.

2023-06-01 13:40 UTC, njerigrevious commented on concepts/search-concept-multipleRequest.md
> +- File entity type can only occur once across different entity requests.
List the different file entity types here so it's clear

2023-06-07 08:03 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- Duplicate entitytype across different search requests in the request body is not allowed.
yes. a "listItem" block and another "listItem" block are not allowed. Is there any suggested location for bad request?

2023-06-07 08:09 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +`site`, `drive`, `driveItem`, `list`,`listItem` can only be set in the same search request.
same as "File entity type(`site`, `drive`, `driveItem`, `list`,`listItem`) can only occur once across different entity requests.". Duplicate. Remove

2023-06-07 08:11 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +Entity types in every search request in the request body should be contained in the entity types list: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. And
similar as supported entity types for interleaving

2023-06-07 15:17 UTC, njerigrevious requested changes
Thanks for making some of the edits - left additional questions. Thanks!

2023-06-07 15:17 UTC, njerigrevious commented on concepts/search-concept-multipleRequest.md
> +- Duplicate entitytype across different search requests in the request body is not allowed.
Great question - there's no place for bad requests but I do think that we should bring this up in team meeting!

In the meantime, I would just rephrase line 169 to "Duplicate entitytype across different search requests in the request body is not allowed. For example, you cannot have a "listItem" block and another "listItem" block."

2023-06-07 15:17 UTC, njerigrevious commented on concepts/search-concept-multipleRequest.md
> +Supported entity types for passing multiple search requests in a request body are: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. And Entity types in eve
What do you mean by "And Entity types in every search request should follow the relationships defined in [interleaving search](search-concept-interleaving.md)"?

2023-06-07 15:17 UTC, njerigrevious requested changes
Thanks for making some of the edits - left additional questions. Thanks!

2023-06-08 03:49 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- Duplicate entitytype across different search requests in the request body is not allowed.
Done.

2023-06-08 03:52 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +Supported entity types for passing multiple search requests in a request body are: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. And Entity types in eve
Entity types in the same request block should follow the interleaving supported entity types.

2023-06-08 13:58 UTC, njerigrevious requested changes
One more change based on what we discussed - thanks!

2023-06-08 13:58 UTC, njerigrevious commented on concepts/search-concept-multipleRequest.md
> +Supported entity types for passing multiple search requests in a request body are: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. And Entity types in eve
Agreed! Please rephrase to "This means that entity types in the same request block should follow the interleaving supported entity type relationships/combinations as defined in [interleaving search](search-concept-interleaving.md)"

2023-06-08 14:04 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +Supported entity types for passing multiple search requests in a request body are: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. And Entity types in eve
rephrase to "And in  the same time, the entity types in the same request block should follow the interleaving supported entity type relationships/combinations as defined in [interleaving search](search-concept-interleaving.md)."
Because it's diffferent from previous line

2023-06-13 16:07 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +title: "Pass multiple search requests in a request body with the Microsoft Search API"
Is this a shorter but still clear tittle? @ZChristine

2023-06-13 16:11 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +Now you can pass multiple search requests in a request body with the Microsoft Search API. This is currently enabled for OneDrive or SharePoint, external contents ingested and indexed by [Microsoft G
```suggestion
The Microsoft Search API allows you to include multiple search requests in a single request body. This capability is currently available for OneDrive and SharePoint, as well as for external contents that are ingested and indexed by [Microsoft Graph connectors](/microsoftsearch/connectors-overview) and answers types, including bookmarks, acronyms, and Q&A.
```

2023-06-13 16:12 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +## Supported entity combination
```suggestion
## Supported entities combination
```

2023-06-13 16:13 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +## Supported entity combination
```suggestion
## Supported entity types
```

2023-06-13 16:17 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +### Example 1: Search with SharePoint file types and bookmark/acornym combination
```suggestion
### Example 1: Search with SharePoint file types and bookmark/acronym combinations
```

2023-06-13 16:18 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +## Bad Request Examples
```suggestion
## Bad request examples
```

2023-06-13 16:19 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +### Example 1: Search with the same entity types in seperate requst blocks in the request body
```suggestion
### Example 1: Search with the same entity types in separate request blocks within the request body
```

2023-06-13 16:21 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +### Example 2: Search with the file entity types in seperate requst blocks in the request body
```suggestion
### Example 2: Search with the file entity types in separate request blocks in the request body
```

2023-06-13 16:24 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +- Properties **from**, **size** from different [searchRequest](graph/api/resources/searchrequest?view=graph-rest-beta) in the request body should be the same. And properties **queryString** of [searc
```suggestion
- The properties **from**, **size** from different [searchRequest](graph/api/resources/searchrequest?view=graph-rest-beta) in the request body should be the same. And the  **queryString** property of [searchQuery](graph/api/resources/searchquery?view=graph-rest-beta) in different searchRequest should be the same.
```

2023-06-13 16:26 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +- File entity type(`site`, `drive`, `driveItem`, `list`,`listItem`) can only occur once across different entity requests.
```suggestion
- The file entity types (`site`, `drive`, `driveItem`, `list`,`listItem`)  can only be present once among different entity requests..
```

2023-06-13 16:26 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +- Speller can only be used once and in the first entity request.
```suggestion
- The speller functionality can only be used once and it should be included in the first entity request.
```

2023-06-13 16:27 UTC, Danielabom requested changes
@ZChristine, please review my comments. Thanks.

2023-06-14 03:01 UTC, ZChristine commented
> @ZChristine, please review my comments. Thanks.

comment resolve. thanks.

2023-06-15 00:11 UTC, ZChristine commented
@Danielabom  the comments have been resolved. Can you help approve the PR if no concerns? 

cc: @njerigrevious

2023-06-16 14:54 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +- The properties **from**, **size** from different [searchRequest](graph/api/resources/searchrequest?view=graph-rest-beta) in the request body should be the same. And the  **queryString** property of
```suggestion
- The properties **from** and **size** from different [searchRequest](graph/api/resources/searchrequest?view=graph-rest-beta) in the request body should be the same. And the  **queryString** property of [searchQuery](graph/api/resources/searchquery?view=graph-rest-beta) in different searchRequest should be the same.
```

2023-06-16 14:56 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +- The file entity types (`site`, `drive`, `driveItem`, `list`,`listItem`)  can only be present once among different entity requests..
```suggestion
- The file entity types (`site`, `drive`, `driveItem`, `list`,`listItem`)  can only be present once among different entity requests.
```

2023-06-16 14:57 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +The supported entity types for including multiple search requests in a request body are: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. Entity types with
```suggestion
The supported entity types for including multiple search requests in a request body are: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`, `acronym`, and `qna`. Entity types within the same request block should adhere to the supported entity type relationships and combinations defined in the [interleaving search](search-concept-interleaving.md) topic.
```

2023-06-16 14:58 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +title: "Pass multiple search requests in the request body with the Microsoft Search API"
```suggestion
title: "Use the Microsoft Graph Search API to pass multiple search requests"
```

2023-06-17 01:35 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +The Microsoft Search API allows you to include multiple search requests in a single request body. This capability is currently available for OneDrive and SharePoint, as well as for external contents
What do you mean by "answers types" here; is this a reference to resource types?

2023-06-17 01:36 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +The supported entity types for including multiple search requests in a request body are: `site`, `drive`, `driveItem`, `list`,`listItem`,`externalItem`, `bookmark`,`acronym`, `qna`. Entity types with
Note that resource/entity types are formatted in bold; the tick marks are how we format values and inline code. Please adjust the formatting here.

2023-06-17 01:43 UTC, Lauragra commented on concepts/search-concept-interleaving.md
> +The following table shows the relationship between different entity types that can be interleaved. Note that **qna** is only supported in v1.0.
Please verify this statement - the qna resource is only in beta and not in v1.0; is that what you meant to say here? Also, to be clear, you should then statue that all resources are supported in v1.0 except for the qna resource.

How should a developer interpret this table? Does this mean that any combination of Trues can be combined in a single search request?

2023-06-17 01:44 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +The following is an example of interleaving response.
Revise as: The following example shows a response with interleaved results.

2023-06-17 01:46 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +The following is an example of bad request response.
Why are we showing an example that's invalid? If it's to illustrate what they can and can't do in a search, I suggest that you provide a bit more context before introducing the example. Also note that you're missing the article "a" before "bad request".

2023-06-17 01:47 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +### Example 2: Search with the file entity types in separate request blocks in the request body
I have the same comment about this request, which it seems is also invalid. I think you need to provide an explanation for why you're including an example that won't return a valid response.

2023-06-17 01:47 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +The following is an example of bad request response.
Add the missing article "a" here as well.

2023-06-17 02:00 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +- The properties **from** and **size** from different [searchRequest](graph/api/resources/searchrequest?view=graph-rest-beta) in the request body should be the same. And the  **queryString** property
I'm not sure that this sentence is clear. It's one search request, right? And what do you mean they should be the same, if they're different properties? And how is the queryString property related to from and size? Please clarify.

2023-06-17 02:08 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +- The file entity types (`site`, `drive`, `driveItem`, `list`, and `listItem`)  can only be present once among different entity requests.
Note that entity type names are formatted as bold. Again, I'm not sure that "among different entity requests" is clear. Do you mean within a search request? And if so, how is this statement different than the statement in the previous bullet?

2023-06-17 02:09 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +- The speller functionality can only be used once and it should be included in the first entity request.
Do you need to clarify what the speller functionality or have a link here?

2023-06-17 03:03 UTC, Danielabom commented
@ZChristine, please review Laura's comments. Thanks.

2023-06-18 10:36 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +The Microsoft Search API allows you to include multiple search requests in a single request body. This capability is currently available for OneDrive and SharePoint, as well as for external contents
answer types includes bookmarks, acronyms, and Q&A. It's a general term mentioned in https://learn.microsoft.com/en-us/graph/search-concept-answers?tabs=http

2023-06-18 10:51 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +The following is an example of interleaving response.
Revise as: The following shows a response that searches with SharePoint file types and bookmark/acronym combinations.

2023-06-18 12:21 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +### Example 2: Search with the file entity types in separate request blocks in the request body
Because there's some Known limitations down this article. And the bad request some parts of the limitation to give the user a clear view.

2023-06-18 12:24 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- The properties **from** and **size** from different [searchRequest](graph/api/resources/searchrequest?view=graph-rest-beta) in the request body should be the same. And the  **queryString** property
They are in the different entity requests of the same request body. The value of the property should be the same for from, size and query string.

2023-06-18 12:25 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- Duplicate entity types across different search requests in the request body are not allowed. For example, you cannot have a "bookmark" block and another "bookmark" block.".
Rephrase to: For example, you cannot have a "bookmark" search request and another "bookmark" search request in a request body.

2023-06-18 12:28 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- The file entity types (`site`, `drive`, `driveItem`, `list`, and `listItem`)  can only be present once among different entity requests.
Will add a example.

2023-06-18 12:35 UTC, ZChristine commented on concepts/search-concept-interleaving.md
> +The following table shows the relationship between different entity types that can be interleaved. Note that **qna** is only supported in v1.0.
Yes, it means that any combination of Trues can be combined in a single search request.

2023-06-18 12:38 UTC, ZChristine commented
> @ZChristine, please review Laura's comments. Thanks.

2023-06-18 12:39 UTC, ZChristine commented
> @ZChristine, please review Laura's comments. Thanks.

Update

2023-06-19 17:11 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +The Microsoft Search API allows you to include multiple search requests in a single request body. This capability is currently available for OneDrive and SharePoint, as well as for external contents
```suggestion
The Microsoft Search API allows you to include multiple search requests in a single request body. This capability is currently available for OneDrive and SharePoint, as well as for external contents that are ingested and indexed by [Microsoft Graph connectors](/microsoftsearch/connectors-overview) and answer resource types, including bookmarks, acronyms, and Q&A.
```

2023-06-19 17:14 UTC, Danielabom commented on concepts/search-concept-multipleRequest.md
> +The supported entity types for including multiple search requests in a request body are: **site**, **drive**, **driveItem**, **list**,**listItem**,**externalItem**, **bookmark**,**acronym**, **qna**.
```suggestion
The supported entity types for including multiple search requests in a request body are: **site**, **drive**, **driveItem**, **list**,**listItem**,**externalItem**, **bookmark**,**acronym**, and **qna**. Entity types within the same request block should adhere to the supported entity type relationships and combinations defined in the [interleaving search](search-concept-interleaving.md) topic.
```

2023-06-19 17:17 UTC, Danielabom commented on concepts/search-concept-interleaving.md
> +The following table shows the relationship between different entity types that can be interleaved. Note that **qna** is only supported in beta.
```suggestion
The following table shows the relationship between different entity types that can be interleaved. Note that the **qna** entity type is only supported in beta.
```

2023-06-20 00:46 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +- The properties **from** and **size** from different [searchRequest](graph/api/resources/searchrequest?view=graph-rest-beta) in the request body should be the same. And the  **queryString** property
@ZChristine  , can you please clarify the sentence for readers? For example:

The values used for the **from**, **size**, and **queryString** properties in the request body must be the same.

2023-06-20 00:47 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +### Example 2: Search with the file entity types in separate request blocks in the request body
Please explain that this is a bad request in introductory text for this example. Otherwise, readers might think it's a valid example until they see the response/known limitations section.

2023-06-20 00:51 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +- Duplicate entity types across different search requests in the request body are not allowed. For example, you cannot have a "bookmark" search request and another "bookmark" search request in a requ
Would this be an accurate revision for the second sentence:

"For example, you can't have a **bookmark** entity type and a second **bookmark** entity type within a single request block."

Also note that we don't use quotation marks for resource names; they should be bold.

2023-06-20 00:57 UTC, Lauragra reviewed
Please see my additional comments.

2023-06-20 00:57 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +- The file entity types (**site**, **drive**, **driveItem**, **list**, and **listItem**)  can only be present in the same entity request of a request body. For example, you cannot have a "site" searc
I don't know if the "parts" of a search request body are clear from this article. What do we mean by "entity request" and "search request". Is there only one request block per request? Would it be accurate to simply the statement as:

"Only one file entity type (**site**.... ) can be included in a search request. For example, you can't include both a **site** and a **drive** entity type in the same search request."

2023-06-20 00:57 UTC, Lauragra commented on concepts/search-concept-multipleRequest.md
> +- The [speller](search-concept-speller.md) functionality can only be used once and it should be included in the first entity request.
Can you help clarify what you mean by "entity request"? Do you mean to say "... should be included as the first entity in the search request"?

2023-06-20 01:14 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- The file entity types (**site**, **drive**, **driveItem**, **list**, and **listItem**)  can only be present in the same entity request of a request body. For example, you cannot have a "site" searc
Rephrase to: 
- The file entity types (**site**, **drive**, **driveItem**, **list**, and **listItem**)  can only be present in the same search request of a request body. For example, you can't include both a **site** and a **drive** entity type in the different search requests of a request body.

2023-06-20 01:17 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- The [speller](search-concept-speller.md) functionality can only be used once and it should be included in the first entity request.
Rephrase to: The first search request in the request body.

2023-06-20 01:20 UTC, ZChristine commented on concepts/search-concept-multipleRequest.md
> +- Duplicate entity types across different search requests in the request body are not allowed. For example, you cannot have a "bookmark" search request and another "bookmark" search request in a requ
A request body would contain multiple search request. The schema would look like below. Here means that bookmark cannot be put in different searchRequest in the same request body.
{
"requests":[{},{},{}]
}

2023-06-20 03:56 UTC, Lauragra approved these changes

2023-06-20 04:07 UTC, merged