matching v1 to have beta properties
microsoftgraph/microsoft-graph-docs pull request #21410
Opened 2023-05-24 15:30 UTC by quievey

Get the properties on V1 to be at par with properties on beta.

2023-07-06 09:36 UTC, msewaweru requested changes
@quievey - thanks for the work on this PR. Some minor suggestions for you to action. Thanks.

2023-07-06 09:36 UTC, msewaweru commented on api-reference/v1.0/resources/organizationalbrandinglocalization.md
> +| signInPageText | String | Text that appears at the bottom of the sign-in box. Use this to communicate additional information, such as the phone number to your help desk or a legal statement. This t
```suggestion
| signInPageText | String | Text that appears at the bottom of the sign-in box. Use this to communicate additional information, such as the phone number to your help desk or a legal statement. This text must be in Unicode format and not exceed 1024 characters. Inherited from [organizationalBrandingProperties](organizationalbrandingproperties.md).|
```

2023-07-12 16:27 UTC, quievey commented on api-reference/v1.0/resources/loginPageTextVisibilitySettings.md
> +| hideResetItNow | Boolean | Option to hide the self-service password reset (SSPR) "reset it now" hyperlink on the sign-in form. |
PR to add this https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/14627

2023-07-26 04:57 UTC, Lauragra commented
@FaithOmbongi , @msewaweru , has anyone reviewed this PR?

2023-07-26 07:32 UTC, msewaweru commented
> @FaithOmbongi , @msewaweru , has anyone reviewed this PR?

@Lauragra - Yes, I completed the reviews and approved.

2023-07-26 07:33 UTC, msewaweru approved these changes
Review completed.

2023-07-27 03:56 UTC, Lauragra commented on api-reference/v1.0/resources/loginPageLayoutConfiguration.md
> +title: "loginPageLayoutConfiguration resource type"
Please use all lowercase for the file names instead of lower camel case.

2023-07-27 03:56 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the `customAccountResetCredentialsUrl` property to the [organizationalBrandingProperties](https://learn.microsoft.com/en-us/graph/api/resources/organizationalBrandingP
Please apply bold formatting instead of tick marks to the property names.

2023-07-27 14:58 UTC, quievey commented
@Lauragra comments addressed and resolved.

2023-07-27 16:07 UTC, Lauragra approved these changes

2023-07-28 03:50 UTC, merged