V1 changes for LearnerCourseActivity docs
microsoftgraph/microsoft-graph-docs pull request #21455
Opened 2023-05-29 06:55 UTC by pkattekol

2023-06-16 16:20 UTC, Danielabom commented on api-reference/v1.0/resources/learningcourseactivity.md
> +|status|courseStatus|The status of the course activity. Possible values are: `notStarted`, `inProgress`, `completed`. Required.|
It seems that you are promoting only a few properties to v1, because the CSDL and the api.md files show fewer properties. Please check.

2023-06-16 16:32 UTC, Danielabom commented on api-reference/v1.0/resources/learningselfinitiatedcourse.md
> +
It seems that you are promoting only a few properties to v1, because the CSDL and the api.md files show fewer properties. Please check.

2023-06-16 18:03 UTC, Danielabom commented on changelog/Microsoft.Viva.Learning.json
> +          "ChangedApiName": "learningAssignment",
```suggestion
          "ChangedApiName": "assignmentType",
```

2023-06-16 18:23 UTC, Danielabom commented on changelog/Microsoft.Viva.Learning.json
> +          "Target": "learningAssignment"
```suggestion
          "Target": "assignmentType"
```

2023-06-16 18:54 UTC, Danielabom commented on api-reference/v1.0/toc.yml
> +            href: api/learningcourseactivity-delete.md
We are missing resources and operations in the TOC.

2023-06-16 18:54 UTC, Danielabom commented on changelog/Microsoft.Viva.Learning.json
> +          "ChangedApiName": "learningAssignment",
```suggestion
          "ChangedApiName": "courseStatus",
```

2023-06-16 18:55 UTC, Danielabom commented on changelog/Microsoft.Viva.Learning.json
> +          "Target": "learningAssignment"
```suggestion
          "Target": "courseStatus"
```

2023-06-16 20:08 UTC, Danielabom requested changes
Please see my comments. @pkattekol Thanks!

2023-06-19 11:31 UTC, pkattekol commented on api-reference/v1.0/resources/learningassignment.md
> +|status|courseStatus|The status of the course activity. Possible values are: `notStarted`, `inProgress`, `completed`. Required.|
@Danielabom  We have all the properties listed in api.md and CSDL here. @odata.type is an attribute which is not specific to our API but is a common property provider by odata schema. Other than that, rest all are available in the CSDL file. 
api.md - https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/14416
CSDL - https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/8187315

2023-06-19 11:32 UTC, pkattekol commented on api-reference/v1.0/resources/learningselfinitiatedcourse.md
> +
@Danielabom We have all the properties listed in api.md and CSDL here. @odata.type is an attribute which is not specific to our API but is a common property provider by odata schema. Other than that, rest all are available in the CSDL file.
api.md - https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/14416
CSDL - https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/8187315

2023-06-24 02:12 UTC, Danielabom commented on api-reference/v1.0/toc.yml
> +            href: api/learningcourseactivity-delete.md
@pkattekol, I do not see any updates on the TOC. We a missing resources and operations. Please add them.

2023-06-26 05:11 UTC, pkattekol commented on api-reference/v1.0/toc.yml
> +            href: api/learningcourseactivity-delete.md
Modified the toc now to add LearningAssignment and LearningSelfInitiated course. There are no specific operations for these as LearningCourseActivity is base cass and all the operations like Get,Delete,Update is same for both LearningAssignment and LearningSelfInitiatedCourse

2023-06-29 00:43 UTC, Danielabom commented
@pkattekol, Hi Prasanna,
To address the build conflicts on this PR [V1 changes for LearnerCourseActivity docs by pkattekol · Pull Request #21455 · microsoftgraph/microsoft-graph-docs (github.com)](https://github.com/microsoftgraph/microsoft-graph-docs/pull/21455), please follow these steps:
Scroll down to the end of the pull request (PR).
Click on "Resolve conflicts."
Build conflicts related to the TOC, typically occur when authors update the Table of Contents (TOC) and copy content that already exists, treating it as a template. Another common cause is leaving a file open for an extended period, causing syncing issues with GitHub.
Please be careful to avoid deleting any topics that were successfully published in the TOC previously.
By resolving these conflicts carefully, we can ensure the smooth integration of changes and preserve the integrity of the TOC.

2023-06-30 01:24 UTC, merged