Add 2 error code for canary new built-in roles
microsoftgraph/microsoft-graph-docs pull request #21454
Opened 2023-05-29 06:47 UTC by Sodaine

2023-05-29 06:58 UTC, RuiHou105 requested changes
@Sodaine  Please:
1.Update the changelog to describe your change.
2.Create roadmap workitem and attach the workitem number in comments.

2023-05-31 09:12 UTC, Sodaine commented
> @Sodaine Please: 1.Update the changelog to describe your change. 2.Create roadmap workitem and attach the workitem number in comments.

Done

2023-05-31 09:13 UTC, Sodaine commented
> @Sodaine Please: 1.Update the changelog to describe your change. 2.Create roadmap workitem and attach the workitem number in comments.

Done

2023-05-31 09:13 UTC, closed without merging

2023-06-01 06:33 UTC, RuiHou105 approved these changes

2023-06-08 18:04 UTC, Danielabom commented
@Jarbas-MSFT @Lauragra, moving this PR back into my queue.

2023-06-08 20:33 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the **permissionCheckNoWindows365NetworkUserRole** member to the [cloudPcOnPremisesConnectionHealthCheckErrorType](https://learn.microsoft.com/en-us/graph/api/re
```suggestion
                "Description": "Added the `permissionCheckNoWindows365NetworkUserRole` member to the **cloudPcOnPremisesConnectionHealthCheckErrorType** enumeration .",
```

2023-06-08 20:34 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "ApiChange": "Property",
```suggestion
                "ApiChange": "Member",
```

2023-06-08 20:35 UTC, Danielabom commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the **permissionCheckNoWindows365NetworkInterfaceContributorRole** member to the [cloudPcOnPremisesConnectionHealthCheckErrorType](https://learn.microsoft.com/en
```suggestion
                "Description": "Added the `permissionCheckNoWindows365NetworkInterfaceContributorRole` member to the **cloudPcOnPremisesConnectionHealthCheckErrorType** enumeration.",
```

2023-06-08 20:45 UTC, Danielabom commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckNoWindows365NetworkInterfaceContributorRole|Cloud PC service principal does not have Windows365 network interface contributor role on the specified resource group. Please work with th
1. Windows 365 will be mentioned correctly above. Please confirm if "Windows 365" is the accepted abbreviation.
2. Please remove the word "please."

2023-06-08 20:45 UTC, Danielabom requested changes
Thank you for working on this PR, @Sodaine. Please review my comments.

2023-07-20 06:36 UTC, Emma0727 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckNoWindows365NetworkUserRole|Cloud PC service principal does not have Windows365 network user role on the specified virtual network. Please work with subscription owner to add the  Win
Done, please help review again.

2023-07-20 06:36 UTC, Emma0727 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckNoWindows365NetworkInterfaceContributorRole|Cloud PC service principal does not have Windows365 network interface contributor role on the specified resource group. Please work with th
Done, please help review again.

2023-07-25 06:50 UTC, Emma0727 commented
@Danielabom @Lauragra  Can you help review this PR when you are available?