Add get azure resources api
microsoftgraph/microsoft-graph-docs pull request #21458
Opened 2023-05-29 08:08 UTC by hyc3z

This PR is for review only. The schema updated is hidden, and is not planned for public doc update.

2023-05-31 08:15 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionazureresource.md
> + `resourceId`         | `Edm.String`                                                          | Unique identifier of the Azure Resource. Read-only.                                    |
```suggestion
| `resourceId`         | `Edm.String`                                                          | Unique identifier of the Azure Resource. Read-only.                                    |
```

2023-05-31 08:16 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionazureresource.md
> +| `resourceState`      | [cloudPcOnPremisesConnectionAzureResourceState](#cloudpconpremisesconnectionazureresourcestate-values) | The state of the resource. Read-only.
```suggestion
| `resourceState`      | [cloudPcOnPremisesConnectionAzureResourceState](#cloudpconpremisesconnectionazureresourcestate-values) | Indicates  the state of the resource. Possible values include... Read-only.                                                  | 
```

2023-05-31 08:18 UTC, RuiHou105 commented on api-reference/beta/api/cloudpconpremisesconnection-getazureresources.md
> +|Application|Not supported.|
I believe this API should also suport app-only token ?

2023-05-31 08:19 UTC, RuiHou105 commented on api-reference/beta/api/cloudpconpremisesconnection-getazureresources.md
> +POST /deviceManagement/virtualEndpoint/onPremisesConnections/getAzureResources(rootResourceId='*',resourceType='virtualNetwork',resourceStatus='available')
```suggestion
GET/deviceManagement/virtualEndpoint/onPremisesConnections/getAzureResources(rootResourceId='*',resourceType='virtualNetwork',resourceStatus='available')
```

2023-05-31 08:20 UTC, RuiHou105 commented on api-reference/beta/api/cloudpconpremisesconnection-getazureresources.md
> +# [C#](#tab/csharp)
You don't need to manually write these different languages' scripts, since after PR gets merged, the tool will help you to generate the scripts. So please remove these scripts in your PR.

2023-05-31 08:23 UTC, RuiHou105 requested changes
@hyc3z 
1.Please resolve comments in this PR
2.Please do update the changelog to describe your change.
3.Please create a roadmap workitem and attach the workitem number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/17432/). If you don't have permissions, please do these firstly:
Pass this info to new partners who need access:

-Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
-Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2023-05-31 08:23 UTC, RuiHou105 requested changes
@hyc3z 
1.Please resolve comments in this PR
2.Please do update the changelog to describe your change.
3.Please create a roadmap workitem and attach the workitem number in comment. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/17432/). If you don't have permissions, please do these firstly:
Pass this info to new partners who need access:

-Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
-Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2023-06-01 04:03 UTC, hyc3z commented
Thanks @RuiHou105 for your comments!! Will update the pr to include changes

2023-06-01 07:11 UTC, hyc3z commented
Hi @RuiHou105 I've resolved comments and updated the changelog and roadmap item. Please help validate when you're free, thanks!!

2023-06-01 07:32 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "ApiChange": "Resource",
```suggestion
                "ApiChange": "Enumeration",
```

2023-06-01 07:32 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the [cloudPcOnPremisesConnectionAzureResourceState](https://learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionazureresource?view=graph-res
```suggestion
                "Description": "Added the [cloudPcOnPremisesConnectionAzureResourceState](https://learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionazureresource?view=graph-rest-beta) enumeration type.",
```

2023-06-01 07:32 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "ApiChange": "Resource",
```suggestion
                "ApiChange": "Enumeration",
```

2023-06-01 07:33 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Description": "Added the [cloudPcOnPremisesConnectionAzureResourceType](https://learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionazureresource?view=graph-rest
```suggestion
                "Description": "Added the [cloudPcOnPremisesConnectionAzureResourceType](https://learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionazureresource?view=graph-rest-beta) enumeration type.",
```

2023-06-01 07:34 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +        ],
In addition to these changes, please also add this resource: cloudPcOnPremisesConnectionAzureResource

2023-06-01 07:37 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionazureresource.md
> +| `resourceType`       | [cloudPcOnPremisesConnectionAzureResourceType](#cloudpconpremisesconnectionazureresourcetype-values)  | Indicates the resource type of the resource. Possible values include `
```suggestion
| `resourceType`       | [cloudPcOnPremisesConnectionAzureResourceType](#cloudpconpremisesconnectionazureresourcetype-values)  | Indicates the resource type of the resource. Possible values include `subscription`, `resourceGroup`, `virtualNetwork`, `subnet` . Read-only.                                          | 
```

2023-06-01 07:38 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionazureresource.md
> +| `resourceState`      | [cloudPcOnPremisesConnectionAzureResourceState](#cloudpconpremisesconnectionazureresourcestate-values) | Indicates  the state of the resource. Possible values include `availa
```suggestion
| `resourceState`      | [cloudPcOnPremisesConnectionAzureResourceState](#cloudpconpremisesconnectionazureresourcestate-values) | Indicates  the state of the resource. Possible values include `available`, `unavailable`, `notSpecified` Read-only.                                                  | 
```

2023-06-01 07:39 UTC, RuiHou105 commented on api-reference/beta/api/cloudpconpremisesconnection-getazureresources.md
> +POST /deviceManagement/virtualEndpoint/onPremisesConnections/getAzureResources(rootResourceId='*',resourceType='resourceGroup',resourceStatus='available')
```suggestion
GET/deviceManagement/virtualEndpoint/onPremisesConnections/getAzureResources(rootResourceId='*',resourceType='resourceGroup',resourceStatus='available')
```

2023-06-01 09:13 UTC, RuiHou105 approved these changes

2023-07-14 07:36 UTC, AshleyYangSZ requested changes
@hyc3z Please abandon this PR, since the API is hidden, no need to publish doc.

2023-08-03 02:00 UTC, closed without merging