IsCourseActivitySyncEnabled for LearningProvider
microsoftgraph/microsoft-graph-docs pull request #21464
Opened 2023-05-29 18:29 UTC by pkattekol

2023-05-30 16:42 UTC, Danielabom commented on api-reference/beta/resources/learningprovider.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether the course activities will be ingested for this provider or not. Default value is `false`. Course activities for a provider cannot be ingested i
Perhaps, we can have a better word choice here. I am not clear, on who could be a provider. Please share an example.

2023-05-30 16:43 UTC, Danielabom commented on api-reference/beta/resources/learningprovider.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether the course activities will be ingested for this provider or not. Default value is `false`. Course activities for a provider cannot be ingested i
Please add the changelog.

2023-05-30 16:43 UTC, Danielabom requested changes
@pkattekol, please see my comments. Thanks!

2023-05-30 18:41 UTC, udbach commented on api-reference/beta/resources/learningprovider.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether the course activities will be ingested for this provider or not. Default value is `false`. Course activities for a provider cannot be ingested i
Added changelog. This is a new property added to existing learning provider api.

2023-05-31 22:47 UTC, Danielabom commented on api-reference/beta/resources/learningprovider.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether learning course activity records will be ingested for this provider or not. Default value is `false`. Learning course activities for a provider
```suggestion
|isCourseActivitySyncEnabled|Boolean|Indicates whether a provider can ingest learning course activity records. The default value is `false`. Turn to true to make learningCourseActivities for this provider. .|
```

2023-05-31 22:49 UTC, Danielabom commented on api-reference/v1.0/resources/learningprovider.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether learning course activity records will be ingested for this provider or not. Default value is `false`. Learning course activities for a provider
```suggestion
|isCourseActivitySyncEnabled|BooleanIndicates whether a provider can ingest learning course activity records. The default value is `false`. Set to true to make learningCourseActivities for this provider.|
```

2023-05-31 23:24 UTC, Danielabom commented on api-reference/beta/api/employeeexperience-post-learningproviders.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether [learningCourseActivity](../resources/learningcourseactivity.md) records will be ingested for this provider or not. Default value is `false`. Le
```suggestion
|isCourseActivitySyncEnabled|Boolean|Indicates whether a provider can ingest [learningCourseActivity](../resources/learningcourseactivity.md) records. The default value is `false`. Set to true to make learningCourseActivities available for this provider.|
```

2023-05-31 23:24 UTC, Danielabom commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to upd
```suggestion
**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to update them.
```

2023-05-31 23:25 UTC, Danielabom commented on api-reference/beta/api/learningcourseactivity-delete.md
> +**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to upd
```suggestion
**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to update them.
```

2023-05-31 23:25 UTC, Danielabom commented on api-reference/beta/api/learningcourseactivity-update.md
> +**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to upd
```suggestion
**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to update them.
```

2023-05-31 23:26 UTC, Danielabom commented on api-reference/beta/api/learningprovider-update.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether [learningCourseActivity](../resources/learningcourseactivity.md) records will be ingested for this provider or not. Default value is `false`. Le
```suggestion
|isCourseActivitySyncEnabled|Boolean|Indicates whether a provider can ingest [learningCourseActivity](../resources/learningcourseactivity.md). The default value is `false`. Set to true to make learningCourseActivities available for this provider.|
```

2023-05-31 23:29 UTC, Danielabom commented on api-reference/beta/resources/learningcourseactivity.md
> +>**Note**: Course activities can only be ingested for a provider when courseAcitvitySyncEnabled is true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to update the
```suggestion
>**Note**: A provider can ingest course activities when courseAcitvitySyncEnabled is set to true. Please use the [Update learningProvider API](../api/learningprovider-update.md) to update the value. 
```

2023-05-31 23:36 UTC, Danielabom requested changes
Hi @pkattekol, I've made the changes required. Please review them and approve my suggestions or reach out if you have questions.

2023-06-01 17:43 UTC, Danielabom approved these changes
@pkattekol, thank you for working on this PR. PR approved.

2023-06-02 17:32 UTC, dodaromike approved these changes

2023-06-02 17:32 UTC, dodaromike approved these changes

2023-06-02 17:32 UTC, dodaromike approved these changes

2023-06-03 00:30 UTC, Lauragra commented on api-reference/beta/api/employeeexperience-post-learningproviders.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether a provider can ingest [learningCourseActivity](../resources/learningcourseactivity.md) records. The default value is `false`. Set to true to mak
Global: Please add the new property to the table in alphabetical order instead of adding it to the end of the table.

2023-06-03 00:32 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is set to `true`. Please use the [Update learningProvider API](../api/learningprovider-update.m
Global: Please format this text as a note and revise as follows:

>**Note**: Learning course activities can be managed by a provider only when **isCourseAcitvitySyncEnabled** is set to `true`. To update the value, use the [Update learningProvider](../api/learningprovider-update.md) method.

2023-06-03 00:33 UTC, Lauragra commented on api-reference/beta/resources/learningcourseactivity.md
> +>**Note**: A provider can ingest course activities when courseAcitvitySyncEnabled is set to `true`. Please use the [Update learningProvider API](../api/learningprovider-update.md) to update the value
Revise as:

>**Note**: A provider can ingest course activities when **courseAcitvitySyncEnabled** is set to `true`. To update the value, use the [Update learningProvider](../api/learningprovider-update.md) method.

2023-06-03 00:34 UTC, Lauragra commented on changelog/Microsoft.Viva.Learning.json
> +          "Description": "Added the **isCourseActivitySyncEnabled** property to [learningProvider](https://learn.microsoft.com/en-us/graph/api/resources/learningProvider?view=graph-rest-beta) resourc
Add the missing article "the" after the word "to".

2023-06-03 00:34 UTC, Lauragra commented on changelog/Microsoft.Viva.Learning.json
> +          "Description": "Added the **isCourseActivitySyncEnabled** property to [learningProvider](https://learn.microsoft.com/en-us/graph/api/resources/learningProvider?view=graph-rest-1.0) resource
Add the missing article "the" after the word "to".

2023-06-05 15:14 UTC, Danielabom commented on api-reference/beta/resources/learningcourseactivity.md
> +>**Note**: A provider can ingest course activities when courseAcitvitySyncEnabled is set to `true`. Please use the [Update learningProvider API](../api/learningprovider-update.md) to update the value
```suggestion
>**Note**: A provider can ingest course activities when courseAcitvitySyncEnabled is set to `true`. To update the value, use the [Update learningProvider API](../api/learningprovider-update.md) method.  
```

2023-06-05 15:15 UTC, Danielabom commented on api-reference/beta/api/learningcourseactivity-delete.md
> +**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is set to `true`. Please use the [Update learningProvider API](../api/learningprovider-update.m
```suggestion
**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is set to `true`. To update the value, use the  [Update learningProvider API](../api/learningprovider-update.md) method.
```

2023-06-05 15:16 UTC, Danielabom commented on api-reference/beta/api/learningcourseactivity-update.md
> +**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is set to `true`. Please use the [Update learningProvider API](../api/learningprovider-update.m
```suggestion
**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is set to `true`. To update the value, use the [Update learningProvider API](../api/learningprovider-update.md) method.
```

2023-06-05 15:19 UTC, Danielabom commented on changelog/Microsoft.Viva.Learning.json
> +          "Description": "Added the **isCourseActivitySyncEnabled** property to [learningProvider](https://learn.microsoft.com/en-us/graph/api/resources/learningProvider?view=graph-rest-1.0) resource
```suggestion
          "Description": "Added the **isCourseActivitySyncEnabled** property to the [learningProvider](https://learn.microsoft.com/en-us/graph/api/resources/learningProvider?view=graph-rest-1.0) resource.",
```

2023-06-05 15:19 UTC, Danielabom commented on changelog/Microsoft.Viva.Learning.json
> +          "Description": "Added the **isCourseActivitySyncEnabled** property to [learningProvider](https://learn.microsoft.com/en-us/graph/api/resources/learningProvider?view=graph-rest-beta) resourc
```suggestion
          "Description": "Added the **isCourseActivitySyncEnabled** property to the [learningProvider](https://learn.microsoft.com/en-us/graph/api/resources/learningProvider?view=graph-rest-beta) resource.",
```

2023-06-05 19:32 UTC, Lauragra commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +**Note**: Learning course activities can be managed by a provider only when isCourseAcitvitySyncEnabled is set to `true`.  To update the value, use the [Update learningProvider API](../api/learningpr
Global: Please format the notes as a note by adding the > symbold. Please apply bold formatting to the property name, and remove API from the link text.

2023-06-06 03:43 UTC, Lauragra commented on api-reference/beta/api/employeeexperience-post-learningproviders.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether a provider can ingest [learningCourseActivity](../resources/learningcourseactivity.md) records. The default value is `false`. Set to true to mak
Please format the word true as a value: `true`

2023-06-06 15:06 UTC, Danielabom commented on api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
> +>[!Note]
```suggestion
> [!Note]
```

2023-06-06 15:16 UTC, Danielabom commented on api-reference/beta/api/learningcourseactivity-delete.md
> +>**Note**: Learning course activities can be managed by a provider only when `isCourseAcitvitySyncEnabled` is set to `true`. To update the value, use the [Update learningProvider](../api/learningprov
```suggestion
>**Note**: Learning course activities can be managed by a provider only when **isCourseAcitvitySyncEnabled** is set to `true`. To update the value, use the [Update learningProvider](../api/learningprovider-update.md) method.
```

2023-06-06 15:18 UTC, Danielabom commented on api-reference/beta/resources/learningcourseactivity.md
> +>**Note**: A provider can ingest course activities when `isCourseAcitvitySyncEnabled` is set to `true`. To update the value, use the [Update learningProvider](../api/learningprovider-update.md) metho
```suggestion
>**Note**: A provider can ingest course activities when **isCourseAcitvitySyncEnabled** is set to `true`. To update the value, use the [Update learningProvider](../api/learningprovider-update.md) method.  
```

2023-06-07 13:54 UTC, Danielabom commented on api-reference/beta/api/employeeexperience-post-learningproviders.md
> +|isCourseActivitySyncEnabled|Boolean|Indicates whether a provider can ingest [learningCourseActivity](../resources/learningcourseactivity.md) records. The default value is `false`. Set to true to mak
Updated by author. Thanks.

2023-06-08 02:35 UTC, merged