Adding assign and extract sensitivity label files
microsoftgraph/microsoft-graph-docs pull request #21472
Opened 2023-05-30 10:51 UTC by abhishek-microsoft-2021

Our team is planning to expose v1.0 of set labels api which will allow users to assign and extract sensitivity label on a given drive item.
This PR will document the API and resources associated with the APIs.

2023-06-02 18:49 UTC, jaLuthra requested changes
validate and fix url redirections and other url path related comments

2023-06-02 18:49 UTC, jaLuthra commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +For more information about sensitivity labels from an administrator's perspective, see [Enable sensitivity labels for Office files in SharePoint and OneDrive](/microsoft-365/compliance/sensitivity-la
this url is broken, also verify all other relative urls.
Use branch selector in microsoft graph api viewer similar to this url:
https://review.learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?branch=kumarabhis-migrate-beta-docs-v1-setlabelsapi&view=graph-rest-1.0&tabs=http
to validate post deployment url redirections

2023-06-02 18:49 UTC, jaLuthra commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +POST /users/{user-id}/drive/root:/{item-path}/assignSensitivityLabel
item-path url should succeed with ':/' instead '/' as in  https://github.com/microsoftgraph/microsoft-graph-docs/blob/a2a77371fa29175c0b1cfc917bdfb522c0e52997/api-reference/v1.0/api/range-merge.md#L28
Also, please add that change in all other api docs in this PR and the beta documents as well

2023-06-02 18:49 UTC, jaLuthra commented on api-reference/v1.0/resources/driveitem.md
> +| [Extract sensitivity labels](../api/driveitem-extractsensitivitylabels.md)   | `POST /drive/items/{item-id}/extractSensitivityLabels`                 |
nit: allign '|' for better readability

2023-06-02 18:49 UTC, jaLuthra commented on api-reference/v1.0/resources/driveitem.md
> +| [Assign sensitivity label](../api/driveitem-assignsensitivitylabel.md)       | `POST /drive/items/{item-id}/assignSensitivityLabel`                   |
add brief description as well

2023-06-02 18:49 UTC, jaLuthra commented on api-reference/v1.0/resources/extractsensitivitylabelsresult.md
> +Represents the response format for the [extractSensitivityLabels](../api/driveitem-extractsensitivitylabels.md) API.
validate all relative urls starting with ../ as well

2023-06-02 18:56 UTC, jaLuthra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [assignSensitivityLabel](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-1.0) method to the [driveItem](https://learn.microsoft.com/en-us/gra
url for assignsensitivity label method is wrong, the url should be: https://review.learn.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-1.0&tabs=http

2023-06-02 18:57 UTC, jaLuthra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [extractSensitivityLabels](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-1.0) method to the [driveItem](https://learn.microsoft.com/en-us/g
fix url similar to assignSensitivityLabel API

2023-06-05 05:43 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +POST /users/{user-id}/drive/root:/{item-path}/assignSensitivityLabel
done

2023-06-05 05:55 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/resources/driveitem.md
> +| [Extract sensitivity labels](../api/driveitem-extractsensitivitylabels.md)   | `POST /drive/items/{item-id}/extractSensitivityLabels`                 |
done

2023-06-05 05:56 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/resources/driveitem.md
> +| [Assign sensitivity label](../api/driveitem-assignsensitivitylabel.md)       | `POST /drive/items/{item-id}/assignSensitivityLabel`                   |
Added.

2023-06-05 06:10 UTC, abhishek-microsoft-2021 commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [assignSensitivityLabel](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-1.0) method to the [driveItem](https://learn.microsoft.com/en-us/gra
I was thinking to do the same. Done.

2023-06-05 06:10 UTC, abhishek-microsoft-2021 commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [extractSensitivityLabels](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-1.0) method to the [driveItem](https://learn.microsoft.com/en-us/g
Done.

2023-06-05 09:29 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/resources/extractsensitivitylabelsresult.md
> +Represents the response format for the [extractSensitivityLabels](../api/driveitem-extractsensitivitylabels.md) API.
All seems good.

2023-06-05 09:46 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +For more information about sensitivity labels from an administrator's perspective, see [Enable sensitivity labels for Office files in SharePoint and OneDrive](/microsoft-365/compliance/sensitivity-la
Added.

2023-06-05 14:11 UTC, jaLuthra approved these changes

2023-06-16 01:09 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# [HTTP](#tab/http)
Please remove this line.

2023-06-16 01:11 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# driveItem: assignSensitivityLabel
Is there a charge for this API now that it's going to v1.0? Note that this topic mentions that it's a metered API, but there are no charges while it's in beta: https://learn.microsoft.com/en-us/graph/metered-api-list. Please check the concept topics and update as appropriate. Also, if it is metered, we should have a note with a link to where they can find the payment information. For example, see this metered API topic: https://learn.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&tabs=http.

2023-06-16 01:12 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-extractsensitivitylabels.md
> +# [HTTP](#tab/http)
Delete this line.

2023-06-16 11:39 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-extractsensitivitylabels.md
> +# [HTTP](#tab/http)
done

2023-06-16 11:40 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# [HTTP](#tab/http)
Deleted this line.

2023-06-16 11:41 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# driveItem: assignSensitivityLabel
There is no changes in the api specifications from beta and v1.0 and we have added the note with a link in this file at Line no 19 below.

2023-06-16 11:42 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +> This is a metered API and some charges for use may apply. For details, see [Overview of metered Microsoft 365 APIs in Microsoft Graph](/graph/metered-api-overview).
@Lauragra here is a note with a link to payment information.

2023-06-17 02:14 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# driveItem: assignSensitivityLabel
Okay, so since this API is no longer in preview, do you want to change this text:
<img width="439" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/8648854/23b94920-39dd-4af3-9e29-6cb28067384a">

To say "No charge for this API." (removing the in preview part because it's no longer in preview.)

If so, then, I wonder if we do want or need a note about metering this API, since it sounds like we actually aren't charging for it... ?

2023-06-17 02:14 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +> This is a metered API and some charges for use may apply. For details, see [Overview of metered Microsoft 365 APIs in Microsoft Graph](/graph/metered-api-overview).
Great. Let's only keep this if we think there will be charges for use now that the API is in v1.0.

2023-06-20 03:48 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +> This is a metered API and some charges for use may apply. For details, see [Overview of metered Microsoft 365 APIs in Microsoft Graph](/graph/metered-api-overview).
It's a first paid API exposed by Microsoft. There will be charge for it.

2023-06-20 03:52 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# driveItem: assignSensitivityLabel
@Lauragra this will paid API and we need to keep a note about metering.

2023-06-21 01:33 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# driveItem: assignSensitivityLabel
To be clear. publishing this PR does mean that the API is GA. So, I'm trying to clarify whether there will be a charge for it now that it's GA, and make sure that we update the related docs accordingly. I'm not sure what you mean by PayG. In short, do you want to still say in the metered API docs that there is no charge for this API, even though it is no longer in preview?

2023-06-21 20:04 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# driveItem: assignSensitivityLabel
PayG stands for Pay as you Go as charges incurred while calling this API will depend on its usage. I have modified the text to SharePoint Online premium API.

2023-06-21 20:24 UTC, abhishek-microsoft-2021 commented
@Lauragra The schema PR for v1 API has already been merged and its very important for this PR to get completed. We are time bound to announce GA, all your comments are addressed. Please help review

2023-06-21 23:03 UTC, JeremyKelley commented on concepts/metered-api-list.md
> +| SharePoint and OneDrive for Business [assignSensitivityLabel](/graph/api/driveitem-assignsensitivitylabel) | SharePoint Online premium API | [SharePoint preview enrollment form](https://aka.ms/Prev
This seems to conflict with the change submitted in the PR here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/21624

Can we verify the right content?

2023-06-22 04:52 UTC, abhishek-microsoft-2021 commented on concepts/metered-api-list.md
> +| SharePoint and OneDrive for Business [assignSensitivityLabel](/graph/api/driveitem-assignsensitivitylabel) | SharePoint Online premium API | [SharePoint preview enrollment form](https://aka.ms/Prev
@JeremyKelley I was unaware of the change in the above mentioned PR. I have reverted back my changes.

2023-06-22 04:53 UTC, abhishek-microsoft-2021 commented on api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
> +# driveItem: assignSensitivityLabel
This is taken care in https://github.com/microsoftgraph/microsoft-graph-docs/pull/21624.

2023-06-22 04:54 UTC, abhishek-microsoft-2021 commented
@Lauragra The change in PR:-  https://github.com/microsoftgraph/microsoft-graph-docs/pull/21624 is more correct. I have reverted back my change.

2023-06-23 01:04 UTC, Lauragra approved these changes

2023-06-23 06:10 UTC, abhishek-microsoft-2021 commented
@Lauragra  PR :- https://github.com/microsoftgraph/microsoft-graph-docs/pull/21624 has been merged. Can we merge this PR?.

2023-06-23 23:05 UTC, merged