Promote LCW Beta to v1.0
microsoftgraph/microsoft-graph-docs pull request #21480
Opened 2023-05-30 18:27 UTC by OWinfreyATL

2023-06-12 17:14 UTC, msewaweru requested changes
@OWinfreyATL - thanks for the work on this PR. I have completed the first review with a few issues for you to address.

- Please add Changelog for this PR.
- Review the suggestions I have added.

2023-06-13 16:14 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-workflowversion.md
> +|[List userProcessingResults](../api/identitygovernance-workflow-list-userprocessingresults.md)|[microsoft.graph.identityGovernance.userProcessingResult](../resources/identitygovernance-userprocessin
Removed useprocessingresults to match TOC. Replaced with "Get Tasks"

2023-06-14 01:46 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-taskprocessingresult.md
> +|[resume](../api/identitygovernance-taskprocessingresult-resume.md)|None|Resumes the **taskProcessingResult** as part of the Azure Logic App integration.|
Confirmed with product team that we only support resume with this resource. Engineering will have to update the API to show this.

2023-06-14 01:47 UTC, OWinfreyATL commented on api-reference/v1.0/resources/identitygovernance-task.md
> +|[Update task](../api/identitygovernance-task-update.md)|[microsoft.graph.identityGovernance.task](../resources/identitygovernance-task.md)|update the properties of a [task](../resources/identitygove
Confirmed with Product team that Patch is supported. Engineering will have to update the API.md to reflect this.

2023-06-14 16:52 UTC, msewaweru requested changes
@OWinfreyATL - a minor change that was an oversight in my first review. I'm yet to conclude on the change log review.

2023-06-15 15:58 UTC, msewaweru approved these changes
@OWinfreyATL - LGTM! Thank you.

2023-06-23 23:07 UTC, Lauragra commented on api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-post-workflows.md
> +POST https://graph.microsoft.com/v1.0/identityGovernance/lifecycleWorkflows/workflows
Global: For topics in the /beta folder, the request examples should use the /beta URL, not v1.0 (even if the API is GA/available in the v1.0 folder). Please revert these changes in the beta topics.

2023-06-23 23:08 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-customtaskextension-delete.md
> +Delete a [customTaskExtension](../resources/identitygovernance-customtaskextension.md) object. Can only be deleted if it is not referenced in any task objects in a lifecycle workflow.
For clarity, please add a subject to the second sentence. For example, "A custom task extension can only be deleted if...".

2023-06-23 23:10 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-customtaskextension-get.md
> +The following is an example of the response
Global: Please make sure that this boilerplate text ends with a period.

2023-06-23 23:15 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-lifecycleworkflowscontainer-list-deleteditems.md
> +Namespace: microsoft.graph
Are all of these APIs in the identityGovernance subnamespace? If so, please make sure that the namspace line and return type references are consistent throughout. For details, See this CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace

2023-06-23 23:45 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-lifecycleworkflowscontainer-list-workflows.md
> +Get the workflow resources from the workflows navigation property.
I would be good if we can improve this description as this boilerplate construction is not meaningful to readers. For example: "Get a list of the workflow resources that are associated with a lifecycle workflow."

2023-06-24 00:31 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-run-summary.md
> +A summary of runs for a specified time period. Since the amount of runs returned by the List API call can be overwhelming, this summary allows the administrator to get a quick overview based on count
This should start with a verb. Suggested revision: "Get a summary of runs for a specified time period. Because the number runs returned by the List API call can be overwhelming, this summary allows the administrator to get a quick overview based on counts."

Also, please link to the List API.

2023-06-24 00:32 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-run-summary.md
> +description: "A summary of runs for a specified time period. Since the amount of runs returned by the List API call can be overwhelming, this summary allows the administrator to get a quick overview
Please add the verb here too and remove the second sentence.

2023-06-24 00:33 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-task-get.md
> +Get a task specific from a [workflow](../resources/identitygovernance-workflow.md) or [workflowVersion](../resources/identitygovernance-workflowversion.md).
Did you mean to say "Get a specific task from... " here?

2023-06-24 00:37 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-taskprocessingresult-resume.md
> +Resume a task processing result that's `inProgress`. In the default case an Azure Logic Apps system-assigned managed identity calls this API. For more information read about [Lifecycle Workflows exte
Change the last sentence to read: "For more information, see...".

2023-06-24 00:39 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-taskreport-summary.md
> +This API provides a summary of task processing results for a specified time period. Because the volume of task processing results and task reports returned by the List API calls can be overwhelming,
Add a link to the List API topic here, if possible.

2023-06-24 00:40 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-taskreport-summary.md
> +description: "A summary of task processing results for a specified time period. Since the amount of task processing results and task reports returned by the List API calls can be overwhelming, this s
Just use the firs sentence for the description, and add the verb "Get".

2023-06-24 00:46 UTC, Lauragra commented on api-reference/v1.0/api/identitygovernance-workflow-activate.md
> +description: "Run a workflow on-demand for time critical execution and testing."
Revise the description here: "Run a workflow object on demand."

2023-06-26 19:12 UTC, OWinfreyATL commented on api-reference/v1.0/api/identitygovernance-lifecycleworkflowscontainer-list-deleteditems.md
> +Namespace: microsoft.graph
This references deleteditemcontainer resource and uses the microsoft.graph namespace

2023-06-27 01:54 UTC, Lauragra commented on api-reference/beta/api/workflow-list-executionscope.md
> +GET https://graph.microsoft.com/v1.0/identitygovernance/lifecycleWorkflows/workflows/8696088c-1aef-4f65-afe9-acd55343e327/executionScope
We need to back out this change; this is a beta topic so should have beta in the URL.

2023-06-27 01:55 UTC, Lauragra commented on api-reference/beta/api/workflow-list-executionscope.md
> +### Example: Retrieve the users that fall in scope of a workflow
We don't need the extra H3 in the case where there's only one example in the topic; just remove this heading and make the Request and Response headings H3s.

2023-06-27 02:19 UTC, merged