Add all available retrievable properties in search for chatMessage
microsoftgraph/microsoft-graph-docs pull request #21498
Opened 2023-06-01 09:40 UTC by yiwenwang-ms

Add all available retrievable properties in search for chatMessage

2023-06-01 12:58 UTC, njerigrevious requested changes
Let's update the language before finalizing. Thanks!

2023-06-01 12:58 UTC, njerigrevious commented on concepts/search-concept-chat-messages.md
> +The following is a JSON representation of all retrievable properties in search to [chatMessage](/graph/api/resources/chatmessage)
Please update to "The following is a JSON representation of all retrievable properties currently available for [chatMessage] (/graph/api/resources/chatmessage) search"

2023-06-01 14:15 UTC, njerigrevious requested changes
Add last minor punctuation change and then you can merge. Thanks!

2023-06-01 19:03 UTC, dodaromike approved these changes

2023-06-05 02:02 UTC, yiwenwang-ms commented on concepts/search-concept-chat-messages.md
> +The following is a JSON representation of all retrievable properties currently available for [chatMessage] (/graph/api/resources/chatmessage) search
Done.

2023-06-06 03:47 UTC, merged