Add deprecation notification for externalitem legacy
microsoftgraph/microsoft-graph-docs pull request #21512
Opened 2023-06-02 07:23 UTC by ZChristine

Add deprecation notification for externalitem legacy and update the odatatype to use the new namespace for externalItem

2023-06-02 08:08 UTC, njerigrevious requested changes
Some minor phrasing changes - let me know if any questions.

2023-06-07 03:29 UTC, njerigrevious approved these changes
Thanks for making the changes - all set!

2023-06-07 15:13 UTC, njerigrevious approved these changes
Approved - thanks!

2023-06-13 17:32 UTC, Danielabom requested changes
@ZChristine, I've made some changes. But, I would like to know if we are missing info. Please review this link to ensure we comply with our deprecation guidelines. Here's the link: [Deprecate docs](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211775/Deprecate-docs)

2023-06-14 23:36 UTC, njerigrevious approved these changes
Changes look good - just approved!

2023-06-28 02:21 UTC, Danielabom commented
@ZChristine, following up on this PR. Please look at my last comment. thanks.

2023-07-26 05:57 UTC, ZChristine commented
> The deprecation of externalitem legacy which has the legacy name space "microsoft.graph" has been announced deprecation in [CSDL change](https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads?path=/Workloads/Microsoft.SubstrateConnectors/override/schema-Prod-beta.csdl&version=GBmaster&line=395&lineEnd=396&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) since 2021-08-01

hi, @Danielabom . the deprecation of externalitem legacy which has the legacy name space "microsoft.graph" has been announced deprecation in [CSDL change](https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads?path=/Workloads/Microsoft.SubstrateConnectors/override/schema-Prod-beta.csdl&version=GBmaster&line=395&lineEnd=396&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) since 2021-08-01. seems nothing missing in https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211775/Deprecate-docs

2023-07-26 20:34 UTC, Danielabom commented on api-reference/beta/resources/search-api-overview.md
> +Starting from August 31, 2023, the [externalItem resource](./externalconnectors-externalitem.md) resource within the Microsoft Graph namespace will be deprecated in the beta version of the API.  It w
```suggestion
Starting from August 31, 2023, the [externalItem resource](./externalconnectors-externalitem.md) resource within the Microsoft Graph namespace will be deprecated in the beta version of the API.  Instead, it will be replaced by the new namespace **Microsoft.Graph.ExternalConnectors**.  o avoid any errors after the deprecation, make sure that you update any namespace dependencies in the beta version before the specified date. Alternatively, you may consider transitioning to the v1 version of the API.
```

2023-07-26 20:35 UTC, Danielabom approved these changes
Thank you for working on this PR, @ZChristine. PR approved.

2023-07-28 03:40 UTC, Lauragra commented on api-reference/beta/resources/search-api-overview.md
> +Starting from August 31, 2023, the [externalItem resource](./externalconnectors-externalitem.md) resource within the Microsoft Graph namespace will be deprecated in the beta version of the API.  Inst
Please revise as:
Effective August 31, 2023, the beta version of the [externalItem](./externalconnectors-externalitem.md) resource in the Microsoft Graph namespace will be deprecated.  Going forward, use the version of the resource in the **Microsoft.Graph.ExternalConnectors** namespace.  Make sure that you update any namespace dependencies before the specified date. Alternatively, consider transitioning to the v1.0 version of the API.

2023-07-28 03:49 UTC, Lauragra commented on api-reference/beta/resources/search-api-overview.md
> +Starting from August 31, 2023, the [externalItem resource](./externalconnectors-externalitem.md) resource within the Microsoft Graph namespace will be deprecated in the beta version of the API.  Inst
It looks like we only have a resource topic for the externalItem resource in the subnamespace. This is confusing to readers because we are saying that the resource in the global namespace is deprecated starting at the end of August. So, we should still have a topic for the externalItem resource in the global namespace, which would be marked as deprecated on August 31, until it gets removed. Otherwise, why are we announcing a deprecation at all, instead of introducing this as a breaking change?

2023-07-31 02:18 UTC, ZChristine commented on api-reference/beta/resources/search-api-overview.md
> +Starting from August 31, 2023, the [externalItem resource](./externalconnectors-externalitem.md) resource within the Microsoft Graph namespace will be deprecated in the beta version of the API.  Inst
hi, @Lauragra . We use namespace for locating for a resource that owned by the resource owner team. And the externalItem has been announced as deprecation and they have new externalItem resource which is similar to origin externalItem resource but has different namespace. And our documentation aims to preannounced the deprecation and we will change the namespace to locate the new resource to align with the change from resourced owner team. 
Could you help merge the PR?

2023-07-31 16:24 UTC, Lauragra commented on api-reference/beta/resources/search-api-overview.md
> +(1)Effective August 31, 2023, the beta version of the [externalItem resource](./externalconnectors-externalitem.md) resource  in the Microsoft Graph namespace will be deprecated. Going forward, use t
My original comment here hasn't been fully addressed. We currently have two versions of the externalItem resource type defined in the metadata - one in the global namespace and one in the subnamespace. When we announce a deprecation, we should update the topic to reflect that it's deprecated. In the case of a move to a subnamespace, we need to have two topics for the resource until the deprecated resource is removed from the global namespace. For details, see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211775/Deprecate-docs?anchor=deprecate-content-for-a-resource

2023-07-31 23:44 UTC, ZChristine commented on api-reference/beta/resources/search-api-overview.md
> +(1)Effective August 31, 2023, the beta version of the [externalItem resource](./externalconnectors-externalitem.md) resource  in the Microsoft Graph namespace will be deprecated. Going forward, use t
Hi, @Lauragra . The legacy externalItem  resource has been already removed from the resource owner team in the doc. check https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem?view=graph-rest-beta. The namespace is updated to use the new subnamespace.

2023-08-01 00:31 UTC, Lauragra approved these changes

2023-08-01 02:21 UTC, merged