Adding SLA attainment
microsoftgraph/microsoft-graph-docs pull request #21538
Opened 2023-06-06 00:25 UTC by besiler

Adding new SLA attainment API and resources

2023-07-04 09:20 UTC, msewaweru requested changes
@besiler - Completed an initial review of the PR. Please review the comments and address. Thanks.

2023-07-04 09:20 UTC, msewaweru commented on api-reference/beta/api/azureadauthentication-get.md
> ++ Global Administrator
Consider removing the Global Admin role from the docs. There is a team initiative to stop using it if there are lesser privileged roles.

2023-07-04 09:20 UTC, msewaweru commented on changelog/Microsoft.AAD.Reporting.json
> +        },
This change has not been captured in this PR. Please add it.

2023-07-05 17:37 UTC, jamesw-msft commented on api-reference/beta/resources/azureadauthentication.md
> +|[Get azureADAuthentication](../api/azureadauthentication-get.md)|[azureADAuthentication](../resources/azureadauthentication.md)|Read the properties and relationships of an [azureADAuthentication](..
It is just get, the "list" is because it contains a property with a list. We only support this single API interaction right now, so makes sense to me it's only GET.

2023-07-05 17:40 UTC, jamesw-msft commented on api-reference/beta/resources/azureadauthentication.md
> +Inherits from [entity](../resources/entity.md).
I confirm it's the navigation property from parent "sla". Here is the CSDL: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/8302398?_a=files&path=/Workloads/Microsoft.AAD.Reporting/override/schema-Prod-beta.csdl

2023-07-05 17:43 UTC, jamesw-msft commented on api-reference/beta/api/azureadauthentication-get.md
> ++ Global Administrator
I copied this pattern from signins: https://learn.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http

The permissions check is the same. We don't require global administrator to view, it just lists the roles which can view it, since global admin can do all it is shown.

2023-07-05 17:46 UTC, jamesw-msft commented on api-reference/beta/resources/servicelevelagreementroot.md
> +Inherits from [entity](../resources/entity.md).
I confirm it's the "sla" navigation property under reports. You can see it in the CSDL checkin: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/8302398?_a=files&path=/Workloads/Microsoft.AAD.Reporting/override/schema-Prod-beta.csdl

2023-07-06 08:16 UTC, msewaweru commented on changelog/Microsoft.AAD.Reporting.json
> +        },
@jamesw-msft - Yes. I meant the change is in the CSDL but not part of the PR. I can't find the additional relationship in the reportRoot resource. Also change the ApiChange to relationship instead of resource.

2023-07-06 08:22 UTC, msewaweru requested changes
@jamesw-msft - Just one issue pending. On the changelog, I meant the change is in the CSDL but not part of the PR. I can't find the additional relationship in the reportRoot resource. Also change the ApiChange to relationship instead of resource.

2023-07-07 10:28 UTC, msewaweru approved these changes
LGTM. Thanks, @jamesw-msft.

2023-07-07 17:21 UTC, jamesw-msft commented
#sign-off

2023-07-08 00:54 UTC, merged