docs: update mgt-todo documentation
microsoftgraph/microsoft-graph-docs pull request #21549
Opened 2023-06-06 12:58 UTC by Mnickii

Closes https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/2096

2023-06-06 18:02 UTC, Danielabom commented on concepts/toolkit/components/todo.md
> +The control exposes the following variables that can be localized. See how you setup localization [here](../customize-components/localization.md).
```suggestion
The control exposes the following variables that can be localized. For more information, see [setup localization](../customize-components/localization.md).
```

2023-06-06 18:49 UTC, Danielabom commented on concepts/toolkit/components/todo.md
> +
@musale Is this the valid format for default values? Why do you want to keep them in quotes?

2023-06-06 18:50 UTC, Danielabom requested changes
@musale, please review my comments. Thanks!

2023-06-07 06:38 UTC, Mnickii commented on concepts/toolkit/components/todo.md
> +
Yes, this is the valid format for the default values, should be a back-tick though.

2023-06-07 16:55 UTC, Danielabom approved these changes
PR approved. Thanks

2023-06-08 15:25 UTC, Danielabom commented
@Mnickii, please add the "ready to merge" label as soon as you want to publish the content.

2023-06-13 02:13 UTC, merged