[Doc Feature][Call recording API][3099832]
microsoftgraph/microsoft-graph-docs pull request #21546
Opened 2023-06-06 12:38 UTC by v-sdhakshina

2023-06-13 14:13 UTC, devjha-ms reviewed
Changes looks good, few comments.

2023-06-14 11:58 UTC, devjha-ms commented on api-reference/beta/api/callrecording-get.md
> +```
remove this extra http code.

2023-06-14 12:01 UTC, devjha-ms commented
Looks good

2023-06-14 12:08 UTC, devjha-ms approved these changes
Looks good.

2023-06-14 16:35 UTC, v-sdhakshina commented on api-reference/beta/api/onlinemeeting-list-recordings.md
> +|Delegated (work or school account) | OnlineMeetingRecording.Read.All |
updated as suggested

2023-06-14 16:36 UTC, v-sdhakshina commented on api-reference/beta/api/callrecording-get.md
> +<v User Name>This is a recording test.</v>
Updated as suggested

2023-06-14 16:37 UTC, v-sdhakshina commented on api-reference/beta/api/callrecording-get.md
> +```
As discussed with Devi, kept this tag as it is. Content reviewer needs to provide input for this.

2023-06-15 08:57 UTC, ayan-ms commented on api-reference/beta/api/onlinemeeting-list-recordings.md
> +```
Seems few forward slashes are missing here. It should be /me/onlineMeetings**/{meetingId}/**recordings. Similarly /users**/{userId}/**onlineMeetings...

2023-06-15 09:53 UTC, ayan-ms commented on api-reference/beta/api/onlinemeeting-list-recordings.md
> +> - This API works differently in one or more national clouds. For details, see [Implementation differences in national clouds](/graph/teamwork-national-cloud-differences).
Please add a section in page [Implementation differences in national clouds] (https://review.learn.microsoft.com/en-us/graph/teamwork-national-cloud-differences?branch=pr-en-us-21546) stating that "Meeting recording APIs are not supported" with content same as section for transcripts with minor changes linking to recording pages.

2023-06-15 09:58 UTC, ayan-ms requested changes
Reviewed this PR

2023-07-11 07:31 UTC, v-sdhakshina commented
Closing this PR as it has added too many files.

2023-07-11 07:31 UTC, closed without merging