docs: Adding search components
microsoftgraph/microsoft-graph-docs pull request #21555
Opened 2023-06-06 16:53 UTC by sebastienlevert

Closes https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/2352

2023-06-06 17:58 UTC, musale commented on concepts/toolkit/components/includes/preview-disclaimer.md
> +> This component is marked as `Preview` and is subject to change. The use of these components in production applications is not supported.
```suggestion
> This component is marked as `Preview` and is subject to change. The use of these components in production applications is not advised.
```

Are they not usable in production or advised against?

2023-06-06 18:05 UTC, sebastienlevert commented on concepts/toolkit/components/includes/preview-disclaimer.md
> +> This component is marked as `Preview` and is subject to change. The use of these components in production applications is not supported.
I've been using the same wording than the beta endpoint... I would say they are not supported in production at this point. Like beta endpoints.

2023-06-14 16:49 UTC, gavinbarron requested changes

2023-06-14 16:49 UTC, gavinbarron commented on concepts/toolkit/components/search-results.md
> +| entity-types              | entityTypes             | One or more types of resources expected in the response. Possible values are: list, site, listItem, message, event, drive, driveItem, person, e
Do we want to document the default values here?

2023-06-14 16:49 UTC, gavinbarron commented on concepts/toolkit/components/search-results.md
> +| max-pages                 | maxPages                | Optional number of pages (for resources that support paging). Default is 3. Setting this value to 0 will get all pages.
I'm not seeing this attribute or property in the mgt-search-results

2023-06-14 16:49 UTC, gavinbarron commented on concepts/toolkit/components/search-results.md
> +| cache-invalidation-period | cacheInvalidationPeriod | Optional number of milliseconds. When set in combination with `cacheEnabled`, the delay before the cache reaches its invalidation period will b
default is 30000 according to the code

2023-06-14 16:49 UTC, gavinbarron commented on concepts/toolkit/components/search-results.md
> +| default   | The response from Microsoft Graph.        | The default template is required to render the data coming from Microsoft Graph.
This is confusing IMO. 

AFAIK a default template is not required, but provides a catch all single renderer for all result-types when provided. 

A developer could choose to provide a single result-type template and have the search work correctly.

2023-06-14 16:49 UTC, gavinbarron commented on concepts/toolkit/components/search-results.md
> +Permissions required by this component depend on the data that you want to retrieve with it from Microsoft Graph. For more information about permissions, see Microsoft Graph [permissions reference](.
can we be more specific here given this is search and not the generic get component?

2023-06-14 16:49 UTC, gavinbarron commented on concepts/toolkit/components/search-results.md
> +> For more information about the data returned in the `response` property see the API reference of the API that you used in the `resource` property of the Get component.
There is no resource property on the search results

2023-06-15 02:44 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Preview
A more standard approach here would be to just include the components in the TOC with preview in parentheses after it, and not include them in a separate node, which adds a layer to the TOC and makes the content less discoverable. Like this:
Search box (preview)
Search results (preview)

Also, can we alphabetize the components in the TOC for easier scanning?

2023-06-15 02:48 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Notifications for cloud printing
Not sure why these changes are here and if they're necessary.

2023-06-15 02:50 UTC, Lauragra commented on concepts/toolkit/components/includes/preview-disclaimer.md
> +> This component is marked as `Preview` and is subject to change. The use of these components in production applications is not supported.
It would be more clear to simply state that the component is IN preview, not marked as preview. Suggested revision:
"This component is currently in preview and is subject to change. The use of this component in production applications is not supported."

2023-06-15 02:51 UTC, Lauragra commented on concepts/toolkit/components/search-box.md
> +[!INCLUDE [preview-disclaimer](./includes/preview-disclaimer.md)]
Global: I recommend placing the preview disclaimer above the summary so that readers see it first when reading the topic. This placement is consistent with the disclaimer in the beta reference topics.

2023-06-15 02:51 UTC, Lauragra commented on concepts/toolkit/components/search-box.md
> +| debounce-delay | debounceDelay | Debounce delay of the search input. Default is `300`         |
Please add a period to the description.

2023-06-15 02:52 UTC, Lauragra commented on concepts/toolkit/components/search-box.md
> +| placeholder | 'Search'      |
The values here should be styled with tick marks ` instead of apostrophes.

2023-06-15 02:53 UTC, Lauragra commented on concepts/toolkit/components/search-results.md
> +| content-sources           | contentSources          | Content sources to use with External Items.
Why is External Items capitalized here? That's not a proper noun.

2023-06-15 02:53 UTC, Lauragra commented on concepts/toolkit/components/search-results.md
> +| enable-top-results        | enableTopResults        | This triggers hybrid sort for messages : the first 3 messages are the most relevant. This property is only applicable to `entityType=message`.
There's an extra space after the colon here.

2023-06-15 02:55 UTC, Lauragra commented on concepts/toolkit/components/search-box.md
> +The control exposes the following variables that can be localized. See how you setup localization [here](../customize-components/localization.md).
Global: The second sentence here needs to be fixed in every topic to conform to Microsoft style:
For details about how to set up localization, see [Localizing components](../customize-components/localization.md).

2023-06-16 13:51 UTC, sebastienlevert commented on concepts/toc.yml
> +              - name: Notifications for cloud printing
They are not required and I don't know why they were affected.

2023-06-19 14:18 UTC, gavinbarron approved these changes
LGTM

2023-06-20 01:31 UTC, merged

2023-06-20 01:54 UTC, sebastienlevert commented
Thanks @Lauragra!