Meaedle/personal scope rsc documentation
microsoftgraph/microsoft-graph-docs pull request #21559
Opened 2023-06-06 19:09 UTC by mehakagarwal

Update documents for :- 
1) Add New TeamsAppSetting FF 
2) Add new User /permissionGrants API
3) Update document for new Set of Permissions TeamsAppInstallConsentFor*User.

2023-06-07 17:46 UTC, eddie-lee-msft commented
@mehakagarwal there are several things in this PR to note to start:

1. You need to add the new 'TeamsActivity.Send.User' RSC permission in this document: 'https://learn.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&tabs=http' and this 'https://learn.microsoft.com/en-us/graph/api/teamwork-sendactivitynotificationtorecipients?view=graph-rest-beta&tabs=http'. See the chat equivalent API to see how it was done.
2. The changelog changes should be in the Microsoft.Teams.Core.json.

2023-06-07 19:43 UTC, eddie-lee-msft requested changes

2023-06-07 19:43 UTC, eddie-lee-msft commented on api-reference/beta/api/teamsappsettings-update.md
> +
no response on example 3?

2023-06-07 19:43 UTC, eddie-lee-msft commented on concepts/permissions-reference.md
> +| _TeamsAppInstallation.ReadWriteAndConsentSelfForUser_ | Allow the Teams app to manage itself and its permission grants on your user account| Allows a Teams app to read, install, upgrade, and uninst
are we missing adding 'ResourceSpecificPermissionGrant.ReadForUser' and 'ResourceSpecificPermissionGrant.ReadForUser.All'?

2023-06-07 19:43 UTC, eddie-lee-msft commented on concepts/permissions-reference.md
> +| _TeamsAppInstallation.ReadWriteAndConsentForUser.All_ | Manage installation and permission grants of Teams apps in a user account| Allows the app to read, install, upgrade, and uninstall Teams apps
Manage installation and permission grants of Teams apps in a user account -> Manage installation and permission grants of Teams apps in all user accounts ?

2023-06-07 19:47 UTC, eddie-lee-msft commented
@mehakagarwal , This is TBD, pending the question I asked Anand/Subhajit in the group chat, but we might need to make some changes in 'https://learn.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-beta&tabs=http' and 'https://learn.microsoft.com/en-us/graph/api/userteamwork-teamsappinstallation-upgrade?view=graph-rest-beta&tabs=http' to add these new permissions supported on that API:

- TeamsAppInstallation.ReadWriteAndConsentSelfForUser
- TeamsAppInstallation.ReadWriteAndConsentForUser
- TeamsAppInstallation.ReadWriteAndConsentSelfForUser.All
- TeamsAppInstallation.ReadWriteAndConsentForUser.All

As well as some detail about the 'consentedPermissionSet' param in the body as seen here 'https://learn.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&tabs=http'

2023-06-08 17:28 UTC, eddie-lee-msft commented
> @mehakagarwal , This is TBD, pending the question I asked Anand/Subhajit in the group chat, but we might need to make some changes in 'https://learn.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-beta&tabs=http' and 'https://learn.microsoft.com/en-us/graph/api/userteamwork-teamsappinstallation-upgrade?view=graph-rest-beta&tabs=http' to add these new permissions supported on that API:
> 
> * TeamsAppInstallation.ReadWriteAndConsentSelfForUser
> * TeamsAppInstallation.ReadWriteAndConsentForUser
> * TeamsAppInstallation.ReadWriteAndConsentSelfForUser.All
> * TeamsAppInstallation.ReadWriteAndConsentForUser.All
> 
> As well as some detail about the 'consentedPermissionSet' param in the body as seen here 'https://learn.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&tabs=http'

Confirmed from Sweta that these docs are good to update too.

2023-06-08 19:50 UTC, mehakagarwal commented on concepts/permissions-reference.md
> +| _TeamsAppInstallation.ReadWriteAndConsentSelfForUser_ | Allow the Teams app to manage itself and its permission grants on your user account| Allows a Teams app to read, install, upgrade, and uninst
confirmed with Subhajit, these permissions are still to be onboarded.

2023-06-08 19:59 UTC, mehakagarwal commented on api-reference/beta/api/teamsappsettings-update.md
> +
it's there in #193

2023-06-08 20:04 UTC, eddie-lee-msft commented on api-reference/beta/api/teamsappsettings-update.md
> +
I think the request is missing actually. Please check the doc preview, you will see there is something not right with this example.

2023-06-08 20:18 UTC, mehakagarwal commented on concepts/permissions-reference.md
> +| _TeamsAppInstallation.ReadWriteAndConsentSelfForUser_ | Allow the Teams app to manage itself and its permission grants on your user account| Allows a Teams app to read, install, upgrade, and uninst
adding ResourceSpecificPermissionGrant.ReadForUser*

2023-06-15 20:41 UTC, eddie-lee-msft commented
This is missing from the install / upgrade app pages

<img width="686" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/59708116/abbe0173-45b2-4385-aa43-4a36a5806223">

2023-06-15 20:42 UTC, eddie-lee-msft commented on api-reference/beta/api/teamwork-sendactivitynotificationtorecipients.md
> +>**Note:** Permissions marked with * use [resource-specific consent](/microsoftteams/platform/graph-api/rsc/resource-specific-consent).
Can you clarify in this note that the RSC permission pertains to the individual recipients in the payload?

2023-06-15 20:47 UTC, eddie-lee-msft commented
I think also upgrade installed app has missing changes in the v1 doc

2023-06-22 15:32 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +>**Note:** Permissions marked with * use [resource-specific consent](/microsoftteams/platform/graph-api/rsc/resource-specific-consent). These RSC permissions pertains to the individual recipients in
For this doc and the v1 equivalent only, let's remove the clause saying `These RSC permissions pertains to the individual recipients in the payload.`. It is implied in this API that the id of the user in the request URL is the recipient of the notification. We only needed it for the bulk API because 1) the recipients are in the payload and 2) there are many of them due to the bulk nature of the API.

2023-07-06 13:55 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +| _TeamsAppInstallation.ReadWriteAndConsentForUser.All_ | Manage installation and permission grants of Teams apps in a user account| Allows the app to read, install, upgrade, and uninstall Teams apps
Hi @mehakagarwal, I see that these permissions haven't been deployed yet. I can't see them in the Microsoft Graph service principal / Azure Active Directory. Please, let me know once the permissions have been deployed as this is a requirement for the PR publishing.

2023-07-06 14:44 UTC, eddie-lee-msft commented on concepts/permissions-reference.md
> +| _TeamsAppInstallation.ReadWriteAndConsentForUser.All_ | Manage installation and permission grants of Teams apps in a user account| Allows the app to read, install, upgrade, and uninstall Teams apps
Yup, they are pending final deployment to production. We will let you know when it is completed.

2023-07-10 03:55 UTC, JarbasHorst commented
Hello @mehakagarwal, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, please resolve the merge conflicts. Thanks!

2023-07-12 08:32 UTC, JarbasHorst commented
Hi @mehakagarwal, can you please share with me the workitem ID for your PR? Thanks!

2023-07-12 14:14 UTC, mehakagarwal commented
> Hi @mehakagarwal, can you please share with me the workitem ID for your PR? Thanks!

Hi @JarbasHorst here is the parent feature Id https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/2909023

2023-07-12 14:14 UTC, closed without merging

2023-07-12 16:19 UTC, eddie-lee-msft approved these changes

2023-07-12 16:20 UTC, mehakagarwal commented on api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
> +The request body should contain the catalog generated app ID for the app catalog. For details, see [teamsApp properties](../resources/teamsapp.md#properties).
Addressed

2023-07-12 16:20 UTC, mehakagarwal commented on api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
> +
Addressed

2023-07-12 16:30 UTC, mehakagarwal commented on api-reference/beta/api/userteamwork-post-installedapps.md
> -|teamsApp|String|The ID of the app to add.|
I kept the document in sync with https://learn.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&tabs=http#request-body  Here we are referring to additional parameter needed in request body. Keeping it as it is.

2023-07-21 04:53 UTC, JarbasHorst commented
Hello @mehakagarwal, the link you shared with me is related to a Microsoft Teams ADO instance, not Microsoft Graph, so, it doesn't have links to the artifacts as per the Microsoft Graph roadmap items. Can you please share with me a pointer to the CSDL and api.md files for your PR?

2023-07-21 15:17 UTC, mehakagarwal commented
> Hello @mehakagarwal, the link you shared with me is related to a Microsoft Teams ADO instance, not Microsoft Graph, so, it doesn't have links to the artifacts as per the Microsoft Graph roadmap items. Can you please share with me a pointer to the CSDL and api.md files for your PR?

@Jarbas-MSFT , here is the link to csdl P.R https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/8268663.

APi.md file : https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/14281?path=/reviews/10349-list-permissiongrants-of-user/api.md

2023-08-02 21:36 UTC, JarbasHorst commented
Hello @mehakagarwal, I checked your PR again and left two comments. Please, take a look when you will have time.

2023-08-04 15:27 UTC, mehakagarwal commented on api-reference/beta/api/userteamwork-post-installedapps.md
> -|teamsApp|String|The ID of the app to add.|
@JarbasHorst , I notice in line 45, it is already mentioned, what does the table describes for this additional Parameter in request body. 
Already we are stating this as additional parameter. 
**"The following table lists additional parameters that can be used with the request body."**

2023-08-04 16:00 UTC, mehakagarwal commented on api-reference/beta/api/userteamwork-post-installedapps.md
> -|teamsApp|String|The ID of the app to add.|
> The following table lists additional parameters that can be used with the request body

@JarbasHorst , I notice in line 45, it is already mentioned, what does the table describes for this additional Parameter in request body.
Already we are stating this as additional parameter. Keeping it as it is. Let me know if you still want me to update this.
"The following table lists additional parameters that can be used with the request body."