Update attachment-get.md
microsoftgraph/microsoft-graph-docs pull request #21573
Opened 2023-06-07 16:10 UTC by MSFT-AN

Due to a user request via ticket system. This note was added for the scenario of when getting an email attachment with a link to email attachment (*.pdf, *.doc, *.png) in HTTPS response output.

2023-06-07 16:48 UTC, Danielabom commented on api-reference/v1.0/api/attachment-get.md
> +> Depending on the requested files MIME type the byte stream output maybe in the response via link to email attachment.
```suggestion
> When certain files are requested, MIME can encode the byte stream output in the response and provide a link to download the file as an email attachment.
```

2023-06-07 16:48 UTC, Danielabom commented on api-reference/v1.0/api/attachment-get.md
> +> Depending on the requested files MIME type the byte stream output maybe in the response via link to email attachment.
@MSFT-AN, please review my suggestion.

2023-06-07 16:50 UTC, Danielabom requested changes
@MSFT-AN, please review my comments. Thanks!

2023-06-09 18:29 UTC, MSFT-AN reviewed
recommended changes approved.

2023-06-14 04:16 UTC, merged