resource files
microsoftgraph/microsoft-graph-docs pull request #21578
Opened 2023-06-08 05:56 UTC by bakerCaleb

resource files

2023-06-12 12:32 UTC, dkershaw10 commented
@FaithOmbongi Do we have a clear idea of where this is going in the TOC?  I guess this is part of the discussion with Angela...

2023-06-12 13:21 UTC, FaithOmbongi commented
> @FaithOmbongi Do we have a clear idea of where this is going in the TOC? I guess this is part of the discussion with Angela...

Hi @dkershaw10 - We'll surface them under "Identity and access" for now until we conclude the IA discussion with Angela.

2023-06-12 17:14 UTC, FaithOmbongi requested changes
Hi @bakerCaleb, @moti-ba - Excellent work getting the docs together and aligned with the Graph information architecture.

This is Batch 1 of the review feedback:

- Changelog errors: broken links - The referenced resource files are missing from your PR. For example, networkaccess-association.md, networkaccess-iprange.md etc.
   - I see some resources, like filteringPolicy are still hidden in the schema but their references are still showing up in some of the files hence some of the broken link errors. Please investigate what needs to be cleaned out. Are some APIs not supposed to be released in this iteration?
- The namespace statement "Namespace: microsoft.graph.networkaccess", please use the proper casing, i.e. **networkAccess** instead of "networkaccess". The schema PR was updated to networkAcccess following API review.
- I see the new (approved) permissions are NetworkAccessBranch.** and NetworkAccessPolicy.** and _not_ NetworkAccess.**. Please fix all permissions tables.
- Update the permissions reference to document the new permissions. Match what will be displayed on the product side (not what you proposed as the permissions string).
- Please document the RBAC information after the permissions tables. You can check out the [synchronization API docs](https://learn.microsoft.com/en-us/graph/api/synchronization-synchronization-acquireaccesstoken?view=graph-rest-beta&tabs=http) to see how the include file should look like and how to reference it.
- For "HTTP request" sections, make sure the domain and version parts of the URL aren't included. For example, it should be `/networkAccess/forwardingProfiles/{forwardingProfileId}/policies/ ` instead of `https://graph.microsoft.com/beta/networkAccess/forwardingProfiles/{forwardingProfileId}/policies/ `. This only applies to the HTTP request section.
- **GLOBAL:** Please update all instances of "https://graph.microsoft-ppe.com/.." especially in the OData context to the public endpoint "https://graph.microsoft.com/..."
- **GLOBAL:** For all APIs that require a request body, for example PATCH/PUT/POST operations, always leave a white line between the header and the opening brace `{`. Otherwise, the example will fail validation and code snippets won't be generated for such examples.

2023-06-13 14:13 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingprofile.md
> +|associations|[microsoft.graph.networkaccess.association](../resources/networkaccess-association.md) collection|Specifies the associated users, groups, devices, and branch locations for a given traff
```suggestion
|associations|[microsoft.graph.networkaccess.association](../resources/networkaccess-association.md) collection|Specifies the users, groups, devices, and branch locations whose traffic is associated with the given traffic forwarding profile.|
```

2023-06-13 14:14 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingprofile.md
> +|version|String|version Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md).|
Full descriptive sentences, please. Proper punctuation. We're writing for humans 🙂.

2023-06-13 14:35 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-associatedbranch.md
> +A branch associated with another entity (for example, a forwarding profile) is called an associated branch.
Apply what you have in the metadata above.

2023-06-13 14:43 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-forwardingprofile-list.md
> +  "name": "get_forwardingprofile"
To differentiate from the example in the GET doc.
```suggestion
  "name": "list_forwardingprofile"
```

2023-06-13 14:44 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-forwardingprofile-list.md
> +
Add an Example 2 showing use of $select and $expand. Refer to the guidance for guidance on how the heading levels changes.

2023-06-13 14:46 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-forwardingprofile-update.md
> +|associations|[microsoft.graph.networkaccess.association](../resources/networkaccess-association.md) collection|Specifies the associated users, groups, devices, and branch locations for a given traff
Interesting that name is required. Is this true? I thought in PATCH all properties are optional.
I recommend adding the @odata.type statement to future proof when you introduce new associations.
```suggestion
|name|String|Name of profile. Required.|
|associations|[microsoft.graph.networkaccess.association](../resources/networkaccess-association.md) collection|Specifies the users, groups, devices, and branch locations that are associated with this traffic forwarding profile. Optional. You must include the **@odata.type** property with a value of the specific association in the body. For example, "@odata.type": "#microsoft.graph.associatedBranch". |
```

2023-06-13 14:50 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingprofile.md
> +|[Create forwardingProfile](../api/networkaccess-networkaccessroot-post-forwardingprofiles.md)|[microsoft.graph.networkaccess.forwardingProfile](../resources/networkaccess-forwardingprofile.md)|Creat
This file is missing from this PR.

2023-06-13 14:51 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingprofile.md
> +|[Delete forwardingProfile](../api/networkaccess-networkaccessroot-delete-forwardingprofiles.md)|None|Delete a [microsoft.graph.networkaccess.forwardingProfile](../resources/networkaccess-forwardingp
This file is missing from this PR.

2023-06-13 14:55 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingprofile.md
> +|[List policies](../api/networkaccess-filteringprofile-list-policies.md)|[microsoft.graph.networkaccess.policyLink](../resources/networkaccess-policylink.md) collection|Get the policyLink resources f
filteringProfile isn't going public so filertingprofile-list-policies.md API doc doc isn't required. You should have networkaccess-forwardingprofile-post-policies instead.

2023-06-13 16:40 UTC, dkershaw10 commented on api-reference/beta/resources/devicelink.md
> +|[Get deviceLink](../api/networkaccess-devicelink-get.md)|[microsoft.graph.networkaccess.deviceLink](../resources/networkaccess-devicelink.md)|Read the properties and relationships of a [microsoft.gr
This object doesn't have relationships

2023-06-13 16:44 UTC, dkershaw10 commented on api-reference/beta/resources/devicelink.md
> +|id|String|idInherited from [microsoft.graph.entity](../resources/entity.md).|
```suggestion
|id|String|id is inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-06-13 18:54 UTC, FaithOmbongi requested changes
Hi @moti-ba - This is Batch 3 of the review feedback relating to forwarding policies and downstream and interlinked objects and APIs.

- Again - for properties of forwardingPolicy.md, indicate which support $filter and if the relationship supports $expand.
   - The LIST and GET docs should document the supported query parameters in the Optional query parameters section.
- Missing API files relating to forwardingPolicy
   - LIST /networkAccess/forwardingProfiles/{id}/policies
   - UPDATE /networkAccess/forwardingProfiles/{id}/policies/{ID}
   - GET /networkAccess/forwardingProfiles/{id}/policies/{ID}
- Missing the iprange complex type doc.
- File name fixes:
  - networkaccess-forwardingrule-get.md => networkaccess-policyrule-get.md
  - networkaccess-forwardingrule-list.md => networkaccess-policy-list-policyrules.md
- Missing files for policyRule (API.md says these operations are supported)
   - networkaccess-policyrule-delete.md 
   - networkaccess-policy-post-policyrules.md
 - Missing file for forwardingPolicy
    - networkaccess-networkaccessroot-list-forwardingpolicies.md
 - filteringPolicy-related APIs are all still hidden in the schema. Please remove all corresponding files from your PR.

2023-06-13 19:37 UTC, dkershaw10 commented on api-reference/beta/resources/devicelink.md
> +|version|String|version|
More detail required.

2023-06-13 19:38 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-associateddevice.md
> +|deviceId|String|**TODO: Add Description**|
Fix all TODOs, everywhere

2023-06-13 19:42 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-branchsite.md
> +branchSite represent locations for connectivity
```suggestion
branchSite represents locations for connectivity.
```
Does this need a bit more information?  This seems very sparse.
@FaithOmbongi what's the formatting rule for talking about a type in a sentence?

2023-06-13 19:44 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-branchsite.md
> +|bandwidthCapacity|Int64|Determines the maximum allowed Mbps (magabits per second) bandwidth from a branch site	|
Please state the allow options here.  I seem to recollect from API review there were some limited choices.

2023-06-13 19:45 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-branchsite.md
> +|id|String|Id Inherited from [microsoft.graph.entity](../resources/entity.md).|
```suggestion
|id|String|id inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-06-13 19:47 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-conditionalaccesspolicy.md
> +conditional Access Policy
We definitely need more than this.  Please add details.  How does this relate to the existing CA policy?
Everything is really sparse here - the property descriptions have nothing meaningful either.

2023-06-13 19:49 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-conditionalaccesssettings.md
> +Conditional access settings. Admin can enable or disable conditional access signaling for source IP restoration and Connectivity through NaaS.
Please rewrite - this makes little sense.  It should be about what this API does.

2023-06-13 19:50 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-connectivity.md
> +|[Create branchSite](../api/networkaccess-connectivity-post-branches.md)|[microsoft.graph.networkaccess.branchSite](../resources/networkaccess-branchsite.md)|Create a new branchSite object.|
```suggestion
|[Create branch](../api/networkaccess-connectivity-post-branches.md)|[microsoft.graph.networkaccess.branchSite](../resources/networkaccess-branchsite.md)|Create a new branchSite object.|
```

2023-06-13 19:51 UTC, dkershaw10 commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +Cross tenant access settings. For now it only contains the Network Packet Tagging Status. The network packet tagging with the user tenant ID will eventually be destined to Azure AD, and it will enfor
This reads like it came from an internal spec.  Please make this clearer for our developer audience

2023-06-14 08:28 UTC, FaithOmbongi requested changes
Hi @moti-ba -

This is Batch 4 of the content review feedback relating to tenantStatus. Again, I still defer to you for technical accuracy.

- There's an onboard action in the schema. Tenant status should be the very first item in the TOC after the overview because it sounds like you can't use these features unless you explicitly onboard.
- Your API.md says you have an offboard action, but I can't trace it to the schema.
- You're missing at least two API docs for tenantStatus (GET and onboard action). I'm not sure how a customer offboards. It'll be good to clarify.

2023-06-14 08:28 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tenantstatus.md
> +description: "TenantStatus is a top level entity under networkAccess which represents a tenant status."
```suggestion
description: "Indicates whether the tenant has onboarded to use the Microsoft Entra Internet Access and Microsoft Entra Private Access features."
```

2023-06-14 08:28 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tenantstatus.md
> +TenantStatus is a top level entity under networkAccess which represents a tenant status.
Match with the metadata description.

2023-06-14 08:28 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tenantstatus.md
> +|onboardingStatus|microsoft.graph.networkaccess.onboardingStatus|Reflects the tenant onboarding status. The possible values are: `offboarded`, `offboardingInProgress`, `onboardingInProgress`, `onboar
```suggestion
|id|String|Identifier for the status. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|onboardingErrorMessage|String|The error message in case onboarding failed.|
|onboardingStatus|microsoft.graph.networkaccess.onboardingStatus|Reflects the tenant onboarding status. The possible values are: `offboarded`, `offboardingInProgress`, `onboardingInProgress`, `onboarded`, `onboardingErrorOccurred`, `offboardingErrorOccurred`.|
```

2023-06-14 08:28 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tenantstatus.md
> +|[Delete tenantStatus](../api/networkaccess-networkaccessroot-delete-tenantstatus.md)|None|Delete a [microsoft.graph.networkaccess.tenantStatus](../resources/networkaccess-tenantstatus.md) object.|
- From the API.md, it looks like only GET operation, **onboard** action, and (possibly) **offboard** action are supported. I'm not sure about offboard because it's not in your schema in staging. But that begs the question, how does a customer get to the offboarding** statuses unless there's some way they can offboard?
- Please fix the list and document the related API docs.

2023-06-14 09:48 UTC, FaithOmbongi requested changes
Hi @moti-ba -

This is Batch 5 of the content review feedback relating to the settings. Again, I defer to you for technical accuracy.

The CA settings object seems to affect a lot of things downstream. The docs need to be clearer on what these are, what happens if enabled vs disabled, cross-link to the affected APIs/features etc.

- I reiterate the need for clear descriptions and complete sentences [that will be read by humans](https://learn.microsoft.com/en-us/style-guide/brand-voice-above-all-simple-human).
- Two relationships are missing from the settings entity.
- conditionalAccessSettings:
  - Demonstrate how that minor configuration affects everything else. Also I assume there's the linkage between this setting and the actual CA policy + the reporting APIs. It's important to update the corresponding https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessapplications?view=graph-rest-beta
  - Another good to have: Add an example in the CA docs showing how to create a CA policy targeting one of the supported traffic profiles.

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-conditionalaccesssettings.md
> +|signalingStatus|microsoft.graph.networkaccess.status|Conditional Access policy includes zero trust network access information when SignalingStatus is enabled	.The possible values are: `enabled`, `di
Isn't the signalingStatus property only the fancy term for enable/disable source IP restoration?
Suggestion
```suggestion
|Property|Type|Description|
|:---|:---|:---|
|id|String|Identifier of the setting. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|signalingStatus|microsoft.graph.networkaccess.status| Whether source IP restoration is enabled for Conditional Access. The possible values are: `enabled`, `disabled`. <br/> When enabled, the real source IP is shared with services such as [Conditional Access](conditionalaccesspolicy.md), [Identity Protection](identityprotection-overview.md), and [sign-in logs](signin.md) that rely on source IP information. For example, source IP restoration allows organizations to continue using IP location-based Conditional Access policies. |
```

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-conditionalaccesssettings-get.md
> +description: "Read the  conditional access signaling for source IP restoration and Connectivity through NaaS"
I recommend avoid NaaS because we don't use the term anywhere to refer to Global Secure Access nor have we agreed to use it as the TOC name for this set of API docs.
```suggestion
description: "Read the details of conditional access signaling for source IP restoration."
```

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-conditionalaccesssettings-get.md
> +Read the  conditional access signaling for source IP restoration and Connectivity through NaaS
Match with the metadata description.

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-conditionalaccesssettings-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Document supported query parameters. Can be $select only (if supported). If not, then "This method does not support any OData..."

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-conditionalaccesssettings-update.md
> +description: "Update the conditional access signaling for source IP restoration and Connectivity through NaaS."
Apply same feedback I left on the GET doc

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-conditionalaccesssettings-update.md
> +Update the conditional access signaling for source IP restoration and Connectivity through NaaS
Apply same feedback I left on the GET doc

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-conditionalaccesssettings-update.md
> +|signalingStatus|microsoft.graph.networkaccess.status|**TODO: Add Description**. The possible values are: `enabled`, `disabled`. Required.|
Replace ** TODO**.
Remove the "Required." statement

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-conditionalaccesssettings.md
> +|[Delete conditionalAccessSettings](../api/networkaccess-settings-delete-conditionalaccess.md)|None|Delete a [microsoft.graph.networkaccess.conditionalAccessSettings](../resources/networkaccess-condi
Only GET and UPDATE are supported.

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +description: "Cross tenant access settings. For now it only contains the Network Packet Tagging Status. The network packet tagging with the user tenant ID will eventually be destined to Azure AD, and
```suggestion
description: " Defines whether the tenant restrictions in cross-tenant access settings are enabled for traffic profiles. Each tenant has only one cross-tenant access settings object."
```

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +Cross tenant access settings. For now it only contains the Network Packet Tagging Status. The network packet tagging with the user tenant ID will eventually be destined to Azure AD, and it will enfor
`+1.` Same sentiment as the conditionalaccesssettings description. And then as a last sentence, refer readers to /azure/global-secure-access/how-to-universal-tenant-restrictions for more information. "_For more information about cross-tenant access settings, see [Universal tenant restrictions](/azure/global-secure-access/how-to-universal-tenant-restrictions)._"

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +|networkPacketTaggingStatus|microsoft.graph.networkaccess.status|Determines if the service inserts a header with the user tenant ID into network traffic	.The possible values are: `enabled`, `disabled
Suggestion
```suggestion
|id|String|Identifier for the setting. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|networkPacketTaggingStatus|microsoft.graph.networkaccess.status| Determines whether tenant restrictions for cross-tenant access settings are enabled. The possible values are: `enabled`, `disabled`. <br/> When enabled, the service inserts a header that contains the user tenant ID and the tenant restrictions policy ID into network traffic. |
```

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +|[Delete crossTenantAccessSettings](../api/networkaccess-settings-delete-crosstenantaccess.md)|None|Delete a [microsoft.graph.networkaccess.crossTenantAccessSettings](../resources/networkaccess-cross
Only GET and UPDATE are supported.

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-crosstenantaccesssettings-get.md
> +description: "Get the network packet tagging status for a user's tenant ID to enforce Tenant Restrictions Policies (TRv2 Policies) that prevent data exfiltration to external tenants."
```suggestion
description: "Get details of whether tenant restrictions for conditional access policies are enabled for traffic profiles."
```

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-crosstenantaccesssettings-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Document supported query parameters Can be $select only if supported.

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-crosstenantaccesssettings-update.md
> +description: "Updates the network packet tagging status for a user's tenant ID to enforce Tenant Restrictions Policies (TRv2 Policies) that prevent data exfiltration to external tenants."
Same suggestions as in the GET doc.

2023-06-14 09:48 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-crosstenantaccesssettings-update.md
> +|networkPacketTaggingStatus|microsoft.graph.networkaccess.status| network packet tagging status. The possible values are: `enabled`, `disabled`. Required.|
```suggestion
|networkPacketTaggingStatus|microsoft.graph.networkaccess.status| Whether tenant restrictions are enabled in cross-tenant access for the traffic profiles and the Global Secure Access service should tag the network packets. The possible values are: `enabled`, `disabled`. |
```

2023-06-14 17:20 UTC, FaithOmbongi requested changes
Hi @moti-ba -

This is Batch 6 of content review feedback related to connectivity and related objects.

- You're missing the following files
   - connectivity-list-branches file
   - branchsite-list-forwardingprofiles.md
- forwardingprofile-update.md should document two URLs: 
   - /networkAccess/forwardingProfiles/{forwardingProfileId}
   - /networkAccess/connectivity/branches/{id}/forwardingProfiles/{id}
   - If the permissions and RBAC for either operation are different, you need separate permissions tables and separate HTTP blocks in the HTTP request section. See the raw version of this doc for guidance  https://learn.microsoft.com/en-us/graph/api/directoryobject-getmemberobjects?view=graph-rest-beta&tabs=http#permissions
- forwardingprofile-get.md file should document two URLs:
   - /networkAccess/forwardingProfiles/{forwardingProfileId}
   - /networkAccess/connectivity/branches/{id}/forwardingProfiles/{id}
   - If the permissions and RBAC for either operation are different, you need separate permissions tables and separate HTTP blocks in the HTTP request section. See the raw version of this doc for guidance  https://learn.microsoft.com/en-us/graph/api/directoryobject-getmemberobjects?view=graph-rest-beta&tabs=http#permissions


Edge crashed and I lost a few of my points but hopefully, the suggestions inline are enough.

2023-06-14 17:20 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-forwardingoptions-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Either it supports $select or is doesn't support any. Update accordingly.

2023-06-14 17:20 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-forwardingoptions-get.md
> +  "name": "get_conditionalaccesssettings"
use a name that makes it easier to correlate the example with this file. This name is already in use and will cause a mismatch and conflict.

2023-06-14 17:20 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-branchsite-updateforwardingprofiles.md
Not a valid operation according to the schema. Delete file.

2023-06-14 17:20 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-networkaccessroot-delete-branches.md
Correct file name is networkaccess-branchsite-delete.md. Please fix.

2023-06-14 17:20 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-webcategories-list.md
Not a valid operation as per the schema.

2023-06-14 17:20 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-associateddevice.md
Not live as per the schema. Please delete.

2023-06-14 17:20 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-conditionalaccesspolicy.md
This doc is technically not in use because the filtering* features are still hidden. So you don't need to document it. But Dan's comment apply if you're documenting it.

2023-06-14 18:24 UTC, FaithOmbongi requested changes
Hi @moti-ba -

This is batch 7 of content review feedback touching on reporting APIs. Unfortunately, you have a lot of missing files for this batch of APIs - possibly 17+ files.

- Document the logs entity and the linked relationship.
- Document the networkAccessTraffic entity and related objects including properties, enums, and complex types like headers, deviceCategory.
- Document the GET and LIST operations for logs.
- Document at least 5 functions relating to the logs APIs and the related 5 or so complex types.
- Clearly differentiate between logs and enrichedAuditLogs.
- Missing API files for enrichedAuditLogs
    - networkaccess-enrichedauditlogs-update.md
    - networkaccess-enrichedauditlogs-get.md

2023-06-14 18:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogs.md
> +description: "This entity is designed to offer a comprehensive snapshot of our enhanced audit log workloads. At present, it encompasses three partners: SharePoint, Teams, and Exchange. Within each pa
Make it something like "_Defines whether enriched audit logs are available for the supported services that have corresponding traffic profiles in the Global Secure Access service." 

Then in the description section below:
1. add a base description like the one you apply in this metadata
2. And then explain what "enriched logs" are and how they compare with the networkaccess-logs.md, i.e. how do they look like in comparison with "basic" audit logs?

2023-06-14 18:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogs.md
> +This entity is designed to offer a comprehensive snapshot of our enhanced audit log workloads. At present, it encompasses three partners: SharePoint, Teams, and Exchange. Within each partner, the sta
See the comment in the metadata.
Also call out that enriched audit logs are supported for Microsoft SharePoint, Microsoft Teams, and Microsoft Exchange services.

2023-06-14 18:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogs.md
> +|teams|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)|Teams enriched audit logs settings|
```suggestion
|exchange|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)| Defines whether enriched audit logs for Exchange Online is enabled.	|
|id|String|Id Inherited from [microsoft.graph.entity](../resources/entity.md).|
|sharepoint|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)|Defines whether enriched audit logs for SharePoint Online is enabled.|
|teams|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)|Defines whether enriched audit logs for Teams is enabled.|
```

2023-06-14 18:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogs.md
> +|[Delete enrichedAuditLogs](../api/networkaccess-settings-delete-enrichedauditlogs.md)|None|Delete a [microsoft.graph.networkaccess.enrichedAuditLogs](../resources/networkaccess-enrichedauditlogs.md)
Only GET and UPDATE are supported.

2023-06-14 18:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogssettings.md
> +description: "The enriched audit logs settings will be organized in an expandable object to centralize all future feature-relevant settings. At present, it only includes the 'status' setting, which i
The only thing this complex type does is set the state.
```suggestion
description: "Defines whether the enriched logs setting is enabled for the service."
```

2023-06-14 18:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogssettings.md
> +The enriched audit logs settings will be organized in an expandable object to centralize all future feature-relevant settings. At present, it only includes the 'status' setting, which indicates wheth
Match with the metadata description above.

2023-06-14 18:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogssettings.md
> +|status|microsoft.graph.networkaccess.status|Indicate if Global Secure Access should enrich audit logs.The possible values are: `enabled`, `disabled`|
```suggestion
|status|microsoft.graph.networkaccess.status|Indicate whether the Global Secure Access service should enrich audit logs for the associated service that has a linked traffic profile. The possible values are: `enabled`, `disabled`, `unknownFutureValue`.|
```

2023-06-15 19:21 UTC, FaithOmbongi requested changes
Hi @moti-ba - 

This is batch 8 of content review feedback. I've re-reviewed all API operations except the two logs files. What's pending content re-review is these two + resource files.

- **Wrong HTTP request and the request URLs in the examples:** For all APIs relating to branchSite, please confirm whether the endpoints should start with `/networkAccess/connectivity/branches` or `/networkAccess/branches`. You currently document the latter, but your example responses show it's the former.
   - Same feedback applies to docs related to /deviceLinks.
   - I haven't left this suggestion on all affected instances, so please check carefully and address all of them.
- GLOBAL: For _examples_, always use the full URL including the https: and domain part; It's only in the HTTP request section that we document the shortened version. Find + replace will change what shouldn't be changed.
- GLOBAL: Where the response is a 204 No Content, delete this line in the response section ">**Note:** The response object shown here might be shortened for readability."
- GLOBAL: Make sure these's always a line between the header and the opening { of a JSON block. Aplies to both request bodies and response payloads.
- GLOBAL: If the response object is not a 204 No Content, then the HTML block in that response section must always include an @odata.type property to define what kind of response to expect in the payload. This is good for some planned validation.
- GLOBAL: In some cases, I've left suggestions for using the active voice instead of the passive voice. See the [Microsoft writing tone](https://learn.microsoft.com/en-us/style-guide/global-communications/writing-tips#:~:text=Use%20active%20voice%20and%20indicative%20mood).
   - So you'll see edits like "_~Allows developers to~ Retrieve a list of device links associated with a specific branch._"
   - Delete networkaccess-branchsite-updateforwardingprofiles.md, it's not a valid doc. I've left a comment for where to document the URL.
- You have a lot of API Doctor errors 50+. Please start addressing them soon.
- Are the NetworkAccessBranch.* permissions used anywhere?

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-policy-list-policyrules.md
> +If successful, this method returns a `200 OK` response code and a collection of [forwardingRule](../resources/networkaccess-forwardingrule.md) objects in the response body.
```suggestion
If successful, this method returns a `200 OK` response code and a collection of [policyRule](../resources/networkaccess-policyrule.md) objects in the response body.
```

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-policy-list-policyrules.md
> +  "@odata.type": "Collection(microsoft.graph.networkaccess.forwardingRule)"
```suggestion
  "@odata.type": "Collection(microsoft.graph.networkaccess.policyRule)"
```

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-policyrule-get.md
> +# Get forwardingRule
```suggestion
title: "Get policyRule"
description: "Retrieve information about a specific policy rule within a forwarding policy."
author: Moti-ba
ms.localizationpriority: medium
ms.prod: identity-and-access
doc_type: apiPageType
---

# Get policyRule
```

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-policyrule-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Document supported query parameters.

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-policyrule-get.md
> +  "name": "get_forwardingrule"
```suggestion
  "name": "get_policyrule"
```

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-settings-list-enrichedauditlogs.md
> +Retrieve the enriched audit logs for the configured workloads. This API call provides a way to access the comprehensive enriched audit logs data, including the original audit logs from partners such
```suggestion
Retrieve the enriched audit logs for the configured workloads. This API call provides a way to access the comprehensive enriched audit logs data, including the original audit logs from partners such as SharePoint, Teams, and Exchange.
```

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-settings-list-enrichedauditlogs.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Document supported query parameters.

2023-06-15 19:21 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-tenantstatus-get.md
> +Retreive the onboarding status of a specific tenant
```suggestion
description: "Retrieve the onboarding status of a specific tenant."
author: Moti-ba
ms.localizationpriority: medium
ms.prod: identity-and-access
doc_type: apiPageType
---

# Get tenantStatus
Namespace: microsoft.graph.networkaccess

[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]

Retrieve the onboarding status of a specific tenant.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-bgpconfiguration.md
> +|ipAddress|String|Specifies the BGP IP address of customer's on-premise VPN router configuration|
```suggestion
|asn|Int64|Specifies the ASN of the border gateway protocol (BGP).|
|ipAddress|String|Specifies the BGP IP address of the customer's on-premise VPN router configuration.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-branchsite.md
> +|forwardingProfiles|[microsoft.graph.networkaccess.forwardingProfile](../resources/networkaccess-forwardingprofile.md) collection|Specifies each forwarding profile that a branch site is associated wi
```suggestion
|deviceLinks|[microsoft.graph.networkaccess.deviceLink](../resources/networkaccess-devicelink.md) collection|Specifies each unique CPE device associated with a branch.|
|forwardingProfiles|[microsoft.graph.networkaccess.forwardingProfile](../resources/networkaccess-forwardingprofile.md) collection|Specifies each forwarding profile that a branch site is associated with.    |
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-conditionalaccesssettings.md
> +Conditional access settings defines how you can restore users source IP and how you can use compliant network validation. Source IP restoration preserves your original user IP context for all AAD and
```suggestion
Conditional access settings defines how you can restore users' source IP and how you can use compliant network validation. Source IP restoration preserves the user's original IP context for all Azure AD and Microsoft 365 traffic, while compliant network validation ensures the user is connecting from a verified network.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-conditionalaccesssettings.md
> +|signalingStatus|microsoft.graph.networkaccess.status|Conditional Access policy includes zero trust network access information when SignalingStatus is enabled	.The possible values are: `enabled`, `di
```suggestion
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|signalingStatus|microsoft.graph.networkaccess.status|Conditional Access policy includes zero trust network access information when signalingStatus is enabled.The possible values are: `enabled`, `disabled`.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-connectivity.md
> +description: "connectivity is a top level entity under networkAccess which represent all connectivity components in Global Secure Access"
```suggestion
description: "A top level entity that represents all connectivity components in the Global Secure Access service."
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-connectivity.md
> +connectivity is a top level entity under networkAccess which represent all connectivity components in Global Secure Access
```suggestion
A top level entity that represents all connectivity components in the Global Secure Access service.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-connectivity.md
> +|[List branches](../api/networkaccess-networkaccessroot-list-branches.md)|[microsoft.graph.networkaccess.branchSite](../resources/networkaccess-branchsite.md) collection|Get the branch resources from
```suggestion
|[List branches](../api/networkaccess-connectivity-list-branches.md)|[microsoft.graph.networkaccess.branchSite](../resources/networkaccess-branchsite.md) collection|Get the branch resources from the branches navigation property.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-connectivity.md
> +|webCategories|[microsoft.graph.networkaccess.webCategory](../resources/networkaccess-webcategory.md) collection|A web category is a group or classification of websites that share similar characteris
webCategories isn't live.
```suggestion
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-connectivity.md
> +|branches|[microsoft.graph.networkaccess.branchSite](../resources/networkaccess-branchsite.md) collection|branchSite represent locations for connectivity|
```suggestion
|branches|[microsoft.graph.networkaccess.branchSite](../resources/networkaccess-branchsite.md) collection|branchSite represent locations for connectivity.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-connectivity.md
> +}
```suggestion
{
  "@odata.type": "#microsoft.graph.networkaccess.connectivity",
  "id": "String (identifier)"
}
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +description: "A tenant's cross tenant access settings define Universal tenant restrictions version 2. The universal tenant restrictions version 2 offer coverage for tagging all traffic regardless of
Limited field length; In Graph we don't have a concept of different TR versions.
```suggestion
description: "A tenant's cross tenant access settings defines universal tenant restrictions."
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +A tenant's cross tenant access settings define Universal tenant restrictions version 2. The universal tenant restrictions version 2 offer coverage for tagging all traffic regardless of the browser or
```suggestion
A tenant's cross tenant access settings defines universal tenant restrictions. The universal tenant restrictions offer coverage for tagging all traffic regardless of the browser or operating system used on the device, support for branch connectivity and direct from device connectivity, and native integration with Microsoft 365 and Azure Active Directory.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +For more information about cross-tenant access settings, see [Universal tenant restrictions](https://github.com/azure/global-secure-access/how-to-universal-tenant-restrictions)."
```suggestion
For more information about cross-tenant access settings, see [Universal tenant restrictions](https://github.com/azure/global-secure-access/how-to-universal-tenant-restrictions).
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-crosstenantaccesssettings.md
> +|networkPacketTaggingStatus|microsoft.graph.networkaccess.status|Determines if the service inserts a header with the user tenant ID into network traffic	.The possible values are: `enabled`, `disabled
```suggestion
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|networkPacketTaggingStatus|microsoft.graph.networkaccess.status|Determines if the service inserts a header with the user tenant ID into network traffic. The possible values are: `enabled`, `disabled`.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-devicelink.md
> +description: "A link is a a single customer premises customer-premises equipment (CPE), at a physical branch site location."
```suggestion
description: "A link is a a single customer premises customer-premises equipment (CPE) at a physical branch site location."
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-devicelink.md
> +A link is a a single customer premises customer-premises equipment (CPE), at a physical branch site location.
```suggestion
A link is a a single customer premises customer-premises equipment (CPE) at a physical branch site location.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-devicelink.md
> +|version|String|version|
```suggestion
|bgpConfiguration|[microsoft.graph.networkaccess.bgpConfiguration](../resources/networkaccess-bgpconfiguration.md)|Specifies the IP address and ASN of the border gateway protocol to send traffic from a link to the edge.    |
|deviceVendor|microsoft.graph.networkaccess.deviceVendor|Specifies the vendor of the link.The possible values are: `barracudaNetworks`, `checkPoint`, `ciscoMeraki`, `citrix`, `fortinet`, `hpeAruba`, `netFoundry`, `nuage`, `openSystems`, `paloAltoNetworks`, `riverbedTechnology`, `silverPeak`, `vmWareSdWan`, `versa`, `other`.|
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|ipAddress|String|Specifies the client IPv4 address of the link.    |
|lastModifiedDateTime|DateTimeOffset|When the CPE was last updated.|
|name|String|Name for the CPE.|
|redundancyConfiguration|[microsoft.graph.networkaccess.redundancyConfiguration](../resources/networkaccess-redundancyconfiguration.md)|Specifies the details of redundancy option for the device link.|
|tunnelConfiguration|[microsoft.graph.networkaccess.tunnelConfiguration](../resources/networkaccess-tunnelconfiguration.md)|Specifies connectivity settings such as protocol, IPSec policy, and presharked key for establishing connectivity.    |
|version|String|Version.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogs.md
> +description: "Represents a complete overview of the enriched audit logs workloads within the tenant. It consists of three partners: SharePoint, Teams, and Exchange. Each partner represents a specific
```suggestion
description: "Represents a complete overview of the enriched audit logs workloads within the tenant. It consists of three partners: SharePoint, Teams, and Exchange. Each partner represents a specific workload that generates audit logs."
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogs.md
> +Represents a complete overview of the enriched audit logs workloads within the tenant. It consists of three partners: SharePoint, Teams, and Exchange. Each partner represents a specific workload that
```suggestion
Represents a complete overview of the enriched audit logs workloads within the tenant. It consists of three partners: SharePoint, Teams, and Exchange. Each partner represents a specific workload that generates audit logs.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogs.md
> +|teams|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)|Teams enriched audit logs settings|
```suggestion
|exchange|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)|Exchange Online enriched audit logs settings.    |
|id|String|Id Inherited from [microsoft.graph.entity](../resources/entity.md).|
|sharepoint|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)|SharePoint Online enriched audit logs settings.|
|teams|[microsoft.graph.networkaccess.enrichedAuditLogsSettings](../resources/networkaccess-enrichedauditlogssettings.md)|Teams enriched audit logs settings.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogssettings.md
> +description: "Represents a configuration object that centralizes enriched audit logs settings related to speficic M365 workload"
```suggestion
description: "Represents a configuration object that centralizes enriched audit logs settings related to specific Microsoft 365 workload."
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogssettings.md
> +Represents a configuration object that centralizes enriched audit logs settings related to speficic M365 workload
```suggestion
Represents a configuration object that centralizes enriched audit logs settings related to speficic Microsoft 365 workload.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-enrichedauditlogssettings.md
> +|status|microsoft.graph.networkaccess.status|Define the current status of the enrichment feature for a particular workload.The possible values are: `enabled`, `disabled`|
```suggestion
|status|microsoft.graph.networkaccess.status|Define the current status of the enrichment feature for a particular workload.The possible values are: `enabled`, `disabled`.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingoptions.md
> +description: "Defines the traffic forwarding options for the tenant. The forwardingOptions object contains the skipDnsLookupState settings, which determine whether DNS lookup will be performed at the
160 char limit
```suggestion
description: "Defines the traffic forwarding options for the tenant. "
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingoptions.md
> +Defines the traffic forwarding options for the tenant. The forwardingOptions object contains the skipDnsLookupState settings, which determine whether DNS lookup will be performed at the client, allow
```suggestion
Defines the traffic forwarding options for the tenant. The forwardingOptions object contains the **skipDnsLookupState** settings, which determine whether DNS lookup will be performed at the client, allowing Microsoft 365 traffic to be forwarded directly to the Front Door, or if DNS resolution will be conducted at the edge. This operation provides control over the traffic flow and DNS resolution strategy within the network infrastructure.
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingoptions.md
> +|skipDnsLookupState|microsoft.graph.networkaccess.status|The forwardingOptions control manages the various traffic forwarding options.The possible values are: `enabled`, `disabled`.|
```suggestion
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|skipDnsLookupState|microsoft.graph.networkaccess.status|The forwardingOptions control manages the various traffic forwarding options. The possible values are: `enabled`, `disabled`.|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingpolicy.md
> +|version|String|Forwarding policy version Inherited from [microsoft.graph.networkaccess.policy](../resources/networkaccess-policy.md).|
```suggestion
|description|String|Forwarding policy description. Inherited from [microsoft.graph.networkaccess.policy](../resources/networkaccess-policy.md).|
|id|String|Identifier for the forwarding policy. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|name|String|Forwarding policy name. Inherited from [microsoft.graph.networkaccess.policy](../resources/networkaccess-policy.md).|
|trafficForwardingType|microsoft.graph.networkaccess.trafficForwardingType|Traffic type for forwarding policy. The possible values are: `m365`, `internet`, `private`.|
|version|String|Forwarding policy version. Inherited from [microsoft.graph.networkaccess.policy](../resources/networkaccess-policy.md).|
```

2023-06-16 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingpolicylink.md
> +A forwardingPolicyLink connects a forwarding Policy with a forwarding profile
```suggestion
A forwardingPolicyLink connects a forwarding policy with a forwarding profile.
```

2023-06-16 15:54 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingpolicylink.md
> +|policy|[policy](../resources/networkaccess-policy.md)|forwarding Policy Inherited from [microsoft.graph.networkaccess.policyLink](../resources/networkaccess-policylink.md)|
```suggestion
|policy|[policy](../resources/networkaccess-policy.md)|The forwarding policy. Inherited from [microsoft.graph.networkaccess.policyLink](../resources/networkaccess-policylink.md)|
```

2023-06-16 15:55 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingprofile.md
> +|version|String|version Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md).|
```suggestion
|associations|[microsoft.graph.networkaccess.association](../resources/networkaccess-association.md) collection|Specifies the users, groups, devices, and branch locations whose traffic is associated with the given traffic forwarding profile.|
|description|String|Profile description. Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md).|
|id|String|Identifier for the profile. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|lastModifiedDateTime|DateTimeOffset|Profile last modified time. Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md).|
|name|String|Profile name. Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md).|
|priority|Int32|Profile priority.|
|state|microsoft.graph.networkaccess.status|Determines whether the profile is enabled or disabled.     Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md). The possible values are: `enabled`, `disabled`.|
|trafficForwardingType|microsoft.graph.networkaccess.trafficForwardingType|Profile traffic type. The possible values are: `m365`, `internet`, `private`.|
|version|String|Version. Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md).|
```

2023-06-16 15:55 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-forwardingprofile.md
> +|policies|[microsoft.graph.networkaccess.policyLink](../resources/networkaccess-policylink.md) collection|The collection of policies that are linked to this traffic forwarding profile.	 Inherited fro
```suggestion
|policies|[microsoft.graph.networkaccess.policyLink](../resources/networkaccess-policylink.md) collection|The collection of policies that are linked to this traffic forwarding profile.     Inherited from [microsoft.graph.networkaccess.profile](../resources/networkaccess-profile.md).|
```

2023-06-16 15:57 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-headers.md
> +Represents the HTTP headers included in a network request or response
```suggestion
Represents the HTTP headers included in a network request or response.
```

2023-06-16 15:57 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-headers.md
> +||String|Represents the information about the client's original IP address when the request passes through one or more proxy servers or load balancers|
```suggestion
|origin|String|Represents the origin or source from which the request is being made.|
|referrer|String|Represents the referring URL or the URL of the web page that the current request originates from.|
|String|Represents the information about the client's original IP address when the request passes through one or more proxy servers or load balancers.|
```

2023-06-16 15:58 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-intune-iprange.md
Rename to networkaccess-iprange.md

2023-06-16 15:58 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-intune-iprange.md
> +description: "Represents a range of IP addresses or a specific IP address. It is used to define a set of network addresses or a single network endpoint within a specified range"
```suggestion
description: "Represents a range of IP addresses or a specific IP address. It is used to define a set of network addresses or a single network endpoint within a specified range."
```

2023-06-16 15:58 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-intune-iprange.md
> +Represents a range of IP addresses or a specific IP address. It is used to define a set of network addresses or a single network endpoint within a specified range
```suggestion
Represents a range of IP addresses or a specific IP address. It is used to define a set of network addresses or a single network endpoint within a specified range.
```

2023-06-16 15:58 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-intune-iprange.md
> +|endAddress|String|Specifies the ending IP address of the IP range|
```suggestion
|beginAddress|String|Specifies the starting IP address of the IP range.|
|endAddress|String|Specifies the ending IP address of the IP range.|
```

2023-06-16 15:59 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-networkaccesstraffic.md
> +description: "Represents a log entry in the network access traffic log. The networkAccessTrafficLogEntry object provides detailed information about network traffic events"
```suggestion
description: "Represents a log entry in the network access traffic log. The networkAccessTrafficLogEntry object provides detailed information about network traffic events."
```

2023-06-16 15:59 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-networkaccesstraffic.md
> +Represents a log entry in the network access traffic log. The networkAccessTrafficLogEntry object provides detailed information about network traffic events
```suggestion
Represents a log entry in the network access traffic log. The networkAccessTrafficLogEntry object provides detailed information about network traffic events.
```

2023-06-16 16:03 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-networkaccesstraffic.md
> +|deviceOperatingSystemVersion|String|Represents the version or release number of the operating system installed on a device within a network infrastructure|
```suggestion
|action|microsoft.graph.networkaccess.filteringPolicyAction|Represents an action applied within a filtering policy. The possible values are: `block`, `allow`.|
|agentVersion|String|Represents the version of an agent software.|
|connectionId|String|Represents a unique identifier assigned to a connection.|
|createdDateTime|DateTimeOffset|Represents the date and time when a network access traffic log entry was created.|
|destinationFQDN|String|Represents the fully qualified domain name (FQDN) of the destination host or server in a network communication.|
|destinationIp|String|Represents the IP address of the destination host or server in a network communication.|
|destinationPort|Int32|Represents the network port number on the destination host or server in a network communication.|
|deviceCategory|microsoft.graph.networkaccess.deviceCategory|Represents the category classification of a device within a network infrastructure. The possible values are: `client`, `branch`.|
|deviceId|String|Represents a unique identifier assigned to a device within a network infrastructure.|
|deviceOperatingSystem|String|Represents the operating system installed on a device within a network infrastructure.|
|deviceOperatingSystemVersion|String|Represents the version or release number of the operating system installed on a device within a network infrastructure.|
```

2023-06-16 16:05 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-networkaccesstraffic.md
> +|userPrincipalName|String|Represents the user principal name (UPN) associated with a user|
```suggestion
|headers|[microsoft.graph.networkaccess.headers](../resources/networkaccess-headers.md)|Represents the headers included in a network request or response.|
|networkProtocol|microsoft.graph.networkaccess.networkingProtocol|Represents the networking protocol used for communication. The possible values are: `ip`, `icmp`, `igmp`, `ggp`, `ipv4`, `tcp`, `pup`, `udp`, `idp`, `ipv6`, `ipv6RoutingHeader`, `ipv6FragmentHeader`, `ipSecEncapsulatingSecurityPayload`, `ipSecAuthenticationHeader`, `icmpV6`, `ipv6NoNextHeader`, `ipv6DestinationOptions`, `nd`, `raw`, `ipx`, `spx`, `spxII`.|
|policyId|String|Represents a unique identifier assigned to a policy.|
|policyRuleId|String|Represents a unique identifier assigned to a policy rule.|
|receivedBytes|Int64|Represents the total number of bytes received in a network communication or data transfer.|
|sentBytes|Int64| Represents the total number of bytes sent in a network communication or data transfer.|
|sessionId|String|Represents a unique identifier assigned to a session or connection within a network infrastructure.|
|sourceIp|String|Represents the source IP address in a network communication.|
|sourcePort|Int32|Represents the network port number on the source host or device in a network communication.|
|tenantId|String|Represents a unique identifier assigned to a tenant within a network infrastructure.|
|trafficType|microsoft.graph.networkaccess.trafficType|Represents the type or category of network traffic. The possible values are: `internet`, `private`, `microsoft365`, `all`.|
|transactionId|String|Represents a unique identifier assigned to a specific transaction or operation. |
|transportProtocol|microsoft.graph.networkaccess.networkingProtocol|Represents the transport protocol used for communication.The possible values are: `ip`, `icmp`, `igmp`, `ggp`, `ipv4`, `tcp`, `pup`, `udp`, `idp`, `ipv6`, `ipv6RoutingHeader`, `ipv6FragmentHeader`, `ipSecEncapsulatingSecurityPayload`, `ipSecAuthenticationHeader`, `icmpV6`, `ipv6NoNextHeader`, `ipv6DestinationOptions`, `nd`, `raw`, `ipx`, `spx`, `spxII`.|
|userId|String|Represents a unique identifier assigned to a user.|
|userPrincipalName|String|Represents the user principal name (UPN) associated with a user.|
```

2023-06-16 16:06 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-policy.md
> +|version|String|Policy version number|
```suggestion
|description|String|Description.|
|id|String|Identifier for the policy. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|name|String|Policy name.|
|version|String|Policy version number.|
```

2023-06-16 16:06 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-policylink.md
> +description: "Contains the link for a Policy for a given profile"
```suggestion
description: "Contains the link for a policy for a given profile."
```

2023-06-16 16:07 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-policylink.md
> +Contains the link for a Policy for a given profile
```suggestion
Contains the link for a policy for a given profile.
```

2023-06-16 16:07 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-policylink.md
> +|version|String|version|
```suggestion
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|state|microsoft.graph.networkaccess.status|Link status. The possible values are: `enabled`, `disabled`, `unknownFutureValue`.|
|version|String|Version.|
```

2023-06-16 16:08 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-policyrule.md
> +|id|String|id Inherited from [microsoft.graph.entity](../resources/entity.md).|
```suggestion
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
```

2023-06-16 16:10 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-privateaccessforwardingrule.md
> +|name|String|name Inherited from [microsoft.graph.networkaccess.policyRule](../resources/networkaccess-policyrule.md).|
```suggestion
|name|String|Name. Inherited from [microsoft.graph.networkaccess.policyRule](../resources/networkaccess-policyrule.md).|
```

2023-06-16 16:10 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-profile.md
> +description: "A profile is a container for forwarding or filtering policies"
```suggestion
description: "A profile is a container for forwarding or filtering policies."
```

2023-06-16 16:11 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-profile.md
> +A profile is a container for forwarding or filtering policies
```suggestion
A profile is a container for forwarding or filtering policies.
```

2023-06-16 16:12 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-redundancyconfiguration.md
> +description: "Specifies the details of redundancy option for the device link"
```suggestion
description: "Specifies the details of redundancy option for the device link."
```

2023-06-16 16:12 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-redundancyconfiguration.md
> +Specifies the details of redundancy option for the device link
```suggestion
Specifies the details of redundancy option for the device link.
```

2023-06-16 16:12 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-redundancyconfiguration.md
> +|zoneLocalIpAddress|String|Specifies the zone BGP IP address of peer (Microsoft, in this case)	|
```suggestion
|zoneLocalIpAddress|String|Specifies the zone BGP IP address of peer (Microsoft, in this case).    |
```

2023-06-16 16:14 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-settings.md
> +description: "Global Settings"
```suggestion
description: "Global Secure Service settings for the tenant."
```

2023-06-16 16:14 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-settings.md
> +Global Settings
```suggestion
Global Secure Service settings for the tenant.
```

2023-06-16 16:14 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-settings.md
> +|:---|:---|:---|
```suggestion
None.
```

2023-06-16 16:16 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-settings.md
> +|crossTenantAccess|[crossTenantAccessSettings](../resources/networkaccess-crosstenantaccesssettings.md)|Cross tenant access settings. For now it only contains the Network Packet Tagging Status. The n
```suggestion
|conditionalAccess|[conditionalAccessSettings](../resources/networkaccess-conditionalaccesssettings.md)|Conditional access settings. You can enable or disable conditional access signaling for source IP restoration and connectivity through NaaS. In other words, Conditional Access policy will include zero trust network access information when signalingStatus is enabled.|
|crossTenantAccess|[crossTenantAccessSettings](../resources/networkaccess-crosstenantaccesssettings.md)|Cross tenant access settings. Currently defines the network packet tagging status. The network packet tagging with the user tenant ID will eventually be destined to Azure AD, and it will enforce Tenant Restrictions Policies, known as TRv2 Policies, which prevents users from exfiltrating data to tenants outside their organization.|
```

2023-06-16 16:17 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tenantstatus.md
> +TenantStatus is a top level entity under networkAccess which represents a tenant status.
```suggestion
Represents the status of the Global Secure Service for the tenant. 
```

2023-06-16 16:18 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tenantstatus.md
> +|[Update tenantStatus](../api/networkaccess-networkaccessroot-post-tenantstatus.md)|[microsoft.graph.networkaccess.tenantStatus](../resources/networkaccess-tenantstatus.md)|Update the properties of a
Only Onboard tenant and Get tenantSatus are supported.
```suggestion
|[Onboard](../api/networkaccess-networkaccessroot-onboard.md)|[microsoft.graph.networkaccess.tenantStatus](../resources/networkaccess-tenantstatus.md)|Onboard the tenant to the Global Secure Access service.|
|[Get tenantStatus](../api/networkaccess-tenantstatus-get.md)|[microsoft.graph.networkaccess.tenantStatus](../resources/networkaccess-tenantstatus.md)|Read the properties and relationships of a [microsoft.graph.networkaccess.tenantStatus](../resources/networkaccess-tenantstatus.md) object.|
```

2023-06-16 16:19 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tenantstatus.md
> +|onboardingStatus|microsoft.graph.networkaccess.onboardingStatus|Reflects the tenant onboarding status. The possible values are: `offboarded`, `offboardingInProgress`, `onboardingInProgress`, `onboar
```suggestion
|id|String|Identifier. Inherited from [microsoft.graph.entity](../resources/entity.md).|
|onboardingErrorMessage|String|Reflects a message to the user in case of an error.|
|onboardingStatus|microsoft.graph.networkaccess.onboardingStatus|Reflects the tenant onboarding status. The possible values are: `offboarded`, `offboardingInProgress`, `onboardingInProgress`, `onboarded`, `onboardingErrorOccurred`, `offboardingErrorOccurred`.|
```

2023-06-16 16:19 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfiguration.md
> +description: "Specifies connectivity settings (protocol, IPSec policy, and presharked key) for establishing connectivity"
```suggestion
description: "Specifies connectivity settings such as protocol, IPSec policy, and presharked key for establishing connectivity."
```

2023-06-16 16:19 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfiguration.md
> +Specifies connectivity settings (protocol, IPSec policy, and presharked key) for establishing connectivity
```suggestion
Specifies connectivity settings such as protocol, IPSec policy, and presharked key for establishing connectivity.
```

2023-06-16 16:20 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfiguration.md
> +|preSharedKey|String|A key to establish secure connection between the link and VPN tunnel on the Edge	|
```suggestion
|preSharedKey|String|A key to establish secure connection between the link and VPN tunnel on the edge.    |
```

2023-06-16 16:21 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfigurationikev2custom.md
> +description: "Specifies connectivity settings (protocol, IPSec policy, and presharked key) for establishing connectivity"
```suggestion
description: "Specifies connectivity settings such as protocol, IPSec policy, and presharked key for establishing connectivity."
```

2023-06-16 16:21 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfigurationikev2custom.md
> +Specifies connectivity settings (protocol, IPSec policy, and presharked key) for establishing connectivity
```suggestion
Specifies connectivity settings such as protocol, IPSec policy, and presharked key for establishing connectivity.
```

2023-06-16 16:21 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfigurationikev2custom.md
> +|dhGroup|microsoft.graph.networkaccess.dhGroup|Specifies the DH group identifier for IPSec SA negotiation	.The possible values are: `dhGroup14`, `dhGroup24`, `dhGroup2048`, `ecp256`, `ecp384`.|
```suggestion
|dhGroup|microsoft.graph.networkaccess.dhGroup|Specifies the DH group identifier for IPSec SA negotiation.The possible values are: `dhGroup14`, `dhGroup24`, `dhGroup2048`, `ecp256`, `ecp384`.|
```

2023-06-16 16:22 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfigurationikev2custom.md
> +|saLifeTimeSeconds|Int64|a standard specifiying Security Association lifetime with recommended values from an RFC standard	|
```suggestion
|dhGroup|microsoft.graph.networkaccess.dhGroup|Specifies the DH group identifier for IPSec SA negotiation. The possible values are: `dhGroup14`, `dhGroup24`, `dhGroup2048`, `ecp256`, `ecp384`.|
|ikeEncryption|microsoft.graph.networkaccess.ikeEncryption|Specifies the IKE encryption protocol. The possible values are: `aes128`, `aes192`, `aes256`, `gcmAes128`, `gcmAes256`.|
|ikeIntegrity|microsoft.graph.networkaccess.ikeIntegrity|Specifies the integration properties of the IKE protocol. The possible values are: `sha256`, `sha384`, `gcmAes128`, `gcmAes256`.|
|ipSecEncryption|microsoft.graph.networkaccess.ipSecEncryption|Specifies the encryption protocol used for the IPSec tunnel. The possible values are: `none`, `gcmAes128`, `gcmAes192`, `gcmAes256`.|
|ipSecIntegrity|microsoft.graph.networkaccess.ipSecIntegrity|Specifies the integrity properties of the IPSec protocol. The possible values are: `gcmAes128`, `gcmAes192`, `gcmAes256`, `sha256`.|
|pfsGroup|microsoft.graph.networkaccess.pfsGroup|Specifies the Phase 2 DH group identifier for IPSec SA negotiation. The possible values are: `none`, `pfs1`, `pfs2`, `pfs14`, `pfs24`, `pfs2048`, `pfsmm`, `ecp256`, `ecp384`.|
|preSharedKey|String|A key to establish secure connection between the link and VPN tunnel on the Edge     Inherited from [microsoft.graph.networkaccess.tunnelConfiguration](../resources/networkaccess-tunnelconfiguration.md).|
|saLifeTimeSeconds|Int64|a standard specifiying Security Association lifetime with recommended values from an RFC standard    |
```

2023-06-16 16:23 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfigurationikev2default.md
> +description: "Specifies connectivity settings (protocol, IPSec policy, and presharked key) for establishing connectivity"
```suggestion
description: "Specifies connectivity settings such as protocol, IPSec policy, and presharked key) for establishing connectivity."
```

2023-06-16 16:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-tunnelconfigurationikev2default.md
> +|preSharedKey|String|A key to establish secure connection between the link and VPN tunnel on the Edge	 Inherited from [microsoft.graph.networkaccess.tunnelConfiguration](../resources/networkaccess-tu
```suggestion
|preSharedKey|String|A key to establish secure connection between the link and VPN tunnel on the edge.   Inherited from [microsoft.graph.networkaccess.tunnelConfiguration](../resources/networkaccess-tunnelconfiguration.md).|
```

2023-06-16 16:24 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-url.md
> +Represents a Uniform Resource Locator (URL), which specifies the address of a web resource and includes the protocol, domain, path, and parameters
```suggestion
Represents a Uniform Resource Locator (URL), which specifies the address of a web resource and includes the protocol, domain, path, and parameters.
```

2023-06-16 16:25 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-webcategory.md
Not in the live schema. Delete file.

2023-06-16 16:42 UTC, FaithOmbongi requested changes
Hi @moti-ba -

This is batch 9 of content re-review feedback against all the pending docs.

- Missing files
   - logs.md entity doc and related r/ships
   - networkaccessroot-list-logs.md to document the LIST logs `https://graph.microsoft.com/beta/networkAccess/logs` operation. 
      - There's alot of query capabilities supported by this LIST operation - $filter, $select, $orderby, $top, contains, $expand. Please ensure you adequately document the properties that support $filter + supported operators & add the base example and a second example to the LIST doc.
      - Proper documentation of supported query operators is always a top dev ask for reporting APIs and pretty much most LIST APIs.
 
- What's completely pending is the TOC. please surface all the API files as soon as so we can make sure everything's there.
--------------------------------------------
The biggest problem in your PR is missing punctuations, like a period to mark the end of a sentence. This kind of problem blocks PRs. You also still have a lot of comments left over from the last review. Please address them and let's avoid another round of comprehensive content review.

2023-06-29 11:11 UTC, moti-ba commented on api-reference/beta/resources/networkaccess-policyrule.md
> +|[Delete policyRule](../api/networkaccess-policy-delete-policyrules.md)|None|Delete a [microsoft.graph.networkaccess.policyRule](../resources/networkaccess-policyrule.md) object.|
you can't create or delete rule

2023-07-05 18:59 UTC, FaithOmbongi requested changes
Hi @moti-ba - I've re-reviewed the core APIs and pushed a commit to address a number of issues. Only three or four new comments.

Next up, I'll review the set of reporting API docs including the new ones you've added.

2023-07-05 18:59 UTC, FaithOmbongi commented on api-reference/beta/resources/networkaccess-policyrule.md
> +|[Update policyRule](../api/networkaccess-policyrule-update.md)|[microsoft.graph.networkaccess.policyRule](../resources/networkaccess-policyrule.md)|Update the properties of a [microsoft.graph.networ
Your API.md shows CREATE and DELETE are also supported. Please confirm you don't have any missing files.

<img width="743" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/a8c4fbf0-a296-48e6-aa13-9c4568c6c3e6">

2023-07-06 16:44 UTC, FaithOmbongi requested changes
Hi @moti-ba -

This is the last review and finally we have only five or six issues to look into.

- Check the previous pending issue summary https://github.com/microsoftgraph/microsoft-graph-docs/pull/21578#pullrequestreview-1514087241 
- There's one pending API Doctor error that will be resolved if you fix the response object in the api-reference/beta/api/networkaccess-branchsite-post-devicelinks.md file. 
- Permissions: I notice you haven't used the NetworkAccessBranch.Read.All and NetworkAccessBranch.ReadWrite.Al permissions anywhere, even in the APIs linked to /branches endpoint. Can you confirm and correct the permission tables where applicable?
- I don't think the purpose and usefulness of enriched audit logs is clear. Because none of the APIs really shows any logs, they more like show the settings. Let's sync about this internally.

We'll now be able to focus on the API Overview next.

2023-07-06 16:44 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-branchsite-list-forwardingprofiles.md
> +  "value": [
Real example, please.

2023-07-06 16:44 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-networkaccesstraffic-get.md
> +      "tenantId": "cb9af522-39fe-4056-b879-e3200ff37b3d",
This response belongs to a LIST operation, not a GET operation. Replace with an appropriate response.

2023-07-06 16:44 UTC, FaithOmbongi commented on api-reference/beta/api/networkaccess-branchsite-post-devicelinks.md
> +```
Add the full response body here. It will resolve the one last pending API Doctor error.

<img width="538" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/41e8e157-9120-4142-9964-66524a1c18a2">

2023-07-10 14:23 UTC, FaithOmbongi approved these changes

2023-07-11 04:33 UTC, merged