Entitlement Management Extensibility GA
microsoftgraph/microsoft-graph-docs pull request #21571
Opened 2023-06-07 13:02 UTC by OWinfreyATL

2023-06-16 10:30 UTC, msewaweru requested changes
@OWinfreyATL - thanks for the work on this PR. I have left a few review comments including the below:
1. Reconcile the properties of the accessPackageAssignmentRequestCallbackData resource type between the schema and the API.md.
2. For both accessPackageAssignmentWorkflowExtension  and AccessPackageAssignmentRequestWorkflowExtension check the list of properties for a missing inherited property 'clientconfiguration' and 'type' that is defined in the API.md and not in the schema.

2023-06-16 20:22 UTC, OWinfreyATL commented on api-reference/v1.0/resources/accesspackageassignmentrequestworkflowextension.md
> +|lastModifiedDateTime|DateTimeOffset|When the object was last modified.|
Confirmed that the "type" property is an oversight by engineering. clientconfiguration added.

2023-06-16 20:41 UTC, OWinfreyATL commented on api-reference/v1.0/resources/accesspackageassignmentrequestcallbackdata.md
> +|customExtensionStageInstanceDetail|String|Details for the callback.|
Original schema update shows these two: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/8235696?_a=files

2023-06-16 20:41 UTC, OWinfreyATL commented on api-reference/v1.0/resources/logicapptriggerendpointconfiguration.md
> +|url|String| The URL to the logic app endpoint that will be triggered. Only required for app-only token scenarios where app is creating a [customCalloutExtension](../resources/customcalloutextension.
Schema shows these 4 properties: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/8235696?_a=files

2023-06-19 16:32 UTC, msewaweru commented on api-reference/v1.0/resources/accesspackageassignmentrequestcallbackdata.md
> +|customExtensionStageInstanceDetail|String|Details for the callback.|
> Original schema update shows these two: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/8235696?_a=files

The API.md then needs to be updated to reflect what's in the schema.

2023-06-19 17:28 UTC, msewaweru requested changes
@OWinfreyATL - thanks for addressing the feedback provided. I have completed reviewing the changelog and there are a few additions that are not part of this PR.

Also note that we cannot mark this PR as content review complete until [this PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20747), that deprecates the previous version of the extensibility APIs in beta, is merged.

2023-06-19 17:28 UTC, msewaweru commented on changelog/Microsoft.IGAELM.json
> +        },
This change is not capture in this PR.

2023-06-19 17:28 UTC, msewaweru commented on changelog/Microsoft.IGAELM.json
> +          "Target": "accessPackageAssignmentRequest"
This change is not capture in this PR.

2023-06-19 17:28 UTC, msewaweru commented on changelog/Microsoft.IGAELM.json
> +          "Target": "accessPackageAssignmentPolicy"
This change is not capture in this PR.

2023-06-19 17:28 UTC, msewaweru commented on changelog/Microsoft.IGAELM.json
> +          "Target": "accessPackageCatalog"
This change is not capture in this PR.

2023-07-12 16:35 UTC, msewaweru requested changes
@OWinfreyATL - I have a had another review. You missed 2 issues I had raised in the change log where the changes indicated are not in this PR. Please recheck. Thanks.

2023-07-12 16:35 UTC, msewaweru commented on api-reference/v1.0/resources/customextensiondata.md
>  - [customTaskExtensionCallbackData](../resources/identitygovernance-customtaskextensioncallbackdata.md)
These 2 resources are not captured in the schema to be derived from customExtensionData.

2023-07-12 16:35 UTC, msewaweru commented on changelog/Microsoft.IGAELM.json
> +        },
@OWinfreyATL - this has not been addressed yet.

2023-07-12 16:35 UTC, msewaweru commented on changelog/Microsoft.IGAELM.json
> +          "Target": "accessPackageAssignmentRequest"
This too.

2023-07-18 14:03 UTC, msewaweru reviewed
@OWinfreyATL - I have completed my review of this PR and it looks good.

The approval of this PR is blocked by the [PR deprecating some custom extension modules](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20747). Faith is reviewing it and will notify, so we can proceed to merge this work. Thanks.

2023-07-19 08:19 UTC, msewaweru approved these changes
@OWinfreyATL - This PR has been unblocked. Thanks for your patience.

2023-07-27 04:10 UTC, merged