Changes for rsc app installation support in v1.0
microsoftgraph/microsoft-graph-docs pull request #21605
Opened 2023-06-09 18:22 UTC by sweta-thapliyal

2023-06-30 19:35 UTC, AkJo approved these changes

2023-07-05 15:37 UTC, Danielabom commented
Contacted author to get info.

2023-07-10 16:14 UTC, Danielabom commented on api-reference/v1.0/resources/teamsapppermissionset.md
> +description: "Set of Resource specific permissions."
```suggestion
description: "Set of resource specific permissions."
```

2023-07-10 16:41 UTC, Danielabom commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the `authorization` property to the [teamsAppDefinition](https://learn.microsoft.com/en-us/graph/api/resources/teamsAppDefinition?view=graph-rest-1.0) resource.",
```suggestion
          "Description": "Added the **authorization** property to the [teamsAppDefinition](https://learn.microsoft.com/en-us/graph/api/resources/teamsAppDefinition?view=graph-rest-1.0) resource.",
```

2023-07-10 16:41 UTC, Danielabom commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the `consentedPermissionSet` property to the [teamsAppInstallation](https://learn.microsoft.com/en-us/graph/api/resources/teamsAppInstallation?view=graph-rest-1.0) res
```suggestion
          "Description": "Added the **consentedPermissionSet** property to the [teamsAppInstallation](https://learn.microsoft.com/en-us/graph/api/resources/teamsAppInstallation?view=graph-rest-1.0) resource.",
```

2023-07-10 16:53 UTC, Danielabom commented on api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
> +# teamsAppInstallation in team: upgrade
```suggestion
# teamsAppInstallation in a team: upgrade
```

2023-07-10 16:53 UTC, Danielabom commented on api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
> +title: "teamsAppInstallation in team: upgrade"
```suggestion
title: "teamsAppInstallation in a team: upgrade"
```

2023-07-10 16:55 UTC, Danielabom commented on api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
> +> - Currently, upgrading an app that requires resource-specific consent permissions is not supported in application context.
```suggestion
> - Currently, upgrading an app that requires resource-specific consent permissions is not supported in an application context.
```

2023-07-10 17:10 UTC, Danielabom commented on api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadWriteSelfForTeam<sup>1</sup>, TeamsAppInstallation.ReadWriteForTeam<sup>1</sup>, TeamsAppInstallation.ReadWriteAndConsentForTeam, TeamsA
Are these new permissions? If so, please add changelog entries.

2023-07-10 17:14 UTC, Danielabom commented on api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
> +> - Currently, upgrading an app that requires resource-specific consent permissions is not supported in an application context.
```suggestion
> Currently, upgrading an app that requires resource-specific consent permissions is not supported in an application context.
```

2023-07-10 17:14 UTC, Danielabom commented on api-reference/v1.0/api/team-post-installedapps.md
> +> - Currently, installing an app that requires resource-specific consent permissions is not supported in application context.
```suggestion
> Currently, installing an app that requires resource-specific consent permissions is not supported in an application context.
```

2023-07-10 17:23 UTC, Danielabom commented on api-reference/v1.0/api/team-post-installedapps.md
> +The request body should contain the catalog app's generated app ID. For details, see [teamsApp properties](../resources/teamsapp.md#properties).
```suggestion
The request body should include the generated app ID of the catalog app. For more information, see [teamsApp properties](../resources/teamsapp.md#properties).
```

2023-07-10 17:26 UTC, Danielabom commented on api-reference/v1.0/api/team-post-installedapps.md
> +> The permissions consented to during the install must be the same as the resource-specific permissions present in the [teamsAppDefinition](../resources/teamsAppDefinition.md) of the app. To get the
```suggestion
> The permissions consented to during the installation must match the resource-specific permissions defined in the [teamsAppDefinition](../resources/teamsAppDefinition.md) of the app. To get the application and delegated resource-specific permissions, see [Example 7](../api/appcatalogs-list-teamsapps.md#example-7-list-applications-with-a-given-id-and-return-only-the-resource-specific-permissions-required-by-the-app). If only delegated resource-specific permissions are specified in the **teamsAppDefinition**, permissions can be omitted in the request body.
```

2023-07-10 17:29 UTC, Danielabom commented on api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md
> +# teamsAppInstallation in chat: upgrade
```suggestion
# teamsAppInstallation in a chat: upgrade
```

2023-07-10 17:30 UTC, Danielabom commented on api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
> +> The permissions consented to during the upgrade must be the same as the resource-specific permissions present in the [teamsAppDefinition](../resources/teamsAppDefinition.md) of the app. To get the
```suggestion
> The permissions consented to during the installation must match the resource-specific permissions defined in the [teamsAppDefinition](../resources/teamsAppDefinition.md) of the app. To get the application and delegated resource-specific permissions, see [Example 7](../api/appcatalogs-list-teamsapps.md#example-7-list-applications-with-a-given-id-and-return-only-the-resource-specific-permissions-required-by-the-app). If only delegated resource-specific permissions are present in **teamsAppDefinition**, permissions can be omitted in the body of this request.
```

2023-07-10 17:32 UTC, Danielabom commented on api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md
> +> The permissions consented to during the upgrade must be the same as the resource-specific permissions present in the [teamsAppDefinition](../resources/teamsAppDefinition.md) of the app. To get the
```suggestion
> he permissions consented to during the installation must match the resource-specific permissions defined in the [teamsAppDefinition](../resources/teamsAppDefinition.md) of the app. To get the application and delegated resource-specific permissions, see [Example 7](../api/appcatalogs-list-teamsapps.md#example-7-list-applications-with-a-given-id-and-return-only-the-resource-specific-permissions-required-by-the-app). IIf only delegated resource-specific permissions are specified in the **teamsAppDefinition**, permissions can be omitted in the body of this request.
```

2023-07-10 17:37 UTC, Danielabom commented on api-reference/v1.0/api/chat-post-installedapps.md
> +The request body should contain the catalog generated app ID for the app catalog. For details, see [teamsApp properties](../resources/teamsapp.md#properties).
```suggestion
The request body should contain the catalog generated app ID for the app catalog. For details, see [teamsApp properties](../resources/teamsapp.md#properties).
```
```suggestion
The request body should contain the catalog generated app ID for the app catalog. For details, see [teamsApp properties](../resources/teamsapp.md#properties).
```
```suggestion
The request body should include the generated app ID of the catalog app. For more information, see [teamsApp properties](../resources/teamsapp.md#properties).
```

2023-07-10 17:43 UTC, Danielabom commented on api-reference/v1.0/api/chat-post-installedapps.md
> +> **Note**: The permissions consented to during the install must be same as the resource-specific permissions present in the [teamsAppDefinition](../resources/teamsAppDefinition.md) of the app. To ge
```suggestion
> **Note**: 
```

2023-07-10 18:39 UTC, Danielabom requested changes
@sweta-thapliyal, thank you for working on this PR. Please see my comments. Quick question are you adding new permissions, or is it more of a doc update because the operations did not reflect the correct permissions? If these are new permissions, we need changelog entries.

2023-07-10 19:37 UTC, sweta-thapliyal commented on api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md
> +# teamsAppInstallation in chat: upgrade
All the other teams related titles have similar structure, where we don't use article. Let's keep this one consistent.

2023-07-10 21:03 UTC, Danielabom approved these changes
PR approved.

2023-07-10 23:41 UTC, sweta-thapliyal commented on api-reference/v1.0/resources/teamsappauthorization.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
```suggestion
```

2023-07-10 23:41 UTC, sweta-thapliyal commented on api-reference/v1.0/resources/teamsapppermissionset.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
```suggestion
```

2023-07-10 23:41 UTC, sweta-thapliyal commented on api-reference/v1.0/resources/teamsappresourcespecificpermission.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
```suggestion
```

2023-07-11 05:05 UTC, merged