Issue #21272 fix and updating workflow to include access assignment.
microsoftgraph/microsoft-graph-docs pull request #21631
Opened 2023-06-13 09:42 UTC by koravvams

Issue #21272 fix and updated the GDAP workflow section to include access assignment creation steps to ensure users setup access assignment after relation approval.

2023-07-22 02:59 UTC, Danielabom commented
Contacted author to get info.

2023-08-01 03:05 UTC, Danielabom commented on api-reference/beta/resources/delegatedadminrelationships-api-overview.md
> +Send the invitation link to the customer for them to approve the GDAP request. For example, `https://admin.microsoft.com/AdminPortal/Home#/partners/invitation/granularAdminRelationships/5d027261-d21f
```suggestion
Send the invitation link to the customer for them to approve the GDAP request. For example, `https://admin.microsoft.com/AdminPortal/Home#/partners/invitation/granularAdminRelationships/5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836` is an invitation link, where `5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836` is the admin relationship request ID. Once the customer approves the GDAP request, the GDAP relationship will transition to the active state.
```

2023-08-01 03:06 UTC, Danielabom commented on api-reference/beta/resources/delegatedadminrelationships-api-overview.md
> +Next, to complete the workflow for enabling AOBO management of customer tenant, create new access assignment for this delegated admin relationship using [Create accessAssignments](../api/delegatedadm
```suggestion
To finalize the workflow for enabling AOBO (Admin-on-behalf-of) management of the customer's tenant, proceed by creating a new access assignment for the delegated admin relationship using the [Create accessAssignments](../api/delegatedadminrelationship-post-accessassignments.md) API. 
```

2023-08-01 03:07 UTC, Danielabom commented on api-reference/beta/resources/delegatedadminrelationships-api-overview.md
> +### Lifecycle of a GDAP Relationship Access Assignment
```suggestion
### Lifecycle of a GDAP relationship access assignment
```

2023-08-01 03:07 UTC, Danielabom commented on api-reference/beta/resources/delegatedadminrelationships-api-overview.md
> +The status of the Delegated Admin access assignment. The status transitions are as follows:
```suggestion
The status of the delegated admin access assignment. The status transitions are as follows:
```

2023-08-01 03:09 UTC, Danielabom commented on api-reference/beta/resources/delegatedadminrelationships-api-overview.md
> +![Delegated Admin access assignment status transition diagram](access-assignment-status-transitions.png)
```suggestion
![Delegated admin access assignment status transition diagram](access-assignment-status-transitions.png)
```

2023-08-01 03:10 UTC, Danielabom requested changes
@koravvams, please review my suggestions in the beta doc, and apply them in both versions. Thanks

2023-08-01 15:44 UTC, Danielabom commented on api-reference/v1.0/resources/delegatedadminrelationships-api-overview.md
> +Send the invitation link to the customer for them to approve the GDAP request. For example, `https://admin.microsoft.com/AdminPortal/Home#/partners/invitation/granularAdminRelationships/5d027261-d21f
```suggestion
Send the invitation link to the customer for them to approve the GDAP request. For example, `https://admin.microsoft.com/AdminPortal/Home#/partners/invitation/granularAdminRelationships/5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836` is an invitation link, where `5d027261-d21f-4aa9-b7db-7fa1f56fb163-8777b240-c6f0-4469-9e98-a3205431b836` is the admin relationship request ID.  Once the customer approves the GDAP request, the GDAP relationship will transition to an active state.
```

2023-08-01 15:45 UTC, Danielabom commented on api-reference/v1.0/resources/delegatedadminrelationships-api-overview.md
> +Next, to complete the workflow for enabling AOBO management of customer tenant, create new access assignment for this delegated admin relationship using [Create accessAssignments](../api/delegatedadm
```suggestion
To finalize the workflow for enabling AOBO (Admin-on-behalf-of) management of the customer's tenant, proceed by creating a new access assignment for the delegated admin relationship using the [Create accessAssignments](../api/delegatedadminrelationship-post-accessassignments.md) API. 
```

2023-08-01 15:46 UTC, Danielabom commented on api-reference/v1.0/resources/delegatedadminrelationships-api-overview.md
> +The status of the Delegated Admin access assignment. The status transitions are as follows:
```suggestion
The delegated admin access assignment goes through the following status transitions:
```

2023-08-01 15:46 UTC, Danielabom commented on api-reference/v1.0/resources/delegatedadminrelationships-api-overview.md
> +![Delegated Admin access assignment status transition diagram](access-assignment-status-transitions.png)
```suggestion
![Delegated admin access assignment status transition diagram](access-assignment-status-transitions.png)
```

2023-08-01 15:47 UTC, Danielabom approved these changes
@koravvams , I've applied all the suggested changes. PR approved.

2023-08-03 03:10 UTC, Lauragra commented on api-reference/beta/resources/delegatedadminrelationships-api-overview.md
> +![Delegated admin access assignment status transition diagram](access-assignment-status-transitions.png)
Global: The font color and size in the diagrams in these topics is faint and difficult to read. Consider updating the diagrams to be more readable. You can preview the topic here: https://review.learn.microsoft.com/en-us/graph/api/resources/delegatedadminrelationships-api-overview?view=graph-rest-beta&branch=pr-en-us-21631

Also note that for accessibility, any information conveyed in a diagram also needs to be available to a screen reader. In addition to providing the diagrams, please add text that describes the transitions. Note that readers who rely on a screen reader won't be able to read the numbers from the diagram and what the numbered lists correlate to won't be clear, so it will be helpful to elaborate.

2023-08-03 03:39 UTC, merged