Doc updates for user-to-group affiliation GA
microsoftgraph/microsoft-graph-docs pull request #21662
Opened 2023-06-15 07:31 UTC by clairechiu1004

Doc updates for groupPeerOutlierRecommendationInsightSettings and membershipOutlierInsight, with additional changes for any references to them. For user-to-group affiliation GA.

This docs PR is tracked via this work item  https://dev.azure.com/msft-skilling/Content/_queries/edit/111173/?triage=true

2023-06-21 06:50 UTC, FaithOmbongi commented
Reopening after accidental closure because of linked PR.

2023-06-21 17:53 UTC, FaithOmbongi requested changes
Hi @clairechiu1004 - I've left suggestions inline plus the following summary:
- GLOBAL: Remove all the `[!INCLUDE [accessreviews-disclaimer-v2](../../includes/accessreviews-disclaimer-v2.md)]` statements/lines from the v1.0 docs because the statement is useful in beta where we have two versions of the AR APIs side-by-side. There's only 1 version in v1.0 and therefore no room for confusion necessitating this disclaimer.
- Add the 2 new properties to the accessReviewScheduleSettings doc.
- Add the 1 new property to the accessReviewStageSettings doc.
- There's a missing relationship in your v1.0 schema - the **insights** nav property should be added to the **accessReviewInstanceDecisionItem** and that links to the **governanceInsight** and related objects. Please confirm if this is an oversight on the engineering side.
   - Otherwise, governanceInsight is currently hanging with no correlation to AR APIs except the fact that it's in the AR schema file.
   - After fixing the schema, update the doc.
- membershipOutlierInsight isn't in your v1.0 schema. Please check if that's an engineering oversight.
   - After fixing the schema, update the doc.
- GLOBAL: Rename all file names to all lowercase. For example usersignininsight.md and membershipoutlierinsight.md

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewset-post-definitions.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created se
Keep the asterisk around the property name so that the automation tools don't try to translate it.

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewset-post-definitions.md
> +| backupReviewers (deprecated) |[accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) collection| This property has been replaced by **fallbackReviewers**. However, specifying either
backupReviewers never made it to v1.0, so we shouldn't document it.
```suggestion
```

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewset-post-definitions.md
> +        "dayOfMonth": 5,
Good catch but still doesn't match the paragraph preceding the request where we say "It recurs on the third day of every quarter and continues indefinitely.". Can you align the three (the description, the request and the response)?

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewschedulesettings.md
> +description: "In the Azure AD access reviews feature, the `accessReviewScheduleSettings"
The previous description looks OK and complete. The new description leaves the reader hanging. Please confirm the change you wanted to make?

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewschedulesettings.md
> +[!INCLUDE [accessreviews-disclaimer-v2](../../includes/accessreviews-disclaimer-v2.md)]
The old version was only in beta so this note isn't needed in v1.0
```suggestion
```

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewschedulesettings.md
>  ## Properties
Document the two new properties related to insights: recommendationLookBackDuration and recommendationInsightSettings.

Make sure to update the JSON representation as well.

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/governanceinsight.md
> +---
The **insights** navigation property, whose return type is this entity **governanceInsight**, is missing from **accessReviewInstanceDecisionItem**. Please check if it's an engineering oversight.

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/usersigninInsight.md
> +| lastSignInDateTime | DateTimeOffset | Indicates when the user last signed in |
Also include the insightCreatedDateTime property that you inherited from governanceInsight. If the beta file is also missing this property, then that's an oversight in beta as well.

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/membershipOutlierInsight.md
According to your schema PR, this object isn't going to v1.0. Was this an engineering oversight?

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/governanceinsight.md
> ++ [membershipOutlierInsight](membershipoutlierinsight.md) derived type.
According to your schema PR, membershipOutlierInsight isn't in v1.0. Was this an engineering oversight?

2023-06-21 17:53 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the `recommendationInsightSettings` property to the [accessReviewStageSettings](https://learn.microsoft.com/en-us/graph/api/resources/accessReviewStageSettings?view=gr
You haven't documented these three new properties.

2023-06-21 17:53 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +        {
There are two possible oversights in your schema PR and because of those, you have two missing changelog objects (that weren't autogenerated):
-  **insights** nav property in the **accessReviewInstanceDecisionItem**
- membershipOutlierInsight  entity

Please look into those.

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/enums.md
> +| application |
Add unknownFutureValue

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/usersigninInsight.md
rename this file to all lowercase

2023-06-21 17:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/membershipOutlierInsight.md
Rename file name to all lowercase, please.

2023-06-26 16:33 UTC, FaithOmbongi commented
Close/reopen to trigger API doctor revalidation.

2023-06-26 17:13 UTC, FaithOmbongi commented
Closing/reopening for changelog link revalidation.

2023-06-26 17:16 UTC, FaithOmbongi approved these changes
Hi @clairechiu1004 - I only have one comment regrading the instance relationship in decisions. Please verify whether there was another oversight in the schema and address it accordingly.

Otherwise, approved with comments.

2023-06-26 17:16 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
> +| instance |[accessReviewInstance](accessreviewinstance.md) | There is exactly one accessReviewInstance associated with each decision. The instance is the parent of the decision item, representing th
There's no **instance** relationship for decisions in v1.0...though there was in beta. Was this another oversight?

<img width="509" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/fb95238f-ab9a-49f6-a245-65b25806c325">


Unless you're raising a schema PR to close this gap, please remove the insights relationship from this doc before setting this PR as ready to merge.

2023-06-27 16:56 UTC, clairechiu1004 commented on api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
> +| instance |[accessReviewInstance](accessreviewinstance.md) | There is exactly one accessReviewInstance associated with each decision. The instance is the parent of the decision item, representing th
Yes, there's no instance relationship in decisions in v1.0 (it's only there in beta). It was added to a beta as part of a private preview feature. Once that feature goes to GA, we can add this relationship in v1.0 as well, but it shouldn't be in v1.0 for now. I'll edit the docs accordingly now!

2023-06-27 17:04 UTC, clairechiu1004 commented
Closing and reopening for changelog validator

2023-06-27 17:04 UTC, clairechiu1004 commented
Reopening

2023-06-28 02:02 UTC, merged