Added details of synchronization bulk upload API
microsoftgraph/microsoft-graph-docs pull request #21691
Opened 2023-06-17 04:54 UTC by cmmdesai

2023-06-17 06:32 UTC, cmmdesai commented
We can proceed with the content review. Please hold the merge to the main branch as we'd like to time it so it aligns with our public preview announcement. Thanks!

2023-06-21 19:00 UTC, FaithOmbongi requested changes
Hi @cmmdesai - I've left a few suggestions inline plus the following summary:
- Add the bulkUpload relationship to the synchronizationJob entity.
- Rename synchronization-synchronizationjobbulkupload.md to _synchronization-bulkupload.md_.
- GAP: Document the new permissions in the [permissions reference : Synchronization permissions](https://learn.microsoft.com/en-us/graph/permissions-reference#synchronization-permissions).
- Document your changelog without replacing old records. Please refer to the authoring guidance for the process of copying the changelog from the schema PR and adding it to your docs PR.

2023-06-28 00:26 UTC, cmmdesai commented
@FaithOmbongi Thank you for the thorough review and feedback. I have incorporated the feedback and requested for another review.

2023-07-05 13:49 UTC, FaithOmbongi requested changes
Minor changes

2023-07-05 13:49 UTC, FaithOmbongi commented on changelog/Microsoft.IAM.json
> +      "SubArea": "Directory management"
```suggestion
      "WorkloadArea": "Applications",
      "SubArea": ""
```

2023-07-05 13:49 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronization-bulkupload.md
> +Represents the capability of the Azure AD synchronization service to process bulk uploads.
```suggestion
Represents the capability of the Azure AD synchronization service to process bulk uploads. The bulk upload should be compliant with the [SCIM bulk request](https://www.rfc-editor.org/rfc/rfc7644.html#section-3.7) format.
```

2023-07-06 04:32 UTC, merged