Export API to v1.0
microsoftgraph/microsoft-graph-docs pull request #21700
Opened 2023-06-19 11:41 UTC by vbhatt0211

2023-06-28 15:03 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +## Properties
The properties in the CSDL, the api.md, and this file don't match. Please clarify. Thanks.

2023-06-28 15:04 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +|[Get caseOperation](../api/security-caseoperation-get.md)|Resource | Please use the new **exportFileMetadata** property returned by the method to obtain downloadUrl,fileName and size of exported con
```suggestion
|[Get caseOperation](../api/security-caseoperation-get.md)|Resource | Please use the **exportFileMetadata** property returned by the method to obtain downloadUrl, fileName, and size of the exported content.|
```

2023-06-28 15:12 UTC, JarbasHorst commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +|[Get caseOperation](../api/security-caseoperation-get.md)|Resource | Read the properties and relationships of a [caseOperation](../resources/security-caseoperation.md) object. Please use the new **e
@vbhatt0211, is the following sentence required for this v1.0 version. I think that for the beta scenario it was relevant but there hasn't been any other option in v1.0 to obtain the following properties: downloadUrl, fileName and size. If this sentence is not needed, please remove it.

- Please use the new **exportFileMetadata** property returned by the method to obtain downloadUrl,fileName and size of exported content.

2023-06-28 15:13 UTC, Danielabom requested changes
@vbhatt0211, please add the changelog and address our comments. Thanks!

2023-06-28 15:21 UTC, vbhatt0211 commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +|[Get caseOperation](../api/security-caseoperation-get.md)|Resource | Read the properties and relationships of a [caseOperation](../resources/security-caseoperation.md) object. Please use the new **e
Updated the statement as  - "The **exportFileMetadata** property returned by the method will provide downloadUrl,fileName and size of exported content " 
This is new property json which will provide these details. Hence adding in description

2023-06-28 15:25 UTC, vbhatt0211 commented on api-reference/v1.0/api/security-ediscoveryreviewset-export.md
> +
Added

2023-06-28 16:53 UTC, vbhatt0211 commented on api-reference/v1.0/resources/security-ediscoveryexportfilemetadata.md
> +title: "ediscoveryExportFileMetadata resource type"
The reason is to easily differentiate in the file name. The property is still named as exportFileMetadata

2023-06-28 17:41 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/ediscoveryReviewSetQuery?view=graph-rest-1.0) method to the [ediscoveryReviewSetQuery](https://learn.microsoft.com/e
```suggestion
				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/ediscoveryReviewSetQuery?view=graph-rest-1.0) method to the [ediscoveryReviewSetQuery](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryreviewsetquery?view=graph-rest-1.0) resource.",
```

2023-06-28 17:56 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/ediscoveryReviewSet?view=graph-rest-1.0) method to the [ediscoveryReviewSet](https://learn.microsoft.com/en-us/graph
```suggestion
				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewsetquery-export?view=graph-rest-1.0) method to the [ediscoveryReviewSet](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryreviewsetquery?view=graph-rest-1.0) resource.",
```

2023-06-28 18:00 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewsetquery-export?view=graph-rest-1.0) method to the [ediscoveryReviewSet](https://learn.micr
```suggestion
				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewsetquery-export?view=graph-rest-1.0) method to the [ediscoveryReviewSet](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryreviewset?view=graph-rest-1.0) resource.",
```

2023-06-28 18:02 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Target": "ediscoveryReviewSet"
@vbhatt0211. Please add the ediscoveryReviewSet resource file to the PR and add the export method to the methods table. Notices that I have updated the links because they were incorrect.

2023-06-28 20:59 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewsetquery-export?view=graph-rest-1.0) method to the [ediscoveryReviewSet](https://learn.micr
```suggestion
				"Description": "Added the [export](https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewset-export?view=graph-rest-1.0) method to the [ediscoveryReviewSet](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryreviewset?view=graph-rest-1.0) resource.",
```

2023-06-28 20:59 UTC, Danielabom commented on api-reference/v1.0/api/security-ediscoveryreviewset-export.md
> +---
I do not see this change yet. @vbhatt0211

2023-06-28 21:12 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +|action|[microsoft.graph.security.caseAction](../resources/security-caseoperation.md#caseaction-values)| The type of action the operation represents. Possible values are: `addToReviewSet`,`applyTags`
I reviewed the operations and the api.md file indicates that the following properties (`outputName`, `description`, `outputFolderId`, `azureBlobContainer`, `azureBlobToken`, `exportOptions`, and `exportStructure`) are inherited from another resource, please add the sentence "Inherited from (resource name)" next to each property description.

2023-06-28 21:15 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +|directory|All files in a singe folder called NativeFiles.|
```suggestion
|directory|All files in a single folder called NativeFiles.|
```

2023-06-28 21:20 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"ChangedApiName": "ediscoveryExportOperation",
```suggestion
				"ChangedApiName": "ediscoveryExportFileMetadata",
```

2023-06-28 21:20 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Description": "Added the [ediscoveryExportOperation](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryExportOperation?view=graph-rest-1.0) resource",
```suggestion
				"Description": "Added the [ediscoveryExportFileMetadata](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryExportOperation?view=graph-rest-1.0) resource",
```

2023-06-28 21:22 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"ChangedApiName": "ediscoveryExportFileMetadata",
```suggestion
				"ChangedApiName": "ediscoveryExportOperation",
```

2023-06-28 21:22 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Description": "Added the [ediscoveryExportFileMetadata](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryexportfilemetadata?view=graph-rest-1.0) resource",
```suggestion
				"Description": "Added the [ediscoveryExportOperation](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryExportOperation?view=graph-rest-1.0) resource",
```

2023-06-28 21:24 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"ChangedApiName": "exportFileMetadata",
```suggestion
				"ChangedApiName": "ediscoveryExportFileMetadata",
```

2023-06-28 21:24 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Description": "Added the [exportFileMetadata](https://learn.microsoft.com/en-us/graph/api/resources/security-exportFileMetadata?view=graph-rest-1.0) resource type.",
```suggestion
				"Description": "Added the [ediscoveryExportFileMetadata](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoveryExportFileMetadata?view=graph-rest-1.0) resource type.",
```

2023-06-28 21:25 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"Target": "exportFileMetadata"
```suggestion
				"Target": "ediscoveryExportFileMetadata"
```

2023-06-28 21:32 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportfilemetadata.md
> +description: "Represents the file metadata for an export in eDiscovery."
```suggestion
description: "Represents the file metadata for an export in Microsoft Graph eDiscovery."
```

2023-06-28 23:03 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportfilemetadata.md
> +Represents the file metadata for an export in eDiscovery.
```suggestion
Represents the file metadata for an export in Microsoft Purview eDiscovery.
```

2023-06-28 23:04 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +Represents the process of an eDiscovery export.
```suggestion
Represents the process of a Microsoft Purview eDiscovery export.
```

2023-06-28 23:04 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +description: "Represents the process of an eDiscovery export."
```suggestion
description: "Represents the process of a Microsoft Purview eDiscovery export."
```

2023-06-28 23:06 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportfilemetadata.md
> +description: "Represents the file metadata for an export in  Microsoft Purview eDiscovery."
```suggestion
description: "Represents the file metadata for an export in Microsoft Purview eDiscovery."
```

2023-06-28 23:17 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"ApiChange": "Enumeration",
This enum does not exist in v1's metadata. You need to add it. Here's the wiki to add enums: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations

2023-06-28 23:17 UTC, Danielabom commented on changelog/Microsoft.Security.Ediscovery.json
> +				"ApiChange": "Enumeration",
This enum does not exist in v1's metadata. You need to add it. Here's the wiki to add enums: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations

2023-06-28 23:24 UTC, Danielabom commented on api-reference/v1.0/api/security-caseoperation-get.md
> +**Note:** In case of export case operation, you will  receive the downloadURL, fileName and size in the exportfileMetadata property of the response. The actual operation where you will initiate the d
```suggestion
**Note:** In the case of the export case operation, you will receive the downloadURL, fileName, and size in the exportfileMetadata property of the response. The operation where you will initiate the download is managed on your side. You may download it to your local machine or export it to your storage account.
```

2023-06-28 23:24 UTC, Danielabom commented on api-reference/v1.0/api/security-caseoperation-get.md
> +In order to avoid the interactive sign-in page and fully automate the process, please follow the following steps
```suggestion
To avoid the interactive sign-in page and fully automate the process, please follow the following steps:
```

2023-06-28 23:25 UTC, Danielabom commented on api-reference/v1.0/api/security-caseoperation-get.md
> +1. Provision the MicrosoftPurviewEDiscovery application by leveraging [Create ServicePrincpal](../api/serviceprincipal-post-serviceprincipals.md) for the application id b26e684c-5068-4120-a679-64a5d2
```suggestion
1. Provision the Microsoft Purview eDiscovery application by leveraging [Create ServicePrincpal](../api/serviceprincipal-post-serviceprincipals.md) for the application id b26e684c-5068-4120-a679-64a5d2c909d9
```

2023-06-28 23:30 UTC, Danielabom commented on api-reference/v1.0/api/security-caseoperation-get.md
> +2. After provisioning, please raise request for user delegated permission of ediscovery.Download.Read for the above application from your third party application which you would be using for the grap
```suggestion
2.Once the application is provisioned, request user-delegated permissions for discovery.Download.Read from the tenant admin. This request should be made from your third-party application interacting with Microsoft Graph.
```

2023-06-28 23:30 UTC, Danielabom commented on api-reference/v1.0/api/security-caseoperation-get.md
> +3. Ensure the tenant admin approve the request
```suggestion
3. Make sure the tenant admin approves the request
```

2023-06-28 23:31 UTC, Danielabom commented on api-reference/v1.0/api/security-caseoperation-get.md
> +4. Now, you can add the scope for the application to your existing scope in the script and ensure the headers allow ("X-AllowWithAADToken", "true");
```suggestion
4. Add the scope for the application to your existing script and make sure the headers include ("X-AllowWithAADToken", "true");. 
```

2023-06-28 23:31 UTC, Danielabom commented on api-reference/v1.0/api/security-caseoperation-get.md
> +With these steps, user authorisation will take place in the automated manner and you will not receive manual interactive sign in page.
```suggestion
By following these steps, the user authorization process will be automated, and you won't encounter a manual interactive sign-in page.
```

2023-06-28 23:38 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +# ediscoveryExportOperation resource type
Please add this resource to the TOC.

2023-06-28 23:47 UTC, Danielabom requested changes
@vbhatt0211 , please note that:
I've fixed the build issues.
Updated the changelog with the correct links.
Made several changes in the files and left some suggestions for you to commit.
However, there are some things that you must address: 
 Add ediscoveryReviewSet resource file to the PR and its method. 
The enums do not exist in v1's metadata. In the comments, I added a wiki with the steps to add them. 
Add the ediscoveryExportOperation resource in the TOC (v1). I did not find it beta's TOC either. So, please fix that or explain what Jarbas commented about the names. 
I reviewed the operations, and the api.md file indicates that the following properties (outputName, description, outputFolderId, azureBlobContainer, azureBlobToken, exportOptions, and exportStructure) are inherited from another resource; please add the sentence "Inherited from (resource name)" next to each property description.
I completely modified the note in the GET operation file (V1); please add the resource file published in beta and update the note accordingly. 
Run a punctuation review. Sentences must end with a period.

2023-06-29 13:55 UTC, vbhatt0211 commented on changelog/Microsoft.Security.Ediscovery.json
> +				"ApiChange": "Enumeration",
These enums are present in the security-ediscoveryexportoperation.md under v1.0 resources folder.

2023-06-29 13:55 UTC, vbhatt0211 commented on changelog/Microsoft.Security.Ediscovery.json
> +				"ApiChange": "Enumeration",
These enums are present in the security-ediscoveryexportoperation.md under v1.0 resources folder.

2023-06-30 18:12 UTC, Danielabom commented on api-reference/v1.0/resources/security-ediscoveryexportoperation.md
> +# ediscoveryExportOperation resource type
@Lauragra, the author mentioned: I have not added this as the export is still not an independent resource; export is being used through review set and review set query. Advise me on what should be the ideal scenario.

2023-06-30 18:12 UTC, Danielabom approved these changes
PR approved.

2023-07-03 17:18 UTC, Danielabom commented on api-reference/v1.0/api/security-ediscoveryreviewsetquery-export.md
> +``
```suggestion
```
```

2023-07-03 18:25 UTC, Danielabom commented on api-reference/v1.0/api/security-ediscoveryreviewsetquery-export.md
> +HTTP/1.1 202 Accepted
```

2023-07-06 04:31 UTC, merged