EM - Auto Assignment - More granular settings
microsoftgraph/microsoft-graph-docs pull request #21740
Opened 2023-06-21 00:40 UTC by fsheik

2023-06-22 19:25 UTC, FaithOmbongi requested changes
Hi @fsheik - The doc changes look good. The changelog changes not so. Please use the autogenerated changelog or if you missed the window to download it, refer to the guidance for the structure of new properties.

2023-06-22 19:25 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +          "Description": "Added the **removeAccessWhenTargetLeavesAllowedTargets** and **gracePeriodBeforeAccessRemoval** properties to [accessPackageAutomaticRequestSettings](https://learn.microsoft
This changelog is incorrect. Please use the autogenerated changelog or if you missed the window to download it, refer to the guidance for the structure of new properties.

2023-06-26 22:41 UTC, fsheik commented on changelog/Microsoft.IGAELM.json
> +          "Description": "Added the **removeAccessWhenTargetLeavesAllowedTargets** and **gracePeriodBeforeAccessRemoval** properties to [accessPackageAutomaticRequestSettings](https://learn.microsoft
Hello @FaithOmbongi - I'm not sure what is missing in this changelog change, can you please point me relevant documentation?

2023-06-27 07:48 UTC, FaithOmbongi approved these changes
Hi @fsheik - I've left two suggestions for minor fixes and then approved your PR. Please resolve those before merging your PR.

Approved with comments.

2023-06-28 02:00 UTC, merged