Added docs for Permanently deleting a drive item.
microsoftgraph/microsoft-graph-docs pull request #21780
Opened 2023-06-23 11:16 UTC by MahaGoyal

Added docs for Permanently deleting a drive item.

2023-06-23 13:17 UTC, MahaGoyal commented
ReadyForReview

2023-06-23 13:19 UTC, MahaGoyal commented
ReadyForReview

2023-07-10 18:59 UTC, MahaGoyal commented
@microsoft-github-policy-service agree company="Microsoft"

2023-07-10 18:59 UTC, MahaGoyal commented
Hi,

Yes I agree to CLA. Please find the required information below:

@microsoft-github-policy-service agree company="Microsoft"

Thanks,
Mahak
________________________________
From: microsoft-github-policy-service[bot] ***@***.***>
Sent: Tuesday, July 11, 2023 12:20 AM
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Mahak Goyal ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoftgraph/microsoft-graph-docs] Added docs for Permanently deleting a drive item. (PR #21780)


@MahaGoyal<https://github.com/MahaGoyal> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree [company="{your company}"]


Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree


  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"


Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement (“Agreement”) is agreed to by the party signing below (“You”),
and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your
contributions to Microsoft open source projects. This Agreement is effective as of the latest signature
date below.

  1.  Definitions.
“Code” means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to Microsoft under this Agreement.
“Project” means any of the projects owned or managed by Microsoft and offered under a license
approved by the Open Source Initiative (www.opensource.org<http://www.opensource.org/>).
“Submit” is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”
“Submission” means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.
  2.  Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.
  3.  Originality of Work. You represent that each of Your Submissions is entirely Your original work.
Should You wish to Submit materials that are not Your original work, You may Submit them separately
to the Project if You (a) retain all copyright and license information that was in the materials as You
received them, (b) in the description accompanying Your Submission, include the phrase “Submission
containing materials of a third party:” followed by the names of the third party and any licenses or other
restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
guidelines concerning Submissions.
  4.  Your Employer. References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.
  5.  Licenses.

  *   Copyright License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
parties.
  *   Patent License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.
  *   Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

  1.  Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
  2.  Notice to Microsoft. You agree to notify Microsoft in writing of any facts or circumstances of which
You later become aware that would make Your representations in this Agreement inaccurate in any
respect.
  3.  Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.
  4.  Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
defenses of lack of personal jurisdiction and forum non-conveniens.
  5.  Entire Agreement/Assignment. This Agreement is the entire agreement between the parties, and
supersedes any and all prior agreements, understandings or communications, written or oral, between
the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

—
Reply to this email dire [...]

2023-07-10 18:59 UTC, MahaGoyal commented
ReadyForReview

2023-07-11 08:25 UTC, MahaGoyal commented
ReadyForReview

2023-07-17 17:51 UTC, Danielabom commented
Hi @MahaGoyal, I contacted you via Teams. Please remove the snippets from the PR, as they will be automatically generated. Thanks.

2023-07-18 06:48 UTC, MahaGoyal commented
> Hi @MahaGoyal, I contacted you via Teams. Please remove the snippets from the PR, as they will be automatically generated. Thanks.
 Hi @Danielabom , Could you please specify which snippets you want me to remove. I havn't added anything explicitely, but please let me know if something got added.

2023-07-21 18:31 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [permanentDelete] method to the [driveItem] [DriveItem-beta] resource.",
Please follow example 7 on this wiki and update the description accordingly: [Changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-07-21 18:32 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [permanentDelete] method to the [driveItem] [DriveItem-beta] resource.",
Please follow example 7 on this wiki and update the description accordingly: [Changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2023-07-21 18:45 UTC, Danielabom commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +title: Permanently delete a file or folder
```suggestion
title: Permanently delete a file or folder.
```

2023-07-21 18:46 UTC, Danielabom commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +description: "Permanently delete a DriveItem by using its ID."
```suggestion
description: "Permanently delete a driveItem by using its ID."
```

2023-07-21 18:48 UTC, Danielabom commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +# Permanently delete a DriveItem
```suggestion
# Permanently delete a driveItem
```

2023-07-22 00:33 UTC, Danielabom commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +Note that deleting items using this method will be permanently deleted and won't go to recycleBin. Hence can't be restored.
```suggestion
Note that if you delete items using this method, they will be permanently removed and won't be sent to the recycle bin. Therefore, they cannot be restored afterward.
```

2023-07-22 00:36 UTC, Danielabom commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +---
Filenames must be in lowercase.

2023-07-22 00:38 UTC, Danielabom requested changes
@MahaGoyal, I've added comments in the v1 files, but please apply those changes to the beta files as well. Thanks!

2023-07-23 19:43 UTC, MahaGoyal commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [permanentDelete] method to the [driveItem] [DriveItem-beta] resource.",
Actually it was giving link error with format given in wiki as link generated was not present. So I removed the links. Is there any way these links can be validated ?

2023-07-23 19:51 UTC, MahaGoyal commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +---
Done. Thanks

2023-07-23 19:51 UTC, MahaGoyal commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +Note that deleting items using this method will be permanently deleted and won't go to recycleBin. Hence can't be restored.
Done

2023-07-23 19:51 UTC, MahaGoyal commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +# Permanently delete a DriveItem
Done

2023-07-23 19:51 UTC, MahaGoyal commented on api-reference/v1.0/api/driveitem-permanentDelete.md
> +description: "Permanently delete a DriveItem by using its ID."
Done

2023-07-23 19:52 UTC, MahaGoyal commented
> @MahaGoyal, I've added comments in the v1 files, but please apply those changes to the beta files as well. Thanks!

Done. Thanks.

2023-07-23 19:53 UTC, MahaGoyal commented
#feedback-addressed

2023-07-25 19:09 UTC, MahaGoyal commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [permanentDelete] method to the [driveItem] [DriveItem-beta] resource.",
Done I've made the changes, and added required links in changeLog changes.

2023-07-26 05:52 UTC, MahaGoyal commented
It was closed by mistake.

2023-07-26 15:04 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [permanentDelete](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-beta) method to the [driveItem](https://learn.microsoft.com/en-us/graph/api
```suggestion
          "Description": "Added the [permanentDelete](https://learn.microsoft.com/en-us/graph/api/permanentDelete?view=graph-rest-beta) method to the [driveItem](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-beta) resource.",
```

2023-07-26 15:05 UTC, Danielabom commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [permanentDelete](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-1.0) method to the [driveItem](https://learn.microsoft.com/en-us/graph/api/
```suggestion
          "Description": "Added the [permanentDelete](https://learn.microsoft.com/en-us/graph/api/permanentDelete?view=graph-rest-1.0) method to the [driveItem](https://learn.microsoft.com/en-us/graph/api/driveItem?view=graph-rest-1.0) resource.",
```

2023-07-27 04:16 UTC, Lauragra commented on api-reference/beta/api/driveitem-permanentdelete.md
> +# Permanently delete a driveItem
The title and H1 should be driveItem: permanentDelete.

2023-07-27 04:16 UTC, Lauragra commented on api-reference/beta/api/driveitem-permanentdelete.md
> +Permanently deletes a [DriveItem](../resources/driveitem.md) by using its ID.
Revise as: 
Permanently delete a [driveItem](../resources/driveitem.md) by using its ID.

2023-07-27 04:17 UTC, Lauragra commented on api-reference/beta/api/driveitem-permanentdelete.md
> +Here is an example of how to call this API.
Revise as: The following example shows how to call this API.

2023-07-27 04:18 UTC, Lauragra commented on api-reference/beta/api/driveitem-permanentdelete.md
> +
Add an H3 Request.

2023-07-27 04:18 UTC, Lauragra commented on api-reference/beta/api/driveitem-permanentdelete.md
> +See [Error Responses][error-response] for more info about
Revise as: For details about how errors are returned, see [Error responses](error-response).

2023-07-27 04:19 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-permanentdelete.md
> +# Permanently delete a driveItem
Please apply the same fixes to the v1.0 topic.

2023-07-27 05:29 UTC, Lauragra approved these changes

2023-07-28 03:50 UTC, merged