[CloudPC] Added GetInaccessibleCloudPcReports API.
microsoftgraph/microsoft-graph-docs pull request #21823
Opened 2023-06-27 02:28 UTC by guanchenga

Roadmap Id: 18012

2023-06-27 03:01 UTC, AshleyYangSZ requested changes

2023-06-27 03:01 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcreports-getInaccessibleCloudPcReports.md
> +POST /deviceManagement/virtualEndpoint/reports/getTotalAggregatedRemoteConnectionReports
getInaccessibleCloudPcReports

2023-06-27 03:01 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcreports-getInaccessibleCloudPcReports.md
> +  "name": "cloudpcreportsthis.gettotalaggregatedremoteconnectionreports"
getInaccessibleCloudPcReports

2023-06-27 03:17 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +            - name: Get inaccessible Cloud PC reports
The methods except CRUD should be sorted alphabetically, so please place it before `- name: Get real time remote connection latency`

2023-06-27 03:20 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcreports.md
> +|[getInaccessibleCloudPcReports](../api/cloudpcreports-getinaccessiblecloudpcreports.md)|Stream|Get the details of inaccessible Cloud PCs，like **deviceHealthStatus**, **recentDeviceHealthFailureCount
```suggestion
|[getInaccessibleCloudPcReports](../api/cloudpcreports-getinaccessiblecloudpcreports.md)|Stream|Get the details of inaccessible Cloud PCs reports，like **deviceHealthStatus**, **recentDeviceHealthFailureCount**, **recentConnectionFailureCount** and **systemStatus**.|
```

2023-06-27 03:21 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcreports.md
> +|[getInaccessibleCloudPcReports](../api/cloudpcreports-getinaccessiblecloudpcreports.md)|Stream|Get the details of inaccessible Cloud PCs，like **deviceHealthStatus**, **recentDeviceHealthFailureCount
Also, please place it before `|[getRealTimeRemoteConnectionLatency]` to make sure the alphabetical order.

2023-06-27 03:22 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcreports-getInaccessibleCloudPcReports.md
> +Definition of "Inaccessible Cloud PC": A Cloud PC is in unavailable state(at least one of health checks is failed) or has consecutive user connection failures.
```suggestion
Definition of "Inaccessible Cloud PC": A Cloud PC is in unavailable state(at least one of health checks failed) or has consecutive user connection failure.
```

2023-06-27 03:23 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcreports-getInaccessibleCloudPcReports.md
> +# [HTTP](#tab/http)
Please remove this line since it'll be automatically generated by tool once your PR checks in.

2023-06-27 03:24 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcreports-getInaccessibleCloudPcReports.md
> +>**Note:** The response object shown here might be shortened for readability.
Remove it.

2023-06-27 03:25 UTC, RuiHou105 requested changes
@guanchenga  Please resolve comments in this PR, thanks.

2023-07-04 04:51 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +      "WorkloadArea": "Devices and apps",
```suggestion
      "WorkloadArea": "Devices and app management",
```

2023-07-12 04:52 UTC, JarbasHorst commented
Hi @Lauragra, this PR is ready for final review.

2023-07-17 02:58 UTC, AshleyYangSZ approved these changes

2023-07-17 02:58 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcreports-getinaccessiblecloudpcreports.md
> +author: "AshleyYangSZ"
Please put your GitHub name here.

2023-07-17 03:03 UTC, RuiHou105 commented
@guanchenga  Also need to include `inaccessibleCloudPcReports `enum member ?

2023-07-17 03:14 UTC, RuiHou105 approved these changes

2023-07-18 03:03 UTC, guanchenga commented
Hi @Jarbas-MSFT could you help review?

2023-07-18 03:49 UTC, JarbasHorst commented
Hi @guanchenga, I am done with my content review work for this PR. My colleague, Laura Graham, will final review this PR before she can approve/merge it.

2023-07-20 02:04 UTC, guanchenga commented
Hi @Lauragra , clould you help review this PR?

2023-07-28 03:26 UTC, Lauragra approved these changes

2023-08-01 02:43 UTC, merged