initial revision - resources
microsoftgraph/microsoft-graph-docs pull request #21821
Opened 2023-06-26 17:58 UTC by markwahl-msft

2023-07-10 16:12 UTC, markwahl-msft commented
> Hi @markwahl-msft - Please file an ADO work item for this docs PR https://aka.ms/msgraph-identity-workitem. Thanks.

User story 124121.

2023-07-14 15:56 UTC, FaithOmbongi requested changes
Hi @markwahl-msft - I've left suggestions for minor updates plus the following:
- Document the **resources** relationship in entitlementmanagement.md
- I see some docs are assigned to hanki-microsoft but I don't see the alias in the system. There are only 5 instances in the repo. Please reassign them to an active owner.

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageresource.md
> +In [Azure AD Entitlement Management](entitlementmanagement-overview.md), an access package resource is a reference to a resource associated with an access package catalog. The roles for the access pa
```suggestion
In [Azure AD entitlement management](entitlementmanagement-overview.md), an access package resource is a reference to a resource associated with an access package catalog. The roles for the access package resource can be used in one or more access packages.  To request to associate a resource with an access package catalog, or remove a resource from a catalog, create an [accessPackageResourceRequest](accesspackageresourcerequest.md).
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackagecatalog-list-resources.md
> +```msgraph-interactive
GLOBAL: Please use `http` instead of `msgraph-interactive` for any requests that contain IDs that are specific to the tenant. For such requests, the user wouldn't be able to try the query because they don't have a correct ID.

We automated the updates of many docs a few months ago but seems we might have missed some because beta still has the "Try it" experience.

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +description: "An access package resource request is a request to a add a resource to a catalog so that the roles of the resource can be used in one or more of the catalog's access packages."
```suggestion
description: "An access package resource request is a request to add a resource to a catalog so that the roles of the resource can be used in one or more of the catalog's access packages."
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +|catalog|[accessPackageCatalog](accesspackagecatalog.md)| Read-only.|
nit - alphabetical order
```suggestion
|catalog|[accessPackageCatalog](accesspackagecatalog.md)| Read-only.|
|resource|[accessPackageResource](accesspackageresource.md)| Nullable.|
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +## JSON representatio
```suggestion
## JSON representation
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +| [Create accessPackageResourceRequest](../api/entitlementmanagement-post-resourcerequests.md) | [accessPackageCatalog](accesspackageresourcerequest.md) | Create a new **accessPackageResourceRequest*
```suggestion
| [Create accessPackageResourceRequest](../api/entitlementmanagement-post-resourcerequests.md) | [accessPackageCatalog](accesspackageresourcerequest.md) | Add, update, or remove a **accessPackageResourceRequest** object from a catalog. |
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageresourceenvironment.md
> +In [Azure AD Entitlement Management](entitlementmanagement-overview.md), an access package resource environment is a reference to the geolocation environment in which a resource is located. This envi
```suggestion
In [Azure AD entitlement management](entitlementmanagement-overview.md), an access package resource environment is a reference to the geolocation environment in which a resource is located. This environment is automatically provided as part of Azure AD entitlement management. The API is only applicable to Multi-Geo SharePoint Online sites.
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackage-list-resourcerolescopes.md
> +# List accessPackageResourceRoleScopes
nit
```suggestion
title: "List resourceRoleScopes"
description: "Retrieve a list of accesspackageresourcerolescope objects."
ms.localizationpriority: medium
author: "markwahl-msft"
ms.prod: "governance"
doc_type: "apiPageType"
---

# List resourceRoleScopes
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackage-post-resourcerolescopes.md
> +# Create accessPackageResourceRoleScope
```suggestion
title: "Create resourceRoleScope"
description: "Create a new accessPackageResourceRoleScope for adding a resource role to an access package."
ms.localizationpriority: medium
author: "markwahl-msft"
ms.prod: "governance"
doc_type: "apiPageType"
---

# Create resourceRoleScope
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackage-delete-resourcerolescopes.md
> +# Remove resourceRoleScope from resourceRoleScopes
```suggestion
title: "Remove resourceRoleScope from an accessPackage"
description: "Remove a resourceRoleScope from an access package."
ms.localizationpriority: medium
author: "markwahl-msft"
ms.prod: "governance"
doc_type: "apiPageType"
---

# Remove resourceRoleScope from an accessPackage
```

2023-07-14 15:56 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +                      - name: List resource role scopes
General comment (applies to both beta + v1.0): We should have surfaced the key entities in the TOC alongside their methods and not just the methods for roleScopes, resources, resourceRoles. Similar to what you have for resource environment below.

2023-07-14 15:56 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +            "Description": "Added the **resourceRequests** relationship on [entitlementManagement](https://learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0) res
```suggestion
            "Description": "Added the **resourceRoleScopes** relationship to the [accessPackage](https://learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0) resource.",
            "Target": "accessPackage"
          },
          {
            "Id": "9e91b305-975d-46fa-b322-88e522ed5256",
            "ApiChange": "Relationship",
            "ChangedApiName": "resourceEnvironments",
            "ChangeType": "Addition",
            "Description": "Added the **resourceEnvironments** relationship to the [entitlementManagement](https://learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0) resource.",
            "Target": "entitlementManagement"
          },
          {
            "Id": "9e91b305-975d-46fa-b322-88e522ed5256",
            "ApiChange": "Relationship",
            "ChangedApiName": "resourceRequests",
            "ChangeType": "Addition",
            "Description": "Added the **resourceRequests** relationship to the [entitlementManagement](https://learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0) resource.",
```

2023-07-19 21:39 UTC, markwahl-msft commented on api-reference/v1.0/resources/entitlementmanagement.md
> +|resourceEnvironments|[accessPackageResourceEnvironment](../resources/accesspackageresourceenvironment.md) collection| A reference to the geolocation environments in which a resource is located.|
thanks, added.

2023-07-19 21:43 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageresource.md
> +In [Azure AD Entitlement Management](entitlementmanagement-overview.md), an access package resource is a reference to a resource associated with an access package catalog. The roles for the access pa
updated capitalization, thanks.

2023-07-19 21:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +description: "An access package resource request is a request to a add a resource to a catalog so that the roles of the resource can be used in one or more of the catalog's access packages."
updated, thanks

2023-07-19 21:46 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +|catalog|[accessPackageCatalog](accesspackagecatalog.md)| Read-only.|
updated

2023-07-19 21:52 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +| [Create accessPackageResourceRequest](../api/entitlementmanagement-post-resourcerequests.md) | [accessPackageCatalog](accesspackageresourcerequest.md) | Create a new **accessPackageResourceRequest*
updated description

2023-07-19 21:52 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageresourceenvironment.md
> +In [Azure AD Entitlement Management](entitlementmanagement-overview.md), an access package resource environment is a reference to the geolocation environment in which a resource is located. This envi
updated capitalization

2023-07-19 21:53 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackageresourcerequest.md
> +## JSON representatio
fixed, thanks

2023-07-19 21:54 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackagecatalog-list-resources.md
> +```msgraph-interactive
removed.

2023-07-19 21:58 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackagecatalog-list-resourceroles.md
> +This method uses OData query parameters to construct the response. For general information, see [OData query parameters](/graph/query-parameters).
updated to include the specific query parameters.

2023-07-19 22:04 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackage-list-resourcerolescopes.md
> +# List accessPackageResourceRoleScopes
updated

2023-07-19 22:04 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackage-post-resourcerolescopes.md
> +# Create accessPackageResourceRoleScope
updated

2023-07-19 22:05 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackage-delete-resourcerolescopes.md
> +# Remove resourceRoleScope from resourceRoleScopes
updated

2023-07-19 22:30 UTC, markwahl-msft commented on api-reference/v1.0/toc.yml
> +                      - name: List resource role scopes
This PR was using the same structure as in beta so that when a user moved the switch between beta and v1 the docs would be as similar as possible.   If changes are needed for beta, I'd prefer to do a refresh of the beta and v1 TOCs in a separate doc PR, so as to not delay getting the basic articles for this v1 new API.

2023-07-27 07:58 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +                      - name: List resource role scopes
OK, please remember to raise a follow up PR to clean up both TOCs.

2023-07-27 07:59 UTC, FaithOmbongi approved these changes
.@markwahl-msft LGTM! Please remember to raise a follow-up PR to clean up the TOC and provide comprehensive examples.

2023-07-28 16:04 UTC, merged