Update TOC to include SLA
microsoftgraph/microsoft-graph-docs pull request #21990
Opened 2023-07-11 00:10 UTC by jamesw-msft

Update TOC to include SLA

2023-07-11 16:02 UTC, msewaweru requested changes
@jamesw-msft - See my comment below for your action.

2023-07-13 15:43 UTC, msewaweru approved these changes
@jamesw-msft -LGTM! Thanks.

2023-07-14 01:32 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: Service Level Agreement attainment
Per our guidelines, we don't surface complex types in the TOC. I think here the TOC structure can simply be:

Azure AD authentication
    Get

Also note that per our guidelines, we use sentence case in the TOC, so only the first letter is capitalized except for proper nouns.

2023-07-14 17:56 UTC, jamesw-msft commented on api-reference/beta/toc.yml
> +          - name: Service Level Agreement attainment
Removed the complex type and fixed the casing per our chat offline.

2023-07-15 02:31 UTC, merged