Add Host Pairs
microsoftgraph/microsoft-graph-docs pull request #22038
Opened 2023-07-12 20:39 UTC by jakedavies-microsoft

Updates docs to include Host Pairs

2023-07-13 13:14 UTC, joerattazzi-microsoft commented on api-reference/beta/toc.yml
> +          - name: List
`List host pairs for a host`

We need to call it out explicitly. Just saying `List` here indicates we're supporting `/security/threatIntelligence/hostPairs` to get a list of all host pairs (which we're not).

2023-07-13 13:17 UTC, joerattazzi-microsoft commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +If successful, this method returns a `200 OK` response code and a collection of [hostPair](../resources/security-hostpair.md) objects in the response body.
Can you make the `[hostPair]` fully qualified, please? so - `[microsoft.graph.security.hostPair](...)`

Rule of thumb we've gotten:
> Note that we don't spell out the fully qualified name in the summary section; we do in the Response section and anywhere that we list a return type

2023-07-13 14:28 UTC, joerattazzi-microsoft commented on api-reference/beta/resources/security-threatintelligence.md
> +|[List childHostPairs](../api/security-host-list-childhostpairs.md)|[microsoft.graph.security.host](../resources/security-hostpair.md) |Get a list of **hostPair** resources for the host, where that h
not sure we need to call out the APIs that go  through host. Those would be called out as part of the host page (like you have it)

2023-07-13 14:29 UTC, joerattazzi-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [hostPair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostPair?view=graph-rest-beta) resource",
Doc team asks for periods (`.`) at the of all of these, please.

2023-07-13 16:03 UTC, jakedavies-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [hostPair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostPair?view=graph-rest-beta) resource",
Updated

2023-07-13 16:03 UTC, jakedavies-microsoft commented on api-reference/beta/resources/security-threatintelligence.md
> +|[List childHostPairs](../api/security-host-list-childhostpairs.md)|[microsoft.graph.security.host](../resources/security-hostpair.md) |Get a list of **hostPair** resources for the host, where that h
Updated

2023-07-13 16:04 UTC, jakedavies-microsoft commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +If successful, this method returns a `200 OK` response code and a collection of [hostPair](../resources/security-hostpair.md) objects in the response body.
Updated

2023-07-13 16:04 UTC, jakedavies-microsoft commented on api-reference/beta/toc.yml
> +          - name: List
Updated

2023-07-14 20:07 UTC, jakedavies-microsoft commented
The validation is saying that my name is not real. I'm pretty sure it is, and I've tried a couple different fixes, but am at a loss. Open to any and all suggestions...

2023-07-21 02:24 UTC, joerattazzi-microsoft commented on api-reference/beta/resources/security-hostpair.md
> +|[List parentHostPairs for a host](../api/security-host-list-hostpairs.md)|[microsoft.graph.security.hostPair](../resources/security-hostpair.md) collection|Get a list of the [microsoft.graph.securit
For the Description fields - can you remove the full qualification, please? I have that wrong in the examples we're using

2023-07-21 02:24 UTC, joerattazzi-microsoft approved these changes

2023-07-21 15:28 UTC, jakedavies-microsoft commented on api-reference/beta/resources/security-hostpair.md
> +|[List parentHostPairs for a host](../api/security-host-list-hostpairs.md)|[microsoft.graph.security.hostPair](../resources/security-hostpair.md) collection|Get a list of the [microsoft.graph.securit
Updated to reflect!

2023-07-22 03:16 UTC, Danielabom commented
Contacted author to get info.

2023-07-25 23:39 UTC, nblankenau approved these changes

2023-07-26 15:48 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-07-26 15:49 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-07-26 15:49 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **hostPairs** relationship to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
```suggestion
          "Description": "Added the **hostPairs** navigation property to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
```

2023-07-26 15:50 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-07-26 15:50 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **parentHostPairs** relationship to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
```suggestion
          "Description": "Added the **parentHostPairs** navigation property to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
```

2023-07-26 15:51 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Relationship",
```

2023-07-26 15:52 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **hostPairs** relationship to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatIntelligence?view=graph-rest-beta) reso
```suggestion
          "Description": "Added the **hostPairs** navigation property to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatIntelligence?view=graph-rest-beta) resource.",
```

2023-07-26 15:59 UTC, Danielabom commented on api-reference/beta/api/security-host-list-parentHostPairs.md
> +---
All the filenames must be in lowercase.

2023-07-26 16:10 UTC, Danielabom commented on api-reference/beta/resources/security-hostpair.md
> +description: "Represents a pair of parent and child hosts where the child-host was able to be reached via the parent-host"
```suggestion
description: "Represents a pair of parent-child hosts in which the child host is reachable via the parent-host"
```

2023-07-26 16:15 UTC, Danielabom commented on api-reference/beta/resources/security-hostpair.md
> +Represents a pair of parent and child hosts where the child host was able to be reached via the parent host. For example, if contoso.com redirects to microsoft.com, then contoso.com would be the pare
```suggestion
Represents a pair of parent-child hosts in which the child host is reachable via the parent host. For example, if contoso.com redirects to microsoft.com, then contoso.com would be the parent host and microsoft.com the child host.
```

2023-07-26 17:35 UTC, Danielabom commented on api-reference/beta/resources/security-hostpair.md
> +|linkKind|String|The reason the two hosts were identified as hostPairs.|
```suggestion
|linkKind|String|The reason the two hosts are identified as hostPairs.|
```

2023-07-26 17:40 UTC, Danielabom commented on api-reference/beta/api/security-hostpair-get.md
> +description: "Read the properties and relationships of a microsoft.graph.security.hostPair object."
```suggestion
description: "Read the properties and relationships of a Microsoft Graph Security hostPair object."
```

2023-07-26 20:03 UTC, Danielabom requested changes
Thank you for working on this PR, @jakedavies-microsoft . Please see my comments and feel free to apply my comments where needed.

2023-07-27 18:13 UTC, jakedavies-microsoft commented on api-reference/beta/api/security-hostpair-get.md
> +description: "Read the properties and relationships of a microsoft.graph.security.hostPair object."
Updated to reflect suggested change

2023-07-27 18:13 UTC, jakedavies-microsoft commented on api-reference/beta/resources/security-hostpair.md
> +Represents a pair of parent and child hosts where the child host was able to be reached via the parent host. For example, if contoso.com redirects to microsoft.com, then contoso.com would be the pare
Updated to reflect suggested change

2023-07-27 18:13 UTC, jakedavies-microsoft commented on api-reference/beta/resources/security-hostpair.md
> +description: "Represents a pair of parent and child hosts where the child-host was able to be reached via the parent-host"
Updated to reflect suggested change

2023-07-27 18:13 UTC, jakedavies-microsoft commented on api-reference/beta/api/security-host-list-parentHostPairs.md
> +---
Updated to reflect suggestion

2023-07-27 18:14 UTC, jakedavies-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **hostPairs** relationship to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatIntelligence?view=graph-rest-beta) reso
Updated to reflect suggested change

2023-07-27 18:14 UTC, jakedavies-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "ApiChange": "Resource",
Updated to reflect suggested change

2023-07-27 18:14 UTC, jakedavies-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **parentHostPairs** relationship to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
Updated to reflect suggested change

2023-07-27 18:14 UTC, jakedavies-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "ApiChange": "Resource",
Updated to reflect suggested change

2023-07-27 18:14 UTC, jakedavies-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **hostPairs** relationship to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
Updated to reflect suggested change

2023-07-27 18:14 UTC, jakedavies-microsoft commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **childHostPairs** relationship to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
Updated to reflect suggested change

2023-07-28 15:20 UTC, jakedavies-microsoft commented
@Danielabom Thank you for the feedback. I've addressed it and updated the PR to reflect. Please let me know if there is anything else I can change!

2023-07-28 16:43 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                  - name: List Children Host Pairs
```suggestion
                  - name: List children host pairs
```

2023-07-28 16:44 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                    href: api/security-host-list-childHostPairs.md
```suggestion
                    href: api/security-host-list-childhostpairs.md
```

2023-07-28 16:44 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                  - name: List Host Pairs
```suggestion
                  - name: List host pairs
```

2023-07-28 16:44 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                  - name: List Parent Host Pairs
```suggestion
                  - name: List parent host pairs
```

2023-07-28 16:47 UTC, Danielabom commented on api-reference/beta/resources/security-hostpair.md
> +| [List childHostPairs for a host](../api/security-host-list-childhostpairs.md)|[microsoft.graph.security.hostPair](../resources/security-hostpair.md) collection|Get a list of **hostPair** objects as
```suggestion
|[List childHostPairs for a host](../api/security-host-list-childhostpairs.md)|[microsoft.graph.security.hostPair](../resources/security-hostpair.md) collection|Get a list of **hostPair** objects associated with a host, where that host is the *parent* and has an outgoing pairing to a *child*.|
```

2023-07-28 16:50 UTC, Danielabom commented on api-reference/beta/resources/security-host.md
> +| [List childHostPairs](../api/security-host-list-childHostPairs.md)               | [microsoft.graph.security.hostPair](../resources/security-hostpair.md) collection       | Get a list of **hostPair
```suggestion
| [List childHostPairs](../api/security-host-list-childhostpairs.md)               | [microsoft.graph.security.hostPair](../resources/security-hostpair.md) collection       | Get a list of **hostPair** resources.  
```

2023-07-28 16:59 UTC, Danielabom commented on api-reference/beta/toc.yml
> +              - name: Host Pair
```suggestion
              - name: Host pair
```

2023-07-28 16:59 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                  - name: Host Pair
```suggestion
                  - name: Host pair
```

2023-07-28 16:59 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                  - name: List Children Host Pairs
```suggestion
                  - name: List children host pairs
```

2023-07-28 17:00 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                    href: api/security-host-list-childHostPairs.md
```suggestion
                    href: api/security-host-list-childhostpairs.md
```

2023-07-28 17:00 UTC, Danielabom commented on api-reference/beta/toc.yml
> +                  - name: List Parent Host Pairs
```suggestion
                  - name: List parent host pairs
```

2023-07-28 17:24 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the **hostPairs** navigation property to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatIntelligence?view=graph-rest-bet
```suggestion
          "Description": "Added the **hostPairs** navigation property to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-28 17:30 UTC, Danielabom requested changes
Hi @jakedavies-microsoft, thank you for applying the changes requested. My only observation is that  I don't see changelog entries for the new methods. Please add them so I can approve the PR. See example #6 on this wiki: [Changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog) Thanks again.

2023-07-31 14:31 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list childhostpairs](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [hostpair](htt
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair?view=graph-rest-beta) resource.",
```

2023-07-31 14:31 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list hostpairs](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair?view=graph-rest-beta) resource.",
```

2023-07-31 14:31 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list parenthostpairs](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [hostpair](h
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair?view=graph-rest-beta) resource.",
```

2023-07-31 18:33 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [threatintelligence](https://
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:33 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatintelligence](https://learn
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:34 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [threatintelligence](https:/
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:44 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:45 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:45 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https:/
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:45 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [get](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair-get?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microso
```suggestion
          "Description": "Added the [get](https://learn.microsoft.com/en-us/graph/api/security-hostpair-get?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:45 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [host](https://learn.microsof
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
```

2023-07-31 18:46 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [host](https://learn.microsoft.com
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-hostpairs?view=graph-rest-beta) operation to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
```

2023-07-31 18:46 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [host](https://learn.microso
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [host](https://learn.microsoft.com/en-us/graph/api/resources/security-host?view=graph-rest-beta) resource.",
```

2023-07-31 18:46 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn.micr
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-childhostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair?view=graph-rest-beta) resource.",
```

2023-07-31 18:47 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn.mic
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-parenthostpairs?view=graph-rest-beta) operation to the [hostpair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair?view=graph-rest-beta) resource.",
```

2023-07-31 18:47 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [get](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair-get?view=graph-rest-beta) operation to the [hostpair](https://learn.microsoft.com/en-
```suggestion
          "Description": "Added the [get](https://learn.microsoft.com/en-us/graph/api/security-hostpair-get?view=graph-rest-beta) operation to the [hostpair](https://learn.microsoft.com/en-us/graph/api/resources/security-hostpair?view=graph-rest-beta) resource.",
```

2023-07-31 18:49 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/resources/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-07-31 18:53 UTC, Danielabom commented on changelog/Microsoft.ThreatIntelligence.json
> +          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft
```suggestion
          "Description": "Added the [list](https://learn.microsoft.com/en-us/graph/api/security-host-list-hostpairs?view=graph-rest-beta) operation to the [threatIntelligence](https://learn.microsoft.com/en-us/graph/api/resources/security-threatintelligence?view=graph-rest-beta) resource.",
```

2023-08-02 00:21 UTC, Lauragra commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +`$count` is an optional query parameter.
When you say here that something is an optional query parameter, you mean that the method supports that query parameter, right? In that case, please make this section more clear and concise by revising the first sentence to say:

This method supports the `$count`, `$filter`, `$orderby`, `$select`, `$skip`, and `$top` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).

Then the tables can follow and we can remove the H3 subsections.

2023-08-02 00:22 UTC, Lauragra commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +|`childHost/id`|`$filter=(childHost/id eq 'contoso.com')`|Full path is requried for `$filter` usage.|
Global: Please don't use the inline code formatting for property names. Property names are generally bold, although in a table the formatting isn't necessary.

2023-08-02 00:22 UTC, Lauragra commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +|`firstSeenDateTime`|`$orderby=firstSeenDateTime desc`||
Are there notes for these properties? If not, remove the empty Notes column.

2023-08-02 00:26 UTC, Lauragra commented on api-reference/beta/api/security-host-list-hostpairs.md
> +title: "List hostPairs for a host"
Global: Please update the title fields to match the H1 titles of the articles. This ensures a consistent user experience in SERP.

2023-08-02 00:27 UTC, Lauragra commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +description: "Get the hostPair resources from the hostPairs navigation property in the child direction."
Global: Please update the descriptions to use the summary statement or a close variation. This generated description isn't particularly clear or helpful. The description field is what can show up on the SERP.

2023-08-02 00:28 UTC, Lauragra commented on api-reference/beta/api/security-host-list-hostpairs.md
> +## Optional query parameters
Please see my previous comment about the Optional query parameters section and apply the same here.

2023-08-02 00:32 UTC, Lauragra commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +Get the list of [hostpair](../resources/security-hostpair.md) resources associated with a host, where that host is the *parent* and has an outgoing pairing to a *cihld*.
Is the context of what we mean by "host" clear here, or would it be helpful to further specify that it's an IP address that was detected by Microsoft Defender?

2023-08-02 00:33 UTC, Lauragra commented on api-reference/beta/api/security-host-list-parenthostpairs.md
> +## Optional query parameters
Please see my previous comment about the Optional query parameters section and apply the same here.

2023-08-02 00:34 UTC, Lauragra commented on api-reference/beta/api/security-hostpair-get.md
> +Read the properties and relationships of a [microsoft.graph.security.hostPair](../resources/security-hostpair.md) object.
We don't spell out the subnamespace in the summary descriptions; please update here and in the description above.

2023-08-02 00:35 UTC, Lauragra commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +|`parentHost`|`$select=parentHost`|Does not support selecting on nested properties (i.e. `parentHost/id`).|
Global: Per Microsoft style, please don't use "i.e.". You can replace with "for example" here.

2023-08-02 00:36 UTC, Lauragra commented on api-reference/beta/api/security-hostpair-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Please update this section as well to remove the H3 and make more concise.

2023-08-02 00:38 UTC, Lauragra commented on api-reference/beta/resources/security-hostpair.md
> +description: "Represents a pair of parent-child hosts in which the child host is reachable to be reached via the parent host"
Please clarify the description here; I'm not sure "reachable to be reached via" makes sense? Also make sure to add the missing period.

2023-08-02 20:32 UTC, jakedavies-microsoft commented on api-reference/beta/api/security-host-list-childhostpairs.md
> +Get the list of [hostpair](../resources/security-hostpair.md) resources associated with a host, where that host is the *parent* and has an outgoing pairing to a *cihld*.
So "host" in this context can be *either* an ip or a domain name. So we could definitely specify that it could be either/or here if you thought that might be useful.

2023-08-04 03:12 UTC, Lauragra approved these changes

2023-08-05 21:00 UTC, merged