fix #21098
microsoftgraph/microsoft-graph-docs pull request #22097
Opened 2023-07-17 17:47 UTC by FaithOmbongi

fix #21098

2023-07-17 22:07 UTC, Licantrop0 commented on concepts/filter-query-parameter.md
> +| Equality operators    | <ul><li> Equals (`eq`) </li><li> Not equals (`ne`)</li><li> Logical negation (`not`)</li><li> In (`in`)</li><li> Has (`has`)</li></ul> <br/><br/> The maximum number of expre
2048 is the limit of the *total url* length (including the base URL and other query parameters), not just for the text inside the `in` operator.

2023-07-17 22:09 UTC, Licantrop0 requested changes
need to be specific of what '2048' characters we refer to.

2023-07-18 08:10 UTC, FaithOmbongi commented on concepts/filter-query-parameter.md
> +| Equality operators    | <ul><li> Equals (`eq`) </li><li> Not equals (`ne`)</li><li> Logical negation (`not`)</li><li> In (`in`)</li><li> Has (`has`)</li></ul> <br/><br/> The maximum number of expre
Applied this feedback.

2023-07-18 09:43 UTC, Licantrop0 approved these changes

2023-07-18 09:43 UTC, Licantrop0 commented on concepts/filter-query-parameter.md
> +| Equality operators    | <ul><li> Equals (`eq`) </li><li> Not equals (`ne`)</li><li> Logical negation (`not`)</li><li> In (`in`)</li><li> Has (`has`)</li></ul> <br/><br/> **Note:**When using the `in
there should be a space between **Note:** and the next word.

2023-07-18 20:35 UTC, merged