Update change-notifications-subscription-lifetime.md
microsoftgraph/microsoft-graph-docs pull request #22121
Opened 2023-07-18 17:08 UTC by erichui-ms

Increase from 1 hour to 3 days for a few teams resources

2023-07-19 19:05 UTC, leoquijano requested changes

2023-07-19 19:05 UTC, leoquijano commented on api-reference/beta/resources/subscription.md
> +| lifecycleNotificationUrl | String | Required for Teams resources if `expirationDateTime` is more than 1 hour from now; optional otherwise. The URL of the endpoint that receives lifecycle notificati
It would be useful to have a link to the lifecycle notifications [documentation page](https://learn.microsoft.com/en-us/graph/webhooks-lifecycle) here.

2023-07-19 19:05 UTC, leoquijano commented on api-reference/v1.0/resources/subscription.md
> +| lifecycleNotificationUrl | String | Required for Teams resources if `expirationDateTime` is more than 1 hour from now; optional otherwise. The URL of the endpoint that receives lifecycle notificati
It would be useful to have a link to the lifecycle notifications [documentation page](https://learn.microsoft.com/en-us/graph/webhooks-lifecycle) here.

2023-07-19 22:04 UTC, erichui-ms commented
Hi, @leoquijano.  I've updated the docs based on your feedback.
Hi, @Lauragra .  This is ready for "content review" by your team now.  Thanks.

2023-07-20 15:03 UTC, leoquijano approved these changes

2023-07-26 17:22 UTC, Danielabom commented on api-reference/v1.0/resources/subscription.md
> +| lifecycleNotificationUrl | String | Required for Teams resources if `expirationDateTime` is more than 1 hour from now; optional otherwise. The URL of the endpoint that receives lifecycle notificati
```suggestion
| lifecycleNotificationUrl | String | Required for Teams resources if  the `expirationDateTime` value is more than 1 hour from now; optional otherwise. The URL of the endpoint that receives lifecycle notifications, including `subscriptionRemoved`, `reauthorizationRequired`, and `missed` notifications. This URL must make use of the HTTPS protocol. For more information, see [Reduce missing subscriptions and change notifications](/graph/webhooks-lifecycle). |
```

2023-07-26 17:25 UTC, Danielabom commented on api-reference/beta/resources/subscription.md
> +| lifecycleNotificationUrl | String | Required for Teams resources if `expirationDateTime` is more than 1 hour from now; optional otherwise. The URL of the endpoint that receives lifecycle notificati
```suggestion
| lifecycleNotificationUrl | String | Required for Teams resources if the `expirationDateTime` value is more than 1 hour from now; optional otherwise. The URL of the endpoint that receives lifecycle notifications, including `subscriptionRemoved`, `reauthorizationRequired`, and `missed` notifications. This URL must make use of the HTTPS protocol. For more information, see [Reduce missing subscriptions and change notifications](/graph/webhooks-lifecycle).|
```

2023-07-26 17:25 UTC, Danielabom approved these changes
Thank you for working on this PR @erichui-ms. PR approved.

2023-07-27 04:03 UTC, merged