adding new updates
microsoftgraph/microsoft-graph-docs pull request #22250
Opened 2023-07-26 17:54 UTC by rimisra2

Getting rid of rollback changes and merging old flow with new flow

2023-07-31 20:25 UTC, Danielabom commented on concepts/data-connect-quickstart.yml
> +  - title: Set up your Azure Active Directory Application
```suggestion
  - title: Set up your Azure Active Directory application
```

2023-07-31 20:27 UTC, Danielabom commented on includes/data-connect-quickstart-01.md
> +> For existing tenants who already have Microsoft Graph Data Connect enabled and want to use this tutorial: please notify your global adminstrator toggle Microsoft Graph Data Connect off and then on
```suggestion
> For existing tenants who already have Microsoft Graph Data Connect enabled and want to use this tutorial: please notify your global administrator toggle Microsoft Graph Data Connect off and then on again in the [admin portal](https://admin.microsoft.com/adminportal/home#/Settings/Services/:/Settings/L1/O365DataPlan) to be able to follow this tutorial flow. For new customers who have not yet toggled Microsoft Graph Data Connect on, please follow the steps in this tutorial below. No extra action is required from you.
```

2023-07-31 20:29 UTC, Danielabom commented on includes/data-connect-quickstart-01.md
> +> For existing tenants who already have Microsoft Graph Data Connect enabled and want to use this tutorial: please notify your global administrator toggle Microsoft Graph Data Connect off and then on
```suggestion
> For existing tenants who already have Microsoft Graph Data Connect enabled and want to use this tutorial: please notify your global administrator toggle Microsoft Graph Data Connect off and then on again in the [admin portal](https://admin.microsoft.com/adminportal/home#/Settings/Services/:/Settings/L1/O365DataPlan) to be able to follow this tutorial flow. For new customers who have not yet toggled Microsoft Graph Data Connect, please follow the steps in this tutorial below. No further action is needed on your part.

2023-07-31 20:32 UTC, Danielabom commented on includes/data-connect-quickstart-01.md
> +> For reference, we have left guidance for our former consent process involving Privileged Access Management (PAM) in sections of our tutorial as tabs. We highly recommend following our new consent f
```suggestion
>We have included the guidance for our former consent process involving Privileged Access Management (PAM) in sections of our tutorial as tabs for reference purposes. However, we highly recommend following our new consent flow for a more simplified onboarding process.
```

2023-07-31 20:32 UTC, Danielabom commented on includes/data-connect-quickstart-01.md
> +>We have included the guidance for our former consent process involving Privileged Access Management (PAM) in sections of our tutorial as tabs for reference purposes. However, we highly recommend fol
```suggestion
> We have included the guidance for our former consent process involving Privileged Access Management (PAM) in sections of our tutorial as tabs for reference purposes. However, we highly recommend following our new consent flow for a more simplified onboarding process.
```

2023-07-31 20:34 UTC, Danielabom commented on includes/data-connect-quickstart-01.md
> +   > The screenshots and examples used in this tutorial are from a Microsoft 365 developer tenant with sample email from test users. You can use your own Microsoft 365 tenant to perform the same step
```suggestion
   > The screenshots and examples used in this tutorial are from a Microsoft 365 developer tenant with a sample email from test users. You can use your own Microsoft 365 tenant to perform the same steps. No data is written to Microsoft 365. A copy of email data is extracted from all users in a Microsoft 365 tenant and copied to an Azure Blob Storage account. You maintain control over who has access to the data within the Azure Blob Storage.
```

2023-07-31 20:38 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +The first tab goes over our new and updated consent flow. We highly recommend new and current customers to use this new consent flow for a smoother and secure onboarding process. The later tab follow
```suggestion
The first tab goes over our new and updated consent flow. We highly recommend new and current customers use this new consent flow for a smoother and more secure onboarding process. The later tab follows our previous guidance on our soon-to-be deprecated consent process involving Privileged Access Management (PAM).
```

2023-07-31 20:43 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +For this tutorial, please ensure you have an account with admin priviledges available. You cannot set up your first pipeline without completing this step. We recommend having two users in your Micros
```suggestion
For this tutorial, please ensure you have an account with admin privileges available. You must complete this step to set up your first pipeline. We recommend having at least two users in your Microsoft 365 tenant with the **global administrator** role enabled.
```

2023-07-31 20:46 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +1. Open a browser and go to your [Microsoft 365 Admin Portal](https://admin.microsoft.com/) and sign in with your “admin” user.
```suggestion
1. Open a browser and go to your [Microsoft 365 Admin Portal](https://admin.microsoft.com/) and sign in with your **admin** user. 
```

2023-07-31 20:46 UTC, isvargasmsft commented on includes/data-connect-quickstart-01.md
> +> For existing tenants who already have Microsoft Graph Data Connect enabled and want to use this tutorial: please notify your global administrator toggle Microsoft Graph Data Connect off and then on
```suggestion
> For existing tenants who already have Microsoft Graph Data Connect enabled and want to use this tutorial: notify your global administrator toggle Microsoft Graph Data Connect off and then on again in the [admin portal](https://admin.microsoft.com/adminportal/home#/Settings/Services/:/Settings/L1/O365DataPlan) to be able to follow this tutorial flow. For new customers who have not yet toggled Microsoft Graph Data Connect, please follow the steps in this tutorial below. No further action is needed on your part.
```

2023-07-31 20:50 UTC, isvargasmsft commented on includes/data-connect-quickstart-06.md
> +1. In the **Details** screen, look for the status of the pipeline activity as highlighted in the following image.The status should progress through Initializing, Consent Pending, Extracting Data, Per
```suggestion
1. In the **Details** screen, look for the status of the pipeline activity as highlighted in the following image. The status should progress through Initializing, Consent Pending, Extracting Data, Persisting Data and Succeeded – no further action needed from you for this.  
```

2023-07-31 20:50 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +1. Select the **Settings > Org settings** menu item. You might have to click **Show all** before you're able to view **Settings**.
```suggestion
1. Select **Settings > Org settings**. You might have to click **Show all** before you're able to view **Settings**.
```

2023-07-31 20:51 UTC, isvargasmsft commented on includes/data-connect-quickstart-06.md
> +1. By default, Azure Synapse Analytics uses an integration runtime that auto-resolves the region. In this tutorial, we recommend to the default auto-resolve in the developer tenant.
Did you mean:
```suggestion
1. By default, Azure Synapse Analytics uses an integration runtime that auto-resolves the region. In this tutorial, we recommend to use the default auto-resolve in the developer tenant.
```
?

Please review.

2023-07-31 20:52 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +1. In the **Services** tab (which should be the default selection), select the **Microsoft Graph Data Connect** service.
```suggestion
1. In the **Services** tab (which should be the default selection), select **Microsoft Graph Data Connect**.
```

2023-07-31 20:53 UTC, isvargasmsft commented on includes/data-connect-quickstart-06.md
> +1. Sign in to the portal using an account with an [Application Administrator](/azure/active-directory/roles/permissions-reference#application-administrator) or [Application Developer](/azure/active-d
Instead of using "" please be specific. 
```suggestion
1. Sign in to the portal using an account with an [Application Administrator](/azure/active-directory/roles/permissions-reference#application-administrator) or [Application Developer](/azure/active-directory/roles/permissions-reference#application-developer) role. Ensure that you are signed-in with your developer account that has privileges to create Azure resources within your subscription.
```

2023-07-31 20:54 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +This page goes over the steps for our former consent flow involving the Priviledged Access Management (PAM). We recommend new and current customers to refer to our newer consent flow on the previous
```suggestion
This page goes over the steps for our former consent flow involving Privileged Access Management (PAM).We highly recommend new and current customers use this new consent flow for a smoother and more secure onboarding process available in the previous tab. 
```

2023-07-31 20:56 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +1. Open a browser and go to your [Microsoft 365 Admin Portal](https://admin.microsoft.com/). Please ensure this is done through an account with admin priviledges.
```suggestion
1. Open a browser and go to your [Microsoft 365 Admin Portal](https://admin.microsoft.com/). Please ensure this is done through an account with admin privileges.
```

2023-07-31 20:56 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +Enable the Microsoft Graph Data Connect service on your Microsoft 365 tenant. Please ensure this is done with an account that has admin priviledges.
```suggestion
Enable the Microsoft Graph Data Connect service on your Microsoft 365 tenant. Please ensure this is done with an account that has admin privileges.
```

2023-07-31 21:02 UTC, Danielabom commented on includes/data-connect-quickstart-03.md
> +In this exercise, you will learn how to create an Azure Active Directory (Azure AD) application that serves as the security principal to run the data extraction process with Micrsoft Graph Data Conne
```suggestion
In this exercise, you will learn how to create an Azure Active Directory (Azure AD) application that serves as the security principal to run the data extraction process with Microsoft Graph Data Connect.
```

2023-07-31 21:03 UTC, Danielabom commented on includes/data-connect-quickstart-04.md
> +1. Sign in using an account with **[Application Developer](/azure/active-directory/roles/permissions-reference#application-developer)** role to your Azure portal.
```suggestion
1. Sign in using an account with an **[Application developer](/azure/active-directory/roles/permissions-reference#application-developer)** role to your Azure portal.
```

2023-07-31 21:09 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +The first section and tab is for users who have followed the new and updated consent flow to set up their pipeline. This goes over how to register and approve an AAD application with Microsoft Graph
```suggestion
The first section and tab are for users who have completed the new and updated consent flow to set up their pipeline. It provides guidance on registering and approving an AAD application with Microsoft Graph Data Connect (Data Connect). As a prerequisite, Data Connect should be enabled in your tenant. We recommend creating an Azure Active Directory (Azure AD) application and a storage destination resource.
```

2023-07-31 21:10 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +The second section goes over how to approve and deny application requests using our former consent process with Privileged Access Management (PAM). The first tab follows our former consent process on
```suggestion
The second section covers the approval and denial of application requests using our former consent process with Privileged Access Management (PAM). The first tab provides instructions for the admin center's former consent process, while the second tab offers guidance through a PowerShell script. If you are following the PAM steps, we suggest revisiting this step AFTER setting up your Azure Synapse or Factory pipeline in the next step.
```

2023-07-31 21:30 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +As a pre-requisite, Data Connect should be enabled in your tenant. It is recommended to have an AAD app and storage destination resource already created, however these can be created from the wizard.
```suggestion
As a pre-requisite, Data Connect should be enabled in your tenant. It is recommended to have an Azure AD app and storage destination resource already created. However, these can be created by a wizard. To register an app with Data Connect, developers are welcome by a wizard divided into three tabs: **Registration info, Datasets,** and **Review + create**.
```

2023-07-31 21:33 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +### Provide details for the Registration Info tab
```suggestion
### Provide details in the Registration info tab
```

2023-07-31 21:34 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +1. Access [Microsoft Graph Data Connect in the Azure portal](https://aka.ms/mgdcinazure). Moving forward, the experience will be available through the search bar in the [Azure portal](https://portal.
```suggestion
1. Access [Microsoft Graph Data Connect in the Azure portal](https://aka.ms/mgdcinazure). You can find it through the search bar in the [Azure portal](https://portal.azure.com/)
```

2023-07-31 21:35 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +2. Click the **Add** or the **Add a new application** button
```suggestion
2. Click the **Add** or **Add a new application**.
```

2023-07-31 21:37 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +3. Follow the **Add** wizard by specifying the project details for the registration. Once you have completed the following fields, click **Next : Datasets >**
```suggestion
3. Follow the **Add** wizard to provide the project details for registration. Once you have completed the required fields, click **Next: Datasets >**
```

2023-07-31 21:40 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +    1. **Subscription:** Select a subscription in the tenant that will be used exclusively to filter the next four selections utilized to configure the data destination
```suggestion
    1. **Subscription:** Select a subscription to filter the next selections. Choose the previously created resource group, select "Azure Storage Account" as the destination type, and then choose the relevant Storage Account.
```

2023-07-31 22:02 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +        - **Resource Group:**  Select the resource group you created previously
```suggestion
        - **Resource Group:**  Select the resource group you created previously.
```

2023-07-31 22:03 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +        - **Destination Type:** Select Azure Storage Account as the destination type
```suggestion
        - **Destination Type:** Select Azure Storage Account.
```

2023-07-31 22:03 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +        - **Storage Account:** Select the Storage Account you created previously
```suggestion
        - **Storage Account:** Select the storage account you created previously
```

2023-07-31 22:04 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +        - **Storage Account Uri:** Select the option including **.blob.core.windows.net**
```suggestion
        - **Storage Account Uri:** Select the option that shows **.blob.core.windows.net**
```

2023-07-31 22:05 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +        - **Storage Account:** Select the storage account you created previously
```suggestion
        - **Storage Account:** Select the storage account you created previously.
```

2023-07-31 22:06 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +    2. **Application ID:** Select from the Azure AD apps in the tenant or create a new one
```suggestion
    2. **Application ID:** Select it from the Azure AD apps in the tenant or create a new one.
```

2023-07-31 22:06 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +    3. **Description:** Enter **My first MGDC app**
```suggestion
    3. **Description:** Enter **My first MGDC app**.
```

2023-07-31 22:06 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +    4. **Publish Type:** Choose **Single-Tenant**
```suggestion
    4. **Publish Type:** Choose **Single-Tenant**.
```

2023-07-31 22:08 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +    2. **Application ID:** Select it from the Azure AD apps in the tenant or create a new one.
```suggestion
    2. **Application ID:** Select an existing Azure AD in the tenant or create a new one.
```

2023-07-31 22:22 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +Specify the datasets that the app registration needs to query. To learn more about datasets, see [Datasets, regions, and sinks supported by Microsoft Graph Data Connect](/graph/data-connect-datasets)
```suggestion
Specify the datasets that the app registration needs to query. To learn more about datasets, see [Datasets, regions, and sinks supported by Microsoft Graph Data Connect](/graph/data-connect-datasets). Click **Next : Datasets >**.
```

2023-07-31 22:22 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +### Review and Create
```suggestion
### Review and Create
```

2023-07-31 22:33 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +# Former Guidance on Privileged Access Management (PAM)
```suggestion
# Former guidance on Privileged Access Management (PAM)
```

2023-07-31 23:12 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +1. Open a new browser window in private mode, go to your [Microsoft 365 admin center](https://admin.microsoft.com/), and sign in with your "admin" user.
```suggestion
1. Open a new browser window in private mode, go to your [Microsoft 365 admin center](https://admin.microsoft.com/), and sign in with your **admin** user.
```

2023-07-31 23:18 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> + > If you are not in your "admin" account, there will be an error with approval. You cannot self-approve your apps.
```suggestion
 > If you are not in your **admin** account, there will be an error with the approval. You cannot self-approve your apps.
```

2023-07-31 23:58 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +4. In the Microsoft Graph Data Connect applications portal, you should see the application you registered previously with Data Connect in the application summary table with the status **Pre-consent**
```suggestion
4. In the Microsoft Graph Data Connect applications portal,  find the application you registered previously with Data Connect. It should have a **Pre-consent** status in the application summary table.
```

2023-08-01 00:04 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +If you are following the PAM steps, we recommend you come back to this step **AFTER** setting up your Azure Synapse or Factory pipeline in the next step.
```suggestion
If you are following the PAM steps, return to this section  **AFTER** setting up your Azure Synapse or Factory pipeline in the next step.
```

2023-08-01 00:06 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +A Microsoft 365 administrator can approve or deny consent requests. This can be done via the Microsoft 365 Admin Center or programmatically via PowerShell.
```suggestion
A Microsoft 365 administrator can approve or deny consent requests.either through the Microsoft 365 admin center or programmatically using PowerShell.
```

2023-08-01 00:06 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +When a developer runs a pipeline, they trigger a privileged access management (PAM) request. The request is attached to your user account that owns the service principal used by the pipeline. Even if
```suggestion
When a developer triggers a pipeline, it initiates a privileged access management (PAM) request. This request is associated with the user account that owns the service principal used by the pipeline. However, self-approvals are not permitted even if the account belongs to the designated approver group.
```

2023-08-01 00:17 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +If you try, you'll get an error message in the PAM portal: "Requestor and approver are the same. Self-approval is not allowed." For development, you'll want to have a second account in addition to th
```suggestion
Attempting self-approval will result in an error message in the PAM portal: "Requestor and approver are the same. Self-approval is not allowed." During development, make sure you have a separate account in addition to the admin, who can approve the requests. Both the submitter and approver must have active Exchange Online accounts.
```

2023-08-01 00:25 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +1. Open a browser and go to your [Azure portal](https://portal.azure.com/#home).
```suggestion
1. Open a browser and navigate to the [Azure portal](https://portal.azure.com/#home).
```

2023-08-01 00:26 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +1. Sign in using an account with **global administrator** rights to your Azure AD and Microsoft 365 tenants.
```suggestion
1. Sign in using an account with **Global Administrator** rights to your Azure AD and Microsoft 365 tenants.
```

2023-08-01 00:26 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +1. In the **Recent** list of resources, select the **Azure Storage account** you created previously in this tutorial.
```suggestion
1. From the **Recent** list of resources, select the **Azure Storage account** you created previously in this tutorial.
```

2023-08-01 00:29 UTC, Danielabom commented on includes/data-connect-quickstart-05.md
> +1. Go to the sidebar navigation menu and click **Storage browser**, then select **Blob containers**. From there, choose the specific container that you created in this tutorial, which you configured
```suggestion
1. Click **Storage browser** in the sidebar navigation menu, then choose **Blob containers**. Select the specific container you created in this tutorial, which you configured as the destination for the extracted data in the Azure Data Factory pipeline. You should now be able to view the data stored within this container.
```

2023-08-01 00:32 UTC, Danielabom commented on includes/data-connect-quickstart-06.md
> +We recommend that you use Azure Synapse because it has more in-built capabilities for data processing.
@rimisra2 why in-built?

2023-08-01 00:41 UTC, Danielabom commented on includes/data-connect-quickstart-06.md
> +1. By default, Azure Synapse Analytics uses an integration runtime that auto-resolves the region. In this tutorial, we recommend to use the default auto-resolve in the developer tenant.
```suggestion
1. By default, Azure Synapse Analytics uses an integration runtime that automatically resolves the region. In this tutorial, we recommend using the default auto-resolve option in the developer tenant.
```

2023-08-01 00:41 UTC, Danielabom commented on includes/data-connect-quickstart-06.md
> +ig
```suggestion
```

2023-08-01 00:44 UTC, Danielabom commented on includes/data-connect-quickstart-06.md
> +1. Sign in using an account with [Application Administrator](/azure/active-directory/roles/permissions-reference#application-administrator) or [Application Developer](/azure/active-directory/roles/pe
```suggestion
1. Sign in to the Azure portal with an account that has either the [Application administrator](https://chat.openai.com/azure/active-directory/roles/permissions-reference#application-administrator) or [Application developer](https://chat.openai.com/azure/active-directory/roles/permissions-reference#application-developer) role. Make sure you are using your **developer** account, which has the necessary privileges to create Azure resources within your subscription.
```

2023-08-01 02:01 UTC, Danielabom commented on includes/data-connect-quickstart-02.md
> +This page goes over the steps for our former consent flow involving Privileged Access Management (PAM).We highly recommend new and current customers use this new consent flow for a smoother and more
```suggestion
This page describes the steps of the former consent flow involving Privileged Access Management (PAM). We highly recommend new and current customers use the new consent flow for a smoother and more secure onboarding process available in the previous tab. 
```

2023-08-01 02:06 UTC, Danielabom requested changes
@rimisra2, please see my comments and ping me once you are available because I need your input to make more edits.

2023-08-01 05:31 UTC, rimisra2 commented on includes/data-connect-quickstart-06.md
> +1. Sign in using an account with [Application Administrator](/azure/active-directory/roles/permissions-reference#application-administrator) or [Application Developer](/azure/active-directory/roles/pe
@Danielabom please remove the chat.openai.com links and revert to the links from the original file.

Please let me know once you've edited the suggest and I can commit it.

2023-08-01 05:32 UTC, rimisra2 commented on includes/data-connect-quickstart-06.md
> +We recommend that you use Azure Synapse because it has more in-built capabilities for data processing.
@rimisra2 it's a better description of the capabilities that we dont want the documentation to detail since it's not the focus of this file. Let's keep as is from the original file.

2023-08-01 05:34 UTC, rimisra2 commented
@Danielabom  I've addressed the comments by either including them or responding to your comments.

2023-08-01 19:09 UTC, Danielabom approved these changes
Thank you for working on this PR @rimisra2. PR approved.

2023-08-02 03:55 UTC, Lauragra commented on includes/data-connect-quickstart-01.md
> +> For existing tenants who already have Microsoft Graph Data Connect enabled and want to use this tutorial: notify your global administrator toggle Microsoft Graph Data Connect off and then on again
This note text is currently unclear. The following is a suggested revision:

If you have an existing tenant that already has Microsoft Graph Data Connect enabled, before you complete this tutorial, ask your global administrator to toggle Microsoft Graph Data Connect off and then on again in the [admin portal](https://admin.microsoft.com/adminportal/home#/Settings/Services/:/Settings/L1/O365DataPlan). If you're working in a new tenant that doesn't have Data Connect enabled, you don't need to take any action.

2023-08-02 03:58 UTC, Lauragra commented on includes/data-connect-quickstart-01.md
> +> We have included the guidance for our former consent process involving Privileged Access Management (PAM) in sections of our tutorial as tabs for reference purposes. However, we highly recommend fo
Revise as:

The guidance for using the former consent process involving Privileged Access Management (PAM) is included in a separate tab for reference purposes. We recommend that you follow the new consent flow for a simplified onboarding process.

Also, you have two notes next to each other here, which can dilute the emphasis. See if you can rearrange the text to avoid having the two notes together.

2023-08-02 03:58 UTC, Lauragra commented on includes/data-connect-quickstart-01.md
> +   > You can't approve your own test application using the same account. Ensure that you have another member (or account) in your tenant that acts as an "admin".
Remove the quotes from "admin".

2023-08-02 04:04 UTC, Lauragra commented on includes/data-connect-quickstart-02.md
> +1. Congrats, you just enabled Microsoft Graph Data Connect for your organization!
Please spell out as "Congratulations" for globalization/localization.

2023-08-02 04:04 UTC, Lauragra commented on includes/data-connect-quickstart-02.md
> +This page describes the steps of the former consent flow involving Privileged Access Management (PAM). We highly recommend new and current customers use the new consent flow for a smoother and more s
Revise the second sentence: 

We recommend that you use the new consent flow for a smoother and more secure onboarding process.

2023-08-02 04:06 UTC, Lauragra commented on includes/data-connect-quickstart-02.md
> +1. Open a browser and go to your [Microsoft 365 Admin Portal](https://admin.microsoft.com/). Please ensure this is done through an account with admin privileges.
It would be more clear/concise to word this step as:

Open a browser and use an account with admin privileges to go to your [Microsoft 365 admin portal](https://admin.microsoft.com/).

2023-08-02 04:07 UTC, Lauragra commented on includes/data-connect-quickstart-02.md
> +Enable the Microsoft Graph Data Connect service on your Microsoft 365 tenant. Please ensure this is done with an account that has admin privileges.
Revise as:

Enable the Microsoft Graph Data Connect service on your Microsoft 365 tenant by using an account that has admin privileges.

2023-08-02 04:10 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +The first section and tab are for users who have completed the new and updated consent flow to set up their pipeline. It provides guidance on registering and approving an AAD application with Microso
AAD is not an allowed acronym - please spell out as Azure AD.

2023-08-02 04:10 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +The second section covers the approval and denial of application requests using our former consent process with Privileged Access Management (PAM). The first tab provides instructions for the admin c
AFTER does not have to be in all caps; please change to "after".

2023-08-02 04:12 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +As a pre-requisite, Data Connect should be enabled in your tenant. While having an Azure AD app and storage destination resource pre-created is recommended, these can also be set up using the wizard.
Revise as:

As a prerequisite, enable Data Connect in your tenant. It's helpful to have an Azure AD app and storage destination resource created; you can also set these up by using the wizard. The app registration process in Data Connect involves using a wizard with three tabs: Registration info, Datasets, and Review + create.

2023-08-02 04:12 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +2. Click the **Add** or **Add a new application**.
Remove the "the" here.

2023-08-02 04:13 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +3. Follow the **Add** wizard to provide the project details for registration. Once you have completed the required fields, click **Next: Datasets >**
Revise the second sentence:

After you have completed the required fields, choose **Next: Datasets >**

2023-08-02 04:13 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +    3. **Description:** Type **My first MGDC app**.
Please avoid using the acronym MGDC, can we change that to Data Connect here?

2023-08-02 04:14 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +Specify the datasets that the app registration needs to query. To learn more about datasets, see [Datasets, regions, and sinks supported by Microsoft Graph Data Connect](/graph/data-connect-datasets)
Global: Avoid using click for accessibility reasons; replace with choose or select where possible.

2023-08-02 04:15 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +5. Once completed, click **Review + Create**, and then click **Create**.
Don't use "once" to mean "after" or "when", per Microsoft style and for globalization/localization. Make sure that it's clear in this step "what" is completed. Maybe you can just remove "Once completed". Change the Clicks to Choose.

2023-08-02 04:17 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +7. After clicking **Approve**, the application summary table reloads with your app listed with the status **Approved**.
You can remove the phrase "After clicking Approve" here.

2023-08-02 04:18 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +# Former guidance on Privileged Access Management (PAM)
The guidance itself isn't "former". Suggest revising the heading to be: 
"Guidance for using Privileged Access Management (PAM)"

2023-08-02 04:18 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +If you are following the PAM steps, return to this section  **AFTER** setting up your Azure Synapse or Factory pipeline in the next step.
Why does AFTER have to be all caps and bold? Also, avoid gerunds; change "setting" to "you set up".

2023-08-02 04:19 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +1. Open a browser and navigate to the [Azure portal](https://portal.azure.com/#home).
Simplify language where possible for global readers; change "navigate" to "go".

2023-08-02 04:20 UTC, Lauragra commented on includes/data-connect-quickstart-07.md
> +You've completed the Microsoft Graph Data Connect tutorial! You should now be able to see your JSON file in your Azure Storage account with the following steps:
Revise the second sentence as:
To see your JSON file in your Azure Storage account:

2023-08-02 04:22 UTC, Lauragra commented on includes/data-connect-quickstart-07.md
> +After building your first successful Microsoft Graph Data Connect pipeline, you can start learning more about the product [here](/graph/data-connect-concept-overview).
Revise this sentence as:

You've built your first successful Microsoft Graph Data Connect pipeline. To learn more about Data Connect, see [Overview of Microsoft Graph Data Connect](/graph/data-connect-concept-overview).

2023-08-02 22:13 UTC, rimisra2 commented on includes/data-connect-quickstart-05.md
> +    3. **Description:** Type **My first MGDC app**.
Some of the screenshots in this step and other steps **may** have the name "My first MGDC app". To keep in parity with the text in the screenshots with that description, can we keep MGDC here?

2023-08-02 23:34 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +The second section covers the approval and denial of application requests using our former consent process with Privileged Access Management (PAM). The first tab provides instructions for the admin c
The description of sections and tabs here is a little confusing. Why is the first section in a tab if there is only one tab? Then later we seem to have another tabbed section with two tabs.

At a minimum, maybe instead of referring to sections and tabs, we can provide the section headings with jump links to help readers navigate through this step?

Here's the step on the review site so you can see how it looks: https://review.learn.microsoft.com/en-us/graph/data-connect-quickstart?branch=u%2Frimisra%2FgettingStarted&tabs=NewConsentFlow%2CRegisterAADApplication%2CPAMMicrosoft365%2CAzureSynapsePipeline&tutorial-step=4

2023-08-02 23:35 UTC, Lauragra commented on includes/data-connect-quickstart-05.md
> +    3. **Description:** Type **My first MGDC app**.
I don't think we can/should perpetuate the use of a branding violation where we have any editorial control. Is it possible to update the screenshots?

2023-08-03 17:02 UTC, sannaga7 commented on includes/data-connect-quickstart-01.md
> +![A screenshot that explains the onboarding flow.](../concepts/images/data-connect-overview-flowchart.png)
Can we update this to the latest image in Michael's PR?

2023-08-03 18:43 UTC, rimisra2 commented on includes/data-connect-quickstart-01.md
> +![A screenshot that explains the onboarding flow.](../concepts/images/data-connect-overview-flowchart.png)
@sannaga7  can you send me the image please?

2023-08-03 19:08 UTC, Lauragra approved these changes

2023-08-04 03:55 UTC, merged

2023-08-04 18:29 UTC, sannaga7 commented on includes/data-connect-quickstart-03.md
>  1. Ensure that your account (if you are using a developer tenant use the Global admin account) meets the following requirements to be an application owner:
This step on licenses only applies to PAM... can we explicitly call that out in the next iteration?

2023-08-04 18:32 UTC, sannaga7 commented on includes/data-connect-quickstart-05.md
> +The first section in this step is for users who have completed the new and updated consent flow to set up their pipeline. It describes how to register and approve an Azure Active Directory (Azure AD)
For this page, can we make the content tabbed as well?

2023-08-04 18:37 UTC, sannaga7 commented on includes/data-connect-quickstart-06.md
> +1. Sign in to the Azure portal with an account that has either the [Application administrator](/azure/active-directory/roles/permissions-reference#application-administrator) or [Application developer
Not letting me comment on that line, but can we make it clear that "1. The request will be sent to the global admin to be approved. For the context of this tutorial, we recommend opening another tab with your admin priviledges enabled so you can approve the pipeline request." only applies to PAM flow?