Jiawwu dlp 20190122
microsoftgraph/microsoft-graph-docs pull request #3839
Opened 2019-01-23 00:05 UTC by jiawwu

2019-01-23 00:05 UTC, jthake-msft commented
OPS Build status updates of commit _[b9c0dd9](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/b9c0dd93d776543d5bbb718002e4bdc754ae03c9)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 00:06 UTC, jthake-msft commented
OPS Build status updates of commit _[b9c0dd9](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/b9c0dd93d776543d5bbb718002e4bdc754ae03c9)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\1205-s, target branch: master, target branch commit: 6fa825aebb17d2c7d26171ed0995759c7810c3c9, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901230005265618-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FzFq9cH%2F9do0EhMs2bWdxDPclr8o5tVm5ckExu464yg%3D&st=2019-01-23T00%3A01%3A27Z&se=2019-02-23T00%3A06%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 00:06 UTC, jthake-msft commented
OPS Build status updates of commit _[4f3352e](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/4f3352e954891a1e6ada2d8cea3dfc3957eca945)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 00:08 UTC, jthake-msft commented
OPS Build status updates of commit _[4f3352e](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/4f3352e954891a1e6ada2d8cea3dfc3957eca945)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 00:10 UTC, jthake-msft commented
OPS Build status updates of commit _[4f3352e](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/4f3352e954891a1e6ada2d8cea3dfc3957eca945)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901230006459295-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6rSsYUAv1YquL5x%2FeKnp5%2Bo0hwEpPpqrn6ZEGerlA9Y%3D&st=2019-01-23T00%3A05%3A03Z&se=2019-02-23T00%3A10%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 00:21 UTC, jthake-msft commented
OPS Build status updates of commit _[66f20b2](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/66f20b22d975edb944b07563d4a467525524828c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 00:32 UTC, jthake-msft commented
OPS Build status updates of commit _[1c4c218](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1c4c21887db7cc2e4fb2b012451484cd01317367)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-01-23 00:32 UTC, jthake-msft commented
OPS Build status updates of commit _[1c4c218](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1c4c21887db7cc2e4fb2b012451484cd01317367)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 00:34 UTC, jthake-msft commented
OPS Build status updates of commit _[1c4c218](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1c4c21887db7cc2e4fb2b012451484cd01317367)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 00:36 UTC, jthake-msft commented
OPS Build status updates of commit _[1c4c218](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1c4c21887db7cc2e4fb2b012451484cd01317367)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901230032338169-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mTdzFpF%2BkJGuxfsfcMKmtsG7pIHr%2FtLYAJ1GNSGERWk%3D&st=2019-01-23T00%3A31%3A01Z&se=2019-02-23T00%3A36%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 00:37 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +The following is an example of the request for updating DLP properties on a Microsoft Teams channel message.
Is a channel message a chat message? I'm not sure that this is clarified in our docs.

2019-01-23 00:37 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +PATCH https://graph.microsoft.com/v1.0/teams/{group-id}/channels/{channel-id}/messages/{message-id}
This is a beta API so the example should use the beta endpoint.

2019-01-23 00:51 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +| policyTip | JSON | The policy tip for the DLP violation. See the following table for details about the structure |
Please verify that Type JSON is accurate for this property. It looks like the type is chatMessagePolicyViolationPolicyTip.

2019-01-23 00:52 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +| verdictDetails | Bitwise Enum | Indicates the details of the allowed sender actions based on the verdict of the DLP app for the message processed. Possible values are None (0), AllowFalsePositiveOv
Please verify that the types are accurate per the metadata.

2019-01-23 00:55 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +### policyTip JSON
These are defined in the complex type topic; they don't need to be defined here.

2019-01-23 00:57 UTC, jiawwu commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +The following is an example of the request for updating DLP properties on a Microsoft Teams channel message.
channel root message, channel reply message, and chat conversation message are chatMessage, which is a class defined in graph.

2019-01-23 01:01 UTC, Lauragra commented on api-reference/beta/resources/chatmessage.md
> +|[Update DLP violation](../api/chatmessage-update-dlpviolation.md) | http response status| Update a chatMessage with a Data Loss Prevention (DLP) policy violation.|
HTTP response code is not a type. Should this say "None"?

2019-01-23 01:05 UTC, jthake-msft commented
OPS Build status updates of commit _[58cc5f2](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/58cc5f2451aded8f3152f24d5b4a188e8497b1d9)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 01:07 UTC, jthake-msft commented
OPS Build status updates of commit _[58cc5f2](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/58cc5f2451aded8f3152f24d5b4a188e8497b1d9)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 01:08 UTC, jthake-msft commented
OPS Build status updates of commit _[58cc5f2](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/58cc5f2451aded8f3152f24d5b4a188e8497b1d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901230105387879-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BKJDJUDhhrlXmgsgAtoxMkWZcSDY8Ci2RK1GR65z2Po%3D&st=2019-01-23T01%3A03%3A51Z&se=2019-02-23T01%3A08%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 05:46 UTC, degoh commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +PATCH https://graph.microsoft.com/v1.0/teams/{group-id}/channels/{channel-id}/messages/{message-id}
@jiawwu please provide the beta endpoint so that it can be updated

2019-01-23 05:47 UTC, degoh commented on api-reference/beta/resources/chatmessage.md
> +|[Update DLP violation](../api/chatmessage-update-dlpviolation.md) | http response status| Update a chatMessage with a Data Loss Prevention (DLP) policy violation.|
I will change this to none.

2019-01-23 05:47 UTC, degoh commented on api-reference/beta/api/chatmessage-update-dlpviolation.md
> +| verdictDetails | Bitwise Enum | Indicates the details of the allowed sender actions based on the verdict of the DLP app for the message processed. Possible values are None (0), AllowFalsePositiveOv
@jiawwu please validate that the types are accurate.

2019-01-23 05:48 UTC, jthake-msft commented
OPS Build status updates of commit _[0549764](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/0549764cddc8bffb560449f78f023151db10fa9d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 05:50 UTC, jthake-msft commented
OPS Build status updates of commit _[0549764](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/0549764cddc8bffb560449f78f023151db10fa9d)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 05:51 UTC, jthake-msft commented
OPS Build status updates of commit _[0549764](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/0549764cddc8bffb560449f78f023151db10fa9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901230548421573-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=b4o8RXdf2A%2BF4wrNqBtlJbibvIjNBNnJ8N5k5QSdivM%3D&st=2019-01-23T05%3A46%3A55Z&se=2019-02-23T05%3A51%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 19:03 UTC, jthake-msft commented
OPS Build status updates of commit _[fe6eee4](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/fe6eee4f241f3ccabdee1a06a183fa31bf018a58)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 19:05 UTC, jthake-msft commented
OPS Build status updates of commit _[fe6eee4](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/fe6eee4f241f3ccabdee1a06a183fa31bf018a58)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 19:07 UTC, jthake-msft commented
OPS Build status updates of commit _[fe6eee4](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/fe6eee4f241f3ccabdee1a06a183fa31bf018a58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901231903574615-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5kj4MK01T6%2B9QMTs8EUG%2BqKE7W4lj8WHsWLZVyI0HwA%3D&st=2019-01-23T19%3A02%3A15Z&se=2019-02-23T19%3A07%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 20:15 UTC, jthake-msft commented
OPS Build status updates of commit _[dfa787e](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/dfa787ef916df54de5ecf760eba81beaa3c1e8c8)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 20:15 UTC, jthake-msft commented
OPS Build status updates of commit _[dfa787e](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/dfa787ef916df54de5ecf760eba81beaa3c1e8c8)_: 

:clock10: **Pending**: waiting for processors ([24](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-01-23 20:16 UTC, jthake-msft commented
OPS Build status updates of commit _[dfa787e](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/dfa787ef916df54de5ecf760eba81beaa3c1e8c8)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 20:18 UTC, jthake-msft commented
OPS Build status updates of commit _[dfa787e](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/dfa787ef916df54de5ecf760eba81beaa3c1e8c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901232015211988-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4dylG3jpS%2B%2B0mjUASpSRGtmEf7cXTzVtjV9T1knxdQo%3D&st=2019-01-23T20%3A13%3A36Z&se=2019-02-23T20%3A18%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 22:30 UTC, jthake-msft commented
OPS Build status updates of commit _[6624b2f](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/6624b2f3298a32acee3fb535918c052ed6902f90)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 22:32 UTC, jthake-msft commented
OPS Build status updates of commit _[6624b2f](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/6624b2f3298a32acee3fb535918c052ed6902f90)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 22:34 UTC, jthake-msft commented
OPS Build status updates of commit _[6624b2f](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/6624b2f3298a32acee3fb535918c052ed6902f90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901232230482676-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Vhwo835ZWY1N5FPSlHBJceUziTSiOkeAiRGE3RQ%2FytY%3D&st=2019-01-23T22%3A29%3A38Z&se=2019-02-23T22%3A34%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 22:34 UTC, jthake-msft commented
OPS Build status updates of commit _[f08573d](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/f08573dfd33fb3e6e2b8b49b10a957225c2f5b7d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 22:36 UTC, jthake-msft commented
OPS Build status updates of commit _[f08573d](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/f08573dfd33fb3e6e2b8b49b10a957225c2f5b7d)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 22:38 UTC, jthake-msft commented
OPS Build status updates of commit _[f08573d](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/f08573dfd33fb3e6e2b8b49b10a957225c2f5b7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901232231366725-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=d1Dit7cqMkAmkAYYR8wNTO5C0qyW9I8yj9%2F0daa2DXc%3D&st=2019-01-23T22%3A33%3A19Z&se=2019-02-23T22%3A38%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 22:44 UTC, jthake-msft commented
OPS Build status updates of commit _[1ea82dc](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1ea82dca6b637491c7aa4b96777f2db0a884abca)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 22:45 UTC, jthake-msft commented
OPS Build status updates of commit _[1ea82dc](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1ea82dca6b637491c7aa4b96777f2db0a884abca)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 22:47 UTC, jthake-msft commented
OPS Build status updates of commit _[1ea82dc](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1ea82dca6b637491c7aa4b96777f2db0a884abca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901232244169627-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4SSoSq4h8qPrj2DEXNtIs%2B%2B%2BiyZANz5lzJsiu78psbs%3D&st=2019-01-23T22%3A42%3A50Z&se=2019-02-23T22%3A47%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-01-23 22:47 UTC, jthake-msft commented
OPS Build status updates of commit _[b7a86ee](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/b7a86ee69568d2e783822a59f52fa4761f64a662)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 22 sec(s)_

2019-01-23 22:49 UTC, jthake-msft commented
OPS Build status updates of commit _[b7a86ee](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/b7a86ee69568d2e783822a59f52fa4761f64a662)_: 

:clock10: **Incremental building**: average incremental building time is _1 min(s) 55 sec(s)_

2019-01-23 22:51 UTC, jthake-msft commented
OPS Build status updates of commit _[b7a86ee](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/b7a86ee69568d2e783822a59f52fa4761f64a662)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-dlpviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-dlpviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201901232244517152-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CXAIfSuglj3poDwoNWqvbk1ey8x8HmKfrOR7%2F1SC7Ww%3D&st=2019-01-23T22%3A46%3A18Z&se=2019-02-23T22%3A51%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-13 23:22 UTC, jthake-msft commented
OPS Build status updates of commit _[3b09137](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3b09137db7893aa609b3f27282eb1a22d8e70990)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-13 23:23 UTC, jthake-msft commented
OPS Build status updates of commit _[3b09137](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3b09137db7893aa609b3f27282eb1a22d8e70990)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\zgk1-s, target branch: master, target branch commit: 0ac9d6172aec70ea98b61a3ee568c7744e0b2f50, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902132322372558-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sNC30%2Fnj2YOcasS8DdB61jfNunNnmgcvl1RDt2zVi9w%3D&st=2019-02-13T23%3A18%3A33Z&se=2019-03-16T23%3A23%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-13 23:33 UTC, jthake-msft commented
OPS Build status updates of commit _[64dbb46](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/64dbb46f38d13936edb625c87537afe2fd551e40)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-13 23:34 UTC, jthake-msft commented
OPS Build status updates of commit _[64dbb46](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/64dbb46f38d13936edb625c87537afe2fd551e40)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\tvtf-s, target branch: master, target branch commit: 0ac9d6172aec70ea98b61a3ee568c7744e0b2f50, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902132333405911-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2B1g5ECYsI6Jeifo5MyM8H6PzWooz1pvT7C4RVArdvuI%3D&st=2019-02-13T23%3A29%3A38Z&se=2019-03-16T23%3A34%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-13 23:34 UTC, jthake-msft commented
OPS Build status updates of commit _[ab73833](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/ab73833444ed2bda2d353a490232e1848f95307c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-13 23:35 UTC, jthake-msft commented
OPS Build status updates of commit _[ab73833](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/ab73833444ed2bda2d353a490232e1848f95307c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\vocj-s, target branch: master, target branch commit: 0ac9d6172aec70ea98b61a3ee568c7744e0b2f50, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902132333558023-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3skXuoMZPZUAgtKYbNFRk1otx5EDyGeeZtbt2%2FlCXF4%3D&st=2019-02-13T23%3A30%3A47Z&se=2019-03-16T23%3A35%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-13 23:35 UTC, jthake-msft commented
OPS Build status updates of commit _[916c82f](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/916c82fee9df0ac859e4562b3d21efc5d26c6603)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-13 23:36 UTC, jthake-msft commented
OPS Build status updates of commit _[916c82f](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/916c82fee9df0ac859e4562b3d21efc5d26c6603)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\2l4x-s, target branch: master, target branch commit: 0ac9d6172aec70ea98b61a3ee568c7744e0b2f50, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902132334522897-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MfPiumGfqp27n4IcKx1i4Ss8dwtAEgWtUZi25PbFkio%3D&st=2019-02-13T23%3A31%3A50Z&se=2019-03-16T23%3A36%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 00:00 UTC, jthake-msft commented
OPS Build status updates of commit _[8f56376](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/8f56376c561ee9f47016e6a4c332ac7ad9025158)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 00:01 UTC, jthake-msft commented
OPS Build status updates of commit _[8f56376](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/8f56376c561ee9f47016e6a4c332ac7ad9025158)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\ppxw-s, target branch: master, target branch commit: 44760d8217b191be2f70f6a45e8332335fbbb99c, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902150000222475-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=trV6OmcqTE2pUSA%2FkYs0WNnu280z685%2F9%2ByxTaruPQE%3D&st=2019-02-14T23%3A56%3A21Z&se=2019-03-18T00%3A01%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 00:23 UTC, jthake-msft commented
OPS Build status updates of commit _[171b8e6](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/171b8e636b19d9d3246a30e6003e95aae9d29df0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 00:24 UTC, jthake-msft commented
OPS Build status updates of commit _[171b8e6](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/171b8e636b19d9d3246a30e6003e95aae9d29df0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\hjtp-s, target branch: master, target branch commit: 44760d8217b191be2f70f6a45e8332335fbbb99c, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902150023275982-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9e8YSmCNOTXIhk28GQr18fKbSZlhG3mtfX8E7WR5Nak%3D&st=2019-02-15T00%3A19%3A28Z&se=2019-03-18T00%3A24%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 20:16 UTC, jthake-msft commented
OPS Build status updates of commit _[f34cd00](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/f34cd002755d6d1af3074e65ae3cb73f451e22f2)_: 

:clock10: **Pending**: waiting for processors ([61](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 20:27 UTC, jthake-msft commented
OPS Build status updates of commit _[f34cd00](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/f34cd002755d6d1af3074e65ae3cb73f451e22f2)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 20:28 UTC, jthake-msft commented
OPS Build status updates of commit _[f34cd00](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/f34cd002755d6d1af3074e65ae3cb73f451e22f2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\dd2v-s, target branch: master, target branch commit: 43b9a378c29202a8cef31117d752f00807feb2f5, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902152016320626-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JFwl3EVnHh2XLG45fKHu%2F9zRI7QrgveeO2Z3kIIwxoc%3D&st=2019-02-15T20%3A23%3A40Z&se=2019-03-18T20%3A28%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 21:32 UTC, jthake-msft commented
OPS Build status updates of commit _[adeb219](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/adeb219f79a753682d77fa68d3c0960960660824)_: 

:clock10: **Pending**: waiting for processors ([75](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 21:32 UTC, jthake-msft commented
OPS Build status updates of commit _[adeb219](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/adeb219f79a753682d77fa68d3c0960960660824)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 21:32 UTC, jthake-msft commented
OPS Build status updates of commit _[e657fbc](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e657fbc8b87d81560462ef19a9e5bebdfafc2838)_: 

:clock10: **Pending**: waiting for processors ([72](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 21:33 UTC, jthake-msft commented
OPS Build status updates of commit _[adeb219](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/adeb219f79a753682d77fa68d3c0960960660824)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\mwbh-s, target branch: master, target branch commit: 43b9a378c29202a8cef31117d752f00807feb2f5, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902152132133186-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6Qwd%2FE4%2B12w70TgFQzt2GSlfM8imhrlMrixJEsVvy%2FI%3D&st=2019-02-15T21%3A28%3A22Z&se=2019-03-18T21%3A33%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 21:33 UTC, jthake-msft commented
OPS Build status updates of commit _[054b705](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/054b70557750b5b0c4382711a8b1a1779a334fe3)_: 

:clock10: **Pending**: waiting for processors ([72](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 21:33 UTC, jthake-msft commented
OPS Build status updates of commit _[d788da5](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/d788da5e7c9df99aabfe65ec1292a80f8decc842)_: 

:clock10: **Pending**: waiting for processors ([72](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 21:34 UTC, jthake-msft commented
OPS Build status updates of commit _[e657fbc](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e657fbc8b87d81560462ef19a9e5bebdfafc2838)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 21:35 UTC, jthake-msft commented
OPS Build status updates of commit _[e657fbc](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e657fbc8b87d81560462ef19a9e5bebdfafc2838)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\ycle-s, target branch: master, target branch commit: 43b9a378c29202a8cef31117d752f00807feb2f5, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902152132332884-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SeDNexTGV5C50t%2FlYFUOP4RFKt363gSimZdYjJz0jAs%3D&st=2019-02-15T21%3A30%3A12Z&se=2019-03-18T21%3A35%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 21:44 UTC, jthake-msft commented
OPS Build status updates of commit _[e03dd68](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e03dd687607780a854360703d37441346ab68252)_: 

:clock10: **Pending**: waiting for processors ([87](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 21:45 UTC, jthake-msft commented
OPS Build status updates of commit _[e03dd68](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e03dd687607780a854360703d37441346ab68252)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 21:46 UTC, jthake-msft commented
OPS Build status updates of commit _[e03dd68](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e03dd687607780a854360703d37441346ab68252)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\rnhu-s, target branch: master, target branch commit: 0526f782836d6e7fc1339b42f98db112ec983680, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902152144233545-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Mjyp62pvQFKFJtMT3Genn3LvDp8xVDxCSgnAy5AjQUA%3D&st=2019-02-15T21%3A41%3A03Z&se=2019-03-18T21%3A46%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 21:47 UTC, jthake-msft commented
OPS Build status updates of commit _[e47ada9](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e47ada9087a6c72a991386e8acf88c4cf85915c1)_: 

:clock10: **Pending**: waiting for processors ([73](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 21:47 UTC, jthake-msft commented
OPS Build status updates of commit _[e47ada9](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e47ada9087a6c72a991386e8acf88c4cf85915c1)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 21:48 UTC, jthake-msft commented
OPS Build status updates of commit _[a70565b](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/a70565b20ab0bb3d30254e03a5098bfe472bd1f5)_: 

:clock10: **Pending**: waiting for processors ([73](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

2019-02-15 21:48 UTC, jthake-msft commented
OPS Build status updates of commit _[e47ada9](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/e47ada9087a6c72a991386e8acf88c4cf85915c1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\1ta4-s, target branch: master, target branch commit: 0526f782836d6e7fc1339b42f98db112ec983680, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902152147264847-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Azvqv6CgrMXA%2FaNs%2FVIyZbcOxQkK0uH6%2FxRUInCK8TQ%3D&st=2019-02-15T21%3A43%3A43Z&se=2019-03-18T21%3A48%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 21:49 UTC, jthake-msft commented
OPS Build status updates of commit _[a70565b](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/a70565b20ab0bb3d30254e03a5098bfe472bd1f5)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 24 sec(s)_

2019-02-15 21:50 UTC, jthake-msft commented
OPS Build status updates of commit _[a70565b](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/a70565b20ab0bb3d30254e03a5098bfe472bd1f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\jeyo-s, target branch: master, target branch commit: 0526f782836d6e7fc1339b42f98db112ec983680, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201902152148194956-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YgEa08%2Bjl73ZcOyFC0fGMY53juzk%2Fkw9dj4bekHQtF0%3D&st=2019-02-15T21%3A45%3A33Z&se=2019-03-18T21%3A50%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-02-15 22:55 UTC, Lauragra commented on api-reference/beta/api/dlpaction.md
> +---
Please see the guidance for documenting enums, here: https://msgo.azurewebsites.net/add/document/guidelines/enumerations.html. Basically, you'll want to add a "dlpAction values" H3 to the enums.md file with your table listing the values.

2019-02-15 22:55 UTC, Lauragra commented on api-reference/beta/api/policytip.md
> +---
What is the intent for this topic? It is currently incomplete.

2019-02-15 22:56 UTC, Lauragra commented on api-reference/beta/api/policyviolation.md
> +title: "PolicyViolation Resource"
Please also clarify - this topic is currently incomplete.

2019-03-06 01:31 UTC, jthake-msft commented
OPS Build status updates of commit _[dec0ef1](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/dec0ef116eb355e835615798a9cd89ac2f4b513b)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

2019-03-06 01:33 UTC, jthake-msft commented
OPS Build status updates of commit _[dec0ef1](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/dec0ef116eb355e835615798a9cd89ac2f4b513b)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

2019-03-06 01:35 UTC, jthake-msft commented
OPS Build status updates of commit _[dec0ef1](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/dec0ef116eb355e835615798a9cd89ac2f4b513b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fdlpaction.md)
[api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicytip.md)
[api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md)
[api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuseraction.md)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fverdictdetails.md)
[api-reference/beta/api/update-chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/update-chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fapi%2Fdlpaction.md"></a>
### [api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicytip.md"></a>
### [api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md"></a>
### [api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 100) - (Line: 3, Col: 16, Idx: 106): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fuseraction.md"></a>
### [api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fverdictdetails.md"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903060131411516-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=g%2BDSdjA8piCHaBRsMA2K2yrH%2F3BB8VGR8CO%2FptgofDE%3D&st=2019-03-06T01%3A30%3A09Z&se=2019-04-06T01%3A35%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-03-06 18:54 UTC, jthake-msft commented
OPS Build status updates of commit _[3671243](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3671243567e9758424ba958610a9564f983ec087)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

2019-03-06 18:55 UTC, jthake-msft commented
OPS Build status updates of commit _[3671243](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3671243567e9758424ba958610a9564f983ec087)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

2019-03-06 18:57 UTC, jthake-msft commented
OPS Build status updates of commit _[3671243](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3671243567e9758424ba958610a9564f983ec087)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fdlpaction.md)
[api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicytip.md)
[api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md)
[api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuseraction.md)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fverdictdetails.md)
[api-reference/beta/api/update-chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/update-chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fapi%2Fdlpaction.md"></a>
### [api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicytip.md"></a>
### [api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md"></a>
### [api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 100) - (Line: 3, Col: 16, Idx: 106): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fuseraction.md"></a>
### [api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fverdictdetails.md"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903061854012096-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lQ8dY9mnp55Jx4t0peRcIpslfL0ILxJPezKDeLQH%2B84%3D&st=2019-03-06T18%3A52%3A40Z&se=2019-04-06T18%3A57%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-03-06 21:37 UTC, jthake-msft commented
OPS Build status updates of commit _[957c815](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/957c8151e92ec86b2fe30b5d5171b7346514713a)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

2019-03-06 21:37 UTC, degoh commented on api-reference/beta/api/policytip.md
> +---
Added description

2019-03-06 21:38 UTC, jthake-msft commented
OPS Build status updates of commit _[957c815](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/957c8151e92ec86b2fe30b5d5171b7346514713a)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

2019-03-06 21:40 UTC, degoh commented on api-reference/beta/api/policyviolation.md
> +title: "PolicyViolation Resource"
Added description.

2019-03-06 21:40 UTC, jthake-msft commented
OPS Build status updates of commit _[957c815](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/957c8151e92ec86b2fe30b5d5171b7346514713a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fdlpaction.md)
[api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicytip.md)
[api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md)
[api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuseraction.md)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fverdictdetails.md)
[api-reference/beta/api/update-chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/update-chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fapi%2Fdlpaction.md"></a>
### [api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicytip.md"></a>
### [api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md"></a>
### [api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 100) - (Line: 3, Col: 16, Idx: 106): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fuseraction.md"></a>
### [api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fverdictdetails.md"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903062137137640-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8pWk9tWzrez7hflPqvOvhQraEq6D3W4tfKYIFBTwKg0%3D&st=2019-03-06T21%3A35%3A52Z&se=2019-04-06T21%3A40%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-03-06 21:40 UTC, jthake-msft commented
OPS Build status updates of commit _[7f3afd0](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/7f3afd0d90d30656faa4e43b0803446ed793eeae)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

2019-03-06 21:42 UTC, jthake-msft commented
OPS Build status updates of commit _[7f3afd0](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/7f3afd0d90d30656faa4e43b0803446ed793eeae)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

2019-03-06 21:44 UTC, jthake-msft commented
OPS Build status updates of commit _[7f3afd0](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/7f3afd0d90d30656faa4e43b0803446ed793eeae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fdlpaction.md)
[api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicytip.md)
[api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md)
[api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuseraction.md)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fverdictdetails.md)
[api-reference/beta/api/update-chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/update-chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fapi%2Fdlpaction.md"></a>
### [api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicytip.md"></a>
### [api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md"></a>
### [api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 100) - (Line: 3, Col: 16, Idx: 106): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fuseraction.md"></a>
### [api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fverdictdetails.md"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903062139540319-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=T9dYLsLZ%2B9KNFIXWd4GNkUiUQ479oucOn4evSZM9tt8%3D&st=2019-03-06T21%3A39%3A27Z&se=2019-04-06T21%3A44%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-03-06 23:55 UTC, jthake-msft commented
OPS Build status updates of commit _[3f325ed](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3f325ed41fce55a683608256d6637028169d3151)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

2019-03-06 23:57 UTC, jthake-msft commented
OPS Build status updates of commit _[3f325ed](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3f325ed41fce55a683608256d6637028169d3151)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 4 sec(s)_

2019-03-06 23:59 UTC, jthake-msft commented
OPS Build status updates of commit _[3f325ed](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/3f325ed41fce55a683608256d6637028169d3151)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fdlpaction.md)
[api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicytip.md)
[api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md)
[api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuseraction.md)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fverdictdetails.md)
[api-reference/beta/api/update-chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/update-chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fapi%2Fdlpaction.md"></a>
### [api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicytip.md"></a>
### [api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md"></a>
### [api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 100) - (Line: 3, Col: 16, Idx: 106): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fuseraction.md"></a>
### [api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fverdictdetails.md"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903062355470354-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VBvRc9PWxz5Qp1Opz4qDAZH4LPhff%2FHScmIyQFxzvtQ%3D&st=2019-03-06T23%3A54%3A21Z&se=2019-04-06T23%3A59%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-03-06 23:59 UTC, jthake-msft commented
OPS Build status updates of commit _[1e110b1](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1e110b17c71c45c105731b07d23f2668f6de121f)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

2019-03-07 00:00 UTC, jthake-msft commented
OPS Build status updates of commit _[1e110b1](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/1e110b17c71c45c105731b07d23f2668f6de121f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\5nwo-s, target branch: master, target branch commit: 5f0619bcba12f024efecea37ef73092355d080f3, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903062356208725-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jczWb6fNs68aw1gU1gXN5mAjkH%2BL7%2FEypoP1IOfVV5E%3D&st=2019-03-06T23%3A55%3A28Z&se=2019-04-07T00%3A00%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-03-08 19:17 UTC, jthake-msft commented
OPS Build status updates of commit _[05cf484](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/05cf48483ee0aa40afffd63a2d9ff1f3d01370ad)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 26 sec(s)_

2019-03-08 19:19 UTC, jthake-msft commented
OPS Build status updates of commit _[05cf484](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/05cf48483ee0aa40afffd63a2d9ff1f3d01370ad)_: 

:clock10: **Incremental building**: average incremental building time is _2 min(s) 5 sec(s)_

2019-03-08 19:21 UTC, jthake-msft commented
OPS Build status updates of commit _[05cf484](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/05cf48483ee0aa40afffd63a2d9ff1f3d01370ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fdlpaction.md)
[api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicytip.md)
[api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md)
[api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fuseraction.md)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | | [Details](#user-content-api-reference%2Fbeta%2Fapi%2Fverdictdetails.md)
[api-reference/beta/api/update-chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/update-chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | |

<a name="api-reference%2Fbeta%2Fapi%2Fdlpaction.md"></a>
### [api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicytip.md"></a>
### [api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fpolicyviolation.md"></a>
### [api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 100) - (Line: 3, Col: 16, Idx: 106): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fuseraction.md"></a>
### [api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.

<a name="api-reference%2Fbeta%2Fapi%2Fverdictdetails.md"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **Line 0**: **[Warning]** (Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201903081917521104-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Li%2BN%2Fc7tlWb3W4WLiFr8bMssYtBOL0YLB%2FQmOcFgW54%3D&st=2019-03-08T19%3A16%3A30Z&se=2019-04-08T19%3A21%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-04-09 22:14 UTC, opbld32 commented
Docs Build status updates of commit _[d6cdf3b](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/d6cdf3bbc6d1f6fcee8541f92683f05ed5662f3a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-92ccb347)

<a id="92ccb347"></a>
###
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\baiy-s, target branch: master, target branch commit: c5561199b70cadc311e4c22e1d6031c5d100df5b, source branch: 00451b014402a925053b57c277203570/jiawwu-DLP-20190122, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201904092214171126-3839%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RwGXEbE0S%2BY8IkLIpKt8jqPPPCEjjea4uPK%2Fn3DgFMY%3D&st=2019-04-09T22%3A09%3A54Z&se=2019-05-10T22%3A14%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-07-18 16:51 UTC, opbld33 commented
Docs Build status updates of commit _[2695c12](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/2695c127e6fcd99a3da35598646da35215d3f449)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/dlpaction?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-b2bb38aa-1681151d)
[api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-88923bc5-1681151d)
[api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-f71961cf-1681151d)
[api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/useraction?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-78339b46-1681151d)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/verdictdetails?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-01073d5a-1681151d)
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-1681151d)
[api-reference/beta/api/update-chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/update-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/update-chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) |

<a id="b2bb38aa-1681151d"></a>
### [api-reference/beta/api/dlpaction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/dlpaction.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="88923bc5-1681151d"></a>
### [api-reference/beta/api/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policytip.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 88) - (Line: 3, Col: 16, Idx: 94): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="f71961cf-1681151d"></a>
### [api-reference/beta/api/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/policyviolation.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 100) - (Line: 3, Col: 16, Idx: 106): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="78339b46-1681151d"></a>
### [api-reference/beta/api/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/useraction.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="01073d5a-1681151d"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="97ee62ac-1681151d"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 25**: **[Warning]** `````Invalid file link:(~/beta/api/channel-post-chatmessage.md).`````
 - **Line 50**: **[Warning]** `````Invalid file link:(~/beta/resources/chatmention.md).`````
 - **Line 52**: **[Warning]** `````Invalid file link:(~/beta/resources/chatreaction.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201907181648340610-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o2cVv4%2FapZp882CODypSgj%2FG4f%2FHvfpwWgM2rLF3zDc%3D&st=2019-07-18T16%3A46%3A43Z&se=2019-08-18T16%3A51%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-07-19 02:21 UTC, clearab commented on api-reference/beta/api/useraction.md
> +title: "useraction Resource"
@jiawwu Is this a resource type, or an enum?

2019-07-19 02:23 UTC, clearab commented on api-reference/beta/api/verdictdetails.md
> +---
@jiawwu Is this a resource type, or an just an enum?

2019-07-19 02:27 UTC, clearab commented on api-reference/beta/resources/chatmessagepolicyviolation.md
> +---
@jiawwu What's the difference between this an the policyviolation? Should there be only one?

2019-07-19 03:00 UTC, opbld33 commented
Docs Build status updates of commit _[f442b3a](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/f442b3ae55ae09433ba935c4952864817e84b05a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-361ba3ef-ab17643e)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/verdictdetails?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-01073d5a-ab17643e)
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-ab17643e)
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-41077463-ab17643e)
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-b272b3c4-ab17643e)
[api-reference/beta/resources/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/useraction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/useraction?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-0a4a3155-ab17643e)
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) |

<a id="361ba3ef-ab17643e"></a>
### [api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md)
 - **Line 45**: **[Warning]** `````Invalid file link:(~/beta/api/policyviolation.md).`````

<a id="01073d5a-ab17643e"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="97ee62ac-ab17643e"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 24**: **[Warning]** `````Invalid file link:(~/beta/api/channel-post-chatmessage.md).`````
 - **Line 50**: **[Warning]** `````Invalid file link:(~/beta/resources/chatmention.md).`````
 - **Line 52**: **[Warning]** `````Invalid file link:(~/beta/resources/chatreaction.md).`````

<a id="41077463-ab17643e"></a>
### [api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md)
 - **Line 21**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````

<a id="b272b3c4-ab17643e"></a>
### [api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md)
 - **Line 17**: **[Warning]** `````Invalid file link:(~/beta/resources/verdictdetails.md).`````
 - **Line 18**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````

<a id="0a4a3155-ab17643e"></a>
### [api-reference/beta/resources/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/useraction.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201907190257388456-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FVP%2BkDXzEPMa6fkPVuf0snJ69JIX4I331dRT%2BgC3UJk%3D&st=2019-07-19T02%3A55%3A49Z&se=2019-08-19T03%3A00%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-07-19 21:14 UTC, jiawwu commented on api-reference/beta/api/verdictdetails.md
> +---
this is an enum type for field "verdictDetails"

2019-07-19 21:21 UTC, jiawwu commented on api-reference/beta/api/useraction.md
> +title: "useraction Resource"
enum

2019-07-19 22:48 UTC, jiawwu commented on api-reference/beta/resources/chatmessagepolicyviolation.md
> +---
I did not prepare the content. They do describe the same class object but seems for difference audience. 
Feel free to modify if needed

2019-07-23 18:22 UTC, opbld34 commented
Docs Build status updates of commit _[eb7e05d](https://github.com/jiawwu/microsoft-graph-docs/pull/3839/commits/eb7e05d84be9698f45000d623125ad9ce40d4b61)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-361ba3ef-1cd95d0d)
[api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/verdictdetails?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-01073d5a-1cd95d0d)
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-1cd95d0d)
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-41077463-1cd95d0d)
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-b272b3c4-1cd95d0d)
[api-reference/beta/resources/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/useraction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/useraction?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-0a4a3155-1cd95d0d)
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) |

<a id="361ba3ef-1cd95d0d"></a>
### [api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md)
 - **Line 45**: **[Warning]** `````Invalid file link:(~/beta/api/policyviolation.md).`````

<a id="01073d5a-1cd95d0d"></a>
### [api-reference/beta/api/verdictdetails.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/verdictdetails.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 98) - (Line: 3, Col: 16, Idx: 104): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

<a id="97ee62ac-1cd95d0d"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 24**: **[Warning]** `````Invalid file link:(~/beta/api/channel-post-chatmessage.md).`````
 - **Line 50**: **[Warning]** `````Invalid file link:(~/beta/resources/chatmention.md).`````
 - **Line 52**: **[Warning]** `````Invalid file link:(~/beta/resources/chatreaction.md).`````

<a id="41077463-1cd95d0d"></a>
### [api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md)
 - **Line 21**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````

<a id="b272b3c4-1cd95d0d"></a>
### [api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md)
 - **Line 17**: **[Warning]** `````Invalid file link:(~/beta/resources/verdictdetails.md).`````
 - **Line 18**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````

<a id="0a4a3155-1cd95d0d"></a>
### [api-reference/beta/resources/useraction.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/useraction.md)
 - **[Warning]** `````(Line: 3, Col: 10, Idx: 90) - (Line: 3, Col: 16, Idx: 96): While parsing a block mapping, did not find expected key.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201907231819530239-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L3mLt47nFE13D0xJi%2F9Jjs64EgcURT2s4i8YhGgMncQ%3D&st=2019-07-23T18%3A17%3A53Z&se=2019-08-23T18%3A22%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 20:54 UTC, opbld32 commented
Docs Build status updates of commit _[7109609](https://github.com/jiawwu/microsoft-graph-docs/commits/71096097f8624a9191299c7ac70390f0e31c61bc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c0f69c9b)

<a id="c0f69c9b"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\u52k-s, target branch: HEAD, target branch commit: 14222fda75ec8166c482ff80618d8b18c776c3a5, source commit: 71096097f8624a9191299c7ac70390f0e31c61bc.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182053297944-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uIhX2k69nOBt7coV9h5vz0wE9CjAXM3EvTrzZ2C%2FD7Y%3D&st=2019-08-18T20%3A49%3A14Z&se=2019-09-18T20%3A54%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 20:59 UTC, opbld31 commented
Docs Build status updates of commit _[9e447b6](https://github.com/jiawwu/microsoft-graph-docs/commits/9e447b6e88b346016531e4fcd790de1cb1275847)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-361ba3ef-4eb24c35)
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-4eb24c35)
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-41077463-4eb24c35)
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-b272b3c4-4eb24c35)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-4eb24c35)
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-4eb24c35)
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="361ba3ef-4eb24c35"></a>
### [api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md)
 - **Line 46**: **[Warning]** `````Invalid file link:(~/beta/api/policyviolation.md).`````

<a id="97ee62ac-4eb24c35"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 25**: **[Warning]** `````Invalid file link:(~/beta/api/channel-post-chatmessage.md).`````
 - **Line 51**: **[Warning]** `````Invalid file link:(~/beta/resources/chatmention.md).`````
 - **Line 53**: **[Warning]** `````Invalid file link:(~/beta/resources/chatreaction.md).`````

<a id="41077463-4eb24c35"></a>
### [api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md)
 - **Line 21**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````

<a id="b272b3c4-4eb24c35"></a>
### [api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md)
 - **Line 18**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````
 - **Line 19**: **[Warning]** `````Invalid file link:(~/beta/resources/useraction.md).`````

<a id="7a1003a0-4eb24c35"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="3e83d71e-4eb24c35"></a>
### [api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182056123550-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NdCV%2BocX6ms%2B1w9k5NlAh0Fxpvm6QsT6xx69Y84wvZE%3D&st=2019-08-18T20%3A54%3A25Z&se=2019-09-18T20%3A59%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 21:18 UTC, opbld30 commented
Docs Build status updates of commit _[4d30a83](https://github.com/jiawwu/microsoft-graph-docs/commits/4d30a83ee0a6a2c5d1d0f838fc27c3e49793afca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-b6cb0c97)
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-41077463-b6cb0c97)
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-b272b3c4-b6cb0c97)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-b6cb0c97)
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-b6cb0c97)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-b6cb0c97"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 25**: **[Warning]** `````Invalid file link:(~/beta/api/channel-post-chatmessage.md).`````
 - **Line 51**: **[Warning]** `````Invalid file link:(~/beta/resources/chatmention.md).`````
 - **Line 53**: **[Warning]** `````Invalid file link:(~/beta/resources/chatreaction.md).`````

<a id="41077463-b6cb0c97"></a>
### [api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md)
 - **Line 21**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````

<a id="b272b3c4-b6cb0c97"></a>
### [api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md)
 - **Line 18**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````
 - **Line 19**: **[Warning]** `````Invalid file link:(~/beta/resources/useraction.md).`````

<a id="7a1003a0-b6cb0c97"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="3e83d71e-b6cb0c97"></a>
### [api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182114502724-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k%2Bnoy8IJYlHzciqC5NlHT1KetUb7nzzXIaPSUaKwV4M%3D&st=2019-08-18T21%3A13%3A08Z&se=2019-09-18T21%3A18%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 21:40 UTC, opbld30 commented
Docs Build status updates of commit _[971002f](https://github.com/jiawwu/microsoft-graph-docs/commits/971002fac9d5efe2a152270c48fbc8a4b1be26b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-41077463-ffb2d7fa)
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-b272b3c4-ffb2d7fa)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-ffb2d7fa)
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-ffb2d7fa)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="41077463-ffb2d7fa"></a>
### [api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md)
 - **Line 22**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpAction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpAction-values.`````
 - **Line 25**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#userAction-values">userAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named userAction-values.`````

<a id="b272b3c4-ffb2d7fa"></a>
### [api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md)
 - **Line 19**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpAction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpAction-values.`````
 - **Line 20**: **[Warning]** `````Invalid file link:(~/beta/resources/useraction.md).`````

<a id="7a1003a0-ffb2d7fa"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="3e83d71e-ffb2d7fa"></a>
### [api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182136453101-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OqgnhC%2FqunClFirHuIf9Bl7%2FsuG4R6EcIlh0%2B4BI4Cg%3D&st=2019-08-18T21%3A35%3A00Z&se=2019-09-18T21%3A40%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 22:06 UTC, opbld33 commented
Docs Build status updates of commit _[80e7c71](https://github.com/jiawwu/microsoft-graph-docs/commits/80e7c7166ffc859e802427c635d0f12c5bebbd95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-41077463-91252eca)
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-b272b3c4-91252eca)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-91252eca)
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-91252eca)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="41077463-91252eca"></a>
### [api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md)
 - **Line 22**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````

<a id="b272b3c4-91252eca"></a>
### [api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md)
 - **Line 19**: **[Warning]** `````Illegal link: `<a href="beta/resources/enums.md#dlpaction-values">dlpAction</a>` -- missing bookmark. The file beta/resources/enums.md doesn't contain a bookmark named dlpaction-values.`````
 - **Line 20**: **[Warning]** `````Invalid file link:(~/beta/resources/useraction.md).`````

<a id="7a1003a0-91252eca"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="3e83d71e-91252eca"></a>
### [api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182202465394-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pU5wJ9hDPNJa6BTVKXWPk9Wsx9IKGH5IdKRwc3cw5ds%3D&st=2019-08-18T22%3A01%3A11Z&se=2019-09-18T22%3A06%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 22:18 UTC, opbld31 commented
Docs Build status updates of commit _[f51bc0a](https://github.com/jiawwu/microsoft-graph-docs/commits/f51bc0a842df329561a28bb1473305648b8e1206)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-9f334b1a)
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-9f334b1a)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-9f334b1a"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="3e83d71e-9f334b1a"></a>
### [api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182215305429-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w1I0SIbGg6Bjf4egBIHieV9iKCTwSigJSG%2BG7TWRUYc%3D&st=2019-08-18T22%3A13%3A49Z&se=2019-09-18T22%3A18%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 22:39 UTC, opbld33 commented
Docs Build status updates of commit _[f7135a9](https://github.com/jiawwu/microsoft-graph-docs/commits/f7135a9f698b92ff230bc226d2c6768c58cf8679)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-87e2bcf4)
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-87e2bcf4)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-87e2bcf4"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="3e83d71e-87e2bcf4"></a>
### [api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182235544890-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QF70Ci1CHdFsPNI%2FghaDpeIxKKozcj1dy8NVP5xsYaE%3D&st=2019-08-18T22%3A33%3A59Z&se=2019-09-18T22%3A38%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-18 22:59 UTC, opbld30 commented
Docs Build status updates of commit _[98e5935](https://github.com/jiawwu/microsoft-graph-docs/commits/98e5935b23477aae874468f54cf7fed2b51aa16b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-215f8905)
[api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-3839) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-215f8905)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-215f8905"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="3e83d71e-215f8905"></a>
### [api-reference/v1.0/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/v1.0/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908182256427262-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YjUoCucTGN6Y9EfeIHx9pIrYXz1GUmTjobRUBBqY%2BuE%3D&st=2019-08-18T22%3A54%3A52Z&se=2019-09-18T22%3A59%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 00:48 UTC, opbld33 commented
Docs Build status updates of commit _[57b540b](https://github.com/jiawwu/microsoft-graph-docs/commits/57b540b5b5a629013ead96f2c35a6ea11a1c822f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-68125efa)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-68125efa)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-68125efa"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 55**: **[Warning]** `````Invalid file link:(~/beta/resources/chatmessagepolicyviolation.md).`````

<a id="7a1003a0-68125efa"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908220044510436-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Abn2gJgxucS6272%2FFCme4%2FKgzrJ8cBJGpKKTf53D0jY%3D&st=2019-08-22T00%3A43%3A01Z&se=2019-09-22T00%3A48%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 01:50 UTC, opbld33 commented
Docs Build status updates of commit _[2516411](https://github.com/jiawwu/microsoft-graph-docs/commits/251641149f677c749562c9fdb37a78bcecf7bc7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-3e4c8b3e)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-3e4c8b3e"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908220147413081-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=piWklIihUMvRTrfAiwwvraiOq1YM0PvimvHQ%2FTPz%2B1s%3D&st=2019-08-22T01%3A45%3A56Z&se=2019-09-22T01%3A50%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 02:01 UTC, opbld31 commented
Docs Build status updates of commit _[8c8e1b9](https://github.com/jiawwu/microsoft-graph-docs/commits/8c8e1b9a6c23d02a65313f38879c4e1d33a51514)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-5499e744)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-5499e744"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908220158162093-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7t4BmbS9mXzV0q2BcxjYzSB6wlRcVkA6Falu3nMut5E%3D&st=2019-08-22T01%3A56%3A30Z&se=2019-09-22T02%3A01%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 02:05 UTC, opbld32 commented
Docs Build status updates of commit _[45d13f8](https://github.com/jiawwu/microsoft-graph-docs/commits/45d13f8dcb631457c6c1ad4b966d1626f80f929f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-f893c34f)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-f893c34f"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908220202185058-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D1AMIgJN8AFwDaybayzYxcwriYzyblU%2FbT2fKnLGgec%3D&st=2019-08-22T02%3A00%3A48Z&se=2019-09-22T02%3A05%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 02:15 UTC, opbld30 commented
Docs Build status updates of commit _[990d563](https://github.com/jiawwu/microsoft-graph-docs/commits/990d563ae83174a1546d51742d310f9874ae7e47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-ba608dbb)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-ba608dbb"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908220212247404-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KVo1uvReM6W7FF9abe1Kae4duAUFFdNmmiboER9BC90%3D&st=2019-08-22T02%3A10%3A39Z&se=2019-09-22T02%3A15%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 19:09 UTC, opbld31 commented
Docs Build status updates of commit _[2bd181a](https://github.com/jiawwu/microsoft-graph-docs/commits/2bd181a607774a9f7fcddaa0d5fddde74768a133)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-849fd399)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-849fd399)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-849fd399"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 55**: **[Warning]** `````Invalid file link:(~/beta/resources/policyviolation.md).`````

<a id="7a1003a0-849fd399"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908221906102390-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aGRLG8rBKO%2ByFXAhQG1rqABLZG0Y4O8ZiRfssSj1Tn0%3D&st=2019-08-22T19%3A04%3A23Z&se=2019-09-22T19%3A09%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 19:14 UTC, opbld34 commented
Docs Build status updates of commit _[ccd5f32](https://github.com/jiawwu/microsoft-graph-docs/commits/ccd5f32ed7d0b216ec75899d19bca022eb621788)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-8755f3c3)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-8755f3c3"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908221911398248-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fAODYG1S1XvliAtaQod%2BR0vzwcM6bH4Z1qBHYtsX%2B%2BM%3D&st=2019-08-22T19%3A09%3A58Z&se=2019-09-22T19%3A14%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 19:23 UTC, opbld34 commented
Docs Build status updates of commit _[462c348](https://github.com/jiawwu/microsoft-graph-docs/commits/462c348b579c6fe1ac09337607964411b7ff27fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-1d326c59)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-1d326c59"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908221919419478-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZINzqjDXicgjAyXXETv6PPyfEYcs6ChkhaOmU3x4iW4%3D&st=2019-08-22T19%3A18%3A08Z&se=2019-09-22T19%3A23%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-22 19:38 UTC, opbld33 commented
Docs Build status updates of commit _[da28fa4](https://github.com/jiawwu/microsoft-graph-docs/commits/da28fa43e2dabfb4a5c43b5fbbaaa8086b977175)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-7a3d9bfa)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-7a3d9bfa"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908221934497933-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iHEdYg5DQ165k4ec3T2gTNN%2Fxa1d1jzfE0%2FykPfo02Y%3D&st=2019-08-22T19%3A33%3A02Z&se=2019-09-22T19%3A38%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-23 19:03 UTC, opbld34 commented
Docs Build status updates of commit _[76eceab](https://github.com/jiawwu/microsoft-graph-docs/commits/76eceaba0c1dd2cf659aea7c5e1e49c5f27bf392)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-2a52a7f4)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-2a52a7f4"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908231859380137-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p%2FPnkodOuCIUDvB580sLxRHPZ5HXvz8eZHUE1iekSJc%3D&st=2019-08-23T18%3A58%3A01Z&se=2019-09-23T19%3A03%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-23 19:06 UTC, opbld32 commented
Docs Build status updates of commit _[5bc8e01](https://github.com/jiawwu/microsoft-graph-docs/commits/5bc8e01f0097d0da3736174d3cb35eece3843407)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-bd98af7e)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-bd98af7e"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908231903054539-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AR8tMrzHDsxbHw%2BmGfmk5NN3LTYTVt1UpK4%2FQaZ2y%2BM%3D&st=2019-08-23T19%3A01%3A16Z&se=2019-09-23T19%3A06%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-23 19:13 UTC, opbld32 commented
Docs Build status updates of commit _[f967291](https://github.com/jiawwu/microsoft-graph-docs/commits/f96729134a79c79716c8e6bc24e50826480f65e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-00ccc8a8)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-00ccc8a8"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908231910086766-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PRhPDAXRBT%2FgXtJrsTuvE1hlvdh5zfSyJ7ufx9NCBXM%3D&st=2019-08-23T19%3A08%3A25Z&se=2019-09-23T19%3A13%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-23 19:17 UTC, opbld31 commented
Docs Build status updates of commit _[bd99734](https://github.com/jiawwu/microsoft-graph-docs/commits/bd997345ff015fff30cc1ae6fc048562f601db39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-6de4ae2a)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-6de4ae2a"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908231913509782-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iOeSSlT1dNBMF1Qa0oIV%2B6yysaOG7GbjkHfT5ul94ig%3D&st=2019-08-23T19%3A12%3A09Z&se=2019-09-23T19%3A17%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-23 19:22 UTC, opbld32 commented
Docs Build status updates of commit _[444cf8a](https://github.com/jiawwu/microsoft-graph-docs/commits/444cf8ac8c3ac221c6ae08c5c6fe5e17bd280880)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-c297305b)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-c297305b"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908231919276838-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YxchtlYcq415lBMTgNzoBgi8azV7t6txD3RZW8gn7R0%3D&st=2019-08-23T19%3A17%3A38Z&se=2019-09-23T19%3A22%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-24 00:46 UTC, opbld33 commented
Docs Build status updates of commit _[712c277](https://github.com/jiawwu/microsoft-graph-docs/commits/712c2774921d8671a7b94f20b90b991df5546830)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-8f36340a)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-8f36340a"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908240043375970-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8ejQCbgLMDoavcSrZpHR4PvhadPctfaL8oFuw9ipc%2BE%3D&st=2019-08-24T00%3A41%3A57Z&se=2019-09-24T00%3A46%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-24 00:58 UTC, opbld30 commented
Docs Build status updates of commit _[c6244c9](https://github.com/jiawwu/microsoft-graph-docs/commits/c6244c939fefa3199a5ae2248afc7b3990bb4891)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-90fe39b7)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-90fe39b7"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908240055197357-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PSh535NGob9ECRR0JfzvlLFo4yS1xpnP8oya0flenbc%3D&st=2019-08-24T00%3A53%3A49Z&se=2019-09-24T00%3A58%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 19:25 UTC, opbld33 commented
Docs Build status updates of commit _[1bcf480](https://github.com/jiawwu/microsoft-graph-docs/commits/1bcf480d6602af51110f34ca0c5f0ce675ed3020)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-41077463-93435947)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-93435947)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="41077463-93435947"></a>
### [api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md)
 - **Line 21**: **[Warning]** `````Invalid file link:(~/beta/resources/chatmessagepolicytip.md).`````

<a id="7a1003a0-93435947"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908251921458777-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ohJ2qeT8l1czXHWG%2BwMZljfh%2FEKTJLU%2BQfJCMUcgoK0%3D&st=2019-08-25T19%3A19%3A59Z&se=2019-09-25T19%3A24%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 19:28 UTC, opbld31 commented
Docs Build status updates of commit _[f1d2a7e](https://github.com/jiawwu/microsoft-graph-docs/commits/f1d2a7e086e70f09af39f41eb962cf92e4a32359)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-062b69e0)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-062b69e0"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908251923567394-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IyoVqbP6yb8FDmdHwZ9KHLkOBQEmrRlaCl06myrVHdM%3D&st=2019-08-25T19%3A23%3A12Z&se=2019-09-25T19%3A28%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 19:56 UTC, opbld30 commented
Docs Build status updates of commit _[f47609e](https://github.com/jiawwu/microsoft-graph-docs/commits/f47609eccba01f43ca37865afd004fc53af7238a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-053ab3b6)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-053ab3b6"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908251953097140-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WFzGZ%2BZpKCs6Oj8uYKI1KHILlgc1BDX3laQQqpcUJOc%3D&st=2019-08-25T19%3A51%3A23Z&se=2019-09-25T19%3A56%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 19:59 UTC, opbld30 commented
Docs Build status updates of commit _[07482e7](https://github.com/jiawwu/microsoft-graph-docs/commits/07482e7725e365e056d67684bb0f721b408568b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-0a690256)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-0a690256"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908251955340803-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5YrRSXqL9cYz4yldv3LVeLdEv5%2BDS1jIyy4eMpD7vJc%3D&st=2019-08-25T19%3A54%3A39Z&se=2019-09-25T19%3A59%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 20:17 UTC, opbld32 commented
Docs Build status updates of commit _[bbe4cdc](https://github.com/jiawwu/microsoft-graph-docs/commits/bbe4cdc4bb33886a71b9e6fcebc4bc3fe8bb84f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-8a7fcff1)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-8a7fcff1"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252013528051-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P8owPhua7rgfWxQLDQSk4Xoyyg0HapGVWrksvIQeyxI%3D&st=2019-08-25T20%3A12%3A05Z&se=2019-09-25T20%3A17%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 20:38 UTC, opbld32 commented
Docs Build status updates of commit _[0572a0b](https://github.com/jiawwu/microsoft-graph-docs/commits/0572a0b9dece2701f50be639aea2fd16fd7b07cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-df77c5dc)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-df77c5dc"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252035314258-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SY2efGR40T9nTsA75vv7oNTGS0sxg2gNHbpbNWIpFNQ%3D&st=2019-08-25T20%3A33%3A56Z&se=2019-09-25T20%3A38%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 20:45 UTC, opbld30 commented
Docs Build status updates of commit _[9062739](https://github.com/jiawwu/microsoft-graph-docs/commits/90627396dcb3e65a2e856cb6c312ae738629520e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-1dad9bc7)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-1dad9bc7"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252041400107-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MQuuT%2F2e0N2hVyUKhHUa3WQLGb7EBu%2FMsm6j89jvrus%3D&st=2019-08-25T20%3A40%3A19Z&se=2019-09-25T20%3A45%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 20:57 UTC, opbld33 commented
Docs Build status updates of commit _[097a7b3](https://github.com/jiawwu/microsoft-graph-docs/commits/097a7b374a5e78086730f1155d0bdd29ee5328cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-bd6dc7cf)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-bd6dc7cf"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252053516364-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nf%2Bk593VaD95cbMGpwWvLxHZltRM92yRvNxDi%2FUoxgc%3D&st=2019-08-25T20%3A52%3A13Z&se=2019-09-25T20%3A57%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 21:05 UTC, opbld31 commented
Docs Build status updates of commit _[ad8c6eb](https://github.com/jiawwu/microsoft-graph-docs/commits/ad8c6eb3b696fa4f27c78b28fd918fa513a2dcc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-bb40998e)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-bb40998e"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252101564502-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u9BtLxFb0suVrAF3l99oe1AXMNQOMK9SVoxnuR8Ha5w%3D&st=2019-08-25T21%3A00%3A11Z&se=2019-09-25T21%3A05%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 21:12 UTC, opbld33 commented
Docs Build status updates of commit _[3d20406](https://github.com/jiawwu/microsoft-graph-docs/commits/3d204067041ce6a2452d260538cea195955b8bc2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-4d522672)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-4d522672"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252109236208-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pCG3KgXWI%2FsggMaZ%2BuXzZ8HQilFwPNS1R%2BJipNcX8wI%3D&st=2019-08-25T21%3A07%3A44Z&se=2019-09-25T21%3A12%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 21:15 UTC, opbld31 commented
Docs Build status updates of commit _[4d3cef4](https://github.com/jiawwu/microsoft-graph-docs/commits/4d3cef42f6da62b9c68a3366d235c5959c85844d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-0dc340fd)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-0dc340fd"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252110330643-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WrZ8ABzji4HWkeCN5Wd4Bb6xXBjdtr8she7LjGWvTUU%3D&st=2019-08-25T21%3A10%3A55Z&se=2019-09-25T21%3A15%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 21:24 UTC, opbld31 commented
Docs Build status updates of commit _[9199c59](https://github.com/jiawwu/microsoft-graph-docs/commits/9199c595caeeb2c6a8245371a6317df9d170c2ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-e0d149da)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-e0d149da"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908252120539244-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Dkl0XsVDceqk%2BO7vce9et%2FltQSneA4gkpgMRP9FnD1o%3D&st=2019-08-25T21%3A19%3A05Z&se=2019-09-25T21%3A24%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-25 21:28 UTC, clearab commented
@Lauragra Can you assist? I can't figure out why this is failing API doctor.

2019-08-26 16:21 UTC, opbld32 commented
Docs Build status updates of commit _[ec30c1c](https://github.com/jiawwu/microsoft-graph-docs/commits/ec30c1c9c823d4d6017ab43b05c38903ff535ea7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/use-the-api?branch=pr-en-us-3839) | [Details](#user-content-98e28376-9f4f555b)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-9f4f555b)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="98e28376-9f4f555b"></a>
### [concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md)
 - **Line 28**: **[Warning]** `````Illegal link: `<a href="#query-parameters-optional">{query-parameters}</a>` -- missing bookmark. The file use-the-api.md doesn't contain a bookmark named query-parameters-optional. NOTE: This Suggestion will be elevated to a Warning on 8/26/2019. Please fix invalid bookmarks as soon as possible.`````

<a id="7a1003a0-9f4f555b"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261618112143-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v2OCt2Azu6YdTAXgW9AUXkPzT05HRxPtfff9wqlYy%2FA%3D&st=2019-08-26T16%3A16%3A21Z&se=2019-09-26T16%3A21%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 16:24 UTC, opbld34 commented
Docs Build status updates of commit _[0778b56](https://github.com/jiawwu/microsoft-graph-docs/commits/0778b56c33df0d46b9ba3800b90fad58956539ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/use-the-api?branch=pr-en-us-3839) | [Details](#user-content-98e28376-7da08819)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-7da08819)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="98e28376-7da08819"></a>
### [concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md)
 - **Line 28**: **[Warning]** `````Illegal link: `<a href="#query-parameters-optional">{query-parameters}</a>` -- missing bookmark. The file use-the-api.md doesn't contain a bookmark named query-parameters-optional. NOTE: This Suggestion will be elevated to a Warning on 8/26/2019. Please fix invalid bookmarks as soon as possible.`````

<a id="7a1003a0-7da08819"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261618358822-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fZ4MqDuSPfgWbfeTY2O6sKQ96Al13ljclmqzkhYLuX0%3D&st=2019-08-26T16%3A19%3A38Z&se=2019-09-26T16%3A24%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 16:29 UTC, opbld30 commented
Docs Build status updates of commit _[0c7f43b](https://github.com/jiawwu/microsoft-graph-docs/commits/0c7f43b982a6ee0d6969775ad96e29296e3b71ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/use-the-api?branch=pr-en-us-3839) | [Details](#user-content-98e28376-e3628beb)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-e3628beb)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="98e28376-e3628beb"></a>
### [concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md)
 - **Line 28**: **[Warning]** `````Illegal link: `<a href="#query-parameters-optional">{query-parameters}</a>` -- missing bookmark. The file use-the-api.md doesn't contain a bookmark named query-parameters-optional. NOTE: This Suggestion will be elevated to a Warning on 8/26/2019. Please fix invalid bookmarks as soon as possible.`````

<a id="7a1003a0-e3628beb"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261626291148-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uMsquS%2BNSZxLwUW0mYOlryfqINTwfAIdiXSgcDIRMk0%3D&st=2019-08-26T16%3A24%3A51Z&se=2019-09-26T16%3A29%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 16:59 UTC, opbld32 commented
Docs Build status updates of commit _[5d86800](https://github.com/jiawwu/microsoft-graph-docs/commits/5d868001b59cc03332dff874342db6c2dba5e5f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/use-the-api?branch=pr-en-us-3839) | [Details](#user-content-98e28376-ea015dc4)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-ea015dc4)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="98e28376-ea015dc4"></a>
### [concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md)
 - **Line 28**: **[Warning]** `````Illegal link: `<a href="#query-parameters-optional">{query-parameters}</a>` -- missing bookmark. The file use-the-api.md doesn't contain a bookmark named query-parameters-optional. NOTE: This Suggestion will be elevated to a Warning on 8/26/2019. Please fix invalid bookmarks as soon as possible.`````

<a id="7a1003a0-ea015dc4"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261656389519-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Rs%2F0jotrwyrvi0AUeU6Ue4u9CIs0x%2FPeV6%2Fd9kUCq6Y%3D&st=2019-08-26T16%3A54%3A51Z&se=2019-09-26T16%3A59%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 17:07 UTC, opbld34 commented
Docs Build status updates of commit _[7223c15](https://github.com/jiawwu/microsoft-graph-docs/commits/7223c156e486a682e2a0902f5686c7fe898da067)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/use-the-api?branch=pr-en-us-3839) | [Details](#user-content-98e28376-8ef4c92f)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-8ef4c92f)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="98e28376-8ef4c92f"></a>
### [concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md)
 - **Line 28**: **[Warning]** `````Illegal link: `<a href="#query-parameters-optional">{query-parameters}</a>` -- missing bookmark. The file use-the-api.md doesn't contain a bookmark named query-parameters-optional. NOTE: This Suggestion will be elevated to a Warning on 8/26/2019. Please fix invalid bookmarks as soon as possible.`````

<a id="7a1003a0-8ef4c92f"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261704513160-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AkgiThJT7w1ZQ9EL3xs3JUl1ka%2BvFgmDy4THqgffH%2Bc%3D&st=2019-08-26T17%3A02%3A52Z&se=2019-09-26T17%3A07%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 17:25 UTC, opbld33 commented
Docs Build status updates of commit _[cb1da1c](https://github.com/jiawwu/microsoft-graph-docs/commits/cb1da1c16086b2bda3dc45475e5e87454c9d4e74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/use-the-api?branch=pr-en-us-3839) | [Details](#user-content-98e28376-5242b062)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-5242b062)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="98e28376-5242b062"></a>
### [concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md)
 - **Line 28**: **[Warning]** `````Illegal link: `<a href="#query-parameters-optional">{query-parameters}</a>` -- missing bookmark. The file use-the-api.md doesn't contain a bookmark named query-parameters-optional. NOTE: This Suggestion will be elevated to a Warning on 8/26/2019. Please fix invalid bookmarks as soon as possible.`````

<a id="7a1003a0-5242b062"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261722200605-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4qhN1n8dXfUHKZ3Ht%2BNJ6Oci56%2By89MwCXqcZ8vJqTQ%3D&st=2019-08-26T17%3A20%3A27Z&se=2019-09-26T17%3A25%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 17:33 UTC, opbld31 commented
Docs Build status updates of commit _[79f158c](https://github.com/jiawwu/microsoft-graph-docs/commits/79f158c9569f835cb0755ae8a74459e4e2488e61)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/use-the-api?branch=pr-en-us-3839) | [Details](#user-content-98e28376-14e476e7)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-14e476e7)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="98e28376-14e476e7"></a>
### [concepts/use-the-api.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/use-the-api.md)
 - **Line 28**: **[Warning]** `````Illegal link: `<a href="#query-parameters-optional">{query-parameters}</a>` -- missing bookmark. The file use-the-api.md doesn't contain a bookmark named query-parameters-optional. NOTE: This Suggestion will be elevated to a Warning on 8/26/2019. Please fix invalid bookmarks as soon as possible.`````

<a id="7a1003a0-14e476e7"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261729593215-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IH6QxiHsbhVn6F8m5F6PbmMSbLjfjN3IbEcatVm830E%3D&st=2019-08-26T17%3A28%3A17Z&se=2019-09-26T17%3A33%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 19:34 UTC, opbld33 commented
Docs Build status updates of commit _[b2d6d61](https://github.com/jiawwu/microsoft-graph-docs/commits/b2d6d617bcb767ffbe0b8823299cf25b39a02511)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-afd47dfa)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-afd47dfa"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261931506515-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e1cU5jkhCWCl2OpxkxDVDkmUWLYlwBBvtFDdswf317Q%3D&st=2019-08-26T19%3A29%3A57Z&se=2019-09-26T19%3A34%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 19:41 UTC, opbld32 commented
Docs Build status updates of commit _[b534394](https://github.com/jiawwu/microsoft-graph-docs/commits/b534394ae382e1dcaa64b12cc0cc57f7d9f9b8ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-f45499b7)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-f45499b7"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261938257599-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7GIeItAIFJOVwd%2BV5cFnGvbGEbrDHjt%2FTkiSoZFmFYA%3D&st=2019-08-26T19%3A36%3A43Z&se=2019-09-26T19%3A41%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2019-08-26 19:55 UTC, opbld33 commented
Docs Build status updates of commit _[241088c](https://github.com/jiawwu/microsoft-graph-docs/commits/241088ca58adb1c9db33c78ada7c44f4b93fd090)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-c4f1563c)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-c4f1563c"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C201908261952182730-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YRHvLMmLk9s4kNNN9ldkCcu8VKfrXTjck6UPtHm9LXc%3D&st=2019-08-26T19%3A50%3A42Z&se=2019-09-26T19%3A55%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2020-09-14 21:17 UTC, opbld31 commented
Docs Build status updates of commit _[241088c](https://github.com/jiawwu/microsoft-graph-docs/commits/241088ca58adb1c9db33c78ada7c44f4b93fd090)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8d11398b)

<a id="8d11398b"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009142116469818-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3Ime2AhrJ%2BuoFcgvWkm4qqdTnGZXjiLSnT7wnlOn9Ko%3D&st=2020-09-14T21%3A12%3A21Z&se=2020-10-15T21%3A17%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 21:12 UTC, opbld30 commented
Docs Build status updates of commit _[9fcd00d](https://github.com/jiawwu/microsoft-graph-docs/commits/9fcd00d34671af22c1b4b2e895fe6c1f7243373d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-ea70d647)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-ea70d647"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents an individual chat message within a channel or chat entity. The chat message can be a root chat message or part of a thread that is defined by the **replyToId** property in the chat message.' is duplicated in 'beta/resources/chatmessage.md(3,14)', 'v1.0/resources/chatmessage.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152111062133-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3I6sz9uf7ix8ZUbLD51FOQrL9YRAdlDNbfOCqZk9o5w%3D&st=2020-09-15T21%3A07%3A27Z&se=2020-10-16T21%3A12%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 21:52 UTC, opbld33 commented
Docs Build status updates of commit _[eaaf73a](https://github.com/jiawwu/microsoft-graph-docs/commits/eaaf73a10b503c0f2955e62b530d140a1b802887)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-75e58707)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-75e58707"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents an individual chat message within a channel or chat entity. The chat message can be a root chat message or part of a thread that is defined by the **replyToId** property in the chat message.' is duplicated in 'beta/resources/chatmessage.md(3,14)', 'v1.0/resources/chatmessage.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152151185410-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pAkOniKlbJiIanvfb%2FMvI8AcBJ2HpLyJnwaV5VPl2Uk%3D&st=2020-09-15T21%3A47%3A38Z&se=2020-10-16T21%3A52%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 22:12 UTC, opbld31 commented
Docs Build status updates of commit _[85624f1](https://github.com/jiawwu/microsoft-graph-docs/commits/85624f10b665042b73095df9738014e7b8bb5469)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-8df60043)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-8df60043"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents an individual chat message within a channel or chat entity. The chat message can be a root chat message or part of a thread that is defined by the **replyToId** property in the chat message.' is duplicated in 'beta/resources/chatmessage.md(3,14)', 'v1.0/resources/chatmessage.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152211196840-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A4YJlHyd7DzKkM%2FO9XX2PgOon9BgqCL6YGw3YN0WIKg%3D&st=2020-09-15T22%3A07%3A40Z&se=2020-10-16T22%3A12%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 22:26 UTC, opbld30 commented
Docs Build status updates of commit _[014bbc9](https://github.com/jiawwu/microsoft-graph-docs/commits/014bbc99590c204aea2862b57c9750a09235c2df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152224445041-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jXygbLSJyS7aN3eIASRNNBACseFcW%2FSmSUYp31nW2B4%3D&st=2020-09-15T22%3A21%3A09Z&se=2020-10-16T22%3A26%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 23:26 UTC, opbld34 commented
Docs Build status updates of commit _[49fe33f](https://github.com/jiawwu/microsoft-graph-docs/commits/49fe33f620d3de2e20d2174eacb28d60ea7c5110)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-15 23:28 UTC, opbld31 commented
Docs Build status updates of commit _[49fe33f](https://github.com/jiawwu/microsoft-graph-docs/commits/49fe33f620d3de2e20d2174eacb28d60ea7c5110)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152326177285-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dnQohUXAGq6dtqas3TsDZFD9DXZp6r%2FCyg9w6O8vYv0%3D&st=2020-09-15T23%3A22%3A59Z&se=2020-10-16T23%3A27%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 00:46 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +title: "Update chatMessage with DLP policy violation"
The title and H1 should be the same. Where does the policy violation part come in? Is this just updating a chatMessage, and one of the properties they can update is policyViolation?

2020-09-16 00:49 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +Update a chatMessage with a Data Loss Prevention (DLP) policy violation.
The metadata shows a chatMessagePolicyViolation complex type, but we don't appear to have a topic for it. Please make sure that it's documented.

2020-09-16 00:53 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +| policyViolation | [chatMessagePolicyViolation](../resources/chatmessagepolicyviolation.md) | Supply the properties for the Data Loss Prevention (DLP) violation.|
We need a description for this property; it should go in the complex type topic as well.

2020-09-16 00:54 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +| Content-Type | string  | Nature of the data in the body of an entity. Required. |
Shouldn't the content-type header be application/json?

2020-09-16 01:00 UTC, Lauragra commented on api-reference/beta/resources/chatmessage.md
> +  "policyViolation": {"@odata.type": "microsoft.graph.chatMessagePolicyViolation"},
You need to add policyViolation to the Properties table as well.

2020-09-16 01:04 UTC, Lauragra requested changes
See comments. This PR also needs an entry in the changelog and the new method topic needs to be added to the TOC.

2020-09-16 21:08 UTC, laujan commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +title: "Update chatMessage with DLP policy violation"
Please review @nkramer.

2020-09-16 21:08 UTC, opbld32 commented
Docs Build status updates of commit _[2c12f5e](https://github.com/jiawwu/microsoft-graph-docs/commits/2c12f5e72ab0cfa2ca3d7482eac6dd9da451f06a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162106402995-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CXJdN%2BQnLP7eoOc2CQrTD%2FKlPhYkUYC6eV0w2tN9zW4%3D&st=2020-09-16T21%3A03%3A14Z&se=2020-10-17T21%3A08%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 21:25 UTC, laujan commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +| policyViolation | [chatMessagePolicyViolation](../resources/chatmessagepolicyviolation.md) | Supply the properties for the Data Loss Prevention (DLP) violation.|
Can you assist @nkramer?

2020-09-16 21:33 UTC, laujan commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +| Content-Type | string  | Nature of the data in the body of an entity. Required. |
Yes!

2020-09-16 21:36 UTC, opbld30 commented
Docs Build status updates of commit _[206bd7e](https://github.com/jiawwu/microsoft-graph-docs/commits/206bd7e2e986e307d1c85288b824e8da36fcba78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162134420864-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aoLqborIg5EI2pTgSMbCQNYZzTjtPNDW1u1Vzyx7hlE%3D&st=2020-09-16T21%3A31%3A09Z&se=2020-10-17T21%3A36%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 21:39 UTC, opbld34 commented
Docs Build status updates of commit _[483a981](https://github.com/jiawwu/microsoft-graph-docs/commits/483a9817b800b81bb5779d988d2cbc29a49d3a6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162138247137-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P5GE1Y%2FNfFrmIbXlMHOV9y3rP%2FVOB5X5cQUnVFT4xGU%3D&st=2020-09-16T21%3A34%3A46Z&se=2020-10-17T21%3A39%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 22:54 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +| policyViolation | [chatMessagePolicyViolation](../resources/chatmessagepolicyviolation.md) | Supply the properties for the Data Loss Prevention (DLP) violation.|
I think the description of the property is something like "Defines the properties of a policy violation." I don't know if we should be referring to it as a "DLP violation", as opposed to a policy violation set by a DLP provider....

2020-09-16 23:21 UTC, opbld34 commented
Docs Build status updates of commit _[c09bf62](https://github.com/jiawwu/microsoft-graph-docs/commits/c09bf623f533730d055ddee3edc69ea09c0e581b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162319427086-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TX%2BkduN%2FgmYK3fMXIbAJknFlKZYCYOJS42gKn7VsyUc%3D&st=2020-09-16T23%3A16%3A01Z&se=2020-10-17T23%3A21%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 23:36 UTC, opbld31 commented
Docs Build status updates of commit _[2dba9fc](https://github.com/jiawwu/microsoft-graph-docs/commits/2dba9fcd84280a25c5700b93979766d2f2cffe96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162335117663-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p94jyJhVdom8MWxchn0pg9zLrldC4Ck%2FtMM6d3mFQ7s%3D&st=2020-09-16T23%3A31%3A34Z&se=2020-10-17T23%3A36%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 23:39 UTC, opbld32 commented
Docs Build status updates of commit _[f96ed6a](https://github.com/jiawwu/microsoft-graph-docs/commits/f96ed6a73ad33e212f5fab7229173a7924b938df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162337599853-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e5muxXFYmEmVX8VosP1aKvxepaNHlmqxzaPZxdYCK3Y%3D&st=2020-09-16T23%3A34%3A24Z&se=2020-10-17T23%3A39%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 23:51 UTC, nkramer commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +title: "Update chatMessage with DLP policy violation"
fixed

2020-09-16 23:51 UTC, opbld33 commented
Docs Build status updates of commit _[720f7c9](https://github.com/jiawwu/microsoft-graph-docs/commits/720f7c93cd8713025e2e398792baba91c219552c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162350146276-3839%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tk2WNDXXkL4p7nb3SUS46timxw5Whx%2F%2BFIvSbdyT9N8%3D&st=2020-09-16T23%3A46%3A37Z&se=2020-10-17T23%3A51%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 23:53 UTC, nkramer commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +| policyViolation | [chatMessagePolicyViolation](../resources/chatmessagepolicyviolation.md) | Supply the properties for the Data Loss Prevention (DLP) violation.|
I believe this has been addressed by getting rid of this property table in favor of pointing to a resource page

2020-09-17 00:43 UTC, opbld33 commented
Docs Build status updates of commit _[aac47f7](https://github.com/jiawwu/microsoft-graph-docs/commits/aac47f734214ba6a5f1a9beb4b70140ce134fda3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-e462623e)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="de0bbbbb-e462623e"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 25, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsipackagetype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-17 00:46 UTC, opbld33 commented
Docs Build status updates of commit _[bf8a2ac](https://github.com/jiawwu/microsoft-graph-docs/commits/bf8a2acbc4810ef6437bd0246bb30b43d5c9bec6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-957e2834)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="de0bbbbb-957e2834"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 25, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsipackagetype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-17 00:48 UTC, opbld33 commented
Docs Build status updates of commit _[2735b15](https://github.com/jiawwu/microsoft-graph-docs/commits/2735b15079b26eccc1edc747773e1cefae013342)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-1804ceaa)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="de0bbbbb-1804ceaa"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 25, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warnin [...]

2020-09-17 00:49 UTC, nkramer commented
@Lauragra I've added the TOC and change log entry and address the other feedback.

2020-09-17 02:16 UTC, opbld30 commented
Docs Build status updates of commit _[a092404](https://github.com/jiawwu/microsoft-graph-docs/commits/a0924040fe92e8e0a68a003f546b38d29605f3d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-c1bbe6e3)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="de0bbbbb-c1bbe6e3"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warnin [...]

2020-09-17 02:20 UTC, opbld30 commented
Docs Build status updates of commit _[f020123](https://github.com/jiawwu/microsoft-graph-docs/commits/f020123d6f750cd8e5d284150566b972051a366e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-43255f7a)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="de0bbbbb-43255f7a"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warnin [...]

2020-09-17 02:21 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +In the request body, supply a JSON representation of the [chatMessage](../resources/chatMessage.md) object. Only the **policyViolation** property can be updated.
Is this accurate? The example does not show a JSON representation of chatMessage. I think it is accurate to say to include only the policyViolation property in the request. Confirm?

2020-09-17 02:24 UTC, opbld31 commented
Docs Build status updates of commit _[241115b](https://github.com/jiawwu/microsoft-graph-docs/commits/241115b20edd93b8a42bd642a344c3be12ca5857)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-86882e58)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="de0bbbbb-86882e58"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warnin [...]

2020-09-17 02:26 UTC, opbld34 commented
Docs Build status updates of commit _[a047a98](https://github.com/jiawwu/microsoft-graph-docs/commits/a047a9878bcb34a645a434125bf99f974e8e022e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-51676cb1)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="de0bbbbb-51676cb1"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warnin [...]

2020-09-17 05:08 UTC, nkramer commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +In the request body, supply a JSON representation of the [chatMessage](../resources/chatMessage.md) object. Only the **policyViolation** property can be updated.
I think we're both right -- it's a chatMessage where you can only supply the policyViolation property.

2020-09-17 05:10 UTC, nkramer commented on api-reference/beta/api/chatmessage-update-policyviolation.md
> +In the request body, supply a JSON representation of the [chatMessage](../resources/chatMessage.md) object. Only the **policyViolation** property can be updated.
I updated the proposed wording, please change as appropriate.

2020-09-17 05:11 UTC, opbld34 commented
Docs Build status updates of commit _[8f0c3b0](https://github.com/jiawwu/microsoft-graph-docs/commits/8f0c3b0c8263c427b11d2ae089132de846dc3772)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-aafee00c)
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-aafee00c)
[api-reference/beta/api/chatmessage-update-policyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update-policyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update-policyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-aafee00c"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-aafee00c"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[ [...]

2020-09-17 05:11 UTC, nkramer approved these changes

2020-09-17 21:45 UTC, opbld34 commented
Docs Build status updates of commit _[d8ae95c](https://github.com/jiawwu/microsoft-graph-docs/commits/d8ae95c5d3b4828a9e556040cf0ee60fad92a296)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-77a28fb3)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-77a28fb3)
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-00685cff-77a28fb3)
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-77a28fb3)
[api-reference/beta/api/chatmessage-update.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-77a28fb3"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-update-policyviolation.md'.`````
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-update-policyviolation.md'.`````
 - **Line 41, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-update-policyviolation.md'.`````

<a id="7a1003a0-77a28fb3"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="00685cff-77a28fb3"></a>
### [api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml)
 - **Line 12148, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-update-policyviolation.md'.`````

<a id="de0bbbbb-77a28fb3"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view [...]

2020-09-17 21:53 UTC, opbld34 commented
Docs Build status updates of commit _[b334542](https://github.com/jiawwu/microsoft-graph-docs/commits/b334542c945d53de0e0181b4beac26969579e538)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-97ee62ac-a19a2dc3)
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-a19a2dc3)
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-00685cff-a19a2dc3)
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-a19a2dc3)
[api-reference/beta/api/chatmessage-update.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="97ee62ac-a19a2dc3"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md)
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-update-policyviolation.md'.`````
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-update-policyviolation.md'.`````
 - **Line 41, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-update-policyviolation.md'.`````

<a id="7a1003a0-a19a2dc3"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="00685cff-a19a2dc3"></a>
### [api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml)
 - **Line 12148, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-update-policyviolation.md'.`````

<a id="de0bbbbb-a19a2dc3"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view [...]

2020-09-17 21:54 UTC, Lauragra approved these changes

2020-09-17 21:54 UTC, opbld33 commented
Docs Build status updates of commit _[9792ceb](https://github.com/jiawwu/microsoft-graph-docs/commits/9792ceb985ae2114e87d04980e9489f082afc416)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-22e67817)
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-00685cff-22e67817)
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-22e67817)
[api-reference/beta/api/chatmessage-update.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-22e67817"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="00685cff-22e67817"></a>
### [api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml)
 - **Line 12148, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-update-policyviolation.md'.`````

<a id="de0bbbbb-22e67817"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]* [...]

2020-09-17 21:55 UTC, opbld30 commented
Docs Build status updates of commit _[da13ddf](https://github.com/jiawwu/microsoft-graph-docs/commits/da13ddf4afffda4ce0bdd263e89c2e69e6b0d4af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-d2933f4f)
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-d2933f4f)
[api-reference/beta/api/chatmessage-update.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-d2933f4f"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-d2933f4f"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-09-17 22:06 UTC, opbld31 commented
Docs Build status updates of commit _[8ba63d8](https://github.com/jiawwu/microsoft-graph-docs/commits/8ba63d8c251219b8fd7151d4ae67c19ba58575d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) | [Details](#user-content-7a1003a0-01cd3edb)
[concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-3839) | [Details](#user-content-de0bbbbb-01cd3edb)
[api-reference/beta/api/chatmessage-update.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolation.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolation?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagepolicyviolationpolicytip?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-3839) (graph-rest-beta) |

<a id="7a1003a0-01cd3edb"></a>
### [api-reference/beta/resources/enums.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-01cd3edb"></a>
### [concepts/changelog.md](https://github.com/jiawwu/microsoft-graph-docs/blob/jiawwu-DLP-20190122/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-09-17 22:11 UTC, merged