B2C authentication methods policy
microsoftgraph/microsoft-graph-docs pull request #9033
Opened 2020-07-09 00:15 UTC by namkedia

2020-07-09 00:46 UTC, opbld34 commented
Docs Build status updates of commit _[de86b73](https://github.com/namkedia/microsoft-graph-docs/commits/de86b730e0f8d86ccd3e57f787036e504c44a438)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202007090015252874-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dA2cJLN5R5%2BzFtJfUTapz6gYcPDwVzu2qd6k%2B280uCo%3D&st=2020-07-09T00%3A41%3A53Z&se=2020-08-09T00%3A46%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-09 16:24 UTC, davidmu1 commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +description: "Retrieve the properties and relationships of an b2cAuthenticationMethodsPolicy object."
This should probably say something like: Update properties of an b2cAuthenticationMethodsPolicy object.

2020-07-09 16:26 UTC, davidmu1 commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +In the request body, you can supply a JSON representation of the [b2cAuthenticationMethodsPolicy](../resources/b2cauthenticationmethodspolicy.md) object (but is not required.)
What would be the point of running this action without a request body?

2020-07-09 16:27 UTC, davidmu1 commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +## Examples
I think there should be an example showing the properties being updated. Not sure why the call would be made with no properties to update.

2020-07-09 16:32 UTC, davidmu1 commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +|isPhoneOneTimePasswordAuthenticationEnabled|Boolean|This property lets the tenant admin configure if the phone one time password authentication method is enabled|
This property lets the tenant admin configure if the phone one time password authentication method is enabled

Should have a period at the end of the sentence. Not sure what the sentence is saying. What can the tenant admin configure if the **phone one time password authentication method** is enabled?

2020-07-09 16:32 UTC, davidmu1 commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +|isEmailPasswordAuthenticationEnabled|Boolean|This property lets the tenant admin configure if the email and password authentication method is enabled|
Same comment. Not sure what can be configured.

2020-07-09 16:33 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +description: "Represents a local account authentication method registered to a user configured in a B2C tenant."
Active Directory B2C tenant

2020-07-09 16:34 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +Azure AD B2C allows tenant admins to choose a mechanism for letting end customers register via local accounts. Local accounts are the accounts where the identity assertion is being done by Azure AD.
Azure Active Directory (Azure AD) B2C on first mention.

2020-07-09 16:37 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +The Local accounts in Azure AD B2C do not follow the settings or paradigms from AAD. The methods set by Azure AD authentication methods policy are not used or enforced by AAD B2C. AAD B2C stores thes
The local accounts in Azure AD B2C do not follow the settings or paradigms from Azure AD. The Azure AD authentication methods policy is not used or enforced by Azure AD B2C. Azure AD B2C stores these settings in a different policy, which are consumed by user flows.

2020-07-09 16:43 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +In the Azure portal they are called Local Accounts. As of now we do not have plans to change the portal naming.
Future plans should not be discussed in the reference article. Not sure that the first sentence provides any value for this particular API.

2020-07-09 16:44 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +|id|String|The id of the B2C authentication methods policy|Yes|No|Yes|
The Required and Read only columns need to be removed and that information should be added to the description.

2020-07-09 16:45 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +|isPhoneOneTimePasswordAuthenticationEnabled|Boolean|This property lets the tenant admin configure if the phone one time password authentication method is enabled|No|No|No|
The words "This property lets" are not needed. Same comment applies about not understanding what is being configured.

2020-07-09 16:47 UTC, davidmu1 commented on api-reference/beta/toc.yml
> -          - name: Overview
This should not be changed.

2020-07-09 16:48 UTC, davidmu1 commented on api-reference/beta/toc.yml
>              href: resources/authenticationmethod.md
The indentation doesn't look correct here. When adding the items node, the child items must be indented.

2020-07-09 16:50 UTC, davidmu1 commented on api-reference/beta/toc.yml
> +          - name: B2C Authentication methods
This title seem odd to me. Each one of these is an authentication method. Perhaps "B2C policy"?

2020-07-10 00:20 UTC, Lauragra commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +## Optional query parameters
Generally, we talk about query parameters in the context of GET and LIST operations. Does this apply to an UPDATE operation? If not, pls. remove this section.

2020-08-27 21:28 UTC, hiteshjaviya commented on api-reference/beta/api/b2cauthenticationmethodspolicy-get.md
> +    "isPhoneOneTimePasswordAuthenticationEnabled": false,
Phone option wont be available until public preview Phone auth basic

2020-08-27 21:28 UTC, hiteshjaviya commented on api-reference/beta/api/b2cauthenticationmethodspolicy-get.md
> +    "id": "b2CAuthenticationMethodsPolicy",
in this example all the account type is disabled which cannot be the case

2020-08-27 21:33 UTC, hiteshjaviya commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +|isPhoneOneTimePasswordAuthenticationEnabled|Boolean|This property lets the tenant admin configure if the phone one time password authentication method is enabled|
Same here. this can be removed for now and added back once we public preview phone auth

2020-08-27 21:42 UTC, hiteshjaviya commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +    "id": "String",
Id needs to be b2CAuthenticationMethodsPolicy

2020-08-27 21:45 UTC, hiteshjaviya commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +  "name": "patch_b2cauthenticationmethodspolicy"
Can we have an example of request and response for a patch b2cAuthenticationMethodsPolicy ?

2020-09-24 21:50 UTC, namkedia commented on api-reference/beta/api/b2cauthenticationmethodspolicy-get.md
> +    "isPhoneOneTimePasswordAuthenticationEnabled": false,
HTTP/1.1 200 OK
Content-type: application/json

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#b2cAuthenticationMethodsPolicy",
    "id": "b2CAuthenticationMethodsPolicy",
    "isPhoneOneTimePasswordAuthenticationEnabled": false,
    "isEmailPasswordAuthenticationEnabled": true,
    "isUserNameAuthenticationEnabled": false
}

2020-09-24 22:06 UTC, namkedia commented on api-reference/beta/toc.yml
> -          - name: Overview
This entire section currently belongs to B2B authentication method. The overview is also for B2B authentication.
The new added section is for B2C authentication

2020-09-24 22:10 UTC, namkedia commented on api-reference/beta/toc.yml
> +          - name: B2C Authentication methods
So within Authentication methods, the current documentation is for B2B /AAD authentication methods. The new ones being added are for B2C.

2020-09-24 22:32 UTC, opbld30 commented
Docs Build status updates of commit _[2fb2f85](https://github.com/namkedia/microsoft-graph-docs/commits/2fb2f851002a39022ae28c37eda2158ce5a3b77d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009242231177007-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Riyp1zLy%2Fdaeiw9afAjW4a8TWQk1b2csWlXqvbLpx7I%3D&st=2020-09-24T22%3A27%3A51Z&se=2020-10-25T22%3A32%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 22:35 UTC, opbld34 commented
Docs Build status updates of commit _[e762a3b](https://github.com/namkedia/microsoft-graph-docs/commits/e762a3b6af05621741fd0405f9485d102dd3b135)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009242234155246-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DGnrSxqTrcKuCV7v8qUMqQ7sa0SUMOgZFKbLwlBnFi8%3D&st=2020-09-24T22%3A30%3A42Z&se=2020-10-25T22%3A35%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 22:38 UTC, opbld30 commented
Docs Build status updates of commit _[9f11491](https://github.com/namkedia/microsoft-graph-docs/commits/9f1149151bcfa7140eeff73eff1220f0f3c9401e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009242236386791-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MG5IsKPNRjAMTwXrpB2qLc0UMwmqHhf8bgFs5fhal1I%3D&st=2020-09-24T22%3A33%3A02Z&se=2020-10-25T22%3A38%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 22:40 UTC, opbld33 commented
Docs Build status updates of commit _[f96ff7c](https://github.com/namkedia/microsoft-graph-docs/commits/f96ff7c3295a9d6319cdde05fe1000c0a1d6fa6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009242239078160-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bgDv6mQlH11im7t6uAZtiLQDdCv75qzz4XHlIyRVb6Y%3D&st=2020-09-24T22%3A35%3A29Z&se=2020-10-25T22%3A40%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 22:59 UTC, davidmu1 commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +|isEmailPasswordAuthenticationEnabled|Boolean|The tenant admin configure local accounts using email if the email and password authentication method is enabled|
```suggestion
|isEmailPasswordAuthenticationEnabled|Boolean|The tenant admin can configure local accounts using email if the email and password authentication method is enabled|
```

2020-09-24 22:59 UTC, davidmu1 commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +|isUserNameAuthenticationEnabled|Boolean|The tenant admin configure local accounts using username if the user name and password authentication method is enabled|
```suggestion
|isUserNameAuthenticationEnabled|Boolean|The tenant admin can configure local accounts using username if the user name and password authentication method is enabled|
```

2020-09-24 23:03 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +|id|String|The id of the B2C authentication methods policy. This is a required and read only property.|Yes|
The sentence doesn't make sense: This is a required and read only property. Typically, we use the word "required" for input that the user must enter. Doesn't matter if it's required if it's read-only.

2020-09-24 23:03 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +|isEmailPasswordAuthenticationEnabled|Boolean|The tenant admin configure local accounts using email if the email and password authentication method is enabled|No|
```suggestion
|isEmailPasswordAuthenticationEnabled|Boolean|The tenant admin can configure local accounts using email if the email and password authentication method is enabled.|No|
```

2020-09-24 23:03 UTC, davidmu1 commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +|isUserNameAuthenticationEnabled|Boolean|The tenant admin configure local accounts using username if the user name and password authentication method is enabled|No|
```suggestion
|isUserNameAuthenticationEnabled|Boolean|The tenant admin can configure local accounts using username if the user name and password authentication method is enabled.|No|
```

2020-09-24 23:05 UTC, davidmu1 approved these changes

2020-09-25 21:06 UTC, Lauragra commented on api-reference/beta/api/b2cauthenticationmethodspolicy-get.md
> +Read the properties of an [b2cAuthenticationMethodsPolicy](../resources/b2cauthenticationmethodspolicy.md) object.
Change "an" to "a".

2020-09-25 21:08 UTC, Lauragra commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +Update the properties of an [b2cAuthenticationMethodsPolicy](../resources/b2cauthenticationmethodspolicy.md) object.
Global: an -> a

2020-09-25 21:09 UTC, Lauragra commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +| Delegated (work or school account)     | Policy.ReadWrite.AuthenticationMethod|
This permission is not currently documented. Please verify the permission and add it to the Permissions reference topic if necessary.

2020-09-25 21:10 UTC, Lauragra commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +PATCH https://graph.microsoft.com/beta/policies/b2cAuthenticationMethodsPolicy
Global: Show the syntax only here.

2020-09-25 21:11 UTC, Lauragra commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +PATCH https://graph.microsoft.com/v1.0/policies/b2cAuthenticationMethodsPolicy
The example should be using /beta, not /v1.0.

2020-09-25 21:17 UTC, opbld32 commented
Docs Build status updates of commit _[52ce7c5](https://github.com/namkedia/microsoft-graph-docs/commits/52ce7c57e0268024d5e3fd6f94538b293df97a90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009252115359751-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yKFSTkNQckL%2F%2BoEhl42Wys5rXeEHlPFUe2S8OboCcqE%3D&st=2020-09-25T21%3A12%3A27Z&se=2020-10-26T21%3A17%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-25 21:17 UTC, Lauragra commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +Azure Active Directory (Azure AD) B2C allows tenant admins to choose a mechanism for letting end customers register via local accounts. Local accounts are the accounts where the identity assertion is
What do we mean by "end customers"? Should that be "end users"?

2020-09-25 21:20 UTC, Lauragra commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +Azure Active Directory (Azure AD) B2C allows tenant admins to choose a mechanism for letting end customers register via local accounts. Local accounts are the accounts where the identity assertion is
The second and third sentences should be combined into one sentence: "Local accounts are the accounts where Azure AD does the identity assertion, as opposed to a federated identity provider such as Google or Facebook.

2020-09-25 21:26 UTC, Lauragra commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +The local accounts in Azure AD B2C do not follow the settings or paradigms from Azure AD. The Azure AD authentication methods policy is not used or enforced by Azure AD B2C. Azure AD B2C stores these
If it's a single policy, then change "which are" to "which is".

2020-09-25 21:27 UTC, Lauragra commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +| [Get b2cAuthenticationMethodsPolicy](../api/b2cauthenticationmethodspolicy-get.md) | [b2cauthenticationmethodspolicy](b2cauthenticationmethodspolicy.md) | Read the properties of an **b2cauthenticat
Change an -> a in the descriptions here too.

2020-09-25 21:27 UTC, Lauragra commented on api-reference/beta/resources/b2cauthenticationmethodspolicy.md
> +|id|String|The id of the B2C authentication methods policy. This is a required and read only property.|Yes|
The Key column is non-standard for our reference docs. Can you add that information to the Description column?

2020-09-25 21:29 UTC, Lauragra requested changes
Please address comments and include a changelog entry with this PR to call out the new resource/methods.

2020-09-25 21:32 UTC, opbld34 commented
Docs Build status updates of commit _[39d06ff](https://github.com/namkedia/microsoft-graph-docs/commits/39d06ffc27e18accb4c2b600604a6ae2ed448cb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009252130337297-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oIBAIcWdx0TswKlZqAj6sFbLS1dbP6QBpLM8IEz71Gs%3D&st=2020-09-25T21%3A27%3A25Z&se=2020-10-26T21%3A32%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-28 18:48 UTC, namkedia commented on api-reference/beta/api/b2cauthenticationmethodspolicy-get.md
> +Read the properties of an [b2cAuthenticationMethodsPolicy](../resources/b2cauthenticationmethodspolicy.md) object.
Yes!

2020-09-28 19:13 UTC, opbld34 commented
Docs Build status updates of commit _[1559a95](https://github.com/namkedia/microsoft-graph-docs/commits/1559a95e12f6d6b9a84ac0a7333c7db3a1019e68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009281911504896-9033%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xo3qoO8KQdLdPKvm0Qhp%2BTY4T%2B42xO2NnDnOFq9nqog%3D&st=2020-09-28T19%3A08%3A13Z&se=2020-10-29T19%3A13%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 19:12 UTC, opbld34 commented
Docs Build status updates of commit _[b714df1](https://github.com/namkedia/microsoft-graph-docs/commits/b714df10b4d270913d6488644326e4f3f363f471)_: 

:clock10: **Pending**: waiting for processors ([24](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 24 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 19:12 UTC, namkedia commented on api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
> +| Delegated (work or school account)     | Policy.ReadWrite.AuthenticationMethod|
Added permissions

2020-10-08 19:16 UTC, opbld33 commented
Docs Build status updates of commit _[b714df1](https://github.com/namkedia/microsoft-graph-docs/commits/b714df10b4d270913d6488644326e4f3f363f471)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9033) | [Details](#user-content-075040e5-2e8580c3)
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |

<a id="075040e5-2e8580c3"></a>
### [concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md)
 - **Line 177, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 206, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 208, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 209, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 238, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 238, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 378, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 618, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 618, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 618, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 620, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 620, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 620, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 748, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 801, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 801, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 1194, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 1195, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 1200, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 1201, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 1203, Column 0**: **[Suggesti [...]

2020-10-08 21:46 UTC, opbld32 commented
Docs Build status updates of commit _[55d67b7](https://github.com/namkedia/microsoft-graph-docs/commits/55d67b7e515e21f3ccbdb36a60015a60777c4bfa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9033) | [Details](#user-content-de0bbbbb-6fbb4736)
[concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9033) | [Details](#user-content-075040e5-6fbb4736)
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-6fbb4736"></a>
### [concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy.md?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get.md?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update.md?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 43, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 44, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?vi [...]

2020-10-08 21:49 UTC, opbld31 commented
Docs Build status updates of commit _[03c1fb1](https://github.com/namkedia/microsoft-graph-docs/commits/03c1fb11a0d68f8322c11a9c0798fabeec85b303)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9033) | [Details](#user-content-de0bbbbb-a4ddd02b)
[concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9033) | [Details](#user-content-075040e5-a4ddd02b)
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a4ddd02b"></a>
### [concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 43, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 44, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph- [...]

2020-10-08 21:54 UTC, opbld31 commented
Docs Build status updates of commit _[7f97cb0](https://github.com/namkedia/microsoft-graph-docs/commits/7f97cb059c0846f7c292690830f2f7a1af27b346)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9033) | [Details](#user-content-de0bbbbb-76a47f5d)
[concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9033) | [Details](#user-content-075040e5-76a47f5d)
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-76a47f5d"></a>
### [concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 43, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 44, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph- [...]

2020-10-08 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[08ca400](https://github.com/namkedia/microsoft-graph-docs/commits/08ca400469c84daa00cdef1ad04cc69c0afcc113)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9033) | [Details](#user-content-de0bbbbb-53d6e061)
[concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9033) | [Details](#user-content-075040e5-53d6e061)
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-53d6e061"></a>
### [concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 43, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 44, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph- [...]

2020-10-08 22:05 UTC, opbld30 commented
Docs Build status updates of commit _[7d4a8ad](https://github.com/namkedia/microsoft-graph-docs/commits/7d4a8ad1d4b830caad614b563dbf9b5ea74098aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9033) | [Details](#user-content-de0bbbbb-f0fb41da)
[concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9033) | [Details](#user-content-075040e5-f0fb41da)
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f0fb41da"></a>
### [concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 43, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 44, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph- [...]

2020-10-08 22:08 UTC, Lauragra approved these changes

2020-10-08 22:12 UTC, opbld31 commented
Docs Build status updates of commit _[a45f900](https://github.com/namkedia/microsoft-graph-docs/commits/a45f9008ef074c9f386101f164c514f164754ea6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9033) | [Details](#user-content-de0bbbbb-35347b85)
[concepts/permissions-reference.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9033) | [Details](#user-content-075040e5-35347b85)
[api-reference/beta/api/b2cauthenticationmethodspolicy-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/api/b2cauthenticationmethodspolicy-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/api/b2cauthenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/resources/b2cauthenticationmethodspolicy.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/resources/b2cauthenticationmethodspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta&branch=pr-en-us-9033) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-35347b85"></a>
### [concepts/changelog.md](https://github.com/namkedia/microsoft-graph-docs/blob/localAccount/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 43, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 44, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph- [...]

2020-10-08 22:49 UTC, merged