New BitLocker recovery key API documentation
microsoftgraph/microsoft-graph-docs pull request #9309
Opened 2020-07-29 22:31 UTC by hafowler

2020-07-29 22:42 UTC, opbld33 commented
Docs Build status updates of commit _[f6eb1b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6eb1b3113d07e5b868bbbf4a51d1ea0fe822955)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202007292231250784-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EycRrltUjea0c0nbz9DczJer1TXU6R%2FHMS3ZS3UKp9k%3D&st=2020-07-29T22%3A37%3A52Z&se=2020-08-29T22%3A42%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-30 19:47 UTC, opbld33 commented
Docs Build status updates of commit _[d882bbe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d882bbeac7535c6ba122c0b931e904028a77022d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202007301935263150-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ui%2B51R0Izg%2B9gluuoHKiS9If%2BUHKmDO78SB3T%2BcYNyY%3D&st=2020-07-30T19%3A42%3A15Z&se=2020-08-30T19%3A47%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-30 20:08 UTC, opbld33 commented
Docs Build status updates of commit _[8a59c98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a59c980328df9443834e103940af689c2d26040)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202007301956476263-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EitjEPk5UPDxxA7c0cYX3N8aeat%2Bya4WtctX%2FFMp5%2BU%3D&st=2020-07-30T20%3A03%3A27Z&se=2020-08-30T20%3A08%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-30 20:20 UTC, opbld30 commented
Docs Build status updates of commit _[6ddbafc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ddbafc2f476fa8974b79936e0f70fd73214c125)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202007301957514571-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BoqBM0yJTSxyKrMFmkpZwnarreWYUNEYcEEnSJoIYtU%3D&st=2020-07-30T20%3A15%3A40Z&se=2020-08-30T20%3A20%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-07-30 20:35 UTC, opbld30 commented
Docs Build status updates of commit _[8130bb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8130bb6d02e6fc7b51e8535393a630c8d37f3f26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202007302023234675-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xlOtZbdiTpD9t0tq8rv%2FDZXDJY14IKqqyHxed1jbnv0%3D&st=2020-07-30T20%3A30%3A13Z&se=2020-08-30T20%3A35%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-01 00:13 UTC, opbld31 commented
Docs Build status updates of commit _[b1223a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1223a29075870ba4bb777873e715e67d991a6c9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7daf1464)

<a id="7daf1464"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\nw3z-s, target branch: master, target branch commit: a683041119897116f405dfca3bff3728bb6ca845, source commit: b1223a29075870ba4bb777873e715e67d991a6c9.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008010012492658-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yTsCDSdFKpyKB%2Bjp1GkxJa0mxWdKCm8jwkyR%2F5SZo1M%3D&st=2020-08-01T00%3A08%3A38Z&se=2020-09-01T00%3A13%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-01 00:20 UTC, hafowler commented
@Lauragra - For TOC, I put the BitLocker recovery key in Identity and access>Directory management. However, conceptually, BitLocker recovery key doesn't fall under Directory management. Some guidance as to where BitLocker recovery key in TOC is greatly appreciated.

Other options we considered: Devices & apps>Corporate management>Device management

2020-08-02 20:44 UTC, opbld32 commented
Docs Build status updates of commit _[c8bf514](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8bf514df62777afe75190a8662e46653adc22c5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4d347462)

<a id="4d347462"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/microsoftgraph/microsoft-graph-docs, working directory: W:\oien-s, target branch: master, target branch commit: a683041119897116f405dfca3bff3728bb6ca845, source commit: c8bf514df62777afe75190a8662e46653adc22c5.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008022043136198-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sCPkte7QF6MdDrLsJ3DgxPaBF2QkSC8818%2BYHzEXsyE%3D&st=2020-08-02T20%3A39%3A08Z&se=2020-09-02T20%3A44%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-02 20:56 UTC, opbld34 commented
Docs Build status updates of commit _[bd26c32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd26c32b050f1fbf7b3b0b0988902c31263207d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008022044305654-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YcSBsj7XphQOsfMnq55CNnPXyngdMWwegQvKAXwxtaM%3D&st=2020-08-02T20%3A51%3A13Z&se=2020-09-02T20%3A56%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-04 02:12 UTC, Lauragra commented
> Hi Hannah! I actually don't have perms to merge to master. Maybe @angelgolfer-ms (I assume that's Angela) can help?

Hi, Angela looped me in on this PR and I will help out on it when I'm back on Thursday. Thanks.

2020-08-04 02:16 UTC, Lauragra commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +### OData query parameters
Why do we have a separate H3 and table just to list a single supported query parameter? Suggest updating the existing boilerplate text as "This method supports the `$select` OData query parameter to return the **key** property...."

2020-08-04 03:33 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +One of the following roles must be assigned to call this API: <br>
Hi @hafowler , just browsing and noticed this, thought I'd leave you a comment:
Line 17: "One of the following roles must be assigned to call this API:"
I have 2 comments for that sentence: 
(a) In general, we try to avoid passive voice in docs; please use active voice so that customers are clear who does what .
(b) Can you explain more clearly who needs to assign whom one of the listed roles?
If I may make a guess - 

If that's the case, I would suggest moving lines 17-24 to below line 36, in the "Permissions" section. You can add a sentence to the effect of:
```
> **Note**: For delegated permissions to allow apps to get bitLockerRecoveryKey resources on behalf of the signed-in user, the tenant administrator must have assigned the user one of the following roles, or, the user is the registered owner of the device that the BitLocker recovery key was originally backed up from."

{list of roles from lines 18-24}
```

And, can you please do the same to the bitlockerrecoverykey-list.md topic as well?

2020-08-05 08:24 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
Since getting the key property returned is a major use case of this API, I would suggest you elevate that by documenting the syntax in the "HTTP request" section as well. You'd have two syntax lines for this API.
To do that, preceding line 39, please add something like:
"To get the specified BitLocker key without retrieving its recovery key:"

Then to add a second syntax line, after line 46, insert:
"To get the specified key including its recovery key:
<!-- {
  "blockType": "ignored"
}
-->
``` http
GET /bitlocker/recoveryKeys/{bitlockerRecoveryKeyId}?$select=key
```

2020-08-05 08:29 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +|[$select](/graph/query-parameters#select-parameter)|Use to return the 'key' property. Requires BitLocker.Read.All permission.|`/recoveryKeys/{bitlockerRecoveryKeyId}?$select=key`|
Line 53:
For the example, instead of trying to show some pseudo example with a partial query URL, I think it would be more helpful if you can replace that by a link to example 2. You can find an example in the [GET open extension](https://docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&tabs=http#optional-query-parameters) topic.

2020-08-05 08:43 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +Read the properties and relationships of a [bitlockerRecoveryKey](../resources/bitlockerrecoverykey.md) object. Does not return the key property by default.
Line 15:
As I read this topic, I see some significant info that can be better discovered if you just roll them all up in the top section here, before the first H2 section "Permissions".

You can do something like:
```
Read the properties and relationships of a [bitlockerRecoveryKey](../resources/bitlockerrecoverykey.md) object. 

By default, this operation does not return the **key** property which represents the recovery key. 

To include the **key** property in the response, use `$select`. 

Including the $select query parameter triggers Azure AD auditing the operation and generating an audit log. You can find this log in Azure AD audit logs under the KeyManagement category.
```

One additional comment is, can you add a link to for this phrase "find this log in Azure AD audit logs under the KeyManagement category"? I can't figure where to find this, or find more info about this KeyManagement category.

Please also note the bolding of properties like the key property, and enclosing tick marks around $select.

2020-08-05 08:45 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +> NOTE: When the $select query parameter is included in the API call, the call is audited, and an audit log is generated. You can find this log in Azure Active Directory audit logs under the KeyManag
Line 54: I think this special info would be better discovered if you put it up top in the context of using $select for this operation.
That space before the first H2 section is where we enter useful conceptual info about the operation (or resource, if this was a resource type topic). See my comment above around line 15.

2020-08-05 08:48 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
Lines 61 and 62:
If these 2 request headers are required, then you should include them in each of example 1 and example 2, as part of the corresponding request section.
You can see [example 3](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=http#example-3) of the GET message topic - the example request query includes a Prefer header.

2020-08-05 09:01 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +GET https://graph.microsoft.com/beta/bitlocker/recoveryKeys/{bitlockerRecoveryKeyId}
Line 82 and 118:
I strongly recommend that in place of {bitlockerRecoveryKeyId} in the example query URL, you specify the corresponding GUID key ID, for each of the two example requests.
That is, for the first example:
GET https://graph.microsoft.com/beta/bitlocker/recoveryKeys/b465e4e8-e4e8-b465-e8e4-65b4e8e465b4

To properly support API Doctor, please add the following line after line 77 for the first example:
"sampleKeys": ["b465e4e8-e4e8-b465-e8e4-65b4e8e465b4"],

Do the similar for the second example.

I recommend this because I had found the "recoveryKeys" segment, and terminology used around the "BitLocker key", "recovery key", and "BitLocker recovery key" are easily confused. Showing what {bitlockerRecoveryKeyId} can be like (like a GUID) helps customers.

2020-08-05 09:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/bitlockerrecoverykey.md
> +Collectively represents a stored BitLocker recovery key and contains the actual key. Inherits from [entity](../resources/entity.md).
Line 16:
What does "Collectively" here mean?
Would it be fine if we just start with "Represents a stored BitLocker key that contains the actual recovery key. "?
I use the term "BitLocker key" and "actual recovery key" based on how you describe the id property (line 31) and key property (line 32).

I also suggest removing "Inherits from entity." I think all the entities in the Microsoft Graph API inherit from the entity resource, so there's no special reason we have to specify it here :-)

2020-08-05 09:10 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Get BitLocker recovery key
Line 9489: You can just say "Get" and not repeat "BitLocker recovery key".
Same with line 9491.
This is because the children of this node (line 9486, which is labelled "BitLocker recovery key") all have a verb and the same object "BitLocker recovery key".

2020-08-05 09:11 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | beta | Added the [bitlockerRecoveryKey](/graph/api/resources/bitlockerRecoveryKey?view=graph-rest-beta) resource type|
Lines 126 and 127: Can you end each description with a period?

2020-08-05 09:19 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
This comment applies to both this operation and the "list" operation:
Since the api.md file describes that there is a "recoveryKeys" root segment for all BitLocker operations, I think you should document the bitLocker entity, which has recoveryKeys as a navigation property. That would fully explain why the get and list operation topics show syntax with segments "/bitlocker/recoveryKeys/".

Was there a reason why you didn't include the bitLocker resource type topic in this PR?

2020-08-05 09:30 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-list.md
> +|[$filter](/graph/query-parameters#filter-parameter)|Filters results by device|`/recoveryKeys?$filter=deviceId eq {deviceId}`|
Line 54:
The api.md file says one can filter by the id or deviceId property. Can you confirm and clarify if necessary?

2020-08-05 20:00 UTC, davidmu1 commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +Read the properties and relationships of a [bitlockerRecoveryKey](../resources/bitlockerrecoverykey.md) object. Does not return the key property by default.
To be consistent with most GET documentation, I suggest using the word "Retrieve" rather than "Read", as in "Retrieve the properties..."

2020-08-05 20:03 UTC, davidmu1 commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +#### Request
Add this sentence:

The following is an example of the request.

2020-08-05 20:04 UTC, davidmu1 commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +#### Response
Add this sentence:

The following is an example of the response.

2020-08-05 20:05 UTC, davidmu1 commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +    "createdDateTime": "String (timestamp)",
These values should show something realistic looking from a response.

2020-08-05 20:06 UTC, davidmu1 commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +#### Request
Add this sentence:

The following is an example of the request.

2020-08-05 20:06 UTC, davidmu1 commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +#### Response
Add this sentence:

The following is an example of the response.

2020-08-05 20:06 UTC, davidmu1 commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +    "volumeType": "String",
Add realistic values.

2020-08-20 22:55 UTC, hafowler commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
I did not include the BitLocker resource type as it is not accessible via the MS Graph API, and we though it would further confuse customers if we did include it.

2020-08-20 22:59 UTC, hafowler commented on api-reference/beta/api/bitlockerrecoverykey-list.md
> +|[$filter](/graph/query-parameters#filter-parameter)|Filters results by device|`/recoveryKeys?$filter=deviceId eq {deviceId}`|
You can filter by the deviceID. To get a specific key based on the key ID, you have to include it in the request. I will make that clearer in the updated PR.

2020-08-30 23:08 UTC, hafowler commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
@Lauragra What are your thoughts on this?

2020-08-30 23:38 UTC, opbld33 commented
Docs Build status updates of commit _[e97e81f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e97e81fc5ffe638c1fba1ad8a60949d612a401aa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e3479593)

<a id="e3479593"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008302338267700-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oAGjolBX5V8K1gNz%2FRxQJYnpopFkbUJlibls3dXetVY%3D&st=2020-08-30T23%3A33%3A54Z&se=2020-09-30T23%3A38%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-30 23:45 UTC, opbld31 commented
Docs Build status updates of commit _[0d95fe7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d95fe788a0241607476ed14bbbda95d5adf93f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-f2f57801-88d72670)
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-311a9e75-88d72670)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-88d72670)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-88d72670)
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

<a id="f2f57801-88d72670"></a>
### [api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md)
 - **Line 57, Column 94**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#Example-2' in 'beta/api/bitlockerrecoverykey-get.md', did you mean '#example-2'?`````

<a id="311a9e75-88d72670"></a>
### [api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md)
 - **Line 57, Column 142**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#Example-2' in 'beta/api/bitlockerrecoverykey-list.md', did you mean '#example-2'?`````

<a id="7a1003a0-88d72670"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="075040e5-88d72670"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md)
 - **Line 453, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 507, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008302343436498-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LAYajZIaBuXcQeBM6MzAowusbfsL4LqTYZjKNtrZCDE%3D&st=2020-08-30T23%3A40%3A05Z&se=2020-09-30T23%3A45%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-31 00:50 UTC, opbld30 commented
Docs Build status updates of commit _[ba258c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba258c3676ee0b75ef8c8aab44fbece9097fc222)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-738a0f26)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-738a0f26)
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

<a id="7a1003a0-738a0f26"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="075040e5-738a0f26"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md)
 - **Line 453, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 507, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008310049133398-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Yi%2FEYQRH7JscG2gfto2JYzl7Q6IxctdY%2BtsFyBrUxw4%3D&st=2020-08-31T00%3A45%3A30Z&se=2020-10-01T00%3A50%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-31 01:03 UTC, hafowler commented
@Lauragra I think that I have addressed all feedback requested. Please let me know if I have not taken the correct steps to get this merged.

2020-09-01 03:00 UTC, opbld32 commented
Docs Build status updates of commit _[c22e2cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c22e2cba0136f11f15db6b22d651cdf405c02f68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-a03b1d04)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-a03b1d04)
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

<a id="7a1003a0-a03b1d04"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="075040e5-a03b1d04"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md)
 - **Line 453, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 507, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009010258377884-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FEFAtl3%2B2Hcowg63P9Yt4Zs8FrIQRq7mbwaIgFSntfQ%3D&st=2020-09-01T02%3A55%3A11Z&se=2020-10-02T03%3A00%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-01 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[3c4e397](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c4e3979d85b09e9a31fb3b9441213c0980bf2c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-77cdd87f)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-77cdd87f)
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

<a id="7a1003a0-77cdd87f"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="075040e5-77cdd87f"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md)
 - **Line 453, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 507, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009010302583745-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u9wALobOwlWt6nJaDBjqjv3QEELzfzvBxqxJji3Fa6g%3D&st=2020-09-01T02%3A59%3A48Z&se=2020-10-02T03%3A04%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-01 03:07 UTC, opbld34 commented
Docs Build status updates of commit _[c36740b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c36740b370a9ad8f35b41e1e554336c9f25a8120)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-af354a62)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-af354a62)
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

<a id="7a1003a0-af354a62"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="075040e5-af354a62"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md)
 - **Line 453, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 507, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009010306160476-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N5wgQR4N7YhT2YagX3J8ZTehLOhn04zlaGiOtomhKNs%3D&st=2020-09-01T03%3A02%3A42Z&se=2020-10-02T03%3A07%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-01 03:09 UTC, opbld34 commented
Docs Build status updates of commit _[d574b18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d574b1872dbcfca9fc74cb938731098c81cfd97f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-deb8caec)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-deb8caec)
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-list?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) |

<a id="7a1003a0-deb8caec"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="075040e5-deb8caec"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md)
 - **Line 453, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 507, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009010307488460-9309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=11MrLL3p9BBLbjtxtLCyTA46qEvd8qE%2FL0VfIVh5vnM%3D&st=2020-09-01T03%3A04%3A10Z&se=2020-10-02T03%3A09%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-01 03:15 UTC, Lauragra commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
What does "not accessible" mean? Is it defined in the metadata or hidden via exposure control?

2020-09-02 00:47 UTC, hafowler commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
See Teams message. But essentially by "not accessible" I mean that the only customer facing information that users see on the BitLocker entity is that it is a root segment of recovery keys. Aside from that, there is no further information, and no operations are supported on the bitlocker entity. We felt that including documentation on this would confuse customers, as it would be publicly surfacing something that is inoperable.

2020-09-04 20:32 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-list.md
> +Namespace: microsoft.graph
@hafowler , please rename the file of the list operation as bitlocker-list-recoverykeys.md, and fix any links to it.
FYI, this is based on how your API is defined in the CSDL, and on the filename conventions used in Microsoft Graph.
If the stub topic generator generated the files for this PR, that would be the name of the file too. Having consistent filenaming is important especially for full topic generation when the generator can reliably determine filenames so as to generate links to them in the docs.
CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55061/File-naming

2020-09-04 20:35 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-list.md
> +Namespace: microsoft.graph
Line 10: Please also change the topic title to "List recoveryKeys".
The second term is the name of the navigation property. Please do not pluralize the resource name (adding an 's' to the resource bitLockerRecoveryKey).
This would also be how the stub topic generator generates the topic title for a "list" operation topic - using the nav property name.

2020-09-04 21:03 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-get.md
> +
Hi @hafowler , FYI in Microsoft Graph, every resource that's defined in the CSDL should be documented. We maintain the expectations for customers that an API in the CSDL <-> the API is available for access <-> API is documented.

Based on this PR and just the list and get operations you're exposing at this point, the bitLocker entity would have an entity file bitlocker.md, exposing 1 operation, the "list" operation, and 1 nav property, recoveryKeys. The entity needs to exist because it is the parent resource for recoveryKeys. Without defining this parent resource, there would be no "list" operation to get all the recovery keys for the tenant. Where would the term "recoveryKeys" come from? 

If you like, you can take a look at the entity topic todo.md (https://docs.microsoft.com/en-us/graph/api/resources/todo?view=graph-rest-beta) and the "list task lists" topic (todo-list-lists.md) (https://docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-beta). The todo entity is used in much the same way for their "list" and "create" operations, as your bitLocker entity for your "list" operation.

2020-09-04 21:23 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Get
Line 9548:
Please remove this href line. 
Instead, please add 2 lines after line 9549:
(Indent the way as the existing line 9550)
- name: BitLocker recovery key
- href: resources/bitlockerrecoverykey.md

2020-09-04 21:25 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            href: api/bitlockerrecoverykey-get.md
Please flip the order of "list" and "get" in the TOC, to be consistent with the order of CRUD topics in other parts of the TOC.
Related CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title

2020-09-04 21:28 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlockerrecoverykey-list.md
> +Namespace: microsoft.graph
Reminder: when you change the topic title, please also update the Methods table in bitlockerrecoverykey.md.

2020-09-04 21:31 UTC, angelgolfer-ms requested changes
@hafowler , Laura brought to my attention that you had some questions about my earlier comment regarding documenting the bitlocker entity. I added some more explanation. 
I also added comments for the "list" operation and the TOC. Please take a look. Those are simple to incorporate. Please ping me on Teams if you have more questions.

2020-09-16 21:08 UTC, opbld30 commented
Docs Build status updates of commit _[cb6041e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb6041e021b0f11452d3254623f1e6e5f72a0864)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-32c0bfd1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) | [Details](#user-content-de0bbbbb-32c0bfd1)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-32c0bfd1)
[api-reference/beta/api/bitlocker-list-recoverykeys.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlocker-list-recoverykeys.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlocker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlocker?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |

<a id="7a1003a0-32c0bfd1"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-32c0bfd1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-16 21:15 UTC, opbld30 commented
Docs Build status updates of commit _[2636c36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2636c36675b3684822b670fbd032bbcfb4398de7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-959a5374)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) | [Details](#user-content-de0bbbbb-959a5374)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-959a5374)
[api-reference/beta/api/bitlocker-list-recoverykeys.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlocker-list-recoverykeys.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlocker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlocker?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |

<a id="7a1003a0-959a5374"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-959a5374"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-16 23:21 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | beta | Added the [bitlockerRecoveryKey](/graph/api/resources/bitlockerRecoveryKey?view=graph-rest-beta) resource type.|
@hafowler , can you please move row 240 (your changelog item) from the July section to the September section? 
We do go by when the docs are eventually published, for the benefit of customers to discover the new API.

2020-09-16 23:24 UTC, angelgolfer-ms commented on api-reference/beta/api/bitlocker-list-recoverykeys.md
> +# List bitlockerRecoveryKeys
I think the topic title should reflect the name of the nav property, not pluralizing the actual resource name.
Like you have it in the Methods table in bitlocker.md, "List recoverKeys", based on recoveryKeys being the name of the nav property.

2020-09-16 23:25 UTC, angelgolfer-ms requested changes
@hafowler , just two comments, one on the list operation topic title, and the changelog item location.

2020-09-17 01:19 UTC, opbld34 commented
Docs Build status updates of commit _[e5cedd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5cedd575957dd11b708500e3964af965c972374)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-ff4f7b92)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) | [Details](#user-content-de0bbbbb-ff4f7b92)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-ff4f7b92)
[api-reference/beta/api/bitlocker-list-recoverykeys.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlocker-list-recoverykeys.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlocker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlocker?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |

<a id="7a1003a0-ff4f7b92"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-ff4f7b92"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md)
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 25, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-17 02:34 UTC, opbld30 commented
Docs Build status updates of commit _[0379839](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0379839258aa45f3587bf5e1485933c4506ccd59)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-da58051d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) | [Details](#user-content-de0bbbbb-da58051d)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-da58051d)
[api-reference/beta/api/bitlocker-list-recoverykeys.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlocker-list-recoverykeys.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlocker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlocker?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |

<a id="7a1003a0-da58051d"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-da58051d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-17 02:35 UTC, opbld33 commented
Docs Build status updates of commit _[ac38067](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac380672cb3ac0d6749c4b0b8dc094acfce277b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) | [Details](#user-content-7a1003a0-ba84909d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9309) | [Details](#user-content-de0bbbbb-ba84909d)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9309) | [Details](#user-content-075040e5-ba84909d)
[api-reference/beta/api/bitlocker-list-recoverykeys.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlocker-list-recoverykeys.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/api/bitlockerrecoverykey-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/api/bitlockerrecoverykey-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlocker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlocker?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/resources/bitlockerrecoverykey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/bitlockerrecoverykey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bitlockerrecoverykey?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&branch=pr-en-us-9309) (graph-rest-beta) |
[changelog/Microsoft.BitLocker.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/changelog/Microsoft.BitLocker.json) | :white_check_mark:Succeeded | |

<a id="7a1003a0-ba84909d"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="de0bbbbb-ba84909d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-07-23-hafowler-bitlocker-update/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-17 02:38 UTC, merged