Update application.md for spa type
microsoftgraph/microsoft-graph-docs pull request #9423
Opened 2020-08-07 18:46 UTC by hamiltonha

2020-08-07 18:47 UTC, opbld30 commented
Docs Build status updates of commit _[7ef5265](https://github.com/hamiltonha/microsoft-graph-docs/commits/7ef526559895398192b2c0e9bfc6c3c3be5ab35f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-6a5dd4b2-33d042c4)

<a id="6a5dd4b2-33d042c4"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md)
 - **Line 83, Column 8**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008071846293052-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=44CacOPEhRC7LdOeVUfcCpEMu8r3e4w2zlzN9u0utIM%3D&st=2020-08-07T18%3A42%3A40Z&se=2020-09-07T18%3A47%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-07 18:56 UTC, opbld32 commented
Docs Build status updates of commit _[4369eba](https://github.com/hamiltonha/microsoft-graph-docs/commits/4369eba45be74797d446a5c91e453e502010d344)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008071855347953-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4KLvICCUc4vluFEjsIo1hEMd7xtiqBFam5RTRB7e1xA%3D&st=2020-08-07T18%3A51%3A45Z&se=2020-09-07T18%3A56%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-07 19:14 UTC, opbld32 commented
Docs Build status updates of commit _[6c16c3f](https://github.com/hamiltonha/microsoft-graph-docs/commits/6c16c3f7c043d294b291a888c2113a05c0145bc6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-96ce013d)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="8fd121af-96ce013d"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 32**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008071913379349-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f0iLFPL6NspE%2FXdjdBwn6W0uP%2BTVVWSFYBJgTIzef8Q%3D&st=2020-08-07T19%3A09%3A57Z&se=2020-09-07T19%3A14%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-07 19:21 UTC, opbld33 commented
Docs Build status updates of commit _[1ff684f](https://github.com/hamiltonha/microsoft-graph-docs/commits/1ff684fe18d45bcddb47fa346a6c4f3ca3e8c9e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-b345cf0a)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="8fd121af-b345cf0a"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 32**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008071919576396-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=grK9rpbFgqUrfLIeTA%2FGJIzrJUf5wqQgNzgKyHe3TdI%3D&st=2020-08-07T19%3A16%3A07Z&se=2020-09-07T19%3A21%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-07 19:23 UTC, opbld33 commented
Docs Build status updates of commit _[b456676](https://github.com/hamiltonha/microsoft-graph-docs/commits/b4566767ab44f78e2b7b669c4d366ca2e220d440)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-d4f05efe)
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-c20c8335-d4f05efe)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="8fd121af-d4f05efe"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 32**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

<a id="c20c8335-d4f05efe"></a>
### [api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md)
 - **Line 62, Column 29**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008071922232475-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fLYszH5css05xKG3LUU85rUwwv%2FsuQfi%2BwKHfZolS%2Fo%3D&st=2020-08-07T19%3A18%3A41Z&se=2020-09-07T19%3A23%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-07 19:25 UTC, opbld33 commented
Docs Build status updates of commit _[e99e2a3](https://github.com/hamiltonha/microsoft-graph-docs/commits/e99e2a371ed9f8ffd60a39a45e1ccb386e8d60cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-fd9e4ebb-33b375b0)
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-33b375b0)
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-c20c8335-33b375b0)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="fd9e4ebb-33b375b0"></a>
### [api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md)
 - **Line 65, Column 29**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

<a id="8fd121af-33b375b0"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 32**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

<a id="c20c8335-33b375b0"></a>
### [api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md)
 - **Line 62, Column 29**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008071923596935-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8nWR7Mv%2BbsZgVIBDDxDTR4wXBlXkUD5%2Bu276dY9yVHY%3D&st=2020-08-07T19%3A20%3A11Z&se=2020-09-07T19%3A25%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-13 04:05 UTC, opbld32 commented
Docs Build status updates of commit _[be99f73](https://github.com/hamiltonha/microsoft-graph-docs/commits/be99f73c312466f79e7f6805ae738ebb09c9e234)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-fd9e4ebb-ab350b08)
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-ab350b08)
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-c20c8335-ab350b08)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="fd9e4ebb-ab350b08"></a>
### [api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md)
 - **Line 65, Column 29**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

<a id="8fd121af-ab350b08"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 32**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

<a id="c20c8335-ab350b08"></a>
### [api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md)
 - **Line 62, Column 29**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008130404249273-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FYON446TsTxw35Iz4AE5nizbOYvkm3yRrBqQATplyjk%3D&st=2020-08-13T04%3A00%3A37Z&se=2020-09-13T04%3A05%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-13 04:14 UTC, CelesteDG commented on api-reference/beta/resources/application.md
> +| spa                        | [spaApplication](spaapplication.md)                                                | Specifies settings for a single-page application. `spa` type redirect URIs notify t
Missing the .. to get to where the spapplication.md file is (in api-reference/v1.0/resources folder). Not familiar enough with Graph, but should the stuff in beta be linking to v1.0 resources files? Just checking.

2020-08-13 04:14 UTC, CelesteDG commented on api-reference/beta/api/application-update.md
> +| spa                     | [spaApplication](spaapplication.md)                                          | Specifies settings for a single-page application. `spa` type redirect URIs notify the server
Missing the .. to get to where the spapplication.md file is (in api-reference/v1.0/resources folder). Not familiar enough with Graph, but should the stuff in beta be linking to v1.0 resources files? Just checking.

2020-08-13 04:16 UTC, CelesteDG commented on api-reference/v1.0/api/application-update.md
> +| spa                     | [spaApplication](spaapplication.md)                                         | Specifies settings for a single-page application. `spa` type redirect URIs notify the server
Missing the ../resources/ part of the link for the spaapplication.md.

2020-08-13 04:19 UTC, CelesteDG commented
@hamiltonha - For the API Doctor errors, please see this page: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/66012/API-Doctor-validate-examples

2020-08-14 17:53 UTC, opbld34 commented
Docs Build status updates of commit _[79a7173](https://github.com/hamiltonha/microsoft-graph-docs/commits/79a7173b00f41876df55004034048c1549a1b14c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-fd9e4ebb-3861f7ca)
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-3861f7ca)
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-c20c8335-3861f7ca)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="fd9e4ebb-3861f7ca"></a>
### [api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md)
 - **Line 65, Column 29**: **[Warning-file-not-found]** `````Invalid file link: '../resources/spaapplication.md'.`````

<a id="8fd121af-3861f7ca"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 32**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

<a id="c20c8335-3861f7ca"></a>
### [api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md)
 - **Line 62, Column 29**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008141752374975-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P%2F4RHQqX6WoH4zfJaSXNgMtDAEp7V5m%2FMSdFV2ZuD5U%3D&st=2020-08-14T17%3A48%3A57Z&se=2020-09-14T17%3A53%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-14 17:55 UTC, opbld30 commented
Docs Build status updates of commit _[f90b99a](https://github.com/hamiltonha/microsoft-graph-docs/commits/f90b99aa23302003a1b7bc5a61b6ac3782e407e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-fd9e4ebb-adf21a27)
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-adf21a27)
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="fd9e4ebb-adf21a27"></a>
### [api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md)
 - **Line 65, Column 29**: **[Warning-file-not-found]** `````Invalid file link: '../resources/spaapplication.md'.`````

<a id="8fd121af-adf21a27"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 32**: **[Warning-file-not-found]** `````Invalid file link: 'spaapplication.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008141753079420-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=07e855HOY%2BS5CR20%2BgWwOY211x4PqcTi8WTSrCtVtOc%3D&st=2020-08-14T17%3A50%3A16Z&se=2020-09-14T17%3A55%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 18:17 UTC, opbld30 commented
Docs Build status updates of commit _[467e886](https://github.com/hamiltonha/microsoft-graph-docs/commits/467e886a92f682793427120eae9dc7b8c9fcfc85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-fd9e4ebb-8c722875)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-6a5dd4b2-8c722875)
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) |
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="fd9e4ebb-8c722875"></a>
### [api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md)
 - **Line 65, Column 29**: **[Warning-file-not-found]** `````Invalid file link: '../resources/spaapplication.md'.`````

<a id="6a5dd4b2-8c722875"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011061815589904-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w5CZoaNMYczVNvfuHwvB80TUgzlEXWCyzIJSuXepMKU%3D&st=2020-11-06T18%3A12%3A13Z&se=2020-12-07T18%3A17%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-09 21:01 UTC, opbld31 commented
Docs Build status updates of commit _[321250b](https://github.com/hamiltonha/microsoft-graph-docs/commits/321250bfe890549462be76042a134429102e45d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-6a5dd4b2-f603991e)
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) |
[api-reference/beta/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) |
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="6a5dd4b2-f603991e"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011092059524034-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OkoLGwunqEYns4rezE5wMp3FPLXpnGofV2YZ4ze4lz0%3D&st=2020-11-09T20%3A56%3A16Z&se=2020-12-10T21%3A01%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-09 21:02 UTC, opbld32 commented
Docs Build status updates of commit _[0dd5edb](https://github.com/hamiltonha/microsoft-graph-docs/commits/0dd5edba9cab06ba3093953c92a088db5682df17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-6a5dd4b2-aaf0ae3f)
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) |
[api-reference/beta/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) |
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="6a5dd4b2-aaf0ae3f"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011092100540778-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DYC9XB7K17qJhS8fh6CFG0djsw0dPtyn3GUuG0%2BSszs%3D&st=2020-11-09T20%3A57%3A46Z&se=2020-12-10T21%3A02%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-09 22:45 UTC, opbld30 commented
Docs Build status updates of commit _[f187ea8](https://github.com/hamiltonha/microsoft-graph-docs/commits/f187ea8fa59dc33c00970a96c2115b60023cc93b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-6a5dd4b2-f6400878)
[api-reference/beta/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) |
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="6a5dd4b2-f6400878"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011092244264447-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n6%2FcuXp%2FZN62WmCZEfWLMu91wL29FTEK%2FzkgLWb60pQ%3D&st=2020-11-09T22%3A40%3A39Z&se=2020-12-10T22%3A45%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-09 22:47 UTC, opbld34 commented
Docs Build status updates of commit _[2a4d38d](https://github.com/hamiltonha/microsoft-graph-docs/commits/2a4d38d2bfe1618d6608b7713ace6ed09cba92f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-6a5dd4b2-205c4c01)
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |

<a id="6a5dd4b2-205c4c01"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011092244376035-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wCjau%2FgqNcQVlScpFSnZvigfdtidoJ1HFtWchpY%2Fo0M%3D&st=2020-11-09T22%3A42%3A46Z&se=2020-12-10T22%3A47%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 23:41 UTC, Lauragra requested changes
Please add an entry to the changelog.md file and the DirectoryServices.json changelog file to mention that this property is now available in v1.0.

2021-01-13 23:22 UTC, opbld31 commented
Docs Build status updates of commit _[927875a](https://github.com/hamiltonha/microsoft-graph-docs/commits/927875a0d14320aa232fb964f22eee2ae7dded19)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-af82c896)

<a id="af82c896"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132321305730-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3FQdULlSYG%2FVJcB5xPCHy51PjQDhNvrDmHTBJBgFu%2F4%3D&st=2021-01-13T23%3A16%3A59Z&se=2021-02-13T23%3A21%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:23 UTC, opbld32 commented
Docs Build status updates of commit _[feae6e8](https://github.com/hamiltonha/microsoft-graph-docs/commits/feae6e8a519b15862a666dbee24150701f2890cc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-368cb875)

<a id="368cb875"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132323091540-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JQ3EU7vhmFvhC47UyU18oSsuPW8WVCo7fAHPw9s0nHo%3D&st=2021-01-13T23%3A18%3A33Z&se=2021-02-13T23%3A23%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:46 UTC, opbld34 commented
Docs Build status updates of commit _[3360616](https://github.com/hamiltonha/microsoft-graph-docs/commits/33606166b02ea78ff5349107cf5c592fe1e1ed38)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-47865128)

<a id="47865128"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132346098948-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ra1fqO%2FR1G9bxzMTG3D1U75koi5dW0CLEr5uMx5zcWE%3D&st=2021-01-13T23%3A41%3A29Z&se=2021-02-13T23%3A46%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-19 20:22 UTC, opbld31 commented
Docs Build status updates of commit _[ba16d21](https://github.com/hamiltonha/microsoft-graph-docs/commits/ba16d21e91d739655a9cabc105d7057937a2afa9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-607e601b)

<a id="607e601b"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101192022134618-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c5h9K687yVnY%2Baln3i%2FJo9eX3K8AU6YOy%2Bw35e1X5VE%3D&st=2021-01-19T20%3A17%3A36Z&se=2021-02-19T20%3A22%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-19 20:52 UTC, opbld30 commented
Docs Build status updates of commit _[7486374](https://github.com/hamiltonha/microsoft-graph-docs/commits/748637432b20fa4f0e54beb57e4562810103af4d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-fd9e4ebb-77e1042d)
[api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-9423) (graph-rest-beta) | [Details](#user-content-8fd121af-77e1042d)
[api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) | [Details](#user-content-6a5dd4b2-77e1042d)
[api-reference/v1.0/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/spaapplication.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/spaapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/spaapplication?view=graph-rest-1.0&branch=pr-en-us-9423) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Intune.json](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/changelog/Microsoft.Intune.json) | :white_check_mark:Succeeded | |
[changelog/changelog.json](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="fd9e4ebb-77e1042d"></a>
### [api-reference/beta/api/application-update.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/api/application-update.md)
 - **Line 65, Column 29**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'spaapplication.md'.`````

<a id="8fd121af-77e1042d"></a>
### [api-reference/beta/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/application.md)
 - **Line 90, Column 29**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/spaapplication.md'.`````
 - **Line 67, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online`````

<a id="6a5dd4b2-77e1042d"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/hamiltonha/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101192051184617-9423%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1YeQTmdh%2F7s8JrvyM8zgfzpm316xQXE0450WgejtCz0%3D&st=2021-01-19T20%3A47%3A29Z&se=2021-02-19T20%3A52%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 19:01 UTC, closed without merging