Added calendar permission changes
microsoftgraph/microsoft-graph-docs pull request #9525
Opened 2020-08-14 08:51 UTC by Bhupesh12Hub

Added List and Create changes for calendar permission resource

2020-08-14 08:51 UTC, opbld32 commented
Docs Build status updates of commit _[35eae05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35eae057a116760f24e356314dab0197397eb28b)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-08-14 08:52 UTC, opbld31 commented
Docs Build status updates of commit _[35eae05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35eae057a116760f24e356314dab0197397eb28b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendarpermission-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-create?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-66256dfe-a17e3a59)
[api-reference/beta/api/calendarpermission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-list?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-62187b28-a17e3a59)
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |

<a id="66256dfe-a17e3a59"></a>
### [api-reference/beta/api/calendarpermission-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-create.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````

<a id="62187b28-a17e3a59"></a>
### [api-reference/beta/api/calendarpermission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-list.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008140851069903-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XHCh1BAXmz4dgWVM9uG6tfdLAuX6bjONFpGduFIGHdA%3D&st=2020-08-14T08%3A47%3A18Z&se=2020-09-14T08%3A52%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-14 09:57 UTC, opbld33 commented
Docs Build status updates of commit _[579ec22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/579ec226450f717d6ba23b8d2e36521399971c12)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendarpermission-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-create?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-66256dfe-314c83c6)
[api-reference/beta/api/calendarpermission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-list?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-62187b28-314c83c6)
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

<a id="66256dfe-314c83c6"></a>
### [api-reference/beta/api/calendarpermission-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-create.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````

<a id="62187b28-314c83c6"></a>
### [api-reference/beta/api/calendarpermission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-list.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008140956339081-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YOQDJNSe5WH6nEeyQ5m5UdlbW4e1ikouAeDB%2FqBtbe4%3D&st=2020-08-14T09%3A52%3A45Z&se=2020-09-14T09%3A57%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-14 10:05 UTC, Bhupesh12Hub commented
@angelgolfer-ms 
Please review the PR and let me know your valuable feedback.

2020-08-14 17:10 UTC, opbld31 commented
Docs Build status updates of commit _[c795f7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c795f7e0c519fa4013e191a44f724415b7c47467)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendarpermission-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-create?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-list?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008141708491375-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FloFQt9sBg18MTQQ53Pq80FeuYT9ihUy9IgNojVoRJU%3D&st=2020-08-14T17%3A05%3A08Z&se=2020-09-14T17%3A10%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-14 17:59 UTC, opbld34 commented
Docs Build status updates of commit _[39e54bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39e54bfa5234d85d2f091a5097952e7c3d80a034)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendarpermission-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-create?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendarpermission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-list?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008141758052745-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nBqWXoxyGrvrIOOzmtBGVh6FIaDFIkhWcHrfLy5oIWI%3D&st=2020-08-14T17%3A54%3A30Z&se=2020-09-14T17%3A59%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-14 21:45 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +# Create calendarPermission
Comments for this topic, as also conveyed in Teams:

(1) File name - I suppose you haven't had a chance to read this filenaming CDK topic:: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55061/File-naming

 

That file should be named calendar-post-calendarpermissions.md, based on how the calendarPermissions nav property is defined as part of the calendar entity in the beta CSDL:

<NavigationProperty Name="calendarPermissions" Type="Collection(graph.calendarPermission)" ContainsTarget="true"/>

 

(2) In that topic, the HTTP request section doesn't seem to have to incur that many segments, because after all, you only need to show the most basic scenario - creating a calendarPermission resource given a calendar, that describes any of its sharing or delegation. Instead of this:


POST /users/{usersId}/messages/{messageId}/event/calendar/calendarPermissions


 

The HTTP request section should be just like this for the default calendar:


POST /users/{usersId}/calendar/calendarPermissions
 
You should also include the non-default calendar scenarios, like a specified calendar, or a calendar in a calendar group, like what has been done in the HTTP request section in the GET, PATCH, and DELETE topics. For example: https://docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&tabs=http#http-request
 
(3) In the Examples section, you should include request and response payloads with real-looking property values. What you have currently are just defining the type of each property in a payload.
 
(4) Delete the blank line in line 98.
 
(5) Always remember to have a blank line before the payload. That is, insert a blank line between line 99 and 100.

2020-08-14 21:48 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-list.md
> +# List calendarPermissions
The similar issues as calendarpermission-create.md apply to this topic with the filename calendarpermission-list.md. The correct filename should be calendar-list-calendarpermissions.md.
 
Please refer to the rest of the comments for calendarpermission-create.md and apply the similar fixes to calendarpermissions-list.md.

2020-08-15 00:40 UTC, angelgolfer-ms commented on api-reference/beta/resources/calendarpermission.md
> +Get, update, delete, list and create of calendar permissions is supported on behalf of only the calendar owner.
Can you please change the order: list, create, get, update, delete
We follow that order in the TOC and in method tables in parent resource topics.

2020-08-15 00:42 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Addition | Beta | Added [list](/graph/api/calendarpermission-list?view=graph-rest-beta) and     [create](/graph/api/calendarpermission-create?view=graph-rest-beta) APIs to manage [calendarPermission
Line 19: Please keep a single space between words, reduce the space before "[create]".

2020-08-15 00:59 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +author: Bhupesh12Hub
GLOBAL:
As an example, line 4 for this topic, but the same comment applies to all Microsoft Graph topics.
@Bhupesh12Hub , @Harini84 , FYI the author field is for automated assignment of GitHub issues. Generally we recommend:
(1) Having the same person to be the contact person for Github issues, representing the product side owner team. That person will answer or redirect to other internal team members to answer these customer questions, and address any documentation updates. 
(2) Choosing a person who is relatively stable in the role and would not be frequently reassigned to a different project . 
Reasons are to help build rapport with the community, and for internal maintenance, as often when a person switches project, previous assignments are orphaned.

2020-08-16 16:59 UTC, opbld33 commented
Docs Build status updates of commit _[5ab4f6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ab4f6af324707368d32595e8f3447572d432dee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-create-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-create-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-create-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendar-list-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-list-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008161658107765-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mNxA5L5U6gRwe%2FzkI%2BKcLZFByickivIuS%2B9ao%2BWmlyg%3D&st=2020-08-16T16%3A54%3A26Z&se=2020-09-16T16%3A59%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-16 17:10 UTC, opbld32 commented
Docs Build status updates of commit _[f9f569d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9f569de2df0a0574ed8a3d46489adeeceb2b116)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-create-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-create-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-create-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendar-list-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-list-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202008161709441207-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JhuccxGDdP3bh49S8k682gOeoQonwUHIIEXs5wYyKW4%3D&st=2020-08-16T17%3A05%3A59Z&se=2020-09-16T17%3A10%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-08-16 17:38 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendarpermission-create.md
> +# Create calendarPermission
Updated

2020-08-16 17:39 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendarpermission-list.md
> +# List calendarPermissions
Updated

2020-08-16 17:39 UTC, Bhupesh12Hub commented on api-reference/beta/resources/calendarpermission.md
> +Get, update, delete, list and create of calendar permissions is supported on behalf of only the calendar owner.
Updated

2020-08-16 17:39 UTC, Bhupesh12Hub commented on concepts/changelog.md
> +|Addition | Beta | Added [list](/graph/api/calendarpermission-list?view=graph-rest-beta) and     [create](/graph/api/calendarpermission-create?view=graph-rest-beta) APIs to manage [calendarPermission
Updated

2020-08-16 17:43 UTC, Bhupesh12Hub commented
@angelgolfer-ms 
Thanks for the detailed and valuable review, feedback was really helpful in understanding the process.
I have made the changes as per the feedback and all the checks has been passed successfully.
Please review the updated PR.
Thanks,
Bhupesh

2020-08-27 05:28 UTC, Harini84 commented on api-reference/beta/api/calendarpermission-create.md
> +author: Bhupesh12Hub
@angelgolfer-ms 
Sure, if the field permits both my name and Bhupesh name can be added as author.

Thanks,
Harini

2020-08-31 19:43 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +author: Bhupesh12Hub
@Harini84 , the field supports only one name.

2020-08-31 19:49 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-create-calendarpermission.md
>  -->
File name:
@Bhupesh12Hub , if you refer to my [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/9525#discussion_r470878497) earlier: the filename should be calendar-post-calendarpermissions.md.
That's for consistency with how the stub topic generator and most of the other existing files.

2020-08-31 19:54 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-create-calendarpermission.md
> +POST /users/{id}/calendar/calendarPermissions/{id}
Line 31:
@Harini84 , does this line look correct to you?
Or should it be what I brought up in my [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/9525#discussion_r470878497) last time:
POST /users/{id}/calendar/calendarPermissions

BTW, @Bhupesh12Hub , FYI, GLOBAL:
Whenever you document the "HTTP request" section that indexes into the users segment, please make sure you show 2 lines:
- One line using the 'me' shortcut
- Another line using the users/{id} shortcut.

Using this topic as an example, assuming the following is the correct syntax, then you should have 2 lines:
POST /me/calendar/calendarPermissions
POST /users/{id}/calendar/calendarPermissions

2020-08-31 20:25 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-create-calendarpermission.md
> +POST https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions/{id}
@Bhupesh12Hub ,
Line 76 is still incorrect.

GLOBAL:
When you document a new example, please try it out with a sample tenant on Graph Explorer. Please do not attempt to just plug in property values, as you probably have done here; there's still room for error.
If you use the correct process, there's less chance that an incorrect example gets published.

2020-08-31 20:27 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-create-calendarpermission.md
>      "@odata.type": "microsoft.graph.emailAddress"
Line 107:
Same comment as the last - this line is still incorrect. Please try out your example before copying it to the topic.

2020-08-31 20:40 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +# Create calendarPermission
Unresolved this comment for #1 and #2.

2020-08-31 20:41 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-list.md
> +# List calendarPermissions
Unresolved this because the filename is still incorrect.

2020-08-31 20:44 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermission.md
> +GET /users/{id}/calendar/calendarPermissions/{id}
The file name is still incorrect. Please see the original comment: https://github.com/microsoftgraph/microsoft-graph-docs/pull/9525#discussion_r470879623

2020-08-31 20:47 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermission.md
> +GET https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions/{id}
Per my global comment in the "create" operation topic, please make sure you add another syntax line that uses the 'me' shortcut.

2020-08-31 20:48 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermission.md
>        "emailAddress": {
Line 80 is still incorrect. Please fix.

2020-08-31 20:53 UTC, angelgolfer-ms commented on api-reference/beta/resources/calendarpermission.md
> +|[List](../api/calendar-list-calendarpermission.md)|[calendarPermission](../resources/calendarpermission.md) collection|Get a list of the [calendarPermission](../resources/calendarpermission.md) obje
Please fix the links to the topics for which you renamed the files!!

GLOBAL:
Are you aware of how to review your topics on the staging site? 
It's a good practice to always review your files on the staging site whenever you make a change.
When you do a commit on GitHub, the build would generate a table that lists what's changed in that commit. The table has a column "Preview URL". Click "View" in that column lets you see the corresponding topic on the staging site for your PR.

For example, the staged topic for calendarpermission.md is here: https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525

2020-08-31 20:54 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Addition | Beta | Added [list](/graph/api/calendarpermission-list?view=graph-rest-beta) and [create](/graph/api/calendarpermission-create?view=graph-rest-beta) operations to manage [calendarPermissi
Please fix the links to the 2 files you renamed!

2020-08-31 21:04 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Addition | Beta | Added [list](/graph/api/calendarpermission-list?view=graph-rest-beta) and [create](/graph/api/calendarpermission-create?view=graph-rest-beta) operations to manage [calendarPermissi
Also, please move this changelog item to a September section.

2020-09-02 17:16 UTC, opbld31 commented
Docs Build status updates of commit _[e0a8bee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0a8bee30565ce810dcdbfb2cd491babfd7cee9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-493bebf0-b851295a)
[api-reference/beta/api/calendar-create-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-create-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-create-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendar-list-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-list-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

<a id="493bebf0-b851295a"></a>
### [api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'The permissions of a user with whom the calendar is shared.' is duplicated in 'beta/resources/calendarpermission.md(3,14)', 'v1.0/resources/calendarpermission.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009021715323485-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TKUyqgsSIOhVY%2Bml2KpvA2oEOoVyntTpI20i9Lv04xM%3D&st=2020-09-02T17%3A11%3A58Z&se=2020-10-03T17%3A16%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-03 14:49 UTC, opbld30 commented
Docs Build status updates of commit _[5726ead](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5726ead32444930d137af8c1a3d6a7d6cf82d8c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-493bebf0-39511ab8)
[api-reference/beta/api/calendar-create-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-create-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-create-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendar-list-calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-list-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

<a id="493bebf0-39511ab8"></a>
### [api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'The permissions of a user with whom the calendar is shared.' is duplicated in 'beta/resources/calendarpermission.md(3,14)', 'v1.0/resources/calendarpermission.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009031448157687-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jl%2B6chLcoC%2BTCPlE2a8hCZC0V3EBwMm5ZelfdR4CVLM%3D&st=2020-09-03T14%3A44%3A39Z&se=2020-10-04T14%3A49%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-03 15:50 UTC, opbld34 commented
Docs Build status updates of commit _[78ffa45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78ffa451300120fdb821bee5768241e8d7de577f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-493bebf0-04a6ac7e)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) |

<a id="493bebf0-04a6ac7e"></a>
### [api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'The permissions of a user with whom the calendar is shared.' is duplicated in 'beta/resources/calendarpermission.md(3,14)', 'v1.0/resources/calendarpermission.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009031549083503-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uhppvJdCD8q%2F1WDFzJR5WDGaUodIwcA%2BAzVsS%2ByeLs8%3D&st=2020-09-03T15%3A45%3A31Z&se=2020-10-04T15%3A50%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-03 16:45 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendarpermission-create.md
> +# Create calendarPermission
Comments 1 and 2 are resolved.

2020-09-03 16:46 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendarpermission-list.md
> +# List calendarPermissions
Filename is updated

2020-09-03 16:46 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendarpermission-create.md
> +author: Bhupesh12Hub
Updated

2020-09-03 16:47 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendar-create-calendarpermission.md
>  -->
updated

2020-09-03 16:47 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendar-create-calendarpermission.md
> +POST /users/{id}/calendar/calendarPermissions/{id}
Updated

2020-09-03 16:48 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendar-create-calendarpermission.md
> +POST https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions/{id}
Noted and updated the same

2020-09-03 16:48 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendar-create-calendarpermission.md
>      "@odata.type": "microsoft.graph.emailAddress"
Updated

2020-09-03 16:48 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendar-list-calendarpermission.md
> +GET /users/{id}/calendar/calendarPermissions/{id}
Updated

2020-09-03 16:49 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendar-list-calendarpermission.md
> +GET https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions/{id}
Noted and Updated

2020-09-03 16:49 UTC, Bhupesh12Hub commented on api-reference/beta/api/calendar-list-calendarpermission.md
>        "emailAddress": {
Updated

2020-09-03 16:50 UTC, Bhupesh12Hub commented on api-reference/beta/resources/calendarpermission.md
> +|[List](../api/calendar-list-calendarpermission.md)|[calendarPermission](../resources/calendarpermission.md) collection|Get a list of the [calendarPermission](../resources/calendarpermission.md) obje
Updated and Noted

2020-09-03 16:50 UTC, Bhupesh12Hub commented on concepts/changelog.md
> +|Addition | Beta | Added [list](/graph/api/calendarpermission-list?view=graph-rest-beta) and [create](/graph/api/calendarpermission-create?view=graph-rest-beta) operations to manage [calendarPermissi
Updated

2020-09-03 16:51 UTC, Bhupesh12Hub commented
@angelgolfer-ms 

Files are updated as per the comments. Please review.

Thanks,
Bhupesh

2020-11-03 04:21 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +  "@odata.type": "Collection(microsoft.graph.calendarPermission)"
Line 68: 
The way to specify this is:
  "@odata.type": "microsoft.graph.calendarPermission",
  "isCollection": true

See the CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/66013/Set-up-for-API-Doctor?anchor=set-up-for-api-doctor-in-an-api-topic

2020-11-03 04:28 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +      "isRemovable": true,
Lines 81 and 83:
If the emailAddress is My organization, then the isRemovable property should be false.
We documented for the isRemovable property in the calendarpermission.md topic that:
"You cannot remove "My organization" as a sharee to a calendar."

2020-11-03 04:38 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +|Permission type|Permissions (from most to least privileged)|
Lines 18-22, the permissions table:
If you take a look at calendarpermission-get.md and calendarpermission-update.md, we have to address two different sets of permissions, depending on whether the calendar is a user calendar or group calendar.

Perhaps you should confirm with @Harini84 and @JuForan that group calendar is a valid scenario to document for both "list calendarPermissions" and "create calendarPermission". If so, the permissions should be respectively, same as those documented for "get calendarPermission" and "update calendarPermission".

2020-11-03 04:38 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +|Permission type|Permissions (from most to least privileged)|
Lines 18-22, the permissions table:
If you take a look at calendarpermission-get.md and calendarpermission-update.md, we have to address two different sets of permissions, depending on whether the calendar is a user calendar or group calendar.

Perhaps you should confirm with @Harini84 and @JuForan that group calendar is a valid scenario to document for both "list calendarPermissions" and "create calendarPermission". If so, the permissions should be respectively, same as those documented for "get calendarPermission" and "update calendarPermission".

2020-11-03 04:49 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +|id|String|The unique identifier of the user with whom the calendar has been shared. Inherited from [entity](../resources/entity.md)|
Line 48:
I don't think you can specify the id property when creating a calendarPermission object. Please remove that row.

2020-11-03 04:51 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +|isRemovable|Boolean|True if the user can be removed from the list of delegates for the specified calendar, false otherwise.|
Line 50:
I think you should include in the description, "The "My organization" user determines the permissions other people within your organization have to the given calendar. You cannot remove "My organization" as a sharee to a calendar."

2020-11-03 04:54 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +  "isRemovable": "true",
Line 79:
Should isRemovable be false for the "My organization" email name?
Based on the existing documentation for the isRemovable property:
"... The "My organization" user determines the permissions other people within your organization have to the given calendar. You cannot remove "My organization" as a sharee to a calendar."

I think in this example, isRemovable should be false.

2020-11-03 04:54 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +  "isInsideOrganization": true,
Line 110:
Same comment - isRemovable should be false if emailAddress specifies the My organization name.

2020-11-03 04:59 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +
Lines 30-33:
Based on the existing calendarpermission-get.md and calendarpermission-update.md topics, I think we should document the syntax lines to address the case if the calendar is a group calendar.
Similar to the permissions section, please seek confirmation with @Harini84 and @JuForan that group calendar is a valid scenario and review the syntax lines you add.

2020-11-03 05:00 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +
Lines 30-33:
Based on the existing calendarpermission-get.md and calendarpermission-update.md topics, I think we should document the syntax lines to address the case if the calendar is a group calendar.
Similar to the permissions section, please seek confirmation with @Harini84 and @JuForan that group calendar is a valid scenario and review the syntax lines you add.

2020-11-03 05:03 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +POST https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions/{id}
Line 70:
When you do a POST to create an object, you don't specify the id. Please remove the trailing "/{id}" in that line.
The id gets assigned when the POST operation succeeds.

You know, as I suggested last time, if you had used Graph Explorer to try the example request, then you would have noticed this syntax doesn't work. Please try your example requests and responses in the future before adding them tot he docs.

2020-11-03 05:04 UTC, angelgolfer-ms commented on api-reference/beta/resources/calendarpermission.md
> +|[Create](../api/calendar-post-calendarpermissions.md)|[calendarPermission](../resources/calendarpermission.md)|Create a new calendarPermissions object.|
Line 27:
Since you can create only one resource at a time, please use singular "calendarPermission object" in the description.

2020-11-03 05:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/calendarpermission.md
> +|[Create](../api/calendar-post-calendarpermissions.md)|[calendarPermission](../resources/calendarpermission.md)|Create a new calendarPermissions object.|
Lines 26-27:
In general, it's helpful to customers if the descriptions in the Methods table for each operation matches the same summary description in the operation topic. Please make sure the descriptions here correspond to the description in each of the "list" and "create" topics.

2020-11-03 05:12 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +
Line 13:
I'd suggest providing some context to the description, like:
"Get a list of calendarPermission resources for the specified user or group calendar."

We can skip "properties", that's implicit; please still provide the link to calendarpermission.md.

2020-11-03 05:15 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +Create a new [calendarPermission](../resources/calendarpermission.md) object.
Line 13:
"Create a calendarPermission resource to specify the permissions with which the specified user or group calendar has been shared or delegated."

2020-11-03 05:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/calendarpermission.md
> + List, create, get, update and delete of calendar permissions is supported on behalf of only the calendar owner.
Line 16:
Sorry, the original sentence had a grammatical error. Please say "... are supported on behalf of..."

2020-11-03 05:18 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub . thanks for incorporating the last set of feedback.
We might have missed the group calendar scenario in the last iteration. Please see my comments on that, and a few others.

2020-11-03 05:33 UTC, angelgolfer-ms commented on concepts/changelog.md
@Bhupesh12Hub , 
Please change your changelog item to go under November 2020 in changelog.md.

Also, wanted to let you know/remind you, the changelog process is in transition. Please see the CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55053/Changelog

Basically, you'd need to update the changelog.md, and a new json version of the changelog, and include both md file and json file in this PR.

2020-11-27 15:44 UTC, opbld32 commented
Docs Build status updates of commit _[80c7d98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80c7d98ba7a7f051a0b70abec85120426da11191)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/activities-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/activities-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/activities-list?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-5ba57854-edbf1108)
[api-reference/beta/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-1fe644aa-edbf1108)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-0cf87949-edbf1108)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-07b05d2b-edbf1108)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-686f0a31-edbf1108)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-f03fc281-edbf1108)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-6bb5760f-edbf1108)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-591908b5-edbf1108)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-e82c98d3-edbf1108)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-c8045151-edbf1108)
[api-reference/beta/api/filter-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/filter-apply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-apply?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-9902448c-edbf1108)
[api-reference/beta/api/filter-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/filter-clear.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-clear?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-57baf092-edbf1108)
[api-reference/beta/api/formatprotection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/formatprotection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/formatprotection-get?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-601687eb-edbf1108)
[api-reference/beta/api/formatprotection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/formatprotection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/formatprotection-update?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-e8edf6d1-edbf1108)
[api-reference/beta/api/get-device-command-status.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/get-device-command-status.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/get-device-command-status?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-6b2b92ca-edbf1108)
[api-reference/beta/api/icon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/icon-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/icon-get?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-81bfe83c-edbf1108)
[api-reference/beta/api/icon-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/icon-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/icon-update?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-401fd58d-edbf1108)
[api-reference/beta/api/inferenceclassification-list-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/inferenceclassification-list-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-list-overrides?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-b0b224dc-edbf1108)
[api-reference/beta/api/inferenceclassification-post-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/inferenceclassification-post-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-post-overrides?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) | [Details](#user-content-c371ea37-edbf1108)
[api-reference/beta/api/inferenceclassificationoverride-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/inferenceclassificationoverride-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2020-11-27 15:55 UTC, opbld33 commented
Docs Build status updates of commit _[2973bea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2973bea57150667b6038b651fdc6cd70b31c007f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) | [Details](#user-content-de0bbbbb-4fc46ce3)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |

<a id="de0bbbbb-4fc46ce3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md)
 - **Line 14, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'September 2020''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/calendar-list-calendarpermissions?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/calendar-post-calendarpermissions?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendarpermission?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-beta`````
 - **Line 260, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'September 2020''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011271554055450-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fDM3zBIjRHLXa4ls8n%2Bo0GJiQiZk2kra%2FEuPBnD%2FzoE%3D&st=2020-11-27T15%3A50%3A45Z&se=2020-12-28T15%3A55%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-27 16:07 UTC, opbld33 commented
Docs Build status updates of commit _[8695c2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8695c2cdc6571e84f453d24d362f738603aa9f4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9525) | [Details](#user-content-de0bbbbb-1c7f9135)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-9525) (graph-rest-beta) |

<a id="de0bbbbb-1c7f9135"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/calendarPermission/Methods/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/calendar-list-calendarpermissions?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/calendar-post-calendarpermissions?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendarpermission?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011271605433319-9525%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tBriqFfSPoVwFuhLO5F%2FmPyfO8wWDaeUVYheTZbPj2g%3D&st=2020-11-27T16%3A02%3A16Z&se=2020-12-28T16%3A07%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 09:39 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub , you missed all my comments from Nov. 2, and part of #2 in a comment earlier on August 14 (https://github.com/microsoftgraph/microsoft-graph-docs/pull/9525#discussion_r470878497). Please read them carefully, let me know if you have questions, and incorporate them if you don't? 

In particular, from my comments on Nov.2, please have @Harini84 or @sochowdh review the "HTTP request" and "Permissions" sections for the "list" and "create" topics. They should be in close parity with the "get", "update", and "delete" topics that @sochowdh had documented earlier.

Regarding the changelog, now that we're in Dec., please make sure the changelog items are displayed under an appropriate month/date, for the changelog MD file and changelog JSON file.

2021-05-05 19:01 UTC, closed without merging