Testing
microsoftgraph/microsoft-graph-docs pull request #9715
Opened 2020-08-31 17:06 UTC by pixieofhugs

@Lauragra and @zengin V1 fixes with build issues resolved. Thanks to @millicentachieng

2020-08-31 17:07 UTC, opbld34 commented
Docs Build status updates of commit _[1fc1678](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fc1678da1d081a8c2b19eab4a3e41bcdb905597)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-6eea3ec5)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ca221dd6-6eea3ec5)
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-e1b1e4f9-6eea3ec5)
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-e75829b0-6eea3ec5)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-6eea3ec5)
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-efcb4743-6eea3ec5)
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-6eea3ec5)
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-e16c9e30-6eea3ec5)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-6eea3ec5)
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-f88d520f-6eea3ec5)
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-6045d151-6eea3ec5)
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-bf66a374-6eea3ec5)
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-95994530-6eea3ec5)
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-1c4a05f2-6eea3ec5)
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-83ecaef8-6eea3ec5)
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-b82159ac-6eea3ec5)
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-4513435c-6eea3ec5)

<a id="68694239-6eea3ec5"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ca221dd6-6eea3ec5"></a>
### [api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Use this API to create a new certificateBasedAuthConfiguration.' is duplicated in 'beta/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md(3,14)', 'v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md(3,14)'. NOTE: This  [...]

2020-09-01 02:46 UTC, Lauragra commented on api-reference/v1.0/api/place-update.md
> +Update the properties of [place](../resources/place.md) object, which can be a [room](../resources/room.md) or [roomList](../resources/roomList.md). You can identify the **room** or **roomList** by s
Please don't update the file names to be camel case. File names are all lowercase.

2020-09-01 02:47 UTC, Lauragra commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +Adds a key credential to a [servicePrincipal](../resources/servicePrincipal.md). This method along with [removeKey](servicePrincipal-removekey.md) can be used by a servicePrincipal to automate rollin
Same here - pls. revert all the changes to the file names in links.

2020-09-09 19:49 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +[!INCLUDE [sample-code](../includes/snippets/java/servicePrincipal-removekey-java-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/java/serviceprincipal-removekey-java-snippets.md)]
```

2020-09-09 19:49 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +[!INCLUDE [sample-code](../includes/snippets/objc/servicePrincipal-removekey-objc-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/objc/serviceprincipal-removekey-objc-snippets.md)]
```

2020-09-09 19:49 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +[!INCLUDE [sample-code](../includes/snippets/javascript/servicePrincipal-removekey-javascript-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/javascript/serviceprincipal-removekey-javascript-snippets.md)]
```

2020-09-09 19:49 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/servicePrincipal-removekey-csharp-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/csharp/serviceprincipal-removekey-csharp-snippets.md)]
```

2020-09-09 19:49 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +  "name": "servicePrincipal_removekey"
```suggestion
  "name": "serviceprincipal_removekey"
```

2020-09-09 19:50 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +[Update servicePrincipal](../api/servicePrincipal-update.md) operations can continue to be used to add and update key credentials for any servicePrincipal with or without a user's context.
```suggestion
[Update servicePrincipal](../api/serviceprincipal-update.md) operations can continue to be used to add and update key credentials for any servicePrincipal with or without a user's context.
```

2020-09-09 19:50 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +> [Create servicePrincipal](../api/servicePrincipal-post-servicePrincipals.md) and
```suggestion
> [Create servicePrincipal](../api/serviceprincipal-post-serviceprincipals.md) and
```

2020-09-09 19:50 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-removekey.md
> +Remove a key credential from a [servicePrincipal](../resources/servicePrincipal.md). This method along with [addKey](servicePrincipal-addkey.md) can be used by a servicePrincipal to automate rolling
```suggestion
Remove a key credential from a [servicePrincipal](../resources/serviceprincipal.md). This method along with [addKey](serviceprincipal-addkey.md) can be used by a servicePrincipal to automate rolling its expiring keys.
```

2020-09-09 19:51 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +[!INCLUDE [sample-code](../includes/snippets/java/create-serviceprincipal-from-servicePrincipals-java-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/java/create-serviceprincipal-from-serviceprincipals-java-snippets.md)]
```

2020-09-09 19:51 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +[!INCLUDE [sample-code](../includes/snippets/objc/create-serviceprincipal-from-servicePrincipals-objc-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/objc/create-serviceprincipal-from-serviceprincipals-objc-snippets.md)]
```

2020-09-09 19:51 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +[!INCLUDE [sample-code](../includes/snippets/javascript/create-serviceprincipal-from-servicePrincipals-javascript-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/javascript/create-serviceprincipal-from-serviceprincipals-javascript-snippets.md)]
```

2020-09-09 19:51 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/create-serviceprincipal-from-servicePrincipals-csharp-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/csharp/create-serviceprincipal-from-serviceprincipals-csharp-snippets.md)]
```

2020-09-09 19:51 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +  "name": "create_serviceprincipal_from_servicePrincipals"
```suggestion
  "name": "create_serviceprincipal_from_serviceprincipals"
```

2020-09-09 19:52 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +If successful, this method returns a `201 Created` response code and a [servicePrincipal](../resources/servicePrincipal.md) object in the response body.
```suggestion
If successful, this method returns a `201 Created` response code and a [servicePrincipal](../resources/serviceprincipal.md) object in the response body.
```

2020-09-09 19:52 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +In the request body, supply a JSON representation of a [servicePrincipal](../resources/servicePrincipal.md) object. The request body must contain  **appId**.
```suggestion
In the request body, supply a JSON representation of a [servicePrincipal](../resources/serviceprincipal.md) object. The request body must contain  **appId**.
```

2020-09-09 19:52 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +> Adding [**passwordCredential**](../resources/passwordcredential.md) when creating servicePrincipals is not supported. Use the [addPassword](servicePrincipal-addpassword.md) method to add passwords
```suggestion
> Adding [**passwordCredential**](../resources/passwordcredential.md) when creating servicePrincipals is not supported. Use the [addPassword](serviceprincipal-addpassword.md) method to add passwords for a servicePrincipal.
```

2020-09-09 19:52 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
> +Create a new [servicePrincipal](../resources/servicePrincipal.md) object.
```suggestion
Create a new [servicePrincipal](../resources/serviceprincipal.md) object.
```

2020-09-09 19:55 UTC, zengin commented on api-reference/v1.0/api/eventmessage-post-attachments.md
> +  "item": "message or event entity"
We need a sample object of type `OutlookItem` instead of a string here, but we can address that as part of generating meaningful input data for testing.

2020-09-09 19:55 UTC, zengin commented on api-reference/v1.0/api/place-update.md
> +Update the properties of [place](../resources/place.md) object, which can be a [room](../resources/room.md) or [roomList](../resources/roomList.md). You can identify the **room** or **roomList** by s
```suggestion
Update the properties of [place](../resources/place.md) object, which can be a [room](../resources/room.md) or [roomList](../resources/roomlist.md). You can identify the **room** or **roomList** by specifying the **id** or **emailAddress** property.
```

2020-09-09 19:56 UTC, zengin commented on api-reference/v1.0/api/place-update.md
> +  "name": "update_roomList"
```suggestion
  "name": "update_roomlist"
```

2020-09-09 19:56 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +Adds a key credential to a [servicePrincipal](../resources/servicePrincipal.md). This method along with [removeKey](servicePrincipal-removekey.md) can be used by a servicePrincipal to automate rollin
```suggestion
Adds a key credential to a [servicePrincipal](../resources/serviceprincipal.md). This method along with [removeKey](serviceprincipal-removekey.md) can be used by a servicePrincipal to automate rolling its expiring keys.
```

2020-09-09 19:56 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +> [Create servicePrincipal](../api/servicePrincipal-post-servicePrincipals.md) and
```suggestion
> [Create servicePrincipal](../api/serviceprincipal-post-serviceprincipals.md) and
```

2020-09-09 19:57 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +[Update servicePrincipal](../api/servicePrincipal-update.md) operations can continue to be used to add and update key credentials for any servicePrincipal with or without a user's context.
```suggestion
[Update servicePrincipal](../api/serviceprincipal-update.md) operations can continue to be used to add and update key credentials for any servicePrincipal with or without a user's context.
```

2020-09-09 19:57 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +ServicePrincipals that don’t have any existing valid certificates (i.e.: no certificates have been added yet, or all certificates have expired), won’t be able to use this service action. [Update serv
```suggestion
ServicePrincipals that don’t have any existing valid certificates (i.e.: no certificates have been added yet, or all certificates have expired), won’t be able to use this service action. [Update servicePrincipal](../api/serviceprincipal-update.md) can be used to perform an update instead.
```

2020-09-09 19:57 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +  "name": "servicePrincipal_addkey"
```suggestion
  "name": "serviceprincipal_addkey"
```

2020-09-09 19:57 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/servicePrincipal-addkey-csharp-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/csharp/serviceprincipal-addkey-csharp-snippets.md)]
```

2020-09-09 19:58 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +[!INCLUDE [sample-code](../includes/snippets/javascript/servicePrincipal-addkey-javascript-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/javascript/serviceprincipal-addkey-javascript-snippets.md)]
```

2020-09-09 19:58 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +[!INCLUDE [sample-code](../includes/snippets/objc/servicePrincipal-addkey-objc-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/objc/serviceprincipal-addkey-objc-snippets.md)]
```

2020-09-09 19:58 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +[!INCLUDE [sample-code](../includes/snippets/java/servicePrincipal-addkey-java-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/java/serviceprincipal-addkey-java-snippets.md)]
```

2020-09-09 19:58 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +  "name": "servicePrincipal_addkey"
```suggestion
  "name": "serviceprincipal_addkey"
```

2020-09-09 19:58 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-addkey.md
> +    "Error: servicePrincipal_addkey:\r\n      Resource type was null or missing, so we assume there is no response to validate."
```suggestion
    "Error: serviceprincipal_addkey:\r\n      Resource type was null or missing, so we assume there is no response to validate."
```

2020-09-09 19:59 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-list.md
> +Retrieve a list of [servicePrincipal](../resources/servicePrincipal.md) objects.
```suggestion
Retrieve a list of [servicePrincipal](../resources/serviceprincipal.md) objects.
```

2020-09-09 19:59 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-list.md
> +If successful, this method returns a `200 OK` response code and collection of [servicePrincipal](../resources/servicePrincipal.md) objects in the response body.
```suggestion
If successful, this method returns a `200 OK` response code and collection of [servicePrincipal](../resources/serviceprincipal.md) objects in the response body.
```

2020-09-09 19:59 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-list.md
> +  "name": "list_servicePrincipal"
```suggestion
  "name": "list_serviceprincipal"
```

2020-09-09 20:00 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-list.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/list-servicePrincipal-csharp-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/csharp/list-serviceprincipal-csharp-snippets.md)]
```

2020-09-09 20:00 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-list.md
> +[!INCLUDE [sample-code](../includes/snippets/javascript/list-servicePrincipal-javascript-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/javascript/list-serviceprincipal-javascript-snippets.md)]
```

2020-09-09 20:00 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-list.md
> +[!INCLUDE [sample-code](../includes/snippets/objc/list-servicePrincipal-objc-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/objc/list-serviceprincipal-objc-snippets.md)]
```

2020-09-09 20:00 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-list.md
> +[!INCLUDE [sample-code](../includes/snippets/java/list-servicePrincipal-java-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/java/list-serviceprincipal-java-snippets.md)]
```

2020-09-09 20:01 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-delete-owners.md
> +Remove an owner from a [servicePrincipal](../resources/servicePrincipal.md) object.
```suggestion
Remove an owner from a [servicePrincipal](../resources/serviceprincipal.md) object.
```

2020-09-09 20:01 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-delete-owners.md
> +  "name": "servicePrincipal_delete_owners"
```suggestion
  "name": "serviceprincipal_delete_owners"
```

2020-09-09 20:01 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-delete-owners.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/servicePrincipal-delete-owners-csharp-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/csharp/serviceprincipal-delete-owners-csharp-snippets.md)]
```

2020-09-09 20:01 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-delete-owners.md
> +[!INCLUDE [sample-code](../includes/snippets/javascript/servicePrincipal-delete-owners-javascript-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/javascript/serviceprincipal-delete-owners-javascript-snippets.md)]
```

2020-09-09 20:01 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-delete-owners.md
> +[!INCLUDE [sample-code](../includes/snippets/objc/servicePrincipal-delete-owners-objc-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/objc/serviceprincipal-delete-owners-objc-snippets.md)]
```

2020-09-09 20:01 UTC, zengin commented on api-reference/v1.0/api/serviceprincipal-delete-owners.md
> +[!INCLUDE [sample-code](../includes/snippets/java/servicePrincipal-delete-owners-java-snippets.md)]
```suggestion
[!INCLUDE [sample-code](../includes/snippets/java/serviceprincipal-delete-owners-java-snippets.md)]
```

2020-09-09 20:05 UTC, zengin requested changes
@pixieofhugs, I marked all the changes that we didn't need to make the camel casing work in snippet generation. We don't need block names and file names to be changed as we don't consume that information to generate type names.

You can commit the changes using Github UI, please let me know if the requested changes doesn't make sense.

2020-09-30 20:24 UTC, opbld30 commented
Docs Build status updates of commit _[3575a5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3575a5affac4dd0752821e24fdf10aeae0b8aae3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-3401946e)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-3401946e)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-3401946e)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-3401946e)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-3401946e"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-3401946e"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-3401946e"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:25 UTC, opbld34 commented
Docs Build status updates of commit _[560181d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/560181deb2cce65b120fc57c26c22cf79f4fed67)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-f8f4f6b3)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-f8f4f6b3)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-f8f4f6b3)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-f8f4f6b3)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-f8f4f6b3"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-f8f4f6b3"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-f8f4f6b3"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:27 UTC, opbld30 commented
Docs Build status updates of commit _[d6eed63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6eed630ab7dd1b7f55624de4f2b867b5fd35e13)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-4aee2fbb)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-4aee2fbb)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-4aee2fbb)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-4aee2fbb)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-4aee2fbb"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-4aee2fbb"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-4aee2fbb"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:28 UTC, opbld32 commented
Docs Build status updates of commit _[c010994](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c01099410fd45bc40fcfbe17a56a516272cdaf27)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-6ecd1706)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-6ecd1706)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-6ecd1706)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-6ecd1706)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-6ecd1706"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-6ecd1706"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-6ecd1706"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:30 UTC, opbld34 commented
Docs Build status updates of commit _[7a3ad77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a3ad7799ddfe2d8859a321845a5621e79bb2b1c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-296a3b95)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-296a3b95)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-296a3b95)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-296a3b95)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-296a3b95"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-296a3b95"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-296a3b95"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:31 UTC, opbld33 commented
Docs Build status updates of commit _[44060fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44060fd273a3cc0cd3e234d86ec53f448efd4eff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-cec43b7d)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-cec43b7d)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-cec43b7d)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-cec43b7d)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-cec43b7d"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-cec43b7d"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-cec43b7d"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:33 UTC, opbld32 commented
Docs Build status updates of commit _[1be7534](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1be7534efcb09a8d4b695946b21e1f96fb724fdb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-44335cfb)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-44335cfb)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-44335cfb)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-44335cfb)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-44335cfb"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-44335cfb"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-44335cfb"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:35 UTC, opbld30 commented
Docs Build status updates of commit _[b6eac1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6eac1c0968d90b22eb502540cfede5e4bd50d52)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-6630828a)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-6630828a)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-6630828a)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-6630828a)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-6630828a"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-6630828a"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-6630828a"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:36 UTC, opbld32 commented
Docs Build status updates of commit _[6a929ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a929ee331ef93acfba1be65662955cd18bb5464)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-49bfabad)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-49bfabad)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-49bfabad)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-49bfabad)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-49bfabad"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-49bfabad"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-49bfabad"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:38 UTC, opbld31 commented
Docs Build status updates of commit _[a1e6758](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1e6758d4d1ea2cdf7e0ed2a0c20d64754d9dff4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-179288c2)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-179288c2)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-179288c2)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-179288c2)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-179288c2"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-179288c2"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-179288c2"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:45 UTC, opbld34 commented
Docs Build status updates of commit _[1bb16a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bb16a5904b99ae4c72ac4bc4fc8082ee4e0c149)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-a978316d)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-a978316d)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-a978316d)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-a978316d)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-a978316d"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-a978316d"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-a978316d"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:47 UTC, opbld34 commented
Docs Build status updates of commit _[372a796](https://github.com/microsoftgraph/microsoft-graph-docs/commits/372a7960ffacc89d489fa06569f7c266129d8a67)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-c9809106)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-c9809106)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-c9809106)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-c9809106)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-c9809106"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-c9809106"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-c9809106"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:48 UTC, opbld34 commented
Docs Build status updates of commit _[59c0d0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59c0d0b47116dd167e7163cfa95282457e8e331b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-965e5c6b)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-965e5c6b)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-965e5c6b)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-965e5c6b)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-965e5c6b"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-965e5c6b"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-965e5c6b"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 20:50 UTC, opbld32 commented
Docs Build status updates of commit _[9f594fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f594fe361563db910f7f2e6e0f2e3769fee4800)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-b3461f60)
[concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/sdks/batch-requests?branch=pr-en-us-9715) | [Details](#user-content-68694239-b3461f60)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-b3461f60)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-b3461f60)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-b3461f60"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="68694239-b3461f60"></a>
### [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/concepts/sdks/batch-requests.md)
 - **Line 9, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** `````Multiple H1s(H1 'Have a wonderful day!') are not allowed. You can only have one top-level heading.`````

<a id="ef9c44dc-b3461f60"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?bran [...]

2020-09-30 21:09 UTC, zengin approved these changes
@Lauragra I have reverted all the changes in block and file names in this PR. The requested changes look good to me. Can you please have a second look at this? Thanks!

2020-11-03 20:45 UTC, Lauragra commented on api-reference/v1.0/api/driveitem-unfollow.md
> +POST /me/drive/items/{item-id}/unfollow
The HTTP request section in this topic shows both DELETE and POST. Which is correct?

2020-11-03 20:46 UTC, Lauragra commented on api-reference/v1.0/api/table-headerrowrange.md
> +GET https://graph.microsoft.com/v1.0/me/drive/items/{id}/workbook/tables/{id|name}/headerRowRange
The HTTP request section in this topic shows POST - which is correct?

2020-11-03 20:48 UTC, Lauragra requested changes
Please see comments on the PR.

2020-11-03 20:49 UTC, opbld30 commented
Docs Build status updates of commit _[b1cdcc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1cdcc119e42a025fd9c03d091f498346536e9c6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-d478803a)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-d478803a)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-d478803a)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-d478803a"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="ef9c44dc-d478803a"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Add attachment' is duplicated with other articles: 'v1.0/api/eventmessage-post-attachments.md(10,1), v1.0/api/event-post-attachments.md(10,1), v1.0/api/message-post-attachments.md(10,1), v1.0/api/post-post-attachments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="a8dcca08-d478803a"></a>
### [api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?br [...]

2020-11-03 21:35 UTC, zengin commented on api-reference/v1.0/api/driveitem-unfollow.md
> +POST /me/drive/items/{item-id}/unfollow
URLs that end with `/drive/items/{item-id}/unfollow` are using POST method.

URLs that end with `/drive/following/{item-id}` are using DELETE method.

2020-11-03 21:41 UTC, zengin commented on api-reference/v1.0/api/table-headerrowrange.md
> +GET https://graph.microsoft.com/v1.0/me/drive/items/{id}/workbook/tables/{id|name}/headerRowRange
Updated the HTTP request section.

2020-11-03 21:42 UTC, opbld32 commented
Docs Build status updates of commit _[0de2b1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0de2b1d2b826402e7f4e38070e281c7481861168)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-2a1c97b1-3228e134)
[api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/eventmessage-post-attachments?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-ef9c44dc-3228e134)
[api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-owners?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) | [Details](#user-content-a8dcca08-3228e134)
[api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-unfollow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/driveitem-unfollow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-unfollow?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/endpoint-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/endpoint-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/endpoint-get?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/group-list-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/table-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/table-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-headerrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-headerrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-headerrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-range?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablecolumn-totalrowrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/tablecolumn-totalrowrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-totalrowrange?view=graph-rest-1.0&branch=pr-en-us-9715) (>= graph-rest-1.0) |

<a id="2a1c97b1-3228e134"></a>
### [api-reference/v1.0/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/place-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Outlook'.`````

<a id="ef9c44dc-3228e134"></a>
### [api-reference/v1.0/api/eventmessage-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/eventmessage-post-attachments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Add attachment - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/eventmessage-post-attachments.md(2,8), v1.0/api/event-post-attachments.md(2,8), v1.0/api/message-post-attachments.md(2,8), v1.0/api/post-post-attachments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Add attachment' is duplicated with other articles: 'v1.0/api/eventmessage-post-attachments.md(10,1), v1.0/api/event-post-attachments.md(10,1), v1.0/api/message-post-attachments.md(10,1), v1.0/api/post-post-attachments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="a8dcca08-3228e134"></a>
### [api-reference/v1.0/api/serviceprincipal-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Testing/api-reference/v1.0/api/serviceprincipal-delete-owners.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?br [...]

2020-11-03 21:43 UTC, Lauragra approved these changes

2020-11-03 21:45 UTC, merged