Updated documents for policy-based app token APIs
microsoftgraph/microsoft-graph-docs pull request #9726
Opened 2020-09-01 05:28 UTC by frankpeng7

2020-09-01 05:30 UTC, opbld33 commented
Docs Build status updates of commit _[3a875fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a875fd385d82406a0b40340fe9b6c80669a644d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-f8d2224a)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-f8d2224a)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-f8d2224a)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-f8d2224a)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-f8d2224a)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-f8d2224a)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-f8d2224a)

<a id="fb5dd14f-f8d2224a"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-f8d2224a"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 108**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-f8d2224a"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-f8d2224a"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 113**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-f8d2224a"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-f8d2224a"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-03 02:48 UTC, Lauragra commented on api-reference/beta/api/application-post-onlinemeetings.md
> +> Creating an online meeting with an application token is now available. Administrator will need to create an [application access policy](../../../concepts/cloud-communication-online-meeting-applicat
Change Administrator to Administrators (plural). For the link, just use /graph/cloud-communication... without the .md file extension.

2020-09-03 02:49 UTC, Lauragra commented on api-reference/beta/api/application-post-onlinemeetings.md
> +| Authorization   | Bearer {token}.   | Yes      |
Global: Please restore the original table structure. This might be a more scannable approach but currently the tool outputs only the Description column and that is where we specify required/optional. We need to keep the docs consistent.

2020-09-03 02:52 UTC, Lauragra commented on concepts/cloud-communication-online-meeting-application-access-policy.md
> +TODO: some background?
Add the missing content.

2020-09-03 02:52 UTC, Lauragra requested changes
This update will merit an entry in the changelog as well.

2020-09-04 19:59 UTC, opbld31 commented
Docs Build status updates of commit _[8185588](https://github.com/microsoftgraph/microsoft-graph-docs/commits/818558885e3fb445cd73ea815bbc43cca5811a1c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-2140f134)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-2140f134)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-2140f134)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-2140f134)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-2140f134)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-2140f134)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-2140f134)

<a id="fb5dd14f-2140f134"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-2140f134"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 108**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-2140f134"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-2140f134"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 113**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-2140f134"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-2140f134"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-04 19:59 UTC, jsandoval-msft commented on api-reference/beta/api/application-post-onlinemeetings.md
> +> **Note:** `userId` is the object ID in AAD (TODO: more proper definition?)
what is AAD? Expand please.

2020-09-04 20:00 UTC, opbld32 commented
Docs Build status updates of commit _[ee9270d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee9270d98e62dc7b7c6cf33561a425d9ff207609)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-ad5a4acd)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-ad5a4acd)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-ad5a4acd)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-ad5a4acd)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-ad5a4acd)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-ad5a4acd)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-ad5a4acd)

<a id="fb5dd14f-ad5a4acd"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-ad5a4acd"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 108**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-ad5a4acd"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-ad5a4acd"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 113**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-ad5a4acd"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-ad5a4acd"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-09 19:21 UTC, opbld34 commented
Docs Build status updates of commit _[145d234](https://github.com/microsoftgraph/microsoft-graph-docs/commits/145d23486be002012d5c440fc3659c3dbe6573e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-bf9975b1)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-bf9975b1)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-bf9975b1)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-bf9975b1)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-bf9975b1)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-bf9975b1)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-bf9975b1)

<a id="fb5dd14f-bf9975b1"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-bf9975b1"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-bf9975b1"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-bf9975b1"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 113**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-bf9975b1"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-bf9975b1"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-09 19:23 UTC, opbld33 commented
Docs Build status updates of commit _[b9853cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9853ccd418866c38ae79b4c570f46ebbf30914c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-242c3605)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-242c3605)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-242c3605)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-242c3605)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-242c3605)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-242c3605)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-242c3605)

<a id="fb5dd14f-242c3605"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-242c3605"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-242c3605"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-242c3605"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 113**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-242c3605"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-242c3605"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-09 19:25 UTC, opbld32 commented
Docs Build status updates of commit _[e94409d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e94409ddeeeadcf5f0cbacfb6f754b7f3dc27627)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-68464db2)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-68464db2)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-68464db2)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-68464db2)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-68464db2)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-68464db2)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-68464db2)

<a id="fb5dd14f-68464db2"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-68464db2"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-68464db2"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-68464db2"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 113**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-68464db2"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-68464db2"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-09 19:31 UTC, opbld32 commented
Docs Build status updates of commit _[73f3aaf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73f3aafe90e3fa537d1304be710ca4b5ff81d73f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-4e7b2711)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-4e7b2711)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-4e7b2711)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-4e7b2711)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-4e7b2711)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-4e7b2711)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-4e7b2711)

<a id="fb5dd14f-4e7b2711"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-4e7b2711"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-4e7b2711"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-4e7b2711"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-4e7b2711"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 111**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-4e7b2711"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-09 19:35 UTC, opbld34 commented
Docs Build status updates of commit _[615e504](https://github.com/microsoftgraph/microsoft-graph-docs/commits/615e50437d66d416bff64bc8aa01a53c499d4384)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-6187f0e7)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-6187f0e7)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-6187f0e7)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-6187f0e7)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-6187f0e7)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-6187f0e7)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-6187f0e7)

<a id="fb5dd14f-6187f0e7"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-6187f0e7"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID.' is duplicated in 'beta/api/onlinemeeting-createorget.md(3,14)', 'v1.0/api/onlinemeeting-createorget.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-6187f0e7"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="81d219b4-6187f0e7"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an **online meeting** object.' is duplicated in 'beta/api/onlinemeeting-get.md(3,14)', 'v1.0/api/onlinemeeting-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3251e69-6187f0e7"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-6187f0e7"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is  [...]

2020-09-09 19:43 UTC, jsandoval-msft requested changes
Made a couple minor wording files. Please expand the acronym AAD as noted, and remove the TODO comment prior to publishing.

2020-09-09 21:23 UTC, frankpeng7 commented on api-reference/beta/api/application-post-onlinemeetings.md
> +| Authorization   | Bearer {token}.   | Yes      |
Sure will do

2020-09-09 21:49 UTC, frankpeng7 commented on concepts/cloud-communication-online-meeting-application-access-policy.md
> +TODO: some background?
@jsandoval-msft can you help with this? Refer to https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access

2020-09-09 21:52 UTC, opbld32 commented
Docs Build status updates of commit _[754c1be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/754c1bec7d00a746c1c3f4c279c5b398fd2623bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-c55b0e01)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-c55b0e01)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |

<a id="eb2f7c0b-c55b0e01"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is not a valid GitHub ID.`````
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="075040e5-c55b0e01"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 208, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 391, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 414, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 414, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 432, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permi [...]

2020-09-09 22:11 UTC, opbld30 commented
Docs Build status updates of commit _[15b1a50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15b1a502ae58497e6731038a57680ad1930b576b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-fc674fbc)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-fc674fbc)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-fc674fbc)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-fc674fbc)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-fc674fbc)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-fc674fbc)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-fc674fbc)

<a id="fb5dd14f-fc674fbc"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="98057f49-fc674fbc"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="4e311bd1-fc674fbc"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="81d219b4-fc674fbc"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="c3251e69-fc674fbc"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-fc674fbc"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is not a valid GitHub ID.`````
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="075040e5-fc674fbc"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-n [...]

2020-09-09 22:14 UTC, opbld31 commented
Docs Build status updates of commit _[7076c5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7076c5c3b16869d7c7dca6f844e08c9cec76283a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-2c37a805)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-2c37a805)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-2c37a805)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-2c37a805)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-2c37a805)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-2c37a805)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-2c37a805)

<a id="fb5dd14f-2c37a805"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="98057f49-2c37a805"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="4e311bd1-2c37a805"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="81d219b4-2c37a805"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="c3251e69-2c37a805"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-2c37a805"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'frpeng' is not a valid GitHub ID.`````
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="075040e5-2c37a805"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-n [...]

2020-09-09 22:18 UTC, opbld33 commented
Docs Build status updates of commit _[6c672f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c672f0ac4f0c80f614a8a4044ebadba915216fa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-89c5c779)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-89c5c779)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-89c5c779)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-89c5c779)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-89c5c779)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-89c5c779)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-89c5c779)

<a id="fb5dd14f-89c5c779"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="98057f49-89c5c779"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="4e311bd1-89c5c779"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="81d219b4-89c5c779"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="c3251e69-89c5c779"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-89c5c779"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="075040e5-89c5c779"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December [...]

2020-09-09 22:22 UTC, opbld34 commented
Docs Build status updates of commit _[a98d1f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a98d1f1017d3f3b0d51d8440120af575606736bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-2b6865db)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-2b6865db)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-2b6865db)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-2b6865db)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-2b6865db)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-2b6865db)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-2b6865db)

<a id="fb5dd14f-2b6865db"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="98057f49-2b6865db"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="4e311bd1-2b6865db"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="81d219b4-2b6865db"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="c3251e69-2b6865db"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-2b6865db"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="075040e5-2b6865db"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December [...]

2020-09-09 23:59 UTC, opbld34 commented
Docs Build status updates of commit _[4df5883](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4df58839e3558a1202db9f57758eefcf9eec4f13)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-aefaa228)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-aefaa228)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-aefaa228)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-aefaa228)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-aefaa228)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-aefaa228)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-aefaa228)

<a id="fb5dd14f-aefaa228"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 46, Column 180**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="98057f49-aefaa228"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 46, Column 180**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="4e311bd1-aefaa228"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="81d219b4-aefaa228"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 44, Column 172**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="c3251e69-aefaa228"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 45, Column 172**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-aefaa228"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="075040e5-aefaa228"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /gr [...]

2020-09-10 00:07 UTC, frankpeng7 commented
```
  Error: /api/onlinemeeting-delete.md:
      Relative link outside of doc set: '[../../../concepts/cloud-communication-online-meeting-application-access-policy.md](application access policy)'.

  Error: /api/onlinemeeting-delete.md:
      FileNotFound: '[/concepts/cloud-communication-online-meeting-application-access-policy.md](application access policy)'. 

  Error: /api/onlinemeeting-get.md:
      Relative link outside of doc set: '[../../../concepts/cloud-communication-online-meeting-application-access-policy.md](application access policy)'.

  Error: /api/onlinemeeting-get.md:
      Relative link outside of doc set: '[../../../concepts/cloud-communication-online-meeting-application-access-policy.md](application access policy)'.

  Error: /api/onlinemeeting-update.md:
      Relative link outside of doc set: '[../../../concepts/cloud-communication-online-meeting-application-access-policy.md](application access policy)'.

  Error: /api/onlinemeeting-update.md:
      Relative link outside of doc set: '[../../../concepts/cloud-communication-online-meeting-application-access-policy.md](application access policy)'.
```

I honestly don't know what these errors are about. @Lauragra would you be able to help identify them?

2020-09-10 02:25 UTC, opbld30 commented
Docs Build status updates of commit _[ecca7c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecca7c88e95544a1a50ea89a5b06c7d5f9dfb9ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-ab07d26f)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-98057f49-ab07d26f)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-ab07d26f)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-81d219b4-ab07d26f)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-c3251e69-ab07d26f)
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-ab07d26f)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-ab07d26f)

<a id="fb5dd14f-ab07d26f"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 30, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 46, Column 180**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="98057f49-ab07d26f"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 30, Column 101**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 46, Column 180**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="4e311bd1-ab07d26f"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="81d219b4-ab07d26f"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 31, Column 106**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 44, Column 172**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="c3251e69-ab07d26f"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 27, Column 104**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````
 - **Line 45, Column 172**: **[Warning-link-out-of-scope]** `````File '../concepts/cloud-communication-online-meeting-application-access-policy.md' referenced by link '../../../concepts/cloud-communication-online-meeting-application-access-policy.md' will not be built because it is not included in build scope.`````

<a id="eb2f7c0b-ab07d26f"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from li [...]

2020-09-10 02:43 UTC, Lauragra commented on api-reference/beta/api/application-post-onlinemeetings.md
> +> Creating an online meeting with an application token is now available. Administrators must create an [application access policy](../../../concepts/cloud-communication-online-meeting-application-acc
Remove the first sentence. This should be called out in the changelog and is apparent by the fact that we added the application permissions. Also, update the link to use this convention: /graph/could-communication-online-meeting-application-access-policy.

2020-09-10 02:50 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-createorget.md
> +description: "[Beta] Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID."
Remove this. In search results, the Beta version shows in the title. Also this description doesn't always show in the search results, depending on the algorithm.

2020-09-10 02:51 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-createorget.md
> +> Calling CreateOrGet API with an application token is now available. Administrators must create an [application access policy](../../../concepts/cloud-communication-online-meeting-application-access
Same changes here.

2020-09-10 02:54 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-createorget.md
> +POST https://graph.microsoft.com/beta/me/onlineMeetings/createOrGet
We don't use the full URLs in the HTTP request section. The introductory sentences should be "Using a delegated token:", etc.

2020-09-10 02:55 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-get.md
> +description: "[Beta] Retrieve the properties and relationships of an **online meeting** object."
Remove. Also remove the ** formatting around online meeting, or change it to the resource name, onlineMeeting.

2020-09-10 02:55 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-get.md
> +> ~~**Note:** The `GET` method is currently only supported for a [VTC conference id](https://docs.microsoft.com/microsoftteams/cloud-video-interop-for-teams-set-up). These IDs are generated for Cloud
What are these symbols here for?

2020-09-10 02:56 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-get.md
> +> - `userId` is the object ID of a user in [Azure user management portal](https://portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade). See more details in [application access policy](
Global: Property names should have bold formatting, not inline code.

2020-09-10 02:58 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-delete.md
> +> Deleting an online meeting with an application token is now available. Administrators must create an [application access policy](../../../concepts/cloud-communication-online-meeting-application-acc
Update this.

2020-09-10 02:59 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-get.md
> +> **Note:**
Make this plural, Notes.

2020-09-10 02:59 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-get.md
> +> - `meetingId` is the `id` of an [onlineMeeting entity](../resources/onlinemeeting.md)
Add the missing period.

2020-09-10 02:59 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-update.md
> +description: "[Beta] Update the properties of an online meeting."
Remove Beta.

2020-09-10 03:00 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-update.md
> +> **Note:**
Make plural, add missing period, update formatting.

2020-09-10 04:43 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-createorget.md
> +description: "[Beta] Create an online meeting with a custom specified external ID. If the external ID already exists, this API will return the **onlineMeeting** object with that external ID."
was trying to get rid of auto check warnings...sure I'll remove this.

2020-09-10 04:53 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +> - `userId` is the object ID of a user in [Azure user management portal](https://portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade). See more details in [application access policy](
Are you suggesting change all `userId` `meetingId` from inline code to bold, or just the `id` in L#45? As I think only that one is a property

2020-09-10 04:55 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-update.md
> +> Updating an online meeting with an application token is now available. Administrators must create an [application access policy](../../../concepts/cloud-communication-online-meeting-application-acc
Same question as above so keeping this comment there.

2020-09-10 05:04 UTC, opbld32 commented
Docs Build status updates of commit _[a5e3d48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5e3d48e65da445769e1650256dbb08cd3d6610f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-8ecbb5a1)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-8ecbb5a1)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-8ecbb5a1)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-8ecbb5a1)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |

<a id="eb2f7c0b-8ecbb5a1"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 11, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 26, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="fb5dd14f-8ecbb5a1"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-8ecbb5a1"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="075040e5-8ecbb5a1"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 208, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-li [...]

2020-09-10 21:09 UTC, opbld33 commented
Docs Build status updates of commit _[e1104e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1104e6c355b513cf70a8d6b385766cbb37dbb4d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) | [Details](#user-content-eb2f7c0b-7e456f2c)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-7e456f2c)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-7e456f2c)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-7e456f2c)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |

<a id="eb2f7c0b-7e456f2c"></a>
### [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md)
 - **Line 11, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="fb5dd14f-7e456f2c"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-7e456f2c"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="075040e5-7e456f2c"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 208, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 391, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-ca [...]

2020-09-11 05:23 UTC, jsandoval-msft approved these changes

2020-09-11 05:24 UTC, opbld30 commented
Docs Build status updates of commit _[a1fef66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1fef662c8b42a33aff5ebe63c0d5916968596b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-85021662)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-85021662)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-85021662)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-85021662"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-85021662"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="075040e5-85021662"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 208, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 391, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 429, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 483, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channe [...]

2020-09-11 22:45 UTC, opbld30 commented
Docs Build status updates of commit _[5888167](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5888167f7492bc376026fe499a14eeeb744a85f1)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-11 22:47 UTC, opbld31 commented
Docs Build status updates of commit _[5888167](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5888167f7492bc376026fe499a14eeeb744a85f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-61285072)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-61285072)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-61285072)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-61285072"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-61285072"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="075040e5-61285072"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 205, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 206, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 208, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 237, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 391, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 429, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 483, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 627, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 627, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 627, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 629, Column 0**: **[Suggestion-preserve-view-not-set]* [...]

2020-09-11 22:51 UTC, opbld30 commented
Docs Build status updates of commit _[7980a04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7980a040c529ee7692142f50a06882c69cd47e48)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-11 22:53 UTC, frankpeng7 commented
Hi @Lauragra I updated the changelog but please do not review this yet as some external links in the documents is not ready yet.

2020-09-11 22:53 UTC, opbld31 commented
Docs Build status updates of commit _[7980a04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7980a040c529ee7692142f50a06882c69cd47e48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-80f620fd)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-80f620fd)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-80f620fd)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-80f620fd)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-80f620fd"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-80f620fd"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-80f620fd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-14 22:19 UTC, frankpeng7 commented
External links are available now. Removed `do not merge` tag.

2020-09-15 00:58 UTC, opbld33 commented
Docs Build status updates of commit _[11d40ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11d40ba77908e415a479e769af18f1e289a599bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-75d2f1d5)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-75d2f1d5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-75d2f1d5)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-75d2f1d5)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-75d2f1d5"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-75d2f1d5"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-75d2f1d5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:00 UTC, opbld33 commented
Docs Build status updates of commit _[0aab3e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0aab3e3bf354f53e124daa180a8e57ece2085ef6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-07a64a81)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-07a64a81)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-07a64a81)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-07a64a81)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-07a64a81"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-07a64a81"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-07a64a81"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:01 UTC, opbld32 commented
Docs Build status updates of commit _[713d260](https://github.com/microsoftgraph/microsoft-graph-docs/commits/713d260ffe33b9641f109335918e202cfc9ebc40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-2f79978c)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-2f79978c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-2f79978c)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-2f79978c)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-2f79978c"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-2f79978c"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-2f79978c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:03 UTC, opbld31 commented
Docs Build status updates of commit _[116250d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/116250d3b05df4ef9c3b5b41d4fe90d45fe58787)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-3170e43a)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-3170e43a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-3170e43a)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-3170e43a)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-3170e43a"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-3170e43a"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-3170e43a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:04 UTC, opbld30 commented
Docs Build status updates of commit _[7bafa47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bafa47c6d8e9b7339678f76282c260ea82c858e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-23e4d1c3)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-23e4d1c3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-23e4d1c3)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-23e4d1c3)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-23e4d1c3"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-23e4d1c3"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-23e4d1c3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:23 UTC, opbld34 commented
Docs Build status updates of commit _[552fe35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/552fe352650dfbbede881b67102ae2698ce4e0b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-1b8cba68)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-1b8cba68)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-1b8cba68)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-1b8cba68)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-1b8cba68"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-1b8cba68"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-1b8cba68"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:26 UTC, opbld34 commented
Docs Build status updates of commit _[2faf799](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2faf7991e3553513b7e55ad80f5a7604e68bb6ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-0fa51939)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-0fa51939)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-0fa51939)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-0fa51939)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-0fa51939"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-0fa51939"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-0fa51939"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:37 UTC, opbld31 commented
Docs Build status updates of commit _[2a03646](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a0364663687b814b64471d529d877312378ec64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-5ad93730)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-5ad93730)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-5ad93730)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-5ad93730)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-5ad93730"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-5ad93730"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-5ad93730"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:41 UTC, opbld30 commented
Docs Build status updates of commit _[264095e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/264095e52acd80d285c8fae74820f05710c6e9ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-b010699b)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-b010699b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-b010699b)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-b010699b)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-b010699b"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-b010699b"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-b010699b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:42 UTC, opbld34 commented
Docs Build status updates of commit _[99acf35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99acf353968c2fd771b2f92809e7d59267cc9ac2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-f3ce8ba5)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-f3ce8ba5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-f3ce8ba5)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-f3ce8ba5)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-f3ce8ba5"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-f3ce8ba5"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-f3ce8ba5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 01:43 UTC, Lauragra approved these changes

2020-09-15 01:43 UTC, opbld31 commented
Docs Build status updates of commit _[f7acb5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7acb5b0fa55d03e4efa8d02cfec9f7d47326cb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-75114834)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-75114834)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-75114834)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-75114834)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-75114834"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-75114834"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-75114834"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 02:00 UTC, opbld31 commented
Docs Build status updates of commit _[afab6f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afab6f2ae0fada774789310a46d654d781d92f83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-ae9f4d7e)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-ae9f4d7e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-ae9f4d7e)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-ae9f4d7e)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-ae9f4d7e"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-ae9f4d7e"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-ae9f4d7e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 02:09 UTC, opbld33 commented
Docs Build status updates of commit _[da35a1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da35a1ebe6032477296ed2a5d91ed6f447a31096)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-bb9e05a5)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-bb9e05a5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-bb9e05a5)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-bb9e05a5)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-bb9e05a5"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-bb9e05a5"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-bb9e05a5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 02:13 UTC, opbld31 commented
Docs Build status updates of commit _[ca1ad51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca1ad5133e7d67baa9ab10a4d4617e33d92466a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-0c4a94b8)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-0c4a94b8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-0c4a94b8)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-0c4a94b8)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-0c4a94b8"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-0c4a94b8"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-0c4a94b8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 02:15 UTC, opbld34 commented
Docs Build status updates of commit _[1a59369](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a5936947a669d83a6576972a854e8da2a28efec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-d6d3654e)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-d6d3654e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-d6d3654e)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-d6d3654e)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-d6d3654e"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-d6d3654e"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-d6d3654e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 02:15 UTC, Lauragra commented on concepts/cloud-communication-online-meeting-application-access-policy.md
> +# Allow applications to access online meetings on behalf of a user
This file needs to be surfaced in the TOC. I assume that you want to include it in this node? https://review.docs.microsoft.com/en-us/graph/cloud-communications-concept-overview?view=graph-rest-beta&branch=pr-en-us-9726

2020-09-15 02:16 UTC, opbld31 commented
Docs Build status updates of commit _[c3a450d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3a450d180ea642ca70193bf5dad43c1045d205a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-ec9817fa)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-ec9817fa)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-ec9817fa)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-ec9817fa)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-ec9817fa"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-ec9817fa"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-ec9817fa"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 02:22 UTC, opbld33 commented
Docs Build status updates of commit _[7241124](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7241124feb5ebba939ffe08abea9b86608d7ccca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-96317618)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-96317618)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-96317618)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-96317618)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |

<a id="fb5dd14f-96317618"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-96317618"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-96317618"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-09-15 17:40 UTC, opbld31 commented
Docs Build status updates of commit _[165e293](https://github.com/microsoftgraph/microsoft-graph-docs/commits/165e293377e3b4b025c1f11465d7b18c74bd65ea)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-15 17:43 UTC, opbld34 commented
Docs Build status updates of commit _[165e293](https://github.com/microsoftgraph/microsoft-graph-docs/commits/165e293377e3b4b025c1f11465d7b18c74bd65ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-6171ef89)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-6171ef89)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-6171ef89)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-6171ef89)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) |

<a id="fb5dd14f-6171ef89"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-6171ef89"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-6171ef89"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resour [...]

2020-09-15 18:25 UTC, Lauragra approved these changes

2020-09-15 18:25 UTC, opbld33 commented
Docs Build status updates of commit _[5c23b11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c23b11df0943c846512416091260c6239ebdee4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-66e63954)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-66e63954)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-66e63954)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-66e63954)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) |

<a id="fb5dd14f-66e63954"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-66e63954"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-66e63954"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resour [...]

2020-09-15 18:27 UTC, opbld31 commented
Docs Build status updates of commit _[c80962b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c80962b03459e0b7308890a8c5b551cf7f46ee37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-fb5dd14f-28ce804c)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) | [Details](#user-content-4e311bd1-28ce804c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) | [Details](#user-content-de0bbbbb-28ce804c)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9726) | [Details](#user-content-075040e5-28ce804c)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-9726) (graph-rest-beta) |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-9726) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9726) |

<a id="fb5dd14f-28ce804c"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create an online meeting on behalf of a user specified in the request body.' is duplicated in 'beta/api/application-post-onlinemeetings.md(3,14)', 'v1.0/api/application-post-onlinemeetings.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4e311bd1-28ce804c"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete an online meeting.' is duplicated in 'beta/api/onlinemeeting-delete.md(3,14)', 'v1.0/api/onlinemeeting-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-28ce804c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/app-access-policy/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resour [...]

2020-09-15 18:29 UTC, merged