Added Documentation for hideAttendees in Beta
microsoftgraph/microsoft-graph-docs pull request #9727
Opened 2020-09-01 05:59 UTC by Bhupesh12Hub

@angelgolfer-ms 
Please review the PR for Documentation of hideAttendees in Beta.

Thanks

2020-09-01 06:01 UTC, opbld33 commented
Docs Build status updates of commit _[57b1058](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57b10580154651e0345c2814a026da4cc9f69090)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) | [Details](#user-content-95a9f530-4ab6d62d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) |

<a id="95a9f530-4ab6d62d"></a>
### [api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'An event in a calendar.' is duplicated in 'beta/resources/event.md(3,14)', 'v1.0/resources/event.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009010559556633-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d3BIHUBYKNFOwrDzT1S1NaCPHukHQs%2BS6YiMGsrXxag%3D&st=2020-09-01T05%3A56%3A19Z&se=2020-10-02T06%3A01%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-01 17:05 UTC, opbld32 commented
Docs Build status updates of commit _[8cfe5c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cfe5c0182608c821411c79fed61c8c685642cf4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) | [Details](#user-content-95a9f530-40f5148e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) |

<a id="95a9f530-40f5148e"></a>
### [api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'An event in a calendar.' is duplicated in 'beta/resources/event.md(3,14)', 'v1.0/resources/event.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009011703363473-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Vt61XtupGw%2BR2Aa9CTR3AQurQml4mgtwNesnrxIwyHk%3D&st=2020-09-01T17%3A00%3A08Z&se=2020-10-02T17%3A05%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-01 18:12 UTC, opbld30 commented
Docs Build status updates of commit _[5f85172](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f85172420e1250d8b9039ff75f9e2d719a1377c)_: 

:clock10: **Pending**: waiting for processors ([37](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 37 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-01 18:15 UTC, opbld34 commented
Docs Build status updates of commit _[5f85172](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f85172420e1250d8b9039ff75f9e2d719a1377c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) | [Details](#user-content-443f7feb-38c087f2)
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) | [Details](#user-content-4b1c4123-38c087f2)
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) | [Details](#user-content-f65ed406-38c087f2)
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) | [Details](#user-content-95a9f530-38c087f2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) |

<a id="443f7feb-38c087f2"></a>
### [api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Use this API to create a new event in the default or the specified calendar.' is duplicated in 'beta/api/calendar-post-events.md(3,14)', 'v1.0/api/calendar-post-events.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="4b1c4123-38c087f2"></a>
### [api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Get the properties and relationships of the specified event object.' is duplicated in 'beta/api/event-get.md(3,14)', 'v1.0/api/event-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="f65ed406-38c087f2"></a>
### [api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Update the properties of the event object.' is duplicated in 'beta/api/event-update.md(3,14)', 'v1.0/api/event-update.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="95a9f530-38c087f2"></a>
### [api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'An event in a calendar.' is duplicated in 'beta/resources/event.md(3,14)', 'v1.0/resources/event.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009011812261759-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iRaTFBbDO37qZA72Eksua8%2BcS%2FNquFCCih7uC9e6C9g%3D&st=2020-09-01T18%3A10%3A02Z&se=2020-10-02T18%3A15%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 18:11 UTC, opbld34 commented
Docs Build status updates of commit _[5f85172](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f85172420e1250d8b9039ff75f9e2d719a1377c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-abef9fae)

<a id="abef9fae"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011171810595735-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5vRgUsE0faYHdtoEFzOhZaATt3J5pdPxD8Jl%2Fzq7Jko%3D&st=2020-11-17T18%3A06%3A14Z&se=2020-12-18T18%3A11%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 18:15 UTC, opbld32 commented
Docs Build status updates of commit _[16b81ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16b81ad388cdfdaed89e4dd9bf9d0e8b4240bb8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) | [Details](#user-content-de0bbbbb-58f6d878)
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-58f6d878"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011171814318390-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EUwrR3LQAm6q5PPNcw%2B6HAWJntHJID1x7T1LL5jlpKs%3D&st=2020-11-17T18%3A10%3A51Z&se=2020-12-18T18%3A15%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 09:34 UTC, angelgolfer-ms commented on api-reference/beta/api/event-get.md
> +    "hideAttendees": false,
Please update the example request for this example as well to include the hideAttendees property in the $select query parameter.

2020-11-18 09:37 UTC, angelgolfer-ms commented on api-reference/beta/api/event-update.md
> +>**Note:** Note: The response object shown here may be truncated for brevity.
Lines 139 and 141:
Please put the 2 sentences on the same line, as in the original paragraph. Please also remove the extra ">**Note**".
You can leave out the third sentence please.

2020-11-18 09:40 UTC, angelgolfer-ms commented on api-reference/beta/resources/event.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
Line 120:
In the description, perhaps you can add "Default is `true`.", if that's the case?

2020-11-18 09:42 UTC, angelgolfer-ms commented on api-reference/beta/api/event-update.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
Line 63:
In the description, perhaps you can add "Default is `true`.", if that's the case?

2020-11-18 09:45 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub , @grjsrinivas , the comments I have for this PR are almost the same as PR 10693. 
Please take a look and incorporate. Since these are two separate PRs, anticipate a merge conflict in the changelog file, as both attempt to update the similar area in that file.
Thanks.

2020-11-18 11:17 UTC, grjsrinivas commented on api-reference/beta/resources/event.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
The default value is false which will be similar to the existing behaviour.

2020-11-18 11:19 UTC, grjsrinivas commented on api-reference/beta/api/event-update.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
The default is false which will be similar to the existing behaviour.

2020-11-18 11:30 UTC, grjsrinivas commented on api-reference/beta/api/event-update.md
> +>**Note:** Note: The response object shown here may be truncated for brevity.
Done.

2020-11-18 11:30 UTC, grjsrinivas commented on api-reference/beta/api/event-get.md
> +    "hideAttendees": false,
Thanks for pointing out. Have corrected it.

2020-11-18 11:31 UTC, opbld33 commented
Docs Build status updates of commit _[708199d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/708199d08c9e08b6484fb2ccdf95f0c8c53ca1e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) | [Details](#user-content-de0bbbbb-d2af517a)
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d2af517a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingdefinition?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectioninstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettinginstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingvalue?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationdependenton?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationgroupsettingcollectioninstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationgroupsettinginstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconf [...]

2020-11-18 11:43 UTC, opbld31 commented
Docs Build status updates of commit _[7217aff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7217aff5514bf8881b3b114935ffd97d91308f21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) | [Details](#user-content-de0bbbbb-a068ded2)
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a068ded2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingdefinition?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectioninstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettinginstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingvalue?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationdependenton?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationgroupsettingcollectioninstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationgroupsettinginstance?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconf [...]

2020-12-03 08:28 UTC, angelgolfer-ms commented on api-reference/beta/api/event-update.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
Ok, like in PR 10693 for v1, FYI I added the default is false. I think that would be helpful for customers.

2020-12-03 08:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/event.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
FYI I added the default is false. I think that would be helpful for customers.

2020-12-03 08:30 UTC, angelgolfer-ms commented on api-reference/beta/api/event-get.md
> +    "hideAttendees": false,
Hm, @grjsrinivas , I don't see the the example request for the first example including hideAttendees in the $select query parameter. FYI I just added it directly to your PR.

2020-12-03 08:31 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +      "CreatedDateTime": "2020-10-09T00:00:00",
Line 17: 
Please update the date to be some date in December, otherwise this would be confusing to customers in both the changelog and what's new topic.

2020-12-03 08:31 UTC, angelgolfer-ms commented on concepts/changelog.md
> +### Calendar
Please move this to under the "December 2020" section.

2020-12-03 08:35 UTC, opbld32 commented
Docs Build status updates of commit _[9b42bdf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b42bdf8a2897b5286e6ec5bfe84cefbeeb1a57c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) | [Details](#user-content-de0bbbbb-1d9cea5f)
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-1d9cea5f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012030833023784-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uF3KPJgjKRpfIdFWOzN6T0Yf1VuBml5hUoyGlp0SOzM%3D&st=2020-12-03T08%3A29%3A59Z&se=2021-01-03T08%3A34%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 08:36 UTC, angelgolfer-ms requested changes
@grjsrinivas , FYI to cut down the back and forth, I applied a couple of fixes directly to this PR. Please take a look at my remaining comments about setting the date for the changelog json and changelog md to December.
After you fix them, this PR should be good for publishing.

2020-12-03 08:36 UTC, opbld34 commented
Docs Build status updates of commit _[2eba7b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eba7b0127ee2170aa4992b7b979151f7f39ef46)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) | [Details](#user-content-de0bbbbb-8a713b9b)
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8a713b9b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012030833391937-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iNsKEOqVRAIhhVyZW7hNd0MAWR1fGoytZRzNkQrl1w4%3D&st=2020-12-03T08%3A31%3A56Z&se=2021-01-03T08%3A36%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 05:13 UTC, opbld30 commented
Docs Build status updates of commit _[06d05fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06d05feeef506cdde8da87e2660caea39b6d641d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) | [Details](#user-content-de0bbbbb-78835500)
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-78835500"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 139, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 139, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170512098687-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0%2B%2F9wKZAIgS7k7Ce7bDlbYx8BAXKmFOjbJ1e9BZI5PE%3D&st=2020-12-17T05%3A08%3A22Z&se=2021-01-17T05%3A13%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 05:24 UTC, opbld32 commented
Docs Build status updates of commit _[f714979](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f714979e9b0dc8b0e048ad2985d56a182c8bbc31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) | [Details](#user-content-de0bbbbb-24140c0d)
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-24140c0d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md)
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 85, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 151, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 151, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 152, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 152, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170523041091-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BJE7y6P7JS646jQcNQZBXpq3wWHpoE39%2Fbcd%2BHWwZK0%3D&st=2020-12-17T05%3A19%3A23Z&se=2021-01-17T05%3A24%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 05:26 UTC, Bhupesh12Hub commented on changelog/Microsoft.Exchange.json
> +      "CreatedDateTime": "2020-10-09T00:00:00",
Done.

2020-12-17 05:26 UTC, Bhupesh12Hub commented on concepts/changelog.md
> +### Calendar
Done.

2020-12-17 05:28 UTC, Bhupesh12Hub commented
@angelgolfer-ms, i have incorporated the all feedback comments.
This PR is good to publish.
@Lauragra @Harini84

2020-12-18 05:08 UTC, Harini84 commented
> @angelgolfer-ms, i have incorporated the all feedback comments.
> This PR is good to publish.
> @Lauragra @Harini84

@Bhupesh12Hub 
Please re-request for review and set the label to 'readytomerge'.

![image](https://user-images.githubusercontent.com/59600764/102577024-2412c900-411d-11eb-8373-bf7c41bdfc8f.png)

2020-12-18 08:37 UTC, opbld34 commented
Docs Build status updates of commit _[195b2c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/195b2c01f5875076608be13353824007e5f2b9f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/calendar-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/event-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9727) (graph-rest-beta) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/beta/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9727) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012180835582352-9727%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NkshHE9fBQB3Yi5ciEN8w0sdLLhY3FDWhVXfp%2FCC3Rg%3D&st=2020-12-18T08%3A32%3A16Z&se=2021-01-18T08%3A37%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-18 08:41 UTC, merged

2020-12-18 08:41 UTC, angelgolfer-ms reviewed
PR looks good now, just merged it to master.