User flow attributes doc creation
microsoftgraph/microsoft-graph-docs pull request #9748
Opened 2020-09-01 23:31 UTC by jkdouglas

Docs for the userFlowAttributes API

2020-09-01 23:32 UTC, opbld30 commented
Docs Build status updates of commit _[78dcf46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78dcf46d1250487da18c6a3d660a4bf6947412b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattribute-post-userflowattributes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-57eed3d6-33230a27)
[api-reference/beta/api/userflowattributes-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-ffb6d4b1-33230a27)
[api-reference/beta/api/userflowattributes-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-0a260e9a-33230a27)
[api-reference/beta/api/userflowattributes-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-eb75b22a-33230a27)
[api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-159c84a3-33230a27)
[api-reference/beta/resources/userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/userflowattributes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-d9cef199-33230a27)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="57eed3d6-33230a27"></a>
### [api-reference/beta/api/userflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattribute-post-userflowattributes.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````

<a id="ffb6d4b1-33230a27"></a>
### [api-reference/beta/api/userflowattributes-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-delete.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'Delete identityProvider' is duplicated with other articles: 'beta/api/userflowattributes-delete.md(10,1), v1.0/api/identityprovider-delete.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="0a260e9a-33230a27"></a>
### [api-reference/beta/api/userflowattributes-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-get.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````

<a id="eb75b22a-33230a27"></a>
### [api-reference/beta/api/userflowattributes-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-list.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````

<a id="159c84a3-33230a27"></a>
### [api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````

<a id="d9cef199-33230a27"></a>
### [api-reference/beta/resources/userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/userflowattributes.md)
 - **Line 7, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009012331326244-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0vipOOz25zfhnWzkiA1oIBXpaOWGJIEFMBSSjETgwyc%3D&st=2020-09-01T23%3A27%3A46Z&se=2020-10-02T23%3A32%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instruction [...]

2020-09-02 00:13 UTC, opbld30 commented
Docs Build status updates of commit _[6023a5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6023a5d4acecb259b5409901f0fe17d2e8b0e493)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-159c84a3-db9a3a0d)
[api-reference/beta/api/userflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattribute-post-userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="159c84a3-db9a3a0d"></a>
### [api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009020012033039-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3rys2Nwi1U26YZJykijG4nP5BgWyW0zrpA6yGDUtfRw%3D&st=2020-09-02T00%3A08%3A46Z&se=2020-10-03T00%3A13%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-02 15:43 UTC, agrabhi commented on api-reference/beta/api/userflowattribute-post-userflowattributes.md
> +|displayName|String|The display name of the user flow attribute.|
id and userFlowAttributeType is missing

2020-09-02 15:44 UTC, agrabhi commented on api-reference/beta/api/userflowattribute-post-userflowattributes.md
> +|displayName|String|The display name of the user flow attribute.|
will help to run the sample request, response given here against prod

2020-09-02 15:44 UTC, agrabhi commented on api-reference/beta/api/userflowattribute-post-userflowattributes.md
> +|displayName|String|The display name of the user flow attribute.|
Location header?

2020-09-02 15:45 UTC, agrabhi commented on api-reference/beta/api/userflowattributes-delete.md
> +Delete a [userFlowAttribute](../resources/userflowattributes.md).
we must mention that only user created (custom attributes) can be deleted.

2020-09-02 15:47 UTC, agrabhi commented on api-reference/beta/api/userflowattributes-get.md
> +{
in all the examples @odata.type field is missing - should that be added?

2020-09-02 15:49 UTC, agrabhi commented on api-reference/beta/api/userflowattributes-update.md
> +Update the properties of a [userFlowAttribute](../resources/userflowattributes.md) object.
we should mention only custom attributes can be updated

2020-09-02 15:50 UTC, agrabhi commented on api-reference/beta/resources/userflowattributes.md
> +Configuring user flow attributes in your Azure Active Directory or Azure AD B2C tenant allows you collect information about a user during sign up. There is a built-in set of attributes that you can c
we should link with `Azure Active Directory schema extensions`  documentation

2020-09-02 15:51 UTC, agrabhi commented on api-reference/beta/resources/userflowattributes.md
> +
we can mention here as well in 'emphasis' that only custom attributes can be modified.

2020-09-03 03:26 UTC, jkdouglas commented on api-reference/beta/api/userflowattribute-post-userflowattributes.md
> +|displayName|String|The display name of the user flow attribute.|
Fixed

2020-09-03 03:26 UTC, jkdouglas commented on api-reference/beta/api/userflowattributes-delete.md
> +Delete a [userFlowAttribute](../resources/userflowattributes.md).
Added this note

2020-09-03 03:28 UTC, jkdouglas commented on api-reference/beta/api/userflowattributes-get.md
> +{
@odata.type is not returned in the API calls when testing them.

2020-09-03 03:28 UTC, jkdouglas commented on api-reference/beta/api/userflowattributes-update.md
> +Update the properties of a [userFlowAttribute](../resources/userflowattributes.md) object.
Added this note.

2020-09-03 03:29 UTC, jkdouglas commented on api-reference/beta/resources/userflowattributes.md
> +
Added emphasis on the `custom user flow attribute` string.

2020-09-03 03:30 UTC, jkdouglas commented on api-reference/beta/resources/userflowattributes.md
> +Configuring user flow attributes in your Azure Active Directory or Azure AD B2C tenant allows you collect information about a user during sign up. There is a built-in set of attributes that you can c
Added link to this doc: https://docs.microsoft.com/azure/active-directory/develop/active-directory-schema-extensions

2020-09-03 03:32 UTC, opbld30 commented
Docs Build status updates of commit _[09537fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09537fed2b366c983d607dd8371a2003980286b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-159c84a3-cfed5b4d)
[api-reference/beta/api/userflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattribute-post-userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="159c84a3-cfed5b4d"></a>
### [api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'jodougla' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009030331184723-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iPWo8og6ojz4cMuk%2F4W07N%2F2FD5l9TY7DbEqAp5y8UU%3D&st=2020-09-03T03%3A27%3A45Z&se=2020-10-04T03%3A32%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-03 03:36 UTC, opbld30 commented
Docs Build status updates of commit _[5807eb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5807eb3948d516f06120fda17d35b3edbc85275d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattribute-post-userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009030335041233-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZqXrebyxaIvHgikSMK9LRnUwf308Pkm7DZa%2BFll0lU4%3D&st=2020-09-03T03%3A31%3A19Z&se=2020-10-04T03%3A36%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 18:46 UTC, John-YOU commented on api-reference/beta/api/userflowattribute-post-userflowattributes.md
> +    "dataType": "String"
'String' should be 'string'

2020-09-15 18:47 UTC, John-YOU commented on api-reference/beta/api/userflowattributes-list.md
> +          "dataType": "String"
Same here, 'String' should be all lowercase

2020-09-15 18:47 UTC, John-YOU commented on api-reference/beta/resources/userflowattributes.md
> +    "dataType": "String"
Same here

2020-09-15 18:56 UTC, John-YOU commented on api-reference/beta/api/userflowattributes-get.md
> +{
During the implementation, I have difficulty adding it, so we didn't have the @odata.type returned in the API per previous discussion. Do you guys want me to have a fix to add it?

2020-09-15 20:02 UTC, opbld34 commented
Docs Build status updates of commit _[3069b53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3069b53799bff29c6a31b91830c5adfdcb90af47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattribute-post-userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/userflowattributes-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/userflowattributes-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattributes-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152001364656-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oAaiAtadOzmLXgNrm5jX4bd3r%2BT%2BW7DqyhIfbIDcYJ0%3D&st=2020-09-15T19%3A57%3A53Z&se=2020-10-16T20%3A02%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 22:54 UTC, opbld32 commented
Docs Build status updates of commit _[b4e31de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4e31defded7d9f3801e18f887ca3ad08282b89a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-post-userflowattributes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-b745d3b1-83e93bef)
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="b745d3b1-83e93bef"></a>
### [api-reference/beta/api/identityuserflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-post-userflowattributes.md)
 - **Line 62, Column 70**: **[Warning-file-not-found]** `````Invalid file link: '../resources/userflowattributes.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152252559594-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jR64KVn9oSXYx0qDMx4ijv2oXICdf2LjGmt6xUgNASs%3D&st=2020-09-15T22%3A49%3A14Z&se=2020-10-16T22%3A54%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 22:56 UTC, opbld34 commented
Docs Build status updates of commit _[51ae9cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51ae9cb08b445d391b000c86cffb1b13f12ec2c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-post-userflowattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-post-userflowattributes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-post-userflowattributes?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152255244535-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UJvUlHJcta5BWbTFRscIB%2FzfJJAT6PvYJ8qFjWI1Aog%3D&st=2020-09-15T22%3A51%3A44Z&se=2020-10-16T22%3A56%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 18:51 UTC, opbld30 commented
Docs Build status updates of commit _[131a8fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/131a8fb222c41c7f598625d840a8b378e9926ef6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-02c461bf)

<a id="02c461bf"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171851096247-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B7XHCRz82INWcGaiUTPkD5QemiREuE2i70pkAdwYvJI%3D&st=2020-09-17T18%3A46%3A36Z&se=2020-10-18T18%3A51%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 18:53 UTC, opbld34 commented
Docs Build status updates of commit _[8f02aab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f02aab516d4ef0c704ce8655c9cabee38f27401)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-7a1003a0-b0c7604d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-00685cff-b0c7604d)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="7a1003a0-b0c7604d"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

<a id="00685cff-b0c7604d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml)
 - **Line 10309, Column 22**: **[Warning-file-not-found]** `````Invalid file link: 'api/identityuserflowattribute-post-userflowattributes.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171852376372-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zKVz07ume%2FkMibS04ApNdwQ7PqGRw61qFyIa0TFY44M%3D&st=2020-09-17T18%3A48%3A56Z&se=2020-10-18T18%3A53%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 19:00 UTC, opbld30 commented
Docs Build status updates of commit _[6913956](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6913956b58a806444667aa027a4c3771cc9078e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-7a1003a0-9a8aef55)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="7a1003a0-9a8aef55"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md)
 - **Line 22, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=master)]** 
`````
Multiple H1s(H1 '| Member
|:--------------
| operatingSystemVolume
| fixedDataVolume
| removableDataVolume
| unknownFutureValue') are not allowed. You can only have one top-level heading.
`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171859272128-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2QPasJhabcM09GGgRqy3VfkzKtAof4s7fHHJJEtLUvU%3D&st=2020-09-17T18%3A55%3A42Z&se=2020-10-18T19%3A00%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 19:32 UTC, jkdouglas commented on api-reference/beta/resources/userflowattributes.md
> +    "dataType": "String"
This is how the doc generator tool generates these and we need to follow that standard.

2020-09-17 19:32 UTC, jkdouglas commented on api-reference/beta/api/userflowattributes-list.md
> +          "dataType": "String"
Docs standards have these as documented above and we need to follow that.

2020-09-17 19:33 UTC, jkdouglas commented on api-reference/beta/api/userflowattribute-post-userflowattributes.md
> +    "dataType": "String"
Doc standards document it as 'String' and we need to follow that

2020-09-28 22:39 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-create.md
> +|description|String|Required. The description of the user flow attribute. It is shown to the user at the time of sign up.|
```suggestion
|description|String|Required. The description of the user flow attribute. It is shown to the user at the time of sign-up.|
```

2020-09-28 22:40 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-create.md
> +Content-length: 154
Content-length isn't needed.

2020-09-28 22:41 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-create.md
> +  "dataType": "string",
This should be one of the values listed in the definition for the property.

2020-09-28 22:42 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-create.md
> +    "dataType": "String"
Should this be "string"? The definition shows it as lowercase 's'.

2020-09-28 22:43 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-create.md
> +|Delegated (work or school account)|IdentityUserFlow.ReadWrite.All|
Please make sure this permission is listed in the permissions-reference page.

2020-09-28 22:44 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-get.md
> +|Delegated (work or school account)|IdentityUserFlow.Read.All, IdentityUserFlow.ReadWrite.All|
Please make sure these permissions are documented in the permissions-reference page.

2020-09-28 22:45 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-get.md
> +    "dataType": "String"
lowercase?

2020-09-28 22:46 UTC, davidmu1 commented on api-reference/beta/api/identityuserflowattribute-update.md
> +Content-length: 41
Content-length isn't needed here.

2020-09-28 22:48 UTC, davidmu1 commented on api-reference/beta/resources/enums.md
> +### identityUserFlowAttributeDataType values
Although it has been done in a few cases, values and descriptions shouldn't be defined in the enums.md file.

2020-09-28 22:49 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +Represents user flow attributes in an Azure Active Directory tenant and an Azure AD B2C tenant.
```suggestion
Represents user flow attributes in an Azure Active Directory (Azure AD) tenant and an Azure AD B2C tenant.
```

2020-09-28 22:51 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +Configuring user flow attributes in your Azure Active Directory or Azure AD B2C tenant allows you collect information about a user during sign up. There is a built-in set of attributes that you can c
```suggestion
Configuring user flow attributes in your Azure AD or Azure AD B2C tenant allows you to collect information about a user during sign-up. There is a built-in set of attributes that you can choose to collect. For example, Given Name, Surname, City, and Postal Code. You can also configure custom user flow attributes to collect information from a user that is not built in to the directory. Custom user flow attributes are an abstraction over [Azure Active Directory schema extensions](https://docs.microsoft.com/azure/active-directory/develop/active-directory-schema-extensions).
```

2020-09-28 22:52 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +|[List](../api/identityuserflowattribute-list.md)|identityUserFlowAttributes collection|Retrieve all built in and custom user flow attributes.|
```suggestion
|[List](../api/identityuserflowattribute-list.md)|identityUserFlowAttributes collection|Retrieve all built-in and custom user flow attributes.|
```

2020-09-28 22:52 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +|[Create](../api/identityuserflowattribute-create.md)|identityUserFlowAttribute|Create a new `custom user flow attribute`.|
```suggestion
|[Create](../api/identityuserflowattribute-create.md)|identityUserFlowAttribute|Create a new custom user flow attribute.|
```

2020-09-28 22:53 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +|[Update](../api/identityuserflowattribute-update.md)|None|Update a `custom user flow attribute`.|
```suggestion
|[Update](../api/identityuserflowattribute-update.md)|None|Update a custom user flow attribute.|
```

2020-09-28 22:53 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +|[Delete](../api/identityuserflowattribute-delete.md)|None|Delete a `custom user flow attribute`.|
```suggestion
|[Delete](../api/identityuserflowattribute-delete.md)|None|Delete a custom user flow attribute.|
```

2020-09-28 22:53 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +|id|String|The ID of the user flow attribute. This is a read-only attribute that is automatically created.|
```suggestion
|id|String|The identifier of the user flow attribute. This is a read-only attribute that is automatically created.|
```

2020-09-28 22:53 UTC, davidmu1 commented on api-reference/beta/resources/identityuserflowattribute.md
> +|description|String|The description of the user flow attribute. It is shown to the user at the time of sign up.|
```suggestion
|description|String|The description of the user flow attribute. It's shown to the user at the time of sign-up.|
```

2020-09-28 22:55 UTC, davidmu1 commented on api-reference/beta/toc.yml
>          - name: Access reviews
Don't forget your changelog entries.

2020-09-29 18:45 UTC, opbld32 commented
Docs Build status updates of commit _[bd14c54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd14c5400bc5fb1a362353bf949d78534c49a475)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e31fb949)

<a id="e31fb949"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009291845103644-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Cd4hkTM%2BsgPNTezC5TGA8lR%2F8A0NA67sCZ3XwI6K7fc%3D&st=2020-09-29T18%3A40%3A55Z&se=2020-10-30T18%3A45%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 18:46 UTC, opbld31 commented
Docs Build status updates of commit _[8e64069](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e64069a5e857fe8f31aaa92e0bdfd3111b91fa3)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:46 UTC, opbld32 commented
Docs Build status updates of commit _[ff7575d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff7575dfeb94684034d3286ad1b5e43d7b0ddcfe)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dd889a74)

<a id="dd889a74"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009291845474551-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LagmY%2FqxqSgsaQ0%2Bd%2FLTtUVDmf595d2tgnNbqgdIUis%3D&st=2020-09-29T18%3A41%3A41Z&se=2020-10-30T18%3A46%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 18:49 UTC, opbld30 commented
Docs Build status updates of commit _[7d673d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d673d5ae7f781b363c5360a46bdbd9e7137fef4)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:50 UTC, opbld31 commented
Docs Build status updates of commit _[7d673d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d673d5ae7f781b363c5360a46bdbd9e7137fef4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009291848567608-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OPOJCrKDV2qbQGqTAqb%2F8XyLK6jxMLGZMHe4wh43wMw%3D&st=2020-09-29T18%3A45%3A11Z&se=2020-10-30T18%3A50%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 18:59 UTC, jkdouglas commented on api-reference/beta/api/identityuserflowattribute-create.md
> +    "dataType": "String"
Updated

2020-09-29 18:59 UTC, jkdouglas commented on api-reference/beta/api/identityuserflowattribute-get.md
> +    "dataType": "String"
Fixed

2020-09-29 18:59 UTC, jkdouglas commented on api-reference/beta/api/identityuserflowattribute-update.md
> +Content-length: 41
Removed

2020-09-29 18:59 UTC, jkdouglas commented on api-reference/beta/resources/identityuserflowattribute.md
> +|[Update](../api/identityuserflowattribute-update.md)|None|Update a `custom user flow attribute`.|
Fixed

2020-09-29 18:59 UTC, jkdouglas commented on api-reference/beta/resources/identityuserflowattribute.md
> +|id|String|The ID of the user flow attribute. This is a read-only attribute that is automatically created.|
Fixed

2020-09-29 19:03 UTC, opbld33 commented
Docs Build status updates of commit _[6571529](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6571529da104fee222b2256f36fc0c6ccc0ff1ab)_: 

:clock10: **Pending**: waiting for processors ([17](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 19:05 UTC, opbld34 commented
Docs Build status updates of commit _[6571529](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6571529da104fee222b2256f36fc0c6ccc0ff1ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009291903044112-9748%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c%2B8NMMORVaW07IXTihUfLRVGOeEXUx2w5rYRaaAUKY0%3D&st=2020-09-29T19%3A00%3A16Z&se=2020-10-30T19%3A05%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 21:25 UTC, opbld30 commented
Docs Build status updates of commit _[a2d8e97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2d8e97ddb948881e8bb00e09a41daf4707caba7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-55c8b034)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="075040e5-55c8b034"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md)
 - **Line 176, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 205, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 206, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 208, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 237, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 237, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 413, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 451, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 505, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Channel settings permissions''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 649, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 649, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 649, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 651, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 651, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 651,  [...]

2020-10-01 22:24 UTC, jkdouglas commented on api-reference/beta/api/identityuserflowattribute-get.md
> +|Delegated (work or school account)|IdentityUserFlow.Read.All, IdentityUserFlow.ReadWrite.All|
Added permissions reference for IdentityUserFlows

2020-10-06 01:31 UTC, Lauragra requested changes
Please add an update to changelog.md and the DirectoryServices.json changelog file. Otherwise, looks good!

2020-10-06 17:18 UTC, opbld30 commented
Docs Build status updates of commit _[c1c8732](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1c873263eafaa9eccf9033399661d39223e6d21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-0400286b)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |

<a id="075040e5-0400286b"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md)
 - **Line 177, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 206, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 208, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 209, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 238, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 238, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 378, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 618, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 618, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 618, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 620, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 620, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 620, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 748, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 801, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-10-06 17:44 UTC, opbld31 commented
Docs Build status updates of commit _[34040db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34040db17e9b46d99078471b983d1b79eb0e8f63)_: 

:clock10: **Pending**: waiting for processors ([19](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 19 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-06 17:46 UTC, opbld34 commented
Docs Build status updates of commit _[34040db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34040db17e9b46d99078471b983d1b79eb0e8f63)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-d6647161)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-d6647161)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d6647161"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/identityuserflowattribute?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** ``` [...]

2020-10-09 21:09 UTC, opbld34 commented
Docs Build status updates of commit _[8f2aaf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f2aaf9cc7d057087c437268aba706f78c8c9b60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-ef52920b)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-ef52920b)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ef52920b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2authenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/identityuserflowattribute?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Sugge [...]

2020-10-09 22:52 UTC, opbld33 commented
Docs Build status updates of commit _[80fabb7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80fabb7b754ae5a4040d895189246cd0ebe44c82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-846f5e28)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-846f5e28)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-846f5e28"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2authenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/identityuserflowattribute?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Sugge [...]

2020-10-22 02:41 UTC, opbld30 commented
Docs Build status updates of commit _[fe3ab55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe3ab5574034f8f94e281fffc5a37ea53dfd3608)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-bfde97e6)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-bfde97e6)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-bfde97e6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysum [...]

2020-10-22 02:43 UTC, opbld32 commented
Docs Build status updates of commit _[070bca6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/070bca6a5355f499cc3d9e085c77679b7ddacdbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-be812368)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-be812368)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-be812368"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysum [...]

2020-10-22 02:45 UTC, Lauragra commented on api-reference/beta/api/identityuserflowattribute-update.md
> +|description|String|The description of the user flow attribute. It is shown to the user at the time of sign up.|
Is description the only property that can be updated, or can they also update the display name? If the former, please adjust the sentence under request body. Either way, you don't need an H3 here, just say "provide a JSON object with the property/properties listed in the following table."

2020-10-22 02:48 UTC, Lauragra commented on api-reference/beta/api/identityuserflowattribute-update.md
> +The following is an example of the request.
Global: It's not a high priority, but FYI, in general we're looking at removing this boilerplate text in the Request/Response examples..

2020-10-22 02:53 UTC, opbld32 commented
Docs Build status updates of commit _[0988f33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0988f33134ce59c0880aefb50af4a136244ff7ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-5dddd05a-b17818db)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-b17818db)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-b17818db)
[api-reference/beta/api/identityuserflowattribute-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-create?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5dddd05a-b17818db"></a>
### [api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md)
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/identityuserflowattribute-post.md'.`````

<a id="de0bbbbb-b17818db"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link [...]

2020-10-22 02:54 UTC, opbld30 commented
Docs Build status updates of commit _[932a963](https://github.com/microsoftgraph/microsoft-graph-docs/commits/932a963beb07ad94b0416157b24266e160e769c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) | [Details](#user-content-00685cff-aad444fd)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-aad444fd)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-aad444fd)
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-post?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="00685cff-aad444fd"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml)
 - **Line 10513, Column 22**: **[Warning-file-not-found]** `````Invalid file link: 'api/identityuserflowattribute-create.md'.`````

<a id="de0bbbbb-aad444fd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL [...]

2020-10-22 02:55 UTC, Lauragra reviewed
Please clarify the properties that can be updated in the update topic. Otherwise looks good!

2020-10-22 23:30 UTC, opbld32 commented
Docs Build status updates of commit _[185ed0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/185ed0d934d8137ceb412bf4b0d094013b536a3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-5f377ea5)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-5f377ea5)
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-post?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5f377ea5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pr [...]

2020-10-22 23:32 UTC, opbld34 commented
Docs Build status updates of commit _[682af36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/682af364812655c4a87ddc57a34941ac6566ef0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-e6928381)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-e6928381)
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-post?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e6928381"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pr [...]

2020-10-23 00:26 UTC, opbld34 commented
Docs Build status updates of commit _[7e83ce1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e83ce12120759f70220c14ae4a67dfd97bcab0d)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-23 00:27 UTC, Lauragra approved these changes

2020-10-23 00:28 UTC, opbld33 commented
Docs Build status updates of commit _[7e83ce1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e83ce12120759f70220c14ae4a67dfd97bcab0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9748) | [Details](#user-content-de0bbbbb-15ecf3a0)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9748) | [Details](#user-content-075040e5-15ecf3a0)
[api-reference/beta/api/identityuserflowattribute-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-get?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-post?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/api/identityuserflowattribute-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/api/identityuserflowattribute-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflowattribute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/resources/identityuserflowattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflowattribute-delete?view=graph-rest-beta&branch=pr-en-us-9748) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-15ecf3a0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowAttributes/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pr [...]

2020-10-23 00:39 UTC, merged