Added documentation for content type apis
microsoftgraph/microsoft-graph-docs pull request #9775
Opened 2020-09-03 06:33 UTC by swapnil1993

2020-09-03 06:33 UTC, opbld33 commented
Docs Build status updates of commit _[3c8537c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c8537c45a63d6f2cfd8c561047e4ca0d728eec1)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-03 06:34 UTC, opbld31 commented
Docs Build status updates of commit _[3c8537c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c8537c45a63d6f2cfd8c561047e4ca0d728eec1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-00685cff-154a8af3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-154a8af3)
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-6e1728cd-154a8af3)
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-14be6879-154a8af3)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.co [...]

2020-09-03 06:51 UTC, opbld31 commented
Docs Build status updates of commit _[88682b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88682b5892bfb38fb96f185156bc546181723145)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-03 06:52 UTC, opbld34 commented
Docs Build status updates of commit _[88682b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88682b5892bfb38fb96f185156bc546181723145)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-14be6879-fa68cbf9)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentapprovalstatuscolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contentapprovalstatuscolumn?view=graph-rest-beta&b [...]

2020-09-03 09:28 UTC, opbld32 commented
Docs Build status updates of commit _[7ee1a28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ee1a28dfc634c829899e9d4b2523ac9aba3749c)_: 

:clock10: **Pending**: waiting for processors ([13](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-03 09:29 UTC, opbld32 commented
Docs Build status updates of commit _[7ee1a28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ee1a28dfc634c829899e9d4b2523ac9aba3749c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-14be6879-1c930486)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-column.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-column.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-column?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentapprovalstatuscolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contentapprovalstatuscolumn?view=graph-rest-beta&b [...]

2020-09-15 08:12 UTC, opbld30 commented
Docs Build status updates of commit _[628e00b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/628e00b80b86f82b4e3efc56c36790a9cfd7b090)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1caa7791)

<a id="1caa7791"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009150812050028-9775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uAHPwSC5cpYp4iIVfeXS5dUjBpsGVr5U2VuGDLX6kGQ%3D&st=2020-09-15T08%3A07%3A33Z&se=2020-10-16T08%3A12%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 08:16 UTC, opbld33 commented
Docs Build status updates of commit _[10b6603](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10b6603405095fe0af1bca095d8c0febc595b477)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-9d43abf0-ee000605)
[api-reference/beta/resources/termcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/termcolumn.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termcolumn?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-4cc4e04d-ee000605)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-00685cff-ee000605)
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-8f76dfd3-ee000605)
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-14be6879-ee000605)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-ee000605)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicableconten [...]

2020-09-15 08:26 UTC, opbld32 commented
Docs Build status updates of commit _[fb7ef63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb7ef636731c11e214a1bc13d44223fa5de7dd8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-14be6879-e5f34196)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-e5f34196)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.m [...]

2020-09-15 16:32 UTC, opbld31 commented
Docs Build status updates of commit _[f31e7d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f31e7d46fa9dce6e3e3e323255765769287f78d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-14be6879-caf2c681)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-caf2c681)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.m [...]

2020-09-15 16:40 UTC, Lauragra commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +# Associate a content type with list of hubsites
The H1 title needs to match the title attribute. In this case, the title should be "contentType: associateWithHubSites".

2020-09-15 16:44 UTC, Lauragra commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +Associate a [content type][contentType] with list of hubsites.
Global: Add articles such as "a", "an", and "the" to your sentences for readability, clarity, and proper English grammar. So in this sentence, for example, it needs to say: with "a" list of hub sites. Note that "hub sites" is two words.

2020-09-15 16:45 UTC, Lauragra commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +Note: This feature limited to tenants having cortex license
Use proper note formatting. It should be like this:

> **Note:**

2020-09-15 16:47 UTC, Lauragra commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +Note: This feature limited to tenants having cortex license
This sentence is missing some words, like "is" and "a". Should be revised to say, "This feature is limited to tenants that have a cortex license." What is cortex? Is that going to be clear to customers? Do you need to link to something that explains it, and is that the correct branding/casing?

2020-09-15 16:52 UTC, Lauragra commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +|Parameter|Type|Required|Description|
Global: Did you add the Required column, or was that output by the tool? Generally we just have three columns and we indicate required/optional in the description column.

2020-09-15 16:55 UTC, Lauragra commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +If successful, this action returns a `204 No Content` response code
Global: Add the missing period.

2020-09-15 16:56 UTC, Lauragra commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +In the request body, supply JSON representation of the parameters.
supply JSON -> supply a JSON

2020-09-15 16:57 UTC, Lauragra commented on api-reference/beta/api/contenttype-copytodefaultcontentlocation.md
> +description: "Copy a file to default content location in a Content Type"
The descriptions should also end with a period and follow correct capitalization - content type should be lowercase here.

2020-09-15 16:58 UTC, Lauragra commented on api-reference/beta/api/contenttype-copytodefaultcontentlocation.md
> +Copy a file to default content location in a [content type][contentType] so that they can be added as default content or template via POST operation.
Revise: Copy a file to a default content location in a content type. The file can then be added as a default file or template via a POST operation.

2020-09-15 16:59 UTC, Lauragra commented on api-reference/beta/api/contenttype-copytodefaultcontentlocation.md
> +POST https://graph.microsoft.com/beta/sites/id/contentTypes/id/copyToDefaultContentLocation
Global: The HTTP syntax section only shows the syntax, not the full URL. The full URL is shown in the request example.

2020-09-17 10:05 UTC, opbld33 commented
Docs Build status updates of commit _[f70c46d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f70c46d893236e6153b529e05e1b3b8790293f11)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-7a1003a0-d6211f66)
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-14be6879-d6211f66)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-d6211f66)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.c [...]

2020-09-17 10:10 UTC, swapnil1993 commented on api-reference/beta/api/contenttype-associatewithhubsites.md
> +|Parameter|Type|Required|Description|
Removed required column

2020-09-26 01:10 UTC, opbld33 commented
Docs Build status updates of commit _[ed50f82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed50f82ffe7f6d729dd73957c0d8e5b51123d88a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-5eb3c806)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:12 UTC, opbld34 commented
Docs Build status updates of commit _[c50d29e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c50d29e23d66eabe297f12ce4cae31f4890da00b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-bfb9b436)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:15 UTC, Lauragra commented on api-reference/beta/api/contenttype-addcopy.md
> +
Global: The permissions tables have extra lines between the rows, causing them to break. Please fix all the tables to remove the extra lines between rows.

2020-09-26 01:15 UTC, opbld34 commented
Docs Build status updates of commit _[7253074](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7253074bb6afea28140121b01a13a7ed2a67e098)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-832d62b0)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:18 UTC, Lauragra commented on api-reference/beta/api/contenttype-create-columns.md
> +## HTTP request
Add the missing HTML comment to ignore this request.

2020-09-26 01:18 UTC, Lauragra commented on api-reference/beta/api/contenttype-create-columns.md
> +
The Response H2 section is missing here.

2020-09-26 01:19 UTC, opbld30 commented
Docs Build status updates of commit _[a01ea11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a01ea1120f9b6d5b843c8ed876723a33e7ecaae7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-6e7a1c52)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:20 UTC, Lauragra commented on api-reference/beta/api/contenttype-create-columns.md
> +---
For the file name, use post instead of create.

2020-09-26 01:20 UTC, Lauragra commented on api-reference/beta/api/contenttype-create.md
> +---
Change create to post in the file name.

2020-09-26 01:21 UTC, opbld31 commented
Docs Build status updates of commit _[8047c49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8047c4919fb9f10eb547214eee891083296f9344)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-1c82af11)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:23 UTC, Lauragra commented on api-reference/beta/api/contenttype-create-columns.md
> +# Create contentType columns
For the H1 and title, it should be Create columnDefinition.

2020-09-26 01:23 UTC, opbld32 commented
Docs Build status updates of commit _[f7ea706](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7ea70683e9b9de76cbee6b5c7bd3600660237be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-35377bd7)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:23 UTC, Lauragra commented on api-reference/beta/api/contenttype-delete-columns.md
> +title: "Delete a content type column"
For the title here, it should be Delete columnDefinition.

2020-09-26 01:25 UTC, Lauragra commented on api-reference/beta/api/contenttype-get-columns.md
> +title: "Get a contentType column"
The title should be "Get columnDefinition".

2020-09-26 01:25 UTC, opbld34 commented
Docs Build status updates of commit _[1b46494](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b464949dfd219ebb384ee92266eec882f493ce0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-53d71f7f)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:27 UTC, opbld30 commented
Docs Build status updates of commit _[e2a8cd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2a8cd7ff9c8229175c7605c0cbca8a55ca827fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-bb9e73fc)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:28 UTC, opbld31 commented
Docs Build status updates of commit _[b75c7fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b75c7fccbb3f3e76ebfcfb4dd090cb46bf582962)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-97bdb470)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:30 UTC, Lauragra commented on api-reference/beta/api/contenttype-ispublished.md
> +
This topic is missing the Response H2 section.

2020-09-26 01:30 UTC, Lauragra commented on api-reference/beta/api/contenttype-list-columns.md
> +# List content type columns
Change the title to List columnDefinitions.

2020-09-26 01:31 UTC, opbld30 commented
Docs Build status updates of commit _[13827ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13827ec31d970bc61a4d62b6d92aa30a2ffb0692)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-457077c1)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:33 UTC, Lauragra commented on api-reference/beta/api/contenttype-list-columns.md
> +	"value": [
Global: A lot of files have extra spaces in the HTTP syntax, examples, etc. section. For readability, please remove the extra lines. This will reduce scrolling for the user in the live topic.

2020-09-26 01:36 UTC, opbld31 commented
Docs Build status updates of commit _[6514035](https://github.com/microsoftgraph/microsoft-graph-docs/commits/651403592434d4bd6e6c4eb744429926f3dc892f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-6c8c45a7)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:38 UTC, opbld32 commented
Docs Build status updates of commit _[d4c624b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4c624b36ad767ad82514a02017a3c51bfdf1775)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-129d4900)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:39 UTC, opbld32 commented
Docs Build status updates of commit _[8d10d41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d10d410f248ec23215f0dbcc41e5521850182da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-b92f1756)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:41 UTC, opbld32 commented
Docs Build status updates of commit _[a4b3977](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4b39776133a62f76636259897e694684726fb50)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-0c19752d)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:42 UTC, opbld31 commented
Docs Build status updates of commit _[d48a165](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d48a165889ee1f90ca67b165f93319d28c184b3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-8d67648f)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:43 UTC, Lauragra commented on api-reference/beta/api/contenttype-update-columns.md
> +title: "Update a content type column"
"Update columnDefinition"

2020-09-26 01:44 UTC, opbld31 commented
Docs Build status updates of commit _[342a21b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/342a21bb05d555fd54a04c33f231a1a47d807950)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-e84bf1d3)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:45 UTC, opbld33 commented
Docs Build status updates of commit _[af4da5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af4da5dc24cc6752bf50544097c358db555ed55a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-9bfff8ba)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:47 UTC, opbld31 commented
Docs Build status updates of commit _[6e9a6f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e9a6f5f58c01be463a766bac8f54a73f94bb18b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-d44f262a)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:49 UTC, opbld31 commented
Docs Build status updates of commit _[f59938c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f59938c18f8bae2167742d7909190c205894c3f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-35ac48f2)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:49 UTC, Lauragra commented on api-reference/beta/api/site-getapplicablecontenttypesforlist.md
> +## Request body
This section got mixed up with a Function parameters section. Please add a Function parameters section as applicable. A Request body H2 section is always required.

2020-09-26 01:50 UTC, opbld34 commented
Docs Build status updates of commit _[2fb5bbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fb5bbdda99966534724e89426aaaee8497c899a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-401082eb)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:51 UTC, Lauragra commented on api-reference/beta/resources/columndefinition.md
> +| **sourceContentType**   |[contentTypeInfo][]  | ContentType from which this column is inherited from. Used only while fetching contentTypes columns | No | No
You're adding Yes | No columns to some of these properties but there are no columns for those values. Please include those in the Description column instead, for consistency with all property tables.

2020-09-26 01:55 UTC, opbld33 commented
Docs Build status updates of commit _[04930f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04930f43b1c36db690120ff8bbaa8bb44bf4b0d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-74a75cf8)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:57 UTC, Lauragra commented on api-reference/beta/resources/columnvalidation.md
> +
Global: Please ensure that all topics include the required beta disclaimer. If you use the stub generator to create your files, it should be added automatically.

2020-09-26 01:58 UTC, opbld34 commented
Docs Build status updates of commit _[a2d97c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2d97c6f3433f71d18f316f8b95bf28366859fa3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-7fb0c555)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 01:59 UTC, Lauragra commented on api-reference/beta/resources/documentsetcontent.md
> +The **documentSetContent** resource contains metadata about a file present in default content location of a content type.
Global: For these descriptions, you don't need to repeat the resource name, just start with the verb, i.e. "Contains metadata....".

2020-09-26 01:59 UTC, opbld30 commented
Docs Build status updates of commit _[16886a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16886a1efe594721e4d70132b4a906be27c9adf8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-ec5f5936)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftg [...]

2020-09-26 02:01 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get Applicable Content Types For List
Global: We use sentence case for TOC entries, so the casing here should be "Get content types for list". Please update all TOC entries as applicable.

2020-09-26 02:01 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get
Use this order for the CRUD operations: List, Create, Get, Update, Delete.

2020-09-26 02:02 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added content type apis to do CRUD operations on [content type](/graph/api/resources/contenttype?view=graph-rest-beta) and its [columns](/graph/api/resources/columnDefinition?view
You can consolidate these entries - i.e. one row for all the properties added to columnDefinition, one row for all the methods added to contentType, etc.

2020-09-26 02:03 UTC, Lauragra requested changes
Please review and incorporate editorial feedback.

2020-09-28 09:40 UTC, opbld33 commented
Docs Build status updates of commit _[725b64b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/725b64bc7fc09ff323156b2673ace1028dcc95d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-d75c0b3e)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microso [...]

2020-09-28 09:45 UTC, swapnil1993 commented on api-reference/beta/resources/columnvalidation.md
> +
Stub files didn't have beta disclaimers for resources added them now.

2020-09-30 00:33 UTC, opbld34 commented
Docs Build status updates of commit _[cce5c12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cce5c12c73f21979b78f5ae209325c9cae13a0cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-faf3da00)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microso [...]

2020-12-03 14:34 UTC, opbld33 commented
Docs Build status updates of commit _[c3a66aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3a66aa44c382283b7b04e935887be7edf0f2720)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8622c15f)

<a id="8622c15f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012031433517517-9775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s4xFTfOVsIucv51Qd6UXMEPR1iVRLsfmmv7%2F9Qdo7MI%3D&st=2020-12-03T14%3A29%3A15Z&se=2021-01-03T14%3A34%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 14:54 UTC, opbld34 commented
Docs Build status updates of commit _[6c6fc31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c6fc314363f8b81f6df8f0947cc13defc3edff8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-ef2d28ca)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-12-03 14:58 UTC, opbld32 commented
Docs Build status updates of commit _[8dd3e56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8dd3e56c3f1a299f28f4c20029336a393e16638b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9775) | [Details](#user-content-de0bbbbb-9517019f)
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microsoft-grap [...]

2021-02-01 15:14 UTC, swapnil1993 commented on api-reference/beta/api/contenttype-addcopy.md
> +Add a copy of a [site][site] [content type][contentType] to a [list][list].
test comment to prevent closing this pr

2021-02-10 04:34 UTC, opbld31 commented
Docs Build status updates of commit _[16f47f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16f47f123ba9133898bd41591f03a8e96821a44c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentapprovalstatuscolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contentapprovalstatuscolumn?view=graph-rest-beta&branch=pr-en-us-9775) (graph-r [...]

2021-02-10 08:53 UTC, opbld33 commented
Docs Build status updates of commit _[b466dfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b466dfe463f212f2ba5d7ab691d0f9a7d7234d73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) |
[api-reference/beta/resources/contentapprovalstatuscolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/contentapprovalstatuscolumn.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contentapprovalstatuscolumn?view=graph-rest-beta&branch=pr-en-us-9775) (graph-r [...]

2021-03-03 05:35 UTC, Lauragra commented on api-reference/beta/api/contenttype-addcopy.md
> +ms.prod: "sharepoint"
Global: The ms.prod value for these topics should be "sites-and-lists".

2021-03-03 05:39 UTC, Lauragra commented on api-reference/beta/resources/columndefinition.md
> +| **isDeletable**       | boolean | Indicates whether this column can be deleted.
Global: Please capitalize Boolean.

2021-03-03 05:41 UTC, Lauragra commented on api-reference/beta/toc.yml
> +      - name: Content Types
Please use sentence case - Content types.

2021-03-03 05:41 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Add Copy
Add copy.

2021-03-03 05:44 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +      "WorkloadArea": "Files",
The WorkloadArea is Sites and lists (SharePoint), right? Also, the date should reflect the date that we publish the docs. When I publish, I can set the date to that day's date. It sounds like builds are back online so this should hopefully be soon.

2021-03-03 05:44 UTC, Lauragra commented on concepts/changelog.md
> +### Sites and lists
FYI, this file is deprecated; we no longer update the MD file, just the JSON file.

2021-03-03 05:58 UTC, swapnil1993 commented on changelog/Microsoft.FileServices.json
> +      "WorkloadArea": "Files",
These changes are part of "FileServices.csdl", I generated this file using doc generator tool which set it as "Files"

2021-03-03 07:07 UTC, swapnil1993 commented on api-reference/beta/api/contenttype-addcopy.md
> +ms.prod: "sharepoint"
Updated to  "sites-and-lists".

2021-03-03 07:07 UTC, swapnil1993 commented on concepts/changelog.md
> +### Sites and lists
Reverted changes to this file

2021-03-03 17:55 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +      "WorkloadArea": "Files",
All the JSON files get merged into one shared JSON file before publishing so it technically doesn't matter which file contains your entry or what the file name is. I'll just change this to Sites and lists and update the date before publishing.

2021-03-03 18:08 UTC, opbld31 commented
Docs Build status updates of commit _[d797b9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d797b9cc2c0031c820650b47a43ea604f542f50f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-49918d71-42f6acc6)
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-bf43698d-42f6acc6)
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-98fef548-42f6acc6)
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-e3e1531d-42f6acc6)
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-6e1728cd-42f6acc6)
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-61a8b8df-42f6acc6)
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-7ef735f0-42f6acc6)
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-f6fedcfe-42f6acc6)
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-8f76dfd3-42f6acc6)
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-5596491f-42f6acc6)
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-2fcb1741-42f6acc6)
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-82e16117-42f6acc6)
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-8deeb37b-42f6acc6)
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-362e664e-42f6acc6)
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-c1cd5599-42f6acc6)
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-c7d83aa3-42f6acc6)
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-3e7d8e1b-42f6acc6)
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-9d43abf0-42f6acc6)
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-a71273bd-42f6acc6)
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-re [...]

2021-03-03 18:14 UTC, Lauragra approved these changes

2021-03-03 18:14 UTC, merged

2021-03-03 18:24 UTC, opbld34 commented
Docs Build status updates of commit _[fe6d6d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe6d6d81db597b097564185d69a14e571aa6d5e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-addcopy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-49918d71-e267a90d)
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-associatewithhubsites.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-bf43698d-e267a90d)
[api-reference/beta/api/contenttype-copytodefaultcontentlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-copytodefaultcontentlocation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-copytodefaultcontentlocation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-98fef548-e267a90d)
[api-reference/beta/api/contenttype-delete-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-e3e1531d-e267a90d)
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-6e1728cd-e267a90d)
[api-reference/beta/api/contenttype-get-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-61a8b8df-e267a90d)
[api-reference/beta/api/contenttype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-get?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-7ef735f0-e267a90d)
[api-reference/beta/api/contenttype-ispublished.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-ispublished.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-ispublished?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-f6fedcfe-e267a90d)
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-8f76dfd3-e267a90d)
[api-reference/beta/api/contenttype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-5596491f-e267a90d)
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-2fcb1741-e267a90d)
[api-reference/beta/api/contenttype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-82e16117-e267a90d)
[api-reference/beta/api/contenttype-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-publish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-publish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-8deeb37b-e267a90d)
[api-reference/beta/api/contenttype-unpublish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-unpublish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-unpublish?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-362e664e-e267a90d)
[api-reference/beta/api/contenttype-update-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update-columns.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update-columns?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-c1cd5599-e267a90d)
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/contenttype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-c7d83aa3-e267a90d)
[api-reference/beta/api/site-getapplicablecontenttypesforlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/api/site-getapplicablecontenttypesforlist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-getapplicablecontenttypesforlist?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-3e7d8e1b-e267a90d)
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columndefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-9d43abf0-e267a90d)
[api-reference/beta/resources/columnvalidation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-reference/beta/resources/columnvalidation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columnvalidation?view=graph-rest-beta&branch=pr-en-us-9775) (graph-rest-beta) | [Details](#user-content-a71273bd-e267a90d)
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-11-contenttypeapis/api-re [...]