added LCM user properties
microsoftgraph/microsoft-graph-docs pull request #9790
Opened 2020-09-03 23:40 UTC by cmmdesai

2020-09-03 23:41 UTC, opbld34 commented
Docs Build status updates of commit _[6ccbafb](https://github.com/cmmdesai/microsoft-graph-docs/commits/6ccbafb51f7d2ebd9bd982c5a55fe1aa43d9c0a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) | [Details](#user-content-8fa18829-c1ca13fb)

<a id="8fa18829-c1ca13fb"></a>
### [api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Represents an Azure AD user account. Inherits from directoryObject.' is duplicated in 'beta/resources/user.md(3,14)', 'v1.0/resources/user.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009032340135661-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yNQngtt8ZSNBWS5t8dcuH4g6B2O5LBt0DnmzXOPU0Jg%3D&st=2020-09-03T23%3A36%3A31Z&se=2020-10-04T23%3A41%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-04 17:03 UTC, opbld31 commented
Docs Build status updates of commit _[cac3811](https://github.com/cmmdesai/microsoft-graph-docs/commits/cac3811a7388853f7b932c567d54302052f864d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employeeOrgData.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeOrgData.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) | [Details](#user-content-f06abab0-82b99cd2)
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) | [Details](#user-content-8fa18829-82b99cd2)

<a id="f06abab0-82b99cd2"></a>
### [api-reference/beta/resources/employeeOrgData.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeOrgData.md)
 - **Line 7, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'chmutali' is not a valid GitHub ID.`````

<a id="8fa18829-82b99cd2"></a>
### [api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Represents an Azure AD user account. Inherits from directoryObject.' is duplicated in 'beta/resources/user.md(3,14)', 'v1.0/resources/user.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009041701448009-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4LLoW%2FrKq1YZH3dVYMZL%2FTyyGWSnxFfjRDFq4qd%2FS1E%3D&st=2020-09-04T16%3A58%3A03Z&se=2020-10-05T17%3A03%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-04 17:06 UTC, opbld32 commented
Docs Build status updates of commit _[8384902](https://github.com/cmmdesai/microsoft-graph-docs/commits/8384902dd32121daa6cf977f0c6e5a9d9a8323cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) | [Details](#user-content-8fa18829-3718b4ba)
[api-reference/beta/resources/employeeOrgData.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeOrgData.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

<a id="8fa18829-3718b4ba"></a>
### [api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Represents an Azure AD user account. Inherits from directoryObject.' is duplicated in 'beta/resources/user.md(3,14)', 'v1.0/resources/user.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009041705264809-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L7ZGXeTlbf7rZs4wg0s7N5lWN5nyqs6N8iwadB0wbI0%3D&st=2020-09-04T17%3A01%3A48Z&se=2020-10-05T17%3A06%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-04 21:31 UTC, alok-bansal requested changes

2020-09-04 21:31 UTC, alok-bansal commented on api-reference/beta/resources/user.md
> +| division | String | The name of the division in which the user works. <br><br>Returned only on $select. Supports $filter. |
Remove Division from here.

2020-09-04 21:31 UTC, alok-bansal commented on api-reference/beta/resources/user.md
> +| costCenter | String | The cost center associated with the user. <br><br>Returned only on $select. Supports $filter. |
Remove cost center and add employeeOrgData with link to md file for that.

2020-09-25 16:21 UTC, opbld31 commented
Docs Build status updates of commit _[ad160ef](https://github.com/cmmdesai/microsoft-graph-docs/commits/ad160ef428d60696736af3f3112af18c59552651)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employee-org-data.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employee-org-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employee-org-data?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) | [Details](#user-content-b69615e9-78692e75)
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

<a id="b69615e9-78692e75"></a>
### [api-reference/beta/resources/employee-org-data.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employee-org-data.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=master)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009251620163770-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5HBYGU%2FdcSYohwNeDuB4vTyi8sEt6aRRbIqQuIL1CX0%3D&st=2020-09-25T16%3A16%3A39Z&se=2020-10-26T16%3A21%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-25 16:29 UTC, opbld30 commented
Docs Build status updates of commit _[c27d9df](https://github.com/cmmdesai/microsoft-graph-docs/commits/c27d9dfe1c42a7290e8de0e883badbf050e48646)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employee-org-data.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employee-org-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employee-org-data?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) | [Details](#user-content-b69615e9-bcbbec4f)
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

<a id="b69615e9-bcbbec4f"></a>
### [api-reference/beta/resources/employee-org-data.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employee-org-data.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=master)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009251627509352-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hi1DuWHqPqJCrJdGgaMwXnSrzEe%2BMr4dchdBe19smL4%3D&st=2020-09-25T16%3A24%3A41Z&se=2020-10-26T16%3A29%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-25 16:34 UTC, cmmdesai commented
#sign-off

2020-10-13 15:58 UTC, opbld33 commented
Docs Build status updates of commit _[8d1af18](https://github.com/cmmdesai/microsoft-graph-docs/commits/8d1af182376a49ad8227db32369a1ebc46d8f336)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employee-org-data.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employee-org-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employee-org-data?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) | [Details](#user-content-b69615e9-a14421b9)
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

<a id="b69615e9-a14421b9"></a>
### [api-reference/beta/resources/employee-org-data.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employee-org-data.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010131556402374-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SaW4YOGRjgyHHSv8CfLBFlfJMgPn5bNn4ou0pui1l4g%3D&st=2020-10-13T15%3A53%3A36Z&se=2020-11-13T15%3A58%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 16:21 UTC, opbld32 commented
Docs Build status updates of commit _[235e3f2](https://github.com/cmmdesai/microsoft-graph-docs/commits/235e3f25077b7b8a458a79ba8e958a313d24b409)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employee-org-data.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employee-org-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employee-org-data?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010131619495975-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dz4%2FggxcZvP%2FqZVDoTIgRlLAc55k8eWN4umoeZ794%2B0%3D&st=2020-10-13T16%3A16%3A11Z&se=2020-11-13T16%3A21%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 16:34 UTC, opbld32 commented
Docs Build status updates of commit _[ab5a0b1](https://github.com/cmmdesai/microsoft-graph-docs/commits/ab5a0b1112f78805263edea90b3739b670f13ad3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employeeorgdata.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeorgdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010131633176629-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bEIoXNSeLve1zNCaM9uH0TtPzNWejAWn6wdB0Vz3pBs%3D&st=2020-10-13T16%3A29%3A42Z&se=2020-11-13T16%3A34%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 18:40 UTC, opbld31 commented
Docs Build status updates of commit _[780550c](https://github.com/cmmdesai/microsoft-graph-docs/commits/780550cf6d6cd53b363c04f5a8d22d8a4ec7fd3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employeeorgdata.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeorgdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010131838375298-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xRlFh%2Fc8mMYv73GBgxWqsvaFBC2Pq9uZKtssX%2B3LDO4%3D&st=2020-10-13T18%3A35%3A40Z&se=2020-11-13T18%3A40%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 21:40 UTC, opbld31 commented
Docs Build status updates of commit _[43e49dd](https://github.com/cmmdesai/microsoft-graph-docs/commits/43e49dd5193063e8dd9289b1e3e10ff6eb657568)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employeeorgdata.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeorgdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010142138355168-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FbokBNBkhgbZcPRlObuQlJ1IEKLW1ourkMwEPkza9wQ%3D&st=2020-10-14T21%3A35%3A01Z&se=2020-11-14T21%3A40%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-15 14:59 UTC, alok-bansal approved these changes

2020-10-15 15:03 UTC, alok-bansal commented
@microsoftgraph/graph-docs-contributors - can you please review?

2020-10-15 15:27 UTC, alok-bansal commented
@davidmu1 - requesting your review.

2020-10-20 17:44 UTC, opbld34 commented
Docs Build status updates of commit _[c712a49](https://github.com/cmmdesai/microsoft-graph-docs/commits/c712a49c8aad65f57e6dd48e381ad1327bc58d49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employeeorgdata.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeorgdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201743017837-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vrTO2LvKUprkblQV%2FSn1qEIfr9j64MwG3DQSYGI4j0Q%3D&st=2020-10-20T17%3A39%3A30Z&se=2020-11-20T17%3A44%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:11 UTC, davidmu1 approved these changes

2020-10-21 00:35 UTC, opbld30 commented
Docs Build status updates of commit _[16561fa](https://github.com/cmmdesai/microsoft-graph-docs/commits/16561fa3d26e5f53a8261a5c8bd4c48eeaf21912)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employeeorgdata.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeorgdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210034233013-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RLg8lI7SUX5ksn2Hc5AiV%2BsFZO2Ox9Ih%2FhIUCft3Vnk%3D&st=2020-10-21T00%3A30%3A39Z&se=2020-11-21T00%3A35%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 00:42 UTC, opbld34 commented
Docs Build status updates of commit _[979862b](https://github.com/cmmdesai/microsoft-graph-docs/commits/979862baa1a0d35e802172f0d600f2e08882babc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/employeeorgdata.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/employeeorgdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-patch-q1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-9790) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210041343313-9790%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1jRPukSfIeBVknKZAeKRx2adNJc4evSP0bmq6Le2CbI%3D&st=2020-10-21T00%3A37%3A55Z&se=2020-11-21T00%3A42%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 00:54 UTC, merged