Adding printDocument: $value method
microsoftgraph/microsoft-graph-docs pull request #9793
Opened 2020-09-04 00:57 UTC by braedenp-msft

2020-09-04 00:59 UTC, opbld31 commented
Docs Build status updates of commit _[91e0753](https://github.com/braedenp-msft/microsoft-graph-docs/commits/91e0753b0392dd53a421696fc384ab13c589d16c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009040057490921-9793%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=daoFmPby%2BSEpCIPYwmMQUo%2FQWtQkz6RSLBv9XVUvQuw%3D&st=2020-09-04T00%3A54%3A09Z&se=2020-10-05T00%3A59%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-10 17:57 UTC, opbld33 commented
Docs Build status updates of commit _[8cb7aca](https://github.com/braedenp-msft/microsoft-graph-docs/commits/8cb7aca4f1dad4c545a75a2355c3a7eff2f8de99)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-11f1b089)

<a id="11f1b089"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009101756427449-9793%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nh8YqzRh0%2BxsuVSiZvIgKoCzzejH3Arv3zwDFiSVbhA%3D&st=2020-09-10T17%3A52%3A15Z&se=2020-10-11T17%3A57%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-10 17:59 UTC, opbld32 commented
Docs Build status updates of commit _[bca1410](https://github.com/braedenp-msft/microsoft-graph-docs/commits/bca14103b6334c0e196016ed4fa6794f8024bca9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-f1974829-d7b4fa44)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-d7b4fa44)

<a id="f1974829-d7b4fa44"></a>
### [api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-d7b4fa44"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-value?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 90, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-list-printers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 90, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 90, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 90, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 90, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific versi [...]

2020-09-10 18:25 UTC, nilakhan approved these changes

2020-09-11 00:37 UTC, Lauragra commented on api-reference/beta/api/printdocument-value.md
> +GET https://graph.microsoft.com/beta/print/printers/{id}/jobs/{id}/documents/{id}/$value
In this section, we don't include the full URL, just the syntax. We show the full URL in the Examples section.

2020-09-11 00:52 UTC, Lauragra requested changes
Please also expose the new method in the TOC and the parent resource topic. Thanks!

2020-09-11 21:34 UTC, opbld32 commented
Docs Build status updates of commit _[23873b6](https://github.com/braedenp-msft/microsoft-graph-docs/commits/23873b6e164c6d77fb9524bf231ea1cf7baa91c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-f1974829-13c84f38)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-13c84f38)

<a id="f1974829-13c84f38"></a>
### [api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-13c84f38"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-value?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-list-printers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete-allowedgroup?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete-alloweduser?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view [...]

2020-09-11 21:48 UTC, opbld33 commented
Docs Build status updates of commit _[b798fb0](https://github.com/braedenp-msft/microsoft-graph-docs/commits/b798fb0f7dc26b34ab495ffd2fe2d8b5b2457af6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-f1974829-39d04a95)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-39d04a95)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="f1974829-39d04a95"></a>
### [api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-39d04a95"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-value?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-list-printers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete-allowedgroup?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so,  [...]

2020-09-11 21:54 UTC, opbld32 commented
Docs Build status updates of commit _[6b4fe2f](https://github.com/braedenp-msft/microsoft-graph-docs/commits/6b4fe2f311e018e104706c8f79f76a253ba8280b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-f1974829-eee64062)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-eee64062)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-eee64062)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="f1974829-eee64062"></a>
### [api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-eee64062"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-eee64062"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-value?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-list-printers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/a [...]

2020-09-12 00:12 UTC, opbld31 commented
Docs Build status updates of commit _[4b71055](https://github.com/braedenp-msft/microsoft-graph-docs/commits/4b71055280127537d3b29d17551cad275ae77ae3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-f1974829-1fef7ccf)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-1fef7ccf)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-1fef7ccf)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="f1974829-1fef7ccf"></a>
### [api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-1fef7ccf"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-1fef7ccf"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-value?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-list-printers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/a [...]

2020-09-12 00:21 UTC, opbld30 commented
Docs Build status updates of commit _[9649a0f](https://github.com/braedenp-msft/microsoft-graph-docs/commits/9649a0fd069daacd4a48d989488fe885a29658fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-f1974829-0c840d90)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-0c840d90)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-0c840d90)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-value?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="f1974829-0c840d90"></a>
### [api-reference/beta/api/printdocument-value.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-value.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-0c840d90"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-0c840d90"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-value?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-list-printers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 89, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/a [...]

2020-09-12 02:22 UTC, Lauragra commented on api-reference/beta/resources/printdocument.md
>  | [uploadData](../api/printdocument-uploaddata.md) | None | Upload a single binary segment of the **printDocument**. |
This resource and the uploadData method are not currently exposed in the TOC - please add.

2020-09-25 00:11 UTC, braedenp-msft commented on api-reference/beta/resources/printdocument.md
>  | [uploadData](../api/printdocument-uploaddata.md) | None | Upload a single binary segment of the **printDocument**. |
Fixed!

2020-09-25 00:13 UTC, opbld30 commented
Docs Build status updates of commit _[144738d](https://github.com/braedenp-msft/microsoft-graph-docs/commits/144738d3f9482ee4d6762318e6732cfe2028827a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-2c60ef23-b23afcf2)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-b23afcf2)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-b23afcf2)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="2c60ef23-b23afcf2"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-b23afcf2"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 23, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/printdocument-value.md'.`````

<a id="de0bbbbb-b23afcf2"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 145, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 145, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 145, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set] [...]

2020-09-25 00:17 UTC, opbld30 commented
Docs Build status updates of commit _[2519857](https://github.com/braedenp-msft/microsoft-graph-docs/commits/25198579083ff782ba193c0fc3420fa6ccad51fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-2c60ef23-d7afd960)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-d7afd960)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-d7afd960)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="2c60ef23-d7afd960"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-d7afd960"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-d7afd960"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 145, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 145, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 145, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/i [...]

2020-09-25 00:21 UTC, opbld32 commented
Docs Build status updates of commit _[201259c](https://github.com/braedenp-msft/microsoft-graph-docs/commits/201259c5eecae3758eaecea457a9d1fa5895d5a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-2c60ef23-d753e698)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-d753e698)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-d753e698)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="2c60ef23-d753e698"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-d753e698"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-d753e698"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 145, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 145, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 145, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/i [...]

2020-09-25 00:26 UTC, opbld31 commented
Docs Build status updates of commit _[30e509a](https://github.com/braedenp-msft/microsoft-graph-docs/commits/30e509a777412033fb68799c921307bcc7c2b29d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-2c60ef23-5ff47a66)
[api-reference/beta/api/printer-update.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printer-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-update?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-5d49c585-5ff47a66)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-5ff47a66)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-5ff47a66)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="2c60ef23-5ff47a66"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5d49c585-5ff47a66"></a>
### [api-reference/beta/api/printer-update.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printer-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-5ff47a66"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-5ff47a66"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 145, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 145, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 145, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
  [...]

2020-09-25 00:32 UTC, braedenp-msft commented
@Lauragra Requested changes made!

2020-09-25 00:33 UTC, Lauragra approved these changes

2020-09-25 00:34 UTC, opbld34 commented
Docs Build status updates of commit _[36f3f75](https://github.com/braedenp-msft/microsoft-graph-docs/commits/36f3f751e682f4c07f81a5d07ac595335ebf967c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-2c60ef23-3b372ffd)
[api-reference/beta/api/printer-update.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printer-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-update?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-5d49c585-3b372ffd)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-3b372ffd)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-3b372ffd)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="2c60ef23-3b372ffd"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5d49c585-3b372ffd"></a>
### [api-reference/beta/api/printer-update.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printer-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-3b372ffd"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-3b372ffd"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 145, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 145, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 145, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
  [...]

2020-09-25 00:42 UTC, opbld30 commented
Docs Build status updates of commit _[f8be032](https://github.com/braedenp-msft/microsoft-graph-docs/commits/f8be0321b7d3b456b78b17709f5f9089ee33c883)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-2c60ef23-5bfd9f36)
[api-reference/beta/api/printer-update.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printer-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-update?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-5d49c585-5bfd9f36)
[api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) | [Details](#user-content-563a1b8c-5bfd9f36)
[concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9793) | [Details](#user-content-de0bbbbb-5bfd9f36)
[api-reference/beta/toc.yml](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-9793) (graph-rest-beta) |

<a id="2c60ef23-5bfd9f36"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5d49c585-5bfd9f36"></a>
### [api-reference/beta/api/printer-update.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/api/printer-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-5bfd9f36"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-5bfd9f36"></a>
### [concepts/changelog.md](https://github.com/braedenp-msft/microsoft-graph-docs/blob/september-updates-2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 48, Column 0**: **[Suggestion-pres [...]

2020-09-25 00:46 UTC, merged