Update azuread overview to link to new tutorial
microsoftgraph/microsoft-graph-docs pull request #9802
Opened 2020-09-04 20:28 UTC by markwahl-msft

The overview didn't include entitlement management, a neighbor feature to access reviews in Azure AD Premium P2, and also now there's also a new tutorial for illustrating how to use entitlement management,

2020-09-04 20:30 UTC, opbld30 commented
Docs Build status updates of commit _[c279fe6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c279fe66a8c6b21dfcbb9e1cb80ff19d52adff68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/azuread-identity-access-management-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/markwahl-msft-patch-3/concepts/azuread-identity-access-management-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/azuread-identity-access-management-concept-overview?branch=pr-en-us-9802) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009042028548087-9802%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X8DQ7Vz9toCLTE9UGjR16fr1QgcsRor77qAWietqDvg%3D&st=2020-09-04T20%3A25%3A02Z&se=2020-10-05T20%3A30%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-08 16:02 UTC, davidmu1 approved these changes

2020-09-09 00:38 UTC, angelgolfer-ms commented on concepts/azuread-identity-access-management-concept-overview.md
> +
@markwahl-msft , @davidmu1 , does the following overlook anything pertinent at this "Learn" level:
```
[Create access packages](tutorial-access-package-api.md) for users to self-serve access needs to groups, applications, and SharePoint sites.
```

2020-09-09 00:47 UTC, angelgolfer-ms commented on concepts/azuread-identity-access-management-concept-overview.md
> +
I rephrased the original because this conceptual overview is meant to list at a high level the value of the identity and access API. Seems to me the focus should be the value of the functionality and therefore should start with the action - what users can do using the API.
Per [Microsoft Voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28939), we're also supposed to trim all unnecessary words, like "You can" in the preceding H3 sections, hence I didn't start with that phrase :-)

2020-09-09 00:55 UTC, angelgolfer-ms requested changes
Hi @markwahl-msft , since this update goes to the more important conceptual overview, do you mind rephrasing the sentence to put focus on the value (what task customers can get done), rather than on the existence of a tutorial that shows how to achieve the value? We can implicitly blend in the tutorial with a link to it.

2020-11-16 15:01 UTC, closed without merging