Conversationmember resource
microsoftgraph/microsoft-graph-docs pull request #9810
Opened 2020-09-05 04:51 UTC by Mahesh2516

Added methods table to the file. Please review.

2020-09-05 04:53 UTC, opbld34 commented
Docs Build status updates of commit _[1711209](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17112097f8a67bcdb2467062a7a1b3f78d5ff01f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-fd5db94d-9164dc50)

<a id="fd5db94d-9164dc50"></a>
### [api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md)
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009050451432437-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oIY1hkDntJeTMWCAJXs%2BsanDt9n%2F8SyOG1kzA3N0ZKc%3D&st=2020-09-05T04%3A48%3A08Z&se=2020-10-06T04%3A53%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-05 21:54 UTC, opbld33 commented
Docs Build status updates of commit _[b3f0562](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3f05627f61d4873b8116d0f8dcad380ccc0a45a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :x:Error | | [Details](#user-content-6f6649a6-a283ed28)
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :x:Error | | [Details](#user-content-ffb7386b-a283ed28)
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :x:Error | | [Details](#user-content-dbc813dc-a283ed28)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :x:Error | | [Details](#user-content-3e26536d-a283ed28)
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :x:Error | | [Details](#user-content-99184e02-a283ed28)

<a id="6f6649a6-a283ed28"></a>
### [api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md)
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-conversation-member-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-conversation-member-javascript-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-conversation-member-objc-snippets.md'.`````
 - **Line 18, Column 54**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 18, Column 165**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Add a conversationMember to a channel.' is duplicated in 'beta/api/conversationmember-add.md(3,14)', 'v1.0/api/conversationmember-add.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="ffb7386b-a283ed28"></a>
### [api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md)
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-conversation-member-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-conversation-member-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-conversation-member-objc-snippets.md'.`````
 - **Line 18, Column 55**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 18, Column 166**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Delete a conversationMember from a channel.' is duplicated in 'beta/api/conversationmember-delete.md(3,14)', 'v1.0/api/conversationmember-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="dbc813dc-a283ed28"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-conversation-member-csharp-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-conversation-member-javascript-snippets.md'.`````
 - **Line 80, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-conversation-member-objc-snippets.md'.`````
 - **Line 14, Column 76**: **[Warning-file-not-found]** `````Invalid file link: '../resources/chat.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve a member of a chat or channel.' is duplicated in 'beta/api/conversationmember-get.md(3,14)', 'beta/api/conversationmember-list.md(3,14)', 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-a283ed28"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-conversation-members-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-conversation-members-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-conversation-members-objc-snippets.md'.`````
 - **Line 14, Column 74**: **[Warning-file-not-found]** `````Invalid file link: '../resources/chat.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate- [...]

2020-09-05 22:34 UTC, opbld33 commented
Docs Build status updates of commit _[91ff5c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91ff5c54207c356b99ce64af0b2cb759054a64f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-2a0fbbc3)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-2a0fbbc3)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-2a0fbbc3"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-2a0fbbc3"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009052232208850-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r6XFTLqBJb9ZpE0%2Beg%2FhL0B%2BOxL%2B0QQ%2F%2FVKcc%2B%2Fb2o4%3D&st=2020-09-05T22%3A29%3A12Z&se=2020-10-06T22%3A34%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-05 23:02 UTC, laujan commented
Hi @Mahesh2516 . Great job on this assignment. I made a few edits:
✔I merged the related files with this so that the links would be valid. 
✔I removed the snippet files. They are generated automatically.
✔I removed the Note block at the top of the files because it only applied to beta files.

As you can see, the PR is still not passing below I have provided the error reasons in this file:  https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=32076&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=8347

Please go to line2 8235 - 8255 and update the files as indicated:

![image](https://user-images.githubusercontent.com/50501194/92314769-23e92600-ef91-11ea-8635-319fc04de076.png)
 
Thank you! 😊

2020-09-07 07:01 UTC, opbld32 commented
Docs Build status updates of commit _[aa7dbab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa7dbab579028e40c2d40f4876fb7adc5b4ef8d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-74903041)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-74903041)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-74903041"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-74903041"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009070700318260-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JMZfDd5FSwFRYe66AgPDAKQmRBclDRVqtXHdza0yd7Q%3D&st=2020-09-07T06%3A56%3A50Z&se=2020-10-08T07%3A01%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-07 11:56 UTC, opbld32 commented
Docs Build status updates of commit _[f36d738](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f36d738ab2b83dce88c1a19218e2baad9ab4fcbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-a97e36f7)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-a97e36f7)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-a97e36f7"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-a97e36f7"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009071155048214-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1g1FPGINTQle49bZc%2B8ONXlb4VTMZ4Y3TYUZHkCwxtc%3D&st=2020-09-07T11%3A51%3A18Z&se=2020-10-08T11%3A56%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 22:57 UTC, opbld34 commented
Docs Build status updates of commit _[571cbd9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/571cbd91878fd17499468cc630e727f8316c3d2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-0d90e1c1)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-0d90e1c1)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-0d90e1c1"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-0d90e1c1"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152256342780-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fp9pOIVSAwTyFBLD6FdmNonI5JUhCs067FnQ0VyUSFs%3D&st=2020-09-15T22%3A52%3A51Z&se=2020-10-16T22%3A57%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 23:19 UTC, opbld31 commented
Docs Build status updates of commit _[24538d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24538d0ae1d31e65a20af013fb32d8967697833a)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-15 23:21 UTC, opbld32 commented
Docs Build status updates of commit _[24538d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24538d0ae1d31e65a20af013fb32d8967697833a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-b062c2f7)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-b062c2f7)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-b062c2f7"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-b062c2f7"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152319396497-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=msFJ%2FLUpc5J3u1v1aMy2soL7%2FRLT8NXjw7IW7aKL2jA%3D&st=2020-09-15T23%3A15%3A59Z&se=2020-10-16T23%3A20%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 23:24 UTC, opbld31 commented
Docs Build status updates of commit _[f87a41a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f87a41a0ef0e062e09f17fe75fa7b079449db375)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-15 23:25 UTC, opbld32 commented
Docs Build status updates of commit _[f87a41a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f87a41a0ef0e062e09f17fe75fa7b079449db375)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-ec61ad3c)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-ec61ad3c)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-ec61ad3c"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-ec61ad3c"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152324154587-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C7mX4encRnwYAEGGWOELzmEWm9NrBzV1cdlQnxJYLE4%3D&st=2020-09-15T23%3A20%3A31Z&se=2020-10-16T23%3A25%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 23:26 UTC, opbld32 commented
Docs Build status updates of commit _[5b2ca45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b2ca450721bae89881529661858c9860c607ef0)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-15 23:27 UTC, opbld30 commented
Docs Build status updates of commit _[5b2ca45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b2ca450721bae89881529661858c9860c607ef0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-bcbd2a44)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-bcbd2a44)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-bcbd2a44"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-bcbd2a44"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152326093974-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aSyeb9aTnE8c87KdBlQiOxwR%2FdT3sx%2B4%2FiLw%2F9seQcw%3D&st=2020-09-15T23%3A22%3A26Z&se=2020-10-16T23%3A27%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 00:05 UTC, opbld34 commented
Docs Build status updates of commit _[1684797](https://github.com/microsoftgraph/microsoft-graph-docs/commits/168479718290764f8f12b7142aafb3e056411c76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-cc27d41b)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-cc27d41b)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-cc27d41b"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-cc27d41b"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160003308735-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WEh%2B46HqqzIGK8FC9n6kWOJMIdd9lBctEoNd61cF%2FFo%3D&st=2020-09-16T00%3A00%3A01Z&se=2020-10-17T00%3A05%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 00:14 UTC, opbld32 commented
Docs Build status updates of commit _[ec1dff4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec1dff44db890ca89e54bd9d2e768ed4af3b3511)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-8721d8d6)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-8721d8d6)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-8721d8d6"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-8721d8d6"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160012411402-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EH4mbQV5SQZeXNswn0YsPPF7LMR8EnpLL8bzT2IvGSM%3D&st=2020-09-16T00%3A09%3A17Z&se=2020-10-17T00%3A14%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 00:22 UTC, opbld32 commented
Docs Build status updates of commit _[32e1649](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32e1649284c5979d0094ed288c8a61f60a2fd45a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-9b3cb8b8)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-9b3cb8b8)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-9b3cb8b8"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-9b3cb8b8"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160021028708-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BTA%2FLMqMRnVujaOGod370nWC044luBpvMt8PK9BoUYU%3D&st=2020-09-16T00%3A17%3A25Z&se=2020-10-17T00%3A22%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 00:37 UTC, opbld33 commented
Docs Build status updates of commit _[9e23be7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e23be7c86021cc51c33c12b633f90ca1abbe7c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-e6fdc5f7)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-e6fdc5f7)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-e6fdc5f7"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-e6fdc5f7"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160036287541-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BbOA56dOnGTNXbX%2Fv%2Bo2edaF9JVAVvai8dDEc5ELH1M%3D&st=2020-09-16T00%3A32%3A48Z&se=2020-10-17T00%3A37%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 00:41 UTC, opbld31 commented
Docs Build status updates of commit _[6368261](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63682610eaba4e3442934d7246e4cacb95413628)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-b72c3fe4)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-b72c3fe4)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-b72c3fe4"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3e26536d-b72c3fe4"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160040100654-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V6CSMfwxde4KaYxVjDJ4c0IOegb49P6v4Jy2C%2BpxXVc%3D&st=2020-09-16T00%3A36%3A37Z&se=2020-10-17T00%3A41%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 09:52 UTC, opbld31 commented
Docs Build status updates of commit _[870f01b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/870f01b4499358b944aee9e063e687a81400be0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-22e8e614)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-22e8e614)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-22e8e614"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="3e26536d-22e8e614"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010950505467-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QZkIFkvGiD%2BU6eJNeNRXtBsRmgSUSxn3Zdl%2BnagwRGs%3D&st=2020-10-01T09%3A47%3A11Z&se=2020-11-01T09%3A52%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 19:15 UTC, laujan commented
@Mahesh2516 per @Lauragra "This PR will require an updates to the v1.0 TOC file and the changelog to list the new operations"

2020-10-02 19:16 UTC, opbld33 commented
Docs Build status updates of commit _[ea6e5ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea6e5ede4ed842f3cda7a5a519286989079e4bc8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-c2b25223)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-c2b25223)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-c2b25223"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="3e26536d-c2b25223"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010021914573597-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E8HVkbZvSrwUSrAwy2JcF8ypQDcqOItlUGCkAdAUcz8%3D&st=2020-10-02T19%3A11%3A24Z&se=2020-11-02T19%3A16%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 19:21 UTC, opbld31 commented
Docs Build status updates of commit _[2cbeaa7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cbeaa748cbc11ffa137b4a5dd06eb1ca9780db3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-2b10ddde)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-2b10ddde)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-2b10ddde"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="3e26536d-2b10ddde"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010021920194054-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7oAIrej10ZF0pmV%2B3P1thLD7AlIDQZzyx%2FDmXlLbDmo%3D&st=2020-10-02T19%3A16%3A42Z&se=2020-11-02T19%3A21%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 19:24 UTC, opbld33 commented
Docs Build status updates of commit _[699b2c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/699b2c5dc4e910132221295f009a3dda60615ff1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-32777867)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-32777867)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-32777867"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="3e26536d-32777867"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of a chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010021923190715-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p9hZfSf%2BjPsJmDAC4k4UjBoMcQuXzmQzhOmM%2FJdNPN0%3D&st=2020-10-02T19%3A19%3A47Z&se=2020-11-02T19%3A24%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 20:19 UTC, opbld33 commented
Docs Build status updates of commit _[c092312](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c09231205d124151e81c483175f2ae7da55269e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010022017467751-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mCS5erJt%2B3Rk0RzlgIbcA%2BlsQpJILd6%2BgK9iUJ%2FXxvs%3D&st=2020-10-02T20%3A14%3A07Z&se=2020-11-02T20%3A19%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 20:20 UTC, opbld31 commented
Docs Build status updates of commit _[f32182d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f32182d7849932762be5e38c29248c440c52d3a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-2782e0c2)
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-2782e0c2)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="dbc813dc-2782e0c2"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="3e26536d-2782e0c2"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve member of chat or channel.' is duplicated in 'v1.0/api/conversationmember-get.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)' with moniker 'graph-rest-1.0'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010022018152513-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KsoUyZRT7kyq9zVr9BCpJ9xJfCG9bFOUWT2sEWYSx0A%3D&st=2020-10-02T20%3A15%3A40Z&se=2020-11-02T20%3A20%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 20:27 UTC, opbld33 commented
Docs Build status updates of commit _[b304ba2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b304ba2e8fc224db5d182507dad2143d529ffd46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010022026097966-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wuiAVMHzgccopJRMirdX9tKVe%2B4%2BqTVVD%2FLKw5gRL8g%3D&st=2020-10-02T20%3A22%3A26Z&se=2020-11-02T20%3A27%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 20:28 UTC, opbld33 commented
Docs Build status updates of commit _[3a64295](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a642952e61ff9e69df81f3897fdf67ee1d74c13)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010022026428653-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=98QZtzr4TgEc6VMU7cDp7HngP%2F5hKHN1p0%2FYS%2Bko55w%3D&st=2020-10-02T20%3A23%3A51Z&se=2020-11-02T20%3A28%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-05 05:14 UTC, opbld31 commented
Docs Build status updates of commit _[c8d22d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8d22d0d8ef9166aeb2a590fdb14de6b5f66021b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-697fed57)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-697fed57"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 20, Column 37**: **[Warning-file-not-found]** `````Invalid file link: 'conversationmember.md'.`````
 - **Line 20, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 20, Column 171**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 20, Column 219**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 20, Column 267**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 20, Column 325**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=gra [...]

2020-10-05 05:19 UTC, opbld32 commented
Docs Build status updates of commit _[8da65c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8da65c11ba6533c3e4738b57396af563e9a2d559)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-4f462926)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-4f462926"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 20, Column 37**: **[Warning-file-not-found]** `````Invalid file link: 'conversationmember.md'.`````
 - **Line 20, Column 89**: **[Warning-file-not-found]** `````Invalid file link: 'aaduserconversationmember.md'.`````
 - **Line 20, Column 186**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 20, Column 237**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 20, Column 285**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 20, Column 333**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 20, Column 391**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific ve [...]

2020-10-05 19:50 UTC, laujan commented
Please fix file paths:
![image](https://user-images.githubusercontent.com/50501194/95125173-670df480-0709-11eb-91d8-9cd5ec936720.png)

2020-10-06 05:08 UTC, opbld31 commented
Docs Build status updates of commit _[c60ea94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c60ea94a332e81a11b49d062339b260b4e629937)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-2476eead)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-2476eead"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 27, Column 222**: **[Warning-file-not-found]** `````Invalid file link: '../graph/api/conversationmember-list'.`````
 - **Line 27, Column 276**: **[Warning-file-not-found]** `````Invalid file link: '../graph/api/conversationmember-get'.`````
 - **Line 27, Column 327**: **[Warning-file-not-found]** `````Invalid file link: '../graph/api/conversationmember-add'.`````
 - **Line 27, Column 378**: **[Warning-file-not-found]** `````Invalid file link: '../graph/api/conversationmember-update'.`````
 - **Line 27, Column 439**: **[Warning-file-not-found]** `````Invalid file link: '../graph/api/conversationmember-delete'.`````
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion [...]

2020-10-06 05:14 UTC, opbld31 commented
Docs Build status updates of commit _[fbb1613](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbb16132d99e4c8b222d903db763afac36d25b43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-71b4be66)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-71b4be66"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 27, Column 222**: **[Warning-file-not-found]** `````Invalid file link: '..graph//api/conversationmember-list'.`````
 - **Line 27, Column 276**: **[Warning-file-not-found]** `````Invalid file link: '..graph//api/conversationmember-get'.`````
 - **Line 27, Column 327**: **[Warning-file-not-found]** `````Invalid file link: '..graph//api/conversationmember-add'.`````
 - **Line 27, Column 378**: **[Warning-file-not-found]** `````Invalid file link: '..graph//api/conversationmember-update'.`````
 - **Line 27, Column 439**: **[Warning-file-not-found]** `````Invalid file link: '..graph//api/conversationmember-delete'.`````
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion [...]

2020-10-06 05:22 UTC, opbld32 commented
Docs Build status updates of commit _[b45b81f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b45b81fb211d1a7f4b365b48d49752b2d7390894)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f9ad40a2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :warning:Warning | | [Details](#user-content-de0bbbbb-f9ad40a2)

<a id="f9ad40a2"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

<a id="de0bbbbb-f9ad40a2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 27, Column 222**: **[Warning-file-not-found]** `````Invalid file link: '..graph/api/conversationmember-list'.`````
 - **Line 27, Column 275**: **[Warning-file-not-found]** `````Invalid file link: '..graph/api/conversationmember-get'.`````
 - **Line 27, Column 325**: **[Warning-file-not-found]** `````Invalid file link: '..graph/api/conversationmember-add'.`````
 - **Line 27, Column 375**: **[Warning-file-not-found]** `````Invalid file link: '..graph/api/conversationmember-update'.`````
 - **Line 27, Column 435**: **[Warning-file-not-found]** `````Invalid file link: '..graph/api/conversationmember-delete'.`````
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a War [...]

2020-10-06 05:26 UTC, opbld31 commented
Docs Build status updates of commit _[1843f60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1843f607c936e80a42802263d6729b873786ed43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-5a739322)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-5a739322"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** [...]

2020-10-08 01:06 UTC, Lauragra commented on api-reference/v1.0/resources/conversationmember.md
> +## Methods
This resource is not currently exposed in the TOC in beta. If we're going to expose it in v1.0, we should do the same in beta. In beta, the conversationMember methods are exposed under Teamwork/Chat. Do these methods need to be exposed there as well?

2020-10-08 01:08 UTC, Lauragra commented on api-reference/v1.0/resources/aaduserconversationmember.md
> +## Methods
This resource is not exposed in the TOC in beta. If we expose it in v1.0, we should do the same in beta. Also, the resource has the same child methods as conversationMember; why do we need to expose twice? Is there any difference in how to perform the operations depending on whether the user is or isn't in Azure AD?

2020-10-08 01:10 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +      - name: Conversation member
We're exposing these under Groups and not under Teamwork. In beta, the methods are exposed under Teamwork but as part of the Chat resource rather than conversationMember. Please clear up the discrepancy - do they need to be exposed in both places, in beta and v1.0?

2020-10-08 01:10 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +      - name: Aaduser conversation member
If we keep this entry in the TOC, we should use the friendly name, "Azure AD user conversation member".

2020-10-08 01:11 UTC, Lauragra requested changes
Please review editorial comments.

2020-10-08 01:12 UTC, Lauragra commented
@nkramer , @laujan , @Mahesh2516 , please take a look at the comments on this PR and see if you can help clear up some of the discrepancies/confusion. Thanks.

2020-10-08 01:15 UTC, Lauragra commented on api-reference/v1.0/api/conversationmember-update.md
> +# [HTTP](#tab/http)
Remove.

2020-10-08 01:15 UTC, Lauragra commented on api-reference/v1.0/api/conversationmember-update.md
> +# [C#](#tab/csharp)
Remove the SDK snippets - they'll get added via automation.

2020-10-08 01:15 UTC, opbld30 commented
Docs Build status updates of commit _[ca59646](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca5964657096b493acdf13bf7b23802928b616f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-7819ad0a)
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-7819ad0a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=g [...]

2020-10-08 18:03 UTC, laujan commented on api-reference/v1.0/resources/conversationmember.md
> +## Methods
@nkramer can you please clarify? Thanks.

2020-10-08 19:51 UTC, nkramer commented on api-reference/v1.0/resources/aaduserconversationmember.md
> +## Methods
No, there's no real difference, but are users really expected to walk the inheritance hierarchy to figure out all the applicable methods? I think we'll get a slew of confused users if we do that.

2020-10-08 19:52 UTC, nkramer commented on api-reference/v1.0/resources/conversationmember.md
> +## Methods
We should add the resource to both TOCs. See previous comment about whether we want to include these methods in both resource pages.

2020-10-08 19:53 UTC, nkramer commented on api-reference/v1.0/toc.yml
> +      - name: Conversation member
Groups is the wrong place, please fix.

2020-10-09 05:12 UTC, opbld34 commented
Docs Build status updates of commit _[17d9994](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17d9994f28cce7c3ea5ab5fc16da1f5c73bb4055)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f6fd8f82)

<a id="f6fd8f82"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010090512210611-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=upHkUJD3nkKOXaJn9GM9cw2DjPxQH%2BH0AOYjLy0J8yk%3D&st=2020-10-09T05%3A07%3A51Z&se=2020-11-09T05%3A12%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-09 05:36 UTC, opbld34 commented
Docs Build status updates of commit _[7d87e94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d87e94827bcb6d31197dfeff1fb271511d7bd56)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3711f064)

<a id="3711f064"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010090536284572-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rfb1kBEr7vuQ2DDmvBODw9S%2Fgp2zYeHDs8hxOsg%2FPww%3D&st=2020-10-09T05%3A31%3A55Z&se=2020-11-09T05%3A36%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-09 06:19 UTC, opbld34 commented
Docs Build status updates of commit _[6f80daa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f80daa3435ef05388eefc2bd052351dc1a5743f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-896352e6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-9810) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-896352e6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specif [...]

2020-10-09 06:44 UTC, Mahesh2516 commented on api-reference/v1.0/api/conversationmember-update.md
> +# [C#](#tab/csharp)
Removed SDK snippets.

2020-10-09 06:45 UTC, Mahesh2516 commented on api-reference/v1.0/toc.yml
> +      - name: Aaduser conversation member
Changed the name to "Azure AD user conversation member".

2020-10-14 10:36 UTC, opbld31 commented
Docs Build status updates of commit _[d413aba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d413aba8c1a6ebaddfdb059ac700b54a7797ace8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :x:Error | | [Details](#user-content-99184e02-3da276db)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-3da276db)

<a id="99184e02-3da276db"></a>
### [api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md)
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-conversation-member-csharp-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-conversation-member-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-conversation-member-objc-snippets.md'.`````

<a id="de0bbbbb-3da276db"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line  [...]

2020-10-14 10:49 UTC, opbld30 commented
Docs Build status updates of commit _[f4e4e3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4e4e3f71e729e5ac52a05195bba5d9d953fded7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-ca56c5ce)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-9810) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-ca56c5ce"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - [...]

2020-10-15 04:53 UTC, Mahesh2516 commented on api-reference/v1.0/resources/conversationmember.md
> +## Methods
Added resource to both TOCs, beta and v1.0.

2020-10-15 05:00 UTC, opbld33 commented
Docs Build status updates of commit _[b7aa7b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7aa7b0c5cc87344036ca6b56d41978b6f3e7978)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-494d7944)

<a id="494d7944"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010150459517054-9810%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5cTELxav5f%2B04X%2Flu82i71VxYdWKta8i7LcmGHl257E%3D&st=2020-10-15T04%3A55%3A18Z&se=2020-11-15T05%3A00%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-15 05:06 UTC, opbld30 commented
Docs Build status updates of commit _[7c89bd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c89bd0617ccc439ef0ee9781db16a4487140edf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9810) | [Details](#user-content-de0bbbbb-86b1d1de)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-9810) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/api/conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-9810) (>= graph-rest-1.0) |

<a id="de0bbbbb-86b1d1de"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-resource/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - [...]

2020-10-20 18:50 UTC, laujan commented
Hi @Lauragra. This is ready to merge. 🙂

2020-10-20 19:56 UTC, Lauragra commented on api-reference/beta/toc.yml
> +      - name: Conversation member
I think that you'll want to nest Conversation member and aadUserConversationMember under the Teamwork node.

2020-10-20 20:02 UTC, Lauragra requested changes
Please sort out the right TOC structure and ensure that the TOC is consistent for beta and v1.0, per comments.

2020-10-21 06:03 UTC, Mahesh2516 commented on api-reference/beta/toc.yml
> +      - name: Conversation member
Conversation member and aadUserConversationMember are placed under the Teamwork node.

2020-10-21 16:09 UTC, Lauragra approved these changes

2020-10-21 16:09 UTC, merged