added two event methods to v1.0
microsoftgraph/microsoft-graph-docs pull request #9852
Opened 2020-09-10 09:08 UTC by Bhupesh12Hub

Added documentation for CancelEvent and ForwardEvent on MS-Graph v1

@angelgolfer-ms Please review the PR

2020-09-10 09:09 UTC, opbld31 commented
Docs Build status updates of commit _[9818766](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9818766fff115cefa1c7bbfc4f41693b43110c86)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :x:Error | | [Details](#user-content-890f5e98-3a81bac7)
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :x:Error | | [Details](#user-content-f3268a90-3a81bac7)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :bulb:Suggestion | | [Details](#user-content-3076f571-3a81bac7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-3a81bac7)

<a id="890f5e98-3a81bac7"></a>
### [api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md)
 - **Line 90, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/event-cancel-csharp-snippets.md'.`````
 - **Line 94, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/event-cancel-javascript-snippets.md'.`````
 - **Line 98, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/event-cancel-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'This action allows the organizer of a meeting to send a cancellation message and cancel the event. ' is duplicated in 'beta/api/event-cancel.md(3,14)', 'v1.0/api/event-cancel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="f3268a90-3a81bac7"></a>
### [api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/event-forward-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/event-forward-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/event-forward-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'This action allows the organizer or attendee of a meeting event to forward the ' is duplicated in 'beta/api/event-forward.md(3,14)', 'v1.0/api/event-forward.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3076f571-3a81bac7"></a>
### [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'An event in a calendar.' is duplicated in 'beta/resources/event.md(3,14)', 'v1.0/resources/event.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-3a81bac7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-cancel?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-forward?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Su [...]

2020-09-10 09:35 UTC, opbld34 commented
Docs Build status updates of commit _[3f0a2ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f0a2ede51b2961d92e9eafd5985ca66527991a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) | [Details](#user-content-890f5e98-d301e2b6)
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) | [Details](#user-content-f3268a90-d301e2b6)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) | [Details](#user-content-3076f571-d301e2b6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9852) | [Details](#user-content-de0bbbbb-d301e2b6)
[api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |

<a id="890f5e98-d301e2b6"></a>
### [api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'This action allows the organizer of a meeting to send a cancellation message and cancel the event. ' is duplicated in 'beta/api/event-cancel.md(3,14)', 'v1.0/api/event-cancel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="f3268a90-d301e2b6"></a>
### [api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'This action allows the organizer or attendee of a meeting event to forward the ' is duplicated in 'beta/api/event-forward.md(3,14)', 'v1.0/api/event-forward.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="3076f571-d301e2b6"></a>
### [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=master)]** `````Attribute 'description' with value 'An event in a calendar.' is duplicated in 'beta/resources/event.md(3,14)', 'v1.0/resources/event.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="de0bbbbb-d301e2b6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-cancel?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-forward?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-v1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=mas [...]

2020-11-27 16:21 UTC, opbld30 commented
Docs Build status updates of commit _[923bf06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/923bf06f982bd0e80f0816906b372a1d634acd5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9852) | [Details](#user-content-de0bbbbb-d20876d1)
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |

<a id="de0bbbbb-d20876d1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md)
 - **Line 264, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-cancel?view=graph-rest-v1.0`````
 - **Line 264, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-forward?view=graph-rest-v1.0`````
 - **Line 264, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-v1.0`````
 - **Line 264, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-v1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011271619198174-9852%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BrehnSosXBRwa6cPGYzOuvuRxyZVWGdmZhB2PgI2IrQ%3D&st=2020-11-27T16%3A16%3A04Z&se=2020-12-28T16%3A21%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 02:27 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-cancel.md
> +
Please add this topic to the table of contents, like in beta.

2020-12-09 02:36 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/event.md
> +|[forward](../api/event-forward.md)| None |Lets the organizer or attendee of a meeting event forward the meeting request to a new recipient.|
Please reorder the rows for the cancel and forward methods in this table this way. Please do the same for the beta event.md topic as well.

List events
Create event
Get event
Update
Delete
Get delta
Forward
Cancel
accept
tentativelyAccept
decline
dismissReminder
snoozeReminder
List instances

2020-12-09 03:06 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-cancel.md
> +
Please delete lines 76, and 89-101 inclusive.
Please also delete the actual snippet files (that end in ...-snippets.md) in this PR, total 6 of them for the cancel and forward methods.
All these lines and files will be autogenerated.
CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55062/Generate-code-snippets?anchor=enabling-auto-generation-of-code-snippets

2020-12-09 03:07 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-forward.md
> +
Please delete lines 73, and 96-108 inclusive.
Please also delete the actual snippet files (that end in ...-snippets.md) in this PR, total 6 of them for the cancel and forward methods.
All these lines and files will be autogenerated after the PR is merged into master.
CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55062/Generate-code-snippets?anchor=enabling-auto-generation-of-code-snippets

2020-12-09 03:14 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Addition | v1.0| Added [cancel](/graph/api/event-cancel?view=graph-rest-v1.0) and [forward](/graph/api/event-forward?view=graph-rest-v1.0) operations to manage [event](/graph/api/resources/event?vie
GLOBAL and line 264:
Generally, when linking to topics in the v1 reference, you don't have to include the version explicitly. OPS would default to the v1 version if the version is not specified.
The way you have linked has 2 issues though:

- Linking to v1 is NOT specifying the query parameter "?view=graph-rest-v1.0", If you must explicitly link to v1, the query parameter is "?view=graph-rest-1.0" without the 'v'.
- In general, whenever you include the "?view=" query parameter now, you have to add "&preserve-view=true". This would fix the issue, if you have noticed the following build message for changelog.md:
"Line 264, Column 1: [Suggestion-preserve-view-not-set] Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-cancel?view=graph-rest-v1.0"
You've got 4 of them for this PR. 

In general, please make sure you fix these issues for your PRs. Soon the Dev Relations team will make these actual warnings, and later on, errors.

2020-12-09 03:16 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Addition | v1.0| Added [cancel](/graph/api/event-cancel?view=graph-rest-v1.0) and [forward](/graph/api/event-forward?view=graph-rest-v1.0) operations to manage [event](/graph/api/resources/event?vie
Related help topic for linking:
https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-specific-versions

2020-12-09 03:17 UTC, angelgolfer-ms commented on concepts/changelog.md
>  | :-------------- | :------------ | :--------------------------------------- |
Please add a corresponding changelog json item to the Microsoft.Exchange.json file.

2020-12-09 03:19 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Addition | v1.0| Added [cancel](/graph/api/event-cancel?view=graph-rest-v1.0) and [forward](/graph/api/event-forward?view=graph-rest-v1.0) operations to manage [event](/graph/api/resources/event?vie
Please add the item to the month (December 2020?) in changelog.md that you expect to be able to incorporate feedback and publish.

2020-12-09 03:39 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub , please see my comments and incorporate them. Let me know if you have any questions!

2020-12-17 06:12 UTC, opbld34 commented
Docs Build status updates of commit _[191b66b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/191b66b43790dc7b067d14b5b63aef0267405927)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9852) | [Details](#user-content-de0bbbbb-61b8e98f)
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |

<a id="de0bbbbb-61b8e98f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md)
 - **Line 101, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 79, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 148, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 149, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 149, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 363, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-cancel?view=graph-rest-v1.0`````
 - **Line 363, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-forward?view=graph-rest-v1.0`````
 - **Line 363, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-v1.0`````
 - **Line 363, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-v1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170610219052-9852%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hHJqztgYmcFXcOibJ7g43gS2d2PVDdCoLlY2Ooqsf6c%3D&st=2020-12-17T06%3A07%3A25Z&se=2021-01-17T06% [...]

2020-12-17 12:19 UTC, opbld32 commented
Docs Build status updates of commit _[cd4d8da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd4d8da0196db8be1fa183e660352c5afe4b93cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9852) | [Details](#user-content-de0bbbbb-7d585a3c)
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-cancel-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/csharp/event-forward-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-cancel-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/javascript/event-forward-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-cancel-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/includes/snippets/objc/event-forward-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |

<a id="de0bbbbb-7d585a3c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md)
 - **Line 101, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 107, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 79, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 153, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 155, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 155, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 368, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-cancel?view=graph-rest-v1.0`````
 - **Line 368, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-forward?view=graph-rest-v1.0`````
 - **Line 368, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-v1.0`````
 - **Line 368, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /gr [...]

2020-12-17 14:31 UTC, opbld31 commented
Docs Build status updates of commit _[7bce013](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bce0134b592901c535dd7fa2102604274ea9683)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9852) | [Details](#user-content-de0bbbbb-c43301b7)
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c43301b7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md)
 - **Line 107, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 113, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-cancel?view=graph-rest-v1.0`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/event-forward?view=graph-rest-v1.0`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-v1.0`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 85, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 159, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 160, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 160, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 161, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 161, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012171430089391-9852%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kG4l%2BvuH30KBZBb%2B7NML8TTWdLYAHY9R2kq88QndeP8%3D&st=2020-12-17T14%3A26%3A54Z&se=2021-01-17T14%3A31%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies li [...]

2020-12-17 16:59 UTC, Bhupesh12Hub commented on api-reference/v1.0/api/event-cancel.md
> +
Done

2020-12-17 16:59 UTC, Bhupesh12Hub commented on api-reference/v1.0/resources/event.md
> +|[forward](../api/event-forward.md)| None |Lets the organizer or attendee of a meeting event forward the meeting request to a new recipient.|
Done

2020-12-17 16:59 UTC, Bhupesh12Hub commented on api-reference/v1.0/api/event-cancel.md
> +
Done

2020-12-17 16:59 UTC, Bhupesh12Hub commented on api-reference/v1.0/api/event-forward.md
> +
Done

2020-12-17 17:00 UTC, Bhupesh12Hub commented on concepts/changelog.md
> +|Addition | v1.0| Added [cancel](/graph/api/event-cancel?view=graph-rest-v1.0) and [forward](/graph/api/event-forward?view=graph-rest-v1.0) operations to manage [event](/graph/api/resources/event?vie
Done

2020-12-17 17:00 UTC, Bhupesh12Hub commented on concepts/changelog.md
>  | :-------------- | :------------ | :--------------------------------------- |
Done

2020-12-17 17:03 UTC, Bhupesh12Hub commented
@angelgolfer-ms i have resolved all the comments, please review.
If everything is good to go we need to push the PR to the merge state.
@Lauragra @Harini84

2020-12-18 05:12 UTC, Harini84 commented
> @angelgolfer-ms i have resolved all the comments, please review.
> If everything is good to go we need to push the PR to the merge state.
> @Lauragra @Harini84

@Bhupesh12Hub 
Please re-request for review and set the label to 'ready to merge' once complete.

2020-12-19 03:01 UTC, Lauragra commented
@Bhupesh12Hub , please resolve the merge conflict. Thanks.

2020-12-19 09:04 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +          "ChangedApiName": "cancel,forward",
Please refer to guidance in the CDK [section](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=guidelines-for-workload-changelog-json-files-only).
Line 7:
This should be "Method", since you're adding a couple of methods.
Line 8:
ChangedApiName should contain one value. That means you should have two separate changdlist records for the cancel and forward methods.

2020-12-19 09:14 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Addition | v1.0| Added [cancel](/graph/api/event-cancel?view=graph-rest-v1.0) and [forward](/graph/api/event-forward?view=graph-rest-v1.0) operations to manage [event](/graph/api/resources/event?vie
Line 20:
Please remember that if you specify the ?view parameter in any site-relative links, you have to include the preserve-view=true parameter.
Alternatively, since you're linking to v1.0 (the default version for the Graph docs on docs.microsoft.com), you can drop the ?view parameter altogether. Clicking a link without the ?view parameter would just go to the default version, and in the Graph docs, v1.0 is the default version.

2020-12-19 09:40 UTC, opbld34 commented
Docs Build status updates of commit _[3e1a646](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e1a646e21a0c710ad16cb0e5aec05a61ef8d8be)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b8bc9729)

<a id="b8bc9729"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190940239353-9852%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a1UsQzmvoK8qaitjtxJVuHPYd%2FqzmY9x9U9UlCuLUEQ%3D&st=2020-12-19T09%3A35%3A43Z&se=2021-01-19T09%3A40%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 09:53 UTC, opbld31 commented
Docs Build status updates of commit _[6aa53ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6aa53ad65e7afd332c9c2dd6e07b2e11ecd49621)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9852) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190951385975-9852%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5F1KujMBbBIMjeyjZx%2FQh4dn7aQWSXNbQ6R0LNc0uhk%3D&st=2020-12-19T09%3A47%3A59Z&se=2021-01-19T09%3A52%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 09:54 UTC, opbld30 commented
Docs Build status updates of commit _[25c7928](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25c7928eef305c5de245ab0f90aefd93352ee65c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190951561590-9852%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UizHx6QI2oVeds2bKVVVU07iz5se%2FCbA25a%2F8bAXFCM%3D&st=2020-12-19T09%3A49%3A37Z&se=2021-01-19T09%3A54%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 10:00 UTC, opbld30 commented
Docs Build status updates of commit _[f2f370a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2f370a6bb7e7d97f3a520916b9b776c9857a427)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-9852) (graph-rest-beta) |
[api-reference/v1.0/api/event-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/api/event-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-forward?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-cancel?view=graph-rest-1.0&branch=pr-en-us-9852) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Event/Cancel_Forward/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9852) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190958511853-9852%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cAQ98L6VEEs7T6k6FjIzrjLXK4%2F0Wnc7V6m35f1o3c4%3D&st=2020-12-19T09%3A55%3A46Z&se=2021-01-19T10%3A00%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 10:05 UTC, merged

2020-12-19 10:06 UTC, angelgolfer-ms commented
@Bhupesh12Hub , please take a look at the commits I did today in this PR to fix the changelog.md and changelog json files. In the interest of time, I chose to do that so that I can merge this PR on this last day to publish for the year.