Authentication Methods API pwdless refresh doc updates
microsoftgraph/microsoft-graph-docs pull request #9870
Opened 2020-09-10 22:52 UTC by andres-canello

2020-09-10 22:54 UTC, opbld34 commented
Docs Build status updates of commit _[e626594](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e626594bfb2c954473387e845bdbea1c971170b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-a5cf0b4c)
[api-reference/beta/api/emailauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/fido2authenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |

<a id="de0bbbbb-a5cf0b4c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=master)]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-no [...]

2020-09-25 05:54 UTC, opbld32 commented
Docs Build status updates of commit _[ce8d1f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce8d1f58bd9914e03f002ba2f70d0c90bdadb8a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-d83b5a36)
[api-reference/beta/api/emailauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/fido2authenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |

<a id="de0bbbbb-d83b5a36"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning i [...]

2020-09-25 19:00 UTC, mmcla approved these changes

2020-09-28 20:51 UTC, davidmu1 commented on api-reference/beta/api/emailauthenticationmethod-create.md
> +Set a user's [email Authentication Method](../resources/emailauthenticationmethod.md) object. Email authentication is a Self-service Password Reset method. A user may only have one email authenticati
```suggestion
Set a user's [emailAuthenticationMethod](../resources/emailauthenticationmethod.md) object. Email authentication is a self-service password reset method. A user may only have one email authentication method.
```

2020-09-28 20:55 UTC, davidmu1 commented on api-reference/beta/api/emailauthenticationmethod-create.md
> +POST /users/{id}/authentication/emailMethods
The example below shows: https://graph.microsoft.com/beta/users/kim@contoso.com/authentication/emailMethods. So , possibly you may want to show here: POST /users/{id | userPrincipalName}/authentication/emailMethods ?

2020-09-28 20:57 UTC, davidmu1 commented on api-reference/beta/api/emailauthenticationmethod-delete.md
> +DELETE /users/{id}/authentication/emailMethods/{id}
Same comment as above.

2020-09-28 20:58 UTC, davidmu1 commented on api-reference/beta/api/emailauthenticationmethod-create.md
> +POST https://graph.microsoft.com/beta/users/kim@contoso.com/authentication/emailMethods
If it's acceptable, it might be better here to use an id.

2020-09-28 20:59 UTC, davidmu1 commented on api-reference/beta/api/emailauthenticationmethod-delete.md
> +DELETE https://graph.microsoft.com/beta/users/kim@contoso.com/authentication/emailMethods/3ddfcfc8-9383-446f-83cc-3ab9be4be18f
Same comment about id.

2020-09-28 22:29 UTC, davidmu1 commented on api-reference/beta/api/emailauthenticationmethod-update.md
> +The following table shows the properties that are required when you create the [emailAuthenticationMethod](../resources/emailauthenticationmethod.md).
```suggestion
The following table shows the properties that are required when you update the [emailAuthenticationMethod](../resources/emailauthenticationmethod.md).
```

2020-09-28 22:31 UTC, davidmu1 commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
> +DELETE /users/{id}/authentication/passwordlessMicrosoftAuthenticatorMethods/{id}
The example shows: DELETE https://graph.microsoft.com/beta/users/kim@contoso.com

2020-09-28 22:33 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethods-overview.md
> +|[fido2authenticationmethod](fido2authenticationmethod.md)|A FIDO2 Security Key can be used by a user to sign-in to Azure AD.|Delete a lost FIDO2 Security Key.|
```suggestion
|[fido2authenticationmethod](fido2authenticationmethod.md)|A FIDO2 Security Key can be used by a user to sign in to Azure AD.|Delete a lost FIDO2 Security Key.|
```

2020-09-28 22:34 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethods-overview.md
> +|[passwordlessmicrosoftauthenticatorauthenticationmethod](passwordlessmicrosoftauthenticatorauthenticationmethod.md)|Microsoft Authenticator Passwordless Phone Sign-in can be used by a user to sign-i
```suggestion
|[passwordlessmicrosoftauthenticatorauthenticationmethod](passwordlessmicrosoftauthenticatorauthenticationmethod.md)|Microsoft Authenticator Passwordless Phone Sign-in can be used by a user to sign in to Azure AD|Delete a Passwordless Phone Sign-in authentication method.|
```

2020-09-28 23:07 UTC, Lauragra commented on api-reference/beta/api/emailauthenticationmethod-create.md
> +---
For create operations, in the file names, we use post, not create.

2020-09-28 23:12 UTC, opbld32 commented
Docs Build status updates of commit _[01bd2f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01bd2f6aa3247ecf7b3f51c6ef7a6fc5a4081228)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c4b212e8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-c4b212e8)

<a id="c4b212e8"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

<a id="de0bbbbb-c4b212e8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsipackagetype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappnotification?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptruleoperationtype?view=graph-rest-1.0 NOTE: This Suggestio [...]

2020-09-29 22:57 UTC, opbld31 commented
Docs Build status updates of commit _[b90bcf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b90bcf1f13c156dcd5b1a7363f4a3ab015f72b68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-07702111)
[api-reference/beta/api/emailauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/fido2authenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |

<a id="de0bbbbb-07702111"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.``` [...]

2020-09-29 22:59 UTC, opbld33 commented
Docs Build status updates of commit _[781fd6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/781fd6ff9dc29a912c3fd6e0294cfb9924aebde2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-ae6ea47a)
[api-reference/beta/api/emailauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/fido2authenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |

<a id="de0bbbbb-ae6ea47a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.``` [...]

2020-09-30 02:36 UTC, opbld34 commented
Docs Build status updates of commit _[44592f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44592f88de432c5d15814fcdc16cbab55fcba89c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-398d65f7)
[api-reference/beta/api/emailauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/fido2authenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |

<a id="de0bbbbb-398d65f7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.``` [...]

2020-09-30 05:00 UTC, andres-canello commented on api-reference/beta/api/emailauthenticationmethod-create.md
> +POST /users/{id}/authentication/emailMethods
Changed all auth methods docs to show that id or UPN can be used.

2020-09-30 07:50 UTC, opbld33 commented
Docs Build status updates of commit _[33d08f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33d08f31b744623509890416c80aa69c40c86204)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-5d50e47a)
[api-reference/beta/api/emailauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/fido2authenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |

<a id="de0bbbbb-5d50e47a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.``` [...]

2020-09-30 07:52 UTC, opbld34 commented
Docs Build status updates of commit _[3f5ca09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f5ca093449e0d02702e40a35766ce348cfff561)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-c2b97aa4)
[api-reference/beta/api/emailauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/fido2authenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |

<a id="de0bbbbb-c2b97aa4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.``` [...]

2020-09-30 07:53 UTC, andres-canello commented on api-reference/beta/api/emailauthenticationmethod-create.md
> +---
done

2020-09-30 07:55 UTC, opbld31 commented
Docs Build status updates of commit _[9e2f958](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e2f95869c6101a3da9ca8d09473ad33b48588e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-97869197)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-09-30 08:05 UTC, opbld30 commented
Docs Build status updates of commit _[87f446a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87f446aa6dbca4aed438ef380ad1ee81b0698f22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-148efdea)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-09-30 08:12 UTC, opbld33 commented
Docs Build status updates of commit _[741ecb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/741ecb19571e9181fea12ab5a48f0f03af0954c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-d25c3116)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-10-02 00:50 UTC, opbld32 commented
Docs Build status updates of commit _[17e8c5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17e8c5d54e63b99aa5cf42a0c518af3df1295a49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-7989dc11)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-10-02 01:04 UTC, opbld32 commented
Docs Build status updates of commit _[4c2fb83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c2fb8354593603ecaa564daa1bb430cd17c2cb0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-544c6909)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-10-05 22:55 UTC, andrewchoi5 approved these changes

2020-10-08 03:18 UTC, opbld32 commented
Docs Build status updates of commit _[70de85d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70de85d5f5d00bf13f6def987e285e4689f61ad7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-6548302f)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-10-08 23:40 UTC, opbld33 commented
Docs Build status updates of commit _[13cd1ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13cd1ff16e8f7c5be79f05b2cfff84ed28804f45)_: 

:clock10: **Pending**: waiting for processors ([55](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 55 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:41 UTC, opbld31 commented
Docs Build status updates of commit _[13cd1ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13cd1ff16e8f7c5be79f05b2cfff84ed28804f45)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a967a02e)

<a id="a967a02e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082339594641-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JXUga4rdTOoz1JLQJbdSzEH5QeGr0OQA5xpWCqPJPmc%3D&st=2020-10-08T23%3A36%3A04Z&se=2020-11-08T23%3A41%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:41 UTC, opbld32 commented
Docs Build status updates of commit _[6533583](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6533583ff8b96b61dc279b83e0eb2500d27e211b)_: 

:clock10: **Pending**: waiting for processors ([50](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 50 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:41 UTC, opbld34 commented
Docs Build status updates of commit _[6533583](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6533583ff8b96b61dc279b83e0eb2500d27e211b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4d56b4fb)

<a id="4d56b4fb"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082341044427-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uYDHwQ%2FdIJQuS%2BEx9RzkiVzEqR7IKXgOHEhUAJCeYaw%3D&st=2020-10-08T23%3A36%3A55Z&se=2020-11-08T23%3A41%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:42 UTC, opbld34 commented
Docs Build status updates of commit _[11f5b8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11f5b8b53aacbede176ffd4d168f4a542fc9603e)_: 

:clock10: **Pending**: waiting for processors ([50](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 50 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:43 UTC, opbld34 commented
Docs Build status updates of commit _[11f5b8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11f5b8b53aacbede176ffd4d168f4a542fc9603e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1ff766f6)

<a id="1ff766f6"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082342151328-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9El8dwgQAHvrBdbW5uUEneDWghhkJBB4%2FXFougvHkX0%3D&st=2020-10-08T23%3A38%3A06Z&se=2020-11-08T23%3A43%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:43 UTC, opbld31 commented
Docs Build status updates of commit _[4fa755d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fa755d538e721d3ee34cfa4fac5a090a5754267)_: 

:clock10: **Pending**: waiting for processors ([51](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 51 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:43 UTC, opbld33 commented
Docs Build status updates of commit _[bad1d05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bad1d0557ff5f14f8287bebafab848e1b06b3e3f)_: 

:clock10: **Pending**: waiting for processors ([51](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 51 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:44 UTC, opbld33 commented
Docs Build status updates of commit _[78e180e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78e180e059daae6c62f93084ca35a912da8249a8)_: 

:clock10: **Pending**: waiting for processors ([55](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 55 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:44 UTC, opbld33 commented
Docs Build status updates of commit _[4fa755d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fa755d538e721d3ee34cfa4fac5a090a5754267)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-064521b2)

<a id="064521b2"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082343036387-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DH3sSx%2BizH%2Ba%2FJ7LFrUDA6Q0GErCV0Nt8YTIaPSJueA%3D&st=2020-10-08T23%3A39%3A50Z&se=2020-11-08T23%3A44%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:45 UTC, opbld31 commented
Docs Build status updates of commit _[78e180e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78e180e059daae6c62f93084ca35a912da8249a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0bdc1a9f)

<a id="0bdc1a9f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082344310023-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sdz1RqzzyVMaARjxG%2Fyi1rghnJ1SBu%2BvjNE5s1zNztk%3D&st=2020-10-08T23%3A40%3A25Z&se=2020-11-08T23%3A45%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[b61f153](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b61f153bafa9fdc79ec65379012c3a85f411f253)_: 

:clock10: **Pending**: waiting for processors ([54](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 54 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:49 UTC, opbld31 commented
Docs Build status updates of commit _[b61f153](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b61f153bafa9fdc79ec65379012c3a85f411f253)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e0d7bccc)

<a id="e0d7bccc"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082349072878-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Odq5yn7oDU9FioWluz21dCB4lf%2FS6QkUf9%2BHSj58N14%3D&st=2020-10-08T23%3A44%3A53Z&se=2020-11-08T23%3A49%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:52 UTC, opbld33 commented
Docs Build status updates of commit _[9ea5b5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ea5b5bc8c114571320ad0f476372977f9dd7cc8)_: 

:clock10: **Pending**: waiting for processors ([52](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 52 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:53 UTC, opbld30 commented
Docs Build status updates of commit _[9ea5b5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ea5b5bc8c114571320ad0f476372977f9dd7cc8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-602ba7cb)

<a id="602ba7cb"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082352141372-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7rP1rN3O1ySDomqyXDESC2g9I4aOdCfHioNgNNDvyu4%3D&st=2020-10-08T23%3A48%3A38Z&se=2020-11-08T23%3A53%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:54 UTC, opbld32 commented
Docs Build status updates of commit _[7260b6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7260b6d9006156fecf6b9befbb9066561a50b95e)_: 

:clock10: **Pending**: waiting for processors ([56](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 56 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:54 UTC, opbld34 commented
Docs Build status updates of commit _[7260b6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7260b6d9006156fecf6b9befbb9066561a50b95e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f56e86cb)

<a id="f56e86cb"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082354222044-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q5J635fEdZyYNUpnc9rR836YVeo8gL%2BVBolUDcWaSVg%3D&st=2020-10-08T23%3A49%3A50Z&se=2020-11-08T23%3A54%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:55 UTC, opbld32 commented
Docs Build status updates of commit _[4d57d19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d57d19410cebfcd25235a9ddd7560c680ff5d76)_: 

:clock10: **Pending**: waiting for processors ([58](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 58 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:56 UTC, opbld33 commented
Docs Build status updates of commit _[4d57d19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d57d19410cebfcd25235a9ddd7560c680ff5d76)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-123da346)

<a id="123da346"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082355249917-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hdcO2F%2FnGPFC0Em2BCXwcsEruO08C26QNLFlwaYzR38%3D&st=2020-10-08T23%3A51%3A03Z&se=2020-11-08T23%3A56%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-08 23:57 UTC, opbld32 commented
Docs Build status updates of commit _[4e0fbba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e0fbba755a1764857daf3247bb2451101f1c73b)_: 

:clock10: **Pending**: waiting for processors ([57](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 57 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:57 UTC, opbld31 commented
Docs Build status updates of commit _[4e0fbba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e0fbba755a1764857daf3247bb2451101f1c73b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0b3036fa)

<a id="0b3036fa"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010082356567198-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ti4kzuxcMuhoNd8TA2ZEM7qH1%2B0ryDCLUa5RJ%2B9K81k%3D&st=2020-10-08T23%3A52%3A38Z&se=2020-11-08T23%3A57%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-09 00:02 UTC, opbld31 commented
Docs Build status updates of commit _[ff26c13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff26c132913c08da3de9afd95cea6e091e2bd912)_: 

:clock10: **Pending**: waiting for processors ([53](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 53 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-09 00:03 UTC, opbld32 commented
Docs Build status updates of commit _[fe7663a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe7663a3373f01c333ae3ed0bad535eb3768923f)_: 

:clock10: **Pending**: waiting for processors ([52](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 52 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-09 00:03 UTC, opbld33 commented
Docs Build status updates of commit _[ff26c13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff26c132913c08da3de9afd95cea6e091e2bd912)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-04ad4de5)

<a id="04ad4de5"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010090002058509-9870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mIggayLMKaNHroj5nEw6PpP5U73xzjCvgfBXHWC3bqU%3D&st=2020-10-08T23%3A58%3A47Z&se=2020-11-09T00%3A03%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-09 00:05 UTC, opbld34 commented
Docs Build status updates of commit _[024982c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/024982ce3b69af7e5b50336621c21419df16b3d7)_: 

:clock10: **Pending**: waiting for processors ([60](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 60 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-09 00:07 UTC, opbld30 commented
Docs Build status updates of commit _[024982c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/024982ce3b69af7e5b50336621c21419df16b3d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-67341d42)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-10-09 00:08 UTC, Lauragra requested changes
Looks good; we just need an update to the DirectoryServices JSON file.

2020-10-09 02:19 UTC, opbld34 commented
Docs Build status updates of commit _[a513799](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a513799bf6ef3537ce8f32fa839cceb41ab6bb61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9870) | [Details](#user-content-de0bbbbb-a18fd7c3)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_updates_test2/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-9870) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthentic [...]

2020-10-09 15:17 UTC, Lauragra approved these changes

2020-10-09 16:57 UTC, merged