Rodriguezd 1149676 ga membership api
microsoftgraph/microsoft-graph-docs pull request #9909
Opened 2020-09-14 05:00 UTC by v-rodriguezd

Created new branch rodriguezd-1149676GAmembershipAPI
Updated the Methods table with the following methods in the resource type file:
-	List members
-	Add members
-	Remove members
-	Change member’s role
-	Get team photo
Removed the following methods from the v1.0 of team.md
-	Publish apps to your organization
-	Add app to team
-	Add tab to channel

2020-09-14 05:01 UTC, opbld34 commented
Docs Build status updates of commit _[dc5cb28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc5cb2842c7905b8672ee0b57280eda8cfb14b9f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :x:Error | | [Details](#user-content-92d0f4c9-e2f618df)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :x:Error | | [Details](#user-content-32cbace2-e2f618df)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :x:Error | | [Details](#user-content-cbae995f-e2f618df)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :warning:Warning | | [Details](#user-content-362f7170-e2f618df)
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-ce1dfa3a-e2f618df)

<a id="92d0f4c9-e2f618df"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 60, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-members-from-team-csharp-snippets.md'.`````
 - **Line 64, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-members-from-team-javascript-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-members-from-team-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="32cbace2-e2f618df"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-conversationmember-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-conversationmember-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-conversationmember-objc-snippets.md'.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/administrativeunit-list-members.md(10,1), beta/api/connectorgroup-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1), v1.0/api/team-list-members.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="cbae995f-e2f618df"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-conversationmember-from--csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-conversationmember-from--javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-conversationmember-from--objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="362f7170-e2f618df"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="ce1dfa3a-e2f618df"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the photo (picture) for a team.' is duplicated in 'beta/api/team-get-photo.md(3,14)', 'v1.0/api/team-get-photo.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009140500221365-9909%5Cworkflow_report.html [...]

2020-09-16 07:43 UTC, opbld33 commented
Docs Build status updates of commit _[21d94c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21d94c5823e7269df2b943e2a3228cb29a1e3d4e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :x:Error | | [Details](#user-content-32cbace2-2bbc9b1c)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :x:Error | | [Details](#user-content-cbae995f-2bbc9b1c)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :warning:Warning | | [Details](#user-content-362f7170-2bbc9b1c)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | | [Details](#user-content-92d0f4c9-2bbc9b1c)
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-ce1dfa3a-2bbc9b1c)

<a id="32cbace2-2bbc9b1c"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-conversationmember-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-conversationmember-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-conversationmember-objc-snippets.md'.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/administrativeunit-list-members.md(10,1), beta/api/connectorgroup-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="cbae995f-2bbc9b1c"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-conversationmember-from--csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-conversationmember-from--javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-conversationmember-from--objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="362f7170-2bbc9b1c"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="92d0f4c9-2bbc9b1c"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="ce1dfa3a-2bbc9b1c"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the photo (picture) for a team.' is duplicated in 'beta/api/team-get-photo.md(3,14)', 'v1.0/api/team-get-photo.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160741599593-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pKuB9N4jI0%2B6F%2FVW9%2F1Sg5urcSnndyfqR80hhFBlTrA%3D&st=2020-09-16T07%3A38%3A08Z&se=2020-10-17T07%3A43%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URL [...]

2020-09-16 07:44 UTC, opbld34 commented
Docs Build status updates of commit _[c38958b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c38958b9b984f5be5dcb7cd038e87b1ccc64aeef)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :x:Error | | [Details](#user-content-cbae995f-f24ca732)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :warning:Warning | | [Details](#user-content-362f7170-f24ca732)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | | [Details](#user-content-92d0f4c9-f24ca732)
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-ce1dfa3a-f24ca732)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | | [Details](#user-content-32cbace2-f24ca732)

<a id="cbae995f-f24ca732"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-conversationmember-from--csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-conversationmember-from--javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-conversationmember-from--objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="362f7170-f24ca732"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="92d0f4c9-f24ca732"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="ce1dfa3a-f24ca732"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the photo (picture) for a team.' is duplicated in 'beta/api/team-get-photo.md(3,14)', 'v1.0/api/team-get-photo.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="32cbace2-f24ca732"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/administrativeunit-list-members.md(10,1), beta/api/connectorgroup-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160743101715-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AInTusZBCFmg%2BWj%2FZ79QLnTL2boBwkUhSPzk%2BJ8edtc%3D&st=2020-09-16T07%3A39%3A15Z&se=2020-10-17T07%3A44%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;catego [...]

2020-09-16 07:45 UTC, opbld32 commented
Docs Build status updates of commit _[b687fa4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b687fa43394de2b2cf69c56da9248c41c14a01b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-e21d0f39)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-e21d0f39)
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-ce1dfa3a-e21d0f39)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-e21d0f39)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-e21d0f39)

<a id="362f7170-e21d0f39"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="92d0f4c9-e21d0f39"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="ce1dfa3a-e21d0f39"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the photo (picture) for a team.' is duplicated in 'beta/api/team-get-photo.md(3,14)', 'v1.0/api/team-get-photo.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="32cbace2-e21d0f39"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/administrativeunit-list-members.md(10,1), beta/api/connectorgroup-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="cbae995f-e21d0f39"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160744204391-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mXbnDRCCX9xQdaut5GEfZuPCKeenO9dWhoPLQkyfYf8%3D&st=2020-09-16T07%3A40%3A36Z&se=2020-10-17T07%3A45%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/chann [...]

2020-09-16 09:51 UTC, opbld32 commented
Docs Build status updates of commit _[899200d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/899200d132f42003be84f954a664205b5926c385)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-e339aab2)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-e339aab2)
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-ce1dfa3a-e339aab2)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-e339aab2)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-e339aab2)

<a id="362f7170-e339aab2"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="92d0f4c9-e339aab2"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="ce1dfa3a-e339aab2"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the photo (picture) for a team.' is duplicated in 'beta/api/team-get-photo.md(3,14)', 'v1.0/api/team-get-photo.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="32cbace2-e339aab2"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/administrativeunit-list-members.md(10,1), beta/api/connectorgroup-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="cbae995f-e339aab2"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160950368893-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M0Ip%2FAGyjLf9y4k56CkeEW9krbVzWhz0HWpwT8g1tsc%3D&st=2020-09-16T09%3A46%3A56Z&se=2020-10-17T09%3A51%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/cha [...]

2020-09-17 21:32 UTC, opbld33 commented
Docs Build status updates of commit _[e9e570a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9e570af453b322d2e34bd69f5092577cbdf3e38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-076357c1)
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-ce1dfa3a-076357c1)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-076357c1)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-076357c1)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-076357c1)

<a id="92d0f4c9-076357c1"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="ce1dfa3a-076357c1"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-get-photo.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the photo (picture) for a team.' is duplicated in 'beta/api/team-get-photo.md(3,14)', 'v1.0/api/team-get-photo.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="32cbace2-076357c1"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/administrativeunit-list-members.md(2,8), v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/connectorgroup-list-members.md(10,1), v1.0/api/administrativeunit-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="cbae995f-076357c1"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="362f7170-076357c1"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning in early December, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172131056017-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9mikZhtIn7V29HMu9DN9DCgQaRsiySvRoYYzgl2d%2F0Q%3D&st=2020-09-17T21%3A27%3A19Z&se=2020-10-18T21%3A32%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-20 18:59 UTC, nkramer commented on api-reference/v1.0/api/team-get-photo.md
> +---
Please remove this file, teen photo is not part of team membership and is not in v1.0

2020-09-22 17:02 UTC, laujan approved these changes

2020-09-22 17:02 UTC, opbld34 commented
Docs Build status updates of commit _[e6e4979](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6e49790cc938bda20203e55740e9d94bb2c2779)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-88532258)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-88532258)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-88532258)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-88532258)

<a id="362f7170-88532258"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 41, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-get-photo.md'.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="92d0f4c9-88532258"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="32cbace2-88532258"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/administrativeunit-list-members.md(2,8), v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/connectorgroup-list-members.md(10,1), v1.0/api/administrativeunit-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="cbae995f-88532258"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221701475742-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xhB6TJSm1ijoG9FeNnF4jAy%2Bjr9FCaM1Nf0mIrTSgt0%3D&st=2020-09-22T16%3A57%3A56Z&se=2020-10-23T17%3A02%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:20 UTC, opbld31 commented
Docs Build status updates of commit _[282ca49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/282ca49f7dae07d36523cda4d072a9a8cd0b7b5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-f33c1f41)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-f33c1f41)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-f33c1f41)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-f33c1f41)

<a id="92d0f4c9-f33c1f41"></a>
### [api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Remove a conversationMember from a team.' is duplicated in 'beta/api/team-delete-members.md(3,14)', 'v1.0/api/team-delete-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="32cbace2-f33c1f41"></a>
### [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List members - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/administrativeunit-list-members.md(2,8), v1.0/api/directoryrole-list-members.md(2,8), v1.0/api/educationclass-list-members.md(2,8), v1.0/api/group-list-members.md(2,8), v1.0/api/team-list-members.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the conversationMembers of a team.' is duplicated in 'beta/api/team-list-members.md(3,14)', 'v1.0/api/team-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List members' is duplicated with other articles: 'beta/api/connectorgroup-list-members.md(10,1), v1.0/api/administrativeunit-list-members.md(10,1), v1.0/api/directoryrole-list-members.md(10,1), v1.0/api/educationclass-list-members.md(10,1), v1.0/api/group-list-members.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="cbae995f-f33c1f41"></a>
### [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add a new member to a team.' is duplicated in 'beta/api/team-post-members.md(3,14)', 'v1.0/api/team-post-members.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="362f7170-f33c1f41"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md)
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning in early December, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221718447809-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ns8%2BxbnU93mi42%2FjUJuUgyJc%2BO1wNBHYMJKtT630c58%3D&st=2020-09-22T17%3A15%3A29Z&se=2020-10-23T17%3A20%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 01:12 UTC, Lauragra requested changes
This PR requires an update to the changelog and the TOC as well. Thanks.

2020-09-23 07:26 UTC, opbld32 commented
Docs Build status updates of commit _[83f7ff7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83f7ff7129e1b08d31778afc7ef79a4b81b638a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9a06c152)

<a id="9a06c152"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009230726135958-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8HDOeIXsrCWmjxX%2F3dzcjqeAHtvUJTQaxXDlP4pu3tE%3D&st=2020-09-23T07%3A21%3A51Z&se=2020-10-24T07%3A26%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 09:54 UTC, opbld30 commented
Docs Build status updates of commit _[34e2ea7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34e2ea7f2d696c6d7c9686fca21ca7e3a1604777)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-41720736)

<a id="41720736"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009230953577462-9909%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fh7kHbxs5ejUBcCyogMEAJmEFyQxMUBeu%2BYxYfXw%2BAA%3D&st=2020-09-23T09%3A49%3A23Z&se=2020-10-24T09%3A54%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 03:08 UTC, opbld33 commented
Docs Build status updates of commit _[8f73b72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f73b72f1d79783917f87937173f1c620ef9faaa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-793c3aa2)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-793c3aa2)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-793c3aa2)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-793c3aa2)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-793c3aa2)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) |

<a id="de0bbbbb-793c3aa2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 35**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 80**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 128**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0  [...]

2020-09-24 03:16 UTC, opbld34 commented
Docs Build status updates of commit _[c96f7f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c96f7f3dc497db20699a5321c5a77114b2de4414)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-e371ab15)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-e371ab15)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-e371ab15)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-e371ab15)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-e371ab15)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-e371ab15)

<a id="77cfd98e-e371ab15"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml)
 - **Line 4842, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4852, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-list-all-teams.md'.`````

<a id="de0bbbbb-e371ab15"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 35**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 80**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 128**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean  [...]

2020-09-24 03:25 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +        - name: Delete team
For some reason the TOC links don't appear to be working, I'm not sure why. I can't verify the TOC entries on the review site so I'll hold off on publishing this for now.

2020-09-24 05:38 UTC, opbld33 commented
Docs Build status updates of commit _[6accb44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6accb444b6ac879668b3042bfbd6efe87f3fc8c3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-7bec4348)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-7bec4348)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-7bec4348)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-7bec4348)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-7bec4348)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-7bec4348)

<a id="77cfd98e-7bec4348"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml)
 - **Line 4842, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4852, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-list-all-teams.md'.`````

<a id="de0bbbbb-7bec4348"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 35**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 80**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 128**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean  [...]

2020-09-24 18:51 UTC, opbld30 commented
Docs Build status updates of commit _[80c8772](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80c8772ea9bf43a6a5c99e16574e3f975a948418)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-bd8eaa16)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-bd8eaa16)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-bd8eaa16)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-bd8eaa16)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-bd8eaa16)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-bd8eaa16)

<a id="77cfd98e-bd8eaa16"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml)
 - **Line 4834, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/team-delete.md'.`````
 - **Line 4842, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4852, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-list-all-teams.md'.`````

<a id="de0bbbbb-bd8eaa16"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 35**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 80**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 128**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-24 18:53 UTC, laujan commented on api-reference/v1.0/toc.yml
> +        - name: Delete team
Hi @Lauragra I updated the delete team path and now all of the links seems to be working.

2020-09-24 18:57 UTC, laujan approved these changes

2020-09-24 19:02 UTC, laujan approved these changes

2020-09-24 19:03 UTC, laujan commented
Hi @Lauragra: I think this is ready-to-merge.

2020-09-24 23:12 UTC, opbld31 commented
Docs Build status updates of commit _[1b76d37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b76d37fb999e3eb36265a15442dce9a03ad58e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-5a30b9c9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-5a30b9c9)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-5a30b9c9)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-5a30b9c9)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-5a30b9c9)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-5a30b9c9)

<a id="77cfd98e-5a30b9c9"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml)
 - **Line 4834, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/team-delete.md'.`````
 - **Line 4842, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4852, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-list-all-teams.md'.`````

<a id="de0bbbbb-5a30b9c9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in e [...]

2020-09-24 23:21 UTC, opbld34 commented
Docs Build status updates of commit _[a8b245f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8b245f3350495528edded76802112af07ae8793)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-13a32bfc)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-13a32bfc)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-13a32bfc)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-13a32bfc)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-13a32bfc)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-13a32bfc)

<a id="77cfd98e-13a32bfc"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml)
 - **Line 4834, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/team-delete.md'.`````
 - **Line 4850, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-list-all-teams.md'.`````

<a id="de0bbbbb-13a32bfc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a s [...]

2020-09-24 23:34 UTC, opbld32 commented
Docs Build status updates of commit _[40d1188](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40d118801cf8ef806f495fb1e3fa2b9873e8b6a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-ef7352d3)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-ef7352d3)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-ef7352d3)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-ef7352d3)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-ef7352d3)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) |

<a id="de0bbbbb-ef7352d3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0  [...]

2020-09-24 23:36 UTC, opbld33 commented
Docs Build status updates of commit _[912dd78](https://github.com/microsoftgraph/microsoft-graph-docs/commits/912dd78543b539ae0e11ec7ed4fc2533f49ec010)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9909) | [Details](#user-content-de0bbbbb-e3b1dbff)
[api-reference/v1.0/api/team-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-92d0f4c9-e3b1dbff)
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-32cbace2-e3b1dbff)
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/api/team-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-cbae995f-e3b1dbff)
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) | [Details](#user-content-362f7170-e3b1dbff)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-members?view=graph-rest-1.0&branch=pr-en-us-9909) (>= graph-rest-1.0) |

<a id="de0bbbbb-e3b1dbff"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rodriguezd-1149676GAmembershipAPI/concepts/changelog.md)
 - **Line 144, Column 27**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-list-members.md'.`````
 - **Line 144, Column 72**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-post-members.md'.`````
 - **Line 144, Column 120**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-delete-members.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0  [...]

2020-09-24 23:50 UTC, merged