Rajeshwari 1149658gaprivatechannelapi
microsoftgraph/microsoft-graph-docs pull request #9911
Opened 2020-09-14 07:42 UTC by Rajeshwari-v

Placed all files in a single branch Rajeshwari 1149658gaprivatechannelapi and creating a pull request

2020-09-14 07:44 UTC, opbld30 commented
Docs Build status updates of commit _[47ca425](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47ca425e5267b5454ac940c1b97ce073793c0bc7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-0ca311e7)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-0ca311e7)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-0ca311e7)
[api-reference/v1.0/api/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel.md) | :warning:Warning | | [Details](#user-content-34d64f13-0ca311e7)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-0ca311e7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-0ca311e7)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-0ca311e7)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-0ca311e7)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-0ca311e7)

<a id="e9cc4cbd-0ca311e7"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-0ca311e7"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 142, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 146, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-channel-from-user-javascript-snippets.md'.`````
 - **Line 150, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-channel-from-user-objc-snippets.md'.`````

<a id="a68d23a1-0ca311e7"></a>
### [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md)
 - **Line 117, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-delta-1-csharp-snippets.md'.`````
 - **Line 121, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-delta-1-javascript-snippets.md'.`````
 - **Line 125, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-delta-1-objc-snippets.md'.`````
 - **Line 211, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-delta-2-csharp-snippets.md'.`````
 - **Line 215, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-delta-2-javascript-snippets.md'.`````
 - **Line 219, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-delta-2-objc-snippets.md'.`````
 - **Line 306, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-delta-3-csharp-snippets.md'.`````
 - **Line 310, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-delta-3-javascript-snippets.md'.`````
 - **Line 314, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-delta-3-objc-snippets.md'.`````
 - **Line 380, Column 1**: **[E [...]

2020-09-14 09:58 UTC, opbld33 commented
Docs Build status updates of commit _[e798509](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e798509033019ff4a24597433d07dbea391f75a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-1a06a99a)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-1a06a99a)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-1a06a99a)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-1a06a99a)
[api-reference/v1.0/api/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel.md) | :warning:Warning | | [Details](#user-content-34d64f13-1a06a99a)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-1a06a99a)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-1a06a99a)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-1a06a99a)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-1a06a99a)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-1a06a99a)

<a id="e9cc4cbd-1a06a99a"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-1a06a99a"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-1a06a99a"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 142, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 146, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-channel-from-user-javascript-snippets.md'.`````
 - **Line 150, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-channel-from-user-objc-snippets.md'.`````

<a id="a68d23a1-1a06a99a"></a>
### [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md)
 - **Line 117, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?br [...]

2020-09-14 10:09 UTC, opbld32 commented
Docs Build status updates of commit _[4f318d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f318d8e427a137ef2ea0767dc3a7ecb26b17355)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-f682ec70)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-f682ec70)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-f682ec70)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-f682ec70)
[api-reference/v1.0/api/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel.md) | :warning:Warning | | [Details](#user-content-34d64f13-f682ec70)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-f682ec70)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-f682ec70)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-f682ec70)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-f682ec70)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-f682ec70)

<a id="e9cc4cbd-f682ec70"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-f682ec70"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-f682ec70"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 145, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-channel-from-user-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-channel-from-user-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a68d23a1-f682ec7 [...]

2020-09-14 10:15 UTC, opbld30 commented
Docs Build status updates of commit _[ad0251a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad0251a1268cc94d7fbb80861dd308b2f06d4cf8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-019a8dd1)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-019a8dd1)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-019a8dd1)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-019a8dd1)
[api-reference/v1.0/api/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel.md) | :warning:Warning | | [Details](#user-content-34d64f13-019a8dd1)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-019a8dd1)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-019a8dd1)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-019a8dd1)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-019a8dd1)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | | [Details](#user-content-647c6e05-019a8dd1)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-019a8dd1)

<a id="e9cc4cbd-019a8dd1"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-019a8dd1"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-019a8dd1"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 145, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-channel-from-user-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-channel-from-user-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create ne [...]

2020-09-14 10:22 UTC, opbld34 commented
Docs Build status updates of commit _[a8293a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8293a8065ae0bcc79a176e9f3519c37a17789a5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-5d25373a)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-5d25373a)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-5d25373a)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-5d25373a)
[api-reference/v1.0/api/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel.md) | :warning:Warning | | [Details](#user-content-34d64f13-5d25373a)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-5d25373a)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-5d25373a)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-5d25373a)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-5d25373a)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | | [Details](#user-content-b6744499-5d25373a)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | | [Details](#user-content-647c6e05-5d25373a)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-5d25373a)

<a id="e9cc4cbd-5d25373a"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-5d25373a"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-5d25373a"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 145, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-channel-from-user-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-prac [...]

2020-09-14 10:30 UTC, opbld31 commented
Docs Build status updates of commit _[a5556cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5556cb3b70da517048d53a584cee74512429cc9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-d0fc4249)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-d0fc4249)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-d0fc4249)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-d0fc4249)
[api-reference/v1.0/api/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel.md) | :warning:Warning | | [Details](#user-content-34d64f13-d0fc4249)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-d0fc4249)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-d0fc4249)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-d0fc4249)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-d0fc4249)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | | [Details](#user-content-73e72898-d0fc4249)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | | [Details](#user-content-b6744499-d0fc4249)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | | [Details](#user-content-647c6e05-d0fc4249)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-d0fc4249)

<a id="e9cc4cbd-d0fc4249"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-d0fc4249"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-d0fc4249"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 145, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master) [...]

2020-09-14 10:38 UTC, opbld34 commented
Docs Build status updates of commit _[fd6cf9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd6cf9a7670d3b8741967224353e8aeb076e6ffa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-a6d8f095)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-a6d8f095)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-a6d8f095)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-a6d8f095)
[api-reference/v1.0/api/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel.md) | :warning:Warning | | [Details](#user-content-34d64f13-a6d8f095)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-a6d8f095)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-a6d8f095)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-a6d8f095)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-a6d8f095)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | | [Details](#user-content-73e72898-a6d8f095)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | | [Details](#user-content-b6744499-a6d8f095)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | | [Details](#user-content-647c6e05-a6d8f095)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-a6d8f095)

<a id="e9cc4cbd-a6d8f095"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-a6d8f095"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-a6d8f095"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 145, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master) [...]

2020-09-14 13:28 UTC, opbld31 commented
Docs Build status updates of commit _[19b62e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19b62e665b6ff68cd445daa6d0538e8edf5dca2d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-e9cc4cbd-49964c54)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-49964c54)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :x:Error | | [Details](#user-content-13aebb72-49964c54)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/chatmessage-delta.md) | :x:Error | | [Details](#user-content-a68d23a1-49964c54)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | | [Details](#user-content-2d408648-49964c54)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-49964c54)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/chatmessage.md) | :warning:Warning | | [Details](#user-content-0db4f65f-49964c54)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-92c9a2cb-49964c54)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | | [Details](#user-content-73e72898-49964c54)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | | [Details](#user-content-b6744499-49964c54)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | | [Details](#user-content-647c6e05-49964c54)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-message.md) | :bulb:Suggestion | | [Details](#user-content-72f5c4e8-49964c54)

<a id="e9cc4cbd-49964c54"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-channel-messages-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-channel-messages-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-channel-messages-objc-snippets.md'.`````
 - **Line 16, Column 44**: **[Warning-file-not-found]** `````Invalid file link: 'channel-list-messagereplies.md'.`````
 - **Line 16, Column 106**: **[Warning-file-not-found]** `````Invalid file link: 'channel-get-messagereply.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of messages (without the replies) in a channel of a team. To get the replies for a message, call the list message replies or the get message reply API. ' is duplicated in 'beta/api/channel-list-messages.md(3,14)', 'v1.0/api/channel-list-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-49964c54"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-49964c54"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 145, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-channel-from-user-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-channel-from-user-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/incl [...]

2020-09-15 05:24 UTC, opbld31 commented
Docs Build status updates of commit _[6b9408a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b9408acddac0dd7c400c6b89ba5f4058ec64957)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7881b30b)

<a id="7881b30b"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009150524331293-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=URi3VME0Yn5Rosnc4pyR1Ygqbo3%2B2GtBXiDo6TSPwIc%3D&st=2020-09-15T05%3A19%3A57Z&se=2020-10-16T05%3A24%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 07:44 UTC, opbld31 commented
Docs Build status updates of commit _[4afdcc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4afdcc818265060868407831a349d8f5a1f844c9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4b2973e6)

<a id="4b2973e6"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160743318833-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=otJ9Ext8smOsh2VmaqVwE8ZbZidZGKo2EoRQRQMokOg%3D&st=2020-09-16T07%3A39%3A00Z&se=2020-10-17T07%3A44%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 07:48 UTC, opbld33 commented
Docs Build status updates of commit _[b52b7e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b52b7e3bc3664a8f00689738db586e8f65897514)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f027344d)

<a id="f027344d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160747537239-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iG3Qbi%2BezCX7XTp3ZI%2BBR0iNDkE8HSlXHACrQUuFLVI%3D&st=2020-09-16T07%3A43%3A18Z&se=2020-10-17T07%3A48%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 07:56 UTC, opbld34 commented
Docs Build status updates of commit _[0f5f551](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f5f551977a372bf5d99f592f6f8ba17c997cc67)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9de87f11)

<a id="9de87f11"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160755451869-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xyh0grSQq2XCNlQH1Zei%2F3dydrQYkDuTRg8NKVrnmkA%3D&st=2020-09-16T07%3A51%3A13Z&se=2020-10-17T07%3A56%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 08:28 UTC, opbld34 commented
Docs Build status updates of commit _[6100deb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6100deb01eb543762144af9dffeb88b1a45899a0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-04ed14df)

<a id="04ed14df"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160827498877-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ynsIM9N1fUy1fo0Jju1A2weZOwOGCRaU%2FBMI2mML6kI%3D&st=2020-09-16T08%3A23%3A14Z&se=2020-10-17T08%3A28%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 08:32 UTC, opbld34 commented
Docs Build status updates of commit _[3859964](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38599646054b621ef42ae578c2d478ab158d45b1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a6d54208)

<a id="a6d54208"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160831549725-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OGWIyCHFBqU35kDhoEOVzgyr1vTEBg3RpjVE5ltKd4E%3D&st=2020-09-16T08%3A27%3A20Z&se=2020-10-17T08%3A32%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 08:35 UTC, opbld32 commented
Docs Build status updates of commit _[204aeac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/204aeac31eb1d724bcebf85581c0a4e76e42c6fe)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-25cb0fcb)

<a id="25cb0fcb"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160835033254-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GPk8hqxlp1yTY0KgUcvJgNZCu%2FTKync%2FxMjge5IHfuc%3D&st=2020-09-16T08%3A30%3A32Z&se=2020-10-17T08%3A35%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 08:40 UTC, opbld31 commented
Docs Build status updates of commit _[2423e68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2423e68f99224a664063f05c68dc87abda225e7f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-04b26c5a)

<a id="04b26c5a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160840244801-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1PMKGRyf%2BwM3k9ICaPC%2FYwmXT%2BZgsLzmXwbeSZV5CvM%3D&st=2020-09-16T08%3A35%3A51Z&se=2020-10-17T08%3A40%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 08:43 UTC, opbld32 commented
Docs Build status updates of commit _[a6ff176](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6ff1761535605a91c0b34f495500b4a5b3f929a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-807d1cb1)

<a id="807d1cb1"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160842430201-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fJLr7BUfKrF4erkMVEx7TYb8PDvnx5uXKjBhOYmD4PY%3D&st=2020-09-16T08%3A38%3A15Z&se=2020-10-17T08%3A43%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 08:46 UTC, opbld33 commented
Docs Build status updates of commit _[18ea1e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18ea1e4f693b8967dd677733a354354449cd912a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-93b3a953)

<a id="93b3a953"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160845402917-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jo23f%2FCL4y%2FJsdQcH3B4e8QyehASUZxXgZfVQvxgJ7Y%3D&st=2020-09-16T08%3A41%3A06Z&se=2020-10-17T08%3A46%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 08:51 UTC, opbld34 commented
Docs Build status updates of commit _[c180b0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c180b0a547daa286a4d33d3d7db955b97137b2c0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-026db8d4)

<a id="026db8d4"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160850023131-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Dx9IDReuQMonMemLfPcdeJzYKWtSurDuG7cTs34nsog%3D&st=2020-09-16T08%3A46%3A02Z&se=2020-10-17T08%3A51%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-20 19:10 UTC, opbld31 commented
Docs Build status updates of commit _[fa37b0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa37b0c00a61818d09c9854378be490c5bcdac3a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-eca87c6d)

<a id="eca87c6d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009201909480920-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VAAqQfCs03pFPYf%2B94ky%2FT5pzK3f7irfhNre6uUQxm0%3D&st=2020-09-20T19%3A05%3A13Z&se=2020-10-21T19%3A10%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-20 19:16 UTC, opbld31 commented
Docs Build status updates of commit _[49eda1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49eda1c9e4e81fcf46378f8da0ecfc0f6e039396)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5bc56df8)

<a id="5bc56df8"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009201915404713-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W5wAlfkJjlMoWfWIW9kjx0eu5iMtKCFNXzhr7kNYVfM%3D&st=2020-09-20T19%3A11%3A05Z&se=2020-10-21T19%3A16%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-20 19:18 UTC, opbld33 commented
Docs Build status updates of commit _[1d94891](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d948910ad688c04abc5aa0f889ab4547306b936)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-67ae21ef)

<a id="67ae21ef"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009201917552634-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qo7y0t41GYGweSor8afBNsOgVJGCFUCFHHPNo6mkZL4%3D&st=2020-09-20T19%3A13%3A20Z&se=2020-10-21T19%3A18%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-20 19:18 UTC, nkramer requested changes

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-delete.md
>  # [C#](#tab/csharp)
I don't think this is the right way to handle snippets that have been translated yet, I think you need to delete a header as well. Laura Graham would know for sure.

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-list-messages.md
> +---
Please delete this file, it's not part of this feature.

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-list.md
> +author: "clearab"
Andrew Clear is definitely not the author :)

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-list.md
> -doc_type: apiPageType
What's wrong with doc_type apiPageType?

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-patch.md
> +|Application | ChannelSettings.Edit.Group*, ChannelSettings.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All |
RSC Is not supported in v1 yet

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-post-message.md
> +---
Didn't we already have a doc for this? The API is not new.

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-post-messagereply.md
> -[!INCLUDE [sample-code](../includes/snippets/csharp/post-reply-message-csharp-snippets.md)]
Why make changes here?

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-post-messages.md
> ----
If I'm reading this diff right, you didn't delete the file you just removed all the lines from the file.

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/channel-post.md
> +|Application | Channel.Create.Group*, Channel.Create, Group.ReadWrite.All, Directory.ReadWrite.All, Teamwork.Migrate.All|
Again, no RSC support yet

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/chatmessage-delta.md
> +---
Please delete this file, it's not available in v1

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/api/driveitem-get.md
>  GET /me/drive/root
Why are there edits to this file?

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/resources/channel.md
> +
The only change here is whitespace in the raw markup -- what's the point?

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/resources/channel.md
> -|[List tabs](../api/teamstab-list.md) | [teamsTab](teamstab.md) | Lists tabs pinned to a channel.|
Do not remove the tabs APIs.

2020-09-20 19:18 UTC, nkramer commented on api-reference/v1.0/resources/channel.md
> +|@microsoft.graph.channelCreationMode|string|Indicates that the channel is in migration state and is currently being used for migration purposes. It accepts one value: `migration`.|
Not available in V1

2020-09-20 19:40 UTC, opbld32 commented
Docs Build status updates of commit _[4d63dca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d63dca234c95b4019102421d5a41d92432417a0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5ccb4868)

<a id="5ccb4868"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009201940142431-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Byf2itqXtWdrFJ%2BTHi7rhd8%2BUB%2B4b76%2BZf83K9YzvZE%3D&st=2020-09-20T19%3A35%3A39Z&se=2020-10-21T19%3A40%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:50 UTC, opbld33 commented
Docs Build status updates of commit _[780d721](https://github.com/microsoftgraph/microsoft-graph-docs/commits/780d721f22676f106fe529f0fc7a5e575ab1ec8f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a8e3f2e3)

<a id="a8e3f2e3"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221750075467-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MgiXByyDhvsy3iDP1OeeHO58vMWoIeJC%2BbXc3kVGKLI%3D&st=2020-09-22T17%3A45%3A32Z&se=2020-10-23T17%3A50%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:52 UTC, opbld30 commented
Docs Build status updates of commit _[4011a84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4011a84b5dadff9fcf76b6b94440349bb0538832)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-022eb7af)

<a id="022eb7af"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221752036668-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rkGypsiaPNrU%2FZ91tMJjv7RQEFDsiaKRxpYgn%2FOvn6M%3D&st=2020-09-22T17%3A47%3A30Z&se=2020-10-23T17%3A52%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:53 UTC, opbld34 commented
Docs Build status updates of commit _[05d8d3d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05d8d3d3cbeaf5114abdb9b4b0468bdf8f566cd6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2dbd7fea)

<a id="2dbd7fea"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221752350831-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dIMjK%2BMU50j2x5WU9FOkwNgytYm9425EMniU%2FfCabHA%3D&st=2020-09-22T17%3A47%3A58Z&se=2020-10-23T17%3A52%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:54 UTC, opbld33 commented
Docs Build status updates of commit _[7f656c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f656c49a2bae060a5ceaba1e7f6fb3073b51080)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-60ee2fc3)

<a id="60ee2fc3"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221754038409-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hnwKtivrdkqEAmXYxTt0r1tZDmlI0x%2B%2BiHcmuepULw0%3D&st=2020-09-22T17%3A49%3A28Z&se=2020-10-23T17%3A54%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:55 UTC, opbld30 commented
Docs Build status updates of commit _[4ddf337](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ddf3370d4fadbdf52796c831aa116ca815745e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3ffeeb34)

<a id="3ffeeb34"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221755023032-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VcmznoB%2F01pZs4DSW7vcNwgvVDZHcJRBwfunherUzZw%3D&st=2020-09-22T17%3A50%3A27Z&se=2020-10-23T17%3A55%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:58 UTC, opbld34 commented
Docs Build status updates of commit _[e2a537e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2a537e2bf7596686cb0d2b9c3a3877fca10f97d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b4a620d9)

<a id="b4a620d9"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221756589641-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=brvwuQpv%2FHScMTZGFj4IONBxmHmqMM69t17vsdr9Utg%3D&st=2020-09-22T17%3A53%3A01Z&se=2020-10-23T17%3A58%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 17:59 UTC, opbld31 commented
Docs Build status updates of commit _[11a69fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11a69fdde2c612260efc48f3f3082ad40a369a72)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-752c6f21)

<a id="752c6f21"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221759134220-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A4%2BQNIjdaCQUEf4XX6nQw2cEjlbMsxdmtJ9Fc2eWwdc%3D&st=2020-09-22T17%3A54%3A38Z&se=2020-10-23T17%3A59%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 18:00 UTC, opbld34 commented
Docs Build status updates of commit _[1f09112](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f0911217dd60573d1170555ef33a748a41e865d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a61409e6)

<a id="a61409e6"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221800284758-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m8I4AYqxhacY1M0k%2BLKxY8o18cm4TFbeSQz%2BfaFKwGI%3D&st=2020-09-22T17%3A55%3A53Z&se=2020-10-23T18%3A00%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 18:02 UTC, opbld30 commented
Docs Build status updates of commit _[3d4b930](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d4b9308e89d5195a9d27a28f691dafe0d1535d1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ff9c9555)

<a id="ff9c9555"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221801358442-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eEUhrto%2FNHyIAzrFR9eszvQ0hDERPNeIbTGrH64H%2Bio%3D&st=2020-09-22T17%3A57%3A01Z&se=2020-10-23T18%3A02%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 18:05 UTC, opbld30 commented
Docs Build status updates of commit _[4f5c3c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f5c3c242b7c40ccc05e1365c5691f06895bebc5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d0f7d343)

<a id="d0f7d343"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221805230257-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rdQD6lf00R2LXvc5jA8we29qh9T%2B4iqArFoCjXxdJy8%3D&st=2020-09-22T18%3A00%3A58Z&se=2020-10-23T18%3A05%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 18:06 UTC, opbld31 commented
Docs Build status updates of commit _[fde9555](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fde955574e0d1bb25dd6b40574c95c61c589d74c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dfe723a6)

<a id="dfe723a6"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221806075045-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2Q0qycV26oBA7K60rqc0EjpZf%2B%2BzaMoLkRcIv4mULgs%3D&st=2020-09-22T18%3A01%3A31Z&se=2020-10-23T18%3A06%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 18:10 UTC, opbld34 commented
Docs Build status updates of commit _[01f6897](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01f68979b5cdaa2194c29bde114df6987ba2bdda)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-53c0b43a)

<a id="53c0b43a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221810152584-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gh5o0Jzxbb5zBLNECeszN3pNJW1C9bb1mqZBXEWaIDY%3D&st=2020-09-22T18%3A05%3A40Z&se=2020-10-23T18%3A10%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 18:12 UTC, opbld30 commented
Docs Build status updates of commit _[cc371b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc371b371902f3b9f9ee1df5e97fb01cb9b27bcd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dae09079)

<a id="dae09079"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221811501189-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QAYWF4ypb%2FHiNaPhvFb3UHpyW55XhfzU8Z8jQQf86IU%3D&st=2020-09-22T18%3A07%3A17Z&se=2020-10-23T18%3A12%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 18:37 UTC, opbld30 commented
Docs Build status updates of commit _[61bd183](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61bd1834bcff280e3c79e74ee85405f64fd0d4c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/driveitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-24102820-1714ded4)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-1714ded4)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-1714ded4)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-1714ded4)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-1714ded4)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-1714ded4)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-1714ded4)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="24102820-1714ded4"></a>
### [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/driveitem-get.md)
 - **Line 3, Column 12**: **[Warning-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=master)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````
 - **Line 8, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the metadata for a DriveItem in a Drive by file system path or ID.' is duplicated in 'beta/api/driveitem-get.md(3,14)', 'v1.0/api/driveitem-get.md(8,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 97, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Response''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2d408648-1714ded4"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-delta.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-list-messages.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 31, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 32, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 33, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-post-message.md'.`````
 - **Line 48, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="73e72898-1714ded4"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-1714ded4"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-1714ded4"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a  [...]

2020-09-22 18:48 UTC, opbld30 commented
Docs Build status updates of commit _[2dcdf33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2dcdf338b24c3a0732068bc985393427bbea9c68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-50cafbb9)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-50cafbb9)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-50cafbb9)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-50cafbb9)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-50cafbb9)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-50cafbb9)
[api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/driveitem-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-24102820-50cafbb9)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="2d408648-50cafbb9"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatmessage-delta.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-list-messages.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 31, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 32, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 33, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-post-message.md'.`````
 - **Line 48, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="73e72898-50cafbb9"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-50cafbb9"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-50cafbb9"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-50cafbb9"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-50cafbb9"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2 [...]

2020-09-22 19:04 UTC, opbld32 commented
Docs Build status updates of commit _[175d6d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/175d6d9a74b91b304ebae4fee363be3cac0dee16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-5b2900df)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-5b2900df)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-5b2900df)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-5b2900df)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-5b2900df)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-5b2900df)
[api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/driveitem-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-24102820-5b2900df)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="2d408648-5b2900df"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 39, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="73e72898-5b2900df"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-5b2900df"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-5b2900df"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-5b2900df"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-5b2900df"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="24102820-5b2900df"></a>
### [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/driveitem-get.md)
 - **Line 7, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the metadata for a DriveItem in a Drive by file system path or ID.' is duplicated in 'beta/api/driveitem-get.md(3,14)', 'v1.0/api/driveitem-get.md(7,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 96, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Response''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.cor [...]

2020-09-22 19:08 UTC, opbld34 commented
Docs Build status updates of commit _[e885131](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8851310571f7b5676c883dca01f6c42247cc0ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-e933b548)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-e933b548)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-e933b548)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-e933b548)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-e933b548)
[api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/driveitem-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-24102820-e933b548)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-e933b548)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="73e72898-e933b548"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-e933b548"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-e933b548"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-e933b548"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-e933b548"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="24102820-e933b548"></a>
### [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/driveitem-get.md)
 - **Line 7, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the metadata for a DriveItem in a Drive by file system path or ID.' is duplicated in 'beta/api/driveitem-get.md(3,14)', 'v1.0/api/driveitem-get.md(7,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 96, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=master)]** `````Duplicate heading: 'H2 'Response''. Each heading in an article must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2d408648-e933b548"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221906501258-9911%5Cworkflow_report.html?sv=2016-0 [...]

2020-09-22 19:15 UTC, opbld32 commented
Docs Build status updates of commit _[93eb263](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93eb2634a5faecda67e4e4707eac7391df01b52c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-bcf238c3)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-bcf238c3)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-bcf238c3)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-bcf238c3)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-bcf238c3)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-bcf238c3)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="73e72898-bcf238c3"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-bcf238c3"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-bcf238c3"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-bcf238c3"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-bcf238c3"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2d408648-bcf238c3"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221914250425-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kbj0nZkjex%2FTBfqSAfUGfcD0l81OTjeLWlV%2B7P6SWWQ%3D&st=2020-09-22T19%3A10%3A42Z&se=2020-10-23T19%3A15%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 19:18 UTC, opbld30 commented
Docs Build status updates of commit _[11135a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11135a5917f0346725d2e49175710b7160e70f61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-44387620)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-44387620)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-44387620)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-44387620)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-44387620)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-44387620)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="73e72898-44387620"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-44387620"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-44387620"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-44387620"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-44387620"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2d408648-44387620"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221916530749-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8smXsyBAJuuWxE5cj7sH3iJrhGOe3Q4tdwE129qrsI4%3D&st=2020-09-22T19%3A13%3A10Z&se=2020-10-23T19%3A18%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 01:12 UTC, opbld31 commented
Docs Build status updates of commit _[567abcd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/567abcdd39123ae293c3114aa32eb85ee075a9b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-2ed53bcd)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-2ed53bcd)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-2ed53bcd)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-2ed53bcd)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-2ed53bcd)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-2ed53bcd)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="73e72898-2ed53bcd"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-2ed53bcd"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-2ed53bcd"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-2ed53bcd"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-2ed53bcd"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2d408648-2ed53bcd"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009230110549373-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NFtm69qjX5ZbuXFnerUIhUXYCPsZLuDxV38bMsr6Jgs%3D&st=2020-09-23T01%3A07%3A17Z&se=2020-10-24T01%3A12%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 03:03 UTC, Lauragra commented
@Rajeshwari-v , can you let me know what the intent of this PR is? It looks like in some cases links to snippets are getting removed. Was that intentional?

2020-09-24 18:31 UTC, opbld31 commented
Docs Build status updates of commit _[19b5db0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19b5db044a2524f9c10146923540f423777088d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-9f3d7533)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-9f3d7533)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-9f3d7533)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-9f3d7533)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-9f3d7533)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-9f3d7533)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="73e72898-9f3d7533"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-9f3d7533"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-9f3d7533"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-9f3d7533"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-9f3d7533"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2d408648-9f3d7533"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009241830066579-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wYRB8%2FHYlkpb5fGpdCu%2FaJcR08S%2BW8VzUeMdtiCGi5M%3D&st=2020-09-24T18%3A26%3A34Z&se=2020-10-25T18%3A31%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 21:41 UTC, laujan commented
Hi @Lauragra. I fixed the snippet errors so this PR should be ready-to-merge. ✌

2020-09-24 21:46 UTC, Lauragra commented on api-reference/v1.0/api/channel-delete.md
> -# [C#](#tab/csharp)
Was it intentional to delete the snippets from the topic?

2020-09-24 21:46 UTC, Lauragra commented on api-reference/v1.0/api/channel-delete.md
> +##### Request
This is a regression, the Request and Response headings should be H3s, following from the Example H2.

2020-09-24 21:47 UTC, Lauragra commented on api-reference/v1.0/api/channel-delete.md
> +The following is an example of the response.git stat
The words added to the end of this sentence look like a typo.

2020-09-24 21:48 UTC, Lauragra commented on api-reference/v1.0/api/channel-get.md
> -# [C#](#tab/csharp)
Again, here, the snippets were deleted from the file. Was that intentional?

2020-09-24 21:49 UTC, Lauragra commented on api-reference/v1.0/api/channel-list.md
> -GET https://graph.microsoft.com/v1.0/teams/{id}/channels
The request appears to have been deleted here.

2020-09-25 05:51 UTC, opbld32 commented
Docs Build status updates of commit _[60a0f98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60a0f985f9adc0dd729c0f71947f008f7a298b6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-73e72898-15f84b85)
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-b6744499-15f84b85)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-a9116d3e-15f84b85)
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-647c6e05-15f84b85)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-15f84b85)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-15f84b85)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="73e72898-15f84b85"></a>
### [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete the channel.' is duplicated in 'beta/api/channel-delete.md(3,14)', 'v1.0/api/channel-delete.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="b6744499-15f84b85"></a>
### [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a channel.' is duplicated in 'beta/api/channel-get.md(3,14)', 'v1.0/api/channel-get.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a9116d3e-15f84b85"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve the list of channels in this team.' is duplicated in 'beta/api/channel-list.md(3,14)', 'v1.0/api/channel-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="647c6e05-15f84b85"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the properties of the specified channel.' is duplicated in 'beta/api/channel-patch.md(3,14)', 'v1.0/api/channel-patch.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="13aebb72-15f84b85"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create new channel in a Microsoft Team, as specified in the request body.' is duplicated in 'beta/api/channel-post.md(3,14)', 'v1.0/api/channel-post.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="2d408648-15f84b85"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A channel is a collection of chatMessages within a team. ' is duplicated in 'beta/resources/channel.md(3,14)', 'v1.0/resources/channel.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009250550123175-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jdwOkLP1jOgTKtoKscIL39nCkkwGfCHRl5ppuhncZjg%3D&st=2020-09-25T05%3A46%3A31Z&se=2020-10-26T05%3A51%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-26 23:12 UTC, laujan commented on api-reference/v1.0/api/channel-delete.md
> -# [C#](#tab/csharp)
No, it was a mistake.

2020-09-26 23:26 UTC, laujan commented on api-reference/v1.0/api/channel-get.md
> -# [C#](#tab/csharp)
No, it was a mistake.

2020-09-26 23:33 UTC, opbld34 commented
Docs Build status updates of commit _[5cf39c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cf39c6d57f71e41aefccb922e41edc56d7988fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009262331439320-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6TU4UIfngQYxRVLN1GoroF1l7oANJr1XQDDwDJwEAIY%3D&st=2020-09-26T23%3A28%3A09Z&se=2020-10-27T23%3A33%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-28 17:04 UTC, opbld32 commented
Docs Build status updates of commit _[7620158](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7620158de7dce0c63f37311d1d71de0444af26c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-e259f3de)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="2d408648-e259f3de"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 38, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009281702546455-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PImHeia4nZWfYxr63c%2FIPoaHHlhB9rOfMRiY5HDM6Z0%3D&st=2020-09-28T16%3A59%3A14Z&se=2020-10-29T17%3A04%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-28 17:16 UTC, opbld30 commented
Docs Build status updates of commit _[3c39258](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c39258911de302599de84de4c3b42f354e1e1ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) | [Details](#user-content-2d408648-bd61bb24)
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

<a id="2d408648-bd61bb24"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 38, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009281715106745-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hw%2F%2F96hAYvrbCNSC0Hx%2FumjYVpq1YigAIp7Y7aUMnh8%3D&st=2020-09-28T17%3A11%3A21Z&se=2020-10-29T17%3A16%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-28 17:26 UTC, opbld30 commented
Docs Build status updates of commit _[d1b35ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1b35ce95a6b8c6d834966671eabdcea0f2aa0ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009281725222764-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kMpwzeRFVaxVj4LPPftT0Cxq1u9jB3To1%2BdqSMLZu5g%3D&st=2020-09-28T17%3A21%3A37Z&se=2020-10-29T17%3A26%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-30 20:16 UTC, opbld30 commented
Docs Build status updates of commit _[8342014](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8342014ccbabdf2bb0c9377b2ef887532caf2677)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009302014558184-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZubRB1tRkSdXnnNI54o0gwdW%2BX%2F69VcBl60NcfIynrI%3D&st=2020-09-30T20%3A11%3A57Z&se=2020-10-31T20%3A16%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-30 20:21 UTC, opbld32 commented
Docs Build status updates of commit _[797222b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/797222b504eb304c505bc8e680caa37b2647d9f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009302019521735-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TIpDB6tUlJQtlQennrpC1R0Xap2f4N1%2FakQenosK4MY%3D&st=2020-09-30T20%3A16%3A24Z&se=2020-10-31T20%3A21%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-30 20:28 UTC, opbld33 commented
Docs Build status updates of commit _[4b7eb93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b7eb93b996f736c96f139f08e8fcb873e724c57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009302027131054-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Hs1IYGMzyACT9gUWktj%2BvGYkXX05eFbjEbdG14zSaxk%3D&st=2020-09-30T20%3A23%3A30Z&se=2020-10-31T20%3A28%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-30 20:34 UTC, laujan commented
Hi @Lauragra. This is now ready-to-merge. 🙂

2020-10-01 03:04 UTC, opbld34 commented
Docs Build status updates of commit _[546424a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/546424ab798ecbe88dffd263eb0bfcdb2042f3e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010303155816-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3Pdw6MWtpYvZ%2F0F3HqMRHF3mEXsziQIkpP2mcnBiuME%3D&st=2020-10-01T02%3A59%3A36Z&se=2020-11-01T03%3A04%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 03:05 UTC, Lauragra commented on api-reference/v1.0/api/channel-list.md
> -# [C#](#tab/csharp)
These are still deleted and need to be restored in this topic.

2020-10-01 03:06 UTC, Lauragra commented on api-reference/v1.0/api/channel-patch.md
> -```http
In this topic the entire example and the snippets are getting deleted. They need to be added back.

2020-10-01 03:08 UTC, opbld34 commented
Docs Build status updates of commit _[16f68dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16f68dc3a90232c2336c0daf1f894ef67a462b76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010307129840-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kShOsq%2FX2ktew63EmdMSGMogRgtfEHsUnrDOtLT4TcU%3D&st=2020-10-01T03%3A03%3A32Z&se=2020-11-01T03%3A08%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 03:10 UTC, Lauragra commented on api-reference/v1.0/api/channel-post-messagereply.md
> -# [C#](#tab/csharp)
The snippets are still getting deleted here.

2020-10-01 03:10 UTC, opbld32 commented
Docs Build status updates of commit _[7a8fd37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a8fd37c0e1b2ec640cb1365c464c4a085e27a42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010309161105-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1E5JPl%2BRG%2BiAVaqU3FlNmnzWgJ%2FBlWc0UZfaw1TS3T0%3D&st=2020-10-01T03%3A05%3A32Z&se=2020-11-01T03%3A10%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 05:15 UTC, opbld32 commented
Docs Build status updates of commit _[6897953](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68979532334137f5c05e513458ea49d064721d21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010514233919-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UhUbJwKiQkAUB7UOpBIIdR%2F29NytxngHRbPxOxBdQ6Q%3D&st=2020-10-01T05%3A10%3A41Z&se=2020-11-01T05%3A15%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 05:25 UTC, opbld32 commented
Docs Build status updates of commit _[7d63986](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d639861e09ac08b91c5ab434fbb19acbe405457)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010523530215-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m9NpIu%2BPxm1p1oMXvjvi0bT5vZJwooVmKeePpVEeH8s%3D&st=2020-10-01T05%3A20%3A08Z&se=2020-11-01T05%3A25%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 05:36 UTC, opbld31 commented
Docs Build status updates of commit _[1110044](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11100446282542d75fa074e2cc4b3c9a8d183dca)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :x:Error | | [Details](#user-content-a9116d3e-59be0464)

<a id="a9116d3e-59be0464"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-channels-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-channels-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-channels-objc-snippets.md'.`````
 - **Line 131, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/list-private-channels-csharp-snippets.md'.`````
 - **Line 135, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/list-private-channels-javascript-snippets.md'.`````
 - **Line 139, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/list-private-channels-objc-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010535176161-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=THltv3MBsJI2wS8jfINi9NOjD353yy2ip0UMoG%2BH6hk%3D&st=2020-10-01T05%3A31%3A24Z&se=2020-11-01T05%3A36%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 05:47 UTC, opbld34 commented
Docs Build status updates of commit _[4f3b965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f3b965580ceefc92114117d5829624c34342c9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010010546325891-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nCArFknM5y%2FWKiYMXG85SIBMLZFvhXUDEpmum5zd3oc%3D&st=2020-10-01T05%3A42%3A48Z&se=2020-11-01T05%3A47%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 18:19 UTC, opbld30 commented
Docs Build status updates of commit _[cddd446](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cddd446869539a56d010982685d45f01d253aa41)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :x:Error | | [Details](#user-content-647c6e05-04e13134)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :warning:Warning | | [Details](#user-content-a9116d3e-04e13134)

<a id="647c6e05-04e13134"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/patch-channels-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/patch-channels-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/patch-channels-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/patch-channels-java-snippets.md'.`````

<a id="a9116d3e-04e13134"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 127, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010011817565006-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0rDn5Hyk6moh8pj9p65wWySo2A7TbP3D4asPzDO%2FhIg%3D&st=2020-10-01T18%3A14%3A05Z&se=2020-11-01T18%3A19%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 18:39 UTC, opbld31 commented
Docs Build status updates of commit _[6ff946e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ff946e89437e7d559237a69d79c7006f03298d2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :x:Error | | [Details](#user-content-647c6e05-f9960a80)
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :warning:Warning | | [Details](#user-content-a9116d3e-f9960a80)

<a id="647c6e05-f9960a80"></a>
### [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md)
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-channels-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-channels-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-channels-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-channels-java-snippets.md'.`````

<a id="a9116d3e-f9960a80"></a>
### [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md)
 - **Line 126, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010011837513923-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y151G8OoSqZG7F6v3zdydv%2B6bYuVDE0gwzabNCsA6SY%3D&st=2020-10-01T18%3A34%3A01Z&se=2020-11-01T18%3A39%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 18:49 UTC, opbld31 commented
Docs Build status updates of commit _[0f66535](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f66535a84aec3e3c2b4c1a659e17de306e5e129)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010011847477240-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sy6jJYP9dRlyangIs3XA3Q4O0tUF5VLBviqtEsHXo%2BA%3D&st=2020-10-01T18%3A44%3A30Z&se=2020-11-01T18%3A49%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 18:53 UTC, laujan commented
Hi @Lauragra. I restored the deleted code snippets. The channel-patch.md file needs to have automated snippets generated. Can this be merged?

2020-10-02 02:03 UTC, opbld32 commented
Docs Build status updates of commit _[1ce91d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ce91d0ec5e589db7749a4e95db2fa64f50742c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010020201479281-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vfv7Ue%2BRVMrkJiClvPgAgzYL1Wz5hbI3vO%2BR87KGuHY%3D&st=2020-10-02T01%3A58%3A08Z&se=2020-11-02T02%3A03%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 02:09 UTC, opbld33 commented
Docs Build status updates of commit _[9663ca3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9663ca32e050e501e7a2c0927d822b6acd12ffbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010020208167642-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ofFoq9P%2FXLqo2Cs8drnmL3bvNKBBM2AerYNudMKFs74%3D&st=2020-10-02T02%3A04%3A33Z&se=2020-11-02T02%3A09%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 02:53 UTC, opbld33 commented
Docs Build status updates of commit _[8803df0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8803df0d2b5f42fe7e513142ce4bcd35fdbc28ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-9911) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010020252264979-9911%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gm035zy8BLYqmLH%2FN%2B%2FlEuVeLsQo5GyC36DZIWi%2BVJk%3D&st=2020-10-02T02%3A48%3A47Z&se=2020-11-02T02%3A53%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 03:00 UTC, Lauragra commented on api-reference/v1.0/api/channel-post.md
> +### Example 2: Create private channel on behalf of user
@laujan , I can't figure out why this second example is not rendering on the review site: https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911&tabs=java#examples. Do you see anything that might be causing that? I don't want to publish unless we can verify that the new example will be visible on the site.

2020-10-02 18:58 UTC, laujan commented on api-reference/v1.0/api/channel-post.md
> +### Example 2: Create private channel on behalf of user
Hi @Lauragra. I'll check.

2020-10-02 19:07 UTC, laujan commented on api-reference/v1.0/api/channel-post.md
> +### Example 2: Create private channel on behalf of user
Hi @Lauragra. It is because the java tab was enabled: "&tabs=java#examples". The default URL is tabs=http and there Example 2 is displayed.
https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-9911&tabs=http

2020-10-05 17:30 UTC, laujan commented
Hi @Lauragra. This is ready-to-merge. ✌

2020-10-05 20:05 UTC, merged