Ignite/graphconnectors
microsoftgraph/microsoft-graph-docs pull request #9921
Opened 2020-09-15 02:35 UTC by rsamai

Concept Pages for Ignite:
1. Create, update, and delete connections to the Microsoft Graph Connection
2. Register schema for the Microsoft Graph Connection
3. Create, update, and delete items added by your application in the Microsoft Graph Connection

2020-09-15 02:36 UTC, opbld31 commented
Docs Build status updates of commit _[a639e3d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a639e3d06d89c5fa3691dc6225b6624db5788a6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) | [Details](#user-content-66d13b45-0078da3d)
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) | [Details](#user-content-831661b3-0078da3d)
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-0078da3d)
[concepts/images/search-idex-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-idex-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-idex-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-idex-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |

<a id="66d13b45-0078da3d"></a>
### [concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=master)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 5, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'rsamai-msft' is not a valid GitHub ID.`````
 - **Line 15, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoftsearch/configure-connector' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalconnection?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 15, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 17, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'security_overview_diagram_1.png' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 20, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'security_overview_diagram_1.png' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion wil [...]

2020-09-15 02:48 UTC, opbld32 commented
Docs Build status updates of commit _[c096bf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c096bf26b09415f1d2b451efc2481f68ab6d9fd2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) | [Details](#user-content-66d13b45-c48f6f12)
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) | [Details](#user-content-831661b3-c48f6f12)
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-c48f6f12)
[concepts/images/search-idex-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-idex-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-idex-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-idex-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |

<a id="66d13b45-c48f6f12"></a>
### [concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=master)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 15, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/microsoftsearch/configure-connector' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalconnection?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 15, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 17, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'security_overview_diagram_1.png' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 20, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'security_overview_diagram_1.png' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 37, Column 0**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=master)]** `````Column hea [...]

2020-09-15 04:03 UTC, angelgolfer-ms commented on concepts/search-index-manage-connections.md
> +# Create, update, and delete connections to the Microsoft Graph Connection
Hi @rsamai , as mentioned, I will let @jasonjoh and perhaps @Lauragra be the main reviewers for your PR. Just a quick look, the first thing I can comment, and you can use this time to fix, is the use of capitalization.
Microsoft guidelines: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357

For example, line 10, other than not knowing what "Microsoft Graph connection" actually means, the term "Microsoft Graph Connection" should not have upper case 'C'. In both a topic title or section title, we use sentence case (per guidance).

Similarly, in line 14, "The Graph Connectors platform" - there are several issues:
- We cannot refer to Microsoft Graph by just extracting the term "Graph" and add "the" to refer to it;  in general that is against branding rules for any branded product.
- Please use lower case 'c' for connectors, per guidance.
- Nothing to do with capitalization, but referring to something as a "platform" - did you introduce or define the platform somewhere? IMO, since the connectors API is part of Microsoft Graph, it would be a confusing idea to characterize connectors as a platform by itself, when you zoom out and consider how Microsoft Graph fits in a more global picture involving Microsoft 365, and upcoming MetaOS. Instead, please refer to your API simply as "Microsoft Graph connectors API" and drop "platform".

2020-09-16 17:27 UTC, opbld32 commented
Docs Build status updates of commit _[5455969](https://github.com/microsoftgraph/microsoft-graph-docs/commits/545596919113640bfcc3f300d294f026ff036fe7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-886deb2c)
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) | [Details](#user-content-66d13b45-886deb2c)
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) | [Details](#user-content-831661b3-886deb2c)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |

<a id="306535cd-886deb2c"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 39, Column 186**: **[Warning-file-not-found]** `````Invalid file link: '(search-index-manage-item.md'.`````
 - **Line 12, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schema?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 65, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 73, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 147, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/indexing-api-overview?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="66d13b45-886deb2c"></a>
### [concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md)
 - **Line 12, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalconnection?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 18, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/external-post-connections?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/externalconnection-post-schema?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/external-post-connections?view=graph-rest-beta NOTE: This Suggest [...]

2020-09-16 17:35 UTC, opbld30 commented
Docs Build status updates of commit _[bfc9a38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfc9a383315f5e08ce97ec36abba5cd3c16de608)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-58c39b1e)
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) | [Details](#user-content-66d13b45-58c39b1e)
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) | [Details](#user-content-831661b3-58c39b1e)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |

<a id="306535cd-58c39b1e"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 39, Column 186**: **[Warning-file-not-found]** `````Invalid file link: '(search-index-manage-item.md'.`````
 - **Line 12, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schema?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 65, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 73, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 147, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/indexing-api-overview?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````

<a id="66d13b45-58c39b1e"></a>
### [concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md)
 - **Line 12, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalconnection?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 18, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/external-post-connections?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/externalconnection-post-schema?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/external-post-connections?view=graph-rest-beta NOTE: This Suggest [...]

2020-09-16 18:06 UTC, jasonjoh commented on concepts/search-index-manage-connections.md
> +# Create, update, and delete connections to the Microsoft Graph Connection
I've fixed this

2020-09-16 18:07 UTC, opbld34 commented
Docs Build status updates of commit _[4c26eff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c26eff644458ff5c9eccbba1ed2316956f9fd5e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-61e3a4d3)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |

<a id="306535cd-61e3a4d3"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 39, Column 186**: **[Warning-file-not-found]** `````Invalid file link: '(search-index-manage-item.md'.`````
 - **Line 70, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 80, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009161805458597-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E0CZwxyg83%2B7vlws5vO1PCGFrYUWvD6EM6kUwA1qEjs%3D&st=2020-09-16T18%3A02%3A31Z&se=2020-10-17T18%3A07%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequent [...]

2020-09-16 18:21 UTC, opbld34 commented
Docs Build status updates of commit _[a0139a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0139a333f7073db41f81926023f92110031190e)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-16 18:23 UTC, opbld31 commented
Docs Build status updates of commit _[a0139a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0139a333f7073db41f81926023f92110031190e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-0db2bec8)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |

<a id="306535cd-0db2bec8"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 39, Column 186**: **[Warning-file-not-found]** `````Invalid file link: '(search-index-manage-items.md'.`````
 - **Line 70, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 80, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009161821027379-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hLOV0KHMEtol96msVSj6DwBbeflYnWYUt0LLGuuDIys%3D&st=2020-09-16T18%3A18%3A04Z&se=2020-10-17T18%3A23%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequentl [...]

2020-09-16 18:27 UTC, opbld30 commented
Docs Build status updates of commit _[ec2e4d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec2e4d4f94d72d5980a744c98d41ce060bbb1528)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-16 18:29 UTC, opbld33 commented
Docs Build status updates of commit _[ec2e4d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec2e4d4f94d72d5980a744c98d41ce060bbb1528)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-4b724ff7)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |

<a id="306535cd-4b724ff7"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 70, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 80, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009161827256786-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7aWKK3%2BckDLVSfeekBCyk3NiSXJfhti96p3RXosuSjo%3D&st=2020-09-16T18%3A24%3A31Z&se=2020-10-17T18%3A29%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 18:37 UTC, jasonjoh requested changes

2020-09-16 18:37 UTC, jasonjoh commented on concepts/search-index-manage-connections.md
> +![Admin View of Connections including the custom Tickets Connector](./images/search-index-manage-connections-admin-view.png)
I commented this out per convo with Raju for now. This screenshot of a browser window is much bigger than it needs to be, and the content renders very small, making it hard to read. I suggest making the browser smaller (just big enough to show the relevant information)

2020-09-16 18:37 UTC, jasonjoh commented on concepts/search-index-manage-connections.md
> +The following table specifies which operations are available in each state.
I added this to introduce the second table - not sure if this is exactly right, feel free to reword. In general avoid having a table without any introductory text.

2020-09-16 18:37 UTC, jasonjoh commented on concepts/search-index-manage-items.md
> +![Example search results showing a dynamically generate preview of content](./images/search-index-manage-items-3.png)
Commented out as the image renders too small to read.

2020-09-16 18:37 UTC, jasonjoh commented on concepts/search-index-manage-items.md
> +![An example content component](./images/search-index-manage-items-2.png)
This image scales differently than the previous two images. I'm wondering if it wouldn't be better to remove these images and instead have JSON code blocks with the relevant JSON. The image doesn't add much over just the JSON, and JSON is probably better for screen-readers.

2020-09-16 18:37 UTC, jasonjoh commented on concepts/search-index-manage-schema.md
> +<!-->
Removed all the images in this topic - they render too small to read.

2020-09-18 13:19 UTC, opbld34 commented
Docs Build status updates of commit _[b3344a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3344a1f78755a7144f841257d9e495ee99cbc0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-0785c732)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-3.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-3.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

<a id="306535cd-0785c732"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 70, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 80, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'A set of retrievable properties (title, lastEditedBy etc.) rendered as a result' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009181317077548-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QUjB6TuRG9HNi3pmBQ0z3zc2h8CdqkoGJdPTXNWpc8M%3D&st=2020-09-18T13%3A14%3A03Z&se=2020-10-19T13%3A19%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 18:13 UTC, rsamai commented on concepts/search-index-manage-items.md
> +![An example content component](./images/search-index-manage-items-2.png)
JSON works for me!

2020-09-19 03:10 UTC, opbld32 commented
Docs Build status updates of commit _[fad77db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fad77db27a83512232c4b8bd76db49804bd063dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) | [Details](#user-content-66d13b45-967a65d6)
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) | [Details](#user-content-831661b3-967a65d6)
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-967a65d6)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-connections-admin-view.png?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-admin-view.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-1.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-2.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-2.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-items-schema-6.svg?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

<a id="66d13b45-967a65d6"></a>
### [concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md)
 - **Line 25, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-connections-admin-view.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="831661b3-967a65d6"></a>
### [concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md)
 - **Line 46, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-items-3.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="306535cd-967a65d6"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 42, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-items-schema-1.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 52, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-items-schema-2.svg' is the same as the image file name. This r [...]

2020-09-19 03:22 UTC, opbld34 commented
Docs Build status updates of commit _[e1ecc15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1ecc15d0f8ddf89706725f3f50e457f6f8f174d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) | [Details](#user-content-66d13b45-ee1c9dc9)
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) | [Details](#user-content-831661b3-ee1c9dc9)
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-ee1c9dc9)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-connections-admin-view.png?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-admin-view.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-1.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-2.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-2.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-items-schema-6.svg?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

<a id="66d13b45-ee1c9dc9"></a>
### [concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md)
 - **Line 25, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-connections-admin-view.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="831661b3-ee1c9dc9"></a>
### [concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md)
 - **Line 46, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-items-3.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="306535cd-ee1c9dc9"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 42, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-items-schema-1.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 52, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-items-schema-2.svg' is the same as the image file name. This r [...]

2020-09-21 13:24 UTC, opbld30 commented
Docs Build status updates of commit _[a6390a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6390a969a83d9c49636b54bbe927959a5944f69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-2ed2c691)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-connections-admin-view.png?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-admin-view.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-1.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-2.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-2.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-items-schema-6.svg?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

<a id="306535cd-2ed2c691"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 65, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-schema-4.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009211322488872-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2g6m13ejk%2FtL41z4YDl47DhE%2BRcsIj53aQKxInfFi9I%3D&st=2020-09-21T13%3A19%3A06Z&se=2020-10-22T13%3A24%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 13:32 UTC, jasonjoh approved these changes

2020-09-21 13:33 UTC, opbld33 commented
Docs Build status updates of commit _[1ac93ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ac93ec75257395c856596ad5eb6fa1e297c97ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) | [Details](#user-content-306535cd-6fb84998)
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-connections-admin-view.png?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-admin-view.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-1.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-2.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-2.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-items-schema-6.svg?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

<a id="306535cd-6fb84998"></a>
### [concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md)
 - **Line 65, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'search-index-manage-schema-4.svg' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009211332185469-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dEEpDsKDFZascA23rdI0t3iHd2cXRnm03iud7lmGKAM%3D&st=2020-09-21T13%3A28%3A48Z&se=2020-10-22T13%3A33%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 13:37 UTC, opbld34 commented
Docs Build status updates of commit _[71d19d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71d19d5df749d61981e84443da567c283282b5a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-connections-admin-view.png?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-admin-view.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-1.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-2.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-2.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-items-schema-6.svg?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009211336266340-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rMrs2xTnW0gdnmjDIhB7wgc8aqxNdL1hFlqaq4d9DGE%3D&st=2020-09-21T13%3A32%3A41Z&se=2020-10-22T13%3A37%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 02:13 UTC, opbld31 commented
Docs Build status updates of commit _[c2de99f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2de99ff47b5bcc8f8208fee70db896b4b9d01f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-connections-admin-view.png?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-admin-view.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-1.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-2.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-2.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-items-schema-6.svg?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009220212156948-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xkHU1LXvBf1c0yTbdIdYzvG426LUT%2F%2Fqu7MT2YdlaIg%3D&st=2020-09-22T02%3A08%3A31Z&se=2020-10-23T02%3A13%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 02:14 UTC, opbld31 commented
Docs Build status updates of commit _[0b370b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b370b8762ed7b9b2f78978bbf15f03b37c1d925)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/search-index-manage-connections-admin-view.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-connections-admin-view.png?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-admin-view.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-admin-view.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-connections-connector-structure.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-connections-connector-structure.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-acl.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-acl.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-1.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-2.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-2.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-3.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-3.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-items-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-items-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/search-index-manage-items-schema-6.svg?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-4.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-4.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-5.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-5.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/images/search-index-manage-schema-6.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/images/search-index-manage-schema-6.svg) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/search-index-manage-connections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |
[concepts/search-index-manage-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-items?branch=pr-en-us-9921) |
[concepts/search-index-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/search-index-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-schema?branch=pr-en-us-9921) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ignite/graphconnectors/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-connections?branch=pr-en-us-9921) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009220213331322-9921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EzAlIfjSGqYdbhgpPwr6K%2FxcAU%2BydO5A7LDLYlHyCrU%3D&st=2020-09-22T02%3A09%3A50Z&se=2020-10-23T02%3A14%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 02:22 UTC, merged