Authentication Methods Policies API doc updates
microsoftgraph/microsoft-graph-docs pull request #9924
Opened 2020-09-15 08:04 UTC by andres-canello

2020-09-15 08:06 UTC, opbld30 commented
Docs Build status updates of commit _[993b08a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/993b08a06772e831d4867ec0ce2cfb63c964300a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-b1b1c79a)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-b1b1c79a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignment?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve- [...]

2020-09-16 17:02 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +Returns the [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md) object to its default configuration.
This seems like an odd description for a delete operation. It seems like it would be more like "Deletes a [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md) object from the collection of authentication method configurations.

2020-09-16 17:03 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
> +Retrieve the properties and relationships of the [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md) object which represents the FIDO2 Security Keys authe
Is the customer going to know what "FIDO2 Security Keys authentication method policy" is? Possibly link to conceptual content?

2020-09-16 17:06 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
> +For the list of properties, see [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md).
Is the user able to update all properties?

2020-09-16 17:07 UTC, davidmu1 commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
> +Returns the [passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) object to its default configurat
Same as the previous comment.

2020-09-16 17:09 UTC, davidmu1 commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
> +Retrieve the properties and relationships of the [passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration
Same comment about possibly linking to information about the Passwordless Phone Sign-in with Microsoft Authenticator authentication method policy.

2020-09-16 17:09 UTC, davidmu1 commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md
> +For the list of properties, see [passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md).
Can all properties be updated?

2020-09-16 17:14 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +Authentication methods policies define [Authentication methods](https://docs.microsoft.com/azure/active-directory/authentication/concept-authentication-methods) settings and users that are allowed to
```suggestion
Authentication methods policies define [authentication methods](https://docs.microsoft.com/azure/active-directory/authentication/concept-authentication-methods) and the users that are allowed to use them to sign in and perform multi-factor authentication (MFA) in Azure Active Directory (Azure AD). Authentication methods policies that can be managed in Microsoft Graph include FIDO2 security keys and Passwordless Phone Sign in with Microsoft Authenticator app.
```

2020-09-16 17:15 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +* Define which types of FIDO2 security keys can be used in the Azure AD tenant.
```suggestion
* Define the types of FIDO2 security keys that can be used in the Azure AD tenant.
```

2020-09-16 17:16 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +* Define which users or groups of users are allowed to use FIDO2 security keys or Passwordless Phone Sign in to sign in to Azure AD.
```suggestion
* Define the users or groups of users who are allowed to use FIDO2 security keys or Passwordless Phone Sign-in to sign in to Azure AD.
```

2020-09-16 17:17 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +|[fido2authenticationmethodconfiguration](fido2authenticationmethodconfiguration.md)| Define FIDO2 security key restrictions and users that can use them to sign in to Azure AD.|
```suggestion
|[fido2authenticationmethodconfiguration](fido2authenticationmethodconfiguration.md)| Define FIDO2 security key restrictions and users who can use them to sign in to Azure AD.|
```

2020-09-16 17:18 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +|[passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration](passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md)|Define users that can use Passwordless Phone Sign in to
```suggestion
|[passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration](passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md)|Define users who can use Passwordless Phone Sign in to sign in to Azure AD.|
```

2020-09-16 17:18 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +* Review the authentication methods policies and their various methods.
There should be a link here if it is truly a next step.

2020-09-16 17:19 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodtarget.md
> +description: "A collection of users or groups enabled to use an authentication method as part of an Authentication Method Policy."
```suggestion
description: "A collection of users or groups enabled to use an authentication method as part of an authentication method policy."
```

2020-09-16 17:19 UTC, davidmu1 commented on api-reference/beta/resources/authenticationmethodtarget.md
> +A collection of users or groups enabled to use an authentication method as part of an Authentication Method Policy in Azure AD.
```suggestion
A collection of users or groups enabled to use an authentication method as part of an authentication method policy in Azure AD.
```

2020-09-16 17:22 UTC, davidmu1 commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +A representation of FIDO2 Authentication Methods policy. Authentication Methods policies define configuration settings and users or groups that are enabled to use the authentication method.
```suggestion
A representation of FIDO2 Authentication Methods policy. Authentication methods policies define configuration settings and users or groups who are enabled to use the authentication method.
```

2020-09-16 17:23 UTC, davidmu1 commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|[Delete](../api/fido2authenticationmethodconfiguration-delete.md)|None|Returns the fido2AuthenticationMethodConfiguration object to its default configuration.|
Please consider revising the Delete description.

2020-09-16 17:24 UTC, davidmu1 commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|isAttestationEnforced|Boolean|Determines whether attestation must be enforced for FIDO2 security key registration.|
Is there a simpler word or term to use other than "attestation"? Not a common word in normal conversation.

2020-09-16 17:25 UTC, davidmu1 commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|keyRestrictions|[fido2KeyRestrictions](../resources/fido2keyrestrictions.md)|Controls whether key restrictions are enforced on FIDO2 security keys, either allowing or disallowing certain key types a
Are users going to know what AAGUID is?

2020-09-16 17:25 UTC, davidmu1 commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|includeTargets|[authenticationMethodTarget](../resources/authenticationmethodtarget.md) collection|A collection of users or groups that are enabled to use the authentication method.|
```suggestion
|includeTargets|[authenticationMethodTarget](../resources/authenticationmethodtarget.md) collection|A collection of users or groups who are enabled to use the authentication method.|
```

2020-09-16 17:26 UTC, davidmu1 commented on api-reference/beta/resources/fido2keyrestrictions.md
> +description: "A representation of key restrictions that are enforced as part of FIDO2 security keys authentication methods policy"
```suggestion
description: "Represents the key restrictions that are enforced as part of the FIDO2 security keys authentication methods policy."
```

2020-09-16 17:27 UTC, davidmu1 commented on api-reference/beta/resources/fido2keyrestrictions.md
> +A representation of key restrictions that are enforced as part of [FIDO2 security keys authentication methods policy](../resources/fido2authenticationmethodconfiguration.md).
Represents the key restrictions that are enforced as part of the [FIDO2 security keys authentication methods policy](../resources/fido2authenticationmethodconfiguration.md).

2020-09-16 17:28 UTC, davidmu1 commented on api-reference/beta/resources/fido2keyrestrictions.md
> +|aaGuids|String collection|A collection of Authenticator Attestation GUIDs. AADGUIDs define key types and manufacturers.|
```suggestion
|aaGuids|String collection|A collection of Authenticator Attestation GUIDs (AADGUID). AADGUIDs define key types and manufacturers.|
```

Is there a link to any conceptual documentation about AADGUIDs?

2020-09-16 17:31 UTC, davidmu1 commented on api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
> +description: "A representation of a Passwordless Phone Sign-in with Microsoft Authenticator Authentication Methods policy."
```suggestion
description: "Represents a Passwordless Phone Sign-in with Microsoft Authenticator Authentication Methods policy."
```

2020-09-16 17:36 UTC, davidmu1 commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +description: "A representation of FIDO2 Authentication Methods policy"
```suggestion
description: "Represents a FIDO2 authentication methods policy"
```

2020-09-16 17:46 UTC, davidmu1 commented on api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
> +A representation of a Passwordless Phone Sign-in with Microsoft Authenticator Authentication Methods policy. Authentication Methods policies define configuration settings and users or groups that are
```suggestion
Represents a Passwordless Phone Sign-in with Microsoft Authenticator authentication methods policy. Authentication methods policies define configuration settings and users or groups that are enabled to use the authentication method.
```

2020-09-16 17:47 UTC, davidmu1 commented on api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
> +|[Delete](../api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md)|None|Returns the passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration object to its defa
Please consider revising the description for Delete.

2020-09-16 17:47 UTC, davidmu1 commented on api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
> +|includeTargets|[passwordlessMicrosoftAuthenticatorAuthenticationMethodTarget](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) collection|A collection of users or groups
```suggestion
|includeTargets|[passwordlessMicrosoftAuthenticatorAuthenticationMethodTarget](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) collection|A collection of users or groups who are enabled to use the authentication method.|
```

2020-09-16 17:48 UTC, davidmu1 commented on api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md
> +description: "A collection of users or groups enabled to use Passwordless Phone Sign in with Microsoft Authenticator as part of the Authentication Method Policy."
```suggestion
description: "A collection of users or groups enabled to use Passwordless Phone Sign-in with Microsoft Authenticator authentication methods policy."
```

2020-09-16 17:49 UTC, davidmu1 commented on api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md
> +A collection of users or groups enabled to use Passwordless Phone Sign in with Microsoft Authenticator as part of the [Authentication Method Policy](../resources/passwordlessMicrosoftAuthenticatorAut
```suggestion
A collection of users or groups enabled to use Passwordless Phone Sign-in with Microsoft Authenticator authentication methods policy](../resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration.md) in Azure AD.
```

2020-09-16 17:51 UTC, davidmu1 commented on api-reference/beta/toc.yml
> +          - name: Microsoft Authenticator passwordless sign-in
```suggestion
          - name: Microsoft Authenticator Passwordless Sign-in
```

2020-09-16 17:51 UTC, davidmu1 commented on concepts/changelog.md
> +| Addition | beta | Added the [fido2AuthenticationMethodConfiguration](/graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta) entity for managing users' FIDO2 security keys
```suggestion
| Addition | beta | Added the [fido2AuthenticationMethodConfiguration](/graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta) entity for managing users' FIDO2 Security Keys authentication method policy. |
```

2020-09-25 00:42 UTC, andres-canello commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +Returns the [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md) object to its default configuration.
Done. What delete does here is taking the policy to it's default configuration. Changed to "Removes changes made to the FIDO2 authentication method policy by reverting the policy to it's default configuration."

2020-09-25 00:48 UTC, andres-canello commented on api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
> +Retrieve the properties and relationships of the [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md) object which represents the FIDO2 Security Keys authe
Added a link to the auth method policy overview page

2020-09-25 00:50 UTC, andres-canello commented on api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
> +For the list of properties, see [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md).
Yes. Should this be clarified?

2020-09-25 00:56 UTC, andres-canello commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
> +Returns the [passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) object to its default configurat
Fixed

2020-09-25 00:59 UTC, andres-canello commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
> +Retrieve the properties and relationships of the [passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration
Linked to the policy overview.

2020-09-25 01:01 UTC, andres-canello commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md
> +For the list of properties, see [passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration](../resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md).
Yes, in this case only the "state" prop.

2020-09-25 01:05 UTC, opbld31 commented
Docs Build status updates of commit _[b05486a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b05486a3be2b507c214c2f71eeee5753cda2c46c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-48b404cc)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-48b404cc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:06 UTC, opbld32 commented
Docs Build status updates of commit _[060c9ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/060c9ae6783cf072e9e2373d6909a3234338473d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-e56c1261)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-e56c1261"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:07 UTC, andres-canello commented on api-reference/beta/resources/authenticationmethodspolicies-overview.md
> +* Review the authentication methods policies and their various methods.
Removed.

2020-09-25 01:08 UTC, opbld32 commented
Docs Build status updates of commit _[26970f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26970f7581d2cd1b497906900bb5a9930e8a5d3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-d92bbe82)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-d92bbe82"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:09 UTC, andres-canello commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|[Delete](../api/fido2authenticationmethodconfiguration-delete.md)|None|Returns the fido2AuthenticationMethodConfiguration object to its default configuration.|
Done

2020-09-25 01:09 UTC, opbld33 commented
Docs Build status updates of commit _[315b3f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/315b3f2e75347ad658fb7cd117fd4444be64dd51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-b7666dde)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-b7666dde"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:09 UTC, andres-canello commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|isAttestationEnforced|Boolean|Determines whether attestation must be enforced for FIDO2 security key registration.|
@mmcla suggestions?

2020-09-25 01:14 UTC, andres-canello commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|keyRestrictions|[fido2KeyRestrictions](../resources/fido2keyrestrictions.md)|Controls whether key restrictions are enforced on FIDO2 security keys, either allowing or disallowing certain key types a
Added more details about AAGUIDs

2020-09-25 01:16 UTC, opbld32 commented
Docs Build status updates of commit _[e539f8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e539f8ee04bd51ade382d559902a2a85bb0ade99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-8bb6f3c1)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-8bb6f3c1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:16 UTC, andres-canello commented on api-reference/beta/resources/fido2keyrestrictions.md
> +A representation of key restrictions that are enforced as part of [FIDO2 security keys authentication methods policy](../resources/fido2authenticationmethodconfiguration.md).
Fixed

2020-09-25 01:17 UTC, andres-canello commented on api-reference/beta/resources/fido2keyrestrictions.md
> +|aaGuids|String collection|A collection of Authenticator Attestation GUIDs. AADGUIDs define key types and manufacturers.|
No

2020-09-25 01:17 UTC, opbld31 commented
Docs Build status updates of commit _[dc3dd8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc3dd8e2ef04e777478ead75d729e3edbc654245)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-71a36905)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-71a36905"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:19 UTC, opbld32 commented
Docs Build status updates of commit _[99f2115](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99f2115a4da9465798d6332a0b5dadc57b93ba9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-3c966c98)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-3c966c98"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:20 UTC, opbld32 commented
Docs Build status updates of commit _[cb63bc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb63bc9f6bd40fcedd04c1aa36c30eb4ad715c15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-57f85793)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-57f85793"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:22 UTC, andres-canello commented on api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
> +|[Delete](../api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md)|None|Returns the passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration object to its defa
Done

2020-09-25 01:23 UTC, opbld34 commented
Docs Build status updates of commit _[edd534a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edd534aca51b8d0c557c5e88a592fb31597d4974)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-f496182a)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-f496182a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:24 UTC, opbld30 commented
Docs Build status updates of commit _[c833bb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c833bb406246d8e9494c2956ee271d25c16cf0df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-7fbc70de)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-7fbc70de"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:26 UTC, opbld30 commented
Docs Build status updates of commit _[c1b71cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1b71cc27f30aff07d0ad0235751ba817fdb8163)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-1bcdc988)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-1bcdc988"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:27 UTC, opbld33 commented
Docs Build status updates of commit _[181005c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/181005ce77ca370680ea78d442826c022fabaa15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-8ab64f15)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-8ab64f15"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-25 01:34 UTC, opbld32 commented
Docs Build status updates of commit _[ac45ca1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac45ca1accbfb98a27476e0d3bf8b29527a01169)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-36f38c30)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-36f38c30"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-09-28 20:34 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +|Delegated (work or school account)|Policy.ReadWrite.AuthenticationMethod|
I'm not finding the Policy.ReadWrite.AuthenticationMethod permission in this page: https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#policy-permissions. Please add it.

2020-09-28 20:37 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +DELETE /policies/authenticationMethodsPolicy/authenticationMethodConfigurations/fido2
Is fido2 the name of the configuration? If so, this should be something like:

DELETE /policies/authenticationMethodsPolicy/authenticationMethodConfigurations/{configuration-name}

If fido2 is an example name, it can be used in the Examples section.

2020-09-28 20:42 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +DELETE /policies/authenticationMethodsPolicy/authenticationMethodConfigurations/fido2
Is fido2 the name of the configuration? Is it always fido2? Should probably have a note stating what the fido2 object is.

2020-09-28 20:44 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
> +Retrieve the properties and relationships of the [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md) object which represents the FIDO2 Security Keys [auth
First mention of Azure AD should be Azure Active Directory (Azure AD).

2020-09-28 20:46 UTC, davidmu1 commented on api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
> +For the list of properties, see [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md).
yes

2020-09-28 20:49 UTC, davidmu1 approved these changes

2020-09-29 22:49 UTC, andres-canello commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +DELETE /policies/authenticationMethodsPolicy/authenticationMethodConfigurations/fido2
Yes, fido2 is the name of the fido2 auth method policy. Will discuss with @mmcla

2020-09-29 22:50 UTC, andres-canello commented on api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
> +Retrieve the properties and relationships of the [fido2AuthenticationMethodConfiguration](../resources/fido2authenticationmethodconfiguration.md) object which represents the FIDO2 Security Keys [auth
Fixed

2020-09-29 23:45 UTC, mmcla commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +DELETE /policies/authenticationMethodsPolicy/authenticationMethodConfigurations/fido2
in this case, fido2 is the id of the entity. These are singleton entities - there's exactly one of each per tenant - and they have the same id in each tenant.

2020-09-29 23:58 UTC, CelesteDG commented
@andres-canello - Looks like there's an error with API Doctor. More info here: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/66012/API-Doctor-validate-examples

2020-09-29 23:59 UTC, opbld32 commented
Docs Build status updates of commit _[1a3f96d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a3f96d8c6f97943e0fb093f065a7474d4a74cf4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-ebf4876b)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-ebf4876b)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-ebf4876b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /grap [...]

2020-09-30 02:45 UTC, opbld33 commented
Docs Build status updates of commit _[518cb8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/518cb8b0b253ad5285a2476ca0b78ce64c66d336)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-46e02c57)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-46e02c57)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-46e02c57"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /grap [...]

2020-09-30 02:53 UTC, andres-canello commented on api-reference/beta/resources/fido2authenticationmethodconfiguration.md
> +|isAttestationEnforced|Boolean|Determines whether attestation must be enforced for FIDO2 security key registration.|
Attestation is the word used by the fido2 spec.

2020-09-30 04:02 UTC, andres-canello commented on api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
> +|Delegated (work or school account)|Policy.ReadWrite.AuthenticationMethod|
Added

2020-09-30 04:07 UTC, opbld31 commented
Docs Build status updates of commit _[34b52f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34b52f4770734e667d86a35c37a751f3c5f93be8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-32792bc6)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-32792bc6)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-32792bc6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /grap [...]

2020-09-30 04:27 UTC, opbld33 commented
Docs Build status updates of commit _[951e372](https://github.com/microsoftgraph/microsoft-graph-docs/commits/951e37211112455b234b385267db8e050bd78c16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-83e41e9d)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-83e41e9d)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-83e41e9d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /grap [...]

2020-09-30 04:34 UTC, opbld33 commented
Docs Build status updates of commit _[b99f0f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b99f0f2275be822ba1381a8f87a65e5985fa95ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-278aa84a)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-278aa84a)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-278aa84a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /grap [...]

2020-09-30 04:39 UTC, andres-canello commented
> @andres-canello - Looks like there's an error with API Doctor. More info here: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/66012/API-Doctor-validate-examples

I fixed a couple of them but I don't know what to do with these:
Finished publishing metadata.
  Error: microsoft.graph.authenticationMethodTarget/targetType:
      Referenced type microsoft.graph.authenticationMethodTargetType is not defined in the doc set! Potential suggestion: microsoft.graph.authenticationMethod

  Error: microsoft.graph.fido2AuthenticationMethodConfiguration:
      Referenced base type microsoft.graph.authenticationMethodConfiguration in resource microsoft.graph.fido2AuthenticationMethodConfiguration is not defined in the doc set!

  Error: microsoft.graph.fido2AuthenticationMethodConfiguration/state:
      Referenced type microsoft.graph.authenticationMethodState is not defined in the doc set! Potential suggestion: microsoft.graph.authenticationMethod

  Error: microsoft.graph.fido2KeyRestrictions/enforcementType:
      Referenced type microsoft.graph.fido2RestrictionEnforcementType is not defined in the doc set! Potential suggestion: UNKNOWN

  Error: microsoft.graph.passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration:
      Referenced base type microsoft.graph.authenticationMethodConfiguration in resource microsoft.graph.passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration is not defined in the doc set!

  Error: microsoft.graph.passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration/state:
      Referenced type microsoft.graph.authenticationMethodState is not defined in the doc set! Potential suggestion: microsoft.graph.authenticationMethod

  Error: microsoft.graph.passwordlessMicrosoftAuthenticatorAuthenticationMethodTarget/shownContext:
      Referenced type microsoft.graph.authenticatorAppContextType is not defined in the doc set! Potential suggestion: UNKNOWN

  Error: microsoft.graph.passwordlessMicrosoftAuthenticatorAuthenticationMethodTarget/targetType:
      Referenced type microsoft.graph.authenticationMethodTargetType is not defined in the doc set! Potential suggestion: microsoft.graph.authenticationMethod

2020-10-02 01:13 UTC, opbld32 commented
Docs Build status updates of commit _[db5b8cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db5b8ccf4f9ed3f0453dbdfc530cc498483d0a64)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4e5df893)

<a id="4e5df893"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010020113248554-9924%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GrUPZWoae2g3c4ql2cM3g4vow3YHL6Qtd%2FKkOVQALA8%3D&st=2020-10-02T01%3A08%3A51Z&se=2020-11-02T01%3A13%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 01:49 UTC, opbld30 commented
Docs Build status updates of commit _[d6d5849](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6d584962f06b5838bd75405e397d8d8004fdec4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a43b39ac)

<a id="a43b39ac"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010020148528735-9924%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U16LOOHXW1kwaqdUSS%2FMUr1kOlxaJCPbvit%2B6zOxvFY%3D&st=2020-10-02T01%3A44%3A22Z&se=2020-11-02T01%3A49%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 01:55 UTC, opbld32 commented
Docs Build status updates of commit _[45e622e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45e622ea414f11ee2f287259852367ac45d089e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-966ea44d)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-966ea44d)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-966ea44d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOT [...]

2020-10-02 15:46 UTC, mmcla approved these changes

2020-10-05 22:55 UTC, andrewchoi5 approved these changes

2020-10-08 18:32 UTC, opbld32 commented
Docs Build status updates of commit _[3437d7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3437d7d7ab61ca3261fdd120a1443cbdc614666c)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 18:35 UTC, opbld30 commented
Docs Build status updates of commit _[e30eaad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e30eaad81941454f7932587bcf819d5259c578c5)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 18:36 UTC, opbld32 commented
Docs Build status updates of commit _[3437d7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3437d7d7ab61ca3261fdd120a1443cbdc614666c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-9f7c18e7)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-9f7c18e7)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-9f7c18e7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 18:39 UTC, opbld32 commented
Docs Build status updates of commit _[e30eaad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e30eaad81941454f7932587bcf819d5259c578c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-b8833ac6)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-b8833ac6)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-b8833ac6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 18:42 UTC, opbld33 commented
Docs Build status updates of commit _[941ad09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/941ad095719f72e72ae01e224278ce727488b024)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-3d002031)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-3d002031)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-3d002031"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 18:43 UTC, Lauragra commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
> +> [!NOTE]
We already have a disclaimer on all topics in beta that says that APIs are subject to change and are not supported in production. So, this note might be a bit duplicative. It seems like you have the note here because you know of upcoming changes, but maybe the beta disclaimer covers this sufficiently?

2020-10-08 18:45 UTC, Lauragra commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
> +> [!NOTE]
Same comment here re: the note.

2020-10-08 18:46 UTC, opbld31 commented
Docs Build status updates of commit _[47270f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47270f798f98d232c303c1e3cc46ee1a77b76e25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-0014fe9c)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-0014fe9c)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-0014fe9c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 18:59 UTC, opbld31 commented
Docs Build status updates of commit _[84745fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84745fcfa218948e3a21bf15173ad296f52fe5fa)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 19:02 UTC, opbld33 commented
Docs Build status updates of commit _[84745fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84745fcfa218948e3a21bf15173ad296f52fe5fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-25ab8104)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-25ab8104)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-25ab8104"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 19:04 UTC, opbld31 commented
Docs Build status updates of commit _[3e05bc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e05bc9ceadd0dd9453a262a23f7c626050979db)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 19:10 UTC, opbld32 commented
Docs Build status updates of commit _[3e05bc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e05bc9ceadd0dd9453a262a23f7c626050979db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-187ac0f9)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-187ac0f9)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-187ac0f9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 22:18 UTC, opbld33 commented
Docs Build status updates of commit _[643f722](https://github.com/microsoftgraph/microsoft-graph-docs/commits/643f7227a0f392050a9a5dbaba2d1d102dc45db1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-432cb0ac)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-432cb0ac)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-432cb0ac"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 22:19 UTC, opbld33 commented
Docs Build status updates of commit _[448ac4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/448ac4cb2016f824f55f2e015d801c1e5d8379d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-ebfc77b9)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-ebfc77b9)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-ebfc77b9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 22:19 UTC, Lauragra requested changes
I just had one comment/question about the inclusion of the Note text in topics that already have a beta disclaimer. Please also add a JSON entry to the DirectoryServices JSON file as we're currently testing the new changelog process.

2020-10-08 22:23 UTC, opbld33 commented
Docs Build status updates of commit _[2a0dc9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a0dc9d5c90fd13c1d532ce3eddd4cf5b4119e7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-a80ba6ef)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-a80ba6ef)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="de0bbbbb-a80ba6ef"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=grap [...]

2020-10-08 22:23 UTC, andres-canello commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
> +> [!NOTE]
@mmcla what do you think?

2020-10-08 22:35 UTC, mmcla commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
> +> [!NOTE]
I'd rather keep this here to over-highlight the change. We know some of our customers are indeed taking prod dependencies on these APIs despite us telling them, repeatedly, not to. Given that, I want to call this out because not only may it change but we know it will.

2020-10-08 22:35 UTC, mmcla commented on api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
> +> [!NOTE]
Same as above.

2020-10-08 23:23 UTC, opbld33 commented
Docs Build status updates of commit _[b3841ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3841eaaa714015c6c74a4672d930ced4eac23c1)_: 

:clock10: **Pending**: waiting for processors ([34](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 34 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-08 23:26 UTC, opbld34 commented
Docs Build status updates of commit _[b3841ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3841eaaa714015c6c74a4672d930ced4eac23c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) | [Details](#user-content-00685cff-0265d4b9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-0265d4b9)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-0265d4b9)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |

<a id="00685cff-0265d4b9"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml)
 - **Line 10019, Column 21**: **[Warning-file-not-found]** `````Invalid file link: 'api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.m'.`````
 [...]

2020-10-09 00:11 UTC, Lauragra commented on concepts/changelog.md
> +### Identity and access | Identity and sign-in
This entry should be moved into October.

2020-10-09 00:49 UTC, andres-canello commented on concepts/changelog.md
> +### Identity and access | Identity and sign-in
Done

2020-10-09 00:49 UTC, opbld32 commented
Docs Build status updates of commit _[37116a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37116a5d56b755f3fe7cd4213390bcde49f22d14)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) | [Details](#user-content-00685cff-49894b0e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-49894b0e)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-49894b0e)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="00685cff-49894b0e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authme [...]

2020-10-09 00:54 UTC, opbld34 commented
Docs Build status updates of commit _[8df30fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8df30fdc010a9645a4c6286a225523760f81b43e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-76f41cc4)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-76f41cc4)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-76f41cc4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/cha [...]

2020-10-09 01:04 UTC, Lauragra approved these changes

2020-10-09 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[45232ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45232eae42bdc2f918003851628c7f1acf0627a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-0debbc72)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-0debbc72)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0debbc72"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/cha [...]

2020-10-09 18:29 UTC, opbld32 commented
Docs Build status updates of commit _[8f76ebd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f76ebd206600d0733417db1afcf8ad35d358e4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9924) | [Details](#user-content-de0bbbbb-512092f6)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-9924) | [Details](#user-content-075040e5-512092f6)
[api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/authenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2authenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/fido2keyrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/fido2keyrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2keyrestrictions?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-9924) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-512092f6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-03-authmethods_policy_adds/concepts/cha [...]

2020-10-09 18:31 UTC, merged