Changes in Graph v1.0 for hexColor and isDraft properties
microsoftgraph/microsoft-graph-docs pull request #9928
Opened 2020-09-15 10:47 UTC by Bhupesh12Hub

Hi @angelgolfer-ms , Please review the PR.

2020-11-27 16:59 UTC, opbld33 commented
Docs Build status updates of commit _[e80db93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e80db930baa74afaf27a53251717a885a6f8ed19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-6f9b0da7)
[api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get-event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-6b196964-6f9b0da7)
[api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-59fa496a-6f9b0da7)
[api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-b3590bba-6f9b0da7)
[api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-d16ad008-6f9b0da7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9928) | [Details](#user-content-de0bbbbb-6f9b0da7)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/event-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |

<a id="2f98de3e-6f9b0da7"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="6b196964-6f9b0da7"></a>
### [api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="59fa496a-6f9b0da7"></a>
### [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="b3590bba-6f9b0da7"></a>
### [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List calendars - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendargroup-list-calendars.md(2,8), v1.0/api/user-list-calendars.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion [...]

2020-12-04 04:41 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **isDraft** property to the [event](/graph/api/resources/event?view=graph-rest-1.0) entity. |
Lines 264 and 265, and GLOBAL for other PRs as well:
Please note that in general, when you create a "site-relative" link and include the query parameter **?view**, you now need to include **preserve-view=true**. This requirement applies to all existing site-relative links in the topic too, not just new links. Ignoring this requirement would trigger a build warning, You can find more info here: 
https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-articles-in-other-repos-or-docsets
https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-specific-versions

So for the site-relative links you have in lines 264 and 265, I suggest you either add **preserve-view=true**, or, simply drop ?view=graph-rest-1.0. When you drop ?view=graph-rest-1.0, OPS would just default to the v1 version, which is the intended purpose in this case.

2020-12-04 04:51 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **isDraft** property to the [event](/graph/api/resources/event?view=graph-rest-1.0) entity. |
Please also update the corresponding changelog json file Microsoft.Exchange.json.
CDK help: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55075/Graph-doc-stub-generator-tool?anchor=update-the-json-changelog

2020-12-04 04:51 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub , please see a couple of comments on handling the changelog files. Good job for the rest of the PR!

2020-12-16 16:35 UTC, opbld34 commented
Docs Build status updates of commit _[27b1a0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27b1a0df184242ac579a7379104d2a8767e44b7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-9fe1a068)
[api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get-event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-6b196964-9fe1a068)
[api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-59fa496a-9fe1a068)
[api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-b3590bba-9fe1a068)
[api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-d16ad008-9fe1a068)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9928) | [Details](#user-content-de0bbbbb-9fe1a068)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/event-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |

<a id="2f98de3e-9fe1a068"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="6b196964-9fe1a068"></a>
### [api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="59fa496a-9fe1a068"></a>
### [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="b3590bba-9fe1a068"></a>
### [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List calendars - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendargroup-list-calendars.md(2,8), v1.0/api/user-list-calendars.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion [...]

2020-12-16 16:45 UTC, opbld32 commented
Docs Build status updates of commit _[2ad5b69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ad5b69488f98a72941bb9ec4c7f2523e02f0f0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-cab9aec9)
[api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get-event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-6b196964-cab9aec9)
[api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-59fa496a-cab9aec9)
[api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-b3590bba-cab9aec9)
[api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-d16ad008-cab9aec9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9928) | [Details](#user-content-de0bbbbb-cab9aec9)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/event-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="2f98de3e-cab9aec9"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="6b196964-cab9aec9"></a>
### [api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="59fa496a-cab9aec9"></a>
### [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="b3590bba-cab9aec9"></a>
### [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List calendars - Microsoft Graph v [...]

2020-12-17 17:21 UTC, Bhupesh12Hub commented
@angelgolfer-ms, i have resolved the feedback, if everything is good to go we can push the PR to merge state.

@Lauragra @Harini84

2020-12-19 05:58 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **isDraft** property to the [event](/graph/api/resources/event?view=graph-rest-1.0) entity. |
@Bhupesh12Hub , you overlooked fixing the site-relative links in changelog.md.
Please make sure you understand what to do with them in general.
For this PR, in the interest of time, I'm going to fix changelog.md so that I can merge the PR before the end of today (last day to publish this year).

2020-12-19 06:04 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the **hexColor** property to the [event](/graph/api/resources/event?view=graph-rest-1.0) entity.",
Line 10:
This is not correct; the property was added to the calendar entity, not event entity.

2020-12-19 06:10 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +          "Id": "8fcb5dbc-d5aa-4681-8e31-b001d5168d79",
The id values within the same changelog records (e.g., lines 4-20 form one changelog record, lines 21-38 form another changelog record) should be the same, but not across changelog records. 
Here you have the same GUID for all the id properties in these two changelog records. You should use a GUID generator to generate a different GUID for one of the two changelog records.

Alternatively, the two changes - adding the hexColor and isDraft properties - can go into their own changelist records within the same changelog record. In this case, the changelist records can use the same GUID value for their id.

2020-12-19 06:14 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **isDraft** property to the [event](/graph/api/resources/event?view=graph-rest-1.0) entity. |
@Bhupesh12Hub , also, for the changelog.md updates - you overlooked moving the changelog items to the current month (December). Those items are still listed under September 2020.

FYI in general, the date/month associated with a changelog item, whether it's the changelog json or changelog.md, goes by the month that the docs are published.

2020-12-19 06:24 UTC, opbld32 commented
Docs Build status updates of commit _[2dafb96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2dafb963655fb3d9fcf1a4266656353cd53e6e04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-4018c0b1)
[api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get-event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-6b196964-4018c0b1)
[api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-59fa496a-4018c0b1)
[api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-b3590bba-4018c0b1)
[api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-d16ad008-4018c0b1)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/event-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9928) |

<a id="2f98de3e-4018c0b1"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="6b196964-4018c0b1"></a>
### [api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="59fa496a-4018c0b1"></a>
### [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="b3590bba-4018c0b1"></a>
### [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List calendars - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendargroup-list-calendars.md(2,8), v1.0/api/user-list-calendars.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[dupli [...]

2020-12-19 06:26 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +          "Target": "Calendar"
Also, for line 10 and line 28, links should be full HTTP links. The new changelog is a web page on the Microsoft Graph portal on developer.microsoft.com (https://developer.microsoft.com/en-us/graph/changelog), not docs.microsoft.com, so links to the Graph docs should be full HTTP links.

2020-12-19 06:27 UTC, opbld33 commented
Docs Build status updates of commit _[a013dbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a013dbd613d2e21afcfad74cf582021caa91964d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-a99fb978)
[api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get-event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-6b196964-a99fb978)
[api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-59fa496a-a99fb978)
[api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-b3590bba-a99fb978)
[api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-d16ad008-a99fb978)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/event-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="2f98de3e-a99fb978"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="6b196964-a99fb978"></a>
### [api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="59fa496a-a99fb978"></a>
### [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="b3590bba-a99fb978"></a>
### [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List calendars - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendargroup-list-calendars.md(2,8), v1.0/api/user-list-calendars.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List calendars' is duplicated with other articles: 'v1.0/api/calendargroup-list-calendars.md(10,1), v1.0/api/user-list-calendars.md(10,1)'.  [...]

2020-12-19 06:33 UTC, opbld30 commented
Docs Build status updates of commit _[3565ef8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3565ef8c3e2a0a7cff1b9e9dc6de80ebc985ba7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-dfb26e67)
[api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get-event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-6b196964-dfb26e67)
[api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-59fa496a-dfb26e67)
[api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-b3590bba-dfb26e67)
[api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-calendars.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) | [Details](#user-content-d16ad008-dfb26e67)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/event-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-9928) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9928) |

<a id="2f98de3e-dfb26e67"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="6b196964-dfb26e67"></a>
### [api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-get-event.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="59fa496a-dfb26e67"></a>
### [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/group-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="b3590bba-dfb26e67"></a>
### [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/Haxcolor/IsDraft/v1/api-reference/v1.0/api/user-list-calendars.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List calendars - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendargroup-list-calendars.md(2,8), v1.0/api/user-list-calendars.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[dupli [...]

2020-12-19 06:35 UTC, merged

2020-12-19 06:39 UTC, angelgolfer-ms commented
@Bhupesh12Hub , there were a few issues with both the changelog.md and changelog json. Please make sure you got the comments I had left last time for the items in changelog.md.
In the interest of time (as today is the last day to publish this year), I had fixed these issues directly so that I can merge this PR. Please take a look at my commits so that in the future, you can handle the similar appropriately.