Access review v2 api
microsoftgraph/microsoft-graph-docs pull request #9935
Opened 2020-09-15 22:26 UTC by isabelleatmsft

Documentation for V2 of Access Reviews APIs.

2020-09-15 22:27 UTC, opbld32 commented
Docs Build status updates of commit _[42c1f8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42c1f8e35685d8471fe4db55eccd0ee53bb70653)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-fe2160ee-aaffb8b4)
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d4387319-aaffb8b4)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="fe2160ee-aaffb8b4"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````
 - **Line 18, Column 64**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````
 - **Line 143, Column 3**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````

<a id="d4387319-aaffb8b4"></a>
### [api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md)
 - **Line 53, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstances.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009152226278308-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JxoPJZ%2BqfVxUcJAwginmKlfhxNJV0JFjtV%2FMUQtEVxA%3D&st=2020-09-15T22%3A22%3A49Z&se=2020-10-16T22%3A27%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 15:00 UTC, opbld34 commented
Docs Build status updates of commit _[52391ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52391ae7db182812bc2aea29a0fc326e7082802f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-fe2160ee-1fecf843)
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-dc25d172-1fecf843)
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d4387319-1fecf843)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="fe2160ee-1fecf843"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````
 - **Line 18, Column 64**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````
 - **Line 143, Column 3**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````

<a id="dc25d172-1fecf843"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md)
 - **Line 18, Column 96**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance.md'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'Update accessReview' is duplicated with other articles: 'beta/api/accessreviewscheduledefinition-update.md(10,1), beta/api/accessreview-update.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="d4387319-1fecf843"></a>
### [api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md)
 - **Line 55, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstances.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009161458531768-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rUSeMmlUEvEFVzk46hgTxbk0zovrEt9d0dlT5oQHZ7o%3D&st=2020-09-16T14%3A55%3A11Z&se=2020-10-17T15%3A00%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 18:02 UTC, opbld30 commented
Docs Build status updates of commit _[6d5a436](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d5a4361e868335bce98f95df67f1f9014d2adb0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-fe2160ee-e2101025)
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-dc25d172-e2101025)
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d4387319-e2101025)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="fe2160ee-e2101025"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````
 - **Line 18, Column 64**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````
 - **Line 142, Column 3**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````

<a id="dc25d172-e2101025"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md)
 - **Line 18, Column 127**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance.md'.`````
 - **Line 45, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="d4387319-e2101025"></a>
### [api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md)
 - **Line 55, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstances.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009161801066469-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eU5Oau9bffou4111h%2F9H0vIZZxEnC2VsyvcW9KlWu8Y%3D&st=2020-09-16T17%3A57%3A23Z&se=2020-10-17T18%3A02%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 18:08 UTC, opbld33 commented
Docs Build status updates of commit _[15c8e7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15c8e7cd5b872de95fb1061c501f8b7e923f0169)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-fe2160ee-529be744)
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-dc25d172-529be744)
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d4387319-529be744)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="fe2160ee-529be744"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````
 - **Line 18, Column 64**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````
 - **Line 142, Column 3**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-list.md'.`````

<a id="dc25d172-529be744"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md)
 - **Line 18, Column 127**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance.md'.`````
 - **Line 45, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="d4387319-529be744"></a>
### [api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md)
 - **Line 55, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstances.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009161806562409-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cvgLx%2Fwk11QcsFf93RWUnmIfgsn53jMuffnqzHEOeCk%3D&st=2020-09-16T18%3A03%3A21Z&se=2020-10-17T18%3A08%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 20:58 UTC, opbld32 commented
Docs Build status updates of commit _[627f826](https://github.com/microsoftgraph/microsoft-graph-docs/commits/627f8264570abb03c0ef173ebd83204009497df5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-ecd76634-6d6c3c0b)
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-fe2160ee-6d6c3c0b)
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-dc25d172-6d6c3c0b)
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e54d038b-6d6c3c0b)
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d4387319-6d6c3c0b)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="ecd76634-6d6c3c0b"></a>
### [api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md)
 - **Line 114, Column 3**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance-get.md'.`````

<a id="fe2160ee-6d6c3c0b"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````

<a id="dc25d172-6d6c3c0b"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md)
 - **Line 18, Column 127**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance.md'.`````
 - **Line 45, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="e54d038b-6d6c3c0b"></a>
### [api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md)
 - **Line 48, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstancedecisionitem.md'.`````

<a id="d4387319-6d6c3c0b"></a>
### [api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md)
 - **Line 55, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstances.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162056355342-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jjlfniCI4psYBpUaonMwj3t2%2BAIY3qc%2FKlz9r%2Bo0bng%3D&st=2020-09-16T20%3A53%3A04Z&se=2020-10-17T20%3A58%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 22:47 UTC, opbld31 commented
Docs Build status updates of commit _[bb1d627](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb1d627bfcb3dc79c592b9e2e2670e06eb0687a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-682e57a8-cfd2634a)
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-fe2160ee-cfd2634a)
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-dc25d172-cfd2634a)
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d4387319-cfd2634a)
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="682e57a8-cfd2634a"></a>
### [api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````
 - **Line 18, Column 52**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstancedecisionitem-list.md'.`````

<a id="fe2160ee-cfd2634a"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````

<a id="dc25d172-cfd2634a"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md)
 - **Line 18, Column 127**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance.md'.`````
 - **Line 45, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="d4387319-cfd2634a"></a>
### [api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md)
 - **Line 55, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstances.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172246342442-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yFfLqdXpLDbpLc3BNC9j4%2FgPimoSOIgo3ZiDS%2FRLS%2FA%3D&st=2020-09-17T22%3A42%3A55Z&se=2020-10-18T22%3A47%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/he [...]

2020-09-18 22:02 UTC, opbld32 commented
Docs Build status updates of commit _[d8d1553](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8d15535f8e5051596987a465daeae2eafce5b40)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-682e57a8-76dbd4a4)
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-2b509d78-76dbd4a4)
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-fe2160ee-76dbd4a4)
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-dc25d172-76dbd4a4)
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d4387319-76dbd4a4)
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="682e57a8-76dbd4a4"></a>
### [api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````

<a id="2b509d78-76dbd4a4"></a>
### [api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=master)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="fe2160ee-76dbd4a4"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md)
 - **Line 16, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../resources/accessreview-root.md'.`````

<a id="dc25d172-76dbd4a4"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md)
 - **Line 18, Column 127**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance.md'.`````
 - **Line 45, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="d4387319-76dbd4a4"></a>
### [api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md)
 - **Line 55, Column 30**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstances.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod [...]

2020-09-21 20:58 UTC, opbld31 commented
Docs Build status updates of commit _[7bdaf25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bdaf25729b1e0ef31398cfead37fe123449ce98)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-2b509d78-3ea4f3d5)
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-dc25d172-3ea4f3d5)
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-0ca5a09a-3ea4f3d5)
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

<a id="2b509d78-3ea4f3d5"></a>
### [api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=master)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="dc25d172-3ea4f3d5"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md)
 - **Line 18, Column 127**: **[Warning-file-not-found]** `````Invalid file link: 'accessreviewinstance.md'.`````
 - **Line 45, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="0ca5a09a-3ea4f3d5"></a>
### [api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'Azure AD access reviews - Microsoft Graph beta [...]

2020-09-21 21:15 UTC, opbld32 commented
Docs Build status updates of commit _[0c5695c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c5695c48ab6f7f8de5efbf5dff37b910b6cc298)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009212114131722-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uQSDfrg1WpXhVDYJEPCxBB5YWTjSSFuvSJ%2Fkh5759RY%3D&st=2020-09-21T21%3A10%3A28Z&se=2020-10-22T21%3A15%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 21:35 UTC, opbld34 commented
Docs Build status updates of commit _[c35599c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c35599c6e0b5b3fc74b2f0f6ca2cda16ed70144a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009212133478284-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dMyYs%2B0EbFSTKtWf8%2BOvPreZjely5pXbcEocKv%2BMdM8%3D&st=2020-09-21T21%3A30%3A05Z&se=2020-10-22T21%3A35%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 22:21 UTC, opbld34 commented
Docs Build status updates of commit _[8dc8de2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8dc8de2d1fd653692900a2cc45583ae81c2d3ee6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009212220113823-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8oA9mUM1B7kGQN8Q37yoA2%2FsZlifm9atfBi2MMwe5%2FM%3D&st=2020-09-21T22%3A16%3A41Z&se=2020-10-22T22%3A21%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 22:33 UTC, opbld34 commented
Docs Build status updates of commit _[f5bbb13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5bbb137c1ac3a10bd5e9bb95789423b7e3b7c60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009212231417236-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jimtBN3tEOVP3Szc0dKxXieOVV4UEwfylqilV9TJu64%3D&st=2020-09-21T22%3A28%3A02Z&se=2020-10-22T22%3A33%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 20:40 UTC, opbld33 commented
Docs Build status updates of commit _[67b4039](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67b403978bd645737ee5032be7578f92a79826ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/e [...]

2020-09-23 20:46 UTC, opbld30 commented
Docs Build status updates of commit _[731fe96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/731fe9689a25809bdd77e8e0100fb9ae4074b843)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/e [...]

2020-09-24 21:29 UTC, opbld30 commented
Docs Build status updates of commit _[4593d49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4593d49c767967f4e5c2727b925ab8c48f76d8a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [ [...]

2020-09-24 21:36 UTC, opbld30 commented
Docs Build status updates of commit _[0a29799](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a297997fbb030cf5e81ed55947d0beb4650c80d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [ [...]

2020-09-25 17:39 UTC, opbld34 commented
Docs Build status updates of commit _[b716737](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b716737f663b16103e2426b51aaac1e8348a91de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succe [...]

2020-09-25 17:48 UTC, opbld34 commented
Docs Build status updates of commit _[282fd86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/282fd863b8143e3e7d3f74bb6b31a6b092350cd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succe [...]

2020-09-25 17:53 UTC, opbld34 commented
Docs Build status updates of commit _[a0eb7ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0eb7ece1e8d48a30071febd408838e173dc060c)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-25 17:55 UTC, opbld34 commented
Docs Build status updates of commit _[a0eb7ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0eb7ece1e8d48a30071febd408838e173dc060c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succe [...]

2020-09-28 19:04 UTC, opbld33 commented
Docs Build status updates of commit _[682ce4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/682ce4fe8e4d3a7d366a7c5af7580fe38bb6e924)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succe [...]

2020-09-28 19:30 UTC, opbld32 commented
Docs Build status updates of commit _[e7cce63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7cce639dd8537a874efbf8e1b2578a9edbb7ce8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succe [...]

2020-09-29 02:32 UTC, opbld33 commented
Docs Build status updates of commit _[8f58ca5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f58ca52ceecb823dcccc014a904a46851d91750)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e54d038b-16fa2f6b)
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemtarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-d1532db5-16fa2f6b)
[api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemusertarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-4465d2e8-16fa2f6b)
[api-reference/beta/resources/accessreviewinstanceserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstanceserviceprincipaltarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstanceserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-43d5118f-16fa2f6b)
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-20fb12a7-16fa2f6b)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta [...]

2020-09-29 02:45 UTC, opbld30 commented
Docs Build status updates of commit _[679c70d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/679c70dea81d0dfb3fda77cbd604cc4ce5d69aa3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-3ff55b44-25504249)
[api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemusertarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-4465d2e8-25504249)
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-20fb12a7-25504249)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/acc [...]

2020-09-29 02:50 UTC, opbld31 commented
Docs Build status updates of commit _[f5f81e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5f81e0c9bd49a27037b4f4c1cba976b02f2e379)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-3ff55b44-0aee3117)
[api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemusertarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-4465d2e8-0aee3117)
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewreviewerscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-20fb12a7-0aee3117)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/acc [...]

2020-09-29 02:59 UTC, opbld33 commented
Docs Build status updates of commit _[b0a8161](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0a81617c22353daa3467e457177489364222ae0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/reso [...]

2020-10-01 17:12 UTC, opbld33 commented
Docs Build status updates of commit _[5700c1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5700c1ed0f301c2ddeabba14fe8ecd4178c7ac66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/reso [...]

2020-10-01 17:47 UTC, opbld33 commented
Docs Build status updates of commit _[554cef5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/554cef52e515bd66c8a8ac430bb1a071224c9918)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-01 17:49 UTC, opbld30 commented
Docs Build status updates of commit _[554cef5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/554cef52e515bd66c8a8ac430bb1a071224c9918)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/reso [...]

2020-10-01 18:05 UTC, opbld33 commented
Docs Build status updates of commit _[7992a62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7992a6235e36811b2746406587aece56ae5517a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/reso [...]

2020-10-02 16:41 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +title: "Accept recommendations for an accessReviewInstance"
```suggestion
title: "acceptRecommendations resource type"
```

2020-10-02 16:42 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +description: "In the Azure AD access reviews feature, allow calling user to accept recommendations on all NotReviewed decisions on an `accessReviewInstance` that they are the reviewer on. "
```suggestion
description: "Allows the acceptance of recommendations on all not reviewed decisions on an access review instance` that they are the reviewer on. "
```

2020-10-02 16:43 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +# Accept recommendations
```suggestion
# acceptRecommendations resource type
```

2020-10-02 16:46 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, the calling user can accept recommendations for every NotReviewed [accessReviewInstanceDecisionItem](../resources/acces
```suggestion
Allows the acceptance of recommendations on all not reviewed [accessReviewInstanceDecisionItem](../resources/accessreviewinstancedecisionitem.md) on an [accessReviewInstance](../resources/accessreviewinstance.md) that they are the reviewer on.
```

2020-10-02 16:47 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +|Delegated (work or school account)     | AccessReview.ReadWrite.All |
There should be a row here for:

| Delegated (personal Microsoft account) | Not supported. |

2020-10-02 16:48 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +The signed in user must also be a reviewer on the `accessReviewInstance`.
```suggestion
The signed in user must also be a reviewer on the accessReviewInstance.
```

We typically use the tick mark to identify user inputted data.

2020-10-02 16:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +POST /me/pendingAccessReviewInstances/{instanceID}/acceptRecommendations
```suggestion
POST /me/pendingAccessReviewInstances/{instance-id}/acceptRecommendations
```

2020-10-02 16:56 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 16:59 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +---
The name of this file should be accessreviewinstance-post-acceptrecommendations.md

2020-10-02 17:04 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +# [HTTP](#tab/http)
The SDK snippets are automatically generated. For a new API, this should not be here. Remove line 45.

2020-10-02 17:05 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +# [C#](#tab/csharp)
Remove lines 53 through 62.

2020-10-02 17:05 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 17:06 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +---
The name of this file should be accessreviewinstance-post-applydecisions.md

2020-10-02 17:07 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +description: "In the Azure AD access reviews feature, apply decisions on an accessReviewInstance. "
```suggestion
description: "Apply decisions on an accessReviewInstance. "
```

2020-10-02 17:17 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +title: "Accept recommendations for an accessReviewInstance"
```suggestion
title: "accessReviewInstance: accessReviewInstance"
```

2020-10-02 17:20 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +title: "Apply accessReviewInstance decisions"
```suggestion
accessReviewInstance: applyDecisions
```

2020-10-02 17:21 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, apply review decisions on an [accessReviewInstance](../resources/accessreviewinstance.md).
```suggestion
Apply review decisions on an [accessReviewInstance](../resources/accessreviewinstance.md).
```

2020-10-02 17:21 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +|Delegated (personal Microsoft account)|None.|
```suggestion
|Delegated (personal Microsoft account)|Not supported.|
```

2020-10-02 17:21 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +POST /identityGovernance/accessReviews/definitions/{definitionId}/instances/{instanceId}/applyDecisions
```suggestion
POST /identityGovernance/accessReviews/definitions/{definition-id}/instances/{instance-id}/applyDecisions
```

2020-10-02 17:23 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, retrieve an [accessReviewInstance](../resources/accessreviewinstance.md) object by ID of **accessReviewInstance** and p
```suggestion
Retrieve an [accessReviewInstance](../resources/accessreviewinstance.md) object using the identifier of an accessReviewInstance and its parent accessReviewScheduleDefinition. This returns all properties of the instance except for the associated accessReviewInstanceDecisionItems.
```

2020-10-02 17:24 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +To retrieve the decisions on the instance, use the [list accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem-list.md) API.
```suggestion
To retrieve the decisions on the instance, use [List accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem-list.md).
```

2020-10-02 17:25 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +description: "In the Azure AD access reviews feature, retrieve an accessReviewInstance object."
```suggestion
description: "Retrieve an accessReviewInstance object."
```

2020-10-02 17:26 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 17:27 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 17:27 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +GET /identityGovernance/accessReviews/definitions/{definitionId}/instances/{instanceId}
```suggestion
GET /identityGovernance/accessReviews/definitions/{definition-id}/instances/{instance-id}
```

2020-10-02 17:28 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 17:29 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +# [HTTP](#tab/http)
Remove line 48.

2020-10-02 17:29 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +# [C#](#tab/csharp)
Remove lines 56 through 65.

2020-10-02 17:30 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 17:39 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 17:41 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
```suggestion
|Delegated (work or school account)     | AccessReview.Read.All, AccessReview.ReadWrite.All  |
```

Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 17:41 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +|Application                            | AccessReview.Read.All or AccessReview.ReadWrite.All |
```suggestion
|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
```

2020-10-02 17:41 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> + The signed in user must also be in a directory role that permits them to read an access review.
```suggestion
 The signed-in user must also be in a directory role that permits them to read an access review.
```

2020-10-02 17:48 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +GET /identityGovernance/accessReviews/definitions/{definitionID}/instances?$top={pagesize}&$skip=0
I this this should be:

GET /identityGovernance/accessReviews/definitions/{definitionID}/instances

And an example can show the parameter use.

2020-10-02 17:52 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +## Example
```suggestion
## Examples
```

2020-10-02 17:52 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +## Example
```suggestion
## Examples
```

2020-10-02 17:54 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +##### Request
This should be a H3, not an H4: ### Response

2020-10-02 17:54 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +# [HTTP](#tab/http)
Remove line 51.

2020-10-02 17:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 18:00 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +title: "List accessReviewInstances pending approval"
accessReviewInstance: pendingAccessReviewInstances

2020-10-02 18:01 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +# List accessReviewInstances pending approval
accessReviewInstance: pendingAccessReviewInstances

2020-10-02 18:03 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 18:07 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
```suggestion
|Delegated (work or school account)     | AccessReview.Read.All, AccessReview.ReadWrite.All  |
```

2020-10-02 18:08 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-get.md
> +|Application                            | AccessReview.Read.All or AccessReview.ReadWrite.All |
```suggestion
|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
```

2020-10-02 18:11 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
```suggestion
|Delegated (work or school account)     | AccessReview.Read.All, AccessReview.ReadWrite.All  |
```

2020-10-02 18:12 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +---
I think the name of this file should be: accessreviewinstance-pendingaccessreviewinstances.md

2020-10-02 18:13 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +Retrieve the [accessReviewInstance](../resources/accessreviewinstance.md) objects pending approval by the calling user. A list of zero or more **accessReviewInstance** objects are returned, of which
```suggestion
Retrieve the [accessReviewInstance](../resources/accessreviewinstance.md) objects pending approval by the calling user. A list of zero or more accessReviewInstance objects are returned, of which the calling user is an assigned reviewer.
```

2020-10-02 18:14 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +|Application                            | AccessReview.Read.All or AccessReview.ReadWrite.All |
```suggestion
|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
```

2020-10-02 18:16 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> + The signed in user must also be in a directory role that permits them to read an access review. The signed in user will also only see instances of which they are assigned reviewer in that instance's
```suggestion
 The signed-in user must also be in a directory role that permits them to read an access review. The signed in user only sees instances of which they are assigned reviewer in the accessReviewScheduleDefinition of the instance.
```

2020-10-02 18:16 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +GET /me/pendingAccessReviewInstances?$expand=definition&$top={pagesize}&$skip=0
```suggestion
GET /me/pendingAccessReviewInstances
```

2020-10-02 18:17 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +##### Request
This should be a H3, not an H4: ### Response

2020-10-02 18:18 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +# [HTTP](#tab/http)
Remove line 51

2020-10-02 18:18 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +# [C#](#tab/csharp)
Remove lines 60 through 67.

2020-10-02 18:18 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 18:27 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +title: "SendReminder accessReviewInstance"
accessReviewInstance: sendReminder

2020-10-02 18:27 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +description: "In the Azure AD access reviews feature, send a reminder to the reviewers of a currently active accessReviewInstance."
```suggestion
description: "Sends a reminder to the reviewers of a currently active accessReviewInstance."
```

2020-10-02 18:27 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +# SendReminder accessReviewInstance
accessReviewInstance: sendReminder

2020-10-02 18:28 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, send a reminder to the reviewers of a currently active [accessReviewInstance](../resources/accessreviewinstance.md).
```suggestion
Send a reminder to the reviewers of a currently active [accessReviewInstance](../resources/accessreviewinstance.md).
```

2020-10-02 18:29 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +|Delegated (work or school account)     | AccessReview.ReadWrite.All |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 18:29 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +## HTTP request
Remove line 26.

2020-10-02 18:29 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +## Example
```suggestion
## Examples
```

2020-10-02 18:30 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 18:30 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +# [HTTP](#tab/http)
Remove line 43.

2020-10-02 18:30 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +# [C#](#tab/csharp)
Remove lines 51 through 60.

2020-10-02 18:31 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 18:31 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +description: "In the Azure AD access reviews feature, stop a currently active accessReviewInstance."
```suggestion
description: "Stop a currently active accessReviewInstance."
```

2020-10-02 18:32 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, stop a currently active [accessReviewInstance](../resources/accessreviewinstance.md). (To prevent a recurring access re
```suggestion
Stop a currently active [accessReviewInstance](../resources/accessreviewinstance.md). To prevent a recurring access review from starting future instances, [update it](accessreviewscheduledefinition-update.md) to change its scheduled end date.  After the access review stops, reviewers can no longer give input, and the access review decisions can be applied.
```

2020-10-02 18:33 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +|Delegated (work or school account)     | AccessReview.ReadWrite.All |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 18:33 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +## HTTP request
Remove line 25.

2020-10-02 18:33 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +POST /identityGovernance/accessReviews/definitions/{definitionId}/instances/{instanceId}/stop
```suggestion
POST /identityGovernance/accessReviews/definitions/{definition-id}/instances/{instance-id}/stop
```

2020-10-02 18:33 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +## Example
```suggestion
## Examples
```

2020-10-02 18:34 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 18:34 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +# [HTTP](#tab/http)
Remove line 43.

2020-10-02 18:35 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +# [C#](#tab/csharp)
Remove lines 51 through 60.

2020-10-02 18:35 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-stop.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 18:36 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +Retrieve the [accessReviewInstanceDecisionItem](../resources/accessreviewinstance.md) objects for a specific [accessReviewInstance](../resources/accessreviewscheduledefinition.md). A list of zero or
```suggestion
Retrieve the [accessReviewInstanceDecisionItem](../resources/accessreviewinstance.md) objects for a specific [accessReviewInstance](../resources/accessreviewscheduledefinition.md). A list of zero or more accessReviewInstanceDecisionItem objects are returned, including all of their nested properties.
```

2020-10-02 18:36 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 18:36 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
```suggestion
|Delegated (work or school account)     | AccessReview.Read.All, AccessReview.ReadWrite.All  |
```

2020-10-02 18:37 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 18:37 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +|Application                            | AccessReview.Read.All or AccessReview.ReadWrite.All |
```suggestion
|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
```

2020-10-02 18:37 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> + The signed in user must also be in a directory role that permits them to read an access review.
```suggestion
 The signed-in user must also be in a directory role that permits them to read an access review.
```

2020-10-02 18:38 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +GET /identityGovernance/accessReviews/definitions/{definitionID}/instances/{instanceID}/decisions?$top={pagesize}&$skip=0
```suggestion
GET /identityGovernance/accessReviews/definitions/{definition-id}/instances/{instance-id}/decisions
```

2020-10-02 18:38 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 18:39 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +# [HTTP](#tab/http)
Remove line 51.

2020-10-02 18:39 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +# [C#](#tab/csharp)
Remove lines 60 through 70.

2020-10-02 18:40 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +##### Response
This should be a H3, not an H4: ### Response.

2020-10-02 18:45 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +---
It seems like the title of this page should be: pendingAccessReviewInstances: decisions.

The name of the file should change to match.

2020-10-02 18:46 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +# List accessReviewInstanceDecisionItems pending approval
pendingAccessReviewInstances: decisions

2020-10-02 18:47 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +Retrieve the [accessReviewInstanceDecisionItem](../resources/accessreviewinstance.md) objects for a specific [accessReviewInstance](../resources/accessreviewscheduledefinition.md) pending approval by
```suggestion
Retrieve the [accessReviewInstanceDecisionItem](../resources/accessreviewinstance.md) objects for a specific [accessReviewInstance](../resources/accessreviewscheduledefinition.md) pending approval by the calling user. A list of zero or more accessReviewInstanceDecisionItem objects are returned, including all of their nested properties.
```

2020-10-02 18:48 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 18:48 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
```suggestion
|Delegated (work or school account)     | AccessReview.Read.All, AccessReview.ReadWrite.All  |
```

2020-10-02 18:49 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 18:49 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +|Application                            | AccessReview.Read.All or AccessReview.ReadWrite.All |
```suggestion
|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
```

2020-10-02 18:50 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> + The signed in user must also be in a directory role that permits them to read an access review. The signed in user will also only see decisions of which they are assigned reviewer in that decision's
```suggestion
 The signed-in user must also be in a directory role that permits them to read an access review. The signed-in user will also only see decisions of which they are assigned reviewer in that decision's instance's `accessReviewScheduleDefinition`.
```

2020-10-02 18:50 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +GET /me/pendingAccessReviewInstances/{instanceID}/decisions?$top={pagesize}&$skip=0
```suggestion
GET /me/pendingAccessReviewInstances/{instanceID}/decisions
```

2020-10-02 18:51 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 18:51 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +# [HTTP](#tab/http)
Remove line 51.

2020-10-02 18:52 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +# [C#](#tab/csharp)
Remove lines 60 through 70.

2020-10-02 18:52 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 18:53 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +title: "Patch accessReviewInstanceDecisionItem"
```suggestion
title: "Update accessReviewInstanceDecisionItem"
```

2020-10-02 18:53 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +description: "In the Azure AD access reviews feature, update an existing accessReviewInstanceDecisionItem object that calling user is the reviewer of."
```suggestion
description: "Update an existing accessReviewInstanceDecisionItem object that calling user is the reviewer of."
```

2020-10-02 18:54 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +>[!NOTE]
This note should go after the introduction paragraph.

2020-10-02 18:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, reviewers can use this API to update access decisions, known as [accessReviewInstanceDecisionItems](../resources/access
```suggestion
Update access decisions, known as [accessReviewInstanceDecisionItems](../resources/accessreviewinstancedecisionitem.md), for which the user is the reviewer.
```

2020-10-02 18:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +|Delegated (work or school account)     | AccessReview.ReadWrite.All |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 18:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +PATCH /me/pendingAccessReviewInstances/{instanceID}/decisions/{decisionID}
```suggestion
PATCH /me/pendingAccessReviewInstances/{instance-id}/decisions/{decision-id}
```

2020-10-02 18:56 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +| `decision`             |`String`                      | Access decision for the entity being reviewed. Possible values are: `Approve` `Deny` `NotReviewed` `DontKnow`. |
```suggestion
| decision  | String | Access decision for the entity being reviewed. Possible values are: `Approve` `Deny` `NotReviewed` `DontKnow`.  |
```

2020-10-02 18:56 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +| `justification`    |`String`                       | Context of the review provided to admins. |
```suggestion
|  justification | String | Context of the review provided to admins. |
```

2020-10-02 18:57 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +# [HTTP](#tab/http)
Remove item 56.

2020-10-02 18:57 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +# [C#](#tab/csharp)
Remove lines 69 through 78.

2020-10-02 18:58 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +
### Request

2020-10-02 18:58 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +## Example
```suggestion
## Examples
```

2020-10-02 18:59 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 18:59 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +description: "In the Azure AD access reviews feature, create a new accessReviewScheduleDefinition object."
```suggestion
description: "Create a new accessReviewScheduleDefinition object."
```

2020-10-02 19:00 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, create a new [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object.
```suggestion
Create a new [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object.
```

2020-10-02 19:00 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 19:00 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +|Delegated (work or school account)     | AccessReview.ReadWrite.All  |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 19:01 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +The signed in user must also be in a directory role that permits them to create an access review.  For more details, see the role and permission requirements for [access reviews](../resources/accessr
```suggestion
The signed-in user must also be in a directory role that permits them to create an access review.  For more details, see the role and permission requirements for [access reviews](../resources/accessreviewsv2-root.md).
```

2020-10-02 19:02 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| `displayName`             |`String`                     | Yes       | Name of access review series.|
```suggestion
| displayName | String | Name of access review series.|
```

2020-10-02 19:02 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| Property     | Type       | Required | Description |
I would suggest removing the Required column and putting that in the description.
```suggestion
| Property | Type | Description |
```

2020-10-02 19:03 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +|:-------------|:------------|:-----|:------------|
```suggestion
|:-------------|:------------|:------------|
```

2020-10-02 19:03 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| `descriptionForAdmins`    |`string`                     | Yes        | Context of the review provided to admins. |
```suggestion
| descriptionForAdmins | string | Context of the review provided to admins. Required. |
```

2020-10-02 19:04 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| `descriptionForReviewers` |`string`                     | Yes        | Context of the review provided to reviewers. |
```suggestion
|  descriptionForReviewers | string | Context of the review provided to reviewers. Required. |
```

2020-10-02 19:05 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| `scope`                   |`microsoft.graph.accessReviewScope` | Yes | Defines scope of users reviewed in a group. See  [accessReviewScope](../resources/accessreviewscheduledefinition.md). |
```suggestion
| scope |  [accessReviewScope](accessreviewscope.md) | Defines the scope of users reviewed in a group. See  [accessReviewScope](../resources/accessreviewscheduledefinition.md). Required.| 
```

2020-10-02 19:07 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| `instanceEnumerationScope`|`microsoft.graph.accessReviewScope` | No | In the case of an all groups review, this determines the scope of which groups will be reviewed. See [accessReviewScope](../res
```suggestion
| instanceEnumerationScope | [accessReviewScope](accessreviewscope.md) | In the case of an all groups review, this determines the scope of which groups will be reviewed. See [accessReviewScope](../resources/accessreviewscheduledefinition.md). | 
```

2020-10-02 19:09 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| `settings`                |`microsoft.graph.accessReviewScheduleSettings`| No | The settings for an access review series. Recurrence is determined here. See [accessReviewScheduleSettings](../resour
```suggestion
| settings` | [accessReviewScheduleSettings](../resources/accessreviewschedulesettings.md)| No | The settings for an access review series. Recurrence is determined here. See [accessReviewScheduleSettings](../resources/accessreviewscheduledefinition.md). |
```

2020-10-02 19:10 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| `reviewers`               |`Collection(microsoft.graph.accessReviewReviewerScope)`| No | Defines who the reviewers are. If none are specified, the review will be a self-review (users reviewed revie
```suggestion
| reviewers | [accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) | Defines who the reviewers are. If none are specified, the review is a self-review (users reviewed review their own access). See [accessReviewReviewerScope](../resources/accessreviewscheduledefinition.md). |
```

2020-10-02 19:10 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +## Example
```suggestion
## Examples
```

2020-10-02 19:11 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +description: "In the Azure AD access reviews feature, delete an accessReviewScheduleDefinition object."
```suggestion
description: "Delete an accessReviewScheduleDefinition object."
```

2020-10-02 19:11 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, delete an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object.
```suggestion
Delete an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object.
```

2020-10-02 19:12 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +One of the following permissions is required to call this API.Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permissi
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 19:12 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +|Delegated (work or school account)     | AccessReview.ReadWrite.All  |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 19:12 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +DELETE /identityGovernance/accessReviews/definitions/{reviewID}
```suggestion
DELETE /identityGovernance/accessReviews/definitions/{review-id}
```

2020-10-02 19:13 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +## Example
```suggestion
## Examples
```

2020-10-02 19:13 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 19:14 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +# [HTTP](#tab/http)
Remove line 43.

2020-10-02 19:14 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +# [C#](#tab/csharp)
Remove lines 51 through 60.

2020-10-02 19:14 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 19:15 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +description: "In the Azure AD access reviews feature, retrieve an accessReviewScheduleDefinition object."
```suggestion
description: "Retrieve an accessReviewScheduleDefinition object."
```

2020-10-02 19:15 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, retrieve an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object by ID. This returns
```suggestion
Retrieve an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object by ID. This returns all properties of the scheduled access review series except for the associated accessReviewInstances. Each accessReviewScheduleDefinition has at least one instance, representing each recurrence of the review, as well as individual groups being reviewed.
```

2020-10-02 19:15 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 19:16 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
```suggestion
|Delegated (work or school account)     | AccessReview.Read.All, AccessReview.ReadWrite.All  |
```

2020-10-02 19:16 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 19:16 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +|Application                            | AccessReview.Read.All or AccessReview.ReadWrite.All |
```suggestion
|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
```

2020-10-02 19:17 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +In order to call this API, the signed in user must also be in a directory role that permits them to read an access review, or the user can be assigned as a reviewer on the access review.  For more de
```suggestion
To call this API, the signed-in user must also be in a directory role that permits them to read an access review, or the user can be assigned as a reviewer on the access review.  For more details, see the role and permission requirements for [access reviews](../resources/accessreviewsv2-root.md).
```

2020-10-02 19:17 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +GET /identityGovernance/accessReviews/definitions/{reviewID}
```suggestion
GET /identityGovernance/accessReviews/definitions/{review-id}
```

2020-10-02 19:17 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +## Example
```suggestion
## Examples
```

2020-10-02 19:18 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 19:18 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +# [HTTP](#tab/http)
Remove line 48.

2020-10-02 19:18 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +# [C#](#tab/csharp)
Remove lines 56 through 65.

2020-10-02 19:19 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 19:19 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +Retrieve the [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) objects. A list of zero or more **accessReviewScheduleDefinition** objects are returned, including all of
```suggestion
Retrieve the [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) objects. A list of zero or more accessReviewScheduleDefinition objects are returned, including all of their nested properties, for each access review series created. This does not include associated accessReviewInstances.
```

2020-10-02 19:20 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 19:21 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
```suggestion
|Delegated (work or school account)     | AccessReview.Read.All, AccessReview.ReadWrite.All  |
```

2020-10-02 19:21 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +|Delegated (work or school account)     | AccessReview.Read.All or AccessReview.ReadWrite.All  |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 19:21 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +|Application                            | AccessReview.Read.All or AccessReview.ReadWrite.All |
```suggestion
|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
```

2020-10-02 19:21 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> + The signed in user must also be in a directory role that permits them to read an access review.
```suggestion
 The signed-in user must also be in a directory role that permits them to read an access review.
```

2020-10-02 19:22 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +GET /identityGovernance/accessReviews/definitions?$top={pagesize}&$skip=0
```suggestion
GET /identityGovernance/accessReviews/definitions
```

2020-10-02 19:22 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 19:22 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +# [HTTP](#tab/http)
Remove line 52.

2020-10-02 19:23 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +# [C#](#tab/csharp)
Remove lines 61 through 75.

2020-10-02 19:23 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 19:24 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +description: "In the Azure AD access reviews feature, update an existing accessReviewScheduleDefinition object to change one or more of its properties."
```suggestion
description: "Update an existing accessReviewScheduleDefinition object to change one or more of its properties."
```

2020-10-02 19:24 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +>[!NOTE]
This note should be moved to after the introduction paragraph.

2020-10-02 19:25 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +>Any updates made to an **accessReviewScheduleDefinition** will only apply to future instances. Currently running instances cannot be updated.
```suggestion
>Any updates made to an accessReviewScheduleDefinition only apply to future instances. Currently running instances cannot be updated.
```

2020-10-02 19:25 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +>Additionally, this API is not intended to update properties, including decisions, on the **accessReviewInstance** level. See [accessReviewInstance](../resources/accessreviewinstance.md) for more inf
```suggestion
>Additionally, this API is not intended to update properties, including decisions, on the accessReviewInstance level. See [accessReviewInstance](../resources/accessreviewinstance.md) for more information on instances.
```

2020-10-02 19:25 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +In the Azure AD [access reviews](../resources/accessreviewsv2-root.md) feature, update an existing [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object to change on
```suggestion
Update an existing [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object to change one or more of its properties.
```

2020-10-02 19:25 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +One of the following permissions is required to call this API. Delegated permissions to personal Microsoft accounts are not supported. To learn more, including how to choose permissions, see [Permiss
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
```

2020-10-02 19:26 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +|Delegated (work or school account)     | AccessReview.ReadWrite.All |
Add this row:

|Delegated (personal Microsoft account)|Not supported.|

2020-10-02 19:26 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +PUT /identityGovernance/accessReviews/definitions/{reviewID}
```suggestion
PUT /identityGovernance/accessReviews/definitions/{review-id}
```

2020-10-02 19:29 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +|:-------------|:------------|
|Authorization|Bearer {token}. Required.|

2020-10-02 19:29 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +|:-------------|:------------|
|Authorization|Bearer {token}. Required.|

2020-10-02 19:30 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +|:-------------|:------------|
|Authorization|Bearer {token}. Required.|

2020-10-02 19:31 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +| Property     | Type       | Description | Additional Notes |
Recommend combining Description and Additional Notes.
```suggestion
| Property | Type | Description |
```

2020-10-02 19:32 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +|:-------------|:------------|:------------|:------------|
```suggestion
|:-------------|:------------|:------------|
```

2020-10-02 19:32 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +| `displayName`             |`String`                      | Name of access review series.|
```suggestion
| displayName | String | Name of access review series. |
```

2020-10-02 19:33 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +| `descriptionForAdmins`    |`String`                       | Context of the review provided to admins. |
```suggestion
| descriptionForAdmins | String | Context of the review provided to admins. |
```

2020-10-02 19:33 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +| `descriptionForReviewers` |`String`                         | Context of the review provided to reviewers. |
```suggestion
| descriptionForReviewers | String | Context of the review provided to reviewers. |
```

2020-10-02 19:34 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +| `settings`                |`microsoft.graph.accessReviewScheduleSettings`| The settings for an access review series. Recurrence is determined here. See [accessReviewScheduleSettings](../resources/a
```suggestion
| settings | [accessReviewScheduleSettings](../resources/accessreviewschedulesettings.md) | The settings for an access review series. See [accessReviewScheduleSettings](../resources/accessreviewscheduledefinition.md). |
```

2020-10-02 19:37 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +| `reviewers`               |`Collection(microsoft.graph.accessReviewReviewerScope)`|  Defines who the reviewers are. If none are specified, the review will be a self-review (users reviewed review th
```suggestion
| reviewers | [accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) collection|  Defines who the reviewers are. If none are specified, the review is a self-review (users reviewed review their own access). The Reviewers property is only updatable if individual users assigned are as reviewers. See [accessReviewReviewerScope](../resources/accessreviewscheduledefinition.md). | 
```

2020-10-02 19:38 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +##### Request
This should be a H3, not an H4: ### Request

2020-10-02 19:38 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +## Example
```suggestion
## Examples
```

2020-10-02 19:39 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +# [HTTP](#tab/http)
Remove line 67.

2020-10-02 19:39 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +# [C#](#tab/csharp)
Remove lines 111 through 120.

2020-10-02 19:40 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +##### Response
This should be a H3, not an H4: ### Response

2020-10-02 19:40 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewapplyaction.md
> +description: "In the Azure AD access reviews feature, the `accessReviewApplyAction` represents the action to take on reviewed users after an access review instance is completed."
```suggestion
description: "Represents the action to take on reviewed users after an access review instance is completed."
```

2020-10-02 19:41 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewapplyaction.md
> +**accessReviewApplyAction** is a complex type representing a base class for apply actions in the [accessReviewScheduleSettings](accessreviewschedulesettings.md) of an [accessReviewScheduleDefinition]
```suggestion
**Represents a base class for apply actions in the [accessReviewScheduleSettings](accessreviewschedulesettings.md) of an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md). Supported derived types: removeAccessApplyAction and disableAndDeleteApplyAction.
```

2020-10-02 19:43 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewapplyaction.md
> +**removeAccessApplyAction** is a derived type of `accessReviewApplyAction` that indicates removing access of an entity being reviewed upon completion of the review. This is the default type for the `
```suggestion
- **removeAccessApplyAction** is a derived type of accessReviewApplyAction that indicates removing access of an entity being reviewed upon completion of the review. This is the default type for the applyActions property in accessReviewScheduleSettings and does not need to be specified.
```

2020-10-02 19:44 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewapplyaction.md
> +**disableAndDeleteUserApplyAction** is a derived type of `accessReviewApplyAction` that indicates disabling and deleting the user being reviewed upon completion of the review. This is the non-default
```suggestion
- **disableAndDeleteUserApplyAction** is a derived type of accessReviewApplyAction that indicates disabling and deleting the user being reviewed upon completion of the review. This is the non-default type and needs to specified in accessReviewScheduleSettings.
```

2020-10-02 19:44 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewapplyaction.md
> +|Property|Type|Description|
If there aren't any properties, remove the table and say None.

2020-10-02 19:45 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +description: "In the Azure AD access reviews feature, the `accessReviewInstance` represents a recurrence of an `accessReviewScheduleDefinition`."
```suggestion
description: "Represents a recurrence of an accessReviewScheduleDefinition."
```

2020-10-02 19:45 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +Represents an Azure AD [access review](accessreviewsv2-root.md) recurrence. If the parent **accessReviewScheduleDefinition** is a recurring access review, instances represent each recurrence. A revie
```suggestion
Represents an Azure AD [access review](accessreviewsv2-root.md) recurrence. If the parent accessReviewScheduleDefinition is a recurring access review, instances represent each recurrence. A review that does not recur will have exactly one instance. Instances also represent each unique group being reviewed in the schedule definition. If a schedule definition reviews multiple groups, each group will have a unique instance for each recurrence.
```

2020-10-02 19:46 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| Method		   | Return Type	|Description|
```suggestion
| Method | Return Type | Description |
```

2020-10-02 19:47 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +|[Get accessReviewInstance](../api/accessreviewinstance-get.md) | [accessReviewInstance](accessreviewinstance.md) | Returns `accessReviewInstance` for an `accessReviewScheduleDefinition`. Does not in
```suggestion
|[Get accessReviewInstance](../api/accessreviewinstance-get.md) | [accessReviewInstance](accessreviewinstance.md) | Returns accessReviewInstance for an accessReviewScheduleDefinition. Does not include associated accessReviewInstanceDecisionItem`s in the object. |
```

2020-10-02 19:47 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +|[List pendingAccessReviewInstances](../api/accessreviewinstance-listpendingapproval.md) | [accessReviewInstance](accessreviewinstance.md) collection. | Get all pending `accessReviewInstance` resourc
```suggestion
|[List pendingAccessReviewInstances](../api/accessreviewinstance-listpendingapproval.md) | [accessReviewInstance](accessreviewinstance.md) collection. | Get all pending accessReviewInstance resources assigned to the calling user. |
```

2020-10-02 19:47 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +|[Send accessReviewInstance reminder](../api/accessreviewinstance-sendreminder.md) | None. | Send a reminder to the reviewers of an `accessReviewInstance`. |
```suggestion
|[Send accessReviewInstance reminder](../api/accessreviewinstance-sendreminder.md) | None. | Send a reminder to the reviewers of an accessReviewInstance. |
```

2020-10-02 19:47 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +|[Stop accessReviewInstance](../api/accessreviewinstance-stop.md) | None. | Manually stop an `accessReviewInstance`. |
```suggestion
|[Stop accessReviewInstance](../api/accessreviewinstance-stop.md) | None. | Manually stop an accessReviewInstance. |
```

2020-10-02 19:48 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +|[Accept recommendations](../api/accessreviewinstance-acceptrecommendations.md) | None. | Allows the calling user to accept the decision recommendation for each NotReviewed `accessReviewInstanceDecis
```suggestion
|[Accept recommendations](../api/accessreviewinstance-acceptrecommendations.md) | None. | Allows the calling user to accept the decision recommendation for each NotReviewed accessReviewInstanceDecisionItem that they are the reviewer on for a specific accessReviewInstance. |
```

2020-10-02 19:48 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +|[Apply decisions](../api/accessreviewinstance-applydecisions.md) | None. | Manually apply decision on an `accessReviewInstance`. |
```suggestion
|[Apply decisions](../api/accessreviewinstance-applydecisions.md) | None. | Manually apply decision on an accessReviewInstance. |
```

2020-10-02 19:48 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| Property                  | Type                                |  Description |
```suggestion
| Property | Type | Description |
```

2020-10-02 19:49 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `id`                      |`String`                                                         | Unique identifier of the instance |
```suggestion
| id | String | Unique identifier of the instance. |
```

2020-10-02 19:49 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `displayName`             |`String`                                                         | Name of the parent `accessReviewScheduleDefinition` |
```suggestion
| displayName | String | Name of the parent accessReviewScheduleDefinition. |
```

2020-10-02 19:50 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `startDateTime`           |`DateTimeOffset`                                                 | DateTime when review instance is scheduled to start. May be in the future. |
```suggestion
| startDateTime | DateTimeOffset | DateTime when review instance is scheduled to start. May be in the future. |
```

2020-10-02 19:50 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `endDateTime`             |`DateTimeOffset`                                                 | DateTime when review instance is scheduled to end. |
```suggestion
| endDateTime | DateTimeOffset | DateTime when review instance is scheduled to end. |
```

2020-10-02 19:51 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `status`                  |`string`                                                          | Read-only. Field specifies the status of an accessReview. The typical states include `Initializing`, `
```suggestion
| status | string | Specifies the status of an accessReview. The typical states include `Initializing`, `NotStarted`, `Starting`, `InProgress`, `Completing`, `Completed`, `AutoReviewing`, and `AutoReviewed`.  Read-only.|
```

2020-10-02 19:53 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `scope`                   |`microsoft.graph.accessReviewScope`                              | Read-only. Created based on `scope` and `instanceEnumerationScope` at the `accessReviewScheduleDefiniti
```suggestion
| scope | [accessReviewScope](accessreviewscope.md) | Created based on **scope** and **instanceEnumerationScope** at the accessReviewScheduleDefinition level. Defines the scope of users reviewed in a group. In the case of a single-group review, the scope defined at the `accessReviewScheduleDefinition` level applies to all instances. In the case of all groups review, scope may be different for each group. Read-only.  | 
```

2020-10-02 19:54 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `decisions`               |`Collection(microsoft.graph.accessReviewInstanceDecisionItem)`  | Set of decisions for this review instance. |
```suggestion
| decisions | [accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem.md) collection  | Set of decisions for this review instance. |
```

2020-10-02 19:55 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `definition`              |`microsoft.graph.accessReviewScheduleDefinition`                | Back link to the `accessReviewScheduleDefinition` associated with the instance. |
```suggestion
| definition | [accessReviewScheduleDefinition](accessreviewscheduledecision.md) | Back link to the accessReviewScheduleDefinition associated with the instance. |
```

2020-10-02 19:55 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `definition`               |[accessReviewScheduleDefinition](accessreviewscheduledefinition.md)          | There is exactly one `accessReviewScheduleDefinition` associated with each instance. It is
```suggestion
| definition |[accessReviewScheduleDefinition](accessreviewscheduledefinition.md) | There is exactly one accessReviewScheduleDefinition associated with each instance. It is the parent schedule for the instance, where instances are created for each recurrence of a review definition and each group selected to review by the definition. |
```

2020-10-02 19:56 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +| `decisions`               |[accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem.md) collection        | Each user reviewed in an `accessReviewInstance` has a decision item representi
```suggestion
| decisions | [accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem.md) collection | Each user reviewed in an accessReviewInstance has a decision item representing if they were approved, denied, or not yet reviewed. |
```

2020-10-02 19:58 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstance.md
> +## user
This shouldn't be here. I'm not seeing where it is referenced, but it seems like a complex type that needs to be documented. It won't be able to use "user" as a name because that resource already exists.

2020-10-02 19:59 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +description: "In the Azure AD access reviews feature, the `accessReviewInstanceDecisionItem` represents a decision on a user's access on an `accessReviewInstance`."
```suggestion
description: "Represents a decision on a user's access on an accessReviewInstance."
```

2020-10-02 19:59 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| Method		   | Return Type	|Description|
```suggestion
| Method | Return Type | Description |
```

2020-10-02 20:00 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +|[List accessReviewInstanceDecisionItems pending approval](../api/accessreviewinstancedecisionitem-listpendingapproval.md) | [accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem.md) co
```suggestion
|[List accessReviewInstanceDecisionItems pending approval](../api/accessreviewinstancedecisionitem-listpendingapproval.md) | [accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem.md) collection. | Get all accessReviewInstanceDecisionItems assigned to the calling user, for a specific accessReviewInstance. |
```

2020-10-02 20:00 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +|[Update accessReviewInstanceDecisionItem](../api/accessreviewinstancedecisionitem-update.md) | None. | For any `accessReviewInstanceDecisionItems` that the calling user is assigned a reviewer on, ca
```suggestion
|[Update accessReviewInstanceDecisionItem](../api/accessreviewinstancedecisionitem-update.md) | None. | For any accessReviewInstanceDecisionItems that the calling user is assigned a reviewer on, calling user can record a decision by patching the decision object. |
```

2020-10-02 20:00 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| Property                  | Type                                |  Description |
```suggestion
| Property | Type |  Description |
```

2020-10-02 20:01 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| :-------------------------| :---------------------------------- | :---------- |
```suggestion
| :---------------| :---- | :---------- |
```

2020-10-02 20:01 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `id`                            |`String`                      | ID of the decision                                                                                     |
```suggestion
| id | String | The identifier of the decision. |
```

2020-10-02 20:02 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `accessReviewId`                |`String`                      | ID of the accessReviewInstance parent                                                                                       |
```suggestion
| accessReviewId | String | The identifier of the accessReviewInstance parent. |
```

2020-10-02 20:03 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `reviewedBy`                    |`microsoft.graph.userIdentity`| Reviewer user ID                                                                                       |
```suggestion
| reviewedBy | [userIdentity](useridentity.md) | The identifier of the reviewer. |
```

2020-10-02 20:04 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `reviewedDateTime`                  |`DateTimeOffset`              | DateTime when review occurred                                                                     |
```suggestion
| reviewedDateTime | DateTimeOffset | The DateTime when the review occurred. |
```

2020-10-02 20:05 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `decision`                      |`String`                      | Result of the review. Values can be: `Approve` `Deny` `NotReviewed` `DontKnow`.
```suggestion
| decision | String | Result of the review. Possible values: `Approve`, `Deny`, `NotReviewed`, or `DontKnow`. |
```

2020-10-02 20:05 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `justification`                 |`String`                      | Review decision justification                                                                          |
```suggestion
| justification | String | The review decision justification. |
```

2020-10-02 20:06 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `appliedBy`                     |`microsoft.graph.userIdentity`| User ID of the user who applied the decision                                                           |
```suggestion
| appliedBy | [userIdentity](useridentity.md) | The identifier of the user who applied the decision. |
```

2020-10-02 20:07 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `appliedDateTime`               |`DateTimeOffset`              | DateTime when approval decision was applied                                                           |
```suggestion
| appliedDateTime | DateTimeOffset | The DateTime when the approval decision was applied. |
```

2020-10-02 20:08 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `applyResult`                   |`String`                      | Result of applying the decision. Values are: `NotApplied` `Success` `Failed` `NotFound` `NotSupported`.                      |
```suggestion
| applyResult | String | The result of applying the decision. Possible values: `NotApplied`, `Success`, `Failed`, `NotFound`, or `NotSupported`. |
```

2020-10-02 20:09 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `recommendation`          |`String`                      | System-generated recommendation for the approval decision. Values are: `Approve` `Deny` `NotAvailable`. |
```suggestion
| recommendation | String | A system-generated recommendation for the approval decision. Possible values: `Approve`, `Deny`, or `NotAvailable`.  |
```

2020-10-02 20:10 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `target`                       |`microsoft.graph.accessReviewInstanceDecisionItemTarget`                      | Target of this specific decision. Decision Targets can be of different types – each o
```suggestion
| target | [accessReviewInstanceDecisionItemTarget](accessreviewinstancedecisionitemtarget.md)  | The target of this specific decision. Decision targets can be of different types – each one with its own specific properties. See [accessReviewInstanceDecisionItemTarget](accessreviewinstancedecisionitemtarget.md). |
```

2020-10-02 20:11 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| `instance`               |[accessReviewInstance](accessreviewinstance.md)          | There is exactly one `accessReviewInstance` associated with each decision. The instance is the parent of the dec
```suggestion
| instance |[accessReviewInstance](accessreviewinstance.md) | There is exactly one accessReviewInstance associated with each decision. The instance is the parent of the decision item, representing the recurrence of the access review the decision is made on. |
```

2020-10-02 20:11 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
> +description: "In the Azure AD access reviews feature, the `accessReviewInstanceDecisionItemServicePrincipalTarget` represents the target of a review as a service principal target."
```suggestion
description: "Represents the target of a review as a service principal target."
```

2020-10-02 20:12 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
> +The **accessReviewInstanceDecisionItemServicePrincipalTarget** represents a service principal under review in an [accessReviewInstance](accessreviewinstance.md).
```suggestion
Represents a service principal under review in an [accessReviewInstance](accessreviewinstance.md).
```

2020-10-02 20:12 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
> +| Property                     | Type                      | Description |
```suggestion
| Property | Type | Description |
```

2020-10-02 20:12 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
> +| `servicePrincipalID`          |`String`  | The ID of the service principal whose access is being reviewed. |
```suggestion
| servicePrincipalID | String | The identifier of the service principal whose access is being reviewed. |
```

2020-10-02 20:13 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
> +| `servicePrincipalDisplayName`          |`String`  | The display name of the service principal whose access is being reviewed. |
```suggestion
| servicePrincipalDisplayName | String | The display name of the service principal whose access is being reviewed. |
```

2020-10-02 20:13 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
> +| `appId`          |`String`  | The appId for the service principal entity being reviewed. |
```suggestion
| appId | String | The appId for the service principal entity being reviewed. |
```

2020-10-02 20:13 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md
> +description: "In the Azure AD access reviews feature, the `accessReviewInstanceDecisionItemTarget` represents the target of a review as either a user target or a service principal target. "
```suggestion
description: "Represents the target of a review as either a user target or a service principal target. "
```

2020-10-02 20:14 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md
> +The **accessReviewInstanceDecisionItemTarget** represents a base class for different types of review targets, each one with its own specific properties. The supported target types are: [accessReviewI
```suggestion
Represents a base class for different types of review targets, each one with its own specific properties. The supported target types are: [accessReviewInstanceDecisionItemUserTarget](accessreviewinstancedecisionitemusertarget.md) and [accessReviewInstanceDecisionItemServicePrincipalTarget](accessreviewinstancedecisionitemserviceprincipaltarget.md).
```

2020-10-02 20:14 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md
> +| Property                     | Type                      | Description |
Remove this table.

2020-10-02 20:14 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
> +description: "In the Azure AD access reviews feature, the `accessReviewInstanceDecisionItemUserTarget` represents the target of a review as  a user."
```suggestion
description: "Represents the target of a review as  a user."
```

2020-10-02 20:15 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
> +The **accessReviewInstanceDecisionItemUserTarget** represents a user identity under review in an [accessReviewInstance](accessreviewinstance.md).
```suggestion
Represents a user identity under review in an [accessReviewInstance](accessreviewinstance.md).
```

2020-10-02 20:15 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
> +|userDisplayName|String|Name of user.|
```suggestion
| userDisplayName | String | The name of user. |
```

2020-10-02 20:16 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
> +|userId|String|Identifier of user.|
```suggestion
| userId | String | The identifier of user. |
```

2020-10-02 20:16 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
> +|userPrincipalName|String|User principal name.|
```suggestion
| userPrincipalName | String | The user principal name. |
```

2020-10-02 20:16 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +description: "In the Azure AD access reviews feature, the `accessReviewReviewerScope` represents who will review an access review."
```suggestion
description: "Represents who will review an access review."
```

2020-10-02 20:17 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +The **accessReviewReviewerScope** defines who will review instances of an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md). This is expressed as an odata query, which allows review
```suggestion
The accessReviewReviewerScope defines who will review instances of an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md). This is expressed as an odata query, which allows reviewers to be specified both as a static list of users (i.e., specific users, group owners, group members) or dynamically (i.e., the case where every user is reviewed by their manager). To create a self-review (where users review their own access), do not provide reviewers on [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) creation.
```

2020-10-02 20:17 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +| Property                  | Type                                 | Description |
```suggestion
| Property | Type | Description |
```

2020-10-02 20:18 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +| `query`          |`String`  | The query specifying who will be the reviewer. See table for examples. |
```suggestion
| query | String | The query specifying who will be the reviewer. See table for examples. |
```

2020-10-02 20:18 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +| `queryType`          |`String`  | The type of query. Examples include MicrosoftGraph and ARM. |
```suggestion
| queryType | String | The type of query. Examples include `MicrosoftGraph` and `ARM`. |
```

2020-10-02 20:19 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +| `queryRoot`          |`String`  | In the scenario where reviewers need to be specified dynamically, this property is used to indicate the relative source of the query. This property is only require
```suggestion
| queryRoot | String | In the scenario where reviewers need to be specified dynamically, this property is used to indicate the relative source of the query. This property is only required if a relative query (i.e., ./manager) is specified. |
```

2020-10-02 20:20 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +description: "In the Azure AD access reviews feature, the `accessReviewScheduleDefinition` represents an access review or access review series."
```suggestion
description: "Represents an access review or access review series."
```

2020-10-02 20:21 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +An **accessReviewScheduleDefinition** contains a list of [accessReviewInstance](accessreviewinstance.md) objects. Each recurrence of the schedule definition will create an instance. Instances also re
```suggestion
An accessReviewScheduleDefinition contains a list of [accessReviewInstance](accessreviewinstance.md) objects. Each recurrence of the schedule definition will create an instance. Instances also represent each unique group being reviewed. If a schedule definition reviews multiple groups, each group will have a unique instance per each recurrence. In the case of a one-time review, only one instance will be created per group.
```

2020-10-02 20:22 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +|[List accessReviewScheduleDefinitions](../api/accessreviewscheduledefinition-list.md) | [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) collection | Lists every `accessReviewSche
```suggestion
|[List accessReviewScheduleDefinitions](../api/accessreviewscheduledefinition-list.md) | [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) collection | Lists every accessReviewScheduleDefinition. Does not include associated accessReviewInstance instances in listings. |
```

2020-10-02 20:23 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +|[Get accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-get.md) | [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) | Get an `accessReviewScheduleDefinition` wit
```suggestion
|[Get accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-get.md) | [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) | Get an accessReviewScheduleDefinition with a specified id. |
```

2020-10-02 20:23 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +|[Create accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-create.md) | [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) | Create a new `accessReviewScheduleDef
```suggestion
|[Create accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-create.md) | [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) | Create a new accessReviewScheduleDefinition. |
```

2020-10-02 20:23 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +|[Delete accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-delete.md) | None. | Delete an `accessReviewScheduleDefinition` with a specified ID. |
```suggestion
|[Delete accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-delete.md) | None. | Delete an accessReviewScheduleDefinition with a specified identifier. |
```

2020-10-02 20:24 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +|[Update accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-update.md) | None. | Update properties of an `accessReviewScheduleDefinition` with a specified ID. |
```suggestion
|[Update accessReviewScheduleDefinition](../api/accessreviewscheduledefinition-update.md) | None. | Update properties of an accessReviewScheduleDefinition with a specified identifier. |
```

2020-10-02 20:25 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +| Property                  | Type                                | Required on Create                     | Description |
Please follow the formatting suggestions on the previous tables.

2020-10-02 20:27 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| :-------------------------| :---------- | :---------- |
Please format this table as previously suggested.

2020-10-02 20:27 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscope.md
> +| `query`          |`String`  | The query specifying what will be reviewed. See table for examples. |
Please change as previously suggested.

2020-10-02 20:29 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewsv2-root.md
> +title: "Azure AD access reviews - Version 2"
Are there two versions that can be used? or is this a replacement? Not sure versioning should be used.

2020-10-06 20:03 UTC, opbld32 commented
Docs Build status updates of commit _[46e22a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46e22a1e029832ca67d6da6b27195bb117997faf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/reso [...]

2020-10-06 20:04 UTC, opbld32 commented
Docs Build status updates of commit _[46e22a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46e22a1e029832ca67d6da6b27195bb117997faf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/reso [...]

2020-10-06 20:06 UTC, opbld32 commented
Docs Build status updates of commit _[92414bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92414bd4fa4b0966b4a1d5cf3584ec52750a3f3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/reso [...]

2020-10-06 20:16 UTC, opbld33 commented
Docs Build status updates of commit _[5e59533](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e59533ffbb2a230f587dc5da1b23d8cbc3488c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-ce1e5a7a)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-06 20:18 UTC, opbld34 commented
Docs Build status updates of commit _[5e59533](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e59533ffbb2a230f587dc5da1b23d8cbc3488c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-b77b4108)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-14 16:11 UTC, opbld33 commented
Docs Build status updates of commit _[78517c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78517c613cc072d6c0dce2820ae5c4e11cd113a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-c35524b3)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-14 16:23 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstance-list.md
> +GET /identityGovernance/accessReviews/definitions/{definitionID}/instances?$top={pagesize}&$skip=0
The current api documentation has the parameter use here, and I want to be consistent with that. I also want it to be clear that these parameters are necessary.

2020-10-20 19:36 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewsv2-root.md
> +title: "Azure AD access reviews - Version 2"
This v2 will be a replacement of the existing in the long term

2020-10-20 19:37 UTC, opbld31 commented
Docs Build status updates of commit _[bdf4f58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bdf4f58f4b50a08f1902c5445179f0f05bd49a13)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-1fb6c211)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:38 UTC, opbld31 commented
Docs Build status updates of commit _[64cd8c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64cd8c7235ccaa0c11f713e531a7d057d142d3ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-c1fd3b10)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:40 UTC, opbld34 commented
Docs Build status updates of commit _[d877f77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d877f77c9e7f05b1e370848b09458c2fbe6f9415)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-c3be5899)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:41 UTC, opbld32 commented
Docs Build status updates of commit _[d877f77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d877f77c9e7f05b1e370848b09458c2fbe6f9415)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-b98ca268)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:43 UTC, opbld31 commented
Docs Build status updates of commit _[13fbdb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13fbdb3e4587e8cfb5c538fd48c6d9cdb49d1b8e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-4e917624)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:44 UTC, opbld32 commented
Docs Build status updates of commit _[33b7a38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33b7a38687e9a6e9ee076aef45cc899f9eccc42e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-2beadcfc)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:46 UTC, opbld32 commented
Docs Build status updates of commit _[da64af1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da64af1f8c744b8348126c42600ef925b922a848)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-2a93f73c)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:47 UTC, opbld30 commented
Docs Build status updates of commit _[ba34bd6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba34bd67c5fdf0f9549ded7eacc765550870b35f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-5ba4791e)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 19:49 UTC, opbld33 commented
Docs Build status updates of commit _[b2a8b6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2a8b6dcd27b97280988bab6b541671814ade5e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-4767d7d6)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:20 UTC, opbld31 commented
Docs Build status updates of commit _[347480a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/347480af477f15cdcce823c326e305a65db10baf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-e7b1f738)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:22 UTC, opbld32 commented
Docs Build status updates of commit _[243327f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/243327fc611d0d0a048f343384acbe1df922628a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-fefde0d9)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:23 UTC, opbld32 commented
Docs Build status updates of commit _[3838ac9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3838ac9ad83df59544ece792ee2b2d5a8baf6d9f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-cbf4aee8)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:25 UTC, opbld32 commented
Docs Build status updates of commit _[1b82be0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b82be033cf6e96760643cffee494c0e0d56271c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-d8d1e056)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:26 UTC, opbld30 commented
Docs Build status updates of commit _[41e4f2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41e4f2ae01da88732f5aa55b40a296f9ea90c08f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-f3eb08fa)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:28 UTC, opbld32 commented
Docs Build status updates of commit _[c31b9b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c31b9b26ce26ee5ab6e0dda70f7cfd5f17025987)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-aac52e48)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:29 UTC, opbld33 commented
Docs Build status updates of commit _[b170da9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b170da9b1a2f9c65bee1c62efb71c583674865c3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-bc67beda)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:32 UTC, opbld33 commented
Docs Build status updates of commit _[dd398bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd398bb2f92911d6ad23552d0eec04a58e7996a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-fd6c7316)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:33 UTC, opbld32 commented
Docs Build status updates of commit _[dd398bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd398bb2f92911d6ad23552d0eec04a58e7996a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-0c87f483)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:34 UTC, opbld33 commented
Docs Build status updates of commit _[f0ab4f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0ab4f5f3ddc6fdcd43691fee26440c83c3cdc11)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-70308be8)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:36 UTC, opbld34 commented
Docs Build status updates of commit _[db893eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db893eb58dce78ccaeaa8d53cb1bd2376f368d91)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-52dba4fb)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:37 UTC, opbld34 commented
Docs Build status updates of commit _[7874b62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7874b6269b1cab37b90447585f42b17e6abf0271)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-b15ccad1)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:39 UTC, opbld34 commented
Docs Build status updates of commit _[3489c76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3489c76219e0dd185b8905cf41aa183393e52b2e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-62896afc)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:40 UTC, opbld30 commented
Docs Build status updates of commit _[3a3b635](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a3b63573677f56f0b4295975c3be5fb441ac3f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-b51a0cbf)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:42 UTC, opbld34 commented
Docs Build status updates of commit _[f5cb0cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5cb0cb5c57569dc8fd0ec41b9d14f8ee59b89c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-2d6cbba3)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:43 UTC, opbld34 commented
Docs Build status updates of commit _[819fb44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/819fb4495fa73adbc4281c8e8430b739695b2468)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-4f143a68)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:45 UTC, opbld31 commented
Docs Build status updates of commit _[bca7933](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bca7933193ed9d46491faef930a9811b75e715f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-4922c39f)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:46 UTC, opbld32 commented
Docs Build status updates of commit _[55df505](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55df5050233c509812cb63cecf07c9ec083f6647)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-5875639b)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:48 UTC, opbld31 commented
Docs Build status updates of commit _[f5cb0cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5cb0cb5c57569dc8fd0ec41b9d14f8ee59b89c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-365dbffb)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:49 UTC, opbld33 commented
Docs Build status updates of commit _[bf54709](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf547090c2e871c11f6300b7507673487850a08d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-a6351c36)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:52 UTC, opbld31 commented
Docs Build status updates of commit _[fcb2f3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcb2f3a70efb98ceaa32832354092c89848db717)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-4408f870)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:53 UTC, opbld32 commented
Docs Build status updates of commit _[fcb2f3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcb2f3a70efb98ceaa32832354092c89848db717)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-57af6e4c)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:55 UTC, opbld33 commented
Docs Build status updates of commit _[fda357a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fda357a399394e4556249de60cc2c8c26c079a29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-8d086718)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:56 UTC, opbld34 commented
Docs Build status updates of commit _[fda357a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fda357a399394e4556249de60cc2c8c26c079a29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-4048af75)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:57 UTC, opbld31 commented
Docs Build status updates of commit _[a399e62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a399e6259689435e7358b0cf8f7d89ed97c244eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-15ec03a5)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-20 21:59 UTC, opbld30 commented
Docs Build status updates of commit _[a399e62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a399e6259689435e7358b0cf8f7d89ed97c244eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-e0adf8bd)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-26 23:01 UTC, opbld30 commented
Docs Build status updates of commit _[c5967ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5967edd7111baf40ee6aa9a453c3b94dee5bb99)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-82dd2f7f)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-26 23:02 UTC, opbld34 commented
Docs Build status updates of commit _[c5967ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5967edd7111baf40ee6aa9a453c3b94dee5bb99)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-bb94db9a)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-26 23:05 UTC, opbld32 commented
Docs Build status updates of commit _[a62048f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a62048fb193cc77c686750d670d2bf829ee2fc89)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-75cbb3e3)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-26 23:06 UTC, opbld32 commented
Docs Build status updates of commit _[a62048f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a62048fb193cc77c686750d670d2bf829ee2fc89)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-071365f7)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-27 17:48 UTC, opbld32 commented
Docs Build status updates of commit _[0983b2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0983b2bfac07691c7151f9885eef10e9900f7b41)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-a640c679)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2AP [...]

2020-10-27 19:19 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstance-listpendingapproval.md
> +GET /me/pendingAccessReviewInstances?$expand=definition&$top={pagesize}&$skip=0
The current api documentation has the parameter use here, and I want to be consistent with that. I also want it to be clear that these parameters are necessary.

2020-10-27 19:21 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +## HTTP request
Wondering why? all other files have this line

2020-10-27 19:22 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +GET /identityGovernance/accessReviews/definitions/{definitionID}/instances/{instanceID}/decisions?$top={pagesize}&$skip=0
The current api documentation has the parameter use here, and I want to be consistent with that. I also want it to be clear that these parameters are necessary.

2020-10-27 19:23 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +---
I think that title is misleading. This method only returns the decision items the calling user is the reviewer on, not all the decision items on the instance. accessreviewinstancedecisionitem-list does that.

2020-10-27 19:24 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +GET /me/pendingAccessReviewInstances/{instanceID}/decisions?$top={pagesize}&$skip=0
The current api documentation has the parameter use here, and I want to be consistent with that. I also want it to be clear that these parameters are necessary.

2020-10-27 19:24 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +GET /identityGovernance/accessReviews/definitions?$top={pagesize}&$skip=0
The current api documentation has the parameter use here, and I want to be consistent with that. I also want it to be clear that these parameters are necessary.

2020-10-27 19:47 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstance.md
> +## user
Can I name it anything I want? It is called "user" in our internal docs.

2020-10-27 20:07 UTC, opbld34 commented
Docs Build status updates of commit _[ca2ddfc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca2ddfcd3fa1e3a551b7306d6baf84bab38d9a11)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-908c94c1)
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e54d038b-908c94c1)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.co [...]

2020-10-27 20:14 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-list.md
> +GET /identityGovernance/accessReviews/definitions/{definitionID}/instances?$top={pagesize}&$skip=0
The parameters are not allowed in the HTTP request definition. Please move them to the examples section.

2020-10-27 20:15 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstance-sendreminder.md
> +## HTTP request
Ignore comment.

2020-10-27 20:17 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +GET /identityGovernance/accessReviews/definitions?$top={pagesize}&$skip=0
Please remove parameters and move to example section.

2020-10-27 22:01 UTC, opbld31 commented
Docs Build status updates of commit _[62b6506](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62b6506c4accdacc60d59a9b66dc4d1eda518442)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-d161b3a0)
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e54d038b-d161b3a0)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.co [...]

2020-10-27 22:21 UTC, opbld32 commented
Docs Build status updates of commit _[2b8c8ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b8c8add93dc0ed447db4b4b40bde6a9dd91e592)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-7bf9e516)
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e54d038b-7bf9e516)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.co [...]

2020-10-27 22:23 UTC, opbld32 commented
Docs Build status updates of commit _[2b8c8ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b8c8add93dc0ed447db4b4b40bde6a9dd91e592)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-e1903b7f)
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e54d038b-e1903b7f)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.co [...]

2020-10-28 18:16 UTC, opbld30 commented
Docs Build status updates of commit _[b9a1b0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9a1b0dadbe9a04351d2c35b31c41d3fd7589c27)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:18 UTC, opbld30 commented
Docs Build status updates of commit _[b9a1b0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9a1b0dadbe9a04351d2c35b31c41d3fd7589c27)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e8e8183c-bd567a42)
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) | [Details](#user-content-e54d038b-bd567a42)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.co [...]

2020-10-28 18:27 UTC, opbld33 commented
Docs Build status updates of commit _[f951965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f951965e6884e1be10cf63d89b5a55605766cc87)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:29 UTC, opbld30 commented
Docs Build status updates of commit _[f951965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f951965e6884e1be10cf63d89b5a55605766cc87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2 [...]

2020-10-28 18:31 UTC, opbld33 commented
Docs Build status updates of commit _[2a16b71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a16b7179c9c6f6b7cde0ec4266ed4e221ed5da3)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:32 UTC, opbld30 commented
Docs Build status updates of commit _[2a16b71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a16b7179c9c6f6b7cde0ec4266ed4e221ed5da3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2 [...]

2020-10-28 18:47 UTC, davidmu1 commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +---
Ignore comments

2020-11-04 21:36 UTC, davidmu1 approved these changes

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +The signed-in user must also be a reviewer on the accessReviewInstance.
I notice this says "the signed-in user" but also in the perms table, that it is available for apps without a signed in user.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
> +POST /me/pendingAccessReviewInstances/{instance-id}/acceptRecommendations
Does an application have a "/me"?

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +Apply review decisions on an [accessReviewInstance](../resources/accessreviewinstance.md).
Would it make sense to link to the IT docs that explains what "apply" does, and also mention that this isn't needed for auto-applying reviews.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-get.md
> +Retrieve an [accessReviewInstance](../resources/accessreviewinstance.md) object using the identifier of an accessReviewInstance and its parent accessReviewScheduleDefinition. This returns all propert
Would it help if you you made accessReviewScheduleDefinition and accessReviewInstanceDecisionItem be links to those resources?  E.g., if I land at this page, wanting to learn how to retrieve an access review, and I don't know what a schedule definition is.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-get.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/accessReviews/definitions('60860cdd-fb4d-4054-91ba-444404f3baa6')/instances/$entity",
I know they're there but personally I wouldn't include the "odata.context' lines here if there's nothing that the customer would do with them.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-list.md
> +Retrieve the [accessReviewInstance](../resources/accessreviewinstance.md) objects for a specific [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md). A list of zero or mo
I'd suggest adding to this article too the statement about how to get the decisions

To retrieve the decisions on the instance, use [List accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem-list.md).

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-list.md
> +The following example shows a request to retrieve all the access review series in a tenant.
I am not sure this statement is correct or matches the query.  This only returnes the ones for a particular definition, and the query limits to top 1000.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md
> +|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
isn't there usually 3 rows in the permission table template ?  MSA row missing?

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md
> +|Application                            | AccessReview.Read.All, AccessReview.ReadWrite.All |
Also there is a permission for application, but an app isn't a calling user so not sure how that would work.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +Retrieve the [accessReviewInstanceDecisionItem](../resources/accessreviewinstance.md) objects for a specific [accessReviewInstance](../resources/accessreviewscheduledefinition.md). A list of zero or
I think these links are to the wrong MD files- copy and paste :-) ????

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +    "@odata.count": 26,
it says 26 but there are only 4 in the example. maybe change this count to 4 so they don't think there's an odata.next lnk they're missing.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstancedecisionitem-update.md
> +Update access decisions, known as [accessReviewInstanceDecisionItems](../resources/accessreviewinstancedecisionitem.md), for which the user is the reviewer.
You might want to add a note about how the app can tell whether or not providing a justification is required

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| settings | [accessReviewScheduleSettings](../resources/accessreviewschedulesettings.md)| No | The settings for an access review series. Recurrence is determined here. See [accessReviewScheduleSetti
What does the "No" mean here?

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +This is an example of creating an access review series with a specific user as the reviewer. The review reviews all members of a specific group. It recurs weekly.
to make it clearer to the reader you might want to say something like,

with a specific user, whose user object ID is 7eae444    ...  all members of a specific group, whose object ID is b7a05 ...

so that they can tell which of those GUIDs are parameters they should change to the values from their own tenant, and not "magic" strings.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +  "descriptionForAdmins": "Test create",
Maybe use a different string for each

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-delete.md
> +Delete an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object.
Might want to say what will happen (either here or lnk to another article).  E.g., what about all the instances. What if it's running.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +Retrieve an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object by ID. This returns all properties of the scheduled access review series except for the associated
I had some difficulty parsing the second sentence "as well as individual groups being reviewed".   I misread this as a defintion has groups.  But a definition only "has" instances.  And some instances are created for recurrence and some are created for groups.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +Note that a PUT request expects the full object to be passed in, in addition to the properties being updated.
maybe say "full object to be passed in, in which all writable properties are included, not just the properties being updated"

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewinstance.md
> +Represents an Azure AD [access review](accessreviewsv2-root.md) recurrence. If the parent accessReviewScheduleDefinition is a recurring access review, instances represent each recurrence. A review th
please make schedule definition a []()

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewinstance.md
> +| `decisions`               |[accessReviewInstanceDecisionItem](accessreviewinstancedecisionitem.md) collection        | Each user reviewed in an `accessReviewInstance` has a decision item representi
might wish to say "representing if their access was approved, denied..."  Since it's the access being removed generally rather than the user.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +Represents an Azure AD [access review](accessreviewsv2-root.md) decision on an instance of a review. This decision represents the determination of a user or service principal's access for a given acc
Could you have a  "for a given [access review]()" that links to the container instance.  So that if someone comes across this article they can navigate to the article on the access review all up.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| recommendation | String | A system-generated recommendation for the approval decision. Possible values: `Approve`, `Deny`, or `NotAvailable`.  |
where's the other recommendatoin detail like user hasn't signed in

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +The accessReviewReviewerScope defines who will review instances of an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md). This is expressed as an odata query, which allows reviewers
capitalized OData

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviews-root.md
>  Namespace: microsoft.graph
shouldn't there be a link to the new docs from here?

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| recurrence|[patternedRecurrence](../resources/patternedrecurrence.md) | Detailed settings for recurrence. Using standard outlook recurrence object.  |
capitalize Outlook

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewsv2-root.md
> +title: "Azure AD access reviews - Version 2"
The term "v2" is confusing since this is in Graph beta and there is a Graph 1.0.  So as a reader I would expect that documentatoin for a v2 comes after Graph 1.0 not before Graph 1.0.  Maybe "beta update" rather than "v2"?

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewsv2-root.md
> +>Currently, the Microsoft Graph APIs only supports access reviews of group membership.
Since the existing APIs also support app reviews then those aren't legacy.

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewsv2-root.md
> +Prior to creating an access review, an administrator must have previously onboarded. The organization can onboard to Azure AD access reviews or, in the case of access reviews of Azure AD roles or Azu
Note onboarding might be going away soon?

2020-11-04 22:47 UTC, markwahl-msft commented on api-reference/beta/toc.yml
> +          - name: Business flow template (legacy)
If the names are being changed here then they should probably be changed in the articles themselves for consistency. Maybe do that all as a separate change after this one?

2020-11-05 02:51 UTC, Lauragra requested changes
This PR still has tech review feedback - please take a look and incorporate. Also, please include updates to the changelog.md and DirectoryServices.json changelog files with this PR.

2020-11-09 15:16 UTC, isabelleatmsft commented on api-reference/beta/toc.yml
> +          - name: Business flow template (legacy)
Fair - I'll remove that from this PR.

2020-11-09 15:29 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewsv2-root.md
> +Prior to creating an access review, an administrator must have previously onboarded. The organization can onboard to Azure AD access reviews or, in the case of access reviews of Azure AD roles or Azu
Good catch - checking with Shubham on this

2020-11-09 15:43 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-applydecisions.md
> +Apply review decisions on an [accessReviewInstance](../resources/accessreviewinstance.md).
https://docs.microsoft.com/azure/active-directory/governance/complete-access-review

2020-11-10 15:17 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstance-list.md
> +The following example shows a request to retrieve all the access review series in a tenant.
Yep you're right - i copied this from definition-list and overlooked it!

2020-11-10 15:28 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> +Retrieve the [accessReviewInstanceDecisionItem](../resources/accessreviewinstance.md) objects for a specific [accessReviewInstance](../resources/accessreviewscheduledefinition.md). A list of zero or
yep good catch once again

2020-11-10 15:35 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +| settings | [accessReviewScheduleSettings](../resources/accessreviewschedulesettings.md)| No | The settings for an access review series. Recurrence is determined here. See [accessReviewScheduleSetti
Remnants of a deleted column - thanks for catching

2020-11-10 17:50 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +Retrieve an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object by ID. This returns all properties of the scheduled access review series except for the associated
How is this: An instance represents an individual group under review during one recurrence of the review.

2020-11-10 17:52 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstance.md
> +Represents an Azure AD [access review](accessreviewsv2-root.md) recurrence. If the parent accessReviewScheduleDefinition is a recurring access review, instances represent each recurrence. A review th
You may have cut off here?

2020-11-10 18:01 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| recommendation | String | A system-generated recommendation for the approval decision. Possible values: `Approve`, `Deny`, or `NotAvailable`.  |
last sign in info is not available in the APIs

2020-11-10 18:05 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviews-root.md
>  Namespace: microsoft.graph
Added

2020-11-10 18:08 UTC, opbld30 commented
Docs Build status updates of commit _[d8ff670](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8ff670e34db1846c0bb15426b318f076a36f265)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2 [...]

2020-11-10 18:28 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +Retrieve an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object by ID. This returns all properties of the scheduled access review series except for the associated
An instance represents a review for a specific resource (such as a particular group's members), during one occurrence (e.g., March 2021) of a recurring review.

2020-11-10 18:30 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewinstance.md
> +Represents an Azure AD [access review](accessreviewsv2-root.md) recurrence. If the parent accessReviewScheduleDefinition is a recurring access review, instances represent each recurrence. A review th
Github ate my markdown.  please make schedule definition a link like \[accessReviewScheduleDefinition\]\(accessreviewscheduledefinition.md\)

2020-11-10 18:37 UTC, opbld33 commented
Docs Build status updates of commit _[f2e1e11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2e1e1107c58c1553d0cc22842ba78cfb71d1fbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2 [...]

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md
> + The signed-in user must also be in a directory role that permits them to read an access review. The signed-in user only sees instances of which they are assigned reviewer in the accessReviewSchedule
I am not sure the first sentence (directory role...) is needed, only the second sentence?

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstancedecisionitem-list.md
> + The signed-in user must also be in a directory role that permits them to read an access review.
You might want to mention that there is another API call for a reviewer to retrieve the decisions for a review they're assigned to do. (One of /me/ ones)

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> + The signed-in user must also be in a directory role that permits them to read an access review. The signed-in user will also only see decisions of which they are assigned reviewer in that decision's
See earlier comment about directory role - is the first sentence applicable to a /me path - a user even a guest should be able to read things pending their approval.

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
> +The following example shows a request to retrieve all the decisions on an instance of an access review.
you might want to add 'that the caller is authorized to see.'.  E.g., if this is a self-review of every member in a group of 50 people, and I'm one of those members, then I only see one item returned, not 50, correct?

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +        "@odata.type": "microsoft.graph.disableAndDeleteUserApplyAction"
You didn't mention this at the top of what the review example did.  This is a pretty significant effect of this review, so I suggest not including it in the example.  We don't want to have a customer copy-pasting hte example and inadvertnatly deleting guests.

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/api/accessreviewscheduledefinition-get.md
> +Retrieve an [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object by ID. This returns all properties of the scheduled access review series except for the associated
See earlier feedback  An instance represents an individual resource (such as a group's members) during one occurence..

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewinstancedecisionitem.md
> +| recommendation | String | A system-generated recommendation for the approval decision. Possible values: `Approve`, `Deny`, or `NotAvailable`.  |
do we have a bug open for that?

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +|--|--|--|
I'm wondering if it would help the reader to have each of the properties as columns in your table.   | Scenario | query | queryType | queryRoot |    even if it's Microsoftgraph as the value for each row's queryType, so that it is clear when to use these, and what to send "" as queryRoot

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewscope.md
> +| Review of guest users assigned to all groups | ./members/microsoft.graph.user/?$count=true&$filter=(userType eq 'Guest') | Note that the corresponding instanceEnumerationScope should also be passed
passed in where?

2020-11-10 18:51 UTC, markwahl-msft commented on api-reference/beta/resources/accessreviewscope.md
> +| Review of guest users assigned to all groups, excluding specified groups | /groups?$filter=(groupTypes/any(c:c+eq+'Unified') and id ne '{group id}' and id ne '{group id}' and id ne '{group id}')&$c
is the "passed in" referring to the next sentence about scope table?  Or are those two different instructucions?

2020-11-11 00:30 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +|--|--|--|
done

2020-11-11 00:37 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewscope.md
> +| Review of guest users assigned to all groups, excluding specified groups | /groups?$filter=(groupTypes/any(c:c+eq+'Unified') and id ne '{group id}' and id ne '{group id}' and id ne '{group id}')&$c
Yes, updated it to be more clear

2020-11-11 00:38 UTC, opbld34 commented
Docs Build status updates of commit _[e7fced6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7fced6555fd16eae4f409f93e9cedfd19a21f8f)_: 

:clock10: **Pending**: waiting for processors ([28](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 28 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-11 00:39 UTC, opbld30 commented
Docs Build status updates of commit _[e7fced6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7fced6555fd16eae4f409f93e9cedfd19a21f8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2 [...]

2020-11-11 20:44 UTC, opbld34 commented
Docs Build status updates of commit _[7566c22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7566c22881214c268fe2ee6ad64013dd04e0dabe)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e323896d)

<a id="e323896d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011112043451477-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7Mt4zaw3T7ut637uNoPTj76Zrc%2B7piYkal0M98gYQd8%3D&st=2020-11-11T20%3A39%3A08Z&se=2020-12-12T20%3A44%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 21:32 UTC, opbld34 commented
Docs Build status updates of commit _[3eecf4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3eecf4c0174328ba08de8bd2b326c03594177527)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-10c01220)

<a id="10c01220"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011112132293387-9935%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=azxqepxMp%2FtZlCN1bfejGP%2BKD7yAoKKVVotEEZCOiys%3D&st=2020-11-11T21%3A27%3A55Z&se=2020-12-12T21%3A32%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 21:43 UTC, opbld33 commented
Docs Build status updates of commit _[a74babf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a74babf1896ab22c0e37a5758a95722a90e38de9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9935) | [Details](#user-content-de0bbbbb-bcdcdb57)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2020-11-11 21:49 UTC, opbld30 commented
Docs Build status updates of commit _[08504fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08504fae76006fe43024640cf862d93d8d2624d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9935) | [Details](#user-content-de0bbbbb-5fbd6d98)
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2020-11-12 04:20 UTC, Lauragra approved these changes

2020-11-12 04:21 UTC, opbld30 commented
Docs Build status updates of commit _[c74a831](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c74a8316977553bd9f9f3e00bce9b709b0544490)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-acceptrecommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-acceptrecommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-acceptrecommendations?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-applydecisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-applydecisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-applydecisions?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-pendingaccessreviewinstances?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-sendreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-sendreminder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-sendreminder?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstance-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstance-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-stop?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-listpendingapproval?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2API/api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemserviceprincipaltarget?view=graph-rest-beta&branch=pr-en-us-9935) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AccessReviewV2 [...]

2020-11-12 04:24 UTC, merged