User flow doc file name and resource name fixes
microsoftgraph/microsoft-graph-docs pull request #9937
Opened 2020-09-16 00:20 UTC by jkdouglas

Fixed file names and resource names from original PR that was published

2020-09-16 00:21 UTC, opbld30 commented
Docs Build status updates of commit _[f609ff4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f609ff4c273cb1b87f2fcb0a12bcedd5a160fa85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) | [Details](#user-content-024638b9-cdf03b91)
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) | [Details](#user-content-b4591974-cdf03b91)
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) | [Details](#user-content-6076afe2-cdf03b91)
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) | [Details](#user-content-92bf4c85-cdf03b91)
[api-reference/beta/api/b2cidentityuserflow-delete-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-update-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-update-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-update-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-update-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-update-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-update-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

<a id="024638b9-cdf03b91"></a>
### [api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md)
 - **Line 16, Column 20**: **[Warning-file-not-found]** `````Invalid file link: '../resources/b2cuserflows.md'.`````
 - **Line 59, Column 81**: **[Warning-file-not-found]** `````Invalid file link: '../resources/b2cuserflows.md'.`````

<a id="b4591974-cdf03b91"></a>
### [api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md)
 - **Line 16, Column 20**: **[Warning-file-not-found]** `````Invalid file link: '../resources/b2xuserflows.md'.`````
 - **Line 5 [...]

2020-09-16 00:31 UTC, opbld32 commented
Docs Build status updates of commit _[9b2b6e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b2b6e33cf61dc8791a0c4d0f4b0a84ae57a264d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-update-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-update-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-update-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-update-identityprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-update-identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-update-identityprovider?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160030292183-9937%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=16H1mFYyYT91tE6bxTIIzEwD09%2BsZe2TQHQwLcQvPmA%3D&st=2020-09-16T00%3A26%3A54Z&se=2020-10-17T00%3A31%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questi [...]

2020-09-16 00:49 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            - name: identityUserflow
Line 10137, 10149, 10167: Sorry, misled you on the fly, I think the TOC title for the resources should retain some user friendliness to them, so can you please change the _TOC title_ of the 3 resources to the following, just dropping "identity" which seems to act as a prefix anyway:
User flow
B2C user flow
B2X user flow

The updated topic titles themselves for the last two topics look fine, as the actual {resource name} + "resource type". For the identityUserFlow resource, the topic title should be "identityUserFlow resource type", not "UserFlow resource type".

2020-09-16 01:23 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +               href: api/b2cidentityuserflow-update-identityprovider.md
Line 10161, 10162:
For our reference, this is the CSDL:
<EntityType Name="b2cIdentityUserFlow" BaseType="graph.identityUserFlow">
<NavigationProperty Name="identityProviders" Type="Collection(graph.identityProvider)"/>
</EntityType>

Line 10161 the TOC title should be "Create identity provider".

"Create" and not "add" because the nav property definition doesn't say ContainsTarget="true", which means ContainsTarget is false, in which case the verbs to use should be "create" and "delete", and not "add" nor "remove". 

This is explained here: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22

The filename should be b2cIdentityUserFlow-post-identityProviders.md. This follows the pattern {parent resource name}-post-{nav property name}.md.

2020-09-16 01:26 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +               href: api/b2cidentityuserflow-delete-identityprovider.md
Line 10164:
The filename for the delete operation follows the convention {resource name}-delete.md.
In this case, we're deleting an instance of an identityProvider, so the filename is identityprovider-delete.md.

2020-09-16 01:31 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>               - name: Create
Line 10153:
The CSDL in question is the following, for our convenience:
```
<EntityType Name="identityContainer" BaseType="graph.entity">
...
<NavigationProperty Name="b2cUserFlows" Type="Collection(graph.b2cIdentityUserFlow)" ContainsTarget="true"/>
...
```
Since ContainsTarget="true" for the nav property b2cUserFlows, the verbs to use are "Add" (and "Remove"), and not "Create" (nor "Delete").

So line 10153 should actually be "Add", and not "Create".
The filename identitycontainer-post-b2cuserflows.md is correct.

2020-09-16 02:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[List identity providers](../api/b2cidentityuserflow-list-identityproviders.md)|[identityProvider](../resources/identityProvider.md) collection|Retrieve all identity providers in a user flow.|
Line 34:
Perhaps in the description you can further clarify, "... in a B2C user flow".

2020-09-16 02:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[Add identity provider](../api/b2cidentityuserflow-update-identityprovider.md)|None|Add an identity provider to a user flow.|
Line 35:
Please change to "Create identity provider", and the description, add "... to a B2C user flow".

You use "create' rather than "add" because the nav property identityProvider is defined with the implicit default ContainsTarget=false.

So for line 36, the topic title "Delete identity provider" is appropriate.

2020-09-16 02:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/b2cidentityuserflow.md
Line 36:
Please change the filename to identityprovider-delete.md.
For get single instance, update, and delete operations, the filename pattern is {name of resource to delete}-{verb}.md.

2020-09-16 02:17 UTC, angelgolfer-ms commented on api-reference/beta/api/identitycontainer-list-b2cuserflows.md
> +# List b2cIdentityUserFlow objects
Line 10:
For the topic title of a list operation topic, the original is actually what the current stub topic generator would generate: "List {nav property name}".
So in this case, the topic title would be "List b2cUserFlows".

2020-09-16 02:24 UTC, angelgolfer-ms requested changes
Hi @jkdouglas , I reviewed and commented the topics pertaining to the B2C user flow resource and took a quick look at the B2X user flow counterparts.
Can you please take a look at my comments, let me know if you have questions, and if not, apply them to both B2C and B2X and make corresponding updates?
Thank you very much for your quick response!

2020-09-16 18:44 UTC, jkdouglas commented on api-reference/beta/toc.yml
> +            - name: identityUserflow
Fixed

2020-09-16 18:46 UTC, jkdouglas commented on api-reference/beta/toc.yml
>               - name: Create
The wiki mentions if ContainsTarget=true you use Create/Delete. 

If the resource A is represented by a navigation property in its containing parent resource and is defined with the following in the CSDL:

... ContainsTarget="true"
That means if one deletes the parent resource, the contained resources specified by the navigation property are also deleted. In this case, use "Delete" and "Create" for resource A.

Am I misunderstanding?

2020-09-16 18:47 UTC, jkdouglas commented on api-reference/beta/toc.yml
> +               href: api/b2cidentityuserflow-update-identityprovider.md
The wiki mentions if ContaingsTarget=false you should use Add/Remove. Am I reading it backwards? Also, should the file name be 'post' when it is a 'patch' operation? That is why I went with update and not post originally.

2020-09-16 18:47 UTC, jkdouglas commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[List identity providers](../api/b2cidentityuserflow-list-identityproviders.md)|[identityProvider](../resources/identityProvider.md) collection|Retrieve all identity providers in a user flow.|
Fixed throughout

2020-09-16 18:48 UTC, jkdouglas commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[Add identity provider](../api/b2cidentityuserflow-update-identityprovider.md)|None|Add an identity provider to a user flow.|
The wiki mentions ContainsTarget=false should follow Add/Remove naming conventions. Updated the files to follow that format. Please let me know if I read the wiki wrong.

2020-09-16 18:48 UTC, jkdouglas commented on api-reference/beta/api/identitycontainer-list-b2cuserflows.md
> +# List b2cIdentityUserFlow objects
Fixed for b2c and b2x

2020-09-16 20:19 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>               - name: Create
I apologize, @jkdouglas , I got it the other way round, the wiki is correct. Should have read the wiki clearly myself yesterday (even though I wrote it up based on consensus with Dan).
When ContainsTarget="true", we use "create/delete".

2020-09-16 20:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[Add identity provider](../api/b2cidentityuserflow-update-identityprovider.md)|None|Add an identity provider to a user flow.|
The wiki is correct. Thanks.

2020-09-16 20:34 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +               href: api/b2cidentityuserflow-update-identityprovider.md
The wiki is correct. If ContainsTarget is not specified, it is false by default, we use add/remove. So in this case, "add identity provider" is correct. Sorry for the confusion.

2020-09-16 20:40 UTC, angelgolfer-ms commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[Add identity provider](../api/b2cidentityuserflow-update-identityprovider.md)|None|Add an identity provider to a user flow.|
But in line 36, please change the first column to "Remove identity provider", if that operation is to remove an identity provider from a specified B2C user flow.

2020-09-16 21:46 UTC, opbld31 commented
Docs Build status updates of commit _[2f12d44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f12d44bb7dd1351cb595fa46de79884756890cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162145009238-9937%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y2TdhaCDsB2zLkBHIb3A88su9EyPm7F5nx4SRXtaIMs%3D&st=2020-09-16T21%3A41%3A47Z&se=2020-10-17T21%3A46%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked question [...]

2020-09-16 22:06 UTC, jkdouglas commented on api-reference/beta/api/identitycontainer-list-b2cuserflows.md
> +# List b2cIdentityUserFlow objects
Actually changed it back after checking generated doc stubs and it followed my original naming

2020-09-16 22:07 UTC, jkdouglas commented on api-reference/beta/resources/b2cidentityuserflow.md
Fixed these based on doc stub generator naming

2020-09-16 22:07 UTC, jkdouglas commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[Add identity provider](../api/b2cidentityuserflow-update-identityprovider.md)|None|Add an identity provider to a user flow.|
Fixed

2020-09-16 22:07 UTC, jkdouglas commented on api-reference/beta/toc.yml
>               - name: Create
Fixed

2020-09-16 22:08 UTC, jkdouglas commented on api-reference/beta/toc.yml
> +               href: api/b2cidentityuserflow-delete-identityprovider.md
Fixed based on doc stub generator tool naming

2020-09-16 22:08 UTC, jkdouglas commented on api-reference/beta/toc.yml
> +               href: api/b2cidentityuserflow-update-identityprovider.md
Fixed

2020-09-18 16:35 UTC, opbld31 commented
Docs Build status updates of commit _[a5731ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5731efaf62d0e19e8b0fcfa0e7b20ee33d8b345)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009181634049267-9937%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jPy9LTFW0p5LaFGL9Wl3XXaTzBejm9%2BidvPwf8DJjQo%3D&st=2020-09-18T16%3A30%3A22Z&se=2020-10-19T16%3A35%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questi [...]

2020-09-28 20:30 UTC, davidmu1 approved these changes

2020-09-29 18:51 UTC, opbld30 commented
Docs Build status updates of commit _[8811829](https://github.com/microsoftgraph/microsoft-graph-docs/commits/881182978b3b62f49ec0362366b444daad172e5c)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:53 UTC, opbld33 commented
Docs Build status updates of commit _[8811829](https://github.com/microsoftgraph/microsoft-graph-docs/commits/881182978b3b62f49ec0362366b444daad172e5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009291851329730-9937%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X7RjwCZ27Ur4du0JV1eo%2FAA%2FJW43vS3K0Hpcy1HbDLc%3D&st=2020-09-29T18%3A48%3A04Z&se=2020-10-30T18%3A53%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked ques [...]

2020-10-06 01:34 UTC, Lauragra approved these changes

2020-10-07 18:10 UTC, opbld30 commented
Docs Build status updates of commit _[77dda8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77dda8e61c2b8491cb74bc10c1f0b33000691db1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9937) | [Details](#user-content-de0bbbbb-7d7b428b)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

<a id="de0bbbbb-7d7b428b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning  [...]

2020-10-08 01:35 UTC, opbld33 commented
Docs Build status updates of commit _[acf2893](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acf2893474a579b7f81ff55891ac27350090ba87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9937) | [Details](#user-content-de0bbbbb-cc79cc89)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

<a id="de0bbbbb-cc79cc89"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning  [...]

2020-10-08 16:28 UTC, opbld30 commented
Docs Build status updates of commit _[1934613](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19346138a1b93b9b52fd36920a932609544b2005)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9937) | [Details](#user-content-de0bbbbb-98614263)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

<a id="de0bbbbb-98614263"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning  [...]

2020-10-08 22:52 UTC, opbld33 commented
Docs Build status updates of commit _[b336097](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b33609781cccd45828cad2d77b003d279a612de3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9937) | [Details](#user-content-de0bbbbb-433ea5ad)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-list-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-list-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2cuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2cuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2cuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/api/identitycontainer-post-b2xuserflows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/api/identitycontainer-post-b2xuserflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-b2xuserflows?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-9937) (graph-rest-beta) |

<a id="de0bbbbb-433ea5ad"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-userFlowDocUpdates/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggest [...]

2020-10-08 23:08 UTC, merged