update documentation for ToDo
microsoftgraph/microsoft-graph-docs pull request #9941
Opened 2020-09-16 06:40 UTC by avijityadav

2020-09-16 06:42 UTC, opbld30 commented
Docs Build status updates of commit _[0499e0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0499e0e10ddbada4587906193ed092e5f9561aae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) | [Details](#user-content-9df83b7a-1204389a)
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |

<a id="9df83b7a-1204389a"></a>
### [api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md)
 - **Line 17, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/todotasklist-post-tasks?view=graph-rest-beta&tabs=http#examples NOTE: This Suggestion will become a Warning in early December, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160640173877-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eqG7guctvXf8tnViuLF%2Fzfd%2Fe4gqByoC3EOpYftFsIY%3D&st=2020-09-16T06%3A37%3A01Z&se=2020-10-17T06%3A42%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 06:54 UTC, opbld31 commented
Docs Build status updates of commit _[2c8867b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c8867bb5202b427fae314bacecb3c64b78f65b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160652522266-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IdUsifzF1cryyEllYIZCVFItEiBK577fATbPLqb8Bho%3D&st=2020-09-16T06%3A49%3A15Z&se=2020-10-17T06%3A54%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 07:11 UTC, opbld32 commented
Docs Build status updates of commit _[2e70a49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e70a497704ae694052155c92d7aa7b79efbb4d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009160710393643-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gcUXzu0OvJggfAb47UySwy3LN796M1mLiQAfUg%2F%2Byv8%3D&st=2020-09-16T07%3A06%3A55Z&se=2020-10-17T07%3A11%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 16:10 UTC, jasonjoh commented
Please ignore EOL Blocker errors on PNG files. These should be excluded.

2020-09-16 17:33 UTC, opbld33 commented
Docs Build status updates of commit _[994f97f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/994f97f0c9b7f491634a9a81833aeb8c44d81fcf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009161732066581-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rDLsSFbsS7LneKubVtJgLPfVHbj6mPy38hk5mlA3aA4%3D&st=2020-09-16T17%3A28%3A26Z&se=2020-10-17T17%3A33%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 18:19 UTC, mashriv approved these changes

2020-09-22 16:52 UTC, opbld34 commented
Docs Build status updates of commit _[b26f871](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b26f871ab5965d515cb019d711bcc58e9f56bfb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221650294302-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AeG3Cv4nmFIk51EjO9eVAWFlX4vIYXaZc0OFJ4cnplQ%3D&st=2020-09-22T16%3A47%3A01Z&se=2020-10-23T16%3A52%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 07:51 UTC, opbld32 commented
Docs Build status updates of commit _[f70f188](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f70f188efd5bd8d510d1a97d4db8c27fc733cb0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource-taskdetail.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource-taskdetail.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource-taskdetail.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009230749551491-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hDQcFA70quKM1u7IQqDsukYpgIXzApKGH0tLe90g4cM%3D&st=2020-09-23T07%3A46%3A20Z&se=2020-10-24T07%3A51%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 07:59 UTC, opbld33 commented
Docs Build status updates of commit _[0f9eeea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f9eeeab9dd71f3526192466651cdf3d3cd6daf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource-taskdetail.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource-taskdetail.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource-taskdetail.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009230758130637-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zmz52uFLVNKUXVPQVHMjkpQ11OgwghGD8GTrrovEycg%3D&st=2020-09-23T07%3A54%3A41Z&se=2020-10-24T07%3A59%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 08:10 UTC, opbld31 commented
Docs Build status updates of commit _[6e09ec8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e09ec87ee20035598a53d2db709d653feb7096a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource-taskdetail.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource-taskdetail.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource-taskdetail.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009230809302529-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=duEFLwSNywYR1pcv6HsI9V%2B%2BMGjOUDdDmnLYO%2FFngeg%3D&st=2020-09-23T08%3A05%3A53Z&se=2020-10-24T08%3A10%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-25 07:11 UTC, angelgolfer-ms commented on api-reference/beta/api/todotask-post-linkedresources.md
> +> [!NOTE]
Line 10:
We probably overlooked this last time. Please change the topic title to "Create linkedResource". The object should be the name of the resource, which doesn't have the 's'.

2020-09-25 07:14 UTC, angelgolfer-ms commented on api-reference/beta/api/todotask-post-linkedresources.md
> +> You can also create a linkedResource object while [creating a todoTask](/graph/api/todotasklist-post-tasks?view=graph-rest-beta&preserve-view=true&tabs=http#examples).
Line 17:
Please just format this as a separate paragraph.
We usually keep the special formatting for any kind of note only for special content. I think you might be inclined to call it out because this is recently added, in a transition period.

2020-09-25 07:16 UTC, angelgolfer-ms commented on api-reference/beta/api/todotask-post-linkedresources.md
> +> You can also create a linkedResource object while [creating a todoTask](/graph/api/todotasklist-post-tasks?view=graph-rest-beta&preserve-view=true&tabs=http#examples).
Also please remember to bold any API element, like bolding linkedResource here. 
BTW, you wouldn't need to bold todoTask in this sentence, because that term is part of a hyperlink and would be formatted with emphasis already.

2020-09-25 07:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/linkedresource.md
> +We also support linkedResource without web URL. This can be used when the linked item doesn't have a web URL (e.g. in case of custom business apps or native platform apps like SMS app on phone). Here
Line 16:
Add "the" in "... in the task details view...".

GLOBAL:
In general, please make sure you don't use "we" in documentation. Use only "you", or infinitive without to as in a command, like "Open the email", where the "you" is implied.

In line 20:
You can rephrase the first two sentences as follows:
"Some linkedResource objects are not associated with any web URLs, in which case, the webUrl property is {Is it null?Fill this in please}. For example, the linked item can be a custom business app or native platform app such as an SMS app on a mobile phone..."

Please remember to bold API elements like linkedResource and webUrl.

2020-09-25 07:41 UTC, angelgolfer-ms commented on api-reference/beta/resources/todotasklist.md
Line 42:
Please don't document extra info for enum values like the way you modified the description. Please follow the convention: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55059/Enumerations?anchor=second-option%3A-in-parent-resource-topic

2020-09-25 07:43 UTC, angelgolfer-ms requested changes
Hi @avijityadav , thanks for the PR, please see my comments.

2020-09-25 12:30 UTC, opbld33 commented
Docs Build status updates of commit _[838e954](https://github.com/microsoftgraph/microsoft-graph-docs/commits/838e9542aaca0bddddc490713b6cad60fed35efd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource-taskdetail.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource-taskdetail.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource-taskdetail.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009251228281068-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=exHirLfzC3YkWMzZrSfS7KkOaVBnWWQDXRktp%2FpEfqA%3D&st=2020-09-25T12%3A25%3A14Z&se=2020-10-26T12%3A30%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-25 14:34 UTC, avijityadav commented
Hi @angelgolfer-ms, Thanks for reviewing. I have addressed the comments.

2020-09-25 14:34 UTC, avijityadav commented
Hi @angelgolfer-ms , Thanks for reviewing. I have addressed the comments.

2020-09-26 02:34 UTC, angelgolfer-ms commented on api-reference/beta/api/todotask-post-linkedresources.md
> +Create a new **linkedResource** object.
@avijityadav , please change line 10, the topic title, as well, to "Create linkedResource".

2020-09-26 02:38 UTC, angelgolfer-ms commented on api-reference/beta/api/todotask-post-linkedresources.md
Hm, I just thought of one thing - because specifying a linkedResource is optional when creating a task, in the example in todotasklist-post-tasks.md, under "Examples", after the "Request" section title, it would be a good idea to call that out, by adding a sentence like: 
"The following example creates a **todoTask** in the specified task list, and includes a linkedResource (and link to the linkedresource.md topic)."

2020-09-26 02:47 UTC, angelgolfer-ms commented on api-reference/beta/resources/linkedresource.md
> +Some **linkedResource** objects are not associated with any web URLs, in which case, the **webUrl** property is not required. For example, the linked item can be from a custom business app or native
Line 20:
3 edits for last two sentences:
For example, the linked item can be from a custom business app or native platform app, such as an SMS app on a mobile phone. Here is how a **linkedResource** appears with and without URL.

2020-09-26 02:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/todotasklist.md
> +
Line 42:
Slight reword of first sentence for readability:
"Property indicating the list name if the given list is a well-known list."

2020-09-26 02:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/todotasklist.md
> +|flaggedEmails| Built-in **Flagged email** list. Tasks from flagged emails will be present in this list.|
Line 49:
Please use present tense in almost all circumstances in docs; this is part of the Microsoft Writing Style Guide.
"Tasks from flagged emails are present in this list."

2020-09-26 02:52 UTC, angelgolfer-ms requested changes
@avijityadav , thanks for the quick turnaround. Just a few last changes. After you incorporate them, this PR is good to be published.

2020-09-27 12:49 UTC, avijityadav commented on api-reference/beta/api/todotask-post-linkedresources.md
> +Create a new **linkedResource** object.
Corrected this

2020-09-27 12:51 UTC, avijityadav commented on api-reference/beta/api/todotask-post-linkedresources.md
Thanks for the suggestion, added the line in todotasklist-post-tasks.md

2020-09-27 12:52 UTC, avijityadav commented on api-reference/beta/resources/linkedresource.md
> +Some **linkedResource** objects are not associated with any web URLs, in which case, the **webUrl** property is not required. For example, the linked item can be from a custom business app or native
Fixed it.

2020-09-27 12:52 UTC, avijityadav commented on api-reference/beta/resources/todotasklist.md
> +
Made the change.

2020-09-27 12:53 UTC, avijityadav commented on api-reference/beta/resources/todotasklist.md
> +|flaggedEmails| Built-in **Flagged email** list. Tasks from flagged emails will be present in this list.|
Fixed it.

2020-09-27 12:58 UTC, opbld31 commented
Docs Build status updates of commit _[cac4b70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cac4b706fedf4e95f37977573bbb3826a48162fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource-taskdetail.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource-taskdetail.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource-taskdetail.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009271257030791-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qEg7f81kL3rYYJFXmEaZ5LpXDvO%2BgWvB31pmrcNmeHc%3D&st=2020-09-27T12%3A53%3A24Z&se=2020-10-28T12%3A58%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-27 13:06 UTC, avijityadav commented
Thanks @angelgolfer-ms, I have incorporated your feedback and made changes.

2020-09-27 17:44 UTC, avijityadav commented on api-reference/beta/resources/todotasklist.md
Made the suggested changes, Thank for pointing to correct convention.

2020-09-29 01:28 UTC, opbld34 commented
Docs Build status updates of commit _[40cbf32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40cbf320d32ec7122c6eb30eb48ab15a9bf00c0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource-taskdetail.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource-taskdetail.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource-taskdetail.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009290127009417-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p1EdqBGliMmCrReVcjoIUxadzcRMz1zZBvRYMlDRB4s%3D&st=2020-09-29T01%3A23%3A21Z&se=2020-10-30T01%3A28%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 01:31 UTC, Lauragra commented on api-reference/beta/resources/linkedresource.md
> +![Linked resource in task details pane](/graph/images/todo-linkedresource-taskdetail.png)
This image is a bit small and leaves a lot of white space on the page. Is there a way to make it bigger/wider? Maybe a more zoomed in view. https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941

2020-09-29 01:32 UTC, Lauragra requested changes
One suggestion to improve the sizing of the first image in the resource topic.

2020-09-29 05:12 UTC, opbld32 commented
Docs Build status updates of commit _[4bb895b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4bb895b44a63809228518be26980d3093ea3f751)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-9941) (graph-rest-beta) |
[concepts/images/todo-api-entities.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-api-entities.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-api-entities.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource-taskdetail.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource-taskdetail.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource-taskdetail.png?branch=pr-en-us-9941) |
[concepts/images/todo-linkedresource.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-linkedresource.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/todo-linkedresource.png?branch=pr-en-us-9941) |
[concepts/images/todo-windows-app.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-updates/concepts/images/todo-windows-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-9941) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009290510528692-9941%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C3hBkptbp%2Fctxk7cf5OoiHc5%2FUb%2BHRIWxvLldUmxrKs%3D&st=2020-09-29T05%3A07%3A41Z&se=2020-10-30T05%3A12%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 05:18 UTC, avijityadav commented
@Lauragra , Thanks for your feedback. Fixed the image and removed the white spaces.

2020-09-29 06:12 UTC, angelgolfer-ms approved these changes
Thanks, @avijityadav .

2020-09-30 00:47 UTC, Lauragra approved these changes

2020-09-30 00:48 UTC, merged