add new and update property in chatMessage resource
microsoftgraph/microsoft-graph-docs pull request #9949
Opened 2020-09-16 23:23 UTC by laujan

2020-09-16 23:25 UTC, opbld34 commented
Docs Build status updates of commit _[65e7d56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65e7d56f444001f89cfbf97313d5d57ac2032b37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) | [Details](#user-content-1ce5904b-7e1de2af)
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) | [Details](#user-content-1a435eb8-7e1de2af)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) | [Details](#user-content-97ee62ac-7e1de2af)
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) | [Details](#user-content-c3041e45-7e1de2af)
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) | [Details](#user-content-e8a191d0-7e1de2af)
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) | [Details](#user-content-0db4f65f-7e1de2af)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |

<a id="1ce5904b-7e1de2af"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Create a new chatMessage in the specified channel.' is duplicated in 'beta/api/channel-post-message.md(3,14)', 'v1.0/api/channel-post-messages.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'Create chatMessage in a channel' is duplicated with other articles: 'beta/api/channel-post-message.md(10,1), v1.0/api/channel-post-messages.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

<a id="1a435eb8-7e1de2af"></a>
### [api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Reply to an existing message in a channel.' is duplicated in 'beta/api/channel-post-messagereply.md(3,14)', 'v1.0/api/channel-post-messagereply.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="97ee62ac-7e1de2af"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents an individual chat message within a channel or chat entity. The chat message can be a root chat message or part of a thread that is defined by the **replyToId** property in the chat message.' is duplicated in 'beta/resources/chatmessage.md(3,14)', 'v1.0/resources/chatmessage.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="c3041e45-7e1de2af"></a>
### [api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-mo [...]

2020-09-16 23:32 UTC, opbld30 commented
Docs Build status updates of commit _[6a35444](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a35444823598f86f1b4a124137a994395a63598)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) | [Details](#user-content-0db4f65f-fb0ad8b8)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

<a id="0db4f65f-fb0ad8b8"></a>
### [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md)
 - **Line 14, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162331130431-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9Rrf%2BL8urE23Khl7nQj0EBRVh9axUNyI84IEoOdIAPw%3D&st=2020-09-16T23%3A27%3A29Z&se=2020-10-17T23%3A32%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 23:36 UTC, opbld31 commented
Docs Build status updates of commit _[d6e505d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6e505d659fe109fac7e444c589a178d1ec7a5a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009162334523274-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vP6CunUfXCstm2rgPXpKUWOodjwma8EQWzZpo4NnKYI%3D&st=2020-09-16T23%3A31%3A43Z&se=2020-10-17T23%3A36%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 02:33 UTC, RamjotSingh requested changes
Their should a changelog entry informing people of the change (new property as well changes to existing property). Ideally running stub generator would have done it for you for the new property.

2020-09-17 02:33 UTC, RamjotSingh commented on api-reference/beta/api/channel-get-message.md
> +    "lastModifiedDateTime": "2019-02-04T19:58:15.511Z",
lastModifiedTime cant be before created. For examples if lastEdited time is not present u can copy over created date time to keep examples sane.

2020-09-17 02:33 UTC, RamjotSingh commented on api-reference/beta/api/channel-get-message.md
> +    "lastModifiedDateTime": "2019-02-04T19:58:15.511Z",
Goes for all examples.

2020-09-17 02:33 UTC, RamjotSingh commented on api-reference/beta/resources/chatmessage.md
> +|lastModifiedDateTime|dateTimeOffset|Read only. Timestamp when the chat message is created (initial setting) or edited, including when a reply is made (if it's a root chat message in a channel) or a
modified might be a better word here you can say modified (including edits)

2020-09-17 02:34 UTC, RamjotSingh commented
Their should a changelog entry informing people of the change (new property as well changes to existing property). Ideally running stub generator would have done it for you for the new property.

2020-09-17 19:47 UTC, laujan commented on api-reference/beta/api/channel-get-message.md
> +    "lastModifiedDateTime": "2019-02-04T19:58:15.511Z",
Okay, great catch!

2020-09-17 19:50 UTC, opbld33 commented
Docs Build status updates of commit _[9140df1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9140df1a0d874368b329a6a979313bcbd5e55552)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171949150515-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MNt51xV36KOkwA9QV8aWEFY6PfLJ7dH4S2bzm3syDKI%3D&st=2020-09-17T19%3A45%3A23Z&se=2020-10-18T19%3A50%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 19:52 UTC, opbld30 commented
Docs Build status updates of commit _[4ea47e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ea47e7c4c871aabe554d376d77a1d16569f9ad8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171951043861-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iLcs%2BNw1AQOF3g32DNGzIFQxp7iJe8Q3UXS7aVJ70yI%3D&st=2020-09-17T19%3A47%3A57Z&se=2020-10-18T19%3A52%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 19:54 UTC, opbld33 commented
Docs Build status updates of commit _[5fe9c3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5fe9c3e363bb66e06cc77b4ce6437e1060ad613a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171952030781-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2hX4wul3l8vUrYyhmIwCMICL1EQU0BU7q89hwBD5cvA%3D&st=2020-09-17T19%3A49%3A20Z&se=2020-10-18T19%3A54%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 19:55 UTC, opbld33 commented
Docs Build status updates of commit _[03bb22c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03bb22c8845af215fcfe547c599bc96bd08448fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171953240362-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aJzwfaCVr2qTjZlPW8KEpHXuTzfLo5KkOftWpvmkxJ8%3D&st=2020-09-17T19%3A50%3A46Z&se=2020-10-18T19%3A55%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 19:57 UTC, opbld33 commented
Docs Build status updates of commit _[bc178b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc178b140cc1cca5d5d948208e72d4c6f68b1314)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171954557462-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ACF%2BDe%2B3gWfDE%2BPyLgIn2%2F4Bhw%2FF0JtL1Qi2CQ8AbLU%3D&st=2020-09-17T19%3A52%3A05Z&se=2020-10-18T19%3A57%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 20:01 UTC, opbld33 commented
Docs Build status updates of commit _[afbefd9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afbefd95a47fb57677eb37d20c6ab238a1635680)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009171959480249-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IUaFkojVl7csljDWaYvnxNIWENJJ5qEDMpRjqIQZ3GY%3D&st=2020-09-17T19%3A56%3A02Z&se=2020-10-18T20%3A01%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 20:02 UTC, opbld30 commented
Docs Build status updates of commit _[6b259f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b259f419ef01c0acdf1a328f6133f57a15ebd4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172001386813-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3FGoF%2FrC8bL1zV2Aw54DR%2Fky7PlkNWTJsYgCW7Px%2FeQ%3D&st=2020-09-17T19%3A57%3A56Z&se=2020-10-18T20%3A02%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 20:06 UTC, opbld33 commented
Docs Build status updates of commit _[a0c14eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0c14ebb78ebfbb133c99be8de27e19e97cbd636)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172004517076-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OAFL96g9dCrOdPzk6tv9kRyJl3%2BIayhCZcfx8LfdtXI%3D&st=2020-09-17T20%3A01%3A10Z&se=2020-10-18T20%3A06%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 20:13 UTC, opbld32 commented
Docs Build status updates of commit _[a209934](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a209934caadc52520920fd830dd593687b47ca2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172012192481-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5itNKvY4w8nX3ZB1%2FcsQKBXUud0nvOTP46E1qv92fJ8%3D&st=2020-09-17T20%3A08%3A35Z&se=2020-10-18T20%3A13%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 20:15 UTC, opbld34 commented
Docs Build status updates of commit _[ad438dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad438dcaa746518498286bc9e3ab3cdb7cc2dccf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172014108023-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BQYPS%2BmEnj9g7ZAMae9TqIyL2LcMxR7O4noz0zKBmXs%3D&st=2020-09-17T20%3A10%3A24Z&se=2020-10-18T20%3A15%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 20:19 UTC, opbld30 commented
Docs Build status updates of commit _[6a6195e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a6195ec2e30b6f0f1bb972011fc85e272aec902)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172018127480-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oywsREbpnn5AVc7PyYJ3lAvoRyr06QLSWeVUEKEK2DY%3D&st=2020-09-17T20%3A14%3A21Z&se=2020-10-18T20%3A19%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-17 21:12 UTC, opbld30 commented
Docs Build status updates of commit _[707c494](https://github.com/microsoftgraph/microsoft-graph-docs/commits/707c4947d6217c00d505e0fbb5a890d22bef0084)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009172111086270-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AzIqwq9UNreQ1tE8r7RqjStH1ECkwM68qh8Pr01B9aU%3D&st=2020-09-17T21%3A07%3A26Z&se=2020-10-18T21%3A12%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 17:56 UTC, RamjotSingh requested changes

2020-09-18 17:56 UTC, RamjotSingh commented on api-reference/beta/resources/chatmessage.md
> +|lastModifiedDateTime|dateTimeOffset|Read only. Timestamp when the chat message is created (initial setting) or modified, including when a reply is made (if it's a root chat message in a channel) or
```suggestion
|lastModifiedDateTime|dateTimeOffset|Read only. Timestamp when the chat message is created (initial setting) or modified, including when a reaction is added or removed. |
```

2020-09-18 17:56 UTC, RamjotSingh commented on api-reference/v1.0/resources/chatmessage.md
> +|lastModifiedDateTime|dateTimeOffset|Read only. Timestamp when the chat message is created (initial setting) or edited, including when a reply is made (if it's a root chat message in a channel) or a
```suggestion
|lastModifiedDateTime|dateTimeOffset|Read only. Timestamp when the chat message is created (initial setting) or edited, including when a reaction is added or removed. |
```

2020-09-18 18:47 UTC, opbld33 commented
Docs Build status updates of commit _[7db1961](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7db1961e64c327269269708762f30facac530b81)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2b551b73)

<a id="2b551b73"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009181847060566-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tcn%2BFFFZzL8qTiSd0QL6h2CtT8xJh3rP4kjWWo9%2Fdew%3D&st=2020-09-18T18%3A42%3A35Z&se=2020-10-19T18%3A47%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 18:48 UTC, opbld33 commented
Docs Build status updates of commit _[962ded1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/962ded13f9f5952057b8fff56dc440ebcb3d63db)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-10cd6e23)

<a id="10cd6e23"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009181847190459-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BgXfoG64KhBbRCpyjAh%2BYPz2AucWGTPKw%2BwqKGwpup0%3D&st=2020-09-18T18%3A43%3A05Z&se=2020-10-19T18%3A48%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 18:51 UTC, opbld31 commented
Docs Build status updates of commit _[3fc4267](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fc426797222a138a3662426bd971308a1f72549)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009181849355249-9949%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jgnAw%2BS5urwP4zMFQ7pW3v19IknRAbv2TgTt6TAl%2Fpo%3D&st=2020-09-18T18%3A46%3A38Z&se=2020-10-19T18%3A51%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 21:02 UTC, opbld30 commented
Docs Build status updates of commit _[884d9ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/884d9cae2f88f3432ec0a371cfe29747b99b4d70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9949) | [Details](#user-content-de0bbbbb-9b95e4fe)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

<a id="de0bbbbb-9b95e4fe"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set [...]

2020-09-19 18:26 UTC, RamjotSingh approved these changes

2020-09-19 18:28 UTC, RamjotSingh requested changes

2020-09-19 18:28 UTC, RamjotSingh commented on api-reference/beta/api/channel-get-filesfolder.md
> +    "lastModifiedDateTime": "2020-02-23T18:47:13Z",
Remove changes.

2020-09-19 18:28 UTC, RamjotSingh commented on api-reference/beta/api/channel-get-filesfolder.md
> +        "lastModifiedDateTime": "2020-02-23T18:47:13Z",
Remove changes.

2020-09-19 18:28 UTC, RamjotSingh commented on api-reference/beta/resources/chatmessage.md
> +|lastEditedDateTime|dateTimeOffset|Read only. Timestamp when edits to the chat message were made. Triggers an "Edited" flag in the Teams UI. If no edits are made the value is `null`.|
Microsoft Teams? For clarifying between Teams as entity collection and Microsoft Teams as a product.

2020-09-19 19:53 UTC, opbld31 commented
Docs Build status updates of commit _[a9aa39a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9aa39ac23bf211955422b9769f86f3754e5dbc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9949) | [Details](#user-content-de0bbbbb-51e42400)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

<a id="de0bbbbb-51e42400"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If [...]

2020-09-19 19:55 UTC, opbld33 commented
Docs Build status updates of commit _[a5d4745](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5d4745ddc3e8d16de180f612b5924956378e4f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9949) | [Details](#user-content-de0bbbbb-2dbf38f2)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

<a id="de0bbbbb-2dbf38f2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If [...]

2020-09-19 20:08 UTC, RamjotSingh approved these changes
Undo the filesFolder files. Rest looks fine.

2020-09-19 20:08 UTC, RamjotSingh commented on api-reference/beta/api/channel-get-filesfolder.md
> +        "lastModifiedDateTime": "2020-01-23T18:47:13Z",
Undo this entire file.

2020-09-19 20:08 UTC, RamjotSingh commented on api-reference/beta/api/channel-get-filesfolder.md
> +    "lastEditedDateTime": null,
Undo.

2020-09-22 02:23 UTC, opbld32 commented
Docs Build status updates of commit _[38f8d28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38f8d28f6c50e2d88c09c78051464ceb356c16d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-9949) | [Details](#user-content-de0bbbbb-f031e956)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-get-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-get-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-9949) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-9949) (>= graph-rest-1.0) |

<a id="de0bbbbb-f031e956"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/update-modified-edited-dateTime/concepts/changelog.md)
 - **Line 25, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning in early December, 2020.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If [...]

2020-09-22 02:28 UTC, merged