Conversationmember list
microsoftgraph/microsoft-graph-docs pull request #9973
Opened 2020-09-18 04:49 UTC by Mahesh2516

Removed sample code snippet links.

2020-09-18 04:51 UTC, opbld30 commented
Docs Build status updates of commit _[6e4b774](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e4b7745908ff67941cda2b0efd9ba449e139785)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-list/api-reference/v1.0/api/conversationmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9973) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-53dcfc40)

<a id="3e26536d-53dcfc40"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-list/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 14, Column 74**: **[Warning-file-not-found]** `````Invalid file link: '../resources/chat.md'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve a member of a chat or channel.' is duplicated in 'beta/api/conversationmember-get.md(3,14)', 'beta/api/conversationmember-list.md(3,14)', 'v1.0/api/conversationmember-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009180449561792-9973%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y1dLyrs1Da0SeB2iCVAWsq9K0PMgj%2BFKtBeRN5bPOPY%3D&st=2020-09-18T04%3A46%3A14Z&se=2020-10-19T04%3A51%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 02:39 UTC, Lauragra requested changes
This PR will require an update to the parent resources to list this operation in the Methods table, an entry in the v1.0 TOC, and and entry in the changelog.

2020-09-22 02:39 UTC, opbld31 commented
Docs Build status updates of commit _[bb0a4a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb0a4a92a4e5d7be48ff6663762c72de96f3654e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-list/api-reference/v1.0/api/conversationmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-9973) (>= graph-rest-1.0) | [Details](#user-content-3e26536d-fb4a8166)

<a id="3e26536d-fb4a8166"></a>
### [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-list/api-reference/v1.0/api/conversationmember-list.md)
 - **Line 14, Column 88**: **[Warning-file-not-found]** `````Invalid file link: '../resources/chat.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009220238103461-9973%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4SqoT0oTqRV%2B8%2Fo4JLU83L5LpOXEoG8cXtOH2uzAOBg%3D&st=2020-09-22T02%3A34%3A37Z&se=2020-10-23T02%3A39%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 19:23 UTC, laujan commented
Already in #9810 PR.

2020-10-02 19:26 UTC, laujan commented
Already in #9810 PR.

2020-10-02 19:26 UTC, closed without merging