LCM v1.0 updates
microsoftgraph/microsoft-graph-docs pull request #9981
Opened 2020-09-18 17:12 UTC by cmmdesai

Added new attributes to user object - employeeType, employeeOrgData and employeeHireDate

2020-09-18 17:13 UTC, opbld32 commented
Docs Build status updates of commit _[94dbab0](https://github.com/cmmdesai/microsoft-graph-docs/commits/94dbab000e3972917d11a123b038933ca5d262a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/employeeOrgData.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-v1.0-update/api-reference/v1.0/resources/employeeOrgData.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-1.0&branch=pr-en-us-9981) (>= graph-rest-1.0) | [Details](#user-content-b07e022d-957f9597)
[api-reference/v1.0/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-v1.0-update/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-9981) (>= graph-rest-1.0) | [Details](#user-content-6f302778-957f9597)

<a id="b07e022d-957f9597"></a>
### [api-reference/v1.0/resources/employeeOrgData.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-v1.0-update/api-reference/v1.0/resources/employeeOrgData.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=master)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6f302778-957f9597"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/cmmdesai/microsoft-graph-docs/blob/lcm-v1.0-update/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents an Azure AD user account. Inherits from directoryObject.' is duplicated in 'beta/resources/user.md(3,14)', 'v1.0/resources/user.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning in late September, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009181712098258-9981%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A%2B%2Bdq3OS4MaNPYdEhyNoVL9f5Q0okwgIwQ4x4vc6SgQ%3D&st=2020-09-18T17%3A08%3A27Z&se=2020-10-19T17%3A13%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-19 00:39 UTC, Lauragra commented on api-reference/v1.0/resources/employeeOrgData.md
> +title: "employeeOrgData resource type"
File names need to be all lowercase - please update.

2020-09-19 00:42 UTC, Lauragra commented on api-reference/v1.0/resources/employeeOrgData.md
> +title: "employeeOrgData resource type"
This complex type does not exist in beta. We don't update v1.0 without updating beta first. Does this need to be documented for beta?

2020-09-19 00:43 UTC, Lauragra requested changes
Please see comments. This PR will also require an update to the changelog.

2020-09-19 00:44 UTC, Lauragra commented on api-reference/v1.0/resources/user.md
> +|employeeOrgData|[employeeOrgData](employeeOrgData.md) collection|Represents organization data (e.g. division and costCenter) associated with a user.|
Do you need to update response examples in operation topics to include the new property?

2020-10-20 17:12 UTC, opbld30 commented
Docs Build status updates of commit _[f480eed](https://github.com/cmmdesai/microsoft-graph-docs/commits/f480eeda6478931582a6ac419b7d99b1acb2ede4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-15057011)

<a id="15057011"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201712215656-9981%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1AqRiGipwQ4yB4rzAWNGbg8%2BYOKb8uwx11kP3d09%2BMM%3D&st=2020-10-20T17%3A07%3A47Z&se=2020-11-20T17%3A12%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 17:23 UTC, opbld31 commented
Docs Build status updates of commit _[22ef089](https://github.com/cmmdesai/microsoft-graph-docs/commits/22ef089279fd9480c7284f5f2173a08894660d25)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0ed58af9)

<a id="0ed58af9"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201723046166-9981%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fdi4K45BBTqiqb7wPZZbH7I%2FFtsY5KzSZVumf3YT2Lk%3D&st=2020-10-20T17%3A18%3A24Z&se=2020-11-20T17%3A23%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 17:28 UTC, cmmdesai commented on api-reference/v1.0/resources/employeeOrgData.md
> +title: "employeeOrgData resource type"
Done.

2020-10-20 17:28 UTC, cmmdesai commented on api-reference/v1.0/resources/employeeOrgData.md
> +title: "employeeOrgData resource type"
Done. Here is the beta update PR - https://github.com/microsoftgraph/microsoft-graph-docs/pull/9790

2020-10-20 17:30 UTC, cmmdesai commented on api-reference/v1.0/resources/user.md
> +|employeeOrgData|[employeeOrgData](employeeOrgData.md) collection|Represents organization data (e.g. division and costCenter) associated with a user.|
Since these are optional properties, we don't need to update the response examples for different operations.

2020-10-20 18:04 UTC, alok-bansal approved these changes

2020-10-20 18:11 UTC, alok-bansal commented
> Please see comments. This PR will also require an update to the changelog.

Updated.

2020-10-20 21:10 UTC, davidmu1 approved these changes

2020-10-21 00:33 UTC, Lauragra approved these changes

2020-10-21 00:41 UTC, merged