add known limitations for drive
microsoftgraph/microsoft-graph-docs pull request #9994
Opened 2020-09-22 01:32 UTC by lanhongvp

2020-09-22 01:33 UTC, opbld32 commented
Docs Build status updates of commit _[60eaa7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60eaa7bae0c8761de05246908e4143610a4dc30f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009220132058601-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PZOLKYCI3dbeXNEoSljF9sR32u700Eu%2BjZ%2Ftp9eF9t8%3D&st=2020-09-22T01%3A28%3A22Z&se=2020-10-23T01%3A33%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-22 16:22 UTC, opbld34 commented
Docs Build status updates of commit _[9e9aac2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e9aac230a8657841417764bc6621728d9e8ab82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009221620545498-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZbjKC8Qfm7xpkEAXLkpmBYYOqPf4WsTRhlDXbmAy58o%3D&st=2020-09-22T16%3A17%3A11Z&se=2020-10-23T16%3A22%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 20:14 UTC, opbld31 commented
Docs Build status updates of commit _[62561a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62561a4a8d496d9de9996572722fa1a55e383c4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-9994) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009292013246641-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EhHfvAL7nqsLrgsRK0ezOz3DBhEptvSbCQ3%2FMFpEr4U%3D&st=2020-09-29T20%3A09%3A39Z&se=2020-10-30T20%3A14%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 20:25 UTC, opbld34 commented
Docs Build status updates of commit _[b80114b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b80114bc9cc3f6d04c226287e68ee6e5481f251f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-9994) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009292024173907-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XWxTIjjryU9cgpZlc80YfwIPOVTRRa9f%2FgUzJEcGdd4%3D&st=2020-09-29T20%3A20%3A35Z&se=2020-10-30T20%3A25%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 20:29 UTC, nmoreau commented
Hi @Lauragra  and @angelgolfer-ms  - This PR is ready to be merged. Minor updates / clarifications / Polish.
Thanks.

2020-09-29 20:57 UTC, opbld34 commented
Docs Build status updates of commit _[cb5bd96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb5bd96de3bee094d214eae7a5cde98e1871f7f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-9994) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009292056067206-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tsvPTOmfKn2XaNgNSjmXp9RQppozW4%2BUvv%2F5L1GE%2FP4%3D&st=2020-09-29T20%3A52%3A30Z&se=2020-10-30T20%3A57%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 20:59 UTC, opbld32 commented
Docs Build status updates of commit _[27116f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27116f9dbaeba32738dfd7c551bda5df69833a65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-9994) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009292058095931-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5nQwis0aBdl%2B8krAYW8REtIo2EYNwJFPgp%2Fo%2BkJ6gA8%3D&st=2020-09-29T20%3A54%3A27Z&se=2020-10-30T20%3A59%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 21:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-api-overview.md
> +- **listItem** will not return any field.
Line 98: 
For listItem resources from SharePoint, do you mean, if the query request doesn't specify any value for fields in the request body, then only default fields and no custom fields would be returned?

If so, please change line 98 to:
"**listItem** will not return any custom fields."

I would expect that to be the behavior based on the fact that the **fields** property is optional in the query request body, and its description currently says: 
"Contains the fields to be returned for each resource object specified in entityTypes, allowing customization of the fields returned by default otherwise..."

2020-09-29 21:58 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-api-overview.md
> +- **listItem** will not return any field.
BTW, since you have the PR open, can you please fix the spelling error "earch" in the description for the **fields** property, in searchrequest.md? Thanks.

2020-09-29 22:09 UTC, angelgolfer-ms commented on concepts/search-concept-custom-types.md
> +- The **fields** property to include the fields in the external item to retrieve. Note that if you do not include any **fields** in the request, the response will contain all the fields marked as *re
Line 29:
There's a branding problem - we should not publicly refer to Microsoft Graph as just "Graph".
However, looking at the context of the entire topic, I don't think we necessarily have to loop in the full term "Microsoft Graph connectors" here, as the earlier parts of the topic has already been talking about connectors.
Please change the part of the sentence to:
"... marked as *retrievable* in the data schema specified for that [external connection](/graph/api/resources/externalconnection?view=graph-rest-beta&preserve-view=true)."

2020-09-29 22:14 UTC, angelgolfer-ms commented on concepts/search-concept-files.md
> +When searching for **drive**, you need to include in the **queryString** a term contained in the name of the document library. Query `*` is not supported and will not return all available drives.
Line 418:
Please change the last sentence:
"Querying `*` is not supported and does not return all..."
We're supposed to use present tense in most cases, to reflect that this is the current behavior.

2020-09-29 22:14 UTC, angelgolfer-ms requested changes
Please see and address a few comments, thanks!

2020-10-06 21:55 UTC, nmoreau commented on api-reference/beta/resources/search-api-overview.md
> +- **listItem** will not return any field.
Fixed and clarified.
Updated searchrequest.md?

2020-10-06 22:08 UTC, nmoreau commented on concepts/search-concept-custom-types.md
> +- The **fields** property to include the fields in the external item to retrieve. Note that if you do not include any **fields** in the request, the response will contain all the fields marked as *re
Updated but did not refer to the external Connection since this would only be valid for custom connectors.
Here the connection can be an OOB connector

2020-10-06 22:11 UTC, nmoreau commented on concepts/search-concept-custom-types.md
> +- The **fields** property to include the fields in the external item to retrieve. Note that if you do not include any **fields** in the request, the response will contain all the fields marked as *re
Fixed

2020-10-06 22:12 UTC, opbld32 commented
Docs Build status updates of commit _[069e298](https://github.com/microsoftgraph/microsoft-graph-docs/commits/069e298e0130aa57f3cb3442365fe2f15f3daf88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-9994) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010062211291580-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ceqep5CC4BgYJa68egGwMJOM1kjBjBGFti7jN8bFVEM%3D&st=2020-10-06T22%3A07%3A48Z&se=2020-11-06T22%3A12%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-06 22:24 UTC, opbld34 commented
Docs Build status updates of commit _[e811544](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e81154411c64f4a61aed8d6d95dacd0a15c41274)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[api-reference/beta/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-9994) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-9994) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010062223298003-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2oxhr%2BtuyBToERa41VuZqphm2jP4cs2bn%2BliQbUfWK8%3D&st=2020-10-06T22%3A19%3A49Z&se=2020-11-06T22%3A24%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-07 02:24 UTC, Lauragra approved these changes

2020-10-07 02:24 UTC, opbld34 commented
Docs Build status updates of commit _[c2f4749](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2f4749133869492608d9247d8c23c688259cc11)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[api-reference/beta/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-9994) (graph-rest-beta) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-9994) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-9994) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-9994) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-Update/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-9994) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010070223163641-9994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ay3AXFGKiFXmpDGuXoxfsjiDOW1cUP%2BZ7PtjTv8rTvM%3D&st=2020-10-07T02%3A19%3A36Z&se=2020-11-07T02%3A24%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-07 02:32 UTC, merged